Repository angular/components, pull requests merged in 2018-06, with the labels that each got.

#11622 Revert "fix(overlay): flexible overlay with push not handling scroll offset and position locking"
  src/cdk/overlay/position/flexible-connected-position-strategy.spec.ts
  src/cdk/overlay/position/flexible-connected-position-strategy.ts
  src/cdk/scrolling/viewport-ruler.ts
  src/lib/menu/menu-trigger.ts
Labels: cla: yes, pr: lgtm, pr: merge ready, target: patch

#11657 Revert "fix(tabs): Add role to mat-tab-nav-bar and mat-tab-link"
  src/lib/tabs/tab-nav-bar/tab-nav-bar.html
  src/lib/tabs/tab-nav-bar/tab-nav-bar.spec.ts
  src/lib/tabs/tab-nav-bar/tab-nav-bar.ts
Labels: cla: yes, pr: lgtm, pr: merge ready, target: patch

#11661 Revert "perf(tabs): use a transform to resize and move the ink bar"
  src/lib/tabs/_tabs-common.scss
  src/lib/tabs/ink-bar.ts
Labels: cla: yes, pr: lgtm, pr: merge ready, target: patch

#11656 chore: update changelog and bump version (6.2.1)
  CHANGELOG.md
  package.json
Labels: cla: yes, docs, pr: lgtm, pr: merge ready, pr: merge safe

#11483 feat(table): support sticky headers, footers, and columns
  .firebaserc
  src/cdk/table/BUILD.bazel
  src/cdk/table/can-stick.ts
  src/cdk/table/cell.ts
  src/cdk/table/public-api.ts
  src/cdk/table/row.ts
  src/cdk/table/sticky-styler.ts
  src/cdk/table/table.spec.ts
  src/cdk/table/table.ts
  src/demo-app/example/example.ts
  src/demo-app/table/table-demo.ts
  src/lib/table/BUILD.bazel
  src/lib/table/_table-theme.scss
  src/lib/table/cell.ts
  src/lib/table/row.ts
  src/lib/table/table.md
  src/lib/table/table.spec.ts
  src/lib/table/table.ts
  src/material-examples/table-basic-flex/table-basic-flex-example.html
  src/material-examples/table-sticky-columns/table-sticky-column-example.css
  src/material-examples/table-sticky-columns/table-sticky-column-example.html
  src/material-examples/table-sticky-columns/table-sticky-column-example.ts
  src/material-examples/table-sticky-complex-flex/table-sticky-complex-flex-example.css
  src/material-examples/table-sticky-complex-flex/table-sticky-complex-flex-example.html
  src/material-examples/table-sticky-complex-flex/table-sticky-complex-flex-example.ts
  src/material-examples/table-sticky-complex/table-sticky-complex-example.css
  src/material-examples/table-sticky-complex/table-sticky-complex-example.html
  src/material-examples/table-sticky-complex/table-sticky-complex-example.ts
  src/material-examples/table-sticky-footer/table-sticky-footer-example.css
  src/material-examples/table-sticky-footer/table-sticky-footer-example.html
  src/material-examples/table-sticky-footer/table-sticky-footer-example.ts
  src/material-examples/table-sticky-header/table-sticky-header-example.css
  src/material-examples/table-sticky-header/table-sticky-header-example.html
  src/material-examples/table-sticky-header/table-sticky-header-example.ts
Labels: cla: yes, pr: lgtm, pr: merge ready, target: minor

#11409 fix(tabs): update mat-tab-link to set aria-current when active
  src/lib/tabs/tab-nav-bar/tab-nav-bar.spec.ts
  src/lib/tabs/tab-nav-bar/tab-nav-bar.ts
Labels: cla: yes, pr: lgtm, pr: merge ready, target: patch

#11447 fix(form-field): fix wrong underline color in error state
  src/lib/form-field/_form-field-theme.scss
Labels: cla: yes, pr: lgtm, pr: merge ready, target: patch

#11517 fix(sidenav): scrollable instance not exposed when explicitly specifying content element
  src/lib/sidenav/drawer-container.html
  src/lib/sidenav/drawer.spec.ts
  src/lib/sidenav/drawer.ts
  src/lib/sidenav/sidenav.md
  src/lib/sidenav/sidenav.ts
Labels: cla: yes, pr: lgtm, pr: merge ready, target: major

#11697 Revert "fix(sidenav): scrollable instance not exposed when explicitly specifying content element"
  src/lib/sidenav/drawer-container.html
  src/lib/sidenav/drawer.spec.ts
  src/lib/sidenav/drawer.ts
  src/lib/sidenav/sidenav.md
  src/lib/sidenav/sidenav.ts
Labels: cla: yes

#11518 fix(scrolling): scrollable elementScrolled stream not being completed on destroy
  src/cdk/scrolling/scroll-dispatcher.spec.ts
  src/cdk/scrolling/scrollable.ts
Labels: cla: yes, pr: lgtm, pr: merge ready, target: patch

#11531 fix(icon): IE/Edge ignoring style tags inside inline SVG
  src/lib/icon/icon.spec.ts
  src/lib/icon/icon.ts
Labels: cla: yes, pr: lgtm, pr: merge ready, target: patch

#11574 fix(slider): value not being rounded when using keyboard and decimal step
  src/lib/slider/slider.spec.ts
  src/lib/slider/slider.ts
Labels: cla: yes, pr: lgtm, pr: merge ready, target: patch

#11579 chore: remove internal usages of deprecated APIs
  src/cdk/a11y/key-manager/list-key-manager.spec.ts
  src/cdk/table/table.spec.ts
  src/lib/menu/menu-directive.ts
  src/lib/menu/menu-trigger.ts
  src/lib/menu/menu.spec.ts
  src/lib/snack-bar/snack-bar.spec.ts
Labels: cla: yes, pr: lgtm, pr: merge ready, target: patch

#11586 fix(badge, tooltip): Add A11yModule
  src/lib/badge/badge-module.ts
  src/lib/tooltip/tooltip-module.ts
Labels: cla: yes, pr: lgtm, pr: merge ready, target: patch

#11592 fix(overlay): unable to reset overlay size properties to initial value
  src/cdk/overlay/overlay-ref.ts
  src/cdk/overlay/overlay.spec.ts
Labels: cla: yes, pr: lgtm, pr: merge ready, target: patch

#11612 fix(menu): reintroduce panel position classes
  src/lib/menu/menu-directive.ts
  src/lib/menu/menu.spec.ts
Labels: cla: yes, pr: lgtm, pr: merge ready, target: patch

#11633 fix(checkbox): high contrast accessibility improvements
  src/cdk/a11y/_a11y.scss
  src/lib/checkbox/_checkbox-theme.scss
  src/lib/checkbox/checkbox.scss
Labels: cla: yes, pr: lgtm, pr: merge ready, target: patch

#11651 fix(progress-bar): not usable in high contrast mode
  src/lib/progress-bar/progress-bar.scss
Labels: a11y, cla: yes, pr: lgtm, pr: merge ready, target: patch

#11667 fix(select): multi-select checkbox not having an outline in high contrast mode
  src/lib/core/selection/pseudo-checkbox/pseudo-checkbox.scss
Labels: a11y, cla: yes, pr: lgtm, pr: merge ready, target: patch

#11684 Add aria-modal where appropriate
  src/lib/bottom-sheet/bottom-sheet-container.ts
  src/lib/dialog/dialog-container.ts
Labels: a11y, cla: yes, pr: lgtm, pr: merge ready, target: patch

#11688 fix(progress-spinner): animation not working when default size is set via token
  src/lib/progress-spinner/progress-spinner.ts
Labels: cla: yes, pr: lgtm, pr: merge ready, target: patch

#11694 fix(tabs): tab position and amount of tabs not being read out by screen reader
  src/lib/tabs/tab-group.html
  src/lib/tabs/tab-group.spec.ts
Labels: a11y, cla: yes, pr: lgtm, pr: merge ready, target: patch

#9819 refactor(tabs): use common logic for handling keyboard focus
  src/lib/tabs/BUILD.bazel
  src/lib/tabs/tab-header.spec.ts
  src/lib/tabs/tab-header.ts
Labels: cla: yes, pr: lgtm, pr: merge ready, target: patch

#11683 build(bazel): switch to rules_sass 0.1.0
  WORKSPACE
  src/cdk-experimental/dialog/BUILD.bazel
  src/cdk-experimental/scrolling/BUILD.bazel
  src/cdk/text-field/BUILD.bazel
  src/lib/autocomplete/BUILD.bazel
  src/lib/bottom-sheet/BUILD.bazel
  src/lib/button-toggle/BUILD.bazel
  src/lib/button/BUILD.bazel
  src/lib/card/BUILD.bazel
  src/lib/checkbox/BUILD.bazel
  src/lib/chips/BUILD.bazel
  src/lib/core/BUILD.bazel
  src/lib/datepicker/BUILD.bazel
  src/lib/dialog/BUILD.bazel
  src/lib/divider/BUILD.bazel
  src/lib/expansion/BUILD.bazel
  src/lib/form-field/BUILD.bazel
  src/lib/grid-list/BUILD.bazel
  src/lib/icon/BUILD.bazel
  src/lib/input/BUILD.bazel
  src/lib/list/BUILD.bazel
  src/lib/menu/BUILD.bazel
  src/lib/paginator/BUILD.bazel
  src/lib/prebuilt-themes/BUILD.bazel
  src/lib/progress-bar/BUILD.bazel
  src/lib/progress-spinner/BUILD.bazel
  src/lib/radio/BUILD.bazel
  src/lib/select/BUILD.bazel
  src/lib/sidenav/BUILD.bazel
  src/lib/slide-toggle/BUILD.bazel
  src/lib/slider/BUILD.bazel
  src/lib/snack-bar/BUILD.bazel
  src/lib/sort/BUILD.bazel
  src/lib/stepper/BUILD.bazel
  src/lib/table/BUILD.bazel
  src/lib/tabs/BUILD.bazel
  src/lib/toolbar/BUILD.bazel
  src/lib/tooltip/BUILD.bazel
  src/lib/tree/BUILD.bazel
Labels: cla: yes, pr: lgtm, pr: merge ready, pr: merge safe, target: master only

#11629 build: add tslint rule to enforce consistent rxjs imports
  src/demo-app/virtual-scroll/virtual-scroll-demo.ts
  tools/tslint-rules/rxjsImportsRule.ts
  tslint.json
Labels: cla: yes, pr: lgtm, pr: merge ready, pr: merge safe, target: master only

#11424 fix(schematics): remove temp path #11198
  src/lib/schematics/update/update.ts
  src/lib/schematics/update/update_spec.ts
Labels: cla: yes, pr: lgtm, pr: merge ready, pr: merge safe, target: patch

#11659 fix(expansion): expansion panel blending in with background in high contrast mode
  src/lib/expansion/expansion-panel.scss
Labels: a11y, cla: yes, pr: lgtm, pr: merge ready, target: patch

#11599 fix(badge): remove badge margins
  src/demo-app/badge/badge-demo.scss
  src/lib/badge/_badge-theme.scss
Labels: caretaker note, cla: yes, pr: lgtm, pr: merge ready, target: minor

#11594 fix(select): disable all animations when using NoopAnimationsModule
  src/lib/core/selection/pseudo-checkbox/pseudo-checkbox.scss
  src/lib/core/selection/pseudo-checkbox/pseudo-checkbox.ts
  src/lib/core/style/_noop-animation.scss
  src/lib/select/select.scss
Labels: cla: yes, pr: lgtm, pr: merge ready, target: patch

#11560 feat(collections): add isMultipleSelection function to SelectionModel
  src/cdk/collections/selection.spec.ts
  src/cdk/collections/selection.ts
Labels: cla: yes, pr: lgtm, pr: merge ready, target: minor

#11502 fix(selection-list): support selecting all via ctrl + a
  src/lib/list/selection-list.spec.ts
  src/lib/list/selection-list.ts
Labels: cla: yes, pr: lgtm, pr: merge ready, target: patch

#11412 fix(overlay): global overlay incorrectly handling left/right position when RTL is set on body
  src/cdk/overlay/position/global-position-strategy.spec.ts
  src/cdk/overlay/position/global-position-strategy.ts
Labels: cla: yes, pr: lgtm, pr: merge ready, target: patch

#11144 fix(datepicker): make date range aria-live and fix active date logic
  src/lib/datepicker/calendar-header.html
  src/lib/datepicker/calendar.html
  src/lib/datepicker/month-view.ts
  src/lib/datepicker/multi-year-view.spec.ts
  src/lib/datepicker/multi-year-view.ts
  src/lib/datepicker/year-view.spec.ts
  src/lib/datepicker/year-view.ts
Labels: a11y, cla: yes, pr: lgtm, pr: merge ready, target: minor

#9907 refactor(overlay): avoid circular type references
  src/cdk/overlay/overlay-reference.ts
  src/cdk/overlay/position/connected-position-strategy.ts
  src/cdk/overlay/position/flexible-connected-position-strategy.ts
  src/cdk/overlay/position/global-position-strategy.ts
  src/cdk/overlay/position/position-strategy.ts
  src/cdk/overlay/scroll/close-scroll-strategy.ts
  src/cdk/overlay/scroll/reposition-scroll-strategy.ts
  src/cdk/overlay/scroll/scroll-strategy.ts
Labels: cla: yes, pr: lgtm, pr: merge ready, target: master only

#11705 chore(table): remove native docs
  src/demo-app/table/table-demo.ts
  src/lib/table/table.md
  src/material-examples/table-native-only/table-native-only-example.css
  src/material-examples/table-native-only/table-native-only-example.html
  src/material-examples/table-native-only/table-native-only-example.ts
Labels: cla: yes, pr: lgtm, pr: merge ready, pr: merge safe, target: patch

#11660 chore: focus monitor directives example not working
  src/material-examples/material-module.ts
Labels: cla: yes, pr: lgtm, pr: merge ready, pr: merge safe, target: master only

#11712 chore(tabs): revise examples and demo
  src/demo-app/demo-app/demo-module.ts
  src/demo-app/demo-app/routes.ts
  src/demo-app/tabs/routes.ts
  src/demo-app/tabs/tabs-demo.html
  src/demo-app/tabs/tabs-demo.scss
  src/demo-app/tabs/tabs-demo.ts
  src/material-examples/tab-group-async/tab-group-async-example.css
  src/material-examples/tab-group-async/tab-group-async-example.html
  src/material-examples/tab-group-async/tab-group-async-example.ts
  src/material-examples/tab-group-basic/tab-group-basic-example.css
  src/material-examples/tab-group-basic/tab-group-basic-example.html
  src/material-examples/tab-group-basic/tab-group-basic-example.ts
  src/material-examples/tab-group-custom-label/tab-group-custom-label-example.css
  src/material-examples/tab-group-custom-label/tab-group-custom-label-example.html
  src/material-examples/tab-group-custom-label/tab-group-custom-label-example.ts
  src/material-examples/tab-group-dynamic-height/tab-group-dynamic-height-example.css
  src/material-examples/tab-group-dynamic-height/tab-group-dynamic-height-example.html
  src/material-examples/tab-group-dynamic-height/tab-group-dynamic-height-example.ts
  src/material-examples/tab-group-dynamic/tab-group-dynamic-example.css
  src/material-examples/tab-group-dynamic/tab-group-dynamic-example.html
  src/material-examples/tab-group-dynamic/tab-group-dynamic-example.ts
  src/material-examples/tab-group-header-below/tab-group-header-below-example.css
  src/material-examples/tab-group-header-below/tab-group-header-below-example.html
  src/material-examples/tab-group-header-below/tab-group-header-below-example.ts
  src/material-examples/tab-group-lazy-loaded/tab-group-lazy-loaded-example.css
  src/material-examples/tab-group-lazy-loaded/tab-group-lazy-loaded-example.html
  src/material-examples/tab-group-lazy-loaded/tab-group-lazy-loaded-example.ts
  src/material-examples/tab-group-stretched/tab-group-stretched-example.css
  src/material-examples/tab-group-stretched/tab-group-stretched-example.html
  src/material-examples/tab-group-stretched/tab-group-stretched-example.ts
  src/material-examples/tab-group-theme/tab-group-theme-example.css
  src/material-examples/tab-group-theme/tab-group-theme-example.html
  src/material-examples/tab-group-theme/tab-group-theme-example.ts
  src/material-examples/tab-nav-bar-basic/tab-nav-bar-basic-example.css
  src/material-examples/tab-nav-bar-basic/tab-nav-bar-basic-example.html
  src/material-examples/tab-nav-bar-basic/tab-nav-bar-basic-example.ts
  src/material-examples/tabs-overview/tabs-overview-example.html
  src/material-examples/tabs-overview/tabs-overview-example.ts
Labels: cla: yes, pr: lgtm, pr: merge ready, pr: merge safe, target: minor

#11718 chore(tabs): remove minor spacing in examples
  src/material-examples/tab-group-lazy-loaded/tab-group-lazy-loaded-example.html
Labels: cla: yes, pr: lgtm, pr: merge ready, pr: merge safe, target: patch

#11721 chore(tabs): adjust tabs docs for examples
  src/lib/tabs/tabs.md
  src/material-examples/tabs-template-label/tabs-template-label-example.css
  src/material-examples/tabs-template-label/tabs-template-label-example.html
  src/material-examples/tabs-template-label/tabs-template-label-example.ts
Labels: cla: yes, pr: lgtm, pr: merge ready, pr: merge safe, target: patch

#11717 chore: fix table sticky column file name
  src/demo-app/table/table-demo.ts
  src/material-examples/table-sticky-columns/table-sticky-columns-example.css
  src/material-examples/table-sticky-columns/table-sticky-columns-example.html
  src/material-examples/table-sticky-columns/table-sticky-columns-example.ts
Labels: cla: yes, pr: lgtm, pr: merge ready, pr: merge safe, target: minor

#11727 Revert "This commit fixes #11148"
  src/demo-app/tree/dynamic-tree-demo/dynamic-database.ts
Labels: cla: yes

#11191 Schematic improvements
  src/lib/schematics/README.md
  src/lib/schematics/collection.json
  src/lib/schematics/dashboard/files/__path__/__name@dasherize@if-flat__/__name@dasherize__.component.ts
  src/lib/schematics/dashboard/index.ts
  src/lib/schematics/dashboard/index_spec.ts
  src/lib/schematics/dashboard/schema.json
  src/lib/schematics/install/custom-theme.ts
  src/lib/schematics/install/index.ts
  src/lib/schematics/install/index_spec.ts
  src/lib/schematics/install/schema.json
  src/lib/schematics/install/schema.ts
  src/lib/schematics/install/theming.ts
  src/lib/schematics/nav/files/__path__/__name@dasherize@if-flat__/__name@dasherize__.component.__styleext__
  src/lib/schematics/nav/files/__path__/__name@dasherize@if-flat__/__name@dasherize__.component.html
  src/lib/schematics/nav/files/__path__/__name@dasherize@if-flat__/__name@dasherize__.component.ts
  src/lib/schematics/nav/index_spec.ts
  src/lib/schematics/nav/schema.json
  src/lib/schematics/shell/README.md
  src/lib/schematics/table/README.md
  src/lib/schematics/table/files/__path__/__name@dasherize@if-flat__/__name@dasherize__.component.html
  src/lib/schematics/table/index_spec.ts
  src/lib/schematics/table/schema.json
  src/lib/schematics/utils/lib-versions.ts
Labels: cla: yes, pr: lgtm, pr: merge ready, pr: merge safe, target: patch

#11752 chore(overlay): remove unused properties from checks
  src/cdk/overlay/overlay-directives.ts
Labels: cla: yes, pr: lgtm, pr: merge ready, target: patch

#11751 fix(menu): toggle aria-expanded attribute on menu trigger
  src/lib/menu/menu-trigger.ts
  src/lib/menu/menu.spec.ts
Labels: cla: yes, pr: lgtm, pr: merge ready, target: patch

#11736 fix(form-field): inaccessible in high contrast mode
  src/lib/form-field/form-field-fill.scss
  src/lib/form-field/form-field-legacy.scss
  src/lib/form-field/form-field-standard.scss
  src/lib/form-field/form-field.scss
Labels: a11y, cla: yes, pr: lgtm, pr: merge ready, target: patch

#11723 fix(dialog): inconsistently resetting dimensions
  src/lib/dialog/dialog-ref.ts
  src/lib/dialog/dialog.spec.ts
Labels: cla: yes, pr: lgtm, pr: merge ready, target: patch

#11711 fix(stepper): reading out wrong amount of steps with NVDA on Firefox
  src/lib/stepper/stepper-horizontal.html
  src/lib/stepper/stepper-vertical.html
  src/lib/stepper/stepper.spec.ts
Labels: a11y, cla: yes, pr: lgtm, pr: merge ready, target: patch

#11695 fix(autocomplete): model not being updated when typing in input with disabled autocomplete
  src/lib/autocomplete/autocomplete-trigger.ts
  src/lib/autocomplete/autocomplete.spec.ts
Labels: cla: yes, pr: lgtm, pr: merge ready, target: patch

#11669 CdkTable change scope of data prop
  package-lock.json
  src/cdk/table/table.ts
Labels: cla: yes, pr: lgtm, pr: merge ready, target: patch

#11528 fix(select): unable to use the MatOption select/deselect API to toggle options
  src/cdk/collections/selection.spec.ts
  src/cdk/collections/selection.ts
  src/lib/core/option/option.spec.ts
  src/lib/core/option/option.ts
  src/lib/select/select.spec.ts
  src/lib/select/select.ts
Labels: cla: yes, pr: lgtm, pr: merge ready, target: patch

#11425 feat(schematics): address form schematic
  src/lib/schematics/address-form/files/__path__/__name@dasherize@if-flat__/__name@dasherize__.component.__styleext__
  src/lib/schematics/address-form/files/__path__/__name@dasherize@if-flat__/__name@dasherize__.component.html
  src/lib/schematics/address-form/files/__path__/__name@dasherize@if-flat__/__name@dasherize__.component.spec.ts
  src/lib/schematics/address-form/files/__path__/__name@dasherize@if-flat__/__name@dasherize__.component.ts
  src/lib/schematics/address-form/index.ts
  src/lib/schematics/address-form/schema.json
  src/lib/schematics/address-form/schema.ts
  src/lib/schematics/collection.json
Labels: cla: yes, pr: lgtm, pr: merge ready, pr: merge safe, target: minor

#11767 docs(dialog): emphasize clicking on backdrop in disableClose docs
  src/lib/dialog/dialog-config.ts
Labels: cla: yes, pr: lgtm, pr: merge ready, pr: merge safe, target: patch

#11738 fix(schematics): add app prefix to components
  src/lib/schematics/utils/devkit-utils/component.ts
  src/lib/schematics/utils/devkit-utils/config.ts
Labels: cla: yes, pr: lgtm, pr: merge ready, pr: merge safe, target: patch

#11769 chore: make merge-ready not required for PR status to be green
  .github/angular-robot.yml
Labels: cla: yes, pr: lgtm, pr: merge ready, pr: merge safe, target: master only

#11779 docs: fix typo
  src/lib/core/style/_form-common.scss
Labels: cla: yes, pr: lgtm, pr: merge ready, pr: merge safe, target: master only

#11710 fix(select): label not being read out when using mat-label in mat-form-field
  src/lib/form-field/form-field.html
  src/lib/form-field/form-field.ts
  src/lib/select/select.spec.ts
  src/lib/select/select.ts
Labels: a11y, cla: yes, pr: lgtm, pr: merge ready, target: patch

#11722 fix(paginator): page size selections being truncated with outline and fill appearances
  src/lib/paginator/paginator.scss
Labels: cla: yes, pr: lgtm, pr: merge ready, target: patch

#11828 chore: update return types in portal docs
  src/cdk/portal/portal.md
Labels: cla: yes, docs, pr: lgtm, pr: merge ready, pr: merge safe, target: patch

#11833 chore: bump version to 6.3.0 w/ changelog
  CHANGELOG.md
  package-lock.json
  package.json
Labels: cla: yes, docs, pr: lgtm, pr: merge ready, pr: merge safe, target: master only

#11728 fix(tree): fix dynamic tree example and demo not closing children (#11148)
  src/demo-app/tree/dynamic-tree-demo/dynamic-database.ts
  src/material-examples/tree-dynamic/tree-dynamic-example.ts
Labels: cla: yes, target: patch

#11496 docs(virtual-scroll): add initial documentation
  src/cdk-experimental/scrolling/auto-size-virtual-scroll.ts
  src/cdk-experimental/scrolling/fixed-size-virtual-scroll.ts
  src/cdk-experimental/scrolling/virtual-for-of.ts
  src/cdk-experimental/scrolling/virtual-scroll.md
Labels: cla: yes, docs, pr: lgtm, pr: merge ready, pr: merge safe, target: minor

#11835 Created essential datepicker CDK files and CalendarView component.
  src/cdk/datepicker/BUILD.bazel
  src/cdk/datepicker/calendar-view.ts
  src/cdk/datepicker/datepicker-module.ts
  src/cdk/datepicker/index.ts
  src/cdk/datepicker/public-api.ts
  src/cdk/datepicker/tsconfig-build.json
  src/cdk/datepicker/typings.d.ts
  src/lib/datepicker/BUILD.bazel
  src/lib/datepicker/calendar.ts
  src/lib/datepicker/month-view.ts
  src/lib/datepicker/multi-year-view.ts
  src/lib/datepicker/year-view.ts
Labels: cla: yes, intern project!, pr: lgtm, target: patch

#10990 fix(button-toggle): use native button and aria-pressed for button-toggle
  src/lib/button-toggle/button-toggle.html
  src/lib/button-toggle/button-toggle.scss
  src/lib/button-toggle/button-toggle.spec.ts
  src/lib/button-toggle/button-toggle.ts
Labels: a11y, cla: yes, pr: lgtm, pr: merge ready, target: patch

#11533 fix(table): use solid color for sorting arrow
  src/lib/sort/_sort-theme.scss
Labels: cla: yes, pr: lgtm, pr: merge ready, target: patch

#11537 fix(select): don't blur label when trigger is blurred while the panel is opened
  src/lib/select/select.spec.ts
  src/lib/select/select.ts
Labels: cla: yes, pr: lgtm, pr: merge ready, target: patch

#11707 fix(menu): panel positions not changing if position is updated after first open
  src/lib/menu/menu-trigger.ts
  src/lib/menu/menu.spec.ts
Labels: cla: yes, pr: lgtm, pr: merge ready, target: patch

#11719 feat(slide-toggle): make slide-toggle click and drag actions configurable
  src/lib/slide-toggle/public-api.ts
  src/lib/slide-toggle/slide-toggle-config.ts
  src/lib/slide-toggle/slide-toggle.spec.ts
  src/lib/slide-toggle/slide-toggle.ts
Labels: cla: yes, pr: lgtm, pr: merge ready, target: minor

#11850 fix(docs): add missing semicolon
  src/material-examples/table-sticky-footer/table-sticky-footer-example.html
Labels: cla: yes, pr: lgtm, pr: merge ready, pr: merge safe, target: master only

#11462 fix(progress-spinner): Create internal default to force animations to always be on
  src/lib/progress-spinner/progress-spinner.ts
Labels: G, cla: yes, pr: lgtm, pr: merge ready, target: patch

#11886 fix(button-toggle): emit change event when button is clicked
  src/lib/button-toggle/button-toggle.spec.ts
  src/lib/button-toggle/button-toggle.ts
Labels: cla: yes, pr: lgtm, pr: merge ready, target: master only

#11927 chore: add 6.3.x branch to CI
  .travis.yml
Labels: cla: yes, pr: lgtm, pr: merge ready, pr: merge safe, target: master only

#11824 fix(overlay): explicitly implement OverlayReference.
  src/cdk/overlay/overlay-ref.ts
Labels: P1, cla: yes, pr: lgtm, pr: merge ready, target: patch

#11937 chore: bump the version to 6.3.1
  CHANGELOG.md
  package-lock.json
  package.json
Labels: cla: yes, pr: lgtm, pr: merge ready, pr: merge safe, target: patch

#11771 Update MatFormField outline DOM structure
  src/lib/form-field/_form-field-outline-theme.scss
  src/lib/form-field/form-field-outline.scss
  src/lib/form-field/form-field.html
Labels: cla: yes, pr: lgtm, pr: merge ready, target: patch

#11859 fix(menu): scrollable menu not scrolled to top when opened for the first time
  src/lib/menu/menu-directive.ts
  src/lib/menu/menu.spec.ts
Labels: cla: yes, pr: lgtm, pr: merge ready, target: patch

#11934 fix(select): reset option being marked as selected
  src/lib/select/select.spec.ts
  src/lib/select/select.ts
Labels: cla: yes, pr: lgtm, pr: merge ready, target: patch

#11920 fix(list-key-manager): allow withWrap to be disabled
  src/cdk/a11y/key-manager/list-key-manager.spec.ts
  src/cdk/a11y/key-manager/list-key-manager.ts
Labels: cla: yes, pr: lgtm, pr: merge ready, target: patch

#11900 fix(aria-describer): clear duplicate container coming in from the server
  src/cdk/a11y/aria-describer/aria-describer.spec.ts
  src/cdk/a11y/aria-describer/aria-describer.ts
Labels: cla: yes, pr: lgtm, pr: merge ready, target: patch

#11911 fix(button): not resetting all outlines on firefox
  src/lib/core/style/_button-common.scss
Labels: cla: yes, pr: lgtm, pr: merge ready, target: patch

#11899 fix(card): don't override vertical divider styles
  src/lib/card/card.scss
  src/lib/divider/divider.spec.ts
  src/lib/divider/divider.ts
Labels: cla: yes, pr: lgtm, pr: merge ready, target: patch

#11918 fix(chips): ripples still showing up when globally disabled
  src/lib/chips/chip.ts
  src/lib/tabs/tab-nav-bar/tab-nav-bar.ts
Labels: cla: yes, pr: lgtm, pr: merge ready, target: patch

#11898 fix(tabs): unable to set aria-label or aria-labelledby on tab
  src/lib/tabs/tab-group.html
  src/lib/tabs/tab-group.spec.ts
  src/lib/tabs/tab.ts
Labels: a11y, cla: yes, pr: lgtm, pr: merge ready, target: patch

#11938 fix(overlay): clear timeout if the backdrop transition completes early
  src/cdk/overlay/overlay-ref.ts
  src/cdk/overlay/overlay.spec.ts
Labels: cla: yes, pr: lgtm, pr: merge ready, target: patch

#11830 docs(chips): make separatorKeysCodes readonly
  src/material-examples/chips-input/chips-input-example.ts
Labels: cla: yes, docs, pr: lgtm, pr: merge ready, pr: merge safe, target: master only

#11891 build: include cdk-experimental/dialog in various configs
  src/cdk-experimental/public-api.ts
  src/demo-app/demo-material-module.ts
  src/demo-app/system-config.ts
  src/e2e-app/e2e-app-module.ts
  src/e2e-app/system-config.ts
  test/karma-test-shim.js
Labels: cla: yes, pr: lgtm, pr: merge ready, pr: merge safe, target: master only

#11336 feat(moment-dateadapter): add option to create utc dates
  src/lib/datepicker/datepicker.md
  src/material-moment-adapter/adapter/index.ts
  src/material-moment-adapter/adapter/moment-date-adapter.spec.ts
  src/material-moment-adapter/adapter/moment-date-adapter.ts
Labels: cla: yes, pr: lgtm, pr: merge ready, target: patch

#11870 fix(tree): define CdkTree before CdkTreeNode to prevent errors in JIT
  src/cdk/tree/tree.ts
Labels: cla: yes, pr: lgtm, pr: merge ready, target: master only

#11909 docs(ripple): add note about NoopAnimationsModule
  src/demo-app/toolbar/toolbar-demo.html
  src/lib/core/ripple/ripple.md
  src/lib/core/ripple/ripple.ts
Labels: cla: yes, pr: lgtm, pr: merge ready, target: patch

#11958 build: index file for cdk-experimental/scrolling not being generated
  src/cdk-experimental/scrolling/virtual-scroll-viewport.spec.ts
  src/cdk-experimental/tsconfig-tests.json
Labels: cla: yes, pr: lgtm, pr: merge ready, pr: merge safe, target: master only

#11926 fix(autocomplete): don't override native autocomplete attribute
  src/lib/autocomplete/autocomplete-trigger.ts
  src/lib/autocomplete/autocomplete.spec.ts
Labels: cla: yes, pr: lgtm, pr: merge ready, target: patch

#11433 docs(button): add stroked buttons to examples
  src/lib/button/button.md
  src/material-examples/button-types/button-types-example.css
  src/material-examples/button-types/button-types-example.html
Labels: cla: yes, pr: lgtm, pr: merge ready, pr: merge safe, target: master only

#11967 refactor(checkbox): improve unit test speed
  src/lib/checkbox/checkbox.spec.ts
Labels: cla: yes, pr: lgtm, pr: merge ready, pr: merge safe, target: master only

#11864 feat: add experimental drag-drop package
  .github/CODEOWNERS
  packages.bzl
  src/cdk-experimental/drag-drop/BUILD.bazel
  src/cdk-experimental/drag-drop/drag-drop-module.ts
  src/cdk-experimental/drag-drop/drag-drop.md
  src/cdk-experimental/drag-drop/drag-events.ts
  src/cdk-experimental/drag-drop/drag-handle.ts
  src/cdk-experimental/drag-drop/drag-placeholder.ts
  src/cdk-experimental/drag-drop/drag-preview.ts
  src/cdk-experimental/drag-drop/drag-utils.ts
  src/cdk-experimental/drag-drop/drag.spec.ts
  src/cdk-experimental/drag-drop/drag.ts
  src/cdk-experimental/drag-drop/drop-container.ts
  src/cdk-experimental/drag-drop/drop.scss
  src/cdk-experimental/drag-drop/drop.ts
  src/cdk-experimental/drag-drop/index.ts
  src/cdk-experimental/drag-drop/public-api.ts
  src/cdk-experimental/drag-drop/tsconfig-build.json
  src/cdk-experimental/drag-drop/typings.d.ts
  src/cdk/testing/event-objects.ts
  src/demo-app/demo-app/demo-app.ts
  src/demo-app/demo-app/demo-module.ts
  src/demo-app/demo-app/routes.ts
  src/demo-app/demo-material-module.ts
  src/demo-app/drag-drop/drag-drop-demo.html
  src/demo-app/drag-drop/drag-drop-demo.scss
  src/demo-app/drag-drop/drag-drop-demo.ts
  src/demo-app/system-config.ts
  src/e2e-app/e2e-app-module.ts
  src/e2e-app/system-config.ts
  test/karma-test-shim.js
Labels: cla: yes, pr: lgtm, pr: merge ready, pr: merge safe, target: master only

#11647 fix(schematics): add parse5 dep
  package.json
  src/lib/schematics/install/index.ts
Labels: cla: yes, pr: lgtm, pr: merge ready, pr: merge safe, target: patch

#11846 fix(slide-toggle): not updating model from toggle method
  src/lib/slide-toggle/slide-toggle.spec.ts
  src/lib/slide-toggle/slide-toggle.ts
Labels: cla: yes, pr: lgtm, pr: merge ready, target: patch

#11956 fix(icon): clearing all content when inserting a new SVG
  src/lib/icon/icon.spec.ts
  src/lib/icon/icon.ts
Labels: cla: yes, pr: lgtm, pr: merge ready, target: patch

#11951 fix(button-toggle): allow event bubbling for toggle button clicks
  src/lib/button-toggle/button-toggle.html
  src/lib/button-toggle/button-toggle.ts
Labels: cla: yes, pr: lgtm, pr: merge ready, target: patch

#11901 feat(docs): show additional type aliases in docs.
  src/lib/input/autosize.ts
  tools/dgeni/processors/component-grouper.ts
  tools/dgeni/templates/componentGroup.template.html
  tools/dgeni/templates/type-alias.template.html
Labels: cla: yes, docs, pr: lgtm, pr: merge ready, pr: merge safe, target: patch

#10589 fix(checkbox): fix checkbox animation when moved between view containers
  src/lib/checkbox/checkbox.spec.ts
  src/lib/checkbox/checkbox.ts
Labels: cla: yes, pr: lgtm, pr: merge ready, presubmit failures, target: patch

#10886 feat(tree): support array of data as children in nested tree
  src/cdk/tree/control/base-tree-control.ts
  src/cdk/tree/control/nested-tree-control.spec.ts
  src/cdk/tree/control/nested-tree-control.ts
  src/cdk/tree/control/tree-control.ts
  src/cdk/tree/nested-node.ts
  src/cdk/tree/tree.spec.ts
  src/cdk/tree/tree.ts
  src/demo-app/tree/tree-demo.ts
  src/lib/tree/data-source/flat-data-source.ts
  src/lib/tree/tree.md
  src/material-examples/tree-checklist/tree-checklist-example.ts
  src/material-examples/tree-nested-overview/tree-nested-overview-example.ts
Labels: cla: yes, pr: lgtm, pr: merge ready, target: minor

#11839 Fix schematics collection JSON.
  src/lib/schematics/collection.json
Labels: cla: yes, pr: lgtm, pr: merge ready, pr: merge safe, target: patch

#11816 fix: default config check is not checking test builder
  src/lib/schematics/install/theming.ts
Labels: cla: yes, pr: lgtm, pr: merge ready, pr: merge safe, target: patch

#11884 fix(schematics): error in generated unit test
  src/lib/schematics/nav/files/__path__/__name@dasherize@if-flat__/__name@dasherize__.component.spec.ts
Labels: cla: yes, pr: lgtm, pr: merge ready, pr: merge safe, target: patch

#11799 fix(select): support ctrl+a shortcut for multi-select
  src/lib/select/select.spec.ts
  src/lib/select/select.ts
Labels: cla: yes, pr: lgtm, pr: merge ready, target: patch

#11877 fix(GlobalPositionStrategy): justifyContent center ignored when direction is RTL
  src/cdk/overlay/position/global-position-strategy.spec.ts
  src/cdk/overlay/position/global-position-strategy.ts
Labels: cla: yes, pr: lgtm, pr: merge ready, target: patch

#11827 fix(sort): arrow visible while parent row is being animated
  src/lib/sort/sort-animations.ts
  src/lib/sort/sort-header.scss
Labels: cla: yes, pr: lgtm, pr: merge ready, target: patch

#11810 fix(overlay): don't dispatch key events to overlays that don't handle them
  src/cdk/overlay/keyboard/overlay-keyboard-dispatcher.spec.ts
  src/cdk/overlay/keyboard/overlay-keyboard-dispatcher.ts
  src/cdk/overlay/overlay-ref.ts
  src/lib/bottom-sheet/bottom-sheet-ref.ts
Labels: cla: yes, pr: lgtm, pr: merge ready, target: patch

#11865 fix(tab-nav-bar): ripples still showing up when globally disabled
  src/lib/tabs/tab-nav-bar/tab-nav-bar.ts
  tools/gulp/tasks/screenshots.ts
Labels: cla: yes, pr: lgtm, pr: merge ready, target: patch

#11879 feat(autocomplete): allow panel to have a width value of auto
  src/lib/autocomplete/autocomplete-trigger.ts
  src/lib/autocomplete/autocomplete.spec.ts
  src/lib/autocomplete/autocomplete.ts
Labels: cla: yes, pr: lgtm, pr: merge ready, target: minor

#11882 fix(select): not resuming keyboard selection after clicking on single-select option
  src/lib/select/select.spec.ts
  src/lib/select/select.ts
Labels: cla: yes, pr: lgtm, pr: merge ready, target: patch

#11955 fix(selection-list): disabling list doesn't disable ripples of options
  src/lib/list/selection-list.spec.ts
  src/lib/list/selection-list.ts
Labels: cla: yes, pr: lgtm, pr: merge ready, target: patch

#11962 fix(focus-monitor): allow native focus options to be passed through focusVia
  src/cdk/a11y/focus-monitor/focus-monitor.spec.ts
  src/cdk/a11y/focus-monitor/focus-monitor.ts
Labels: cla: yes, pr: lgtm, pr: merge ready, target: patch

#4469 fix(autocomplete): reposition the panel when the amount of options changes
  src/lib/autocomplete/autocomplete-trigger.ts
  src/lib/autocomplete/autocomplete.spec.ts
Labels: cla: yes, pr: lgtm, pr: merge ready, target: patch

#11981 fix: parse5 not listed as dependency for material
  package-lock.json
  package.json
  src/lib/package.json
Labels: cla: yes, pr: lgtm, pr: merge ready, pr: merge safe, target: patch

#9132 fix(tabs): maintain selected tab when new tabs are added or removed
  src/lib/tabs/tab-group.spec.ts
  src/lib/tabs/tab-group.ts
Labels: cla: yes, pr: lgtm, pr: merge ready, target: patch

#7665 fix(focus-trap): not attaching correctly if element is not in the DOM on init
  src/cdk/a11y/focus-trap/focus-trap.ts
Labels: cla: yes, pr: lgtm, pr: merge ready, target: patch

#11986 fix(sidenav): remove margin from content instead of setting zero
  src/lib/sidenav/drawer.spec.ts
  src/lib/sidenav/drawer.ts
Labels: cla: yes, pr: lgtm, pr: merge ready, target: patch
