Repository angular/components, pull requests merged in 2018-07, with the labels that each got.

#12019 chore: update changelog for 6.3.2
  CHANGELOG.md
  package-lock.json
  package.json
Labels: cla: yes, pr: merge ready, pr: merge safe, target: patch

#10316 feat(list): allow avatar in selection list options
  src/demo-app/list/list-demo.html
  src/lib/list/list-option.html
  src/lib/list/list.scss
  src/lib/list/list.ts
  src/lib/list/selection-list.ts
Labels: cla: yes, pr: lgtm, pr: merge ready, target: minor, target: patch

#11194 fix(tabs): don't show focus indication for mouse focus
  src/lib/tabs/BUILD.bazel
  src/lib/tabs/_tabs-theme.scss
  src/lib/tabs/tab-group.html
  src/lib/tabs/tab-nav-bar/tab-nav-bar.ts
  src/lib/tabs/tabs-module.ts
Labels: cla: yes, pr: lgtm, pr: merge ready, target: patch

#12054 chore: fix duplicate dependency in bazel build
  package-lock.json
  src/lib/tabs/BUILD.bazel
Labels: cla: yes, pr: lgtm, pr: merge ready, pr: merge safe, target: master only

#12018 doc(card): fix landmark roles link
  src/lib/card/card.md
Labels: cla: yes, pr: lgtm, pr: merge safe, target: master only

#11995 build: use index file from material package
  src/demo-app/system-config.ts
  src/demo-app/tsconfig-build.json
  src/material-examples/tsconfig-build.json
  src/material-experimental/tsconfig-build.json
  src/material-moment-adapter/tsconfig-build.json
  test/karma-test-shim.js
Labels: cla: yes, pr: lgtm, pr: merge ready, pr: merge safe, target: master only

#11999 chore(select): panel class example not working and pluralize custom trigger
  src/material-examples/select-custom-trigger/select-custom-trigger-example.html
  src/material-examples/select-panel-class/select-panel-class-example.ts
Labels: cla: yes, docs, pr: lgtm, pr: merge ready, pr: merge safe, target: master only

#12005 docs(radio): fix wrong documentation comment
  src/lib/radio/radio.ts
Labels: cla: yes, docs, pr: lgtm, pr: merge ready, pr: merge safe, target: master only

#12077 build: don't allow duplicate scss imports
  src/lib/menu/menu.scss
  stylelint-config.json
Labels: cla: yes, pr: lgtm, pr: merge ready, pr: merge safe, target: master only

#12098 fix(drag-drop): not accounting for scroll position when dragging
  src/cdk-experimental/drag-drop/BUILD.bazel
  src/cdk-experimental/drag-drop/drag.spec.ts
  src/cdk-experimental/drag-drop/drag.ts
  src/cdk-experimental/drag-drop/drop.scss
Labels: cla: yes, pr: lgtm, pr: merge ready, pr: merge safe, target: patch

#12102 feat(drag-drop): add support for multiple handles and handles that are added after init
  src/cdk-experimental/drag-drop/drag.spec.ts
  src/cdk-experimental/drag-drop/drag.ts
  src/cdk/testing/event-objects.ts
Labels: cla: yes, pr: lgtm, pr: merge ready, pr: merge safe, target: patch

#12104 feat(drag-drop): support sorting items horizontally
  src/cdk-experimental/drag-drop/BUILD.bazel
  src/cdk-experimental/drag-drop/drag.spec.ts
  src/cdk-experimental/drag-drop/drag.ts
  src/cdk-experimental/drag-drop/drop-container.ts
  src/cdk-experimental/drag-drop/drop.ts
  src/demo-app/drag-drop/drag-drop-demo.html
  src/demo-app/drag-drop/drag-drop-demo.scss
  src/demo-app/drag-drop/drag-drop-demo.ts
Labels: cla: yes, pr: lgtm, pr: merge ready, pr: merge safe, target: patch

#12120 update changelog for 6.3.3
  CHANGELOG.md
  package-lock.json
  package.json
Labels: cla: yes, pr: lgtm, pr: merge ready, pr: merge safe, target: patch

#11993 fix(button-toggle): parent margin and padding being propagated to underlying button
  src/lib/button-toggle/button-toggle.scss
Labels: cla: yes, pr: lgtm, pr: merge ready, target: patch

#11989 fix(stepper): unable to set aria-label on step
  src/cdk/stepper/stepper.ts
  src/lib/stepper/stepper-horizontal.html
  src/lib/stepper/stepper-vertical.html
  src/lib/stepper/stepper.spec.ts
Labels: a11y, cla: yes, pr: lgtm, pr: merge ready, target: patch

#11881 fix(autocomplete): error when typing in input with disabled autocomplete and no panel
  src/lib/autocomplete/autocomplete-trigger.ts
  src/lib/autocomplete/autocomplete.spec.ts
Labels: cla: yes, pr: lgtm, pr: merge ready, target: patch

#11867 feat(overlay): expose keydown events on the opened overlay
  src/cdk/overlay/overlay-directives.spec.ts
  src/cdk/overlay/overlay-directives.ts
Labels: cla: yes, pr: lgtm, pr: merge ready, target: minor

#11658 fix(form-field): label gap not being calculated when switching to outline dynamically
  src/lib/form-field/form-field.ts
  src/lib/input/input.spec.ts
Labels: cla: yes, pr: lgtm, pr: merge ready, target: patch

#8669 fix(focus-origin): focus origin sometimes invalid in firefox 57
  src/cdk/a11y/focus-monitor/focus-monitor.spec.ts
  src/cdk/a11y/focus-monitor/focus-monitor.ts
  src/lib/menu/menu.spec.ts
  src/lib/sidenav/drawer.spec.ts
  src/lib/tooltip/tooltip.spec.ts
Labels: cla: yes, pr: lgtm, pr: merge ready, target: patch

#11916 Refactor DateAdapter component to CDK.
  .github/CODEOWNERS
  src/cdk/datepicker/BUILD.bazel
  src/cdk/datetime/BUILD.bazel
  src/cdk/datetime/calendar-view.ts
  src/cdk/datetime/date-adapter.md
  src/cdk/datetime/date-adapter.ts
  src/cdk/datetime/datepicker-module.ts
  src/cdk/datetime/datetime-module.ts
  src/cdk/datetime/index.ts
  src/cdk/datetime/native-date-adapter.spec.ts
  src/cdk/datetime/native-date-adapter.ts
  src/cdk/datetime/public-api.ts
  src/cdk/datetime/tsconfig-build.json
  src/cdk/datetime/typings.d.ts
  src/cdk/testing/month-constants.ts
  src/cdk/testing/public-api.ts
  src/demo-app/demo-material-module.ts
  src/demo-app/system-config.ts
  src/e2e-app/system-config.ts
  src/lib/core/BUILD.bazel
  src/lib/core/datetime/datetime-module.ts
  src/lib/core/datetime/index.ts
  src/lib/core/datetime/public-api.ts
  src/lib/core/public-api.ts
  src/lib/datepicker/BUILD.bazel
  src/lib/datepicker/calendar-header.spec.ts
  src/lib/datepicker/calendar.spec.ts
  src/lib/datepicker/calendar.ts
  src/lib/datepicker/datepicker.spec.ts
  src/lib/datepicker/month-view.spec.ts
  src/lib/datepicker/month-view.ts
  src/lib/datepicker/multi-year-view.spec.ts
  src/lib/datepicker/multi-year-view.ts
  src/lib/datepicker/year-view.spec.ts
  src/lib/datepicker/year-view.ts
  src/material-moment-adapter/BUILD.bazel
  src/material-moment-adapter/adapter/index.ts
  src/material-moment-adapter/adapter/moment-date-adapter.spec.ts
  test/karma-test-shim.js
Labels: cla: yes, intern project!, pr: lgtm, pr: merge ready, target: major

#12099 fix(datepicker): showing dot in high contrast mode after popup has closed
  src/lib/datepicker/calendar-body.scss
Labels: cla: yes, pr: lgtm, pr: merge ready, target: patch

#12097 fix(tabs): don't fire change event when amount of tabs changes
  src/lib/tabs/tab-group.spec.ts
  src/lib/tabs/tab-group.ts
Labels: cla: yes, pr: lgtm, pr: merge ready, target: patch

#12082 fix(ripple): remove webkit touch highlights from ripple containers
  src/lib/button-toggle/button-toggle.scss
  src/lib/chips/chips.scss
  src/lib/core/option/option.scss
  src/lib/list/list.scss
  src/lib/stepper/step-header.scss
  src/lib/tabs/tab-nav-bar/tab-nav-bar.scss
Labels: cla: yes, pr: lgtm, pr: merge ready, target: patch

#12080 fix(expansion-panel): disable hover highlight on non-hover devices
  src/lib/expansion/_expansion-theme.scss
Labels: cla: yes, pr: lgtm, pr: merge ready, target: patch

#12079 fix(slider): track not being rendered under some conditions when using a thumb label
  src/lib/slider/slider.spec.ts
  src/lib/slider/slider.ts
Labels: cla: yes, pr: lgtm, pr: merge ready, target: patch

#12078 fix(icon): reverse for loop when removing child nodes from mat-icon
  src/lib/icon/icon.ts
Labels: cla: yes, pr: lgtm, pr: merge ready, target: patch

#12076 fix(form-field): placeholder not hiding if `-webkit-text-fill-color` is used
  src/lib/input/input.scss
  src/lib/select/select.scss
Labels: cla: yes, pr: lgtm, pr: merge ready, target: patch

#12067 fix(sidenav): continuously hitting zone when using autosize option
  src/lib/sidenav/drawer.ts
Labels: P1, cla: yes, pr: lgtm, pr: merge ready, regression, target: patch

#12129 chore(toolbar): deprecate unused landscape row-height variable
  src/lib/toolbar/toolbar.scss
  src/lib/toolbar/toolbar.ts
Labels: cla: yes, pr: lgtm, pr: merge ready, target: minor

#12030 fix(button): don't show hover overlay on devices that don't support hovering
  src/lib/button/button.scss
Labels: cla: yes, pr: lgtm, pr: merge ready, target: patch

#12014 fix(progress-bar): query animation not working on safari
  src/lib/progress-bar/progress-bar.html
  src/lib/progress-bar/progress-bar.spec.ts
  src/lib/progress-bar/progress-bar.ts
Labels: cla: yes, pr: lgtm, pr: merge ready, target: patch

#12008 fix(datepicker): set role on datepicker popup and aria-haspopup on the datepicker toggle
  src/lib/datepicker/datepicker-toggle.html
  src/lib/datepicker/datepicker.md
  src/lib/datepicker/datepicker.spec.ts
  src/lib/datepicker/datepicker.ts
Labels: a11y, cla: yes, pr: lgtm, pr: merge ready, target: patch

#12003 fix(slider): support two-way binding for value
  src/lib/slider/slider.spec.ts
  src/lib/slider/slider.ts
Labels: cla: yes, pr: lgtm, pr: merge ready, target: minor

#11970 build: fix small browser test coverage
  package-lock.json
  package.json
  scripts/saucelabs/start-tunnel.sh
  src/cdk/table/table.spec.ts
  src/lib/select/select.spec.ts
  test/browser-providers.js
  test/karma-system-config.js
  test/karma-test-shim.js
  test/karma.conf.js
  test/protractor.conf.js
  test/remote_browsers.json
Labels: cla: yes, pr: lgtm, pr: merge ready, pr: merge safe, target: master only

#12028 fix(schematic): parse5 v5.0.0 requires different parse options
  src/lib/schematics/utils/html.ts
Labels: cla: yes, pr: lgtm, pr: merge ready, pr: merge safe, target: patch

#12063 chore: add example for ripple
  src/demo-app/ripple/ripple-demo.html
  src/demo-app/ripple/ripple-demo.scss
  src/material-examples/ripple-overview/ripple-overview-example.css
  src/material-examples/ripple-overview/ripple-overview-example.html
  src/material-examples/ripple-overview/ripple-overview-example.ts
Labels: cla: yes, pr: lgtm, pr: merge ready, pr: merge safe, target: master only

#12093 build: make body scrollable element in demo
  src/demo-app/demo-app/demo-app.html
  src/demo-app/demo-app/demo-app.scss
Labels: cla: yes, pr: lgtm, pr: merge ready, pr: merge safe, target: master only

#12100 build: enable fullTemplateTypeCheck in aot mode
  src/demo-app/bottom-sheet/bottom-sheet-demo.html
  src/demo-app/bottom-sheet/bottom-sheet-demo.ts
  src/demo-app/dialog/dialog-demo.html
  src/demo-app/sidenav/sidenav-demo.html
  src/demo-app/tsconfig-aot.json
  src/e2e-app/tsconfig-build.json
  src/material-examples/tsconfig-build.json
Labels: cla: yes, pr: lgtm, pr: merge ready, pr: merge safe, target: master only

#12103 build: fix random ngc resolve failures
  src/lib/tsconfig-tests.json
  tools/package-tools/build-package.ts
  tools/package-tools/gulp/build-tasks-gulp.ts
Labels: cla: yes, pr: lgtm, pr: merge ready, pr: merge safe, target: master only

#12111 chore: fix typo in comment
  test/karma.conf.js
Labels: cla: yes, commit message fixup, pr: merge ready, pr: merge safe, target: master only

#12121 fix(drag-drop): add fallback if the placeholder transition doesn't complete
  src/cdk-experimental/drag-drop/drag.spec.ts
  src/cdk-experimental/drag-drop/drag.ts
Labels: cla: yes, pr: lgtm, pr: merge ready, pr: merge safe, target: patch

#12136 chore: invalid jsdoc in focus-monitor
  src/cdk/a11y/focus-monitor/focus-monitor.ts
Labels: cla: yes, pr: lgtm, pr: merge ready, pr: merge safe, target: patch

#12143 docs: update README for Q3 2018
  README.md
Labels: cla: yes, docs, pr: lgtm, pr: merge ready, pr: merge safe, target: master only

#12160 fix(tabs): unable to distinguish disabled tab in high contrast mode
  src/lib/tabs/_tabs-common.scss
Labels: a11y, cla: yes, pr: lgtm, pr: merge ready, target: patch

#12159 fix(sort): arrow indicator not visible in high contrast mode
  src/lib/sort/sort-header.scss
Labels: a11y, cla: yes, pr: lgtm, pr: merge ready, target: patch

#12151 fix(progress-spinner): circle not rendering correctly when switching modes in Safari
  src/lib/progress-spinner/progress-spinner-module.ts
  src/lib/progress-spinner/progress-spinner.html
  src/lib/progress-spinner/progress-spinner.spec.ts
Labels: cla: yes, pr: lgtm, pr: merge ready, target: patch

#12150 fix(slide-toggle): no color demarcation in high contrast black mode
  src/lib/slide-toggle/slide-toggle.scss
Labels: a11y, cla: yes, pr: lgtm, pr: merge ready, target: patch

#12137 fix(form-field): clear safari autofill icons
  src/lib/input/input.scss
Labels: cla: yes, pr: lgtm, pr: merge ready, target: patch

#12142 fix(overlay): remove panelClass when the overlay is detached
  src/cdk/overlay/overlay-ref.ts
  src/cdk/overlay/overlay.spec.ts
Labels: cla: yes, pr: lgtm, pr: merge ready, target: patch

#12127 fix(radio): circle not being greyed out when disabled
  src/lib/radio/_radio-theme.scss
Labels: cla: yes, pr: lgtm, pr: merge ready, target: patch

#12119 fix(overlay): account for virtual keyboard offset on mobile devices
  src/cdk/overlay/position/flexible-connected-position-strategy.spec.ts
  src/cdk/overlay/position/flexible-connected-position-strategy.ts
  src/cdk/overlay/position/overlay-position-builder.ts
Labels: P3, cla: yes, pr: lgtm, pr: merge ready, target: patch

#12113 fix(selection-list): form control disable locks disabled property
  src/lib/list/selection-list.spec.ts
  src/lib/list/selection-list.ts
Labels: cla: yes, pr: lgtm, pr: merge ready, target: patch

#12106 fix(bottom-sheet): close on page navigation
  src/lib/bottom-sheet/bottom-sheet-config.ts
  src/lib/bottom-sheet/bottom-sheet-ref.ts
  src/lib/bottom-sheet/bottom-sheet.spec.ts
  src/lib/bottom-sheet/bottom-sheet.ts
Labels: cla: yes, pr: lgtm, pr: merge ready, target: patch

#12068 fix: sanity checks throwing an error if scripts are set in the head
  src/lib/core/common-behaviors/common-module.ts
Labels: cla: yes, pr: lgtm, pr: merge ready, target: patch

#12042 fix(button): unable to set a custom tabindex on a link button
  src/lib/button/button.spec.ts
  src/lib/button/button.ts
Labels: cla: yes, pr: lgtm, pr: merge ready, target: patch

#12006 fix(datepicker): all cells being read out as selected
  src/lib/datepicker/calendar-body.html
  src/lib/datepicker/calendar-body.spec.ts
Labels: a11y, cla: yes, pr: lgtm, pr: merge ready, target: patch

#12004 fix(datepicker): calendar input changes not being propagated on child views
  src/lib/datepicker/calendar.spec.ts
  src/lib/datepicker/calendar.ts
Labels: cla: yes, pr: lgtm, pr: merge ready, target: patch

#11994 fix(select): blank option label throwing off alignment
  src/lib/select/select.html
Labels: cla: yes, pr: lgtm, pr: merge ready, target: patch

#12158 virtual-scroll: use `detectChanges` rather than `markForCheck` in `CdkVirtualScrollViewport`
  src/cdk-experimental/scrolling/virtual-scroll-viewport.spec.ts
  src/cdk-experimental/scrolling/virtual-scroll-viewport.ts
Labels: cla: yes, pr: lgtm, pr: merge ready, pr: merge safe, target: master only

#12240 chore: bump version to 6.4.0 w/ changelog
  CHANGELOG.md
  package.json
Labels: cla: yes, pr: lgtm, pr: merge ready, pr: merge safe, target: master only

#11975 Docs: Adds new button examples
  src/material-examples/button-types/button-types-example.html
Labels: cla: yes, pr: lgtm, pr: merge ready, pr: merge safe, target: patch

#12181 virtual-scroll: Avoid using bypassSecurityTrustStyle which is banned in google3
  src/cdk-experimental/scrolling/virtual-scroll-viewport.html
  src/cdk-experimental/scrolling/virtual-scroll-viewport.spec.ts
  src/cdk-experimental/scrolling/virtual-scroll-viewport.ts
Labels: cla: yes, pr: lgtm, pr: merge ready, pr: merge safe, target: master only

#12215 fix(tabs): content animation in RTL not working (chrome)
  src/lib/tabs/tabs-animations.ts
Labels: P2, cla: yes, pr: lgtm, pr: merge ready, target: patch

#12214 fix(drag-drop): make `CDK_DROP_CONTAINER` public
  src/cdk-experimental/drag-drop/drop-container.ts
  src/cdk-experimental/drag-drop/public-api.ts
Labels: cla: yes, pr: lgtm, pr: merge ready, pr: merge safe, target: patch

#12219 test(drag-drop): add missing unit tests
  src/cdk-experimental/drag-drop/drag-utils.spec.ts
  src/cdk-experimental/drag-drop/drag-utils.ts
  src/cdk-experimental/drag-drop/drag.spec.ts
Labels: cla: yes, pr: lgtm, pr: merge ready, pr: merge safe, target: patch

#12200 fix(tooltip): interfering with native drag&drop
  src/lib/tooltip/tooltip.spec.ts
  src/lib/tooltip/tooltip.ts
Labels: cla: yes, pr: lgtm, pr: merge ready, target: patch

#12201 fix(menu): focus indication not visible in high contrast mode
  src/lib/menu/menu.scss
Labels: cla: yes, pr: lgtm, pr: merge ready, target: patch

#12204 fix(drag-drop): disable text selection on draggable element
  src/cdk-experimental/drag-drop/drop.scss
Labels: cla: yes, pr: lgtm, pr: merge ready, pr: merge safe, target: patch

#12029 fix(moment-date-adapter): not returning utc date when parsing
  src/material-moment-adapter/adapter/moment-date-adapter.spec.ts
  src/material-moment-adapter/adapter/moment-date-adapter.ts
Labels: cla: yes, pr: lgtm, pr: merge ready, target: patch

#12255 chore(examples): fix tab group example title
  src/material-examples/tab-group-dynamic/tab-group-dynamic-example.ts
Labels: cla: yes, pr: lgtm, pr: merge ready, pr: merge safe, target: patch

#12230 build: add git-semver-tags to dev dependencies
  package-lock.json
  package.json
Labels: cla: yes, pr: lgtm, pr: merge ready, pr: merge safe, target: master only

#11739 feat(schematics): tree schematic
  src/lib/schematics/collection.json
  src/lib/schematics/tree/files/__path__/__name@dasherize@if-flat__/__name@dasherize__.component.__styleext__
  src/lib/schematics/tree/files/__path__/__name@dasherize@if-flat__/__name@dasherize__.component.html
  src/lib/schematics/tree/files/__path__/__name@dasherize@if-flat__/__name@dasherize__.component.spec.ts
  src/lib/schematics/tree/files/__path__/__name@dasherize@if-flat__/__name@dasherize__.component.ts
  src/lib/schematics/tree/files/__path__/__name@dasherize@if-flat__/example-data.ts
  src/lib/schematics/tree/index.ts
  src/lib/schematics/tree/schema.json
  src/lib/schematics/tree/schema.ts
Labels: cla: yes, pr: lgtm, pr: merge ready, pr: merge safe, target: master only

#12207 chore: gesture config test logging out warnings
  src/lib/core/gestures/gesture-config.spec.ts
Labels: cla: yes, pr: lgtm, pr: merge ready, pr: merge safe, target: master only

#12221 build: e2e and test init files not being linted
  e2e/components/tabs-e2e.spec.ts
  test/angular-test-init-spec.ts
  tsconfig.json
Labels: cla: yes, pr: lgtm, pr: merge ready, pr: merge safe, target: master only

#12235 docs(stepper): Fix Stackblitz example for mat-vertical-stepper
  src/material-examples/stepper-vertical/stepper-vertical-example.ts
Labels: cla: yes, commit message fixup, pr: lgtm, pr: merge ready, pr: merge safe, target: master only

#12216 fix(schematics): fix object iteration error in dashboard
  src/lib/schematics/dashboard/files/__path__/__name@dasherize@if-flat__/__name@dasherize__.component.html
  src/lib/schematics/dashboard/files/__path__/__name@dasherize@if-flat__/__name@dasherize__.component.ts
Labels: cla: yes, pr: lgtm, pr: merge ready, target: patch

#12218 fix(tabs): enable keyboard wrapping and mark disabled tabs
  e2e/components/tabs-e2e.spec.ts
  src/lib/tabs/tab-group.spec.ts
  src/lib/tabs/tab-header.ts
  src/lib/tabs/tab-label-wrapper.ts
Labels: a11y, cla: yes, pr: lgtm, pr: merge ready, target: patch

#12239 fix(badge): hide badges with no content
  src/lib/badge/badge.spec.ts
  src/lib/badge/badge.ts
Labels: cla: yes, pr: lgtm, pr: merge ready, target: patch

#12222 fix(overlay): avoid same overlay being added to the keyboard event stack multiple times
  src/cdk/overlay/keyboard/overlay-keyboard-dispatcher.spec.ts
  src/cdk/overlay/keyboard/overlay-keyboard-dispatcher.ts
Labels: cla: yes, pr: lgtm, pr: merge ready, target: patch

#12253 docs(datepicker): custom datepicker header demo styling not working
  src/material-examples/datepicker-custom-header/datepicker-custom-header-example.css
  src/material-examples/datepicker-custom-header/datepicker-custom-header-example.ts
Labels: cla: yes, pr: lgtm, pr: merge ready, pr: merge safe, target: master only

#12229 fix(tabs): reposition tab body on direction change
  src/lib/tabs/tab-body.spec.ts
  src/lib/tabs/tab-body.ts
  src/lib/tabs/tab-group.ts
Labels: cla: yes, i18n, pr: lgtm, pr: merge ready, target: patch

#12211 fix(menu): collapse empty menu panel
  src/lib/menu/menu.scss
Labels: cla: yes, pr: lgtm, pr: merge ready, target: patch

#12183 virtual-scroll: add support for user-provided content wrapper
  src/cdk-experimental/scrolling/virtual-for-of.ts
  src/cdk-experimental/scrolling/virtual-scroll-viewport.scss
  src/cdk-experimental/scrolling/virtual-scroll-viewport.spec.ts
  src/cdk-experimental/scrolling/virtual-scroll-viewport.ts
  src/cdk-experimental/scrolling/virtual-scroll.md
  src/demo-app/virtual-scroll/virtual-scroll-demo.html
  src/demo-app/virtual-scroll/virtual-scroll-demo.scss
Labels: cla: yes, pr: lgtm, pr: merge ready, pr: merge safe, target: patch

#12209 fix(menu): changed after checked error when toggling quickly between triggers for same submenu
  src/lib/menu/menu-trigger.ts
Labels: caretaker note, cla: yes, pr: lgtm, pr: merge ready, target: patch

#12193 feat(bottom-sheet): allow autofocusing to be disabled
  src/lib/bottom-sheet/bottom-sheet-config.ts
  src/lib/bottom-sheet/bottom-sheet-container.ts
  src/lib/bottom-sheet/bottom-sheet.spec.ts
Labels: cla: yes, pr: lgtm, pr: merge ready, target: minor

#11890 feat(select): allow for option sorting logic to be customized
  src/lib/select/select.spec.ts
  src/lib/select/select.ts
Labels: cla: yes, pr: lgtm, pr: merge ready, target: minor

#11821 Add public method to MatCalendar to update today's date
  src/lib/datepicker/calendar.spec.ts
  src/lib/datepicker/calendar.ts
  src/lib/datepicker/datepicker-content.html
  src/lib/datepicker/datepicker.spec.ts
  src/lib/datepicker/datepicker.ts
Labels: cla: yes, pr: lgtm, pr: merge ready, target: minor

#12036 fix(tabs): ripple overflow in internet explorer
  src/lib/tabs/tab-header.ts
Labels: cla: yes, pr: lgtm, pr: merge ready, target: patch

#12273 refactor(schematics): no longer duplicate files for inline flags
  src/lib/schematics/address-form/files/__path__/__name@dasherize@if-flat__/__name@dasherize__.component.ts
  src/lib/schematics/address-form/index.ts
  src/lib/schematics/dashboard/files/__path__/__name@dasherize@if-flat__/__name@dasherize__.component.ts
  src/lib/schematics/dashboard/index.ts
  src/lib/schematics/nav/files/__path__/__name@dasherize@if-flat__/__name@dasherize__.component.ts
  src/lib/schematics/nav/index.ts
  src/lib/schematics/table/files/__path__/__name@dasherize@if-flat__/__name@dasherize__.component.ts
  src/lib/schematics/table/index.ts
  src/lib/schematics/tree/files/__path__/__name@dasherize@if-flat__/__name@dasherize__.component.ts
  src/lib/schematics/tree/index.ts
  src/lib/schematics/utils/devkit-utils/component.ts
Labels: cla: yes, pr: lgtm, pr: merge ready, pr: merge safe, target: master only

#12052 fix(table): unable to sort large numbers in strings
  src/lib/table/table-data-source.ts
  src/lib/table/table.spec.ts
Labels: cla: yes, pr: lgtm, pr: merge ready, target: patch

#12168 fix(ripple): don't hide directive host in high contrast
  src/lib/core/ripple/_ripple.scss
Labels: a11y, cla: yes, pr: lgtm, pr: merge ready, target: patch

#12192 fix(tab-group): focus change event not firing for keyboard navigation
  src/lib/tabs/tab-group.spec.ts
  src/lib/tabs/tab-header.ts
Labels: cla: yes, pr: lgtm, pr: merge ready, target: patch

#12289 docs(cdk): fix spelling
  src/lib/expansion/accordion.ts
Labels: cla: yes, pr: lgtm, pr: merge ready, pr: merge safe, target: patch

#12141 fix(menu): showing scrollbars on first open in Edge if item width is set
  src/lib/core/style/_menu-common.scss
Labels: cla: yes, pr: lgtm, pr: merge ready, target: patch

#11910 fix(chips): losing focus if active chip is deleted
  src/lib/chips/chip-list.spec.ts
  src/lib/chips/chip-list.ts
Labels: a11y, cla: yes, pr: lgtm, pr: merge ready, target: patch

#12281 fix(schematics): tree schematic not working
  src/lib/schematics/tree/files/__path__/__name@dasherize@if-flat__/__name@dasherize__.component.ts
  src/lib/schematics/tree/files/__path__/__name@dasherize@if-flat__/example-data.ts
Labels: cla: yes, pr: lgtm, pr: merge ready, pr: merge safe, target: master only

#12286 chore(autocomplete): fix image spacing on overview example
  src/material-examples/autocomplete-overview/autocomplete-overview-example.css
Labels: cla: yes, docs, pr: lgtm, pr: merge ready, pr: merge safe, target: patch

#12284 fix(slide-toggle): invert the thumb and slide gesture in rtl
  src/lib/slide-toggle/BUILD.bazel
  src/lib/slide-toggle/slide-toggle.scss
  src/lib/slide-toggle/slide-toggle.spec.ts
  src/lib/slide-toggle/slide-toggle.ts
Labels: cla: yes, pr: lgtm, pr: merge ready, target: patch

#12245 fix(tabs): selectedIndex being overwritten if tabs are being added / removed
  src/lib/tabs/tab-group.spec.ts
  src/lib/tabs/tab-group.ts
Labels: cla: yes, pr: lgtm, pr: merge ready, target: patch

#12305 docs(ripple): fix missing jsdoc descriptions
  src/lib/core/ripple/ripple-ref.ts
  src/lib/core/ripple/ripple.ts
Labels: cla: yes, docs, pr: lgtm, pr: merge ready, target: patch

#12313 docs(theming): update theming.md for angular 6
  guides/theming.md
Labels: cla: yes, pr: lgtm, pr: merge ready, pr: merge safe, target: patch

#12261 fix(drag-drop): unable to drag last item back into initial container
  src/cdk-experimental/drag-drop/drag.spec.ts
  src/cdk-experimental/drag-drop/drag.ts
  src/cdk-experimental/drag-drop/drop.ts
Labels: cla: yes, pr: lgtm, pr: merge ready, pr: merge safe, target: patch

#12320 docs: fix up button-types and dialog-content examples
  src/material-examples/button-types/button-types-example.css
  src/material-examples/dialog-content/dialog-content-example-dialog.html
  src/material-examples/dialog-content/dialog-content-example.ts
Labels: cla: yes, docs, pr: lgtm, pr: merge ready, pr: merge safe, target: patch

#12308 docs: properly show method overloads
  tools/dgeni/processors/categorizer.ts
Labels: cla: yes, docs, pr: lgtm, pr: merge ready, pr: merge safe, target: patch

#12314 fix(update): support parenthesized directive metadata
  src/lib/schematics/update/tslint/component-walker.ts
Labels: cla: yes, pr: lgtm, pr: merge ready, pr: merge safe, target: patch

#12317 fix(schematics): properly indent inline files
  src/lib/schematics/address-form/files/__path__/__name@dasherize@if-flat__/__name@dasherize__.component.ts
  src/lib/schematics/dashboard/files/__path__/__name@dasherize@if-flat__/__name@dasherize__.component.ts
  src/lib/schematics/nav/files/__path__/__name@dasherize@if-flat__/__name@dasherize__.component.ts
  src/lib/schematics/table/files/__path__/__name@dasherize@if-flat__/__name@dasherize__.component.ts
  src/lib/schematics/tree/files/__path__/__name@dasherize@if-flat__/__name@dasherize__.component.ts
  src/lib/schematics/utils/devkit-utils/README.md
  src/lib/schematics/utils/devkit-utils/component.ts
Labels: cla: yes, pr: lgtm, pr: merge ready, pr: merge safe, target: master only

#12335 build: avoid manually-maintained example lists
  src/demo-app/table/table-demo.ts
  src/demo-app/tabs/tabs-demo.ts
  src/demo-app/tooltip/tooltip-demo.ts
Labels: cla: yes, pr: lgtm, pr: merge ready, pr: merge safe, target: master only

#12346 build: remove unused dependencies
  BUILD.bazel
  package-lock.json
  package.json
Labels: cla: yes, pr: lgtm, pr: merge ready, pr: merge safe, target: master only

#12316 refactor: remove internal usages of deprecated apis
  src/cdk-experimental/drag-drop/drag.ts
  src/lib/datepicker/datepicker.ts
  src/lib/list/selection-list.spec.ts
Labels: cla: yes, pr: lgtm, pr: merge ready, target: patch

#12334 perf(tree): leaking reference through mostRecentTreeNode
  src/cdk/tree/tree.spec.ts
  src/cdk/tree/tree.ts
Labels: cla: yes, perf, pr: lgtm, pr: merge ready, target: patch

#12272 virtual-scroll: add support for `scrollToOffset` and `scrollToIndex`
  src/cdk-experimental/scrolling/BUILD.bazel
  src/cdk-experimental/scrolling/auto-size-virtual-scroll.ts
  src/cdk-experimental/scrolling/fixed-size-virtual-scroll.ts
  src/cdk-experimental/scrolling/virtual-scroll-strategy.ts
  src/cdk-experimental/scrolling/virtual-scroll-viewport.spec.ts
  src/cdk-experimental/scrolling/virtual-scroll-viewport.ts
  src/cdk/platform/features.ts
  src/demo-app/virtual-scroll/virtual-scroll-demo.html
  src/demo-app/virtual-scroll/virtual-scroll-demo.ts
Labels: cla: yes, pr: lgtm, pr: merge ready, target: patch

#12315 feat(drag-drop): allow connecting containers via string ids, attaching data to drop instances and consolidate global event listeners
  src/cdk-experimental/drag-drop/drag-drop-registry.spec.ts
  src/cdk-experimental/drag-drop/drag-drop-registry.ts
  src/cdk-experimental/drag-drop/drag.spec.ts
  src/cdk-experimental/drag-drop/drag.ts
  src/cdk-experimental/drag-drop/drop.ts
  src/cdk-experimental/drag-drop/public-api.ts
Labels: cla: yes, pr: lgtm, pr: merge ready, pr: merge safe, target: patch

#12274 Integrated material datepicker and datepicker inputs with CDK datepicker and datepicker inputs
  src/cdk/datetime/datepicker-input.ts
  src/cdk/datetime/public-api.ts
  src/demo-app/datepicker/datepicker-demo.ts
  src/lib/core/datetime/date-formats.ts
  src/lib/core/datetime/datetime-module.ts
  src/lib/core/datetime/native-date-formats.ts
  src/lib/datepicker/datepicker-input.ts
  src/lib/datepicker/datepicker.spec.ts
  src/lib/datepicker/datepicker.ts
  src/material-examples/datepicker-events/datepicker-events-example.ts
  src/material-examples/datepicker-formats/datepicker-formats-example.ts
  src/material-examples/datepicker-locale/datepicker-locale-example.ts
  src/material-examples/datepicker-moment/datepicker-moment-example.ts
  src/material-examples/datepicker-views-selection/datepicker-views-selection-example.ts
  src/material-moment-adapter/adapter/index.ts
  src/material-moment-adapter/adapter/moment-date-formats.ts
Labels: cla: yes, intern project!, pr: lgtm, pr: merge ready, target: major

#12377 docs: Getting started guide update about animations
  guides/getting-started.md
Labels: cla: yes, docs, pr: lgtm, pr: merge ready, pr: merge safe, target: patch

#12350 fix(progress-bar): query animation not working inside routes with named outlets
  src/lib/progress-bar/progress-bar.html
  src/lib/progress-bar/progress-bar.spec.ts
  src/lib/progress-bar/progress-bar.ts
Labels: P2, cla: yes, pr: lgtm, pr: merge ready, target: patch

#12301 refactor(table): remove redundant constructors
  src/lib/table/cell.ts
  src/lib/table/row.ts
Labels: cla: yes, pr: lgtm, pr: merge ready, target: patch

#12381 virtual-scroll: emit the currently scrolled to index
  src/cdk-experimental/scrolling/auto-size-virtual-scroll.ts
  src/cdk-experimental/scrolling/fixed-size-virtual-scroll.ts
  src/cdk-experimental/scrolling/virtual-scroll-strategy.ts
  src/cdk-experimental/scrolling/virtual-scroll-viewport.spec.ts
  src/cdk-experimental/scrolling/virtual-scroll-viewport.ts
  src/demo-app/virtual-scroll/virtual-scroll-demo.html
  src/demo-app/virtual-scroll/virtual-scroll-demo.ts
Labels: cla: yes, pr: lgtm, pr: merge ready, pr: merge safe, target: patch

#11706 fix(sidenav): scrollable instance not exposed when explicitly specifying content element
  src/lib/sidenav/drawer-container.html
  src/lib/sidenav/drawer.spec.ts
  src/lib/sidenav/drawer.ts
  src/lib/sidenav/sidenav.md
  src/lib/sidenav/sidenav.ts
Labels: cla: yes, pr: lgtm, pr: merge ready, target: major

#12269 perf(table): leaking reference through mostRecentCellOutlet
  src/cdk/table/row.ts
  src/cdk/table/table.spec.ts
Labels: cla: yes, perf, pr: lgtm, pr: merge ready, target: patch

#12285 fix(card): incorrectly inverting inset divider in rtl
  src/lib/card/card.scss
Labels: cla: yes, pr: lgtm, pr: merge ready, target: patch

#12294 fix(snack-bar): prevent content from overriding configured aria-live message
  src/lib/snack-bar/snack-bar-config.ts
  src/lib/snack-bar/snack-bar.spec.ts
  src/lib/snack-bar/snack-bar.ts
Labels: cla: yes, pr: lgtm, pr: merge ready, target: patch

#12393 fix(drag-drop): throwing off NgFor differ
  src/cdk-experimental/drag-drop/drag.spec.ts
  src/cdk-experimental/drag-drop/drag.ts
Labels: cla: yes, pr: lgtm, pr: merge ready, pr: merge safe, target: patch

#12370 build: switch to dart-sass
  package-lock.json
  package.json
  tools/package-tools/gulp/build-scss-task.ts
Labels: cla: yes, pr: lgtm, pr: merge ready, pr: merge safe, target: major

#12310 feat(tooltip): align with 2018 material design spec
  src/lib/tooltip/_tooltip-theme.scss
  src/lib/tooltip/tooltip-animations.ts
  src/lib/tooltip/tooltip.scss
Labels: caretaker note, cla: yes, pr: lgtm, pr: merge ready, target: major

#12421 build: rename @deletion-target to @breaking-change
  src/cdk/a11y/aria-describer/aria-describer.ts
  src/cdk/a11y/focus-monitor/focus-monitor.ts
  src/cdk/a11y/focus-trap/focus-trap.ts
  src/cdk/a11y/key-manager/list-key-manager.ts
  src/cdk/a11y/live-announcer/live-announcer.ts
  src/cdk/overlay/keyboard/overlay-keyboard-dispatcher.ts
  src/cdk/overlay/overlay-container.ts
  src/cdk/overlay/overlay-directives.ts
  src/cdk/overlay/overlay-module.ts
  src/cdk/overlay/position/connected-position-strategy.ts
  src/cdk/overlay/position/flexible-connected-position-strategy.ts
  src/cdk/overlay/position/global-position-strategy.ts
  src/cdk/overlay/position/overlay-position-builder.ts
  src/cdk/platform/platform.ts
  src/cdk/scrolling/scroll-dispatcher.ts
  src/cdk/scrolling/viewport-ruler.ts
  src/cdk/stepper/stepper.ts
  src/cdk/table/table.ts
  src/lib/autocomplete/autocomplete-trigger.ts
  src/lib/button-toggle/button-toggle.ts
  src/lib/button/button.ts
  src/lib/chips/chip-input.ts
  src/lib/core/datetime/date-adapter.ts
  src/lib/core/gestures/gesture-config.ts
  src/lib/core/ripple/ripple-renderer.ts
  src/lib/core/ripple/ripple.ts
  src/lib/core/theming/_palette.scss
  src/lib/datepicker/datepicker-input.ts
  src/lib/form-field/_form-field-legacy-theme.scss
  src/lib/form-field/form-field.html
  src/lib/form-field/form-field.scss
  src/lib/form-field/form-field.ts
  src/lib/form-field/placeholder.ts
  src/lib/input/autosize.ts
  src/lib/input/input.ts
  src/lib/list/list.ts
  src/lib/menu/menu-animations.ts
  src/lib/menu/menu-directive.ts
  src/lib/menu/menu-item.ts
  src/lib/menu/menu-trigger.ts
  src/lib/paginator/paginator.scss
  src/lib/paginator/paginator.ts
  src/lib/progress-bar/progress-bar.ts
  src/lib/progress-spinner/progress-spinner.ts
  src/lib/select/select-animations.ts
  src/lib/select/select.ts
  src/lib/slide-toggle/slide-toggle.ts
  src/lib/slider/slider.ts
  src/lib/snack-bar/snack-bar-ref.ts
  src/lib/tabs/tab-body.ts
  src/lib/tabs/tab-nav-bar/tab-nav-bar.ts
  src/lib/toolbar/toolbar.scss
  tools/dgeni/common/decorators.ts
  tools/dgeni/common/dgeni-definitions.ts
  tools/dgeni/index.ts
  tools/dgeni/templates/macros.html
  tools/tslint-rules/breakingChangeRule.ts
  tslint.json
Labels: cla: yes, pr: lgtm, pr: merge ready, pr: merge safe, target: master only

#12441 chore: 6.4.2 changelog
  CHANGELOG.md
  package.json
Labels: cla: yes, target: patch

#12439 cleanup: use regex to whitelist branches for CI
  .circleci/config.yml
  .travis.yml
Labels: cla: yes, pr: lgtm, pr: merge ready, pr: merge safe, target: patch

#12434 fix(schematics): properly detect tsconfig files
  src/lib/schematics/update/update.spec.ts
  src/lib/schematics/update/update.ts
  tslint.json
Labels: cla: yes, pr: lgtm, pr: merge ready, pr: merge safe, target: major

#12426 build: speed-up stylesheet building
  package-lock.json
  package.json
  src/demo-app/theme.scss
  tools/gulp/tasks/development.ts
  tools/gulp/tasks/material-release.ts
  tools/package-tools/gulp/build-scss-pipeline.ts
  tools/package-tools/gulp/build-scss-task.ts
  tools/package-tools/gulp/build-tasks-gulp.ts
  tools/package-tools/index.ts
Labels: cla: yes, pr: lgtm, pr: merge ready, pr: merge safe, target: major

#12420 build: remove deprecated node-github api
  package-lock.json
  package.json
  scripts/caretaking/write-presumbit-scheduler.js
Labels: cla: yes, pr: lgtm, pr: merge ready, pr: merge safe, target: master only

#12444 chore: remove tinayuangao from codeowners
  .github/CODEOWNERS
Labels: cla: yes, pr: merge ready, pr: merge safe, target: master only
