Repository angular/components, pull requests merged in 2018-04, with the labels that each got.

#10649 build: lock down typescript version
  package-lock.json
  package.json
Labels: cla: yes, pr: lgtm, pr: merge ready, pr: merge safe, release: patch

#10642 build: bump to angular 6.0.0-rc.1 and rxjs 6.0.0-rc.0
  BUILD.bazel
  WORKSPACE
  angular.tsconfig.json
  package-lock.json
  package.json
  src/cdk/a11y/BUILD.bazel
  src/cdk/overlay/BUILD.bazel
  src/cdk/tree/BUILD.bazel
Labels: cla: yes, pr: lgtm, pr: merge ready, pr: merge safe, release: patch

#10689 build(bazel): add rules for moment adapter and experimental packages
  packages.bzl
  src/cdk-experimental/BUILD.bazel
  src/cdk/BUILD.bazel
  src/cdk/rollup_globals.bzl
  src/lib/BUILD.bazel
  src/lib/rollup_globals.bzl
  src/material-experimental/BUILD.bazel
  src/material-moment-adapter/BUILD.bazel
Labels: cla: yes, pr: lgtm, pr: merge ready, pr: merge safe

#10704 fix(tooltip): error when updating position while closed
  src/lib/tooltip/tooltip.spec.ts
  src/lib/tooltip/tooltip.ts
Labels: cla: yes, pr: lgtm, pr: merge ready, release: patch

#10692 fix: remove duplicate imports
  src/cdk/overlay/position/connected-position-strategy.spec.ts
  src/cdk/overlay/position/connected-position-strategy.ts
  src/cdk/overlay/position/flexible-connected-position-strategy.spec.ts
  src/cdk/text-field/autofill.ts
  src/demo-app/autocomplete/autocomplete-demo.ts
  src/demo-app/datepicker/datepicker-demo.ts
  src/demo-app/overlay/overlay-demo.ts
  src/demo-app/table/table-demo.ts
  src/demo-app/tree/dynamic-tree-demo/dynamic-database.ts
  src/demo-app/tree/tree-demo.ts
  src/lib/autocomplete/autocomplete.spec.ts
  src/lib/bottom-sheet/bottom-sheet-ref.ts
  src/lib/bottom-sheet/bottom-sheet.spec.ts
  src/lib/chips/chip-list.ts
  src/lib/core/common-behaviors/initialized.ts
  src/lib/datepicker/datepicker-module.ts
  src/lib/datepicker/datepicker-toggle.ts
  src/lib/datepicker/month-view.spec.ts
  src/lib/datepicker/year-view.spec.ts
  src/lib/dialog/dialog-ref.ts
  src/lib/dialog/dialog.ts
  src/lib/expansion/expansion-panel-header.ts
  src/lib/expansion/expansion-panel.ts
  src/lib/form-field/form-field.ts
  src/lib/icon/icon-registry.ts
  src/lib/menu/menu-directive.ts
  src/lib/paginator/paginator-intl.ts
  src/lib/select/select.spec.ts
  src/lib/snack-bar/snack-bar-container.ts
  src/lib/snack-bar/snack-bar-ref.ts
  src/lib/snack-bar/snack-bar.ts
  src/lib/sort/sort-header.ts
  src/lib/stepper/stepper.spec.ts
  src/lib/table/table-data-source.ts
  src/lib/table/table.spec.ts
  src/lib/tabs/ink-bar.ts
  src/lib/tabs/tab-group.ts
  src/lib/tabs/tab-header.ts
  src/lib/tabs/tab-nav-bar/tab-nav-bar.ts
  src/lib/tree/data-source/flat-data-source.ts
  src/lib/tree/data-source/nested-data-source.ts
  src/lib/tree/tree.spec.ts
  src/material-examples/autocomplete-auto-active-first-option/autocomplete-auto-active-first-option-example.ts
  src/material-examples/autocomplete-display/autocomplete-display-example.ts
  src/material-examples/autocomplete-filter/autocomplete-filter-example.ts
  src/material-examples/autocomplete-overview/autocomplete-overview-example.ts
  src/material-examples/cdk-table-basic/cdk-table-basic-example.ts
  src/material-examples/chips-autocomplete/chips-autocomplete-example.ts
  src/material-examples/datepicker-formats/datepicker-formats-example.ts
  src/material-examples/datepicker-moment/datepicker-moment-example.ts
  src/material-examples/datepicker-views-selection/datepicker-views-selection-example.ts
  src/material-examples/table-http/table-http-example.ts
  src/material-examples/tree-flat-overview/tree-flat-overview-example.ts
  src/material-examples/tree-nested-overview/tree-nested-overview-example.ts
  src/material-moment-adapter/adapter/moment-date-adapter.ts
  src/universal-app/kitchen-sink/kitchen-sink.ts
  tools/package-tools/metadata-inlining.ts
  tslint.json
Labels: cla: yes, pr: lgtm, pr: merge ready, release: patch

#10671 fix(tree): fix nested node cannot expand/collapse multiple times
  src/cdk/tree/nested-node.ts
  src/cdk/tree/tree.spec.ts
Labels: P1, cla: yes, pr: lgtm, pr: merge ready, release: major

#10662 fix(datepicker): close datepicker popup on alt + up arrow
  src/lib/datepicker/datepicker.spec.ts
  src/lib/datepicker/datepicker.ts
Labels: a11y, cla: yes, pr: lgtm, pr: merge ready, release: patch

#10661 fix(tabs): tab content portal not being cleaned up on destroy
  src/lib/tabs/tab-body.ts
Labels: cla: yes, pr: lgtm, pr: merge ready, release: patch

#10655 fix(slide-toggle): run timeout outside the NgZone
  src/lib/slide-toggle/slide-toggle.ts
Labels: cla: yes, pr: lgtm, pr: merge ready, release: patch

#10654 feat(coercion): add utility for coercing CSS values
  src/cdk/coercion/css-pixel-value.spec.ts
  src/cdk/coercion/css-pixel-value.ts
  src/cdk/coercion/public-api.ts
  src/cdk/overlay/overlay-ref.ts
  src/cdk/overlay/position/flexible-connected-position-strategy.ts
  src/cdk/overlay/scroll/block-scroll-strategy.ts
Labels: cla: yes, pr: lgtm, pr: merge ready, release: minor

#10650 fix(overlay): incorrect bottom offset using upward-flowing flexible position with a viewport margin
  src/cdk/overlay/position/flexible-connected-position-strategy.spec.ts
  src/cdk/overlay/position/flexible-connected-position-strategy.ts
Labels: cla: yes, pr: lgtm, pr: merge ready, release: patch

#10644 fix(stepper): horizontal stepper cutting off bottom part of content
  src/lib/stepper/stepper.scss
Labels: cla: yes, pr: lgtm, pr: merge ready, release: patch

#10633 fix(datepicker): export `MatCalendarHeader`
  src/lib/datepicker/datepicker-module.ts
Labels: cla: yes, pr: lgtm, pr: merge ready, release: patch

#10630 fix(badge): incorrectly handling rtl
  src/lib/badge/_badge-theme.scss
Labels: cla: yes, pr: lgtm, pr: merge ready, release: patch

#10629 fix(autocomplete): panel width not being updated on window resize
  src/lib/autocomplete/autocomplete-trigger.ts
  src/lib/autocomplete/autocomplete.spec.ts
Labels: cla: yes, pr: lgtm, pr: merge ready, release: patch

#10617 fix(table,sort,paginator): incorrect spacing in rtl
  src/lib/paginator/paginator.scss
  src/lib/sort/sort-header.scss
  src/lib/table/table.scss
Labels: cla: yes, pr: lgtm, pr: merge ready, release: minor

#10608 fix(focus-monitor): hitting ngzone when using focusVia
  src/cdk/a11y/focus-monitor/focus-monitor.ts
Labels: cla: yes, pr: lgtm, pr: merge ready, release: patch

#10605 fix(button-toggle): setting blank aria-label attribute by default
  src/lib/button-toggle/button-toggle.spec.ts
  src/lib/button-toggle/button-toggle.ts
Labels: cla: yes, pr: lgtm, pr: merge ready, release: patch

#10670 fix(form-field): run change detection when prefix or suffix changes
  src/lib/form-field/form-field.ts
Labels: cla: yes, pr: lgtm, pr: merge ready, release: patch

#10717 docs(readme): update angular material links
  README.md
Labels: cla: yes, pr: lgtm, pr: merge ready, pr: merge safe, release: patch

#10714 chore: bind devapp to 0.0.0.0
  tools/gulp/util/task_helpers.ts
Labels: cla: yes, pr: lgtm, pr: merge ready, pr: merge safe, release: patch

#10725 chore: bump version to 6.0.0-rc.1 w/ changelog
  CHANGELOG.md
  package.json
Labels: cla: yes, pr: lgtm, pr: merge ready, pr: merge safe, release: patch

#10502 docs: schematics
  guides/schematics.md
Labels: cla: yes, pr: lgtm, pr: merge ready, pr: merge safe, release: major

#10448 fix copy-paste error in demo-app
  src/demo-app/tree/checklist-tree-demo/checklist-nested-tree-demo.html
Labels: cla: yes, pr: lgtm, pr: merge ready, pr: merge safe

#10719 fix(form-field): server-side rendering error with outline appearance
  src/lib/form-field/form-field.ts
  src/universal-app/kitchen-sink/kitchen-sink.html
Labels: cla: yes, pr: lgtm, pr: merge ready, release: patch

#10583 refactor(input): run ios keyup event outside the ngzone
  src/lib/input/input.ts
Labels: cla: yes, pr: lgtm, pr: merge ready, release: patch

#10561 fix(table): MatTableDataSource incorrectly sorting zero
  src/lib/table/table-data-source.ts
  src/lib/table/table.spec.ts
Labels: cla: yes, pr: lgtm, pr: merge ready, release: minor

#10515 fix(datepicker): avoid accidental form submissions through calendar buttons
  src/lib/datepicker/calendar-header.html
  src/lib/datepicker/calendar.spec.ts
Labels: cla: yes, pr: lgtm, pr: merge ready, release: patch

#10747 chore: fix test failure due to changed label
  src/lib/table/table.spec.ts
Labels: cla: yes, pr: lgtm, pr: merge ready, pr: merge safe, release: patch

#10687 build(bazel): add version stamping
  WORKSPACE
  package-lock.json
  package.json
  src/lib/BUILD.bazel
  tools/bazel-stamp-vars.sh
  tools/bazel.rc
Labels: cla: yes, pr: lgtm, pr: merge ready, pr: merge safe, release: patch

#10739 chore(examples): minor fixes
  src/material-examples/chips-autocomplete/chips-autocomplete-example.html
  src/material-examples/sidenav-open-close/sidenav-open-close-example.ts
  src/material-examples/table-basic/table-basic-example.css
  src/material-examples/table-filtering/table-filtering-example.css
  src/material-examples/table-http/table-http-example.css
  src/material-examples/table-overview/table-overview-example.css
  src/material-examples/table-pagination/table-pagination-example.css
  src/material-examples/table-selection/table-selection-example.css
  src/material-examples/table-sorting/table-sorting-example.css
Labels: cla: yes, pr: lgtm, pr: merge ready, pr: merge safe, release: patch

#10775 refactor: avoid casting document to any in constructor
  src/cdk-experimental/dialog/dialog-container.ts
  src/cdk/a11y/aria-describer/aria-describer.ts
  src/cdk/a11y/focus-trap/focus-trap.ts
  src/cdk/a11y/live-announcer/live-announcer.ts
  src/cdk/overlay/keyboard/overlay-keyboard-dispatcher.ts
  src/cdk/overlay/overlay-container.ts
  src/cdk/overlay/overlay.ts
  src/cdk/overlay/position/overlay-position-builder.ts
  src/cdk/overlay/scroll/block-scroll-strategy.ts
  src/cdk/overlay/scroll/scroll-strategy-options.ts
  src/lib/autocomplete/autocomplete-trigger.ts
  src/lib/badge/badge.ts
  src/lib/bottom-sheet/bottom-sheet-container.ts
  src/lib/datepicker/datepicker.ts
  src/lib/dialog/dialog-container.ts
  src/lib/icon/icon-registry.ts
  src/lib/menu/menu-content.ts
  src/lib/progress-spinner/progress-spinner.ts
Labels: P1, cla: yes, pr: lgtm, pr: merge ready, release: patch

#10765 chore: remove noRxjsPatchImportsRule
  CODING_STANDARDS.md
  tools/tslint-rules/noRxjsPatchImportsRule.ts
  tslint.json
Labels: cla: yes, pr: lgtm, pr: merge ready, pr: merge safe, release: patch

#10790 chore: bump remaining 6.0.0 deletion targets to 7.0.0
  src/lib/menu/menu-directive.ts
  src/lib/menu/menu-item.ts
  src/lib/menu/menu-trigger.ts
Labels: cla: yes, pr: lgtm, pr: merge ready, pr: merge safe, release: patch

#10659 fix(platform): change isBrowser check to use Angular PLATFORM_ID
  src/cdk/a11y/focus-trap/focus-trap.spec.ts
  src/cdk/a11y/interactivity-checker/interactivity-checker.spec.ts
  src/cdk/overlay/scroll/block-scroll-strategy.spec.ts
  src/cdk/platform/platform.ts
  src/lib/core/datetime/native-date-adapter.spec.ts
Labels: P1, cla: yes, pr: lgtm, pr: merge ready, release: patch

#10740 refactor(tree): use destroy cleanup logic from base class
  src/cdk/tree/nested-node.ts
Labels: cla: yes, pr: lgtm, pr: merge ready, release: major

#10341 fix(stepper): header icon collapsing with very long labels
  src/lib/stepper/step-header.scss
Labels: cla: yes, pr: lgtm, pr: merge ready, release: patch

#10793 refactor(slider): improve unit test speed
  src/lib/slider/slider.spec.ts
Labels: cla: yes, pr: lgtm, pr: merge ready, pr: merge safe

#10788 build(bazel): add flatModuleIndexRedirect to material package
  package-lock.json
  scripts/bazel/update-material-metadata-reexports.js
Labels: cla: yes, pr: lgtm, pr: merge ready, pr: merge safe

#10777 fix(datepicker): reformat valid values on blur
  src/lib/datepicker/datepicker-input.ts
  src/lib/datepicker/datepicker.spec.ts
Labels: cla: yes, pr: lgtm, pr: merge ready, release: minor

#10764 refactor(tree): ensure input is applied to the getter and not the setter
  src/cdk/tree/padding.ts
  src/cdk/tree/tree.spec.ts
  src/lib/tree/tree.spec.ts
Labels: cla: yes, pr: lgtm, pr: merge ready, release: major

#10763 refactor: remove duplicate types and correct some TODOs
  src/cdk/table/table.ts
  src/lib/icon/icon-registry.ts
  src/lib/menu/menu-trigger.ts
Labels: cla: yes, pr: lgtm, pr: merge ready, release: patch

#10761 chore(calendar): remove explicit preserveWhitespaces setting
  src/lib/datepicker/calendar.ts
  tslint.json
Labels: cla: yes, pr: lgtm, pr: merge ready, release: patch

#10355 fix(datepicker): nested animation not working
  src/lib/datepicker/datepicker-animations.ts
Labels: cla: yes, pr: lgtm, pr: merge ready, release: patch

#10737 fix(theme): apply base theme classes at location the theme is included
  src/lib/core/_core.scss
Labels: cla: yes, pr: lgtm, pr: merge ready, release: patch

#9701 fix(tabs): hide mat-tab-nav-bar ink bar when no link is active
  src/lib/tabs/tab-nav-bar/tab-nav-bar.spec.ts
  src/lib/tabs/tab-nav-bar/tab-nav-bar.ts
Labels: cla: yes, pr: lgtm, pr: merge ready, release: patch

#10806 build: fix sass compilation error
  src/lib/core/_core.scss
Labels: P1, cla: yes, pr: lgtm, pr: merge ready, release: patch

#10736 cleanup: migrate migration tool to schematics
  BUILD.bazel
  package-lock.json
  package.json
  src/lib/schematics/BUILD.bazel
  src/lib/schematics/collection.json
  src/lib/schematics/update/material/color.ts
  src/lib/schematics/update/material/component-data.ts
  src/lib/schematics/update/material/data/attribute-selectors.json
  src/lib/schematics/update/material/data/class-names.json
  src/lib/schematics/update/material/data/css-names.json
  src/lib/schematics/update/material/data/element-selectors.json
  src/lib/schematics/update/material/data/export-as-names.json
  src/lib/schematics/update/material/data/input-names.json
  src/lib/schematics/update/material/data/method-call-checks.json
  src/lib/schematics/update/material/data/output-names.json
  src/lib/schematics/update/material/data/property-names.json
  src/lib/schematics/update/material/extra-stylsheets.ts
  src/lib/schematics/update/material/typescript-specifiers.ts
  src/lib/schematics/update/rules/checkClassDeclarationMiscRule.ts
  src/lib/schematics/update/rules/checkIdentifierMiscRule.ts
  src/lib/schematics/update/rules/checkImportMiscRule.ts
  src/lib/schematics/update/rules/checkInheritanceRule.ts
  src/lib/schematics/update/rules/checkMethodCallsRule.ts
  src/lib/schematics/update/rules/checkPropertyAccessMiscRule.ts
  src/lib/schematics/update/rules/checkTemplateMiscRule.ts
  src/lib/schematics/update/rules/switchIdentifiersRule.ts
  src/lib/schematics/update/rules/switchPropertyNamesRule.ts
  src/lib/schematics/update/rules/switchStringLiteralAttributeSelectorsRule.ts
  src/lib/schematics/update/rules/switchStringLiteralCssNamesRule.ts
  src/lib/schematics/update/rules/switchStringLiteralElementSelectorsRule.ts
  src/lib/schematics/update/rules/switchStylesheetAttributeSelectorsRule.ts
  src/lib/schematics/update/rules/switchStylesheetCssNamesRule.ts
  src/lib/schematics/update/rules/switchStylesheetElementSelectorsRule.ts
  src/lib/schematics/update/rules/switchStylesheetInputNamesRule.ts
  src/lib/schematics/update/rules/switchStylesheetOutputNamesRule.ts
  src/lib/schematics/update/rules/switchTemplateAttributeSelectorsRule.ts
  src/lib/schematics/update/rules/switchTemplateCssNamesRule.ts
  src/lib/schematics/update/rules/switchTemplateElementSelectorsRule.ts
  src/lib/schematics/update/rules/switchTemplateExportAsNamesRule.ts
  src/lib/schematics/update/rules/switchTemplateInputNamesRule.ts
  src/lib/schematics/update/rules/switchTemplateOutputNamesRule.ts
  src/lib/schematics/update/tslint/component-file.ts
  src/lib/schematics/update/tslint/component-walker.ts
  src/lib/schematics/update/tslint/find-tslint-binary.ts
  src/lib/schematics/update/typescript/identifiers.ts
  src/lib/schematics/update/typescript/imports.ts
  src/lib/schematics/update/typescript/literal.ts
  src/lib/schematics/update/update.ts
  tools/gulp/tasks/material-release.ts
Labels: cla: yes, pr: lgtm, pr: merge ready, pr: merge safe, release: patch

#10810 chore: bump version to 6.0.0-rc.2 w/ changelog
  CHANGELOG.md
  package-lock.json
  package.json
Labels: cla: yes, pr: lgtm, pr: merge ready, pr: merge safe, release: patch

#10707 fix(button-toggle): selected value not being maintained when changing value while toggles are being swapped out
  src/lib/button-toggle/button-toggle.spec.ts
  src/lib/button-toggle/button-toggle.ts
Labels: P1, cla: yes, pr: lgtm, pr: merge ready, release: patch

#10816 build: mark material and cdk packages as sideEffect-free for webpack v4
  src/cdk/package.json
  src/lib/package.json
  tools/package-tools/entry-point-package-json.ts
Labels: P1, cla: yes, pr: lgtm, pr: merge ready, pr: merge safe

#10824 Revert "refactor: avoid casting document to any in constructor (#10775)"
  src/cdk-experimental/dialog/dialog-container.ts
  src/cdk/a11y/aria-describer/aria-describer.ts
  src/cdk/a11y/focus-trap/focus-trap.ts
  src/cdk/a11y/live-announcer/live-announcer.ts
  src/cdk/overlay/keyboard/overlay-keyboard-dispatcher.ts
  src/cdk/overlay/overlay-container.ts
  src/cdk/overlay/overlay.ts
  src/cdk/overlay/position/overlay-position-builder.ts
  src/cdk/overlay/scroll/block-scroll-strategy.ts
  src/cdk/overlay/scroll/scroll-strategy-options.ts
  src/lib/autocomplete/autocomplete-trigger.ts
  src/lib/badge/badge.ts
  src/lib/bottom-sheet/bottom-sheet-container.ts
  src/lib/datepicker/datepicker.ts
  src/lib/dialog/dialog-container.ts
  src/lib/icon/icon-registry.ts
  src/lib/menu/menu-content.ts
  src/lib/progress-spinner/progress-spinner.ts
Labels: P1, cla: yes, pr: lgtm, pr: merge ready

#10809 chore: update readme for Q2 2018
  README.md
Labels: cla: yes, docs, pr: lgtm, pr: merge ready, pr: merge safe, release: patch

#10343 refactor(tabs): provide method for re-aligning the ink bar
  src/lib/tabs/tab-group.ts
  src/lib/tabs/tab-header.ts
Labels: cla: yes, pr: lgtm, pr: merge ready, release: minor

#10729 fix(focus-monitor): server-side rendering error when using focusVia
  src/cdk/a11y/focus-monitor/focus-monitor.ts
  src/universal-app/kitchen-sink/kitchen-sink.ts
Labels: cla: yes, pr: lgtm, pr: merge ready, release: patch

#10753 fix(radio): checked radio button indistinguishable in high contrast mode
  src/lib/radio/radio.scss
Labels: cla: yes, pr: lgtm, pr: merge ready, release: patch

#10829 chore: bump the version to 6.0.0-rc.3 w/ changelog
  CHANGELOG.md
  package-lock.json
  package.json
Labels: cla: yes, pr: lgtm, pr: merge ready, pr: merge safe

#10844 fix(schematics): add ng-update config to package.json
  WORKSPACE
  package-lock.json
  package.json
  src/lib/package.json
  src/lib/schematics/migration.json
Labels: cla: yes, pr: lgtm, pr: merge ready, pr: merge safe, release: patch

#10779 doc(autocomplete-filter): Update example to use Array.prototype.Inclu…
  src/material-examples/autocomplete-filter/autocomplete-filter-example.ts
Labels: cla: yes, pr: lgtm, pr: merge ready, pr: merge safe

#10845 chore: remove circleci and travisci webooks for caretaker.
  .circleci/config.yml
  .travis.yml
Labels: cla: yes, pr: lgtm, pr: merge ready, pr: merge safe

#10580 fix(button-toggle): focus monitoring not being cleaned up on destroy
  src/lib/button-toggle/button-toggle.ts
Labels: cla: yes, pr: lgtm, pr: merge ready, release: patch

#10846 chore: changelog for 6.0.0-rc.4
  CHANGELOG.md
Labels: cla: yes, docs, pr: lgtm, pr: merge ready, pr: merge safe

#10850 fix(schematics): correct path to ng-update entry-point
  src/lib/package.json
Labels: cla: yes, pr: lgtm, pr: merge ready, pr: merge safe

#10789 fix(breakpoint-observer): split comma separated queries into separte queries
  src/cdk/layout/breakpoints-observer.spec.ts
  src/cdk/layout/breakpoints-observer.ts
Labels: cla: yes, pr: lgtm, pr: merge ready, release: patch

#7619 fix(select): open method triggered twice on click
  src/lib/select/select.ts
Labels: cla: yes, pr: lgtm, pr: merge ready, release: patch

#10876 chore: update to angular core rc.5
  package-lock.json
  package.json
Labels: cla: yes, pr: lgtm, pr: merge ready, pr: merge safe, release: patch

#10853 fix(schematics): make v6 migration work
  CHANGELOG.md
  package.json
  src/cdk/package.json
  src/lib/package.json
  src/lib/schematics/BUILD.bazel
  src/lib/schematics/collection.json
  src/lib/schematics/migration.json
  src/lib/schematics/update/update.ts
  src/material-moment-adapter/package.json
  tools/gulp/tasks/material-release.ts
Labels: cla: yes, pr: lgtm, pr: merge ready, pr: merge safe, release: patch

#10840 chore: set up angular-robot for repo
  .github/angular-robot.yaml
Labels: cla: yes, pr: lgtm, pr: merge ready, pr: merge safe, release: patch

#10363 fix(datepicker): high contrast accessibility improvements
  src/lib/datepicker/calendar-body.scss
Labels: a11y, cla: yes, pr: lgtm, pr: merge ready, release: patch

#10883 fix(schematics): ignore e2e projects w/ `ng add`
  src/lib/schematics/utils/devkit-utils/config.ts
Labels: cla: yes, pr: lgtm, pr: merge ready, pr: merge safe, release: patch

#10837 fix(menu): svg icons not aligned inside menu item
  src/lib/core/style/_menu-common.scss
Labels: cla: yes, pr: lgtm, pr: merge ready, release: patch

#10826 fix(directionality): complete change event on destroy
  src/cdk/bidi/directionality.spec.ts
  src/cdk/bidi/directionality.ts
Labels: cla: yes, pr: lgtm, pr: merge ready, release: patch

#10879 fix(tree): make toggle non-recursive by default
  src/cdk/tree/toggle.ts
  src/lib/tree/toggle.ts
Labels: P1, cla: yes, pr: lgtm, pr: merge ready, release: patch

#10866 refactor: remove usages of deprecated rxjs apis
  src/cdk/layout/breakpoints-observer.ts
  src/cdk/table/BUILD.bazel
  src/cdk/table/table.spec.ts
  src/cdk/text-field/autofill.spec.ts
  src/cdk/text-field/autofill.ts
  src/lib/table/table-data-source.ts
Labels: cla: yes, pr: lgtm, pr: merge ready, release: patch

#10828 fix(selection-list): toggle newly-focused item when pressing arrow key + shift
  src/lib/list/selection-list.spec.ts
  src/lib/list/selection-list.ts
Labels: cla: yes, pr: lgtm, pr: merge ready, release: patch

#10822 fix(table): Allow any Iterable or ArrayLike to be used for `columns`
  src/cdk/table/row.ts
  src/cdk/table/table.ts
Labels: cla: yes, pr: lgtm, pr: merge ready, release: patch

#10742 refactor(icon): id attribute not being cleared completely
  src/lib/icon/icon-registry.ts
  src/lib/icon/icon.spec.ts
Labels: cla: yes, pr: lgtm, pr: merge ready, release: patch

#10893 chore(paginator): add paginator demo
  .github/CODEOWNERS
  src/demo-app/demo-app/demo-app.ts
  src/demo-app/demo-app/demo-module.ts
  src/demo-app/demo-app/routes.ts
  src/demo-app/paginator/paginator-demo.html
  src/demo-app/paginator/paginator-demo.scss
  src/demo-app/paginator/paginator-demo.ts
Labels: cla: yes

#10899 chore: Allow Angular v5 or v6 as peer dep
  build-config.js
Labels: P1, cla: yes, pr: merge safe, pr: needs review

#10901 chore: update changelog for 5.2.5
  CHANGELOG.md
  package-lock.json
  package.json
Labels: cla: yes, pr: lgtm, pr: merge ready, pr: merge safe

#10902 chore: update changelog for 6.0.0-rc.12
  CHANGELOG.md
  package-lock.json
  package.json
Labels: cla: yes, pr: lgtm, pr: merge ready, pr: merge safe

#10891 feat(cdk/keycodes): add missing keycodes
  src/cdk/keycodes/keycodes.ts
Labels: cla: yes, pr: lgtm, pr: merge ready, release: minor

#10858 fix(accordion): complete accordion item emitters on destroy
  src/cdk/accordion/accordion-item.spec.ts
  src/cdk/accordion/accordion-item.ts
Labels: cla: yes, pr: lgtm, pr: merge ready, release: patch

#10852 chore(overlay): export ConnectedPosition interface
  src/cdk/overlay/public-api.ts
Labels: G, cla: yes, pr: lgtm, pr: merge ready, release: patch

#10666 docs(autocomplete): Adds option group example
  src/lib/autocomplete/autocomplete.md
  src/material-examples/autocomplete-optgroup/autocomplete-optgroup-example.css
  src/material-examples/autocomplete-optgroup/autocomplete-optgroup-example.html
  src/material-examples/autocomplete-optgroup/autocomplete-optgroup-example.ts
Labels: cla: yes, pr: lgtm, pr: merge ready, release: patch

#10369 fix(tab): add flex-basis hack for IE11
  src/lib/tabs/tab-group.scss
Labels: cla: yes, pr: lgtm, pr: merge ready, release: patch

#10315 fix(radio): radios aren't checkable when the value is falsy
  src/lib/radio/radio.ts
Labels: cla: yes, pr: lgtm, pr: merge ready, release: patch

#10773 fix(overlay): handle OnDestroy in FullscreenOverlayContainer and use document injection token
  src/cdk/overlay/fullscreen-overlay-container.ts
  src/cdk/overlay/overlay-container.ts
Labels: cla: yes, pr: lgtm, pr: merge ready, release: patch

#10889 fix(select,autocomplete): mat-option theme not being applied correctly when nested inside a selector
  src/lib/core/option/_option-theme.scss
Labels: cla: yes, pr: lgtm, pr: merge ready, release: patch

#10619 fix(sort): arrow not centered vertically inside multiline headers
  src/lib/sort/sort-header.scss
Labels: cla: yes, pr: lgtm, pr: merge ready, release: minor

#10904 fix(datepicker): producing wrong selector for disabled dates for themes inside a selector
  src/lib/datepicker/_datepicker-theme.scss
Labels: cla: yes, pr: lgtm, pr: merge ready, release: patch

#10593 fix(table): data source can listen for init from sort, page
  src/demo-app/table/custom-table/custom-table.ts
  src/demo-app/table/table-demo.ts
  src/lib/paginator/paginator.spec.ts
  src/lib/paginator/paginator.ts
  src/lib/sort/sort.spec.ts
  src/lib/sort/sort.ts
  src/lib/table/table-data-source.ts
  src/lib/table/table.spec.ts
  src/material-examples/table-overview/table-overview-example.ts
  src/material-examples/table-pagination/table-pagination-example.ts
  src/material-examples/table-sorting/table-sorting-example.ts
Labels: cla: yes, pr: lgtm, pr: merge ready, release: patch

#10531 feat(overlay): allow multiple classes to be assigned to the backdrop
  src/cdk/overlay/overlay-config.ts
  src/cdk/overlay/overlay-ref.ts
  src/cdk/overlay/overlay.spec.ts
Labels: cla: yes, pr: lgtm, pr: merge ready, release: minor

#10501 feat(selection-list): add support for compareWith function
  src/lib/list/selection-list.spec.ts
  src/lib/list/selection-list.ts
Labels: cla: yes, pr: lgtm, pr: merge ready, release: minor

#10487 fix(bottom-sheet): server-side rendering error when opened
  src/lib/bottom-sheet/bottom-sheet-container.ts
  src/universal-app/kitchen-sink/kitchen-sink.ts
Labels: cla: yes, pr: lgtm, pr: merge ready, release: patch

#10465 fix(toolbar): improved high contrast accessibility
  src/lib/toolbar/toolbar.scss
Labels: a11y, cla: yes, pr: lgtm, pr: merge ready, release: patch

#10403 fix(text-field): autosize textarea not scrolling to end of input on firefox
  src/cdk/text-field/autosize.ts
Labels: cla: yes, pr: lgtm, pr: merge ready, release: patch

#10856 fix(datepicker): allow MatCalendarHeader to be re-used inside a custom header
  src/lib/datepicker/calendar.ts
  src/lib/datepicker/datepicker.spec.ts
  tools/package-tools/rollup-globals.ts
Labels: cla: yes, pr: lgtm, pr: merge ready, release: patch

#10486 fix(overlay): clear element reference on destroy
  src/cdk/overlay/overlay-ref.ts
  src/cdk/overlay/overlay.spec.ts
  src/cdk/overlay/position/connected-position-strategy.spec.ts
  src/cdk/overlay/position/flexible-connected-position-strategy.spec.ts
  src/cdk/overlay/position/global-position-strategy.spec.ts
Labels: cla: yes, pr: lgtm, pr: merge ready, release: patch

#10396 fix(menu): not closing sibling sub-menus when hovering over disabled items
  src/lib/menu/_menu-theme.scss
  src/lib/menu/menu-item.ts
  src/lib/menu/menu-trigger.ts
  src/lib/menu/menu.spec.ts
Labels: cla: yes, pr: lgtm, pr: merge ready, release: patch

#10943 fix(form-field): make outline appearance work in situations where the…
  src/demo-app/input/input-demo.html
  src/lib/form-field/form-field.ts
Labels: G, P1, cla: yes, pr: lgtm, pr: merge ready

#10330 feat(table): add optional footer row
  src/cdk/table/cell.ts
  src/cdk/table/row.ts
  src/cdk/table/table-module.ts
  src/cdk/table/table.md
  src/cdk/table/table.spec.ts
  src/cdk/table/table.ts
  src/demo-app/table/table-demo.html
  src/lib/table/_table-theme.scss
  src/lib/table/cell.ts
  src/lib/table/row.ts
  src/lib/table/table-module.ts
  src/lib/table/table.md
  src/lib/table/table.scss
  src/lib/table/table.spec.ts
  src/material-examples/table-footer-row/table-footer-row-example.css
  src/material-examples/table-footer-row/table-footer-row-example.html
  src/material-examples/table-footer-row/table-footer-row-example.ts
Labels: cla: yes, pr: lgtm, pr: merge ready, release: minor

#10464 refactor(overlay): move connected position assertions into FlexibleConnectedPositionStrategy
  src/cdk/overlay/position/connected-position-strategy.spec.ts
  src/cdk/overlay/position/connected-position-strategy.ts
  src/cdk/overlay/position/flexible-connected-position-strategy.spec.ts
  src/cdk/overlay/position/flexible-connected-position-strategy.ts
Labels: cla: yes, pr: lgtm, pr: merge ready, release: patch

#10982 build(table): explicitly define MatTable ctor
  src/cdk/table/table.ts
  src/lib/table/table.ts
Labels: P1, cla: yes, pr: lgtm, pr: merge ready, release: patch

#11011 ci: fix github bot config file extension
  .github/angular-robot.yml
Labels: cla: yes, pr: lgtm, pr: merge ready, pr: merge safe, release: patch

#11010 fix(schematics): include 6.0.0 RC releases for migrations
  src/lib/schematics/migration.json
Labels: P1, cla: yes, pr: merge safe, pr: needs review, release: patch

#10999 fix(overlay): wrong import path in distributed overlay styles
  src/cdk/overlay/_overlay.scss
Labels: P1, cla: yes, pr: lgtm, pr: merge ready, release: patch

#10989 fix(schematics): support basic style asset string
  src/lib/schematics/shell/theming.ts
Labels: P1, cla: yes, pr: needs review

#11016 feat(accordion): allow intermediate elements between accordion and expansion panel
  src/lib/expansion/expansion-panel.scss
Labels: G, cla: yes, pr: lgtm, pr: merge ready, release: minor

#11015 fix(tree): add theme to angular-material-theme mixin
  src/lib/core/theming/_all-theme.scss
  src/lib/core/typography/_all-typography.scss
Labels: P1, cla: yes, pr: lgtm, pr: merge ready, release: patch

#11000 fix(menu): set proper focus origin when the user starts using the keyboard after opening with the mouse
  src/lib/menu/menu-directive.ts
  src/lib/menu/menu.spec.ts
Labels: a11y, cla: yes, pr: lgtm, pr: merge ready, release: patch

#10985 feat(tree): add level to tree node context
  src/cdk/tree/nested-node.ts
  src/cdk/tree/node.ts
  src/cdk/tree/tree.spec.ts
  src/cdk/tree/tree.ts
Labels: cla: yes, pr: lgtm, pr: merge ready, release: minor

#10976 fix(ripple): only persist top ripple on pointer down
  src/lib/core/ripple/ripple-renderer.ts
  src/lib/core/ripple/ripple.spec.ts
Labels: cla: yes, pr: lgtm, pr: merge ready, release: patch

#10975 fix(overlay): unable to use overlay provider during app initialization
  src/cdk/overlay/overlay.spec.ts
  src/cdk/overlay/overlay.ts
Labels: cla: yes, pr: lgtm, pr: merge ready, release: patch

#10960 fix(datepicker): calendar stateChanges not being completed
  src/lib/datepicker/calendar.spec.ts
  src/lib/datepicker/calendar.ts
Labels: cla: yes, pr: lgtm, pr: merge ready, release: patch

#10959 fix(slider): truncate long decimal values
  src/lib/slider/slider.spec.ts
  src/lib/slider/slider.ts
Labels: cla: yes, pr: lgtm, pr: merge ready, release: patch

#10956 fix(form-field): inconsistent border width across outline gap in Chrome
  src/lib/form-field/form-field-outline.scss
Labels: cla: yes, pr: lgtm, pr: merge ready, release: patch

#10945 refactor(slide-toggle): remove SlideToggleRenderer
  src/lib/slide-toggle/slide-toggle.html
  src/lib/slide-toggle/slide-toggle.ts
Labels: cla: yes, pr: lgtm, pr: merge ready, release: patch

#10940 refactor(tabs): expose _activeLinkChanged and _activeLinkElement as protected properties
  src/lib/tabs/tab-nav-bar/tab-nav-bar.ts
Labels: cla: yes, pr: lgtm, pr: merge ready, release: patch

#10935 fix(tree): remove invalid aria attribute
  src/cdk/tree/tree.ts
  src/lib/tree/node.ts
Labels: cla: yes, pr: lgtm, pr: merge ready, release: patch

#10933 feat(sidenav): allow for auto focusing to be disabled
  src/lib/sidenav/drawer.spec.ts
  src/lib/sidenav/drawer.ts
Labels: cla: yes, pr: lgtm, pr: merge ready, release: minor

#10855 fix(chips): unable to bind to chip input placeholder
  src/lib/chips/chip-input.spec.ts
  src/lib/chips/chip-input.ts
Labels: cla: yes, pr: lgtm, pr: merge ready, release: patch

#10842 docs(overlay): mention the FlexibleConnectedPositionStrategy in the overlay guide
  src/cdk/overlay/overlay.md
Labels: P1, cla: yes, docs, pr: lgtm, pr: merge ready, pr: merge safe, release: patch

#10643 fix(tabs): tab-nav-link disableRipple input not working
  src/lib/tabs/tab-nav-bar/tab-nav-bar.spec.ts
  src/lib/tabs/tab-nav-bar/tab-nav-bar.ts
Labels: cla: yes, pr: lgtm, pr: merge ready, release: patch

#11017 Revert "chore(demo): add examples to demo app"
  .github/CODEOWNERS
  package-lock.json
  package.json
  src/demo-app/demo-app/demo-app.ts
  src/demo-app/demo-app/demo-module.ts
  src/demo-app/demo-app/routes.ts
  src/demo-app/example/example-list.ts
  src/demo-app/example/example-module.ts
  src/demo-app/example/example.ts
  src/demo-app/examples-page/examples-page.ts
  src/demo-app/index.html
  src/demo-app/system-config.ts
  src/demo-app/tsconfig-build.json
  src/material-examples/tsconfig-tests.json
  tools/gulp/tasks/development.ts
Labels: cla: yes

#10348 docs(icon): Add docs for inline icon
  src/demo-app/icon/icon-demo.html
  src/lib/icon/icon.md
Labels: cla: yes, pr: lgtm, pr: merge ready, pr: merge safe

#11008 docs(sidenav): make the sidenav easier to see in overview example
  src/material-examples/sidenav-overview/sidenav-overview-example.css
Labels: cla: yes, pr: lgtm, pr: merge ready, pr: merge safe, release: patch

#11005 chore(tree): invert arrow direction in demo app and examples
  src/demo-app/tree/checklist-tree-demo/checklist-nested-tree-demo.html
  src/demo-app/tree/checklist-tree-demo/checklist-tree-demo.html
  src/demo-app/tree/dynamic-tree-demo/dynamic-tree-demo.html
  src/demo-app/tree/loadmore-tree-demo/loadmore-tree-demo.html
  src/demo-app/tree/tree-demo.html
  src/material-examples/cdk-tree-flat/cdk-tree-flat-example.html
  src/material-examples/cdk-tree-nested/cdk-tree-nested-example.html
  src/material-examples/tree-checklist/tree-checklist-example.html
  src/material-examples/tree-dynamic/tree-dynamic-example.html
  src/material-examples/tree-flat-overview/tree-flat-overview-example.html
  src/material-examples/tree-loadmore/tree-loadmore-example.html
  src/material-examples/tree-nested-overview/tree-nested-overview-example.html
Labels: cla: yes, pr: lgtm, pr: merge ready, pr: merge safe

#10981 chore: use dot reporter in karma
  test/karma.conf.js
Labels: cla: yes, pr: lgtm, pr: merge ready, pr: merge safe, release: patch

#10949 build: add stylelint rule to validate ampersands in theme selectors
  stylelint-config.json
  tools/stylelint/no-ampersand-beyond-selector-start/index.js
  tools/stylelint/selector-nested-pattern-scoped/index.js
Labels: cla: yes, pr: lgtm, pr: merge ready, pr: merge safe

#10947 fix(examples): add missing module imports and exports
  src/material-examples/material-module.ts
Labels: cla: yes, docs, pr: lgtm, pr: merge ready, pr: merge safe

#10921 chore(table): change schematics to use native table
  src/lib/schematics/table/files/__path__/__name@dasherize@if-flat__/__name@dasherize__.component.ts
Labels: cla: yes, pr: lgtm, pr: merge ready, pr: merge safe, release: minor

#10762 chore: remove unnecessary information in code_reviews
  CODE_REVIEWS.md
Labels: cla: yes, pr: lgtm, pr: merge ready, pr: merge safe

#11002 build: bump to rxjs 6.0 final
  package-lock.json
  package.json
Labels: cla: yes, pr: lgtm, pr: merge ready, pr: merge safe

#11032 chore: update angular robot labels and required statuses
  .github/angular-robot.yml
Labels: cla: yes, pr: lgtm, pr: merge ready, pr: merge safe, target: master only

#11035 chore: bump to rc.13
  CHANGELOG.md
  package-lock.json
  package.json
Labels: cla: yes, pr: lgtm, pr: merge ready, pr: merge safe, target: master only

#11012 docs(snack-bar): expand a11y guidance
  src/lib/snack-bar/snack-bar.md
Labels: a11y, cla: yes, docs, pr: lgtm, pr: merge ready, pr: merge safe, target: patch

#11026 build: fix e2e setup error
  src/e2e-app/system-config.ts
Labels: cla: yes, pr: lgtm, pr: merge ready, pr: merge safe, target: master only

#11028 fix(card): flat card selector not working
  src/lib/card/card.scss
Labels: cla: yes, pr: lgtm, pr: merge ready, target: patch

#10988 virtual-scroll: address amcdnl's feedback
  src/cdk-experimental/scrolling/auto-size-virtual-scroll.ts
  src/cdk-experimental/scrolling/fixed-size-virtual-scroll.ts
  src/cdk-experimental/scrolling/virtual-for-of.ts
  src/demo-app/virtual-scroll/virtual-scroll-demo.html
  src/demo-app/virtual-scroll/virtual-scroll-demo.ts
Labels: cla: yes, pr: lgtm, pr: merge ready, pr: merge safe

#11048 fix(ci): Shard tests on CI across 3 browsers
  package-lock.json
  package.json
  test/karma.conf.js
Labels: cla: yes, pr: lgtm, pr: merge ready, pr: merge safe, target: master only

#11057 build: bump to angular 6.0.0-rc.6
  package.json
Labels: cla: yes, pr: lgtm, pr: merge ready, pr: merge safe, target: master only

#10807 fix(overlay): always dispatch keyboard events to top overlay in OverlayKeyboardDispatcher
  src/cdk/overlay/keyboard/overlay-keyboard-dispatcher.spec.ts
  src/cdk/overlay/keyboard/overlay-keyboard-dispatcher.ts
Labels: cla: yes, pr: lgtm, pr: merge ready, target: patch

#11034 docs(table): fix typo
  src/cdk/table/table.md
Labels: cla: yes, pr: lgtm, pr: merge ready, pr: merge safe, target: minor

#11018 chore(demo): add examples to demo app
  .github/CODEOWNERS
  package.json
  src/demo-app/demo-app/demo-app.ts
  src/demo-app/demo-app/demo-module.ts
  src/demo-app/demo-app/routes.ts
  src/demo-app/example/example-list.ts
  src/demo-app/example/example-module.ts
  src/demo-app/example/example.ts
  src/demo-app/examples-page/examples-page.ts
  src/demo-app/index.html
  src/demo-app/system-config.ts
  src/demo-app/tsconfig-aot.json
  src/demo-app/tsconfig-build.json
  src/demo-app/tsconfig.json
  src/material-examples/tsconfig-tests.json
  tools/gulp/tasks/aot.ts
  tools/gulp/tasks/development.ts
Labels: cla: yes, pr: lgtm, pr: merge ready, pr: merge safe, target: master only

#11036 chore: suppress tsconfig override warnings in bazel builds
  src/cdk-experimental/tsconfig-build.json
  src/cdk/tsconfig-build.json
  src/lib/tsconfig-build.json
  src/material-experimental/tsconfig-build.json
  src/material-moment-adapter/tsconfig-build.json
Labels: cla: yes, pr: lgtm, pr: merge ready, pr: merge safe, target: master only

#11037 docs(form-field): update documentation regarding label and placeholder
  src/lib/form-field/form-field.html
  src/lib/form-field/form-field.md
  src/lib/form-field/placeholder.ts
  src/lib/input/input.md
  src/lib/select/select.md
  src/material-examples/form-field-label/form-field-label-example.html
Labels: cla: yes, pr: lgtm, pr: merge ready, pr: merge safe, target: patch

#11058 fix(schematics): allow more tsconfig locations for ng update
  src/lib/schematics/update/update.ts
Labels: P1, cla: yes, pr: lgtm, pr: merge ready, pr: merge safe, target: patch

#11081 chore: bump to 6.0.0-rc.14
  CHANGELOG.md
  package-lock.json
  package.json
Labels: cla: yes, pr: lgtm, pr: merge ready, pr: merge safe, target: master only
