Repository angular/components, pull requests merged in 2018-10, with the labels that each got.

#13376 build: fix e2e rate limit failures
  src/e2e-app/tsconfig-build.json
  tools/gulp/tasks/e2e.ts
  tools/gulp/util/task_helpers.ts
Labels: cla: yes, pr: lgtm, pr: merge ready, pr: merge safe, target: patch

#13311 fix(slide-toggle): clear tabindex from host element
  src/lib/slide-toggle/slide-toggle.spec.ts
  src/lib/slide-toggle/slide-toggle.ts
Labels: cla: yes, pr: lgtm, pr: merge ready, target: patch

#13249 fix(chips): set aria-invalid on chip input
  src/lib/chips/chip-input.ts
  src/lib/chips/chip-list.spec.ts
Labels: cla: yes, pr: lgtm, pr: merge ready, target: patch

#13228 fix(select): give native select a bigger clickable area
  src/lib/input/input.scss
Labels: cla: yes, pr: lgtm, pr: merge ready, target: patch

#13224 fix(autocomplete): dividers in list throwing off keyboard navigation
  src/lib/autocomplete/autocomplete.scss
Labels: G, cla: yes, pr: lgtm, pr: merge ready, target: patch

#13196 feat(badge): allow badge to be disabled
  src/demo-app/badge/badge-demo.html
  src/lib/badge/_badge-theme.scss
  src/lib/badge/badge.spec.ts
  src/lib/badge/badge.ts
Labels: cla: yes, pr: lgtm, pr: merge ready, target: minor

#13384 chore: update to TypeScript 3.1
  package-lock.json
  package.json
  src/cdk-experimental/dialog/dialog.spec.ts
  src/cdk/a11y/focus-trap/focus-trap.spec.ts
  src/cdk/a11y/interactivity-checker/interactivity-checker.ts
  src/cdk/drag-drop/drag.ts
  src/cdk/layout/breakpoints-observer.spec.ts
  src/cdk/layout/breakpoints-observer.ts
  src/cdk/layout/media-matcher.spec.ts
  src/cdk/layout/media-matcher.ts
  src/cdk/overlay/position/flexible-connected-position-strategy.ts
  src/cdk/overlay/scroll/block-scroll-strategy.spec.ts
  src/cdk/overlay/scroll/block-scroll-strategy.ts
  src/cdk/platform/features/scrolling.ts
  src/cdk/scrolling/viewport-ruler.ts
  src/e2e-app/fullscreen/fullscreen-e2e.ts
  src/lib/bottom-sheet/bottom-sheet.spec.ts
  src/lib/core/ripple/ripple.spec.ts
  src/lib/datepicker/calendar-header.spec.ts
  src/lib/datepicker/calendar.spec.ts
  src/lib/dialog/dialog.spec.ts
  src/lib/form-field/form-field.ts
  src/lib/select/select.spec.ts
Labels: P1, cla: yes, pr: lgtm, pr: merge ready, target: major

#13278 fix(select): handle home and end keys on closed select
  src/lib/select/select.spec.ts
  src/lib/select/select.ts
Labels: cla: yes, pr: lgtm, pr: merge ready, target: patch

#13199 fix(overlay): wait for panel to detach before removing panelClass
  src/cdk/overlay/overlay-ref.ts
  src/cdk/overlay/overlay.spec.ts
Labels: cla: yes, pr: lgtm, pr: merge ready, target: patch

#13185 fix(overlay): incorrectly calculating centered position on a scrolled page with pushing
  src/cdk/overlay/position/flexible-connected-position-strategy.spec.ts
  src/cdk/overlay/position/flexible-connected-position-strategy.ts
Labels: cla: yes, pr: lgtm, pr: merge ready, target: patch

#13137 refactor(table): allow readonly array in data source input
  src/cdk/table/table.ts
Labels: cla: yes, pr: lgtm, pr: merge ready, target: patch

#13136 fix(menu): incorrectly styling keyboard focus, if trigger is right clicked before opening
  src/lib/menu/menu-trigger.ts
  src/lib/menu/menu.spec.ts
Labels: cla: yes, pr: lgtm, pr: merge ready, target: patch

#13133 fix(a11y): not being able to escape disabled focus trap using arrow keys
  src/cdk/a11y/focus-trap/focus-trap.spec.ts
  src/cdk/a11y/focus-trap/focus-trap.ts
Labels: a11y, cla: yes, pr: lgtm, pr: merge ready, target: patch

#13086 fix(grid-list): incorrectly laying out tiles for nested list
  src/lib/grid-list/grid-list-base.ts
  src/lib/grid-list/grid-list.spec.ts
  src/lib/grid-list/grid-list.ts
  src/lib/grid-list/grid-tile.ts
  src/lib/grid-list/tile-coordinator.ts
Labels: cla: yes, pr: lgtm, pr: merge ready, target: patch

#12909 fix(scrolling): viewport ruler resize event running inside the NgZone
  src/cdk/scrolling/viewport-ruler.spec.ts
  src/cdk/scrolling/viewport-ruler.ts
Labels: cla: yes, pr: lgtm, pr: merge ready, target: patch

#12786 perf(table): prevent unnecessary reflow with sticky row
  src/cdk/table/sticky-styler.ts
Labels: cla: yes, perf, pr: lgtm, pr: merge ready, target: patch

#13173 fix(chips): selectionChange event firing when value has not changed
  src/lib/chips/chip.spec.ts
  src/lib/chips/chip.ts
Labels: caretaker note, cla: yes, pr: lgtm, pr: merge ready, target: patch

#12348 refactor(selection): avoid awkward null check for onChange event
  src/cdk/collections/selection.spec.ts
  src/cdk/collections/selection.ts
  src/demo-app/tree/dynamic-tree-demo/dynamic-database.ts
  src/lib/list/selection-list.ts
  src/lib/select/select.ts
  src/lib/tree/data-source/flat-data-source.ts
  src/material-examples/tree-dynamic/tree-dynamic-example.ts
Labels: cla: yes, pr: lgtm, pr: merge ready, target: patch

#12495 fix(paginator): icons and labels not centered vertically on IE
  src/lib/paginator/paginator.html
  src/lib/paginator/paginator.scss
Labels: cla: yes, pr: lgtm, pr: merge ready, target: patch

#13398 chore: fix compilation error in master
  src/lib/bottom-sheet/bottom-sheet.spec.ts
Labels: cla: yes, pr: lgtm, pr: merge ready, pr: merge safe, target: major

#13352 build: cache bazel managed node modules
  .circleci/bazel.rc
  .circleci/config.yml
Labels: cla: yes, pr: lgtm, pr: merge ready, pr: merge safe, target: major

#13301 fix(schematics): avoid multiple async calls
  src/lib/schematics/nav/files/__path__/__name@dasherize@if-flat__/__name@dasherize__.component.html
  src/lib/schematics/nav/files/__path__/__name@dasherize@if-flat__/__name@dasherize__.component.ts
Labels: cla: yes, pr: lgtm, pr: merge safe, target: major

#13399 Revert "avoid multiple async calls (#13301)"
  src/lib/schematics/nav/files/__path__/__name@dasherize@if-flat__/__name@dasherize__.component.html
  src/lib/schematics/nav/files/__path__/__name@dasherize@if-flat__/__name@dasherize__.component.ts
Labels: cla: yes, pr: lgtm, pr: merge ready, pr: merge safe, target: major

#13400 chore: fix drag-drop test failure
  src/cdk/drag-drop/drag.spec.ts
Labels: cla: yes, pr: lgtm, pr: merge ready, pr: merge safe, target: major

#13363 fix(list): selection list not marking options as selected correctly when setting value with duplicates
  src/lib/list/selection-list.spec.ts
  src/lib/list/selection-list.ts
Labels: cla: yes, pr: lgtm, pr: merge ready, target: patch

#13120 fix(bottom-sheet): dismiss bottom sheet on destroy
  src/lib/bottom-sheet/bottom-sheet.spec.ts
  src/lib/bottom-sheet/bottom-sheet.ts
Labels: cla: yes, pr: lgtm, pr: merge ready, target: patch

#13184 fix(select): use pointer cursor for native select when not disabled
  src/lib/input/input.scss
Labels: cla: yes, pr: lgtm, pr: merge ready, target: patch

#13411 chore: remove amcdnl from codeowners
  .github/CODEOWNERS
Labels: cla: yes, pr: lgtm, pr: merge ready, pr: merge safe

#13406 fix(schematics): @angular/material schematics not working
  src/cdk/schematics/tsconfig.json
  src/lib/schematics/ng-update/upgrade-data.ts
  src/lib/schematics/tsconfig.json
Labels: P1, cla: yes, pr: lgtm, pr: merge ready, pr: merge safe, target: major

#13395 chore(changelog): remove superfluous breaking change note
  CHANGELOG.md
Labels: cla: yes, pr: lgtm, pr: merge ready, pr: merge safe, target: major

#13393 build: fix bazel schematic setup on windows
  src/cdk/schematics/#bazel_workaround.txt
  src/cdk/schematics/BUILD.bazel
  src/lib/schematics/BUILD.bazel
Labels: cla: yes, pr: lgtm, pr: merge ready, pr: merge safe, target: major

#13364 docs(drag-drop): fix cross-browser inconsistencies in demos
  src/material-examples/cdk-drag-drop-axis-lock/cdk-drag-drop-axis-lock-example.css
  src/material-examples/cdk-drag-drop-handle/cdk-drag-drop-handle-example.css
  src/material-examples/cdk-drag-drop-overview/cdk-drag-drop-overview-example.css
Labels: cla: yes, docs, pr: lgtm, pr: merge ready, pr: merge safe, target: major

#13394 docs(schematics): add drawing for CDK shared logic
  src/lib/schematics/cdk-shared-logic.png
Labels: cla: yes, pr: lgtm, pr: merge ready, pr: merge safe, target: major

#13418 Fix(script): schedule presubmit at same time and fix a typo in file name
  scripts/caretaking/write-presubmit-scheduler.js
Labels: cla: yes, pr: lgtm, pr: merge ready, pr: merge safe, target: major

#13413 fix(autocomplete): closing parent overlay when pressing escape
  src/lib/autocomplete/autocomplete-trigger.ts
  src/lib/autocomplete/autocomplete.spec.ts
Labels: cla: yes, pr: lgtm, pr: merge ready, target: patch

#13412 fix(virtual-scroll): don't set both `right` and `left` on the content wrapper
  src/cdk/scrolling/virtual-scroll-viewport.scss
Labels: P2, cla: yes, pr: lgtm, pr: merge ready, target: major

#13397 fix(button-toggle): not setting proper border in vertical mode
  src/lib/button-toggle/_button-toggle-theme.scss
Labels: cla: yes, pr: lgtm, pr: merge ready, target: major

#13396 fix(select): allow extra content to be projected after label in mat-optgroup
  src/lib/core/option/optgroup.html
Labels: cla: yes, pr: lgtm, pr: merge ready, target: patch

#13367 fix(button-toggle): remove extra focus indication added by firefox
  src/lib/button-toggle/button-toggle.scss
Labels: cla: yes, pr: lgtm, pr: merge ready, target: patch

#13295 fix(checkbox): ripple not hiding after click/touch
  src/lib/checkbox/checkbox.scss
Labels: cla: yes, pr: lgtm, pr: merge ready, target: major

#13168 build(docs): show exported constants in docs
  src/cdk/overlay/overlay-module.ts
  src/lib/datepicker/datepicker-animations.ts
  src/lib/dialog/dialog-animations.ts
  src/lib/expansion/expansion-animations.ts
  src/lib/form-field/form-field-animations.ts
  src/lib/menu/menu-animations.ts
  src/lib/select/select-animations.ts
  src/lib/sidenav/drawer-animations.ts
  src/lib/snack-bar/snack-bar-animations.ts
  src/lib/sort/sort-animations.ts
  src/lib/stepper/stepper-animations.ts
  src/lib/tabs/tabs-animations.ts
  src/lib/tooltip/tooltip-animations.ts
  tools/dgeni/common/dgeni-definitions.ts
  tools/dgeni/index.ts
  tools/dgeni/nunjucks-tags/highlight.ts
  tools/dgeni/processors/categorizer.ts
  tools/dgeni/processors/entry-point-grouper.ts
  tools/dgeni/templates/constant.template.html
  tools/dgeni/templates/entry-point.template.html
Labels: cla: yes, pr: lgtm, pr: merge ready, target: patch

#12244 fix(chips): ripple not clipping correctly in safari
  src/lib/chips/chips.scss
Labels: cla: yes, pr: lgtm, pr: merge ready, target: patch

#10358 fix(tabs): disabled tab link not preventing router navigation
  src/lib/tabs/tab-nav-bar/tab-nav-bar.scss
  src/lib/tabs/tab-nav-bar/tab-nav-bar.spec.ts
  src/lib/tabs/tab-nav-bar/tab-nav-bar.ts
Labels: cla: yes, pr: lgtm, pr: merge ready, target: patch

#13425 Fixed typo in bottom-sheet-overview
  src/material-examples/bottom-sheet-overview/bottom-sheet-overview-example.html
Labels: cla: yes, commit message fixup, pr: lgtm, pr: merge ready, pr: merge safe, target: patch

#13421 fix(experimental/dialog): clean up open dialogs on destroy
  src/cdk-experimental/dialog/dialog.spec.ts
  src/cdk-experimental/dialog/dialog.ts
Labels: cla: yes, pr: lgtm, pr: merge ready, pr: merge safe, target: patch

#13417 fix(form-field): updated form-field-prefix-suffix password icon
  src/material-examples/form-field-prefix-suffix/form-field-prefix-suffix-example.html
Labels: cla: yes, commit message fixup, docs, pr: lgtm, pr: merge ready, pr: merge safe, target: patch

#13408 build: update bazel typescript rules
  WORKSPACE
  package-lock.json
  package.json
  src/lib/schematics/ng-update/test-cases/v6-test-cases.spec.ts
  src/lib/schematics/ng-update/test-cases/v6/css-selectors_expected_output.ts
  src/lib/schematics/ng-update/test-cases/v6/css-selectors_input.ts
Labels: cla: yes, pr: lgtm, pr: merge ready, pr: merge safe, target: major

#13368 feat(schematics): create drag-drop schematic
  src/cdk/schematics/BUILD.bazel
  src/cdk/schematics/collection.json
  src/cdk/schematics/ng-generate/drag-drop/files/__path__/__name@dasherize@if-flat__/__name@dasherize__.component.__styleext__
  src/cdk/schematics/ng-generate/drag-drop/files/__path__/__name@dasherize@if-flat__/__name@dasherize__.component.html
  src/cdk/schematics/ng-generate/drag-drop/files/__path__/__name@dasherize@if-flat__/__name@dasherize__.component.spec.ts
  src/cdk/schematics/ng-generate/drag-drop/files/__path__/__name@dasherize@if-flat__/__name@dasherize__.component.ts
  src/cdk/schematics/ng-generate/drag-drop/index.spec.ts
  src/cdk/schematics/ng-generate/drag-drop/index.ts
  src/cdk/schematics/ng-generate/drag-drop/schema.json
  src/cdk/schematics/ng-generate/drag-drop/schema.ts
  src/cdk/schematics/tsconfig.json
  tslint.json
Labels: cla: yes, pr: lgtm, pr: merge ready, pr: merge safe, target: major

#13433 docs(slide-toggle): remove orphaned duplicate comment
  src/lib/slide-toggle/slide-toggle.ts
Labels: P2, cla: yes, pr: lgtm, pr: merge ready, pr: merge safe, target: major

#13429 fix(ng-add): allow using noop animations
  src/cdk/schematics/utils/ast/ng-module-imports.ts
  src/cdk/schematics/utils/index.ts
  src/lib/schematics/ng-add/index.spec.ts
  src/lib/schematics/ng-add/schema.json
  src/lib/schematics/ng-add/schema.ts
  src/lib/schematics/ng-add/setup-project.ts
Labels: cla: yes, pr: lgtm, pr: merge ready, pr: merge safe, target: major

#13260 fix(chips): content not centered vertically on IE in some cases
  src/lib/chips/chips.scss
Labels: cla: yes, pr: lgtm, pr: merge ready, target: major

#13236 feat(datepicker): add ng-content to datepicker header
  src/demo-app/datepicker/datepicker-demo.html
  src/demo-app/datepicker/datepicker-demo.ts
  src/demo-app/demo-app/demo-module.ts
  src/lib/datepicker/calendar-header.html
  src/lib/datepicker/datepicker.spec.ts
Labels: cla: yes, pr: lgtm, pr: merge ready, target: minor

#12428 fix(icon): handle references for pages with base tag
  src/lib/icon/icon.spec.ts
  src/lib/icon/icon.ts
Labels: cla: yes, pr: lgtm, pr: merge ready, target: patch

#13449 build(docs): deprecated state of type alias not showing up
  tools/dgeni/common/dgeni-definitions.ts
  tools/dgeni/processors/categorizer.ts
  tools/dgeni/templates/constant.template.html
  tools/dgeni/templates/type-alias.template.html
Labels: cla: yes, pr: lgtm, pr: merge ready, pr: merge safe, target: patch

#13447 refactor(schematics): better margin for drag-drop schematic
  src/cdk/schematics/ng-generate/drag-drop/files/__path__/__name@dasherize@if-flat__/__name@dasherize__.component.__styleext__
  src/lib/schematics/nav/files/__path__/__name@dasherize@if-flat__/__name@dasherize__.component.html
  src/lib/schematics/table/files/__path__/__name@dasherize@if-flat__/__name@dasherize__.component.html
Labels: cla: yes, pr: lgtm, pr: merge ready, pr: merge safe, target: major

#13416 docs(button-toggle): add appearance docs and example
  src/lib/button-toggle/button-toggle.md
  src/material-examples/button-toggle-appearance/button-toggle-appearance-example.css
  src/material-examples/button-toggle-appearance/button-toggle-appearance-example.html
  src/material-examples/button-toggle-appearance/button-toggle-appearance-example.ts
Labels: cla: yes, pr: lgtm, pr: merge ready, pr: merge safe, target: major

#13253 fix(form-field): not updating outline when prefix/suffix is added or removed
  src/lib/form-field/form-field.ts
  src/lib/input/input.spec.ts
Labels: cla: yes, pr: lgtm, pr: merge ready, target: patch

#10631 refactor(live-announcer): run outside NgZone
  src/cdk/a11y/live-announcer/live-announcer.ts
Labels: cla: yes, pr: lgtm, pr: merge ready, target: patch

#13453 chore(docs): hide value accessors from docs
  src/lib/datepicker/datepicker-input.ts
  src/lib/slide-toggle/slide-toggle.ts
  src/lib/slider/slider.ts
Labels: cla: yes, pr: lgtm, pr: merge ready, pr: merge safe, target: patch

#13435 docs: clean up and clarify theming docs
  guides/theming-your-components.md
  guides/theming.md
Labels: cla: yes, docs, pr: lgtm, pr: merge ready, pr: merge safe, target: patch

#13362 build: switch to yarn
  .circleci/config.yml
  .travis.yml
  WORKSPACE
  package-lock.json
  package.json
  scripts/ci/install-yarn.sh
  yarn.lock
Labels: cla: yes, pr: lgtm, pr: merge ready, pr: merge safe, target: major

#13452 fix(schematics): name is required when generating the drag-drop schematic
  src/cdk/schematics/ng-generate/drag-drop/schema.json
Labels: cla: yes, pr: lgtm, pr: merge ready, pr: merge safe, target: major

#13457 build(docs): ensure const types are not truncated
  tools/dgeni/index.ts
  tools/dgeni/processors/no-truncate-const-type.ts
Labels: cla: yes, pr: lgtm, pr: merge ready, pr: merge safe, target: patch

#13441 feat(drag-drop): convert cdk-drop into a directive
  src/cdk/drag-drop/BUILD.bazel
  src/cdk/drag-drop/drag-drop-registry.spec.ts
  src/cdk/drag-drop/drag-drop-registry.ts
  src/cdk/drag-drop/drag-drop.md
  src/cdk/drag-drop/drag-handle.ts
  src/cdk/drag-drop/drag-styling.ts
  src/cdk/drag-drop/drag.spec.ts
  src/cdk/drag-drop/drag.ts
  src/cdk/drag-drop/drop.scss
  src/cdk/drag-drop/drop.ts
  src/cdk/schematics/ng-generate/drag-drop/files/__path__/__name@dasherize@if-flat__/__name@dasherize__.component.html
  src/demo-app/drag-drop/drag-drop-demo.html
  src/material-examples/cdk-drag-drop-connected-sorting/cdk-drag-drop-connected-sorting-example.html
  src/material-examples/cdk-drag-drop-custom-preview/cdk-drag-drop-custom-preview-example.html
  src/material-examples/cdk-drag-drop-horizontal-sorting/cdk-drag-drop-horizontal-sorting-example.html
  src/material-examples/cdk-drag-drop-sorting/cdk-drag-drop-sorting-example.html
Labels: P2, cla: yes, commit message fixup, pr: lgtm, pr: merge ready, target: major

#13500 chore: fix implicit-any error in drag-styling.ts
  src/cdk/drag-drop/drag-styling.ts
Labels: cla: yes, pr: lgtm, pr: merge ready, target: major

#13501 chore: bump verion to 7.0.0-rc.1 w/ changelog
  CHANGELOG.md
  package.json
Labels: cla: yes, pr: lgtm, pr: merge ready, pr: merge safe

#13516 demo(prerender): add theme to prerender demo
  src/universal-app/index.html
  src/universal-app/kitchen-sink/kitchen-sink.html
  src/universal-app/theme.scss
  tools/gulp/tasks/universal.ts
Labels: cla: yes, pr: lgtm, pr: merge ready, pr: merge safe, target: patch

#13520 docs: show all available schematics in the schematics guide
  guides/schematics.md
Labels: cla: yes, docs, pr: lgtm, pr: merge ready, pr: merge safe

#13521 fix(schematics): template content exceeds max line length
  src/lib/schematics/address-form/files/__path__/__name@dasherize@if-flat__/__name@dasherize__.component.ts
Labels: cla: yes, pr: lgtm, pr: merge ready, pr: merge safe, target: major

#13542 chore(schematics): re-enable linting for ignored file
  src/cdk/schematics/utils/build-component.ts
Labels: cla: yes, pr: lgtm, pr: merge ready, pr: merge safe, target: major

#13564 docs: fix typo in typography example
  guides/theming-your-components.md
Labels: cla: yes, pr: lgtm, pr: merge ready, pr: merge safe, target: patch

#13541 build: build cdk with angular from source
  .circleci/config.yml
  BUILD.bazel
  WORKSPACE
  package.json
  src/cdk/BUILD.bazel
  src/cdk/a11y/BUILD.bazel
  src/cdk/accordion/BUILD.bazel
  src/cdk/bidi/BUILD.bazel
  src/cdk/coercion/BUILD.bazel
  src/cdk/collections/BUILD.bazel
  src/cdk/drag-drop/BUILD.bazel
  src/cdk/keycodes/BUILD.bazel
  src/cdk/layout/BUILD.bazel
  src/cdk/observers/BUILD.bazel
  src/cdk/overlay/BUILD.bazel
  src/cdk/platform/BUILD.bazel
  src/cdk/portal/BUILD.bazel
  src/cdk/schematics/BUILD.bazel
  src/cdk/scrolling/BUILD.bazel
  src/cdk/stepper/BUILD.bazel
  src/cdk/table/BUILD.bazel
  src/cdk/testing/BUILD.bazel
  src/cdk/testing/tsconfig-bazel.json
  src/cdk/text-field/BUILD.bazel
  src/cdk/tree/BUILD.bazel
  src/cdk/tsconfig-build.json
  src/lib/schematics/BUILD.bazel
  tools/BUILD.bazel
  tools/bazel.rc
  tools/defaults.bzl
  yarn.lock
Labels: cla: yes, pr: lgtm, pr: merge ready, pr: merge safe, target: major

#13522 docs: clean up slide toggle API Docs
  src/lib/slide-toggle/slide-toggle.ts
Labels: cla: yes, pr: lgtm, pr: merge ready, pr: merge safe, target: patch

#13518 feat(schematics): prompt for name when generating component
  src/cdk/schematics/ng-generate/drag-drop/schema.json
  src/lib/schematics/address-form/schema.json
  src/lib/schematics/dashboard/schema.json
  src/lib/schematics/nav/schema.json
  src/lib/schematics/table/schema.json
  src/lib/schematics/tree/schema.json
Labels: cla: yes, pr: lgtm, pr: merge ready, pr: merge safe, target: major

#13515 chore: fix z-index on drag-drop demos and button width on tooltip demo
  src/material-examples/cdk-drag-drop-axis-lock/cdk-drag-drop-axis-lock-example.css
  src/material-examples/cdk-drag-drop-handle/cdk-drag-drop-handle-example.css
  src/material-examples/cdk-drag-drop-overview/cdk-drag-drop-overview-example.css
  src/material-examples/tooltip-auto-hide/tooltip-auto-hide-example.css
Labels: cla: yes, pr: lgtm, pr: merge ready, pr: merge safe, target: major

#13513 chore: wrong name for drag&drop input
  src/cdk/drag-drop/drop.ts
Labels: P1, cla: yes, pr: lgtm, pr: merge ready, target: major

#13609 doc: fix typo in changelog
  CHANGELOG.md
Labels: cla: yes, commit message fixup, pr: lgtm, pr: merge ready, pr: merge safe, target: patch

#13604 chore: remove unused schematics readme
  src/cdk/schematics/BUILD.bazel
  src/cdk/schematics/README.md
  src/lib/schematics/BUILD.bazel
  src/lib/schematics/README.md
Labels: cla: yes, pr: lgtm, pr: merge ready, pr: merge safe, target: patch

#13596 build: move lint job to circleci
  .circleci/config.yml
  .travis.yml
  package.json
Labels: cla: yes, pr: lgtm, pr: merge ready, pr: merge safe, target: major

#13595 build: fix cronjob snapshot jobs failing
  .travis.yml
  scripts/install-angular-snapshot.sh
Labels: cla: yes, pr: lgtm, pr: merge ready, pr: merge safe, target: patch

#13594 refactor(schematics): do not depend on parse5 twice
  src/cdk/schematics/utils/html-head-element.ts
  src/cdk/schematics/utils/index.ts
  src/lib/package.json
  src/lib/schematics/BUILD.bazel
  src/lib/schematics/ng-add/fonts/material-fonts.ts
  src/lib/schematics/ng-add/setup-project.ts
Labels: cla: yes, pr: lgtm, pr: merge ready, pr: merge safe, target: major

#13587 fix(experimental/dialog): emitting events twice on some browsers
  src/cdk-experimental/dialog/dialog-container.ts
Labels: cla: yes, pr: lgtm, pr: merge ready, pr: merge safe, target: patch

#13584 fix(experimental/dialog): disableClose option not working
  src/cdk-experimental/dialog/dialog.spec.ts
  src/cdk-experimental/dialog/dialog.ts
  src/lib/bottom-sheet/bottom-sheet.spec.ts
  src/lib/dialog/dialog.spec.ts
Labels: cla: yes, pr: lgtm, pr: merge ready, pr: merge safe, target: patch

#13576 chore(table): cleanup demo by moving to examples
  src/demo-app/table/custom-table/custom-table.html
  src/demo-app/table/custom-table/custom-table.scss
  src/demo-app/table/custom-table/custom-table.ts
  src/demo-app/table/custom-table/wrapper-table.ts
  src/demo-app/table/data-input-table/data-input-table.html
  src/demo-app/table/data-input-table/data-input-table.scss
  src/demo-app/table/data-input-table/data-input-table.ts
  src/demo-app/table/element-data.ts
  src/demo-app/table/table-demo-module.ts
  src/demo-app/table/table-demo.html
  src/demo-app/table/table-demo.ts
  src/demo-app/table/when-rows/when-rows.html
  src/demo-app/table/when-rows/when-rows.ts
  src/material-examples/table-simple-column/table-simple-column-example.css
  src/material-examples/table-simple-column/table-simple-column-example.html
  src/material-examples/table-simple-column/table-simple-column-example.ts
  src/material-examples/table-wrapped/table-wrapped-example.css
  src/material-examples/table-wrapped/table-wrapped-example.html
  src/material-examples/table-wrapped/table-wrapped-example.ts
  src/material-examples/table-wrapped/wrapper-table.html
Labels: cla: yes, pr: lgtm, pr: merge ready, pr: merge safe

#13563 build: set up tooling to ensure consistent prefixes for CSS classes
  guides/creating-a-custom-form-field-control.md
  src/demo-app/demo-app/demo-app.ts
  src/demo-app/drag-drop/drag-drop-demo.html
  src/demo-app/drag-drop/drag-drop-demo.scss
  src/demo-app/screen-type/screen-type-demo.html
  src/demo-app/screen-type/screen-type-demo.scss
  src/demo-app/theme.scss
  src/e2e-app/block-scroll-strategy/block-scroll-strategy-e2e.css
  src/e2e-app/block-scroll-strategy/block-scroll-strategy-e2e.html
  src/material-examples/button-types/button-types-example.css
  src/material-examples/button-types/button-types-example.html
  src/material-examples/cdk-drag-drop-axis-lock/cdk-drag-drop-axis-lock-example.css
  src/material-examples/cdk-drag-drop-axis-lock/cdk-drag-drop-axis-lock-example.html
  src/material-examples/cdk-drag-drop-connected-sorting/cdk-drag-drop-connected-sorting-example.css
  src/material-examples/cdk-drag-drop-connected-sorting/cdk-drag-drop-connected-sorting-example.html
  src/material-examples/cdk-drag-drop-custom-preview/cdk-drag-drop-custom-preview-example.css
  src/material-examples/cdk-drag-drop-custom-preview/cdk-drag-drop-custom-preview-example.html
  src/material-examples/cdk-drag-drop-handle/cdk-drag-drop-handle-example.css
  src/material-examples/cdk-drag-drop-handle/cdk-drag-drop-handle-example.html
  src/material-examples/cdk-drag-drop-horizontal-sorting/cdk-drag-drop-horizontal-sorting-example.css
  src/material-examples/cdk-drag-drop-horizontal-sorting/cdk-drag-drop-horizontal-sorting-example.html
  src/material-examples/cdk-drag-drop-overview/cdk-drag-drop-overview-example.css
  src/material-examples/cdk-drag-drop-overview/cdk-drag-drop-overview-example.html
  src/material-examples/cdk-drag-drop-root-element/cdk-drag-drop-root-element-example.css
  src/material-examples/cdk-drag-drop-root-element/cdk-drag-drop-root-element-example.html
  src/material-examples/cdk-drag-drop-sorting/cdk-drag-drop-sorting-example.css
  src/material-examples/cdk-drag-drop-sorting/cdk-drag-drop-sorting-example.html
  src/material-examples/form-field-custom-control/example-tel-input-example.css
  src/material-examples/form-field-custom-control/example-tel-input-example.html
  src/material-examples/form-field-custom-control/form-field-custom-control-example.html
  src/material-examples/form-field-custom-control/form-field-custom-control-example.ts
  src/material-examples/form-field-custom-control/my-tel-input-example.html
  src/universal-app/kitchen-sink/kitchen-sink.css
  src/universal-app/kitchen-sink/kitchen-sink.ts
  stylelint-config.json
  tools/dashboard/src/app/coverage-chart/coverage-chart.html
  tools/dashboard/src/app/payload-chart/payload-chart.html
  tools/dashboard/src/styles.scss
Labels: cla: yes, pr: lgtm, pr: merge ready, pr: merge safe, target: major

#13575 build: test cdk with bazel
  .circleci/config.yml
  BUILD.bazel
  WORKSPACE
  package.json
  src/BUILD.bazel
  src/bazel-tsconfig-build.json
  src/bazel-tsconfig-test.json
  src/cdk/BUILD.bazel
  src/cdk/a11y/BUILD.bazel
  src/cdk/accordion/BUILD.bazel
  src/cdk/bidi/BUILD.bazel
  src/cdk/coercion/BUILD.bazel
  src/cdk/collections/BUILD.bazel
  src/cdk/drag-drop/BUILD.bazel
  src/cdk/keycodes/BUILD.bazel
  src/cdk/layout/BUILD.bazel
  src/cdk/observers/BUILD.bazel
  src/cdk/overlay/BUILD.bazel
  src/cdk/platform/BUILD.bazel
  src/cdk/portal/BUILD.bazel
  src/cdk/scrolling/BUILD.bazel
  src/cdk/stepper/BUILD.bazel
  src/cdk/table/BUILD.bazel
  src/cdk/testing/BUILD.bazel
  src/cdk/testing/tsconfig-bazel.json
  src/cdk/text-field/BUILD.bazel
  src/cdk/tree/BUILD.bazel
  src/cdk/tsconfig-build.json
  src/cdk/tsconfig-tests.json
  test/BUILD.bazel
  test/angular-test-init-spec.ts
  tools/bazel.rc
  tools/defaults.bzl
  yarn.lock
Labels: cla: yes, pr: lgtm, pr: merge ready, pr: merge safe, target: major

#13578 fix(drag-drop): enterPredicate being called with wrong drop container
  src/cdk/drag-drop/drag.spec.ts
  src/cdk/drag-drop/drop.ts
Labels: cla: yes, pr: lgtm, pr: merge ready, target: major

#13619 chore(drag-drop): rename cdkDrop to cdkDropList
  src/cdk/drag-drop/drag-drop-module.ts
  src/cdk/drag-drop/drag-drop-registry.spec.ts
  src/cdk/drag-drop/drag-drop.md
  src/cdk/drag-drop/drag-events.ts
  src/cdk/drag-drop/drag.spec.ts
  src/cdk/drag-drop/drag.ts
  src/cdk/drag-drop/drop-list-container.ts
  src/cdk/drag-drop/drop-list.ts
  src/cdk/drag-drop/public-api.ts
  src/demo-app/drag-drop/drag-drop-demo.html
  src/demo-app/drag-drop/drag-drop-demo.scss
  src/demo-app/drag-drop/drag-drop-demo.ts
  src/material-examples/cdk-drag-drop-connected-sorting/cdk-drag-drop-connected-sorting-example.css
  src/material-examples/cdk-drag-drop-connected-sorting/cdk-drag-drop-connected-sorting-example.html
  src/material-examples/cdk-drag-drop-custom-preview/cdk-drag-drop-custom-preview-example.css
  src/material-examples/cdk-drag-drop-custom-preview/cdk-drag-drop-custom-preview-example.html
  src/material-examples/cdk-drag-drop-horizontal-sorting/cdk-drag-drop-horizontal-sorting-example.css
  src/material-examples/cdk-drag-drop-horizontal-sorting/cdk-drag-drop-horizontal-sorting-example.html
  src/material-examples/cdk-drag-drop-sorting/cdk-drag-drop-sorting-example.css
  src/material-examples/cdk-drag-drop-sorting/cdk-drag-drop-sorting-example.html
Labels: cla: yes, pr: lgtm, pr: merge ready, target: major

#13597 fix(virtual-scroll): fix several small bugs
  src/cdk/scrolling/scrolling.md
  src/cdk/scrolling/virtual-scroll-viewport.scss
  src/cdk/scrolling/virtual-scroll-viewport.spec.ts
  src/cdk/scrolling/virtual-scroll-viewport.ts
  src/material-examples/cdk-virtual-scroll-custom-strategy/cdk-virtual-scroll-custom-strategy-example.css
  src/material-examples/cdk-virtual-scroll-custom-strategy/cdk-virtual-scroll-custom-strategy-example.html
  src/material-examples/cdk-virtual-scroll-custom-strategy/cdk-virtual-scroll-custom-strategy-example.ts
Labels: P1, cla: yes, pr: lgtm, pr: merge ready, target: patch

#13623 chore: bump package.json to 7.0.0-rc.2
  CHANGELOG.md
  package.json
Labels: cla: yes, pr: lgtm, pr: merge ready, pr: merge safe, target: major

#13603 build: run chrome and firefox headless tests in circleci
  .circleci/config.yml
  .travis.yml
  package.json
  test/browser-providers.js
  test/karma.conf.js
Labels: cla: yes, pr: lgtm, pr: merge ready, pr: merge safe, target: major

#13629 chore(drag-drop): fix leftover cdkDrop references
  src/cdk/drag-drop/drag-drop-registry.ts
  src/cdk/drag-drop/drag-drop.md
  src/cdk/drag-drop/drag.ts
  src/cdk/drag-drop/drop-list-container.ts
  src/cdk/schematics/ng-generate/drag-drop/files/__path__/__name@dasherize@if-flat__/__name@dasherize__.component.html
  src/material-examples/cdk-drag-drop-horizontal-sorting/cdk-drag-drop-horizontal-sorting-example.html
Labels: cla: yes, pr: lgtm, pr: merge ready, pr: merge safe, target: major

#13622 build: update bazel sass rules
  WORKSPACE
Labels: cla: yes, pr: lgtm, pr: merge ready, pr: merge safe, target: major

#13633 fix(schematics): do not publish testing utilities to npm
  src/cdk/schematics/BUILD.bazel
  src/cdk/schematics/index.ts
  src/cdk/schematics/testing/BUILD.bazel
  src/cdk/schematics/tsconfig.json
  src/lib/schematics/BUILD.bazel
  src/lib/schematics/address-form/index.spec.ts
  src/lib/schematics/dashboard/index.spec.ts
  src/lib/schematics/nav/index.spec.ts
  src/lib/schematics/ng-add/index.spec.ts
  src/lib/schematics/ng-update/test-cases/misc/constructor-checks.spec.ts
  src/lib/schematics/ng-update/test-cases/misc/import-checks.spec.ts
  src/lib/schematics/ng-update/test-cases/v6-test-cases.spec.ts
  src/lib/schematics/ng-update/test-cases/v7-test-cases.spec.ts
  src/lib/schematics/table/index.spec.ts
  src/lib/schematics/tree/index.spec.ts
Labels: P0, cla: yes, pr: lgtm, pr: merge ready, pr: merge safe, target: major

#13639 chore: update required statuses for github robot
  .circleci/config.yml
  .github/angular-robot.yml
Labels: cla: yes, pr: lgtm, pr: merge ready, pr: merge safe, target: major

#13638 chore: clean up internal usages of deprecated signatures
  src/cdk/accordion/accordion-item.spec.ts
  src/cdk/accordion/accordion.spec.ts
  src/cdk/collections/selection.spec.ts
  src/cdk/text-field/autosize.spec.ts
  src/lib/chips/chip-input.spec.ts
  src/lib/chips/chip.spec.ts
  src/lib/input/input.spec.ts
  src/lib/tabs/tab-nav-bar/tab-nav-bar.spec.ts
  src/lib/tooltip/tooltip.spec.ts
Labels: cla: yes, pr: lgtm, pr: merge ready, pr: merge safe, target: patch

#13637 build: run overlay and text-field tests with Bazel
  src/cdk/overlay/BUILD.bazel
  src/cdk/text-field/BUILD.bazel
  tools/defaults.bzl
Labels: cla: yes, pr: lgtm, pr: merge ready, pr: merge safe, target: patch

#13404 feat: add support for noImplicitThis
  e2e/tsconfig.json
  e2e/util/asserts.ts
  src/bazel-tsconfig-build.json
  src/cdk-experimental/tsconfig-build.json
  src/cdk/a11y/interactivity-checker/interactivity-checker.spec.ts
  src/cdk/a11y/key-manager/list-key-manager.spec.ts
  src/demo-app/tsconfig-aot.json
  src/demo-app/tsconfig-build.json
  src/e2e-app/tsconfig-build.json
  src/lib/tsconfig-build.json
  src/material-examples/tsconfig-build.json
  src/material-experimental/tsconfig-build.json
  src/material-moment-adapter/tsconfig-build.json
  src/universal-app/tsconfig-build.json
  src/universal-app/tsconfig-prerender.json
  test/angular-test-init-spec.ts
  tools/dashboard/functions/tsconfig.json
  tools/dgeni/tsconfig.json
  tools/gulp/tasks/docs.ts
  tools/gulp/tsconfig.json
  tsconfig.json
Labels: cla: yes, pr: lgtm, pr: merge ready, target: major

#13621 build: initial release staging script
  package.json
  tools/release/BUILD.bazel
  tools/release/git/git-client.ts
  tools/release/prompt/new-version-prompt.ts
  tools/release/stage-release-bin.sh
  tools/release/stage-release.ts
  tools/release/tsconfig.json
  tools/release/version-name/create-version.ts
  tools/release/version-name/parse-version.ts
  tools/release/version-name/publish-branch.ts
  yarn.lock
Labels: cla: yes, infrastructure, pr: lgtm, pr: merge ready, pr: merge safe, target: major

#13654 chore: update deprecation targets
  src/cdk/a11y/aria-describer/aria-describer.ts
  src/cdk/a11y/focus-monitor/focus-monitor.ts
  src/cdk/a11y/focus-trap/focus-trap.ts
  src/cdk/a11y/key-manager/list-key-manager.ts
  src/cdk/a11y/live-announcer/live-announcer.ts
  src/cdk/overlay/keyboard/overlay-keyboard-dispatcher.ts
  src/cdk/overlay/overlay-container.ts
  src/cdk/overlay/overlay-directives.ts
  src/cdk/overlay/overlay-module.ts
  src/cdk/overlay/position/connected-position-strategy.ts
  src/cdk/overlay/position/flexible-connected-position-strategy.ts
  src/cdk/overlay/position/global-position-strategy.ts
  src/cdk/overlay/position/overlay-position-builder.ts
  src/cdk/platform/platform.ts
  src/cdk/scrolling/scroll-dispatcher.ts
  src/cdk/scrolling/viewport-ruler.ts
  src/cdk/stepper/stepper.ts
  src/lib/autocomplete/autocomplete-trigger.ts
  src/lib/button-toggle/button-toggle.ts
  src/lib/button/button.ts
  src/lib/core/datetime/date-adapter.ts
  src/lib/core/gestures/gesture-config.ts
  src/lib/core/theming/_palette.scss
  src/lib/datepicker/datepicker-input.ts
  src/lib/form-field/_form-field-legacy-theme.scss
  src/lib/form-field/form-field.scss
  src/lib/form-field/form-field.ts
  src/lib/input/autosize.ts
  src/lib/input/input.ts
  src/lib/list/list.ts
  src/lib/menu/menu-animations.ts
  src/lib/menu/menu-directive.ts
  src/lib/menu/menu-item.ts
  src/lib/menu/menu-trigger.ts
  src/lib/paginator/paginator.ts
  src/lib/progress-spinner/progress-spinner.ts
  src/lib/select/select-animations.ts
  src/lib/slide-toggle/slide-toggle.ts
  src/lib/slider/slider.ts
  src/lib/snack-bar/snack-bar-ref.ts
  src/lib/tabs/tab-body.ts
  src/lib/tabs/tab-nav-bar/tab-nav-bar.ts
Labels: cla: yes, pr: lgtm, pr: merge ready, pr: merge safe, target: major

#13099 fix(list): action list items clickable area not stretching the full width
  src/lib/list/list.scss
Labels: cla: yes, pr: lgtm, pr: merge ready, target: major

#13643 build: run e2e tests on circlci
  .circleci/config.yml
  .travis.yml
  test/protractor.conf.js
Labels: cla: yes, pr: lgtm, pr: merge ready, pr: merge safe, target: major

#13655 build: build material with angular from source
  .circleci/config.yml
  src/BUILD.bazel
  src/cdk/drag-drop/tsconfig-build.json
  src/cdk/drag-drop/typings.d.ts
  src/cdk/scrolling/tsconfig-build.json
  src/cdk/scrolling/typings.d.ts
  src/cdk/stepper/typings.d.ts
  src/cdk/table/typings.d.ts
  src/cdk/tree/typings.d.ts
  src/lib/BUILD.bazel
  src/lib/autocomplete/BUILD.bazel
  src/lib/badge/BUILD.bazel
  src/lib/bottom-sheet/BUILD.bazel
  src/lib/button-toggle/BUILD.bazel
  src/lib/button/BUILD.bazel
  src/lib/card/BUILD.bazel
  src/lib/checkbox/BUILD.bazel
  src/lib/chips/BUILD.bazel
  src/lib/core/BUILD.bazel
  src/lib/datepicker/BUILD.bazel
  src/lib/dialog/BUILD.bazel
  src/lib/divider/BUILD.bazel
  src/lib/expansion/BUILD.bazel
  src/lib/form-field/BUILD.bazel
  src/lib/grid-list/BUILD.bazel
  src/lib/icon/BUILD.bazel
  src/lib/input/BUILD.bazel
  src/lib/list/BUILD.bazel
  src/lib/menu/BUILD.bazel
  src/lib/paginator/BUILD.bazel
  src/lib/progress-bar/BUILD.bazel
  src/lib/progress-spinner/BUILD.bazel
  src/lib/radio/BUILD.bazel
  src/lib/select/BUILD.bazel
  src/lib/sidenav/BUILD.bazel
  src/lib/slide-toggle/BUILD.bazel
  src/lib/slider/BUILD.bazel
  src/lib/snack-bar/BUILD.bazel
  src/lib/sort/BUILD.bazel
  src/lib/stepper/BUILD.bazel
  src/lib/table/BUILD.bazel
  src/lib/tabs/BUILD.bazel
  src/lib/toolbar/BUILD.bazel
  src/lib/tooltip/BUILD.bazel
  src/lib/tree/BUILD.bazel
  src/module-typings.d.ts
  tools/defaults.bzl
Labels: cla: yes, pr: lgtm, pr: merge ready, pr: merge safe, target: major

#13644 build: move bazel config to workspace root
  .bazelrc
Labels: cla: yes, pr: lgtm, pr: merge ready, pr: merge safe, target: major

#13523 docs(tree-checklist-example): root tree node correct selected state
  src/material-examples/tree-checklist/tree-checklist-example.html
  src/material-examples/tree-checklist/tree-checklist-example.ts
Labels: cla: yes, pr: lgtm, pr: merge ready, pr: merge safe, target: patch

#13658 docs(table component): Improve instructions on sorting
  src/lib/table/table.md
Labels: cla: yes, pr: lgtm, pr: merge ready, pr: merge safe, target: patch

#13657 refactor(overlay): convert fullscreen overlay container e2e tests into unit tests
  .github/CODEOWNERS
  e2e/components/fullscreen-e2e.spec.ts
  src/cdk/overlay/fullscreen-overlay-container.spec.ts
  src/e2e-app/e2e-app-module.ts
  src/e2e-app/e2e-app/e2e-app.html
  src/e2e-app/e2e-app/routes.ts
  src/e2e-app/fullscreen/fullscreen-e2e.html
  src/e2e-app/fullscreen/fullscreen-e2e.ts
Labels: cla: yes, pr: lgtm, pr: merge ready, pr: merge safe, target: major

#13656 build: update saucelabs connect version
  scripts/saucelabs/start-tunnel.sh
Labels: cla: yes, pr: lgtm, pr: merge ready, pr: merge safe, target: patch

#13641 fix(icon): not taking current path after initialization
  src/lib/icon/icon.spec.ts
  src/lib/icon/icon.ts
Labels: cla: yes, pr: lgtm, pr: merge ready, target: patch

#13672 chore: update changelog with v7 changes
  CHANGELOG.md
  package.json
  yarn.lock
Labels: cla: yes, pr: lgtm, pr: merge ready, pr: merge safe, target: major

#13679 build: exported scss files missing in CDK
  tools/package-tools/gulp/build-tasks-gulp.ts
Labels: cla: yes, pr: lgtm, pr: merge ready, pr: merge safe, target: patch

#13608 fix(stepper): emitting the animationDone event twice on some browsers
  src/lib/stepper/stepper-horizontal.html
  src/lib/stepper/stepper-vertical.html
  src/lib/stepper/stepper.ts
Labels: cla: yes, pr: lgtm, pr: merge ready, target: patch

#12947 fix(stepper): custom icons not centered inside circle
  src/lib/stepper/step-header.html
  src/lib/stepper/step-header.scss
Labels: cla: yes, pr: lgtm, pr: merge ready, target: patch

#13020 fix(slider): update value on mousedown instead of click
  src/lib/slider/slider.spec.ts
  src/lib/slider/slider.ts
Labels: cla: yes, pr: lgtm, pr: merge ready, target: patch

#12934 fix(stepper): intl provider not being picked up in lazy-loaded modules
  src/lib/stepper/stepper-intl.ts
  src/lib/stepper/stepper-module.ts
Labels: cla: yes, pr: lgtm, pr: merge ready, target: patch

#13201 fix(form-field): native select options blending in with dropdown background on a dark theme
  src/lib/input/_input-theme.scss
Labels: P2, cla: yes, pr: lgtm, pr: merge ready, target: patch

#13437 fix(text-field): autosize textarea not resizing on minRows decrease
  src/cdk/text-field/autosize.spec.ts
  src/cdk/text-field/autosize.ts
  src/demo-app/input/input-demo.html
  src/demo-app/input/input-demo.scss
Labels: cla: yes, pr: lgtm, pr: merge ready, target: patch

#13442 fix(menu): closing parent overlay when pressing escape
  src/lib/menu/menu-directive.ts
  src/lib/menu/menu-trigger.ts
  src/lib/menu/menu.spec.ts
Labels: cla: yes, pr: lgtm, pr: merge ready, target: patch

#13448 fix(datepicker): don't allow clicks on disabled cells in year and multi-year views
  src/lib/datepicker/calendar-body.spec.ts
  src/lib/datepicker/calendar-body.ts
  src/lib/datepicker/multi-year-view.html
  src/lib/datepicker/year-view.html
Labels: cla: yes, pr: lgtm, pr: merge ready, target: patch

#13481 chore: clean up unused catch clause parameters
  src/cdk/a11y/interactivity-checker/interactivity-checker.ts
  src/lib/toolbar/toolbar.spec.ts
  tools/dashboard/functions/jwt/verify-token.ts
  tools/gulp/util/task_helpers.ts
Labels: cla: yes, pr: lgtm, pr: merge ready, target: patch

#13487 fix(table): delimit words when filtering
  src/lib/table/table-data-source.ts
  src/lib/table/table.spec.ts
Labels: cla: yes, pr: lgtm, pr: merge ready, target: patch

#13492 fix(button-toggle): content shifting in IE11
  src/lib/button-toggle/button-toggle.scss
Labels: cla: yes, pr: lgtm, pr: merge ready, target: patch

#13507 refactor(sort): remove sort header dependency on table
  src/cdk/table/cell.ts
  src/lib/sort/BUILD.bazel
  src/lib/sort/sort-header.ts
  src/lib/table/cell.ts
Labels: cla: yes, pr: lgtm, pr: merge ready, target: patch

#13526 fix(drag-drop): use passive event listeners for start events
  src/cdk/drag-drop/drag.ts
Labels: cla: yes, pr: lgtm, pr: merge ready, target: patch

#13529 fix(drag-drop): preserve previous inline transform
  src/cdk/drag-drop/drag.spec.ts
  src/cdk/drag-drop/drag.ts
Labels: cla: yes, pr: lgtm, pr: merge ready, target: patch

#13531 fix(list): selection list moving focus when an option is destroyed
  src/lib/list/selection-list.spec.ts
  src/lib/list/selection-list.ts
Labels: a11y, cla: yes, pr: lgtm, pr: merge ready, target: patch

#13532 perf(focus-monitor): mark event listeners as passive
  src/cdk/a11y/focus-monitor/focus-monitor.ts
Labels: cla: yes, perf, pr: lgtm, pr: merge ready, target: patch

#13570 fix(radio): improved alignment for native validation messages
  src/lib/radio/radio.html
  src/lib/radio/radio.scss
Labels: cla: yes, pr: lgtm, pr: merge ready, target: patch

#13599 fix(menu): proper focus styling when opened by tap on a touch device
  src/lib/menu/menu-trigger.ts
  src/lib/menu/menu.spec.ts
Labels: cla: yes, pr: lgtm, pr: merge ready, target: patch

#13600 fix(expansion-panel): emitting events twice on some browsers
  src/lib/expansion/expansion-panel.html
  src/lib/expansion/expansion-panel.ts
Labels: cla: yes, pr: lgtm, pr: merge ready, target: patch

#13634 fix(autocomplete): not propagating same model value when reset while open
  src/lib/autocomplete/autocomplete-trigger.ts
  src/lib/autocomplete/autocomplete.spec.ts
Labels: cla: yes, pr: lgtm, pr: merge ready, target: patch

#13649 fix(sidenav): opened and closed events emitting twice on IE and Edge
  src/lib/sidenav/drawer.ts
  src/lib/sidenav/sidenav.ts
Labels: cla: yes, pr: lgtm, pr: merge ready, target: patch

#13628 fix(progress-bar): not taking current path after first initialization
  src/lib/progress-bar/progress-bar.spec.ts
  src/lib/progress-bar/progress-bar.ts
Labels: cla: yes, pr: lgtm, pr: merge ready, target: patch

#13652 fix(grid-list): unable to assign numeric zero as gutter size
  src/lib/grid-list/grid-list.spec.ts
  src/lib/grid-list/grid-list.ts
Labels: cla: yes, pr: lgtm, pr: merge ready, target: patch

#13369 refactor(list): convert MatLineSetter into a function
  src/lib/core/line/line.ts
  src/lib/grid-list/grid-tile.ts
  src/lib/list/list.ts
  src/lib/list/selection-list.ts
Labels: cla: yes, pr: lgtm, pr: merge ready, target: patch

#13691 doc(select): correct css styles in select panel custom styling example
  src/material-examples/select-panel-class/select-panel-class-example.css
Labels: cla: yes, pr: lgtm, pr: merge ready, pr: merge safe, target: patch

#13690 build: move aot and prerender jobs to circleci
  .circleci/config.yml
  .travis.yml
  tools/gulp/tasks/aot.ts
Labels: cla: yes, pr: lgtm, pr: merge ready, pr: merge safe, target: patch

#13360 fix(drag-drop): not picking up handle that isn't a direct descendant
  src/cdk/drag-drop/drag-handle.ts
  src/cdk/drag-drop/drag-parent.ts
  src/cdk/drag-drop/drag.spec.ts
  src/cdk/drag-drop/drag.ts
Labels: cla: yes, pr: lgtm, pr: merge ready, target: patch

#13533 refactor(platform): add utility to normalize passive event listener options
  src/cdk/a11y/focus-monitor/focus-monitor.ts
  src/cdk/drag-drop/drag-drop-registry.ts
  src/cdk/platform/features/passive-listeners.ts
  src/cdk/text-field/autofill.spec.ts
  src/cdk/text-field/autofill.ts
  src/lib/core/ripple/ripple-renderer.ts
Labels: caretaker note, cla: yes, pr: lgtm, pr: merge ready, target: patch

#13687 refactor(schematics): better ng-update success message
  src/cdk/schematics/ng-update/index.ts
  src/lib/schematics/ng-update/index.ts
Labels: cla: yes, pr: lgtm, pr: merge ready, pr: merge safe, target: patch

#13699 build: fix `getRemoteCommitSha` to only return the sha
  tools/release/git/git-client.ts
Labels: cla: yes, pr: lgtm, pr: merge ready, pr: merge safe, target: patch

#13706 build: bump dashboard to Angular 7 final and switch to yarn
  tools/dashboard/package-lock.json
  tools/dashboard/package.json
  tools/dashboard/yarn.lock
Labels: cla: yes, pr: lgtm, pr: merge ready, pr: merge safe, target: patch

#13747 chore: bump version to 7.0.1 w/ changelog
  CHANGELOG.md
  package.json
Labels: pr: lgtm, pr: merge ready, target: patch

#13748 chore: stage release script should create commit
  tools/release/stage-release.ts
Labels: cla: yes, pr: lgtm, pr: merge ready, pr: merge safe, target: patch

#13721 fix(button-toggle): webkit tap highlight conflicting with ripples
  src/lib/button-toggle/button-toggle.scss
Labels: cla: yes, pr: lgtm, pr: merge ready, target: patch

#13702 fix(slide-toggle): don't show hover ripples on touch devices
  src/lib/slide-toggle/slide-toggle.scss
Labels: cla: yes, pr: lgtm, pr: merge ready, target: patch

#13505 feat(tabs): add the ability to customize the animation duration
  src/lib/tabs/tab-body.html
  src/lib/tabs/tab-body.ts
  src/lib/tabs/tab-group.html
  src/lib/tabs/tab-group.ts
  src/lib/tabs/tabs-animations.ts
  src/lib/tabs/tabs.md
  src/material-examples/tab-group-animations/tab-group-animations-example.css
  src/material-examples/tab-group-animations/tab-group-animations-example.html
  src/material-examples/tab-group-animations/tab-group-animations-example.ts
Labels: P2, cla: yes, pr: lgtm, pr: merge ready, target: minor

#13153 feat(bottom-sheet): allow focus restoration to be disabled
  src/lib/bottom-sheet/bottom-sheet-config.ts
  src/lib/bottom-sheet/bottom-sheet-container.ts
  src/lib/bottom-sheet/bottom-sheet.spec.ts
Labels: cla: yes, pr: lgtm, pr: merge ready, target: minor

#13146 feat(paginator): allow paginator to be disabled
  src/demo-app/paginator/paginator-demo.html
  src/demo-app/paginator/paginator-demo.ts
  src/lib/paginator/paginator.html
  src/lib/paginator/paginator.spec.ts
  src/lib/paginator/paginator.ts
Labels: cla: yes, pr: lgtm, pr: merge ready, target: minor

#13772 build: update dgeni-packages version
  package.json
  scripts/ci/sources/mode.sh
  scripts/ci/travis-testing.sh
  scripts/closure-compiler/build-devapp-bundle.sh
  scripts/closure-compiler/tsconfig-rxjs.json
  tools/dgeni/index.ts
  tools/dgeni/processors/no-truncate-const-type.ts
  yarn.lock
Labels: cla: yes, pr: lgtm, pr: merge ready, pr: merge safe, target: patch
