Repository angular/components, pull requests merged in 2018-05, with the labels that each got.

#10946 refactor(layout): use single style tag for dynamically-created media queries
  src/cdk/layout/media-matcher.spec.ts
  src/cdk/layout/media-matcher.ts
Labels: cla: yes, pr: lgtm, pr: merge ready, target: patch

#10969 fix(sidenav): box shadow visible while closed when rendering on the server
  src/lib/sidenav/drawer-animations.ts
Labels: cla: yes, pr: lgtm, pr: merge ready, target: patch

#11059 fix(dialog): add generic parameter for the dialog result to open method
  src/lib/dialog/dialog.ts
Labels: cla: yes, pr: lgtm, pr: merge ready, target: patch

#11061 fix(select): unable to toggle multi select option after using the mouse
  src/lib/select/select.spec.ts
  src/lib/select/select.ts
Labels: a11y, cla: yes, pr: lgtm, pr: merge ready, target: patch

#11068 fix(paginator): handle negative pageSize and pageIndex correctly
  src/lib/paginator/paginator.spec.ts
  src/lib/paginator/paginator.ts
Labels: cla: yes, pr: lgtm, pr: merge ready, target: patch

#11070 fix(menu): not updating panel direction after init
  src/lib/menu/menu-trigger.ts
  src/lib/menu/menu.spec.ts
Labels: cla: yes, pr: lgtm, pr: merge ready, target: patch

#11072 fix(overlay): error when rendering flexible overlay on the server
  src/cdk/overlay/position/connected-position-strategy.ts
  src/cdk/overlay/position/flexible-connected-position-strategy.ts
  src/cdk/overlay/position/overlay-position-builder.ts
Labels: cla: yes, pr: lgtm, pr: merge ready, target: patch

#10916 fix(autocomplete): panel direction not being updated if the trigger direction changes
  src/lib/autocomplete/autocomplete-trigger.ts
  src/lib/autocomplete/autocomplete.spec.ts
Labels: cla: yes, pr: lgtm, pr: merge ready, target: patch

#10811 fix(form-field): scrollbars appear on autosize textarea in chrome
  src/cdk/text-field/_text-field.scss
  src/cdk/text-field/autosize.ts
  src/lib/input/input.scss
Labels: cla: yes, pr: lgtm, pr: merge ready, target: patch

#11029 fix(list): selection list always firing change event for selectAll and deselectAll
  src/lib/list/selection-list.spec.ts
  src/lib/list/selection-list.ts
Labels: cla: yes, pr: lgtm, pr: merge ready, target: patch

#11085 virtual-scroll: fix updating when data changes and add trackBy demos
  src/cdk-experimental/scrolling/virtual-for-of.ts
  src/demo-app/virtual-scroll/virtual-scroll-demo.html
  src/demo-app/virtual-scroll/virtual-scroll-demo.scss
  src/demo-app/virtual-scroll/virtual-scroll-demo.ts
Labels: cla: yes, pr: needs review

#10627 fix(form-field,select): handle form field controls inside toolbar
  src/demo-app/toolbar/toolbar-demo.html
  src/lib/toolbar/_toolbar-theme.scss
Labels: cla: yes, pr: lgtm, pr: merge ready, target: minor

#11092 chore: remove @kara from codeowners as she no longer works on material2
  .github/CODEOWNERS
Labels: cla: yes, pr: lgtm, pr: merge ready, pr: merge safe, target: master only

#11066 build: fix dashboard compilation errors
  tools/dashboard/package.json
Labels: cla: yes, pr: lgtm, pr: merge ready, pr: merge safe, target: master only

#11062 fix(form-field): inconsistent underline height at different DPIs
  src/lib/core/style/_form-common.scss
  src/lib/form-field/form-field.scss
Labels: cla: yes, pr: lgtm, pr: merge ready, target: patch

#10905 fix(select): losing focus position when tabbing away after clicking inside multi select
  src/lib/select/select.spec.ts
  src/lib/select/select.ts
Labels: cla: yes, pr: lgtm, pr: merge ready, target: patch

#11045 chore: fix test leaking overlay elements
  src/lib/menu/menu.spec.ts
Labels: cla: yes, pr: lgtm, pr: merge ready, pr: merge safe, target: master only

#11095 chore: do not require reviews for material github bot
  .github/angular-robot.yml
Labels: cla: yes, pr: lgtm, pr: merge ready, pr: merge safe, target: master only

#11091 docs: update information about schematics
  guides/schematics.md
Labels: P1, cla: yes, pr: lgtm, pr: merge ready, pr: merge safe, target: master only

#10132 fix(menu): unable to open same sub-menu from different triggers and not picking up indirect descendant items
  src/cdk/a11y/key-manager/list-key-manager.ts
  src/lib/menu/menu-directive.ts
  src/lib/menu/menu-item.ts
  src/lib/menu/menu-panel.ts
  src/lib/menu/menu-trigger.ts
  src/lib/menu/menu.html
  src/lib/menu/menu.spec.ts
Labels: cla: yes, pr: lgtm, pr: merge ready, target: patch

#10964 feat(table): enable multiple data rows
  package-lock.json
  src/cdk/table/BUILD.bazel
  src/cdk/table/render-rows.md
  src/cdk/table/row.ts
  src/cdk/table/table-errors.ts
  src/cdk/table/table.spec.ts
  src/cdk/table/table.ts
  src/demo-app/table/expandable-rows/expandable-rows.html
  src/demo-app/table/expandable-rows/expandable-rows.ts
  src/demo-app/table/routes.ts
  src/demo-app/table/table-demo-module.ts
  src/demo-app/table/table-demo-page.ts
  src/demo-app/table/when-rows/when-rows.html
  src/demo-app/table/when-rows/when-rows.ts
  src/lib/table/table.spec.ts
Labels: caretaker note, cla: yes, pr: lgtm, pr: merge ready, target: minor

#11102 Revert "feat(table): enable multiple data rows"
  package-lock.json
  src/cdk/table/BUILD.bazel
  src/cdk/table/render-rows.md
  src/cdk/table/row.ts
  src/cdk/table/table-errors.ts
  src/cdk/table/table.spec.ts
  src/cdk/table/table.ts
  src/demo-app/table/expandable-rows/expandable-rows.html
  src/demo-app/table/expandable-rows/expandable-rows.ts
  src/demo-app/table/routes.ts
  src/demo-app/table/table-demo-module.ts
  src/demo-app/table/table-demo-page.ts
  src/demo-app/table/when-rows/when-rows.html
  src/demo-app/table/when-rows/when-rows.ts
  src/lib/table/table.spec.ts
Labels: cla: yes, pr: lgtm, pr: merge ready, target: master only

#11104 docs: add badge example and fix some tree docs formatting
  src/cdk/tree/tree.md
  src/lib/badge/badge.md
  src/lib/tree/tree.md
  src/material-examples/autocomplete-optgroup/autocomplete-optgroup-example.ts
  src/material-examples/badge-overview/badge-overview-example.css
  src/material-examples/badge-overview/badge-overview-example.html
  src/material-examples/badge-overview/badge-overview-example.ts
Labels: P2, cla: yes, docs, pr: lgtm, pr: merge ready, pr: merge safe, target: master only

#11105 docs(expansion): fix directive typo
  src/lib/expansion/expansion-panel-header.ts
Labels: cla: yes, pr: lgtm, pr: merge ready, pr: merge safe, target: patch

#11060 build: fix screenshot tool compilation errors
  tools/screenshot-test/package-lock.json
  tools/screenshot-test/package.json
Labels: cla: yes, pr: lgtm, pr: merge ready, pr: merge safe, target: master only

#11115 fix(ng-update): work with yarn
  src/lib/schematics/update/update.ts
Labels: P1, cla: yes, pr: lgtm, pr: merge ready, pr: merge safe, target: master only

#11120 ci: add config for size plugin of the github rebot
  .github/angular-robot.yml
Labels: cla: yes, pr: lgtm, pr: merge ready, pr: merge safe, target: master only

#11138 chore: fix tabs.md to have lazy loading be a linkable header in docs
  src/lib/tabs/tabs.md
Labels: cla: yes, pr: lgtm, pr: merge ready, pr: merge safe, target: master only

#11140 chore: bump version and create changelog for version 6.0.0
  CHANGELOG.md
  package.json
Labels: cla: yes, pr: lgtm, pr: merge ready, pr: merge safe, target: master only

#11103 fix(tree) make change detection less often
  src/cdk/tree/tree.spec.ts
  src/cdk/tree/tree.ts
Labels: cla: yes, pr: lgtm, pr: merge ready, target: patch

#11122 change OnInit to AfterViewInit to load MatSort before http table request
  src/material-examples/table-http/table-http-example.ts
Labels: cla: yes, docs, pr: lgtm, pr: merge ready, pr: merge safe, target: master only

#11111 chore: fix error when running demo app in IE11
  src/demo-app/index.html
Labels: cla: yes, pr: lgtm, pr: merge ready, pr: merge safe, target: master only

#11141 docs(tooltip): expand a11y section with guidance on interactions
  src/lib/tooltip/tooltip.md
Labels: cla: yes, docs, pr: lgtm, pr: merge ready, pr: merge safe, target: patch

#11150 build: bump screenshot tool to Angular 6
  tools/screenshot-test/angular-cli.json
  tools/screenshot-test/angular.json
  tools/screenshot-test/package-lock.json
  tools/screenshot-test/package.json
  tools/screenshot-test/src/app/firebase.service.ts
Labels: cla: yes, pr: lgtm, pr: merge ready, pr: merge safe, target: master only

#11143 fix(chips): stacked chips overflowing chip list
  src/lib/chips/chips.scss
Labels: cla: yes, pr: lgtm, pr: merge ready, target: patch

#11108 fix(form-field): error on IE11 when using outline appearance
  src/lib/form-field/form-field.ts
Labels: cla: yes, pr: lgtm, pr: merge ready, target: patch

#11056 fix(radio): update MatRadioButton disabled setter to trigger change detection
  src/lib/radio/radio.spec.ts
  src/lib/radio/radio.ts
Labels: G, cla: yes, pr: lgtm, pr: merge ready, target: patch

#11049 fix(datepicker): don't autofocus calendar cell if used outside of overlay
  src/lib/datepicker/calendar.spec.ts
  src/lib/datepicker/calendar.ts
  src/lib/datepicker/datepicker.ts
  src/lib/datepicker/month-view.ts
  src/lib/datepicker/multi-year-view.ts
  src/lib/datepicker/year-view.ts
Labels: cla: yes, pr: lgtm, pr: merge ready, target: patch

#10915 fix(icon): log full error message when icon set fails to load
  src/lib/icon/icon-registry.ts
  src/lib/icon/icon.spec.ts
Labels: cla: yes, pr: lgtm, pr: merge ready, target: patch

#11116 feat(table): enable multiple data rows
  src/cdk/table/BUILD.bazel
  src/cdk/table/render-rows.md
  src/cdk/table/row.ts
  src/cdk/table/table-errors.ts
  src/cdk/table/table.spec.ts
  src/cdk/table/table.ts
  src/demo-app/table/expandable-rows/expandable-rows.html
  src/demo-app/table/expandable-rows/expandable-rows.ts
  src/demo-app/table/routes.ts
  src/demo-app/table/table-demo-module.ts
  src/demo-app/table/table-demo-page.ts
  src/demo-app/table/when-rows/when-rows.html
  src/demo-app/table/when-rows/when-rows.ts
  src/lib/table/table.spec.ts
Labels: cla: yes, pr: lgtm, pr: merge ready, target: minor

#10549 fix(focus-monitor): reenter ngzone before emitting
  src/cdk/a11y/focus-monitor/focus-monitor.spec.ts
  src/cdk/a11y/focus-monitor/focus-monitor.ts
Labels: cla: yes, pr: lgtm, pr: merge ready, target: patch

#11142 feat(autocomplete): allow autocomplete panel to be disabled
  src/lib/autocomplete/BUILD.bazel
  src/lib/autocomplete/autocomplete-trigger.ts
  src/lib/autocomplete/autocomplete.spec.ts
Labels: cla: yes, pr: lgtm, pr: merge ready, target: minor

#11164 docs(table): fix table footer doc
  src/material-examples/table-footer-row/table-footer-row-example.html
Labels: cla: yes, pr: lgtm, pr: merge ready, pr: merge safe, target: patch

#10881 fix(progress-bar/progress-spinner): prevent animations when in a noopanimations module context
  src/lib/core/style/_noop-animation.scss
  src/lib/progress-bar/progress-bar.scss
  src/lib/progress-bar/progress-bar.ts
  src/lib/progress-spinner/progress-spinner.scss
  src/lib/progress-spinner/progress-spinner.ts
Labels: cla: yes, pr: lgtm, pr: merge ready, target: minor

#11163 fix(ng-add): install added packages
  src/lib/schematics/shell/index.ts
Labels: cla: yes, pr: lgtm, pr: merge ready, target: patch

#11204 chore: 6.0.1 release
  CHANGELOG.md
  package-lock.json
  package.json
Labels: cla: yes, pr: lgtm, pr: merge ready, pr: merge safe, target: patch

#11137 virtual-scroll: add logic to correct the scroll position as user move…
  src/cdk-experimental/scrolling/auto-size-virtual-scroll.ts
  src/cdk-experimental/scrolling/fixed-size-virtual-scroll.ts
  src/cdk-experimental/scrolling/virtual-for-of.ts
  src/cdk-experimental/scrolling/virtual-scroll-strategy.ts
  src/cdk-experimental/scrolling/virtual-scroll-viewport.ts
  src/demo-app/virtual-scroll/virtual-scroll-demo.html
  src/demo-app/virtual-scroll/virtual-scroll-demo.ts
Labels: cla: yes, pr: needs review, target: master only

#11192 fix(scrolling): adds right to fix pushed content
  src/cdk-experimental/scrolling/virtual-scroll-viewport.scss
  src/cdk-experimental/scrolling/virtual-scroll-viewport.ts
Labels: cla: yes, pr: lgtm, pr: merge ready, pr: merge safe

#11214 fix(icon): remove duplicate icon registry provider
  package-lock.json
  src/lib/icon/icon-module.ts
Labels: cla: yes, pr: lgtm, pr: merge ready, target: patch

#11218 chore: update README.md with new available features that came with v6
  README.md
Labels: cla: yes, pr: lgtm, pr: merge ready, pr: merge safe, target: master only

#11190 fix(autocomplete): panel blending in with background in high contrast mode
  src/lib/autocomplete/autocomplete.scss
Labels: a11y, cla: yes, pr: lgtm, pr: merge ready, target: patch

#11186 fix(stepper): error being thrown if selected step is accessed too early
  src/cdk/stepper/stepper.ts
  src/lib/stepper/stepper.spec.ts
Labels: cla: yes, pr: lgtm, pr: merge ready, target: patch

#11185 chore: fix syntax error in tree readme
  src/cdk/tree/tree.md
  src/lib/tree/tree.md
Labels: cla: yes, pr: lgtm, pr: merge ready, pr: merge safe, target: patch

#11181 fix(button): ripples not being clipped by button border radius
  src/lib/button/button.scss
Labels: cla: yes, pr: lgtm, pr: merge ready, target: patch

#11225 fix(sidenav-demo): trigger event opened
  src/demo-app/sidenav/sidenav-demo.html
Labels: cla: yes, pr: lgtm, pr: merge ready, pr: merge safe, target: master only

#11189 fix: add custom theme using string ref in angular.json
  src/lib/schematics/utils/ast.ts
Labels: cla: yes, pr: lgtm, pr: merge ready, pr: merge safe, target: patch

#11098 fix(checkbox): update MatCheckbox disabled setter to trigger change detection
  src/lib/checkbox/checkbox.spec.ts
  src/lib/checkbox/checkbox.ts
Labels: cla: yes, pr: lgtm, pr: merge ready, target: patch

#11179 chore: remove references to the web animations polyfill
  guides/getting-started.md
  package-lock.json
  package.json
  src/demo-app/index.html
  src/e2e-app/index.html
  tools/gulp/tasks/development.ts
Labels: cla: yes, pr: lgtm, pr: merge ready, pr: merge safe, target: master only

#11241 docs(overlay): fix typos in flex position strategy comments
  src/cdk/overlay/position/flexible-connected-position-strategy.ts
Labels: cla: yes, pr: lgtm, pr: merge ready, pr: merge safe, target: patch

#11175 docs(chips): use consistent data structure in autocomplete example
  src/material-examples/chips-autocomplete/chips-autocomplete-example.html
  src/material-examples/chips-autocomplete/chips-autocomplete-example.ts
Labels: cla: yes, pr: lgtm, pr: merge ready, pr: merge safe, target: master only

#10711 docs: hammerjs using systemjs.config
  guides/getting-started.md
Labels: cla: yes, pr: lgtm, pr: merge ready, pr: merge safe, target: master only

#11119 docs(table): fix example not correctly changing pages when filtering
  src/material-examples/table-overview/table-overview-example.ts
Labels: cla: yes, docs, pr: lgtm, pr: merge ready, pr: merge safe, target: patch

#11257 docs(button): document mat-stroked-button
  src/lib/button/button.md
Labels: cla: yes, docs, pr: lgtm, pr: merge ready, pr: merge safe, target: patch

#11252 fix(table): add missing constructors
  src/lib/table/cell.ts
  src/lib/table/row.ts
Labels: cla: yes, pr: lgtm, pr: merge ready, target: patch

#11250 chore: clear outdated overlay demo
  src/demo-app/demo-app/demo-app.ts
  src/demo-app/demo-app/demo-module.ts
  src/demo-app/demo-app/routes.ts
  src/demo-app/overlay/overlay-demo.html
  src/demo-app/overlay/overlay-demo.scss
  src/demo-app/overlay/overlay-demo.ts
Labels: cla: yes, pr: lgtm, pr: merge ready, pr: merge safe, target: master only

#11248 chore: update dgeni-packages
  package-lock.json
  package.json
Labels: cla: yes, pr: lgtm, pr: merge ready, pr: merge safe, target: patch

#11235 fix(dialog): min-height and max-height not having an effect on dialog container
  src/lib/dialog/dialog.scss
Labels: cla: yes, pr: lgtm, pr: merge ready, target: patch

#11231 perf(sidenav): avoid hitting zone continuously when using autosize option
  src/lib/sidenav/drawer.ts
  src/lib/sidenav/sidenav.ts
Labels: cla: yes, pr: lgtm, pr: merge ready, target: patch

#11226 Expose isIconButton publicly
  src/lib/button/button.html
  src/lib/button/button.ts
Labels: cla: yes, pr: lgtm, pr: merge ready, target: minor

#11205 fix(ripple): disable ripple animations when using NoopAnimationsModule
  src/lib/core/ripple/ripple.spec.ts
  src/lib/core/ripple/ripple.ts
Labels: cla: yes, pr: lgtm, pr: merge ready, target: patch

#11180 fix(sidenav): disable all sidenav animations when using NoopAnimationsModule
  src/lib/sidenav/drawer.scss
  src/lib/sidenav/drawer.spec.ts
  src/lib/sidenav/drawer.ts
Labels: cla: yes, pr: lgtm, pr: merge ready, target: patch

#11113 chore: use table examples for demo app
  src/demo-app/demo-app/routes.ts
  src/demo-app/example/example-list.ts
  src/demo-app/example/example.ts
  src/demo-app/table/custom-table/custom-table.ts
  src/demo-app/table/data-input-table/data-input-table.ts
  src/demo-app/table/dynamic-columns/dynamic-columns.html
  src/demo-app/table/dynamic-columns/dynamic-columns.ts
  src/demo-app/table/element-data.ts
  src/demo-app/table/mat-table-data-source/mat-table-data-source.html
  src/demo-app/table/mat-table-data-source/mat-table-data-source.ts
  src/demo-app/table/people-database.ts
  src/demo-app/table/person-data-source.ts
  src/demo-app/table/person-detail-data-source.ts
  src/demo-app/table/routes.ts
  src/demo-app/table/row-context/row-context.html
  src/demo-app/table/row-context/row-context.ts
  src/demo-app/table/table-demo-module.ts
  src/demo-app/table/table-demo-page.html
  src/demo-app/table/table-demo-page.ts
  src/demo-app/table/table-demo.html
  src/demo-app/table/table-demo.ts
Labels: cla: yes, pr: lgtm, pr: merge ready, pr: merge safe, target: master only

#11109 fix(autosize): error thrown by IE in some cases when component is destroyed
  src/cdk/text-field/autosize.ts
Labels: cla: yes, pr: lgtm, pr: merge ready, target: patch

#11067 fix(stepper): handle keyboard interactions if direction changes after init
  src/cdk/stepper/stepper.ts
  src/lib/stepper/stepper.spec.ts
Labels: cla: yes, pr: lgtm, pr: merge ready, target: patch

#10903 fix(tabs): handle long tab labels in mat-tab-nav-bar
  src/lib/tabs/tab-nav-bar/tab-nav-bar.scss
Labels: cla: yes, pr: lgtm, pr: merge ready, target: patch

#11069 feat(overlay): expose flexible overlay features through CdkConnectedOverlay
  src/cdk/overlay/overlay-directives.spec.ts
  src/cdk/overlay/overlay-directives.ts
  src/cdk/overlay/position/flexible-connected-position-strategy.ts
Labels: cla: yes, pr: lgtm, pr: merge ready, target: minor

#10877 feat(elevation): preserve the alpha value of the provided color
  guides/elevation.md
  src/lib/core/style/_elevation.scss
Labels: cla: yes, pr: lgtm, pr: merge ready, target: minor

#10952 fix(datepicker): dateInput event being fired if the value hasn't changed
  src/lib/datepicker/datepicker-input.ts
  src/lib/datepicker/datepicker.spec.ts
Labels: cla: yes, pr: lgtm, pr: merge ready, target: patch

#11255 virtual-scroll: add tests for fixed size items
  src/cdk-experimental/scrolling/BUILD.bazel
  src/cdk-experimental/scrolling/fixed-size-virtual-scroll.ts
  src/cdk-experimental/scrolling/virtual-scroll-viewport.spec.ts
  src/cdk-experimental/scrolling/virtual-scroll-viewport.ts
  src/demo-app/virtual-scroll/virtual-scroll-demo.scss
Labels: cla: yes, pr: lgtm

#11270 docs: fix typo in schematics guide
  guides/schematics.md
Labels: cla: yes, docs, pr: lgtm, pr: merge ready, pr: merge safe, target: patch

#11277 Revert "fix(tabs): handle long tab labels in mat-tab-nav-bar (#10903)"
  src/lib/tabs/tab-nav-bar/tab-nav-bar.scss
Labels: cla: yes, pr: lgtm, pr: merge ready

#11278 build: fix and re-enable bazel unit tests for the cdk
  .circleci/config.yml
  BUILD.bazel
  WORKSPACE
  package.json
  src/cdk/a11y/BUILD.bazel
  src/cdk/accordion/BUILD.bazel
  src/cdk/bidi/BUILD.bazel
  src/cdk/coercion/BUILD.bazel
  src/cdk/collections/BUILD.bazel
  src/cdk/layout/BUILD.bazel
  src/cdk/observers/BUILD.bazel
  src/cdk/portal/BUILD.bazel
  src/cdk/scrolling/BUILD.bazel
  src/cdk/table/BUILD.bazel
Labels: cla: yes, pr: lgtm, pr: merge ready, pr: merge safe, target: master only

#11275 virtual-scroll: add tests for `cdkVirtualFor` logic
  src/cdk-experimental/scrolling/BUILD.bazel
  src/cdk-experimental/scrolling/virtual-for-of.ts
  src/cdk-experimental/scrolling/virtual-scroll-viewport.scss
  src/cdk-experimental/scrolling/virtual-scroll-viewport.spec.ts
  src/cdk-experimental/scrolling/virtual-scroll-viewport.ts
  src/cdk/collections/array-data-source.ts
Labels: cla: yes, pr: lgtm, pr: merge ready

#10768 chore: add missing lifecycles interfaces to declarations
  package-lock.json
  package.json
  src/cdk-experimental/dialog/dialog-container.ts
  src/cdk/a11y/aria-describer/aria-describer.ts
  src/cdk/portal/portal-directives.ts
  src/cdk/table/row.ts
  src/cdk/table/table.spec.ts
  src/cdk/table/table.ts
  src/cdk/tree/tree.ts
  src/demo-app/a11y/table/table-a11y.ts
  src/demo-app/example/example.ts
  src/demo-app/stepper/stepper-demo.ts
  src/demo-app/table/custom-table/custom-table.ts
  src/demo-app/table/custom-table/simple-column.ts
  src/demo-app/table/custom-table/wrapper-table.ts
  src/demo-app/table/expandable-rows/expandable-rows.ts
  src/demo-app/tabs/tabs-demo.ts
  src/lib/core/option/option.ts
  src/lib/menu/menu-trigger.ts
  src/lib/sidenav/drawer.ts
  src/lib/sort/sort-header.ts
  src/lib/stepper/stepper.spec.ts
  src/lib/table/table.spec.ts
  src/lib/tabs/tab-body.spec.ts
  src/lib/tabs/tab-group.spec.ts
  src/lib/tabs/tab-nav-bar/tab-nav-bar.ts
  src/lib/tree/node.ts
  src/material-examples/autocomplete-auto-active-first-option/autocomplete-auto-active-first-option-example.ts
  src/material-examples/autocomplete-display/autocomplete-display-example.ts
  src/material-examples/autocomplete-filter/autocomplete-filter-example.ts
  src/material-examples/cdk-tree-flat/cdk-tree-flat-example.ts
  src/material-examples/cdk-tree-nested/cdk-tree-nested-example.ts
  src/material-examples/sidenav-responsive/sidenav-responsive-example.ts
  src/material-examples/stepper-editable/stepper-editable-example.ts
  src/material-examples/stepper-optional/stepper-optional-example.ts
  src/material-examples/stepper-overview/stepper-overview-example.ts
  src/material-examples/table-overview/table-overview-example.ts
  src/material-examples/table-pagination/table-pagination-example.ts
  src/material-examples/table-sorting/table-sorting-example.ts
  tslint.json
Labels: cla: yes, pr: lgtm, pr: merge ready, target: patch

#10868 feat(overlay): add support for automatically setting the transform-origin based on the current position
  src/cdk/overlay/overlay.md
  src/cdk/overlay/position/flexible-connected-position-strategy.spec.ts
  src/cdk/overlay/position/flexible-connected-position-strategy.ts
  src/lib/core/style/_menu-common.scss
  src/lib/datepicker/datepicker-content.scss
  src/lib/datepicker/datepicker.spec.ts
  src/lib/datepicker/datepicker.ts
  src/lib/menu/menu-directive.ts
  src/lib/menu/menu-panel.ts
  src/lib/menu/menu-trigger.ts
  src/lib/menu/menu.scss
  src/lib/menu/menu.spec.ts
  src/lib/tooltip/tooltip.html
  src/lib/tooltip/tooltip.spec.ts
  src/lib/tooltip/tooltip.ts
Labels: cla: yes, pr: lgtm, pr: merge ready, target: minor

#11245 feat(table): allow multiple header/footer rows
  src/cdk/table/table-errors.ts
  src/cdk/table/table.spec.ts
  src/cdk/table/table.ts
  src/lib/table/table.spec.ts
  src/material-examples/table-multiple-header-footer/table-multiple-header-footer-example.css
  src/material-examples/table-multiple-header-footer/table-multiple-header-footer-example.html
  src/material-examples/table-multiple-header-footer/table-multiple-header-footer-example.ts
Labels: cla: yes, pr: lgtm, pr: merge ready, target: minor

#11264 refactor: remove deprecated injector.get signature usages
  src/cdk-experimental/dialog/dialog.ts
  src/lib/bottom-sheet/bottom-sheet.ts
  src/lib/dialog/dialog.ts
Labels: cla: yes, pr: lgtm, pr: merge ready, target: master only

#11267 feat(tree): Add support for trackBy
  src/cdk/tree/nested-node.ts
  src/cdk/tree/tree.md
  src/cdk/tree/tree.spec.ts
  src/cdk/tree/tree.ts
Labels: cla: yes, pr: lgtm, pr: merge ready, target: minor

#11288 docs: consistent links to Material spec
  guides/elevation.md
  guides/theming-your-components.md
  guides/theming.md
  src/lib/checkbox/checkbox.ts
  src/lib/core/gestures/gesture-config.ts
  src/lib/core/style/_elevation.scss
  src/lib/core/theming/_palette.scss
  src/lib/grid-list/grid-list.md
  src/lib/schematics/shell/custom-theme.ts
  src/lib/tabs/tab-group.ts
Labels: cla: yes, pr: lgtm, pr: merge ready, pr: merge safe, target: patch

#11287 build: fix tests crashing IE test runs
  src/cdk/overlay/position/flexible-connected-position-strategy.spec.ts
Labels: cla: yes, pr: lgtm, pr: merge ready, pr: merge safe, target: master only

#11283 docs: Add name flag to commands in Schematic guide
  guides/schematics.md
Labels: cla: yes, pr: lgtm, pr: merge ready, pr: merge safe, target: patch

#11295 virtual-scroll: add some basic tests for autosize
  src/cdk-experimental/scrolling/virtual-scroll-viewport.spec.ts
  src/cdk-experimental/scrolling/virtual-scroll-viewport.ts
Labels: cla: yes, pr: lgtm, pr: merge ready, pr: merge safe

#11327 chore: update version and changelog for 6.0.2
  CHANGELOG.md
  package.json
Labels: cla: yes, pr: lgtm, pr: merge ready, pr: merge safe, target: master only

#11263 Apply styling to .mat-tab-label-content which is a child element
  src/lib/tabs/_tabs-common.scss
Labels: cla: yes, pr: lgtm, pr: merge ready, target: patch

#11305 fix(expansion-panel): inconsistent margin for nested panels
  src/lib/expansion/expansion-panel.scss
Labels: cla: yes, pr: lgtm, pr: merge ready, target: patch

#11302 refactor(dialog,bottom-sheet,snack-bar): use injector to pass config to container instance
  src/cdk-experimental/dialog/dialog-container.ts
  src/cdk-experimental/dialog/dialog.ts
  src/cdk/overlay/position/flexible-connected-position-strategy.ts
  src/lib/bottom-sheet/bottom-sheet-container.ts
  src/lib/bottom-sheet/bottom-sheet.ts
  src/lib/dialog/dialog-container.ts
  src/lib/dialog/dialog.ts
  src/lib/snack-bar/snack-bar-container.ts
  src/lib/snack-bar/snack-bar.ts
Labels: cla: yes, pr: lgtm, pr: merge ready, target: patch

#11285 fix(dialog,bottom-sheet): don't provide directionality if no direction is set
  src/cdk-experimental/dialog/dialog.spec.ts
  src/cdk-experimental/dialog/dialog.ts
  src/lib/bottom-sheet/bottom-sheet.spec.ts
  src/lib/bottom-sheet/bottom-sheet.ts
  src/lib/dialog/dialog.spec.ts
  src/lib/dialog/dialog.ts
  src/lib/sidenav/drawer.ts
Labels: cla: yes, pr: lgtm, pr: merge ready, target: patch

#11303 chore(sort): include sort theme and typography in theme mixin
  src/lib/core/theming/_all-theme.scss
  src/lib/core/typography/_all-typography.scss
  src/lib/sort/_sort-theme.scss
Labels: cla: yes, pr: lgtm, pr: merge ready, target: master only

#11170 feat(observe-content): refactor so logic can be used without directive
  src/cdk/observers/observe-content.spec.ts
  src/cdk/observers/observe-content.ts
Labels: cla: yes, pr: lgtm, pr: merge ready, target: minor

#11322 refactor(overlay): allow HTMLElement to be passed in directly to connected position
  src/cdk/overlay/position/flexible-connected-position-strategy.spec.ts
  src/cdk/overlay/position/flexible-connected-position-strategy.ts
  src/cdk/overlay/position/overlay-position-builder.ts
Labels: cla: yes, pr: lgtm, pr: merge ready, target: patch

#11292 fix(button-toggle): fix button toggle with 0 value not checked
  src/lib/button-toggle/button-toggle.spec.ts
  src/lib/button-toggle/button-toggle.ts
Labels: cla: yes, pr: lgtm, pr: merge ready, target: patch

#11249 fix(checkbox): disable animations when using NoopAnimationsModule
  src/lib/checkbox/checkbox.scss
  src/lib/checkbox/checkbox.ts
Labels: cla: yes, pr: lgtm, pr: merge ready, target: patch

#11296 fix(radio): disable animations when using NoopAnimationsModule
  src/lib/radio/radio.scss
  src/lib/radio/radio.ts
Labels: cla: yes, pr: lgtm, pr: merge ready, target: patch

#11167 feat(cdk-input): change autosize to be bindable (#9884)
  src/cdk/text-field/BUILD.bazel
  src/cdk/text-field/autosize.spec.ts
  src/cdk/text-field/autosize.ts
  src/demo-app/input/input-demo.html
  src/demo-app/input/input-demo.ts
  src/lib/input/autosize.ts
Labels: cla: yes, pr: lgtm, pr: merge ready, target: minor

#11230 fix(snack-bar): snack bar not animating in if no positions are passed in
  src/lib/snack-bar/snack-bar.spec.ts
  src/lib/snack-bar/snack-bar.ts
Labels: cla: yes, pr: lgtm, pr: merge ready, target: patch

#11345 virtual-scroll: add e2e tests for autosize scroll strategy
  .github/CODEOWNERS
  e2e/components/virtual-scroll-e2e.spec.ts
  src/cdk-experimental/scrolling/virtual-scroll-viewport.scss
  src/e2e-app/e2e-app-module.ts
  src/e2e-app/e2e-app/e2e-app.html
  src/e2e-app/e2e-app/routes.ts
  src/e2e-app/tsconfig-build.json
  src/e2e-app/virtual-scroll/virtual-scroll-e2e.css
  src/e2e-app/virtual-scroll/virtual-scroll-e2e.html
  src/e2e-app/virtual-scroll/virtual-scroll-e2e.ts
  tools/gulp/tasks/e2e.ts
  tools/package-tools/rollup-globals.ts
Labels: cla: yes

#11310 fix(nav-schematics): Subscribe to breakpoint observable
  src/lib/schematics/nav/files/__path__/__name@dasherize@if-flat__/__name@dasherize__.component.html
  src/lib/schematics/nav/files/__path__/__name@dasherize@if-flat__/__name@dasherize__.component.ts
Labels: cla: yes, pr: lgtm, pr: merge ready, pr: merge safe, target: master only

#11347 chore: fix lint failure
  src/material-examples/stepper-vertical/stepper-vertical-example.ts
Labels: cla: yes, pr: lgtm, pr: merge ready, pr: merge safe, target: master only

#8533 fix(autocomplete): return consistent output from panelClosingActions
  src/lib/autocomplete/autocomplete-trigger.ts
  src/lib/autocomplete/autocomplete.spec.ts
Labels: cla: yes, pr: lgtm, pr: merge ready, presubmit failures, target: patch

#11213 fix(overlay): injection errors for scroll strategy providers in lazy-loaded modules
  src/cdk/overlay/overlay-directives.ts
  src/cdk/overlay/overlay-module.ts
  src/lib/autocomplete/autocomplete-module.ts
  src/lib/autocomplete/autocomplete-trigger.ts
  src/lib/datepicker/datepicker-module.ts
  src/lib/datepicker/datepicker.ts
  src/lib/dialog/dialog.ts
  src/lib/menu/menu-module.ts
  src/lib/menu/menu-trigger.ts
  src/lib/tooltip/tooltip-module.ts
  src/lib/tooltip/tooltip.ts
Labels: P2, cla: yes, pr: lgtm, pr: merge ready, target: patch

#11193 fix(scrolling): scrollbar jump when data change on scroll
  src/cdk-experimental/scrolling/auto-size-virtual-scroll.ts
Labels: cla: yes, pr: lgtm, pr: merge ready

#11324 fix(tooltip): not handling direction changes after the first open
  src/cdk/overlay/overlay-ref.ts
  src/lib/tooltip/tooltip.spec.ts
  src/lib/tooltip/tooltip.ts
Labels: cla: yes, pr: lgtm, pr: merge ready, target: patch

#11440 chore: bump the version to 6.1.0 with changelog
  CHANGELOG.md
  package.json
  src/lib/schematics/utils/lib-versions.ts
Labels: cla: yes, pr: lgtm, pr: merge ready, pr: merge safe, target: master only

#11420 chore: fix typo in form field docs
  src/lib/form-field/form-field.md
Labels: cla: yes, pr: lgtm, pr: merge ready, pr: merge safe, target: master only

#8199 feat(expansion): allow expansion indicator positioning.
  src/demo-app/expansion/expansion-demo.html
  src/demo-app/expansion/expansion-demo.ts
  src/lib/expansion/_expansion-theme.scss
  src/lib/expansion/accordion.spec.ts
  src/lib/expansion/accordion.ts
  src/lib/expansion/expansion-animations.ts
  src/lib/expansion/expansion-panel-header.html
  src/lib/expansion/expansion-panel-header.scss
  src/lib/expansion/expansion-panel-header.ts
  src/lib/expansion/expansion-panel.ts
  src/lib/expansion/expansion.md
  src/lib/expansion/expansion.spec.ts
Labels: caretaker note, cla: yes, pr: lgtm, pr: merge ready, target: minor

#11466 Revert "feat(expansion): allow expansion indicator positioning."
  src/demo-app/expansion/expansion-demo.html
  src/demo-app/expansion/expansion-demo.ts
  src/lib/expansion/_expansion-theme.scss
  src/lib/expansion/accordion.spec.ts
  src/lib/expansion/accordion.ts
  src/lib/expansion/expansion-animations.ts
  src/lib/expansion/expansion-panel-header.html
  src/lib/expansion/expansion-panel-header.scss
  src/lib/expansion/expansion-panel-header.ts
  src/lib/expansion/expansion-panel.ts
  src/lib/expansion/expansion.md
  src/lib/expansion/expansion.spec.ts
Labels: cla: yes

#11349 fix(checkbox,radio): remove webkit tap highlights
  src/lib/checkbox/checkbox.scss
  src/lib/radio/radio.scss
Labels: cla: yes, pr: lgtm, pr: merge ready, target: patch

#11393 fix(overlay): incorrect position when using flexible positioning and rtl on the body
  src/cdk-experimental/dialog/dialog.spec.ts
  src/cdk/overlay/overlay-directives.spec.ts
  src/cdk/overlay/overlay-ref.ts
  src/cdk/overlay/overlay.spec.ts
  src/cdk/overlay/position/flexible-connected-position-strategy.ts
  src/lib/autocomplete/autocomplete.spec.ts
  src/lib/bottom-sheet/bottom-sheet.spec.ts
  src/lib/datepicker/datepicker.spec.ts
  src/lib/dialog/dialog.spec.ts
  src/lib/menu/menu.spec.ts
  src/lib/snack-bar/snack-bar.spec.ts
  src/lib/tooltip/tooltip.spec.ts
Labels: cla: yes, pr: lgtm, pr: merge ready, target: patch

#11394 fix(table): data source not unsubscribing from render changes subscription
  src/lib/table/table-data-source.ts
Labels: cla: yes, pr: lgtm, pr: merge ready, target: patch

#11460 fix(autosize): textarea receiving focus on init
  src/cdk/text-field/autosize.ts
Labels: cla: yes, pr: lgtm, pr: merge ready, target: patch

#11434 fix(select): panel content blurry in some browsers
  src/lib/select/select.spec.ts
  src/lib/select/select.ts
Labels: cla: yes, pr: lgtm, pr: merge ready, target: patch

#11431 perf(overlay): only compute and emit position changes if there are subscribers
  src/cdk/overlay/position/flexible-connected-position-strategy.ts
Labels: cla: yes, pr: lgtm, pr: merge ready, target: patch

#11477 fix(button): disable all animations when using the NoopAnimationsModule
  src/lib/button/_button-base.scss
  src/lib/button/button.scss
  src/lib/button/button.ts
  src/lib/core/style/_noop-animation.scss
Labels: cla: yes, pr: lgtm, pr: merge ready, target: patch

#11422 fix(slider): disable animations when using NoopAnimationsModule
  src/lib/slider/slider.scss
  src/lib/slider/slider.ts
Labels: cla: yes, pr: lgtm, pr: merge ready, target: patch

#11414 fix(slide-toggle): disable animations when using NoopAnimationsModule
  src/lib/slide-toggle/slide-toggle.scss
  src/lib/slide-toggle/slide-toggle.ts
Labels: cla: yes, pr: lgtm, pr: merge ready, target: patch

#11411 feat(overlay): allow for Directionality instance to be passed in
  src/cdk/overlay/overlay-config.ts
  src/cdk/overlay/overlay-directives.ts
  src/cdk/overlay/overlay-ref.ts
  src/cdk/overlay/overlay.spec.ts
  src/cdk/overlay/position/connected-position-strategy.ts
  src/cdk/overlay/position/flexible-connected-position-strategy.ts
  src/lib/autocomplete/autocomplete-trigger.ts
  src/lib/datepicker/datepicker.ts
  src/lib/menu/menu-trigger.ts
  src/lib/tooltip/tooltip.ts
Labels: cla: yes, pr: lgtm, pr: merge ready, target: minor

#11481 chore: minor cleanup in icon tests and virtual scrolling
  src/cdk-experimental/scrolling/tsconfig-build.json
  src/cdk-experimental/scrolling/typings.d.ts
  src/lib/icon/icon.spec.ts
Labels: cla: yes, pr: lgtm, pr: merge ready, pr: merge safe, target: master only

#11413 build: fix rollup global name in umd bundle
  tools/package-tools/rollup-globals.ts
Labels: cla: yes, pr: lgtm, pr: merge ready, pr: merge safe, target: patch

#11406 fix(form-field): infinite loop when using outline appearance and element isn't in the DOM
  src/lib/form-field/form-field.ts
Labels: cla: yes, pr: lgtm, pr: merge ready, target: patch

#11342 fix: prevent nested expansion panels from registering to the same accordion
  src/cdk/accordion/accordion-item.ts
  src/cdk/accordion/accordion.spec.ts
  src/lib/expansion/accordion.spec.ts
  src/lib/expansion/expansion-panel.ts
Labels: cla: yes, pr: lgtm, pr: merge ready, target: patch

#11487 chore: fix bazel failure
  src/cdk-experimental/scrolling/tsconfig-build.json
  src/cdk-experimental/scrolling/typings.d.ts
Labels: cla: yes, pr: lgtm, pr: merge ready, pr: merge safe, target: master only

#11493 feat(progress-spinner): add injection token for configuring the diameter and stroke globally
  src/lib/progress-spinner/progress-spinner.spec.ts
  src/lib/progress-spinner/progress-spinner.ts
Labels: cla: yes, pr: lgtm, pr: merge ready, target: minor

#11476 virtual-scroll: add update method
  src/cdk-experimental/scrolling/virtual-scroll-viewport.spec.ts
  src/cdk-experimental/scrolling/virtual-scroll-viewport.ts
Labels: cla: yes, pr: lgtm, pr: merge ready, pr: merge safe, target: master only

#11371 fix(form-field): disable all animations when using NoopAnimationsModule
  src/lib/form-field/form-field-fill.scss
  src/lib/form-field/form-field-outline.scss
  src/lib/form-field/form-field-standard.scss
  src/lib/form-field/form-field.scss
  src/lib/form-field/form-field.ts
  src/lib/input/input.spec.ts
Labels: cla: yes, pr: lgtm, pr: merge ready, target: patch

#11564 chore: bump version and changelog to 6.2.0
  CHANGELOG.md
  package-lock.json
  package.json
  src/lib/schematics/utils/lib-versions.ts
Labels: cla: yes, docs, pr: lgtm, pr: merge safe

#11558 fix typo
  src/lib/slider/slider.ts
Labels: cla: yes, pr: lgtm, pr: merge ready, pr: merge safe, target: master only

#11506 chore(table): add expandable rows demo
  src/demo-app/table/expandable-rows/expandable-rows.html
  src/demo-app/table/expandable-rows/expandable-rows.ts
  src/demo-app/table/table-demo.ts
  src/material-examples/table-expandable-rows/table-expandable-rows-example.css
  src/material-examples/table-expandable-rows/table-expandable-rows-example.html
  src/material-examples/table-expandable-rows/table-expandable-rows-example.ts
Labels: cla: yes, docs, pr: lgtm, pr: merge ready, pr: merge safe, target: patch

#11541 docs(tabs): remove duplicated shortcut
  src/lib/tabs/tabs.md
Labels: cla: yes, pr: lgtm, pr: merge ready, pr: merge safe, target: master only

#11567 chore: add 6.2.x branch to CI
  .travis.yml
Labels: cla: yes, pr: merge ready, pr: merge safe, target: master only

#10664 perf(tabs): use a transform to resize and move the ink bar
  src/lib/tabs/_tabs-common.scss
  src/lib/tabs/ink-bar.ts
Labels: cla: yes, pr: lgtm, pr: merge ready, target: patch

#11561 Add title to creating custom form guide
  guides/creating-a-custom-form-field-control.md
Labels: cla: yes, pr: lgtm, pr: merge ready, pr: merge safe, target: master only

#11548 build: add bazel config for cdk-experimental/dialog
  package-lock.json
  packages.bzl
  src/cdk-experimental/dialog/BUILD.bazel
  src/cdk-experimental/dialog/dialog-container.scss
  src/cdk-experimental/dialog/typings.d.ts
Labels: cla: yes, pr: lgtm, pr: merge ready, pr: merge safe, target: master only

#11461 fix(select): inconsistent openedChange event dispatched between browsers
  src/lib/select/select.html
  src/lib/select/select.ts
Labels: cla: yes, pr: lgtm, pr: merge ready, target: patch

#11410 fix(tabs): Add role to mat-tab-nav-bar and mat-tab-link
  src/lib/tabs/tab-nav-bar/tab-nav-bar.html
  src/lib/tabs/tab-nav-bar/tab-nav-bar.spec.ts
  src/lib/tabs/tab-nav-bar/tab-nav-bar.ts
Labels: cla: yes, pr: lgtm, pr: merge ready, target: patch

#11516 fix(dialog): not closing correctly when detached externally
  src/lib/dialog/dialog-ref.ts
  src/lib/dialog/dialog.spec.ts
Labels: cla: yes, pr: lgtm, pr: merge ready, target: patch

#10728 fix(tooltip): don't open for mouse and touch focus
  src/lib/tooltip/tooltip.spec.ts
  src/lib/tooltip/tooltip.ts
Labels: cla: yes, pr: lgtm, pr: merge ready, target: patch

#11587 docs(button): add mat-flat-button
  src/lib/button/button.md
Labels: cla: yes, pr: lgtm, pr: merge ready, pr: merge safe, target: master only

#11593 refactor(dialog): remove unused config property
  src/cdk-experimental/dialog/dialog-config.ts
Labels: cla: yes, pr: lgtm, pr: merge ready, pr: merge safe, target: master only

#11585 fix(tabs): Set initial ink bar width as 0 width
  src/lib/tabs/_tabs-common.scss
  src/lib/tabs/ink-bar.ts
Labels: cla: yes, pr: lgtm, pr: merge ready, target: patch

#11421 fix(overlay): flexible overlay with push not handling scroll offset and position locking
  src/cdk/overlay/position/flexible-connected-position-strategy.spec.ts
  src/cdk/overlay/position/flexible-connected-position-strategy.ts
  src/cdk/scrolling/viewport-ruler.ts
  src/lib/menu/menu-trigger.ts
Labels: P2, cla: yes, pr: lgtm, pr: merge ready, target: patch
