Repository angular/components, pull requests merged in 2019-11, with the labels that each got.

#17562 build: update to angular v9.0.0-rc.0
  package.json
  yarn.lock
Labels: cla: yes, pr: lgtm, pr: merge ready, pr: merge safe, target: major

#17563 build: generate changelog for google-maps package
  tools/release/changelog.ts
Labels: cla: yes, pr: lgtm, pr: merge ready, pr: merge safe, target: patch

#17570 build: max-line-length check not catching all cases
  src/material-examples/cdk-experimental/popover-edit/module.ts
  src/material-experimental/select/testing/shared.spec.ts
  tools/release/base-release-task.ts
  tslint.json
Labels: P3, cla: yes, pr: lgtm, pr: merge ready, pr: merge safe, target: patch

#17569 build: decorator validation rule skipping property check if next line is disabled
  tools/tslint-rules/validateDecoratorsRule.ts
Labels: P3, cla: yes, pr: lgtm, pr: merge ready, pr: merge safe, target: patch

#17565 build: set up API golden for google-maps package
  tools/public_api_guard/generate-guard-tests.bzl
  tools/public_api_guard/google-maps/google-maps.d.ts
Labels: P3, cla: yes, pr: lgtm, pr: merge ready, pr: merge safe, target: major

#17558 docs(chips): chips autocomplete demo separator key codes not working correctly
  src/material-examples/material/chips/chips-autocomplete/chips-autocomplete-example.html
  src/material-examples/material/chips/chips-autocomplete/chips-autocomplete-example.ts
Labels: P3, cla: yes, docs, pr: lgtm, pr: merge ready, pr: merge safe, target: patch

#17556 feat(material-experimental/mdc-tabs): add default fitInkBarToContent option
  src/material-experimental/mdc-tabs/tab-group.spec.ts
  src/material-experimental/mdc-tabs/tab-group.ts
  src/material-experimental/mdc-tabs/tab-nav-bar/tab-nav-bar.spec.ts
  src/material-experimental/mdc-tabs/tab-nav-bar/tab-nav-bar.ts
  src/material/tabs/public-api.ts
  src/material/tabs/tab-config.ts
  src/material/tabs/tab-group.ts
  tools/public_api_guard/material/tabs.d.ts
Labels: P3, cla: yes, pr: lgtm, target: minor

#17536 build: add lint rule to enforce coercion static properties for setters
  tools/tslint-rules/coercionTypesRule.ts
  tslint.json
Labels: P2, cla: yes, pr: lgtm, pr: merge ready, pr: merge safe, target: major

#17566 build: ensure no permission errors thrown in packages-dist script
  scripts/build-packages-dist.sh
Labels: cla: yes, pr: lgtm, pr: merge ready, pr: merge safe, target: patch

#17590 Fix typo
  src/youtube-player/README.md
Labels: cla: yes, docs, pr: lgtm, pr: merge ready, pr: merge safe, target: patch

#17602 feat(schematics): add prompt to add global typography class
  src/cdk/schematics/utils/html-manipulation.ts
  src/cdk/schematics/utils/index.ts
  src/material/schematics/ng-add/index.spec.ts
  src/material/schematics/ng-add/schema.json
  src/material/schematics/ng-add/schema.ts
  src/material/schematics/ng-add/setup-project.ts
  src/material/schematics/ng-add/theming/theming.ts
Labels: P3, cla: yes, pr: lgtm, pr: merge ready, pr: merge safe, target: minor

#17555 fix(stepper): not rendering correctly in some cases when step is inside ngIf
  src/material/stepper/stepper.spec.ts
  src/material/stepper/stepper.ts
Labels: P2, cla: yes, pr: lgtm, pr: merge ready, target: patch

#17575 fix(material-experimental/mdc-button): rename state class
  src/material-experimental/mdc-button/_button-base.scss
  src/material-experimental/mdc-button/_mdc-button.scss
  src/material-experimental/mdc-button/button.html
  src/material-experimental/mdc-button/button.scss
Labels: cla: yes, pr: lgtm, pr: merge ready, pr: merge safe, target: patch

#17606 build: skip bazel mirror urls when fetching yarn and node
  WORKSPACE
Labels: cla: yes, pr: lgtm, pr: merge ready, pr: merge safe, target: patch

#17607 build: move all jobs into a single workflow
  .circleci/config.yml
Labels: cla: yes, pr: lgtm, pr: merge ready, pr: merge safe, target: patch

#17573 build: upgrade to bazel 1.0.0
  WORKSPACE
  package.json
  tools/bazel/angular_bazel_0.38.2.patch
  yarn.lock
Labels: cla: yes, pr: lgtm, pr: merge ready, pr: merge safe, target: patch

#17609 build: enable coercion-types rule and fix leftover cases
  src/dev-app/example/example.ts
  src/material-examples/cdk/stepper/cdk-custom-stepper-without-form/cdk-custom-stepper-without-form-example.ts
  src/material-examples/material/slider/slider-configurable/slider-configurable-example.html
  src/material-examples/material/slider/slider-configurable/slider-configurable-example.ts
  src/material/paginator/paginator.ts
  tools/tslint-rules/coercionTypesRule.ts
  tslint.json
Labels: P2, cla: yes, pr: lgtm, pr: merge ready, pr: merge safe, target: major

#17578 feat(material-experimental/mdc-checkbox): add default options
  src/material-experimental/mdc-checkbox/checkbox.spec.ts
  src/material-experimental/mdc-checkbox/checkbox.ts
Labels: cla: yes, pr: lgtm, pr: merge ready, pr: merge safe, target: patch

#17600 fix(popover-edit): incorrect spacing for form field inside popover
  src/material-experimental/popover-edit/_popover-edit.scss
Labels: P3, cla: yes, pr: lgtm, pr: merge ready, pr: merge safe, target: patch

#17605 build: update goldens to ngtsc output
  .circleci/config.yml
  tools/public_api_guard/cdk/a11y.d.ts
  tools/public_api_guard/cdk/accordion.d.ts
  tools/public_api_guard/cdk/bidi.d.ts
  tools/public_api_guard/cdk/clipboard.d.ts
  tools/public_api_guard/cdk/collections.d.ts
  tools/public_api_guard/cdk/drag-drop.d.ts
  tools/public_api_guard/cdk/layout.d.ts
  tools/public_api_guard/cdk/observers.d.ts
  tools/public_api_guard/cdk/overlay.d.ts
  tools/public_api_guard/cdk/platform.d.ts
  tools/public_api_guard/cdk/portal.d.ts
  tools/public_api_guard/cdk/scrolling.d.ts
  tools/public_api_guard/cdk/stepper.d.ts
  tools/public_api_guard/cdk/table.d.ts
  tools/public_api_guard/cdk/text-field.d.ts
  tools/public_api_guard/cdk/tree.d.ts
  tools/public_api_guard/generate-guard-tests.bzl
  tools/public_api_guard/google-maps/google-maps.d.ts
  tools/public_api_guard/material/autocomplete.d.ts
  tools/public_api_guard/material/badge.d.ts
  tools/public_api_guard/material/bottom-sheet.d.ts
  tools/public_api_guard/material/button-toggle.d.ts
  tools/public_api_guard/material/button.d.ts
  tools/public_api_guard/material/card.d.ts
  tools/public_api_guard/material/checkbox.d.ts
  tools/public_api_guard/material/chips.d.ts
  tools/public_api_guard/material/core.d.ts
  tools/public_api_guard/material/datepicker.d.ts
  tools/public_api_guard/material/dialog.d.ts
  tools/public_api_guard/material/divider.d.ts
  tools/public_api_guard/material/expansion.d.ts
  tools/public_api_guard/material/form-field.d.ts
  tools/public_api_guard/material/grid-list.d.ts
  tools/public_api_guard/material/icon.d.ts
  tools/public_api_guard/material/input.d.ts
  tools/public_api_guard/material/list.d.ts
  tools/public_api_guard/material/menu.d.ts
  tools/public_api_guard/material/paginator.d.ts
  tools/public_api_guard/material/progress-bar.d.ts
  tools/public_api_guard/material/progress-spinner.d.ts
  tools/public_api_guard/material/radio.d.ts
  tools/public_api_guard/material/select.d.ts
  tools/public_api_guard/material/sidenav.d.ts
  tools/public_api_guard/material/slide-toggle.d.ts
  tools/public_api_guard/material/slider.d.ts
  tools/public_api_guard/material/snack-bar.d.ts
  tools/public_api_guard/material/sort.d.ts
  tools/public_api_guard/material/stepper.d.ts
  tools/public_api_guard/material/table.d.ts
  tools/public_api_guard/material/tabs.d.ts
  tools/public_api_guard/material/toolbar.d.ts
  tools/public_api_guard/material/tooltip.d.ts
  tools/public_api_guard/material/tree.d.ts
  tools/public_api_guard/youtube-player/youtube-player.d.ts
Labels: cla: yes, pr: lgtm, pr: merge ready, pr: merge safe, target: patch

#17612 docs(table): use correct directives for flex table
  src/material/table/table.md
Labels: cla: yes, docs, pr: lgtm, pr: merge ready, pr: merge safe, target: patch

#17617 test: fix a couple of shared harness functions ignoring module parameter
  src/material/dialog/testing/shared.spec.ts
  src/material/progress-spinner/testing/shared.spec.ts
Labels: P3, cla: yes, pr: lgtm, pr: merge ready, pr: merge safe, target: patch

#17608 build: fine-grain examples for dev-app pages
  src/dev-app/popover-edit/BUILD.bazel
  src/dev-app/popover-edit/popover-edit-demo-module.ts
  src/dev-app/popover-edit/popover-edit-demo.ts
  src/dev-app/ripple/BUILD.bazel
  src/dev-app/ripple/ripple-demo-module.ts
  src/dev-app/ripple/ripple-demo.html
  src/dev-app/table/BUILD.bazel
  src/dev-app/table/table-demo-module.ts
  src/dev-app/table/table-demo.html
  src/dev-app/table/table-demo.ts
  src/dev-app/tabs/BUILD.bazel
  src/dev-app/tabs/tabs-demo-module.ts
  src/dev-app/tabs/tabs-demo.html
  src/dev-app/tabs/tabs-demo.ts
  src/dev-app/tooltip/BUILD.bazel
  src/dev-app/tooltip/tooltip-demo-module.ts
  src/dev-app/tooltip/tooltip-demo.html
  src/dev-app/tooltip/tooltip-demo.ts
  src/dev-app/tree/BUILD.bazel
  src/dev-app/tree/tree-demo-module.ts
  src/dev-app/tree/tree-demo.html
  src/dev-app/tsconfig.json
  tsconfig.json
Labels: cla: yes, pr: lgtm, pr: merge ready, pr: merge safe, target: patch

#17627 build: set up API golden files for testing targets
  tools/public_api_guard/material/autocomplete/testing.d.ts
  tools/public_api_guard/material/button/testing.d.ts
  tools/public_api_guard/material/checkbox/testing.d.ts
  tools/public_api_guard/material/dialog/testing.d.ts
  tools/public_api_guard/material/menu/testing.d.ts
  tools/public_api_guard/material/progress-bar/testing.d.ts
  tools/public_api_guard/material/progress-spinner/testing.d.ts
  tools/public_api_guard/material/radio/testing.d.ts
  tools/public_api_guard/material/sidenav/testing.d.ts
  tools/public_api_guard/material/slide-toggle/testing.d.ts
  tools/public_api_guard/material/slider/testing.d.ts
  tools/public_api_guard/material/snack-bar/testing.d.ts
  tools/public_api_guard/material/tabs/testing.d.ts
Labels: P2, cla: yes, pr: lgtm, pr: merge ready, pr: merge safe, target: patch

#17620 build: allow ng_package patch to silently fail so that issue can be fixed in angular repo
  package.json
  tools/bazel/postinstall-patches.js
  yarn.lock
Labels: cla: yes, pr: lgtm, pr: merge ready, pr: merge safe, target: patch

#17568 fix(material-experimental/mdc-chips): chip set not picking up indirect descendant chips
  src/material-experimental/mdc-chips/chip-set.spec.ts
  src/material-experimental/mdc-chips/chip-set.ts
Labels: P2, cla: yes, pr: lgtm, pr: merge ready, target: major

#17515 build: member naming rule not catching private readonly
  src/google-maps/map-info-window/map-info-window.ts
  src/google-maps/map-marker/map-marker.ts
  tools/tslint-rules/memberNamingRule.ts
Labels: P3, cla: yes, pr: lgtm, pr: merge ready, pr: merge safe, target: patch

#17622 Fix docs api section
  src/cdk/clipboard/clipboard.ts
  src/cdk/clipboard/copy-to-clipboard.ts
  src/cdk/tree/nested-node.ts
Labels: cla: yes, docs, pr: lgtm, pr: merge ready, pr: merge safe, target: patch

#17624 test: menu test flaky due to missing animation flush
  src/material/menu/menu.spec.ts
Labels: cla: yes, pr: lgtm, pr: merge ready, pr: merge safe, target: patch

#17632 build: api golden check failure
  tools/public_api_guard/google-maps/google-maps.d.ts
Labels: P3, cla: yes, pr: lgtm, pr: merge ready, pr: merge safe, target: patch

#17642 build: remove example package workaround for flat module bundle
  tools/bazel/postinstall-patches.js
Labels: cla: yes, pr: lgtm, pr: merge ready, pr: merge safe, target: patch

#17633 refactor: update to MDC 4.0.0 stable
  package.json
  packages.bzl
  src/material-experimental/mdc-menu/BUILD.bazel
  src/material-experimental/mdc-menu/menu.scss
  src/material-experimental/mdc-progress-bar/progress-bar.spec.ts
  src/material-experimental/mdc-progress-bar/progress-bar.ts
  yarn.lock
Labels: P2, cla: yes, pr: lgtm, pr: merge ready, target: patch

#16101 feat(portal): add new portal that projects DOM nodes
  src/cdk-experimental/dialog/dialog-container.ts
  src/cdk/overlay/overlay.ts
  src/cdk/portal/dom-portal-outlet.ts
  src/cdk/portal/portal-directives.ts
  src/cdk/portal/portal.spec.ts
  src/cdk/portal/portal.ts
  src/dev-app/portal/portal-demo.html
  src/dev-app/portal/portal-demo.scss
  src/dev-app/portal/portal-demo.ts
  src/material/bottom-sheet/bottom-sheet-container.ts
  src/material/dialog/dialog-container.ts
  src/material/snack-bar/snack-bar-container.ts
  src/material/tabs/tab-body.ts
  tools/public_api_guard/cdk/portal.d.ts
  tools/public_api_guard/material/bottom-sheet.d.ts
  tools/public_api_guard/material/dialog.d.ts
  tools/public_api_guard/material/snack-bar.d.ts
  tools/public_api_guard/material/tabs.d.ts
Labels: P3, cla: yes, pr: lgtm, pr: merge ready, target: major

#17652 build: switch mdc snapshot test to run against master branch
  .circleci/config.yml
Labels: cla: yes, pr: lgtm, pr: merge ready, pr: merge safe, target: patch

#17648 demo(youtube-player): add auto video resizing
  src/dev-app/tsconfig.json
  src/dev-app/youtube-player/youtube-player-demo.html
  src/dev-app/youtube-player/youtube-player-demo.scss
  src/dev-app/youtube-player/youtube-player-demo.ts
Labels: P4, cla: yes, docs, pr: lgtm, pr: merge ready, pr: merge safe, target: patch

#17641 build: update to latest Angular RC
  package.json
  yarn.lock
Labels: P3, cla: yes, pr: lgtm, pr: merge ready, pr: merge safe, target: major

#17378 feat(cdk/a11y): add high-contrast mode detection
  src/cdk/a11y/_a11y.scss
  src/cdk/a11y/a11y-module.ts
  src/cdk/a11y/high-contrast-mode/high-contrast-mode-detector.spec.ts
  src/cdk/a11y/high-contrast-mode/high-contrast-mode-detector.ts
  src/cdk/a11y/public-api.ts
  src/material/core/common-behaviors/common-module.ts
  tools/public_api_guard/cdk/a11y.d.ts
  tools/public_api_guard/material/core.d.ts
Labels: G, P2, a11y, cla: yes, pr: lgtm, pr: merge ready, target: major

#17476 refactor: remove abstract directive selector workaround
  src/cdk-experimental/popover-edit/popover-edit.spec.ts
  src/material-experimental/mdc-button/button-base.ts
  src/material-experimental/mdc-button/module.ts
  src/material-experimental/popover-edit/popover-edit.spec.ts
  src/material/form-field/form-field-control.ts
  src/material/form-field/form-field-module.ts
  src/material/menu/menu-module.ts
  src/material/menu/menu.ts
  src/material/tabs/paginated-tab-header.ts
  src/material/tabs/tab-body.ts
  src/material/tabs/tab-group.ts
  src/material/tabs/tab-header.ts
  src/material/tabs/tab-nav-bar/tab-nav-bar.ts
  src/material/tabs/tabs-module.ts
  tools/public_api_guard/material/form-field.d.ts
  tools/public_api_guard/material/menu.d.ts
  tools/public_api_guard/material/tabs.d.ts
  tools/tslint-rules/coercionTypesRule.ts
Labels: cla: yes, pr: lgtm, pr: merge ready, target: patch

#17647 demo(google-map): minor clarity tweaks to the dev-app demo
  src/dev-app/google-map/BUILD.bazel
  src/dev-app/google-map/google-map-demo.html
  src/dev-app/google-map/google-map-demo.scss
  src/dev-app/google-map/google-map-demo.ts
Labels: P4, cla: yes, pr: lgtm, pr: merge ready, pr: merge safe, target: minor

#17583 fix(slider): track fill not rendering on ios safari when slider starts at 0
  src/material/slider/slider.spec.ts
  src/material/slider/slider.ts
Labels: P3, cla: yes, pr: lgtm, pr: merge ready, target: patch

#17669 build: remove rollup windows postinstall workaround
  WORKSPACE
  tools/bazel/postinstall-patches.js
  tools/bazel/rollup_windows_arguments.patch
Labels: cla: yes, pr: lgtm, pr: merge ready, pr: merge safe, target: patch

#17649 fix(chips): handle ripple color in theme using CSS variables
  src/material/chips/_chips-theme.scss
Labels: P3, cla: yes, pr: lgtm, pr: merge ready, target: patch

#17619 fix(sidenav): not destroying custom QueryList
  src/material/sidenav/drawer.spec.ts
  src/material/sidenav/drawer.ts
Labels: P3, cla: yes, pr: lgtm, pr: merge ready, target: patch

#17598 fix(clipboard): namespace copied output name
  src/cdk/clipboard/copy-to-clipboard.spec.ts
  src/cdk/clipboard/copy-to-clipboard.ts
  tools/public_api_guard/cdk/clipboard.d.ts
Labels: P3, cla: yes, pr: lgtm, pr: merge ready, target: patch

#17592 fix(select): select active item when tabbing away
  src/material/select/select.spec.ts
  src/material/select/select.ts
Labels: P3, cla: yes, pr: lgtm, pr: merge ready, target: patch

#17662 docs(datepicker): bump max date in example
  src/components-examples/material/datepicker/datepicker-min-max/datepicker-min-max-example.ts
Labels: P3, cla: yes, docs, pr: lgtm, pr: merge ready, pr: merge safe, target: patch

#17671 build: fix failing api golden for clipboard
  tools/public_api_guard/cdk/clipboard.d.ts
Labels: cla: yes, pr: lgtm, pr: merge ready, pr: merge safe

#17586 fix(overlay): maxWidth and maxHeight not applied when using exact dimensions
  src/cdk/overlay/position/flexible-connected-position-strategy.spec.ts
  src/cdk/overlay/position/flexible-connected-position-strategy.ts
Labels: P3, cla: yes, pr: lgtm, pr: merge ready, target: patch

#17580 fix(slider): some potentially broken styles when using css variables
  src/material/slider/_slider-theme.scss
Labels: P3, cla: yes, pr: lgtm, pr: merge ready, target: patch

#17548 fix(tabs): custom QueryList not being cleaned up
  src/material-experimental/mdc-tabs/tab-group.spec.ts
  src/material/tabs/tab-group.spec.ts
  src/material/tabs/tab-group.ts
Labels: P3, cla: yes, pr: lgtm, pr: merge ready, target: patch

#17538 fix(tree): class name mistyped
  src/material/tree/tree.scss
Labels: P3, cla: yes, pr: lgtm, pr: merge ready, target: patch

#17520 fix(slider): handle touchcancel event
  src/material/slider/slider.ts
Labels: P3, cla: yes, pr: lgtm, pr: merge ready, target: patch

#17674 test: disambiguate MDC component test names
  src/material-experimental/mdc-button/button.spec.ts
  src/material-experimental/mdc-checkbox/checkbox.e2e.spec.ts
  src/material-experimental/mdc-checkbox/checkbox.spec.ts
  src/material-experimental/mdc-chips/chip-grid.spec.ts
  src/material-experimental/mdc-chips/chip-input.spec.ts
  src/material-experimental/mdc-chips/chip-listbox.spec.ts
  src/material-experimental/mdc-chips/chip-option.spec.ts
  src/material-experimental/mdc-chips/chip-remove.spec.ts
  src/material-experimental/mdc-chips/chip-row.spec.ts
  src/material-experimental/mdc-chips/chip-set.spec.ts
  src/material-experimental/mdc-chips/chip.spec.ts
  src/material-experimental/mdc-menu/menu.e2e.spec.ts
  src/material-experimental/mdc-menu/menu.spec.ts
  src/material-experimental/mdc-progress-bar/progress-bar.e2e.spec.ts
  src/material-experimental/mdc-progress-bar/progress-bar.spec.ts
  src/material-experimental/mdc-slide-toggle/slide-toggle.e2e.spec.ts
  src/material-experimental/mdc-slide-toggle/slide-toggle.spec.ts
  src/material-experimental/mdc-slider/slider.spec.ts
  src/material-experimental/mdc-tabs/tab-body.spec.ts
  src/material-experimental/mdc-tabs/tab-group.spec.ts
  src/material-experimental/mdc-tabs/tab-header.spec.ts
  src/material-experimental/mdc-tabs/tab-nav-bar/tab-nav-bar.spec.ts
  src/material-experimental/mdc-tabs/tabs.e2e.spec.ts
Labels: cla: yes, pr: lgtm, pr: merge ready, pr: merge safe, target: patch

#17547 feat(clipboard): add the ability to specify number of attempts in clipboard directive
  src/cdk/clipboard/clipboard.md
  src/cdk/clipboard/copy-to-clipboard.spec.ts
  src/cdk/clipboard/copy-to-clipboard.ts
  tools/public_api_guard/cdk/clipboard.d.ts
Labels: P3, cla: yes, pr: lgtm, pr: merge ready, target: minor

#17680 release: fix typing for excludedChangelogPackages
  tools/release/changelog.ts
Labels: cla: yes, pr: lgtm, pr: merge ready, pr: merge safe, target: patch

#17679 build: set up all packages to publish via wombot proxy
  src/cdk-experimental/package.json
  src/cdk/package.json
  src/google-maps/package.json
  src/material-experimental/package.json
  src/material-moment-adapter/package.json
  src/material/package.json
  src/youtube-player/package.json
  tools/release/npm/npm-client.ts
  tools/release/prompt/npm-dist-tag-prompt.ts
  tools/release/publish-release.ts
Labels: cla: yes, pr: lgtm, pr: merge ready, pr: merge safe, target: patch

#17684 chore: bump version to 9.0.0-rc.1 w/ changelog
  CHANGELOG.md
Labels: cla: yes, pr: lgtm, pr: merge ready, pr: merge safe, target: major

#17685 release: remove .npmrc file at end of release
  tools/release/publish-release.ts
Labels: cla: yes, pr: lgtm, pr: merge ready, pr: merge safe, target: major

#17686 chore: mark all packages as `sideEffects: false`
  src/cdk-experimental/package.json
  src/material-experimental/package.json
  src/material-moment-adapter/package.json
Labels: cla: yes, pr: lgtm, pr: merge ready, pr: merge safe, target: patch

#17696 build: update to latest Angular version
  package.json
  yarn.lock
Labels: P3, cla: yes, pr: lgtm, pr: merge ready, pr: merge safe, target: major

#17704 fix(ng-update): migrations not running for release candidate versions
  package.json
  src/cdk/schematics/migration.json
  src/material/schematics/migration.json
  tools/release/check-release-output.ts
  tools/release/publish-release.ts
  tools/release/release-output/check-package.ts
  tools/release/release-output/output-validations.ts
  tools/release/stage-release.ts
  yarn.lock
Labels: P1, cla: yes, pr: merge safe, target: patch

#17485 fix(checkbox): unknown property warning with Ivy during server-side rendering
  src/material-experimental/mdc-checkbox/checkbox.html
  src/material-experimental/mdc-checkbox/checkbox.ts
  src/material/checkbox/checkbox.html
  src/material/checkbox/checkbox.ts
  tools/public_api_guard/material/checkbox.d.ts
Labels: P2, cla: yes, pr: lgtm, pr: merge ready, presubmit failures, target: major

#17709 chore: bump version to 9.0.0-rc.2 w/ changelog
  CHANGELOG.md
  package.json
Labels: cla: yes, pr: lgtm, pr: merge ready

#17713 fix(ng-update): hammer v9 migration should not unnecessarily set up gestures
  src/cdk/schematics/update-tool/utils/imports.ts
  src/material/schematics/ng-update/test-cases/v9/hammer-migration-v9.spec.ts
  src/material/schematics/ng-update/upgrade-rules/hammer-gestures-v9/hammer-gestures-rule.ts
  src/material/schematics/ng-update/upgrade-rules/hammer-gestures-v9/identifier-imports.ts
  tools/tslint-rules/noUndecoratedClassWithNgFieldsRule.ts
Labels: P1, cla: yes, pr: lgtm, pr: merge ready, pr: merge safe, target: patch

#17717 fix(ng-update): imports to `MatProgressSpinnerModule` not migrated
  src/material/progress-spinner/progress-spinner-module.ts
  src/material/schematics/ng-update/upgrade-rules/package-imports-v8/material-symbols.json
  tools/public_api_guard/material/progress-spinner.d.ts
Labels: P1, cla: yes, pr: lgtm, pr: merge ready, target: patch

#17740 build: changelog should collect deprecations
  CONTRIBUTING.md
  tools/release/changelog-root-template.hbs
  tools/release/changelog.ts
Labels: cla: yes, pr: lgtm, pr: merge ready, pr: merge safe, target: patch

#17739 refactor(ng-update): follow-up cleanup of hammer v9 migration
  src/material/schematics/ng-update/test-cases/v9/hammer-migration-v9.spec.ts
  src/material/schematics/ng-update/upgrade-rules/hammer-gestures-v9/hammer-gestures-rule.ts
Labels: cla: yes, pr: lgtm, pr: merge ready, pr: merge safe, target: patch

#17733 build: Object.assign linting not working
  src/material-experimental/mdc-chips/chip-grid.spec.ts
  src/material-experimental/mdc-chips/chip-remove.spec.ts
  src/material-experimental/mdc-chips/chip-row.spec.ts
  src/material-experimental/mdc-chips/chip.spec.ts
  src/material/input/input.spec.ts
  tools/dgeni/processors/merge-inherited-properties.ts
  tslint.json
Labels: P3, cla: yes, pr: lgtm, pr: merge ready, pr: merge safe, target: patch

#17730 test: clean up dom insertions in tests
  src/cdk/a11y/aria-describer/aria-describer.spec.ts
  src/cdk/a11y/live-announcer/live-announcer.spec.ts
  src/cdk/clipboard/clipboard.spec.ts
  src/cdk/overlay/overlay-container.spec.ts
  src/material-experimental/mdc-chips/chip-option.spec.ts
  src/material-experimental/mdc-chips/chip-row.spec.ts
  src/material-experimental/mdc-chips/chip.spec.ts
  src/material/chips/chip.spec.ts
Labels: P3, cla: yes, pr: lgtm, pr: merge ready, pr: merge safe, target: patch

#17724 docs(list): remove spurious "the"
  src/material/list/list.md
Labels: cla: yes, docs, pr: lgtm, pr: merge ready, pr: merge safe, target: patch

#17692 refactor: remove @dynamic tag from harness classes
  src/cdk/testing/tests/harnesses/sub-component-harness.ts
  src/material-experimental/form-field/testing/form-field-harness.ts
  src/material-experimental/input/testing/input-harness.ts
  src/material-experimental/mdc-button/testing/button-harness.ts
  src/material-experimental/mdc-checkbox/testing/checkbox-harness.ts
  src/material-experimental/mdc-chips/testing/chip-grid-harness.ts
  src/material-experimental/mdc-chips/testing/chip-harness.ts
  src/material-experimental/mdc-chips/testing/chip-input-harness.ts
  src/material-experimental/mdc-chips/testing/chip-listbox-harness.ts
  src/material-experimental/mdc-chips/testing/chip-option-harness.ts
  src/material-experimental/mdc-chips/testing/chip-row-harness.ts
  src/material-experimental/mdc-chips/testing/chip-set-harness.ts
  src/material-experimental/mdc-menu/testing/menu-harness.ts
  src/material-experimental/mdc-progress-bar/testing/progress-bar-harness.ts
  src/material-experimental/mdc-slide-toggle/testing/slide-toggle-harness.ts
  src/material-experimental/mdc-slider/testing/slider-harness.ts
  src/material-experimental/select/testing/option-harness.ts
  src/material-experimental/select/testing/select-harness.ts
  src/material/autocomplete/testing/autocomplete-harness.ts
  src/material/autocomplete/testing/option-harness.ts
  src/material/button/testing/button-harness.ts
  src/material/checkbox/testing/checkbox-harness.ts
  src/material/dialog/testing/dialog-harness.ts
  src/material/menu/testing/menu-harness.ts
  src/material/progress-bar/testing/progress-bar-harness.ts
  src/material/progress-spinner/testing/progress-spinner-harness.ts
  src/material/radio/testing/radio-harness.ts
  src/material/sidenav/testing/drawer-harness.ts
  src/material/sidenav/testing/sidenav-harness.ts
  src/material/slide-toggle/testing/slide-toggle-harness.ts
  src/material/slider/testing/slider-harness.ts
  src/material/snack-bar/testing/snack-bar-harness.ts
  src/material/tabs/testing/tab-group-harness.ts
  src/material/tabs/testing/tab-harness.ts
Labels: cla: yes, pr: lgtm, pr: merge ready, pr: merge safe, target: patch

#17698 docs(guides/typography): update recommended font url
  guides/typography.md
Labels: cla: yes, docs, pr: lgtm, pr: merge ready, pr: merge safe, target: patch

#17737 refactor(ng-update): handle namespaced angular decorators in update-tool
  src/cdk/schematics/ng-update/test-cases/v6/attribute-selectors_expected_output.ts
  src/cdk/schematics/ng-update/test-cases/v6/attribute-selectors_input.ts
  src/cdk/schematics/testing/test-case-setup.ts
  src/cdk/schematics/update-tool/public-api.ts
  src/cdk/schematics/update-tool/target-version.ts
  src/cdk/schematics/update-tool/utils/decorators.ts
  src/cdk/schematics/update-tool/utils/imports.ts
  src/material/schematics/ng-update/test-cases/v8/misc/material-imports.spec.ts
  src/material/schematics/ng-update/test-cases/v8/misc/material-imports_expected_output.ts
  src/material/schematics/ng-update/test-cases/v8/misc/material-imports_input.ts
  src/material/schematics/ng-update/test-cases/v9/misc/hammer-migration-v9.spec.ts
  src/material/schematics/ng-update/test-cases/v9/misc/material-imports.spec.ts
  src/material/schematics/ng-update/test-cases/v9/misc/material-imports_expected_output.ts
  src/material/schematics/ng-update/test-cases/v9/misc/material-imports_input.ts
  src/material/schematics/ng-update/upgrade-rules/hammer-gestures-v9/hammer-gestures-rule.ts
  src/material/schematics/ng-update/upgrade-rules/hammer-gestures-v9/identifier-imports.ts
Labels: P3, cla: yes, pr: lgtm, pr: merge ready, pr: merge safe, target: patch

#17673 build: expand decorators validation rule to cover class members
  tools/tslint-rules/validateDecoratorsRule.ts
  tslint.json
Labels: P2, cla: yes, pr: lgtm, pr: merge ready, pr: merge safe, target: patch

#17161 feat(material-experimental/mdc-snackbar): Add skeleton.
  .github/CODEOWNERS
  src/material-experimental/mdc-snackbar/BUILD.bazel
  src/material-experimental/mdc-snackbar/_mdc-snackbar.scss
  src/material-experimental/mdc-snackbar/index.ts
  src/material-experimental/mdc-snackbar/module.ts
  src/material-experimental/mdc-snackbar/public-api.ts
  src/material-experimental/mdc-snackbar/snackbar.html
  src/material-experimental/mdc-snackbar/snackbar.scss
  src/material-experimental/mdc-snackbar/snackbar.ts
  src/material-experimental/mdc-snackbar/tsconfig-build.json
  test/karma-system-config.js
Labels: cla: yes, pr: lgtm, pr: merge ready, pr: merge safe, target: patch

#17747 build: fix errors in mdc-snackbar build
  src/material-experimental/mdc-snackbar/BUILD.bazel
  src/material-experimental/mdc-snackbar/snackbar.ts
Labels: P1, cla: yes, pr: lgtm, pr: merge ready, pr: merge safe, target: patch

#17744 fix(google-maps): error during server-side rendering
  src/google-maps/google-map/google-map.ts
  src/universal-app/BUILD.bazel
  src/universal-app/kitchen-sink/kitchen-sink.html
  src/universal-app/kitchen-sink/kitchen-sink.ts
Labels: P3, cla: yes, pr: lgtm, pr: merge ready, pr: merge safe, target: patch

#17658 feat(cdk/testing): support querying for multiple TestHarness / Compon…
  package.json
  src/cdk/testing/component-harness.ts
  src/cdk/testing/harness-environment.ts
  src/cdk/testing/private/expect-async-error.ts
  src/cdk/testing/tests/BUILD.bazel
  src/cdk/testing/tests/harnesses/main-component-harness.ts
  src/cdk/testing/tests/harnesses/sub-component-harness.ts
  src/cdk/testing/tests/protractor.e2e.spec.ts
  src/cdk/testing/tests/test-main-component.html
  src/cdk/testing/tests/testbed.spec.ts
  src/material-experimental/form-field/testing/form-field-harness.ts
  tools/public_api_guard/cdk/testing.d.ts
Labels: P2, cla: yes, pr: lgtm, pr: merge ready, target: minor

#17745 build: server-side rendering check not failing for async errors
  src/universal-app/kitchen-sink-mdc/kitchen-sink-mdc.ts
  src/universal-app/kitchen-sink/kitchen-sink.ts
Labels: P3, cla: yes, pr: lgtm, pr: merge ready, pr: merge safe, target: patch

#17703 build: remove unused variable in docs-content publishing script
  scripts/deploy/publish-docs-content.sh
Labels: cla: yes, pr: lgtm, pr: merge ready, pr: merge safe, target: patch

#17700 build: update to bazel v1.1.0
  WORKSPACE
  package.json
  yarn.lock
Labels: cla: yes, pr: lgtm, pr: merge ready, pr: merge safe, target: patch

#17695 build: delete rxjs d.ts files referencing rxjs-compat
  tools/bazel/postinstall-patches.js
Labels: cla: yes, pr: lgtm, pr: merge ready, pr: merge safe, target: major

#17675 build: enable bazel node modules symlinking
  .circleci/config.yml
  WORKSPACE
  package.json
  tools/bazel/postinstall-patches.js
Labels: cla: yes, pr: lgtm, pr: merge ready, pr: merge safe, target: patch

#17664 fix(google-maps): avoid event listener leaks if inputs change
  src/google-maps/google-map/google-map.ts
  src/google-maps/map-info-window/map-info-window.ts
  src/google-maps/map-marker/map-marker.ts
Labels: P3, cla: yes, pr: lgtm, pr: merge ready, pr: merge safe, target: patch

#17755 refactor: handle stubbed window in SSR checks
  src/google-maps/BUILD.bazel
  src/google-maps/google-map/google-map.ts
  src/youtube-player/BUILD.bazel
  src/youtube-player/youtube-player.ts
  tools/public_api_guard/google-maps/google-maps.d.ts
  tools/public_api_guard/youtube-player/youtube-player.d.ts
Labels: P3, cla: yes, pr: lgtm, pr: merge ready, pr: merge safe, target: patch

#17757 build: fix missing amd module name for primary entry-point
  src/material/BUILD.bazel
Labels: P2, cla: yes, pr: lgtm, pr: merge ready, pr: merge safe, target: patch

#17756 build: remove schematic tsconfig project references
  src/cdk/schematics/tsconfig.json
  src/material/schematics/tsconfig.json
Labels: cla: yes, pr: lgtm, pr: merge ready, pr: merge safe, target: patch

#17753 refactor(ng-update): do not copy gesture config if only standard HammerJS events are used
  src/material/schematics/ng-update/test-cases/v9/misc/hammer-migration-v9.spec.ts
  src/material/schematics/ng-update/upgrade-rules/hammer-gestures-v9/hammer-gestures-rule.ts
  src/material/schematics/ng-update/upgrade-rules/hammer-gestures-v9/hammer-template-check.ts
Labels: P1, cla: yes, commit message fixup, pr: lgtm, pr: merge ready, pr: merge safe, target: patch

#17751 build: set @returns description for void async methods automatically
  tools/dgeni/docs-package.ts
  tools/dgeni/processors/async-return-description.ts
  tools/dgeni/processors/categorizer.ts
Labels: cla: yes, pr: lgtm, pr: merge ready, pr: merge safe, target: patch

#17752 docs: create migration guide for v9 hammer migration
  guides/v9-hammerjs-migration.md
Labels: P1, cla: yes, docs, pr: lgtm, pr: merge ready, pr: merge safe, target: patch

#17758 build: rework package-builder script to node script
  .circleci/config.yml
  package.json
  scripts/build-packages-dist.js
  scripts/build-packages-dist.sh
  tools/release/publish-release.ts
Labels: cla: yes, pr: lgtm, pr: merge ready, pr: merge safe, target: patch

#17763 chore: bump version to 9.0.0-rc.3 w/ changelog
  CHANGELOG.md
  package.json
Labels: G, cla: yes, pr: lgtm, pr: merge ready, pr: merge safe, target: major

#17772 Revert "build: fix missing amd module name for primary entry-point (#17757)"
  src/material/BUILD.bazel
Labels: P1, cla: yes, pr: lgtm, pr: merge ready, pr: merge safe, target: major

#17768 build: update to angular v9.0.0-rc.3
  package.json
  yarn.lock
Labels: cla: yes, pr: lgtm, pr: merge ready, pr: merge safe, target: patch

#17769 refactor(ng-update): add links to migration guide in v9 hammer migration
  src/material/schematics/ng-update/upgrade-rules/hammer-gestures-v9/gesture-config.template
  src/material/schematics/ng-update/upgrade-rules/hammer-gestures-v9/hammer-gestures-rule.ts
Labels: cla: yes, pr: lgtm, pr: merge ready, pr: merge safe, target: patch

#17773 Revert "build: enable bazel node modules symlinking (#17675)"
  .circleci/config.yml
  WORKSPACE
  package.json
  tools/bazel/postinstall-patches.js
Labels: cla: yes, pr: lgtm, pr: merge ready, pr: merge safe, target: major

#17766 Date selection model
  src/material/core/datetime/date-selection-model.ts
  tools/public_api_guard/material/core.d.ts
Labels: cla: yes

#17775 Revert "Revert "build: fix missing amd module name for primary entry-point (#17757)""
  src/material/BUILD.bazel
Labels: P1, cla: yes, pr: lgtm, pr: merge ready, pr: merge safe, target: patch

#17723 docs(harnesses): ensure all harnesses have complete and correct docs
  src/cdk/testing/component-harness.ts
  src/material/autocomplete/testing/autocomplete-harness-filters.ts
  src/material/autocomplete/testing/autocomplete-harness.ts
  src/material/autocomplete/testing/option-harness.ts
  src/material/button/testing/button-harness-filters.ts
  src/material/button/testing/button-harness.ts
  src/material/checkbox/testing/checkbox-harness-filters.ts
  src/material/checkbox/testing/checkbox-harness.ts
  src/material/dialog/testing/dialog-harness-filters.ts
  src/material/dialog/testing/dialog-harness.ts
  src/material/menu/testing/menu-harness-filters.ts
  src/material/menu/testing/menu-harness.ts
  src/material/progress-bar/testing/progress-bar-harness-filters.ts
  src/material/progress-bar/testing/progress-bar-harness.ts
  src/material/progress-spinner/testing/progress-spinner-harness-filters.ts
  src/material/progress-spinner/testing/progress-spinner-harness.ts
  src/material/radio/testing/radio-harness-filters.ts
  src/material/radio/testing/radio-harness.ts
  src/material/sidenav/testing/drawer-harness-filters.ts
  src/material/sidenav/testing/drawer-harness.ts
  src/material/sidenav/testing/sidenav-harness.ts
  src/material/slide-toggle/testing/slide-toggle-harness-filters.ts
  src/material/slide-toggle/testing/slide-toggle-harness.ts
  src/material/slider/testing/slider-harness-filters.ts
  src/material/slider/testing/slider-harness.ts
  src/material/snack-bar/testing/snack-bar-harness-filters.ts
  src/material/snack-bar/testing/snack-bar-harness.ts
  src/material/tabs/testing/tab-group-harness.ts
  src/material/tabs/testing/tab-harness-filters.ts
  src/material/tabs/testing/tab-harness.ts
  tools/public_api_guard/material/menu/testing.d.ts
Labels: P2, cla: yes, pr: lgtm, pr: merge ready, pr: merge safe, target: patch

#17776 build: enable bazel node modules symlinking [resubmit w/ fixes]
  .circleci/config.yml
  WORKSPACE
  package.json
  tools/bazel/postinstall-patches.js
Labels: cla: yes, pr: lgtm, pr: merge ready, pr: merge safe, target: patch

#17788 fix(schematics): do not depend on external dependency for colors
  src/cdk/schematics/BUILD.bazel
  src/cdk/schematics/ng-update/index.ts
  src/cdk/schematics/ng-update/upgrade-rules/class-inheritance-rule.ts
  src/cdk/schematics/ng-update/upgrade-rules/index.ts
  src/material/schematics/BUILD.bazel
  src/material/schematics/ng-add/index.spec.ts
  src/material/schematics/ng-add/setup-project.ts
  src/material/schematics/ng-add/theming/theming.ts
  src/material/schematics/ng-update/index.ts
  src/material/schematics/ng-update/upgrade-rules/hammer-gestures-v9/hammer-gestures-rule.ts
Labels: P1, cla: yes, pr: lgtm, pr: merge ready, pr: merge safe, target: patch

#17741 build: add lint rule to avoid relative cross entry-point imports/exports
  src/cdk/testing/private/BUILD.bazel
  src/cdk/testing/private/public-api.ts
  src/cdk/testing/protractor/BUILD.bazel
  src/cdk/testing/protractor/protractor-element.ts
  src/cdk/testing/protractor/protractor-harness-environment.ts
  src/cdk/testing/public-api.ts
  src/cdk/testing/test-element.ts
  src/cdk/testing/testbed/BUILD.bazel
  src/cdk/testing/testbed/fake-events/dispatch-events.ts
  src/cdk/testing/testbed/fake-events/element-focus.ts
  src/cdk/testing/testbed/fake-events/event-objects.ts
  src/cdk/testing/testbed/fake-events/index.ts
  src/cdk/testing/testbed/fake-events/type-in-element.ts
  src/cdk/testing/testbed/testbed-harness-environment.ts
  src/cdk/testing/testbed/unit-test-element.ts
  src/material-experimental/form-field/testing/form-field-harness.ts
  test/karma-system-config.js
  tools/public_api_guard/cdk/testing.d.ts
  tools/tslint-rules/noCrossEntryPointRelativeImportsRule.ts
  tslint.json
Labels: P1, cla: yes, pr: lgtm, pr: merge ready, target: patch

#17779 docs: rename cdk/testing overview doc name
  src/cdk/testing/BUILD.bazel
  src/cdk/testing/test-harnesses.md
Labels: P1, cla: yes, docs, pr: lgtm, pr: merge safe

#17754 docs(cdk/testing): add documentation for harness environment authors
  src/cdk/testing/test-element.ts
  src/cdk/testing/test-harnesses.md
Labels: P2, cla: yes, pr: lgtm, pr: merge ready, pr: merge safe, target: patch

#17793 chore: bump version to 9.0.0-rc.4 w/ changelog
  CHANGELOG.md
  package.json
  scripts/build-packages-dist.js
Labels: cla: yes, pr: lgtm, pr: merge ready, pr: merge safe, target: major

#17801 docs(readme): update docs url for ripples
  README.md
Labels: cla: yes, docs, pr: lgtm, pr: merge ready, pr: merge safe, target: patch

#17804 refactor: clean up ReplaySubject usages
  src/cdk-experimental/popover-edit/lens-directives.ts
  src/cdk-experimental/popover-edit/table-directives.ts
Labels: P3, cla: yes, pr: lgtm, pr: merge ready, pr: merge safe, target: patch

#17811 build: update to rules_nodejs v0.41.0
  WORKSPACE
  package.json
  src/cdk/testing/BUILD.bazel
  yarn.lock
Labels: cla: yes, pr: lgtm, pr: merge ready, pr: merge safe, target: patch

#17812 build: create api goldens for cdk/testing protractor and testbed
  tools/public_api_guard/cdk/testing/protractor.d.ts
  tools/public_api_guard/cdk/testing/testbed.d.ts
Labels: cla: yes, pr: lgtm, pr: merge ready, pr: merge safe, target: patch

#17813 build: mark asynchronous functions in API docs
  tools/dgeni/docs-package.ts
  tools/dgeni/processors/async-functions.ts
  tools/dgeni/templates/method.template.html
Labels: cla: yes, pr: lgtm, pr: merge ready, pr: merge safe, target: patch

#17731 fix(portal): content not rendered inside outlet when view container is provided
  src/cdk/portal/portal-directives.ts
  src/cdk/portal/portal.spec.ts
Labels: P2, cla: yes, pr: lgtm, pr: merge ready, target: patch

#17725 fix(bottom-sheet): don't move focus if it was moved during close animation
  src/material/bottom-sheet/bottom-sheet-container.ts
  src/material/bottom-sheet/bottom-sheet.spec.ts
Labels: P3, cla: yes, pr: lgtm, pr: merge ready, target: patch

#17687 fix(menu): cap maximum elevation for nested menus
  src/material/menu/menu.ts
Labels: P3, cla: yes, pr: lgtm, pr: merge ready, target: patch

#17481 fix(expansion): accordion picking up headers from descendant accordion during keyboard navigation
  src/material/expansion/accordion.spec.ts
  src/material/expansion/accordion.ts
Labels: P3, a11y, cla: yes, pr: lgtm, pr: merge ready, target: patch

#17330 fix(drag-drop): disabled state not synced on data binding changes
  src/cdk/drag-drop/directives/drag.spec.ts
  src/cdk/drag-drop/directives/drop-list.ts
Labels: P3, cla: yes, pr: lgtm, pr: merge ready, target: patch

#17561 fix(material-experimental/mdc-tabs): markForCheck on ink bar content input setter
  src/material-experimental/mdc-tabs/tab-group.ts
  src/material-experimental/mdc-tabs/tab-nav-bar/tab-nav-bar.ts
  src/material/tabs/tab-group.ts
  tools/public_api_guard/material/tabs.d.ts
Labels: P3, cla: yes, discussion, pr: lgtm, pr: merge ready, pr: merge safe, target: patch

#17790 chore(ivy): fix host listener inheritence for mdc-chips and mdc-anchor
  src/material-experimental/mdc-button/button-base.ts
  src/material-experimental/mdc-chips/chip-option.ts
  src/material-experimental/mdc-chips/chip-row.ts
  src/material-experimental/mdc-chips/chip.ts
Labels: P1, cla: yes, pr: lgtm, pr: merge ready, target: patch

#17785 fix(select): don't handle open key presses while the user is typing
  src/cdk/a11y/key-manager/list-key-manager.spec.ts
  src/cdk/a11y/key-manager/list-key-manager.ts
  src/material/select/select.spec.ts
  src/material/select/select.ts
  tools/public_api_guard/cdk/a11y.d.ts
Labels: P3, cla: yes, pr: lgtm, pr: merge ready, target: patch

#17778 build: enforce that the descendants flag is set on all queries
  src/material-experimental/mdc-tabs/tab-header.ts
  src/material/menu/menu.ts
  src/material/tabs/tab-header.ts
  tslint.json
Labels: P2, cla: yes, pr: lgtm, pr: merge ready, target: patch

#17777 fix(drag-drop): position reset if viewport is resized while boundary is invisible
  src/cdk/drag-drop/directives/drag.spec.ts
  src/cdk/drag-drop/drag-ref.ts
Labels: P3, cla: yes, pr: lgtm, pr: merge ready, target: patch

#17694 fix(material-experimental/mdc-chips): add checkmark container
  src/material-experimental/mdc-chips/chip-option.html
Labels: P3, cla: yes, pr: lgtm, pr: merge ready

#17693 refactor(expansion): avoid unnecessary spacing check
  src/material/expansion/expansion-panel.ts
Labels: cla: yes, pr: lgtm, pr: merge ready, target: patch

#17681 fix(material-experimental/mdc-chips): use ripple target for state interactions
  src/material-experimental/mdc-chips/chip-option.html
  src/material-experimental/mdc-chips/chip-row.html
  src/material-experimental/mdc-chips/chip.html
  src/material-experimental/mdc-chips/chips.scss
Labels: cla: yes, pr: lgtm, pr: merge ready, target: patch

#17665 perf(youtube-player): triggering change detection for unused events
  src/youtube-player/youtube-player.ts
Labels: P3, cla: yes, pr: lgtm, pr: merge ready, pr: merge safe, target: patch

#17805 fix(google-maps): handle trying to access the map before it has been initialized
  src/google-maps/google-map/google-map.ts
Labels: P3, cla: yes, pr: lgtm, pr: merge ready, pr: merge safe, target: patch

#17829 build: don't flag classes with empty constructors in undecorated class lint rule
  tools/tslint-rules/noUndecoratedBaseClassDiRule.ts
Labels: P4, cla: yes, pr: lgtm, pr: merge ready, pr: merge safe, target: patch

#17833 build: update to angular v9.0.0-rc.4
  package.json
  yarn.lock
Labels: cla: yes, pr: lgtm, pr: merge ready, pr: merge safe, target: patch

#17836 build: disallow usages of the first operator
  tslint.json
Labels: P3, cla: yes, pr: lgtm, pr: merge ready, pr: merge safe, target: patch

#17835 fix(youtube-player): clean up internal observables
  src/youtube-player/youtube-player.ts
Labels: P4, cla: yes, pr: lgtm, pr: merge ready, pr: merge safe, target: patch
