Repository angular/components, pull requests merged in 2019-04, with the labels that each got.

#15068 docs(table): note that viewchange is not yet implemented
  src/cdk/table/table.ts
Labels: cla: yes, pr: lgtm, pr: merge ready, pr: merge safe, target: patch

#15446 fix(schematics): use ngAfterViewInit instead of ngOnInit in table
  src/lib/schematics/ng-generate/table/files/__path__/__name@dasherize@if-flat__/__name@dasherize__.component.ts
Labels: cla: yes, pr: lgtm, pr: merge ready, pr: merge safe

#15653 build: bump to stable version of codelyzer
  package.json
  yarn.lock
Labels: cla: yes, pr: lgtm, pr: merge ready, pr: merge safe, target: patch

#15659 build: add lint rule to catch SimpleChanges direct property access
  tools/tslint-rules/ngOnChangesPropertyAccessRule.ts
  tslint.json
Labels: cla: yes, pr: lgtm, pr: merge ready, pr: merge safe, target: patch

#15644 cleanup(build): some bazel related cleanup
  WORKSPACE
  src/e2e-app/BUILD.bazel
Labels: P2, cla: yes, pr: lgtm, pr: merge ready, pr: merge safe

#15617 fix(option): Remove aria-selected='false' in single-selection mode
  src/lib/core/option/option.ts
  src/lib/select/select.spec.ts
  tools/public_api_guard/lib/core.d.ts
Labels: G, P2, a11y, cla: yes, pr: lgtm, pr: merge ready

#15679 cleanup(universal-app): various improvements
  src/universal-app/index.html
  src/universal-app/kitchen-sink-root.ts
  src/universal-app/kitchen-sink/kitchen-sink.html
  src/universal-app/kitchen-sink/kitchen-sink.ts
  src/universal-app/main.ts
  src/universal-app/prerender.ts
  src/universal-app/tsconfig-build.json
  src/universal-app/tsconfig-prerender.json
  src/universal-app/tsconfig.json
  tools/gulp/tasks/universal.ts
Labels: cla: yes, pr: lgtm, pr: merge ready, pr: merge safe, target: patch

#15490 fix(form-field): remove nonbreaking space before * for required fields
  src/lib/form-field/form-field.html
  src/lib/input/input.spec.ts
Labels: G, P2, cla: yes, pr: lgtm, pr: merge ready, target: patch

#15588 build: add validation for prebuilt cdk css
  tools/release/release-output/check-package.ts
  tools/release/release-output/output-validations.ts
Labels: cla: yes, pr: lgtm, pr: merge ready, pr: merge safe, target: patch

#15688 docs(layout): fix breakpoint url to material.io
  src/cdk/layout/layout.md
Labels: cla: yes, docs, pr: lgtm, pr: merge ready, pr: merge safe, target: patch

#15370 docs(drag-drop): add docs and live example for delay input
  src/cdk/drag-drop/drag-drop.md
  src/material-examples/cdk-drag-drop-delay/cdk-drag-drop-delay-example.css
  src/material-examples/cdk-drag-drop-delay/cdk-drag-drop-delay-example.html
  src/material-examples/cdk-drag-drop-delay/cdk-drag-drop-delay-example.ts
Labels: cla: yes, docs, pr: lgtm, pr: merge ready, pr: merge safe, target: major

#15496 feat(popover-edit): experimental popover edit for tables (mvp)
  .github/CODEOWNERS
  packages.bzl
  src/cdk-experimental/popover-edit/BUILD.bazel
  src/cdk-experimental/popover-edit/constants.ts
  src/cdk-experimental/popover-edit/edit-event-dispatcher.ts
  src/cdk-experimental/popover-edit/edit-ref.ts
  src/cdk-experimental/popover-edit/index.ts
  src/cdk-experimental/popover-edit/lens-directives.ts
  src/cdk-experimental/popover-edit/polyfill.ts
  src/cdk-experimental/popover-edit/popover-edit-module.ts
  src/cdk-experimental/popover-edit/popover-edit-position-strategy-factory.ts
  src/cdk-experimental/popover-edit/popover-edit.spec.ts
  src/cdk-experimental/popover-edit/public-api.ts
  src/cdk-experimental/popover-edit/table-directives.ts
  src/cdk-experimental/popover-edit/tsconfig-build.json
  src/dev-app/BUILD.bazel
  src/dev-app/dev-app/dev-app-layout.ts
  src/dev-app/dev-app/routes.ts
  src/dev-app/popover-edit/popover-edit-demo-module.ts
  src/dev-app/popover-edit/popover-edit-demo.ts
  src/dev-app/system-config.ts
  src/material-examples/BUILD.bazel
  src/material-examples/cdk-popover-edit-cdk-table-flex/cdk-popover-edit-cdk-table-flex-example.css
  src/material-examples/cdk-popover-edit-cdk-table-flex/cdk-popover-edit-cdk-table-flex-example.html
  src/material-examples/cdk-popover-edit-cdk-table-flex/cdk-popover-edit-cdk-table-flex-example.ts
  src/material-examples/cdk-popover-edit-cdk-table/cdk-popover-edit-cdk-table-example.css
  src/material-examples/cdk-popover-edit-cdk-table/cdk-popover-edit-cdk-table-example.html
  src/material-examples/cdk-popover-edit-cdk-table/cdk-popover-edit-cdk-table-example.ts
  src/material-examples/cdk-popover-edit-vanilla-table/cdk-popover-edit-vanilla-table-example.css
  src/material-examples/cdk-popover-edit-vanilla-table/cdk-popover-edit-vanilla-table-example.html
  src/material-examples/cdk-popover-edit-vanilla-table/cdk-popover-edit-vanilla-table-example.ts
  src/material-examples/material-module.ts
  src/material-examples/tsconfig-build.json
Labels: P2, cla: yes, pr: lgtm, pr: merge ready, pr: merge safe, target: patch

#15690 chore(e2e): switch to Sass theme instead of prebuilt
  src/e2e-app/BUILD.bazel
  src/e2e-app/index.html
  src/e2e-app/theme.scss
Labels: cla: yes, pr: lgtm, pr: merge ready, pr: merge safe, target: patch

#15693 fix: error when attempting to access Intl API on some versions of Windows
  src/cdk/platform/platform.ts
  src/lib/core/datetime/native-date-adapter.ts
Labels: P2, cla: yes, pr: lgtm, pr: merge ready, target: patch

#14696 feat(drag-drop): add API to get/set current position of a standalone draggable
  src/cdk/drag-drop/directives/drag.spec.ts
  src/cdk/drag-drop/directives/drag.ts
  src/cdk/drag-drop/drag-ref.ts
  tools/public_api_guard/cdk/drag-drop.d.ts
Labels: P2, cla: yes, pr: lgtm, pr: merge ready, target: minor

#15706 chore: fix popover compilation error
  src/cdk-experimental/popover-edit/edit-ref.ts
Labels: cla: yes, pr: merge safe, target: patch

#15654 fix(dialog): remove default aria-label from mat-dialog-close
  src/lib/dialog/dialog-content-directives.ts
  src/lib/dialog/dialog.md
  src/lib/dialog/dialog.spec.ts
  tools/public_api_guard/lib/dialog.d.ts
Labels: P2, a11y, cla: yes, pr: lgtm, pr: merge ready, target: patch

#15647 refactor: constructor breaking changes for 8.0
  src/cdk/drag-drop/directives/drag.ts
  src/cdk/drag-drop/directives/drop-list.ts
  src/cdk/overlay/position/connected-position-strategy.ts
  src/cdk/overlay/position/flexible-connected-position-strategy.ts
  src/cdk/overlay/position/overlay-position-builder.ts
  src/cdk/schematics/ng-update/data/constructor-checks.ts
  src/cdk/table/table.ts
  src/lib/form-field/form-field.ts
  src/lib/schematics/ng-update/data/constructor-checks.ts
  src/lib/tabs/tab-nav-bar/tab-nav-bar.ts
  tools/public_api_guard/cdk/drag-drop.d.ts
  tools/public_api_guard/cdk/overlay.d.ts
  tools/public_api_guard/cdk/table.d.ts
  tools/public_api_guard/lib/form-field.d.ts
  tools/public_api_guard/lib/tabs.d.ts
Labels: P2, cla: yes, pr: lgtm, pr: merge ready, target: major

#15725 chore: bump version to 7.3.7 w/ changelog
  CHANGELOG.md
  package.json
Labels: cla: yes, pr: lgtm, pr: merge ready, pr: merge safe, target: patch

#15726 chore: changelog for 7.3.7
  CHANGELOG.md
Labels: cla: yes, pr: merge safe, target: major

#15737 chore: add cdk-experimental to deps for material-examples
  scripts/bazel/build-packages.sh
  tools/gulp/packages.ts
Labels: cla: yes, pr: merge safe, target: major

#15552 fix(list): not picking up indirect descendant lines
  src/lib/list/list.spec.ts
  src/lib/list/list.ts
Labels: G, cla: yes, pr: lgtm, pr: merge ready, target: patch

#15711 fix: missing tag in footer-row of material table
  src/lib/table/table.md
Labels: cla: yes, pr: lgtm, pr: merge ready, pr: merge safe, target: patch

#15739 chore: bump version to 8.0.0-beta.0 w/ changelog
  CHANGELOG.md
  package.json
Labels: cla: yes, pr: lgtm, pr: merge ready, pr: merge safe, target: major

#15740 chore: add release name for 8.0.0-beta.0
  CHANGELOG.md
Labels: cla: yes, pr: lgtm, pr: merge ready, pr: merge safe, target: major

#15746 chore: remove precommit hook since it doesn't work on windows
  .huskyrc.json
Labels: cla: yes, pr: lgtm, pr: merge ready, pr: merge safe, target: patch

#15753 feat: run v8 migration schematics for v8 beta and rc releases
  src/cdk/schematics/migration.json
  src/lib/schematics/migration.json
Labels: P1, cla: yes, pr: lgtm, pr: merge ready, pr: merge safe, target: major

#15757 chore: bump version to 8.0.0-beta.1 w/ changelog
  CHANGELOG.md
  package.json
Labels: cla: yes, pr: lgtm, pr: merge ready, pr: merge safe, target: major

#15772 build: disable branch manager check
  .github/branch-manager.yml
Labels: cla: yes, pr: lgtm, pr: merge ready, pr: merge safe, target: patch

#15770 chore(a11y): Allow FocusTrap to be extended
  src/cdk/a11y/focus-trap/focus-trap.ts
  tools/public_api_guard/cdk/a11y.d.ts
Labels: cla: yes, pr: lgtm, pr: merge ready, pr: merge safe, target: minor

#15758 refactor(badge): breaking constructor changes for 8.0
  src/lib/badge/badge.ts
  src/lib/schematics/ng-update/data/constructor-checks.ts
  tools/public_api_guard/lib/badge.d.ts
Labels: P2, cla: yes, pr: lgtm, pr: merge ready, target: major

#15734 refactor(button): constructor changes for 8.0
  src/lib/button/BUILD.bazel
  src/lib/button/button.ts
  src/lib/schematics/ng-update/data/constructor-checks.ts
  tools/public_api_guard/lib/button.d.ts
Labels: P2, cla: yes, pr: lgtm, pr: merge ready, target: major

#15761 refactor(progress-spinner): breaking constructor changes for 8.0
  src/lib/progress-spinner/progress-spinner.ts
  src/lib/schematics/ng-update/data/constructor-checks.ts
  tools/public_api_guard/lib/progress-spinner.d.ts
Labels: P2, cla: yes, pr: lgtm, pr: merge ready, target: major

#15723 refactor(list): constructor breaking changes for 8.0
  src/lib/list/list.ts
  src/lib/schematics/ng-update/data/constructor-checks.ts
  tools/public_api_guard/lib/list.d.ts
Labels: P2, cla: yes, pr: lgtm, pr: merge ready, target: major

#15722 refactor(expansion): constructor breaking changes for 8.0
  src/lib/expansion/expansion-panel.ts
  src/lib/schematics/ng-update/data/constructor-checks.ts
  tools/public_api_guard/lib/expansion.d.ts
Labels: P2, cla: yes, pr: lgtm, pr: merge ready, target: major

#15738 refactor(tabs): constructor breaking changes for 8.0
  src/lib/schematics/ng-update/data/constructor-checks.ts
  src/lib/tabs/tab-body.ts
  src/lib/tabs/tab-header.ts
  tools/public_api_guard/lib/tabs.d.ts
Labels: P2, caretaker note, cla: yes, pr: lgtm, pr: merge ready, target: major

#15762 feat(popover-edit): Arrow keys move focus to neighboring cells
  src/cdk-experimental/popover-edit/BUILD.bazel
  src/cdk-experimental/popover-edit/constants.ts
  src/cdk-experimental/popover-edit/focus-dispatcher.ts
  src/cdk-experimental/popover-edit/popover-edit.spec.ts
  src/cdk-experimental/popover-edit/public-api.ts
  src/cdk-experimental/popover-edit/table-directives.ts
Labels: cla: yes, pr: lgtm, pr: merge ready, pr: merge safe, target: minor

#15825 build(popover-edit): Fix bazel rule to include cdk/scrolling
  src/cdk-experimental/popover-edit/BUILD.bazel
Labels: cla: yes, pr: lgtm, pr: merge ready, pr: merge safe, target: minor

#15826 chore: bump version to 8.0.0-beta.2 w/ changelog
  CHANGELOG.md
  package.json
Labels: cla: yes, pr: lgtm, pr: merge ready, pr: merge safe, target: major

#15769 docs(theming): add explicit customization guidance
  guides/theming.md
Labels: cla: yes, docs, pr: lgtm, pr: merge ready, pr: merge safe, target: patch

#15774 docs(cdk): add cdk-drag-handle to Styling
  src/cdk/drag-drop/drag-drop.md
Labels: cla: yes, pr: lgtm, pr: merge ready, pr: merge safe, target: patch

#15783 chore: fix miscellaneous typos in comments
  src/cdk/a11y/focus-monitor/focus-monitor.ts
  src/cdk/scrolling/virtual-scroll-viewport.scss
  src/module-typings.d.ts
Labels: cla: yes, pr: lgtm, pr: merge ready, pr: merge safe, target: patch

#15784 docs(readme): general update and refresh
  README.md
Labels: cla: yes, docs, pr: lgtm, pr: merge ready, pr: merge safe

#15793 feat(popover-edit): allow tabbing from popup to next/previous cell
  src/cdk-experimental/popover-edit/edit-event-dispatcher.ts
  src/cdk-experimental/popover-edit/edit-ref.ts
  src/cdk-experimental/popover-edit/focus-escape-notifier.ts
  src/cdk-experimental/popover-edit/lens-directives.ts
  src/cdk-experimental/popover-edit/popover-edit-module.ts
  src/cdk-experimental/popover-edit/popover-edit.spec.ts
  src/cdk-experimental/popover-edit/table-directives.ts
  src/material-examples/cdk-popover-edit-tab-out-vanilla-table/cdk-popover-edit-tab-out-vanilla-table-example.css
  src/material-examples/cdk-popover-edit-tab-out-vanilla-table/cdk-popover-edit-tab-out-vanilla-table-example.html
  src/material-examples/cdk-popover-edit-tab-out-vanilla-table/cdk-popover-edit-tab-out-vanilla-table-example.ts
Labels: cla: yes, pr: lgtm, pr: merge ready, pr: merge safe, target: minor

#15700 refactor: move version export to core entry-point
  src/lib/core/public-api.ts
  src/lib/core/version.ts
  src/lib/public-api.ts
  src/lib/schematics/ng-update/test-cases/misc/material-imports.spec.ts
  src/lib/schematics/ng-update/test-cases/misc/material-imports_expected_output.ts
  src/lib/schematics/ng-update/test-cases/misc/material-imports_input.ts
  src/lib/schematics/ng-update/test-cases/v8/material-subpackage_expected_output.ts
  src/lib/schematics/ng-update/test-cases/v8/material-subpackage_input.ts
  src/lib/schematics/ng-update/upgrade-rules/package-imports-v8/updateAngularMaterialImportsRule.ts
  tools/public_api_guard/lib/core.d.ts
  tools/public_api_guard/lib/lib.d.ts
Labels: P1, cla: yes, pr: lgtm, pr: merge ready, target: major

#15835 build: wire up dev-server for ivy demo-app
  scripts/ivy/README.md
  scripts/ivy/build.sh
  src/dev-app/rollup-bundles.js
  tools/gulp/gulpfile.ts
  tools/gulp/tasks/ivy-serve.ts
Labels: cla: yes, pr: merge safe

#15837 refactor(sidenav): rework animation listeners to account for Ivy
  src/lib/sidenav/drawer.ts
  src/lib/sidenav/sidenav.ts
  tools/public_api_guard/lib/sidenav.d.ts
Labels: P1, cla: yes, pr: lgtm, pr: merge safe

#15797 perf(popover-edit): collect common services into a single class for dependency injection
  src/cdk-experimental/popover-edit/edit-services.ts
  src/cdk-experimental/popover-edit/popover-edit.spec.ts
  src/cdk-experimental/popover-edit/table-directives.ts
Labels: cla: yes, pr: lgtm, pr: merge ready, pr: merge safe, target: minor

#15842 docs(button): fix jsdoc on MatAnchor
  src/lib/button/button.ts
Labels: cla: yes, pr: lgtm, pr: merge ready, pr: merge safe, target: patch

#15843 build: make cdk-experimental and material-experimental build settings
  src/cdk-experimental/tsconfig-build.json
  src/material-experimental/mdc-checkbox/checkbox.ts
  src/material-experimental/mdc-checkbox/public-api.ts
  src/material-experimental/tsconfig-build.json
  src/material-experimental/tsconfig.json
  tools/gulp/packages.ts
Labels: cla: yes, pr: lgtm, pr: merge ready, pr: merge safe, target: major

#15818 build: add fixer to import spacing rule
  tools/tslint-rules/noImportSpacingRule.ts
Labels: cla: yes, pr: lgtm, pr: merge ready, pr: merge safe, target: patch

#15720 refactor(form-field): explicitly set static flag on all queries
  src/lib/form-field/form-field.ts
  src/lib/select/select.spec.ts
  tools/public_api_guard/lib/form-field.d.ts
Labels: P1, cla: yes, pr: lgtm, pr: merge ready, target: patch

#15721 refactor(autocomplete): explicitly set static flag on all queries
  src/lib/autocomplete/autocomplete.ts
Labels: P1, cla: yes, pr: lgtm, pr: merge ready, target: patch

#15836 refactor(sidenav): rework animation listeners to account for Ivy
  src/lib/sidenav/drawer.ts
  src/lib/sidenav/sidenav.ts
  tools/public_api_guard/lib/sidenav.d.ts
Labels: P1, cla: yes, pr: lgtm, pr: merge ready, target: patch

#15860 build: fix race condition when building styles
  tools/package-tools/gulp/build-tasks-gulp.ts
Labels: cla: yes, pr: lgtm, pr: merge ready, pr: merge safe, target: patch

#15847 Fixes conjugation issue in table guide
  src/lib/table/table.md
Labels: cla: yes, pr: lgtm, pr: merge ready, pr: merge safe, target: patch

#15863 chore: fix typo in MDC skeleton code
  src/material-experimental/mdc-button/button.ts
  src/material-experimental/mdc-card/card.ts
  src/material-experimental/mdc-menu/menu.ts
  src/material-experimental/mdc-radio/radio.ts
  src/material-experimental/mdc-slide-toggle/slide-toggle.ts
Labels: cla: yes, pr: lgtm, pr: merge ready, pr: merge safe, target: major

#15875 chore: fix type-checking issue in input demo
  src/dev-app/input/input-demo.html
Labels: cla: yes

#15877 fix(autocomplete): make template ViewChild query `static: true`
  src/lib/autocomplete/autocomplete.ts
Labels: P1, cla: yes, pr: lgtm, pr: merge ready

#15806 refactor(slide-toggle): constructor breaking changes for 8.0
  src/lib/schematics/ng-update/data/constructor-checks.ts
  src/lib/slide-toggle/BUILD.bazel
  src/lib/slide-toggle/slide-toggle.ts
  tools/public_api_guard/lib/slide-toggle.d.ts
Labels: P2, cla: yes, pr: lgtm, pr: merge ready, target: major

#15805 fix(drag-drop): not reacting to changes in the cdkDragFreeDragPosition
  src/cdk/drag-drop/directives/drag.spec.ts
  src/cdk/drag-drop/directives/drag.ts
Labels: P2, cla: yes, pr: lgtm, pr: merge ready, target: major

#14841 feat(table): add text column for simple columns
  src/cdk/table/cell.ts
  src/cdk/table/public-api.ts
  src/cdk/table/table-errors.ts
  src/cdk/table/table-module.ts
  src/cdk/table/table.spec.ts
  src/cdk/table/text-column.spec.ts
  src/cdk/table/text-column.ts
  src/lib/table/public-api.ts
  src/lib/table/table-module.ts
  src/lib/table/table.md
  src/lib/table/table.spec.ts
  src/lib/table/table.ts
  src/lib/table/text-column.spec.ts
  src/lib/table/text-column.ts
  src/material-examples/table-simple-column/table-simple-column-example.html
  src/material-examples/table-simple-column/table-simple-column-example.ts
  src/material-examples/table-text-column-advanced/table-text-column-advanced-example.css
  src/material-examples/table-text-column-advanced/table-text-column-advanced-example.html
  src/material-examples/table-text-column-advanced/table-text-column-advanced-example.ts
  src/material-examples/table-text-column/table-text-column-example.css
  src/material-examples/table-text-column/table-text-column-example.html
  src/material-examples/table-text-column/table-text-column-example.ts
  tools/public_api_guard/cdk/table.d.ts
  tools/public_api_guard/lib/table.d.ts
Labels: P2, cla: yes, pr: lgtm, pr: merge ready, target: minor

#15773 refactor(sidenav): constructor breaking changes for 8.0
  src/lib/schematics/ng-update/data/constructor-checks.ts
  src/lib/sidenav/drawer.ts
  tools/public_api_guard/lib/sidenav.d.ts
Labels: P2, cla: yes, pr: lgtm, pr: merge ready, target: major

#15871 refactor(menu): change menu item host listeners so they can be safely inherited
  src/lib/menu/menu-item.ts
Labels: P2, cla: yes, pr: lgtm, pr: merge ready, target: major

#15850 chore(menu): minor file reorganization
  src/lib/menu/menu-directive.ts
  src/lib/menu/menu-module.ts
  src/lib/menu/menu-trigger.ts
  src/lib/menu/menu.ts
  src/lib/menu/public-api.ts
Labels: P2, cla: yes, pr: lgtm, pr: merge ready, target: patch

#15897 chore: fix typo
  src/material-experimental/mdc-checkbox/README.md
Labels: cla: yes, pr: lgtm, pr: merge ready, target: patch

#15895 chore: fix inherited host binding issue with sidenav
  src/material/sidenav/drawer.ts
  src/material/sidenav/sidenav.ts
Labels: P2, cla: yes, pr: lgtm, pr: merge ready, target: patch

#15743 refactor: remove mixin classes from public api
  src/cdk/table/cell.ts
  src/cdk/table/row.ts
  src/material-experimental/mdc-checkbox/public-api.ts
  src/material/autocomplete/autocomplete.ts
  src/material/badge/badge.ts
  src/material/button-toggle/button-toggle.ts
  src/material/button/button.ts
  src/material/checkbox/checkbox.ts
  src/material/chips/chip-list.ts
  src/material/chips/chip.ts
  src/material/core/option/optgroup.ts
  src/material/datepicker/datepicker.ts
  src/material/form-field/form-field.ts
  src/material/icon/icon.ts
  src/material/input/input.ts
  src/material/list/list.ts
  src/material/list/selection-list.ts
  src/material/menu/menu-item.ts
  src/material/paginator/paginator.ts
  src/material/progress-bar/progress-bar.ts
  src/material/progress-spinner/progress-spinner.ts
  src/material/radio/radio.ts
  src/material/select/select.ts
  src/material/slide-toggle/slide-toggle.ts
  src/material/slider/slider.ts
  src/material/sort/sort-header.ts
  src/material/sort/sort.ts
  src/material/tabs/tab-group.ts
  src/material/tabs/tab-header.ts
  src/material/tabs/tab-label-wrapper.ts
  src/material/tabs/tab-nav-bar/tab-nav-bar.ts
  src/material/tabs/tab.ts
  src/material/toolbar/toolbar.ts
  src/material/tree/node.ts
  tools/public_api_guard/cdk/table.d.ts
  tools/public_api_guard/material/autocomplete.d.ts
  tools/public_api_guard/material/badge.d.ts
  tools/public_api_guard/material/button-toggle.d.ts
  tools/public_api_guard/material/button.d.ts
  tools/public_api_guard/material/checkbox.d.ts
  tools/public_api_guard/material/chips.d.ts
  tools/public_api_guard/material/core.d.ts
  tools/public_api_guard/material/datepicker.d.ts
  tools/public_api_guard/material/form-field.d.ts
  tools/public_api_guard/material/icon.d.ts
  tools/public_api_guard/material/input.d.ts
  tools/public_api_guard/material/list.d.ts
  tools/public_api_guard/material/paginator.d.ts
  tools/public_api_guard/material/progress-bar.d.ts
  tools/public_api_guard/material/progress-spinner.d.ts
  tools/public_api_guard/material/radio.d.ts
  tools/public_api_guard/material/select.d.ts
  tools/public_api_guard/material/slide-toggle.d.ts
  tools/public_api_guard/material/slider.d.ts
  tools/public_api_guard/material/sort.d.ts
  tools/public_api_guard/material/tabs.d.ts
  tools/public_api_guard/material/toolbar.d.ts
  tools/public_api_guard/material/tree.d.ts
Labels: P2, cla: yes, pr: lgtm, pr: merge ready, target: major

#15870 fix(stepper): Fix visual flake in focusing stepper header
  src/material/stepper/step-header.ts
  tools/public_api_guard/material/stepper.d.ts
Labels: G, cla: yes, pr: lgtm, pr: merge ready, target: patch

#15857 prototype(menu): create prototype menu based on MDC Web
  e2e/components/mdc-menu-e2e.spec.ts
  e2e/components/menu-e2e.spec.ts
  src/dev-app/mdc-menu/mdc-menu-demo-module.ts
  src/dev-app/mdc-menu/mdc-menu-demo.html
  src/dev-app/mdc-menu/mdc-menu-demo.scss
  src/dev-app/mdc-menu/mdc-menu-demo.ts
  src/e2e-app/mdc-menu/mdc-menu-e2e.html
  src/e2e-app/mdc-menu/mdc-menu-e2e.ts
  src/material-experimental/mdc-menu/BUILD.bazel
  src/material-experimental/mdc-menu/README.md
  src/material-experimental/mdc-menu/_mdc-menu.scss
  src/material-experimental/mdc-menu/menu-item.html
  src/material-experimental/mdc-menu/menu-item.ts
  src/material-experimental/mdc-menu/menu.html
  src/material-experimental/mdc-menu/menu.scss
  src/material-experimental/mdc-menu/menu.spec.ts
  src/material-experimental/mdc-menu/menu.ts
  src/material-experimental/mdc-menu/module.ts
  src/material-experimental/mdc-menu/public-api.ts
  src/material/core/style/_menu-common.scss
  src/material/menu/menu-animations.ts
  src/material/menu/menu-module.ts
  src/material/menu/menu-trigger.ts
  src/material/menu/menu.scss
  src/material/menu/menu.ts
  src/material/menu/public-api.ts
  src/universal-app/kitchen-sink-mdc/kitchen-sink-mdc.html
  tools/public_api_guard/material/menu.d.ts
Labels: P2, cla: yes, pr: lgtm, pr: merge ready, target: major

#15906 chore: move null config check into mat-using-mdc-typography
  src/material-experimental/mdc-button/_mdc-button.scss
  src/material-experimental/mdc-card/_mdc-card.scss
  src/material-experimental/mdc-checkbox/_mdc-checkbox.scss
  src/material-experimental/mdc-helpers/_mdc-helpers.scss
  src/material-experimental/mdc-menu/_mdc-menu.scss
  src/material-experimental/mdc-radio/_mdc-radio.scss
  src/material-experimental/mdc-slide-toggle/_mdc-slide-toggle.scss
Labels: cla: yes, pr: lgtm, pr: merge ready, pr: merge safe

#15905 chore: update "material2" to "components"
  .circleci/config.yml
  CONTRIBUTING.md
  DEV_ENVIRONMENT.md
  README.md
  guides/theming.md
  guides/typography.md
  package.json
  scripts/caretaking/write-presubmit-scheduler.js
  scripts/deploy/publish-docs-content.sh
  src/README.md
  src/cdk-experimental/package.json
  src/cdk/package.json
  src/cdk/platform/platform.ts
  src/cdk/schematics/ng-update/data/attribute-selectors.ts
  src/cdk/schematics/ng-update/data/class-names.ts
  src/cdk/schematics/ng-update/data/constructor-checks.ts
  src/cdk/schematics/ng-update/data/input-names.ts
  src/cdk/schematics/ng-update/data/method-call-checks.ts
  src/cdk/schematics/ng-update/data/property-names.ts
  src/cdk/schematics/ng-update/update-schematic.md
  src/cdk/schematics/ng-update/upgrade-rules/signature-check/constructorSignatureCheckRule.ts
  src/cdk/schematics/utils/build-component.ts
  src/dev-app/dev-app/dev-app-module.ts
  src/e2e-app/devserver-configure.js
  src/e2e-app/e2e-app/e2e-app-module.ts
  src/material-examples/package.json
  src/material-examples/table-http/table-http-example.ts
  src/material-experimental/mdc-checkbox/checkbox.ts
  src/material-experimental/package.json
  src/material-moment-adapter/package.json
  src/material/button-toggle/button-toggle.scss
  src/material/button/button.scss
  src/material/card/card.scss
  src/material/core/datetime/native-date-adapter.ts
  src/material/form-field/form-field-input.scss
  src/material/form-field/form-field-legacy.scss
  src/material/form-field/form-field-outline.scss
  src/material/input/input.ts
  src/material/package.json
  src/material/progress-spinner/progress-spinner.scss
  src/material/progress-spinner/progress-spinner.ts
  src/material/schematics/ng-add/theming/theming.ts
  src/material/schematics/ng-update/data/class-names.ts
  src/material/schematics/ng-update/data/constructor-checks.ts
  src/material/schematics/ng-update/data/css-selectors.ts
  src/material/schematics/ng-update/data/element-selectors.ts
  src/material/schematics/ng-update/data/input-names.ts
  src/material/schematics/ng-update/data/output-names.ts
  src/material/schematics/ng-update/data/property-names.ts
  src/material/schematics/ng-update/upgrade-rules/misc-checks/checkImportsMiscRule.ts
  src/material/tabs/tab-header.ts
  tools/release/publish-release.ts
  tools/release/release-output/output-validations.ts
  tools/release/stage-release.ts
Labels: cla: yes, pr: lgtm, pr: merge ready, pr: merge safe, target: major

#15893 prototype(slide-toggle): create prototype menu based on MDC Web
  e2e/components/mdc-slide-toggle-e2e.spec.ts
  src/dev-app/mdc-slide-toggle/mdc-slide-toggle-demo-module.ts
  src/dev-app/mdc-slide-toggle/mdc-slide-toggle-demo.html
  src/dev-app/mdc-slide-toggle/mdc-slide-toggle-demo.scss
  src/dev-app/mdc-slide-toggle/mdc-slide-toggle-demo.ts
  src/e2e-app/mdc-slide-toggle/mdc-slide-toggle-e2e.html
  src/e2e-app/mdc-slide-toggle/mdc-slide-toggle-e2e.ts
  src/material-experimental/mdc-slide-toggle/BUILD.bazel
  src/material-experimental/mdc-slide-toggle/README.md
  src/material-experimental/mdc-slide-toggle/_mdc-slide-toggle.scss
  src/material-experimental/mdc-slide-toggle/module.ts
  src/material-experimental/mdc-slide-toggle/public-api.ts
  src/material-experimental/mdc-slide-toggle/slide-toggle-config.ts
  src/material-experimental/mdc-slide-toggle/slide-toggle.html
  src/material-experimental/mdc-slide-toggle/slide-toggle.scss
  src/material-experimental/mdc-slide-toggle/slide-toggle.spec.ts
  src/material-experimental/mdc-slide-toggle/slide-toggle.ts
  src/universal-app/kitchen-sink-mdc/kitchen-sink-mdc.html
Labels: P2, cla: yes, pr: lgtm, pr: merge ready, pr: merge safe, target: major

#15907 chore: minor prototype fixes
  src/material-experimental/mdc-menu/menu.scss
  src/material-experimental/mdc-slide-toggle/slide-toggle.scss
Labels: cla: yes, pr: lgtm, pr: merge ready, pr: merge safe, target: major

#15908 ci: fix snapshots
  scripts/deploy/publish-docs-content.sh
Labels: cla: yes

#15910 Fixed double quotes in table.md
  src/material/table/table.md
Labels: cla: yes, pr: lgtm, pr: merge ready, pr: merge safe, target: patch

#15873 feat(popover-edit): Material version
  .github/CODEOWNERS
  packages.bzl
  src/cdk-experimental/popover-edit/constants.ts
  src/cdk-experimental/popover-edit/edit-services.ts
  src/cdk-experimental/popover-edit/lens-directives.ts
  src/cdk-experimental/popover-edit/table-directives.ts
  src/dev-app/BUILD.bazel
  src/dev-app/popover-edit/assets/edit-icon.svg
  src/dev-app/system-config.ts
  src/dev-app/theme.scss
  src/material-examples/BUILD.bazel
  src/material-examples/material-module.ts
  src/material-examples/popover-edit-cell-span-mat-table/popover-edit-cell-span-mat-table-example.css
  src/material-examples/popover-edit-cell-span-mat-table/popover-edit-cell-span-mat-table-example.html
  src/material-examples/popover-edit-cell-span-mat-table/popover-edit-cell-span-mat-table-example.ts
  src/material-examples/popover-edit-mat-table-flex/popover-edit-mat-table-flex-example.css
  src/material-examples/popover-edit-mat-table-flex/popover-edit-mat-table-flex-example.html
  src/material-examples/popover-edit-mat-table-flex/popover-edit-mat-table-flex-example.ts
  src/material-examples/popover-edit-mat-table/popover-edit-mat-table-example.css
  src/material-examples/popover-edit-mat-table/popover-edit-mat-table-example.html
  src/material-examples/popover-edit-mat-table/popover-edit-mat-table-example.ts
  src/material-examples/popover-edit-tab-out-mat-table/popover-edit-tab-out-mat-table-example.css
  src/material-examples/popover-edit-tab-out-mat-table/popover-edit-tab-out-mat-table-example.html
  src/material-examples/popover-edit-tab-out-mat-table/popover-edit-tab-out-mat-table-example.ts
  src/material-examples/tsconfig-build.json
  src/material-experimental/popover-edit/BUILD.bazel
  src/material-experimental/popover-edit/_popover-edit.scss
  src/material-experimental/popover-edit/index.ts
  src/material-experimental/popover-edit/lens-directives.ts
  src/material-experimental/popover-edit/popover-edit-module.ts
  src/material-experimental/popover-edit/popover-edit.spec.ts
  src/material-experimental/popover-edit/public-api.ts
  src/material-experimental/popover-edit/table-directives.ts
  src/material-experimental/popover-edit/tsconfig-build.json
  src/material-experimental/tsconfig-build.json
  test/karma-system-config.js
Labels: cla: yes, pr: lgtm, pr: merge ready, pr: merge safe, target: patch

#15916 build(popover): switch lib to material
  src/material-experimental/popover-edit/BUILD.bazel
  src/material-experimental/popover-edit/_popover-edit.scss
Labels: cla: yes, pr: lgtm, pr: merge ready, pr: merge safe, target: major

#15909 chore: update to angular 8.0.0-rc.1
  WORKSPACE
  package.json
  src/cdk/schematics/ng-add/index.spec.ts
  src/cdk/schematics/ng-generate/drag-drop/index.spec.ts
  src/cdk/schematics/ng-update/test-cases/misc/method-call-checks.spec.ts
  src/cdk/schematics/testing/test-app.ts
  src/cdk/schematics/testing/test-case-setup.ts
  src/cdk/schematics/utils/ast.ts
  src/cdk/schematics/utils/get-project.ts
  src/cdk/schematics/utils/project-main-file.ts
  src/cdk/schematics/utils/project-style-file.ts
  src/cdk/schematics/utils/project-targets.ts
  src/cdk/schematics/utils/schematic-options.ts
  src/e2e-app/BUILD.bazel
  src/material/schematics/ng-add/fonts/project-index-html.ts
  src/material/schematics/ng-add/index.spec.ts
  src/material/schematics/ng-add/theming/theming.ts
  src/material/schematics/ng-generate/address-form/index.spec.ts
  src/material/schematics/ng-generate/dashboard/index.spec.ts
  src/material/schematics/ng-generate/nav/index.spec.ts
  src/material/schematics/ng-generate/table/index.spec.ts
  src/material/schematics/ng-generate/tree/index.spec.ts
  src/material/schematics/ng-update/test-cases/misc/constructor-checks.spec.ts
  src/material/schematics/ng-update/test-cases/misc/import-checks.spec.ts
  src/material/schematics/ng-update/test-cases/misc/material-imports.spec.ts
  tools/package-tools/compile-entry-point.ts
  tools/public_api_guard/generate-guard-tests.bzl
  yarn.lock
Labels: cla: yes, pr: lgtm, pr: merge ready, pr: merge safe, target: major

#15921 build: dev app not being updated when mdc theme files are changed
  tools/gulp/tasks/development.ts
Labels: cla: yes, pr: lgtm, pr: merge ready, pr: merge safe, target: patch

#15925 build: fix material-examples build
  src/material-examples/package.json
  src/material-examples/tsconfig.json
  tools/gulp/packages.ts
Labels: cla: yes, pr: lgtm, pr: merge ready, pr: merge safe, target: patch

#15927 chore: bump version to 8.0.0-rc.0 w/ changelog
  CHANGELOG.md
  package.json
Labels: cla: yes, pr: lgtm, pr: merge ready, pr: merge safe, target: major
