Repository angular/components, pull requests merged in 2019-10, with the labels that each got.

#17251 build: tests should not fail if stylesheets contain quotes
  tools/defaults.bzl
Labels: cla: yes, pr: lgtm, pr: merge ready, pr: merge safe, target: patch

#17250 Fix <img> tag rendering as html instead of text
  src/material/icon/icon.md
Labels: cla: yes, commit message fixup, docs, pr: lgtm, pr: merge ready, target: patch

#17249 build: update bazel setup to rules_nodejs v0.38.0
  WORKSPACE
  package.json
  src/e2e-app/BUILD.bazel
  tools/bazel/angular_bazel_0.38.0.patch
  tools/bazel/postinstall-patches.js
  tools/defaults.bzl
  yarn.lock
Labels: cla: yes, pr: lgtm, pr: merge ready, pr: merge safe, target: patch

#17247 build: ensure build-packages-dist script works on macOS
  scripts/build-packages-dist.sh
Labels: cla: yes, pr: lgtm, pr: merge ready, pr: merge safe, target: patch

#17150 fix(cdk/drag-drop): dragging styles not reset once dragging is…
  src/cdk/drag-drop/directives/drag.spec.ts
  src/cdk/drag-drop/drag-ref.ts
Labels: P1, cla: yes, pr: lgtm, pr: merge ready, target: patch

#17149 refactor: move force-stabilize from TestElement to ComponentHarness
  src/cdk/testing/component-harness.ts
  src/cdk/testing/harness-environment.ts
  src/cdk/testing/protractor/protractor-element.ts
  src/cdk/testing/protractor/protractor-harness-environment.ts
  src/cdk/testing/test-element.ts
  src/cdk/testing/testbed/testbed-harness-environment.ts
  src/cdk/testing/testbed/unit-test-element.ts
  tools/public_api_guard/cdk/testing.d.ts
Labels: P1, caretaker note, cla: yes, pr: lgtm, pr: merge ready, target: major

#17222 refactor(google-maps): Removes reference to GoogleMap from MapMarker
  src/google-maps/google-map/google-map.spec.ts
  src/google-maps/google-map/google-map.ts
  src/google-maps/map-marker/map-marker.spec.ts
  src/google-maps/map-marker/map-marker.ts
  src/google-maps/testing/fake-google-map-utils.ts
Labels: cla: yes, pr: lgtm, pr: merge ready, pr: merge safe, target: major

#17173 build: validate bazel rollup globals
  .circleci/config.yml
  BUILD.bazel
  package.json
  rollup-globals.bzl
  scripts/check-rollup-globals.ts
  src/cdk/config.bzl
  src/material-experimental/mdc-button/testing/button-harness.ts
  src/material-experimental/mdc-menu/testing/menu-harness.ts
  src/material-experimental/mdc-menu/testing/menu-item-harness.ts
  src/material/menu/testing/menu-item-harness.ts
  src/material/radio/testing/radio-harness.ts
  tools/package-tools/rollup-globals.ts
  tools/tslint-rules/missingRollupGlobalsRule.ts
  tslint.json
Labels: P1, cla: yes, pr: lgtm, pr: merge ready, target: patch

#17218 chore(testing): fix compilation for TS3.6.
  src/cdk/testing/event-objects.ts
Labels: P1, cla: yes, pr: lgtm, pr: merge ready, target: patch

#17259 docs(datepicker): add missing provider
  src/material-examples/material/datepicker/datepicker-formats/datepicker-formats-example.ts
  src/material-examples/material/datepicker/datepicker-locale/datepicker-locale-example.ts
  src/material-examples/material/datepicker/datepicker-views-selection/datepicker-views-selection-example.ts
Labels: cla: yes, docs, pr: lgtm, pr: merge ready, pr: merge safe, target: patch

#17229 fix(material-experimental/checkbox): model value not updated through toggle method
  src/material-experimental/mdc-checkbox/checkbox.spec.ts
  src/material-experimental/mdc-checkbox/checkbox.ts
Labels: P3, cla: yes, pr: lgtm, pr: merge ready, pr: merge safe, target: patch

#17207 fix(material-experimental/slider): incorrectly rendering extra background
  src/material-experimental/mdc-slider/slider.ts
Labels: P3, cla: yes, pr: lgtm, pr: merge ready, pr: merge safe, target: patch

#17196 chore: remove secondary entrypoint reexport config
  tools/gulp/packages.ts
Labels: cla: yes, pr: lgtm, pr: merge ready, pr: merge safe, target: major

#17003 feat(tooltip): remove Hammer.js dependency
  src/material/tooltip/BUILD.bazel
  src/material/tooltip/tooltip-module.ts
  src/material/tooltip/tooltip.md
  src/material/tooltip/tooltip.spec.ts
  src/material/tooltip/tooltip.ts
  tools/public_api_guard/material/tooltip.d.ts
Labels: P1, cla: yes, pr: lgtm, pr: merge ready, target: major

#17228 fix(tabs): avoid template type checking errors with Ivy
  src/material/tabs/paginated-tab-header.ts
  src/material/tabs/public-api.ts
  src/material/tabs/tab-body.ts
  src/material/tabs/tab-group.ts
  src/material/tabs/tab-header.ts
  src/material/tabs/tab-nav-bar/tab-nav-bar.ts
  src/material/tabs/tabs-module.ts
Labels: P1, cla: yes, pr: lgtm, pr: merge ready, target: patch

#17267 build: do generate invalid semver versions for snapshot builds
  scripts/deploy/publish-build-artifacts.sh
  scripts/deploy/publish-docs-content.sh
Labels: cla: yes, pr: lgtm, pr: merge ready, pr: merge safe, target: patch

#17245 build: populate release version placeholder properly
  tools/bazel-stamp-vars.js
Labels: P1, cla: yes, pr: lgtm, pr: merge ready, pr: merge safe, target: patch

#17273 build: fix write permissions for bazel npm_package output
  scripts/deploy/publish-docs-content.sh
Labels: cla: yes, pr: lgtm, pr: merge ready, pr: merge safe, target: patch

#17256 chore: bump version to 8.2.2 w/ changelog
  CHANGELOG.md
  package.json
Labels: cla: yes, pr: lgtm, pr: merge ready, target: major

#15403 fix(stepper): unable to skip step if completed value is overwritten
  src/cdk/stepper/stepper.ts
  src/material/stepper/stepper.spec.ts
  tools/public_api_guard/cdk/stepper.d.ts
Labels: P4, cla: yes, pr: lgtm, pr: merge ready, target: patch

#14919 fix(overlay): error when trying to add/remove empty string class
  src/cdk/overlay/overlay-ref.ts
  src/cdk/overlay/overlay.spec.ts
Labels: cla: yes, pr: lgtm, pr: merge ready, target: patch

#17224 prototype(progress-bar): create prototype progress bar based on MDC web
  .github/CODEOWNERS
  src/dev-app/BUILD.bazel
  src/dev-app/dev-app/dev-app-layout.ts
  src/dev-app/dev-app/routes.ts
  src/dev-app/mdc-progress-bar/BUILD.bazel
  src/dev-app/mdc-progress-bar/mdc-progress-bar-demo-module.ts
  src/dev-app/mdc-progress-bar/mdc-progress-bar-demo.html
  src/dev-app/mdc-progress-bar/mdc-progress-bar-demo.scss
  src/dev-app/mdc-progress-bar/mdc-progress-bar-demo.ts
  src/dev-app/system-config.js
  src/e2e-app/BUILD.bazel
  src/e2e-app/e2e-app/e2e-app-layout.html
  src/e2e-app/e2e-app/routes.ts
  src/e2e-app/main-module.ts
  src/e2e-app/mdc-progress-bar/mdc-progress-bar-e2e-module.ts
  src/e2e-app/mdc-progress-bar/mdc-progress-bar-e2e.html
  src/e2e-app/mdc-progress-bar/mdc-progress-bar-e2e.ts
  src/e2e-app/theme.scss
  src/material-experimental/config.bzl
  src/material-experimental/mdc-progress-bar/BUILD.bazel
  src/material-experimental/mdc-progress-bar/README.md
  src/material-experimental/mdc-progress-bar/_mdc-progress-bar.scss
  src/material-experimental/mdc-progress-bar/index.ts
  src/material-experimental/mdc-progress-bar/module.ts
  src/material-experimental/mdc-progress-bar/progress-bar.e2e.spec.ts
  src/material-experimental/mdc-progress-bar/progress-bar.html
  src/material-experimental/mdc-progress-bar/progress-bar.scss
  src/material-experimental/mdc-progress-bar/progress-bar.spec.ts
  src/material-experimental/mdc-progress-bar/progress-bar.ts
  src/material-experimental/mdc-progress-bar/public-api.ts
  src/material-experimental/mdc-progress-bar/testing/BUILD.bazel
  src/material-experimental/mdc-progress-bar/testing/index.ts
  src/material-experimental/mdc-progress-bar/testing/progress-bar-harness.spec.ts
  src/material-experimental/mdc-progress-bar/testing/progress-bar-harness.ts
  src/material-experimental/mdc-progress-bar/testing/public-api.ts
  src/material-experimental/mdc-progress-bar/tsconfig-build.json
  src/material-experimental/mdc-theming/BUILD.bazel
  src/material-experimental/mdc-theming/_all-theme.scss
  src/material-experimental/mdc-typography/BUILD.bazel
  src/material-experimental/mdc-typography/_all-typography.scss
  src/material/progress-bar/testing/shared.spec.ts
  src/universal-app/kitchen-sink-mdc/kitchen-sink-mdc.html
  src/universal-app/kitchen-sink-mdc/kitchen-sink-mdc.ts
  test/karma-system-config.js
Labels: P3, cla: yes, pr: lgtm, pr: merge ready, pr: merge safe, target: patch

#17202 fix(datepicker): year not formatted in multi-year view button
  src/material/datepicker/calendar-header.spec.ts
  src/material/datepicker/calendar.ts
  src/material/datepicker/datepicker-intl.ts
  tools/public_api_guard/material/datepicker.d.ts
Labels: P3, cla: yes, i18n, pr: lgtm, pr: merge ready, target: patch

#17213 fix(select): highlighted option not updated if value is reset while closed
  src/material/select/select.spec.ts
  src/material/select/select.ts
Labels: P3, cla: yes, pr: lgtm, pr: merge ready, target: patch

#17271 docs(dialog): remove errant comma, adjust period use
  src/material/dialog/dialog-config.ts
Labels: cla: yes, docs, pr: lgtm, pr: merge ready, pr: merge safe, target: patch

#17217 chore(drag-drop): Fix compilation in TS3.6.
  src/cdk/drag-drop/drag-styling.ts
Labels: cla: yes, pr: lgtm, pr: merge ready, target: patch

#17268 refactor: clean up remaining hammer.js usages
  .github/CODEOWNERS
  guides/getting-started.md
  guides/schematics.md
  package.json
  src/dev-app/BUILD.bazel
  src/dev-app/dev-app/dev-app-layout.ts
  src/dev-app/dev-app/dev-app-module.ts
  src/dev-app/dev-app/routes.ts
  src/dev-app/gestures/BUILD.bazel
  src/dev-app/gestures/gestures-demo-module.ts
  src/dev-app/gestures/gestures-demo.html
  src/dev-app/gestures/gestures-demo.scss
  src/dev-app/gestures/gestures-demo.ts
  src/dev-app/index.html
  src/e2e-app/BUILD.bazel
  src/e2e-app/e2e-app/e2e-app-module.ts
  src/e2e-app/index.html
  src/material-experimental/mdc-slide-toggle/README.md
  src/material/core/common-behaviors/common-module.ts
  src/material/core/gestures/gesture-annotations.ts
  src/material/core/gestures/gesture-config.spec.ts
  src/material/core/gestures/gesture-config.ts
  src/material/schematics/ng-add/gestures/hammerjs-import.ts
  src/material/schematics/ng-add/index.spec.ts
  src/material/schematics/ng-add/index.ts
  src/material/schematics/ng-add/schema.json
  src/material/schematics/ng-add/schema.ts
  src/material/schematics/ng-add/setup-project.ts
  src/material/schematics/ng-add/version-names.ts
  src/material/slider/slider.spec.ts
  src/material/testing/index.ts
  src/material/testing/test-gesture-config.ts
  test/karma.conf.js
  tools/defaults.bzl
  tools/public_api_guard/material/core.d.ts
  yarn.lock
Labels: P1, cla: yes, pr: lgtm, pr: merge ready, target: major

#17284 fix(material-experimental/mdc): use state container for button interaction
  src/material-experimental/mdc-button/_button-base.scss
  src/material-experimental/mdc-button/_mdc-button.scss
  src/material-experimental/mdc-button/button.html
  src/material-experimental/mdc-button/button.scss
  src/material-experimental/mdc-button/fab.scss
  src/material-experimental/mdc-button/icon-button.scss
Labels: cla: yes, pr: lgtm, pr: merge ready, pr: merge safe, target: patch

#17167 fix(a11y): focus monitor not identifying touch focus inside shadow root
  src/cdk/a11y/focus-monitor/focus-monitor.ts
Labels: P3, cla: yes, pr: lgtm, pr: merge ready, target: patch

#17168 refactor: clean up deprecated uses of combineLatest
  src/cdk-experimental/popover-edit/edit-event-dispatcher.ts
  src/cdk/table/table.spec.ts
  src/cdk/tree/tree.spec.ts
  src/google-maps/google-map/google-map.ts
  src/google-maps/map-info-window/map-info-window.ts
  src/google-maps/map-marker/map-marker.ts
  src/material/table/table-data-source.ts
  src/youtube-player/youtube-player.ts
Labels: P3, cla: yes, pr: lgtm, pr: merge ready, target: patch

#17285 build: change alpha/beta prerelease options to "next"
  tools/release/prompt/prerelease-labels.ts
Labels: cla: yes, pr: lgtm, pr: merge ready, pr: merge safe, target: major

#17282 fix(tabs): avoid Ivy template type checking errors in tab link
  src/material/tabs/tab-nav-bar/tab-nav-bar.ts
  src/material/tabs/tabs-module.ts
Labels: P1, cla: yes, pr: lgtm, pr: merge ready, target: patch

#17278 build: re-add theming scss bundle to material package
  package.json
  src/material/BUILD.bazel
  src/material/_theming.scss
  tools/sass-bundle.ts
  tools/sass_bundle.bzl
  yarn.lock
Labels: P1, cla: yes, pr: lgtm, pr: merge ready, pr: merge safe, target: major

#17286 refactor(ng-update): do not visit external stylesheets multiple times
  src/cdk/schematics/BUILD.bazel
  src/cdk/schematics/ng-update/test-cases/misc/global-stylesheets-test.scss
  src/cdk/schematics/ng-update/test-cases/misc/global-stylesheets.spec.ts
  src/cdk/schematics/ng-update/test-cases/misc/global-stylesheets_input.ts
  src/cdk/schematics/update-tool/index.ts
Labels: cla: yes, pr: lgtm, pr: merge ready, pr: merge safe, target: patch

#17288 chore: bump version to 9.0.0-next.0 w/ changelog
  CHANGELOG.md
  package.json
Labels: cla: yes, pr: lgtm, pr: merge ready, pr: merge safe, target: major

#16817 build: remove workaround for ivy test job
  .circleci/config.yml
  scripts/circleci/setup-ivy-ngcc.js
Labels: cla: yes, pr: lgtm, pr: merge ready, pr: merge safe, target: major

#17289 build: let release script parse "next" in versions
  tools/release/version-name/parse-version.ts
Labels: cla: yes, pr: lgtm, pr: merge ready, pr: merge safe, target: patch

#17244 build: include favicon in dev-app to avoid error
  src/dev-app/BUILD.bazel
Labels: cla: yes, pr: lgtm, pr: merge ready, pr: merge safe, target: patch

#17195 docs(cdk/testing): add guide for using harnesses
  src/cdk/testing/using-component-harnesses.md
Labels: P1, cla: yes, pr: lgtm, pr: merge ready, pr: merge safe, target: major

#17248 build: fix gulp release output not building
  package.json
  src/material/tsconfig-build.json
  tools/gulp/packages.ts
Labels: cla: yes, pr: lgtm, pr: merge ready, pr: merge safe, target: major

#17290 build: publish snapshot scripts incorrectly updating unrelated code
  scripts/deploy/publish-build-artifacts.sh
  scripts/deploy/publish-docs-content.sh
Labels: cla: yes, pr: lgtm, pr: merge ready, pr: merge safe, target: major

#17293 build: generate api docs for all tertiary entry-points
  src/BUILD.bazel
  src/cdk/BUILD.bazel
  src/cdk/config.bzl
  src/cdk/testing/BUILD.bazel
  src/cdk/testing/protractor/BUILD.bazel
  src/cdk/testing/testbed/BUILD.bazel
  src/material/autocomplete/testing/BUILD.bazel
  src/material/button/testing/BUILD.bazel
  src/material/checkbox/testing/BUILD.bazel
  src/material/dialog/testing/BUILD.bazel
  src/material/menu/testing/BUILD.bazel
  src/material/progress-bar/testing/BUILD.bazel
  src/material/progress-spinner/testing/BUILD.bazel
  src/material/radio/testing/BUILD.bazel
  src/material/sidenav/testing/BUILD.bazel
  src/material/slide-toggle/testing/BUILD.bazel
  src/material/slider/testing/BUILD.bazel
  src/material/snack-bar/testing/BUILD.bazel
  src/material/tabs/testing/BUILD.bazel
  tools/dgeni/bazel-bin.ts
  tools/dgeni/common/class-inheritance.ts
  tools/dgeni/common/decorators.ts
  tools/dgeni/common/dgeni-definitions.ts
  tools/dgeni/docs-package.ts
  tools/dgeni/index.bzl
  tools/dgeni/processors/categorizer.ts
  tools/dgeni/processors/entry-point-grouper.ts
  tools/dgeni/processors/merge-inherited-properties.ts
  tools/dgeni/templates/entry-point.template.html
  tools/dgeni/tsconfig.json
Labels: cla: yes, pr: lgtm, pr: merge ready, pr: merge safe, target: major

#17279 refactor: annotate remaining base classes with @directive for ivy
  src/cdk-experimental/popover-edit/popover-edit.spec.ts
  src/material-experimental/mdc-button/button-base.ts
  src/material-experimental/mdc-button/module.ts
  src/material-experimental/popover-edit/popover-edit.spec.ts
  src/material/menu/menu-module.ts
  src/material/menu/menu.ts
  tools/tslint-rules/noUndecoratedClassWithNgFieldsRule.ts
  tslint.json
Labels: P1, cla: yes, pr: lgtm, pr: merge ready, target: major

#17272 feat: move clipboard module into cdk
  .github/CODEOWNERS
  src/cdk-experimental/config.bzl
  src/cdk/clipboard/BUILD.bazel
  src/cdk/clipboard/clipboard-module.ts
  src/cdk/clipboard/clipboard.md
  src/cdk/clipboard/clipboard.spec.ts
  src/cdk/clipboard/clipboard.ts
  src/cdk/clipboard/copy-to-clipboard.spec.ts
  src/cdk/clipboard/copy-to-clipboard.ts
  src/cdk/clipboard/index.ts
  src/cdk/clipboard/public-api.ts
  src/cdk/clipboard/tsconfig-build.json
  src/cdk/config.bzl
  src/dev-app/system-config.js
  src/material-examples/BUILD.bazel
  src/material-examples/cdk/clipboard/BUILD.bazel
  src/material-examples/cdk/clipboard/cdk-clipboard-overview/cdk-clipboard-overview-example.css
  src/material-examples/cdk/clipboard/cdk-clipboard-overview/cdk-clipboard-overview-example.html
  src/material-examples/cdk/clipboard/cdk-clipboard-overview/cdk-clipboard-overview-example.ts
  src/material-examples/cdk/clipboard/module.ts
  src/material-examples/example-module.ts
  test/karma-system-config.js
  tools/public_api_guard/cdk/clipboard.d.ts
Labels: P1, caretaker note, cla: yes, pr: lgtm, pr: merge ready, target: major

#17313 build: changelog should not show changes to google-maps
  tools/release/changelog.ts
Labels: cla: yes, pr: lgtm, pr: merge ready, pr: merge safe, target: major

#17322 refactor(google-maps): Remove duplicate module
  src/google-maps/google-maps-module.ts
Labels: cla: yes, pr: lgtm, pr: merge ready, pr: merge safe, target: major

#17275 docs(cdk/testing): create user docs for cdk/testing
  src/cdk/testing/testing.md
Labels: P1, cla: yes, docs, pr: lgtm, pr: merge ready, pr: merge safe, target: major

#17332 chore: move guide on using Angular Material harnesses under the guides directory
  guides/using-component-harnesses.md
Labels: cla: yes, pr: lgtm, pr: merge ready, pr: merge safe, target: major

#17299 docs(platform): remove comment from API docs
  src/cdk/platform/platform.ts
Labels: cla: yes, docs, pr: lgtm, pr: merge ready, pr: merge safe, target: patch

#17320 fix(cdk-experimental/dialog): don't move focus if it was moved during close animation
  src/cdk-experimental/dialog/dialog-container.ts
  src/cdk-experimental/dialog/dialog.spec.ts
Labels: P3, cla: yes, pr: lgtm, pr: merge ready, pr: merge safe, target: patch

#17329 docs(overlay): Minor comment fix in overlay.ts
  src/cdk/overlay/overlay.ts
Labels: cla: yes, commit message fixup, docs, pr: lgtm, pr: merge ready, pr: merge safe, target: patch

#17334 chore: bump version to 8.2.3 w/ changelog
  CHANGELOG.md
  package.json
Labels: cla: yes, pr: lgtm, pr: merge ready, pr: merge safe, target: patch

#17335 chore: copy 8.2.3 changelog to master
  CHANGELOG.md
Labels: cla: yes, pr: lgtm, pr: merge ready, target: major

#17337 docs: update readme for q4 2019
  README.md
Labels: cla: yes, docs, pr: lgtm, pr: merge ready, pr: merge safe, target: major

#17341 docs(overlay): Drop extra `the` in a comment
  src/cdk/overlay/overlay.ts
Labels: cla: yes, docs, pr: lgtm, pr: merge ready, pr: merge safe, target: patch

#17343 chore: remove unused branch-manager config
  .github/branch-manager.yml
Labels: cla: yes, pr: lgtm, pr: merge ready, pr: merge safe, target: major

#17342 build: set up remote-http-caching
  .bazelrc
Labels: cla: yes, pr: lgtm, pr: merge ready, pr: merge safe, target: major

#17360 build: reintroduce static query rule
  tools/tslint-rules/staticQueryRule.ts
  tslint.json
Labels: P3, cla: yes, pr: merge ready, pr: merge safe, target: patch

#17362 build: ensure to never output files next to sources
  scripts/tsconfig.json
  tools/cherry-pick-patch/tsconfig.json
  tools/release/tsconfig.json
Labels: cla: yes, pr: lgtm, pr: merge ready, pr: merge safe, target: patch

#17349 fix(material-experimental/mdc-button): elevate z-index of content
  src/material-experimental/mdc-button/_button-base.scss
Labels: cla: yes, pr: lgtm, pr: merge ready, pr: merge safe, target: patch

#17345 docs(overlay): Comment type fix - `DOM the` -> `the DOM`
  src/cdk/overlay/overlay-ref.ts
Labels: cla: yes, pr: lgtm, pr: merge ready, pr: merge safe, target: major

#17344 docs(dialog): align text with material design
  src/material/dialog/dialog.md
Labels: cla: yes, pr: lgtm, pr: merge ready, pr: merge safe, target: patch

#17361 chore: update to nodejs rules 0.38.2
  WORKSPACE
  package.json
  tools/bazel/angular_bazel_0.38.0.patch
  tools/bazel/angular_bazel_0.38.2.patch
  tools/bazel/postinstall-patches.js
  tools/dev-server/index.bzl
  yarn.lock
Labels: cla: yes, pr: lgtm, pr: merge ready, pr: merge safe, target: major

#17364 fix(google-maps): Fix issues with google maps inputs
  src/google-maps/google-map/google-map.spec.ts
  src/google-maps/google-map/google-map.ts
  src/google-maps/map-info-window/map-info-window.ts
  src/google-maps/map-marker/map-marker.ts
  src/google-maps/testing/fake-google-map-utils.ts
Labels: cla: yes, pr: lgtm, pr: merge ready, pr: merge safe, target: major

#17359 fix(material-experimental/progress-bar): server-side rendering error
  src/material-experimental/mdc-progress-bar/BUILD.bazel
  src/material-experimental/mdc-progress-bar/progress-bar.ts
Labels: P3, cla: yes, pr: lgtm, pr: merge ready, pr: merge safe, target: major

#16529 fix(tabs): no longer use OnPush
  src/material/tabs/tab-body.ts
  src/material/tabs/tab-group.ts
  src/material/tabs/tab-header.ts
  src/material/tabs/tab-nav-bar/tab-nav-bar.ts
  src/material/tabs/tab.ts
Labels: cla: yes, pr: lgtm, pr: merge ready, target: patch

#17331 perf(tooltip): avoid triggering change detection for all keydown events
  src/material/tooltip/tooltip.ts
  tools/public_api_guard/material/tooltip.d.ts
Labels: P3, cla: yes, pr: lgtm, pr: merge ready, target: patch

#17310 fix(drag-drop): only call enterPredicate when pointer is inside drop list
  src/cdk/drag-drop/directives/drag.spec.ts
  src/cdk/drag-drop/drop-list-ref.ts
Labels: P4, cla: yes, pr: lgtm, pr: merge ready, target: patch

#17303 fix(form-field): outline gap not calculated in shadow dom
  src/material/form-field/form-field.ts
  src/material/input/input.spec.ts
Labels: P2, cla: yes, pr: lgtm, pr: merge ready, target: patch

#17363 Adds a date selection model
  src/material/core/datetime/date-selection-model.ts
  src/material/core/datetime/index.ts
  tools/public_api_guard/material/core.d.ts
Labels: cla: yes

#17376 chore: update to nodejs rules 0.38.3
  WORKSPACE
  package.json
  yarn.lock
Labels: cla: yes, pr: lgtm, pr: merge ready, pr: merge safe, target: major

#17373 build: do not generate type definitions without reference to needed global types
  src/google-maps/google-map/google-map.ts
  src/google-maps/map-info-window/map-info-window.ts
  src/google-maps/map-marker/map-marker.ts
  src/google-maps/tsconfig-build.json
  src/google-maps/tsconfig-tests.json
  src/google-maps/tsconfig.json
  src/youtube-player/tsconfig-build.json
  src/youtube-player/tsconfig-tests.json
  src/youtube-player/tsconfig.json
  src/youtube-player/youtube-player.ts
Labels: cla: yes, pr: lgtm, pr: merge ready, pr: merge safe, target: major

#17369 feat(material/ng-update): add migration for hammerjs in version 9
  src/cdk/private/testing/public-api.ts
  src/cdk/private/testing/text-dedent.ts
  src/cdk/schematics/index.ts
  src/cdk/schematics/ng-update/index.ts
  src/cdk/schematics/ng-update/upgrade-rules/index.ts
  src/cdk/schematics/testing/test-case-setup.ts
  src/cdk/schematics/update-tool/index.ts
  src/cdk/schematics/update-tool/migration-rule.ts
  src/cdk/schematics/update-tool/target-version.ts
  src/cdk/schematics/utils/index.ts
  src/cdk/schematics/utils/project-index-file.ts
  src/cdk/schematics/utils/project-targets.ts
  src/material/schematics/BUILD.bazel
  src/material/schematics/ng-add/fonts/material-fonts.ts
  src/material/schematics/ng-add/fonts/project-index-html.ts
  src/material/schematics/ng-add/index.spec.ts
  src/material/schematics/ng-add/theming/theming.ts
  src/material/schematics/ng-update/index.ts
  src/material/schematics/ng-update/test-cases/v9/hammer-migration-v9.spec.ts
  src/material/schematics/ng-update/upgrade-rules/hammer-gestures-v9/cli-workspace.ts
  src/material/schematics/ng-update/upgrade-rules/hammer-gestures-v9/find-hammer-script-tags.ts
  src/material/schematics/ng-update/upgrade-rules/hammer-gestures-v9/gesture-config.template
  src/material/schematics/ng-update/upgrade-rules/hammer-gestures-v9/hammer-gestures-rule.ts
  src/material/schematics/ng-update/upgrade-rules/hammer-gestures-v9/hammer-template-check.ts
  src/material/schematics/ng-update/upgrade-rules/hammer-gestures-v9/identifier-imports.ts
  src/material/schematics/ng-update/upgrade-rules/hammer-gestures-v9/import-manager.ts
  src/material/schematics/ng-update/upgrade-rules/hammer-gestures-v9/remove-array-element.ts
  src/material/schematics/ng-update/upgrade-rules/hammer-gestures-v9/remove-element-from-html.ts
Labels: cla: yes, pr: lgtm, pr: merge ready, pr: merge safe, target: major

#17393 feat: change tslib from direct dependency to peerDependency
  src/cdk-experimental/package.json
  src/cdk/package.json
  src/material-examples/package.json
  src/material-experimental/package.json
  src/material-moment-adapter/package.json
  src/material/package.json
Labels: cla: yes, pr: lgtm, pr: merge ready, pr: merge safe, target: major

#17389 build: update to latest Angular version
  package.json
  src/cdk/schematics/testing/test-app.ts
  yarn.lock
Labels: P3, cla: yes, pr: lgtm, pr: merge ready, pr: merge safe, target: major

#17388 build: add linting for classList usage
  src/material-experimental/mdc-button/button-base.ts
  tools/tslint-rules/classListSignaturesRule.ts
  tslint.json
Labels: P3, cla: yes, pr: lgtm, pr: merge ready, pr: merge safe, target: patch

#17301 feat(drag-drop): allow drag start delay to be configured based on event type
  src/cdk/drag-drop/directives/drag.spec.ts
  src/cdk/drag-drop/directives/drag.ts
  src/cdk/drag-drop/drag-ref.ts
  tools/public_api_guard/cdk/drag-drop.d.ts
Labels: P3, cla: yes, pr: lgtm, pr: merge ready, target: major

#17396 fix(google-maps): Fix clickable input for MapMarker
  src/google-maps/map-marker/map-marker.ts
Labels: cla: yes, pr: lgtm, pr: merge ready, pr: merge safe, target: major

#17385 refactor(a11y): remove deprecated APIs for 9.0.0
  src/cdk/a11y/aria-describer/aria-describer.ts
  src/cdk/a11y/focus-monitor/focus-monitor.ts
  src/cdk/a11y/key-manager/list-key-manager.spec.ts
  src/cdk/a11y/key-manager/list-key-manager.ts
  src/cdk/a11y/live-announcer/live-announcer.ts
  src/cdk/stepper/stepper.ts
  src/material-experimental/mdc-chips/chip-listbox.ts
  src/material/chips/chip-list.ts
  src/material/stepper/stepper.spec.ts
  src/material/tabs/paginated-tab-header.ts
  tools/public_api_guard/cdk/a11y.d.ts
Labels: P2, cla: yes, pr: lgtm, pr: merge ready, target: major

#17365 fix(menu): trigger should aria-controls panel
  src/material-experimental/mdc-menu/menu.html
  src/material-experimental/mdc-menu/menu.spec.ts
  src/material/menu/menu-panel.ts
  src/material/menu/menu-trigger.ts
  src/material/menu/menu.html
  src/material/menu/menu.spec.ts
  src/material/menu/menu.ts
  tools/public_api_guard/material/menu.d.ts
Labels: P1, a11y, cla: yes, pr: lgtm, pr: merge ready, target: patch

#17346 fix(tabs): not picking up indirect descendant tabs in ivy
  src/material-experimental/mdc-tabs/public-api.ts
  src/material-experimental/mdc-tabs/tab-group.spec.ts
  src/material-experimental/mdc-tabs/tab-group.ts
  src/material/tabs/public-api.ts
  src/material/tabs/tab-group.spec.ts
  src/material/tabs/tab-group.ts
  src/material/tabs/tab.ts
  tools/public_api_guard/material/tabs.d.ts
Labels: P1, cla: yes, pr: lgtm, pr: merge ready, target: patch

#17379 feat(material/menu/testing): finish implementing harness
  src/cdk/testing/component-harness.ts
  src/material-experimental/mdc-menu/testing/menu-harness.spec.ts
  src/material-experimental/mdc-menu/testing/menu-harness.ts
  src/material-experimental/mdc-menu/testing/menu-item-harness.ts
  src/material-experimental/mdc-menu/testing/public-api.ts
  src/material/menu/testing/BUILD.bazel
  src/material/menu/testing/menu-harness-filters.ts
  src/material/menu/testing/menu-harness.ts
  src/material/menu/testing/menu-item-harness.ts
  src/material/menu/testing/public-api.ts
  src/material/menu/testing/shared.spec.ts
  tools/public_api_guard/cdk/testing.d.ts
Labels: P1, cla: yes, pr: lgtm, pr: merge ready, target: major

#17414 feat(material/radio/testing): polish harness API
  src/material/radio/testing/BUILD.bazel
  src/material/radio/testing/radio-harness.ts
  src/material/radio/testing/shared.spec.ts
Labels: P1, cla: yes, pr: lgtm, pr: merge ready, target: major

#17416 feat(material/slide-toggle/testing): polish harness API
  src/material-experimental/mdc-slide-toggle/testing/slide-toggle-harness.ts
  src/material/slide-toggle/testing/shared.spec.ts
  src/material/slide-toggle/testing/slide-toggle-harness-filters.ts
  src/material/slide-toggle/testing/slide-toggle-harness.ts
Labels: P2, cla: yes, pr: lgtm, pr: merge ready, target: major

#17348 fix(material-experimental/mdc-slider): remove theme import from all-theme
  src/dev-app/BUILD.bazel
  src/dev-app/theme.scss
  src/material-experimental/mdc-theming/BUILD.bazel
  src/material-experimental/mdc-theming/_all-theme.scss
  src/universal-app/BUILD.bazel
  src/universal-app/theme.scss
Labels: cla: yes, pr: lgtm, pr: merge ready, pr: merge safe, target: patch

#17413 docs(drag-drop): expose DragRef and DragListRef to docs
  src/cdk/drag-drop/drag-ref.ts
  src/cdk/drag-drop/drop-list-ref.ts
Labels: cla: yes, docs, pr: lgtm, pr: merge ready, pr: merge safe, target: patch

#17421 fix(cdk/scrolling): expand type for "cdkVirtualForOf" input to work with strict null checks
  src/cdk/scrolling/virtual-for-of.ts
  tools/public_api_guard/cdk/scrolling.d.ts
Labels: P1, cla: yes, pr: lgtm, pr: merge ready, target: major

#17426 build: set up API golden file for youtube-player package
  .github/CODEOWNERS
  tools/public_api_guard/generate-guard-tests.bzl
  tools/public_api_guard/youtube-player/youtube-player.d.ts
Labels: P3, cla: yes, pr: lgtm, pr: merge ready, pr: merge safe, target: patch

#17230 refactor(select): remove deprecated APIs for 9.0.0
  src/material/schematics/ng-update/data/constructor-checks.ts
  src/material/select/select-animations.ts
  src/material/select/select.ts
  tools/public_api_guard/material/select.d.ts
Labels: P2, cla: yes, pr: lgtm, pr: merge ready, target: major

#17430 build: do not show inherited protected members in api docs
  tools/dgeni/processors/merge-inherited-properties.ts
Labels: P1, cla: yes, pr: lgtm, pr: merge ready, pr: merge safe, target: major

#17429 refactor: ensure hammer migration properly sets up gesture config in app module
  src/cdk/schematics/update-tool/index.ts
  src/cdk/schematics/update-tool/migration-rule.ts
  src/material/schematics/ng-update/test-cases/v9/hammer-migration-v9.spec.ts
  src/material/schematics/ng-update/upgrade-rules/hammer-gestures-v9/find-main-module.ts
  src/material/schematics/ng-update/upgrade-rules/hammer-gestures-v9/hammer-gestures-rule.ts
Labels: P1, cla: yes, pr: lgtm, pr: merge ready, pr: merge safe, target: major

#17431 build: bump required angular version for upcoming v9 release
  package.json
  packages.bzl
Labels: cla: yes, pr: lgtm, pr: merge ready, pr: merge safe, target: major

#17432 build: add lint rules banning `new`-ing of Object, String, Number and Boolean
  package.json
  tslint.json
  yarn.lock
Labels: cla: yes, pr: lgtm, pr: merge ready, pr: merge safe, target: major

#17409 feat(tabs): add input to opt out of pagination
  src/material-experimental/mdc-tabs/tab-header.spec.ts
  src/material/tabs/paginated-tab-header.ts
  src/material/tabs/tab-group.html
  src/material/tabs/tab-group.ts
  src/material/tabs/tab-header.spec.ts
  tools/public_api_guard/material/tabs.d.ts
Labels: P2, cla: yes, pr: lgtm, pr: merge ready, target: major

#17417 feat(material/tabs/testing): polish harness API
  src/cdk/testing/component-harness.ts
  src/cdk/testing/harness-environment.ts
  src/material/tabs/testing/BUILD.bazel
  src/material/tabs/testing/shared.spec.ts
  src/material/tabs/testing/tab-group-harness.ts
  src/material/tabs/testing/tab-harness-filters.ts
  src/material/tabs/testing/tab-harness.ts
  tools/public_api_guard/cdk/testing.d.ts
Labels: P1, cla: yes, pr: lgtm, pr: merge ready, target: major

#17302 refactor(collections): remove deprecated APIs for 9.0.0
  src/cdk/collections/public-api.ts
  src/cdk/collections/selection-model.ts
  src/cdk/collections/selection.spec.ts
  src/cdk/collections/tree-adapter.ts
  src/cdk/schematics/ng-update/data/property-names.ts
  src/dev-app/tree/dynamic-tree-demo/dynamic-database.ts
  src/material-examples/material/tree/tree-dynamic/tree-dynamic-example.ts
  src/material/list/selection-list.ts
  src/material/select/select.ts
  src/material/tree/data-source/flat-data-source.ts
  tools/public_api_guard/cdk/collections.d.ts
Labels: P2, cla: yes, pr: lgtm, pr: merge ready, target: major

#17425 fix(chips): don't set aria-required when element doesn't have a role
  src/material-experimental/mdc-chips/chip-grid.spec.ts
  src/material-experimental/mdc-chips/chip-grid.ts
  src/material-experimental/mdc-chips/chip-listbox.spec.ts
  src/material-experimental/mdc-chips/chip-listbox.ts
  src/material/chips/chip-list.spec.ts
  src/material/chips/chip-list.ts
Labels: P2, cla: yes, pr: lgtm, pr: merge ready, target: patch

#17424 fix(drag-drop): unable to drop into connected list inside shadow DOM and ngIf
  src/cdk/drag-drop/directives/drag.spec.ts
  src/cdk/drag-drop/drop-list-ref.ts
Labels: P2, cla: yes, pr: lgtm, pr: merge ready, target: patch

#17439 fix(form-field): ensure that descendants are picked up in Ivy
  src/material/form-field/form-field.ts
Labels: P1, cla: yes, pr: lgtm, pr: merge ready, target: major

#17257 fix(drag-drop): global resize subscription not cleared
  src/cdk/drag-drop/drag-ref.ts
Labels: P2, cla: yes, pr: lgtm, pr: merge ready, target: patch

#17304 feat(drag-drop): allow for custom class to be set on preview
  src/cdk/drag-drop/directives/drag.spec.ts
  src/cdk/drag-drop/directives/drag.ts
  src/cdk/drag-drop/drag-ref.ts
  tools/public_api_guard/cdk/drag-drop.d.ts
Labels: P3, cla: yes, pr: lgtm, pr: merge ready, target: major

#17300 fix(dialog): don't move focus if it was moved during close animation
  src/material/dialog/dialog-container.ts
  src/material/dialog/dialog.spec.ts
Labels: P3, cla: yes, pr: lgtm, pr: merge ready, target: patch

#17239 fix(snack-bar): handle large numbers passed in as duration
  src/material/snack-bar/snack-bar-ref.ts
  src/material/snack-bar/snack-bar.spec.ts
Labels: P4, cla: yes, pr: lgtm, pr: merge ready, target: patch

#17226 fix(drag-drop): not picking up indirect descendant items
  src/cdk/drag-drop/directives/drag.spec.ts
  src/cdk/drag-drop/directives/drop-list.ts
Labels: P3, cla: yes, pr: lgtm, pr: merge ready, target: patch

#17447 build: bump to latest MDC version and fix error in master
  package.json
  src/material-experimental/mdc-progress-bar/progress-bar.ts
  yarn.lock
Labels: P3, cla: yes, pr: lgtm, pr: merge ready, pr: merge safe, target: patch

#17444 refactor: hammer migration should add "HammerModule" if needed
  src/material/schematics/ng-update/test-cases/v9/hammer-migration-v9.spec.ts
  src/material/schematics/ng-update/upgrade-rules/hammer-gestures-v9/hammer-gestures-rule.ts
Labels: P1, cla: yes, pr: lgtm, pr: merge ready, pr: merge safe, target: major

#17455 refactor(ng-update): run package manager upon migration completion
  src/cdk/schematics/ng-update/upgrade-rules/index.ts
  src/cdk/schematics/update-tool/migration-rule.ts
  src/material/schematics/ng-update/upgrade-rules/hammer-gestures-v9/hammer-gestures-rule.ts
Labels: P1, cla: yes, pr: lgtm, pr: merge ready, pr: merge safe, target: major

#17452 fix(schematics): secondary entry point migration not working against v9
  scripts/generate-schematic-imports-map.ts
  src/material/schematics/ng-update/test-cases/v8/material-imports.spec.ts
  src/material/schematics/ng-update/test-cases/v8/material-imports_expected_output.ts
  src/material/schematics/ng-update/test-cases/v8/material-imports_input.ts
  src/material/schematics/ng-update/test-cases/v9/material-imports.spec.ts
  src/material/schematics/ng-update/test-cases/v9/material-imports_expected_output.ts
  src/material/schematics/ng-update/test-cases/v9/material-imports_input.ts
  src/material/schematics/ng-update/upgrade-rules/package-imports-v8/material-symbols.json
  src/material/schematics/ng-update/upgrade-rules/package-imports-v8/secondary-entry-points-rule.ts
Labels: P1, cla: yes, pr: lgtm, pr: merge ready, pr: merge safe, target: major

#17408 feat(cdk/testing): add method to wait for async tasks outside angular to complete
  src/cdk/testing/component-harness.ts
  src/cdk/testing/harness-environment.ts
  src/cdk/testing/protractor/protractor-harness-environment.ts
  src/cdk/testing/testbed/BUILD.bazel
  src/cdk/testing/testbed/proxy-zone-types.d.ts
  src/cdk/testing/testbed/task-state-zone-interceptor.ts
  src/cdk/testing/testbed/testbed-harness-environment.ts
  src/cdk/testing/testbed/zone-types.d.ts
  src/cdk/testing/tests/harnesses/main-component-harness.ts
  src/cdk/testing/tests/test-main-component.html
  src/cdk/testing/tests/test-main-component.ts
  src/cdk/testing/tests/testbed.spec.ts
  tools/public_api_guard/cdk/testing.d.ts
Labels: P1, cla: yes, pr: lgtm, pr: merge ready, target: major

#17451 fix(button-toggle): indirect descendant buttons not picked up in some cases
  src/material/button-toggle/BUILD.bazel
  src/material/button-toggle/button-toggle.spec.ts
  src/material/button-toggle/button-toggle.ts
Labels: P1, cla: yes, pr: lgtm, pr: merge ready, target: major

#17457 fix(form-field): annotate base class with Directive for Ivy
  src/material/form-field/form-field-control.ts
  src/material/form-field/form-field-module.ts
  src/material/form-field/public-api.ts
Labels: P1, cla: yes, pr: lgtm, pr: merge ready, target: major

#17458 fix(select): not picking up indirect descendant option groups
  src/material/select/select.spec.ts
  src/material/select/select.ts
Labels: P1, cla: yes, pr: lgtm, pr: merge ready, target: major

#17453 fix(sidenav): container not picking up indirect descendant sidenavs
  src/material/sidenav/BUILD.bazel
  src/material/sidenav/drawer.spec.ts
  src/material/sidenav/drawer.ts
  src/material/sidenav/public-api.ts
  src/material/sidenav/sidenav.spec.ts
  src/material/sidenav/sidenav.ts
  tools/public_api_guard/material/sidenav.d.ts
Labels: P1, cla: yes, pr: lgtm, pr: merge ready, target: major

#17459 build: google maps dev app not working in Edge and IE
  src/dev-app/google-map/google-map-demo-module.ts
  src/dev-app/google-map/google-map-demo.html
  src/dev-app/google-map/google-map-demo.ts
  src/dev-app/index.html
Labels: P3, cla: yes, pr: lgtm, pr: merge ready, pr: merge safe, target: patch

#17461 build: avoid bazel analysis cache discarding
  .bazelrc
Labels: cla: yes, pr: lgtm, pr: merge ready, pr: merge safe, target: patch

#17462 build: re-enable release output validation for source maps
  tools/release/release-output/output-validations.ts
Labels: cla: yes, pr: lgtm, pr: merge ready, pr: merge safe, target: major

#17427 refactor(scrolling): remove deprecated APIs for 9.0.0
  src/cdk/overlay/overlay-module.ts
  src/cdk/overlay/public-api.ts
  src/cdk/scrolling/scroll-dispatcher.ts
  src/cdk/scrolling/scrolling-module.ts
  src/cdk/scrolling/viewport-ruler.ts
  tools/public_api_guard/cdk/scrolling.d.ts
Labels: P2, cla: yes, pr: lgtm, pr: merge ready, target: major

#17377 docs(google-maps): Add docs for Google Maps components
  src/google-maps/README.md
Labels: cla: yes, docs, pr: lgtm, pr: merge ready, pr: merge safe, target: major

#17428 build: update to Typescript 3.6
  .bazelrc
  package.json
  scripts/circleci/setup-ivy-ngcc.js
  src/cdk-experimental/dialog/dialog-container.ts
  src/cdk/clipboard/clipboard.spec.ts
  src/cdk/clipboard/clipboard.ts
  src/cdk/clipboard/copy-to-clipboard.ts
  src/cdk/clipboard/pending-copy.ts
  src/cdk/clipboard/public-api.ts
  src/cdk/drag-drop/directives/drag.ts
  src/cdk/overlay/overlay-config.ts
  src/cdk/table/sticky-styler.ts
  src/material-experimental/mdc-button/button-base.ts
  src/material/datepicker/calendar-body.ts
  src/material/dialog/dialog-content-directives.ts
  src/material/menu/menu.spec.ts
  src/material/menu/menu.ts
  src/material/tooltip/tooltip.ts
  src/youtube-player/youtube-player.spec.ts
  tools/BUILD.bazel
  tools/bazel/postinstall-patches.js
  tools/defaults.bzl
  tools/public_api_guard/material/menu.d.ts
  yarn.lock
Labels: P1, cla: yes, pr: lgtm, pr: merge ready, target: major

#17482 (material-experimental/mdc-checkbox): add disabled class when disabled
  src/material-experimental/mdc-checkbox/checkbox.ts
Labels: P2, cla: yes, pr: lgtm, pr: merge ready, pr: merge safe, target: patch

#17465 build: ensure angular version placeholder is up-to-date when staging release
  tools/release/stage-release.ts
Labels: cla: yes, pr: lgtm, pr: merge ready, pr: merge safe, target: patch

#17486 chore: clean up leftover references to private/testing
  .github/CODEOWNERS
  src/cdk/tsconfig-tests.json
Labels: P3, cla: yes, pr: lgtm, pr: merge ready, pr: merge safe, target: patch

#17496 build: update mdc version placeholder range
  package.json
  packages.bzl
Labels: cla: yes, pr: lgtm, pr: merge ready, pr: merge safe, target: major

#17491 build: run tests against view engine and ivy
  .circleci/config.yml
  package.json
  packages.bzl
  scripts/circleci/setup-ivy-ngcc.js
  src/dev-app/BUILD.bazel
  src/dev-app/index.html
  src/dev-app/system-config.js
  src/e2e-app/BUILD.bazel
  tools/BUILD.bazel
  tools/bazel/postinstall-patches.js
  tools/defaults.bzl
Labels: cla: yes, pr: lgtm, pr: merge ready, pr: merge safe, target: major

#17474 build: update node and yarn to latest stable versions
  .circleci/config.yml
  WORKSPACE
  package.json
  tools/public_api_guard/cdk/a11y.d.ts
  tools/public_api_guard/cdk/testing.d.ts
  tools/public_api_guard/material/bottom-sheet.d.ts
  yarn.lock
Labels: cla: yes, pr: lgtm, pr: merge ready, pr: merge safe, target: major

#17484 docs(cdk/testing): Add documentation for harness authors
  src/cdk/testing/testing.md
Labels: P1, cla: yes, docs, pr: lgtm, pr: merge ready, pr: merge safe, target: major

#17460 build: reduce manual setup for entry-points of packages
  src/dev-app/BUILD.bazel
  src/dev-app/index.html
  src/dev-app/system-config-tmpl.js
  tools/bazel/expand_template.bzl
Labels: cla: yes, pr: lgtm, pr: merge ready, pr: merge safe, target: major

#17469 fix(toolbar): not picking up indirect descendant rows
  src/material/toolbar/BUILD.bazel
  src/material/toolbar/toolbar.spec.ts
  src/material/toolbar/toolbar.ts
Labels: P2, cla: yes, pr: lgtm, pr: merge ready, target: major

#17498 fix(material-experimental/mdc-tabs): add `.mdc-tab__ripple` container
  src/material-experimental/mdc-tabs/_mdc-tabs.scss
  src/material-experimental/mdc-tabs/_tabs-common.scss
  src/material-experimental/mdc-tabs/tab-group.html
  src/material-experimental/mdc-tabs/tab-nav-bar/tab-link.html
Labels: P2, cla: yes, pr: lgtm, pr: merge ready, pr: merge safe

#17471 fix(material-experimental/mdc-slide-toggle): missing focus indication in high contrast mode
  src/material-experimental/mdc-slide-toggle/slide-toggle.scss
Labels: P3, cla: yes, pr: lgtm, pr: merge ready, pr: merge safe, target: patch

#17333 refactor(dialog): remove deprecated APIs for 9.0.0
  src/material/dialog/dialog-animations.ts
  src/material/dialog/dialog-ref.ts
  src/material/dialog/dialog.spec.ts
  src/material/dialog/dialog.ts
  src/material/schematics/ng-update/data/constructor-checks.ts
  src/material/schematics/ng-update/data/property-names.ts
  tools/public_api_guard/material/dialog.d.ts
Labels: P2, cla: yes, pr: lgtm, pr: merge ready, target: major

#17499 docs(cdk/testing): Highlight differences between e2e and unit tests
  src/cdk/testing/testing.md
Labels: P2, cla: yes, docs, pr: lgtm, pr: merge ready, pr: merge safe, target: major

#17467 docs: describe dev-env setup for Windows machines
  DEV_ENVIRONMENT.md
Labels: P4, cla: yes, docs, pr: lgtm, pr: merge ready, pr: merge safe, target: patch

#17340 fix(table): not picking up indirect descendant defs
  src/cdk/table/table.spec.ts
  src/cdk/table/table.ts
Labels: P1, cla: yes, pr: lgtm, pr: merge ready, target: patch

#17511 chore: bump version to 9.0.0-next.1 w/ changelog
  CHANGELOG.md
  package.json
Labels: cla: yes, pr: lgtm, pr: merge ready, pr: merge safe, target: major

#17501 fix(material/list): Do not rely on input binding order
  src/material/list/selection-list.spec.ts
  src/material/list/selection-list.ts
Labels: P2, cla: yes, pr: lgtm, pr: merge ready, target: major

#17510 fix(autocomplete): not picking up indirect descendant option groups
  src/material/autocomplete/autocomplete.spec.ts
  src/material/autocomplete/autocomplete.ts
Labels: P2, cla: yes, pr: lgtm, pr: merge ready, target: major

#17480 fix(drag-drop): coerce drop list autoScrollDisabled input
  src/cdk/drag-drop/directives/drop-list.ts
Labels: P3, cla: yes, pr: lgtm, pr: merge ready, target: patch

#17473 feat(checkbox): add options defaults config
  src/material/checkbox/BUILD.bazel
  src/material/checkbox/checkbox-config.ts
  src/material/checkbox/checkbox.spec.ts
  src/material/checkbox/checkbox.ts
  tools/public_api_guard/material/checkbox.d.ts
Labels: P2, cla: yes, pr: lgtm, pr: merge ready, target: major

#17527 docs: add package ID prefix to h3's ids
  tools/dgeni/templates/entry-point.template.html
Labels: P1, cla: yes, pr: lgtm, pr: merge ready, pr: merge safe, target: major

#16745 docs(text-field,input): text-field headings don't have anchors
  src/cdk/text-field/text-field.md
  src/material/input/input.md
Labels: P3, cla: yes, docs, pr: lgtm, pr: merge ready, pr: merge safe, target: patch

#17532 docs(cdk/platform): remove header in example from TOC
  src/material-examples/cdk/platform/cdk-platform-overview/cdk-platform-overview-example.html
Labels: cla: yes, docs, pr: lgtm, pr: merge ready, pr: merge safe, target: patch

#17507 feat(material-experimental/mdc-tabs): add option to fit ink bar to content
  src/dev-app/mdc-tabs/mdc-tabs-demo.html
  src/dev-app/mdc-tabs/mdc-tabs-demo.ts
  src/material-experimental/mdc-tabs/ink-bar.ts
  src/material-experimental/mdc-tabs/tab-group.html
  src/material-experimental/mdc-tabs/tab-group.spec.ts
  src/material-experimental/mdc-tabs/tab-group.ts
  src/material-experimental/mdc-tabs/tab-label-wrapper.ts
  src/material-experimental/mdc-tabs/tab-nav-bar/tab-nav-bar.spec.ts
  src/material-experimental/mdc-tabs/tab-nav-bar/tab-nav-bar.ts
Labels: P2, cla: yes, pr: lgtm, pr: merge ready, pr: merge safe, target: patch

#17533 docs(cdk/clipboard): fix header anchors and TOC
  src/cdk/clipboard/clipboard.md
Labels: P2, cla: yes, docs, pr: merge ready, pr: merge safe, target: patch

#17516 build: no longer depend on gulp for lint tasks
  .circleci/config.yml
  package.json
  scripts/ownerslint.ts
  tools/gulp/gulpfile.ts
  tools/gulp/tasks/ci.ts
  tools/gulp/tasks/lint.ts
  tslint.json
Labels: P3, cla: yes, pr: lgtm, pr: merge ready, pr: merge safe, target: patch

#17529 fix(stepper): not picking up indirect descendant elements
  src/cdk/stepper/stepper.ts
  src/material/stepper/stepper.spec.ts
  src/material/stepper/stepper.ts
Labels: P2, cla: yes, pr: lgtm, pr: merge ready, target: major

#17530 fix(grid-list): not picking up indirect descendant lines
  src/material/grid-list/grid-list.spec.ts
  src/material/grid-list/grid-tile.ts
Labels: P2, cla: yes, pr: lgtm, pr: merge ready, target: major

#17550 chore: update Angular to 9.0.0-next.14
  package.json
  yarn.lock
Labels: cla: yes, target: major

#17551 chore: bump to Angular 9.0.0-next.15
  package.json
  yarn.lock
Labels: P1, cla: yes, pr: lgtm, pr: merge ready, target: major

#17554 chore: bump version to 9.0.0-next.2 w/ changelog
  CHANGELOG.md
  package.json
Labels: cla: yes, pr: lgtm, pr: merge ready, pr: merge safe, target: major
