Repository angular/components, pull requests merged in 2019-12, with the labels that each got.

#17844 build: remove duplicated tree example code
  src/dev-app/tree/BUILD.bazel
  src/dev-app/tree/checklist-tree-demo/checklist-database.ts
  src/dev-app/tree/checklist-tree-demo/checklist-nested-tree-demo.html
  src/dev-app/tree/checklist-tree-demo/checklist-nested-tree-demo.scss
  src/dev-app/tree/checklist-tree-demo/checklist-nested-tree-demo.ts
  src/dev-app/tree/checklist-tree-demo/checklist-tree-demo.html
  src/dev-app/tree/checklist-tree-demo/checklist-tree-demo.scss
  src/dev-app/tree/checklist-tree-demo/checklist-tree-demo.ts
  src/dev-app/tree/dynamic-tree-demo/dynamic-database.ts
  src/dev-app/tree/dynamic-tree-demo/dynamic-tree-demo.html
  src/dev-app/tree/dynamic-tree-demo/dynamic-tree-demo.scss
  src/dev-app/tree/dynamic-tree-demo/dynamic-tree-demo.ts
  src/dev-app/tree/file-database.ts
  src/dev-app/tree/loadmore-tree-demo/loadmore-database.ts
  src/dev-app/tree/loadmore-tree-demo/loadmore-tree-demo.html
  src/dev-app/tree/loadmore-tree-demo/loadmore-tree-demo.scss
  src/dev-app/tree/loadmore-tree-demo/loadmore-tree-demo.ts
  src/dev-app/tree/tree-demo-module.ts
  src/dev-app/tree/tree-demo.html
Labels: P3, cla: yes, pr: lgtm, pr: merge ready, pr: merge safe, target: patch

#17843 docs(tree): injectable decorator set on wrong class
  src/components-examples/material/tree/tree-dynamic/tree-dynamic-example.ts
Labels: P4, cla: yes, pr: lgtm, pr: merge ready, pr: merge safe

#17850 fix(youtube-player): avoid clobbering api loaded callback
  src/youtube-player/youtube-player.spec.ts
  src/youtube-player/youtube-player.ts
Labels: P3, cla: yes, pr: lgtm, pr: merge ready, pr: merge safe, target: patch

#17846 test: clean up usages of deprecated TestBed method
  src/cdk/a11y/focus-trap/focus-trap.spec.ts
  src/cdk/clipboard/clipboard.spec.ts
  src/cdk/clipboard/copy-to-clipboard.spec.ts
  src/cdk/drag-drop/directives/drag.spec.ts
Labels: P3, cla: yes, pr: lgtm, pr: merge ready, pr: merge safe, target: patch

#17837 docs(select): hide private api from docs
  src/material/select/select.ts
Labels: P4, cla: yes, docs, pr: lgtm, pr: merge ready, pr: merge safe, target: patch

#17512 feat(google-maps): Add MapPolyline component
  src/dev-app/google-map/google-map-demo.html
  src/dev-app/google-map/google-map-demo.ts
  src/google-maps/google-maps-module.ts
  src/google-maps/map-polyline/map-polyline.spec.ts
  src/google-maps/map-polyline/map-polyline.ts
  src/google-maps/public-api.ts
  src/google-maps/testing/fake-google-map-utils.ts
  tools/public_api_guard/google-maps/google-maps.d.ts
Labels: P3, caretaker note, cla: yes, pr: lgtm, pr: merge ready, pr: merge safe, target: minor

#17851 fix(portal): better handling when dom portal content can't be restored
  src/cdk/portal/dom-portal-outlet.ts
  src/cdk/portal/portal-directives.ts
  src/cdk/portal/portal.spec.ts
Labels: P4, cla: yes, pr: lgtm, pr: merge ready, target: patch

#17849 fix(slider): stop dragging if page loses focus
  src/material/slider/slider.spec.ts
  src/material/slider/slider.ts
Labels: P3, cla: yes, pr: lgtm, pr: merge ready, target: patch

#17826 fix(list): don't handle selection keys while using typeahead in selection list
  src/material/list/selection-list.spec.ts
  src/material/list/selection-list.ts
Labels: P3, cla: yes, pr: lgtm, pr: merge ready, target: patch

#17819 fix(dialog): use view container from config when attaching content
  src/material/dialog/dialog.spec.ts
  src/material/dialog/dialog.ts
Labels: P3, cla: yes, pr: lgtm, pr: merge ready, target: patch

#17802 feat(sort): add test harness
  src/material/config.bzl
  src/material/sort/sort-header.ts
  src/material/sort/sort.ts
  src/material/sort/testing/BUILD.bazel
  src/material/sort/testing/index.ts
  src/material/sort/testing/public-api.ts
  src/material/sort/testing/shared.spec.ts
  src/material/sort/testing/sort-harness-filters.ts
  src/material/sort/testing/sort-harness.spec.ts
  src/material/sort/testing/sort-harness.ts
  src/material/sort/testing/sort-header-harness.ts
  test/karma-system-config.js
  tools/public_api_guard/material/sort/testing.d.ts
Labels: P3, cla: yes, pr: lgtm, pr: merge ready, pr: merge safe, target: minor

#17789 refactor: remove QueryList workaround for type checking
  src/cdk/stepper/stepper.ts
  src/components-examples/cdk/stepper/cdk-custom-stepper-without-form/example-custom-stepper.html
  src/material-experimental/mdc-tabs/tab-group.html
  src/material/stepper/stepper-horizontal.html
  src/material/stepper/stepper-vertical.html
  src/material/stepper/stepper.ts
  src/material/tabs/tab-group.html
  src/material/tabs/tab-group.ts
  tools/public_api_guard/cdk/stepper.d.ts
  tools/public_api_guard/material/tabs.d.ts
Labels: P2, cla: yes, pr: lgtm, pr: merge ready, target: patch

#17727 fix(virtual-scroll-viewport): changeDetection run before translate scroll content.
  src/cdk/scrolling/virtual-scroll-viewport.ts
Labels: cla: yes, pr: lgtm, pr: merge ready, target: patch

#17691 feat(material/expansion): add test harness
  src/cdk/testing/component-harness.ts
  src/material/config.bzl
  src/material/expansion/accordion.ts
  src/material/expansion/testing/BUILD.bazel
  src/material/expansion/testing/accordion-harness.ts
  src/material/expansion/testing/expansion-harness-filters.ts
  src/material/expansion/testing/expansion-harness.spec.ts
  src/material/expansion/testing/expansion-harness.ts
  src/material/expansion/testing/index.ts
  src/material/expansion/testing/public-api.ts
  src/material/expansion/testing/shared.spec.ts
  tools/public_api_guard/cdk/testing.d.ts
  tools/public_api_guard/material/expansion/testing.d.ts
Labels: caretaker note, cla: yes, pr: lgtm, pr: merge ready, target: minor

#17661 feat(badge): add test harness
  src/material/badge/testing/BUILD.bazel
  src/material/badge/testing/badge-harness-filters.ts
  src/material/badge/testing/badge-harness.spec.ts
  src/material/badge/testing/badge-harness.ts
  src/material/badge/testing/index.ts
  src/material/badge/testing/public-api.ts
  src/material/badge/testing/shared.spec.ts
  src/material/config.bzl
  test/karma-system-config.js
  tools/public_api_guard/material/badge/testing.d.ts
Labels: P3, caretaker note, cla: yes, pr: lgtm, pr: merge ready, pr: merge safe, target: minor

#17643 feat(tooltip): add theming flexibility
  src/material/core/theming/_palette.scss
  src/material/tooltip/_tooltip-theme.scss
Labels: P3, cla: yes, pr: lgtm, pr: merge ready, target: patch

#17618 feat(bottom-sheet): add test harness
  src/material/bottom-sheet/testing/BUILD.bazel
  src/material/bottom-sheet/testing/bottom-sheet-harness-filters.ts
  src/material/bottom-sheet/testing/bottom-sheet-harness.spec.ts
  src/material/bottom-sheet/testing/bottom-sheet-harness.ts
  src/material/bottom-sheet/testing/index.ts
  src/material/bottom-sheet/testing/public-api.ts
  src/material/bottom-sheet/testing/shared.spec.ts
  src/material/config.bzl
  test/karma-system-config.js
Labels: P3, caretaker note, cla: yes, pr: lgtm, pr: merge ready, pr: merge safe, target: minor

#17488 fix(card): add card content selectors
  src/material/card/card.ts
Labels: cla: yes, pr: lgtm, pr: merge ready, target: patch

#17489 feat(cdk/overlay): add transform origin selector as directive input
  src/cdk/overlay/overlay-directives.spec.ts
  src/cdk/overlay/overlay-directives.ts
  tools/public_api_guard/cdk/overlay.d.ts
Labels: P3, cla: yes, pr: lgtm, pr: merge ready, target: patch

#17407 fix(menu): keyboard controls not working if all items are disabled inside lazy content
  src/material-experimental/mdc-menu/menu.spec.ts
  src/material/menu/menu.spec.ts
  src/material/menu/menu.ts
Labels: P3, cla: yes, pr: lgtm, pr: merge ready, target: patch

#17395 fix(form-field): incorrect assumptions about page direction
  src/material/form-field/form-field.ts
  src/material/input/input.spec.ts
Labels: P3, cla: yes, pr: lgtm, pr: merge ready, target: patch

#17867 build: fix CI failures
  src/dev-app/autocomplete/autocomplete-demo.html
  tools/public_api_guard/cdk/overlay.d.ts
  tools/public_api_guard/material/card.d.ts
Labels: P3, cla: yes, pr: lgtm, pr: merge ready, pr: merge safe, target: patch

#17814 docs: update readme and add FAQ
  FAQ.md
  README.md
Labels: cla: yes, docs, pr: merge safe, target: patch

#17792 build: migrate to new --define=angular_ivy_enabled flag
  .bazelrc
  .circleci/config.yml
  packages.bzl
  scripts/build-packages-dist.js
  src/dev-app/BUILD.bazel
  src/dev-app/system-config-tmpl.js
  tools/BUILD.bazel
Labels: cla: yes, pr: lgtm, pr: merge ready, pr: merge safe, target: major, target: patch

#17858 chore(dev-app) Add demo page for FocusTrap
  .github/CODEOWNERS
  src/dev-app/BUILD.bazel
  src/dev-app/dev-app/dev-app-layout.ts
  src/dev-app/dev-app/routes.ts
  src/dev-app/focus-trap/BUILD.bazel
  src/dev-app/focus-trap/focus-trap-demo-module.ts
  src/dev-app/focus-trap/focus-trap-demo.html
  src/dev-app/focus-trap/focus-trap-demo.scss
  src/dev-app/focus-trap/focus-trap-demo.ts
  src/dev-app/focus-trap/focus-trap-dialog-demo.html
  src/dev-app/focus-trap/focus-trap-dialog-demo.scss
Labels: cla: yes, pr: lgtm, pr: merge ready, pr: merge safe, target: patch

#17866 fix(material/datepicker): remove fixed width as not working on mobile
  src/components-examples/material/datepicker/datepicker-events/datepicker-events-example.css
Labels: cla: yes, pr: lgtm, pr: merge ready, pr: merge safe, target: patch

#17859 feat(material/list): add test harnesses for list components.
  src/cdk/testing/component-harness.ts
  src/material/config.bzl
  src/material/divider/testing/BUILD.bazel
  src/material/divider/testing/divider-harness-filters.ts
  src/material/divider/testing/divider-harness.spec.ts
  src/material/divider/testing/divider-harness.ts
  src/material/divider/testing/index.ts
  src/material/divider/testing/public-api.ts
  src/material/divider/testing/shared.spec.ts
  src/material/list/testing/BUILD.bazel
  src/material/list/testing/action-list-harness.ts
  src/material/list/testing/index.ts
  src/material/list/testing/list-harness-base.ts
  src/material/list/testing/list-harness-filters.ts
  src/material/list/testing/list-harness.spec.ts
  src/material/list/testing/list-harness.ts
  src/material/list/testing/list-item-harness-base.ts
  src/material/list/testing/nav-list-harness.ts
  src/material/list/testing/public-api.ts
  src/material/list/testing/selection-list-harness.ts
  src/material/list/testing/shared.spec.ts
  test/karma-system-config.js
  tools/public_api_guard/material/divider/testing.d.ts
  tools/public_api_guard/material/list/testing.d.ts
Labels: cla: yes, pr: lgtm, pr: merge ready, target: minor

#16374 cdkConnectedOverlay should let us change positioning strategy
  src/cdk/overlay/overlay-directives.spec.ts
  src/cdk/overlay/overlay-directives.ts
  tools/public_api_guard/cdk/overlay.d.ts
Labels: G, cla: yes, commit message fixup, pr: lgtm, pr: merge ready, target: minor

#17817 fix(input): avoid multiple autosize input listeners with ivy
  src/cdk/text-field/autosize.ts
  src/material/input/autosize.ts
Labels: P3, cla: yes, pr: lgtm, pr: merge ready, target: patch

#17762 fix(menu): internal focus state out of sync if item is focused programmatically
  src/material-experimental/mdc-menu/menu.spec.ts
  src/material/menu/menu-item.ts
  src/material/menu/menu.spec.ts
  src/material/menu/menu.ts
  tools/public_api_guard/material/menu.d.ts
Labels: P3, cla: yes, pr: lgtm, pr: merge ready, target: patch

#17845 fix(google-maps): unable to subscribe to events after initialization
  src/google-maps/google-map/google-map.spec.ts
  src/google-maps/google-map/google-map.ts
  src/google-maps/map-event-manager.ts
  src/google-maps/map-info-window/map-info-window.spec.ts
  src/google-maps/map-info-window/map-info-window.ts
  src/google-maps/map-marker/map-marker.spec.ts
  src/google-maps/map-marker/map-marker.ts
  src/google-maps/map-polyline/map-polyline.spec.ts
  src/google-maps/map-polyline/map-polyline.ts
  tools/public_api_guard/google-maps/google-maps.d.ts
Labels: P3, cla: yes, pr: lgtm, pr: merge ready, pr: merge safe, target: patch

#17877 build: update to latest Angular version
  package.json
  yarn.lock
Labels: P3, cla: yes, pr: lgtm, pr: merge ready, pr: merge safe, target: patch

#17883 docs(cdk): fix typo
  src/cdk/testing/test-harnesses.md
Labels: cla: yes, pr: lgtm, pr: merge ready, pr: merge safe, target: patch

#17873 ci: update saucelabs to use angular-components account
  .circleci/config.yml
Labels: cla: yes, pr: lgtm, pr: merge ready, pr: merge safe, target: major, target: patch

#17892 chore: bump version to 9.0.0-rc.5 w/ changelog
  CHANGELOG.md
  package.json
Labels: G, cla: yes, pr: lgtm, pr: merge ready, pr: merge safe, target: major

#17894 fix(youtube-player): avoid setInterval change detection when player is created
  src/youtube-player/youtube-player.ts
Labels: P2, cla: yes, pr: lgtm, pr: merge ready, pr: merge safe, target: patch

#17905 fix(mdc-switch): updated to latest DOM structure guidance
  src/material-experimental/mdc-slide-toggle/slide-toggle.html
Labels: P1, cla: yes, pr: lgtm, pr: merge ready, pr: merge safe, target: patch

#17893 build: set incompatible_strict_action_env flag to allow caching
  .bazelrc
Labels: P2, cla: yes, pr: lgtm, pr: merge ready, pr: merge safe, target: major, target: patch

#17900 fix(text-field): correctly check _initialHeight
  src/cdk/text-field/autosize.ts
Labels: P3, cla: yes, pr: lgtm, pr: merge ready, pr: merge safe, target: patch

#17576 fix(material/chips): fix ripple element opacity when using CSS variable theming
  src/material/chips/_chips-theme.scss
Labels: P3, cla: yes, pr: lgtm, pr: merge ready, target: patch

#17910 build: exit with non-zero status code if rollup globals lint fails
  scripts/check-rollup-globals.ts
Labels: cla: yes, pr: lgtm, pr: merge ready, pr: merge safe, target: patch

#17909 build: fix mdc snapshot test cronjob
  .circleci/config.yml
  scripts/circleci/setup-mdc-snapshots.js
Labels: cla: yes, pr: lgtm, pr: merge ready, pr: merge safe, target: patch

#17735 fix(sort): no focus indication for active header
  src/material/sort/BUILD.bazel
  src/material/sort/sort-header.html
  src/material/sort/sort-header.scss
  src/material/sort/sort-header.ts
  tools/public_api_guard/material/sort.d.ts
Labels: P3, a11y, cla: yes, pr: lgtm, pr: merge ready, target: patch

#17927 refactor: fix ripple-renderer in TS3.7
  src/material/core/ripple/ripple-renderer.ts
Labels: cla: yes, pr: lgtm, pr: merge ready, pr: merge safe, target: patch

#17760 chore: update MDC to latest canary
  package.json
  packages.bzl
  src/material-experimental/mdc-chips/chip-icons.ts
  src/material-experimental/mdc-chips/chip-option.ts
  src/material-experimental/mdc-chips/chip-row.ts
  src/material-experimental/mdc-chips/chip.ts
  src/material-experimental/mdc-helpers/BUILD.bazel
  src/material-experimental/mdc-progress-bar/progress-bar.ts
  yarn.lock
Labels: cla: yes, pr: lgtm, pr: merge ready, target: patch

#17932 Revert "chore: update MDC to latest canary"
  package.json
  packages.bzl
  src/material-experimental/mdc-chips/chip-icons.ts
  src/material-experimental/mdc-chips/chip-option.ts
  src/material-experimental/mdc-chips/chip-row.ts
  src/material-experimental/mdc-chips/chip.ts
  src/material-experimental/mdc-helpers/BUILD.bazel
  src/material-experimental/mdc-progress-bar/progress-bar.ts
  yarn.lock
Labels: cla: yes

#17929 build: update to rules_nodejs@0.42.3
  .bazelrc
  WORKSPACE
Labels: cla: yes, pr: lgtm, pr: merge ready, pr: merge safe, target: major, target: patch

#17871 fix(chips): clear user agent styles when set on button
  src/material/chips/chips.scss
Labels: P4, cla: yes, pr: lgtm, pr: merge ready, target: patch

#17912 build: add option to start karma without browser
  test/BUILD.bazel
  test/bazel-karma-local-config.js
  tools/defaults.bzl
Labels: cla: yes, pr: lgtm, pr: merge ready, pr: merge safe, target: patch

#17935 test: menu tests flaky due to missing animation flush
  src/material-experimental/mdc-menu/menu.spec.ts
  src/material/menu/menu.spec.ts
Labels: cla: yes, pr: lgtm, pr: merge ready, pr: merge safe, target: patch

#17939 fix: google-maps and youtube-player package missing tslib dependency
  packages.bzl
  src/cdk-experimental/package.json
  src/cdk/package.json
  src/google-maps/package.json
  src/material-experimental/package.json
  src/material-moment-adapter/package.json
  src/material/package.json
  src/youtube-player/package.json
Labels: P2, cla: yes, pr: lgtm, pr: merge ready, pr: merge safe, target: patch

#17941 build: bump to latest Angular version
  package.json
  yarn.lock
Labels: P3, cla: yes, pr: lgtm, pr: merge ready, pr: merge safe, target: major

#17906 feat(material-experimental/mdc-list): Add scaffolding for MDC-based list
  .github/CODEOWNERS
  src/material-experimental/config.bzl
  src/material-experimental/mdc-list/BUILD.bazel
  src/material-experimental/mdc-list/README.md
  src/material-experimental/mdc-list/_mdc-list.scss
  src/material-experimental/mdc-list/action-list.ts
  src/material-experimental/mdc-list/index.ts
  src/material-experimental/mdc-list/list-base.ts
  src/material-experimental/mdc-list/list-item.html
  src/material-experimental/mdc-list/list-option.html
  src/material-experimental/mdc-list/list.e2e.spec.ts
  src/material-experimental/mdc-list/list.html
  src/material-experimental/mdc-list/list.scss
  src/material-experimental/mdc-list/list.spec.ts
  src/material-experimental/mdc-list/list.ts
  src/material-experimental/mdc-list/module.ts
  src/material-experimental/mdc-list/nav-list.ts
  src/material-experimental/mdc-list/public-api.ts
  src/material-experimental/mdc-list/selection-list.html
  src/material-experimental/mdc-list/selection-list.ts
  src/material-experimental/mdc-theming/BUILD.bazel
  src/material-experimental/mdc-theming/_all-theme.scss
  src/material-experimental/mdc-typography/BUILD.bazel
  src/material-experimental/mdc-typography/_all-typography.scss
  test/karma-system-config.js
Labels: cla: yes, pr: lgtm, pr: merge ready, pr: merge safe, target: patch

#17930 build: add ci jobs to ensure ngcc compatibility
  .circleci/config.yml
  scripts/circleci/setup-angular-snapshots.js
Labels: cla: yes, pr: lgtm, pr: merge ready, pr: merge safe, target: patch

#17938 fix(material-experimental/mdc-progress-bar): update to latest canary to include adapter changes
  package.json
  src/material-experimental/mdc-helpers/BUILD.bazel
  src/material-experimental/mdc-progress-bar/progress-bar.ts
  yarn.lock
Labels: cla: yes, pr: lgtm, pr: merge ready, pr: merge safe, target: patch

#17953 fix(material-experimental): menu item should not inherit parent classname
  src/material-experimental/mdc-menu/menu-item.ts
  src/material/menu/menu-item.ts
Labels: cla: yes, pr: lgtm, pr: merge ready, pr: merge safe, target: patch

#17964 chore: fix README link to npm
  README.md
Labels: cla: yes, docs, pr: lgtm, pr: merge ready, pr: merge safe, target: patch

#17937 build: add target to create dev-app web package
  src/dev-app/BUILD.bazel
  src/dev-app/system-config-tmpl.js
Labels: cla: yes, pr: lgtm, pr: merge ready, pr: merge safe, target: patch

#17949 refactor(cdk/drag-drop): change misleading comment
  src/cdk/drag-drop/drag-events.ts
Labels: P3, cla: yes, docs, pr: lgtm, pr: merge ready, pr: merge safe, target: patch

#17961 fix(form-field): deprecate `legacy` and `standard` appearances
  src/material/form-field/form-field.ts
Labels: P1, cla: yes, pr: lgtm, pr: merge ready, pr: merge safe, target: patch

#17978 build: update scss-bundle to avoid node-sass dependency
  BUILD.bazel
  package.json
  scss-bundle.config.json
  src/material/BUILD.bazel
  yarn.lock
Labels: cla: yes, pr: lgtm, pr: merge ready, pr: merge safe, target: patch

#17972 docs(readme): fix link to FAQ
  README.md
Labels: P2, cla: yes, docs, pr: lgtm, pr: merge ready, pr: merge safe, target: major

#17895 feat(material-experimental/mdc-snackbar): Add demo.
  .github/CODEOWNERS
  src/dev-app/BUILD.bazel
  src/dev-app/dev-app/dev-app-layout.ts
  src/dev-app/dev-app/routes.ts
  src/dev-app/mdc-snackbar/BUILD.bazel
  src/dev-app/mdc-snackbar/mdc-snackbar-demo-module.ts
  src/dev-app/mdc-snackbar/mdc-snackbar-demo.html
  src/dev-app/mdc-snackbar/mdc-snackbar-demo.scss
  src/dev-app/mdc-snackbar/mdc-snackbar-demo.ts
  src/material-experimental/mdc-snackbar/BUILD.bazel
Labels: cla: yes, pr: lgtm, pr: merge ready, pr: merge safe, target: patch

#17989 build: add script to deploy dev-app web package to firebase
  firebase.json
  package.json
  scripts/deploy-dev-app.js
Labels: cla: yes, pr: lgtm, pr: merge ready, pr: merge safe, target: patch

#17992 feat(material-experimental/mdc-table): add skeleton
  .github/CODEOWNERS
  src/dev-app/BUILD.bazel
  src/dev-app/dev-app/dev-app-layout.ts
  src/dev-app/dev-app/routes.ts
  src/dev-app/mdc-table/BUILD.bazel
  src/dev-app/mdc-table/mdc-table-demo-module.ts
  src/dev-app/mdc-table/mdc-table-demo.html
  src/dev-app/mdc-table/mdc-table-demo.scss
  src/dev-app/mdc-table/mdc-table-demo.ts
  src/material-experimental/config.bzl
  src/material-experimental/mdc-table/BUILD.bazel
  src/material-experimental/mdc-table/README.md
  src/material-experimental/mdc-table/_mdc-table.scss
  src/material-experimental/mdc-table/cell.ts
  src/material-experimental/mdc-table/index.ts
  src/material-experimental/mdc-table/module.ts
  src/material-experimental/mdc-table/public-api.ts
  src/material-experimental/mdc-table/row.ts
  src/material-experimental/mdc-table/table.e2e.spec.ts
  src/material-experimental/mdc-table/table.scss
  src/material-experimental/mdc-table/table.spec.ts
  src/material-experimental/mdc-table/table.ts
  src/material-experimental/mdc-table/tsconfig-build.json
  src/material-experimental/mdc_require_config.js
  test/karma-system-config.js
Labels: cla: yes, pr: lgtm, pr: merge ready, pr: merge safe, target: patch

#17988 build: remove unused dependencies
  angular-tsconfig.json
  gulpfile.js
  package.json
  src/cdk/schematics/BUILD.bazel
  src/material/paginator/paginator.spec.ts
  tools/gulp/gulpfile.ts
  tools/gulp/packages.ts
  tools/gulp/tasks/clean.ts
  tools/gulp/tasks/unit-test.ts
  tools/gulp/tsconfig.json
  tools/package-tools/gulp/build-scss-pipeline.ts
  tools/package-tools/gulp/build-tasks-gulp.ts
  yarn.lock
Labels: cla: yes, pr: lgtm, pr: merge ready, pr: merge safe, target: patch

#17990 build: exclude devserver targets from ci test jobs
  src/dev-app/BUILD.bazel
  src/e2e-app/BUILD.bazel
Labels: cla: yes, pr: lgtm, pr: merge ready, pr: merge safe, target: patch

#18000 feat(material-experimental/mdc-table): add MDC styles/classes
  src/dev-app/mdc-table/mdc-table-demo.html
  src/dev-app/mdc-table/mdc-table-demo.scss
  src/material-experimental/mdc-table/BUILD.bazel
  src/material-experimental/mdc-table/_mdc-table.scss
  src/material-experimental/mdc-table/cell.ts
  src/material-experimental/mdc-table/row.ts
  src/material-experimental/mdc-table/table.scss
  src/material-experimental/mdc-table/table.ts
  src/material-experimental/mdc-theming/BUILD.bazel
  src/material-experimental/mdc-theming/_all-theme.scss
  src/material-experimental/mdc-typography/BUILD.bazel
  src/material-experimental/mdc-typography/_all-typography.scss
Labels: cla: yes, pr: lgtm, pr: merge ready, pr: merge safe, target: patch

#18003 feat(material-experimental/mdc-table): add tests
  src/material-experimental/mdc-table/BUILD.bazel
  src/material-experimental/mdc-table/table.spec.ts
Labels: cla: yes, pr: lgtm, pr: merge ready, pr: merge safe, target: patch

#17969 feat(paginator): add test harness
  src/material/config.bzl
  src/material/paginator/paginator.html
  src/material/paginator/testing/BUILD.bazel
  src/material/paginator/testing/index.ts
  src/material/paginator/testing/paginator-harness-filters.ts
  src/material/paginator/testing/paginator-harness.spec.ts
  src/material/paginator/testing/paginator-harness.ts
  src/material/paginator/testing/public-api.ts
  src/material/paginator/testing/shared.spec.ts
  test/karma-system-config.js
  tools/public_api_guard/material/paginator/testing.d.ts
Labels: P3, cla: yes, pr: lgtm, pr: merge ready, pr: merge safe, target: minor

#17996 feat(button-toggle): add test harness
  src/material/button-toggle/testing/BUILD.bazel
  src/material/button-toggle/testing/button-toggle-group-harness-filters.ts
  src/material/button-toggle/testing/button-toggle-group-harness.ts
  src/material/button-toggle/testing/button-toggle-group-shared.spec.ts
  src/material/button-toggle/testing/button-toggle-group.spec.ts
  src/material/button-toggle/testing/button-toggle-harness-filters.ts
  src/material/button-toggle/testing/button-toggle-harness.spec.ts
  src/material/button-toggle/testing/button-toggle-harness.ts
  src/material/button-toggle/testing/button-toggle-shared.spec.ts
  src/material/button-toggle/testing/index.ts
  src/material/button-toggle/testing/public-api.ts
  src/material/config.bzl
  test/karma-system-config.js
  tools/public_api_guard/material/button-toggle/testing.d.ts
Labels: cla: yes, pr: lgtm, pr: merge ready, pr: merge safe, target: minor

#17999 build: remove entryComponents from development apps
  src/a11y-demo/a11y-demo-module.ts
  src/dev-app/bottom-sheet/bottom-sheet-demo-module.ts
  src/dev-app/datepicker/datepicker-demo-module.ts
  src/dev-app/dialog/dialog-demo-module.ts
  src/dev-app/focus-trap/focus-trap-demo-module.ts
  src/dev-app/portal/portal-demo-module.ts
  src/e2e-app/dialog/dialog-e2e-module.ts
  tools/example-module/example-module.template
Labels: P4, cla: yes, pr: lgtm, pr: merge ready, pr: merge safe, target: patch

#18006 build: update to latest Angular version
  package.json
  yarn.lock
Labels: P3, cla: yes, pr: lgtm, pr: merge ready, pr: merge safe, target: patch

#18007 docs: responsiveness of autocomplete examples tab
  src/components-examples/material/autocomplete/autocomplete-auto-active-first-option/autocomplete-auto-active-first-option-example.html
  src/components-examples/material/autocomplete/autocomplete-display/autocomplete-display-example.html
  src/components-examples/material/autocomplete/autocomplete-filter/autocomplete-filter-example.html
  src/components-examples/material/autocomplete/autocomplete-optgroup/autocomplete-optgroup-example.html
  src/components-examples/material/autocomplete/autocomplete-overview/autocomplete-overview-example.html
  src/components-examples/material/autocomplete/autocomplete-plain-input/autocomplete-plain-input-example.html
  src/components-examples/material/autocomplete/autocomplete-simple/autocomplete-simple-example.html
Labels: cla: yes, docs, pr: lgtm, pr: merge ready, pr: merge safe, target: patch

#17957 fix(menu): forward aria attribute to menu panel
  src/material-experimental/mdc-menu/menu.html
  src/material-experimental/mdc-menu/menu.spec.ts
  src/material/menu/menu.html
  src/material/menu/menu.spec.ts
  src/material/menu/menu.ts
  tools/public_api_guard/material/menu.d.ts
Labels: P2, cla: yes, pr: lgtm, pr: merge ready, target: patch

#18011 chore: bump version to 9.0.0-rc.6 w/ changelog
  CHANGELOG.md
  package.json
Labels: cla: yes

#17799 feat(table): add test harness
  src/material/config.bzl
  src/material/table/testing/BUILD.bazel
  src/material/table/testing/cell-harness.ts
  src/material/table/testing/index.ts
  src/material/table/testing/public-api.ts
  src/material/table/testing/row-harness.ts
  src/material/table/testing/shared.spec.ts
  src/material/table/testing/table-harness-filters.ts
  src/material/table/testing/table-harness.spec.ts
  src/material/table/testing/table-harness.ts
  test/karma-system-config.js
  tools/public_api_guard/material/table/testing.d.ts
Labels: P3, cla: yes, pr: lgtm, pr: merge ready, pr: merge safe, target: minor

#17942 Trying to incorporate the new type definition
  src/material/core/datetime/date-selection-model.ts
  src/material/datepicker/datepicker-input.ts
  tools/public_api_guard/material/core.d.ts
Labels: cla: yes

#18063 fix(datepicker): not respecting form control updateOn: blur for invalid values
  src/material/datepicker/datepicker-input.ts
  src/material/datepicker/datepicker.spec.ts
Labels: P3, cla: yes, pr: lgtm, pr: merge ready, target: patch

#18061 fix(material-experimental/mdc-chips): checkmark not visible in high contrast black-on-white mode
  src/material-experimental/mdc-chips/chips.scss
Labels: P3, cla: yes, pr: lgtm, pr: merge ready, target: patch

#18058 fix(scrolling): update virtual scroll viewport size on resize
  src/cdk/scrolling/virtual-scroll-viewport.spec.ts
  src/cdk/scrolling/virtual-scroll-viewport.ts
  tools/public_api_guard/cdk/scrolling.d.ts
Labels: P3, cla: yes, pr: lgtm, pr: merge ready, target: patch

#18054 fix(material-experimental/mdc-chips): remove aria-hidden from focusable element
  src/material-experimental/mdc-chips/chip-icons.ts
  src/material-experimental/mdc-chips/chip-remove.spec.ts
Labels: P3, cla: yes, pr: lgtm, pr: merge ready, target: patch

#18049 fix(mdc-chips): Set aria-required on input instead of grid
  src/dev-app/mdc-chips/mdc-chips-demo.html
  src/material-experimental/mdc-chips/chip-grid.spec.ts
  src/material-experimental/mdc-chips/chip-grid.ts
  src/material-experimental/mdc-chips/chip-input.spec.ts
  src/material-experimental/mdc-chips/chip-input.ts
Labels: P3, a11y, cla: yes, pr: lgtm, pr: merge ready, target: patch

#18044 fix(material-experimental/mdc-chips): avoid potential server-side rendering errors
  src/material-experimental/mdc-chips/chip.ts
  src/universal-app/kitchen-sink-mdc/kitchen-sink-mdc.html
Labels: P3, cla: yes, pr: lgtm, pr: merge ready, target: patch

#18042 docs: fixed minor typos and table formatting
  FAQ.md
  README.md
  src/material/card/card.md
  src/material/icon/icon.md
Labels: P3, cla: yes, docs, pr: lgtm, pr: merge ready, pr: merge safe, target: patch

#18035 fix(material-experimental/mdc-slide-toggle): fix extra border in latest canary version
  package.json
  src/material-experimental/mdc-slide-toggle/_mdc-slide-toggle.scss
  src/material-experimental/mdc-slide-toggle/slide-toggle.ts
  yarn.lock
Labels: P3, cla: yes, pr: lgtm, pr: merge ready, pr: merge safe, target: patch

#18024 refactor(table): add the ability to get row text organized by column in harness
  src/material/table/testing/row-harness.ts
  src/material/table/testing/shared.spec.ts
  src/material/table/testing/table-harness.ts
  tools/public_api_guard/material/table/testing.d.ts
Labels: P3, cla: yes, pr: lgtm, pr: merge ready, pr: merge safe, target: minor

#18023 build: fix stylelint violations and bump stylelint version
  package.json
  src/cdk/a11y/_a11y.scss
  yarn.lock
Labels: P3, cla: yes, pr: lgtm, pr: merge ready, pr: merge safe, target: patch

#18001 feat(material/grid-list): add test harness
  src/material/grid-list/grid-list.ts
  src/material/grid-list/grid-tile.ts
  src/material/grid-list/public-api.ts
  src/material/grid-list/testing/BUILD.bazel
  src/material/grid-list/testing/grid-list-harness-filters.ts
  src/material/grid-list/testing/grid-list-harness.spec.ts
  src/material/grid-list/testing/grid-list-harness.ts
  src/material/grid-list/testing/grid-tile-harness.ts
  src/material/grid-list/testing/index.ts
  src/material/grid-list/testing/public-api.ts
  src/material/grid-list/testing/shared.spec.ts
  src/material/grid-list/tile-coordinator.ts
Labels: cla: yes, pr: lgtm, pr: merge ready, target: patch

#17995 fix(sidenav): move focus into sidenav in side mode if autoFocus enabled explicitly
  src/material/sidenav/drawer.spec.ts
  src/material/sidenav/drawer.ts
  tools/public_api_guard/material/sidenav.d.ts
Labels: P3, cla: yes, pr: lgtm, pr: merge ready, target: patch

#17991 fix(material-experimental/mdc-slide-toggle): initial checked and disabled state not reflected visually
  src/dev-app/mdc-slide-toggle/mdc-slide-toggle-demo.html
  src/material-experimental/mdc-slide-toggle/slide-toggle.html
  src/material-experimental/mdc-slide-toggle/slide-toggle.spec.ts
  src/material-experimental/mdc-slide-toggle/slide-toggle.ts
Labels: cla: yes, pr: lgtm, pr: merge ready, target: patch

#17956 docs(material/autocomplete): fix exception on page load
  src/components-examples/material/autocomplete/autocomplete-display/autocomplete-display-example.html
  src/components-examples/material/autocomplete/autocomplete-display/autocomplete-display-example.ts
Labels: P2, cla: yes, docs, pr: lgtm, pr: merge ready, pr: merge safe, target: major

#17934 refactor: remove ts 3.7 compatibility type cast in ripple-renderer
  src/material/core/ripple/ripple-renderer.ts
Labels: cla: yes, pr: lgtm, pr: merge ready, target: patch

#17885 fix(form-field): delete top border from focus animation
  src/material/form-field/form-field-outline.scss
Labels: P3, cla: yes, pr: lgtm, pr: merge ready, target: patch
