Repository angular/components, pull requests merged in 2019-02, with the labels that each got.

#14817 fix(cdk-stepper): coercing selectedIndex value to a Number
  src/cdk/stepper/stepper.ts
  src/lib/stepper/stepper.spec.ts
Labels: cla: yes, pr: lgtm, pr: merge ready, target: patch

#14964 perf(focus-monitor): avoid triggering change detection if there are no subscribers to stream
  src/cdk/a11y/focus-monitor/focus-monitor.ts
Labels: cla: yes, pr: lgtm, pr: merge ready, target: patch

#14967 fix(radio): unable to click to select button if text is marked
  src/lib/radio/radio.scss
Labels: cla: yes, pr: lgtm, pr: merge ready, target: patch

#15076 Revert "perf(focus-monitor): avoid triggering change detection if there are no subscribers to stream"
  src/cdk/a11y/focus-monitor/focus-monitor.ts
Labels: cla: yes

#15081 chore: bump version to 7.3.1 w/ changelog
  CHANGELOG.md
  package.json
Labels: cla: yes, pr: lgtm, pr: merge ready

#15082 chore: bump version to 7.3.1 w/ changelog (#15081)
  CHANGELOG.md
  package.json
Labels: cla: yes

#15073 fix(slide-toggle): input element should use switch role
  src/lib/slide-toggle/slide-toggle.html
  src/lib/slide-toggle/slide-toggle.spec.ts
Labels: a11y, cla: yes, pr: lgtm, pr: merge ready, target: patch

#15067 feat(overlay): allow for scroll strategy to be swapped out
  src/cdk/overlay/overlay-ref.ts
  src/cdk/overlay/overlay.spec.ts
  src/cdk/overlay/scroll/close-scroll-strategy.ts
  src/cdk/overlay/scroll/reposition-scroll-strategy.ts
  src/cdk/overlay/scroll/scroll-strategy.ts
  tools/public_api_guard/cdk/overlay.d.ts
Labels: cla: yes, pr: lgtm, pr: merge ready, target: minor

#15062 fix(checkbox): unable to click to select if text is marked
  src/lib/checkbox/checkbox.scss
Labels: cla: yes, pr: lgtm, pr: merge ready, target: patch

#15035 fix(menu): prevent removal of mat-elevation class
  src/lib/menu/menu-directive.ts
  src/lib/menu/menu.spec.ts
Labels: cla: yes, pr: lgtm, pr: merge ready, target: patch

#14943 feat(dialog): add ariaLabelledBy config option
  src/lib/dialog/dialog-config.ts
  src/lib/dialog/dialog-container.ts
  src/lib/dialog/dialog.spec.ts
  tools/public_api_guard/lib/dialog.d.ts
Labels: cla: yes, pr: lgtm, pr: merge ready, target: minor

#15083 fix(guides): typo
  guides/theming-your-components.md
Labels: cla: yes, commit message fixup, pr: lgtm, pr: merge ready, pr: merge safe, target: patch

#15080 build: publish script should not print error if tag does not exist
  tools/release/extract-release-notes.ts
  tools/release/git/git-client.ts
  tools/release/git/github-urls.ts
  tools/release/publish-release.ts
Labels: cla: yes, pr: lgtm, pr: merge ready, pr: merge safe, target: patch

#15078 build: shard component e2e tests with bazel
  e2e/BUILD.bazel
Labels: cla: yes, pr: lgtm, pr: merge ready, pr: merge safe, target: patch

#15072 Fixed typo in mat-table sticky columns example
  src/material-examples/table-sticky-columns/table-sticky-columns-example.ts
Labels: cla: yes, commit message fixup, pr: lgtm, pr: merge ready, pr: merge safe, target: patch

#15097 build: branch manager should use "7.3.x" as patch branch
  .github/branch-manager.yml
Labels: cla: yes, pr: lgtm, pr: merge ready, pr: merge safe, target: patch

#15101 test: remove div ngFor in chip list tests
  src/lib/chips/chip-list.spec.ts
Labels: cla: yes, pr: lgtm, pr: merge ready, pr: merge safe, target: patch

#15115 Badge icon area labels added #14985
  src/material-examples/badge-overview/badge-overview-example.html
Labels: cla: yes, commit message fixup, docs, pr: lgtm, pr: merge ready, pr: merge safe

#14889 [mat-icon] preventing content from translation
  src/lib/icon/icon.spec.ts
  src/lib/icon/icon.ts
Labels: cla: yes, commit message fixup, pr: lgtm, pr: merge ready, target: patch

#15079 fix(autocomplete): set aria-haspopup
  src/lib/autocomplete/autocomplete-trigger.ts
  src/lib/autocomplete/autocomplete.spec.ts
Labels: a11y, cla: yes, pr: lgtm, pr: merge ready, target: patch

#14875 Don't recalculate rippleRadius when its 0
  src/lib/checkbox/checkbox.ts
Labels: cla: yes, commit message fixup, pr: lgtm, pr: merge ready, target: patch

#14816 fix(tree): opposite direction padding not being reset on change
  src/cdk/tree/BUILD.bazel
  src/cdk/tree/padding.ts
  src/cdk/tree/tree.spec.ts
Labels: cla: yes, pr: lgtm, pr: merge ready, target: patch

#14809 refactor(paginator): remove extra exposed properties
  src/lib/paginator/paginator.ts
  tools/public_api_guard/lib/paginator.d.ts
Labels: cla: yes, pr: lgtm, pr: merge ready, target: patch

#14769 fix(drag-drop): set class when item or list is disabled
  src/cdk/drag-drop/directives/drag.spec.ts
  src/cdk/drag-drop/directives/drag.ts
  src/cdk/drag-drop/directives/drop-list.ts
  src/cdk/drag-drop/drag-drop.md
  src/material-examples/cdk-drag-drop-disabled/cdk-drag-drop-disabled-example.css
Labels: cla: yes, pr: lgtm, pr: merge ready, target: patch

#14727 fix(drag-drop): standalone draggable drag class not being applied with OnPush change detection
  src/cdk/drag-drop/directives/drag.spec.ts
  src/cdk/drag-drop/directives/drag.ts
  tools/public_api_guard/cdk/drag-drop.d.ts
Labels: cla: yes, pr: lgtm, pr: merge ready, target: patch

#15116 docs(snack-bar): make custom component example more user-friendly
  src/material-examples/snack-bar-component/snack-bar-component-example.html
  src/material-examples/snack-bar-component/snack-bar-component-example.ts
Labels: cla: yes, docs, pr: lgtm, pr: merge ready, pr: merge safe, target: patch

#15132 chore: add `yarn format` command and pre-commit hook to ensure code is formatted
  .clang-format
  .huskyrc.json
  package.json
  yarn.lock
Labels: cla: yes, pr: lgtm, pr: merge ready, pr: merge safe, target: patch

#15150 docs(radio): add aria labelling to examples
  src/material-examples/radio-ng-model/radio-ng-model-example.css
  src/material-examples/radio-ng-model/radio-ng-model-example.html
  src/material-examples/radio-overview/radio-overview-example.html
Labels: cla: yes, pr: lgtm, pr: merge ready, pr: merge safe, target: patch

#15151 chore: bump version to 7.3.2 w/ changelog
  CHANGELOG.md
  package.json
Labels: cla: yes, pr: lgtm, pr: merge ready, pr: merge safe, target: patch

#15152 chore: bump version to 7.3.2 w/ changelog
  CHANGELOG.md
  package.json
Labels: cla: yes, pr: merge safe, target: major

#15127 Fix 'constrast' spelling error in comment
  guides/theming-your-components.md
Labels: cla: yes, commit message fixup, pr: lgtm, pr: merge ready, pr: merge safe

#15114 Toggle buttons aria labels changes #14999
  src/material-examples/button-toggle-exclusive/button-toggle-exclusive-example.html
Labels: cla: yes, pr: lgtm, pr: merge ready, pr: merge safe, target: patch

#15112 Button icons aria labels changes #14998
  src/material-examples/button-types/button-types-example.html
Labels: cla: yes, commit message fixup, pr: lgtm, pr: merge ready, pr: merge safe, target: patch

#15125 fix(bottom-sheet): focus trap not being attached when autoFocus is disabled
  src/lib/bottom-sheet/bottom-sheet-container.ts
  src/lib/bottom-sheet/bottom-sheet.spec.ts
Labels: a11y, cla: yes, pr: lgtm, pr: merge ready, target: patch

#15108 fix(input): input not focused on click in IE if clicked outside of the native input element
  src/lib/form-field/form-field-input.scss
Labels: cla: yes, commit message fixup, pr: lgtm, pr: merge ready, target: patch

#15103 refactor(drag-drop): don't clone items array inside withItems
  src/cdk/drag-drop/drop-list-ref.ts
Labels: cla: yes, pr: lgtm, pr: merge ready, target: patch

#14988 fix(layout): breakpoint observer completing unrelated subscribers when preceding subscriber unsubscribes
  src/cdk/layout/BUILD.bazel
  src/cdk/layout/breakpoints-observer.spec.ts
  src/cdk/layout/breakpoints-observer.ts
Labels: cla: yes, pr: lgtm, pr: merge ready, target: patch

#15154 docs: update readme for Q1 2019
  README.md
Labels: cla: yes, docs, pr: lgtm, pr: merge ready, pr: merge safe, target: major

#15170 build(release-script): npm logout after publishing
  tools/release/npm/npm-client.ts
  tools/release/publish-release.ts
Labels: cla: yes, pr: lgtm, pr: merge ready, pr: merge safe, target: patch

#11093 fix(dialog): don't assign aria-label to close button if button has text
  src/lib/dialog/dialog-content-directives.ts
  src/lib/dialog/dialog.spec.ts
  tools/public_api_guard/lib/dialog.d.ts
Labels: G, a11y, cla: yes, pr: lgtm, pr: merge ready, target: patch

#15140 fix: errors when building theme using CSS variables
  src/cdk/a11y/_a11y.scss
  src/lib/badge/_badge-theme.scss
  src/lib/core/BUILD.bazel
  src/lib/core/ripple/_ripple.scss
  src/lib/core/style/_elevation.scss
  src/lib/core/theming/_theming.scss
  src/lib/core/theming/test-css-variables-theme.scss
  src/lib/datepicker/_datepicker-theme.scss
  src/lib/sidenav/_sidenav-theme.scss
  src/lib/sort/_sort-theme.scss
  tools/package-tools/gulp/build-scss-pipeline.ts
Labels: cla: yes, pr: lgtm, pr: merge ready, target: patch

#15161 docs(stepper): update non-default boolean for editable prop
  src/cdk/stepper/stepper.md
  src/lib/stepper/stepper.md
Labels: cla: yes, pr: lgtm, pr: merge ready, pr: merge safe, target: patch

#15157 Fixing a typo in a 'select' test
  src/lib/select/select.spec.ts
Labels: cla: yes, commit message fixup, pr: lgtm, pr: merge ready, pr: merge safe, target: patch

#15182 build: fix invalid npm "build" script
  package.json
  tools/gulp/gulpfile.ts
  tools/gulp/tasks/ci.ts
Labels: cla: yes, pr: lgtm, pr: merge ready, pr: merge safe, target: patch

#15183 build: downgrade to sauce-connect v4.5.1
  scripts/saucelabs/start-tunnel.sh
Labels: cla: yes, pr: lgtm, pr: merge ready, pr: merge safe, target: patch

#15131 fix(table): add missing rowgroup roles
  src/cdk/table/table.spec.ts
  src/cdk/table/table.ts
Labels: G, a11y, cla: yes, pr: lgtm, pr: merge ready, target: patch

#15126 feat(a11y): add injection token configure default politeness and duration
  src/cdk/a11y/live-announcer/live-announcer-token.ts
  src/cdk/a11y/live-announcer/live-announcer-tokens.ts
  src/cdk/a11y/live-announcer/live-announcer.spec.ts
  src/cdk/a11y/live-announcer/live-announcer.ts
  src/cdk/a11y/public-api.ts
  tools/public_api_guard/cdk/a11y.d.ts
Labels: cla: yes, pr: lgtm, pr: merge ready, target: minor

#14858 fix(list): disableRipple on selection list not affecting list options after init
  src/dev-app/list/list-demo.html
  src/dev-app/list/list-demo.ts
  src/lib/list/selection-list.spec.ts
  src/lib/list/selection-list.ts
  tools/public_api_guard/lib/list.d.ts
Labels: cla: yes, pr: lgtm, pr: merge ready, target: patch

#14773 fix(bidi): handle uppercase values correctly
  src/cdk/bidi/dir.ts
  src/cdk/bidi/directionality.spec.ts
Labels: cla: yes, pr: lgtm, pr: merge ready, target: patch

#15158 fix(docs): add aria label to checkboxes in selection example, #15021
  src/material-examples/table-selection/table-selection-example.html
  src/material-examples/table-selection/table-selection-example.ts
Labels: cla: yes, commit message fixup, docs, pr: lgtm, pr: merge ready, pr: merge safe, target: patch

#15128 fix(docs): Icons in the toolbar example are missing alternative text …
  src/material-examples/toolbar-multirow/toolbar-multirow-example.html
Labels: cla: yes, commit message fixup, docs, pr: lgtm, pr: merge ready, pr: merge safe, target: patch

#15200 fix(docs): CDK bidi overview
  src/cdk/bidi/bidi.md
Labels: cla: yes, commit message fixup, pr: lgtm, pr: merge ready, pr: merge safe, target: patch

#15206 chore(typescript): uniformly access all index signature with index ac…
  src/cdk/drag-drop/directives/drag.ts
  src/lib/datepicker/calendar-body.ts
  src/lib/datepicker/calendar.ts
  src/lib/datepicker/datepicker-toggle.ts
  src/lib/dialog/dialog-content-directives.ts
  src/lib/expansion/expansion-panel-header.ts
  src/lib/icon/icon.ts
  src/lib/select/select.ts
Labels: cla: yes, pr: lgtm, pr: merge ready, target: patch

#15133 fix: add dependency on @angular/forms
  src/lib/package.json
  src/lib/schematics/ng-add/index.spec.ts
  src/lib/schematics/ng-add/index.ts
Labels: cla: yes, pr: lgtm, pr: merge ready, pr: merge safe, target: major

#15095 docs(select): update live examples to use labels
  src/material-examples/select-disabled/select-disabled-example.html
  src/material-examples/select-error-state-matcher/select-error-state-matcher-example.html
  src/material-examples/select-form/select-form-example.html
  src/material-examples/select-hint-error/select-hint-error-example.html
  src/material-examples/select-multiple/select-multiple-example.html
  src/material-examples/select-no-ripple/select-no-ripple-example.html
  src/material-examples/select-optgroup/select-optgroup-example.html
  src/material-examples/select-overview/select-overview-example.html
  src/material-examples/select-panel-class/select-panel-class-example.html
  src/material-examples/select-reset/select-reset-example.html
  src/material-examples/select-value-binding/select-value-binding-example.html
Labels: cla: yes, docs, pr: lgtm, pr: merge ready, pr: merge safe, target: patch

#15238 chore(ivy): add static flag to tab-related static queries
  src/lib/tabs/tab-header.spec.ts
  src/lib/tabs/tab-header.ts
  src/lib/tabs/tab-nav-bar/tab-nav-bar.ts
  src/lib/tabs/tab.ts
Labels: cla: yes

#15235 fix(schematics): do not generate invalid stylesheet files
  src/cdk/schematics/ng-generate/drag-drop/index.spec.ts
  src/cdk/schematics/utils/build-component.ts
Labels: cla: yes, pr: lgtm, pr: merge ready, pr: merge safe, target: patch

#15218 build: publish script should should note where to paste changelog
  tools/release/git/github-urls.ts
  tools/release/publish-release.ts
Labels: cla: yes, pr: lgtm, pr: merge ready, pr: merge safe, target: patch

#15239 chore(ivy): add static flag to dialog-related static queries
  src/cdk-experimental/dialog/dialog-container.ts
  src/lib/dialog/dialog-container.ts
  src/lib/snack-bar/snack-bar-container.ts
Labels: cla: yes

#15252 chore(ivy): add static flag to more queries
  src/cdk/a11y/aria-describer/aria-describer.spec.ts
  src/cdk/portal/portal.spec.ts
  src/cdk/text-field/autofill.spec.ts
  src/lib/autocomplete/autocomplete.spec.ts
  src/lib/bottom-sheet/bottom-sheet-container.ts
  src/lib/sidenav/drawer.spec.ts
Labels: cla: yes

#15253 chore: bump version to 7.3.3 w/ changelog
  CHANGELOG.md
  package.json
Labels: cla: yes, pr: lgtm, pr: merge ready, pr: merge safe, target: patch

#15255 chore(ivy): add static flag to tree-related static queries
  src/cdk/tree/tree.spec.ts
  src/cdk/tree/tree.ts
  src/lib/tree/tree.ts
Labels: cla: yes, pr: lgtm, pr: merge ready

#15257 chore(ivy): add static flag to table-related static queries
  src/cdk/table/table.ts
Labels: cla: yes

#15269 chore: bump version to 7.3.3 w/ changelog for master (#15253)
  CHANGELOG.md
  package.json
Labels: cla: yes, pr: lgtm, pr: merge ready, pr: merge safe, target: major

#15267 chore(ivy): fix static query stragglers that were not marked static q…
  src/cdk/table/table.spec.ts
  src/lib/paginator/paginator.spec.ts
  src/lib/slide-toggle/slide-toggle.spec.ts
Labels: cla: yes, pr: lgtm, pr: merge ready, pr: merge safe

#15273 test(table): remove redundant test
  src/cdk/table/table.spec.ts
Labels: cla: yes, pr: lgtm, pr: merge ready, pr: merge safe, target: patch

#15244 test(focus-monitor): fix test description
  src/cdk/a11y/focus-monitor/focus-monitor.spec.ts
Labels: cla: yes, commit message fixup, pr: lgtm, pr: merge ready, pr: merge safe, target: patch

#15241 docs: normalize keyboard interaction sections and add escape key
  src/cdk/stepper/stepper.md
  src/lib/autocomplete/autocomplete.md
  src/lib/datepicker/datepicker.md
  src/lib/menu/menu.md
  src/lib/stepper/stepper.md
  src/lib/tabs/tabs.md
Labels: cla: yes, docs, pr: lgtm, pr: merge ready, pr: merge safe

#15229 docs: update documentation on creating a custom material module
  guides/getting-started.md
Labels: cla: yes, docs, pr: lgtm, pr: merge ready, pr: merge safe, target: patch

#14732 feat(drag-drop): allow for dragging sequence to be delayed
  src/cdk/drag-drop/directives/drag.spec.ts
  src/cdk/drag-drop/directives/drag.ts
  src/cdk/drag-drop/drag-ref.ts
  tools/public_api_guard/cdk/drag-drop.d.ts
Labels: cla: yes, pr: lgtm, pr: merge ready, target: minor

#14895 fix(radio): underlying label not expanding to width of radio button
  src/lib/radio/radio.scss
Labels: cla: yes, pr: lgtm, pr: merge ready, target: patch

#14896 fix(menu): support focus first/last item via home/end keys
  src/lib/menu/menu-directive.ts
  src/lib/menu/menu.spec.ts
Labels: a11y, cla: yes, pr: lgtm, pr: merge ready, target: patch

#14932 fix(select): update panel width if the viewport size changes
  src/lib/select/select.spec.ts
  src/lib/select/select.ts
Labels: cla: yes, pr: lgtm, pr: merge ready, target: patch

#14935 fix(overlay): flexible position strategy throwing error for empty strings
  src/cdk/overlay/position/flexible-connected-position-strategy.spec.ts
  src/cdk/overlay/position/flexible-connected-position-strategy.ts
Labels: cla: yes, pr: lgtm, pr: merge ready, target: patch

#15019 fix(progress-bar): clear aria-valuenow in indeterminate or query mode
  src/lib/progress-bar/progress-bar.spec.ts
  src/lib/progress-bar/progress-bar.ts
Labels: a11y, cla: yes, pr: lgtm, pr: merge ready, target: patch

#15052 fix(progress-spinner): clear aria-valuenow in indeterminate mode
  src/lib/progress-spinner/progress-spinner.spec.ts
  src/lib/progress-spinner/progress-spinner.ts
Labels: a11y, cla: yes, pr: lgtm, pr: merge ready, target: patch

#15064 feat(drag-drop): add the ability to disable sorting in a list
  src/cdk/drag-drop/directives/drag.spec.ts
  src/cdk/drag-drop/directives/drop-list.ts
  src/cdk/drag-drop/drop-list-ref.ts
  tools/public_api_guard/cdk/drag-drop.d.ts
Labels: cla: yes, pr: lgtm, pr: merge ready, target: minor

#15065 fix(drag-drop): disabled value not being synced to drop list ref
  src/cdk/drag-drop/directives/drag.spec.ts
  src/cdk/drag-drop/directives/drop-list.ts
Labels: cla: yes, pr: lgtm, pr: merge ready, target: patch

#15066 fix(drag-drop): preview not being rendered inside fullscreen element
  src/cdk/drag-drop/BUILD.bazel
  src/cdk/drag-drop/directives/drag.spec.ts
  src/cdk/drag-drop/drag-ref.ts
Labels: cla: yes, pr: lgtm, pr: merge ready, target: patch

#15135 fix(drag-drop): clear duplicate ids from descendants
  src/cdk/drag-drop/directives/drag.spec.ts
  src/cdk/drag-drop/drag-ref.ts
Labels: cla: yes, pr: lgtm, pr: merge ready, target: patch

#15136 build: avoid 404 warnings in Karma tests
  src/lib/icon/icon.spec.ts
  test/karma.conf.js
Labels: cla: yes, pr: lgtm, pr: merge ready, pr: merge safe, target: patch

#15160 fix(select): error when navigating via keyboard to reset option on a closed select
  src/lib/select/select.spec.ts
  src/lib/select/select.ts
Labels: cla: yes, pr: lgtm, pr: merge ready, target: patch

#15185 fix(autocomplete): remove old classes when classlist has changed
  src/lib/autocomplete/autocomplete.spec.ts
  src/lib/autocomplete/autocomplete.ts
Labels: cla: yes, pr: lgtm, pr: merge ready, target: patch

#15205 feat(menu): allow focus restoration to be disabled
  src/lib/menu/menu-trigger.ts
  src/lib/menu/menu.spec.ts
  tools/public_api_guard/lib/menu.d.ts
Labels: cla: yes, pr: lgtm, pr: merge ready, target: minor

#15210 fix(typography): move header letter spacing into typography config
  src/lib/core/typography/_typography.scss
Labels: cla: yes, pr: lgtm, pr: merge ready, target: patch

#15236 fix(slide-toggle): thumb animation not working on mobile
  src/lib/slide-toggle/slide-toggle.scss
Labels: cla: yes, pr: lgtm, pr: merge ready, target: patch

#15237 feat(selection-list): support specifying theme color
  src/dev-app/list/list-demo.html
  src/lib/list/selection-list.spec.ts
  src/lib/list/selection-list.ts
  tools/public_api_guard/lib/list.d.ts
Labels: cla: yes, pr: lgtm, pr: merge ready, target: minor

#15250 fix(a11y): don't set aria description if it's the same as the node's aria-label
  src/cdk/a11y/aria-describer/aria-describer.spec.ts
  src/cdk/a11y/aria-describer/aria-describer.ts
Labels: a11y, cla: yes, pr: lgtm, pr: merge ready, target: patch

#15167 fix(docs): aria labels added for mat-chip-list examples #15010
  src/material-examples/chips-autocomplete/chips-autocomplete-example.html
  src/material-examples/chips-input/chips-input-example.html
  src/material-examples/chips-overview/chips-overview-example.html
  src/material-examples/chips-stacked/chips-stacked-example.html
Labels: a11y, cla: yes, commit message fixup, docs, pr: lgtm, pr: merge ready, pr: merge safe, target: patch

#15147 fix(examples): fix form-field-custom-control
  src/material-examples/form-field-custom-control/example-tel-input-example.html
  src/material-examples/form-field-custom-control/form-field-custom-control-example.ts
Labels: cla: yes, commit message fixup, pr: lgtm, pr: merge ready, pr: merge safe, target: patch

#15146 fix(docs): Menu button in example is missing an accessible name #15039
  src/material-examples/menu-icons/menu-icons-example.html
Labels: a11y, cla: yes, commit message fixup, docs, pr: lgtm, pr: merge ready, pr: merge safe

#15145 fix(docs): Icon examples aria labels added #15013
  src/material-examples/icon-overview/icon-overview-example.html
  src/material-examples/icon-svg/icon-svg-example.html
Labels: a11y, cla: yes, commit message fixup, docs, pr: lgtm, pr: merge ready, pr: merge safe, target: patch

#15129 fix(docs): password visibility toggle example in form field component…
  src/material-examples/form-field-prefix-suffix/form-field-prefix-suffix-example.html
Labels: a11y, cla: yes, commit message fixup, docs, pr: lgtm, pr: merge ready, pr: merge safe

#15130 fix(docs): telephone number input control example is missing programa…
  src/material-examples/form-field-custom-control/example-tel-input-example.html
Labels: a11y, cla: yes, commit message fixup, docs, pr: lgtm, pr: merge ready, pr: merge safe

#15289 test(menu): refactor test that depends on static queries
  src/lib/menu/menu.spec.ts
Labels: cla: yes, pr: merge safe

#15300 test(sidenav): fix sidenav failures under Ivy
  src/lib/sidenav/drawer.spec.ts
  src/lib/sidenav/drawer.ts
  src/lib/sidenav/sidenav.ts
Labels: cla: yes, pr: lgtm, pr: merge ready, pr: merge safe

#15303 test(grid-list): make error expectation less brittle
  src/lib/grid-list/grid-list.spec.ts
Labels: cla: yes, pr: lgtm, pr: merge ready, pr: merge safe, target: patch

#15309 test(slide-toggle): adding missing detectChanges() and tick()
  src/lib/slide-toggle/slide-toggle.spec.ts
Labels: cla: yes, pr: lgtm, pr: merge ready, pr: merge safe, target: patch

#15301 test(overlay): use static queries w/ overlay containers
  src/cdk/overlay/fullscreen-overlay-container.spec.ts
  src/cdk/overlay/overlay-container.spec.ts
Labels: cla: yes, pr: lgtm, pr: merge ready, pr: merge safe

#15320 test(select): update static query tests
  src/lib/select/select.spec.ts
Labels: cla: yes, pr: lgtm, pr: merge ready, pr: merge safe

#15302 chore: don't run CI on the ivy-2019 branch
  .circleci/config.yml
Labels: cla: yes, pr: lgtm, pr: merge ready, pr: merge safe, target: major

#15330 test(expansion): rework tests that depend on static queries
  src/lib/expansion/accordion.spec.ts
  src/lib/expansion/expansion.spec.ts
Labels: cla: yes, pr: merge safe
