Repository angular/components, pull requests merged in 2019-01, with the labels that each got.

#14687 build: run moment adapter tests with bazel
  src/material-moment-adapter/BUILD.bazel
  src/material-moment-adapter/require-config.js
Labels: cla: yes, pr: lgtm, pr: merge ready, pr: merge safe, target: patch

#14663 docs(radio-button): fix radio button spacing
  src/material-examples/radio-overview/radio-overview-example.css
Labels: cla: yes, docs, pr: lgtm, pr: merge ready, pr: merge safe, target: patch

#14643 build: unable to render individual examples in demo app
  src/dev-app/example/example-list.ts
  src/dev-app/example/example.ts
Labels: cla: yes, pr: lgtm, pr: merge ready, pr: merge safe, target: patch

#14638 build: remove obsolete publish snapshots check
  .circleci/config.yml
Labels: cla: yes, pr: lgtm, pr: merge ready, pr: merge safe, target: patch

#14619 build: ensure that there are no invalid dynamic imports
  tools/release/release-output/check-packages.ts
  tools/release/release-output/output-validations.ts
Labels: cla: yes, pr: lgtm, pr: merge ready, pr: merge safe, target: patch

#14611 build: dev app not picking up typography changes
  tools/gulp/tasks/development.ts
Labels: cla: yes, pr: lgtm, pr: merge ready, pr: merge safe, target: patch

#14618 build: replace custom file casing rule with integrated rule
  package.json
  src/cdk/schematics/ng-update/test-cases/misc/method-call-checks.spec.ts
  src/lib/schematics/ng-update/test-cases/misc/constructor-checks.spec.ts
  tools/tslint-rules/fileNameCasingScopedRule.ts
  tslint.json
  yarn.lock
Labels: cla: yes, pr: lgtm, pr: merge ready, pr: merge safe, target: patch

#14578 docs(drag-drop) correct 'lockAxis' to 'cdkDropListLockAxis'
  src/cdk/drag-drop/drag-drop.md
Labels: cla: yes, docs, pr: lgtm, pr: merge ready, pr: merge safe, target: patch

#14685 fix(moment-adapter): incorrectly deserializing moment dates and not setting locale on deserialized values
  src/material-moment-adapter/adapter/moment-date-adapter.spec.ts
  src/material-moment-adapter/adapter/moment-date-adapter.ts
Labels: cla: yes, pr: lgtm, pr: merge ready, pr: merge safe, target: patch

#14698 fix(input): unable to reset focused state of readonly input
  src/lib/input/input.spec.ts
  src/lib/input/input.ts
Labels: cla: yes, pr: lgtm, pr: merge ready, target: patch

#14688 chore: bump year
  LICENSE
Labels: cla: yes, pr: lgtm, pr: merge ready, pr: merge safe, target: patch

#14601 Fix(tree):allow NestedTreeControl to have null or undefined child
  src/cdk/tree/control/base-tree-control.ts
  src/cdk/tree/control/nested-tree-control.ts
  src/cdk/tree/control/tree-control.ts
  src/lib/tree/tree.spec.ts
  tools/public_api_guard/cdk/tree.d.ts
Labels: cla: yes, pr: lgtm, pr: merge ready, target: patch

#14675 fix(slider): don't handle keyboard events with modifier keys
  src/lib/slider/slider.spec.ts
  src/lib/slider/slider.ts
Labels: cla: yes, pr: lgtm, pr: merge ready, target: patch

#14666 refactor(radio): remove usage of `mixinDisabled`
  src/lib/radio/radio.ts
Labels: cla: yes, pr: lgtm, pr: merge ready, target: patch

#14629 fix(a11y): remove listeners when focus trap anchors are removed
  src/cdk/a11y/focus-trap/focus-trap.ts
Labels: cla: yes, pr: lgtm, pr: merge ready, target: patch

#14691 fix(datepicker): native date adapter not preserving time when cloning
  src/lib/core/datetime/native-date-adapter.spec.ts
  src/lib/core/datetime/native-date-adapter.ts
Labels: cla: yes, pr: lgtm, pr: merge ready, target: patch

#14637 fix(list): add hover and focus indication in high contrast mode
  src/lib/list/BUILD.bazel
  src/lib/list/list.scss
Labels: a11y, cla: yes, pr: lgtm, pr: merge ready, target: patch

#14673 fix(typography): deprecation warning in latest sass version
  package.json
  src/lib/core/typography/_typography-utils.scss
  tools/package-tools/gulp/build-scss-pipeline.ts
  yarn.lock
Labels: cla: yes, pr: lgtm, pr: merge ready, target: patch

#14607 fix(select): don't shift arrow if there is no label
  src/lib/form-field/form-field.ts
  src/lib/select/select.scss
Labels: cla: yes, pr: lgtm, pr: merge ready, target: patch

#14720 fix(select): form field state not updated if options are reset
  src/lib/select/select.spec.ts
  src/lib/select/select.ts
Labels: cla: yes, pr: lgtm, pr: merge ready, target: patch

#14748 chore: bump version to 7.2.1 w/ changelog
  CHANGELOG.md
  package.json
Labels: cla: yes, pr: lgtm, pr: merge ready, pr: merge safe

#14622 build: update nodejs rules
  WORKSPACE
  tools/release/publish-release.ts
Labels: cla: yes, pr: lgtm, pr: merge ready, pr: merge safe, target: patch

#14667 build: prepare schematics for v8
  src/cdk/schematics/migration.json
  src/cdk/schematics/ng-update/index.ts
  src/cdk/schematics/ng-update/target-version.ts
  src/cdk/schematics/ng-update/test-cases/index.spec.ts
  src/cdk/schematics/ng-update/test-cases/misc/method-call-checks.spec.ts
  src/cdk/schematics/ng-update/test-cases/v6-test-cases.spec.ts
  src/cdk/schematics/ng-update/test-cases/v7-test-cases.spec.ts
  src/cdk/schematics/ng-update/update-schematic.md
  src/cdk/schematics/testing/BUILD.bazel
  src/cdk/schematics/testing/test-case-setup.ts
  src/cdk/schematics/testing/tsconfig.json
  src/lib/schematics/ng-update/test-cases/index.spec.ts
  src/lib/schematics/ng-update/test-cases/misc/constructor-checks.spec.ts
  src/lib/schematics/ng-update/test-cases/misc/import-checks.spec.ts
  src/lib/schematics/ng-update/test-cases/v6-test-cases.spec.ts
  src/lib/schematics/ng-update/test-cases/v7-test-cases.spec.ts
Labels: cla: yes, pr: lgtm, pr: merge ready, pr: merge safe, target: patch

#14692 docs(table): incorrect initial request in http example
  src/material-examples/table-http/table-http-example.css
  src/material-examples/table-http/table-http-example.html
  src/material-examples/table-http/table-http-example.ts
Labels: cla: yes, docs, pr: lgtm, pr: merge ready, pr: merge safe, target: patch

#14706 build: do not run docs-package targets on circle
  .circleci/config.yml
  src/BUILD.bazel
  src/material-examples/BUILD.bazel
Labels: cla: yes, pr: lgtm, pr: merge ready, pr: merge safe, target: patch

#14707 build: test material entry-points against api goldens
  src/lib/BUILD.bazel
  tools/public_api_guard/BUILD.bazel
  tools/public_api_guard/lib/autocomplete.d.ts
  tools/public_api_guard/lib/badge.d.ts
  tools/public_api_guard/lib/bottom-sheet.d.ts
  tools/public_api_guard/lib/button-toggle.d.ts
  tools/public_api_guard/lib/button.d.ts
  tools/public_api_guard/lib/card.d.ts
  tools/public_api_guard/lib/checkbox.d.ts
  tools/public_api_guard/lib/chips.d.ts
  tools/public_api_guard/lib/core.d.ts
  tools/public_api_guard/lib/datepicker.d.ts
  tools/public_api_guard/lib/dialog.d.ts
  tools/public_api_guard/lib/divider.d.ts
  tools/public_api_guard/lib/expansion.d.ts
  tools/public_api_guard/lib/form-field.d.ts
  tools/public_api_guard/lib/grid-list.d.ts
  tools/public_api_guard/lib/icon.d.ts
  tools/public_api_guard/lib/input.d.ts
  tools/public_api_guard/lib/lib.d.ts
  tools/public_api_guard/lib/list.d.ts
  tools/public_api_guard/lib/menu.d.ts
  tools/public_api_guard/lib/paginator.d.ts
  tools/public_api_guard/lib/progress-bar.d.ts
  tools/public_api_guard/lib/progress-spinner.d.ts
  tools/public_api_guard/lib/radio.d.ts
  tools/public_api_guard/lib/select.d.ts
  tools/public_api_guard/lib/sidenav.d.ts
  tools/public_api_guard/lib/slide-toggle.d.ts
  tools/public_api_guard/lib/slider.d.ts
  tools/public_api_guard/lib/snack-bar.d.ts
  tools/public_api_guard/lib/sort.d.ts
  tools/public_api_guard/lib/stepper.d.ts
  tools/public_api_guard/lib/table.d.ts
  tools/public_api_guard/lib/tabs.d.ts
  tools/public_api_guard/lib/toolbar.d.ts
  tools/public_api_guard/lib/tooltip.d.ts
  tools/public_api_guard/lib/tree.d.ts
Labels: cla: yes, pr: lgtm, pr: merge ready, pr: merge safe, target: patch

#14716 build: run release output validations on circle
  .circleci/config.yml
  package.json
  tools/release/check-release-output.ts
  tools/release/publish-release.ts
  tools/release/release-output/check-package.ts
Labels: cla: yes, pr: lgtm, pr: merge ready, pr: merge safe, target: patch

#14757 build: update to angular 7.2.0
  WORKSPACE
  package.json
  yarn.lock
Labels: cla: yes, pr: lgtm, pr: merge ready, pr: merge safe, target: patch

#14754 chore(typos): remove extra "the" from comments
  src/cdk/a11y/interactivity-checker/interactivity-checker.ts
  src/cdk/overlay/overlay-ref.ts
  src/cdk/portal/portal.ts
  src/dev-app/chips/chips-demo.html
  src/lib/button-toggle/button-toggle.md
  src/lib/chips/chip-list.ts
  src/lib/core/ripple/ripple.ts
  src/lib/datepicker/calendar.ts
  src/lib/form-field/prefix.ts
Labels: cla: yes, pr: lgtm, pr: merge ready, pr: merge safe, target: patch

#14770 build: fix public api goldens
  tools/public_api_guard/lib/radio.d.ts
Labels: cla: yes, pr: merge safe, target: patch

#14767 chore: reenable branch-manager
  .github/branch-manager.yml
Labels: cla: yes, pr: lgtm, pr: merge ready, pr: merge safe, target: patch

#14775 Revert "build: update to angular 7.2.0 (#14757)"
  WORKSPACE
  package.json
  yarn.lock
Labels: cla: yes, pr: lgtm, target: patch

#14786 build: fix incorrect amd module names
  tools/package-tools/build-bundles.ts
Labels: cla: yes, pr: lgtm, pr: merge ready, pr: merge safe, target: patch

#14656 build: run e2e tests with bazel
  .circleci/config.yml
  WORKSPACE
  e2e/BUILD.bazel
  e2e/components/block-scroll-strategy-e2e.spec.ts
  e2e/components/button-e2e.spec.ts
  e2e/components/button-toggle-e2e.spec.ts
  e2e/components/card-e2e.spec.ts
  e2e/components/checkbox-e2e.spec.ts
  e2e/components/dialog-e2e.spec.ts
  e2e/components/expansion-e2e.spec.ts
  e2e/components/grid-list-e2e.spec.ts
  e2e/components/icon-e2e.spec.ts
  e2e/components/input-e2e.spec.ts
  e2e/components/list-e2e.spec.ts
  e2e/components/menu-e2e.spec.ts
  e2e/components/progress-bar-e2e.spec.ts
  e2e/components/progress-spinner-e2e.spec.ts
  e2e/components/radio-e2e.spec.ts
  e2e/components/sidenav-e2e.spec.ts
  e2e/components/slide-toggle-e2e.spec.ts
  e2e/components/stepper-e2e.spec.ts
  e2e/components/tabs-e2e.spec.ts
  e2e/components/toolbar-e2e.spec.ts
  e2e/components/virtual-scroll-e2e.spec.ts
  e2e/index-e2e.spec.ts
  e2e/protractor.conf.js
  e2e/start-devserver.js
  e2e/tsconfig.json
  e2e/util/actions.ts
  e2e/util/asserts.ts
  e2e/util/query.ts
  src/e2e-app/BUILD.bazel
  src/e2e-app/devserver-configure.js
  src/e2e-app/index.html
  src/e2e-app/system-config.ts
  src/e2e-app/tsconfig-build.json
  test/protractor.conf.js
  tools/axe-protractor/BUILD.bazel
  tools/axe-protractor/index.js
  tools/gulp/gulpfile.ts
  tools/gulp/tasks/ci.ts
  tools/gulp/tasks/e2e.ts
Labels: cla: yes, pr: lgtm, pr: merge ready, pr: merge safe, target: patch

#14655 docs(portal): add overview example
  src/cdk/portal/portal.md
  src/material-examples/cdk-portal-overview/cdk-portal-overview-example.css
  src/material-examples/cdk-portal-overview/cdk-portal-overview-example.html
  src/material-examples/cdk-portal-overview/cdk-portal-overview-example.ts
  src/material-examples/material-module.ts
Labels: cla: yes, docs, pr: lgtm, pr: merge ready, pr: merge safe, target: patch

#14642 build: bazel repository changes not cached on circleci
  .circleci/config.yml
Labels: cla: yes, pr: lgtm, pr: merge ready, pr: merge safe, target: patch

#14612 build: switch to docs-content from examples package
  src/material-examples/example-data.ts
  tools/dgeni/templates/constant.template.html
  tools/dgeni/templates/type-alias.template.html
  tools/package-docs-content/package-docs-content.ts
Labels: cla: yes, pr: lgtm, pr: merge ready, pr: merge safe, target: patch

#14801 fix(icon): clean up cached references in icon registry on destroy
  src/lib/icon/icon-registry.ts
  tools/public_api_guard/lib/icon.d.ts
Labels: cla: yes, pr: lgtm, pr: merge ready, target: patch

#14789 refactor: remove deprecated Observable.create usages
  src/cdk-experimental/scrolling/auto-size-virtual-scroll.ts
  src/cdk/drag-drop/directives/drag.ts
  src/cdk/drag-drop/drag-ref.ts
  src/cdk/observers/observe-content.ts
  src/cdk/overlay/overlay-ref.ts
  src/cdk/overlay/position/flexible-connected-position-strategy.ts
  src/cdk/scrolling/scroll-dispatcher.ts
  src/cdk/scrolling/scrollable.ts
  src/cdk/scrolling/virtual-scroll-viewport.ts
  src/lib/tabs/tab-group.spec.ts
  src/material-examples/tab-group-async/tab-group-async-example.ts
Labels: cla: yes, pr: lgtm, pr: merge ready, target: patch

#14778 fix(tabs): better handling of animationDuration without units
  src/lib/tabs/tab-group.spec.ts
  src/lib/tabs/tab-group.ts
Labels: cla: yes, pr: lgtm, pr: merge ready, target: patch

#14772 feat(dialog): support adding and removing classes via dialogRef
  src/cdk/overlay/overlay-ref.ts
  src/cdk/overlay/overlay.spec.ts
  src/dev-app/dialog/dialog-demo.html
  src/dev-app/dialog/dialog-demo.ts
  src/lib/dialog/dialog-ref.ts
  src/lib/dialog/dialog.spec.ts
  tools/public_api_guard/cdk/overlay.d.ts
Labels: cla: yes, pr: lgtm, pr: merge ready, target: minor

#14747 refactor(table): use DocumentFragment for faster DOM insertions
  src/cdk/table/table.ts
Labels: cla: yes, pr: lgtm, pr: merge ready, target: patch

#14832 chore(ivy): make unit tests runnable
  scripts/ivy/install-angular.sh
  src/cdk/tree/tree.spec.ts
  test/karma-system-config.js
  yarn.lock
Labels: cla: yes, pr: lgtm, pr: merge ready, pr: merge safe

#14740 fix(datepicker): typo in datepicker.spec.ts
  src/lib/datepicker/datepicker.spec.ts
Labels: cla: yes, pr: lgtm, pr: merge ready, pr: merge safe, target: patch

#14830 build: fix api goldens for dialog changes
  tools/public_api_guard/lib/dialog.d.ts
Labels: cla: yes, pr: lgtm, pr: merge ready, pr: merge safe, target: patch

#14654 refactor(drag-drop): clean up DragRef public API
  src/cdk/drag-drop/directives/drag-handle.ts
  src/cdk/drag-drop/directives/drag.ts
  src/cdk/drag-drop/drag-ref.ts
  src/cdk/drag-drop/drop-list-ref.ts
  tools/public_api_guard/cdk/drag-drop.d.ts
Labels: cla: yes, pr: lgtm, pr: merge ready, pr: merge safe, target: patch

#14835 hore(ivy): add @bazel/bazel to devDependencies
  package.json
  yarn.lock
Labels: cla: yes, pr: lgtm, pr: merge ready

#14758 Adding a forgotten markForCheck in mat-chip-list
  src/lib/chips/chip-list.ts
Labels: G, cla: yes, pr: lgtm, pr: merge ready, target: patch

#14725 fix(drag-drop): dragging styling not being reset in some cases with OnPush change detection
  src/cdk/drag-drop/directives/drag.spec.ts
  src/cdk/drag-drop/directives/drop-list.ts
Labels: cla: yes, pr: lgtm, pr: merge ready, target: patch

#14846 chore(ivy): filter unit tests based on a blacklist
  test/karma-test-shim.js
Labels: cla: yes

#14844 chore(tabs): update api goldens
  tools/public_api_guard/lib/tabs.d.ts
Labels: cla: yes, pr: lgtm, pr: merge ready, pr: merge safe, target: patch

#14634 build: publish docs-content bazel artifacts
  .bazelrc
  .circleci/config.yml
  package.json
  scripts/circleci/publish-snapshots.sh
  scripts/deploy/publish-docs-content.sh
  tools/bazel-stamp-vars.js
  tools/bazel-stamp-vars.sh
  tools/gulp/gulpfile.ts
  tools/gulp/tasks/docs.ts
  yarn.lock
Labels: cla: yes, pr: lgtm, pr: merge ready, pr: merge safe, target: patch

#14733 fix(sort): extra Firefox focus outline not being reset
  src/lib/sort/sort-header.scss
Labels: cla: yes, pr: lgtm, pr: merge ready, target: patch

#14712 fix(drag-drop): apply translation transform before user transforms
  src/cdk/drag-drop/directives/drag.spec.ts
  src/cdk/drag-drop/drag-ref.ts
Labels: cla: yes, pr: lgtm, pr: merge ready, target: patch

#14701 fix(drag-drop): restore initial transform when resetting
  src/cdk/drag-drop/directives/drag.spec.ts
  src/cdk/drag-drop/drag-ref.ts
Labels: cla: yes, pr: lgtm, pr: merge ready, target: patch

#14697 fix(drag-drop): incorrectly preserving transform if root element changes
  src/cdk/drag-drop/directives/drag.spec.ts
  src/cdk/drag-drop/drag-ref.ts
Labels: cla: yes, pr: lgtm, pr: merge ready, target: patch

#14672 fix(overlay): not sizing flexible overlay correctly when opening downwards on a scrollable page
  src/cdk/overlay/position/flexible-connected-position-strategy.spec.ts
  src/cdk/overlay/position/flexible-connected-position-strategy.ts
Labels: cla: yes, pr: lgtm, pr: merge ready, target: patch

#14665 fix(table): not re-rendering when switching to a smaller set of data than the current page
  src/lib/table/table-data-source.ts
  src/lib/table/table.spec.ts
Labels: cla: yes, pr: lgtm, pr: merge ready, target: patch

#14660 fix(overlay): reset transform when disposing of position strategy
  src/cdk/overlay/position/flexible-connected-position-strategy.spec.ts
  src/cdk/overlay/position/flexible-connected-position-strategy.ts
Labels: cla: yes, pr: lgtm, pr: merge ready, target: patch

#14627 fix(button-toggle): remove references to selected toggle on destroy
  src/lib/button-toggle/button-toggle.spec.ts
  src/lib/button-toggle/button-toggle.ts
Labels: cla: yes, pr: lgtm, pr: merge ready, target: patch

#14620 fix(tooltip): afterHidden stream not being completed
  src/lib/tooltip/tooltip.spec.ts
  src/lib/tooltip/tooltip.ts
Labels: cla: yes, pr: lgtm, pr: merge ready, target: patch

#14610 fix(overlay): update size if dimensions change in overlay directives
  src/cdk/overlay/overlay-directives.spec.ts
  src/cdk/overlay/overlay-directives.ts
Labels: cla: yes, pr: lgtm, pr: merge ready, target: patch

#14234 fix(tabs): don't handle keyboard events with modifier keys
  src/lib/tabs/tab-header.spec.ts
  src/lib/tabs/tab-header.ts
Labels: cla: yes, pr: lgtm, pr: merge ready, target: patch

#14845 Fix a number of nits
  src/lib/core/datetime/date-selection-model.ts
  src/lib/datepicker/calendar-body.spec.ts
  src/lib/datepicker/calendar-body.ts
  src/lib/datepicker/calendar.ts
  src/lib/datepicker/datepicker-input.ts
  src/lib/datepicker/datepicker.spec.ts
  src/lib/datepicker/datepicker.ts
  src/lib/datepicker/year-view.ts
Labels: cla: yes, pr: lgtm, pr: merge ready

#14711 fix(bottom-sheet): allow disableClose to be updated after opened
  src/lib/bottom-sheet/bottom-sheet-ref.ts
  src/lib/bottom-sheet/bottom-sheet.spec.ts
Labels: cla: yes, pr: lgtm, pr: merge ready, target: patch

#14710 docs(cdk-stepper): add guide to create stepper
  guides/creating-a-custom-stepper-using-the-cdk-stepper.md
  src/cdk/stepper/stepper.ts
  src/lib/stepper/stepper-horizontal.html
  src/lib/stepper/stepper-vertical.html
  src/lib/stepper/stepper.spec.ts
  src/material-examples/cdk-custom-stepper-without-form/cdk-custom-stepper-without-form-example.css
  src/material-examples/cdk-custom-stepper-without-form/cdk-custom-stepper-without-form-example.html
  src/material-examples/cdk-custom-stepper-without-form/cdk-custom-stepper-without-form-example.ts
  src/material-examples/cdk-custom-stepper-without-form/example-custom-stepper.css
  src/material-examples/cdk-custom-stepper-without-form/example-custom-stepper.html
  src/material-examples/material-module.ts
  tools/public_api_guard/cdk/stepper.d.ts
Labels: cla: yes, docs, pr: lgtm, pr: merge ready, target: patch

#14705 feat(ripples): support updating global ripple options at runtime
  src/dev-app/dev-app-module.ts
  src/dev-app/dev-app.html
  src/dev-app/dev-app.ts
  src/dev-app/ripple/ripple-options.ts
  src/lib/chips/BUILD.bazel
  src/lib/chips/chip.spec.ts
  src/lib/chips/chip.ts
  src/lib/core/ripple/ripple.md
  src/lib/core/ripple/ripple.ts
  src/lib/tabs/tab-nav-bar/tab-nav-bar.spec.ts
  src/lib/tabs/tab-nav-bar/tab-nav-bar.ts
Labels: cla: yes, pr: lgtm, pr: merge ready, target: minor

#14677 fix(autocomplete): not updating origin if it changes after init
  src/lib/autocomplete/autocomplete-trigger.ts
  src/lib/autocomplete/autocomplete.spec.ts
  src/lib/autocomplete/public-api.ts
Labels: cla: yes, pr: lgtm, pr: merge ready, target: patch

#14651 fix(drag-drop): unable to move item into connected container by passing through another container
  src/cdk/drag-drop/directives/drag.spec.ts
  src/cdk/drag-drop/drag-ref.ts
  src/cdk/drag-drop/drop-list-ref.ts
Labels: cla: yes, pr: lgtm, pr: merge ready, target: patch

#14616 feat(overlay): allow for connected overlay to be positioned relative to a point
  src/cdk/overlay/position/flexible-connected-position-strategy.spec.ts
  src/cdk/overlay/position/flexible-connected-position-strategy.ts
  src/cdk/overlay/position/overlay-position-builder.ts
  tools/public_api_guard/cdk/overlay.d.ts
Labels: cla: yes, pr: lgtm, pr: merge ready, target: minor

#14230 fix(slide-toggle): use default hue for thumb in dark theme
  src/lib/slide-toggle/_slide-toggle-theme.scss
Labels: cla: yes, pr: lgtm, pr: merge ready, target: patch

#14107 fix(menu): not unsubscribing from close stream if trigger is destroyed
  src/lib/menu/menu-trigger.ts
Labels: cla: yes, pr: lgtm, pr: merge ready, target: patch

#14849 build: fix bazel running out of memory for "publish_snapshots"
  .circleci/config.yml
Labels: cla: yes, pr: lgtm, pr: merge ready, pr: merge safe, target: patch

#14641 build: setup bazel remote execution
  .circleci/base-rbe-bazelrc
  .circleci/bazel.rc
  .circleci/config.yml
  .circleci/gcp_token
  scripts/circleci/bazel/setup-remote-execution.sh
Labels: cla: yes, pr: lgtm, pr: merge ready, pr: merge safe, target: patch

#14847 refactor: Prepare for TypeScript v3.2.2
  src/cdk/scrolling/scrollable.ts
Labels: cla: yes, pr: lgtm, pr: merge ready, target: patch

#14836 fix(list): disableRipple on list input not taking effect after init
  src/lib/list/list.spec.ts
  src/lib/list/list.ts
  tools/public_api_guard/lib/list.d.ts
Labels: cla: yes, pr: lgtm, pr: merge ready, target: patch

#14815 refactor(tabs): fix incorrect types for outputs
  src/lib/tabs/tab-header.ts
  tools/public_api_guard/lib/tabs.d.ts
Labels: cla: yes, pr: lgtm, pr: merge ready, target: patch

#14804 refactor(list): refactor component inputs
  src/lib/list/selection-list.ts
Labels: cla: yes, pr: lgtm, pr: merge ready, target: patch

#14854 build: update outdated api goldens
  src/cdk/drag-drop/directives/drag.spec.ts
  tools/public_api_guard/lib/autocomplete.d.ts
  tools/public_api_guard/lib/bottom-sheet.d.ts
  tools/public_api_guard/lib/chips.d.ts
  tools/public_api_guard/lib/core.d.ts
  tools/public_api_guard/lib/tabs.d.ts
  tools/public_api_guard/lib/tooltip.d.ts
Labels: cla: yes, pr: lgtm, pr: merge ready, pr: merge safe, target: patch

#14868 chore: skip CI for ivy-2019 branch
  .circleci/config.yml
Labels: cla: yes, pr: lgtm

#14800 fix(list): deselect option if value doesn't match up
  src/lib/list/selection-list.spec.ts
  src/lib/list/selection-list.ts
Labels: cla: yes, pr: lgtm, pr: merge ready, target: patch

#14867 build: run publish snapshots job with rbe
  .circleci/config.yml
Labels: cla: yes, pr: lgtm, pr: merge ready, pr: merge safe, target: patch

#14871 build: do run "build_release_packages" job in ivy-2019 branch
  .circleci/config.yml
Labels: cla: yes, pr: merge safe, target: patch

#14870 build: run e2e tests with bazel rbe
  .circleci/config.yml
Labels: cla: yes, pr: lgtm, pr: merge ready, pr: merge safe, target: patch

#14876 build: distribute public api guard files by code owner
  .github/CODEOWNERS
Labels: cla: yes, pr: lgtm, pr: merge ready, pr: merge safe, target: patch

#14877 chore: add script to generate ivy test blacklist
  scripts/ivy/generate-blacklist.js
Labels: cla: yes, pr: lgtm, pr: merge ready

#14885 chore: bump version to 7.2.2 w/ changelog
  CHANGELOG.md
  package.json
Labels: cla: yes, pr: lgtm, pr: merge ready, pr: merge safe, target: patch

#14908 fix(cdk-experimental/dialog): re-export portal module
  src/cdk-experimental/dialog/dialog-module.ts
Labels: cla: yes, pr: lgtm, pr: merge ready, pr: merge safe, target: patch

#14899 add links to v7 features in readme
  README.md
Labels: cla: yes, pr: lgtm, pr: merge ready, pr: merge safe, target: patch

#14872 feat(tooltip): allow for default position to be configured
  src/lib/tooltip/tooltip.spec.ts
  src/lib/tooltip/tooltip.ts
  tools/public_api_guard/lib/tooltip.d.ts
Labels: cla: yes, pr: lgtm, pr: merge ready, target: minor

#14855 docs(stepper): fix typo
  src/cdk/stepper/stepper.ts
Labels: cla: yes, pr: lgtm, pr: merge ready, pr: merge safe, target: patch

#13259 fix(button): focus indication hard to see in high contrast mode
  src/lib/button/button.scss
Labels: a11y, cla: yes, pr: lgtm, pr: merge ready, target: patch

#14771 test(overlay): block scroll strategy testing styles leaking into other tests
  src/cdk/overlay/scroll/block-scroll-strategy.spec.ts
Labels: cla: yes, pr: lgtm, pr: merge ready, pr: merge safe, target: patch

#14883 test(moment-adapter): use arabic locale for testing localized dates
  src/lib/core/datetime/native-date-adapter.spec.ts
  src/material-moment-adapter/adapter/moment-date-adapter.spec.ts
Labels: cla: yes, pr: lgtm, pr: merge ready, pr: merge safe, target: patch

#14909 build: remove unused dgeni package configurations
  tools/dgeni/BUILD.bazel
  tools/dgeni/bazel-bin.ts
  tools/dgeni/docs-package.ts
  tools/dgeni/tsconfig.json
Labels: cla: yes, pr: lgtm, pr: merge ready, pr: merge safe, target: patch

#14910 build: add missing bazel action names
  tools/dgeni/index.bzl
  tools/highlight-files/index.bzl
  tools/markdown-to-html/index.bzl
  tools/package-docs-content/index.bzl
  tools/sass_bundle.bzl
Labels: cla: yes, pr: lgtm, pr: merge ready, pr: merge safe, target: patch

#14916 chore: remove duplicate feature template entries
  .github/ISSUE_TEMPLATE/feature---proposal.md
  .github/ISSUE_TEMPLATE/feature-proposal.md
Labels: cla: yes, pr: lgtm, pr: merge ready, pr: merge safe, target: patch

#14917 build: update bazel sass rules
  WORKSPACE
Labels: cla: yes, pr: lgtm, pr: merge ready, pr: merge safe, target: patch

#14921 chore: bump zone.js to 0.8.29
  package.json
  yarn.lock
Labels: cla: yes, pr: lgtm, pr: merge ready, pr: merge safe, target: patch

#14886 docs(radio): fix typo in intro section
  src/lib/radio/radio.md
Labels: cla: yes, pr: lgtm, pr: merge ready, pr: merge safe, target: patch

#14632 feat(tabs): add automatic scrolling when holding down paginator
  src/lib/tabs/tab-header.html
  src/lib/tabs/tab-header.scss
  src/lib/tabs/tab-header.spec.ts
  src/lib/tabs/tab-header.ts
  tools/public_api_guard/lib/tabs.d.ts
Labels: cla: yes, pr: lgtm, pr: merge ready, target: minor

#14437 feat(drag-drop): add service for attaching drag&drop to arbitrary DOM nodes
  src/cdk/drag-drop/BUILD.bazel
  src/cdk/drag-drop/directives/drag.spec.ts
  src/cdk/drag-drop/directives/drag.ts
  src/cdk/drag-drop/directives/drop-list.ts
  src/cdk/drag-drop/drag-drop-module.ts
  src/cdk/drag-drop/drag-drop.spec.ts
  src/cdk/drag-drop/drag-drop.ts
  src/cdk/drag-drop/drag-ref.ts
  src/cdk/drag-drop/drop-list-ref.ts
  src/cdk/drag-drop/public-api.ts
  tools/public_api_guard/cdk/drag-drop.d.ts
Labels: cla: yes, pr: lgtm, pr: merge ready, target: minor

#14423 fix(datepicker): update validation when switching from null to error input
  src/lib/datepicker/datepicker-input.ts
  src/lib/datepicker/datepicker.spec.ts
Labels: G, P1, cla: yes, pr: lgtm, pr: merge ready, target: patch

#14718 doc(tree):simplify tree example
  src/dev-app/tree/tree-demo-module.ts
  src/dev-app/tree/tree-demo.html
  src/dev-app/tree/tree-demo.ts
  src/material-examples/cdk-tree-flat/cdk-tree-flat-example.html
  src/material-examples/cdk-tree-flat/cdk-tree-flat-example.ts
  src/material-examples/cdk-tree-nested/cdk-tree-nested-example.css
  src/material-examples/cdk-tree-nested/cdk-tree-nested-example.html
  src/material-examples/cdk-tree-nested/cdk-tree-nested-example.ts
  src/material-examples/tree-flat-overview/tree-flat-overview-example.html
  src/material-examples/tree-flat-overview/tree-flat-overview-example.ts
  src/material-examples/tree-nested-overview/tree-nested-overview-example.html
  src/material-examples/tree-nested-overview/tree-nested-overview-example.ts
Labels: cla: yes, pr: lgtm, pr: merge ready, pr: merge safe, target: patch

#14922 test(scrolling): correctly treat TestBed.compileComponents as async
  src/cdk-experimental/scrolling/virtual-scroll-viewport.spec.ts
  src/cdk/scrolling/scrollable.spec.ts
  src/cdk/scrolling/virtual-scroll-viewport.spec.ts
Labels: cla: yes, pr: lgtm, pr: merge ready, pr: merge safe, target: patch

#14929 chore(table): fix module declarations comment
  src/lib/table/table-module.ts
Labels: cla: yes, pr: lgtm, pr: merge ready, pr: merge safe, target: patch

#14930 build: update saucelabs connect version
  scripts/saucelabs/start-tunnel.sh
Labels: cla: yes, pr: lgtm, pr: merge ready, pr: merge safe, target: patch

#14933 fix(stepper): ensure step state is not minified
  src/lib/stepper/step-header.html
  src/lib/stepper/step-header.ts
  tools/public_api_guard/lib/stepper.d.ts
Labels: G, P2, cla: yes, pr: lgtm, pr: merge ready

#14984 fix(datepicker): fix input validation
  src/lib/core/datetime/date-selection-model.ts
  src/lib/datepicker/datepicker-input.ts
Labels: cla: yes, pr: lgtm

#14973 build: simplify api golden target names
  tools/public_api_guard/generate-guard-tests.bzl
Labels: cla: yes, pr: lgtm, pr: merge ready, pr: merge safe, target: patch

#14978 chore(form-field): fix spelling mistake
  src/lib/form-field/form-field.ts
Labels: cla: yes, pr: lgtm, pr: merge ready, pr: merge safe, target: patch

#14962 chore: fix dead link in docs
  src/cdk/a11y/a11y.md
Labels: cla: yes, pr: lgtm, pr: merge ready, pr: merge safe, target: patch

#14957 fix(examples): fix form-field custom control `disabled` input
  guides/creating-a-custom-form-field-control.md
  src/material-examples/form-field-custom-control/form-field-custom-control-example.ts
Labels: cla: yes, docs, pr: lgtm, pr: merge ready, pr: merge safe, target: patch

#14787 build: update to angular 7.2.1
  WORKSPACE
  package.json
  yarn.lock
Labels: cla: yes, pr: lgtm, pr: merge ready, pr: merge safe, target: patch

#13902 docs: pointing out breaking change for MatSidenav and MatDrawer in 7.0
  CHANGELOG.md
Labels: cla: yes, pr: merge safe, target: patch

#14989 Revert "docs: pointing out breaking change for MatSidenav and MatDrawer in 7.0"
  CHANGELOG.md
Labels: cla: yes

#15014 build: fix syntax error within codeowners file
  .github/CODEOWNERS
Labels: cla: yes, pr: lgtm, pr: merge ready, pr: merge safe, target: patch

#15002 docs: fix minor typo on comment
  guides/theming-your-components.md
Labels: cla: yes, pr: lgtm, pr: merge ready, pr: merge safe, target: patch

#15003 fix(list): selection list not picking up indirect descendants
  src/lib/list/selection-list.spec.ts
  src/lib/list/selection-list.ts
Labels: cla: yes, pr: lgtm, pr: merge ready, target: patch

#15001 fix(checkbox): not marked as touched immediately on blur with OnPush change detection
  src/lib/checkbox/checkbox.spec.ts
  src/lib/checkbox/checkbox.ts
Labels: cla: yes, pr: lgtm, pr: merge ready, target: patch

#14976 fix(chips): newly-added chips not being disabled when added to a disabled list
  src/lib/chips/chip-list.spec.ts
  src/lib/chips/chip-list.ts
Labels: cla: yes, pr: lgtm, pr: merge ready, target: patch

#14975 fix(overlay): unnecessarily pushing overlay if it is exactly as wide as the viewport
  src/cdk/overlay/position/flexible-connected-position-strategy.spec.ts
  src/cdk/overlay/position/flexible-connected-position-strategy.ts
Labels: cla: yes, pr: lgtm, pr: merge ready, target: patch

#14972 feat(stepper): allow disabling ripples of headers
  src/dev-app/stepper/stepper-demo.html
  src/dev-app/stepper/stepper-demo.ts
  src/lib/stepper/BUILD.bazel
  src/lib/stepper/step-header.html
  src/lib/stepper/step-header.ts
  src/lib/stepper/stepper-horizontal.html
  src/lib/stepper/stepper-vertical.html
  src/lib/stepper/stepper.spec.ts
  src/lib/stepper/stepper.ts
  tools/public_api_guard/lib/stepper.d.ts
Labels: cla: yes, pr: lgtm, pr: merge ready, target: minor

#14971 fix(MatPseudoCheckbox): fix checkmark pseudo-element box-sizing
  src/lib/core/selection/pseudo-checkbox/pseudo-checkbox.scss
Labels: cla: yes, commit message fixup, pr: lgtm, pr: merge ready, target: patch

#14965 fix(table): allow for a caption to be projected
  src/cdk/table/table.spec.ts
  src/cdk/table/table.ts
  tools/public_api_guard/cdk/table.d.ts
Labels: cla: yes, pr: lgtm, pr: merge ready, target: patch

#14963 fix(button): not updating DOM node name if group name changes
  src/lib/button-toggle/button-toggle.spec.ts
  src/lib/button-toggle/button-toggle.ts
Labels: cla: yes, pr: lgtm, pr: merge ready, target: patch

#14960 fix(slider): focus ring showing when ancestor has focus monitoring
  src/lib/slider/slider.scss
Labels: cla: yes, pr: lgtm, pr: merge ready, target: patch

#14950 fix(radio): not updating DOM node name if group name changes
  src/lib/radio/radio.spec.ts
  src/lib/radio/radio.ts
Labels: cla: yes, pr: lgtm, pr: merge ready, target: patch

#14947 fix(table): Clarify unknown table column error
  src/cdk/table/table.spec.ts
  src/cdk/table/table.ts
Labels: cla: yes, pr: lgtm, pr: merge ready, target: patch
