Repository angular/components, pull requests merged in 2019-06, with the labels that each got.

#16146 Update hover color in table expandable rows example
  src/material-examples/table-expandable-rows/table-expandable-rows-example.css
Labels: P4, cla: yes, docs, pr: lgtm, pr: merge ready, pr: merge safe, target: patch

#16058 fix(popover-edit): unable to change type of popover buttons
  src/cdk-experimental/popover-edit/lens-directives.ts
Labels: cla: yes, pr: lgtm, pr: merge ready, pr: merge safe, target: patch

#15917 feat(popover-edit): accessible row hover content
  src/cdk-experimental/popover-edit/edit-event-dispatcher.ts
  src/cdk-experimental/popover-edit/polyfill.ts
  src/cdk-experimental/popover-edit/popover-edit.spec.ts
  src/cdk-experimental/popover-edit/public-api.ts
  src/cdk-experimental/popover-edit/table-directives.ts
  src/dev-app/popover-edit/assets/edit-icon.svg
  src/material-examples/popover-edit-cell-span-mat-table/popover-edit-cell-span-mat-table-example.ts
  src/material-examples/popover-edit-mat-table-flex/popover-edit-mat-table-flex-example.ts
  src/material-examples/popover-edit-mat-table/popover-edit-mat-table-example.html
  src/material-examples/popover-edit-mat-table/popover-edit-mat-table-example.ts
  src/material-examples/popover-edit-tab-out-mat-table/popover-edit-tab-out-mat-table-example.ts
  src/material-experimental/popover-edit/_popover-edit.scss
  src/material-experimental/popover-edit/popover-edit.spec.ts
  src/material-experimental/popover-edit/table-directives.ts
Labels: cla: yes, pr: lgtm, pr: merge ready, pr: merge safe, target: patch

#15535 feat(bottom-sheet): allow for scroll strategy to be configured
  src/material/bottom-sheet/bottom-sheet-config.ts
  src/material/bottom-sheet/bottom-sheet.spec.ts
  src/material/bottom-sheet/bottom-sheet.ts
  tools/public_api_guard/material/bottom-sheet.d.ts
Labels: P4, cla: yes, pr: lgtm, pr: merge ready, target: minor

#16081 fix(drag-drop): error if drag sequence is started while another one is finishing
  src/cdk/drag-drop/directives/drag.spec.ts
  src/cdk/drag-drop/drag-ref.ts
Labels: P4, cla: yes, pr: lgtm, pr: merge ready, target: patch

#15149 feat(style): allow palettes to specify a separate hue for colored text
  src/material/button/_button-theme.scss
  src/material/core/option/_option-theme.scss
  src/material/core/theming/_theming.scss
  src/material/datepicker/_datepicker-theme.scss
  src/material/form-field/_form-field-theme.scss
  src/material/icon/_icon-theme.scss
  src/material/input/_input-theme.scss
  src/material/select/_select-theme.scss
  src/material/snack-bar/_snack-bar-theme.scss
  src/material/stepper/_stepper-theme.scss
Labels: P3, cla: yes, pr: lgtm, pr: merge ready, target: minor

#15923 fix(drag-n-drop): ignore consecutive touchmove events on drag item on multitouch
  src/cdk/drag-drop/directives/drag.spec.ts
  src/cdk/drag-drop/drag-drop-registry.spec.ts
  src/cdk/drag-drop/drag-drop-registry.ts
  src/cdk/drag-drop/drag-ref.ts
Labels: cla: yes, pr: lgtm, pr: merge ready, target: patch

#16164 refactor: remove calls to deprecated rxjs subscribe signature
  src/cdk/drag-drop/directives/drag.spec.ts
  src/cdk/drag-drop/drag-drop-registry.spec.ts
  src/cdk/layout/breakpoints-observer.spec.ts
  src/cdk/overlay/keyboard/overlay-keyboard-dispatcher.spec.ts
  src/cdk/overlay/overlay.spec.ts
  src/cdk/overlay/position/connected-position-strategy.spec.ts
  src/cdk/scrolling/scroll-dispatcher.spec.ts
  src/cdk/text-field/autofill.spec.ts
  src/material/chips/chip-list.spec.ts
  src/material/core/option/option.spec.ts
  src/material/datepicker/calendar.spec.ts
  src/material/menu/menu-trigger.ts
  src/material/snack-bar/snack-bar.spec.ts
  src/material/tooltip/tooltip.spec.ts
Labels: cla: yes, pr: lgtm, pr: merge ready, pr: merge safe, target: patch

#16177 fix(progress-spinner): non-default diameter indeterminate animation not working inside Shadow DOM
  src/material/progress-spinner/BUILD.bazel
  src/material/progress-spinner/progress-spinner.spec.ts
  src/material/progress-spinner/progress-spinner.ts
  src/material/progress-spinner/public-api.ts
Labels: G, P2, cla: yes, pr: lgtm, pr: merge ready, target: patch

#16019 fix(overlay): stop using capture phase for overlay keyboard handling
  src/cdk/overlay/keyboard/overlay-keyboard-dispatcher.spec.ts
  src/cdk/overlay/keyboard/overlay-keyboard-dispatcher.ts
Labels: P2, cla: yes, pr: lgtm, pr: merge ready, target: patch

#15811 feat(radio): add provider for default color input
  src/material/radio/radio.md
  src/material/radio/radio.spec.ts
  src/material/radio/radio.ts
  tools/public_api_guard/material/radio.d.ts
Labels: P2, cla: yes, pr: lgtm, pr: merge ready, target: minor

#16205 refactor(material): update repository name in tree generator schematic
  src/material/schematics/ng-generate/tree/files/__path__/__name@dasherize@if-flat__/example-data.ts
Labels: P4, cla: yes, pr: lgtm, pr: merge ready, pr: merge safe, target: patch

#16202 fix: prevent default on escape key presses
  src/cdk-experimental/dialog/dialog-ref.ts
  src/cdk-experimental/dialog/dialog.spec.ts
  src/cdk/overlay/overlay-directives.spec.ts
  src/cdk/overlay/overlay-directives.ts
  src/material-experimental/mdc-menu/menu.spec.ts
  src/material/bottom-sheet/bottom-sheet-ref.ts
  src/material/bottom-sheet/bottom-sheet.spec.ts
  src/material/datepicker/datepicker.spec.ts
  src/material/datepicker/datepicker.ts
  src/material/dialog/dialog-ref.ts
  src/material/dialog/dialog.spec.ts
  src/material/menu/menu.spec.ts
  src/material/menu/menu.ts
  src/material/sidenav/drawer.spec.ts
  src/material/sidenav/drawer.ts
  src/material/tooltip/tooltip.spec.ts
  src/material/tooltip/tooltip.ts
Labels: P3, cla: yes, pr: lgtm, pr: merge ready, target: patch

#15939 feat(popover-edit): Helper to reduce form state boilerplate
  src/cdk-experimental/popover-edit/form-value-container.ts
  src/cdk-experimental/popover-edit/popover-edit.spec.ts
  src/cdk-experimental/popover-edit/public-api.ts
  src/material-examples/popover-edit-mat-table/popover-edit-mat-table-example.html
  src/material-examples/popover-edit-mat-table/popover-edit-mat-table-example.ts
  src/material-experimental/popover-edit/popover-edit.spec.ts
Labels: cla: yes, pr: lgtm, pr: merge ready, pr: merge safe, target: patch

#16089 feat(cdk-experimental/testing): Bring in component harness
  .github/CODEOWNERS
  src/cdk-experimental/testing/BUILD.bazel
  src/cdk-experimental/testing/component-harness.ts
  src/cdk-experimental/testing/index.ts
  src/cdk-experimental/testing/protractor.ts
  src/cdk-experimental/testing/public-api.ts
  src/cdk-experimental/testing/test-element.ts
  src/cdk-experimental/testing/testbed.ts
  src/cdk-experimental/testing/tests/BUILD.bazel
  src/cdk-experimental/testing/tests/harnesses/main-component-harness.ts
  src/cdk-experimental/testing/tests/harnesses/sub-component-harness.ts
  src/cdk-experimental/testing/tests/index.ts
  src/cdk-experimental/testing/tests/protractor.e2e.spec.ts
  src/cdk-experimental/testing/tests/test-components-module.ts
  src/cdk-experimental/testing/tests/test-main-component.html
  src/cdk-experimental/testing/tests/test-main-component.ts
  src/cdk-experimental/testing/tests/test-sub-component.ts
  src/cdk-experimental/testing/tests/testbed.spec.ts
  src/cdk/testing/element-focus.ts
  src/e2e-app/BUILD.bazel
  src/e2e-app/component-harness/component-harness-e2e-module.ts
  src/e2e-app/component-harness/component-harness-e2e.ts
  src/e2e-app/e2e-app/e2e-app-layout.html
  src/e2e-app/e2e-app/routes.ts
  src/e2e-app/index.html
  src/e2e-app/main-module.ts
  test/karma-system-config.js
  tools/package-tools/rollup-globals.ts
Labels: cla: yes, pr: merge ready, pr: merge safe, target: patch

#15395 feat(common): Add dev-mode sanity check for mismatched versions of cdk and material
  src/cdk/tsconfig-tests.json
  src/material/core/BUILD.bazel
  src/material/core/common-behaviors/common-module.ts
  src/material/tsconfig-build.json
  src/material/tsconfig-tests.json
  src/material/tsconfig.json
  src/universal-app/tsconfig-prerender.json
Labels: P3, cla: yes, pr: lgtm, pr: merge ready, target: minor

#16188 build: publish-release script should run npm login before build
  tools/release/git/git-client.ts
  tools/release/publish-release.ts
  tools/release/stage-release.ts
  tools/release/version-name/parse-version.ts
Labels: P3, cla: yes, pr: lgtm, pr: merge ready, pr: merge safe, target: patch

#16204 fix(material): fix table generator schematic
  src/material/schematics/ng-generate/table/files/__path__/__name@dasherize@if-flat__/__name@dasherize__.component.ts
Labels: cla: yes, pr: lgtm, pr: merge ready, pr: merge safe, target: patch

#16218 fix(ng-update): parse cli workspace config as json5
  src/cdk/schematics/ng-update/upgrade-rules/project-tsconfig-paths.spec.ts
  src/cdk/schematics/ng-update/upgrade-rules/project-tsconfig-paths.ts
Labels: P3, cla: yes, pr: lgtm, pr: merge ready, pr: merge safe, target: patch

#16213 refactor(ng-generate): use .template suffix for schematic template files
  src/cdk/schematics/ng-add/index.spec.ts
  src/cdk/schematics/ng-add/index.ts
  src/cdk/schematics/ng-generate/drag-drop/files/__path__/__name@dasherize@if-flat__/__name@dasherize__.component.__style__.template
  src/cdk/schematics/ng-generate/drag-drop/files/__path__/__name@dasherize@if-flat__/__name@dasherize__.component.html.template
  src/cdk/schematics/ng-generate/drag-drop/files/__path__/__name@dasherize@if-flat__/__name@dasherize__.component.spec.ts.template
  src/cdk/schematics/ng-generate/drag-drop/files/__path__/__name@dasherize@if-flat__/__name@dasherize__.component.ts.template
  src/cdk/schematics/ng-generate/drag-drop/index.spec.ts
  src/cdk/schematics/ng-generate/drag-drop/index.ts
  src/cdk/schematics/ng-update/index.ts
  src/cdk/schematics/utils/build-component.ts
  src/material/schematics/ng-add/index.spec.ts
  src/material/schematics/ng-add/index.ts
  src/material/schematics/ng-generate/address-form/files/__path__/__name@dasherize@if-flat__/__name@dasherize__.component.__style__.template
  src/material/schematics/ng-generate/address-form/files/__path__/__name@dasherize@if-flat__/__name@dasherize__.component.html.template
  src/material/schematics/ng-generate/address-form/files/__path__/__name@dasherize@if-flat__/__name@dasherize__.component.spec.ts.template
  src/material/schematics/ng-generate/address-form/files/__path__/__name@dasherize@if-flat__/__name@dasherize__.component.ts.template
  src/material/schematics/ng-generate/address-form/index.spec.ts
  src/material/schematics/ng-generate/address-form/index.ts
  src/material/schematics/ng-generate/dashboard/files/__path__/__name@dasherize@if-flat__/__name@dasherize__.component.__style__.template
  src/material/schematics/ng-generate/dashboard/files/__path__/__name@dasherize@if-flat__/__name@dasherize__.component.html.template
  src/material/schematics/ng-generate/dashboard/files/__path__/__name@dasherize@if-flat__/__name@dasherize__.component.spec.ts.template
  src/material/schematics/ng-generate/dashboard/files/__path__/__name@dasherize@if-flat__/__name@dasherize__.component.ts.template
  src/material/schematics/ng-generate/dashboard/index.spec.ts
  src/material/schematics/ng-generate/dashboard/index.ts
  src/material/schematics/ng-generate/nav/files/__path__/__name@dasherize@if-flat__/__name@dasherize__.component.__style__.template
  src/material/schematics/ng-generate/nav/files/__path__/__name@dasherize@if-flat__/__name@dasherize__.component.html.template
  src/material/schematics/ng-generate/nav/files/__path__/__name@dasherize@if-flat__/__name@dasherize__.component.spec.ts.template
  src/material/schematics/ng-generate/nav/files/__path__/__name@dasherize@if-flat__/__name@dasherize__.component.ts.template
  src/material/schematics/ng-generate/nav/index.spec.ts
  src/material/schematics/ng-generate/nav/index.ts
  src/material/schematics/ng-generate/table/files/__path__/__name@dasherize@if-flat__/__name@dasherize__-datasource.ts.template
  src/material/schematics/ng-generate/table/files/__path__/__name@dasherize@if-flat__/__name@dasherize__.component.__style__.template
  src/material/schematics/ng-generate/table/files/__path__/__name@dasherize@if-flat__/__name@dasherize__.component.html.template
  src/material/schematics/ng-generate/table/files/__path__/__name@dasherize@if-flat__/__name@dasherize__.component.spec.ts.template
  src/material/schematics/ng-generate/table/files/__path__/__name@dasherize@if-flat__/__name@dasherize__.component.ts.template
  src/material/schematics/ng-generate/table/index.spec.ts
  src/material/schematics/ng-generate/table/index.ts
  src/material/schematics/ng-generate/tree/files/__path__/__name@dasherize@if-flat__/__name@dasherize__.component.__style__.template
  src/material/schematics/ng-generate/tree/files/__path__/__name@dasherize@if-flat__/__name@dasherize__.component.html.template
  src/material/schematics/ng-generate/tree/files/__path__/__name@dasherize@if-flat__/__name@dasherize__.component.spec.ts.template
  src/material/schematics/ng-generate/tree/files/__path__/__name@dasherize@if-flat__/__name@dasherize__.component.ts.template
  src/material/schematics/ng-generate/tree/files/__path__/__name@dasherize@if-flat__/example-data.ts.template
  src/material/schematics/ng-generate/tree/index.spec.ts
  src/material/schematics/ng-generate/tree/index.ts
  src/material/schematics/ng-update/index.ts
Labels: cla: yes, pr: lgtm, pr: merge ready, pr: merge safe, target: patch

#16118 feat(a11y): allow for element to be used as message in AriaDescriber
  src/cdk/a11y/aria-describer/aria-describer.spec.ts
  src/cdk/a11y/aria-describer/aria-describer.ts
  tools/public_api_guard/cdk/a11y.d.ts
Labels: G, P2, cla: yes, pr: lgtm, pr: merge ready, target: minor

#16137 fix(scrolling): virtual scroll throw off if directive injects ViewContainerRef
  src/cdk/scrolling/virtual-for-of.ts
  src/cdk/scrolling/virtual-scroll-viewport.spec.ts
Labels: G, P2, cla: yes, pr: lgtm, pr: merge ready, target: patch

#16219 docs: MatMenu api docs are not generated
  src/material/menu/menu.ts
  tools/dgeni/bazel-bin.ts
  tools/dgeni/common/dgeni-definitions.ts
  tools/dgeni/common/private-docs.ts
  tools/dgeni/docs-package.ts
  tools/dgeni/processors/categorizer.ts
  tools/dgeni/processors/docs-private-filter.ts
Labels: cla: yes, pr: lgtm, pr: merge ready, pr: merge safe, target: patch

#16233 chore: remove `indent_size = 2` from editorconfig as it messes up the continuation indent
  .editorconfig
Labels: cla: yes, pr: lgtm, pr: merge ready, pr: merge safe, target: patch

#16231 refactor(core): remove version placeholder workaround
  src/material/core/common-behaviors/common-module.ts
Labels: cla: yes, pr: lgtm, pr: merge ready, pr: merge safe, target: patch

#16242 chore: bump version to 8.0.1 w/ changelog
  CHANGELOG.md
  package.json
Labels: cla: yes, pr: lgtm, pr: merge ready, pr: merge safe, target: patch

#16246 Revert "refactor(core): remove version placeholder workaround"
  src/material/core/common-behaviors/common-module.ts
Labels: cla: yes

#16245 docs(radio): Correct providers syntax in default color configuration example
  src/material/radio/radio.md
Labels: cla: yes, pr: lgtm, pr: merge ready, pr: merge safe, target: patch

#16258 chore: bazel lint error message printing out wrong fix command
  scripts/circleci/lint-bazel-files.sh
Labels: cla: yes, pr: lgtm, pr: merge ready, pr: merge safe, target: patch

#16235 fix(overlay): incorrectly calculating position when page is scrolled horizontally and overlay is anchored to the right
  src/cdk/overlay/position/flexible-connected-position-strategy.spec.ts
  src/cdk/overlay/position/flexible-connected-position-strategy.ts
Labels: P2, cla: yes, pr: lgtm, pr: merge ready, target: patch

#16257 feat(expansion): allow expansion toggle indicator positioning
  src/dev-app/expansion/expansion-demo.html
  src/dev-app/expansion/expansion-demo.ts
  src/material/expansion/accordion-base.ts
  src/material/expansion/accordion.spec.ts
  src/material/expansion/accordion.ts
  src/material/expansion/expansion-panel-header.scss
  src/material/expansion/expansion-panel-header.ts
  src/material/expansion/expansion-panel.ts
  tools/public_api_guard/material/expansion.d.ts
Labels: P2, cla: yes, pr: lgtm, pr: merge ready, target: minor

#16270 chore: add scaffolding for mdc-based tabs
  .github/CODEOWNERS
  packages.bzl
  src/dev-app/BUILD.bazel
  src/dev-app/dev-app/dev-app-layout.ts
  src/dev-app/dev-app/routes.ts
  src/dev-app/mdc-tabs/mdc-tabs-demo-module.ts
  src/dev-app/mdc-tabs/mdc-tabs-demo.html
  src/dev-app/mdc-tabs/mdc-tabs-demo.scss
  src/dev-app/mdc-tabs/mdc-tabs-demo.ts
  src/dev-app/system-config.ts
  src/dev-app/theme.scss
  src/e2e-app/BUILD.bazel
  src/e2e-app/e2e-app/e2e-app-layout.html
  src/e2e-app/e2e-app/routes.ts
  src/e2e-app/main-module.ts
  src/e2e-app/mdc-tabs/mdc-tabs-e2e-module.ts
  src/e2e-app/mdc-tabs/mdc-tabs-e2e.html
  src/e2e-app/mdc-tabs/mdc-tabs-e2e.ts
  src/e2e-app/theme.scss
  src/material-experimental/mdc-tabs/BUILD.bazel
  src/material-experimental/mdc-tabs/README.md
  src/material-experimental/mdc-tabs/_mdc-tabs.scss
  src/material-experimental/mdc-tabs/index.ts
  src/material-experimental/mdc-tabs/module.ts
  src/material-experimental/mdc-tabs/public-api.ts
  src/material-experimental/mdc-tabs/tabs.e2e.spec.ts
  src/material-experimental/mdc-tabs/tabs.scss
  src/material-experimental/mdc-tabs/tabs.spec.ts
  src/material-experimental/mdc-tabs/tsconfig-build.json
  src/universal-app/kitchen-sink-mdc/kitchen-sink-mdc.ts
  src/universal-app/theme.scss
  test/karma-system-config.js
Labels: P3, cla: yes, pr: lgtm, pr: merge ready, pr: merge safe, target: patch

#16221 fix(dialog): not moving focus to container if autoFocus is disabled and focus was moved from a different component
  src/material/dialog/dialog-container.ts
Labels: P2, cla: yes, pr: lgtm, pr: merge ready, target: patch

#11538 fix(card): disable all animations when using NoopAnimationsModule
  src/material/card/card.scss
  src/material/card/card.ts
  tools/public_api_guard/material/card.d.ts
Labels: G, P3, cla: yes, pr: lgtm, pr: merge ready, target: minor

#16262 build: option to ignore ci checks when staging release
  tools/release/stage-release.ts
Labels: cla: yes, pr: lgtm, pr: merge ready, pr: merge safe, target: patch

#16272 Spell Mistake | Bug
  guides/getting-started.md
Labels: cla: yes, commit message fixup, docs, pr: lgtm, pr: merge ready, pr: merge safe

#16260 build: update yarn to v1.16.0
  .circleci/config.yml
  WORKSPACE
  package.json
Labels: cla: yes, pr: lgtm, pr: merge ready, pr: merge safe, target: patch

#16277 chore: update marked
  package.json
  yarn.lock
Labels: cla: yes, pr: lgtm, pr: merge ready, pr: merge safe, target: patch

#16281 fix(popover-edit): remove fallthroughs in switch statement
  src/cdk-experimental/popover-edit/lens-directives.ts
Labels: cla: yes, pr: lgtm, pr: merge ready, pr: merge safe, target: patch

#16282 chore: enable noFallthroughCasesInSwitch in the project's tsconfigs
  src/bazel-tsconfig-build.json
  tsconfig.json
Labels: cla: yes, pr: lgtm, pr: merge ready, pr: merge safe, target: patch

#11546 fix(chips): disable all animations when using NoopAnimationsModule
  src/material/chips/chip.ts
  src/material/chips/chips.scss
  tools/public_api_guard/material/chips.d.ts
Labels: G, P3, cla: yes, pr: lgtm, pr: merge ready, target: patch

#11395 fix(tabs): disable all animations when using NoopAnimationsModule
  src/material/tabs/_tabs-common.scss
  src/material/tabs/ink-bar.ts
  src/material/tabs/tab-group.html
  src/material/tabs/tab-group.scss
  src/material/tabs/tab-group.ts
  src/material/tabs/tab-header.html
  src/material/tabs/tab-header.scss
  src/material/tabs/tab-header.ts
  src/material/tabs/tab-nav-bar/tab-nav-bar.ts
  tools/public_api_guard/material/tabs.d.ts
Labels: G, P3, cla: yes, pr: lgtm, pr: merge ready, target: patch

#16018 feat(datepicker): align multi-year-view based on minDate and maxDate
  src/material/datepicker/calendar-header.spec.ts
  src/material/datepicker/calendar.ts
  src/material/datepicker/multi-year-view.spec.ts
  src/material/datepicker/multi-year-view.ts
  src/material/datepicker/public-api.ts
Labels: P4, cla: yes, pr: lgtm, pr: merge ready, target: patch

#15985 chore: fix misspelled aria-labelledby in public API description
  src/material-experimental/mdc-checkbox/checkbox.ts
  src/material/button-toggle/button-toggle.ts
  src/material/checkbox/checkbox.ts
Labels: cla: yes, commit message fixup, pr: lgtm, pr: merge ready, pr: merge safe, target: patch

#16321 chore: temporarily disable ivy_snapshot_test_cronjob on CircleCI
  .circleci/config.yml
Labels: cla: yes, pr: merge ready, pr: merge safe, target: patch

#16323 fix(experimental/dialog): set aria-modal on dialog container
  src/cdk-experimental/dialog/dialog-container.ts
  src/cdk-experimental/dialog/dialog.spec.ts
Labels: P3, cla: yes, pr: lgtm, pr: merge ready, pr: merge safe, target: patch

#16159 fix(checkbox): hover indication showing when disabled
  src/material/checkbox/checkbox.scss
Labels: P3, cla: yes, pr: lgtm, pr: merge ready, target: patch

#16129 refactor(mdc-prototypes): do not mark components dirty in input setters
  src/material-experimental/mdc-checkbox/checkbox.spec.ts
  src/material-experimental/mdc-checkbox/checkbox.ts
  src/material-experimental/mdc-slide-toggle/slide-toggle.spec.ts
  src/material-experimental/mdc-slide-toggle/slide-toggle.ts
Labels: P3, cla: yes, pr: lgtm, pr: merge ready, pr: merge safe, target: patch

#16080 fix(list): matching item not preselected if added after init
  src/material/list/selection-list.spec.ts
  src/material/list/selection-list.ts
  tools/public_api_guard/material/list.d.ts
Labels: P3, cla: yes, pr: lgtm, pr: merge ready, target: patch

#16082 perf(drag-drop): use narrower check for touch events
  src/cdk/drag-drop/drag-ref.ts
Labels: cla: yes, pr: lgtm, pr: merge ready, target: patch

#16122 fix(expansion-panel): header animating on init when using non-default height
  src/material/expansion/expansion-panel-header.ts
  tools/public_api_guard/material/expansion.d.ts
Labels: P4, cla: yes, pr: lgtm, pr: merge ready, target: patch

#16056 fix(button): avoid direct access to nativeElement for consistency
  src/material/button/button.ts
Labels: cla: yes, commit message fixup, pr: lgtm, pr: merge ready, target: patch

#15364 fix(autocomplete): alt + up arrow to close panel not working
  src/material/autocomplete/autocomplete-trigger.ts
  src/material/autocomplete/autocomplete.spec.ts
Labels: a11y, cla: yes, pr: lgtm, pr: merge ready, target: patch

#16319 feat(cdk-experimental/testing): Adds a `HarnessPredicate` class
  src/cdk-experimental/testing/component-harness.ts
  src/cdk-experimental/testing/harness-environment.ts
  src/cdk-experimental/testing/protractor/protractor-harness-environment.ts
  src/cdk-experimental/testing/testbed/testbed-harness-environment.ts
  src/cdk-experimental/testing/tests/harnesses/main-component-harness.ts
  src/cdk-experimental/testing/tests/harnesses/sub-component-harness.ts
  src/cdk-experimental/testing/tests/protractor.e2e.spec.ts
  src/cdk-experimental/testing/tests/test-main-component.ts
  src/cdk-experimental/testing/tests/testbed.spec.ts
Labels: cla: yes, pr: lgtm, pr: merge ready, pr: merge safe, target: patch

#16329 Fix wrong autocomplete-plain-input example (fixes #16327)
  src/material-examples/autocomplete-plain-input/autocomplete-plain-input-example.ts
  src/material-examples/example-module.ts
Labels: cla: yes, pr: lgtm, pr: merge ready, pr: merge safe, target: patch

#16359 chore: use correct StackBlitz template in README
  README.md
Labels: cla: yes, docs, pr: lgtm, pr: merge ready, pr: merge safe

#16358 build: re-enable cronjob snapshot test
  .circleci/config.yml
Labels: cla: yes, pr: lgtm, pr: merge ready, pr: merge safe, target: patch

#16291 docs(form-field): fix link
  src/material/form-field/form-field.md
Labels: cla: yes, pr: lgtm, pr: merge ready, pr: merge safe, target: patch

#16211 style(progress-spinner): move private var to beginning of class
  src/material/progress-spinner/progress-spinner.ts
Labels: cla: yes, pr: lgtm, pr: merge ready, target: patch

#16361 build: use bazel from node modules
  .circleci/config.yml
  scripts/circleci/bazel/setup-remote-execution.sh
  scripts/circleci/setup-angular-snapshots.js
  scripts/circleci/setup-angular-snapshots.py
  scripts/deploy/publish-docs-content.sh
Labels: cla: yes, pr: lgtm, pr: merge ready, pr: merge safe, target: patch

#16362 build: fix snapshot local browsers cronjob test
  .circleci/config.yml
Labels: cla: yes, pr: lgtm, pr: merge ready, pr: merge safe, target: patch

#16365 chore: bump linter versions
  package.json
  yarn.lock
Labels: cla: yes, pr: lgtm, pr: merge ready, pr: merge safe, target: patch

#16363 feat(schematics): add font-display query
  src/material/schematics/ng-add/fonts/material-fonts.ts
  src/material/schematics/ng-add/index.spec.ts
Labels: cla: yes, pr: lgtm, pr: merge ready, pr: merge safe, target: minor

#16370 build: setup RBE caching and remote build event service on CI
  .circleci/base-rbe-bazelrc
  .circleci/bazel.rc
  scripts/circleci/bazel/setup-remote-execution.sh
Labels: cla: yes, pr: lgtm, pr: merge ready, pr: merge safe, target: patch

#16145 prototype(chips): MDC chip APIs match existing APIs
  package.json
  src/dev-app/mdc-chips/mdc-chips-demo-module.ts
  src/dev-app/mdc-chips/mdc-chips-demo.html
  src/dev-app/mdc-chips/mdc-chips-demo.scss
  src/dev-app/mdc-chips/mdc-chips-demo.ts
  src/material-examples/example-module.ts
  src/material-experimental/mdc-chips/BUILD.bazel
  src/material-experimental/mdc-chips/_mdc-chips.scss
  src/material-experimental/mdc-chips/chip-cell.ts
  src/material-experimental/mdc-chips/chip-default-options.ts
  src/material-experimental/mdc-chips/chip-grid.html
  src/material-experimental/mdc-chips/chip-grid.ts
  src/material-experimental/mdc-chips/chip-input.ts
  src/material-experimental/mdc-chips/chip-listbox.ts
  src/material-experimental/mdc-chips/chip-option.html
  src/material-experimental/mdc-chips/chip-option.ts
  src/material-experimental/mdc-chips/chip-row.html
  src/material-experimental/mdc-chips/chip-row.ts
  src/material-experimental/mdc-chips/chip-set.ts
  src/material-experimental/mdc-chips/chip-text-control.ts
  src/material-experimental/mdc-chips/chip.html
  src/material-experimental/mdc-chips/chip.ts
  src/material-experimental/mdc-chips/chips.scss
  src/material-experimental/mdc-chips/module.ts
  src/material-experimental/mdc-chips/public-api.ts
  yarn.lock
Labels: cla: yes, pr: lgtm, pr: merge ready, pr: merge safe, target: minor

#16349 fix(bottom-sheet): DOM nodes not cleaned up if view container is destroyed mid-animation
  src/material/bottom-sheet/bottom-sheet-ref.ts
  src/material/bottom-sheet/bottom-sheet.spec.ts
Labels: P3, cla: yes, pr: lgtm, pr: merge ready, target: patch

#16309 fix(dialog): DOM nodes not cleaned up if view container is destroyed mid-animation
  src/material/dialog/dialog-ref.ts
  src/material/dialog/dialog.spec.ts
Labels: P3, cla: yes, pr: lgtm, pr: merge ready, target: patch

#16268 fix(overlay): events not being unbound from destroyed backdrop
  src/cdk/overlay/overlay-ref.ts
  src/cdk/overlay/overlay.spec.ts
Labels: P3, cla: yes, pr: lgtm, pr: merge ready, target: patch

#15964 fix(breakpoint-observer): fix the breakpoint observer emit count and accuracy
  src/cdk/layout/breakpoints-observer.spec.ts
  src/cdk/layout/breakpoints-observer.ts
Labels: P3, cla: yes, pr: lgtm, pr: merge ready, target: patch

#16379 build: run CI unit tests using bazel
  .circleci/config.yml
  package.json
  tools/defaults.bzl
Labels: caretaker note, cla: yes, pr: lgtm, pr: merge ready, pr: merge safe, target: patch

#16381 fix(ng-update): do not rely on node-glob for finding rule directories
  src/cdk/schematics/ng-update/upgrade-rules/tslint-config.ts
  src/material/schematics/ng-update/index.ts
Labels: cla: yes, pr: lgtm, pr: merge ready, pr: merge safe, target: patch

#16376 build: mark all e2e test suites as flaky within bazel
  src/cdk-experimental/scrolling/BUILD.bazel
  src/cdk-experimental/testing/BUILD.bazel
  src/cdk/overlay/BUILD.bazel
  src/material-experimental/mdc-button/BUILD.bazel
  src/material-experimental/mdc-card/BUILD.bazel
  src/material-experimental/mdc-checkbox/BUILD.bazel
  src/material-experimental/mdc-chips/BUILD.bazel
  src/material-experimental/mdc-menu/BUILD.bazel
  src/material-experimental/mdc-radio/BUILD.bazel
  src/material-experimental/mdc-slide-toggle/BUILD.bazel
  src/material-experimental/mdc-tabs/BUILD.bazel
  src/material/button-toggle/BUILD.bazel
  src/material/button/BUILD.bazel
  src/material/card/BUILD.bazel
  src/material/checkbox/BUILD.bazel
  src/material/dialog/BUILD.bazel
  src/material/expansion/BUILD.bazel
  src/material/grid-list/BUILD.bazel
  src/material/icon/BUILD.bazel
  src/material/input/BUILD.bazel
  src/material/list/BUILD.bazel
  src/material/menu/BUILD.bazel
  src/material/progress-bar/BUILD.bazel
  src/material/progress-spinner/BUILD.bazel
  src/material/radio/BUILD.bazel
  src/material/sidenav/BUILD.bazel
  src/material/slide-toggle/BUILD.bazel
  src/material/stepper/BUILD.bazel
  src/material/tabs/BUILD.bazel
  src/material/toolbar/BUILD.bazel
  tools/defaults.bzl
Labels: cla: yes, pr: lgtm, pr: merge ready, pr: merge safe, target: patch

#16375 build: create script for setting up RBE in local dev environment
  .bazelrc
  .circleci/base-rbe-bazelrc
  .circleci/bazel.rc
  .gitignore
  scripts/local-dev/setup-rbe.sh
Labels: cla: yes, pr: lgtm, pr: merge ready, pr: merge safe, target: patch

#16297 fix(dialog): don't move focus to dialog container if focus is already inside the dialog
  src/material/dialog/dialog-container.ts
Labels: G, P2, cla: yes, pr: lgtm, pr: merge ready, target: patch

#16394 ci: update required statuses for PRs
  .github/angular-robot.yml
Labels: cla: yes, pr: merge ready, target: patch

#16055 feat(tabs): support pagination in nav bar
  src/material-examples/tab-nav-bar-basic/tab-nav-bar-basic-example.css
  src/material-examples/tab-nav-bar-basic/tab-nav-bar-basic-example.html
  src/material-examples/tab-nav-bar-basic/tab-nav-bar-basic-example.ts
  src/material/tabs/_tabs-common.scss
  src/material/tabs/_tabs-theme.scss
  src/material/tabs/paginated-tab-header.ts
  src/material/tabs/public-api.ts
  src/material/tabs/tab-header.html
  src/material/tabs/tab-header.scss
  src/material/tabs/tab-header.ts
  src/material/tabs/tab-nav-bar/tab-nav-bar.html
  src/material/tabs/tab-nav-bar/tab-nav-bar.scss
  src/material/tabs/tab-nav-bar/tab-nav-bar.spec.ts
  src/material/tabs/tab-nav-bar/tab-nav-bar.ts
  tools/public_api_guard/material/tabs.d.ts
Labels: P2, cla: yes, pr: lgtm, pr: merge ready, target: minor

#16384 feature(material-experimental/chips) Add grid keyboard shortcuts
  src/material-experimental/mdc-chips/chip-default-options.ts
  src/material-experimental/mdc-chips/chip-grid.ts
  src/material-experimental/mdc-chips/chip-icons.ts
  src/material-experimental/mdc-chips/chip-input.ts
  src/material-experimental/mdc-chips/chip-listbox.ts
  src/material-experimental/mdc-chips/chip-option.ts
  src/material-experimental/mdc-chips/chip-row.html
  src/material-experimental/mdc-chips/chip-row.ts
  src/material-experimental/mdc-chips/chip-set.ts
  src/material-experimental/mdc-chips/chip.ts
  src/material-experimental/mdc-chips/chips.scss
  src/material-experimental/mdc-chips/grid-focus-key-manager.ts
  src/material-experimental/mdc-chips/grid-key-manager.ts
  src/material-experimental/mdc-chips/module.ts
  src/material-experimental/mdc-chips/public-api.ts
Labels: cla: yes, pr: lgtm, pr: merge ready, pr: merge safe, target: minor
