Repository angular/components, pull requests merged in 2019-08, with the labels that each got.

#16625 test(sidenav): refactor flaky tests in Edge
  src/material/sidenav/drawer.spec.ts
Labels: P2, cla: yes, pr: lgtm, pr: merge ready, pr: merge safe, target: patch

#16670 fix(material-experimental/mdc-chips): prevent ripple from escaping chip
  src/material-experimental/mdc-chips/chips.scss
Labels: cla: yes, pr: lgtm, pr: merge ready, pr: merge safe, target: patch

#16619 feat(material-experimental): add progress bar test harness skeleton
  .github/CODEOWNERS
  src/material-experimental/mdc-progress-bar/BUILD.bazel
  src/material-experimental/mdc-progress-bar/harness/progress-bar-harness.spec.ts
  src/material-experimental/mdc-progress-bar/harness/progress-bar-harness.ts
Labels: P3, cla: yes, pr: lgtm, pr: merge ready, pr: merge safe, target: patch

#16655 build: add API goldens for portal
  src/cdk/portal/dom-portal-outlet.ts
  src/cdk/portal/portal-directives.ts
  src/cdk/portal/portal.ts
  src/cdk/portal/public-api.ts
  tools/public_api_guard/BUILD.bazel
  tools/public_api_guard/cdk/portal.d.ts
Labels: P2, cla: yes, pr: lgtm, pr: merge ready, pr: merge safe, target: patch

#16622 feat(material-experimental): add progress spinner test harness skeleton
  .github/CODEOWNERS
  src/material-experimental/mdc-progress-spinner/BUILD.bazel
  src/material-experimental/mdc-progress-spinner/harness/progress-spinner-harness.spec.ts
  src/material-experimental/mdc-progress-spinner/harness/progress-spinner-harness.ts
Labels: P3, cla: yes, pr: lgtm, pr: merge ready, pr: merge safe, target: patch

#16673 fix(material-experimental): typo in harness focus methods
  src/material-experimental/mdc-button/harness/button-harness.spec.ts
  src/material-experimental/mdc-button/harness/button-harness.ts
  src/material-experimental/mdc-button/harness/mdc-button-harness.ts
  src/material-experimental/mdc-checkbox/harness/checkbox-harness.spec.ts
  src/material-experimental/mdc-checkbox/harness/checkbox-harness.ts
  src/material-experimental/mdc-checkbox/harness/mdc-checkbox-harness.ts
  src/material-experimental/mdc-slide-toggle/harness/mdc-slide-toggle-harness.ts
  src/material-experimental/mdc-slide-toggle/harness/slide-toggle-harness.spec.ts
  src/material-experimental/mdc-slide-toggle/harness/slide-toggle-harness.ts
Labels: cla: yes, pr: lgtm, pr: merge ready, pr: merge safe, target: patch

#16703 Revert "build: add API goldens for portal"
  src/cdk/portal/dom-portal-outlet.ts
  src/cdk/portal/portal-directives.ts
  src/cdk/portal/portal.ts
  src/cdk/portal/public-api.ts
  tools/public_api_guard/BUILD.bazel
  tools/public_api_guard/cdk/portal.d.ts
Labels: cla: yes

#16462 feat(moment-date-adapter): implement strict mode
  src/material-moment-adapter/adapter/moment-date-adapter.spec.ts
  src/material-moment-adapter/adapter/moment-date-adapter.ts
  src/material/datepicker/datepicker.md
Labels: cla: yes, feature, pr: lgtm, pr: merge ready, pr: merge safe, target: minor

#14184 refactor: allow options to be passed to focus methods
  src/material/button-toggle/button-toggle.ts
  src/material/button/button.ts
  src/material/checkbox/checkbox.ts
  src/material/chips/chip-input.ts
  src/material/chips/chip-list.ts
  src/material/chips/chip-text-control.ts
  src/material/core/option/option.ts
  src/material/expansion/expansion-panel-header.ts
  src/material/input/input.ts
  src/material/list/selection-list.ts
  src/material/menu/menu-item.ts
  src/material/menu/menu-trigger.ts
  src/material/radio/radio.ts
  src/material/select/select.ts
  src/material/slide-toggle/slide-toggle.ts
  src/material/slider/slider.ts
  tools/public_api_guard/material/button-toggle.d.ts
  tools/public_api_guard/material/button.d.ts
  tools/public_api_guard/material/checkbox.d.ts
  tools/public_api_guard/material/chips.d.ts
  tools/public_api_guard/material/core.d.ts
  tools/public_api_guard/material/expansion.d.ts
  tools/public_api_guard/material/input.d.ts
  tools/public_api_guard/material/list.d.ts
  tools/public_api_guard/material/menu.d.ts
  tools/public_api_guard/material/radio.d.ts
  tools/public_api_guard/material/select.d.ts
  tools/public_api_guard/material/slide-toggle.d.ts
  tools/public_api_guard/material/slider.d.ts
Labels: G, P2, cla: yes, pr: lgtm, pr: merge ready, target: patch

#16712 fix(material-experimental/mdc-chips): ripple not being clipped in Safari
  src/material-experimental/mdc-chips/chips.scss
Labels: P3, cla: yes, pr: merge safe, target: patch

#16713 build: remove staticQueryRule
  tools/tslint-rules/staticQueryRule.ts
  tslint.json
Labels: P3, cla: yes, pr: lgtm, pr: merge ready, pr: merge safe

#16689 DatePicker: update names of weekdays in month view on init
  src/material/datepicker/month-view.ts
Labels: P3, cla: yes, pr: lgtm, pr: merge ready, target: patch

#16722 fix(material-experimental/mdc-chips): incorrect selector for mdc-chip-avatar
  src/material-experimental/mdc-chips/chip-option.html
  src/material-experimental/mdc-chips/chip-row.html
  src/material-experimental/mdc-chips/chip.html
Labels: P3, cla: yes, commit message fixup, pr: lgtm, pr: merge ready, pr: merge safe, target: patch

#16637 chore: add script to pull commits to cherrypick
  package.json
  tools/cherry-pick-patch/cherry-pick-patch.ts
  tools/cherry-pick-patch/get-merged-pull-requests.ts
  tools/cherry-pick-patch/github.ts
  tools/cherry-pick-patch/output-results.ts
  tools/cherry-pick-patch/prompt.ts
  tools/cherry-pick-patch/tsconfig.json
  yarn.lock
Labels: cla: yes, pr: lgtm, pr: merge ready, pr: merge safe

#16623 feat(google-maps): add google-map component
  .github/CODEOWNERS
  package.json
  packages.bzl
  src/dev-app/BUILD.bazel
  src/dev-app/dev-app/dev-app-layout.ts
  src/dev-app/dev-app/routes.ts
  src/dev-app/google-map/google-map-demo-module.ts
  src/dev-app/google-map/google-map-demo.html
  src/dev-app/google-map/google-map-demo.ts
  src/dev-app/system-config.ts
  src/dev-app/tsconfig-aot.json
  src/dev-app/tsconfig-build.json
  src/dev-app/tsconfig.json
  src/google-maps/BUILD.bazel
  src/google-maps/README.md
  src/google-maps/google-map/BUILD.bazel
  src/google-maps/google-map/google-map-module.ts
  src/google-maps/google-map/google-map.md
  src/google-maps/google-map/google-map.spec.ts
  src/google-maps/google-map/google-map.ts
  src/google-maps/google-map/index.ts
  src/google-maps/google-map/public-api.ts
  src/google-maps/google-map/testing/BUILD.bazel
  src/google-maps/google-map/testing/fake-google-map-utils.ts
  src/google-maps/google-map/tsconfig-build.json
  src/google-maps/index.ts
  src/google-maps/package.json
  src/google-maps/public-api.ts
  src/google-maps/tsconfig-build.json
  src/google-maps/tsconfig-tests.json
  src/google-maps/tsconfig.json
  src/google-maps/typings.d.ts
  tools/gulp/gulpfile.ts
  tools/gulp/packages.ts
  tools/gulp/tasks/aot.ts
  tools/gulp/tasks/development.ts
  tools/gulp/tasks/unit-test.ts
  tools/gulp/tasks/universal.ts
  tools/package-tools/build-release.ts
  tools/package-tools/rollup-globals.ts
  tools/release/release-output/release-packages.ts
  yarn.lock
Labels: G, cla: yes, new component, pr: lgtm, pr: merge ready, pr: merge safe, target: minor

#16645 feat(cdk-experimental/testing): Improve keyboard event support in harnesses
  src/cdk-experimental/dialog/dialog.spec.ts
  src/cdk-experimental/popover-edit/popover-edit.spec.ts
  src/cdk-experimental/testing/BUILD.bazel
  src/cdk-experimental/testing/protractor/BUILD.bazel
  src/cdk-experimental/testing/protractor/protractor-element.ts
  src/cdk-experimental/testing/test-element.ts
  src/cdk-experimental/testing/testbed/BUILD.bazel
  src/cdk-experimental/testing/testbed/unit-test-element.ts
  src/cdk-experimental/testing/tests/BUILD.bazel
  src/cdk-experimental/testing/tests/harnesses/main-component-harness.ts
  src/cdk-experimental/testing/tests/protractor.e2e.spec.ts
  src/cdk-experimental/testing/tests/test-main-component.html
  src/cdk-experimental/testing/tests/test-main-component.ts
  src/cdk-experimental/testing/tests/testbed.spec.ts
  src/cdk/a11y/key-manager/list-key-manager.spec.ts
  src/cdk/keycodes/modifiers.spec.ts
  src/cdk/overlay/keyboard/overlay-keyboard-dispatcher.spec.ts
  src/cdk/testing/dispatch-events.ts
  src/cdk/testing/event-objects.ts
  src/cdk/testing/type-in-element.ts
  src/material-experimental/mdc-chips/chip-grid.spec.ts
  src/material-experimental/mdc-chips/chip-input.spec.ts
  src/material-experimental/mdc-chips/chip-listbox.spec.ts
  src/material-experimental/popover-edit/popover-edit.spec.ts
  src/material/autocomplete/autocomplete.spec.ts
  src/material/bottom-sheet/bottom-sheet.spec.ts
  src/material/chips/chip-input.spec.ts
  src/material/chips/chip-list.spec.ts
  src/material/dialog/dialog.spec.ts
  src/material/list/selection-list.spec.ts
  src/material/select/select.spec.ts
  tools/public_api_guard/cdk/testing.d.ts
Labels: P2, cla: yes, pr: lgtm, pr: merge ready, pr: merge safe, target: patch

#16269 fix(cdk/virtual-scroll): fix subpixel rounding errors on hdpi screens
  src/cdk/scrolling/virtual-scroll-viewport.html
  src/cdk/scrolling/virtual-scroll-viewport.ts
  tools/public_api_guard/cdk/scrolling.d.ts
Labels: G, P3, cla: yes, pr: lgtm, pr: merge ready, target: patch

#16758 build: do not run ngc postinstall on schematics
  angular-tsconfig.json
Labels: P2, cla: yes, pr: merge safe, target: patch

#16724 Update MDC to latest alpha
  package.json
  src/material-experimental/mdc-chips/chip-grid.ts
  src/material-experimental/mdc-chips/chip-icons.ts
  src/material-experimental/mdc-chips/chip-listbox.ts
  src/material-experimental/mdc-chips/chip-set.ts
  src/material-experimental/mdc-chips/chip.html
  src/material-experimental/mdc-chips/chip.ts
  src/material-experimental/mdc-helpers/BUILD.bazel
  yarn.lock
Labels: cla: yes, pr: lgtm, pr: merge ready, target: patch

#16678 build: update to 8.2.0 and TypeScript 3.5.3
  .circleci/config.yml
  package.json
  src/cdk/schematics/ng-update/upgrade-data.ts
  src/cdk/schematics/utils/ast.ts
  src/cdk/schematics/utils/build-component.ts
  src/material/sidenav/drawer.ts
  src/material/tabs/tab-group.ts
  tools/public_api_guard/material/sidenav.d.ts
  tools/public_api_guard/material/tabs.d.ts
  yarn.lock
Labels: P2, cla: yes, pr: lgtm, pr: merge ready, target: patch

#16244 feat(form-field): allow hideRequiredMarker default value to be configured
  src/material/form-field/form-field.ts
  src/material/input/input.spec.ts
  tools/public_api_guard/material/form-field.d.ts
Labels: G, P3, cla: yes, pr: lgtm, pr: merge ready, target: minor

#16672 build: enable noImplicitReturns compiler option
  src/bazel-tsconfig-build.json
  src/cdk/overlay/position/flexible-connected-position-strategy.ts
  src/cdk/schematics/tsconfig.json
  src/cdk/tree/nested-node.ts
  src/dev-app/tsconfig-aot.json
  src/dev-app/tsconfig-build.json
  src/material-examples/tsconfig-build.json
  src/material-moment-adapter/tsconfig-build.json
  src/material/progress-bar/progress-bar.ts
  src/material/schematics/tsconfig.json
  src/universal-app/tsconfig-build.json
  src/universal-app/tsconfig-prerender.json
  tools/dgeni/common/decorators.ts
  tools/dgeni/common/property-bindings.ts
  tools/dgeni/tsconfig.json
  tools/gulp/tsconfig.json
  tools/package-tools/build-bundles.ts
  tsconfig.json
Labels: G, P2, cla: yes, pr: lgtm, pr: merge ready, target: patch

#16764 build: fix bazel not available if cache could not be restored
  .circleci/config.yml
Labels: cla: yes, pr: lgtm, pr: merge ready, pr: merge safe, target: patch

#16763 build: update to angular v8.2.2
  WORKSPACE
  package.json
  yarn.lock
Labels: cla: yes, pr: lgtm, pr: merge ready, pr: merge safe, target: patch

#16662 feat(material-experimental): add option to filter checkbox harnesses by name
  src/material-experimental/mdc-checkbox/harness/checkbox-harness-filters.ts
  src/material-experimental/mdc-checkbox/harness/checkbox-harness.spec.ts
  src/material-experimental/mdc-checkbox/harness/checkbox-harness.ts
  src/material-experimental/mdc-checkbox/harness/mdc-checkbox-harness.ts
Labels: cla: yes, pr: lgtm, pr: merge ready, pr: merge safe, target: patch

#16767 feat(material-experimental/mdc-button): add component classnames per variant
  src/material-experimental/mdc-button/button-base.ts
Labels: P3, cla: yes, pr: lgtm, pr: merge ready, pr: merge safe, target: patch

#16770 Revert "Update MDC to latest alpha (#16724)"
  package.json
  src/material-experimental/mdc-chips/chip-grid.ts
  src/material-experimental/mdc-chips/chip-icons.ts
  src/material-experimental/mdc-chips/chip-listbox.ts
  src/material-experimental/mdc-chips/chip-set.ts
  src/material-experimental/mdc-chips/chip.html
  src/material-experimental/mdc-chips/chip.ts
  src/material-experimental/mdc-helpers/BUILD.bazel
  yarn.lock
Labels: cla: yes, pr: lgtm, pr: merge ready, pr: merge safe, target: patch

#16733 feat(youtube-player): Add outputs that are proxies from the embed API.
  src/youtube-player/fake-youtube-player.ts
  src/youtube-player/youtube-player.spec.ts
  src/youtube-player/youtube-player.ts
Labels: cla: yes, pr: lgtm, pr: merge ready, pr: merge safe, target: minor

#16704 feat(material-experimental): add Clipboard service and directive.
  src/cdk-experimental/clipboard/BUILD.bazel
  src/cdk-experimental/clipboard/clipboard-module.ts
  src/cdk-experimental/clipboard/clipboard.spec.ts
  src/cdk-experimental/clipboard/clipboard.ts
  src/cdk-experimental/clipboard/copy-to-clipboard.spec.ts
  src/cdk-experimental/clipboard/copy-to-clipboard.ts
Labels: cla: yes, commit message fixup, pr: lgtm, pr: merge ready, pr: merge safe, target: patch

#16747 fix(popover-edit): prevent default escape action
  src/cdk-experimental/popover-edit/lens-directives.ts
  src/cdk-experimental/popover-edit/popover-edit.spec.ts
  src/material-experimental/popover-edit/popover-edit.spec.ts
Labels: P3, cla: yes, pr: lgtm, pr: merge ready, pr: merge safe, target: patch

#16771 chore: update MatMenu _hovered typing for rxjs 7
  package.json
  src/material/menu/menu.ts
  yarn.lock
Labels: P3, cla: yes, pr: lgtm, pr: merge ready, target: patch

#16615 feat(material-experimental): add menu test harness skeleton
  src/material-experimental/mdc-menu/BUILD.bazel
  src/material-experimental/mdc-menu/harness/mdc-menu-harness.ts
  src/material-experimental/mdc-menu/harness/mdc-menu-item-harness.ts
  src/material-experimental/mdc-menu/harness/menu-harness-filters.ts
  src/material-experimental/mdc-menu/harness/menu-harness.spec.ts
  src/material-experimental/mdc-menu/harness/menu-harness.ts
  src/material-experimental/mdc-menu/harness/menu-item-harness.ts
  src/material-experimental/tsconfig.json
  src/material/menu/menu-trigger.ts
Labels: cla: yes, pr: lgtm, pr: merge ready, pr: merge safe, target: patch

#16782 feat(material-experimental/mdc-button): support primary/accent/warn
  src/material-experimental/mdc-button/_mdc-button.scss
  src/material-experimental/mdc-button/button-base.ts
Labels: P3, cla: yes, pr: lgtm, pr: merge ready, pr: merge safe, target: patch

#16768 feat(material-experimental/mdc-button): use MDC classnames in CSS
  src/material-experimental/mdc-button/button.scss
  src/material-experimental/mdc-button/fab.scss
  src/material-experimental/mdc-button/icon-button.scss
Labels: P3, cla: yes, pr: lgtm, pr: merge ready, pr: merge safe, target: patch

#16783 chore: bump version to 8.1.3 w/ changelog
  CHANGELOG.md
  package.json
Labels: cla: yes, docs, pr: lgtm, pr: merge ready, pr: merge safe, target: patch

#16784 chore: bump version to 8.1.3 w/ changelog (#16783)
  CHANGELOG.md
  package.json
Labels: cla: yes

#16773 feat(material-experimental/mdc-button): fix ripples
  src/material-experimental/mdc-button/BUILD.bazel
  src/material-experimental/mdc-button/button-base.ts
  src/material-experimental/mdc-button/button.html
  src/material-experimental/mdc-button/button.scss
  src/material-experimental/mdc-button/fab.scss
  src/material-experimental/mdc-button/icon-button.scss
  src/material-experimental/mdc-button/icon-button.ts
  src/material-experimental/mdc-button/module.ts
Labels: P3, cla: yes, pr: merge ready, pr: merge safe, target: patch

#15616 fix(autocomplete): unable to open panel via click inside shadow dom
  src/cdk/platform/features/shadow-dom.ts
  src/cdk/platform/public-api.ts
  src/dev-app/autocomplete/autocomplete-demo.ts
  src/material/autocomplete/BUILD.bazel
  src/material/autocomplete/autocomplete-trigger.ts
  src/material/autocomplete/autocomplete.spec.ts
  tools/public_api_guard/cdk/platform.d.ts
  tools/public_api_guard/material/autocomplete.d.ts
Labels: P2, angular-elements, caretaker note, cla: yes, pr: lgtm, pr: merge ready, target: minor

#16785 fix(cdk-experimental/clipboard): add missing tsconfig
  src/cdk-experimental/clipboard/index.ts
  src/cdk-experimental/clipboard/public-api.ts
  src/cdk-experimental/clipboard/tsconfig-build.json
Labels: cla: yes, pr: lgtm, pr: merge ready, pr: merge safe, target: patch

#16788 fix(schematics): navigation schematic not respecting breakpoints on initial render
  src/material/schematics/ng-generate/nav/files/__path__/__name@dasherize@if-flat__/__name@dasherize__.component.ts.template
Labels: P3, cla: yes, pr: lgtm, pr: merge ready, pr: merge safe, target: patch

#16787 fix(schematics): module imports not generated for schematics
  src/cdk/schematics/utils/version-agnostic-typescript.ts
Labels: P2, cla: yes, pr: lgtm, pr: merge ready, pr: merge safe, target: patch

#16575 docs(dialog): move up entry components section
  src/material/dialog/dialog.md
Labels: P3, cla: yes, docs, pr: lgtm, pr: merge ready, pr: merge safe, target: patch

#16695 feat(material-experimental): add sidenav test harness
  .github/CODEOWNERS
  src/material-experimental/mdc-sidenav/BUILD.bazel
  src/material-experimental/mdc-sidenav/README.md
  src/material-experimental/mdc-sidenav/_mdc-sidenav.scss
  src/material-experimental/mdc-sidenav/harness/mdc-sidenav-harness.ts
  src/material-experimental/mdc-sidenav/harness/sidenav-harness-filters.ts
  src/material-experimental/mdc-sidenav/harness/sidenav-harness.spec.ts
  src/material-experimental/mdc-sidenav/harness/sidenav-harness.ts
  src/material-experimental/mdc-sidenav/index.ts
  src/material-experimental/mdc-sidenav/module.ts
  src/material-experimental/mdc-sidenav/public-api.ts
  src/material-experimental/mdc-sidenav/sidenav.e2e.spec.ts
  src/material-experimental/mdc-sidenav/sidenav.scss
  src/material-experimental/mdc-sidenav/tsconfig-build.json
  src/material/sidenav/drawer.ts
  src/material/sidenav/sidenav.ts
Labels: P3, cla: yes, pr: lgtm, pr: merge ready, pr: merge safe

#11961 fix(dialog): not applying margins to new button variants
  src/material/button/button.ts
  src/material/dialog/dialog.scss
Labels: P2, cla: yes, pr: lgtm, pr: merge ready, target: patch

#16708 build: add API goldens for portal
  src/cdk-experimental/dialog/dialog-container.ts
  src/cdk/portal/dom-portal-outlet.ts
  src/cdk/portal/portal-directives.ts
  src/cdk/portal/portal.ts
  src/cdk/portal/public-api.ts
  tools/public_api_guard/BUILD.bazel
  tools/public_api_guard/cdk/portal.d.ts
Labels: P2, cla: yes, pr: lgtm, pr: merge ready, target: patch

#16688 feat(material-experimental): add test harness for slider
  .github/CODEOWNERS
  src/cdk-experimental/testing/element-dimensions.ts
  src/cdk-experimental/testing/protractor/protractor-element.ts
  src/cdk-experimental/testing/test-element.ts
  src/cdk-experimental/testing/testbed/unit-test-element.ts
  src/cdk-experimental/testing/tests/harnesses/main-component-harness.ts
  src/cdk-experimental/testing/tests/protractor.e2e.spec.ts
  src/cdk-experimental/testing/tests/test-main-component.html
  src/cdk-experimental/testing/tests/test-main-component.ts
  src/cdk-experimental/testing/tests/testbed.spec.ts
  src/material-experimental/mdc-slider/harness/BUILD.bazel
  src/material-experimental/mdc-slider/harness/slider-harness-filters.ts
  src/material-experimental/mdc-slider/harness/slider-harness.spec.ts
  src/material-experimental/mdc-slider/harness/slider-harness.ts
  src/material/slider/slider.ts
  tools/public_api_guard/material/slider.d.ts
Labels: cla: yes, pr: lgtm, pr: merge ready, pr: merge safe, target: patch

#16798 fix(sidenav): avoid CSS class name conflict
  src/material/sidenav/drawer.scss
  src/material/sidenav/drawer.spec.ts
  src/material/sidenav/drawer.ts
Labels: P2, cla: yes, pr: lgtm, pr: merge ready, target: patch

#16734 feat(youtube-player): Add width and height as inputs
  src/youtube-player/public-api.ts
  src/youtube-player/youtube-player.spec.ts
  src/youtube-player/youtube-player.ts
Labels: cla: yes, pr: lgtm, pr: merge ready, pr: merge safe, target: minor

#16735 feat(youtube-player): Add proxy methods for calling the underlying pl…
  src/youtube-player/youtube-player.spec.ts
  src/youtube-player/youtube-player.ts
Labels: cla: yes, pr: lgtm, pr: merge ready, pr: merge safe, target: minor

#16728 feat(material-experimental): add test harness for tabs
  src/material-experimental/mdc-tabs/harness/BUILD.bazel
  src/material-experimental/mdc-tabs/harness/tab-group-harness-filters.ts
  src/material-experimental/mdc-tabs/harness/tab-group-harness.spec.ts
  src/material-experimental/mdc-tabs/harness/tab-group-harness.ts
  src/material-experimental/mdc-tabs/harness/tab-harness.ts
Labels: cla: yes, pr: lgtm, pr: merge ready, pr: merge safe, target: patch

#16803 chore: fix some formatting and grammar nits
  src/material-experimental/mdc-menu/harness/mdc-menu-harness.ts
  src/material/autocomplete/autocomplete-trigger.ts
Labels: P3, cla: yes, pr: lgtm, pr: merge ready, pr: merge safe, target: patch

#16814 build: cleanup material-experimental bazel sass targets
  src/material-experimental/mdc-button/BUILD.bazel
  src/material-experimental/mdc-card/BUILD.bazel
  src/material-experimental/mdc-checkbox/BUILD.bazel
  src/material-experimental/mdc-chips/BUILD.bazel
  src/material-experimental/mdc-menu/BUILD.bazel
  src/material-experimental/mdc-radio/BUILD.bazel
  src/material-experimental/mdc-sidenav/BUILD.bazel
  src/material-experimental/mdc-slide-toggle/BUILD.bazel
  src/material-experimental/mdc-tabs/BUILD.bazel
  src/material-experimental/popover-edit/BUILD.bazel
Labels: cla: yes, pr: lgtm, pr: merge ready, pr: merge safe, target: patch

#16812 build: update rules sass version
  .bazelrc
  WORKSPACE
Labels: cla: yes, pr: lgtm, pr: merge ready, pr: merge safe, target: patch

#16736 feat(youtube-player): Wire up start/end seconds and suggested quality…
  src/youtube-player/youtube-player.spec.ts
  src/youtube-player/youtube-player.ts
Labels: cla: yes, pr: lgtm, pr: merge ready, pr: merge safe, target: minor

#16818 build: switch test targets to karma_web_test_suite
  src/cdk/coercion/BUILD.bazel
  src/cdk/keycodes/BUILD.bazel
  src/material-moment-adapter/BUILD.bazel
  test/BUILD.bazel
  tools/defaults.bzl
Labels: cla: yes, pr: lgtm, pr: merge ready, pr: merge safe, target: patch

#16821 style(button-toggle-demo): missing space in attributes
  src/dev-app/button-toggle/button-toggle-demo.html
Labels: cla: yes, commit message fixup, pr: lgtm, pr: merge ready, pr: merge safe, target: patch

#16828 ci: temporarily disable gesture config tests
  src/material/core/gestures/gesture-config.spec.ts
Labels: cla: yes, pr: lgtm, pr: merge ready, pr: merge safe, target: patch

#16823 build: use bazel automatic execution strategy selection
  .bazelrc
  src/BUILD.bazel
  tools/defaults.bzl
Labels: cla: yes, pr: lgtm, pr: merge ready, pr: merge safe, target: patch

#16668 build: cronjob to run tests against mdc snapshot builds
  .circleci/config.yml
  scripts/circleci/setup-mdc-snapshots.js
Labels: cla: yes, pr: lgtm, pr: merge ready, pr: merge safe, target: patch

#16833 build: add blocklist to disable individual tests in the project
  test/BUILD.bazel
  test/angular-test-init-spec.ts
  test/test-blocklist.ts
Labels: P2, cla: yes, pr: lgtm, pr: merge ready, pr: merge safe, target: patch

#16772 chore: Update MDC to latest alpha
  package.json
  src/material-experimental/mdc-chips/chip-grid.ts
  src/material-experimental/mdc-chips/chip-icons.ts
  src/material-experimental/mdc-chips/chip-listbox.ts
  src/material-experimental/mdc-chips/chip-set.ts
  src/material-experimental/mdc-chips/chip.html
  src/material-experimental/mdc-chips/chip.ts
  src/material-experimental/mdc-helpers/BUILD.bazel
  yarn.lock
Labels: cla: yes, pr: lgtm, target: patch

#16834 build: update jasmine types dependency
  package.json
  src/cdk/a11y/aria-describer/aria-reference.spec.ts
  src/cdk/table/table.spec.ts
  src/material-experimental/mdc-chips/chip-row.spec.ts
  src/material/button-toggle/button-toggle.spec.ts
  src/material/core/gestures/gesture-config.spec.ts
  src/material/datepicker/year-view.spec.ts
  src/youtube-player/fake-youtube-player.ts
  yarn.lock
Labels: cla: yes, pr: lgtm, pr: merge ready, pr: merge safe, target: patch

#16832 build: run snapshot local browser tests with bazel
  .circleci/config.yml
  angular-tsconfig.json
  scripts/circleci/run-local-browser-tests.sh
Labels: cla: yes, pr: lgtm, pr: merge ready, pr: merge safe, target: patch

#16829 build: serve dev-app with bazel
  .circleci/config.yml
  package.json
  src/dev-app/BUILD.bazel
  src/dev-app/index.html
  src/dev-app/main-aot.ts
  src/dev-app/main.ts
  src/dev-app/system-config.js
  src/dev-app/system-config.ts
  src/dev-app/system-rxjs-operators.js
  src/dev-app/tsconfig-aot.json
  src/dev-app/tsconfig-build.json
  tools/gulp/gulpfile.ts
  tools/gulp/tasks/aot.ts
  tools/gulp/tasks/development.ts
  tools/gulp/util/task-helpers.ts
  tools/gulp/util/watch-files-reload.ts
  yarn.lock
Labels: cla: yes, pr: lgtm, pr: merge ready, pr: merge safe, target: patch

#15554 fix(datepicker): don't set aria-haspopup if no datepicker is set
  src/material/datepicker/datepicker-input.ts
  src/material/datepicker/datepicker-toggle.html
  src/material/datepicker/datepicker.spec.ts
Labels: cla: yes, pr: lgtm, pr: merge ready, target: patch

#16602 fix(sidenav): focus trap enabled state not updated if mode changes while open
  src/material/sidenav/drawer.spec.ts
  src/material/sidenav/drawer.ts
Labels: P3, cla: yes, pr: lgtm, pr: merge ready, target: patch

#16603 refactor(dialog): allow matDialogClose on non-button nodes
  src/material/dialog/dialog-content-directives.ts
Labels: P4, cla: yes, pr: lgtm, pr: merge ready, target: patch

#16652 fix(button): fix opacity is not added to ripple when using CSS variables to define custom theme
  src/material/button/_button-theme.scss
Labels: cla: yes, pr: lgtm, pr: merge ready, target: patch

#16680 fix(slider): inconsistent cursor behavior if user's pointer moves around while dragging
  src/material/slider/slider.scss
  src/material/slider/slider.spec.ts
  src/material/slider/slider.ts
Labels: P3, cla: yes, pr: lgtm, pr: merge ready, target: patch

#16696 fix(menu): inconsistent behavior when clicking on a disabled item
  src/material-experimental/mdc-menu/menu.e2e.spec.ts
  src/material-experimental/mdc-menu/menu.scss
  src/material/menu/menu.e2e.spec.ts
  src/material/menu/menu.scss
Labels: P3, cla: yes, pr: lgtm, pr: merge ready, target: patch

#16710 feat(material-experimental): add test harness for select
  .github/CODEOWNERS
  src/cdk-experimental/testing/testbed/testbed-harness-environment.ts
  src/material-experimental/mdc-select/BUILD.bazel
  src/material-experimental/mdc-select/README.md
  src/material-experimental/mdc-select/_mdc-select.scss
  src/material-experimental/mdc-select/harness/mdc-select-harness.ts
  src/material-experimental/mdc-select/harness/select-harness-filters.ts
  src/material-experimental/mdc-select/harness/select-harness.spec.ts
  src/material-experimental/mdc-select/harness/select-harness.ts
  src/material-experimental/mdc-select/index.ts
  src/material-experimental/mdc-select/module.ts
  src/material-experimental/mdc-select/public-api.ts
  src/material-experimental/mdc-select/select.e2e.spec.ts
  src/material-experimental/mdc-select/select.scss
  src/material-experimental/mdc-select/tsconfig-build.json
Labels: P3, cla: yes, pr: lgtm, pr: merge ready, pr: merge safe, target: patch

#16739 feat(overlay): allow width/height when using point as flexible origin
  src/cdk/overlay/position/flexible-connected-position-strategy.spec.ts
  src/cdk/overlay/position/flexible-connected-position-strategy.ts
  src/cdk/overlay/public-api.ts
  tools/public_api_guard/cdk/overlay.d.ts
Labels: P3, cla: yes, pr: lgtm, pr: merge ready, target: minor

#16806 fix(expansion): not adding margin for all button types
  src/material/expansion/expansion-panel.scss
Labels: P3, cla: yes, pr: lgtm, pr: merge ready, target: patch

#16811 fix(material-experimental/chips): high contrast mode fixes
  src/material-experimental/mdc-chips/chips.scss
Labels: P3, cla: yes, pr: lgtm, pr: merge ready, target: patch

#16813 feat(material-experimental): option to filter tab-group harness by selected tab label
  src/material-experimental/mdc-tabs/harness/tab-group-harness-filters.ts
  src/material-experimental/mdc-tabs/harness/tab-group-harness.spec.ts
  src/material-experimental/mdc-tabs/harness/tab-group-harness.ts
Labels: cla: yes, pr: lgtm, pr: merge ready, pr: merge safe, target: patch

#16820 refactor(mdc-chips): Make MatChipTextControl publically available.
  src/material-experimental/mdc-chips/public-api.ts
Labels: cla: yes, pr: lgtm, pr: merge ready, target: patch

#16827 cleanup(select): remove runtime checkbox padding calculation workaround
  src/material/select/select.ts
  tools/public_api_guard/material/select.d.ts
Labels: cla: yes, pr: lgtm, pr: merge ready, target: patch

#16600 _updateElementSize should not fail if pane is disposed.
  src/cdk/overlay/overlay-ref.ts
Labels: cla: yes, commit message fixup, pr: lgtm, pr: merge ready, target: patch

#16512 fix(radio): show ripple on programmatic focus
  src/material/radio/radio.scss
Labels: a11y, cla: yes, pr: lgtm, pr: merge ready, target: patch

#16838 fix: update all files/directories owned by DevInfra to DevInfra alias
  .github/CODEOWNERS
Labels: cla: yes, pr: lgtm, pr: merge ready, pr: merge safe, target: patch

#16700 docs(dialog): add note about passing data to a template dialog
  src/material/dialog/dialog.md
Labels: P3, cla: yes, docs, pr: lgtm, pr: merge ready, pr: merge safe, target: patch

#16839 feat(cdk/testing): allow `preventDefault` on mouse events
  src/cdk/testing/event-objects.ts
Labels: G, P2, cla: yes, pr: lgtm, pr: merge ready, target: patch

#16846 fix: correct DevInfra alias
  .github/CODEOWNERS
Labels: cla: yes, pr: merge safe

#16842 build: remove unnecessary dependency in dev-app devserver
  src/dev-app/BUILD.bazel
Labels: cla: yes, pr: lgtm, pr: merge ready, pr: merge safe, target: patch

#16845 build: re-enable disabled gesture config test
  src/material/core/gestures/gesture-config.spec.ts
Labels: cla: yes, pr: lgtm, pr: merge ready, pr: merge safe, target: patch

#16588 prototype(card): create prototype card based on MDC web
  src/dev-app/mdc-card/BUILD.bazel
  src/dev-app/mdc-card/mdc-card-demo-module.ts
  src/dev-app/mdc-card/mdc-card-demo.html
  src/dev-app/mdc-card/mdc-card-demo.scss
  src/dev-app/mdc-card/mdc-card-demo.ts
  src/material-experimental/mdc-card/BUILD.bazel
  src/material-experimental/mdc-card/_mdc-card.scss
  src/material-experimental/mdc-card/card-header.html
  src/material-experimental/mdc-card/card-title-group.html
  src/material-experimental/mdc-card/card.html
  src/material-experimental/mdc-card/card.scss
  src/material-experimental/mdc-card/card.ts
  src/material-experimental/mdc-card/migration.md
  src/material-experimental/mdc-card/module.ts
  src/material-experimental/mdc-helpers/_mdc-helpers.scss
Labels: cla: yes, pr: lgtm, pr: merge ready, pr: merge safe, target: patch

#16706 fix(material-experimental): unit tests getting wrong root element and add API for getting property value
  src/cdk-experimental/testing/protractor/protractor-element.ts
  src/cdk-experimental/testing/test-element.ts
  src/cdk-experimental/testing/testbed/unit-test-element.ts
  src/cdk-experimental/testing/tests/protractor.e2e.spec.ts
  src/cdk-experimental/testing/tests/testbed.spec.ts
  src/material-experimental/mdc-checkbox/harness/checkbox-harness.ts
  src/material-experimental/mdc-checkbox/harness/mdc-checkbox-harness.ts
  src/material-experimental/mdc-radio/harness/radio-harness.ts
  src/material-experimental/mdc-slide-toggle/harness/mdc-slide-toggle-harness.ts
  src/material-experimental/mdc-slide-toggle/harness/slide-toggle-harness.ts
Labels: P2, cla: yes, pr: lgtm, pr: merge ready, pr: merge safe

#16847 feat(cdk-experimental/testing): Add a public stabilize method to TestElement
  src/cdk-experimental/testing/protractor/protractor-element.ts
  src/cdk-experimental/testing/test-element.ts
  src/cdk-experimental/testing/testbed/unit-test-element.ts
Labels: P2, cla: yes, pr: lgtm, pr: merge ready, pr: merge safe, target: patch

#16654 docs(Getting Started): Updated material Getting Started guide to use install schematics and simplify the overall process
  guides/getting-started.md
Labels: P2, cla: yes, docs, pr: lgtm, pr: merge ready, pr: merge safe, target: patch

#16853 build: switch dev app system config to es5
  src/dev-app/system-config.js
Labels: P2, cla: yes, pr: lgtm, pr: merge ready, pr: merge safe, target: patch

#16858 feat(youtube-player) Add a demo to the dev-app
  .github/CODEOWNERS
  src/dev-app/BUILD.bazel
  src/dev-app/dev-app/dev-app-layout.ts
  src/dev-app/dev-app/routes.ts
  src/dev-app/index.html
  src/dev-app/system-config.js
  src/dev-app/youtube-player/BUILD.bazel
  src/dev-app/youtube-player/youtube-player-demo-module.ts
  src/dev-app/youtube-player/youtube-player-demo.html
  src/dev-app/youtube-player/youtube-player-demo.scss
  src/dev-app/youtube-player/youtube-player-demo.ts
Labels: cla: yes, commit message fixup, pr: lgtm, pr: merge ready, pr: merge safe, target: minor

#16855 fix(icon): Use the ErrorLogger to log HTTP errors
  src/material/icon/icon-registry.ts
  src/material/icon/icon.spec.ts
  tools/public_api_guard/material/icon.d.ts
Labels: G, P2, cla: yes, pr: lgtm, pr: merge ready, target: patch

#16861 docs: fix typo in code comment
  src/cdk/stepper/stepper-button.ts
  src/material/menu/menu-item.ts
  src/material/sidenav/drawer.ts
Labels: cla: yes, pr: lgtm, pr: merge ready, pr: merge safe, target: patch

#16674 feat(material-experimental): add test harness for input
  .github/CODEOWNERS
  src/material-experimental/mdc-input/harness/BUILD.bazel
  src/material-experimental/mdc-input/harness/input-harness-filters.ts
  src/material-experimental/mdc-input/harness/input-harness.spec.ts
  src/material-experimental/mdc-input/harness/input-harness.ts
Labels: cla: yes, pr: lgtm, pr: merge ready, pr: merge safe, target: patch

#16857 build: enable buildifier "unsorted-dict-items" and "out-of-order-load" rules
  package.json
  packages.bzl
  src/cdk-experimental/BUILD.bazel
  src/cdk-experimental/scrolling/BUILD.bazel
  src/cdk-experimental/testing/BUILD.bazel
  src/e2e-app/BUILD.bazel
  src/material-examples/BUILD.bazel
  src/material-experimental/BUILD.bazel
  src/material-experimental/mdc-button/BUILD.bazel
  src/material-experimental/mdc-card/BUILD.bazel
  src/material-experimental/mdc-checkbox/BUILD.bazel
  src/material-experimental/mdc-menu/BUILD.bazel
  src/material-experimental/mdc-radio/BUILD.bazel
  src/material-experimental/mdc-select/BUILD.bazel
  src/material-experimental/mdc-sidenav/BUILD.bazel
  src/material-experimental/mdc-slide-toggle/BUILD.bazel
  src/material-experimental/mdc-tabs/BUILD.bazel
  src/material-moment-adapter/BUILD.bazel
  src/material/BUILD.bazel
  src/material/card/BUILD.bazel
  tools/BUILD.bazel
  tools/defaults.bzl
  tools/dgeni/index.bzl
  tools/sass_bundle.bzl
Labels: cla: yes, pr: lgtm, pr: merge ready, pr: merge safe, target: patch

#16856 build: yarn dev-app script should run with ibazel by default
  package.json
Labels: cla: yes, pr: lgtm, pr: merge ready, pr: merge safe, target: patch

#16906 build: bazel typescript targets should use tsickle for decorator processing
  WORKSPACE
  package.json
  src/bazel-tsconfig-build.json
  src/bazel-tsconfig-test.json
  tools/bazel/BUILD.bazel
  tools/bazel/postinstall-patches.js
  tools/defaults.bzl
  yarn.lock
Labels: cla: yes, pr: lgtm, pr: merge ready, pr: merge safe, target: patch

#16620 feat(material-experimental): add autocomplete test harness
  .github/CODEOWNERS
  src/material-experimental/mdc-autocomplete/BUILD.bazel
  src/material-experimental/mdc-autocomplete/README.md
  src/material-experimental/mdc-autocomplete/_mdc-autocomplete.scss
  src/material-experimental/mdc-autocomplete/autocomplete.e2e.spec.ts
  src/material-experimental/mdc-autocomplete/autocomplete.scss
  src/material-experimental/mdc-autocomplete/harness/autocomplete-harness-filters.ts
  src/material-experimental/mdc-autocomplete/harness/autocomplete-harness.spec.ts
  src/material-experimental/mdc-autocomplete/harness/autocomplete-harness.ts
  src/material-experimental/mdc-autocomplete/harness/mdc-autocomplete-harness.ts
  src/material-experimental/mdc-autocomplete/index.ts
  src/material-experimental/mdc-autocomplete/module.ts
  src/material-experimental/mdc-autocomplete/public-api.ts
  src/material-experimental/mdc-autocomplete/tsconfig-build.json
  src/material/autocomplete/autocomplete-trigger.ts
Labels: P3, cla: yes, pr: lgtm, pr: merge ready, pr: merge safe, target: patch

#16819 feat(material-experimental/mdc-button): focused state
  src/material-experimental/mdc-button/BUILD.bazel
  src/material-experimental/mdc-button/README.md
  src/material-experimental/mdc-button/_button-base.scss
  src/material-experimental/mdc-button/_mdc-button.scss
  src/material-experimental/mdc-button/button.html
  src/material-experimental/mdc-button/button.scss
  src/material-experimental/mdc-button/fab.scss
  src/material-experimental/mdc-button/icon-button.scss
Labels: P3, cla: yes, pr: lgtm, pr: merge ready, pr: merge safe, target: patch

#16766 feat(material-experimental/mdc-button): support disabled FAB
  src/material-experimental/mdc-button/README.md
  src/material-experimental/mdc-button/fab.scss
Labels: P3, cla: yes, pr: lgtm, pr: merge ready, pr: merge safe, target: patch

#16737 feat(material-experimental/mdc-chips): add harness skeleton
  src/material-experimental/mdc-chips/BUILD.bazel
  src/material-experimental/mdc-chips/harness/chip-grid-harness.spec.ts
  src/material-experimental/mdc-chips/harness/chip-grid-harness.ts
  src/material-experimental/mdc-chips/harness/chip-harness.spec.ts
  src/material-experimental/mdc-chips/harness/chip-harness.ts
  src/material-experimental/mdc-chips/harness/chip-input.spec.ts
  src/material-experimental/mdc-chips/harness/chip-input.ts
  src/material-experimental/mdc-chips/harness/chip-listbox-harness.spec.ts
  src/material-experimental/mdc-chips/harness/chip-listbox-harness.ts
  src/material-experimental/mdc-chips/harness/chip-option-harness.spec.ts
  src/material-experimental/mdc-chips/harness/chip-option-harness.ts
  src/material-experimental/mdc-chips/harness/chip-row-harness.spec.ts
  src/material-experimental/mdc-chips/harness/chip-row-harness.ts
  src/material-experimental/mdc-chips/harness/chip-set-harness.spec.ts
  src/material-experimental/mdc-chips/harness/chip-set-harness.ts
Labels: P2, cla: yes, pr: lgtm, pr: merge ready, pr: merge safe, target: patch

#16848 feat(cdk-experimental/testing): add support for matching selector on TestElement
  src/cdk-experimental/testing/component-harness.ts
  src/cdk-experimental/testing/harness-environment.ts
  src/cdk-experimental/testing/protractor/protractor-element.ts
  src/cdk-experimental/testing/test-element.ts
  src/cdk-experimental/testing/testbed/unit-test-element.ts
  src/cdk-experimental/testing/tests/harnesses/main-component-harness.ts
  src/cdk-experimental/testing/tests/harnesses/sub-component-harness.ts
  src/cdk-experimental/testing/tests/protractor.e2e.spec.ts
  src/cdk-experimental/testing/tests/testbed.spec.ts
  src/material-experimental/mdc-button/harness/button-harness-filters.ts
  src/material-experimental/mdc-button/harness/button-harness.ts
  src/material-experimental/mdc-button/harness/mdc-button-harness.ts
  src/material-experimental/mdc-checkbox/harness/checkbox-harness-filters.ts
  src/material-experimental/mdc-checkbox/harness/checkbox-harness.ts
  src/material-experimental/mdc-checkbox/harness/mdc-checkbox-harness.ts
  src/material-experimental/mdc-input/harness/input-harness-filters.ts
  src/material-experimental/mdc-input/harness/input-harness.spec.ts
  src/material-experimental/mdc-input/harness/input-harness.ts
  src/material-experimental/mdc-menu/harness/mdc-menu-harness.ts
  src/material-experimental/mdc-menu/harness/mdc-menu-item-harness.ts
  src/material-experimental/mdc-menu/harness/menu-harness-filters.ts
  src/material-experimental/mdc-menu/harness/menu-harness.ts
  src/material-experimental/mdc-menu/harness/menu-item-harness.ts
  src/material-experimental/mdc-radio/harness/radio-harness-filters.ts
  src/material-experimental/mdc-radio/harness/radio-harness.spec.ts
  src/material-experimental/mdc-radio/harness/radio-harness.ts
  src/material-experimental/mdc-select/harness/select-harness-filters.ts
  src/material-experimental/mdc-select/harness/select-harness.spec.ts
  src/material-experimental/mdc-select/harness/select-harness.ts
  src/material-experimental/mdc-sidenav/harness/sidenav-harness-filters.ts
  src/material-experimental/mdc-sidenav/harness/sidenav-harness.ts
  src/material-experimental/mdc-slide-toggle/harness/mdc-slide-toggle-harness.ts
  src/material-experimental/mdc-slide-toggle/harness/slide-toggle-harness-filters.ts
  src/material-experimental/mdc-slide-toggle/harness/slide-toggle-harness.ts
  src/material-experimental/mdc-slider/harness/slider-harness-filters.ts
  src/material-experimental/mdc-slider/harness/slider-harness.spec.ts
  src/material-experimental/mdc-slider/harness/slider-harness.ts
  src/material-experimental/mdc-tabs/harness/tab-group-harness-filters.ts
  src/material-experimental/mdc-tabs/harness/tab-group-harness.ts
Labels: P2, caretaker note, cla: yes, pr: lgtm, pr: merge ready, target: patch

#16804 feat(google-maps): Add methods and event handling to Google Map
  src/dev-app/google-map/google-map-demo.html
  src/dev-app/google-map/google-map-demo.ts
  src/google-maps/google-map/google-map.spec.ts
  src/google-maps/google-map/google-map.ts
  src/google-maps/google-map/testing/BUILD.bazel
  src/google-maps/google-map/testing/fake-google-map-utils.ts
Labels: cla: yes, pr: lgtm, pr: merge ready, pr: merge safe, target: minor

#16795 prototype(slider): create prototype slider based on MDC web
  .github/CODEOWNERS
  packages.bzl
  src/dev-app/BUILD.bazel
  src/dev-app/dev-app/dev-app-layout.ts
  src/dev-app/dev-app/routes.ts
  src/dev-app/mdc-slider/BUILD.bazel
  src/dev-app/mdc-slider/mdc-slider-demo-module.ts
  src/dev-app/mdc-slider/mdc-slider-demo.html
  src/dev-app/mdc-slider/mdc-slider-demo.ts
  src/dev-app/system-config.js
  src/dev-app/theme.scss
  src/e2e-app/BUILD.bazel
  src/material-experimental/mdc-helpers/_mdc-helpers.scss
  src/material-experimental/mdc-slider/BUILD.bazel
  src/material-experimental/mdc-slider/README.md
  src/material-experimental/mdc-slider/_mdc-slider.scss
  src/material-experimental/mdc-slider/harness/BUILD.bazel
  src/material-experimental/mdc-slider/index.ts
  src/material-experimental/mdc-slider/module.ts
  src/material-experimental/mdc-slider/public-api.ts
  src/material-experimental/mdc-slider/slider.e2e.spec.ts
  src/material-experimental/mdc-slider/slider.html
  src/material-experimental/mdc-slider/slider.scss
  src/material-experimental/mdc-slider/slider.spec.ts
  src/material-experimental/mdc-slider/slider.ts
  src/material-experimental/mdc-slider/tsconfig-build.json
  test/karma-system-config.js
Labels: cla: yes, pr: lgtm, pr: merge ready, pr: merge safe, target: major

#16918 build: fix rebase conflict between autocomplete harness and selector filter
  src/material-experimental/mdc-autocomplete/harness/autocomplete-harness-filters.ts
  src/material-experimental/mdc-autocomplete/harness/autocomplete-harness.spec.ts
  src/material-experimental/mdc-autocomplete/harness/autocomplete-harness.ts
Labels: P1, cla: yes, pr: lgtm, pr: merge ready, pr: merge safe, target: patch

#16919 build: format mdc-slider build file imports
  src/material-experimental/mdc-slider/BUILD.bazel
Labels: cla: yes, pr: merge safe, target: patch

#16916 chore: remove duplicate list entry in dev-app
  src/dev-app/dev-app/dev-app-layout.ts
Labels: cla: yes, pr: lgtm, pr: merge ready, target: patch

#16709 feat(material-experimental): test harness for dialog
  .github/CODEOWNERS
  src/cdk-experimental/testing/testbed/testbed-harness-environment.ts
  src/material-experimental/mdc-dialog/harness/BUILD.bazel
  src/material-experimental/mdc-dialog/harness/dialog-harness-filters.ts
  src/material-experimental/mdc-dialog/harness/dialog-harness.spec.ts
  src/material-experimental/mdc-dialog/harness/dialog-harness.ts
Labels: cla: yes, pr: lgtm, pr: merge ready, pr: merge safe, target: patch
