Repository angular/components, pull requests merged in 2019-05, with the labels that each got.

#15933 docs: add README files for experimental packages
  src/cdk-experimental/README.md
  src/material-experimental/README.md
Labels: cla: yes, docs, pr: lgtm, pr: merge ready, pr: merge safe

#15975 refactor: don't depend on @Inject for _MatMenuBase DI
  src/material/menu/menu.ts
  tools/public_api_guard/material/menu.d.ts
Labels: P1, cla: yes, pr: lgtm, pr: merge ready, target: patch

#15996 build: fix broken codeowners file
  .github/CODEOWNERS
Labels: cla: yes, pr: lgtm, pr: merge ready, pr: merge safe, target: patch

#15978 docs(drag-drop): add docs for cdkDragFreeDragPosition
  src/cdk/drag-drop/drag-drop.md
  src/material-examples/cdk-drag-drop-free-drag-position/cdk-drag-drop-free-drag-position-example.css
  src/material-examples/cdk-drag-drop-free-drag-position/cdk-drag-drop-free-drag-position-example.html
  src/material-examples/cdk-drag-drop-free-drag-position/cdk-drag-drop-free-drag-position-example.ts
Labels: cla: yes, docs, pr: lgtm, pr: merge ready, pr: merge safe, target: patch

#15977 chore: switch examples to secondary entry-points
  src/material-examples/BUILD.bazel
  src/material-examples/bottom-sheet-overview/bottom-sheet-overview-example.ts
  src/material-examples/chips-autocomplete/chips-autocomplete-example.ts
  src/material-examples/chips-input/chips-input-example.ts
  src/material-examples/datepicker-custom-header/datepicker-custom-header-example.ts
  src/material-examples/dialog-content/dialog-content-example.ts
  src/material-examples/dialog-data/dialog-data-example.ts
  src/material-examples/dialog-elements/dialog-elements-example.ts
  src/material-examples/dialog-overview/dialog-overview-example.ts
  src/material-examples/expansion-expand-collapse-all/expansion-expand-collapse-all-example.ts
  src/material-examples/form-field-custom-control/form-field-custom-control-example.ts
  src/material-examples/icon-svg/icon-svg-example.ts
  src/material-examples/material-module.ts
  src/material-examples/paginator-configurable/paginator-configurable-example.ts
  src/material-examples/popover-edit-cell-span-mat-table/popover-edit-cell-span-mat-table-example.ts
  src/material-examples/popover-edit-mat-table-flex/popover-edit-mat-table-flex-example.ts
  src/material-examples/popover-edit-mat-table/popover-edit-mat-table-example.ts
  src/material-examples/popover-edit-tab-out-mat-table/popover-edit-tab-out-mat-table-example.ts
  src/material-examples/snack-bar-component/snack-bar-component-example.ts
  src/material-examples/snack-bar-overview/snack-bar-overview-example.ts
  src/material-examples/snack-bar-position/snack-bar-position-example.ts
  src/material-examples/sort-overview/sort-overview-example.ts
  src/material-examples/table-filtering/table-filtering-example.ts
  src/material-examples/table-http/table-http-example.ts
  src/material-examples/table-overview/table-overview-example.ts
  src/material-examples/table-pagination/table-pagination-example.ts
  src/material-examples/table-selection/table-selection-example.ts
  src/material-examples/table-sorting/table-sorting-example.ts
  src/material-examples/table-sticky-complex-flex/table-sticky-complex-flex-example.ts
  src/material-examples/table-sticky-complex/table-sticky-complex-example.ts
  src/material-examples/table-text-column-advanced/table-text-column-advanced-example.ts
  src/material-examples/table-wrapped/table-wrapped-example.ts
  src/material-examples/tooltip-auto-hide/tooltip-auto-hide-example.ts
  src/material-examples/tooltip-modified-defaults/tooltip-modified-defaults-example.ts
  src/material-examples/tooltip-position/tooltip-position-example.ts
  src/material-examples/tsconfig-build.json
  src/material-examples/tsconfig.json
Labels: P2, caretaker note, cla: yes, pr: lgtm, pr: merge ready, pr: merge safe, target: patch

#15963 build: add rule to enforce static queries
  src/cdk-experimental/popover-edit/popover-edit.spec.ts
  src/material-experimental/mdc-checkbox/checkbox.spec.ts
  src/material-experimental/popover-edit/popover-edit.spec.ts
  tools/tslint-rules/staticQueryRule.ts
  tslint.json
Labels: cla: yes, pr: lgtm, pr: merge ready, pr: merge safe, target: patch

#15962 docs(table): TableExpandableRowsExample
  src/material-examples/table-expandable-rows/table-expandable-rows-example.ts
Labels: cla: yes, pr: lgtm, pr: merge ready, pr: merge safe, target: patch

#15951 fix(popover-edit): direction not being passed to overlay
  src/cdk-experimental/popover-edit/popover-edit.spec.ts
  src/cdk-experimental/popover-edit/table-directives.ts
Labels: cla: yes, pr: lgtm, pr: merge ready, pr: merge safe, target: patch

#15928 docs(autocomplete): document that mat-autocomplete can be used without mat-form-field
  src/material-examples/autocomplete-plain-input/autocomplete-plain-input-example.css
  src/material-examples/autocomplete-plain-input/autocomplete-plain-input-example.html
  src/material-examples/autocomplete-plain-input/autocomplete-plain-input-example.ts
  src/material/autocomplete/autocomplete.md
Labels: cla: yes, docs, pr: lgtm, pr: merge ready, pr: merge safe, target: patch

#15954 refactor(popover-edit): remove unnecessary components
  src/cdk-experimental/popover-edit/popover-edit-module.ts
  src/cdk-experimental/popover-edit/table-directives.ts
  src/material-experimental/popover-edit/popover-edit-module.ts
  src/material-experimental/popover-edit/table-directives.ts
Labels: cla: yes, pr: lgtm, pr: merge ready, pr: merge safe, target: patch

#15976 build: add rule to warn for undecorated base classes
  tools/tslint-rules/noUndecoratedBaseClassDiRule.ts
  tslint.json
Labels: cla: yes, pr: lgtm, pr: merge ready, pr: merge safe, target: patch

#16002 chore: add skeleton files for MDC-based implementation of chips
  .github/CODEOWNERS
  e2e/components/mdc-chips-e2e.spec.ts
  src/dev-app/BUILD.bazel
  src/dev-app/dev-app/dev-app-layout.ts
  src/dev-app/dev-app/routes.ts
  src/dev-app/mdc-chips/mdc-chips-demo-module.ts
  src/dev-app/mdc-chips/mdc-chips-demo.html
  src/dev-app/mdc-chips/mdc-chips-demo.scss
  src/dev-app/mdc-chips/mdc-chips-demo.ts
  src/dev-app/system-config.ts
  src/dev-app/theme.scss
  src/e2e-app/BUILD.bazel
  src/e2e-app/e2e-app/e2e-app-layout.html
  src/e2e-app/e2e-app/routes.ts
  src/e2e-app/main-module.ts
  src/e2e-app/mdc-chips/mdc-chips-e2e-module.ts
  src/e2e-app/mdc-chips/mdc-chips-e2e.html
  src/e2e-app/mdc-chips/mdc-chips-e2e.ts
  src/e2e-app/theme.scss
  src/material-experimental/mdc-chips/BUILD.bazel
  src/material-experimental/mdc-chips/README.md
  src/material-experimental/mdc-chips/_mdc-chips.scss
  src/material-experimental/mdc-chips/chip-cell.ts
  src/material-experimental/mdc-chips/chip-grid.html
  src/material-experimental/mdc-chips/chip-grid.ts
  src/material-experimental/mdc-chips/chips.scss
  src/material-experimental/mdc-chips/chips.spec.ts
  src/material-experimental/mdc-chips/index.ts
  src/material-experimental/mdc-chips/module.ts
  src/material-experimental/mdc-chips/public-api.ts
  src/material-experimental/mdc-chips/tsconfig-build.json
  src/universal-app/kitchen-sink-mdc/kitchen-sink-mdc.html
  src/universal-app/kitchen-sink-mdc/kitchen-sink-mdc.ts
  src/universal-app/theme.scss
  test/karma-system-config.js
Labels: P2, cla: yes, pr: lgtm, pr: merge ready, pr: merge safe, target: minor

#14602 fix(portal): TemplatePortal generic parameter
  src/cdk/portal/portal.ts
Labels: caretaker note, cla: yes, commit message fixup, pr: lgtm, pr: merge ready, target: major

#16005 fix(list): form control cleared when list is destroyed
  src/material/list/selection-list.spec.ts
  src/material/list/selection-list.ts
Labels: cla: yes, pr: lgtm, pr: merge ready, target: patch

#15950 fix(drag-drop): error if item is removed while dragging
  src/cdk/drag-drop/directives/drag.spec.ts
  src/cdk/drag-drop/drop-list-ref.ts
Labels: cla: yes, pr: lgtm, pr: merge ready, target: patch

#15932 refactor(drag-drop): add current index to entered event
  src/cdk/drag-drop/directives/drag.spec.ts
  src/cdk/drag-drop/directives/drag.ts
  src/cdk/drag-drop/directives/drop-list.ts
  src/cdk/drag-drop/drag-events.ts
  src/cdk/drag-drop/drag-ref.ts
  src/cdk/drag-drop/drop-list-ref.ts
  tools/public_api_guard/cdk/drag-drop.d.ts
Labels: cla: yes, pr: lgtm, pr: merge ready, target: patch

#15869 refactor(badge): add method that exposes badge content element
  src/material/badge/badge.spec.ts
  src/material/badge/badge.ts
  tools/public_api_guard/material/badge.d.ts
Labels: cla: yes, pr: lgtm, pr: merge ready, target: patch

#15856 fix(scrolling): virtual scroll not disconnecting from data source on destroy
  src/cdk/scrolling/virtual-for-of.ts
  src/cdk/scrolling/virtual-scroll-viewport.spec.ts
Labels: cla: yes, pr: lgtm, pr: merge ready, target: patch

#15853 fix(overlay): add panelClass from position to the overlay
  src/cdk/overlay/overlay-directives.spec.ts
  src/cdk/overlay/overlay-directives.ts
Labels: cla: yes, pr: lgtm, pr: merge ready, target: patch

#15834 feat(autocomplete): add input to control position
  src/material/autocomplete/autocomplete-trigger.ts
  src/material/autocomplete/autocomplete.spec.ts
  tools/public_api_guard/material/autocomplete.d.ts
Labels: cla: yes, pr: lgtm, pr: merge ready, target: minor

#15810 feat(drag-drop): allow element to be passed in as the boundary
  src/cdk/drag-drop/directives/drag.spec.ts
  src/cdk/drag-drop/directives/drag.ts
  tools/public_api_guard/cdk/drag-drop.d.ts
Labels: cla: yes, pr: lgtm, pr: merge ready, target: minor

#15808 fix(drag-drop): preview element not maintaining canvas data
  src/cdk/drag-drop/directives/drag.spec.ts
  src/cdk/drag-drop/drag-ref.ts
Labels: cla: yes, pr: lgtm, pr: merge ready, target: patch

#15741 feat(radio): support theme color on mat-radio-group
  src/dev-app/radio/radio-demo.html
  src/material/radio/radio.spec.ts
  src/material/radio/radio.ts
  tools/public_api_guard/material/radio.d.ts
Labels: cla: yes, pr: lgtm, pr: merge ready, target: minor

#15660 fix(drag-drop): don't allow user to move item into container that isn't connected to current one by passing it over an intermediate one that is
  src/cdk/drag-drop/directives/drag.spec.ts
  src/cdk/drag-drop/drag-ref.ts
Labels: cla: yes, pr: lgtm, pr: merge ready, target: patch

#15507 fix(overlay): allow overlay sass variables to be overwritten
  src/cdk/overlay/_overlay.scss
Labels: cla: yes, pr: lgtm, pr: merge ready, target: patch

#15455 refactor(overlay): remove explicit subscription count
  src/cdk/overlay/position/flexible-connected-position-strategy.ts
Labels: cla: yes, pr: lgtm, pr: merge ready, target: patch

#15454 fix(menu): prevent menu from collapsing to less than one item
  src/material/menu/menu.scss
Labels: cla: yes, pr: lgtm, pr: merge ready, target: patch

#15441 refactor(drag-drop): remove manual observers count
  src/cdk/drag-drop/drag-ref.ts
Labels: cla: yes, pr: lgtm, pr: merge ready, target: patch

#15091 fix(drag-drop): allow for element in DropListRef to be changed
  src/cdk/drag-drop/drag-ref.ts
  src/cdk/drag-drop/drop-list-ref.ts
  tools/public_api_guard/cdk/drag-drop.d.ts
Labels: cla: yes, pr: lgtm, pr: merge ready, target: patch

#14814 fix(select): optionSelectionChanges not emitting when the list of options changes
  src/material/select/select.spec.ts
  src/material/select/select.ts
Labels: P4, cla: yes, pr: lgtm, pr: merge ready, target: patch

#13700 fix(checkbox): don't show hover ripples on touch devices
  src/material/checkbox/checkbox.scss
Labels: cla: yes, pr: lgtm, pr: merge ready, target: patch

#16008 chore: fix lint failure
  tools/tslint-rules/noUndecoratedBaseClassDiRule.ts
Labels: cla: yes, pr: lgtm, pr: merge ready, pr: merge safe, target: patch

#15750 fix(expansion-panel): don't handle events with modifier keys in accordion
  src/material/expansion/accordion.spec.ts
  src/material/expansion/accordion.ts
Labels: a11y, cla: yes, pr: lgtm, pr: merge ready, target: patch

#15678 fix(icon): handle unescaped characters in names
  src/material/icon/fake-svgs.ts
  src/material/icon/icon-registry.ts
  src/material/icon/icon.spec.ts
Labels: cla: yes, pr: lgtm, pr: merge ready, target: patch

#15668 fix(button-toggle): clear name from host node
  src/material/button-toggle/button-toggle.spec.ts
  src/material/button-toggle/button-toggle.ts
Labels: cla: yes, pr: lgtm, pr: merge ready, target: patch

#15667 fix(menu): trigger not unsubscribing from panel close stream
  src/material/menu/menu-trigger.ts
Labels: cla: yes, pr: lgtm, pr: merge ready, target: patch

#15663 fix(datepicker): screen reader reading out role twice
  src/material/datepicker/month-view.html
  src/material/datepicker/month-view.spec.ts
  src/material/datepicker/multi-year-view.html
  src/material/datepicker/multi-year-view.spec.ts
  src/material/datepicker/year-view.html
  src/material/datepicker/year-view.spec.ts
Labels: a11y, cla: yes, pr: lgtm, pr: merge ready, target: patch

#15661 fix(datepicker): add focus indication in high contrast mode
  src/material/datepicker/calendar-body.scss
Labels: a11y, cla: yes, pr: lgtm, pr: merge ready, target: patch

#15655 fix(select): add duration to live announcer message
  src/material/select/select.spec.ts
  src/material/select/select.ts
Labels: cla: yes, pr: lgtm, pr: merge ready, target: patch

#15366 refactor(autocomplete): rework cases not using document token
  src/material/autocomplete/autocomplete-trigger.ts
Labels: cla: yes, pr: lgtm, pr: merge ready, target: patch

#15344 fix(chips): focus lost if last chip is deleted
  src/material/chips/chip-list.spec.ts
  src/material/chips/chip-list.ts
Labels: a11y, cla: yes, pr: lgtm, pr: merge ready, target: patch

#15060 fix(chips): unable to tab out of chip list with input on firefox
  src/material/chips/chip-input.spec.ts
  src/material/chips/chip-input.ts
  src/material/chips/chip-list.ts
  tools/public_api_guard/material/chips.d.ts
Labels: a11y, cla: yes, pr: lgtm, pr: merge ready, target: patch

#15582 fix(autocomplete): not emitting opened event if options come in after open
  src/material/autocomplete/autocomplete-trigger.ts
  src/material/autocomplete/autocomplete.spec.ts
Labels: cla: yes, pr: lgtm, pr: merge ready, target: patch

#15508 fix(button-toggle): value cleared when replacing with list that still contains the selected value
  src/material/button-toggle/button-toggle.spec.ts
  src/material/button-toggle/button-toggle.ts
  tools/public_api_guard/material/button-toggle.d.ts
Labels: caretaker note, cla: yes, pr: lgtm, pr: merge ready, target: patch

#15947 feat(drag-drop): include dragged distance in events
  src/cdk/drag-drop/directives/drag.spec.ts
  src/cdk/drag-drop/directives/drag.ts
  src/cdk/drag-drop/directives/drop-list.ts
  src/cdk/drag-drop/drag-events.ts
  src/cdk/drag-drop/drag-ref.ts
  src/cdk/drag-drop/drop-list-ref.ts
  tools/public_api_guard/cdk/drag-drop.d.ts
Labels: cla: yes, pr: lgtm, pr: merge ready, target: minor

#16014 chore: bump version to 8.0.0-rc.1 w/ changelog
  CHANGELOG.md
  package.json
Labels: cla: yes, pr: lgtm, pr: merge ready, target: major

#15833 refactor(sidenav): expose api to update content margins
  src/material/sidenav/drawer.ts
  tools/public_api_guard/material/sidenav.d.ts
Labels: cla: yes, pr: lgtm, pr: merge ready, target: patch

#13645 fix(button): ripples not being clipped to border radius on safari
  src/material/button/button.scss
Labels: cla: yes, pr: lgtm, pr: merge ready, target: patch

#13569 fix(checkbox): incorrect ripple color when unchecked
  src/material/checkbox/_checkbox-theme.scss
Labels: cla: yes, pr: lgtm, pr: merge ready, target: patch

#15666 fix(datepicker): use narrower value for aria-haspopup
  src/material/datepicker/datepicker-input.ts
  src/material/datepicker/datepicker-toggle.html
  src/material/datepicker/datepicker.spec.ts
Labels: cla: yes, pr: lgtm, pr: merge ready, target: patch

#15732 fix(chips): able to remove disabled chip via remove button
  src/material/chips/chip-remove.spec.ts
  src/material/chips/chip.ts
Labels: cla: yes, pr: lgtm, pr: merge ready, target: patch

#13562 fix(slide-toggle): focus ripple not hiding after click/touch
  src/material/slide-toggle/slide-toggle.scss
Labels: cla: yes, pr: lgtm, pr: merge ready, target: patch

#16021 docs(text-field): change AutosizeMinRows to 1
  src/material-examples/text-field-autosize-textarea/text-field-autosize-textarea-example.html
Labels: cla: yes, pr: lgtm, pr: merge ready, pr: merge safe, target: patch

#16040 build: remove example-module from gitignore
  .gitignore
  src/material-examples/BUILD.bazel
  src/material-examples/example-module.ts
  tools/example-module/example-module.template
  tools/example-module/generate-example-module.ts
Labels: cla: yes, pr: lgtm, pr: merge ready, pr: merge safe, target: patch

#16053 fix(datepicker): fix tests that were broken in the last rebase
  src/lib/datepicker/month-view.ts
  src/lib/datepicker/multi-year-view.html
  src/lib/datepicker/multi-year-view.ts
  src/lib/datepicker/year-view.ts
Labels: cla: yes

#15800 fix(table): schematic generates code that throws an exception
  src/material/schematics/ng-generate/table/files/__path__/__name@dasherize@if-flat__/__name@dasherize__-datasource.ts
  src/material/schematics/ng-generate/table/files/__path__/__name@dasherize@if-flat__/__name@dasherize__.component.html
  src/material/schematics/ng-generate/table/files/__path__/__name@dasherize@if-flat__/__name@dasherize__.component.ts
Labels: P2, cla: yes, pr: lgtm, pr: merge ready, pr: merge safe, target: patch

#16045 build: bump to Angular 8.0.0-rc.4
  package.json
  yarn.lock
Labels: P2, cla: yes, pr: lgtm, target: major

#16042 adds editorconfig
  .editorconfig
Labels: cla: yes, pr: lgtm, pr: merge ready, pr: merge safe, target: patch

#16071 build: fine-grain dependencies for mdc prototypes
  src/material-experimental/mdc-button/BUILD.bazel
  src/material-experimental/mdc-card/BUILD.bazel
  src/material-experimental/mdc-checkbox/BUILD.bazel
  src/material-experimental/mdc-chips/BUILD.bazel
  src/material-experimental/mdc-helpers/BUILD.bazel
  src/material-experimental/mdc-menu/BUILD.bazel
  src/material-experimental/mdc-radio/BUILD.bazel
  src/material-experimental/mdc-slide-toggle/BUILD.bazel
Labels: cla: yes, pr: lgtm, pr: merge ready, pr: merge safe, target: patch

#16064 build: no longer use deprecated api in sass_bundle rule
  tools/sass_bundle.bzl
Labels: cla: yes, pr: lgtm, pr: merge ready, pr: merge safe, target: patch

#16073 build: fix examples package generating invalid metadata
  src/material-examples/BUILD.bazel
Labels: cla: yes, pr: lgtm, pr: merge ready, pr: merge safe, target: patch

#16063 build: update bazel nodejs rules to v0.29.0
  WORKSPACE
  e2e/BUILD.bazel
  package.json
  src/cdk/schematics/BUILD.bazel
  src/material/schematics/BUILD.bazel
  yarn.lock
Labels: cla: yes, pr: lgtm, pr: merge ready, pr: merge safe, target: patch

#16060 fix(popover-edit): rework host listeners to account for changes in Ivy
  src/cdk-experimental/popover-edit/lens-directives.ts
  src/cdk-experimental/popover-edit/table-directives.ts
  src/material-experimental/popover-edit/lens-directives.ts
  src/material-experimental/popover-edit/table-directives.ts
Labels: cla: yes, pr: lgtm, pr: merge ready, pr: merge safe, target: patch

#15584 refactor: mark injectable refs with `@Injectable`
  src/material/bottom-sheet/bottom-sheet-ref.ts
  src/material/dialog/dialog-ref.ts
  src/material/snack-bar/snack-bar-ref.ts
Labels: cla: yes, pr: lgtm, pr: merge ready, target: patch

#16079 Revert "refactor: mark injectable refs with `@Injectable`"
  src/material/bottom-sheet/bottom-sheet-ref.ts
  src/material/dialog/dialog-ref.ts
  src/material/snack-bar/snack-bar-ref.ts
Labels: cla: yes

#16047 fix(table): error in Ivy for coerced multiTemplateDataRows
  src/cdk/table/table.spec.ts
  src/cdk/table/table.ts
Labels: P2, cla: yes, pr: lgtm, pr: merge ready, target: major

#16084 chore: bump tslint version
  package.json
  src/cdk/schematics/BUILD.bazel
  yarn.lock
Labels: cla: yes, pr: lgtm, pr: merge ready, pr: merge safe, target: patch

#16077 chore: update github issue templates; add docs/troubleshooting
  .github/ISSUE_TEMPLATE/bug.md
  .github/ISSUE_TEMPLATE/docs.md
  .github/ISSUE_TEMPLATE/feature.md
  .github/ISSUE_TEMPLATE/troubleshooting.md
Labels: cla: yes, pr: lgtm, pr: merge ready, pr: merge safe, target: patch

#16088 fix(schematics): avoid lint warning in code generated by nav schematic
  src/material/schematics/ng-generate/nav/files/__path__/__name@dasherize@if-flat__/__name@dasherize__.component.html
Labels: cla: yes, pr: lgtm, pr: merge ready, pr: merge safe, target: patch

#15955 fix(table): better error message if text column is missing a name
  src/cdk/table/table-errors.ts
  src/cdk/table/text-column.spec.ts
  src/cdk/table/text-column.ts
Labels: cla: yes, pr: lgtm, pr: merge ready, target: patch

#15820 fix(badge): throw proper error when set on a non-element node
  src/material/badge/badge.spec.ts
  src/material/badge/badge.ts
Labels: cla: yes, pr: lgtm, pr: merge ready, target: patch

#16102 test: fix flaky slide-toggle test with pending timer task
  src/material/slide-toggle/slide-toggle.spec.ts
Labels: cla: yes, pr: lgtm, pr: merge ready, pr: merge safe, target: patch

#16108 fix(ng-update): type imports not migrated to secondary entry-points
  src/material/schematics/ng-update/test-cases/misc/material-imports.spec.ts
  src/material/schematics/ng-update/test-cases/misc/material-imports_expected_output.ts
  src/material/schematics/ng-update/test-cases/misc/material-imports_input.ts
  src/material/schematics/ng-update/upgrade-rules/package-imports-v8/updateAngularMaterialImportsRule.ts
Labels: P1, cla: yes, pr: lgtm, pr: merge ready, pr: merge safe, target: patch

#16106 chore: bump to Angular 8.0.0-rc.5
  package.json
  yarn.lock
Labels: cla: yes, pr: lgtm, pr: merge ready, pr: merge safe, target: major

#16104 build: source maps for some dependencies not exposed during unit tests
  test/karma.conf.js
Labels: cla: yes, pr: lgtm, pr: merge ready, pr: merge safe, target: patch

#16103 test(popover-edit): fix tests leaking overlay containers
  src/cdk-experimental/popover-edit/BUILD.bazel
  src/cdk-experimental/popover-edit/popover-edit.spec.ts
  src/material-experimental/popover-edit/BUILD.bazel
  src/material-experimental/popover-edit/popover-edit.spec.ts
Labels: cla: yes, pr: lgtm, pr: merge ready, pr: merge safe, target: patch

#16113 build: fill in missing MATERIAL_EXPERIMENTAL_PACKAGES
  package.json
  packages.bzl
  src/dev-app/BUILD.bazel
  src/e2e-app/BUILD.bazel
  src/material-experimental/mdc-button/BUILD.bazel
  src/material-experimental/mdc-card/BUILD.bazel
  src/material-experimental/mdc-checkbox/BUILD.bazel
  src/material-experimental/mdc-chips/BUILD.bazel
  src/material-experimental/mdc-menu/BUILD.bazel
  src/material-experimental/mdc-radio/BUILD.bazel
  src/material-experimental/mdc-slide-toggle/BUILD.bazel
Labels: cla: yes, pr: lgtm, pr: merge ready, pr: merge safe, target: patch

#16116 chore: bump version to 8.0.0-rc.2 w/ changelog
  CHANGELOG.md
  package.json
Labels: cla: yes, pr: lgtm, pr: merge ready, pr: merge safe, target: major

#16131 fix(ng-update): do not always use double quotes for generated imports
  src/material/schematics/ng-update/test-cases/misc/material-imports_expected_output.ts
  src/material/schematics/ng-update/test-cases/misc/material-imports_input.ts
  src/material/schematics/ng-update/upgrade-rules/package-imports-v8/updateAngularMaterialImportsRule.ts
Labels: cla: yes, pr: lgtm, pr: merge ready, pr: merge safe, target: patch

#16134 chore: set Angular version requirement for version 8
  package.json
  packages.bzl
  yarn.lock
Labels: cla: yes, pr: merge safe, target: major

#16135 chore: go down to rc.1 so that the stage-release script works
  package.json
Labels: cla: yes, pr: merge safe, target: major

#16140 chore: bump version to 8.0.0 w/ changelog
  CHANGELOG.md
  package.json
Labels: cla: yes, pr: lgtm, pr: merge ready, pr: merge safe, target: major

#16125 docs(menu): reflect default overlap trigger behavior
  src/material/menu/menu.md
Labels: P4, cla: yes, docs, pr: lgtm, pr: merge ready, pr: merge safe, target: patch

#16138 docs(table): Fix incorrect term in table documentation
  src/material/table/table.md
Labels: cla: yes, pr: lgtm, pr: merge ready, pr: merge safe

#16147 build: release-staging script should have option to not bump version
  tools/release/prompt/new-version-prompt.ts
  tools/release/publish-release.ts
  tools/release/stage-release.ts
  tools/release/version-name/parse-version.ts
Labels: P3, cla: yes, pr: lgtm, pr: merge ready, pr: merge safe, target: patch

#16150 test(schematics): move away from deprecated test API
  src/cdk/schematics/ng-add/index.spec.ts
  src/cdk/schematics/ng-generate/drag-drop/index.spec.ts
  src/material/schematics/ng-add/index.spec.ts
  src/material/schematics/ng-generate/address-form/index.spec.ts
  src/material/schematics/ng-generate/dashboard/index.spec.ts
  src/material/schematics/ng-generate/nav/index.spec.ts
  src/material/schematics/ng-generate/table/index.spec.ts
  src/material/schematics/ng-generate/tree/index.spec.ts
Labels: cla: yes, pr: lgtm, pr: merge ready, pr: merge safe, target: patch

#16161 fix(ng-update): do not report form-field breaking change from v6
  src/material/schematics/ng-update/index.ts
  src/material/schematics/ng-update/test-cases/misc/class-inheritance.spec.ts
  src/material/schematics/ng-update/test-cases/misc/class-inheritance_input.ts
  src/material/schematics/ng-update/upgrade-rules/misc-checks/checkClassInheritanceMiscRule.ts
Labels: P3, cla: yes, pr: lgtm, pr: merge ready, pr: merge safe, target: patch
