Repository angular/components, pull requests merged in 2020-11, with the labels that each got.

#20940 fix(material-experimental/mdc-checkbox): fix broken dark theme
  src/material-experimental/mdc-checkbox/_checkbox-theme.scss
Labels: P1, cla: yes, merge ready, target: patch

#20938 build: update to the latest Angular version
  package.json
  yarn.lock
Labels: P3, cla: yes, merge ready, merge safe, target: rc

#20952 release: bump version to 11.0.0-rc.1 w/ changelog
  CHANGELOG.md
  package.json
Labels: cla: yes, merge ready, target: rc

#20955 release: bump version to 10.2.7 w/ changelog
  CHANGELOG.md
  package.json
Labels: cla: yes, merge ready, target: patch

#20877 fix(material/datepicker): input harness not dispatching dateChange event
  src/material/datepicker/testing/date-range-input-harness-shared.spec.ts
  src/material/datepicker/testing/datepicker-input-harness-base.ts
  src/material/datepicker/testing/datepicker-input-harness-shared.spec.ts
Labels: P2, cla: yes, merge ready, target: patch

#20914 feat(material/stepper): allow focus origin to be optional input in focus method
  src/material/stepper/step-header.ts
  src/material/stepper/stepper.spec.ts
  tools/public_api_guard/material/stepper.d.ts
Labels: G, cla: yes, merge ready, target: minor

#20766 fix(cdk/stepper): error if out-of-bounds index is assigned before initialization
  src/cdk/stepper/stepper.ts
  src/material/stepper/stepper.spec.ts
Labels: P3, cla: yes, merge ready, target: patch

#20873 fix(google-maps): allow ground overlay bounds to be changed
  src/google-maps/map-ground-overlay/map-ground-overlay.spec.ts
  src/google-maps/map-ground-overlay/map-ground-overlay.ts
  tools/public_api_guard/google-maps/google-maps.d.ts
Labels: P3, cla: yes, merge ready, target: patch

#20829 feat(material-experimental/mdc-chips): Allow custom role for chip set
  src/material-experimental/mdc-chips/chip-set.spec.ts
  src/material-experimental/mdc-chips/chip-set.ts
Labels: cla: yes, merge ready, target: patch

#20866 fix(cdk/layout): decrease breakpoint upper bounds
  src/cdk/layout/breakpoints.ts
Labels: area: cdk/layout, cla: yes, merge ready, target: patch

#20912 feat(material/expansion): allow focus origin to be optional input in focus method
  src/material/expansion/expansion-panel-header.ts
  src/material/expansion/expansion.spec.ts
Labels: G, cla: yes, merge ready, target: minor

#20889 fix(material/dialog): incorrect action height if box-sizing is configured globally
  src/material/dialog/dialog.scss
Labels: P4, cla: yes, merge ready, target: patch

#20898 feat(material/button): allow focus origin to be optional input in focus method
  src/material/button/button.spec.ts
  src/material/button/button.ts
Labels: G, P4, cla: yes, merge ready, target: minor

#20905 feat(material/checkbox): allow focus origin to be optional input in focus method
  src/material/checkbox/checkbox.spec.ts
  src/material/checkbox/checkbox.ts
Labels: G, P4, cla: yes, merge ready, target: minor

#20864 feat(material/datepicker) allow custom pickers with date inputs
  src/material/datepicker/date-range-input.ts
  src/material/datepicker/date-range-picker.ts
  src/material/datepicker/datepicker-base.ts
  src/material/datepicker/datepicker-input.ts
  src/material/datepicker/datepicker-toggle.ts
  tools/public_api_guard/material/datepicker.d.ts
Labels: G, P2, area: material/datepicker, cla: yes, merge ready, target: minor

#20880 fix(material-experimental/mdc-chips): use MDC-based form field
  src/dev-app/mdc-chips/BUILD.bazel
  src/dev-app/mdc-chips/mdc-chips-demo-module.ts
  src/dev-app/mdc-chips/mdc-chips-demo.html
  src/dev-app/mdc-chips/mdc-chips-demo.scss
  src/dev-app/mdc-chips/mdc-chips-demo.ts
  src/material-experimental/mdc-chips/BUILD.bazel
  src/material-experimental/mdc-chips/chip-grid.spec.ts
  src/material-experimental/mdc-chips/chip-grid.ts
  src/material-experimental/mdc-chips/chip-input.spec.ts
  src/material-experimental/mdc-chips/chip-input.ts
  src/material-experimental/mdc-chips/chips.scss
  src/material-experimental/mdc-chips/testing/BUILD.bazel
  src/material/chips/chip-input.spec.ts
Labels: P2, cla: yes, merge ready, target: minor

#20907 feat(material/menu): allow focus origin to be optional input in focus method
  src/material/menu/menu-item.ts
  src/material/menu/menu-trigger.ts
  src/material/menu/menu.spec.ts
Labels: G, P4, cla: yes, merge ready, target: minor

#20937 fix(material/datepicker): range input emitters not picked up by language service
  src/material/datepicker/date-range-input-parts.ts
  tools/public_api_guard/material/datepicker.d.ts
Labels: P4, cla: yes, merge ready, target: patch

#20831 feat(material-experimental/mdc-chips): add `remove` method to MDC chip harness
  src/material-experimental/mdc-chips/testing/chip-harness-filters.ts
  src/material-experimental/mdc-chips/testing/chip-harness.spec.ts
  src/material-experimental/mdc-chips/testing/chip-harness.ts
Labels: G, P2, area: material/chips, cla: yes, merge ready, merge safe, target: minor

#20943 fix(material/paginator): remove unnecessary @ViewChild in harness test
  src/material/paginator/testing/shared.spec.ts
Labels: P3, cla: yes, merge ready, merge safe, target: patch

#20957 docs(material-experimental): css paths in readme
  src/material-experimental/README.md
  src/material-experimental/mdc-autocomplete/README.md
  src/material-experimental/mdc-checkbox/README.md
  src/material-experimental/mdc-menu/README.md
  src/material-experimental/mdc-paginator/README.md
  src/material-experimental/mdc-progress-bar/README.md
  src/material-experimental/mdc-progress-spinner/README.md
  src/material-experimental/mdc-select/README.md
  src/material-experimental/mdc-slide-toggle/README.md
  src/material-experimental/mdc-tabs/README.md
Labels: cla: yes, merge ready, merge safe, target: minor

#20870 fix(material/slider): some screen readers announcing long decimal values
  src/material/slider/slider.spec.ts
  src/material/slider/slider.ts
  tools/public_api_guard/material/slider.d.ts
Labels: P3, a11y, caretaker note, cla: yes, merge ready, target: patch

#20819 fix(material/autocomplete): options inside groups not read out with VoiceOver
  src/material-experimental/mdc-core/option/optgroup.ts
  src/material-experimental/mdc-core/option/option.html
  src/material-experimental/mdc-core/option/option.spec.ts
  src/material-experimental/mdc-core/testing/option-harness.ts
  src/material/autocomplete/autocomplete.ts
  src/material/core/option/index.ts
  src/material/core/option/optgroup.ts
  src/material/core/option/option-parent.ts
  src/material/core/option/option.html
  src/material/core/option/option.spec.ts
  src/material/core/option/option.ts
  src/material/core/testing/option-harness.ts
  tools/public_api_guard/material/autocomplete.d.ts
  tools/public_api_guard/material/core.d.ts
Labels: P2, a11y, cla: yes, merge ready, target: minor

#16930 fix(progress-spinner): rotating circle changing surrounding layout
  src/material/progress-spinner/progress-spinner.scss
Labels: P3, cla: yes, merge ready, target: patch

#19735 fix(material/tooltip): not closing when scrolling away using mouse wheel
  src/material/tooltip/tooltip.spec.ts
  src/material/tooltip/tooltip.ts
  tools/public_api_guard/material/tooltip.d.ts
Labels: P3, cla: yes, merge ready, target: minor

#19346 fix(progress-bar): buffer not rendering correctly on ios
  src/material/progress-bar/progress-bar.spec.ts
  src/material/progress-bar/progress-bar.ts
Labels: P3, cla: yes, merge ready, target: patch

#20946 build: use MDC components for MDC demos
  src/dev-app/mdc-checkbox/BUILD.bazel
  src/dev-app/mdc-checkbox/mdc-checkbox-demo-module.ts
  src/dev-app/mdc-checkbox/mdc-checkbox-demo.ts
  src/dev-app/mdc-dialog/BUILD.bazel
  src/dev-app/mdc-dialog/mdc-dialog-demo-module.ts
  src/dev-app/mdc-dialog/mdc-dialog-demo.scss
  src/dev-app/mdc-input/BUILD.bazel
  src/dev-app/mdc-input/mdc-input-demo-module.ts
  src/dev-app/mdc-input/mdc-input-demo.ts
  src/dev-app/mdc-menu/BUILD.bazel
  src/dev-app/mdc-menu/mdc-menu-demo-module.ts
  src/dev-app/mdc-progress-bar/mdc-progress-bar-demo.ts
  src/dev-app/mdc-progress-spinner/BUILD.bazel
  src/dev-app/mdc-progress-spinner/mdc-progress-spinner-demo-module.ts
  src/dev-app/mdc-radio/BUILD.bazel
  src/dev-app/mdc-radio/mdc-radio-demo-module.ts
  src/dev-app/mdc-select/mdc-select-demo.ts
  src/dev-app/mdc-slider/BUILD.bazel
  src/dev-app/mdc-slider/mdc-slider-demo-module.ts
  src/dev-app/mdc-snack-bar/BUILD.bazel
  src/dev-app/mdc-snack-bar/mdc-snack-bar-demo-module.ts
  src/dev-app/mdc-snack-bar/mdc-snack-bar-demo.html
Labels: P3, cla: yes, merge ready, merge safe, target: minor

#20913 feat(material/slide-toggle): allow focus origin to be optional input in focus method
  src/material/slide-toggle/slide-toggle.spec.ts
  src/material/slide-toggle/slide-toggle.ts
  tools/public_api_guard/material/slide-toggle.d.ts
Labels: G, P3, cla: yes, merge ready, target: minor

#20911 feat(material/radio): allow focus origin to be optional input in focus method
  src/material/radio/radio.spec.ts
  src/material/radio/radio.ts
  tools/public_api_guard/material/radio.d.ts
Labels: G, P3, cla: yes, merge ready, target: minor

#20961 fix(material/checkbox): set display on host node
  src/material-experimental/mdc-checkbox/checkbox.scss
  src/material/checkbox/checkbox.scss
Labels: P3, caretaker note, cla: yes, merge ready, target: patch

#20969 fix(material-experimental/mdc-button): narrow down overly-broad selector
  src/material-experimental/mdc-button/fab.scss
Labels: P2, cla: yes, merge ready, target: patch

#17086 fix(button-toggle): clear static aria attributes from host nodes
  src/material/button-toggle/button-toggle.spec.ts
  src/material/button-toggle/button-toggle.ts
Labels: P3, cla: yes, merge ready, target: patch

#19094 fix(table): filter predicate not called for falsy values
  src/material-experimental/mdc-table/table.spec.ts
  src/material/table/table-data-source.ts
  src/material/table/table.spec.ts
Labels: P3, cla: yes, merge ready, target: patch

#20944 feat(google-maps): Add MapMarkerClusterer Component
  src/dev-app/google-map/google-map-demo.html
  src/dev-app/google-map/google-map-demo.ts
  src/dev-app/index.html
  src/google-maps/BUILD.bazel
  src/google-maps/google-maps-module.ts
  src/google-maps/map-marker-clusterer/README.md
  src/google-maps/map-marker-clusterer/map-marker-clusterer.spec.ts
  src/google-maps/map-marker-clusterer/map-marker-clusterer.ts
  src/google-maps/map-marker-clusterer/marker-clusterer-types.ts
  src/google-maps/public-api.ts
  src/google-maps/testing/fake-google-map-utils.ts
  tools/public_api_guard/google-maps/google-maps.d.ts
Labels: P3, cla: yes, merge ready, target: minor

#20964 fix(material-experimental/mdc-slide-toggle): hide native focus outline
  src/material-experimental/mdc-slide-toggle/slide-toggle.scss
Labels: P3, cla: yes, merge ready, target: patch

#20966 fix(cdk/a11y): allow for origin of already focused element to be changed
  src/cdk/a11y/BUILD.bazel
  src/cdk/a11y/focus-monitor/focus-monitor.spec.ts
  src/cdk/a11y/focus-monitor/focus-monitor.ts
  src/material-experimental/mdc-menu/menu.spec.ts
  src/material/menu/menu.spec.ts
Labels: P3, cla: yes, merge ready, target: patch

#20985 ci: rebase PRs before running CI checks
  .circleci/config.yml
  .circleci/env-helpers.inc.sh
  .circleci/env.sh
  .circleci/rebase-pr.js
Labels: area: build, cla: yes, merge ready, merge safe, target: patch

#20988 test(material/menu): resolve test failures
  src/material-experimental/mdc-menu/menu.spec.ts
  src/material/menu/menu.spec.ts
Labels: P2, cla: yes, merge ready, merge safe, target: minor

#20977 build: update to latest Angular RC and MDC canary
  package.json
  yarn.lock
Labels: P3, cla: yes, merge ready, merge safe, target: rc

#20992 build: fix broken yarn.lock attributes
  yarn.lock
Labels: cla: yes, merge ready, merge safe, target: rc

#20993 build: update to latest Angular rc version
  package.json
  yarn.lock
Labels: cla: yes, merge ready, target: rc

#20995 release: bump version to 11.0.0-rc.2 w/ changelog
  CHANGELOG.md
  package.json
Labels: cla: yes, merge ready, target: rc

#20997 release: bump version to 11.0.0-rc.2 w/ changelog
  CHANGELOG.md
  package.json
Labels: cla: yes, merge ready

#21002 release: bump version to 11.0.0-rc.3 w/ changelog
  CHANGELOG.md
  package.json
Labels: cla: yes, merge ready, target: rc

#21006 fix package.json and yarn.lock issues
  package.json
  yarn.lock
Labels: cla: yes, preserve commits, target: rc

#21007 Revert "build: bump scss-bundle from 3.0.2 to 3.1.2 (#20799)"
  yarn.lock
Labels: cla: yes, merge ready

#21008 release: bump version to 11.0.0-rc.4 w/ changelog
  CHANGELOG.md
  package.json
Labels: cla: yes, merge ready

#21010 release: bump version to 11.0.0-rc.4 w/ changelog
  CHANGELOG.md
  package.json
  yarn.lock
Labels: cla: yes

#21018 release: bump angular to version 11
  package.json
  yarn.lock
Labels: cla: yes, merge safe

#21019 release: bump angular to version 11
  package.json
  yarn.lock
Labels: cla: yes, merge safe

#21020 release: update angular version in packages.bzl
  packages.bzl
Labels: cla: yes

#21021 release: bump version to 11.0.0 w/ changelog
  CHANGELOG.md
  package.json
Labels: cla: yes, merge ready, target: rc

#21022 release: collapse down 11.0.0 changelog
  CHANGELOG.md
Labels: cla: yes, merge ready, target: rc

#21023 release: add 11.0.0 changelog and update packages.bzl
  CHANGELOG.md
  packages.bzl
Labels: cla: yes, merge ready, merge safe, target: minor

#21016 build: update to latest scss bundler and resolve file size issue
  package.json
  src/material/BUILD.bazel
  yarn.lock
Labels: P3, cla: yes, merge ready, merge safe, target: patch

#21028 build: correct version for master branch
  package.json
Labels: cla: yes, merge ready, merge safe, target: minor

#21017 build: use MDC 9.0 canary when publishing to npm
  packages.bzl
Labels: P3, cla: yes, merge ready, merge safe, target: patch

#20941 build: add CI check to keep MDC tests in line
  .circleci/config.yml
  scripts/check-mdc-tests-config.ts
  scripts/check-mdc-tests.ts
  src/material-experimental/mdc-chips/chip-input.spec.ts
  src/material-experimental/mdc-list/selection-list.spec.ts
  src/material-experimental/mdc-menu/menu.spec.ts
  src/material-experimental/mdc-radio/radio.spec.ts
  src/material-experimental/mdc-select/select.spec.ts
  src/material-experimental/mdc-slider/slider.spec.ts
Labels: P2, cla: yes, merge ready, merge safe, target: minor

#20942 docs(material/chips): add chips harness example
  src/components-examples/material/chips/BUILD.bazel
  src/components-examples/material/chips/chips-harness/chips-harness-example.html
  src/components-examples/material/chips/chips-harness/chips-harness-example.spec.ts
  src/components-examples/material/chips/chips-harness/chips-harness-example.ts
  src/components-examples/material/chips/index.ts
Labels: cla: yes, merge ready, merge safe, target: patch

#20960 build: add CI check to ensure consistent exports for MDC packages
  .circleci/config.yml
  package.json
  scripts/check-mdc-exports-config.ts
  scripts/check-mdc-exports.ts
  src/material-experimental/mdc-checkbox/public-api.ts
  src/material-experimental/mdc-dialog/public-api.ts
  src/material-experimental/mdc-form-field/public-api.ts
  src/material-experimental/mdc-input/public-api.ts
  src/material-experimental/mdc-list/BUILD.bazel
  src/material-experimental/mdc-list/public-api.ts
  src/material-experimental/mdc-menu/public-api.ts
  src/material-experimental/mdc-progress-spinner/public-api.ts
  src/material-experimental/mdc-radio/public-api.ts
  src/material-experimental/mdc-slide-toggle/public-api.ts
  src/material-experimental/mdc-snack-bar/public-api.ts
  src/material-experimental/mdc-tabs/public-api.ts
Labels: P2, cla: yes, merge ready, merge safe, target: minor

#20986 feat(material/radio): Avoid nested divs in labels by changing to span instead.
  src/material/radio/radio.html
  src/material/radio/radio.scss
Labels: cla: yes, merge ready, target: patch

#20984 build: update to latest sass version
  WORKSPACE
  package.json
  tools/postinstall/sass_worker_async.patch
  yarn.lock
Labels: P3, cla: yes, merge ready, merge safe, target: minor

#20963 fix(material-experimental/mdc-button): fix positioning of icons in text buttons
  src/dev-app/button/button-demo.html
  src/dev-app/mdc-button/mdc-button-demo.html
  src/material-experimental/mdc-button/button.html
  src/material-experimental/mdc-button/button.scss
Labels: G, P2, cla: yes, merge ready, target: patch

#21011 docs(material/dialog): add a11y section about manual focus restoration
  src/components-examples/material/dialog/BUILD.bazel
  src/components-examples/material/dialog/dialog-from-menu/dialog-from-menu-example-dialog.html
  src/components-examples/material/dialog/dialog-from-menu/dialog-from-menu-example.html
  src/components-examples/material/dialog/dialog-from-menu/dialog-from-menu-example.ts
  src/components-examples/material/dialog/index.ts
  src/material/dialog/dialog.md
Labels: cla: yes, docs, merge ready, merge safe, target: patch

#20827 build: drop typescript 3.9 checks
  integration/ts-compat/BUILD.bazel
  package.json
  scripts/caretaking/firebase-functions/package.json
  scripts/caretaking/firebase-functions/yarn.lock
  yarn.lock
Labels: P3, cla: yes, merge ready, merge safe, target: patch

#20990 feat(material/checkbox): Avoid nested divs in labels by changing to span instead.
  src/material/checkbox/checkbox.html
  src/material/checkbox/checkbox.scss
Labels: cla: yes, merge ready, target: patch

#20962 fix(material-experimental/mdc-progress-spinner): prevent animation from affecting surrounding layout
  src/material-experimental/mdc-progress-spinner/progress-spinner.scss
Labels: P3, cla: yes, merge ready, target: patch

#21042 fix(material/checkbox): no color assigned if defaults don't have a color
  src/material-experimental/mdc-checkbox/checkbox.spec.ts
  src/material-experimental/mdc-checkbox/checkbox.ts
  src/material/checkbox/checkbox.spec.ts
  src/material/checkbox/checkbox.ts
Labels: P2, cla: yes, merge ready, target: patch

#21014 fix(google-maps): info window not opening if no anchor is passed in
  src/google-maps/map-info-window/map-info-window.spec.ts
  src/google-maps/map-info-window/map-info-window.ts
Labels: P3, cla: yes, merge ready, target: patch

#21005 fix(material/select): remove focus outline on panel
  src/material-experimental/mdc-select/select.scss
  src/material/select/select.scss
Labels: P4, cla: yes, merge ready, target: patch

#20991 fix(cdk/drag-drop): don't disable native dragging on inactive handles
  src/cdk/drag-drop/directives/drag.spec.ts
  src/cdk/drag-drop/drag-ref.ts
Labels: P3, cla: yes, merge ready, target: patch

#20982 fix(material/chips): ripple not disabled when animations are disabled
  src/material/chips/chip.ts
Labels: P3, cla: yes, merge ready, target: patch

#21032 refactor(material/core): resolve circular dependency and remove underscores from more imported mixins
  src/dev-app/theme.scss
  src/material/button-toggle/_button-toggle-theme.scss
  src/material/core/BUILD.bazel
  src/material/core/_core.scss
  src/material/core/density/private/_all-density.scss
  src/material/core/density/private/_compatibility.scss
  src/material/core/focus-indicators/_focus-indicators.scss
  src/material/core/theming/tests/test-theming-api.scss
  src/material/core/theming/tests/theming-api.spec.ts
  src/material/expansion/_expansion-theme.scss
  src/material/form-field/_form-field-fill-theme.scss
  src/material/form-field/_form-field-legacy-theme.scss
  src/material/form-field/_form-field-outline-theme.scss
  src/material/form-field/_form-field-standard-theme.scss
  src/material/form-field/_form-field-theme.scss
  src/material/paginator/_paginator-theme.scss
  src/material/stepper/_stepper-theme.scss
  src/material/theming-bundle.scss
  src/material/toolbar/_toolbar-theme.scss
  src/material/tree/_tree-theme.scss
Labels: P2, caretaker note, cla: yes, merge ready, target: minor

#21048 refactor(material/datepicker): expose month view change detector ref
  src/material/datepicker/month-view.ts
  tools/public_api_guard/material/datepicker.d.ts
Labels: G, P2, area: material/datepicker, cla: yes, merge ready, target: patch

#21044 feat(material/core): add date format for month label
  src/material/core/datetime/date-formats.ts
  src/material/datepicker/month-view.spec.ts
  src/material/datepicker/month-view.ts
  tools/public_api_guard/material/core.d.ts
Labels: G, P2, area: material/core, area: material/datepicker, cla: yes, merge ready, target: minor

#21015 fix(cdk/drag-drop): avoid retaining disabled handles after they've been destroyed
  src/cdk/drag-drop/drag-ref.ts
Labels: P3, cla: yes, merge ready, target: patch

#20975 refactor(google-maps): simplify marker internal setup
  src/google-maps/map-marker/map-marker.ts
  tools/public_api_guard/google-maps/google-maps.d.ts
Labels: P3, cla: yes, merge ready, target: patch

#21051 fix(material-experimental/mdc-chips): align test harnesses with the non-MDC version
  src/material-experimental/mdc-chips/testing/BUILD.bazel
  src/material-experimental/mdc-chips/testing/chip-grid-harness.spec.ts
  src/material-experimental/mdc-chips/testing/chip-grid-harness.ts
  src/material-experimental/mdc-chips/testing/chip-harness-filters.ts
  src/material-experimental/mdc-chips/testing/chip-harness.spec.ts
  src/material-experimental/mdc-chips/testing/chip-harness.ts
  src/material-experimental/mdc-chips/testing/chip-input-harness.spec.ts
  src/material-experimental/mdc-chips/testing/chip-input-harness.ts
  src/material-experimental/mdc-chips/testing/chip-listbox-harness.spec.ts
  src/material-experimental/mdc-chips/testing/chip-listbox-harness.ts
  src/material-experimental/mdc-chips/testing/chip-option-harness.spec.ts
  src/material-experimental/mdc-chips/testing/chip-option-harness.ts
  src/material-experimental/mdc-chips/testing/chip-remove-harness.ts
  src/material-experimental/mdc-chips/testing/chip-row-harness.spec.ts
  src/material-experimental/mdc-chips/testing/chip-set-harness.spec.ts
  src/material-experimental/mdc-chips/testing/chip-set-harness.ts
  src/material-experimental/mdc-chips/testing/public-api.ts
Labels: P2, caretaker note, cla: yes, merge ready, target: minor

#21074 fix(google-maps): avoid using dotted property access
  src/google-maps/map-marker/map-marker.ts
Labels: cla: yes, merge ready, target: patch

#21076 docs: use valid SCSS variables for example
  guides/theming-your-components.md
Labels: cla: yes, docs, merge ready, merge safe, target: patch

#21082 docs(material/tree): add harness example for tree
  src/components-examples/material/tree/BUILD.bazel
  src/components-examples/material/tree/index.ts
  src/components-examples/material/tree/tree-harness/tree-harness-example.html
  src/components-examples/material/tree/tree-harness/tree-harness-example.spec.ts
  src/components-examples/material/tree/tree-harness/tree-harness-example.ts
Labels: P3, cla: yes, docs, merge ready, merge safe, target: patch

#21084 docs(material/toolbar): add harness example for toolbar
  src/components-examples/material/toolbar/BUILD.bazel
  src/components-examples/material/toolbar/index.ts
  src/components-examples/material/toolbar/toolbar-harness/toolbar-harness-example.html
  src/components-examples/material/toolbar/toolbar-harness/toolbar-harness-example.spec.ts
  src/components-examples/material/toolbar/toolbar-harness/toolbar-harness-example.ts
Labels: P3, cla: yes, docs, merge ready, merge safe, target: patch

#21058 fix(material/datepicker): screen reader close button style specificity too low
  src/material/datepicker/datepicker-content.scss
Labels: P3, cla: yes, merge ready, target: patch

#21089 build: fix error with latest MDC version
  package.json
  src/material-experimental/mdc-slider/slider.ts
  yarn.lock
Labels: P2, cla: yes, merge ready, merge safe, target: minor

#21083 docs(material/tooltip): add harness example for tooltip
  src/components-examples/material/tooltip/BUILD.bazel
  src/components-examples/material/tooltip/index.ts
  src/components-examples/material/tooltip/tooltip-harness/tooltip-harness-example.html
  src/components-examples/material/tooltip/tooltip-harness/tooltip-harness-example.spec.ts
  src/components-examples/material/tooltip/tooltip-harness/tooltip-harness-example.ts
Labels: P3, cla: yes, docs, merge ready, merge safe, target: patch

#21077 feat(material/datepicker): allow for datepicker toggle aria-label to be customized
  src/material/datepicker/datepicker-toggle.html
  src/material/datepicker/datepicker-toggle.ts
  src/material/datepicker/datepicker.spec.ts
  tools/public_api_guard/material/datepicker.d.ts
Labels: P4, a11y, cla: yes, merge ready, target: minor

#21071 perf(cdk/testing): reduce change detections when running parallel actions
  src/cdk/testing/change-detection.ts
  src/cdk/testing/harness-environment.ts
  src/cdk/testing/tests/cross-environment.spec.ts
  src/cdk/testing/tests/protractor.e2e.spec.ts
  src/cdk/testing/tests/testbed.spec.ts
  src/material-experimental/mdc-form-field/testing/form-field-harness.ts
  src/material-experimental/mdc-list/testing/list-harness-base.ts
  src/material-experimental/mdc-list/testing/list-item-harness-base.ts
  src/material-experimental/mdc-list/testing/selection-list-harness.ts
  src/material-experimental/mdc-select/testing/select-harness.ts
  src/material-experimental/mdc-slider/testing/slider-harness.ts
  src/material-experimental/mdc-snack-bar/testing/snack-bar-harness.ts
  src/material-experimental/mdc-table/testing/row-harness.ts
  src/material-experimental/mdc-table/testing/table-harness.ts
  src/material-experimental/mdc-tabs/testing/tab-group-harness.ts
  src/material-experimental/mdc-tabs/testing/tab-nav-bar-harness.ts
  src/material/card/testing/shared.spec.ts
  src/material/chips/testing/chip-list-harness.ts
  src/material/chips/testing/chip-listbox-harness.ts
  src/material/chips/testing/shared.spec.ts
  src/material/core/testing/optgroup-shared.spec.ts
  src/material/core/testing/option-shared.spec.ts
  src/material/datepicker/testing/calendar-harness-shared.spec.ts
  src/material/datepicker/testing/date-range-input-harness-shared.spec.ts
  src/material/datepicker/testing/date-range-input-harness.ts
  src/material/datepicker/testing/datepicker-input-harness-shared.spec.ts
  src/material/datepicker/testing/datepicker-input-harness.ts
  src/material/datepicker/testing/datepicker-toggle-harness-shared.spec.ts
  src/material/datepicker/testing/datepicker-trigger-harness-base.ts
  src/material/expansion/testing/shared.spec.ts
  src/material/form-field/testing/form-field-harness.ts
  src/material/form-field/testing/shared.spec.ts
  src/material/grid-list/testing/grid-list-harness.ts
  src/material/grid-list/testing/shared.spec.ts
  src/material/icon/testing/shared.spec.ts
  src/material/input/testing/input-harness.ts
  src/material/input/testing/native-select-harness.ts
  src/material/input/testing/shared-native-select.spec.ts
  src/material/list/testing/list-harness-base.ts
  src/material/list/testing/list-item-harness-base.ts
  src/material/list/testing/selection-list-harness.ts
  src/material/list/testing/shared.spec.ts
  src/material/select/testing/select-harness.ts
  src/material/select/testing/shared.spec.ts
  src/material/slider/testing/slider-harness.ts
  src/material/snack-bar/testing/snack-bar-harness.ts
  src/material/sort/testing/shared.spec.ts
  src/material/stepper/testing/shared.spec.ts
  src/material/table/testing/row-harness.ts
  src/material/table/testing/shared.spec.ts
  src/material/table/testing/table-harness.ts
  src/material/tabs/testing/tab-group-harness.ts
  src/material/tabs/testing/tab-nav-bar-harness.ts
  src/material/toolbar/testing/toolbar-harness.ts
  src/material/tree/testing/tree-harness.ts
  tools/public_api_guard/cdk/testing.d.ts
Labels: P2, caretaker note, cla: yes, merge ready, target: minor

#21060 refactor(material-experimental/mdc-core): remove underscores from imported mixins
  src/material-experimental/mdc-button/_button-base.scss
  src/material-experimental/mdc-button/button.scss
  src/material-experimental/mdc-button/fab.scss
  src/material-experimental/mdc-button/icon-button.scss
  src/material-experimental/mdc-checkbox/_checkbox-theme.scss
  src/material-experimental/mdc-dialog/_mdc-dialog-structure-overrides.scss
  src/material-experimental/mdc-dialog/dialog.scss
  src/material-experimental/mdc-form-field/_form-field-density.scss
  src/material-experimental/mdc-form-field/_form-field-focus-overlay.scss
  src/material-experimental/mdc-form-field/_form-field-native-select.scss
  src/material-experimental/mdc-form-field/_form-field-subscript.scss
  src/material-experimental/mdc-form-field/_form-field-theme.scss
  src/material-experimental/mdc-form-field/_mdc-text-field-structure-overrides.scss
  src/material-experimental/mdc-form-field/_mdc-text-field-textarea-overrides.scss
  src/material-experimental/mdc-form-field/_mdc-text-field-theme-variable-refresh.scss
  src/material-experimental/mdc-form-field/form-field.scss
  src/material-experimental/mdc-list/_interactive-list-theme.scss
  src/material-experimental/mdc-list/_list-option-theme.scss
  src/material-experimental/mdc-list/_list-theme.scss
  src/material-experimental/mdc-paginator/_paginator-theme.scss
  src/material/button-toggle/_button-toggle-theme.scss
  tools/stylelint/no-top-level-ampersand-in-mixin.ts
  tools/stylelint/theme-mixin-api.ts
Labels: P2, cla: yes, merge ready, target: minor

#21125 build: update yarn.lock
  yarn.lock
Labels: cla: yes, merge ready, merge safe, target: patch

#21127 release: bump version to 11.0.1 w/ changelog
  CHANGELOG.md
  package.json
Labels: cla: yes, merge ready, merge safe, target: patch

#19861 refactor(material/datepicker): consistently import MatCommonModule everywhere
  src/material-experimental/column-resize/column-resize-module.ts
  src/material-experimental/mdc-list/module.ts
  src/material-experimental/popover-edit/BUILD.bazel
  src/material-experimental/popover-edit/popover-edit-module.ts
  src/material/chips/chips-module.ts
  src/material/core/option/index.ts
  src/material/core/selection/index.ts
  src/material/datepicker/datepicker-module.ts
  src/material/expansion/BUILD.bazel
  src/material/expansion/expansion-module.ts
  src/material/input/input-module.ts
  src/material/paginator/paginator-module.ts
  src/material/sort/sort-module.ts
  tools/public_api_guard/material/chips.d.ts
  tools/public_api_guard/material/core.d.ts
  tools/public_api_guard/material/datepicker.d.ts
  tools/public_api_guard/material/expansion.d.ts
  tools/public_api_guard/material/input.d.ts
  tools/public_api_guard/material/paginator.d.ts
  tools/public_api_guard/material/sort.d.ts
Labels: P3, cla: yes, merge ready, target: patch

#20925 refactor(material-experimental/mdc-paginator): clean up theme sass
  src/material-experimental/mdc-paginator/_paginator-theme.scss
Labels: P3, cla: yes, merge ready, target: patch

#20970 fix(material/datepicker): don't invoke change handler when filter is swapped out if result is the same
  src/material/datepicker/date-range-input.spec.ts
  src/material/datepicker/date-range-input.ts
  src/material/datepicker/datepicker-input-base.ts
  src/material/datepicker/datepicker-input.ts
  src/material/datepicker/datepicker.spec.ts
Labels: P3, cla: yes, merge ready, target: patch

#21096 fix(material-experimental/mdc-paginator): buttons not visible in high contrast mode
  src/material-experimental/mdc-paginator/paginator.scss
Labels: P3, a11y, cla: yes, merge ready, target: patch

#21115 feat(material/sidenav): add test harnesses for container and content elements
  src/material/sidenav/testing/drawer-container-harness.ts
  src/material/sidenav/testing/drawer-content-harness.ts
  src/material/sidenav/testing/drawer-harness-filters.ts
  src/material/sidenav/testing/drawer-harness.ts
  src/material/sidenav/testing/public-api.ts
  src/material/sidenav/testing/shared.spec.ts
  src/material/sidenav/testing/sidenav-container-harness.ts
  src/material/sidenav/testing/sidenav-content-harness.ts
  src/material/sidenav/testing/sidenav-harness.spec.ts
  src/material/sidenav/testing/sidenav-harness.ts
  tools/public_api_guard/material/sidenav/testing.d.ts
Labels: P3, cla: yes, merge ready, target: minor

#20929 refactor(material-experimental/mdc-table): share code between MDC and non-MDC versions of MatTableDataSource
  src/material-experimental/mdc-table/BUILD.bazel
  src/material-experimental/mdc-table/table-data-source.ts
  src/material-experimental/mdc-table/text-column.ts
  src/material/table/table-data-source.ts
  src/material/table/text-column.ts
  tools/public_api_guard/material/table.d.ts
Labels: cla: yes, merge ready, target: minor

#21049 fix(google-maps): server-side rendering error from map clusterer
  src/google-maps/map-marker-clusterer/map-marker-clusterer.ts
  src/universal-app/kitchen-sink/kitchen-sink.html
Labels: P3, cla: yes, merge ready, target: minor

#20948 fix(material/menu): icons in menu not inheriting disabled color
  src/material-experimental/mdc-menu/_menu-theme.scss
  src/material/menu/_menu-theme.scss
Labels: P3, cla: yes, merge ready, target: patch

#21075 build: ngOnChanges property access rule not working
  tools/tslint-rules/ngOnChangesPropertyAccessRule.ts
Labels: P2, cla: yes, merge ready, merge safe, target: patch

#21122 docs: remove deprecated harness usage and use parallel promise utility
  src/components-examples/material/card/card-harness/card-harness-example.spec.ts
  src/components-examples/material/chips/chips-harness/chips-harness-example.spec.ts
Labels: P3, cla: yes, docs, merge ready, merge safe, target: minor

#21078 docs: add harness example to issue template
  .github/ISSUE_TEMPLATE/bug.md
  .github/ISSUE_TEMPLATE/troubleshooting.md
Labels: cla: yes, merge ready, merge safe, target: patch

#21113 docs: document global typography class prompt
  guides/getting-started.md
Labels: cla: yes, docs, merge ready, merge safe, target: patch

#21128 release: bump version to 11.0.1 w/ changelog
  CHANGELOG.md
Labels: cla: yes

#21136 build: fix exports check failure
  scripts/check-mdc-exports-config.ts
Labels: P3, cla: yes, merge ready, merge safe, target: minor

#21138 Revert "release: bump version to 11.0.1 w/ changelog (#21127)"
  CHANGELOG.md
  package.json
Labels: cla: yes, merge ready, merge safe, target: patch

#21139 release: bump version to 11.0.1 w/ changelog
  CHANGELOG.md
  package.json
Labels: cla: yes, merge ready, target: patch

#21140 release: update changelog
  CHANGELOG.md
Labels: cla: yes, merge ready

#21126 docs(material/chips): add mat-labels to examples
  src/components-examples/material/chips/chips-autocomplete/chips-autocomplete-example.html
  src/components-examples/material/chips/chips-input/chips-input-example.html
  src/dev-app/chips/chips-demo.html
Labels: P3, cla: yes, docs, merge ready, merge safe, target: patch

#21151 build: fix errors with latest MDC canary version
  package.json
  src/material-experimental/mdc-slider/slider.ts
  yarn.lock
Labels: P3, cla: yes, merge ready, merge safe, target: minor
