Repository angular/components, pull requests merged in 2020-02, with the labels that each got.

#18355 build: remove ngcc postinstall patch in favor of separate script
  WORKSPACE
  package.json
  tools/bazel/postinstall-patches.js
  tools/bazel/update-ngcc-main-fields.js
Labels: P2, cla: yes, pr: lgtm, pr: merge ready, pr: merge safe, target: patch

#18334 chore: delete import that was missed in #18274
  src/cdk/testing/testbed/proxy-zone-types.d.ts
  src/cdk/tsconfig-tests.json
Labels: cla: yes, pr: lgtm, pr: merge ready, target: patch

#18359 docs: update dev environment instructions
  DEV_ENVIRONMENT.md
Labels: P3, cla: yes, docs, pr: lgtm, pr: merge ready, pr: merge safe, target: patch

#18363 build: minor improvements to testing script
  scripts/run-component-tests.js
Labels: P3, cla: yes, pr: lgtm, pr: merge ready, pr: merge safe, target: patch

#18367 build: update to latest Angular RC
  package.json
  tools/bazel/postinstall-patches.js
  yarn.lock
Labels: P3, cla: yes, pr: lgtm, pr: merge ready, pr: merge safe, target: major

#18385 fix(material-experimental): consolidate mixins in e2e theme file
  src/e2e-app/BUILD.bazel
  src/e2e-app/theme.scss
Labels: cla: yes, pr: lgtm, pr: merge ready, pr: merge safe, target: patch

#18374 Fixes for density API and introduction of a new test for validating the API
  src/material/core/BUILD.bazel
  src/material/core/_core.scss
  src/material/core/theming/_theming.scss
  src/material/core/theming/tests/BUILD.bazel
  src/material/core/theming/tests/test-css-variables-theme.scss
  src/material/core/theming/tests/test-theming-api.scss
  src/material/core/typography/_all-typography.scss
  src/material/divider/_divider-theme.scss
Labels: cla: yes, pr: lgtm, pr: merge ready, pr: merge safe, target: development-branch

#18365 fix(ng-add): do not overwrite version range specified in `ng add`
  src/cdk/schematics/ng-add/index.spec.ts
  src/cdk/schematics/ng-add/index.ts
  src/cdk/schematics/ng-add/package-config.ts
  src/material/schematics/ng-add/index.spec.ts
  src/material/schematics/ng-add/index.ts
  src/material/schematics/ng-add/version-names.ts
Labels: P3, cla: yes, pr: lgtm, pr: merge ready, pr: merge safe, target: patch

#18368 fix(youtube-player): handle API interactions before API has loaded
  src/youtube-player/youtube-player.spec.ts
  src/youtube-player/youtube-player.ts
Labels: P3, cla: yes, pr: lgtm, pr: merge ready, pr: merge safe, target: patch

#18372 build: remove test blocklist
  test/BUILD.bazel
  test/angular-test-init-spec.ts
  test/test-blocklist.ts
Labels: cla: yes, pr: lgtm, pr: merge ready, pr: merge safe, target: patch

#18373 build: remove unused angular bazel postinstall patch
  tools/bazel/angular_bazel_rules_nodejs_1.0.0.patch
  tools/bazel/postinstall-patches.js
Labels: cla: yes, pr: lgtm, pr: merge ready, pr: merge safe, target: patch

#18406 fix(form-field): fix underline jank in fill variant
  src/material/form-field/form-field.scss
Labels: P1, cla: yes, pr: lgtm, pr: merge ready, target: patch

#18408 chore: bump version to 9.0.0-rc.10 w/ changelog
  CHANGELOG.md
  package.json
  src/material/yarn.lock
Labels: cla: yes, pr: lgtm, pr: merge ready, pr: merge safe, target: patch

#18415 build: bump deps for 9.0.0
  package.json
  packages.bzl
  yarn.lock
Labels: cla: yes, pr: lgtm, pr: merge ready, pr: merge safe, target: patch

#18417 chore: bump version to 9.0.0 w/ changelog
  CHANGELOG.md
  package.json
Labels: cla: yes, pr: lgtm, pr: merge ready, pr: merge safe, target: patch

#18404 fix(datepicker): handle date ranges across multiple months
  src/material/datepicker/calendar-body.html
  src/material/datepicker/calendar-body.ts
  src/material/datepicker/month-view.ts
  tools/public_api_guard/material/datepicker.d.ts
Labels: P3, cla: yes, pr: lgtm, pr: merge ready, pr: merge safe, target: development-branch

#18418 chore: copy v9 changelog and version bump to master
  CHANGELOG.md
  package.json
  yarn.lock
Labels: cla: yes, pr: lgtm, pr: merge ready, pr: merge safe, target: minor

#18436 build: update to latest MDC canary
  package.json
  src/material-experimental/mdc-helpers/BUILD.bazel
  yarn.lock
Labels: P2, cla: yes, pr: lgtm, pr: merge ready, pr: merge safe, target: patch

#18272 feat(material-experimental/mdc-radio): add functionality and styling
  src/dev-app/mdc-radio/BUILD.bazel
  src/dev-app/mdc-radio/mdc-radio-demo-module.ts
  src/dev-app/mdc-radio/mdc-radio-demo.html
  src/dev-app/mdc-radio/mdc-radio-demo.scss
  src/dev-app/mdc-radio/mdc-radio-demo.ts
  src/material-experimental/mdc-radio/BUILD.bazel
  src/material-experimental/mdc-radio/_mdc-radio.scss
  src/material-experimental/mdc-radio/module.ts
  src/material-experimental/mdc-radio/radio.html
  src/material-experimental/mdc-radio/radio.scss
  src/material-experimental/mdc-radio/radio.spec.ts
  src/material-experimental/mdc-radio/radio.ts
  src/material/radio/radio.ts
  tools/public_api_guard/material/radio.d.ts
Labels: cla: yes, pr: lgtm, pr: merge ready, pr: merge safe, target: minor

#18371 build: add option for running all component tests
  scripts/run-component-tests.js
Labels: cla: yes, pr: lgtm, pr: merge ready, pr: merge safe, target: patch

#18381 fix(material-experimental/mdc-form-field): notched-outline should include prefixes and suffixes
  src/dev-app/mdc-input/mdc-input-demo.html
  src/dev-app/mdc-input/mdc-input-demo.ts
  src/material-experimental/mdc-form-field/BUILD.bazel
  src/material-experimental/mdc-form-field/_mdc-text-field-structure-overrides.scss
  src/material-experimental/mdc-form-field/_mdc-text-field-textarea-overrides.scss
  src/material-experimental/mdc-form-field/directives/floating-label.ts
  src/material-experimental/mdc-form-field/form-field.html
  src/material-experimental/mdc-form-field/form-field.ts
  src/universal-app/kitchen-sink-mdc/kitchen-sink-mdc.html
Labels: P3, cla: yes, pr: lgtm, pr: merge ready, pr: merge safe, target: patch

#18397 feat(material-experimental/mdc-form-field): support for disabling animations
  src/material-experimental/mdc-form-field/form-field.scss
  src/material-experimental/mdc-form-field/form-field.ts
  src/material-experimental/mdc-input/input.spec.ts
Labels: cla: yes, pr: lgtm, pr: merge ready, pr: merge safe, target: patch

#18403 fix(material-experimental): icon/fab missing states color
  src/material-experimental/mdc-button/_mdc-button.scss
Labels: cla: yes, pr: lgtm, pr: merge ready, pr: merge safe, target: patch

#18399 feat(material-experimental/mdc-form-field): add support for accent and warn theming
  src/dev-app/mdc-input/mdc-input-demo.html
  src/dev-app/mdc-input/mdc-input-demo.ts
  src/material-experimental/mdc-form-field/_mdc-form-field.scss
  src/material-experimental/mdc-form-field/form-field.scss
Labels: cla: yes, pr: lgtm, pr: merge ready, pr: merge safe, target: patch

#18438 fix(material-experimental/mdc-form-field): scrollbar always visible on textarea in IE
  src/material-experimental/mdc-form-field/_mdc-text-field-textarea-overrides.scss
Labels: P3, cla: yes, pr: lgtm, pr: merge ready, pr: merge safe, target: patch

#18356 fix(drag-drop): error when dragging items inside transplanted views with OnPush change detection
  src/cdk/drag-drop/directives/drag.ts
Labels: P2, cla: yes, pr: lgtm, pr: merge ready, target: patch

#18439 chore: clean up remaining mixed mat/cdk table usages
  src/a11y-demo/table/table-a11y.html
  src/universal-app/kitchen-sink/kitchen-sink.html
Labels: P4, cla: yes, pr: lgtm, pr: merge ready, pr: merge safe, target: patch

#18407 fix(form-field): fix underline jank in fill variant
  src/material/form-field/form-field.scss
Labels: P1, caretaker note, cla: yes, pr: lgtm, pr: merge ready, target: patch

#18445 fix(material/list): Selection List element should not be focusable.
  src/material/list/selection-list.spec.ts
  src/material/list/selection-list.ts
  tools/public_api_guard/material/list.d.ts
Labels: P2, a11y, cla: yes, pr: lgtm, pr: merge ready, target: patch

#18446 fix(material-experimental/mdc-tabs): not disabling all animations with noop animations module
  src/material-experimental/mdc-tabs/_tabs-common.scss
  src/material-experimental/mdc-tabs/tab-header.html
  src/material-experimental/mdc-tabs/tab-nav-bar/tab-nav-bar.ts
Labels: P3, cla: yes, pr: lgtm, pr: merge ready, pr: merge safe, target: patch

#18454 fix(ng-update): avoid error if project has folder ending with style extension
  src/cdk/schematics/ng-update/test-cases/misc/global-stylesheets.spec.ts
  src/cdk/schematics/ng-update/upgrade-rules/index.ts
  src/cdk/schematics/update-tool/BUILD.bazel
  src/cdk/schematics/update-tool/index.ts
  src/cdk/schematics/utils/project-tsconfig-paths.spec.ts
  src/cdk/schematics/utils/project-tsconfig-paths.ts
Labels: P3, cla: yes, pr: lgtm, pr: merge ready, pr: merge safe, target: patch

#18457 build: update to bazel v2.1.0
  .bazelrc
  .bazelversion
  .circleci/config.yml
  WORKSPACE
  package.json
  scripts/circleci/setup_bazel_binary.sh
  tools/BUILD.bazel
  tools/bazel/BUILD.bazel
  tools/create-system-config.bzl
  tools/defaults.bzl
  tools/expand_template.bzl
  tools/postinstall/BUILD.bazel
  tools/postinstall/apply-patches.js
  tools/postinstall/flat_module_factory_resolution.patch
  tools/postinstall/manifest_externs_hermeticity.patch
  tools/postinstall/sass_worker_async.patch
  tools/postinstall/update-ngcc-main-fields.js
  yarn.lock
Labels: cla: yes, pr: lgtm, pr: merge ready, pr: merge safe, target: patch

#18481 build: make built dev-app web package writable
  scripts/deploy-dev-app.js
Labels: cla: yes, pr: lgtm, pr: merge ready, pr: merge safe, target: patch

#18483 build: temporarily disable safari 10 browserstack tests
  .circleci/config.yml
  .github/angular-robot.yml
Labels: cla: yes, pr: lgtm, pr: merge ready, pr: merge safe, target: patch

#16114 feat(column-resize): Experimental column resize for mat-table
  .github/CODEOWNERS
  src/cdk-experimental/column-resize/BUILD.bazel
  src/cdk-experimental/column-resize/column-resize-directives/column-resize-flex.ts
  src/cdk-experimental/column-resize/column-resize-directives/column-resize.ts
  src/cdk-experimental/column-resize/column-resize-directives/constants.ts
  src/cdk-experimental/column-resize/column-resize-directives/default-enabled-column-resize-flex.ts
  src/cdk-experimental/column-resize/column-resize-directives/default-enabled-column-resize.ts
  src/cdk-experimental/column-resize/column-resize-module.ts
  src/cdk-experimental/column-resize/column-resize-notifier.ts
  src/cdk-experimental/column-resize/column-resize.ts
  src/cdk-experimental/column-resize/column-size-store.ts
  src/cdk-experimental/column-resize/event-dispatcher.ts
  src/cdk-experimental/column-resize/index.ts
  src/cdk-experimental/column-resize/overlay-handle.ts
  src/cdk-experimental/column-resize/public-api.ts
  src/cdk-experimental/column-resize/resizable.ts
  src/cdk-experimental/column-resize/resize-ref.ts
  src/cdk-experimental/column-resize/resize-strategy.ts
  src/cdk-experimental/column-resize/selectors.ts
  src/cdk-experimental/config.bzl
  src/cdk-experimental/popover-edit/public-api.ts
  src/components-examples/BUILD.bazel
  src/components-examples/material-experimental/column-resize/BUILD.bazel
  src/components-examples/material-experimental/column-resize/default-enabled-flex/default-enabled-column-resize-flex-demo-module.ts
  src/components-examples/material-experimental/column-resize/default-enabled-flex/default-enabled-column-resize-flex-demo.html
  src/components-examples/material-experimental/column-resize/default-enabled-flex/default-enabled-column-resize-flex-demo.ts
  src/components-examples/material-experimental/column-resize/default-enabled/default-enabled-column-resize-demo-module.ts
  src/components-examples/material-experimental/column-resize/default-enabled/default-enabled-column-resize-demo.html
  src/components-examples/material-experimental/column-resize/default-enabled/default-enabled-column-resize-demo.ts
  src/components-examples/material-experimental/column-resize/index.ts
  src/components-examples/material-experimental/column-resize/opt-in/opt-in-column-resize-demo-module.ts
  src/components-examples/material-experimental/column-resize/opt-in/opt-in-column-resize-demo.html
  src/components-examples/material-experimental/column-resize/opt-in/opt-in-column-resize-demo.ts
  src/dev-app/BUILD.bazel
  src/dev-app/column-resize/BUILD.bazel
  src/dev-app/column-resize/column-resize-demo-module.ts
  src/dev-app/column-resize/column-resize-home.html
  src/dev-app/column-resize/column-resize-home.ts
  src/dev-app/dev-app/dev-app-layout.ts
  src/dev-app/dev-app/routes.ts
  src/dev-app/theme.scss
  src/material-experimental/column-resize/BUILD.bazel
  src/material-experimental/column-resize/_column-resize.scss
  src/material-experimental/column-resize/column-resize-directives/column-resize-flex.ts
  src/material-experimental/column-resize/column-resize-directives/column-resize.ts
  src/material-experimental/column-resize/column-resize-directives/common.ts
  src/material-experimental/column-resize/column-resize-directives/default-enabled-column-resize-flex.ts
  src/material-experimental/column-resize/column-resize-directives/default-enabled-column-resize.ts
  src/material-experimental/column-resize/column-resize-module.ts
  src/material-experimental/column-resize/column-resize.spec.ts
  src/material-experimental/column-resize/index.ts
  src/material-experimental/column-resize/overlay-handle.ts
  src/material-experimental/column-resize/public-api.ts
  src/material-experimental/column-resize/resizable-directives/common.ts
  src/material-experimental/column-resize/resizable-directives/default-enabled-resizable.ts
  src/material-experimental/column-resize/resizable-directives/resizable.ts
  src/material-experimental/column-resize/resize-strategy.ts
  src/material-experimental/config.bzl
Labels: cla: yes, pr: lgtm, pr: merge ready, pr: merge safe, target: minor

#18494 build(dev-app): prevent directory traversal
  tools/dev-server/dev-server.ts
Labels: cla: yes, pr: lgtm, pr: merge ready, pr: merge safe, target: patch

#18533 build: update to angular v9.0.1
  package.json
  yarn.lock
Labels: cla: yes, pr: lgtm, pr: merge ready, pr: merge safe, target: patch

#18527 build: bump tslint and stylelint to latest major versions
  package.json
  yarn.lock
Labels: P3, cla: yes, pr: lgtm, pr: merge ready, pr: merge safe, target: patch

#18525 fix(ng-update): better detection for workspace project in v9 hammer migration
  src/cdk/schematics/update-tool/index.ts
  src/cdk/schematics/update-tool/migration-rule.ts
  src/material/schematics/ng-update/test-cases/v9/misc/hammer-migration-v9.spec.ts
  src/material/schematics/ng-update/upgrade-rules/hammer-gestures-v9/cli-workspace.ts
  src/material/schematics/ng-update/upgrade-rules/hammer-gestures-v9/hammer-gestures-rule.ts
Labels: P3, cla: yes, pr: lgtm, pr: merge ready, pr: merge safe, target: patch

#18550 chore: remove unused webdriver-manager yarn script alias
  package.json
Labels: cla: yes, pr: lgtm, pr: merge ready, pr: merge safe, target: patch

#18547 build: do not ship load-example code to npm package
  src/components-examples/BUILD.bazel
  src/components-examples/private/BUILD.bazel
  src/components-examples/private/index.ts
  src/components-examples/private/load-example.ts
  src/components-examples/public-api.ts
  src/dev-app/example/BUILD.bazel
  src/dev-app/example/example.ts
  src/e2e-app/BUILD.bazel
  src/e2e-app/example-viewer/example-viewer.ts
  src/e2e-app/tsconfig.json
  tools/example-module/example-module.template
  tools/example-module/generate-example-module.ts
  tools/system-config-tmpl.js
Labels: P3, cla: yes, pr: lgtm, pr: merge ready, pr: merge safe, target: patch

#18554 build: do not ship load-example code to npm package [patch port]
  src/components-examples/BUILD.bazel
  src/components-examples/private/BUILD.bazel
  src/components-examples/private/index.ts
  src/components-examples/private/load-example.ts
  src/components-examples/public-api.ts
  src/dev-app/example/BUILD.bazel
  src/dev-app/example/example.ts
  src/dev-app/system-config-tmpl.js
  src/e2e-app/BUILD.bazel
  src/e2e-app/example-viewer/example-viewer.ts
  src/e2e-app/tsconfig.json
  tools/example-module/example-module.template
  tools/example-module/generate-example-module.ts
Labels: cla: yes

#18556 chore: bump version to 9.0.1 w/ changelog
  CHANGELOG.md
  package.json
Labels: cla: yes, pr: lgtm, pr: merge ready, pr: merge safe, target: patch

#18424 feat(cdk-experimental/selection): add selection state to a list of items
  .github/CODEOWNERS
  src/cdk-experimental/config.bzl
  src/cdk-experimental/selection/BUILD.bazel
  src/cdk-experimental/selection/index.ts
  src/cdk-experimental/selection/public-api.ts
  src/cdk-experimental/selection/row-selection.ts
  src/cdk-experimental/selection/select-all.ts
  src/cdk-experimental/selection/selection-column.ts
  src/cdk-experimental/selection/selection-module.ts
  src/cdk-experimental/selection/selection-set.ts
  src/cdk-experimental/selection/selection-toggle.ts
  src/cdk-experimental/selection/selection.ts
  src/components-examples/BUILD.bazel
  src/components-examples/cdk-experimental/selection/BUILD.bazel
  src/components-examples/cdk-experimental/selection/cdk-selection-column/cdk-selection-column-example.css
  src/components-examples/cdk-experimental/selection/cdk-selection-column/cdk-selection-column-example.html
  src/components-examples/cdk-experimental/selection/cdk-selection-column/cdk-selection-column-example.ts
  src/components-examples/cdk-experimental/selection/cdk-selection-list/cdk-selection-list-example.html
  src/components-examples/cdk-experimental/selection/cdk-selection-list/cdk-selection-list-example.ts
  src/components-examples/cdk-experimental/selection/index.ts
  src/dev-app/BUILD.bazel
  src/dev-app/dev-app/dev-app-layout.ts
  src/dev-app/dev-app/dev-app-module.ts
  src/dev-app/dev-app/routes.ts
  src/dev-app/example/example-list.ts
  src/dev-app/example/example-module.ts
  src/dev-app/selection/BUILD.bazel
  src/dev-app/selection/selection-demo-module.ts
  src/dev-app/selection/selection-demo.ts
Labels: G, cla: yes, pr: lgtm, pr: merge ready, target: development-branch

#18541 fix(a11y): focus trap incorrectly moving focus internally if focus was already moved into it
  src/cdk/a11y/focus-trap/event-listener-inert-strategy.spec.ts
  src/cdk/a11y/focus-trap/event-listener-inert-strategy.ts
Labels: P3, cla: yes, pr: lgtm, pr: merge ready, target: patch

#18540 fix(overlay): incorrectly calculating using minWidth and minHeight as a string
  src/cdk/overlay/position/flexible-connected-position-strategy.spec.ts
  src/cdk/overlay/position/flexible-connected-position-strategy.ts
Labels: P3, cla: yes, pr: lgtm, pr: merge ready, target: patch

#18500 build: update to MDC 5.0.0 final
  package.json
  yarn.lock
Labels: P3, cla: yes, pr: lgtm, pr: merge ready, target: patch

#18499 fix(drag-drop): not working correctly inside transplanted views
  src/cdk/drag-drop/directives/drag.spec.ts
  src/cdk/drag-drop/directives/drag.ts
  src/cdk/drag-drop/directives/drop-list.ts
  src/cdk/drag-drop/drag-ref.ts
  src/cdk/drag-drop/drop-list-ref.ts
  tools/public_api_guard/cdk/drag-drop.d.ts
Labels: P2, cla: yes, pr: lgtm, pr: merge ready, target: patch

#18485 Merge google-maps-next branch into master
  src/dev-app/google-map/google-map-demo.html
  src/dev-app/google-map/google-map-demo.ts
  src/google-maps/google-maps-module.ts
  src/google-maps/map-polygon/map-polygon.spec.ts
  src/google-maps/map-polygon/map-polygon.ts
  src/google-maps/map-polyline/map-polyline.ts
  src/google-maps/map-rectangle/map-rectangle.spec.ts
  src/google-maps/map-rectangle/map-rectangle.ts
  src/google-maps/public-api.ts
  src/google-maps/testing/fake-google-map-utils.ts
  tools/public_api_guard/google-maps/google-maps.d.ts
Labels: cla: yes, pr: lgtm, pr: merge ready, target: minor

#18468 fix(cdk/text-field): fix autofill listener on Chrome 80
  .stylelintrc.json
  src/cdk/text-field/_text-field.scss
Labels: P2, cla: yes, pr: lgtm, pr: merge ready, target: patch

#18447 test(layout): remove unneeded LayoutModule
  src/cdk/layout/media-matcher.spec.ts
Labels: cla: yes, pr: lgtm, pr: merge ready, target: minor

#18441 fix(progress-bar): changed after checked error on animation end event with noop animations
  src/material/progress-bar/progress-bar.scss
  src/material/progress-bar/progress-bar.spec.ts
  src/material/progress-bar/progress-bar.ts
Labels: P3, cla: yes, pr: lgtm, pr: merge ready, target: patch

#18419 fix(datepicker): don't call date filter function if date is out of bounds
  src/material/datepicker/month-view.spec.ts
  src/material/datepicker/month-view.ts
  src/material/datepicker/multi-year-view.spec.ts
  src/material/datepicker/year-view.spec.ts
Labels: P3, cla: yes, pr: lgtm, pr: merge ready, target: patch

#18390 fix: consistently use const enum
  src/cdk/platform/features/scrolling.ts
  src/cdk/schematics/update-tool/target-version.ts
  src/cdk/testing/test-element.ts
  src/material/checkbox/checkbox.ts
  src/material/core/ripple/ripple-ref.ts
  src/material/schematics/ng-update/upgrade-rules/hammer-gestures-v9/import-manager.ts
  tools/public_api_guard/cdk/platform.d.ts
  tools/public_api_guard/material/checkbox.d.ts
  tools/public_api_guard/material/core.d.ts
  tools/tslint-rules/preferConstEnumRule.ts
  tslint.json
Labels: P3, caretaker note, cla: yes, pr: lgtm, pr: merge ready, target: patch

#18389 fix(platform): RTL scrolling behavior detection not using cached value in some cases
  src/cdk/platform/features/scrolling.ts
Labels: P3, cla: yes, pr: lgtm, pr: merge ready, target: patch

#18376 fix(google-maps): avoid errors when accessing API too early
  src/google-maps/map-info-window/map-info-window.ts
  src/google-maps/map-marker/map-marker.ts
  src/google-maps/map-polyline/map-polyline.ts
  tools/public_api_guard/google-maps/google-maps.d.ts
Labels: P3, cla: yes, pr: lgtm, pr: merge ready, target: patch

#18362 feat(drag-drop): add option to match size of dragged element in custom preview
  src/cdk/drag-drop/directives/drag-preview.ts
  src/cdk/drag-drop/directives/drag.spec.ts
  src/cdk/drag-drop/directives/drag.ts
  src/cdk/drag-drop/drag-drop.md
  src/cdk/drag-drop/drag-ref.ts
  tools/public_api_guard/cdk/drag-drop.d.ts
Labels: P3, cla: yes, pr: lgtm, pr: merge ready, target: minor

#18336 feat(cdk/focus-trap) Backwards compatible factory create method
  src/cdk/a11y/focus-trap/configurable-focus-trap-config.ts
  src/cdk/a11y/focus-trap/configurable-focus-trap-factory.ts
  tools/public_api_guard/cdk/a11y.d.ts
Labels: cla: yes, pr: lgtm, pr: merge ready, target: minor

#18387 feat(autocomplete): add event when option is activated
  src/material/autocomplete/autocomplete.spec.ts
  src/material/autocomplete/autocomplete.ts
  tools/public_api_guard/material/autocomplete.d.ts
Labels: P3, cla: yes, pr: lgtm, pr: merge ready, target: minor

#18513 fix(selection-list): incorrectly handling A key in some cases
  src/material/list/selection-list.spec.ts
  src/material/list/selection-list.ts
Labels: P3, cla: yes, pr: lgtm, pr: merge ready, target: patch

#18564 docs(snackbar): correct docs for MatSnackbarConfig#viewContainerRef
  src/material/snack-bar/snack-bar-config.ts
Labels: cla: yes, pr: lgtm, pr: merge ready, pr: merge safe, target: patch

#18531 feat(datepicker): polish up date range selector
  src/dev-app/datepicker/datepicker-demo.html
  src/material/core/datetime/date-selection-model.ts
  src/material/datepicker/_datepicker-theme.scss
  src/material/datepicker/calendar-body.ts
  src/material/datepicker/date-range-input-parts.ts
  src/material/datepicker/date-range-input.scss
  src/material/datepicker/date-range-input.ts
  src/material/datepicker/datepicker-input-base.ts
  src/material/datepicker/datepicker-input.ts
  src/material/datepicker/multi-year-view.ts
  src/material/datepicker/year-view.ts
  tools/public_api_guard/material/datepicker.d.ts
Labels: P3, cla: yes, pr: lgtm, pr: merge ready, pr: merge safe, target: development-branch

#18521 build: use version placeholder for tslib dep in examples package
  src/components-examples/package.json
Labels: cla: yes, pr: lgtm, pr: merge ready, pr: merge safe, target: patch

#18512 build: use local bazel installation in test script watch mode
  package.json
  scripts/ibazel.js
Labels: P3, cla: yes, pr: lgtm, pr: merge ready, pr: merge safe, target: patch

#18511 chore: avoid syntax warnings in dev app on IE
  src/dev-app/index.html
Labels: P4, cla: yes, pr: lgtm, pr: merge ready, pr: merge safe, target: patch

#18510 docs(theming): removed extra only (angular#35465)
  guides/theming.md
Labels: cla: yes, docs, pr: lgtm, pr: merge ready, pr: merge safe, target: patch

#18508 fix(material-experimental/mdc-progress-bar): changed after checked error on animation end event with noop animations
  src/material-experimental/mdc-progress-bar/progress-bar.scss
  src/material-experimental/mdc-progress-bar/progress-bar.spec.ts
  src/material-experimental/mdc-progress-bar/progress-bar.ts
Labels: P3, cla: yes, pr: lgtm, pr: merge ready, pr: merge safe, target: patch

#18497 docs(youtube-player component): fix incorrect syntax
  src/youtube-player/README.md
Labels: cla: yes, commit message fixup, docs, pr: lgtm, pr: merge ready, pr: merge safe, target: patch

#18488 build: re-enable browserstack safari tests
  .circleci/config.yml
  .github/angular-robot.yml
Labels: cla: yes, pr: lgtm, pr: merge ready, pr: merge safe, target: patch

#18480 fix(material-experimental/mdc-form-field): setup typography styles for form-fields
  src/material-experimental/mdc-form-field/_mdc-form-field.scss
  src/material-experimental/mdc-form-field/_mdc-text-field-structure-overrides.scss
Labels: cla: yes, pr: lgtm, pr: merge ready, pr: merge safe, target: patch

#18470 fix(ng-update): do not throw if project does not have dependencies
  src/material/schematics/ng-update/upgrade-rules/hammer-gestures-v9/hammer-gestures-rule.ts
Labels: cla: yes, pr: lgtm, pr: merge ready, pr: merge safe, target: patch

#18383 fix(material-experimental): rename theme files to match stable components
  src/dev-app/theme.scss
  src/material-experimental/mdc-autocomplete/_autocomplete-theme.scss
  src/material-experimental/mdc-button/_button-theme.scss
  src/material-experimental/mdc-card/_card-theme.scss
  src/material-experimental/mdc-checkbox/_checkbox-theme.scss
  src/material-experimental/mdc-chips/_chips-theme.scss
  src/material-experimental/mdc-form-field/BUILD.bazel
  src/material-experimental/mdc-form-field/_form-field-theme.scss
  src/material-experimental/mdc-input/_input-theme.scss
  src/material-experimental/mdc-list/_list-theme.scss
  src/material-experimental/mdc-menu/_menu-theme.scss
  src/material-experimental/mdc-progress-bar/_progress-bar-theme.scss
  src/material-experimental/mdc-radio/_radio-theme.scss
  src/material-experimental/mdc-select/_select-theme.scss
  src/material-experimental/mdc-sidenav/_sidenav-theme.scss
  src/material-experimental/mdc-slide-toggle/_slide-toggle-theme.scss
  src/material-experimental/mdc-slider/_slider-theme.scss
  src/material-experimental/mdc-snackbar/_snackbar-theme.scss
  src/material-experimental/mdc-table/_table-theme.scss
  src/material-experimental/mdc-tabs/_tabs-theme.scss
  src/material-experimental/mdc-theming/_all-theme.scss
  src/material-experimental/mdc-typography/_all-typography.scss
  src/universal-app/theme.scss
Labels: caretaker note, cla: yes, pr: lgtm, pr: merge ready, target: patch

#18557 docs(table): fix typo
  src/material/table/table.md
Labels: cla: yes, commit message fixup, docs, pr: lgtm, pr: merge ready, pr: merge safe, target: patch

#18600 chore: fix Angular package version number
  packages.bzl
Labels: cla: yes, pr: lgtm, pr: merge ready, pr: merge safe, target: patch

#18601 chore: bump version to 9.1.0 w/ changelog
  CHANGELOG.md
  package.json
Labels: cla: yes, pr: lgtm, pr: merge ready, pr: merge safe, target: minor

#18589 build: remove ibazel workaround
  package.json
  scripts/ibazel.js
  yarn.lock
Labels: P3, cla: yes, pr: lgtm, pr: merge ready, pr: merge safe, target: patch

#18614 fix(sidenav): not restoring focus to SVG elements
  src/material/sidenav/drawer.spec.ts
  src/material/sidenav/drawer.ts
Labels: P3, cla: yes, pr: lgtm, pr: merge ready, target: patch

#18609 docs(form-field): use value getter when returning form data
  src/components-examples/material-experimental/mdc-form-field/mdc-form-field-custom-control/form-field-custom-control-example.ts
  src/components-examples/material/form-field/form-field-custom-control/form-field-custom-control-example.ts
Labels: cla: yes, commit message fixup, pr: lgtm, pr: merge ready, pr: merge safe, target: patch

#18590 fix(material-experimental/mdc-radio): use consistent ripple timings
  src/material-experimental/mdc-button/button-base.ts
  src/material-experimental/mdc-checkbox/checkbox.ts
  src/material-experimental/mdc-chips/chip.ts
  src/material-experimental/mdc-radio/BUILD.bazel
  src/material-experimental/mdc-radio/radio.html
  src/material-experimental/mdc-radio/radio.ts
  src/material-experimental/mdc-slide-toggle/slide-toggle.ts
Labels: P3, cla: yes, pr: merge ready, pr: merge safe, target: patch

#18584 fix(material-experimental/mdc-radio): able to focus disabled radio button via click
  src/material-experimental/mdc-radio/radio.spec.ts
  src/material-experimental/mdc-radio/radio.ts
Labels: P3, cla: yes, pr: merge ready, pr: merge safe, target: patch

#18566 build: remove browsersync snippet log
  tools/dev-server/dev-server.ts
Labels: P3, cla: yes, pr: lgtm, pr: merge ready, pr: merge safe, target: patch

#18588 fix(material-experimental/mdc-chips): don't allow focus on checkmark icon
  src/material-experimental/mdc-chips/chip-option.html
  src/material-experimental/mdc-chips/chip-option.spec.ts
Labels: P3, cla: yes, pr: lgtm, pr: merge ready, target: patch

#18565 refactor(dialog): remove custom injector usage
  src/material/dialog/dialog.ts
Labels: P3, cla: yes, pr: lgtm, pr: merge ready, target: patch

#18477 fix(chips): only add type attribute to button remove icons
  src/material-experimental/mdc-chips/chip-icons.ts
  src/material-experimental/mdc-chips/chip-remove.spec.ts
  src/material/chips/chip-remove.spec.ts
  src/material/chips/chip.ts
  tools/public_api_guard/material/chips.d.ts
Labels: P3, cla: yes, pr: lgtm, pr: merge ready, target: patch

#18472 fix(material-experimental/mdc-chips): align with latest MDC markup
  src/material-experimental/mdc-chips/chip.html
Labels: P3, cla: yes, pr: lgtm, pr: merge ready, target: patch

#18456 add example of a mat-table with re-orderable columns
  src/components-examples/material/table/BUILD.bazel
  src/components-examples/material/table/index.ts
  src/components-examples/material/table/table-reorderable/table-reorderable-example.css
  src/components-examples/material/table/table-reorderable/table-reorderable-example.html
  src/components-examples/material/table/table-reorderable/table-reorderable-example.ts
  src/dev-app/table/table-demo.html
Labels: G, cla: yes, docs, pr: lgtm, pr: merge ready, pr: merge safe, target: patch

#18422 fix(material-experimental/mdc-button): add base css class to all buttons
  src/material-experimental/mdc-button/button-base.ts
  src/material/dialog/dialog.scss
  src/material/expansion/expansion-panel.scss
Labels: cla: yes, pr: lgtm, pr: merge ready, target: patch

#18630 fix(datepicker): cancel current range selection when pressing escape
  src/material/datepicker/calendar-body.ts
  src/material/datepicker/month-view.ts
Labels: P3, cla: yes, pr: lgtm, pr: merge ready, pr: merge safe, target: development-branch
