Repository angular/components, pull requests merged in 2020-12, with the labels that each got.

#21167 docs(material/checkbox): use the defined color in the template (#21163)
  src/components-examples/material/checkbox/checkbox-overview/checkbox-overview-example.html
Labels: cla: yes, docs, merge ready, merge safe, target: patch

#21161 fix(cdk/schematics): fix resolving modules in ng update
  src/cdk/schematics/ng-update/devkit-file-system.ts
Labels: P3, cla: yes, merge ready, merge safe, target: patch

#21156 build: set up schematics for v12
  src/cdk/schematics/migration.json
  src/cdk/schematics/ng-update/index.ts
  src/cdk/schematics/update-tool/target-version.ts
  src/material/schematics/migration.json
  src/material/schematics/ng-update/index.ts
Labels: P3, cla: yes, merge ready, merge safe, target: patch

#21103 docs(cdk/testing): document TestElement methods
  src/cdk/testing/test-harnesses.md
Labels: cla: yes, merge ready, merge safe, target: patch

#20892 fix(material/autocomplete): add missing aria-label for autocomplete panel
  src/material-experimental/mdc-autocomplete/autocomplete.html
  src/material-experimental/mdc-autocomplete/autocomplete.spec.ts
  src/material/autocomplete/autocomplete-trigger.ts
  src/material/autocomplete/autocomplete.html
  src/material/autocomplete/autocomplete.spec.ts
  src/material/autocomplete/autocomplete.ts
  tools/public_api_guard/material/autocomplete.d.ts
Labels: G, P2, a11y, cla: yes, merge ready, target: patch

#21046 fix(material/button-toggle): fix ChromeVox focus issue on button toggle
  src/cdk/a11y/focus-trap/focus-trap.ts
  src/material/button-toggle/button-toggle.spec.ts
  src/material/button-toggle/button-toggle.ts
Labels: G, P2, a11y, caretaker note, cla: yes, merge ready, target: patch

#21059 feat(material/core): add typography config normalization function
  src/material/core/typography/_typography.scss
Labels: G, P2, cla: yes, merge ready, target: patch

#21116 fix(cdk/observers): incorrect coercion member type
  src/cdk/observers/observe-content.ts
  tools/public_api_guard/cdk/observers.d.ts
Labels: P3, cla: yes, merge ready, target: patch

#21162 feat(table): expand cell harness api
  src/material-experimental/mdc-table/testing/cell-harness.ts
  src/material/table/testing/cell-harness.ts
  tools/public_api_guard/material/table/testing.d.ts
Labels: P3, cla: yes, merge ready, target: minor

#21184 fix(material-experimental/mdc-select): fix long labels being incorrectly cut off
  src/material-experimental/mdc-select/select.scss
Labels: G, P2, cla: yes, merge ready, target: patch

#21105 fix(material-experimental/mdc-input): add autosize directive
  scripts/check-mdc-exports-config.ts
  src/material-experimental/mdc-input/autosize.ts
  src/material-experimental/mdc-input/module.ts
  src/material-experimental/mdc-input/public-api.ts
Labels: P3, cla: yes, merge ready, target: minor

#21206 docs: fix css class in custom form field control guide
  guides/creating-a-custom-form-field-control.md
Labels: cla: yes, commit message fixup, docs, merge ready, merge safe, target: patch

#21107 fix(cdk/drag-drop): preview not inheriting styles inside shadow dom
  src/cdk/drag-drop/directives/drag.spec.ts
  src/cdk/drag-drop/drag-ref.ts
Labels: P3, cla: yes, merge ready, target: patch

#21154 fix(material/radio): group selected button not set for preselected control value
  src/material-experimental/mdc-radio/radio.spec.ts
  src/material/radio/radio.spec.ts
  src/material/radio/radio.ts
Labels: P3, cla: yes, merge ready, target: patch

#21155 fix(material/slider): unable to assign min/max values if they are more precise than then step
  src/material/slider/slider.spec.ts
  src/material/slider/slider.ts
Labels: P2, cla: yes, merge ready, target: patch

#21168 fix(material-experimental/radio): include form field styles in mdc-radio theme
  src/material-experimental/mdc-radio/_radio-theme.scss
Labels: G, P2, cla: yes, merge ready, target: patch

#21175 fix(material/bottom-sheet): some changes not being picked up
  src/material/bottom-sheet/bottom-sheet-container.ts
Labels: P3, cla: yes, merge ready, target: patch

#21179 feat(cdk/table): Emit CSS classes on sticky elements that border non-…
  src/cdk/table/sticky-styler.ts
  src/cdk/table/table.spec.ts
  src/components-examples/material/table/table-sticky-columns/table-sticky-columns-example.css
  src/components-examples/material/table/table-sticky-complex-flex/table-sticky-complex-flex-example.css
  src/components-examples/material/table/table-sticky-complex/table-sticky-complex-example.css
  tools/public_api_guard/cdk/table.d.ts
Labels: G, P2, cla: yes, merge ready, target: minor

#21211 fix(material-experimental/mdc-table): Fix sticky scrolling
  src/dev-app/mdc-table/BUILD.bazel
  src/dev-app/mdc-table/mdc-table-demo-module.ts
  src/dev-app/mdc-table/mdc-table-demo.html
  src/dev-app/mdc-table/mdc-table-demo.scss
  src/dev-app/mdc-table/mdc-table-demo.ts
  src/material-experimental/mdc-table/table.scss
Labels: G, P2, cla: yes, merge ready, target: patch

#21239 release: bump version to 11.0.2 w/ changelog
  CHANGELOG.md
  package.json
  yarn.lock
Labels: cla: yes

#21240 release: bump version to 11.0.2 w/ changelog
  CHANGELOG.md
  yarn.lock
Labels: cla: yes

#21232 build: update size check goldens
  goldens/size-test.yaml
Labels: P4, cla: yes, merge ready, merge safe, target: patch

#21244 docs(changelog): clarify end of support for node-sass
  CHANGELOG.md
Labels: cla: yes, docs, merge ready, merge safe, target: patch

#21222 fix(material/expansion): not clearing custom query list
  src/material/expansion/accordion.ts
  tools/public_api_guard/material/expansion.d.ts
Labels: P3, cla: yes, merge ready, target: patch

#21231 fix(material/menu): clear static aria attributes from host node
  src/material-experimental/mdc-menu/menu.spec.ts
  src/material-experimental/mdc-menu/menu.ts
  src/material/menu/menu.spec.ts
  src/material/menu/menu.ts
Labels: P3, cla: yes, merge ready, target: patch

#21230 update on docs and comments for default option value for checkbox
  src/material-experimental/mdc-checkbox/testing/checkbox-harness.ts
  src/material/checkbox/checkbox.md
  src/material/checkbox/testing/checkbox-harness.ts
Labels: caretaker note, cla: yes, docs, merge ready, merge safe, target: minor

#21254 docs(material/checkbox): updated docs and comments for default option…
  src/material-experimental/mdc-checkbox/testing/checkbox-harness.ts
  src/material/checkbox/checkbox.md
  src/material/checkbox/testing/checkbox-harness.ts
Labels: cla: yes, merge ready, target: patch

#21229 fix(material/datepicker): screen reader not announcing view switch button value
  src/material/datepicker/calendar-header.html
  src/material/datepicker/calendar-header.spec.ts
  src/material/datepicker/calendar.ts
  tools/public_api_guard/material/datepicker.d.ts
Labels: P3, a11y, cla: yes, merge ready, target: patch

#21186 fix(cdk/a11y): set AriaDescriber messages container to visibility:hidden
  src/cdk/a11y/aria-describer/aria-describer.spec.ts
  src/cdk/a11y/aria-describer/aria-describer.ts
  tools/public_api_guard/cdk/a11y.d.ts
Labels: G, P4, a11y, cla: yes, merge ready, target: minor

#21253 fix(material/select): incorrect default typeahead debounce time
  src/material/select/select.ts
Labels: P2, cla: yes, merge ready, target: patch

#21245 fix(material-experimental/mdc-form-field): make sure fonts are loaded…
  src/material-experimental/mdc-form-field/form-field.ts
Labels: G, P2, cla: yes, merge ready, target: patch

#21243 ci: allow typography mixins to normalize config
  tools/stylelint/theme-mixin-api.ts
Labels: cla: yes, merge ready, merge safe, target: patch

#21286 refactor(material/core): make typography normalization function private
  src/material/core/typography/_typography.scss
Labels: cla: yes, merge ready, merge safe, target: patch

#21345 release: bump version to 11.0.3 w/ changelog
  CHANGELOG.md
Labels: cla: yes, merge ready, target: minor

#21344 release: bump version to 11.0.3 w/ changelog
  CHANGELOG.md
  package.json
  yarn.lock
Labels: cla: yes, merge ready, target: patch

#20758 feat(cdk/testing): support modifiers for clicking on a TestElement
  src/cdk/testing/protractor/protractor-element.ts
  src/cdk/testing/test-element.ts
  src/cdk/testing/testbed/fake-events/dispatch-events.ts
  src/cdk/testing/testbed/fake-events/event-objects.ts
  src/cdk/testing/testbed/unit-test-element.ts
  src/cdk/testing/tests/cross-environment.spec.ts
  src/cdk/testing/tests/harnesses/main-component-harness.ts
  src/cdk/testing/tests/test-main-component.html
  src/cdk/testing/tests/test-main-component.ts
  tools/public_api_guard/cdk/testing.d.ts
  tools/public_api_guard/cdk/testing/protractor.d.ts
  tools/public_api_guard/cdk/testing/testbed.d.ts
Labels: cla: yes, merge ready, target: minor

#20773 docs: fix link in DEV_ENVIRONMENT guide
  DEV_ENVIRONMENT.md
Labels: cla: yes, docs, merge ready, merge safe, target: patch

#21284 fix(material-experimental/mdc-slide-toggle): add class to mdc-switch element
  src/material-experimental/mdc-slide-toggle/slide-toggle.html
Labels: P2, cla: yes, merge ready, target: patch

#21336 docs(material/dialog): state when notification observables close
  src/material/dialog/dialog.md
Labels: cla: yes, docs, merge ready, merge safe, target: patch

#21342 build: clean up some internal deprecated API usages
  src/cdk-experimental/menu/menu.spec.ts
  test/benchmarks/cdk/testing/component-harness/protractor-benchmark-utilities.ts
  test/benchmarks/material/button/button.perf-spec.ts
  test/benchmarks/material/card/card.perf-spec.ts
  test/benchmarks/material/checkbox/checkbox.perf-spec.ts
  test/benchmarks/material/chips/chips.perf-spec.ts
  test/benchmarks/material/form-field/form-field.perf-spec.ts
  test/benchmarks/material/menu/menu.perf-spec.ts
  test/benchmarks/material/radio/radio.perf-spec.ts
  test/benchmarks/material/slide-toggle/slide-toggle.perf-spec.ts
  test/benchmarks/material/table/table.perf-spec.ts
  test/benchmarks/material/tabs/tabs.perf-spec.ts
  test/benchmarks/mdc/button/button.perf-spec.ts
  test/benchmarks/mdc/card/card.perf-spec.ts
  test/benchmarks/mdc/checkbox/checkbox.perf-spec.ts
  test/benchmarks/mdc/chips/chips.perf-spec.ts
  test/benchmarks/mdc/form-field/form-field.perf-spec.ts
  test/benchmarks/mdc/menu/menu.perf-spec.ts
  test/benchmarks/mdc/radio/radio.perf-spec.ts
  test/benchmarks/mdc/slide-toggle/slide-toggle.perf-spec.ts
  test/benchmarks/mdc/table/table.perf-spec.ts
  test/benchmarks/mdc/tabs/tabs.perf-spec.ts
Labels: P4, cla: yes, merge ready, merge safe, target: patch

#21238 build: update to latest Angular version and TypeScript 4.1
  package.json
  src/cdk/testing/change-detection.ts
  src/material/schematics/ng-update/test-cases/v9/misc/hammer-migration-v9.spec.ts
  test/browser-providers.js
  test/karma-browsers.json
  tools/package-tools/ts-compile.ts
  yarn.lock
Labels: P3, cla: yes, merge ready, merge safe, target: minor

#21360 fix(material-experimental/mdc-button): fix ripple noop animation
  src/material-experimental/mdc-button/button-base.ts
Labels: cla: yes, merge ready, target: patch

#20994 feat(material-experimental/mdc-table): add mat-table selector
  src/dev-app/mdc-table/mdc-table-demo.html
  src/material-experimental/mdc-table/BUILD.bazel
  src/material-experimental/mdc-table/cell.ts
  src/material-experimental/mdc-table/row.ts
  src/material-experimental/mdc-table/table.scss
  src/material-experimental/mdc-table/table.ts
  src/material/table/BUILD.bazel
  src/material/table/_table-flex-styles.scss
  src/material/table/table.scss
Labels: G, P2, cla: yes, merge ready, target: patch

#21176 fix(material/datepicker): adjust focused date background for better visibility
  src/material/datepicker/_datepicker-theme.scss
Labels: P3, a11y, cla: yes, merge ready, target: patch

#21265 fix(material-experimental/mdc-form-field): add padding to subscript t…
  src/material-experimental/mdc-form-field/_form-field-subscript.scss
Labels: G, P3, cla: yes, merge ready, target: minor

#21341 fix(material-experimental/mdc-select): panel losing max-height if menu is opened after select
  src/material-experimental/mdc-select/select.scss
Labels: P3, cla: yes, merge ready, target: patch

#21372 docs(material/select): update accessibility information on roles
  src/material/select/select.md
Labels: cla: yes, docs, merge ready, merge safe, target: patch

#21335 fix(cdk/scrolling): virtual scroll not picking up trackBy function when items come in after init
  src/cdk/scrolling/BUILD.bazel
  src/cdk/scrolling/virtual-for-of.ts
  src/cdk/scrolling/virtual-scroll-viewport.spec.ts
Labels: P3, cla: yes, merge ready, target: patch

#21339 fix(material/sort): animation not working correctly when activated on focus
  src/material/sort/sort-header.ts
  tools/public_api_guard/material/sort.d.ts
Labels: P3, a11y, cla: yes, merge ready, target: patch

#21383 build: adjust browserstack version
  package.json
  scripts/browserstack/start-tunnel.sh
  scripts/browserstack/stop-tunnel.sh
  scripts/browserstack/wait-tunnel.sh
  scripts/circleci/run-browserstack-tests.sh
  test/karma.conf.js
  yarn.lock
Labels: P2, cla: yes, merge ready, merge safe, target: minor

#21346 fix(cdk/drag-drop): account for enterPredicate when setting receiving class
  src/cdk/drag-drop/directives/drag.spec.ts
  src/cdk/drag-drop/drop-list-ref.ts
  tools/public_api_guard/cdk/drag-drop.d.ts
Labels: P3, cla: yes, merge ready, target: patch

#21385 build: adjust browserstack version (#21383)
  package.json
  scripts/browserstack/start-tunnel.sh
  scripts/browserstack/stop-tunnel.sh
  scripts/browserstack/wait-tunnel.sh
  scripts/circleci/run-browserstack-tests.sh
  test/karma.conf.js
  yarn.lock
Labels: cla: yes, merge ready, merge safe, target: patch

#21338 fix(material/table): unsubscribe from source when disconnecting
  src/material/table/table-data-source.spec.ts
  src/material/table/table-data-source.ts
  tools/public_api_guard/material/table.d.ts
Labels: P3, cla: yes, merge ready, target: minor

#21359 fix(material-experimental/mdc-progress-spinner): fix noop animation
  src/material-experimental/mdc-progress-spinner/progress-spinner.scss
Labels: cla: yes, merge ready, target: patch
