Repository angular/components, pull requests merged in 2020-04, with the labels that each got.

#18961 refactor: use $execpath instead of deprecated $location
  src/components-examples/BUILD.bazel
  src/material/BUILD.bazel
  tools/defaults.bzl
Labels: cla: yes, lgtm, merge ready, merge safe, target: patch

#18982 build: sanitize postinstall patch markers
  tools/postinstall/apply-patches.js
Labels: cla: yes, lgtm, merge ready, merge safe, target: patch

#18746 fix(mat-button-toggle): mat-button-toggle element should not have a focus indicator class.
  src/material/button-toggle/button-toggle.ts
Labels: G, P2, cla: yes, lgtm, merge ready, target: patch

#18906 fix(autocomplete): provide horizontal fallback positions
  src/material/autocomplete/autocomplete-trigger.ts
Labels: P3, cla: yes, lgtm, merge ready, target: patch

#18202 fix(datepicker): error in IE/Edge for static disabled binding
  src/material/datepicker/datepicker-input.ts
  tools/public_api_guard/material/datepicker.d.ts
Labels: P2, cla: yes, lgtm, merge ready, target: patch

#18969 fix(material-experimental/mdc-radio): no focus indication in high contrast mode
  src/material-experimental/mdc-radio/radio.scss
Labels: P3, cla: yes, lgtm, merge ready, merge safe, target: patch

#18968 fix(cdk-experimental/dialog): disableClose not working for template dialogs
  src/cdk-experimental/dialog/dialog.spec.ts
  src/cdk-experimental/dialog/dialog.ts
Labels: P3, cla: yes, lgtm, merge ready, merge safe, target: patch

#18985 build: add try/catch to @angular/bazel ng_module patch
  tools/postinstall/apply-patches.js
Labels: cla: yes, lgtm, merge ready, merge safe, target: patch

#19006 fix(material-experimental/mdc-chips) Replace default values
  src/material-experimental/mdc-chips/chip-grid.ts
  src/material-experimental/mdc-chips/chip.ts
Labels: G, P2, cla: yes, lgtm, merge ready, target: patch

#18967 fix(google-maps): not rendering until mapTypeId is set
  src/google-maps/google-map/google-map.spec.ts
  src/google-maps/google-map/google-map.ts
Labels: P2, cla: yes, lgtm, merge ready, target: patch

#18974 fix(material-experimental/mdc-chips): support custom errorStateMatcher
  src/material-experimental/mdc-chips/chip-grid.ts
Labels: G, P2, cla: yes, lgtm, merge ready, target: patch

#19000 fix(material-experimental/mdc-chips): align theming setup with other MDC components
  src/material-experimental/mdc-chips/_chips-theme.scss
Labels: P2, cla: yes, lgtm, merge ready, target: patch

#18983 fix(core): ripple mutating global options when animations are disabled
  src/material/core/ripple/ripple.spec.ts
  src/material/core/ripple/ripple.ts
  tools/public_api_guard/material/core.d.ts
Labels: P2, cla: yes, lgtm, merge ready, target: patch

#18323 fix(a11y): avoid errors when trying to add high contrast class
  src/cdk/a11y/high-contrast-mode/high-contrast-mode-detector.ts
Labels: P2, cla: yes, lgtm, merge ready, target: patch

#18667 perf(focus-monitor): optimize event registration
  src/cdk/a11y/focus-monitor/focus-monitor.ts
Labels: G, P2, cla: yes, lgtm, merge ready, perf, target: patch

#18981 build: add lint rule to disallow invocation of lifecycle hooks
  src/material/datepicker/calendar.ts
  tools/tslint-rules/noLifecycleInvocationRule.ts
  tslint.json
Labels: P2, cla: yes, lgtm, merge ready, target: patch

#18995 fix(datepicker): add hover indication to navigation buttons
  src/material/datepicker/calendar.scss
Labels: P3, cla: yes, lgtm, merge ready, target: patch

#18911 refactor: remove unused sass variables in non-theme files
  src/material/paginator/paginator.scss
  src/material/toolbar/toolbar.scss
Labels: P3, cla: yes, lgtm, merge ready, target: patch

#18886 fix(tabs): tab nav bar not disabling pagination animation
  src/material/tabs/tab-nav-bar/tab-nav-bar.html
Labels: P3, cla: yes, lgtm, merge ready, target: patch

#18653 fix(material-experimental/mdc-chips): enter animation not disabled when using noop animations
  src/material-experimental/mdc-chips/chips.scss
Labels: P3, cla: yes, lgtm, merge ready, target: patch

#19013 build: add MDC components to SSR kitchen sink
  src/universal-app/kitchen-sink-mdc/kitchen-sink-mdc.html
Labels: P3, cla: yes, lgtm, merge ready, merge safe, target: patch

#18826 fix(dialog): recapture focus when clicking on backdrop when closing is disabled
  src/material/dialog/dialog-container.ts
  src/material/dialog/dialog-ref.ts
  src/material/dialog/dialog.spec.ts
  src/material/dialog/dialog.ts
  tools/public_api_guard/material/dialog.d.ts
Labels: P3, a11y, cla: yes, lgtm, merge ready, target: patch

#18612 fix(drag-drop): boundary not accounting for scrolling
  src/cdk/drag-drop/client-rect.ts
  src/cdk/drag-drop/directives/drag.spec.ts
  src/cdk/drag-drop/drag-ref.ts
  src/cdk/drag-drop/drop-list-ref.ts
Labels: P3, cla: yes, lgtm, merge ready, target: patch

#18896 feat(material/icon): allow fetching icons with credentials
  src/material/icon/icon-registry.ts
  src/material/icon/icon.spec.ts
  tools/public_api_guard/material/icon.d.ts
Labels: P3, cla: yes, lgtm, merge ready, target: minor

#18135 fix(cdk/table): project colgroup and col elements
  src/cdk/table/table.spec.ts
  src/cdk/table/table.ts
  tools/public_api_guard/cdk/table.d.ts
  tools/public_api_guard/material/table.d.ts
Labels: G, P2, cla: yes, lgtm, merge ready, target: minor

#18552 fix(expansion): add strong focus indication
  src/material/expansion/expansion-panel-header.scss
  src/material/expansion/expansion-panel-header.ts
  src/material/expansion/expansion-panel.scss
  src/material/expansion/expansion.spec.ts
Labels: G, P2, cla: yes, lgtm, merge ready, target: patch

#19026 build: update to latest MDC canary version and fix error
  package.json
  src/material-experimental/mdc-helpers/BUILD.bazel
  yarn.lock
Labels: P2, cla: yes, lgtm, merge ready, merge safe, target: patch

#19031 fix(datepicker): range input label pointing to non-existent id
  src/material/datepicker/date-range-input-parts.ts
  src/material/datepicker/date-range-input.spec.ts
  src/material/datepicker/datepicker-input.ts
Labels: P3, cla: yes, lgtm, merge ready, merge safe, target: development-branch

#19023 Spelling error in CDK Drag and drop placeholder
  src/components-examples/cdk/drag-drop/cdk-drag-drop-custom-placeholder/cdk-drag-drop-custom-placeholder-example.ts
Labels: cla: yes, docs, lgtm, merge ready, merge safe, target: patch

#19021 refactor: all-typography mixin should use all-theme to avoid code duplication
  src/dev-app/theme.scss
  src/e2e-app/theme.scss
  src/material/core/_core-theme.scss
  src/material/core/_core.scss
  src/material/core/theming/_all-theme.scss
  src/material/core/theming/prebuilt/deeppurple-amber.scss
  src/material/core/theming/prebuilt/indigo-pink.scss
  src/material/core/theming/prebuilt/pink-bluegrey.scss
  src/material/core/theming/prebuilt/purple-green.scss
  src/material/core/theming/tests/BUILD.bazel
  src/material/core/theming/tests/test-theming-bundle.scss
  src/material/core/typography/_all-typography.scss
  src/material/theming-bundle.scss
  src/universal-app/theme.scss
Labels: cla: yes, lgtm, merge ready, merge safe, target: development-branch

#19019 refactor: rename MDC strong-focus indicator mixin for consistent naming
  src/dev-app/theme.scss
  src/material-experimental/mdc-helpers/_focus-indicator.scss
  src/material/core/focus-indicator/_focus-indicator.scss
Labels: cla: yes, lgtm, merge ready, merge safe, target: development-branch

#18633 perf(ripple): optimize event registration
  src/material/core/ripple/ripple-renderer.ts
  tools/public_api_guard/material/core.d.ts
Labels: G, P2, cla: yes, lgtm, merge ready, target: patch

#15214 fix(a11y): focus monitor incorrectly detecting fake mousedown from screen reader
  src/cdk/a11y/focus-monitor/focus-monitor.spec.ts
  src/cdk/a11y/focus-monitor/focus-monitor.ts
Labels: P2, a11y, cla: yes, lgtm, merge ready, target: patch

#19040 feat(material/expansion): support density scaling
  src/material-experimental/mdc-color/BUILD.bazel
  src/material-experimental/mdc-density/BUILD.bazel
  src/material/core/density/_index.scss
  src/material/core/theming/tests/BUILD.bazel
  src/material/expansion/BUILD.bazel
  src/material/expansion/_expansion-theme.scss
  src/material/expansion/_expansion-variables.scss
  src/material/expansion/expansion-animations.ts
  src/material/expansion/expansion-panel-header.scss
  src/material/expansion/expansion-panel-header.ts
  tools/public_api_guard/material/expansion.d.ts
Labels: cla: yes, lgtm, merge ready, merge safe, target: development-branch

#19073 chore: bump version to 9.2.1 w/ changelog
  CHANGELOG.md
  package.json
Labels: cla: yes, lgtm, merge ready, merge safe, target: patch

#19077 refactor(schematics): remove comments in collection.json
  src/material/schematics/collection.json
Labels: cla: yes, lgtm, merge ready, merge safe, target: patch

#19056 build: add flag for running tests with ViewEngine
  scripts/run-component-tests.js
Labels: P3, cla: yes, lgtm, merge ready, merge safe, target: patch

#19046 refactor(material-experimental): avoid unique id conflicts
  src/material-experimental/mdc-chips/chip-input.ts
  src/material-experimental/mdc-form-field/directives/error.ts
  src/material-experimental/mdc-form-field/directives/hint.ts
  src/material-experimental/mdc-form-field/form-field.ts
  src/material-experimental/mdc-slide-toggle/slide-toggle.spec.ts
  src/material-experimental/mdc-slide-toggle/slide-toggle.ts
Labels: P3, cla: yes, lgtm, merge ready, merge safe, target: patch

#19036 fix(material-experimental): better server-side rendering support for progress bar
  package.json
  src/material-experimental/mdc-checkbox/BUILD.bazel
  src/material-experimental/mdc-checkbox/checkbox.ts
  src/material-experimental/mdc-progress-bar/BUILD.bazel
  src/material-experimental/mdc-progress-bar/progress-bar.ts
  yarn.lock
Labels: P3, cla: yes, lgtm, merge ready, merge safe, target: patch

#19033 build: update to bazel v3.0.0
  .bazelversion
  WORKSPACE
Labels: cla: yes, lgtm, merge ready, merge safe, target: patch

#18987 docs(checkbox): add indeterminate and disabled checkbox examples
  src/components-examples/material/checkbox/checkbox-overview/checkbox-overview-example.css
  src/components-examples/material/checkbox/checkbox-overview/checkbox-overview-example.html
  src/components-examples/material/checkbox/checkbox-overview/checkbox-overview-example.ts
  src/components-examples/material/checkbox/index.ts
  src/dev-app/checkbox/BUILD.bazel
  src/dev-app/checkbox/checkbox-demo-module.ts
  src/dev-app/checkbox/checkbox-demo.html
Labels: cla: yes, docs, lgtm, merge ready, merge safe, target: patch

#18931 fix(material-experimental/mdc-table): not supporting multiple themes
  src/material-experimental/mdc-table/_table-theme.scss
Labels: P3, cla: yes, merge ready, merge safe, target: patch

#19097 refactor: convert new theme-mixin-api stylelint rule to typescript
  .stylelintrc.json
  tools/stylelint/theme-mixin-api.ts
Labels: cla: yes, lgtm, merge ready, merge safe, target: development-branch

#19098 fix(datepicker): allow same start and end dates for range
  src/material/datepicker/calendar-range-selection-strategy.ts
  src/material/datepicker/month-view.spec.ts
Labels: P2, cla: yes, lgtm, merge ready, merge safe, target: development-branch

#19088 feat(datepicker): allow for the preview range logic to be customized
  src/dev-app/datepicker/datepicker-demo.ts
  src/material/datepicker/calendar-body.spec.ts
  src/material/datepicker/calendar-body.ts
  src/material/datepicker/calendar-range-selection-strategy.ts
  src/material/datepicker/calendar.ts
  src/material/datepicker/month-view.html
  src/material/datepicker/month-view.spec.ts
  src/material/datepicker/month-view.ts
  tools/public_api_guard/material/datepicker.d.ts
Labels: P2, cla: yes, lgtm, merge ready, merge safe, target: development-branch

#19095 refactor: consistently re-export common module
  src/material-experimental/mdc-chips/module.ts
  src/material-experimental/mdc-menu/module.ts
  src/material-experimental/mdc-radio/module.ts
  src/material-experimental/mdc-table/module.ts
  src/material/badge/badge-module.ts
  src/material/menu/menu-module.ts
  src/material/table/table-module.ts
  src/material/tree/tree-module.ts
  tools/public_api_guard/material/badge.d.ts
  tools/public_api_guard/material/menu.d.ts
  tools/public_api_guard/material/table.d.ts
  tools/public_api_guard/material/tree.d.ts
Labels: P3, cla: yes, lgtm, merge ready, target: patch

#19099 build: bump bazelisk version and remove alias
  package.json
  yarn.lock
Labels: P3, cla: yes, lgtm, merge ready, merge safe, target: patch

#19103 fix(material-experimental/form-field): add filled MDC text field class
  package.json
  src/material-experimental/mdc-form-field/form-field.html
  yarn.lock
Labels: P3, cla: yes, lgtm, merge ready, merge safe, target: patch

#19062 fix(drag-drop): preview matchSize sometimes incorrect inside flex container
  src/cdk/drag-drop/directives/drag.spec.ts
  src/cdk/drag-drop/drag-ref.ts
Labels: P3, cla: yes, lgtm, merge ready, target: patch

#19055 fix(drag-drop): unable to start dragging in list if dragged item is destroyed
  src/cdk/drag-drop/directives/drag.spec.ts
  src/cdk/drag-drop/drop-list-ref.ts
Labels: P3, cla: yes, lgtm, merge ready, target: patch

#19052 fix(material-experimental/mdc-input): avoid double event listeners in ivy
  src/material-experimental/mdc-input/input.ts
  src/material/input/input.ts
Labels: P3, cla: yes, lgtm, merge ready, target: patch

#19051 fix(drag-drop): expose Point interface
  src/cdk/drag-drop/public-api.ts
  tools/public_api_guard/cdk/drag-drop.d.ts
Labels: P3, cla: yes, lgtm, merge ready, target: patch

#19048 fix(material-experimental/mdc-slide-toggle): strong focus indication not visible
  src/material-experimental/mdc-slide-toggle/_slide-toggle-theme.scss
  src/material-experimental/mdc-slide-toggle/slide-toggle.html
  src/material-experimental/mdc-slide-toggle/slide-toggle.scss
  src/material-experimental/mdc-slide-toggle/slide-toggle.spec.ts
Labels: P3, cla: yes, lgtm, merge ready, target: patch

#19041 docs: add matButtonModule to fix example
  src/components-examples/cdk/text-field/BUILD.bazel
  src/components-examples/cdk/text-field/index.ts
Labels: cla: yes, commit message fixup, lgtm, merge ready, target: patch

#19037 fix(tabs): group alignment propagating to nested groups
  src/material-experimental/mdc-tabs/_tabs-common.scss
  src/material-experimental/mdc-tabs/tab-header.scss
  src/material-experimental/mdc-tabs/tab-nav-bar/tab-nav-bar.scss
  src/material/tabs/_tabs-common.scss
  src/material/tabs/tab-header.scss
  src/material/tabs/tab-nav-bar/tab-nav-bar.scss
Labels: P3, cla: yes, lgtm, merge ready, target: patch

#19034 fix(dialog): incorrect dialog state for close animation
  src/material/dialog/dialog-ref.ts
  src/material/dialog/dialog.spec.ts
Labels: P3, cla: yes, lgtm, merge ready, target: patch

#19032 fix(material-experimental/mdc-radio): avoid bundling styles from base radio button
  src/material-experimental/mdc-radio/radio.ts
  src/material/radio/radio.ts
  tools/public_api_guard/material/radio.d.ts
Labels: P2, cla: yes, lgtm, merge ready, target: patch

#18885 fix(list): don't select disabled options when pressing ctrl + a
  src/material/list/selection-list.spec.ts
  src/material/list/selection-list.ts
Labels: P3, cla: yes, lgtm, merge ready, target: patch

#18797 fix(select): don't select active item when tabbing away while closed
  src/material/select/select.spec.ts
  src/material/select/select.ts
Labels: P3, cla: yes, lgtm, merge ready, target: patch

#18708 support an optional trackBy function in FlatTreeControl
  src/cdk/tree/control/base-tree-control.ts
  src/cdk/tree/control/flat-tree-control.spec.ts
  src/cdk/tree/control/flat-tree-control.ts
  src/cdk/tree/control/tree-control.ts
  tools/public_api_guard/cdk/tree.d.ts
Labels: G, P2, cla: yes, lgtm, merge ready, target: minor

#18613 feat(google-maps): expose the underlying Google Maps objects.
  package.json
  src/google-maps/google-map/google-map.spec.ts
  src/google-maps/google-map/google-map.ts
  src/google-maps/map-circle/map-circle.spec.ts
  src/google-maps/map-circle/map-circle.ts
  src/google-maps/map-info-window/map-info-window.spec.ts
  src/google-maps/map-info-window/map-info-window.ts
  src/google-maps/map-marker/map-marker.spec.ts
  src/google-maps/map-marker/map-marker.ts
  src/google-maps/map-polygon/map-polygon.spec.ts
  src/google-maps/map-polygon/map-polygon.ts
  src/google-maps/map-polyline/map-polyline.spec.ts
  src/google-maps/map-polyline/map-polyline.ts
  src/google-maps/map-rectangle/map-rectangle.spec.ts
  src/google-maps/map-rectangle/map-rectangle.ts
  src/google-maps/package.json
  src/google-maps/testing/fake-google-map-utils.ts
  tools/public_api_guard/google-maps/google-maps.d.ts
  yarn.lock
Labels: P3, cla: yes, feature, lgtm, merge ready, target: minor

#18440 fix(material-experimental/mdc-chips): not disabling all animations when animations are disabled
  src/material-experimental/mdc-chips/chip.ts
  src/material-experimental/mdc-chips/chips.scss
Labels: P3, cla: yes, lgtm, merge ready, target: patch

#17993 fix(chips): chip list disabled state out of sync when swapping out form group with a disabled one
  src/material/chips/chip-list.spec.ts
  src/material/chips/chip-list.ts
Labels: P3, cla: yes, lgtm, merge ready, target: patch

#18041 feat(table): add the ability to show a data row when no data is available
  src/cdk/table/row.ts
  src/cdk/table/table-module.ts
  src/cdk/table/table.spec.ts
  src/cdk/table/table.ts
  src/components-examples/material/table/table-filtering/table-filtering-example.html
  src/components-examples/material/table/table-overview/table-overview-example.html
  src/material-experimental/mdc-table/module.ts
  src/material-experimental/mdc-table/row.ts
  src/material-experimental/mdc-table/table.spec.ts
  src/material/table/row.ts
  src/material/table/table-module.ts
  src/material/table/table.md
  src/material/table/table.spec.ts
  tools/public_api_guard/cdk/table.d.ts
  tools/public_api_guard/material/table.d.ts
Labels: P3, cla: yes, lgtm, merge ready, target: minor

#19111 fix(datepicker): don't render invalid ranges and clean up range display logic
  src/material/datepicker/calendar-body.spec.ts
  src/material/datepicker/calendar-body.ts
  src/material/datepicker/calendar.html
  src/material/datepicker/calendar.ts
  src/material/datepicker/date-selection-model.ts
  tools/public_api_guard/material/datepicker.d.ts
Labels: P2, cla: yes, lgtm, merge ready, merge safe, target: development-branch

#18856 build: create merge script w/ cherry-picking
  merge-config.js
  package.json
  scripts/merge-script/cli.ts
  scripts/merge-script/config.ts
  scripts/merge-script/console.ts
  scripts/merge-script/failures.ts
  scripts/merge-script/git.ts
  scripts/merge-script/index.ts
  scripts/merge-script/pull-request.ts
  scripts/merge-script/strategies/api-merge.ts
  scripts/merge-script/strategies/autosquash-merge.ts
  scripts/merge-script/strategies/commit-message-filter.js
  scripts/merge-script/strategies/strategy.ts
  scripts/merge-script/string-pattern.ts
  scripts/merge-script/target-label.ts
  scripts/tsconfig.json
Labels: cla: yes, lgtm, merge ready, merge safe, target: patch

#19132 build: update to latest MDC canary and fix error
  package.json
  src/material-experimental/mdc-helpers/BUILD.bazel
  yarn.lock
Labels: P3, cla: yes, lgtm, merge ready, merge safe, target: patch

#19129 build: update to latest dev-infra package changes
  goldens/ts-circular-deps.json
  package.json
  yarn.lock
Labels: cla: yes, lgtm, merge ready, merge safe, target: patch

#19142 fix(components-examples): rename example component
  src/components-examples/material/menu/index.ts
  src/components-examples/material/menu/menu-nested/menu-nested-example.css
  src/components-examples/material/menu/menu-nested/menu-nested-example.html
  src/components-examples/material/menu/menu-nested/menu-nested-example.ts
  src/components-examples/material/menu/nested-menu/nested-menu-example.ts
  src/material/menu/menu.md
Labels: cla: yes, docs, lgtm, merge ready, merge safe, target: patch

#19140 fix(material-experimental/mdc-form-field): missing styles for native select control
  src/material-experimental/mdc-form-field/BUILD.bazel
  src/material-experimental/mdc-form-field/_form-field-native-select.scss
  src/material-experimental/mdc-form-field/form-field.scss
Labels: cla: yes, lgtm, merge ready, merge safe, target: patch

#19114 fix(autocomplete/testing): incorrect options if multiple panels are on the page at the same time
  src/material/autocomplete/testing/autocomplete-harness.ts
  src/material/autocomplete/testing/shared.spec.ts
Labels: P3, cla: yes, lgtm, merge ready, target: patch

#19108 fix(drag-drop): boundary not accounting for parent scrolling
  src/cdk/drag-drop/directives/drag.spec.ts
  src/cdk/drag-drop/drag-ref.ts
  src/cdk/drag-drop/drop-list-ref.ts
  src/cdk/drag-drop/parent-position-tracker.ts
  tools/public_api_guard/cdk/drag-drop.d.ts
Labels: P3, cla: yes, lgtm, merge ready, target: patch

#19112 fix(select/testing): incorrect options if multiple selects are on the page at the same time
  src/material/select/select.html
  src/material/select/testing/select-harness.ts
  src/material/select/testing/shared.spec.ts
Labels: P3, cla: yes, lgtm, merge ready, target: patch

#18442 fix(button-toggle): static checked value not being picked up
  src/material/button-toggle/button-toggle.spec.ts
  src/material/button-toggle/button-toggle.ts
Labels: P3, cla: yes, lgtm, merge ready, target: patch

#17732 fix(datepicker): inconsistent focus restoration timing in touchUi mode
  src/material/datepicker/datepicker.spec.ts
  src/material/datepicker/datepicker.ts
Labels: P3, cla: yes, lgtm, merge ready, target: patch

#19143 Map overlay
  src/dev-app/google-map/google-map-demo.html
  src/dev-app/google-map/google-map-demo.ts
  src/google-maps/google-maps-module.ts
  src/google-maps/map-ground-overlay/map-ground-overlay.spec.ts
  src/google-maps/map-ground-overlay/map-ground-overlay.ts
  src/google-maps/public-api.ts
  src/google-maps/testing/fake-google-map-utils.ts
  tools/public_api_guard/google-maps/google-maps.d.ts
Labels: cla: yes, commit message fixup, lgtm, merge ready, target: minor

#19141 build: include mdc-color and mdc-density entry-points in release
  src/material-experimental/BUILD.bazel
  src/material-experimental/mdc-color/BUILD.bazel
  src/material-experimental/mdc-density/BUILD.bazel
Labels: P2, cla: yes, lgtm, merge ready, merge safe, target: development-branch

#19124 fix(platform): avoid errors if ShadowRoot is not defined
  src/cdk/platform/features/shadow-dom.ts
Labels: G, P2, cla: yes, lgtm, merge ready, target: patch

#19159 build: do not print github auth token if merge script fails
  scripts/merge-script/cli.ts
  scripts/merge-script/failures.ts
  scripts/merge-script/git.ts
  scripts/merge-script/pull-request.ts
  scripts/merge-script/strategies/api-merge.ts
Labels: cla: yes, lgtm, merge ready, merge safe, target: patch

#19161 build: fix ngcc compatibility jobs not running against packages
  .circleci/config.yml
Labels: P2, cla: yes, lgtm, merge ready, merge safe, target: patch

#19151 refactor: cleanup fake event dispatch utilities
  src/cdk/testing/testbed/fake-events/dispatch-events.ts
  src/cdk/testing/testbed/fake-events/event-objects.ts
  src/material-experimental/mdc-menu/menu.spec.ts
  src/material/menu/menu.spec.ts
Labels: cla: yes, lgtm, merge ready, target: patch

#18991 fix(tree): complete viewChange stream on destroy
  src/cdk/tree/tree.spec.ts
  src/cdk/tree/tree.ts
Labels: P4, cla: yes, lgtm, merge ready, target: patch

#16869 fix(tabs): unnecessarily adding pagination when changing to new list of tabs with same labels
  src/material/tabs/paginated-tab-header.ts
  src/material/tabs/tab-nav-bar/tab-nav-bar.spec.ts
Labels: P3, cla: yes, lgtm, merge ready, target: patch

#16698 feat(datepicker): allow for the dropdown position to be customized
  src/material/datepicker/datepicker.spec.ts
  src/material/datepicker/datepicker.ts
  tools/public_api_guard/material/datepicker.d.ts
Labels: P3, cla: yes, lgtm, merge ready, target: minor

#18996 fix(youtube-player): unable to bind to events after initialization
  src/youtube-player/BUILD.bazel
  src/youtube-player/fake-youtube-player.ts
  src/youtube-player/youtube-player.spec.ts
  src/youtube-player/youtube-player.ts
  tools/public_api_guard/youtube-player/youtube-player.d.ts
Labels: P3, cla: yes, lgtm, merge ready, merge safe, target: patch

#19064 refactor(scrolling): add dedicated module for CdkScrollable
  src/cdk/drag-drop/directives/drag.spec.ts
  src/cdk/drag-drop/drag-drop-module.ts
  src/cdk/scrolling/scrolling-module.ts
  src/material-experimental/mdc-menu/BUILD.bazel
  src/material-experimental/mdc-menu/module.ts
  src/material/autocomplete/autocomplete-module.ts
  src/material/datepicker/datepicker-module.ts
  src/material/menu/BUILD.bazel
  src/material/menu/menu-module.ts
  src/material/select/select-module.ts
  src/material/sidenav/sidenav-module.ts
  src/material/tooltip/tooltip-module.ts
  tools/public_api_guard/cdk/drag-drop.d.ts
  tools/public_api_guard/cdk/scrolling.d.ts
  tools/public_api_guard/material/autocomplete.d.ts
  tools/public_api_guard/material/datepicker.d.ts
  tools/public_api_guard/material/menu.d.ts
  tools/public_api_guard/material/select.d.ts
  tools/public_api_guard/material/sidenav.d.ts
  tools/public_api_guard/material/tooltip.d.ts
Labels: P2, cla: yes, lgtm, merge ready, target: patch

#19135 fix(a11y): focus monitor not working inside shadow dom
  src/cdk/a11y/focus-monitor/focus-monitor.ts
Labels: P2, a11y, cla: yes, lgtm, merge ready, target: patch

#19165 test(material-experimental/mdc-tabs): fix failing tests
  src/material-experimental/mdc-tabs/tab-nav-bar/tab-nav-bar.spec.ts
Labels: P3, cla: yes, lgtm, merge ready, merge safe, target: patch

#19166 fix(google-maps): incorrect variable access for server-side rendering check
  src/google-maps/map-info-window/map-info-window.ts
Labels: cla: yes, lgtm, merge ready, target: patch

#19174 fix(datepicker): changed after checked error when moving preview between months
  src/material/datepicker/calendar-body.ts
  src/material/datepicker/month-view.ts
  tools/public_api_guard/material/datepicker.d.ts
Labels: P2, cla: yes, lgtm, merge ready, merge safe, target: development-branch

#19179 fix(datepicker): clearing completed range when pressing escape
  src/material/datepicker/month-view.spec.ts
  src/material/datepicker/month-view.ts
Labels: P2, cla: yes, lgtm, merge ready, merge safe, target: development-branch

#19176 fix(datepicker): end input reset on load when bound through ngModel
  src/material/datepicker/date-range-input-parts.ts
  src/material/datepicker/date-range-input.spec.ts
Labels: P2, cla: yes, lgtm, merge ready, merge safe, target: development-branch

#19187 fix(datepicker): change event dispatched before value is formatted
  src/material/datepicker/datepicker-input-base.ts
  src/material/datepicker/datepicker.spec.ts
Labels: P2, cla: yes, lgtm, merge ready, merge safe, target: development-branch

#19196 build: dev-infra-private package not updating locally as expected
  package.json
  yarn.lock
Labels: P3, cla: yes, lgtm, merge ready, merge safe, target: patch

#19188 build: add server-side rendering check for ground overlay
  src/universal-app/kitchen-sink/kitchen-sink.html
Labels: P4, cla: yes, lgtm, merge ready, merge safe, target: patch

#19181 chore(cdk/a11y): fix contrast spelling
  src/cdk/a11y/aria-describer/aria-reference.spec.ts
  src/cdk/a11y/aria-describer/aria-reference.ts
  src/cdk/a11y/high-contrast-mode/high-contrast-mode-detector.ts
Labels: cla: yes, commit message fixup, docs, lgtm, merge ready, merge safe, target: patch

#19199 fix(overlay): expand flexible origin type to allow SVG elements
  src/cdk/overlay/position/flexible-connected-position-strategy.ts
  tools/public_api_guard/cdk/overlay.d.ts
Labels: P3, cla: yes, lgtm, merge ready, target: patch

#19169 fix(material-experimental/mdc-button): strong focus indication always visible on fab buttons
  src/material-experimental/mdc-button/button-base.ts
  src/material-experimental/mdc-button/button.html
  src/material-experimental/mdc-button/button.spec.ts
  src/material-experimental/mdc-helpers/_mdc-helpers.scss
Labels: P3, cla: yes, lgtm, merge ready, target: patch

#19116 fix(drag-drop): drop-list wrong enter position
  src/cdk/drag-drop/directives/drag.spec.ts
  src/cdk/drag-drop/drop-list-ref.ts
  src/dev-app/drag-drop/drag-drop-demo.html
  src/dev-app/drag-drop/drag-drop-demo.scss
  src/dev-app/drag-drop/drag-drop-demo.ts
Labels: P3, cla: yes, lgtm, merge ready, target: patch

#19211 fix(datepicker): user selection event not emitting value when clicking on the selected date
  src/material/datepicker/month-view.spec.ts
  src/material/datepicker/month-view.ts
Labels: P2, cla: yes, lgtm, merge ready, merge safe, target: development-branch

#19185 build: update to rules_nodejs 1.6.0
  WORKSPACE
  package.json
  src/dev-app/BUILD.bazel
  tools/es5-named-output.bzl
  tools/postinstall/apply-patches.js
  tools/postinstall/manifest_externs_hermeticity.patch
  yarn.lock
Labels: P3, cla: yes, lgtm, merge ready, target: patch

#19214 chore: bump version to 9.2.2 w/ changelog
  CHANGELOG.md
  package.json
Labels: cla: yes, lgtm, merge ready, merge safe, target: patch
