Repository angular/components, pull requests merged in 2020-08, with the labels that each got.

#20168 chore: bump version to 10.1.2 w/ changelog
  CHANGELOG.md
  package.json
Labels: cla: yes, merge ready, merge safe, target: patch

#20032 test(mdc-button): add performance tests for mdc-button
  src/material-experimental/mdc-theming/BUILD.bazel
  src/material-experimental/mdc-theming/_all-theme.scss
  src/material-experimental/mdc-theming/prebuilt/indigo-pink.scss
  test/benchmarks/mdc/button/BUILD.bazel
  test/benchmarks/mdc/button/app.module.ts
  test/benchmarks/mdc/button/button.perf-spec.ts
Labels: G, P2, cla: yes, merge ready, target: patch

#20201 build: fix release output containing invalid imports sometimes
  tools/postinstall/@bazel_typescript_tsc_wrapped_worker_cache_fix.patch
  tools/postinstall/apply-patches.js
Labels: P2, cla: yes, merge ready, merge safe, target: patch

#20183 docs(material/button-toggle): update a11y section
  src/material/button-toggle/button-toggle.md
Labels: P2, a11y, cla: yes, docs, merge ready, merge safe, target: patch

#20191 chore: clean up unnecessary providers arrays from existing code
  src/material/bottom-sheet/bottom-sheet.md
  src/material/dialog/dialog.md
  test/benchmarks/material/button/app.module.ts
  test/benchmarks/material/card/app.module.ts
  test/benchmarks/material/checkbox/app.module.ts
  test/benchmarks/material/chips/app.module.ts
  test/benchmarks/material/form-field/app.module.ts
  test/benchmarks/material/radio/app.module.ts
  test/benchmarks/material/slide-toggle/app.module.ts
  test/benchmarks/material/table/app.module.ts
  test/benchmarks/mdc/card/app.module.ts
Labels: P3, cla: yes, merge ready, merge safe, target: patch

#20180 docs: add readme for MDC-based experimental dialog
  src/material-experimental/mdc-dialog/README.md
Labels: P3, cla: yes, docs, merge ready, merge safe, target: minor

#20195 docs(cdk/scrolling): make ScrollingModule the primary export (#20112)
  src/cdk/scrolling/scrolling-module.ts
Labels: cla: yes, docs, merge ready, merge safe, target: patch

#20156 test: clean up remaining dynamic query usages
  src/cdk/a11y/focus-trap/focus-trap.spec.ts
  src/cdk/drag-drop/directives/drag.spec.ts
  src/cdk/portal/portal.md
  src/cdk/portal/portal.spec.ts
  src/dev-app/portal/portal-demo.ts
  src/google-maps/README.md
  src/material-experimental/column-resize/column-resize.spec.ts
  src/material-experimental/mdc-menu/menu.spec.ts
  src/material/expansion/accordion.spec.ts
  src/material/menu/menu.spec.ts
Labels: P3, cla: yes, merge ready, merge safe, target: patch

#20178 refactor(cdk-experimental/dialog): sync with recent material dialog changes
  src/cdk-experimental/dialog/dialog-container.ts
  src/cdk-experimental/dialog/dialog.ts
Labels: cla: yes, merge ready, merge safe, target: minor

#20173 fix(cdk-experimental/menu): re-open menu on hover after click to close on trigger
  src/cdk-experimental/menu/menu-bar.spec.ts
  src/cdk-experimental/menu/menu-item-trigger.ts
Labels: cla: yes, merge ready, merge safe, target: minor

#20171 feat(cdk-experimental/menu): enable keyboard handling for context menu
  src/cdk-experimental/menu/context-menu.spec.ts
  src/cdk-experimental/menu/context-menu.ts
Labels: cla: yes, merge ready, merge safe, target: minor

#20167 build: swap patch & major options in release stage tool
  tools/release/prompt/new-version-prompt.ts
Labels: cla: yes, merge ready, merge safe, target: patch

#20164 refactor(cdk-experimental/menu): move listeners from host object to host listener decorator
  src/cdk-experimental/menu/menu-bar.ts
  src/cdk-experimental/menu/menu-item-checkbox.ts
  src/cdk-experimental/menu/menu-item-radio.ts
  src/cdk-experimental/menu/menu.ts
Labels: cla: yes, merge ready, merge safe, target: minor

#20086 fix,perf(column-resize): Coalesce style updates along with sticky styler
  src/cdk-experimental/column-resize/column-resize-directives/column-resize-flex.ts
  src/cdk-experimental/column-resize/column-resize-directives/column-resize.ts
  src/cdk-experimental/column-resize/column-resize-directives/default-enabled-column-resize-flex.ts
  src/cdk-experimental/column-resize/column-resize-directives/default-enabled-column-resize.ts
  src/cdk-experimental/column-resize/column-resize-notifier.ts
  src/cdk-experimental/column-resize/overlay-handle.ts
  src/cdk-experimental/column-resize/resizable.ts
  src/cdk-experimental/column-resize/resize-strategy.ts
  src/cdk/table/coalesced-style-scheduler.ts
  src/components-examples/material-experimental/column-resize/default-enabled-column-resize-flex/default-enabled-column-resize-flex-example.html
  src/components-examples/material-experimental/column-resize/default-enabled-column-resize/default-enabled-column-resize-example.html
  src/components-examples/material-experimental/column-resize/opt-in-column-resize/opt-in-column-resize-example.html
  src/material-experimental/column-resize/BUILD.bazel
  src/material-experimental/column-resize/_column-resize.scss
  src/material-experimental/column-resize/column-resize.spec.ts
  src/material-experimental/column-resize/overlay-handle.ts
  src/material-experimental/column-resize/resizable-directives/default-enabled-resizable.ts
  src/material-experimental/column-resize/resizable-directives/resizable.ts
  src/material-experimental/column-resize/resize-strategy.ts
Labels: G, P2, cla: yes, commit message fixup, merge ready, perf, target: patch

#19801 perf(table): Do column name string interpolation once per column instead of once per cell
  src/cdk/table/cell.ts
  src/material-experimental/mdc-table/cell.ts
  src/material/table/cell.ts
  tools/public_api_guard/cdk/table.d.ts
  tools/public_api_guard/material/table.d.ts
Labels: G, cla: yes, merge ready, target: patch

#20136 fix: add non-null assertions for non-nullable input bindings
  src/dev-app/datepicker/datepicker-demo.html
  src/dev-app/stepper/stepper-demo.html
  src/material/paginator/paginator.html
  src/material/select/select.html
Labels: cla: yes, merge ready, target: minor

#20206 Revert "build: fix release output containing invalid imports sometimes"
  tools/postinstall/@bazel_typescript_tsc_wrapped_worker_cache_fix.patch
  tools/postinstall/apply-patches.js
Labels: cla: yes, merge ready, merge safe, target: patch

#20185 Combobox skeleton
  .github/CODEOWNERS
  src/cdk-experimental/combobox/BUILD.bazel
  src/cdk-experimental/combobox/combobox-module.ts
  src/cdk-experimental/combobox/combobox-panel.ts
  src/cdk-experimental/combobox/combobox.ts
  src/cdk-experimental/combobox/index.ts
  src/cdk-experimental/combobox/public-api.ts
  src/cdk-experimental/config.bzl
Labels: cla: yes, commit message fixup, merge ready, merge safe, target: minor

#20202 build: update to latest angular version and cleanup postinstall patch
  package.json
  tools/postinstall/@angular_bazel_ivy_flat_module.patch
  tools/postinstall/@angular_bazel_ng_module.patch
  tools/postinstall/apply-patches.js
  yarn.lock
Labels: cla: yes, merge ready, merge safe, target: patch

#20143 feat(cdk-experimental/menu): add support for inline menus
  src/cdk-experimental/menu/menu-errors.ts
  src/cdk-experimental/menu/menu-stack.ts
  src/cdk-experimental/menu/menu.spec.ts
  src/cdk-experimental/menu/menu.ts
  src/cdk-experimental/menu/public-api.ts
Labels: cla: yes, merge ready, merge safe, target: minor

#20208 build: fix compilation error with latest MDC canary
  package.json
  src/material-experimental/mdc-slider/slider.ts
  yarn.lock
Labels: P3, cla: yes, merge ready, merge safe, target: patch

#17818 fix(material/tree): Apply aria-level to all nodes
  src/cdk/tree/tree.spec.ts
  src/cdk/tree/tree.ts
  src/material/tree/node.ts
  src/material/tree/tree.spec.ts
  tools/public_api_guard/cdk/tree.d.ts
Labels: G, P2, a11y, cla: yes, merge ready, target: patch

#19823 perf(table): Slightly improve speed of adding/remvoing sticky styles
  src/cdk/table/sticky-styler.ts
  src/cdk/table/table.ts
  src/material-experimental/mdc-table/BUILD.bazel
  src/material-experimental/mdc-table/table.scss
  src/material-experimental/mdc-table/table.ts
  src/material/core/style/_vendor-prefixes.scss
  src/material/table/BUILD.bazel
  src/material/table/table.scss
  src/material/table/table.ts
  tools/public_api_guard/cdk/table.d.ts
  tools/public_api_guard/material/table.d.ts
Labels: G, P2, cla: yes, merge ready, target: patch

#16809 fix(stepper): remove tabindex from content
  src/material/stepper/stepper-horizontal.html
  src/material/stepper/stepper-vertical.html
  src/material/stepper/stepper.spec.ts
Labels: P2, a11y, cla: yes, merge ready, target: patch

#17791 fix(cdk/overlay): fix wrong overflow calculation
  src/cdk/overlay/position/flexible-connected-position-strategy.ts
  src/material-experimental/popover-edit/popover-edit.spec.ts
Labels: P2, cla: yes, merge ready, needs rebase, target: patch

#20131 test(mdc-chips): add performance tests for mdc-chips
  test/benchmarks/mdc/chips/BUILD.bazel
  test/benchmarks/mdc/chips/app.module.ts
  test/benchmarks/mdc/chips/chips.html
  test/benchmarks/mdc/chips/chips.perf-spec.ts
Labels: cla: yes, merge ready, merge safe, target: patch

#20132 test(mdc-radio): add performance tests for mdc-radio
  test/benchmarks/mdc/radio/BUILD.bazel
  test/benchmarks/mdc/radio/app.module.ts
  test/benchmarks/mdc/radio/radio.perf-spec.ts
Labels: cla: yes, merge ready, merge safe, target: patch

#20133 test(mdc-slide-toggle): add performance tests for mdc-slide-toggle
  test/benchmarks/mdc/slide-toggle/BUILD.bazel
  test/benchmarks/mdc/slide-toggle/app.module.ts
  test/benchmarks/mdc/slide-toggle/slide-toggle.perf-spec.ts
Labels: cla: yes, merge ready, merge safe, target: patch

#20135 test(mdc-form-field): add performance tests for mdc-form-field
  test/benchmarks/mdc/button/button.perf-spec.ts
  test/benchmarks/mdc/form-field/BUILD.bazel
  test/benchmarks/mdc/form-field/app.module.ts
  test/benchmarks/mdc/form-field/form-field.perf-spec.ts
Labels: cla: yes, merge ready, merge safe, target: patch

#20261 chore: bump version to 10.1.3 w/ changelog
  CHANGELOG.md
  package.json
Labels: cla: yes, merge ready, merge safe, target: patch

#20264 doc(stepper): add missing doc region
  src/components-examples/material/stepper/stepper-overview/stepper-overview-example.html
Labels: P3, cla: yes, merge ready, merge safe, target: patch

#20102 fix(datepicker): not showing single-day comparison ranges
  src/material/datepicker/_datepicker-theme.scss
  src/material/datepicker/calendar-body.html
  src/material/datepicker/calendar-body.spec.ts
  src/material/datepicker/calendar-body.ts
  tools/public_api_guard/material/datepicker.d.ts
Labels: P2, cla: yes, merge ready, target: patch

#19914 fix(datepicker): range selection strategy not picking up custom date adapter
  src/material/datepicker/date-range-picker.ts
  src/material/datepicker/date-range-selection-strategy.ts
  src/material/datepicker/datepicker-module.ts
  src/material/datepicker/public-api.ts
Labels: P2, cla: yes, merge ready, target: patch

#18458 fix(stepper): parent stepper picking up steps from child stepper
  src/cdk/stepper/stepper.ts
  src/material/stepper/stepper.spec.ts
  src/material/stepper/stepper.ts
  tools/public_api_guard/cdk/stepper.d.ts
  tools/public_api_guard/material/stepper.d.ts
Labels: P2, cla: yes, merge ready, target: patch

#20267 refactor(cdk-experimental/menu): rename cdk selectable output and add cdk specific output naming
  src/cdk-experimental/menu/menu-group.ts
  src/cdk-experimental/menu/menu-item-checkbox.spec.ts
  src/cdk-experimental/menu/menu-item-radio.spec.ts
  src/cdk-experimental/menu/menu-item-selectable.ts
Labels: cla: yes, merge ready, merge safe, target: minor

#20259 fix(cdk-experimental/menu): fix double state toggle in radio and checkbox menu items
  src/cdk-experimental/menu/menu-item-checkbox.spec.ts
  src/cdk-experimental/menu/menu-item-checkbox.ts
  src/cdk-experimental/menu/menu-item-radio.spec.ts
  src/cdk-experimental/menu/menu-item-radio.ts
Labels: cla: yes, merge ready, merge safe, target: minor

#20257 docs: update reviews guide to remove lgtm label
  CODE_REVIEWS.md
Labels: P4, cla: yes, merge ready, merge safe, target: patch

#20253 docs(datepicker): add link to date implementation at the top
  src/material/datepicker/datepicker.md
Labels: cla: yes, docs, merge ready, merge safe, target: patch

#20251 docs(mdc-chips): incorrect closing tag
  src/material-experimental/mdc-chips/README.md
Labels: cla: yes, docs, merge ready, merge safe, target: patch

#20241 fix(cdk-experimental/menu): ensure menu is closed out when clicking on an inline menu item
  src/cdk-experimental/menu/menu-bar.spec.ts
  src/cdk-experimental/menu/menu-bar.ts
  src/cdk-experimental/menu/menu.ts
Labels: cla: yes, merge ready, merge safe, target: minor

#20238 perf(column-resize): Further defer initial min/max column size applic…
  src/cdk-experimental/column-resize/resizable.ts
Labels: caretaker note, cla: yes, merge ready, merge safe, target: patch

#20235 feat(cdk-experimental/menu): add roving tab index to menu items
  src/cdk-experimental/menu/menu-bar.spec.ts
  src/cdk-experimental/menu/menu-item-checkbox.ts
  src/cdk-experimental/menu/menu-item-radio.ts
  src/cdk-experimental/menu/menu-item.ts
Labels: cla: yes, merge ready, merge safe, target: minor

#20231 docs(tree): fix typo in tree template
  src/components-examples/cdk/tree/cdk-tree-flat/cdk-tree-flat-example.html
  src/components-examples/cdk/tree/cdk-tree-nested/cdk-tree-nested-example.html
  src/components-examples/material/tree/tree-checklist/tree-checklist-example.html
  src/components-examples/material/tree/tree-dynamic/tree-dynamic-example.html
  src/components-examples/material/tree/tree-flat-overview/tree-flat-overview-example.html
  src/components-examples/material/tree/tree-loadmore/tree-loadmore-example.html
  src/components-examples/material/tree/tree-nested-overview/tree-nested-overview-example.html
  src/material/schematics/ng-generate/tree/files/__path__/__name@dasherize@if-flat__/__name@dasherize__.component.html.template
Labels: P3, cla: yes, docs, merge ready, merge safe, target: patch

#20228 refactor(cdk-experimental/menu): refactor the dev-app to include context menu and inline menu
  src/dev-app/cdk-experimental-menu/cdk-menu-demo.css
  src/dev-app/cdk-experimental-menu/cdk-menu-demo.html
Labels: cla: yes, merge ready, merge safe, target: minor

#20221 fix(mdc-button-benchmark): fix unresolved merge conflict
  test/benchmarks/mdc/button/button.perf-spec.ts
Labels: P2, cla: yes, merge ready, merge safe, target: patch

#20214 build: fix release output containing invalid imports sometimes
  tools/postinstall/@bazel_typescript_tsc_wrapped_worker_cache_fix.patch
  tools/postinstall/apply-patches.js
Labels: P2, cla: yes, merge ready, merge safe, target: patch

#20211 Combobox base
  src/cdk-experimental/combobox/BUILD.bazel
  src/cdk-experimental/combobox/combobox-module.ts
  src/cdk-experimental/combobox/combobox-panel.ts
  src/cdk-experimental/combobox/combobox.spec.ts
  src/cdk-experimental/combobox/combobox.ts
  src/cdk-experimental/combobox/public-api.ts
Labels: cla: yes, commit message fixup, merge ready, merge safe, target: minor

#20198 build: create script for building docs-content
  .circleci/config.yml
  package.json
  scripts/build-docs-content.js
  scripts/deploy/publish-docs-content.sh
Labels: cla: yes, merge ready, merge safe, target: patch

#20151 test(menu): add performance tests for mat-menu
  test/benchmarks/material/menu/BUILD.bazel
  test/benchmarks/material/menu/app.module.ts
  test/benchmarks/material/menu/menu.html
  test/benchmarks/material/menu/menu.perf-spec.ts
Labels: cla: yes, merge ready, merge safe, target: patch

#20134 test(mdc-table): add performance tests for mdc-table
  test/benchmarks/mdc/table/BUILD.bazel
  test/benchmarks/mdc/table/app.module.html
  test/benchmarks/mdc/table/app.module.ts
  test/benchmarks/mdc/table/basic-table.ts
  test/benchmarks/mdc/table/fake-table-data.ts
  test/benchmarks/mdc/table/table.perf-spec.ts
Labels: cla: yes, merge ready, merge safe, target: patch

#19977 refactor(table-benchmark): move template to a separate html file
  test/benchmarks/material/table/BUILD.bazel
  test/benchmarks/material/table/app.module.ts
  test/benchmarks/material/table/basic-table.html
  test/benchmarks/material/table/basic-table.ts
  test/benchmarks/material/table/table-app.html
Labels: cla: yes, merge ready, merge safe, target: patch

#19752 test(tabs): add performance tests for mat-tabs
  test/benchmarks/material/tabs/BUILD.bazel
  test/benchmarks/material/tabs/app.module.ts
  test/benchmarks/material/tabs/fake-tab-data.ts
  test/benchmarks/material/tabs/tabs.perf-spec.ts
Labels: cla: yes, merge ready, merge safe, target: patch

#18218 chore: store dev-app dark/light theme state in localStorage
  src/dev-app/dev-app/dev-app-layout.html
  src/dev-app/dev-app/dev-app-layout.ts
Labels: P2, area: dev-infra, cla: yes, merge ready, merge safe, target: patch

#20244 docs(datepicker): fix various missing words
  src/material/datepicker/datepicker.md
Labels: cla: yes, merge ready, merge safe, target: patch

#20243 chore: clean up leftover tslint disable statements
  src/material/core/option/optgroup.ts
  src/material/core/option/option.ts
  src/material/dialog/dialog-container.ts
  src/material/dialog/dialog.ts
  src/material/snack-bar/snack-bar-container.ts
Labels: P4, cla: yes, merge ready, merge safe, target: minor

#20272 test(cdk-experimental/menu): fix test failure
  src/cdk-experimental/menu/menu-bar.spec.ts
Labels: P3, cla: yes, merge safe, target: patch

#20232 fix(dialog): backdrop not detaching if container view is destroyed
  src/material-experimental/mdc-dialog/dialog.spec.ts
  src/material/dialog/dialog-container.ts
  src/material/dialog/dialog.spec.ts
Labels: P2, cla: yes, merge ready, target: minor

#20224 fix: remove element selectors from test harnesses
  src/material-experimental/mdc-checkbox/testing/checkbox-harness.ts
  src/material-experimental/mdc-chips/chip-option.ts
  src/material-experimental/mdc-chips/chip-row.ts
  src/material-experimental/mdc-chips/testing/chip-grid-harness.ts
  src/material-experimental/mdc-chips/testing/chip-harness.ts
  src/material-experimental/mdc-chips/testing/chip-listbox-harness.ts
  src/material-experimental/mdc-chips/testing/chip-option-harness.ts
  src/material-experimental/mdc-chips/testing/chip-row-harness.ts
  src/material-experimental/mdc-chips/testing/chip-set-harness.ts
  src/material-experimental/mdc-progress-bar/testing/progress-bar-harness.ts
  src/material-experimental/mdc-progress-spinner/testing/progress-spinner-harness.ts
  src/material-experimental/mdc-slide-toggle/testing/slide-toggle-harness.ts
  src/material-experimental/mdc-slider/testing/slider-harness.ts
  src/material/button-toggle/testing/button-toggle-group-harness.ts
  src/material/button-toggle/testing/button-toggle-harness.ts
  src/material/card/testing/card-harness.ts
  src/material/checkbox/testing/checkbox-harness.ts
  src/material/divider/testing/divider-harness.ts
  src/material/list/testing/action-list-harness.ts
  src/material/list/testing/list-harness.ts
  src/material/list/testing/list-item-harness-base.ts
  src/material/list/testing/nav-list-harness.ts
  src/material/list/testing/selection-list-harness.ts
  src/material/progress-bar/testing/progress-bar-harness.ts
  src/material/progress-spinner/testing/progress-spinner-harness.ts
  src/material/radio/testing/radio-harness.ts
  src/material/slide-toggle/testing/slide-toggle-harness.ts
  src/material/slider/testing/slider-harness.ts
  src/material/toolbar/testing/toolbar-harness.ts
Labels: P2, cla: yes, merge ready, target: patch

#20219 feat(datepicker/testing): add test harnesses for the datepicker module
  src/material/config.bzl
  src/material/datepicker/date-range-input-parts.ts
  src/material/datepicker/date-range-input.ts
  src/material/datepicker/datepicker-base.ts
  src/material/datepicker/datepicker-input.ts
  src/material/datepicker/datepicker-toggle.ts
  src/material/datepicker/month-view.ts
  src/material/datepicker/testing/BUILD.bazel
  src/material/datepicker/testing/calendar-cell-harness.ts
  src/material/datepicker/testing/calendar-harness-shared.spec.ts
  src/material/datepicker/testing/calendar-harness.spec.ts
  src/material/datepicker/testing/calendar-harness.ts
  src/material/datepicker/testing/date-range-input-harness-shared.spec.ts
  src/material/datepicker/testing/date-range-input-harness.spec.ts
  src/material/datepicker/testing/date-range-input-harness.ts
  src/material/datepicker/testing/datepicker-harness-filters.ts
  src/material/datepicker/testing/datepicker-input-harness-base.ts
  src/material/datepicker/testing/datepicker-input-harness-shared.spec.ts
  src/material/datepicker/testing/datepicker-input-harness.spec.ts
  src/material/datepicker/testing/datepicker-input-harness.ts
  src/material/datepicker/testing/datepicker-toggle-harness-shared.spec.ts
  src/material/datepicker/testing/datepicker-toggle-harness.spec.ts
  src/material/datepicker/testing/datepicker-toggle-harness.ts
  src/material/datepicker/testing/datepicker-trigger-harness-base.ts
  src/material/datepicker/testing/index.ts
  src/material/datepicker/testing/public-api.ts
  src/material/dialog/dialog-config.ts
  tools/public_api_guard/material/datepicker.d.ts
  tools/public_api_guard/material/datepicker/testing.d.ts
  tools/public_api_guard/material/dialog.d.ts
Labels: P2, cla: yes, merge ready, target: minor

#20125 fix(core): allow for default color and tabindex to be set per instance
  src/material/checkbox/checkbox.ts
  src/material/core/common-behaviors/color.spec.ts
  src/material/core/common-behaviors/color.ts
  src/material/core/common-behaviors/tabindex.spec.ts
  src/material/core/common-behaviors/tabindex.ts
  src/material/datepicker/datepicker-base.ts
  tools/public_api_guard/material/core.d.ts
Labels: P2, cla: yes, merge ready, target: minor

#20295 build: use new labeling and branching in merge script
  .ng-dev/merge.ts
  package.json
  yarn.lock
Labels: cla: yes, merge ready, merge safe, target: minor

#20294 build: do not prompt on postinstall in bazel yarn install
  tools/postinstall/apply-patches.js
Labels: cla: yes, merge ready, merge safe, target: patch

#20288 docs(stepper): correct file name in markdown
  src/components-examples/material/stepper/stepper-editable/stepper-editable-example.html
  src/components-examples/material/stepper/stepper-label-position-bottom/stepper-label-position-bottom-example.html
  src/material/stepper/stepper.md
Labels: cla: yes, docs, merge ready, merge safe, target: patch

#20283 feat(material-experimental/mdc-radio): add test harness
  src/material-experimental/config.bzl
  src/material-experimental/mdc-radio/testing/BUILD.bazel
  src/material-experimental/mdc-radio/testing/index.ts
  src/material-experimental/mdc-radio/testing/public-api.ts
  src/material-experimental/mdc-radio/testing/radio-harness-filters.ts
  src/material-experimental/mdc-radio/testing/radio-harness.spec.ts
  src/material-experimental/mdc-radio/testing/radio-harness.ts
Labels: P3, cla: yes, merge ready, merge safe, target: minor

#20276 Combobox dev app
  .github/CODEOWNERS
  src/cdk-experimental/combobox/combobox.spec.ts
  src/cdk-experimental/combobox/combobox.ts
  src/dev-app/BUILD.bazel
  src/dev-app/cdk-experimental-combobox/BUILD.bazel
  src/dev-app/cdk-experimental-combobox/cdk-combobox-demo-module.ts
  src/dev-app/cdk-experimental-combobox/cdk-combobox-demo.html
  src/dev-app/cdk-experimental-combobox/cdk-combobox-demo.ts
  src/dev-app/cdk-experimental-combobox/panel-content.ts
  src/dev-app/dev-app/dev-app-layout.ts
  src/dev-app/dev-app/routes.ts
Labels: cla: yes, commit message fixup, merge ready, merge safe, target: minor

#18654 perf(icon): avoid unnecessarily parsing icon sets
  src/material/icon/icon-registry.ts
Labels: P2, cla: yes, merge ready, perf, target: patch

#20229 feat(cdk-experimental/selection): Merge cdk–selection to the master
  .github/CODEOWNERS
  src/cdk-experimental/config.bzl
  src/cdk-experimental/selection/BUILD.bazel
  src/cdk-experimental/selection/index.ts
  src/cdk-experimental/selection/public-api.ts
  src/cdk-experimental/selection/row-selection.ts
  src/cdk-experimental/selection/select-all.ts
  src/cdk-experimental/selection/selection-column.ts
  src/cdk-experimental/selection/selection-module.ts
  src/cdk-experimental/selection/selection-set.ts
  src/cdk-experimental/selection/selection-toggle.ts
  src/cdk-experimental/selection/selection.spec.ts
  src/cdk-experimental/selection/selection.ts
  src/components-examples/BUILD.bazel
  src/components-examples/cdk-experimental/selection/BUILD.bazel
  src/components-examples/cdk-experimental/selection/cdk-selection-column/cdk-selection-column-example.css
  src/components-examples/cdk-experimental/selection/cdk-selection-column/cdk-selection-column-example.html
  src/components-examples/cdk-experimental/selection/cdk-selection-column/cdk-selection-column-example.ts
  src/components-examples/cdk-experimental/selection/cdk-selection-list/cdk-selection-list-example.html
  src/components-examples/cdk-experimental/selection/cdk-selection-list/cdk-selection-list-example.ts
  src/components-examples/cdk-experimental/selection/index.ts
  src/components-examples/material-experimental/selection/BUILD.bazel
  src/components-examples/material-experimental/selection/index.ts
  src/components-examples/material-experimental/selection/mat-selection-column/mat-selection-column-example.css
  src/components-examples/material-experimental/selection/mat-selection-column/mat-selection-column-example.html
  src/components-examples/material-experimental/selection/mat-selection-column/mat-selection-column-example.ts
  src/components-examples/material-experimental/selection/mat-selection-list/mat-selection-list-example.html
  src/components-examples/material-experimental/selection/mat-selection-list/mat-selection-list-example.ts
  src/dev-app/BUILD.bazel
  src/dev-app/dev-app/dev-app-layout.ts
  src/dev-app/dev-app/dev-app-module.ts
  src/dev-app/dev-app/routes.ts
  src/dev-app/example/example-list.ts
  src/dev-app/example/example-module.ts
  src/dev-app/selection/BUILD.bazel
  src/dev-app/selection/selection-demo-module.ts
  src/dev-app/selection/selection-demo.ts
  src/material-experimental/config.bzl
  src/material-experimental/selection/BUILD.bazel
  src/material-experimental/selection/_selection.scss
  src/material-experimental/selection/index.ts
  src/material-experimental/selection/public-api.ts
  src/material-experimental/selection/row-selection.ts
  src/material-experimental/selection/select-all.ts
  src/material-experimental/selection/selection-column.scss
  src/material-experimental/selection/selection-column.ts
  src/material-experimental/selection/selection-module.ts
  src/material-experimental/selection/selection-toggle.ts
  src/material-experimental/selection/selection.ts
Labels: caretaker note, cla: yes, merge ready, merge safe, needs rebase, target: minor

#20301 feat(material-experimental/menubar): extends components from cdk menu equivalents
  src/material-experimental/menubar/BUILD.bazel
  src/material-experimental/menubar/menubar-item.spec.ts
  src/material-experimental/menubar/menubar-item.ts
  src/material-experimental/menubar/menubar-module.ts
  src/material-experimental/menubar/menubar.spec.ts
  src/material-experimental/menubar/menubar.ts
Labels: cla: yes, merge ready, merge safe, target: minor

#20240 fix(slider): don't emit change events on mousedown
  src/material/slider/slider.spec.ts
  src/material/slider/slider.ts
Labels: P2, caretaker note, cla: yes, merge ready, target: patch

#20304 test(datepicker/testing): fix test failure
  src/material/datepicker/testing/calendar-harness-shared.spec.ts
Labels: P2, cla: yes, merge ready, merge safe, target: minor

#20306 Combobox open actions
  src/cdk-experimental/combobox/BUILD.bazel
  src/cdk-experimental/combobox/combobox-module.ts
  src/cdk-experimental/combobox/combobox-panel.ts
  src/cdk-experimental/combobox/combobox-popup.ts
  src/cdk-experimental/combobox/combobox.spec.ts
  src/cdk-experimental/combobox/combobox.ts
  src/cdk-experimental/combobox/public-api.ts
Labels: cla: yes, commit message fixup, merge ready, merge safe, target: minor

#20291 Combobox listbox compatible
  src/cdk-experimental/combobox/combobox.spec.ts
  src/cdk-experimental/combobox/combobox.ts
  src/cdk-experimental/listbox/BUILD.bazel
  src/cdk-experimental/listbox/listbox.spec.ts
  src/cdk-experimental/listbox/listbox.ts
Labels: cla: yes, commit message fixup, merge ready, merge safe, target: minor

#20339 Combobox listbox refactor
  src/cdk-experimental/combobox/combobox-panel.ts
  src/cdk-experimental/combobox/combobox-popup.ts
  src/cdk-experimental/combobox/combobox.ts
  src/cdk-experimental/listbox/listbox.spec.ts
  src/cdk-experimental/listbox/listbox.ts
  src/dev-app/cdk-experimental-combobox/cdk-combobox-demo.html
Labels: cla: yes, merge ready, merge safe, target: minor

#20322 feat(material-experimental/mdc-tabs): add test harnesses
  src/material-experimental/config.bzl
  src/material-experimental/mdc-tabs/testing/BUILD.bazel
  src/material-experimental/mdc-tabs/testing/index.ts
  src/material-experimental/mdc-tabs/testing/public-api.ts
  src/material-experimental/mdc-tabs/testing/tab-group-harness.spec.ts
  src/material-experimental/mdc-tabs/testing/tab-group-harness.ts
  src/material-experimental/mdc-tabs/testing/tab-harness-filters.ts
  src/material-experimental/mdc-tabs/testing/tab-harness.ts
Labels: P3, cla: yes, merge ready, merge safe, target: minor

#20319 feat(material-experimental/mdc-table): add test harnesses
  src/material-experimental/config.bzl
  src/material-experimental/mdc-card/testing/BUILD.bazel
  src/material-experimental/mdc-table/testing/BUILD.bazel
  src/material-experimental/mdc-table/testing/cell-harness.ts
  src/material-experimental/mdc-table/testing/index.ts
  src/material-experimental/mdc-table/testing/public-api.ts
  src/material-experimental/mdc-table/testing/row-harness.ts
  src/material-experimental/mdc-table/testing/table-harness-filters.ts
  src/material-experimental/mdc-table/testing/table-harness.spec.ts
  src/material-experimental/mdc-table/testing/table-harness.ts
Labels: P3, cla: yes, merge ready, merge safe, target: minor

#20316 fix(material/table): rename flex example
  src/components-examples/cdk/table/cdk-table-flex-basic/cdk-table-flex-basic-example.css
  src/components-examples/cdk/table/cdk-table-flex-basic/cdk-table-flex-basic-example.html
  src/components-examples/cdk/table/cdk-table-flex-basic/cdk-table-flex-basic-example.ts
  src/components-examples/cdk/table/index.ts
  src/components-examples/material/table/index.ts
  src/components-examples/material/table/table-flex-basic/table-flex-basic-example.css
  src/components-examples/material/table/table-flex-basic/table-flex-basic-example.html
  src/components-examples/material/table/table-flex-basic/table-flex-basic-example.ts
  src/dev-app/table/table-demo.html
Labels: P2, cla: yes, merge ready, merge safe, target: patch

#20300 fix(cdk-experimental/menu): do not allow two separate triggers to open the same menu
  src/cdk-experimental/menu/context-menu.spec.ts
  src/cdk-experimental/menu/context-menu.ts
  src/cdk-experimental/menu/menu-errors.ts
  src/cdk-experimental/menu/menu-item-trigger.spec.ts
  src/cdk-experimental/menu/menu-item-trigger.ts
  src/cdk-experimental/menu/menu-item.ts
  src/cdk-experimental/menu/menu-panel.ts
  src/cdk-experimental/menu/menu-stack.ts
Labels: cla: yes, merge ready, merge safe, target: minor

#20275 docs(form-field): implement error state getter in custom control example
  src/components-examples/material/form-field/form-field-custom-control/form-field-custom-control-example.html
  src/components-examples/material/form-field/form-field-custom-control/form-field-custom-control-example.ts
Labels: P3, cla: yes, docs, merge ready, merge safe, target: patch

#20348 test(material-experimental/menubar): fix test failure
  src/material-experimental/menubar/menubar-item.spec.ts
Labels: P2, cla: yes, merge ready, merge safe, target: minor

#20145 feat(cdk/testing): add optional excludes to TestElement text method
  src/cdk/testing/protractor/protractor-element.ts
  src/cdk/testing/public-api.ts
  src/cdk/testing/test-element.ts
  src/cdk/testing/testbed/unit-test-element.ts
  src/cdk/testing/tests/cross-environment.spec.ts
  src/cdk/testing/tests/protractor.e2e.spec.ts
  src/cdk/testing/text-filtering.ts
  tools/public_api_guard/cdk/testing.d.ts
  tools/public_api_guard/cdk/testing/protractor.d.ts
  tools/public_api_guard/cdk/testing/testbed.d.ts
Labels: cla: yes, merge ready, target: minor

#20148 fix(input/testing): filtering by regex not working
  src/material/input/testing/input-harness.ts
  src/material/input/testing/shared.spec.ts
Labels: P3, cla: yes, merge ready, target: patch

#20155 fix(platform): detect and ignore scrollBehavior polyfills
  src/cdk/platform/features/scrolling.ts
Labels: P3, cla: yes, merge ready, target: patch

#20165 refactor: replace asObservable usages
  src/cdk-experimental/column-resize/column-resize-notifier.ts
  src/cdk-experimental/dialog/dialog-ref.ts
  src/cdk-experimental/popover-edit/edit-ref.ts
  src/cdk-experimental/popover-edit/focus-escape-notifier.ts
  src/cdk-experimental/popover-edit/popover-edit.spec.ts
  src/cdk/a11y/focus-monitor/focus-monitor.ts
  src/cdk/a11y/focus-trap/focus-trap.ts
  src/cdk/drag-drop/directives/drag.spec.ts
  src/cdk/drag-drop/directives/drag.ts
  src/cdk/drag-drop/drag-ref.ts
  src/cdk/overlay/overlay-directives.spec.ts
  src/cdk/overlay/overlay-ref.ts
  src/cdk/overlay/position/connected-position-strategy.ts
  src/cdk/overlay/position/flexible-connected-position-strategy.ts
  src/cdk/overlay/scroll/close-scroll-strategy.spec.ts
  src/cdk/overlay/scroll/reposition-scroll-strategy.spec.ts
  src/cdk/scrolling/virtual-scroll-viewport.ts
  src/cdk/testing/testbed/task-state-zone-interceptor.ts
  src/cdk/text-field/autofill.ts
  src/material-experimental/column-resize/column-resize.spec.ts
  src/material-experimental/mdc-chips/chip-option.ts
  src/material-experimental/mdc-form-field/form-field.ts
  src/material-experimental/mdc-snack-bar/snack-bar-container.ts
  src/material-experimental/mdc-tabs/tab-header.spec.ts
  src/material-experimental/mdc-tabs/tab-nav-bar/tab-nav-bar.spec.ts
  src/material-experimental/popover-edit/popover-edit.spec.ts
  src/material/autocomplete/autocomplete-trigger.ts
  src/material/autocomplete/autocomplete.spec.ts
  src/material/bottom-sheet/bottom-sheet-ref.ts
  src/material/chips/chip.ts
  src/material/core/datetime/date-adapter.ts
  src/material/datepicker/calendar-body.ts
  src/material/datepicker/date-selection-model.ts
  src/material/datepicker/datepicker-base.ts
  src/material/dialog/dialog-ref.ts
  src/material/dialog/dialog.spec.ts
  src/material/form-field/form-field.ts
  src/material/menu/menu-trigger.ts
  src/material/menu/menu.ts
  src/material/select/select.spec.ts
  src/material/select/select.ts
  src/material/sidenav/drawer.ts
  src/material/snack-bar/snack-bar-container.ts
  src/material/snack-bar/snack-bar-ref.ts
  src/material/tabs/tab-header.spec.ts
  src/material/tabs/tab-nav-bar/tab-nav-bar.spec.ts
  src/material/tooltip/tooltip.ts
  tools/public_api_guard/cdk/overlay.d.ts
  tools/public_api_guard/material/core.d.ts
  tools/public_api_guard/material/sidenav.d.ts
  tslint.json
Labels: P3, cla: yes, merge ready, target: patch

#20192 fix(material/progress-spinner): Progress spinner animation fails for floating point diameter values
  src/material/progress-spinner/progress-spinner.html
  src/material/progress-spinner/progress-spinner.spec.ts
  src/material/progress-spinner/progress-spinner.ts
  tools/public_api_guard/material/progress-spinner.d.ts
Labels: P3, cla: yes, merge ready, target: patch

#20250 fix(datepicker): add coercion for opened input
  src/material/datepicker/datepicker-base.ts
Labels: P3, cla: yes, merge ready, target: patch

#20237 fix(cdk/drag-drop): preserve checked state for grouped radio inputs
  src/cdk/drag-drop/clone-node.ts
  src/cdk/drag-drop/directives/drag.spec.ts
Labels: P3, cla: yes, merge ready, target: patch

#20252 fix(cdk/layout): support readonly arrays for public methods
  src/cdk/layout/breakpoints-observer.ts
  tools/public_api_guard/cdk/layout.d.ts
Labels: P3, cla: yes, merge ready, target: patch

#20256 fix(datepicker): support dateClass on year and multi-year views
  src/components-examples/material/datepicker/datepicker-date-class/datepicker-date-class-example.ts
  src/material/datepicker/calendar-body.ts
  src/material/datepicker/calendar.html
  src/material/datepicker/calendar.ts
  src/material/datepicker/datepicker-base.ts
  src/material/datepicker/month-view.spec.ts
  src/material/datepicker/month-view.ts
  src/material/datepicker/multi-year-view.spec.ts
  src/material/datepicker/multi-year-view.ts
  src/material/datepicker/year-view.spec.ts
  src/material/datepicker/year-view.ts
  tools/public_api_guard/material/datepicker.d.ts
Labels: P3, cla: yes, merge ready, target: minor

#20266 fix(table): incorrect padding for single-cell rows in rtl
  src/material/table/table.scss
Labels: P3, caretaker note, cla: yes, merge ready, target: patch

#20357 refactor: remove missing asObservable usages
  src/material-experimental/mdc-autocomplete/autocomplete.spec.ts
  src/material-experimental/mdc-dialog/dialog.spec.ts
Labels: P2, cla: yes, merge ready, merge safe, target: minor

#20324 feat(autocomplete): support variable option height
  src/material-experimental/mdc-autocomplete/autocomplete-trigger.ts
  src/material-experimental/mdc-autocomplete/autocomplete.spec.ts
  src/material/autocomplete/autocomplete-trigger.ts
  src/material/autocomplete/autocomplete.spec.ts
  tools/public_api_guard/material/autocomplete.d.ts
Labels: P3, cla: yes, merge ready, target: minor

#20330 fix(drag-drop): remove redundant style changes from handle directive
  src/cdk/drag-drop/directives/drag-handle.ts
  src/cdk/drag-drop/directives/drag.spec.ts
Labels: P3, cla: yes, merge ready, target: patch

#19889 fix(list): don't redirect focus to first option on mouse focus
  src/material/list/BUILD.bazel
  src/material/list/selection-list.spec.ts
  src/material/list/selection-list.ts
  tools/public_api_guard/material/list.d.ts
Labels: P3, cla: yes, merge ready, target: patch

#20331 fix(badge): allow more data types for badge content
  src/material/badge/badge.spec.ts
  src/material/badge/badge.ts
  tools/public_api_guard/material/badge.d.ts
Labels: P3, caretaker note, cla: yes, merge ready, target: patch

#20169 fix(material-experimental/mdc-menu): apply typography to button menu items
  src/material-experimental/mdc-menu/_menu-theme.scss
Labels: P2, cla: yes, merge ready, target: patch

#20292 fix(chips): support readonly collections in inputs
  src/material-experimental/mdc-chips/chip-default-options.ts
  src/material-experimental/mdc-chips/chip-input.ts
  src/material-experimental/mdc-chips/chip.ts
  src/material/chips/chip-default-options.ts
  src/material/chips/chip-input.ts
  tools/public_api_guard/material/chips.d.ts
Labels: P4, cla: yes, merge ready, target: minor

#19870 fix(list): determine if option value changed (#19828)
  src/material/list/selection-list.spec.ts
  src/material/list/selection-list.ts
Labels: P3, cla: yes, merge ready, target: patch

#20366 feat(material-experimental/mdc-snack-bar): add test harness
  src/material-experimental/config.bzl
  src/material-experimental/mdc-snack-bar/testing/BUILD.bazel
  src/material-experimental/mdc-snack-bar/testing/index.ts
  src/material-experimental/mdc-snack-bar/testing/public-api.ts
  src/material-experimental/mdc-snack-bar/testing/snack-bar-harness-filters.ts
  src/material-experimental/mdc-snack-bar/testing/snack-bar-harness.spec.ts
  src/material-experimental/mdc-snack-bar/testing/snack-bar-harness.ts
  src/material/snack-bar/testing/shared.spec.ts
  src/material/snack-bar/testing/snack-bar-harness.spec.ts
Labels: P3, cla: yes, merge ready, merge safe, target: minor

#20365 feat(material-experimental/menubar): update the dev-app to include a fake mat-menu
  src/dev-app/menubar/BUILD.bazel
  src/dev-app/menubar/mat-menubar-demo-module.ts
  src/dev-app/menubar/mat-menubar-demo.html
  src/dev-app/menubar/mat-menubar-demo.scss
  src/dev-app/menubar/mat-menubar-demo.ts
Labels: cla: yes, merge ready, merge safe, target: minor

#20364 fix(material-experimental/mdc-table): reset table layout
  src/material-experimental/mdc-table/table.scss
Labels: P2, cla: yes, merge ready, merge safe, target: patch

#20359 tests: remove unsupported TS integration tests
  integration/ts-compat/BUILD.bazel
  package.json
  src/cdk-experimental/tsconfig-tests.json
  src/cdk/tsconfig-tests.json
  src/google-maps/tsconfig-tests.json
  src/material-experimental/tsconfig-tests.json
  src/material-moment-adapter/tsconfig-tests.json
  src/material/tsconfig-tests.json
  tools/package-tools/ts-compile.ts
  yarn.lock
Labels: P2, caretaker note, cla: yes, merge ready, merge safe, target: patch

#20355 docs(material/form-field): updated documentation
  src/material/form-field/.form-field.md.swp
  src/material/form-field/form-field.md
Labels: cla: yes, docs, merge ready, merge safe, target: patch

#20354 fix(material-experimental/mdc-core): set up strong focus indication for MDC-based option
  src/material-experimental/mdc-helpers/_focus-indicators.scss
Labels: P3, cla: yes, merge ready, merge safe, target: patch

#20352 fix(material-experimental/mdc-menu/testing): add unimplemented methods
  src/material-experimental/mdc-menu/testing/menu-harness.spec.ts
  src/material-experimental/mdc-menu/testing/menu-harness.ts
  src/material/menu/testing/shared.spec.ts
Labels: P3, cla: yes, merge ready, merge safe, target: patch

#20286 docs(expansion-panel): fix duplicate selectors and add missing docume…
  src/material/expansion/expansion-panel-header.ts
  src/material/expansion/expansion-panel.ts
Labels: cla: yes, docs, merge ready, merge safe, target: patch

#20279 feat(material-experimental/mdc-list): implement selection list
  .github/CODEOWNERS
  src/dev-app/list/list-demo.html
  src/dev-app/mdc-list/BUILD.bazel
  src/dev-app/mdc-list/mdc-list-demo-module.ts
  src/dev-app/mdc-list/mdc-list-demo.html
  src/material-experimental/mdc-checkbox/_checkbox-theme.scss
  src/material-experimental/mdc-list/BUILD.bazel
  src/material-experimental/mdc-list/_interactive-list-theme.scss
  src/material-experimental/mdc-list/_list-option-theme.scss
  src/material-experimental/mdc-list/_list-theme.scss
  src/material-experimental/mdc-list/action-list.ts
  src/material-experimental/mdc-list/interactive-list-base.ts
  src/material-experimental/mdc-list/list-base.ts
  src/material-experimental/mdc-list/list-item.html
  src/material-experimental/mdc-list/list-option.html
  src/material-experimental/mdc-list/list-option.scss
  src/material-experimental/mdc-list/list-option.ts
  src/material-experimental/mdc-list/list.scss
  src/material-experimental/mdc-list/list.spec.ts
  src/material-experimental/mdc-list/list.ts
  src/material-experimental/mdc-list/module.ts
  src/material-experimental/mdc-list/nav-list.ts
  src/material-experimental/mdc-list/public-api.ts
  src/material-experimental/mdc-list/selection-list.spec.ts
  src/material-experimental/mdc-list/selection-list.ts
  src/material/list/list.ts
  src/universal-app/kitchen-sink-mdc/kitchen-sink-mdc.html
  src/universal-app/kitchen-sink-mdc/kitchen-sink-mdc.ts
  src/universal-app/kitchen-sink/kitchen-sink.html
Labels: P2, cla: yes, merge ready, merge safe, target: minor

#20092 feat(stepper): add test harness
  src/material/config.bzl
  src/material/stepper/step-header.html
  src/material/stepper/stepper-button.ts
  src/material/stepper/testing/BUILD.bazel
  src/material/stepper/testing/index.ts
  src/material/stepper/testing/public-api.ts
  src/material/stepper/testing/shared.spec.ts
  src/material/stepper/testing/step-harness-filters.ts
  src/material/stepper/testing/step-harness.ts
  src/material/stepper/testing/stepper-button-harnesses.ts
  src/material/stepper/testing/stepper-harness.spec.ts
  src/material/stepper/testing/stepper-harness.ts
  tools/public_api_guard/material/stepper/testing.d.ts
Labels: P2, cla: yes, merge ready, target: minor

#19587 fix(material/input): do not override existing aria-describedby value
  guides/creating-a-custom-form-field-control.md
  src/components-examples/material-experimental/mdc-form-field/mdc-form-field-custom-control/example-tel-input-example.html
  src/components-examples/material-experimental/mdc-form-field/mdc-form-field-custom-control/form-field-custom-control-example.ts
  src/components-examples/material/form-field/form-field-custom-control/example-tel-input-example.html
  src/components-examples/material/form-field/form-field-custom-control/form-field-custom-control-example.ts
  src/material-experimental/mdc-form-field/form-field.ts
  src/material-experimental/mdc-input/input.spec.ts
  src/material-experimental/mdc-input/input.ts
  src/material/form-field/form-field-control.ts
  src/material/form-field/form-field.ts
  src/material/input/input.spec.ts
  src/material/input/input.ts
  tools/public_api_guard/material/form-field.d.ts
  tools/public_api_guard/material/input.d.ts
Labels: P3, a11y, cla: yes, merge ready, target: minor

#19604 feat(google-maps): Add Layer components.
  src/dev-app/google-map/google-map-demo.html
  src/dev-app/google-map/google-map-demo.ts
  src/google-maps/google-maps-module.ts
  src/google-maps/map-base-layer.ts
  src/google-maps/map-bicycling-layer/map-bicycling-layer.spec.ts
  src/google-maps/map-bicycling-layer/map-bicycling-layer.ts
  src/google-maps/map-traffic-layer/map-traffic-layer.spec.ts
  src/google-maps/map-traffic-layer/map-traffic-layer.ts
  src/google-maps/map-transit-layer/map-transit-layer.spec.ts
  src/google-maps/map-transit-layer/map-transit-layer.ts
  src/google-maps/public-api.ts
  src/google-maps/testing/fake-google-map-utils.ts
  tools/public_api_guard/google-maps/google-maps.d.ts
Labels: P3, cla: yes, merge ready, target: minor

#19955 refactor: handle home/end presses through key manager
  src/cdk-experimental/listbox/listbox.ts
  src/cdk/a11y/key-manager/list-key-manager.ts
  src/cdk/stepper/stepper.ts
  src/material-experimental/mdc-chips/chip-grid.ts
  src/material-experimental/mdc-chips/chip-listbox.ts
  src/material-experimental/mdc-chips/grid-key-manager.ts
  src/material/chips/chip-list.ts
  src/material/expansion/accordion.ts
  src/material/list/selection-list.spec.ts
  src/material/list/selection-list.ts
  src/material/menu/menu.ts
  src/material/select/select.ts
  src/material/tabs/paginated-tab-header.ts
  tools/public_api_guard/cdk/a11y.d.ts
Labels: P3, cla: yes, merge ready, target: minor

#20149 Hugoer/material table
  src/material/table/table-data-source.spec.ts
  src/material/table/table-data-source.ts
Labels: cla: yes, commit message fixup, merge ready, target: minor

#20082 fix(select): use combobox pattern for accessibility
  src/material/select/select.html
  src/material/select/select.spec.ts
  src/material/select/select.ts
  src/material/select/testing/select-harness.ts
  tools/public_api_guard/material/select.d.ts
Labels: P2, a11y, cla: yes, merge ready, target: minor

#20388 build: clean up uses of integers as booleans in Bazel files
  src/cdk/coercion/BUILD.bazel
  src/cdk/keycodes/BUILD.bazel
  src/circular-deps-test.conf.js
  src/google-maps/testing/BUILD.bazel
  tools/defaults.bzl
Labels: P4, cla: yes, merge ready, merge safe, target: patch

#20368 refactor: add support for TypeScript 4.0
  integration/ts-compat/BUILD.bazel
  package.json
  src/cdk-experimental/selection/row-selection.ts
  src/cdk-experimental/selection/selection-toggle.ts
  src/cdk-experimental/selection/selection.ts
  src/cdk/a11y/key-manager/list-key-manager.spec.ts
  src/cdk/table/cell.ts
  src/cdk/tree/padding.ts
  src/google-maps/google-map/google-map.spec.ts
  src/google-maps/map-bicycling-layer/map-bicycling-layer.spec.ts
  src/google-maps/map-circle/map-circle.spec.ts
  src/google-maps/map-ground-overlay/map-ground-overlay.spec.ts
  src/google-maps/map-info-window/map-info-window.spec.ts
  src/google-maps/map-kml-layer/map-kml-layer.spec.ts
  src/google-maps/map-marker/map-marker.spec.ts
  src/google-maps/map-polygon/map-polygon.spec.ts
  src/google-maps/map-polyline/map-polyline.spec.ts
  src/google-maps/map-rectangle/map-rectangle.spec.ts
  src/google-maps/map-traffic-layer/map-traffic-layer.spec.ts
  src/google-maps/map-transit-layer/map-transit-layer.spec.ts
  src/material-experimental/mdc-chips/chip-set.ts
  src/material-experimental/mdc-chips/chip.ts
  src/material-experimental/mdc-table/cell.ts
  src/material-experimental/mdc-tabs/tab.ts
  src/material-experimental/selection/row-selection.ts
  src/material-experimental/selection/selection-toggle.ts
  src/material-experimental/selection/selection.ts
  src/material/chips/chip.ts
  src/material/core/common-behaviors/constructor.ts
  src/material/core/common-behaviors/disable-ripple.ts
  src/material/core/common-behaviors/tabindex.ts
  src/material/radio/radio.ts
  src/material/table/cell.ts
  src/material/tabs/tab.ts
  src/material/tree/padding.ts
  src/material/tree/toggle.ts
  src/youtube-player/youtube-player.spec.ts
  tools/public_api_guard/cdk/table.d.ts
  tools/public_api_guard/cdk/tree.d.ts
  tools/public_api_guard/material/core.d.ts
  tools/public_api_guard/material/table.d.ts
  tools/public_api_guard/material/tabs.d.ts
  tools/public_api_guard/material/tree.d.ts
  yarn.lock
Labels: P2, cla: yes, merge ready, target: minor

#20430 chore: bump version to 10.2.0-rc.0 w/ changelog
  CHANGELOG.md
  package.json
Labels: cla: yes, merge ready, merge safe, target: minor

#20439 build: fix error from latest MDC canary version
  package.json
  src/material-experimental/mdc-slider/slider.ts
  yarn.lock
Labels: P2, cla: yes, merge ready, merge safe, target: patch

#20436 chore: bump master to 11.0.0-next.0
  package.json
Labels: cla: yes, merge ready, merge safe, target: major

#20377 fix(cdk/overlay): ensure error isn't thrown when many overlay items are closed from handler
  src/cdk/overlay/dispatchers/overlay-outside-click-dispatcher.spec.ts
  src/cdk/overlay/dispatchers/overlay-outside-click-dispatcher.ts
Labels: cla: yes, merge ready, target: patch

#20410 fix(drag-drop): expose some missing injection tokens
  src/cdk/drag-drop/public-api.ts
  tools/public_api_guard/cdk/drag-drop.d.ts
Labels: P3, cla: yes, merge ready, merge safe, target: patch

#20407 fix(cdk-experimental/combobox): not cleaning up overlay on destroy
  src/cdk-experimental/combobox/combobox.spec.ts
  src/cdk-experimental/combobox/combobox.ts
Labels: P3, cla: yes, merge ready, merge safe, target: minor

#20405 test: reduce reliance on static queries
  src/cdk/accordion/accordion.spec.ts
  src/cdk/overlay/fullscreen-overlay-container.spec.ts
  src/cdk/overlay/overlay-container.spec.ts
  src/cdk/portal/portal.spec.ts
  src/cdk/text-field/autofill.spec.ts
  src/material-experimental/column-resize/column-resize.spec.ts
  src/material-experimental/mdc-table/table.spec.ts
  src/material-experimental/mdc-tabs/tab-body.spec.ts
  src/material/table/table-data-source.spec.ts
  src/material/table/table.spec.ts
  src/material/tabs/tab-body.spec.ts
Labels: P3, cla: yes, merge ready, merge safe, target: patch

#20396 fix(material-experimental/mdc-core): active option not visible in high contrast mode
  src/material-experimental/mdc-core/option/option.scss
Labels: P3, cla: yes, merge ready, merge safe, target: minor

#20394 build: add support for shorthand names in API golden approval script
  scripts/approve-api-golden.js
  scripts/run-component-tests.js
  scripts/util.js
Labels: P3, cla: yes, merge ready, merge safe, target: patch

#20391 fix(material-experimental/mdc-button): double outline for FAB in high contrast mode
  src/material-experimental/mdc-button/button.scss
Labels: P3, cla: yes, merge ready, merge safe, target: patch

#20387 fix(material-experimental/mdc-dialog): blending in with background in high contrast mode
  src/material-experimental/mdc-dialog/dialog.scss
Labels: P3, cla: yes, merge ready, merge safe, target: minor

#20386 build(google-maps): add server-side rendering checks for new layers
  src/universal-app/kitchen-sink/kitchen-sink.html
Labels: P3, cla: yes, merge ready, merge safe, target: minor

#20383 Cdk stepper example refactor
  src/components-examples/cdk/stepper/cdk-custom-stepper-without-form/cdk-custom-stepper-without-form-example.ts
  src/components-examples/cdk/stepper/cdk-custom-stepper-without-form/example-custom-stepper.html
Labels: cla: yes, commit message fixup, docs, merge ready, merge safe, target: minor

#20371 build: do not consider e2e test targets as flaky locally
  .circleci/config.yml
  package.json
  tools/defaults.bzl
Labels: cla: yes, merge ready, merge safe, target: patch

#20376 fix(button): don't use divs in button template
  src/material-experimental/mdc-button/button.html
  src/material/button/button.html
Labels: G, P3, cla: yes, merge ready, target: patch

#20363 feat(cdk-experimental/menu): add ability to open menus from a standalone trigger
  src/cdk-experimental/menu/context-menu.spec.ts
  src/cdk-experimental/menu/context-menu.ts
  src/cdk-experimental/menu/menu-bar.spec.ts
  src/cdk-experimental/menu/menu-bar.ts
  src/cdk-experimental/menu/menu-item-radio.ts
  src/cdk-experimental/menu/menu-item-trigger.spec.ts
  src/cdk-experimental/menu/menu-item-trigger.ts
  src/cdk-experimental/menu/menu-item.ts
Labels: cla: yes, merge ready, merge safe, target: minor

#20412 docs(cdk-experimental/menu): add initial documentation for cdk menu directives
  src/cdk-experimental/menu/menu.md
  src/cdk-experimental/menu/menuaim.png
Labels: cla: yes, merge ready, merge safe, target: minor
