Repository angular/components, pull requests merged in 2020-05, with the labels that each got.

#19212 fix(cdk/testing): Make harnesses click on the center of the element by default
  src/cdk/testing/protractor/protractor-element.ts
  src/cdk/testing/test-element.ts
  src/cdk/testing/testbed/unit-test-element.ts
  src/material/button/testing/BUILD.bazel
  src/material/button/testing/button-harness.e2e.spec.ts
  tools/public_api_guard/cdk/testing.d.ts
  tools/public_api_guard/cdk/testing/protractor.d.ts
  tools/public_api_guard/cdk/testing/testbed.d.ts
Labels: P2, cla: yes, lgtm, merge ready, regression, target: patch

#19206 feat(focus indicators): Add config map to base focus indicators mixin and tweak some default styles.
  .github/CODEOWNERS
  src/dev-app/theme.scss
  src/material-experimental/mdc-helpers/_mdc-helpers.scss
  src/material/core/focus-indicators/_focus-indicators.scss
Labels: cla: yes, lgtm, merge ready, target: minor

#19216 docs:(material/datepicker) typo
  src/material/datepicker/datepicker.md
Labels: cla: yes, commit message fixup, docs, lgtm, merge ready, merge safe, target: patch

#19215 docs: update readme for Q2 2020
  README.md
Labels: cla: yes, docs, lgtm, merge ready, merge safe, target: patch

#19219 refactor(datepicker): move date range selection logic out of calendar
  src/dev-app/datepicker/datepicker-demo.ts
  src/material/datepicker/calendar.html
  src/material/datepicker/calendar.ts
  src/material/datepicker/date-range-selection-strategy.ts
  src/material/datepicker/datepicker-base.ts
  src/material/datepicker/datepicker-content.html
  src/material/datepicker/datepicker-module.ts
  src/material/datepicker/month-view.spec.ts
  src/material/datepicker/month-view.ts
  src/material/datepicker/public-api.ts
  tools/public_api_guard/material/datepicker.d.ts
Labels: P2, cla: yes, lgtm, merge ready, merge safe, target: development-branch

#19239 fix(datepicker): move focus into start input when pressing backspace on end input
  src/material/datepicker/date-range-input-parts.ts
  src/material/datepicker/date-range-input.spec.ts
  tools/public_api_guard/material/datepicker.d.ts
Labels: P3, cla: yes, lgtm, merge ready, merge safe, target: development-branch

#19170 docs(datepicker): add docs and live examples for date range picker
  src/components-examples/material/datepicker/date-range-picker-comparison/date-range-picker-comparison-example.css
  src/components-examples/material/datepicker/date-range-picker-comparison/date-range-picker-comparison-example.html
  src/components-examples/material/datepicker/date-range-picker-comparison/date-range-picker-comparison-example.ts
  src/components-examples/material/datepicker/date-range-picker-forms/date-range-picker-forms-example.css
  src/components-examples/material/datepicker/date-range-picker-forms/date-range-picker-forms-example.html
  src/components-examples/material/datepicker/date-range-picker-forms/date-range-picker-forms-example.ts
  src/components-examples/material/datepicker/date-range-picker-overview/date-range-picker-overview-example.css
  src/components-examples/material/datepicker/date-range-picker-overview/date-range-picker-overview-example.html
  src/components-examples/material/datepicker/date-range-picker-overview/date-range-picker-overview-example.ts
  src/components-examples/material/datepicker/date-range-picker-selection-strategy/date-range-picker-selection-strategy-example.css
  src/components-examples/material/datepicker/date-range-picker-selection-strategy/date-range-picker-selection-strategy-example.html
  src/components-examples/material/datepicker/date-range-picker-selection-strategy/date-range-picker-selection-strategy-example.ts
  src/components-examples/material/datepicker/index.ts
  src/dev-app/datepicker/datepicker-demo.scss
  src/material/datepicker/_datepicker-theme.scss
  src/material/datepicker/date-range-input.ts
  src/material/datepicker/date-range-selection-strategy.ts
  src/material/datepicker/datepicker.md
Labels: P2, cla: yes, docs, lgtm, merge ready, merge safe, target: development-branch

#19125 feat(datepicker): add date range picker
  goldens/ts-circular-deps.json
  src/components-examples/material/datepicker/date-range-picker-comparison/date-range-picker-comparison-example.css
  src/components-examples/material/datepicker/date-range-picker-comparison/date-range-picker-comparison-example.html
  src/components-examples/material/datepicker/date-range-picker-comparison/date-range-picker-comparison-example.ts
  src/components-examples/material/datepicker/date-range-picker-forms/date-range-picker-forms-example.css
  src/components-examples/material/datepicker/date-range-picker-forms/date-range-picker-forms-example.html
  src/components-examples/material/datepicker/date-range-picker-forms/date-range-picker-forms-example.ts
  src/components-examples/material/datepicker/date-range-picker-overview/date-range-picker-overview-example.css
  src/components-examples/material/datepicker/date-range-picker-overview/date-range-picker-overview-example.html
  src/components-examples/material/datepicker/date-range-picker-overview/date-range-picker-overview-example.ts
  src/components-examples/material/datepicker/date-range-picker-selection-strategy/date-range-picker-selection-strategy-example.css
  src/components-examples/material/datepicker/date-range-picker-selection-strategy/date-range-picker-selection-strategy-example.html
  src/components-examples/material/datepicker/date-range-picker-selection-strategy/date-range-picker-selection-strategy-example.ts
  src/components-examples/material/datepicker/index.ts
  src/dev-app/datepicker/BUILD.bazel
  src/dev-app/datepicker/datepicker-demo-module.ts
  src/dev-app/datepicker/datepicker-demo.html
  src/dev-app/datepicker/datepicker-demo.scss
  src/dev-app/datepicker/datepicker-demo.ts
  src/material/datepicker/BUILD.bazel
  src/material/datepicker/_datepicker-theme.scss
  src/material/datepicker/calendar-body.html
  src/material/datepicker/calendar-body.scss
  src/material/datepicker/calendar-body.spec.ts
  src/material/datepicker/calendar-body.ts
  src/material/datepicker/calendar.html
  src/material/datepicker/calendar.ts
  src/material/datepicker/date-range-input-parts.ts
  src/material/datepicker/date-range-input.html
  src/material/datepicker/date-range-input.scss
  src/material/datepicker/date-range-input.spec.ts
  src/material/datepicker/date-range-input.ts
  src/material/datepicker/date-range-picker.ts
  src/material/datepicker/date-range-selection-strategy.ts
  src/material/datepicker/date-selection-model.ts
  src/material/datepicker/datepicker-base.ts
  src/material/datepicker/datepicker-content.html
  src/material/datepicker/datepicker-input-base.ts
  src/material/datepicker/datepicker-input.ts
  src/material/datepicker/datepicker-module.ts
  src/material/datepicker/datepicker-toggle.ts
  src/material/datepicker/datepicker.md
  src/material/datepicker/datepicker.spec.ts
  src/material/datepicker/datepicker.ts
  src/material/datepicker/month-view.html
  src/material/datepicker/month-view.spec.ts
  src/material/datepicker/month-view.ts
  src/material/datepicker/multi-year-view.html
  src/material/datepicker/multi-year-view.ts
  src/material/datepicker/public-api.ts
  src/material/datepicker/year-view.html
  src/material/datepicker/year-view.spec.ts
  src/material/datepicker/year-view.ts
  tools/public_api_guard/material/datepicker.d.ts
Labels: P2, cla: yes, target: major

#19256 refactor: add missing abstract directive decorators
  src/cdk-experimental/column-resize/resizable.ts
  src/cdk/table/row.ts
  src/material-experimental/mdc-list/list-base.ts
  tools/tslint-rules/noUndecoratedClassWithAngularFeaturesRule.ts
  tslint.json
Labels: P2, cla: yes, lgtm, merge ready, target: patch

#19271 refactor: fix missing abstract directive for date-selection-model
  src/material/datepicker/date-selection-model.ts
Labels: P2, cla: yes, lgtm, merge ready, preserve commits, target: major

#19261 build: fix "test all" script running incorrect browser
  scripts/run-component-tests.js
Labels: cla: yes, lgtm, merge ready, merge safe, target: patch

#19250 build: update to rules nodejs v1.6.1
  WORKSPACE
Labels: cla: yes, lgtm, merge ready, merge safe, target: patch

#19240 docs: prevent form submission in examples
  src/components-examples/cdk/text-field/text-field-autofill-directive/text-field-autofill-directive-example.html
  src/components-examples/cdk/text-field/text-field-autofill-monitor/text-field-autofill-monitor-example.html
Labels: P4, cla: yes, docs, lgtm, merge ready, merge safe, target: patch

#19232 fix(material-experimental/mdc-input): native select option blending in with background on dark themes
  src/material-experimental/mdc-form-field/_form-field-native-select.scss
  src/material-experimental/mdc-form-field/_form-field-theme.scss
Labels: P3, cla: yes, lgtm, merge ready, merge safe, target: patch

#19231 build: add script for approving public API changes
  DEV_ENVIRONMENT.md
  package.json
  scripts/approve-api-golden.js
Labels: P3, cla: yes, lgtm, merge ready, merge safe, target: patch

#19229 refactor: remove usage of private `buildDefaultPath` method from `@schematics/angular`
  src/cdk/schematics/utils/build-component.ts
Labels: cla: yes, lgtm, merge ready, merge safe, target: patch

#19230 build: unable to run schematics tests through test script
  scripts/run-component-tests.js
Labels: P3, cla: yes, lgtm, merge ready, merge safe, target: patch

#17297 fix(datepicker): double role definition on calendar cell
  src/material/datepicker/calendar-body.html
Labels: P2, a11y, cla: yes, lgtm, merge ready, target: patch

#19273 test(datepicker): fix test failure against view engine
  src/material/datepicker/date-range-input.spec.ts
Labels: P3, cla: yes, lgtm, merge ready, merge safe, target: major

#19282 build: add dev app for MDC sidenav
  .github/CODEOWNERS
  src/dev-app/BUILD.bazel
  src/dev-app/dev-app/dev-app-layout.ts
  src/dev-app/dev-app/routes.ts
  src/dev-app/mdc-sidenav/BUILD.bazel
  src/dev-app/mdc-sidenav/mdc-sidenav-demo-module.ts
  src/dev-app/mdc-sidenav/mdc-sidenav-demo.html
  src/dev-app/mdc-sidenav/mdc-sidenav-demo.scss
  src/dev-app/mdc-sidenav/mdc-sidenav-demo.ts
Labels: P3, cla: yes, lgtm, merge ready, merge safe, target: patch

#19168 feat(material-expeirmental/mdc-list): add support for focus/hover states and ripples
  src/material-experimental/mdc-list/_list-theme.scss
  src/material-experimental/mdc-list/action-list.ts
  src/material-experimental/mdc-list/list-base.ts
  src/material-experimental/mdc-list/list.scss
  src/material-experimental/mdc-list/list.ts
  src/material-experimental/mdc-list/module.ts
  src/material-experimental/mdc-list/nav-list.ts
  src/material-experimental/mdc-list/selection-list.ts
Labels: cla: yes, lgtm, merge ready, merge safe, target: patch

#19277 feat(material-experimental/mdc-form-field): expose `MAT_FORM_FIELD` injection token
  src/material-experimental/mdc-form-field/public-api.ts
Labels: P3, cla: yes, lgtm, merge ready, merge safe, target: patch

#19285 chore: bump version to 9.2.3 w/ changelog
  CHANGELOG.md
  package.json
Labels: cla: yes, lgtm, merge ready, merge safe, target: patch

#19286 build: update to typescript 3.9
  integration/ts-compat/BUILD.bazel
  package.json
  src/cdk/drag-drop/drag-ref.ts
  src/cdk/drag-drop/drag-styling.ts
  src/cdk/drag-drop/drop-list-ref.ts
  src/material/tooltip/tooltip.spec.ts
  src/material/tooltip/tooltip.ts
  tools/tslint-rules/tsLoaderRule.js
  tools/tslint-rules/tsconfig.json
  yarn.lock
Labels: P2, cla: yes, lgtm, merge ready, target: major

#19146 fix(overlay): remove potentially leaky observable
  src/cdk/overlay/keyboard/overlay-keyboard-dispatcher.ts
  src/cdk/overlay/overlay-ref.ts
  tools/public_api_guard/cdk/overlay.d.ts
Labels: P3, cla: yes, lgtm, merge ready, target: patch

#19178 refactor(google-maps): use assert functions to avoid casting to non-nullable value
  src/google-maps/google-map/google-map.ts
  src/google-maps/map-circle/map-circle.ts
  src/google-maps/map-ground-overlay/map-ground-overlay.ts
  src/google-maps/map-info-window/map-info-window.ts
  src/google-maps/map-marker/map-marker.ts
  src/google-maps/map-polygon/map-polygon.ts
  src/google-maps/map-polyline/map-polyline.ts
  src/google-maps/map-rectangle/map-rectangle.ts
Labels: P3, cla: yes, lgtm, merge ready, target: major

#19224 feat(table/testing): allow filtering by column name
  src/material/table/testing/cell-harness.ts
  src/material/table/testing/shared.spec.ts
  src/material/table/testing/table-harness-filters.ts
  tools/public_api_guard/material/table/testing.d.ts
Labels: P3, cla: yes, lgtm, merge ready, target: major

#19291 build: fix unexpected bazel cache discarding
  .bazelrc
Labels: P2, cla: yes, merge ready, merge safe, target: patch

#19288 build: disable watch mode for `yarn test all` script
  scripts/run-component-tests.js
Labels: cla: yes, lgtm, merge ready, merge safe, target: patch

#19252 refactor: update api for embedded example comments in md docs
  tools/markdown-to-html/docs-marked-renderer.ts
Labels: cla: yes, lgtm, merge ready, merge safe, target: patch

#19251 fix(dialog): focus trap not attached if autoFocus is disabled
  src/material/dialog/dialog-container.ts
  src/material/dialog/dialog.spec.ts
Labels: P2, a11y, cla: yes, lgtm, merge ready, target: patch

#19228 fix(chips): chip list overriding chip disabled value
  src/material/chips/chip-list.spec.ts
  src/material/chips/chip-list.ts
  src/material/chips/chip.ts
  tools/public_api_guard/material/chips.d.ts
Labels: P3, cla: yes, lgtm, merge ready, target: patch

#19207 fix(tabs): don't prevent default space/enter action if active tab doesn't change
  src/material-experimental/mdc-tabs/tab-header.spec.ts
  src/material/tabs/paginated-tab-header.ts
  src/material/tabs/tab-header.spec.ts
Labels: P3, cla: yes, lgtm, merge ready, target: patch

#19177 fix(list): selection list marked as touched when tabbing in
  src/material/list/selection-list.spec.ts
  src/material/list/selection-list.ts
Labels: P3, cla: yes, lgtm, merge ready, target: patch

#19115 fix(input): avoid repeat accesses to check if element is a textarea
  src/material-experimental/mdc-input/input.ts
  src/material/input/input.ts
  tools/public_api_guard/material/input.d.ts
Labels: P3, cla: yes, lgtm, merge ready, target: patch

#19093 fix(form-field): add missing material common module
  src/material/form-field/form-field-module.ts
  tools/public_api_guard/material/form-field.d.ts
Labels: cla: yes, lgtm, merge ready, target: patch

#19284 fix(material-experimental/form-field): add setLabelRequired adapter
  package.json
  src/material-experimental/mdc-form-field/form-field.ts
  yarn.lock
Labels: P3, cla: yes, lgtm, merge ready, target: patch

#19295 docs: update master changelog for 9.2.2 and 9.2.3
  CHANGELOG.md
Labels: cla: yes, lgtm, merge ready, merge safe, target: major

#19296 chore: add no-op v10 migration entrypoints
  src/cdk/schematics/migration.json
  src/cdk/schematics/ng-update/index.ts
  src/material/schematics/migration.json
  src/material/schematics/ng-update/index.ts
Labels: cla: yes, lgtm, merge ready, merge safe, target: major

#19297 chore: bump version to 10.0.0-next.0 w/ changelog
  CHANGELOG.md
  package.json
Labels: cla: yes, lgtm, merge ready, merge safe, target: major

#19318 refactor(material-experimental/mdc-chips): implement trailing icon foundation
  package.json
  src/material-experimental/mdc-chips/chip-icons.ts
  src/material-experimental/mdc-chips/chip.ts
  yarn.lock
Labels: cla: yes, lgtm, merge ready, merge safe, target: patch

#19322 fix: unable to set expanded or collapsed height in expansion panel
  src/material/expansion/expansion-panel-header.ts
  src/material/expansion/expansion.spec.ts
Labels: cla: yes, lgtm, merge ready, merge safe, target: development-branch

#19310 refactor(cdk/table): remove deprecated APIs for version 10
  src/cdk/table/table.ts
  tools/public_api_guard/cdk/table.d.ts
Labels: P2, cla: yes, lgtm, merge ready, target: major

#19307 refactor(slide-toggle): remove deprecated APIs for version 10
  src/material-experimental/mdc-slide-toggle/slide-toggle-config.ts
  src/material-experimental/mdc-slide-toggle/slide-toggle.ts
  src/material/schematics/ng-update/data/constructor-checks.ts
  src/material/slide-toggle/BUILD.bazel
  src/material/slide-toggle/slide-toggle-config.ts
  src/material/slide-toggle/slide-toggle.spec.ts
  src/material/slide-toggle/slide-toggle.ts
  tools/public_api_guard/material/slide-toggle.d.ts
Labels: P2, cla: yes, lgtm, merge ready, target: major

#19304 fix(datepicker): strong focus indication in calendar always shown
  src/material/core/focus-indicators/_focus-indicators.scss
  src/material/datepicker/calendar-body.html
  src/material/datepicker/calendar-body.spec.ts
Labels: P2, cla: yes, lgtm, merge ready, target: major

#19280 refactor(drag-drop): remove deprecated APIs for version 10
  src/cdk/drag-drop/directives/config.ts
  src/cdk/drag-drop/directives/drag.ts
  src/cdk/drag-drop/directives/drop-list.ts
  tools/public_api_guard/cdk/drag-drop.d.ts
Labels: P2, cla: yes, lgtm, merge ready, target: major

#19238 fix(text-field): unable to undo/redo in autosized text field on firefox
  src/cdk/text-field/_text-field.scss
  src/cdk/text-field/autosize.ts
Labels: P2, cla: yes, lgtm, merge ready, target: patch

#19300 build: fix breaking changes script compilation error
  package.json
  scripts/breaking-changes.ts
  yarn.lock
Labels: P3, cla: yes, lgtm, merge ready, merge safe, target: major

#19298 build: prevent bazel from logging warning on each invocation
  .bazel_fix_commands.json
Labels: P3, cla: yes, lgtm, merge ready, merge safe, target: patch

#19237 fix(a11y): focus monitor not checking children if monitor is called multiple times with different parameters
  src/cdk/a11y/focus-monitor/focus-monitor.spec.ts
  src/cdk/a11y/focus-monitor/focus-monitor.ts
Labels: P3, cla: yes, lgtm, merge ready, target: patch

#19264 fix(column-resize): Resize table as well as columns, improve handing …
  src/cdk-experimental/column-resize/column-resize-directives/column-resize-flex.ts
  src/cdk-experimental/column-resize/column-resize-directives/column-resize.ts
  src/cdk-experimental/column-resize/column-resize-directives/default-enabled-column-resize-flex.ts
  src/cdk-experimental/column-resize/column-resize-directives/default-enabled-column-resize.ts
  src/cdk-experimental/column-resize/column-resize-notifier.ts
  src/cdk-experimental/column-resize/column-resize.ts
  src/cdk-experimental/column-resize/overlay-handle.ts
  src/cdk-experimental/column-resize/resizable.ts
  src/cdk-experimental/column-resize/resize-strategy.ts
  src/components-examples/material-experimental/column-resize/default-enabled-flex/default-enabled-column-resize-flex-demo.css
  src/components-examples/material-experimental/column-resize/default-enabled-flex/default-enabled-column-resize-flex-demo.html
  src/components-examples/material-experimental/column-resize/default-enabled-flex/default-enabled-column-resize-flex-demo.ts
  src/components-examples/material-experimental/column-resize/default-enabled/default-enabled-column-resize-demo.css
  src/components-examples/material-experimental/column-resize/default-enabled/default-enabled-column-resize-demo.html
  src/components-examples/material-experimental/column-resize/default-enabled/default-enabled-column-resize-demo.ts
  src/components-examples/material-experimental/column-resize/opt-in/opt-in-column-resize-demo.css
  src/components-examples/material-experimental/column-resize/opt-in/opt-in-column-resize-demo.html
  src/components-examples/material-experimental/column-resize/opt-in/opt-in-column-resize-demo.ts
  src/material-experimental/column-resize/column-resize-directives/column-resize-flex.ts
  src/material-experimental/column-resize/column-resize-directives/column-resize.ts
  src/material-experimental/column-resize/column-resize-directives/default-enabled-column-resize-flex.ts
  src/material-experimental/column-resize/column-resize-directives/default-enabled-column-resize.ts
  src/material-experimental/column-resize/column-resize.spec.ts
Labels: cla: yes, lgtm, merge ready, merge safe, target: patch

#19201 fix(material-experimental/mdc-list): properly render leading and trailing icons on list items
  package.json
  src/dev-app/list/list-demo.html
  src/dev-app/list/list-demo.scss
  src/dev-app/mdc-list/mdc-list-demo.html
  src/dev-app/mdc-list/mdc-list-demo.scss
  src/material-experimental/mdc-list/_list-theme.scss
  src/material-experimental/mdc-list/list-base.ts
  src/material-experimental/mdc-list/list-item.html
  src/material-experimental/mdc-list/module.ts
Labels: cla: yes, lgtm, merge ready, merge safe, target: patch

#19348 refactor(youtube-player): change deprecated APIs for version 10
  src/youtube-player/youtube-player.ts
  tools/public_api_guard/youtube-player/youtube-player.d.ts
Labels: P2, cla: yes, lgtm, merge ready, merge safe, target: major

#19371 build: generate proper anchor ids for headings in markdown
  package.json
  tools/markdown-to-html/docs-marked-renderer.ts
  tools/markdown-to-html/transform-markdown.ts
  yarn.lock
Labels: P3, cla: yes, lgtm, merge ready, merge safe, target: patch

#19354 refactor: ensure paths are safely passed around in ng-update
  src/cdk/schematics/ng-update/devkit-file-system.ts
  src/cdk/schematics/ng-update/devkit-migration-rule.ts
  src/cdk/schematics/ng-update/migrations/attribute-selectors.ts
  src/cdk/schematics/ng-update/migrations/class-names.ts
  src/cdk/schematics/ng-update/migrations/css-selectors.ts
  src/cdk/schematics/ng-update/migrations/element-selectors.ts
  src/cdk/schematics/ng-update/migrations/input-names.ts
  src/cdk/schematics/ng-update/migrations/output-names.ts
  src/cdk/schematics/ng-update/migrations/property-names.ts
  src/cdk/schematics/ng-update/test-cases/misc/external-resource-resolution.spec.ts
  src/cdk/schematics/ng-update/test-cases/misc/external-resource-resolution_input.ts
  src/cdk/schematics/testing/test-case-setup.ts
  src/cdk/schematics/update-tool/component-resource-collector.ts
  src/cdk/schematics/update-tool/file-system.ts
  src/cdk/schematics/update-tool/index.ts
  src/cdk/schematics/update-tool/migration.ts
  src/cdk/schematics/utils/project-index-file.ts
  src/cdk/schematics/utils/project-main-file.ts
  src/material/schematics/ng-update/migrations/hammer-gestures-v9/hammer-gestures-migration.ts
  src/material/schematics/ng-update/migrations/hammer-gestures-v9/import-manager.ts
  src/material/schematics/ng-update/migrations/misc-ripples-v7/ripple-speed-factor-migration.ts
  src/material/schematics/ng-update/migrations/package-imports-v8/secondary-entry-points-migration.ts
Labels: P3, cla: yes, lgtm, merge ready, merge safe, target: major

#19332 fix(autocomplete): incorrectly detecting shadow DOM when inserted through an embedded view
  src/material/autocomplete/autocomplete-trigger.ts
Labels: P3, cla: yes, lgtm, merge ready, target: patch

#19308 fix(datepicker): set color on range separator
  src/material/datepicker/_datepicker-theme.scss
Labels: P3, cla: yes, lgtm, merge ready, target: major

#19306 fix(google-maps): allow for ground overlay image to be changed
  src/dev-app/google-map/google-map-demo.html
  src/dev-app/google-map/google-map-demo.ts
  src/google-maps/map-ground-overlay/map-ground-overlay.spec.ts
  src/google-maps/map-ground-overlay/map-ground-overlay.ts
  src/google-maps/testing/fake-google-map-utils.ts
  tools/public_api_guard/google-maps/google-maps.d.ts
Labels: P3, cla: yes, lgtm, merge ready, target: patch

#19303 fix(icon): cancel in-flight icon requests if the icon changes
  src/material/icon/icon.spec.ts
  src/material/icon/icon.ts
Labels: P3, cla: yes, lgtm, merge ready, target: patch

#19375 build: fix wrong anchors in docs
  guides/v9-hammerjs-migration.md
Labels: P3, cla: yes, merge ready, merge safe, target: patch

#19336 build: ensure build uses typescript 3.9
  package.json
  src/bazel-tsconfig-test.json
  src/cdk/schematics/BUILD.bazel
  src/cdk/schematics/testing/BUILD.bazel
  src/cdk/schematics/testing/test-case-setup.ts
  src/cdk/schematics/testing/tsconfig.json
  src/cdk/schematics/update-tool/BUILD.bazel
  src/google-maps/google-map/google-map.spec.ts
  src/google-maps/map-circle/map-circle.spec.ts
  src/google-maps/map-ground-overlay/map-ground-overlay.spec.ts
  src/google-maps/map-info-window/map-info-window.spec.ts
  src/google-maps/map-marker/map-marker.spec.ts
  src/google-maps/map-polygon/map-polygon.spec.ts
  src/google-maps/map-polyline/map-polyline.spec.ts
  src/google-maps/map-rectangle/map-rectangle.spec.ts
  src/google-maps/testing/fake-google-map-utils.ts
  src/material/button-toggle/button-toggle.e2e.spec.ts
  src/material/card/card.e2e.spec.ts
  src/material/expansion/expansion.e2e.spec.ts
  src/material/schematics/BUILD.bazel
  src/material/toolbar/toolbar.e2e.spec.ts
  tools/public_api_guard/cdk/drag-drop.d.ts
  tools/public_api_guard/cdk/portal.d.ts
  tools/public_api_guard/material/bottom-sheet.d.ts
  tools/public_api_guard/material/dialog.d.ts
  tools/public_api_guard/material/snack-bar.d.ts
  yarn.lock
Labels: P2, cla: yes, lgtm, merge ready, merge safe, target: major

#19373 fix(expansion): disable header height transition if noop animations is set
  src/material/expansion/expansion-panel-header.scss
  src/material/expansion/expansion-panel-header.ts
  tools/public_api_guard/material/expansion.d.ts
Labels: P3, cla: yes, lgtm, merge ready, target: patch

#19386 chore: bump version to 9.2.4 w/ changelog
  CHANGELOG.md
  package.json
Labels: cla: yes, lgtm, merge ready, target: patch

#19387 chore: bump version to 9.2.4 w/ changelog
  CHANGELOG.md
Labels: cla: yes, lgtm, merge ready

#19388 chore: bump version to 10.0.0-next.1 w/ changelog
  CHANGELOG.md
  package.json
Labels: cla: yes, lgtm, merge ready, merge safe, target: major

#19389 build: update to latest MDC canary and fix error
  package.json
  src/material-experimental/mdc-form-field/BUILD.bazel
  yarn.lock
Labels: P3, cla: yes, lgtm, merge ready, merge safe, target: patch

#19393 refactor: update to tslib 2.0 and move to direct dependencies
  package.json
  packages.bzl
  src/cdk-experimental/package.json
  src/cdk/package.json
  src/components-examples/package.json
  src/material-experimental/package.json
  src/material-moment-adapter/package.json
  src/material/package.json
  yarn.lock
Labels: cla: yes, dependencies, lgtm, merge ready, merge safe, target: major

#19399 build: update to latest ts-node version
  package.json
  scripts/breaking-changes.ts
  scripts/caretaking/resync-caretaker-app-prs.ts
  yarn.lock
Labels: cla: yes, lgtm, merge ready, merge safe, target: patch

#19405 build: remove devmode tsickle decorator processing workaround
  src/bazel-tsconfig-build.json
  src/bazel-tsconfig-test.json
  src/universal-app/prerender.ts
  tools/BUILD.bazel
  tools/defaults.bzl
  tools/postinstall/apply-patches.js
Labels: cla: yes, lgtm, merge ready, merge safe, target: major

#19400 build: remove cherry-pick-patch script
  tools/cherry-pick-patch/cherry-pick-patch.ts
  tools/cherry-pick-patch/get-merged-pull-requests.ts
  tools/cherry-pick-patch/github.ts
  tools/cherry-pick-patch/output-results.ts
  tools/cherry-pick-patch/prompt.ts
  tools/cherry-pick-patch/tsconfig.json
Labels: cla: yes, lgtm, merge ready, merge safe, target: patch

#19404 fix(column-resize): Unbreak Sass build by importing duplicate styles …
  src/material-experimental/column-resize/_column-resize.scss
Labels: cla: yes, lgtm, merge ready, merge safe, target: patch

#19376 refactor(components-example): extract regions from component example source files
  src/components-examples/BUILD.bazel
  tools/highlight-files/BUILD.bazel
  tools/highlight-files/highlight-files.ts
  tools/highlight-files/index.bzl
  tools/markdown-to-html/docs-marked-renderer.ts
  tools/package-docs-content/BUILD.bazel
  tools/package-docs-content/index.bzl
  tools/package-docs-content/package-docs-content.ts
  tools/region-parser/BUILD.bazel
  tools/region-parser/README.md
  tools/region-parser/region-matchers/block-c.ts
  tools/region-parser/region-matchers/html.ts
  tools/region-parser/region-matchers/inline-c.ts
  tools/region-parser/region-parser.ts
  tools/region-parser/tsconfig.json
Labels: cla: yes, lgtm, merge ready, merge safe, target: patch

#19396 fix(drag-drop): error during device emulation on firefox
  src/cdk/drag-drop/directives/drag.spec.ts
  src/cdk/drag-drop/drag-ref.ts
Labels: P3, cla: yes, lgtm, merge ready, target: patch

#19379 refactor(slider): change deprecated APIs for version 10
  src/material/schematics/ng-update/data/constructor-checks.ts
  src/material/slider/slider.ts
  tools/public_api_guard/material/slider.d.ts
Labels: P2, cla: yes, lgtm, merge ready, target: major

#19362 refactor(clipboard): remove deprecated APIs for version 10
  src/cdk/clipboard/copy-to-clipboard.ts
  src/cdk/schematics/ng-update/data/output-names.ts
  tools/public_api_guard/cdk/clipboard.d.ts
Labels: P2, cla: yes, lgtm, merge ready, target: major

#19361 fix(drag-drop): error when item enters from the top and list has an intermediate child
  src/cdk/drag-drop/directives/drag.spec.ts
  src/cdk/drag-drop/drop-list-ref.ts
Labels: P3, cla: yes, lgtm, merge ready, target: patch

#19356 fix(dialog): focus recapturing not accounting for autoFocus option
  src/material/dialog/dialog-container.ts
  src/material/dialog/dialog.spec.ts
Labels: P3, cla: yes, lgtm, merge ready, target: patch

#19321 fix(table): incorrectly sticking multiple footer rows
  src/cdk/table/sticky-styler.ts
  src/cdk/table/table.spec.ts
Labels: P3, cla: yes, lgtm, merge ready, target: patch

#19378 fix(google-maps): allow different anchor objects for info window
  src/google-maps/map-anchor-point.ts
  src/google-maps/map-info-window/map-info-window.spec.ts
  src/google-maps/map-info-window/map-info-window.ts
  src/google-maps/map-marker/map-marker.ts
  src/google-maps/public-api.ts
  tools/public_api_guard/google-maps/google-maps.d.ts
Labels: P3, cla: yes, lgtm, merge ready, target: major

#19412 build: update to angular v10.0.0-rc.0
  package.json
  yarn.lock
Labels: cla: yes, lgtm, merge ready, merge safe, target: major

#19411 fix(material-experimental/mdc-slider): remove slider theme from all-theme
  src/material-experimental/mdc-theming/_all-theme.scss
Labels: cla: yes, lgtm, merge ready, merge safe, target: major

#19415 build: remove ng-dev typescript configuration workaround
  .ng-dev-config.ts
  package.json
  scripts/determine-merge-branches.ts
  yarn.lock
Labels: cla: yes, lgtm, merge ready, merge safe, target: major

#19413 test: add characterization tests for DocsMarkedRenderer
  tools/markdown-to-html/BUILD.bazel
  tools/markdown-to-html/docs-marked-renderer.spec.ts
  tools/markdown-to-html/tsconfig.json
Labels: cla: yes, lgtm, merge ready, merge safe, target: patch

#19372 refactor(sort): change deprecated APIs for version 10
  src/material/schematics/ng-update/data/constructor-checks.ts
  src/material/sort/sort-header.ts
  tools/public_api_guard/material/sort.d.ts
Labels: P2, cla: yes, lgtm, merge ready, target: major

#19289 refactor(button-toggle): remove deprecated APIs for version 10
  src/material/button-toggle/button-toggle.spec.ts
  src/material/button-toggle/button-toggle.ts
  src/material/schematics/ng-update/data/class-names.ts
  tools/public_api_guard/material/button-toggle.d.ts
Labels: P2, cla: yes, lgtm, merge ready, target: major

#19144 feat(tooltip/testing): add test harness for mat-tooltip
  src/cdk/testing/protractor/protractor-element.ts
  src/cdk/testing/test-element.ts
  src/cdk/testing/testbed/unit-test-element.ts
  src/cdk/testing/tests/test-main-component.ts
  src/cdk/testing/tests/testbed.spec.ts
  src/material/config.bzl
  src/material/tooltip/testing/BUILD.bazel
  src/material/tooltip/testing/index.ts
  src/material/tooltip/testing/public-api.ts
  src/material/tooltip/testing/shared.spec.ts
  src/material/tooltip/testing/tooltip-harness-filters.ts
  src/material/tooltip/testing/tooltip-harness.spec.ts
  src/material/tooltip/testing/tooltip-harness.ts
  src/material/tooltip/tooltip.ts
  tools/public_api_guard/cdk/testing.d.ts
  tools/public_api_guard/cdk/testing/protractor.d.ts
  tools/public_api_guard/cdk/testing/testbed.d.ts
  tools/public_api_guard/material/tooltip/testing.d.ts
Labels: P2, cla: yes, lgtm, merge ready, target: major

#19278 refactor(core): remove deprecated gesture code
  src/material/core/gestures/gesture-annotations.ts
  src/material/core/gestures/gesture-config.ts
  src/material/core/public-api.ts
  tools/public_api_guard/material/core.d.ts
Labels: P2, cla: yes, lgtm, merge ready, target: major

#19426 build: bump tooling packages to rc
  package.json
  yarn.lock
Labels: P3, cla: yes, lgtm, merge ready, merge safe, target: major

#19325 refactor(autocomplete): change deprecated APIs for version 10
  src/material/autocomplete/autocomplete-trigger.ts
  src/material/schematics/ng-update/data/constructor-checks.ts
  tools/public_api_guard/material/autocomplete.d.ts
Labels: P2, cla: yes, lgtm, merge ready, target: major

#19347 refactor(platform): change deprecated APIs for version 10
  src/cdk/a11y/focus-trap/focus-trap.spec.ts
  src/cdk/a11y/high-contrast-mode/high-contrast-mode-detector.spec.ts
  src/cdk/a11y/interactivity-checker/interactivity-checker.spec.ts
  src/cdk/platform/platform.ts
  src/cdk/schematics/ng-update/data/constructor-checks.ts
  src/material-experimental/mdc-input/input.spec.ts
  src/material-experimental/mdc-slider/slider.spec.ts
  src/material/checkbox/testing/shared.spec.ts
  src/material/input/input.spec.ts
  src/material/radio/testing/shared.spec.ts
  src/material/slide-toggle/testing/shared.spec.ts
  tools/public_api_guard/cdk/platform.d.ts
Labels: P2, cla: yes, lgtm, merge ready, target: major

#19364 refactor(tooltip): change deprecated APIs for version 10
  src/material/schematics/ng-update/data/constructor-checks.ts
  src/material/tooltip/tooltip.ts
  tools/public_api_guard/material/tooltip.d.ts
Labels: P2, cla: yes, lgtm, merge ready, target: major

#19323 refactor(icon): change deprecated APIs for version 10
  src/material/icon/icon-registry.ts
  src/material/icon/icon.ts
  src/material/schematics/ng-update/data/constructor-checks.ts
  tools/public_api_guard/material/icon.d.ts
Labels: P2, cla: yes, lgtm, merge ready, target: major

#19431 docs(cdk/focus-trap): fix FocusTrap class documentation typo
  src/cdk/a11y/focus-trap/focus-trap.ts
Labels: cla: yes, docs, lgtm, merge ready, merge safe, target: patch

#19447 test(tooltip/testing): disable tests on touch devices
  src/material/tooltip/testing/BUILD.bazel
  src/material/tooltip/testing/shared.spec.ts
Labels: P2, cla: yes, lgtm, merge ready, merge safe, target: major

#19452 chore: bump version to 10.0.0-rc.0 w/ changelog
  CHANGELOG.md
  package.json
  tools/triage-tracker/functions/lib/index.js
  tools/triage-tracker/functions/lib/index.js.map
Labels: cla: yes, lgtm, merge ready, merge safe, target: major

#19453 release: change v10 rc.0 to next.2 due to issue uncovered in pre-release testing
  CHANGELOG.md
  package.json
Labels: cla: yes, merge safe, target: major

#19485 chore: remove squares braces from issue title templates
  .github/ISSUE_TEMPLATE/bug.md
  .github/ISSUE_TEMPLATE/docs.md
  .github/ISSUE_TEMPLATE/feature.md
  .github/ISSUE_TEMPLATE/troubleshooting.md
Labels: cla: yes, lgtm, merge ready, merge safe, target: major
