Repository angular/components, pull requests merged in 2020-03, with the labels that each got.

#18660 fix(datepicker): add gap between range rows and handle rtl
  src/material/datepicker/calendar-body.scss
  src/material/datepicker/calendar-body.ts
Labels: P3, cla: yes, pr: lgtm, pr: merge ready, pr: merge safe, target: development-branch

#18700 chore: bump version to 9.1.1 w/ changelog
  CHANGELOG.md
  package.json
Labels: cla: yes, lgtm, merge ready, merge safe, target: patch

#18685 fix(cdk/testing): don't send unnecessary `Key.chord`s to protractor
  src/cdk/testing/protractor/protractor-element.ts
Labels: G, P2, cla: yes, lgtm, merge ready, target: patch

#18691 build: avoid file collisions in docs-content
  tools/dgeni/index.bzl
  tools/package-docs-content/index.bzl
Labels: P3, cla: yes, lgtm, merge ready, merge safe, target: patch

#18690 docs: do not show deprecated label options in form-field overview
  src/material/form-field/form-field.md
Labels: cla: yes, docs, lgtm, merge ready, merge safe, target: patch

#18687 build: update to rules_nodejs v1.4.0
  WORKSPACE
  package.json
  tools/postinstall/apply-patches.js
  tools/postinstall/manifest_externs_hermeticity.patch
  yarn.lock
Labels: cla: yes, lgtm, merge ready, merge safe, target: patch

#18679 build: fix dev-server running in snippet mode
  tools/dev-server/dev-server.ts
Labels: cla: yes, lgtm, merge ready, merge safe, target: patch

#18674 Update table-row-context-example.html
  src/components-examples/material/table/table-row-context/table-row-context-example.html
Labels: cla: yes, docs, lgtm, merge ready, merge safe, target: patch

#18672 build: include tslib helpers in umd bundles
  rollup-globals.bzl
Labels: cla: yes, lgtm, merge ready, merge safe, target: patch

#18664 fix: event emitter type
  src/material/tabs/tab-body.ts
  tools/public_api_guard/material/tabs.d.ts
Labels: P2, cla: yes, lgtm, merge ready, merge safe, target: patch

#18661 docs(tooltip): scrollable example not working
  src/cdk/scrolling/scroll-dispatcher.spec.ts
  src/components-examples/material/tooltip/BUILD.bazel
  src/components-examples/material/tooltip/index.ts
  src/components-examples/material/tooltip/tooltip-auto-hide/tooltip-auto-hide-example.html
  src/material/tooltip/tooltip.spec.ts
Labels: P3, cla: yes, lgtm, merge ready, merge safe, target: patch

#18657 fix(datepicker): prevent default dialog options from affecting touch ui calendar
  src/material/datepicker/BUILD.bazel
  src/material/datepicker/datepicker.spec.ts
  src/material/datepicker/datepicker.ts
Labels: P3, cla: yes, lgtm, merge ready, target: patch

#18717 chore: add title format and "needs triage" label in issue template
  .github/ISSUE_TEMPLATE.md
  .github/ISSUE_TEMPLATE/bug.md
  .github/ISSUE_TEMPLATE/docs.md
  .github/ISSUE_TEMPLATE/feature.md
  .github/ISSUE_TEMPLATE/troubleshooting.md
Labels: cla: yes, lgtm, merge ready, merge safe, target: patch

#18712 build: update to latest angular version that fixes AMD module names
  package.json
  yarn.lock
Labels: cla: yes, lgtm, merge ready, merge safe, target: patch

#18725 docs: clarify "what we're working on" in readme
  README.md
Labels: cla: yes, docs, lgtm, merge ready, merge safe, target: patch

#18720 build: include tslib as explicit dependency for `ng_package` rule
  tools/defaults.bzl
Labels: cla: yes, lgtm, merge ready, merge safe, target: patch

#18715 build: add clipboard to dev app
  .github/CODEOWNERS
  src/dev-app/BUILD.bazel
  src/dev-app/clipboard/BUILD.bazel
  src/dev-app/clipboard/clipboard-demo-module.ts
  src/dev-app/clipboard/clipboard-demo.html
  src/dev-app/clipboard/clipboard-demo.scss
  src/dev-app/clipboard/clipboard-demo.ts
  src/dev-app/dev-app/dev-app-layout.ts
  src/dev-app/dev-app/routes.ts
Labels: P3, cla: yes, lgtm, merge ready, merge safe, target: patch

#18710 build: upload release packages as job artifacts for PRs
  .circleci/config.yml
  DEV_ENVIRONMENT.md
  scripts/create-package-archives.js
Labels: cla: yes, lgtm, merge ready, merge safe, target: patch

#18709 fix(radio): Move .mat-radio-input above .mat-focus-indicator.
  src/material/radio/radio.html
Labels: cla: yes, lgtm, merge ready, merge safe, target: patch

#18555 fix(typography): default to normal letter spacing
  src/material/core/typography/_typography.scss
Labels: cla: yes, lgtm, merge ready, target: patch

#18727 fix(material-experimental/mdc-progress-bar): account for breaking changes in latest canary
  package.json
  src/material-experimental/mdc-progress-bar/progress-bar.html
  src/material-experimental/mdc-progress-bar/progress-bar.spec.ts
  src/material-experimental/mdc-progress-bar/progress-bar.ts
  yarn.lock
Labels: P2, cla: yes, lgtm, merge ready, merge safe, target: patch

#18741 fix(material-experimental/mdc-form-field): avoid expression changed a…
  src/material-experimental/mdc-form-field/form-field.ts
Labels: cla: yes, lgtm, merge ready, merge safe, target: patch

#18731 chore: split portion of CHANGELOG.md
  CHANGELOG.md
  CHANGELOG_ARCHIVE.md
Labels: cla: yes, docs, lgtm, merge ready, merge safe, target: patch

#18732 chore: add script to resync caretaker app open PRs
  package.json
  scripts/caretaking/resync-caretaker-app-prs.ts
  yarn.lock
Labels: cla: yes, lgtm, merge ready, merge safe, target: patch

#18738 refactor: ensure typography mixins expect consistent arguments
  src/material-experimental/mdc-checkbox/_checkbox-theme.scss
  src/material-experimental/mdc-list/_list-theme.scss
  src/material-experimental/mdc-progress-bar/_progress-bar-theme.scss
Labels: cla: yes, lgtm, merge ready, merge safe, target: patch

#18743 chore: copy 9.1.1 changelog to master
  CHANGELOG.md
  package.json
Labels: cla: yes, lgtm, merge ready, merge safe, target: minor

#18761 feat: add mixins for density styles of all components
  .github/CODEOWNERS
  src/dev-app/theme.scss
  src/material-experimental/mdc-density/BUILD.bazel
  src/material-experimental/mdc-density/_all-density.scss
  src/material-experimental/mdc-typography/BUILD.bazel
  src/material-experimental/mdc-typography/_all-typography.scss
  src/material/core/density/_all-density.scss
  src/material/core/typography/_all-typography.scss
Labels: cla: yes, lgtm, merge ready, merge safe, target: development-branch

#18765 build: do not hide output of bazel yarn install
  WORKSPACE
Labels: cla: yes, lgtm, merge ready, merge safe, target: patch

#18758 fix(column-resize): don't allow dragging using the right mouse button
  src/cdk-experimental/column-resize/overlay-handle.ts
  src/material-experimental/column-resize/column-resize.spec.ts
Labels: P3, cla: yes, lgtm, merge ready, merge safe, target: patch

#18751 docs(sort): fix grammar in the 'sort' documentation
  src/material/sort/sort.md
Labels: cla: yes, commit message fixup, docs, lgtm, merge ready, merge safe, target: patch

#18583 fix(material-experimental/mdc-slider): resolve warnings about active event listeners
  src/material-experimental/mdc-slider/slider.ts
Labels: P3, cla: yes, lgtm, merge ready, merge safe, target: patch

#18178 feat(cdk/testing): Allow custom `querySelectorAll` method
  package.json
  rollup-globals.bzl
  src/cdk/testing/BUILD.bazel
  src/cdk/testing/protractor/protractor-harness-environment.ts
  src/cdk/testing/require-config.js
  src/cdk/testing/testbed/testbed-harness-environment.ts
  src/cdk/testing/tests/BUILD.bazel
  src/cdk/testing/tests/harnesses/main-component-harness.ts
  src/cdk/testing/tests/kagekiri.spec.d.ts
  src/cdk/testing/tests/protractor.e2e.spec.ts
  src/cdk/testing/tests/test-components-module.ts
  src/cdk/testing/tests/test-main-component.html
  src/cdk/testing/tests/test-main-component.ts
  src/cdk/testing/tests/test-shadow-boundary.ts
  src/cdk/testing/tests/testbed.spec.ts
  src/e2e-app/BUILD.bazel
  src/e2e-app/index.html
  test/karma.conf.js
  tools/public_api_guard/cdk/testing/protractor.d.ts
  tools/public_api_guard/cdk/testing/testbed.d.ts
  tools/system-config-tmpl.js
  tslint.json
  yarn.lock
Labels: cla: yes, lgtm, merge ready, target: minor

#18615 fix(material-experimental/mdc-*): rename sass mixins to mat-mdc-*
  src/dev-app/theme.scss
  src/e2e-app/theme.scss
  src/material-experimental/README.md
  src/material-experimental/mdc-autocomplete/_autocomplete-theme.scss
  src/material-experimental/mdc-button/_button-theme.scss
  src/material-experimental/mdc-card/_card-theme.scss
  src/material-experimental/mdc-checkbox/README.md
  src/material-experimental/mdc-checkbox/_checkbox-theme.scss
  src/material-experimental/mdc-chips/_chips-theme.scss
  src/material-experimental/mdc-form-field/README.md
  src/material-experimental/mdc-form-field/_form-field-theme.scss
  src/material-experimental/mdc-input/README.md
  src/material-experimental/mdc-input/_input-theme.scss
  src/material-experimental/mdc-list/_list-theme.scss
  src/material-experimental/mdc-menu/README.md
  src/material-experimental/mdc-menu/_menu-theme.scss
  src/material-experimental/mdc-progress-bar/README.md
  src/material-experimental/mdc-progress-bar/_progress-bar-theme.scss
  src/material-experimental/mdc-radio/_radio-theme.scss
  src/material-experimental/mdc-select/_select-theme.scss
  src/material-experimental/mdc-sidenav/_sidenav-theme.scss
  src/material-experimental/mdc-slide-toggle/README.md
  src/material-experimental/mdc-slide-toggle/_slide-toggle-theme.scss
  src/material-experimental/mdc-slider/_slider-theme.scss
  src/material-experimental/mdc-snackbar/_snackbar-theme.scss
  src/material-experimental/mdc-table/_table-theme.scss
  src/material-experimental/mdc-tabs/README.md
  src/material-experimental/mdc-tabs/_tabs-theme.scss
  src/material-experimental/mdc-theming/_all-theme.scss
  src/material-experimental/mdc-theming/prebuilt/indigo-pink.scss
  src/material-experimental/mdc-typography/_all-typography.scss
  src/universal-app/theme.scss
Labels: P2, caretaker note, cla: yes, lgtm, merge ready, target: patch

#18770 build: add support for common typos in `yarn test`
  scripts/run-component-tests.js
Labels: cla: yes, lgtm, merge ready, merge safe, target: patch

#18736 build: setup snapshot builds for experimental and new packages
  scripts/deploy/publish-build-artifacts.sh
Labels: cla: yes, lgtm, merge ready, merge safe, target: patch

#18781 chore: bump version to 9.1.2 w/ changelog
  CHANGELOG.md
  package.json
Labels: cla: yes, lgtm, merge ready, merge safe, target: patch

#18782 chore: bump version to 9.1.2 w/ changelog
  CHANGELOG.md
  package.json
Labels: cla: yes, lgtm, merge ready, merge safe, target: patch

#18753 feat(datepicker): implement comparison and overlap ranges
  src/dev-app/datepicker/BUILD.bazel
  src/dev-app/datepicker/datepicker-demo.html
  src/dev-app/datepicker/datepicker-demo.scss
  src/dev-app/datepicker/datepicker-demo.ts
  src/material/datepicker/_datepicker-theme.scss
  src/material/datepicker/calendar-body.html
  src/material/datepicker/calendar-body.scss
  src/material/datepicker/calendar-body.ts
  src/material/datepicker/calendar.html
  src/material/datepicker/calendar.ts
  src/material/datepicker/date-range-input.ts
  src/material/datepicker/date-range-picker.ts
  src/material/datepicker/datepicker-base.ts
  src/material/datepicker/datepicker-content.html
  src/material/datepicker/month-view.html
  src/material/datepicker/month-view.ts
  tools/public_api_guard/material/datepicker.d.ts
Labels: P3, cla: yes, merge safe, target: development-branch

#18357 fix(radio): clicks not landing correctly in some cases on Chrome
  src/material/radio/BUILD.bazel
  src/material/radio/radio.spec.ts
  src/material/radio/radio.ts
Labels: P3, cla: yes, lgtm, merge ready, target: patch

#18567 fix(list): no disabled indication in high contrast mode
  src/material/list/list.scss
Labels: P3, a11y, cla: yes, lgtm, merge ready, target: patch

#18573 fix(google-maps): server-side rendering error for polygon and rectangle components
  src/google-maps/map-marker/map-marker.ts
  src/google-maps/map-polygon/map-polygon.ts
  src/google-maps/map-polyline/map-polyline.ts
  src/google-maps/map-rectangle/map-rectangle.ts
  src/universal-app/kitchen-sink/kitchen-sink.html
Labels: P3, cla: yes, lgtm, merge ready, target: patch

#18582 refactor(platform): consolidate and expose shadow dom detection utilities
  src/cdk/drag-drop/drop-list-ref.ts
  src/cdk/platform/features/shadow-dom.ts
  src/material/autocomplete/autocomplete-trigger.ts
  src/material/progress-spinner/progress-spinner.spec.ts
  src/material/progress-spinner/progress-spinner.ts
  tools/public_api_guard/cdk/platform.d.ts
Labels: P2, cla: yes, lgtm, merge ready, target: patch

#18595 fix(cdk/overlay): support SVG element as overlay origin
  src/cdk/overlay/position/flexible-connected-position-strategy.spec.ts
  src/cdk/overlay/position/flexible-connected-position-strategy.ts
Labels: P3, cla: yes, lgtm, merge ready, target: patch

#18626 fix(clipboard): not restoring focus to SVG elements
  src/cdk/clipboard/clipboard.spec.ts
  src/cdk/clipboard/pending-copy.ts
Labels: P3, cla: yes, lgtm, merge ready, target: patch

#18632 fix(material-experimental/mdc-list): fix styles for normal lists
  .stylelintrc.json
  src/components-examples/material/list/list-sections/list-sections-example.html
  src/dev-app/list/list-demo.html
  src/dev-app/mdc-list/mdc-list-demo.html
  src/material-experimental/mdc-list/list-base.ts
  src/material-experimental/mdc-list/list-item.html
  src/material-experimental/mdc-list/list.scss
  src/material-experimental/mdc-list/list.ts
  src/material-experimental/mdc-list/module.ts
  src/material-experimental/mdc-list/selection-list.ts
  src/material/core/line/line.ts
  tools/public_api_guard/material/core.d.ts
Labels: cla: yes, lgtm, merge ready, target: patch

#18666 fix(form-field): error when trying to lock label into position too early
  src/material/form-field/form-field.ts
  src/material/input/input.spec.ts
Labels: P3, cla: yes, lgtm, merge ready, target: patch

#18698 fix(drag-drop): detect changes on custom preview/placeholder before measuring
  src/cdk/drag-drop/directives/drag.spec.ts
  src/cdk/drag-drop/drag-ref.ts
Labels: P3, cla: yes, lgtm, merge ready, target: patch

#18706 fix(drag-drop): only return item to initial index if the new container's sorting is disabled
  src/cdk/drag-drop/directives/drag.spec.ts
  src/cdk/drag-drop/drag-ref.ts
Labels: P3, cla: yes, lgtm, merge ready, target: patch

#18756 fix(menu): allow focus to be moved inside menuClosed event
  src/material-experimental/mdc-menu/menu.spec.ts
  src/material/menu/menu-trigger.ts
  src/material/menu/menu.spec.ts
Labels: P3, cla: yes, lgtm, merge ready, target: patch

#18757 fix(drag-drop): error on IE when document is being auto scrolled
  src/cdk/drag-drop/drop-list-ref.ts
Labels: P3, cla: yes, lgtm, merge ready, target: patch

#18776 fix(mdc-form-field): refresh notch width when toggling appearances
  src/material-experimental/mdc-form-field/_mdc-text-field-textarea-overrides.scss
  src/material-experimental/mdc-form-field/directives/notched-outline.ts
Labels: cla: yes, lgtm, merge ready, merge safe, target: patch

#18778 fix(material/mdc-form-field): text-field should stretch based on host element
  src/dev-app/mdc-input/mdc-input-demo.html
  src/material-experimental/mdc-form-field/form-field.scss
Labels: cla: yes, lgtm, merge ready, merge safe, target: patch

#18780 fix(document-injection): Update to use injected document
  src/cdk/a11y/focus-monitor/focus-monitor.ts
  src/cdk/drag-drop/directives/drag.spec.ts
  src/cdk/scrolling/scroll-dispatcher.ts
  src/cdk/scrolling/viewport-ruler.ts
  src/cdk/text-field/autosize.ts
  src/material/autocomplete/autocomplete-trigger.ts
  src/material/core/common-behaviors/common-module.ts
  src/material/slider/slider.ts
  tools/public_api_guard/cdk/a11y.d.ts
  tools/public_api_guard/cdk/scrolling.d.ts
  tools/public_api_guard/cdk/text-field.d.ts
  tools/public_api_guard/material/core.d.ts
Labels: G, cla: yes, lgtm, merge ready, target: patch

#18384 fix(material-experimental/slider): add slider mixin to main theme mixin
  src/dev-app/BUILD.bazel
  src/dev-app/theme.scss
  src/material-experimental/mdc-theming/BUILD.bazel
  src/material-experimental/mdc-theming/_all-theme.scss
  src/universal-app/BUILD.bazel
  src/universal-app/theme.scss
Labels: P3, cla: yes, lgtm, merge ready, merge safe, target: patch

#18568 Maps circle
  src/dev-app/google-map/google-map-demo.html
  src/dev-app/google-map/google-map-demo.ts
  src/google-maps/google-maps-module.ts
  src/google-maps/map-circle/map-circle.spec.ts
  src/google-maps/map-circle/map-circle.ts
  src/google-maps/public-api.ts
  src/google-maps/testing/fake-google-map-utils.ts
  tools/public_api_guard/google-maps/google-maps.d.ts
Labels: P3, cla: yes, commit message fixup, feature, lgtm, merge ready, target: minor

#18795 fix(material-experimetal/mdc-form-field): account for breaking changes in MDC
  package.json
  src/material-experimental/mdc-form-field/_mdc-text-field-structure-overrides.scss
  yarn.lock
Labels: P3, cla: yes, lgtm, merge ready, merge safe, target: patch

#18777 feat(form-field): use injection token for providing form-field
  src/material-experimental/mdc-form-field/form-field.ts
  src/material/autocomplete/autocomplete-trigger.ts
  src/material/datepicker/datepicker-input.ts
  src/material/form-field/form-field.ts
  src/material/select/select.ts
  tools/public_api_guard/material/form-field.d.ts
Labels: P3, cla: yes, lgtm, merge ready, target: minor

#18766 feat(material/snackbar): add `isDismissed` harness method
  src/material/snack-bar/snack-bar-container.ts
  src/material/snack-bar/snack-bar.spec.ts
  src/material/snack-bar/testing/shared.spec.ts
  src/material/snack-bar/testing/snack-bar-harness.ts
  tools/public_api_guard/material/snack-bar/testing.d.ts
Labels: cla: yes, lgtm, merge ready, target: minor

#18803 build: ensure correct toolchains used for remote execution
  .bazelrc
Labels: cla: yes, lgtm, merge ready, merge safe, target: patch

#18789 build: update to typescript v3.8
  .circleci/config.yml
  .github/CODEOWNERS
  integration/ts-compat/BUILD.bazel
  integration/ts-compat/helpers.js
  integration/ts-compat/import-all-entry-points.bzl
  integration/ts-compat/test.js
  package.json
  src/cdk/schematics/ng-update/upgrade-rules/class-names-rule.ts
  src/cdk/schematics/utils/ast/ng-module-imports.ts
  yarn.lock
Labels: P2, cla: yes, lgtm, merge ready, merge safe, target: minor

#18772 docs(material/expansion-panel): throws No provider found for DateAdapter
  src/components-examples/material/expansion/index.ts
Labels: P2, cla: yes, docs, lgtm, merge ready, merge safe, target: patch

#18819 fix(datepicker): resolve visual inconsistencies with comparison ranges
  src/material/datepicker/calendar-body.scss
  src/material/datepicker/calendar-body.ts
Labels: P3, cla: yes, lgtm, merge ready, merge safe, target: development-branch

#18820 Revert "fix(radio): clicks not landing correctly in some cases on Chrome (#18357)"
  src/material/radio/BUILD.bazel
  src/material/radio/radio.spec.ts
  src/material/radio/radio.ts
Labels: cla: yes, lgtm, merge ready

#16468 docs(table): fix incorrect class description
  src/material/table/row.ts
Labels: P3, cla: yes, docs, lgtm, merge ready, merge safe, target: patch

#18792 docs(coding standards): when to use getters & observable naming
  CODING_STANDARDS.md
Labels: cla: yes, lgtm, merge ready, merge safe, target: patch

#18816 docs-bug(Datepicker): link to Moment broken
  src/material/datepicker/datepicker.md
Labels: cla: yes, commit message fixup, docs, lgtm, merge ready, merge safe, target: patch

#18823 build: update tslint to latest version
  package.json
  yarn.lock
Labels: cla: yes, lgtm, merge ready, merge safe, target: minor

#18785 build: update to angular v9.0.6
  package.json
  tools/release/release-output/check-package.ts
  tools/release/release-output/output-validations.ts
  tools/release/stage-release.ts
  yarn.lock
Labels: P2, caretaker note, cla: yes, lgtm, merge ready, merge safe, target: patch

#18841 chore: bump version to 9.1.3 w/ changelog
  CHANGELOG.md
  package.json
Labels: P2, cla: yes, lgtm, merge ready, target: patch

#18842 chore: bump version to 9.1.3 w/ changelog (#18841)
  CHANGELOG.md
  package.json
Labels: cla: yes, lgtm, merge ready, merge safe, target: patch

#18835 refactor(column-resize): simplify RTL handling
  src/cdk-experimental/column-resize/column-resize-directives/column-resize-flex.ts
  src/cdk-experimental/column-resize/column-resize-directives/column-resize.ts
  src/cdk-experimental/column-resize/column-resize-directives/constants.ts
  src/cdk-experimental/column-resize/column-resize-directives/default-enabled-column-resize-flex.ts
  src/cdk-experimental/column-resize/column-resize-directives/default-enabled-column-resize.ts
  src/cdk-experimental/column-resize/column-resize.ts
  src/material-experimental/column-resize/_column-resize.scss
  src/material-experimental/column-resize/column-resize-directives/column-resize-flex.ts
  src/material-experimental/column-resize/column-resize-directives/column-resize.ts
  src/material-experimental/column-resize/column-resize-directives/common.ts
  src/material-experimental/column-resize/column-resize-directives/default-enabled-column-resize-flex.ts
  src/material-experimental/column-resize/column-resize-directives/default-enabled-column-resize.ts
Labels: P3, cla: yes, lgtm, merge ready, merge safe, target: patch

#18844 docs(form-field): Use Form Validation in custom control example
  src/components-examples/material-experimental/mdc-form-field/mdc-form-field-custom-control/form-field-custom-control-example.ts
  src/components-examples/material/form-field/form-field-custom-control/form-field-custom-control-example.ts
Labels: cla: yes, lgtm, merge ready, merge safe, target: patch

#18684 feat(focus-monitor): Add eventual detection mode option to focus monitor
  src/cdk/a11y/focus-monitor/focus-monitor.spec.ts
  src/cdk/a11y/focus-monitor/focus-monitor.ts
  tools/public_api_guard/cdk/a11y.d.ts
Labels: G, cla: yes, lgtm, merge ready, target: minor

#18848 build: update to latest `@bazel/ibazel` version v0.12.3
  package.json
  yarn.lock
Labels: cla: yes, lgtm, merge ready, merge safe, target: patch

#18860 chore: bump version to 9.2.0-next.0 w/ changelog
  CHANGELOG.md
  package.json
Labels: cla: yes, lgtm, merge ready, target: minor

#18865 Add release output validation for manifest paths and downgrade octokit API
  package.json
  tools/release/release-output/check-package.ts
  tools/release/release-output/output-validations.ts
  tools/release/stage-release.ts
  yarn.lock
Labels: caretaker note, cla: yes, lgtm, merge ready, merge safe

#18868 fix(material-experimental/radio): remove input click handler
  src/material-experimental/mdc-radio/radio.html
Labels: P2, cla: yes, lgtm, merge ready, merge safe, target: patch

#18832 fix(table): error when nesting tables
  src/cdk/table/cell.ts
  src/cdk/table/public-api.ts
  src/cdk/table/row.ts
  src/cdk/table/table.spec.ts
  src/cdk/table/table.ts
  src/cdk/table/text-column.spec.ts
  src/cdk/table/text-column.ts
  src/cdk/table/tokens.ts
  src/material-experimental/mdc-table/table.spec.ts
  src/material/table/table.spec.ts
  src/material/table/table.ts
  tools/public_api_guard/cdk/table.d.ts
Labels: P2, cla: yes, lgtm, merge ready, target: patch

#18867 fix(form-field): incorrectly calculating start gap in RTL in the presence of a prefix
  src/material/form-field/form-field.ts
  src/material/input/input.spec.ts
Labels: P2, cla: yes, lgtm, merge ready, target: patch

#18578 feat(google-maps): support setting the map type
  src/dev-app/google-map/google-map-demo.html
  src/dev-app/google-map/google-map-demo.ts
  src/google-maps/google-map/google-map.spec.ts
  src/google-maps/google-map/google-map.ts
  src/google-maps/testing/fake-google-map-utils.ts
  tools/public_api_guard/google-maps/google-maps.d.ts
Labels: P3, cla: yes, lgtm, merge ready, target: minor

#18585 fix(list): no selected indication in high contrast mode while in single selection
  src/material/list/list.scss
Labels: P3, cla: yes, lgtm, merge ready, target: patch

#18830 fix(material-experimental/mdc-chips): add feature targeting to theme styles
  src/material-experimental/mdc-chips/_chips-theme.scss
Labels: P3, cla: yes, lgtm, merge ready, target: patch

#18786 refactor: change isDateInstance return type to is D
  src/material-moment-adapter/adapter/moment-date-adapter.ts
  src/material/core/datetime/date-adapter.ts
  src/material/core/datetime/native-date-adapter.ts
  tools/public_api_guard/material/core.d.ts
Labels: cla: yes, lgtm, merge ready, target: patch

#18807 fix(cdk/coercion): add the support for readonly array coercion
  src/cdk/coercion/array.ts
  tools/public_api_guard/cdk/coercion.d.ts
Labels: cla: yes, lgtm, merge ready, target: patch

#18869 test(dialog): add missing event dispatch
  src/material/dialog/dialog.spec.ts
Labels: cla: yes, lgtm, merge ready, merge safe, target: patch

#18825 fix(form-field): some input types taller than plain text input
  src/material/form-field/form-field-input.scss
Labels: P4, cla: yes, lgtm, merge ready, target: patch

#18895 fix(material-experimental/slide-toggle): allow different densities
  src/material-experimental/mdc-slide-toggle/slide-toggle.html
  src/material-experimental/mdc-slide-toggle/slide-toggle.scss
Labels: P2, cla: yes, lgtm, merge ready, merge safe, target: patch

#18897 Revert "refactor: change isDateInstance return type to is D"
  src/material-moment-adapter/adapter/moment-date-adapter.ts
  src/material/core/datetime/date-adapter.ts
  src/material/core/datetime/native-date-adapter.ts
  tools/public_api_guard/material/core.d.ts
Labels: cla: yes, lgtm, merge ready

#18908 fix(material-experimental/slide-toggle): redefine more variables
  src/material-experimental/mdc-slide-toggle/_slide-toggle-theme.scss
Labels: P2, cla: yes, lgtm, merge ready, merge safe, target: patch

#18907 fix(material-experimental/radio): redefine theme variables
  src/material-experimental/mdc-radio/_radio-theme.scss
Labels: P2, cla: yes, lgtm, merge ready, merge safe, target: patch

#18892 refactor(material-experimental/mdc-form-field): unset MDC custom baseline adjustment
  src/material-experimental/mdc-form-field/_mdc-text-field-structure-overrides.scss
Labels: cla: yes, lgtm, merge ready, merge safe, target: patch

#18904 build: update to angular v9.1.0
  package.json
  tools/public_api_guard/cdk/a11y.d.ts
  tools/public_api_guard/cdk/accordion.d.ts
  tools/public_api_guard/cdk/bidi.d.ts
  tools/public_api_guard/cdk/clipboard.d.ts
  tools/public_api_guard/cdk/collections.d.ts
  tools/public_api_guard/cdk/drag-drop.d.ts
  tools/public_api_guard/cdk/layout.d.ts
  tools/public_api_guard/cdk/observers.d.ts
  tools/public_api_guard/cdk/overlay.d.ts
  tools/public_api_guard/cdk/platform.d.ts
  tools/public_api_guard/cdk/portal.d.ts
  tools/public_api_guard/cdk/scrolling.d.ts
  tools/public_api_guard/cdk/stepper.d.ts
  tools/public_api_guard/cdk/table.d.ts
  tools/public_api_guard/cdk/text-field.d.ts
  tools/public_api_guard/cdk/tree.d.ts
  tools/public_api_guard/google-maps/google-maps.d.ts
  tools/public_api_guard/material/autocomplete.d.ts
  tools/public_api_guard/material/badge.d.ts
  tools/public_api_guard/material/bottom-sheet.d.ts
  tools/public_api_guard/material/button-toggle.d.ts
  tools/public_api_guard/material/button.d.ts
  tools/public_api_guard/material/card.d.ts
  tools/public_api_guard/material/checkbox.d.ts
  tools/public_api_guard/material/chips.d.ts
  tools/public_api_guard/material/core.d.ts
  tools/public_api_guard/material/datepicker.d.ts
  tools/public_api_guard/material/dialog.d.ts
  tools/public_api_guard/material/divider.d.ts
  tools/public_api_guard/material/expansion.d.ts
  tools/public_api_guard/material/form-field.d.ts
  tools/public_api_guard/material/grid-list.d.ts
  tools/public_api_guard/material/icon.d.ts
  tools/public_api_guard/material/icon/testing.d.ts
  tools/public_api_guard/material/input.d.ts
  tools/public_api_guard/material/list.d.ts
  tools/public_api_guard/material/menu.d.ts
  tools/public_api_guard/material/paginator.d.ts
  tools/public_api_guard/material/progress-bar.d.ts
  tools/public_api_guard/material/progress-spinner.d.ts
  tools/public_api_guard/material/radio.d.ts
  tools/public_api_guard/material/select.d.ts
  tools/public_api_guard/material/sidenav.d.ts
  tools/public_api_guard/material/slide-toggle.d.ts
  tools/public_api_guard/material/slider.d.ts
  tools/public_api_guard/material/snack-bar.d.ts
  tools/public_api_guard/material/sort.d.ts
  tools/public_api_guard/material/stepper.d.ts
  tools/public_api_guard/material/table.d.ts
  tools/public_api_guard/material/tabs.d.ts
  tools/public_api_guard/material/toolbar.d.ts
  tools/public_api_guard/material/tooltip.d.ts
  tools/public_api_guard/material/tree.d.ts
  tools/public_api_guard/youtube-player/youtube-player.d.ts
  yarn.lock
Labels: cla: yes, lgtm, merge ready, merge safe, target: minor

#18921 chore: bump version to 9.2.0 w/ changelog
  CHANGELOG.md
  package.json
Labels: cla: yes, lgtm, merge ready, merge safe, target: minor

#18884 test(datepicker): add tests for the date range picker
  src/material/datepicker/calendar-body.spec.ts
  src/material/datepicker/calendar-body.ts
  src/material/datepicker/date-range-input.spec.ts
  src/material/datepicker/month-view.spec.ts
  src/material/datepicker/month-view.ts
  tools/public_api_guard/material/datepicker.d.ts
Labels: P3, cla: yes, lgtm, merge ready, merge safe, target: development-branch

#18946 fix(material-experimental/mdc-radio): add strong focus indication
  src/material-experimental/mdc-helpers/_mdc-helpers.scss
  src/material-experimental/mdc-radio/radio.html
  src/material-experimental/mdc-radio/radio.spec.ts
Labels: P3, cla: yes, lgtm, merge ready, merge safe, target: patch

#18945 fix(popover-edit): unable to close focus content using the keyboard
  src/cdk-experimental/popover-edit/popover-edit.spec.ts
  src/cdk-experimental/popover-edit/table-directives.ts
Labels: P3, cla: yes, lgtm, merge ready, merge safe, target: patch

#18938 fix(material-experimental/mdc-card): not handling dark themes
  src/dev-app/mdc-card/BUILD.bazel
  src/dev-app/mdc-card/mdc-card-demo-module.ts
  src/dev-app/mdc-card/mdc-card-demo.html
  src/dev-app/mdc-card/mdc-card-demo.ts
  src/material-experimental/mdc-card/_card-theme.scss
Labels: P3, cla: yes, lgtm, merge ready, merge safe, target: patch

#18937 fix(popover-edit): hover content not showing up if content changes after init
  src/cdk-experimental/popover-edit/edit-event-dispatcher.ts
  src/cdk-experimental/popover-edit/popover-edit.spec.ts
Labels: P3, cla: yes, lgtm, merge ready, merge safe, target: patch

#18919 build: clean up stylelint rules directory
  .stylelintrc.json
  tools/stylelint/no-ampersand-beyond-selector-start.js
  tools/stylelint/no-concrete-rules.js
  tools/stylelint/no-nested-mixin.js
  tools/stylelint/no-prefixes/index.js
  tools/stylelint/no-top-level-ampersand-in-mixin.js
  tools/stylelint/selector-no-deep.js
Labels: P3, cla: yes, lgtm, merge ready, merge safe, target: patch

#18899 build: set up ts-circular-deps check to prevent new circular deps
  .circleci/config.yml
  .github/CODEOWNERS
  goldens/ts-circular-deps.json
  package.json
  src/circular-deps-test.conf.js
  yarn.lock
Labels: cla: yes, merge ready, merge safe, target: patch

#18878 docs(button): add more comprehensive button examples
  src/components-examples/material/button/BUILD.bazel
  src/components-examples/material/button/button-overview/button-overview-example.css
  src/components-examples/material/button/button-overview/button-overview-example.html
  src/components-examples/material/button/index.ts
  src/dev-app/button/BUILD.bazel
  src/dev-app/button/button-demo-module.ts
  src/dev-app/button/button-demo.html
Labels: cla: yes, docs, lgtm, merge ready, merge safe, target: patch

#18836 docs(a11y): update high contrast description in readme
  src/cdk/a11y/a11y.md
Labels: P3, cla: yes, docs, lgtm, merge ready, merge safe, target: patch

#18620 feat(material-experimental/selection): Add Material version for `cdk-experimental/selection`
  .github/CODEOWNERS
  src/components-examples/BUILD.bazel
  src/components-examples/material-experimental/selection/BUILD.bazel
  src/components-examples/material-experimental/selection/index.ts
  src/components-examples/material-experimental/selection/mat-selection-column/mat-selection-column-example.css
  src/components-examples/material-experimental/selection/mat-selection-column/mat-selection-column-example.html
  src/components-examples/material-experimental/selection/mat-selection-column/mat-selection-column-example.ts
  src/components-examples/material-experimental/selection/mat-selection-list/mat-selection-list-example.html
  src/components-examples/material-experimental/selection/mat-selection-list/mat-selection-list-example.ts
  src/dev-app/example/example-list.ts
  src/dev-app/selection/BUILD.bazel
  src/dev-app/selection/selection-demo-module.ts
  src/dev-app/selection/selection-demo.ts
  src/material-experimental/config.bzl
  src/material-experimental/selection/BUILD.bazel
  src/material-experimental/selection/_selection.scss
  src/material-experimental/selection/index.ts
  src/material-experimental/selection/public-api.ts
  src/material-experimental/selection/row-selection.ts
  src/material-experimental/selection/select-all.ts
  src/material-experimental/selection/selection-column.scss
  src/material-experimental/selection/selection-column.ts
  src/material-experimental/selection/selection-module.ts
  src/material-experimental/selection/selection-toggle.ts
  src/material-experimental/selection/selection.ts
Labels: G, P3, cla: yes, lgtm, merge ready, merge safe, target: patch

#18957 build: resolve module names in circular deps test
  src/circular-deps-test.conf.js
Labels: cla: yes, lgtm, merge ready, merge safe, target: patch

#18930 refactor(tree): remove renderer usage
  src/cdk/tree/padding.ts
  tools/public_api_guard/cdk/tree.d.ts
Labels: P4, cla: yes, lgtm, merge ready, target: patch

#18918 fix(drag-drop): defer resolving scrollable parents until first drag
  src/cdk/drag-drop/directives/drop-list.ts
  tools/public_api_guard/cdk/drag-drop.d.ts
Labels: P3, cla: yes, lgtm, merge ready, target: patch

#18914 fix(drag-drop): allow preview z-index to be changed
  src/cdk/drag-drop/directives/config.ts
  src/cdk/drag-drop/directives/drag.spec.ts
  src/cdk/drag-drop/directives/drag.ts
  src/cdk/drag-drop/drag-ref.ts
  tools/public_api_guard/cdk/drag-drop.d.ts
Labels: P3, cla: yes, lgtm, merge ready, target: patch

#18905 fix(slider): not stopping drag when released outside of viewport
  src/material/slider/slider.spec.ts
  src/material/slider/slider.ts
Labels: P3, cla: yes, lgtm, merge ready, target: patch

#18876 fix(datepicker): disable calendar hover styles on touch devices
  src/material/datepicker/calendar-body.scss
Labels: P3, cla: yes, lgtm, merge ready, target: patch

#18831 fix(bottom-sheet): allow result to be passed when dismissing through service
  src/material/bottom-sheet/bottom-sheet.spec.ts
  src/material/bottom-sheet/bottom-sheet.ts
  tools/public_api_guard/material/bottom-sheet.d.ts
Labels: P3, cla: yes, lgtm, merge ready, target: patch

#18821 perf(drag-drop): avoid unnecessary change detection on pointer down events
  src/cdk/drag-drop/drag-ref.ts
Labels: P3, cla: yes, lgtm, merge ready, target: patch

#18822 fix(google-maps): map circle error during server-side rendering
  src/google-maps/map-circle/map-circle.ts
  src/universal-app/kitchen-sink/kitchen-sink.html
Labels: P3, cla: yes, lgtm, merge ready, target: patch

#18829 fix(drag-drop): handle custom preview/placeholder with multiple root nodes
  src/cdk/drag-drop/directives/drag.spec.ts
  src/cdk/drag-drop/drag-ref.ts
Labels: P3, cla: yes, lgtm, merge ready, target: patch
