Repository angular/components, pull requests merged in 2020-01, with the labels that each got.

#18114 build: use `online: false` for browsersync
  tools/dev-server/dev-server.ts
Labels: cla: yes, pr: lgtm, pr: merge ready, pr: merge safe, target: patch

#18092 build: enforce golden files and lint entry-point configuration
  .circleci/config.yml
  BUILD.bazel
  package.json
  scripts/check-entry-point-setup.js
  src/material-experimental/config.bzl
  src/material-experimental/mdc-snackbar/BUILD.bazel
  src/material/config.bzl
  tools/public_api_guard/BUILD.bazel
  tools/public_api_guard/material/bottom-sheet/testing.d.ts
  tools/public_api_guard/material/form-field/testing/control.d.ts
  tools/public_api_guard/material/grid-list/testing.d.ts
Labels: P3, cla: yes, pr: lgtm, pr: merge ready, pr: merge safe, target: patch

#18115 docs(cdk/testing): correct test harnesses typo
  src/cdk/testing/test-harnesses.md
Labels: cla: yes, pr: lgtm, pr: merge ready, pr: merge safe, target: patch

#18089 build: inherited members not showing up in API docs
  tools/dgeni/processors/merge-inherited-properties.ts
Labels: P2, cla: yes, pr: lgtm, pr: merge ready, pr: merge safe, target: patch

#18086 build: fix missing example in generated example-module file
  tools/example-module/bazel-bin.ts
  tools/example-module/example-module.template
  tools/example-module/generate-example-module.ts
Labels: P3, cla: yes, pr: lgtm, pr: merge ready, pr: merge safe, target: patch

#18078 chore: bump year
  LICENSE
Labels: cla: yes, pr: lgtm, pr: merge ready, pr: merge safe, target: patch

#18067 docs: fix typos in CDK and Material tree examples
  src/components-examples/cdk/tree/cdk-tree-flat/cdk-tree-flat-example.ts
  src/components-examples/cdk/tree/cdk-tree-nested/cdk-tree-nested-example.ts
  src/components-examples/example-data.ts
  src/components-examples/material/tree/tree-flat-overview/tree-flat-overview-example.ts
  src/components-examples/material/tree/tree-nested-overview/tree-nested-overview-example.ts
  src/material/tree/tree.spec.ts
Labels: P4, cla: yes, docs, pr: lgtm, pr: merge ready, pr: merge safe, target: major

#18064 build: update to rules_nodejs 1.0.0
  WORKSPACE
  package.json
  src/cdk/BUILD.bazel
  src/cdk/schematics/BUILD.bazel
  src/material/BUILD.bazel
  src/material/schematics/BUILD.bazel
  src/universal-app/BUILD.bazel
  tools/bazel/BUILD.bazel
  tools/bazel/angular_bazel_rules_nodejs_1.0.0.patch
  tools/bazel/expand_template.bzl
  tools/bazel/postinstall-patches.js
  tools/bazel/ts_api_guardian_rules_nodejs_1.0.0.patch
  tools/defaults.bzl
  tools/dev-server/BUILD.bazel
  tools/dgeni/BUILD.bazel
  tools/example-module/BUILD.bazel
  tools/highlight-files/BUILD.bazel
  tools/markdown-to-html/BUILD.bazel
  tools/package-docs-content/BUILD.bazel
  yarn.lock
Labels: cla: yes, pr: lgtm, pr: merge ready, pr: merge safe, target: patch

#18028 Fix part of #13195 (Size not enforced)
  guides/creating-a-custom-form-field-control.md
Labels: cla: yes, docs, pr: lgtm, pr: merge ready, pr: merge safe, target: patch

#18027 fix(google-maps): incorrect event name
  src/google-maps/google-map/google-map.ts
Labels: P2, cla: yes, pr: lgtm, pr: merge ready, pr: merge safe, target: patch

#18118 build: try/catch the @angular/bazel rules_nodejs 1.0.0 patch
  tools/bazel/postinstall-patches.js
Labels: cla: yes, pr: lgtm, pr: merge ready, pr: merge safe, target: patch

#18097 build: remove incorrect sass binary for mdc-tabs theme
  src/material-experimental/mdc-tabs/BUILD.bazel
Labels: cla: yes, pr: lgtm, pr: merge ready, pr: merge safe, target: patch

#18077 build: remove unused gulp test watch code
  tools/gulp/packages.ts
  tools/gulp/tasks/unit-test.ts
Labels: cla: yes, pr: lgtm, pr: merge ready, pr: merge safe, target: patch

#18068 fix(material-experimental/mdc-tabs): incorrect tab text color in dark theme
  src/material-experimental/mdc-tabs/_mdc-tabs.scss
Labels: P3, cla: yes, pr: lgtm, pr: merge ready, pr: merge safe, target: patch

#18062 fix(form-field): error when focusing outline form field angular elements on IE/Edge
  src/material/form-field/form-field.ts
Labels: P3, cla: yes, pr: lgtm, pr: merge ready, target: patch

#18060 refactor: fix various typescript 3.7 compilation errors
  src/cdk/overlay/position/flexible-connected-position-strategy.ts
  src/cdk/overlay/scroll/reposition-scroll-strategy.spec.ts
  src/material/core/ripple/ripple.spec.ts
Labels: P2, cla: yes, pr: lgtm, pr: merge ready, pr: merge safe, target: patch

#17903 feat(material-experimental): initial prototype of mdc-form-field
  .github/CODEOWNERS
  rollup-globals.bzl
  src/dev-app/BUILD.bazel
  src/dev-app/dev-app/dev-app-layout.ts
  src/dev-app/dev-app/routes.ts
  src/dev-app/mdc-input/BUILD.bazel
  src/dev-app/mdc-input/mdc-input-demo-module.ts
  src/dev-app/mdc-input/mdc-input-demo.html
  src/dev-app/mdc-input/mdc-input-demo.scss
  src/dev-app/mdc-input/mdc-input-demo.ts
  src/dev-app/system-config-tmpl.js
  src/material-experimental/config.bzl
  src/material-experimental/mdc-form-field/BUILD.bazel
  src/material-experimental/mdc-form-field/README.md
  src/material-experimental/mdc-form-field/_form-field-bottom-line.scss
  src/material-experimental/mdc-form-field/_form-field-sizing.scss
  src/material-experimental/mdc-form-field/_form-field-subscript.scss
  src/material-experimental/mdc-form-field/_mdc-form-field.scss
  src/material-experimental/mdc-form-field/_mdc-text-field-structure-overrides.scss
  src/material-experimental/mdc-form-field/_mdc-text-field-textarea-overrides.scss
  src/material-experimental/mdc-form-field/directives/error.ts
  src/material-experimental/mdc-form-field/directives/floating-label.ts
  src/material-experimental/mdc-form-field/directives/hint.ts
  src/material-experimental/mdc-form-field/directives/label.ts
  src/material-experimental/mdc-form-field/directives/line-ripple.ts
  src/material-experimental/mdc-form-field/directives/notched-outline.html
  src/material-experimental/mdc-form-field/directives/notched-outline.ts
  src/material-experimental/mdc-form-field/directives/prefix.ts
  src/material-experimental/mdc-form-field/directives/suffix.ts
  src/material-experimental/mdc-form-field/form-field.e2e.spec.ts
  src/material-experimental/mdc-form-field/form-field.html
  src/material-experimental/mdc-form-field/form-field.scss
  src/material-experimental/mdc-form-field/form-field.ts
  src/material-experimental/mdc-form-field/index.ts
  src/material-experimental/mdc-form-field/module.ts
  src/material-experimental/mdc-form-field/public-api.ts
  src/material-experimental/mdc-input/BUILD.bazel
  src/material-experimental/mdc-input/README.md
  src/material-experimental/mdc-input/_mdc-input.scss
  src/material-experimental/mdc-input/index.ts
  src/material-experimental/mdc-input/input.e2e.spec.ts
  src/material-experimental/mdc-input/input.spec.ts
  src/material-experimental/mdc-input/input.ts
  src/material-experimental/mdc-input/module.ts
  src/material-experimental/mdc-input/public-api.ts
  src/material-experimental/mdc-theming/BUILD.bazel
  src/material-experimental/mdc-theming/_all-theme.scss
  src/material-experimental/mdc-typography/BUILD.bazel
  src/material-experimental/mdc-typography/_all-typography.scss
  src/material-experimental/mdc_require_config.js
  src/material/input/input-module.ts
  src/material/input/input.ts
  test/karma-system-config.js
  tools/public_api_guard/material/input.d.ts
Labels: cla: yes, new component, pr: lgtm, pr: merge ready, target: patch

#18124 fix(material-experimental/mdc-slide-toggle): update adapter to match new interface
  package.json
  src/material-experimental/mdc-slide-toggle/slide-toggle.ts
  yarn.lock
Labels: P2, cla: yes, pr: lgtm, pr: merge ready, pr: merge safe, target: patch

#18128 docs: update readme for Q1 2020
  README.md
Labels: cla: yes, pr: lgtm, pr: merge ready, pr: merge safe, target: patch

#18133 refactor: default to agnostic ts type to schematics one
  src/cdk/schematics/utils/version-agnostic-typescript.ts
Labels: P1, cla: yes, pr: lgtm, pr: merge ready, pr: merge safe, target: major

#18109 refactor: remove abstract directives injection workaround
  src/material-experimental/mdc-button/button-base.ts
Labels: P3, cla: yes, pr: lgtm, pr: merge ready, target: patch

#18106 build: focus trap demo not working on IE/Edge
  src/dev-app/focus-trap/BUILD.bazel
  src/dev-app/focus-trap/focus-trap-demo.html
  src/dev-app/focus-trap/focus-trap-demo.ts
Labels: P3, cla: yes, pr: lgtm, pr: merge ready, pr: merge safe, target: patch

#18104 fix(slide-toggle): fix and simplify high contrast styles
  src/material/slide-toggle/slide-toggle.scss
Labels: P3, a11y, cla: yes, pr: lgtm, pr: merge ready, target: patch

#18095 fix(chips): avoid accidental form submits when pressing remove button
  src/material-experimental/mdc-chips/chip-icons.ts
  src/material-experimental/mdc-chips/chip-remove.spec.ts
  src/material/chips/chip-remove.spec.ts
  src/material/chips/chip.ts
Labels: P3, cla: yes, pr: lgtm, pr: merge ready, target: patch

#18084 fix(material-experimental/mdc-chips): prevent default space and enter
  src/material-experimental/mdc-chips/chip-remove.spec.ts
  src/material-experimental/mdc-chips/chip.ts
Labels: P3, cla: yes, pr: lgtm, pr: merge ready, target: patch

#18074 fix(material-experimental/mdc-chips): error on IE and Edge due to unsupported classList
  src/material-experimental/mdc-chips/chip-set.ts
  src/material-experimental/mdc-chips/chip.ts
Labels: P3, cla: yes, pr: lgtm, pr: merge ready, target: patch

#18094 fix(datepicker): re-render calendar when locale changes
  src/material/datepicker/calendar.spec.ts
  src/material/datepicker/month-view.ts
  src/material/datepicker/multi-year-view.ts
  src/material/datepicker/year-view.ts
  tools/public_api_guard/material/datepicker.d.ts
Labels: P3, cla: yes, pr: lgtm, pr: merge ready, target: patch

#18083 fix(material-experimental/mdc-chips): removed chip still focusable
  src/material-experimental/mdc-chips/chip.spec.ts
  src/material-experimental/mdc-chips/chip.ts
Labels: P4, cla: yes, pr: lgtm, pr: merge ready, target: patch

#18134 chore: bump version to 9.0.0-rc.7 w/ changelog
  CHANGELOG.md
  package.json
Labels: cla: yes, pr: lgtm, pr: merge ready, pr: merge safe

#18137 build: bump Angular dependencies to latest versions
  package.json
  tools/public_api_guard/cdk/a11y.d.ts
  tools/public_api_guard/cdk/accordion.d.ts
  tools/public_api_guard/cdk/bidi.d.ts
  tools/public_api_guard/cdk/clipboard.d.ts
  tools/public_api_guard/cdk/drag-drop.d.ts
  tools/public_api_guard/cdk/observers.d.ts
  tools/public_api_guard/cdk/overlay.d.ts
  tools/public_api_guard/cdk/portal.d.ts
  tools/public_api_guard/cdk/scrolling.d.ts
  tools/public_api_guard/cdk/stepper.d.ts
  tools/public_api_guard/cdk/table.d.ts
  tools/public_api_guard/cdk/text-field.d.ts
  tools/public_api_guard/cdk/tree.d.ts
  tools/public_api_guard/google-maps/google-maps.d.ts
  tools/public_api_guard/material/autocomplete.d.ts
  tools/public_api_guard/material/badge.d.ts
  tools/public_api_guard/material/button-toggle.d.ts
  tools/public_api_guard/material/button.d.ts
  tools/public_api_guard/material/card.d.ts
  tools/public_api_guard/material/checkbox.d.ts
  tools/public_api_guard/material/chips.d.ts
  tools/public_api_guard/material/core.d.ts
  tools/public_api_guard/material/datepicker.d.ts
  tools/public_api_guard/material/dialog.d.ts
  tools/public_api_guard/material/divider.d.ts
  tools/public_api_guard/material/expansion.d.ts
  tools/public_api_guard/material/form-field.d.ts
  tools/public_api_guard/material/grid-list.d.ts
  tools/public_api_guard/material/icon.d.ts
  tools/public_api_guard/material/input.d.ts
  tools/public_api_guard/material/list.d.ts
  tools/public_api_guard/material/menu.d.ts
  tools/public_api_guard/material/paginator.d.ts
  tools/public_api_guard/material/progress-bar.d.ts
  tools/public_api_guard/material/progress-spinner.d.ts
  tools/public_api_guard/material/radio.d.ts
  tools/public_api_guard/material/select.d.ts
  tools/public_api_guard/material/sidenav.d.ts
  tools/public_api_guard/material/slide-toggle.d.ts
  tools/public_api_guard/material/slider.d.ts
  tools/public_api_guard/material/sort.d.ts
  tools/public_api_guard/material/stepper.d.ts
  tools/public_api_guard/material/table.d.ts
  tools/public_api_guard/material/tabs.d.ts
  tools/public_api_guard/material/toolbar.d.ts
  tools/public_api_guard/material/tooltip.d.ts
  tools/public_api_guard/material/tree.d.ts
  tools/public_api_guard/youtube-player/youtube-player.d.ts
  yarn.lock
Labels: P2, cla: yes, pr: lgtm, pr: merge ready, target: major

#18116 build: add tsickle as explicit dependency
  package.json
Labels: cla: yes, pr: lgtm, pr: merge ready, pr: merge safe, target: patch

#18110 chore: remove outdated todo for docs-content build
  .circleci/config.yml
Labels: cla: yes, pr: lgtm, pr: merge ready, pr: merge safe, target: patch

#18105 fix(google-maps): support numbers for width/height of the map
  src/google-maps/google-map/google-map.spec.ts
  src/google-maps/google-map/google-map.ts
  tools/public_api_guard/google-maps/google-maps.d.ts
Labels: P3, cla: yes, pr: lgtm, pr: merge ready, pr: merge safe, target: patch

#18088 build: do not merge interface members with class API members
  tools/dgeni/common/class-inheritance.ts
  tools/dgeni/docs-package.ts
  tools/dgeni/processors/categorizer.ts
  tools/dgeni/processors/docs-private-filter.ts
  tools/dgeni/processors/merge-inherited-properties.ts
Labels: cla: yes, pr: lgtm, pr: merge ready, pr: merge safe, target: patch

#18019 feat(material/chip): Add focus indicator
  src/material/chips/chip.ts
  src/material/chips/chips.scss
  src/material/core/focus-indicator/_focus-indicator.scss
  tools/public_api_guard/material/chips.d.ts
Labels: cla: yes, pr: lgtm, pr: merge safe

#18055 docs(menu): fix inaccurate descriptions
  src/material-experimental/mdc-menu/menu-item.ts
  src/material/menu/menu-item.ts
  src/material/menu/menu-trigger.ts
Labels: P4, cla: yes, docs, pr: lgtm, pr: merge ready, pr: merge safe, target: patch

#18076 fix(material): ng-add should always install matching CDK version
  src/cdk/schematics/ng-add/index.spec.ts
  src/cdk/schematics/ng-add/index.ts
  src/material/schematics/ng-add/index.spec.ts
  src/material/schematics/ng-add/index.ts
  src/material/schematics/ng-add/version-names.ts
Labels: P3, cla: yes, pr: lgtm, pr: merge ready, pr: merge safe, target: patch

#18102 fix(datepicker): memory leak in popup mode
  src/material/datepicker/datepicker.ts
  tools/public_api_guard/material/datepicker.d.ts
Labels: P2, cla: yes, pr: lgtm, pr: merge ready, target: patch

#18017 refactor(material): deprecate MAT_LABEL_GLOBAL_OPTIONS in favor of form-field global defaults
  src/material/core/label/label-options.ts
  src/material/form-field/form-field.ts
  src/material/input/input.spec.ts
  tools/public_api_guard/material/form-field.d.ts
Labels: P3, cla: yes, pr: lgtm, pr: merge ready, target: patch

#17543 feat(select): add injection token for configuring default options
  src/material/select/select.spec.ts
  src/material/select/select.ts
  tools/public_api_guard/material/select.d.ts
Labels: P3, caretaker note, cla: yes, pr: lgtm, pr: merge ready, target: minor

#18153 docs(cdk): correct code sample for test harnesses
  src/cdk/testing/test-harnesses.md
Labels: cla: yes, pr: lgtm, pr: merge ready, pr: merge safe, target: patch

#18155 refactor: vendor used typescript ast utils from @schematics/angular
  src/cdk/schematics/index.ts
  src/cdk/schematics/utils/ast.ts
  src/cdk/schematics/utils/build-component.ts
  src/cdk/schematics/utils/index.ts
  src/cdk/schematics/utils/vendored-ast-utils/index.ts
  src/cdk/schematics/utils/version-agnostic-typescript.ts
  src/material/schematics/ng-add/setup-project.ts
  src/material/schematics/ng-update/upgrade-rules/hammer-gestures-v9/hammer-gestures-rule.ts
  tslint.json
Labels: P2, cla: yes, pr: lgtm, pr: merge ready, pr: merge safe, target: patch

#18150 feat(material/*) Focus indicator unit tests
  src/material/button-toggle/button-toggle.spec.ts
  src/material/button/button.spec.ts
  src/material/checkbox/checkbox.spec.ts
  src/material/chips/chip.spec.ts
  src/material/core/option/option.spec.ts
  src/material/datepicker/calendar-body.spec.ts
  src/material/expansion/expansion.spec.ts
  src/material/list/list.spec.ts
  src/material/list/selection-list.spec.ts
  src/material/menu/menu.spec.ts
  src/material/radio/radio.spec.ts
  src/material/slide-toggle/slide-toggle.spec.ts
  src/material/slider/slider.spec.ts
  src/material/sort/sort.spec.ts
  src/material/stepper/stepper.spec.ts
  src/material/tabs/tab-group.spec.ts
  src/material/tabs/tab-nav-bar/tab-nav-bar.spec.ts
  src/material/tree/tree.scss
Labels: cla: yes, pr: lgtm, pr: merge ready

#18141 refactor: fix typescript 3.7 compilation errors.
  src/components-examples/material/table/table-multiple-header-footer/table-multiple-header-footer-example.ts
  src/dev-app/mdc-input/mdc-input-demo.ts
  src/material-experimental/mdc-form-field/form-field.ts
Labels: P1, caretaker note, cla: yes, pr: lgtm, pr: merge ready, target: major

#18151 feat(material/icon): New NoopIconModule for silencing unit test errors
  src/material/config.bzl
  src/material/icon/testing/BUILD.bazel
  src/material/icon/testing/fake-icon-registry.ts
  src/material/icon/testing/index.ts
  src/material/icon/testing/public-api.ts
  tools/public_api_guard/material/icon/testing.d.ts
Labels: G, P3, cla: yes, feature, pr: lgtm, pr: merge ready, pr: merge safe, target: minor

#18059 fix(google-maps): sub-components throwing during server-side rendering
  src/google-maps/google-map/google-map.ts
  src/google-maps/map-info-window/map-info-window.ts
  src/google-maps/map-marker/map-marker.ts
  src/google-maps/map-polyline/map-polyline.ts
  src/universal-app/kitchen-sink/kitchen-sink.html
  tools/public_api_guard/google-maps/google-maps.d.ts
Labels: P3, cla: yes, pr: lgtm, pr: merge ready, pr: merge safe, target: patch

#18180 fix(material-experimental/mdc-input): input should not inherit parent classnames
  src/material-experimental/mdc-input/input.ts
  src/material/input/input.ts
Labels: cla: yes, pr: lgtm, pr: merge ready, target: patch

#18161 fix(material-experimental/mdc-form-field): fix baseline and handle custom controls better
  src/components-examples/material-experimental/mdc-form-field/BUILD.bazel
  src/components-examples/material-experimental/mdc-form-field/index.ts
  src/components-examples/material-experimental/mdc-form-field/mdc-form-field-custom-control/example-tel-input-example.css
  src/components-examples/material-experimental/mdc-form-field/mdc-form-field-custom-control/example-tel-input-example.html
  src/components-examples/material-experimental/mdc-form-field/mdc-form-field-custom-control/form-field-custom-control-example.css
  src/components-examples/material-experimental/mdc-form-field/mdc-form-field-custom-control/form-field-custom-control-example.html
  src/components-examples/material-experimental/mdc-form-field/mdc-form-field-custom-control/form-field-custom-control-example.ts
  src/dev-app/mdc-input/BUILD.bazel
  src/dev-app/mdc-input/mdc-input-demo-module.ts
  src/dev-app/mdc-input/mdc-input-demo.html
  src/material-experimental/mdc-form-field/_form-field-sizing.scss
  src/material-experimental/mdc-form-field/_mdc-text-field-structure-overrides.scss
  src/material-experimental/mdc-form-field/_mdc-text-field-textarea-overrides.scss
  src/material-experimental/mdc-form-field/form-field.scss
Labels: cla: yes, pr: lgtm, pr: merge ready, pr: merge safe, target: patch

#18158 build: do not build unnecessary build targets in bazel test jobs
  .circleci/config.yml
Labels: cla: yes, pr: lgtm, pr: merge ready, pr: merge safe, target: patch

#18156 build: make cross entrypoint rule an AbstractRule
  tools/tslint-rules/noCrossEntryPointRelativeImportsRule.ts
Labels: P3, cla: yes, pr: lgtm, pr: merge ready, pr: merge safe, target: patch

#18144 fix(material/form-field): undeprecated legacy and standard appearances
  src/material/form-field/form-field.ts
Labels: P1, caretaker note, cla: yes, pr: lgtm, pr: merge ready, pr: merge safe, target: patch

#17936 feat(google-maps): Add MapPolygon component
  src/dev-app/google-map/google-map-demo.html
  src/dev-app/google-map/google-map-demo.ts
  src/google-maps/google-maps-module.ts
  src/google-maps/map-polygon/map-polygon.spec.ts
  src/google-maps/map-polygon/map-polygon.ts
  src/google-maps/public-api.ts
  src/google-maps/testing/fake-google-map-utils.ts
  tools/public_api_guard/google-maps/google-maps.d.ts
Labels: cla: yes, pr: lgtm, pr: merge ready, pr: merge safe, target: minor

#18126 feat(list): Add single select mode.
  src/components-examples/material/list/index.ts
  src/components-examples/material/list/list-single-selection/list-single-selection-example.css
  src/components-examples/material/list/list-single-selection/list-single-selection-example.html
  src/components-examples/material/list/list-single-selection/list-single-selection-example.ts
  src/dev-app/list/list-demo.html
  src/dev-app/list/list-demo.ts
  src/material/list/_list-theme.scss
  src/material/list/list-option.html
  src/material/list/selection-list.spec.ts
  src/material/list/selection-list.ts
  tools/public_api_guard/material/list.d.ts
Labels: cla: yes, pr: lgtm, pr: merge ready, target: minor

#18025 build: remove hard-coded karma systemjs config
  .circleci/config.yml
  packages.bzl
  src/dev-app/BUILD.bazel
  src/dev-app/index.html
  src/dev-app/system-config-tmpl.js
  test/BUILD.bazel
  test/karma.conf.js
  tools/BUILD.bazel
  tools/create-system-config.bzl
  tools/gulp/tasks/unit-test.ts
  tools/system-config-tmpl.js
  tools/system-rxjs-operators.js
Labels: cla: yes, pr: lgtm, pr: merge ready, pr: merge safe, target: patch

#18190 build: print error if prerender test fails
  src/universal-app/prerender.ts
Labels: cla: yes, pr: lgtm, pr: merge ready, pr: merge safe, target: patch

#18186 build: bump to latest Angular version
  package.json
  tools/public_api_guard/cdk/a11y.d.ts
  tools/public_api_guard/cdk/accordion.d.ts
  tools/public_api_guard/cdk/bidi.d.ts
  tools/public_api_guard/cdk/collections.d.ts
  tools/public_api_guard/cdk/drag-drop.d.ts
  tools/public_api_guard/cdk/observers.d.ts
  tools/public_api_guard/cdk/overlay.d.ts
  tools/public_api_guard/cdk/portal.d.ts
  tools/public_api_guard/cdk/scrolling.d.ts
  tools/public_api_guard/cdk/stepper.d.ts
  tools/public_api_guard/cdk/table.d.ts
  tools/public_api_guard/cdk/text-field.d.ts
  tools/public_api_guard/cdk/tree.d.ts
  tools/public_api_guard/google-maps/google-maps.d.ts
  tools/public_api_guard/material/autocomplete.d.ts
  tools/public_api_guard/material/badge.d.ts
  tools/public_api_guard/material/bottom-sheet.d.ts
  tools/public_api_guard/material/button-toggle.d.ts
  tools/public_api_guard/material/checkbox.d.ts
  tools/public_api_guard/material/chips.d.ts
  tools/public_api_guard/material/core.d.ts
  tools/public_api_guard/material/datepicker.d.ts
  tools/public_api_guard/material/dialog.d.ts
  tools/public_api_guard/material/divider.d.ts
  tools/public_api_guard/material/expansion.d.ts
  tools/public_api_guard/material/form-field.d.ts
  tools/public_api_guard/material/grid-list.d.ts
  tools/public_api_guard/material/icon.d.ts
  tools/public_api_guard/material/input.d.ts
  tools/public_api_guard/material/list.d.ts
  tools/public_api_guard/material/menu.d.ts
  tools/public_api_guard/material/paginator.d.ts
  tools/public_api_guard/material/progress-bar.d.ts
  tools/public_api_guard/material/progress-spinner.d.ts
  tools/public_api_guard/material/radio.d.ts
  tools/public_api_guard/material/select.d.ts
  tools/public_api_guard/material/sidenav.d.ts
  tools/public_api_guard/material/slide-toggle.d.ts
  tools/public_api_guard/material/slider.d.ts
  tools/public_api_guard/material/snack-bar.d.ts
  tools/public_api_guard/material/sort.d.ts
  tools/public_api_guard/material/table.d.ts
  tools/public_api_guard/material/tabs.d.ts
  tools/public_api_guard/material/tooltip.d.ts
  tools/public_api_guard/material/tree.d.ts
  tools/public_api_guard/youtube-player/youtube-player.d.ts
  yarn.lock
Labels: P2, cla: yes, pr: lgtm, pr: merge ready, pr: merge safe, target: major

#18193 docs(material/table): use a hover color that is consistent with Material Design spec
  src/components-examples/material/table/table-expandable-rows/table-expandable-rows-example.css
Labels: cla: yes, docs, material spec, pr: merge safe

#18034 fix(google-maps): internal events run inside NgZone
  src/google-maps/google-map/google-map.ts
  src/google-maps/map-event-manager.ts
  src/google-maps/map-info-window/map-info-window.ts
  src/google-maps/map-marker/map-marker.ts
  src/google-maps/map-polyline/map-polyline.ts
  tools/public_api_guard/google-maps/google-maps.d.ts
Labels: P2, caretaker note, cla: yes, pr: lgtm, pr: merge ready, pr: merge safe, target: patch

#18196 fix(material/input): apply static class binding to host
  src/material/input/input.ts
Labels: cla: yes, pr: lgtm, pr: merge ready, pr: merge safe, target: patch

#17977 build: enable strict attribute type checking
  src/a11y-demo/dialog/dialog-neptune-a11y.html
  src/a11y-demo/progress-spinner/progress-spinner-a11y.html
  src/universal-app/kitchen-sink-mdc/kitchen-sink-mdc.html
  src/universal-app/kitchen-sink/kitchen-sink.html
  tools/bazel/postinstall-patches.js
Labels: cla: yes, pr: lgtm, pr: merge ready, pr: merge safe, target: patch

#18199 chore: bump version to 9.0.0-rc.8 w/ changelog
  CHANGELOG.md
  package.json
Labels: cla: yes, pr: lgtm, pr: merge ready, pr: merge safe, target: major

#18200 chore: bump version to 9.0.0-rc.8 w/ changelog (#18199)
  CHANGELOG.md
  package.json
Labels: cla: yes, pr: lgtm, pr: merge ready, pr: merge safe, target: patch

#18157 build: remove custom rxjs imports rule in favor of import-banlist rule
  tools/tslint-rules/rxjsImportsRule.ts
  tslint.json
Labels: cla: yes, pr: lgtm, pr: merge ready, pr: merge safe, target: patch

#18207 chore: move mdc-chips change to material-experimental in 9.0.0-rc.7
  CHANGELOG.md
Labels: cla: yes, pr: merge safe

#18159 feat(datepicker): set up input for date range picker
  src/dev-app/datepicker/datepicker-demo.html
  src/material/datepicker/BUILD.bazel
  src/material/datepicker/date-range-input-parts.ts
  src/material/datepicker/date-range-input.html
  src/material/datepicker/date-range-input.scss
  src/material/datepicker/date-range-input.ts
  src/material/datepicker/datepicker-module.ts
  src/material/datepicker/public-api.ts
  tools/public_api_guard/material/datepicker.d.ts
Labels: P3, cla: yes, pr: lgtm, pr: merge ready, pr: merge safe, target: development-branch

#18070 docs(icon): add note about HttpClientModule requirement
  src/material/icon/icon.md
Labels: P4, cla: yes, docs, pr: lgtm, pr: merge ready, pr: merge safe, target: patch

#18213 refactor: move common date input logic into base class
  src/dev-app/datepicker/datepicker-demo.html
  src/dev-app/datepicker/datepicker-demo.scss
  src/dev-app/datepicker/datepicker-demo.ts
  src/material/datepicker/date-range-input-parts.ts
  src/material/datepicker/date-range-input.ts
  src/material/datepicker/datepicker-input-base.ts
  src/material/datepicker/datepicker-input.ts
  src/material/datepicker/public-api.ts
  tools/public_api_guard/material/datepicker.d.ts
Labels: P3, cla: yes, pr: lgtm, pr: merge ready, pr: merge safe, target: development-branch

#18242 build: update rules_sass version to latest
  WORKSPACE
Labels: cla: yes, pr: lgtm, pr: merge ready, pr: merge safe, target: patch

#18238 build: allow force overriding of publish branch
  tools/release/base-release-task.ts
  tools/release/publish-release.ts
  tools/release/stage-release.ts
Labels: cla: yes, pr: lgtm, pr: merge ready, pr: merge safe, target: patch

#18216 docs(material/select): new examples - basic reactive form and initial value w/o form
  src/components-examples/material/select/index.ts
  src/components-examples/material/select/select-form/select-form-example.ts
  src/components-examples/material/select/select-hint-error/select-hint-error-example.ts
  src/components-examples/material/select/select-initial-value/select-initial-value-example.css
  src/components-examples/material/select/select-initial-value/select-initial-value-example.html
  src/components-examples/material/select/select-initial-value/select-initial-value-example.ts
  src/components-examples/material/select/select-optgroup/select-optgroup-example.ts
  src/components-examples/material/select/select-overview/select-overview-example.ts
  src/components-examples/material/select/select-reactive-form/select-reactive-form-example.css
  src/components-examples/material/select/select-reactive-form/select-reactive-form-example.html
  src/components-examples/material/select/select-reactive-form/select-reactive-form-example.ts
Labels: cla: yes, docs, pr: lgtm, pr: merge ready, pr: merge safe, target: patch

#18225 build: remove unused karma system configuration file
  test/karma-system-config.js
Labels: cla: yes, pr: lgtm, pr: merge ready, pr: merge safe, target: patch

#18223 build: coercion types rule should check type assignability
  tools/tslint-rules/coercionTypesRule.ts
Labels: cla: yes, pr: lgtm, pr: merge ready, pr: merge safe, target: patch

#18237 build: fix local browser testing target for macOS and linux
  test/bazel-karma-local-config.js
  tools/defaults.bzl
Labels: cla: yes, pr: lgtm, pr: merge ready, pr: merge safe, target: patch

#18232 build: expand import spacing lint rule to exports
  tools/tslint-rules/noImportExportSpacingRule.ts
  tools/tslint-rules/noImportSpacingRule.ts
  tslint.json
Labels: P3, cla: yes, pr: lgtm, pr: merge ready, pr: merge safe, target: patch

#18214 fix(youtube-player): not picking up static startSeconds and endSeconds
  src/youtube-player/youtube-player.spec.ts
  src/youtube-player/youtube-player.ts
Labels: P2, cla: yes, pr: lgtm, pr: merge ready, pr: merge safe, target: patch

#18191 fix(material-experimental/mdc-form-field): fix server side rendering failures
  src/material-experimental/mdc-form-field/BUILD.bazel
  src/material-experimental/mdc-form-field/directives/notched-outline.ts
  src/universal-app/kitchen-sink-mdc/kitchen-sink-mdc.html
  src/universal-app/kitchen-sink-mdc/kitchen-sink-mdc.ts
Labels: cla: yes, pr: lgtm, pr: merge ready, pr: merge safe, target: patch

#18222 docs(form-field): examples should use fill appearance by default
  src/components-examples/material/form-field/form-field-custom-control/form-field-custom-control-example.html
  src/components-examples/material/form-field/form-field-error/form-field-error-example.css
  src/components-examples/material/form-field/form-field-error/form-field-error-example.html
  src/components-examples/material/form-field/form-field-hint/form-field-hint-example.css
  src/components-examples/material/form-field/form-field-hint/form-field-hint-example.html
  src/components-examples/material/form-field/form-field-label/form-field-label-example.css
  src/components-examples/material/form-field/form-field-label/form-field-label-example.html
  src/components-examples/material/form-field/form-field-label/form-field-label-example.ts
  src/components-examples/material/form-field/form-field-overview/form-field-overview-example.css
  src/components-examples/material/form-field/form-field-overview/form-field-overview-example.html
  src/components-examples/material/form-field/form-field-prefix-suffix/form-field-prefix-suffix-example.css
  src/components-examples/material/form-field/form-field-prefix-suffix/form-field-prefix-suffix-example.html
  src/components-examples/material/form-field/form-field-theming/form-field-theming-example.css
  src/components-examples/material/form-field/form-field-theming/form-field-theming-example.html
  src/components-examples/material/form-field/form-field-theming/form-field-theming-example.ts
Labels: P3, cla: yes, docs, material spec, pr: lgtm, pr: merge ready, pr: merge safe, target: patch

#18226 build: render safari detection in platform demo and example
  src/components-examples/cdk/platform/cdk-platform-overview/cdk-platform-overview-example.html
  src/dev-app/platform/platform-demo.html
Labels: cla: yes, pr: lgtm, pr: merge ready, pr: merge safe, target: patch

#18194 feat(popover-edit): Adds support for select-like interactions.
  src/cdk-experimental/popover-edit/lens-directives.ts
  src/components-examples/material-experimental/popover-edit/BUILD.bazel
  src/components-examples/material-experimental/popover-edit/index.ts
  src/components-examples/material-experimental/popover-edit/popover-edit-mat-table/popover-edit-mat-table-example.css
  src/components-examples/material-experimental/popover-edit/popover-edit-mat-table/popover-edit-mat-table-example.html
  src/components-examples/material-experimental/popover-edit/popover-edit-mat-table/popover-edit-mat-table-example.ts
  src/dev-app/popover-edit/popover-edit-demo.ts
  src/material-experimental/popover-edit/_popover-edit.scss
  src/material-experimental/popover-edit/lens-directives.ts
Labels: cla: yes, pr: lgtm, pr: merge ready, pr: merge safe, target: minor

#18046 fix(youtube-player): memory leak if player is destroyed before it is done initializing
  src/youtube-player/youtube-player.ts
Labels: P3, cla: yes, pr: lgtm, pr: merge ready, pr: merge safe, target: patch

#18251 fix(material-experimental): mdc-theming and mdc-typography files not published
  src/material-experimental/BUILD.bazel
  src/material-experimental/config.bzl
  src/material-experimental/mdc-helpers/BUILD.bazel
  src/material-experimental/mdc-helpers/index.ts
  src/material-experimental/mdc-helpers/public-api.ts
  src/material-experimental/mdc-theming/BUILD.bazel
  src/material-experimental/mdc-typography/BUILD.bazel
Labels: P2, cla: yes, pr: lgtm, pr: merge ready, pr: merge safe, target: patch

#18248 build: patch rules_sass to properly report errors in worker mode
  WORKSPACE
  tools/bazel/sass_worker_async.patch
Labels: cla: yes, pr: lgtm, pr: merge ready, pr: merge safe, target: patch

#18244 refactor: remove unused common module imports
  src/cdk-experimental/dialog/BUILD.bazel
  src/cdk-experimental/dialog/dialog-module.ts
  src/cdk/a11y/BUILD.bazel
  src/cdk/a11y/a11y-module.ts
  src/cdk/clipboard/BUILD.bazel
  src/cdk/clipboard/clipboard-module.ts
  src/cdk/stepper/BUILD.bazel
  src/cdk/stepper/stepper-module.ts
  src/cdk/table/BUILD.bazel
  src/cdk/table/table-module.ts
  src/cdk/tree/BUILD.bazel
  src/cdk/tree/tree-module.ts
  src/material-experimental/mdc-autocomplete/module.ts
  src/material-experimental/mdc-button/module.ts
  src/material-experimental/mdc-input/module.ts
  src/material-experimental/mdc-select/module.ts
  src/material-experimental/mdc-sidenav/module.ts
  src/material-experimental/mdc-snackbar/BUILD.bazel
  src/material-experimental/mdc-snackbar/module.ts
  src/material-experimental/mdc-table/BUILD.bazel
  src/material-experimental/mdc-table/module.ts
  src/material-experimental/popover-edit/popover-edit-module.ts
  src/material/bottom-sheet/BUILD.bazel
  src/material/bottom-sheet/bottom-sheet-module.ts
  src/material/button/BUILD.bazel
  src/material/button/button-module.ts
  src/material/checkbox/BUILD.bazel
  src/material/checkbox/checkbox-module.ts
  src/material/dialog/BUILD.bazel
  src/material/dialog/dialog-module.ts
  src/material/divider/BUILD.bazel
  src/material/divider/divider-module.ts
  src/material/input/BUILD.bazel
  src/material/input/input-module.ts
  src/material/radio/BUILD.bazel
  src/material/radio/radio-module.ts
  src/material/table/BUILD.bazel
  src/material/table/table-module.ts
  src/material/tree/BUILD.bazel
  src/material/tree/tree-module.ts
  tools/public_api_guard/cdk/a11y.d.ts
  tools/public_api_guard/cdk/clipboard.d.ts
  tools/public_api_guard/cdk/stepper.d.ts
  tools/public_api_guard/cdk/table.d.ts
  tools/public_api_guard/cdk/tree.d.ts
  tools/public_api_guard/material/bottom-sheet.d.ts
  tools/public_api_guard/material/button.d.ts
  tools/public_api_guard/material/checkbox.d.ts
  tools/public_api_guard/material/dialog.d.ts
  tools/public_api_guard/material/divider.d.ts
  tools/public_api_guard/material/input.d.ts
  tools/public_api_guard/material/radio.d.ts
  tools/public_api_guard/material/table.d.ts
  tools/public_api_guard/material/tree.d.ts
Labels: P3, cla: yes, pr: lgtm, pr: merge ready, target: patch

#18243 build: disallow nested ternary expressions
  src/cdk/scrolling/scrollable.ts
  src/cdk/scrolling/virtual-for-of.ts
  src/cdk/scrolling/virtual-scroll-viewport.ts
  src/cdk/testing/component-harness.ts
  src/cdk/testing/testbed/fake-events/event-objects.ts
  src/components-examples/material/form-field/form-field-error/form-field-error-example.ts
  src/components-examples/material/slider/slider-configurable/slider-configurable-example.ts
  src/material-experimental/mdc-checkbox/checkbox.ts
  src/material/checkbox/checkbox.ts
  src/material/datepicker/calendar.ts
  src/material/select/select.ts
  src/material/slider/slider.ts
  tools/tslint-rules/noNestedTernaryRule.ts
  tslint.json
Labels: P3, cla: yes, pr: lgtm, pr: merge ready, target: patch

#18231 fix(datepicker): able to focus disabled datepicker toggle while disabled via click
  src/material/datepicker/datepicker-toggle.ts
  src/material/datepicker/datepicker.spec.ts
Labels: P3, cla: yes, pr: lgtm, pr: merge ready, target: patch

#18183 feat(cdk/testing): add `isFocused` method to `TestElement`
  src/cdk/testing/protractor/protractor-element.ts
  src/cdk/testing/test-element.ts
  src/cdk/testing/testbed/unit-test-element.ts
  src/cdk/testing/tests/BUILD.bazel
  src/cdk/testing/tests/protractor.e2e.spec.ts
  src/cdk/testing/tests/testbed.spec.ts
  tools/public_api_guard/cdk/testing.d.ts
  tools/public_api_guard/cdk/testing/protractor.d.ts
  tools/public_api_guard/cdk/testing/testbed.d.ts
Labels: cla: yes, pr: lgtm, pr: merge ready, target: minor

#18181 fix(expansion): unable to toggle disabled panel via methods
  src/material/expansion/expansion-panel-header.ts
  src/material/expansion/expansion-panel.ts
  src/material/expansion/expansion.spec.ts
  tools/public_api_guard/material/expansion.d.ts
Labels: P3, cla: yes, pr: lgtm, pr: merge ready, target: patch

#18175 feat(material-experimental/*): Add focus indicators to all MDC except mdc-chips.
  src/dev-app/theme.scss
  src/material-experimental/mdc-button/button-base.ts
  src/material-experimental/mdc-button/button.spec.ts
  src/material-experimental/mdc-button/fab.scss
  src/material-experimental/mdc-button/icon-button.scss
  src/material-experimental/mdc-checkbox/checkbox.html
  src/material-experimental/mdc-checkbox/checkbox.spec.ts
  src/material-experimental/mdc-helpers/_mdc-helpers.scss
  src/material-experimental/mdc-menu/menu-item.ts
  src/material-experimental/mdc-menu/menu.spec.ts
  src/material-experimental/mdc-slide-toggle/slide-toggle.html
  src/material-experimental/mdc-slide-toggle/slide-toggle.scss
  src/material-experimental/mdc-slide-toggle/slide-toggle.spec.ts
  src/material-experimental/mdc-slider/slider.spec.ts
  src/material-experimental/mdc-slider/slider.ts
  src/material-experimental/mdc-tabs/tab-group.html
  src/material-experimental/mdc-tabs/tab-group.spec.ts
  src/material-experimental/mdc-tabs/tab-nav-bar/tab-nav-bar.spec.ts
  src/material-experimental/mdc-tabs/tab-nav-bar/tab-nav-bar.ts
  src/material/button/button.spec.ts
  src/material/core/focus-indicator/_focus-indicator.scss
Labels: cla: yes, pr: lgtm, pr: merge ready, pr: merge safe, target: development-branch

#18173 fix(material-experimental): errors with latest MDC canary version
  package.json
  src/material-experimental/mdc-button/_mdc-button.scss
  src/material-experimental/mdc-button/button.scss
  src/material-experimental/mdc-button/fab.scss
  src/material-experimental/mdc-button/icon-button.scss
  src/material-experimental/mdc-card/_mdc-card.scss
  src/material-experimental/mdc-card/card.scss
  src/material-experimental/mdc-checkbox/_mdc-checkbox.scss
  src/material-experimental/mdc-checkbox/checkbox.scss
  src/material-experimental/mdc-chips/_mdc-chips.scss
  src/material-experimental/mdc-chips/chips.scss
  src/material-experimental/mdc-form-field/_form-field-sizing.scss
  src/material-experimental/mdc-form-field/_mdc-form-field.scss
  src/material-experimental/mdc-helpers/BUILD.bazel
  src/material-experimental/mdc-helpers/_mdc-helpers.scss
  src/material-experimental/mdc-menu/_mdc-menu.scss
  src/material-experimental/mdc-menu/menu.scss
  src/material-experimental/mdc-progress-bar/_mdc-progress-bar.scss
  src/material-experimental/mdc-progress-bar/progress-bar.scss
  src/material-experimental/mdc-radio/radio.scss
  src/material-experimental/mdc-slide-toggle/_mdc-slide-toggle.scss
  src/material-experimental/mdc-slide-toggle/slide-toggle.scss
  src/material-experimental/mdc-slider/_mdc-slider.scss
  src/material-experimental/mdc-slider/slider.scss
  src/material-experimental/mdc-table/_mdc-table.scss
  src/material-experimental/mdc-table/table.scss
  src/material-experimental/mdc-tabs/_mdc-tabs.scss
  src/material-experimental/mdc-tabs/_tabs-common.scss
  src/material-experimental/mdc-tabs/tab-group.scss
  src/material-experimental/mdc-tabs/tab-header.scss
  src/material-experimental/mdc-tabs/tab-nav-bar/tab-link.scss
  src/material-experimental/mdc-tabs/tab-nav-bar/tab-nav-bar.scss
  tools/package-tools/gulp/build-scss-pipeline.ts
  yarn.lock
Labels: P2, cla: yes, pr: lgtm, pr: merge ready, pr: merge safe, target: major

#18172 chore: enable strict apply, bind, and call
  src/bazel-tsconfig-build.json
  src/cdk/a11y/key-manager/list-key-manager.spec.ts
  src/cdk/drag-drop/directives/drag.spec.ts
  src/cdk/overlay/fullscreen-overlay-container.spec.ts
  src/cdk/portal/portal.spec.ts
  src/cdk/testing/private/e2e/actions.ts
  src/cdk/testing/testbed/fake-events/event-objects.ts
  src/cdk/testing/testbed/task-state-zone-interceptor.ts
  tsconfig.json
Labels: G, P2, cla: yes, pr: lgtm, pr: merge ready, target: patch

#18160 fix(tabs): better high contrast indication on supported browsers
  src/material/tabs/_tabs-common.scss
Labels: P3, a11y, cla: yes, pr: lgtm, pr: merge ready, target: patch

#18258 fix(popover-edit): Call markForCheck against row hover content
  src/cdk-experimental/popover-edit/table-directives.ts
  src/components-examples/material-experimental/popover-edit/popover-edit-tab-out-mat-table/popover-edit-tab-out-mat-table-example.ts
Labels: P3, cla: yes, pr: lgtm, pr: merge ready, pr: merge safe, target: patch

#18103 fix(drag-drop): prevent dragging selected text with the mouse
  src/cdk/drag-drop/directives/drag.spec.ts
  src/cdk/drag-drop/drag-ref.ts
Labels: P3, cla: yes, pr: lgtm, pr: merge ready, target: patch

#18260 build: fix sass async worker patch causing successful builds to fail
  tools/bazel/sass_worker_async.patch
Labels: P2, cla: yes, pr: lgtm, pr: merge ready, pr: merge safe, target: patch

#18082 feat(drag-drop): support scrolling parent elements apart from list and viewport
  src/cdk/drag-drop/directives/drag.spec.ts
  src/cdk/drag-drop/directives/drop-list.ts
  src/cdk/drag-drop/drop-list-ref.ts
  tools/public_api_guard/cdk/drag-drop.d.ts
Labels: P2, cla: yes, pr: lgtm, pr: merge ready, target: minor

#18066 fix(clipboard): leak if directive is destroyed while a copy is pending
  src/cdk/clipboard/copy-to-clipboard.spec.ts
  src/cdk/clipboard/copy-to-clipboard.ts
  tools/public_api_guard/cdk/clipboard.d.ts
Labels: P3, cla: yes, pr: lgtm, pr: merge ready, target: patch

#18098 fix(chips): set aria-required on chip input
  src/material/chips/chip-input.spec.ts
  src/material/chips/chip-input.ts
Labels: P3, cla: yes, pr: lgtm, pr: merge ready, target: patch

#18033 fix(tabs): don't start auto-scroll when right clicking on buttons
  src/material-experimental/mdc-tabs/tab-header.html
  src/material-experimental/mdc-tabs/tab-header.spec.ts
  src/material-experimental/mdc-tabs/tab-nav-bar/tab-nav-bar.html
  src/material/tabs/paginated-tab-header.ts
  src/material/tabs/tab-header.html
  src/material/tabs/tab-header.spec.ts
  src/material/tabs/tab-nav-bar/tab-nav-bar.html
Labels: P3, cla: yes, pr: lgtm, pr: merge ready, target: patch

#17911 refactor: remove inherited coercion acceptance members
  src/components-examples/cdk/stepper/cdk-custom-stepper-without-form/cdk-custom-stepper-without-form-example.ts
  src/material-experimental/mdc-button/button-base.ts
  src/material-experimental/mdc-button/button.ts
  src/material-experimental/mdc-button/fab.ts
  src/material-experimental/mdc-button/icon-button.ts
  src/material-experimental/mdc-chips/chip-listbox.ts
  src/material-experimental/mdc-chips/chip-option.ts
  src/material-experimental/mdc-chips/chip-row.ts
  src/material-experimental/mdc-input/input.ts
  src/material-experimental/mdc-menu/menu-item.ts
  src/material-experimental/mdc-menu/menu.ts
  src/material-experimental/mdc-table/cell.ts
  src/material-experimental/mdc-table/table.ts
  src/material-experimental/mdc-tabs/tab-group.ts
  src/material-experimental/mdc-tabs/tab-header.ts
  src/material-experimental/mdc-tabs/tab-label-wrapper.ts
  src/material-experimental/mdc-tabs/tab-nav-bar/tab-nav-bar.ts
  src/material-experimental/mdc-tabs/tab.ts
  src/material/button/button.ts
  src/material/expansion/accordion.ts
  src/material/input/autosize.ts
  src/material/menu/menu.ts
  src/material/progress-spinner/progress-spinner.ts
  src/material/sidenav/sidenav.ts
  src/material/stepper/stepper.ts
  src/material/table/cell.ts
  src/material/table/table.ts
  src/material/tabs/paginated-tab-header.ts
  src/material/tabs/tab-group.ts
  src/material/tabs/tab-header.ts
  src/material/tabs/tab-nav-bar/tab-nav-bar.ts
  src/material/tree/padding.ts
  src/material/tree/toggle.ts
  tools/public_api_guard/material/button.d.ts
  tools/public_api_guard/material/expansion.d.ts
  tools/public_api_guard/material/input.d.ts
  tools/public_api_guard/material/menu.d.ts
  tools/public_api_guard/material/progress-spinner.d.ts
  tools/public_api_guard/material/sidenav.d.ts
  tools/public_api_guard/material/stepper.d.ts
  tools/public_api_guard/material/table.d.ts
  tools/public_api_guard/material/tabs.d.ts
  tools/public_api_guard/material/tree.d.ts
  tools/tslint-rules/coercionTypesRule.ts
Labels: cla: yes, pr: lgtm, pr: merge ready, target: patch

#18053 refactor: use recommended approach for asserting observables
  src/cdk/collections/array-data-source.ts
  src/cdk/scrolling/virtual-for-of.ts
  src/cdk/table/table.ts
  src/cdk/tree/control/nested-tree-control.ts
  src/cdk/tree/nested-node.ts
  src/cdk/tree/tree.ts
Labels: P3, cla: yes, pr: lgtm, pr: merge ready, target: patch

#17842 fix(overlay): don't reset global overlay alignment when width is 100% and there's a maxWidth
  src/cdk/overlay/position/global-position-strategy.spec.ts
  src/cdk/overlay/position/global-position-strategy.ts
Labels: P2, cla: yes, pr: lgtm, pr: merge ready, target: patch

#18262 build: bump to latest MDC canary version
  package.json
  src/dev-app/BUILD.bazel
  src/material-experimental/mdc-helpers/BUILD.bazel
  tools/system-config-tmpl.js
  yarn.lock
Labels: P2, cla: yes, pr: lgtm, pr: merge ready, pr: merge safe, target: major

#18247 refactor(datepicker): implement range selection model
  src/material/core/datetime/date-selection-model.ts
  src/material/datepicker/date-range-input-parts.ts
  src/material/datepicker/date-range-input.ts
  src/material/datepicker/datepicker-input-base.ts
  src/material/datepicker/datepicker-input.ts
  tools/public_api_guard/material/core.d.ts
  tools/public_api_guard/material/datepicker.d.ts
Labels: P3, cla: yes, pr: merge safe, target: development-branch

#18263 build: bump to latest Angular RC
  package.json
  yarn.lock
Labels: P3, cla: yes, pr: lgtm, pr: merge ready, pr: merge safe, target: major

#18224 feat(material-experimental/mdc-input): add test harness
  src/material-experimental/config.bzl
  src/material-experimental/mdc-input/testing/BUILD.bazel
  src/material-experimental/mdc-input/testing/index.ts
  src/material-experimental/mdc-input/testing/input-harness.spec.ts
  src/material-experimental/mdc-input/testing/public-api.ts
Labels: cla: yes, pr: lgtm, pr: merge ready, pr: merge safe, target: minor

#18259 refactor: clean up typescript 3.7 workarounds
  src/cdk/overlay/position/flexible-connected-position-strategy.ts
  src/cdk/text-field/autosize.ts
Labels: P3, cla: yes, pr: lgtm, pr: merge ready, target: major

#18221 fix(material/input): input harness not matching `matNativeControl`
  src/material/input/testing/input-harness.ts
  src/material/input/testing/shared.spec.ts
Labels: P3, cla: yes, pr: lgtm, pr: merge ready, target: patch

#18215 fix(tree): not allowing horizontal overflow
  src/material/tree/tree.scss
Labels: P4, caretaker note, cla: yes, pr: lgtm, pr: merge ready, target: patch

#18201 feat(cdk/focus-trap) Add ConfigurableFocusTrap classes
  src/cdk/a11y/focus-trap/configurable-focus-trap-config.ts
  src/cdk/a11y/focus-trap/configurable-focus-trap-factory.ts
  src/cdk/a11y/focus-trap/configurable-focus-trap.spec.ts
  src/cdk/a11y/focus-trap/configurable-focus-trap.ts
  src/cdk/a11y/focus-trap/event-listener-inert-strategy.spec.ts
  src/cdk/a11y/focus-trap/event-listener-inert-strategy.ts
  src/cdk/a11y/focus-trap/focus-trap-inert-strategy.ts
  src/cdk/a11y/focus-trap/focus-trap-manager.spec.ts
  src/cdk/a11y/focus-trap/focus-trap-manager.ts
  src/cdk/a11y/focus-trap/focus-trap.ts
  src/cdk/a11y/focus-trap/polyfill.ts
  src/cdk/a11y/public-api.ts
  tools/public_api_guard/cdk/a11y.d.ts
Labels: cla: yes, pr: lgtm, pr: merge ready, target: minor

#17970 feat(drag-drop): add injection token for configuring the input defaults
  src/cdk/drag-drop/directives/config.ts
  src/cdk/drag-drop/directives/drag.spec.ts
  src/cdk/drag-drop/directives/drag.ts
  src/cdk/drag-drop/directives/drop-list.ts
  src/cdk/drag-drop/drag-ref.ts
  src/cdk/drag-drop/public-api.ts
  tools/public_api_guard/cdk/drag-drop.d.ts
Labels: P2, cla: yes, pr: lgtm, pr: merge ready, target: minor

#17855 fix(overlay): restore previous host element before attaching
  src/cdk/overlay/overlay-ref.ts
  src/cdk/overlay/overlay.spec.ts
Labels: P3, cla: yes, pr: lgtm, pr: merge ready, target: patch

#17595 feat(paginator): add provider to configure default options
  src/material/paginator/paginator.spec.ts
  src/material/paginator/paginator.ts
  tools/public_api_guard/material/paginator.d.ts
Labels: P3, caretaker note, cla: yes, pr: lgtm, pr: merge ready, target: minor

#17584 fix(list): allow for list and list items to be disabled
  src/material/list/list.scss
  src/material/list/list.spec.ts
  src/material/list/list.ts
  tools/public_api_guard/material/list.d.ts
Labels: P3, cla: yes, pr: lgtm, pr: merge ready, target: patch

#18278 refactor: clean up datepicker base class abstract methods
  src/material/datepicker/date-range-input-parts.ts
  src/material/datepicker/datepicker-input.ts
  tools/public_api_guard/material/datepicker.d.ts
Labels: P3, cla: yes, pr: lgtm, pr: merge ready, pr: merge safe, target: development-branch

#18261 feat(material-experimental/chip): Add focus indicators
  src/material-experimental/mdc-chips/chip-grid.spec.ts
  src/material-experimental/mdc-chips/chip-icons.ts
  src/material-experimental/mdc-chips/chip-option.html
  src/material-experimental/mdc-chips/chip-option.spec.ts
  src/material-experimental/mdc-chips/chip-option.ts
  src/material-experimental/mdc-chips/chip-remove.spec.ts
  src/material-experimental/mdc-chips/chip-row.html
  src/material-experimental/mdc-chips/chip-row.spec.ts
  src/material-experimental/mdc-chips/chip.html
  src/material-experimental/mdc-chips/chip.spec.ts
  src/material-experimental/mdc-chips/chip.ts
  src/material-experimental/mdc-chips/chips.scss
  src/material-experimental/mdc-chips/module.ts
  src/material-experimental/mdc-helpers/_mdc-helpers.scss
Labels: G, cla: yes, pr: lgtm, pr: merge ready, pr: merge safe, target: development-branch

#18281 build: bump to latest MDC Canary to fix regression
  package.json
  yarn.lock
Labels: P3, cla: yes, pr: lgtm, pr: merge ready, pr: merge safe, target: major

#18276 build: run saucelabs and browserstack tests with ivy
  tools/gulp/tasks/unit-test.ts
  tools/system-config-tmpl.js
Labels: cla: yes, pr: lgtm, pr: merge ready, pr: merge safe, target: patch

#18283 build: update to angular v9.0.0-rc.11
  package.json
  yarn.lock
Labels: P3, cla: yes, pr: lgtm, pr: merge ready, pr: merge safe, target: patch

#18266 fix(material-experimental/mdc-form-field): ensure validity styling is not reset by foundation
  src/material-experimental/mdc-form-field/form-field.ts
  src/material-experimental/mdc-input/input.spec.ts
Labels: P3, cla: yes, pr: lgtm, pr: merge ready, pr: merge safe, target: patch

#18265 feat(material-experimental/mdc-form-field): support theming through feature targeting
  src/material-experimental/mdc-form-field/BUILD.bazel
  src/material-experimental/mdc-form-field/_mdc-form-field.scss
  src/material-experimental/mdc-form-field/_mdc-text-field-theme-variable-refresh.scss
  src/material-experimental/mdc-form-field/form-field.scss
Labels: cla: yes, target: patch

#18016 build: create script that simplifies bazel testing workflow
  package.json
  scripts/run-component-tests.js
  tools/defaults.bzl
Labels: cla: yes, pr: lgtm, pr: merge ready, pr: merge safe, target: patch

#18184 Maps rectangle
  src/dev-app/google-map/google-map-demo.html
  src/dev-app/google-map/google-map-demo.ts
  src/google-maps/google-maps-module.ts
  src/google-maps/map-rectangle/map-rectangle.spec.ts
  src/google-maps/map-rectangle/map-rectangle.ts
  src/google-maps/public-api.ts
  src/google-maps/testing/fake-google-map-utils.ts
  tools/public_api_guard/google-maps/google-maps.d.ts
Labels: cla: yes, pr: lgtm, pr: merge ready, pr: merge safe, target: development-branch

#17006 fix(overlay): only clear duplicate containers from different platform
  src/cdk/overlay/fullscreen-overlay-container.ts
  src/cdk/overlay/overlay-container.spec.ts
  src/cdk/overlay/overlay-container.ts
  src/material/select/testing/shared.spec.ts
  tools/public_api_guard/cdk/overlay.d.ts
Labels: P2, cla: yes, pr: lgtm, pr: merge ready, target: patch

#18294 fix(drag-drop): auto scrolling not working if list uses scroll snapping
  src/cdk/drag-drop/directives/drag.spec.ts
  src/cdk/drag-drop/drop-list-ref.ts
Labels: P3, cla: yes, pr: lgtm, pr: merge ready, target: patch

#18275 fix(material/slider) Update slider to use injected document
  src/material/slider/slider.ts
  tools/public_api_guard/material/slider.d.ts
Labels: G, cla: yes, pr: lgtm, pr: merge ready, target: patch

#18274 chore: stop importing symbols from zone-types.d.ts
  src/cdk/testing/testbed/task-state-zone-interceptor.ts
  src/cdk/testing/testbed/zone-types.d.ts
Labels: cla: yes, pr: lgtm, pr: merge ready, target: patch

#18230 fix(drag-drop): error if next sibling is removed after drag sequence has started
  src/cdk/drag-drop/directives/drag.spec.ts
  src/cdk/drag-drop/drag-ref.ts
Labels: P3, cla: yes, pr: lgtm, pr: merge ready, target: patch

#18052 fix(material-experimental/mdc-chips): support home/end in chip grid
  src/material-experimental/mdc-chips/chip-grid.spec.ts
  src/material-experimental/mdc-chips/chip-grid.ts
Labels: P3, cla: yes, pr: lgtm, pr: merge ready, target: patch

#18048 fix(checkbox): outline not visible when checked in high contrast mode
  src/material/checkbox/_checkbox-theme.scss
  src/material/checkbox/checkbox.scss
Labels: P3, a11y, cla: yes, pr: lgtm, pr: merge ready, target: patch

#16643 fix(drag-drop): not picking up initial disabled state of handle
  src/cdk/drag-drop/directives/drag.spec.ts
  src/cdk/drag-drop/directives/drag.ts
Labels: P3, cla: yes, pr: lgtm, pr: merge ready, target: patch

#18300 refactor: fix CI failures for 9.0.x branch
  package.json
  tools/public_api_guard/cdk/a11y.d.ts
  tools/public_api_guard/cdk/accordion.d.ts
  tools/public_api_guard/cdk/bidi.d.ts
  tools/public_api_guard/cdk/collections.d.ts
  tools/public_api_guard/cdk/drag-drop.d.ts
  tools/public_api_guard/cdk/observers.d.ts
  tools/public_api_guard/cdk/overlay.d.ts
  tools/public_api_guard/cdk/portal.d.ts
  tools/public_api_guard/cdk/scrolling.d.ts
  tools/public_api_guard/cdk/stepper.d.ts
  tools/public_api_guard/cdk/table.d.ts
  tools/public_api_guard/cdk/text-field.d.ts
  tools/public_api_guard/cdk/tree.d.ts
  tools/public_api_guard/google-maps/google-maps.d.ts
  tools/public_api_guard/material/autocomplete.d.ts
  tools/public_api_guard/material/badge.d.ts
  tools/public_api_guard/material/bottom-sheet.d.ts
  tools/public_api_guard/material/button-toggle.d.ts
  tools/public_api_guard/material/checkbox.d.ts
  tools/public_api_guard/material/chips.d.ts
  tools/public_api_guard/material/core.d.ts
  tools/public_api_guard/material/datepicker.d.ts
  tools/public_api_guard/material/dialog.d.ts
  tools/public_api_guard/material/divider.d.ts
  tools/public_api_guard/material/expansion.d.ts
  tools/public_api_guard/material/form-field.d.ts
  tools/public_api_guard/material/grid-list.d.ts
  tools/public_api_guard/material/icon.d.ts
  tools/public_api_guard/material/input.d.ts
  tools/public_api_guard/material/list.d.ts
  tools/public_api_guard/material/menu.d.ts
  tools/public_api_guard/material/paginator.d.ts
  tools/public_api_guard/material/progress-bar.d.ts
  tools/public_api_guard/material/progress-spinner.d.ts
  tools/public_api_guard/material/radio.d.ts
  tools/public_api_guard/material/select.d.ts
  tools/public_api_guard/material/sidenav.d.ts
  tools/public_api_guard/material/slide-toggle.d.ts
  tools/public_api_guard/material/slider.d.ts
  tools/public_api_guard/material/snack-bar.d.ts
  tools/public_api_guard/material/sort.d.ts
  tools/public_api_guard/material/table.d.ts
  tools/public_api_guard/material/tabs.d.ts
  tools/public_api_guard/material/tooltip.d.ts
  tools/public_api_guard/material/tree.d.ts
  tools/public_api_guard/youtube-player/youtube-player.d.ts
  yarn.lock
Labels: cla: yes, pr: lgtm, pr: merge ready, pr: merge safe

#18304 build: rework flaky focus trap tests
  src/cdk/a11y/focus-trap/event-listener-inert-strategy.spec.ts
Labels: P3, cla: yes, pr: lgtm, pr: merge ready, pr: merge safe, target: patch

#18273 feat(popover-edit): Ability to disable edit on specific cells
  src/cdk-experimental/popover-edit/edit-event-dispatcher.ts
  src/cdk-experimental/popover-edit/popover-edit.spec.ts
  src/cdk-experimental/popover-edit/table-directives.ts
  src/components-examples/material-experimental/popover-edit/BUILD.bazel
  src/components-examples/material-experimental/popover-edit/index.ts
  src/components-examples/material-experimental/popover-edit/popover-edit-mat-table/popover-edit-mat-table-example.html
  src/components-examples/material-experimental/popover-edit/popover-edit-mat-table/popover-edit-mat-table-example.ts
  src/material-experimental/popover-edit/popover-edit.spec.ts
  src/material-experimental/popover-edit/table-directives.ts
Labels: cla: yes, pr: lgtm, pr: merge ready, pr: merge safe, target: minor

#18210 docs(datepicker): convert date module tables to be mobile-friendly
  src/material/datepicker/datepicker.md
Labels: P2, cla: yes, docs, pr: lgtm, pr: merge ready, pr: merge safe, target: patch

#18036 fix(material-experimental/mdc-button): some button variants not visible in high contrast mode
  src/material-experimental/mdc-button/button.scss
Labels: P3, cla: yes, pr: lgtm, pr: merge ready, pr: merge safe, target: patch

#18315 fix(schematics): global typography class always being added
  src/material/schematics/ng-add/index.spec.ts
  src/material/schematics/ng-add/theming/theming.ts
Labels: P2, cla: yes, pr: lgtm, pr: merge ready, pr: merge safe, target: patch

#18319 docs(drag-drop): add last star wars movie in examples
  src/components-examples/cdk/drag-drop/cdk-drag-drop-custom-placeholder/cdk-drag-drop-custom-placeholder-example.ts
  src/components-examples/cdk/drag-drop/cdk-drag-drop-custom-preview/cdk-drag-drop-custom-preview-example.ts
  src/components-examples/cdk/drag-drop/cdk-drag-drop-sorting/cdk-drag-drop-sorting-example.ts
Labels: cla: yes, docs, pr: lgtm, pr: merge ready, pr: merge safe, target: patch

#18152 fix(cdk/a11y): make cdk-high-contrast work w/ emulated view encapsulation
  src/cdk/a11y/_a11y.scss
Labels: P2, cla: yes, pr: lgtm, pr: merge ready, target: major

#17699 fix(chips): unable to set custom tabindex on chip
  src/material-experimental/mdc-chips/chip.spec.ts
  src/material/chips/chip.spec.ts
  src/material/chips/chip.ts
  tools/public_api_guard/material/chips.d.ts
Labels: P3, cla: yes, pr: lgtm, pr: merge ready, target: patch

#18314 fix(material-experimental/mdc-chips): chip removal not working if animations are disabled
  src/material-experimental/mdc-chips/chips.scss
Labels: P2, cla: yes, pr: lgtm, pr: merge ready, target: patch

#18306 fix(material/icon/testing): Adds size specs to fake icon
  src/material/icon/testing/fake-icon-registry.ts
Labels: G, cla: yes, pr: lgtm, pr: merge ready, target: minor

#18285 fix(slide-toggle): clicks not landing correctly in some cases on Chrome
  src/material/slide-toggle/BUILD.bazel
  src/material/slide-toggle/slide-toggle.spec.ts
  src/material/slide-toggle/slide-toggle.ts
Labels: P3, cla: yes, pr: lgtm, pr: merge ready, target: patch

#17997 fix(material-experimental/mdc-chips): leading icon not hidden on init when preselected
  src/material-experimental/mdc-chips/BUILD.bazel
  src/material-experimental/mdc-chips/chip-option.spec.ts
  src/material-experimental/mdc-chips/chip-option.ts
Labels: P3, cla: yes, pr: lgtm, pr: merge ready, target: patch

#17253 perf(ripple): avoid page layouts from ripple elements
  src/material/core/ripple/_ripple.scss
Labels: P2, cla: yes, perf, pr: lgtm, pr: merge ready, target: patch

#18332 fix: reduce amount of generated high contrast styles
  src/material-experimental/mdc-button/button.scss
  src/material-experimental/mdc-card/card.scss
  src/material-experimental/mdc-chips/chips.scss
  src/material-experimental/mdc-menu/menu.scss
  src/material-experimental/mdc-slide-toggle/slide-toggle.scss
  src/material-experimental/mdc-slider/slider.scss
  src/material-experimental/popover-edit/_popover-edit.scss
  src/material/autocomplete/autocomplete.scss
  src/material/badge/_badge-theme.scss
  src/material/bottom-sheet/bottom-sheet-container.scss
  src/material/button-toggle/button-toggle.scss
  src/material/button/button.scss
  src/material/card/card.scss
  src/material/checkbox/checkbox.scss
  src/material/chips/chips.scss
  src/material/core/option/option.scss
  src/material/core/ripple/_ripple.scss
  src/material/datepicker/calendar-body.scss
  src/material/dialog/dialog.scss
  src/material/expansion/expansion-panel.scss
  src/material/form-field/form-field-fill.scss
  src/material/form-field/form-field-input.scss
  src/material/form-field/form-field-legacy.scss
  src/material/form-field/form-field-standard.scss
  src/material/form-field/form-field.scss
  src/material/list/list.scss
  src/material/menu/menu.scss
  src/material/progress-bar/progress-bar.scss
  src/material/radio/radio.scss
  src/material/select/select.scss
  src/material/sidenav/drawer.scss
  src/material/slide-toggle/slide-toggle.scss
  src/material/slider/slider.scss
  src/material/snack-bar/snack-bar-container.scss
  src/material/sort/sort-header.scss
  src/material/tabs/_tabs-common.scss
  src/material/toolbar/toolbar.scss
  src/material/tooltip/tooltip.scss
Labels: P3, cla: yes, pr: lgtm, pr: merge ready, target: patch

#18330 build: update to latest ts-api-guardian version
  package.json
  tools/bazel/postinstall-patches.js
  tools/bazel/ts_api_guardian_rules_nodejs_1.0.0.patch
  yarn.lock
Labels: cla: yes, pr: lgtm, pr: merge ready, pr: merge safe, target: patch

#18293 docs: grammar test-harness
  src/cdk/testing/test-harnesses.md
Labels: cla: yes, docs, pr: lgtm, pr: merge ready, pr: merge safe, target: patch

#18339 build: enable all ngtsc strictness flags
  src/components-examples/material/select/select-initial-value/select-initial-value-example.html
  src/components-examples/material/select/select-initial-value/select-initial-value-example.ts
  src/components-examples/material/table/table-filtering/table-filtering-example.html
  src/components-examples/material/table/table-filtering/table-filtering-example.ts
  src/components-examples/material/table/table-overview/table-overview-example.html
  src/components-examples/material/table/table-overview/table-overview-example.ts
  src/dev-app/select/select-demo.html
  src/e2e-app/radio/radio-e2e.html
  tools/bazel/postinstall-patches.js
Labels: P3, cla: yes, pr: lgtm, pr: merge ready, pr: merge safe, target: patch

#18107 docs(v9-hammerjs-migration): fixes and refinements
  guides/v9-hammerjs-migration.md
Labels: P3, cla: yes, docs, pr: lgtm, pr: merge ready, pr: merge safe, target: major

#18347 chore: bump version to 9.0.0-rc.9 w/ changelog
  CHANGELOG.md
  package.json
Labels: cla: yes, pr: lgtm, pr: merge ready, pr: merge safe, target: major
