Repository angular/components, pull requests merged in 2021-08, with the labels that each got.

#23291 docs: prebuilt themes incorrectly listed as dark
  guides/theming.md
Labels: P3, cla: yes, docs, merge ready, merge safe, target: patch

#23290 build: flag unnecessary stylelint disable clauses
  .stylelintrc.json
  package.json
  src/material-experimental/mdc-helpers/_mdc-helpers.scss
  src/material/core/typography/_typography.scss
  src/material/sidenav/drawer.scss
  yarn.lock
Labels: P3, cla: yes, merge ready, merge safe, target: minor

#23287 build: update dependencies in lock file
  yarn.lock
Labels: cla: yes, merge ready, merge safe, target: rc

#23296 fix(cdk/text-field): avoid page jump on firefox
  src/cdk/text-field/autosize.ts
Labels: P3, cla: yes, merge ready, target: patch

#23293 refactor(cdk/drag-drop): clean up IE workarounds
  src/cdk/drag-drop/directives/drag.spec.ts
  src/cdk/drag-drop/directives/drag.ts
  src/cdk/drag-drop/drag-ref.ts
  src/cdk/drag-drop/drop-list-ref.ts
  src/cdk/drag-drop/parent-position-tracker.ts
Labels: P3, cla: yes, merge ready, target: major

#23285 fix(material-experimental/mdc-paginator): add screen reader announcement for current range when navigating between pages
  src/material-experimental/mdc-paginator/paginator.html
Labels: P2, a11y, cla: yes, merge ready, target: patch

#23283 refactor(material/progress-spinner): clean up IE workarounds
  src/material/progress-spinner/progress-spinner.html
  src/material/progress-spinner/progress-spinner.scss
  src/material/progress-spinner/progress-spinner.spec.ts
  src/material/progress-spinner/progress-spinner.ts
  tools/public_api_guard/material/progress-spinner.md
Labels: P3, cla: yes, merge ready, target: major

#23272 perf(cdk/drag-drop): avoid excessive change detections with zone-patch-rxjs
  src/cdk/drag-drop/directives/drag.ts
Labels: P3, cla: yes, merge ready, target: patch

#23254 fix(cdk/overlay): expand `OverlayReference` interface to cover more properties
  src/cdk/overlay/overlay-reference.ts
Labels: P3, cla: yes, merge ready, target: patch

#23237 fix(material/core): handle hues inferred as numbers
  src/material/core/theming/_theming.scss
Labels: P3, cla: yes, merge ready, target: patch

#23306 Revert "fix(material/menu): not interrupting keyboard events to other…
  src/material-experimental/mdc-menu/menu.spec.ts
  src/material/menu/menu.spec.ts
  src/material/menu/menu.ts
Labels: P2, cla: yes, merge ready, target: patch

#23307 build: update peer dependency for angular framework dependencies
  packages.bzl
Labels: P2, cla: yes, merge ready, merge safe, target: major

#23312 release: bump version to 12.2.0 w/ changelog
  CHANGELOG.md
  package.json
Labels: cla: yes, merge ready, merge safe, target: patch

#23313 release: update changelog with 12.2.0 release
  CHANGELOG.md
Labels: cla: yes, merge ready, merge safe, target: major

#23318 release: remote luxon adapter from changelog
  CHANGELOG.md
Labels: cla: yes, merge ready, merge safe, target: major

#23319 release: remote luxon adapter from changelog
  CHANGELOG.md
Labels: cla: yes, merge ready, target: patch

#23324 release: add luxon adapter back to the changelog.
  CHANGELOG.md
Labels: cla: yes, merge ready, merge safe, target: patch

#23325 release: add luxon adapter back to the changelog. (#23324)
  CHANGELOG.md
Labels: cla: yes, merge ready, merge safe, target: minor

#23289 fix(material/core): sanity checks not running
  src/material/core/common-behaviors/common-module.ts
Labels: cla: yes, P2, merge ready, caretaker note, target: patch

#23266 fix(material-experimental/mdc-button): fix ripple size after MDC changes
  src/material-experimental/mdc-button/button.scss
Labels: cla: yes, merge ready, merge safe, caretaker note, target: patch

#23160 fix(material/tabs): pagination not working inside flex container
  src/material-experimental/mdc-tabs/tab-group.scss
  src/material/tabs/tab-group.scss
Labels: cla: yes, P3, merge ready, target: patch

#17519 refactor(cdk/overlay): remove deprecated connected position strategy
  src/cdk/overlay/position/connected-position-strategy.spec.ts
  src/cdk/overlay/position/connected-position-strategy.ts
  src/cdk/overlay/position/overlay-position-builder.ts
  src/cdk/overlay/public-api.ts
  tools/public_api_guard/cdk/overlay.md
Labels: cla: yes, P2, merge ready, caretaker note, target: major

#23143 feat(material-experimental/mdc-slide-toggle): switch to non-deprecated styles
  scripts/check-mdc-tests-config.ts
  src/e2e-app/protractor.conf.js
  src/material-experimental/mdc-helpers/_focus-indicators.scss
  src/material-experimental/mdc-slide-toggle/_slide-toggle-theme.scss
  src/material-experimental/mdc-slide-toggle/slide-toggle.e2e.spec.ts
  src/material-experimental/mdc-slide-toggle/slide-toggle.html
  src/material-experimental/mdc-slide-toggle/slide-toggle.scss
  src/material-experimental/mdc-slide-toggle/slide-toggle.spec.ts
  src/material-experimental/mdc-slide-toggle/slide-toggle.ts
  src/material-experimental/mdc-slide-toggle/testing/BUILD.bazel
  src/material-experimental/mdc-slide-toggle/testing/slide-toggle-harness.ts
  src/material/slide-toggle/slide-toggle.spec.ts
  src/material/slide-toggle/testing/shared.spec.ts
  src/material/slide-toggle/testing/slide-toggle-harness.ts
  tools/public_api_guard/material/slide-toggle-testing.md
Labels: cla: yes, P2, merge ready, target: minor

#23209 fix(cdk/drag-drop): add generic parameter for item type in CdkDragDrop
  src/cdk/drag-drop/drag-events.ts
  tools/public_api_guard/cdk/drag-drop.md
Labels: cla: yes, P3, merge ready, target: patch

#23316 build: update peerDependencies to allow rxjs 7
  packages.bzl
Labels: cla: yes, P2, merge ready, merge safe, target: patch

#23332 test(material/slide-toggle): fix test flakes
  src/material-experimental/mdc-slide-toggle/slide-toggle.spec.ts
  src/material/slide-toggle/slide-toggle.spec.ts
Labels: cla: yes, P3, merge ready, merge safe, target: major

#23337 fix(cdk/drag-drop): add conditional to scroll update
  src/cdk/drag-drop/drag-ref.ts
Labels: cla: yes, P2, merge ready, target: major

#23333 build: switch to release tool from dev-infra
  .bazelrc
  .circleci/config.yml
  .ng-dev/release.ts
  package.json
  scripts/build-and-check-release-output.ts
  scripts/build-packages-dist.ts
  src/cdk-experimental/package.json
  src/cdk/package.json
  src/google-maps/package.json
  src/material-date-fns-adapter/package.json
  src/material-experimental/package.json
  src/material-luxon-adapter/package.json
  src/material-moment-adapter/package.json
  src/material/package.json
  src/youtube-player/package.json
  tools/bazel-stamp-vars.js
  tools/legacy-release/base-release-task.ts
  tools/legacy-release/changelog-commit-template.hbs
  tools/legacy-release/changelog-root-template.hbs
  tools/legacy-release/changelog.ts
  tools/legacy-release/check-release-output.ts
  tools/legacy-release/extract-release-notes.ts
  tools/legacy-release/git/git-client.ts
  tools/legacy-release/git/github-urls.ts
  tools/legacy-release/npm/npm-client.ts
  tools/legacy-release/prompt/new-version-prompt.ts
  tools/legacy-release/prompt/npm-dist-tag-prompt.ts
  tools/legacy-release/prompt/prerelease-labels.ts
  tools/legacy-release/prompt/upstream-remote-prompt.ts
  tools/legacy-release/publish-release.ts
  tools/legacy-release/stage-release.ts
  tools/legacy-release/tsconfig.json
  tools/legacy-release/version-name/create-version.ts
  tools/legacy-release/version-name/parse-version.ts
  tools/legacy-release/version-name/publish-branches.ts
  tools/release-checks/check-framework-peer-dependency.ts
  tools/release-checks/check-migration-collections.ts
  tools/release-checks/npm-package-output/check-package.ts
  tools/release-checks/npm-package-output/index.ts
  tools/release-checks/npm-package-output/output-validations.ts
  tools/release/release-output/release-packages.ts
  tools/release/tsconfig.json
  tools/tsconfig-ci.json
Labels: cla: yes, merge ready, merge safe, target: major

#23323 build: don't run tests against edge
  test/browser-providers.js
  test/karma-browsers.json
Labels: cla: yes, P3, merge ready, merge safe, target: patch

#23276 docs(material/slider): changed value property of mat-slider from gett…
  guides/getting-started.md
Labels: cla: yes, merge ready, merge safe, target: patch, commit message fixup

#23346 build: fix staging sanity release checks picking up incorrect packages
  .ng-dev/release.ts
  package.json
  tools/release-checks/index.js
Labels: cla: yes, merge ready, merge safe, target: patch

#23347 Bump version to "v12.2.1" with changelog.
  CHANGELOG.md
  package.json
Labels: cla: yes

#23348 docs: release notes for the v12.2.1 release
  CHANGELOG.md
Labels: cla: yes

#23341 build: update to version 13 of MDC
  package.json
  packages.bzl
  yarn.lock
Labels: cla: yes, P3, merge ready, merge safe, target: major

#23359 docs: fix up getting started guide
  guides/getting-started.md
Labels: cla: yes, P3, docs, merge ready, merge safe, target: patch

#23358 docs(material/expansion): fix typo in doc string
  src/material/expansion/expansion-panel.ts
Labels: cla: yes, docs, merge ready, merge safe, P4, target: patch

#23085 fix(material/dialog): improve screen reader support when opened
  src/material-experimental/mdc-dialog/dialog.spec.ts
  src/material-experimental/mdc-dialog/dialog.ts
  src/material/dialog/dialog-container.ts
  src/material/dialog/dialog.spec.ts
  src/material/dialog/dialog.ts
  tools/public_api_guard/material/dialog.md
Labels: cla: yes, P3, a11y, merge ready, G, target: minor, area: material/dialog

#23321 build: migrate to use the new layout of the @angular/dev-infra-private package
  .ng-dev/caretaker.ts
  .ng-dev/commit-message.ts
  .ng-dev/format.ts
  .ng-dev/github.ts
  .ng-dev/merge.ts
  .ng-dev/release.ts
  package.json
  scripts/build-packages-dist.ts
  test/benchmarks/cdk/testing/component-harness/BUILD.bazel
  test/benchmarks/cdk/testing/component-harness/protractor-benchmark-utilities.ts
  test/benchmarks/material/button/BUILD.bazel
  test/benchmarks/material/button/button.perf-spec.ts
  test/benchmarks/material/card/BUILD.bazel
  test/benchmarks/material/card/card.perf-spec.ts
  test/benchmarks/material/checkbox/BUILD.bazel
  test/benchmarks/material/checkbox/checkbox.perf-spec.ts
  test/benchmarks/material/chips/BUILD.bazel
  test/benchmarks/material/chips/chips.perf-spec.ts
  test/benchmarks/material/form-field/BUILD.bazel
  test/benchmarks/material/form-field/form-field.perf-spec.ts
  test/benchmarks/material/menu/BUILD.bazel
  test/benchmarks/material/menu/menu.perf-spec.ts
  test/benchmarks/material/radio/BUILD.bazel
  test/benchmarks/material/radio/radio.perf-spec.ts
  test/benchmarks/material/slide-toggle/BUILD.bazel
  test/benchmarks/material/slide-toggle/slide-toggle.perf-spec.ts
  test/benchmarks/material/table/BUILD.bazel
  test/benchmarks/material/table/table.perf-spec.ts
  test/benchmarks/material/tabs/BUILD.bazel
  test/benchmarks/material/tabs/tabs.perf-spec.ts
  test/benchmarks/mdc/button/BUILD.bazel
  test/benchmarks/mdc/button/button.perf-spec.ts
  test/benchmarks/mdc/card/BUILD.bazel
  test/benchmarks/mdc/card/card.perf-spec.ts
  test/benchmarks/mdc/checkbox/BUILD.bazel
  test/benchmarks/mdc/checkbox/checkbox.perf-spec.ts
  test/benchmarks/mdc/chips/BUILD.bazel
  test/benchmarks/mdc/chips/chips.perf-spec.ts
  test/benchmarks/mdc/form-field/BUILD.bazel
  test/benchmarks/mdc/form-field/form-field.perf-spec.ts
  test/benchmarks/mdc/menu/BUILD.bazel
  test/benchmarks/mdc/menu/menu.perf-spec.ts
  test/benchmarks/mdc/radio/BUILD.bazel
  test/benchmarks/mdc/radio/radio.perf-spec.ts
  test/benchmarks/mdc/slide-toggle/BUILD.bazel
  test/benchmarks/mdc/slide-toggle/slide-toggle.perf-spec.ts
  test/benchmarks/mdc/table/BUILD.bazel
  test/benchmarks/mdc/table/table.perf-spec.ts
  test/benchmarks/mdc/tabs/BUILD.bazel
  test/benchmarks/mdc/tabs/tabs.perf-spec.ts
  tools/release-checks/check-framework-peer-dependency.ts
  tools/release-checks/check-migration-collections.ts
  tools/release-checks/npm-package-output/check-package.ts
  tools/release-checks/npm-package-output/index.ts
  yarn.lock
Labels: cla: yes, merge ready, merge safe, target: major, area: build

#23367 ci: add breaking changes auto labeling action
  .github/workflows/dev-infra.yml
Labels: cla: yes, merge ready, merge safe, target: patch, area: build

#23368 build: add mainBranchName to Github configuration
  .ng-dev/github.ts
Labels: cla: yes, merge ready, merge safe, target: major, area: build

#23366 build: migrate to use the new layout of the @angular/dev-infra-private package
  .ng-dev/caretaker.ts
  .ng-dev/commit-message.ts
  .ng-dev/format.ts
  .ng-dev/github.ts
  .ng-dev/merge.ts
  .ng-dev/release.ts
  package.json
  scripts/build-packages-dist.ts
  test/benchmarks/cdk/testing/component-harness/BUILD.bazel
  test/benchmarks/cdk/testing/component-harness/protractor-benchmark-utilities.ts
  test/benchmarks/material/button/BUILD.bazel
  test/benchmarks/material/button/button.perf-spec.ts
  test/benchmarks/material/card/BUILD.bazel
  test/benchmarks/material/card/card.perf-spec.ts
  test/benchmarks/material/checkbox/BUILD.bazel
  test/benchmarks/material/checkbox/checkbox.perf-spec.ts
  test/benchmarks/material/chips/BUILD.bazel
  test/benchmarks/material/chips/chips.perf-spec.ts
  test/benchmarks/material/form-field/BUILD.bazel
  test/benchmarks/material/form-field/form-field.perf-spec.ts
  test/benchmarks/material/menu/BUILD.bazel
  test/benchmarks/material/menu/menu.perf-spec.ts
  test/benchmarks/material/radio/BUILD.bazel
  test/benchmarks/material/radio/radio.perf-spec.ts
  test/benchmarks/material/slide-toggle/BUILD.bazel
  test/benchmarks/material/slide-toggle/slide-toggle.perf-spec.ts
  test/benchmarks/material/table/BUILD.bazel
  test/benchmarks/material/table/table.perf-spec.ts
  test/benchmarks/material/tabs/BUILD.bazel
  test/benchmarks/material/tabs/tabs.perf-spec.ts
  test/benchmarks/mdc/button/BUILD.bazel
  test/benchmarks/mdc/button/button.perf-spec.ts
  test/benchmarks/mdc/card/BUILD.bazel
  test/benchmarks/mdc/card/card.perf-spec.ts
  test/benchmarks/mdc/checkbox/BUILD.bazel
  test/benchmarks/mdc/checkbox/checkbox.perf-spec.ts
  test/benchmarks/mdc/chips/BUILD.bazel
  test/benchmarks/mdc/chips/chips.perf-spec.ts
  test/benchmarks/mdc/form-field/BUILD.bazel
  test/benchmarks/mdc/form-field/form-field.perf-spec.ts
  test/benchmarks/mdc/menu/BUILD.bazel
  test/benchmarks/mdc/menu/menu.perf-spec.ts
  test/benchmarks/mdc/radio/BUILD.bazel
  test/benchmarks/mdc/radio/radio.perf-spec.ts
  test/benchmarks/mdc/slide-toggle/BUILD.bazel
  test/benchmarks/mdc/slide-toggle/slide-toggle.perf-spec.ts
  test/benchmarks/mdc/table/BUILD.bazel
  test/benchmarks/mdc/table/table.perf-spec.ts
  test/benchmarks/mdc/tabs/BUILD.bazel
  test/benchmarks/mdc/tabs/tabs.perf-spec.ts
  tools/release-checks/check-framework-peer-dependency.ts
  tools/release-checks/check-migration-collections.ts
  tools/release-checks/npm-package-output/check-package.ts
  tools/release-checks/npm-package-output/index.ts
  yarn.lock
Labels: cla: yes, merge ready, merge safe, target: patch, area: build

#23383 build: update to the latest version of `@angular/dev-infra-private`
  package.json
  yarn.lock
Labels: cla: yes, P2, merge ready, merge safe, target: minor

#23391 build: update to the latest version of `@angular/dev-infra-private` (#23383)
  package.json
  yarn.lock
Labels: cla: yes, merge ready, merge safe, target: patch

#23363 feat(material/progress-bar): add default options injection token
  src/material-experimental/mdc-progress-bar/progress-bar.spec.ts
  src/material-experimental/mdc-progress-bar/progress-bar.ts
  src/material-experimental/mdc-progress-bar/public-api.ts
  src/material/progress-bar/progress-bar.spec.ts
  src/material/progress-bar/progress-bar.ts
  tools/public_api_guard/material/progress-bar.md
Labels: cla: yes, P3, merge ready, target: minor

#23388 fix(material/datepicker): wrong day of week read out for dates in first row
  src/material/datepicker/calendar-body.html
Labels: cla: yes, P2, a11y, merge ready, target: patch

#23302 feat(material-experimental/mdc-card): add DI token for configuring appearance
  src/material-experimental/mdc-card/BUILD.bazel
  src/material-experimental/mdc-card/card.spec.ts
  src/material-experimental/mdc-card/card.ts
Labels: cla: yes, P2, merge ready, target: minor

#23340 fix(material/checkbox): hide svg from assistive technology
  src/material-experimental/mdc-checkbox/checkbox.html
  src/material-experimental/mdc-checkbox/checkbox.spec.ts
  src/material-experimental/mdc-list/list-option.html
  src/material-experimental/mdc-list/selection-list.spec.ts
  src/material/checkbox/checkbox.html
  src/material/checkbox/checkbox.spec.ts
Labels: cla: yes, P3, a11y, merge ready, target: patch

#23304 refactor(cdk/a11y): clean up IE workarounds
  src/cdk/a11y/focus-trap/event-listener-inert-strategy.ts
  src/cdk/a11y/focus-trap/focus-trap.ts
  src/cdk/a11y/focus-trap/polyfill.ts
Labels: cla: yes, P3, merge ready, target: major

#23395 fix(cdk/a11y): error on firefox
  src/cdk/a11y/focus-trap/event-listener-inert-strategy.ts
Labels: cla: yes, P2, merge ready, merge safe, target: major

#23398 Bump version to "v12.2.2" with changelog.
  CHANGELOG.md
  package.json
Labels: cla: yes, target: patch

#23402 docs: release notes for the v12.2.2 release
  CHANGELOG.md
Labels: cla: yes

#23403 Bump version to "v13.0.0-next.1" with changelog.
  CHANGELOG.md
  package.json
Labels: cla: yes

#23393 Project import generated by Copybara.
  src/material-experimental/mdc-button/icon-button.scss
Labels: cla: yes, merge ready, merge safe, target: patch

#23375 docs: mention letter-spacing helper
  guides/typography.md
Labels: cla: yes, P3, docs, merge ready, merge safe, target: patch

#23407 build: update MDC to latest canary
  package.json
  yarn.lock
Labels: cla: yes, merge ready, merge safe, target: minor

#23411 build: update MDC to latest canary (#23407)
  package.json
  packages.bzl
  yarn.lock
Labels: cla: yes, merge ready, merge safe, target: patch

#23412 build: update MDC_PACKAGE_VERSION to latest canary
  packages.bzl
Labels: cla: yes, merge ready, merge safe, target: minor

#23415 docs(material/button-toggle): add selection mode example
  src/components-examples/material/button-toggle/button-toggle-mode/button-toggle-mode-example.html
  src/components-examples/material/button-toggle/button-toggle-mode/button-toggle-mode-example.ts
  src/components-examples/material/button-toggle/index.ts
  src/material/button-toggle/button-toggle.md
Labels: cla: yes, P3, merge ready, merge safe, target: patch

#23401 refactor(cdk/clipboard): clean up deprecated APIs for v13
  src/cdk/clipboard/copy-to-clipboard.ts
  tools/public_api_guard/cdk/clipboard.md
Labels: cla: yes, P2, merge ready, target: major, flag: breaking change, breaking changes

#23390 refactor(material/core): cleanup unsupported browser workarounds
  src/material/core/datetime/native-date-adapter.spec.ts
  src/material/core/datetime/native-date-adapter.ts
  tools/public_api_guard/material/core.md
Labels: cla: yes, P3, merge ready, target: major

#23357 feat(material/dialog): add support for content sections in harness
  src/material-experimental/mdc-dialog/testing/dialog-harness.ts
  src/material-experimental/mdc-dialog/testing/public-api.ts
  src/material/dialog/testing/dialog-harness.ts
  src/material/dialog/testing/shared.spec.ts
  tools/public_api_guard/material/dialog-testing.md
Labels: cla: yes, merge ready, target: minor

#23336 fix(material/datepicker): calendar reopening on spacebar selection
  src/material/datepicker/calendar.spec.ts
  src/material/datepicker/datepicker.spec.ts
  src/material/datepicker/month-view.html
  src/material/datepicker/month-view.spec.ts
  src/material/datepicker/month-view.ts
  src/material/datepicker/multi-year-view.html
  src/material/datepicker/multi-year-view.ts
  src/material/datepicker/year-view.html
  src/material/datepicker/year-view.ts
  tools/public_api_guard/material/datepicker.md
Labels: cla: yes, P2, a11y, merge ready, target: patch

#23429 build: no longer install snapshot build of `@angular/bazel`
  package.json
  src/cdk/schematics/testing/BUILD.bazel
  src/cdk/schematics/testing/test-case-setup.ts
  yarn.lock
Labels: cla: yes, merge ready, merge safe, target: major

#23423 test(multiple): clean up manual ngOnDestroy calls
  src/cdk-experimental/dialog/dialog.spec.ts
  src/cdk-experimental/popover-edit/popover-edit.spec.ts
  src/cdk/a11y/aria-describer/aria-describer.spec.ts
  src/cdk/a11y/focus-monitor/focus-monitor.spec.ts
  src/cdk/a11y/input-modality/input-modality-detector.spec.ts
  src/cdk/a11y/live-announcer/live-announcer.spec.ts
  src/cdk/drag-drop/drag-drop-registry.spec.ts
  src/cdk/overlay/dispatchers/overlay-keyboard-dispatcher.spec.ts
  src/cdk/overlay/dispatchers/overlay-outside-click-dispatcher.spec.ts
  src/cdk/overlay/fullscreen-overlay-container.spec.ts
  src/cdk/overlay/overlay-container.spec.ts
  src/cdk/overlay/overlay-directives.spec.ts
  src/cdk/overlay/position/global-position-strategy.spec.ts
  src/cdk/scrolling/viewport-ruler.spec.ts
  src/cdk/text-field/autofill.spec.ts
  src/material-experimental/column-resize/column-resize.spec.ts
  src/material-experimental/mdc-autocomplete/autocomplete.spec.ts
  src/material-experimental/mdc-dialog/dialog.spec.ts
  src/material-experimental/mdc-menu/menu.spec.ts
  src/material-experimental/mdc-select/select.spec.ts
  src/material-experimental/mdc-snack-bar/snack-bar.spec.ts
  src/material-experimental/mdc-tooltip/tooltip.spec.ts
  src/material-experimental/popover-edit/popover-edit.spec.ts
  src/material/autocomplete/autocomplete.spec.ts
  src/material/autocomplete/testing/shared.spec.ts
  src/material/bottom-sheet/bottom-sheet.spec.ts
  src/material/bottom-sheet/testing/shared.spec.ts
  src/material/datepicker/date-range-input.spec.ts
  src/material/datepicker/datepicker-actions.spec.ts
  src/material/datepicker/datepicker.spec.ts
  src/material/dialog/dialog.spec.ts
  src/material/dialog/testing/shared.spec.ts
  src/material/menu/menu.spec.ts
  src/material/menu/testing/shared.spec.ts
  src/material/select/select.spec.ts
  src/material/snack-bar/snack-bar.spec.ts
  src/material/snack-bar/testing/shared.spec.ts
  src/material/tooltip/tooltip.spec.ts
  test/karma-test-shim.js
Labels: cla: yes, P3, merge ready, merge safe, target: major

#23428 build: remove legacy release tooling
  package.json
  tools/legacy-release/base-release-task.ts
  tools/legacy-release/changelog-commit-template.hbs
  tools/legacy-release/changelog-root-template.hbs
  tools/legacy-release/changelog.ts
  tools/legacy-release/check-release-output.ts
  tools/legacy-release/extract-release-notes.ts
  tools/legacy-release/git/git-client.ts
  tools/legacy-release/git/github-urls.ts
  tools/legacy-release/npm/npm-client.ts
  tools/legacy-release/prompt/new-version-prompt.ts
  tools/legacy-release/prompt/npm-dist-tag-prompt.ts
  tools/legacy-release/prompt/prerelease-labels.ts
  tools/legacy-release/prompt/upstream-remote-prompt.ts
  tools/legacy-release/publish-release.ts
  tools/legacy-release/stage-release.ts
  tools/legacy-release/tsconfig.json
  tools/legacy-release/version-name/create-version.ts
  tools/legacy-release/version-name/parse-version.ts
  tools/legacy-release/version-name/publish-branches.ts
Labels: cla: yes, merge ready, merge safe, target: major

#23431 fix(material-experimental/mdc-slider): correct description of slider …
  src/material-experimental/mdc-slider/testing/slider-harness.spec.ts
  src/material-experimental/mdc-slider/testing/slider-harness.ts
Labels: cla: yes, merge ready, merge safe, target: patch, area: material/slider

#23426 refactor(material/tabs): remove deprecated APIs for v13
  src/material-experimental/mdc-tabs/testing/tab-harness.ts
  src/material/tabs/testing/tab-harness.ts
  tools/public_api_guard/material/tabs-testing.md
Labels: cla: yes, P2, merge ready, target: major, flag: breaking change, breaking changes

#23389 refactor(material/form-field): remove deprecated APIs for version 13
  src/material/form-field/form-field.html
  src/material/form-field/form-field.ts
  src/material/form-field/testing/form-field-harness.ts
  src/material/schematics/ng-update/data/constructor-checks.ts
  tools/public_api_guard/material/form-field-testing.md
  tools/public_api_guard/material/form-field.md
Labels: cla: yes, P2, merge ready, target: major, flag: breaking change, breaking changes

#23386 fix(material/stepper): remove ripple and hover styling for disabled step
  src/material/stepper/_stepper-theme.scss
  src/material/stepper/stepper.html
Labels: cla: yes, P2, a11y, merge ready, target: patch

#23376 refactor(multiple): clean up ripple overrides in MDC components
  src/material-experimental/mdc-button/BUILD.bazel
  src/material-experimental/mdc-button/button-base.ts
  src/material-experimental/mdc-button/button.html
  src/material-experimental/mdc-checkbox/BUILD.bazel
  src/material-experimental/mdc-checkbox/checkbox.html
  src/material-experimental/mdc-checkbox/checkbox.ts
  src/material-experimental/mdc-chips/BUILD.bazel
  src/material-experimental/mdc-chips/chip-option.html
  src/material-experimental/mdc-chips/chip-row.html
  src/material-experimental/mdc-chips/chip.html
  src/material-experimental/mdc-chips/chip.ts
  src/material-experimental/mdc-list/BUILD.bazel
  src/material-experimental/mdc-list/list-base.ts
  src/material-experimental/mdc-menu/BUILD.bazel
  src/material-experimental/mdc-menu/menu-item.html
  src/material-experimental/mdc-menu/menu-item.ts
  src/material-experimental/mdc-radio/BUILD.bazel
  src/material-experimental/mdc-radio/radio.html
  src/material-experimental/mdc-radio/radio.ts
  src/material-experimental/mdc-slide-toggle/BUILD.bazel
  src/material-experimental/mdc-slide-toggle/slide-toggle.html
  src/material-experimental/mdc-slide-toggle/slide-toggle.ts
Labels: cla: yes, P3, merge ready, target: major

#23414 refactor(material/core): update minimum required sass version and clean up workarounds
  package.json
  src/material-experimental/mdc-card/card.scss
  src/material-experimental/mdc-form-field/_form-field-density.scss
  src/material-experimental/mdc-form-field/_form-field-native-select.scss
  src/material-experimental/mdc-select/select.scss
  src/material-experimental/mdc-slide-toggle/slide-toggle.scss
  src/material/badge/_badge-theme.scss
  src/material/card/card.scss
  src/material/checkbox/checkbox.scss
  src/material/core/option/option.scss
  src/material/core/selection/pseudo-checkbox/pseudo-checkbox.scss
  src/material/core/style/_private.scss
  src/material/core/typography/_typography-utils.scss
  src/material/datepicker/calendar-body.scss
  src/material/datepicker/date-range-input.scss
  src/material/form-field/_form-field-fill-theme.scss
  src/material/form-field/_form-field-legacy-theme.scss
  src/material/form-field/_form-field-outline-theme.scss
  src/material/form-field/_form-field-theme.scss
  src/material/form-field/form-field-fill.scss
  src/material/form-field/form-field-input.scss
  src/material/form-field/form-field-outline.scss
  src/material/input/_input-theme.scss
  src/material/radio/radio.scss
  src/material/select/select.scss
  src/material/slide-toggle/slide-toggle.scss
  src/material/slider/slider.scss
  src/material/snack-bar/BUILD.bazel
  src/material/snack-bar/simple-snack-bar.scss
  src/material/stepper/_stepper-theme.scss
  src/material/stepper/stepper.scss
  src/material/tooltip/_tooltip-theme.scss
  yarn.lock
Labels: cla: yes, P2, merge ready, target: major, flag: breaking change

#23421 fix(cdk/testing): fix value stringification in harnesses
  src/cdk/testing/component-harness.ts
  src/cdk/testing/tests/cross-environment.spec.ts
Labels: cla: yes, merge ready, G, target: patch

#23450 fix(material/tabs): tab header border reset when parent has a background color
  src/material/tabs/_tabs-theme.scss
Labels: cla: yes, P3, merge ready, target: patch

#23399 refactor(material-luxon-adapter): clean up unsupported browser workarounds
  src/material-luxon-adapter/adapter/luxon-date-adapter.spec.ts
  src/material-luxon-adapter/adapter/luxon-date-adapter.ts
Labels: cla: yes, P3, merge ready, merge safe, target: major

#23247 docs(material/card): add more examples
  src/components-examples/material/card/BUILD.bazel
  src/components-examples/material/card/card-actions/card-actions-example.html
  src/components-examples/material/card/card-actions/card-actions-example.ts
  src/components-examples/material/card/card-footer/card-footer-example.css
  src/components-examples/material/card/card-footer/card-footer-example.html
  src/components-examples/material/card/card-footer/card-footer-example.ts
  src/components-examples/material/card/card-media-size/card-media-size-example.css
  src/components-examples/material/card/card-media-size/card-media-size-example.html
  src/components-examples/material/card/card-media-size/card-media-size-example.ts
  src/components-examples/material/card/card-subtitle/card-subtitle-example.css
  src/components-examples/material/card/card-subtitle/card-subtitle-example.html
  src/components-examples/material/card/card-subtitle/card-subtitle-example.ts
  src/components-examples/material/card/index.ts
Labels: cla: yes, P3, docs, merge ready, merge safe, target: patch

#23377 docs(cdk/stepper): change misleading documentation
  src/cdk/stepper/stepper.md
Labels: cla: yes, P3, docs, merge ready, merge safe, target: patch

#23460 build: group commits by package name in changelog
  .ng-dev/release.ts
Labels: cla: yes, merge ready, merge safe, target: patch

#23491 build: update to latest version of `rules_sass`
  WORKSPACE
  src/dev-app/mdc-select/BUILD.bazel
  src/dev-app/mdc-sidenav/BUILD.bazel
  src/dev-app/mdc-snack-bar/BUILD.bazel
  src/dev-app/table-scroll-container/BUILD.bazel
  src/material-experimental/column-resize/BUILD.bazel
  src/material-experimental/mdc-helpers/BUILD.bazel
  tools/defaults.bzl
  tools/npm_sass_library.bzl
Labels: cla: yes, merge ready, merge safe, target: patch

#23485 build: update to nodejs v16 and update rules_nodejs to v4 stable
  .circleci/config.yml
  .nvmrc
  WORKSPACE
  package.json
  src/cdk/testing/private/e2e/asserts.ts
  src/material-date-fns-adapter/BUILD.bazel
  src/material-date-fns-adapter/esbuild-amd.bzl
  tools/esbuild/BUILD.bazel
  tools/esbuild/esbuild-amd-config.mjs
  tools/esbuild/index.bzl
  yarn.lock
Labels: cla: yes, merge ready, merge safe, target: patch
