Repository angular/components, pull requests merged in 2021-11, with the labels that each got.

#23870 test(material/select): fix failing unit test
  src/material/select/select.spec.ts
Labels: cla: yes, P2, merge ready, merge safe, target: patch

#23873 build: update to final v13.0.0-rc.3 release-candidate of CLI and framework
  package.json
  yarn.lock
Labels: cla: yes, merge ready, merge safe, target: rc

#23864 build: fix error when dev app is deployed
  DEV_ENVIRONMENT.md
  src/dev-app/index.html
Labels: cla: yes, P3, merge ready, merge safe, target: rc

#23842 build: update firebase preview instance to internal one
  .github/workflows/deploy-dev-app.yml
Labels: cla: yes, merge ready, merge safe, target: patch

#23855 fix(material-experimental/mdc-tabs): update theming api
  package.json
  packages.bzl
  src/material-experimental/mdc-tabs/_tabs-theme.scss
  yarn.lock
Labels: cla: yes, merge ready, merge safe, target: rc

#23857 build: update dev-infra package and format mjs files
  .prettierrc
  integration/linker/link-packages-test.mjs
  integration/npm-packages-from-runfiles.mjs
  integration/ts-compat/helpers.mjs
  scripts/create-legacy-tests-bundle.mjs
  scripts/github/fetch-workflow-artifact.mjs
  tools/angular/create_linker_esbuild_plugin.mjs
  tools/angular/esbuild.config.mjs
  tools/esbuild/esbuild-amd-config.mjs
  tools/spec-bundling/esbuild.config-tmpl.mjs
Labels: cla: yes, P3, merge ready, merge safe, target: rc

#23839 build: cleanup unused dependencies
  package.json
  yarn.lock
Labels: cla: yes, merge ready, merge safe, target: rc, dev-app preview

#23830 ci: update to the latest version of commit-message-based-labels for github action
  .github/workflows/dev-infra.yml
Labels: cla: yes, merge ready, merge safe, target: rc

#23791 docs(a11y): fix typo
  src/cdk/a11y/_index.scss
Labels: cla: yes, docs, merge ready, merge safe, target: patch, commit message fixup, area: cdk/a11y

#23876 Bump version to "v13.0.0-rc.3" with changelog.
  CHANGELOG.md
  package.json
Labels: cla: yes, merge ready, merge safe, target: rc

#23877 docs: release notes for the v13.0.0-rc.3 release
  CHANGELOG.md
Labels: cla: yes, merge ready, merge safe, target: minor

#23874 build: update peer dependency ranges for v13 stable release
  packages.bzl
Labels: cla: yes, merge ready, merge safe, target: rc

#23886 docs: release notes for the v13.0.0 release
  CHANGELOG.md
Labels: cla: yes, merge ready, merge safe, target: minor

#23888 Bump version to "v13.1.0-next.0" with changelog.
  CHANGELOG.md
Labels: cla: yes, merge ready, merge safe, target: minor

#23883 build: update linker integration test to work with APF v13
  integration/linker/BUILD.bazel
  integration/linker/link-packages-test.mjs
  package.json
  yarn.lock
Labels: cla: yes, merge ready, merge safe, target: patch

#23812 build: use issue forms for issue creation
  .github/ISSUE_TEMPLATE/bug.md
  .github/ISSUE_TEMPLATE/bug.yml
  .github/ISSUE_TEMPLATE/config.yml
  .github/ISSUE_TEMPLATE/docs.md
  .github/ISSUE_TEMPLATE/docs.yml
  .github/ISSUE_TEMPLATE/feature.md
  .github/ISSUE_TEMPLATE/feature.yml
  .github/ISSUE_TEMPLATE/troubleshooting.md
  .github/ISSUE_TEMPLATE/troubleshooting.yml
Labels: cla: yes, merge ready, merge safe, target: patch

#23875 build: do not accidentally cache undesired files in github action
  .github/actions/yarn-install/action.yml
  .github/workflows/build-dev-app.yml
Labels: cla: yes, merge ready, merge safe, target: patch, dev-app preview

#23892 build: update to stable v13.0.0 Angular packages
  package.json
  yarn.lock
Labels: cla: yes, merge ready, merge safe, target: patch

#23898 docs: update readme for Q4 2021
  README.md
Labels: cla: yes, docs, merge ready, merge safe, target: patch

#23901 refactor: fix examples not recognizing webcontainer stackblitz instances
  src/components-examples/material/sidenav/sidenav-disable-close/sidenav-disable-close-example.ts
  src/components-examples/material/sidenav/sidenav-fixed/sidenav-fixed-example.ts
  src/components-examples/material/sidenav/sidenav-mode/sidenav-mode-example.ts
  src/components-examples/material/sidenav/sidenav-open-close/sidenav-open-close-example.ts
  src/components-examples/material/sidenav/sidenav-overview/sidenav-overview-example.ts
  src/components-examples/material/sidenav/sidenav-position/sidenav-position-example.ts
  src/components-examples/material/sidenav/sidenav-responsive/sidenav-responsive-example.ts
Labels: cla: yes, P2, merge ready, merge safe, target: patch

#23910 docs: add detailed breaking change note for Sass tilde change
  CHANGELOG.md
Labels: cla: yes, merge ready, merge safe, target: patch

#23899 build: remove unused code from legacy tooling and remove view-engine leftovers
  .clang-format
  build-config.js
  tools/BUILD.bazel
  tools/tslint-rules/requireLicenseBannerRule.ts
Labels: cla: yes, merge ready, merge safe, target: patch

#23722 fix(material/core): test environment check not picking up jest
  src/cdk/a11y/focus-monitor/focus-monitor.ts
  src/cdk/a11y/live-announcer/live-announcer.ts
  src/cdk/overlay/overlay-ref.ts
  src/cdk/platform/BUILD.bazel
  src/cdk/platform/features/test-environment.ts
  src/material-experimental/mdc-chips/chip-row.ts
  src/material-experimental/mdc-dialog/dialog-container.ts
  src/material-experimental/mdc-snack-bar/snack-bar-container.ts
  src/material/bottom-sheet/bottom-sheet-ref.ts
  src/material/dialog/dialog-ref.ts
  src/material/snack-bar/snack-bar-container.ts
  src/material/snack-bar/snack-bar-ref.ts
  src/material/tooltip/tooltip.ts
  src/tsconfig-legacy.json
  tools/public_api_guard/material/tooltip.md
Labels: cla: yes, P2, merge ready, target: patch

#23856 feat(google-maps): Getting google.maps.Map instance
  src/google-maps/google-map/google-map.spec.ts
  src/google-maps/google-map/google-map.ts
  tools/public_api_guard/google-maps/google-maps.md
Labels: cla: yes, P3, merge ready, target: minor

#23868 fix(material/chips): Declare that MatChipInput.inputElement is always defined
  src/material-experimental/mdc-chips/chip-input.ts
  src/material/chips/chip-input.ts
Labels: cla: yes, merge ready, target: patch

#23869 fix(material/form-field): update outline gap when prefix changes
  src/material/form-field/form-field.html
Labels: cla: yes, P3, merge ready, target: patch

#23879 refactor(multiple): clean up host decorator workarounds
  src/cdk-experimental/dialog/dialog-container.ts
  src/cdk-experimental/menu/menu-bar.ts
  src/cdk-experimental/menu/menu-item.ts
  src/cdk-experimental/menu/menu.ts
  src/cdk-experimental/popover-edit/lens-directives.ts
  src/cdk-experimental/popover-edit/table-directives.ts
  src/cdk/coercion/coercion.md
  src/cdk/stepper/stepper-button.ts
  src/cdk/text-field/autosize.ts
  src/cdk/tree/nested-node.ts
  src/cdk/tree/toggle.ts
  src/cdk/tree/tree.ts
  src/material-experimental/mdc-button/button-base.ts
  src/material-experimental/mdc-chips/chip.ts
  src/material-experimental/mdc-list/interactive-list-base.ts
  src/material-experimental/mdc-list/list-base.ts
  src/material/input/input.ts
  src/material/menu/menu-item.ts
  src/material/menu/menu-trigger.ts
  src/material/sidenav/drawer.ts
  src/material/tree/node.ts
  src/material/tree/tree.ts
  tools/public_api_guard/cdk/stepper.md
  tools/public_api_guard/cdk/tree.md
  tools/public_api_guard/material/menu.md
  tools/public_api_guard/material/sidenav.md
  tools/public_api_guard/material/tree.md
Labels: cla: yes, P3, merge ready, target: patch

#23924 fix(material/core): test environment check not picking up jest (#23722)
  src/cdk/a11y/focus-monitor/focus-monitor.ts
  src/cdk/a11y/live-announcer/live-announcer.ts
  src/cdk/overlay/overlay-ref.ts
  src/cdk/platform/BUILD.bazel
  src/cdk/platform/features/test-environment.ts
  src/cdk/tsconfig-tests.json
  src/material-experimental/mdc-chips/chip-row.ts
  src/material-experimental/mdc-dialog/dialog-container.ts
  src/material-experimental/mdc-snack-bar/snack-bar-container.ts
  src/material/bottom-sheet/bottom-sheet-ref.ts
  src/material/dialog/dialog-ref.ts
  src/material/snack-bar/snack-bar-container.ts
  src/material/snack-bar/snack-bar-ref.ts
  src/material/tooltip/tooltip.ts
  tools/public_api_guard/material/tooltip.md
Labels: cla: yes, merge ready, merge safe, target: lts

#23922 build: update karma to v6.3.8 which contains sourcemap generated-code fix
  package.json
  yarn.lock
Labels: cla: yes, merge ready, merge safe, target: patch

#23891 fix(material/slide-toggle): remove tabindex from host node
  src/material-experimental/mdc-slide-toggle/slide-toggle.spec.ts
  src/material-experimental/mdc-slide-toggle/slide-toggle.ts
  src/material/slide-toggle/slide-toggle.spec.ts
  src/material/slide-toggle/slide-toggle.ts
Labels: cla: yes, P2, a11y, merge ready, G, target: patch

#23828 fix(material/chips): add selected indication in high contrast mode
  src/material-experimental/mdc-chips/chip-option.ts
  src/material-experimental/mdc-chips/chips.scss
  src/material/chips/chips.scss
Labels: cla: yes, P3, a11y, merge ready, G, target: patch

#23735 fix(cdk/overlay): remove Optional decorator in ConnectedOverlayPositionChange constructor
  src/cdk/overlay/position/connected-position.ts
Labels: cla: yes, P3, merge ready, target: patch

#23942 Bump version to "v12.2.13" with changelog.
  CHANGELOG.md
  package.json
Labels: cla: yes, target: lts

#23944 build: update to latest @angular/dev-infra-private to address issues related to verifying environment
  package.json
  yarn.lock
Labels: cla: yes, merge ready, merge safe, target: patch, area: build

#23945 Revert "Bump version to "v12.2.13" with changelog."
  CHANGELOG.md
  package.json
Labels: cla: yes, merge ready, target: lts

#23946 Bump version to "v12.2.13" with changelog.
  CHANGELOG.md
  package.json
Labels: cla: yes, target: lts

#23947 docs: release notes for the v12.2.13 release
  CHANGELOG.md
Labels: cla: yes

#23951 fix(multiple): update to angular v13.0.1 to emit proper partial compilation output
  package.json
  yarn.lock
Labels: cla: yes, merge ready, merge safe, target: patch

#23956 Bump version to "v13.0.1" with changelog.
  CHANGELOG.md
  package.json
Labels: cla: yes, merge ready, target: patch

#23957 docs: release notes for the v13.0.1 release
  CHANGELOG.md
Labels: cla: yes, merge ready

#23959 Bump version to "v13.1.0-next.1" with changelog.
  CHANGELOG.md
  package.json
Labels: cla: yes, merge ready

#23906 feat(cdk/bidi): support `auto` direction value
  src/cdk/bidi/bidi.md
  src/cdk/bidi/dir.ts
  src/cdk/bidi/directionality.ts
  tools/public_api_guard/cdk/bidi.md
Labels: cla: yes, P2, merge ready, G, target: minor

#23714 feat(material/datepicker): Add aria-current="date" to current date
  src/material/datepicker/calendar-body.html
  src/material/datepicker/calendar-body.spec.ts
Labels: cla: yes, P2, a11y, merge ready, caretaker note, G, target: patch, commit message fixup

#23960 refactor(multiple): clean up more ViewEngine-specific code
  src/cdk-experimental/dialog/dialog-module.ts
  src/cdk/drag-drop/directives/drag.spec.ts
  src/cdk/portal/portal.md
  src/dev-app/main-module.ts
  src/material-experimental/column-resize/column-resize-module.ts
  src/material-experimental/mdc-button/fab.ts
  src/material-experimental/mdc-dialog/module.ts
  src/material-experimental/mdc-snack-bar/module.ts
  src/material-experimental/mdc-tooltip/module.ts
  src/material-experimental/selection/row-selection.ts
  src/material-experimental/selection/selection-toggle.ts
  src/material/bottom-sheet/bottom-sheet-module.ts
  src/material/bottom-sheet/bottom-sheet.md
  src/material/datepicker/date-range-input-parts.ts
  src/material/datepicker/datepicker-module.ts
  src/material/dialog/dialog-module.ts
  src/material/dialog/dialog.md
  src/material/snack-bar/snack-bar-module.ts
  src/material/tooltip/tooltip-module.ts
  src/material/tree/toggle.ts
  src/universal-app/kitchen-sink-mdc/kitchen-sink-mdc.ts
  src/universal-app/kitchen-sink/kitchen-sink.ts
  tools/public_api_guard/material/datepicker.md
  tools/public_api_guard/material/tree.md
Labels: cla: yes, P2, merge ready, target: patch

#23912 perf(multiple): don't emit fallbacks for CSS variables in experimental components
  src/material-experimental/mdc-helpers/_mdc-helpers.scss
  src/material-experimental/mdc-radio/radio.scss
  src/material-experimental/mdc-slide-toggle/slide-toggle.scss
  src/material-experimental/mdc-tabs/_tabs-common.scss
Labels: cla: yes, P2, merge ready, target: patch

#23759 fix(material/tabs): pagination sometimes incorrectly shown after zoom
  src/material-experimental/mdc-tabs/tab-header.html
  src/material-experimental/mdc-tabs/tab-header.ts
  src/material-experimental/mdc-tabs/tab-nav-bar/tab-nav-bar.html
  src/material-experimental/mdc-tabs/tab-nav-bar/tab-nav-bar.ts
  src/material/tabs/paginated-tab-header.ts
  src/material/tabs/tab-header.html
  src/material/tabs/tab-header.ts
  src/material/tabs/tab-nav-bar/tab-nav-bar.html
  src/material/tabs/tab-nav-bar/tab-nav-bar.ts
  tools/public_api_guard/material/tabs.md
Labels: cla: yes, P3, merge ready, target: patch

#23840 fix(material-experimental/mdc-list): don't override focus styles with hover
  src/material-experimental/mdc-list/_interactive-list-theme.scss
Labels: cla: yes, P3, merge ready, target: patch

#23902 docs(cdk/testing): expand JsDoc for sendKeys with limitations
  src/cdk/testing/test-element.ts
  src/cdk/testing/testbed/unit-test-element.ts
Labels: cla: yes, docs, merge ready, merge safe, target: patch, area: cdk/testing

#23933 build: enable angular strict template checking for IDE tsconfig
  tsconfig.json
Labels: cla: yes, merge ready, merge safe, target: patch

#23958 refactor(multiple): add non-null assertions first and last
  src/cdk/tree/tree.ts
  src/material-experimental/mdc-slider/slider.ts
  src/material/menu/menu.ts
Labels: cla: yes, merge ready, merge safe, target: patch

#23968 ci: remove `cla: yes` from required labels
  .github/angular-robot.yml
Labels: cla: yes, merge ready, merge safe, target: patch, area: build

#23925 build: fix source maps in dev-app due to missing source contents
  integration/size-test/index.bzl
  tools/esbuild/index.bzl
Labels: cla: yes, merge ready, merge safe, target: patch

#23861 build: update to stylelint 14
  .stylelintrc.json
  package.json
  tools/stylelint/no-ampersand-beyond-selector-start.ts
  tools/stylelint/no-concrete-rules.ts
  tools/stylelint/no-import.ts
  tools/stylelint/no-nested-mixin.ts
  tools/stylelint/no-prefixes/index.ts
  tools/stylelint/no-top-level-ampersand-in-mixin.ts
  tools/stylelint/no-unused-import.ts
  tools/stylelint/selector-no-deep.ts
  tools/stylelint/single-line-comment-only.ts
  tools/stylelint/theme-mixin-api.ts
  yarn.lock
Labels: cla: yes, P3, merge ready, merge safe, target: patch

#23974 Bump version to "v13.0.2" with changelog.
  CHANGELOG.md
  package.json
Labels: cla: yes

#23975 Revert "Bump version to "v13.0.2" with changelog."
  CHANGELOG.md
  package.json
Labels: cla: yes

#23976 Bump version to "v13.0.2" with changelog.
  CHANGELOG.md
  package.json
Labels: cla: yes, merge ready, merge safe, target: patch

#23977 Revert "Bump version to "v13.0.2" with changelog."
  CHANGELOG.md
  package.json
Labels: cla: yes

#23978 Bump version to "v13.0.2" with changelog.
  CHANGELOG.md
  package.json
Labels: cla: yes, merge ready, target: patch

#23979 docs: release notes for the v13.0.2 release
  CHANGELOG.md
Labels: cla: yes, merge ready, target: minor

#23980 Bump version to "v13.1.0-next.2" with changelog.
  CHANGELOG.md
  package.json
Labels: cla: yes, merge ready, target: minor

#23973 build: update bazel setup to latest dev-infra and rules_nodejs version
  .github/workflows/dev-infra.yml
  .github/workflows/lock-closed.yml
  WORKSPACE
  package.json
  scripts/create-legacy-tests-bundle.mjs
  src/cdk/testing/tests/webdriver-test.bzl
  src/dev-app/BUILD.bazel
  src/e2e-app/BUILD.bazel
  src/universal-app/BUILD.bazel
  tools/angular/BUILD.bazel
  tools/angular/create_linker_esbuild_plugin.mjs
  tools/angular/esbuild.config.mjs
  tools/angular/index.bzl
  tools/defaults.bzl
  tools/esbuild/BUILD.bazel
  tools/esbuild/devmode-output.bzl
  tools/esbuild/esbuild-amd-config.mjs
  tools/esbuild/index.bzl
  tools/spec-bundling/BUILD.bazel
  tools/spec-bundling/esbuild.config-tmpl.mjs
  tools/spec-bundling/index.bzl
  yarn.lock
Labels: cla: yes, merge ready, merge safe, target: minor

#23969 perf(material/core): tree shake sanity checks
  src/material/core/common-behaviors/common-module.ts
  tools/public_api_guard/material/core.md
Labels: cla: yes, P3, merge ready, target: patch

#23966 fix(cdk/drag-drop): remove boundary error
  src/cdk/drag-drop/directives/drag.ts
Labels: cla: yes, merge ready, P4, target: patch

#23965 perf(material/bottom-sheet): do not run change detection when focusing element
  src/material/bottom-sheet/bottom-sheet-container.ts
Labels: cla: yes, P3, merge ready, target: patch

#23999 refactor(material-experimental/mdc-slider): clean up leftover deprecated function usage
  src/material-experimental/mdc-slider/_slider-theme.scss
  src/material/core/theming/_theming.scss
Labels: cla: yes, merge ready, merge safe, P4, target: patch

#23997 docs: update commit message guidelines
  CONTRIBUTING.md
Labels: cla: yes, merge ready, merge safe, target: patch

#23990 build: update bazel setup to latest dev-infra and rules_nodejs version [patch port]
  .github/workflows/dev-infra.yml
  .github/workflows/lock-closed.yml
  WORKSPACE
  package.json
  scripts/create-legacy-tests-bundle.mjs
  src/cdk/testing/tests/webdriver-test.bzl
  src/dev-app/BUILD.bazel
  src/e2e-app/BUILD.bazel
  src/universal-app/BUILD.bazel
  tools/angular/BUILD.bazel
  tools/angular/create_linker_esbuild_plugin.mjs
  tools/angular/esbuild.config.mjs
  tools/angular/index.bzl
  tools/defaults.bzl
  tools/esbuild/BUILD.bazel
  tools/esbuild/devmode-output.bzl
  tools/esbuild/esbuild-amd-config.mjs
  tools/esbuild/index.bzl
  tools/spec-bundling/BUILD.bazel
  tools/spec-bundling/esbuild.config-tmpl.mjs
  tools/spec-bundling/index.bzl
  yarn.lock
Labels: cla: yes, merge ready, merge safe, target: patch

#23994 fix(multiple): some experimental components not cleaned up completely
  src/cdk-experimental/menu/menu.ts
  src/material-experimental/mdc-form-field/form-field.ts
  src/material-experimental/mdc-list/list-option.ts
  src/material-experimental/mdc-list/selection-list.ts
Labels: cla: yes, P3, merge ready, target: patch

#23967 perf(cdk/a11y): tree-shake warnings in production
  src/cdk/a11y/focus-trap/focus-trap.ts
Labels: cla: yes, perf, merge ready, target: patch
