Repository angular/components, pull requests merged in 2021-04, with the labels that each got.

#22363 build: don't require all reviewers to approve PRs
  .github/angular-robot.yml
Labels: P2, cla: yes, merge ready, merge safe, target: patch

#22366 docs(material/theming): rewrite typography guide for `@use`
  guides/typography.md
Labels: P2, cla: yes, docs, merge ready, merge safe, target: major

#22314 fix(cdk/text-field): autosize text areas using the placeholder
  scripts/check-mdc-tests-config.ts
  src/cdk/text-field/autosize.spec.ts
  src/cdk/text-field/autosize.ts
  src/material/input/input.spec.ts
  tools/public_api_guard/cdk/text-field.d.ts
Labels: G, P2, area: cdk/text-field, cla: yes, merge ready, target: major

#22139 feat(material/stepper): allow for orientation to be changed dynamically
  src/cdk/stepper/stepper.ts
  src/dev-app/stepper/stepper-demo.html
  src/dev-app/stepper/stepper-demo.ts
  src/material/stepper/public-api.ts
  src/material/stepper/stepper-animations.ts
  src/material/stepper/stepper-horizontal.html
  src/material/stepper/stepper-module.ts
  src/material/stepper/stepper-vertical.html
  src/material/stepper/stepper.html
  src/material/stepper/stepper.spec.ts
  src/material/stepper/stepper.ts
  tools/public_api_guard/cdk/stepper.d.ts
  tools/public_api_guard/material/stepper.d.ts
Labels: P2, caretaker note, cla: yes, merge ready, target: major

#22201 fix(material/progress-bar): fix screenreader not reading aria-label
  src/material-experimental/mdc-progress-bar/progress-bar.ts
  src/material-experimental/mdc-progress-spinner/progress-spinner.ts
  src/material/progress-bar/progress-bar.ts
  src/material/progress-spinner/progress-spinner.ts
Labels: P2, a11y, cla: yes, merge ready, target: patch

#22347 feat(cdk/drag-drop): added dropPoint to dropped event
  src/cdk/drag-drop/directives/drag.spec.ts
  src/cdk/drag-drop/directives/drag.ts
  src/cdk/drag-drop/directives/drop-list.ts
  src/cdk/drag-drop/drag-events.ts
  src/cdk/drag-drop/drag-ref.ts
  src/cdk/drag-drop/drop-list-ref.ts
  tools/public_api_guard/cdk/drag-drop.d.ts
Labels: P3, cla: yes, merge ready, target: minor

#22352 fix(material/datepicker): toggle icon not visible in high contrast mode on Chromium browsers
  src/material/datepicker/BUILD.bazel
  src/material/datepicker/datepicker-toggle.scss
Labels: P3, a11y, cla: yes, merge ready, target: patch

#22372 fix(cdk/portal): not marked as attached when going through specific portal methods
  src/cdk/portal/dom-portal-outlet.ts
  src/cdk/portal/portal-directives.ts
  src/cdk/portal/portal.spec.ts
Labels: P3, cla: yes, merge ready, target: patch

#20290 build: enforce consistent readonly array type
  src/cdk-experimental/popover-edit/popover-edit.spec.ts
  src/cdk-experimental/selection/selection.ts
  src/cdk/collections/array-data-source.ts
  src/cdk/collections/data-source.ts
  src/cdk/drag-drop/drop-list-ref.ts
  src/cdk/drag-drop/parent-position-tracker.ts
  src/cdk/schematics/update-tool/utils/decorators.ts
  src/cdk/scrolling/virtual-for-of.ts
  src/cdk/scrolling/virtual-scroll-repeater.ts
  src/cdk/table/sticky-position-listener.ts
  src/cdk/table/table.ts
  src/cdk/tree/tree.ts
  src/components-examples/material/chips/chips-input/chips-input-example.ts
  src/material-experimental/column-resize/column-resize.spec.ts
  src/material-experimental/popover-edit/popover-edit.spec.ts
  src/material/tooltip/tooltip.ts
  tools/public_api_guard/cdk/collections.d.ts
  tools/public_api_guard/cdk/drag-drop.d.ts
  tools/public_api_guard/cdk/scrolling.d.ts
  tools/public_api_guard/cdk/table.d.ts
  tools/public_api_guard/cdk/tree.d.ts
  tslint.json
Labels: cla: yes, merge ready, target: major

#22357 feat(google-maps): add icon input to marker
  src/google-maps/map-marker/map-marker.spec.ts
  src/google-maps/map-marker/map-marker.ts
  tools/public_api_guard/google-maps/google-maps.d.ts
Labels: P4, cla: yes, merge ready, target: minor

#22353 fix(material-experimental/mdc-form-field): set explicit text-align
  src/material-experimental/mdc-form-field/form-field.scss
Labels: P3, cla: yes, merge ready, target: minor

#21376 fix(material-experimental/mdc-list): add high contrast mode treatment
  src/material-experimental/mdc-list/list.scss
Labels: P3, a11y, cla: yes, merge ready, target: minor

#22379 test(cdk/testing): enable webdriver tests on CI
  src/cdk/testing/BUILD.bazel
  src/cdk/testing/tests/BUILD.bazel
  src/cdk/testing/tests/webdriver-test.bzl
  src/cdk/testing/tests/webdriver-test.sh
  src/cdk/testing/tests/webdriver.e2e.spec.ts
  src/cdk/testing/webdriver/framework-stabilizers.d.ts
  src/cdk/testing/webdriver/webdriver-harness-environment.ts
  tools/public_api_guard/cdk/testing/webdriver.d.ts
  tools/server-test/BUILD.bazel
  tools/server-test/index.bzl
  tools/server-test/test-runner.ts
Labels: cla: yes, merge ready, merge safe, target: feature branch

#21833 refactor(material/sort): remove deprecated APIs for v12
  src/material/sort/sort-header-intl.ts
  src/material/sort/sort-header.ts
  src/material/sort/testing/sort-header-harness.ts
  tools/public_api_guard/material/sort.d.ts
  tools/public_api_guard/material/sort/testing.d.ts
Labels: P2, cla: yes, merge ready, target: major

#19848 fix(material/sidenav): mark sidenav content as scrollable
  src/material/sidenav/drawer.html
  src/material/sidenav/drawer.spec.ts
Labels: P3, cla: yes, merge ready, target: patch

#22387 fix(material-experimental/mdc-paginator): rename module file
  src/material-experimental/mdc-paginator/module.ts
  src/material-experimental/mdc-paginator/public-api.ts
Labels: P3, cla: yes, merge ready, target: patch

#20287 fix(expansion): enforce stricter types for inputs
  src/cdk/accordion/accordion-item.ts
  src/material/expansion/expansion-panel-header.ts
  src/material/expansion/expansion-panel.ts
  tools/public_api_guard/cdk/accordion.d.ts
  tools/public_api_guard/material/expansion.d.ts
Labels: caretaker note, cla: yes, merge ready, target: major

#22405 build: bump MDC canary version and fix snapshot check
  package.json
  packages.bzl
  src/material-experimental/mdc-form-field/BUILD.bazel
  yarn.lock
Labels: P3, cla: yes, merge ready, merge safe, target: minor

#22390 build: bump Angular dependencies and drop benchpress
  .circleci/config.yml
  package.json
  tools/public_api_guard/cdk/a11y.d.ts
  tools/public_api_guard/cdk/accordion.d.ts
  tools/public_api_guard/cdk/bidi.d.ts
  tools/public_api_guard/cdk/clipboard.d.ts
  tools/public_api_guard/cdk/collections.d.ts
  tools/public_api_guard/cdk/drag-drop.d.ts
  tools/public_api_guard/cdk/layout.d.ts
  tools/public_api_guard/cdk/observers.d.ts
  tools/public_api_guard/cdk/overlay.d.ts
  tools/public_api_guard/cdk/platform.d.ts
  tools/public_api_guard/cdk/portal.d.ts
  tools/public_api_guard/cdk/scrolling.d.ts
  tools/public_api_guard/cdk/stepper.d.ts
  tools/public_api_guard/cdk/table.d.ts
  tools/public_api_guard/cdk/text-field.d.ts
  tools/public_api_guard/cdk/tree.d.ts
  tools/public_api_guard/google-maps/google-maps.d.ts
  tools/public_api_guard/material/autocomplete.d.ts
  tools/public_api_guard/material/badge.d.ts
  tools/public_api_guard/material/bottom-sheet.d.ts
  tools/public_api_guard/material/button-toggle.d.ts
  tools/public_api_guard/material/button.d.ts
  tools/public_api_guard/material/card.d.ts
  tools/public_api_guard/material/checkbox.d.ts
  tools/public_api_guard/material/chips.d.ts
  tools/public_api_guard/material/core.d.ts
  tools/public_api_guard/material/datepicker.d.ts
  tools/public_api_guard/material/dialog.d.ts
  tools/public_api_guard/material/divider.d.ts
  tools/public_api_guard/material/expansion.d.ts
  tools/public_api_guard/material/form-field.d.ts
  tools/public_api_guard/material/grid-list.d.ts
  tools/public_api_guard/material/icon.d.ts
  tools/public_api_guard/material/icon/testing.d.ts
  tools/public_api_guard/material/input.d.ts
  tools/public_api_guard/material/list.d.ts
  tools/public_api_guard/material/menu.d.ts
  tools/public_api_guard/material/paginator.d.ts
  tools/public_api_guard/material/progress-bar.d.ts
  tools/public_api_guard/material/progress-spinner.d.ts
  tools/public_api_guard/material/radio.d.ts
  tools/public_api_guard/material/select.d.ts
  tools/public_api_guard/material/sidenav.d.ts
  tools/public_api_guard/material/slide-toggle.d.ts
  tools/public_api_guard/material/slider.d.ts
  tools/public_api_guard/material/snack-bar.d.ts
  tools/public_api_guard/material/sort.d.ts
  tools/public_api_guard/material/stepper.d.ts
  tools/public_api_guard/material/table.d.ts
  tools/public_api_guard/material/tabs.d.ts
  tools/public_api_guard/material/toolbar.d.ts
  tools/public_api_guard/material/tooltip.d.ts
  tools/public_api_guard/material/tree.d.ts
  tools/public_api_guard/youtube-player/youtube-player.d.ts
  yarn.lock
Labels: P3, cla: yes, merge ready, merge safe, target: major

#22391 fix(material/radio): ripple not positioned correctly inside parent with centered text
  src/material/radio/radio.scss
Labels: P3, cla: yes, merge ready, target: patch

#22396 fix(material-experimental/mdc-list): align ripple timings with MDC
  src/material-experimental/mdc-list/BUILD.bazel
  src/material-experimental/mdc-list/list-base.ts
  src/material-experimental/mdc-list/testing/BUILD.bazel
Labels: P3, cla: yes, merge ready, target: patch

#22415 build: fix broken import paths
  src/material-experimental/mdc-list/list.scss
  src/material/datepicker/datepicker-toggle.scss
Labels: cla: yes, merge ready, target: major

#22418 fix(material/datepicker): fix high contrast mixin name
  src/material/datepicker/datepicker-toggle.scss
Labels: cla: yes, merge ready, target: patch

#22420 release: bump version to 11.2.8 w/ changelog
  CHANGELOG.md
  package.json
Labels: cla: yes, merge ready, merge safe, target: patch

#22425 release: bump version to 12.0.0-next.6 w/ changelog
  CHANGELOG.md
  package.json
Labels: cla: yes, merge ready, merge safe, target: major

#22410 feat(cdk/testing): create a webdriver harness environment
  package.json
  rollup-globals.bzl
  src/cdk/config.bzl
  src/cdk/testing/BUILD.bazel
  src/cdk/testing/tests/BUILD.bazel
  src/cdk/testing/tests/kagekiri.spec.d.ts
  src/cdk/testing/tests/protractor.e2e.spec.ts
  src/cdk/testing/tests/webdriver-test.bzl
  src/cdk/testing/tests/webdriver.e2e.spec.ts
  src/cdk/testing/webdriver/BUILD.bazel
  src/cdk/testing/webdriver/index.ts
  src/cdk/testing/webdriver/public-api.ts
  src/cdk/testing/webdriver/webdriver-element.ts
  src/cdk/testing/webdriver/webdriver-harness-environment.ts
  src/cdk/testing/webdriver/webdriver-keys.ts
  src/cdk/tsconfig-tests.json
  tools/public_api_guard/cdk/testing/webdriver.d.ts
  tools/public_api_guard/generate-guard-tests.bzl
  tools/server-test/BUILD.bazel
  tools/server-test/index.bzl
  tools/server-test/test-runner.ts
  yarn.lock
Labels: P2, cla: yes, merge ready, target: major

#22424 build: only run snapshot tests against main branch
  .circleci/config.yml
Labels: P3, cla: yes, merge ready, merge safe, target: patch

#22412 docs: add missing standards for building components
  CODING_STANDARDS.md
Labels: cla: yes, docs, merge ready, merge safe, target: patch

#22402 build: add commit message scope for multiple components
  .ng-dev/commit-message.ts
Labels: P4, cla: yes, merge ready, merge safe, target: patch

#16941 refactor(form-field): remove unnecessary bindings
  src/material/form-field/form-field.ts
Labels: P4, cla: yes, merge ready, target: patch

#22340 fix(material/tree): not rendering initial data from flat data source
  src/material/tree/data-source/flat-data-source.ts
  src/material/tree/data-source/nested-data-source.ts
  src/material/tree/tree.spec.ts
  tools/public_api_guard/material/tree.d.ts
Labels: P3, cla: yes, merge ready, target: minor

#22108 fix(material-experimental/mdc-select): correct some differences between
  src/material-experimental/mdc-form-field/_form-field-native-select.scss
  src/material-experimental/mdc-select/select.scss
Labels: P2, cla: yes, merge ready, target: minor

#22436 fix(material/schematics): switch custom theme schematic to `@use`
  src/material/schematics/ng-add/index.spec.ts
  src/material/schematics/ng-add/theming/create-custom-theme.ts
Labels: P2, cla: yes, merge ready, merge safe, target: major

#22374 docs(material/theming): document strong focus indicators
  guides/theming.md
Labels: P2, cla: yes, docs, merge ready, merge safe, target: major

#22439 build: local live reload not working on IE
  package.json
  yarn.lock
Labels: P3, cla: yes, merge ready, merge safe, target: minor

#22322 docs(material/snack-bar): Fix typo in snackbar jsdoc.
  src/material/snack-bar/snack-bar.ts
Labels: G, cla: yes, merge ready, merge safe, target: patch

#22423 build: add workaround to support RBE on macOS and windows
  WORKSPACE
  tools/BUILD.bazel
  tools/rbe_cross_platform_workaround.patch
Labels: area: build, cla: yes, merge ready, merge safe, target: patch

#22445 feat(material-experimental/mdc-slider): rebuild the mdc-slider demo
  src/dev-app/mdc-slider/mdc-slider-demo.html
  src/dev-app/mdc-slider/mdc-slider-demo.ts
  src/material-experimental/mdc-slider/slider.ts
Labels: cla: yes, target: feature branch

#21935 refactor(material/theming): normalize config in all typography mixins for mdc components
  src/dev-app/theme.scss
  src/material-experimental/mdc-autocomplete/_autocomplete-theme.scss
  src/material-experimental/mdc-button/_button-theme.scss
  src/material-experimental/mdc-card/_card-theme.scss
  src/material-experimental/mdc-checkbox/_checkbox-theme.scss
  src/material-experimental/mdc-chips/_chips-theme.scss
  src/material-experimental/mdc-core/option/_optgroup-theme.scss
  src/material-experimental/mdc-core/option/_option-theme.scss
  src/material-experimental/mdc-dialog/_dialog-theme.scss
  src/material-experimental/mdc-form-field/_form-field-theme.scss
  src/material-experimental/mdc-helpers/_mdc-helpers.scss
  src/material-experimental/mdc-input/_input-theme.scss
  src/material-experimental/mdc-list/_list-theme.scss
  src/material-experimental/mdc-menu/_menu-theme.scss
  src/material-experimental/mdc-paginator/_paginator-theme.scss
  src/material-experimental/mdc-radio/_radio-theme.scss
  src/material-experimental/mdc-select/_select-theme.scss
  src/material-experimental/mdc-slide-toggle/_slide-toggle-theme.scss
  src/material-experimental/mdc-slider/_slider-theme.scss
  src/material-experimental/mdc-snack-bar/_snack-bar-theme.scss
  src/material-experimental/mdc-table/_table-theme.scss
  src/material-experimental/mdc-tabs/_tabs-theme.scss
  src/material-experimental/mdc-theming/prebuilt/indigo-pink.scss
  src/material-experimental/mdc-tooltip/_tooltip-theme.scss
  src/material/core/typography/_typography.scss
  tools/stylelint/theme-mixin-api.ts
Labels: P2, cla: yes, merge ready, target: minor

#22437 docs(cdk/testing): copy over doc comments from base class to subclasses
  src/cdk/testing/protractor/protractor-element.ts
  src/cdk/testing/protractor/protractor-harness-environment.ts
  src/cdk/testing/test-element.ts
  src/cdk/testing/testbed/testbed-harness-environment.ts
  src/cdk/testing/testbed/unit-test-element.ts
  src/cdk/testing/webdriver/webdriver-element.ts
  src/cdk/testing/webdriver/webdriver-harness-environment.ts
  tools/public_api_guard/cdk/testing/protractor.d.ts
  tools/public_api_guard/cdk/testing/testbed.d.ts
  tools/public_api_guard/cdk/testing/webdriver.d.ts
Labels: cla: yes, merge ready, target: major

#22459 refactor: update `$schema` and `id` keyword
  src/cdk/schematics/ng-add/schema.json
  src/cdk/schematics/ng-generate/drag-drop/schema.json
  src/material/schematics/ng-add/schema.json
  src/material/schematics/ng-generate/address-form/schema.json
  src/material/schematics/ng-generate/dashboard/schema.json
  src/material/schematics/ng-generate/navigation/schema.json
  src/material/schematics/ng-generate/table/schema.json
  src/material/schematics/ng-generate/theming-api/schema.json
  src/material/schematics/ng-generate/tree/schema.json
Labels: area: ng-generate, cla: yes, merge ready, merge safe, target: major

#22462 build: fix stylelint failure
  src/material-experimental/mdc-theming/prebuilt/indigo-pink.scss
Labels: P3, cla: yes, merge ready, merge safe, target: major

#22438 fix(material/schematics): don't drop imports in files that do not use theming APIs
  src/material/schematics/ng-generate/theming-api/index.spec.ts
  src/material/schematics/ng-generate/theming-api/migration.ts
Labels: P2, cla: yes, merge ready, merge safe, target: major

#22463 test(material-experimental/mdc-slider): create e2e tests
  src/e2e-app/mdc-slider/mdc-slider-e2e.ts
  src/material-experimental/mdc-slider/BUILD.bazel
  src/material-experimental/mdc-slider/slider.e2e.spec.ts
Labels: cla: yes, target: feature branch

#22426 fix(material/core): expose mixin mentioned in the elevation guide
  guides/elevation.md
  src/material/_index.scss
  src/material/button/_button-base.scss
  src/material/card/card.scss
  src/material/checkbox/checkbox.scss
  src/material/chips/chips.scss
  src/material/core/style/_elevation.import.scss
  src/material/core/style/_elevation.scss
  src/material/expansion/expansion-panel.scss
  src/material/schematics/ng-generate/theming-api/migration.ts
Labels: P2, caretaker note, cla: yes, merge ready, target: major

#22376 fix(material/list): dispatching model change event multiple times in single selection mode
  src/material-experimental/mdc-list/list-option.ts
  src/material-experimental/mdc-list/selection-list.spec.ts
  src/material/list/selection-list.spec.ts
  src/material/list/selection-list.ts
Labels: P3, cla: yes, merge ready, target: patch

#22395 fix(cdk/testing): unable to assign value to number inputs using sendKeys
  src/cdk/keycodes/keycodes.ts
  src/cdk/testing/testbed/fake-events/type-in-element.ts
  src/cdk/testing/tests/cross-environment.spec.ts
  src/cdk/testing/tests/harnesses/main-component-harness.ts
  src/cdk/testing/tests/test-components-module.ts
  src/cdk/testing/tests/test-main-component.html
  src/cdk/testing/tests/test-main-component.ts
  tools/public_api_guard/cdk/keycodes.d.ts
Labels: P3, cla: yes, merge ready, target: patch

#22397 feat(material-experimental/mdc-core): set up MDC-based elevation
  src/material-experimental/_index.scss
  src/material-experimental/mdc-core/_core-theme.scss
  src/material-experimental/mdc-core/_elevation.scss
Labels: P3, cla: yes, merge ready, target: minor

#22400 feat(cdk/stepper): emit event when the user interacts with a step
  src/cdk/stepper/stepper.ts
  src/material/stepper/stepper.spec.ts
  tools/public_api_guard/cdk/stepper.d.ts
Labels: P3, cla: yes, merge ready, target: minor

#22429 fix(material-experimental/mdc-progress-spinner): fix aria-valuenow
  src/material-experimental/mdc-progress-spinner/progress-spinner.spec.ts
  src/material-experimental/mdc-progress-spinner/progress-spinner.ts
Labels: P3, a11y, cla: yes, merge ready, target: patch

#22442 fix(material/tabs): pagination not updating on resize
  src/material/tabs/paginated-tab-header.ts
Labels: P3, cla: yes, merge ready, target: patch

#22460 fix(cdk/testing): prevent duplicate subscription
  src/cdk/testing/change-detection.ts
Labels: cla: yes, merge ready, target: patch

#22471 build: add peer dependency to rxjs
  packages.bzl
  src/cdk/package.json
  src/google-maps/package.json
  src/material/package.json
  src/youtube-player/package.json
Labels: P3, cla: yes, merge ready, merge safe, target: major

#22422 fix(cdk/drag-drop): preserve initial transform inside drop list
  src/cdk/drag-drop/directives/drag.spec.ts
  src/cdk/drag-drop/drag-ref.ts
  src/cdk/drag-drop/drag-styling.ts
  src/cdk/drag-drop/drop-list-ref.ts
Labels: P3, cla: yes, merge ready, target: minor

#22473 build: clean up leftover debug log
  src/material-experimental/mdc-core/_elevation.scss
Labels: P3, cla: yes, merge ready, merge safe, target: minor

#22470 test(material-experimental/mdc-slider): add two-way binding unit tests
  src/material-experimental/mdc-slider/slider.spec.ts
  src/material-experimental/mdc-slider/slider.ts
Labels: cla: yes, merge safe, target: feature branch

#22465 docs(material/theming): rewrite theming-your-components guide
  guides/theming-your-components.md
  src/material/_index.scss
Labels: P2, area: theming, cla: yes, docs, merge ready, merge safe, target: major

#22371 feat(cdk/a11y): Add a new InputModalityDetector service to detect the user's current input modality.
  .github/CODEOWNERS
  src/cdk/a11y/focus-monitor/focus-monitor.spec.ts
  src/cdk/a11y/focus-monitor/focus-monitor.ts
  src/cdk/a11y/input-modality/input-modality-detector.spec.ts
  src/cdk/a11y/input-modality/input-modality-detector.ts
  src/cdk/a11y/public-api.ts
  src/dev-app/BUILD.bazel
  src/dev-app/dev-app/dev-app-layout.ts
  src/dev-app/dev-app/routes.ts
  src/dev-app/input-modality/BUILD.bazel
  src/dev-app/input-modality/input-modality-detector-demo-module.ts
  src/dev-app/input-modality/input-modality-detector-demo.html
  src/dev-app/input-modality/input-modality-detector-demo.ts
  tools/public_api_guard/cdk/a11y.d.ts
Labels: G, a11y, area: cdk/a11y, cla: yes, feature, merge ready, merge safe, target: feature branch

#22474 test(material-experimental/mdc-slider): add ngModel unit tests
  src/material-experimental/mdc-slider/slider.spec.ts
Labels: cla: yes, merge ready, target: feature branch

#22480 release: bump version to 11.2.9 w/ changelog
  CHANGELOG.md
  package.json
Labels: cla: yes, merge ready, merge safe, target: patch

#22478 test(material-experimental/mdc-slider): add change handler tests
  src/material-experimental/mdc-slider/slider.spec.ts
Labels: cla: yes, target: feature branch

#22483 release: bump version to 12.0.0-next.7 w/ changelog
  CHANGELOG.md
  package.json
Labels: cla: yes, merge ready, merge safe, target: major

#22484 release: update version to 12.1.0-next.0
  package.json
Labels: cla: yes

#22481 test(material-experimental/mdc-slider): add input handler tests
  src/material-experimental/mdc-slider/slider.e2e.spec.ts
  src/material-experimental/mdc-slider/slider.spec.ts
Labels: cla: yes, target: feature branch

#22485 fix(material/snack-bar): clear timeout upon dismiss with action
  src/material-experimental/mdc-snack-bar/snack-bar.spec.ts
  src/material/snack-bar/snack-bar-ref.ts
  src/material/snack-bar/snack-bar.spec.ts
Labels: P3, cla: yes, merge ready, target: patch

#21912 feat(material/tabs): allow for content tabindex to be customized
  src/material-experimental/mdc-tabs/tab-body.scss
  src/material-experimental/mdc-tabs/tab-group.html
  src/material-experimental/mdc-tabs/tab-group.spec.ts
  src/material/tabs/tab-config.ts
  src/material/tabs/tab-group.html
  src/material/tabs/tab-group.scss
  src/material/tabs/tab-group.spec.ts
  src/material/tabs/tab-group.ts
  tools/public_api_guard/material/tabs.d.ts
Labels: P3, a11y, cla: yes, merge ready, target: minor

#22378 refactor(material/core): clean up prefixes from internal Sass symbols
  src/cdk/a11y/_index.scss
  src/cdk/scrolling/virtual-scroll-viewport.scss
  src/cdk/text-field/_index.scss
  src/material-experimental/mdc-button/_button-theme.scss
  src/material-experimental/mdc-form-field/_form-field-density.scss
  src/material-experimental/mdc-form-field/_form-field-theme.scss
  src/material-experimental/mdc-helpers/_focus-indicators-theme.scss
  src/material-experimental/mdc-progress-bar/_progress-bar-theme.scss
  src/material-experimental/mdc-progress-spinner/_progress-spinner-theme.scss
  src/material-experimental/mdc-tabs/_tabs-theme.scss
  src/material/autocomplete/_autocomplete-theme.scss
  src/material/badge/_badge-theme.scss
  src/material/bottom-sheet/_bottom-sheet-theme.scss
  src/material/bottom-sheet/bottom-sheet-container.scss
  src/material/button/_button-theme.scss
  src/material/card/_card-theme.scss
  src/material/checkbox/_checkbox-theme.scss
  src/material/checkbox/checkbox.scss
  src/material/chips/_chips-theme.scss
  src/material/core/_core.scss
  src/material/core/density/private/_compatibility.scss
  src/material/core/focus-indicators/_focus-indicators-theme.scss
  src/material/core/option/_optgroup-theme.scss
  src/material/core/option/_option-theme.scss
  src/material/core/selection/pseudo-checkbox/_pseudo-checkbox-theme.scss
  src/material/core/selection/pseudo-checkbox/pseudo-checkbox.scss
  src/material/core/theming/_theming.scss
  src/material/datepicker/_datepicker-theme.scss
  src/material/datepicker/calendar-body.scss
  src/material/datepicker/date-range-input.scss
  src/material/dialog/_dialog-theme.scss
  src/material/divider/_divider-theme.scss
  src/material/form-field/_form-field-fill-theme.scss
  src/material/form-field/_form-field-legacy-theme.scss
  src/material/form-field/_form-field-outline-theme.scss
  src/material/form-field/_form-field-theme.scss
  src/material/grid-list/_grid-list-theme.scss
  src/material/icon/_icon-theme.scss
  src/material/input/_input-theme.scss
  src/material/list/_list-theme.scss
  src/material/menu/_menu-theme.scss
  src/material/progress-bar/_progress-bar-theme.scss
  src/material/progress-spinner/_progress-spinner-theme.scss
  src/material/progress-spinner/progress-spinner.scss
  src/material/radio/_radio-theme.scss
  src/material/select/_select-theme.scss
  src/material/sidenav/_sidenav-theme.scss
  src/material/slide-toggle/_slide-toggle-theme.scss
  src/material/slider/_slider-theme.scss
  src/material/snack-bar/_snack-bar-theme.scss
  src/material/sort/_sort-theme.scss
  src/material/table/_table-theme.scss
  src/material/tabs/_tabs-theme.scss
  src/material/toolbar/_toolbar-theme.scss
  src/material/tooltip/_tooltip-theme.scss
Labels: P2, cla: yes, merge ready, target: rc

#22482 build: some public API docs missing descriptions
  tools/dgeni/common/dgeni-definitions.ts
  tools/dgeni/templates/method.template.html
  tools/dgeni/templates/property.template.html
Labels: P2, cla: yes, merge ready, merge safe, target: patch

#22490 feat(google-maps): add visible input to marker
  src/google-maps/map-marker/map-marker.spec.ts
  src/google-maps/map-marker/map-marker.ts
  tools/public_api_guard/google-maps/google-maps.d.ts
Labels: P4, cla: yes, merge ready, target: minor

#22447 fix(material-experimental/mdc-list): add selected indication in high contrast mode
  src/material-experimental/mdc-list/list-option.scss
Labels: P3, a11y, cla: yes, merge ready, target: minor

#22385 fix(material/paginator): button icons blending in with background in high contrast mode on Chromium browsers
  src/material-experimental/mdc-paginator/paginator.scss
  src/material/paginator/BUILD.bazel
  src/material/paginator/paginator.scss
Labels: P3, a11y, cla: yes, merge ready, target: minor

#22435 fix(material-experimental/mdc-progress-spinner): apply correct color in high contrast mode
  src/material-experimental/mdc-progress-spinner/progress-spinner.scss
Labels: P3, a11y, cla: yes, merge ready, target: minor

#22510 build: fix wrong import path
  src/material/paginator/paginator.scss
Labels: P2, cla: yes, merge ready, merge safe, target: minor

#22515 feat(material-experimental/mdc-slide-toggle): swap to deprecated switch dependency
  package.json
  packages.bzl
  src/material-experimental/mdc-slide-toggle/_slide-toggle-theme.scss
  src/material-experimental/mdc-slide-toggle/slide-toggle.scss
  src/material-experimental/mdc-slide-toggle/slide-toggle.ts
  yarn.lock
Labels: cla: yes, merge ready, target: minor

#22500 docs(material/snack-bar): clarify dismissal actions in snackbar and u…
  src/components-examples/material/snack-bar/snack-bar-overview/snack-bar-overview-example.ts
  src/components-examples/material/snack-bar/snack-bar-position/snack-bar-position-example.ts
  src/material/snack-bar/snack-bar.md
Labels: P3, a11y, cla: yes, docs, merge ready, merge safe, target: patch

#22502 docs: add indentation to mat-form-field with suffix example
  src/components-examples/material/form-field/form-field-prefix-suffix/form-field-prefix-suffix-example.html
Labels: cla: yes, docs, merge ready, merge safe, target: patch

#22505 fix(material/schematics): replace removed variables with their values in sass api migration
  src/material/schematics/ng-generate/theming-api/config.ts
  src/material/schematics/ng-generate/theming-api/index.spec.ts
  src/material/schematics/ng-generate/theming-api/migration.ts
Labels: P2, cla: yes, merge ready, merge safe, target: rc

#22513 fix(material/autocomplete): error if keydown is dispatched too early
  src/material-experimental/mdc-autocomplete/autocomplete.spec.ts
  src/material/autocomplete/autocomplete-trigger.ts
  src/material/autocomplete/autocomplete.spec.ts
Labels: P3, cla: yes, merge ready, target: patch

#22514 docs: resolve some docs typos
  .circleci/env.sh
  guides/theming-your-components.md
  guides/typography.md
  src/cdk-experimental/menu/menu-bar.spec.ts
  src/cdk-experimental/menu/menu-item-radio.ts
  src/components-examples/material/button-toggle/button-toggle-harness/button-toggle-harness-example.spec.ts
  src/google-maps/map-directions-renderer/README.md
  src/google-maps/map-geocoder/README.md
  src/material/button-toggle/testing/button-toggle-group-shared.spec.ts
Labels: P4, cla: yes, docs, merge ready, merge safe, target: rc

#22468 docs(cdk/a11y): update Sass docs for new theming API
  src/cdk/a11y/a11y.md
Labels: P2, area: cdk/a11y, cla: yes, docs, merge ready, merge safe, target: rc

#22467 docs(material/theming): rewrite elevation guide
  guides/elevation.md
Labels: P2, area: theming, cla: yes, docs, merge ready, merge safe, target: rc

#22466 docs(material/theming): revise customizing-component-styles
  guides/customizing-component-styles.md
Labels: P2, area: theming, cla: yes, docs, merge ready, merge safe, target: rc

#22507 build: bump a few Angular and external dependencies
  .circleci/config.yml
  package.json
  src/cdk/schematics/ng-generate/drag-drop/schema.json
  src/cdk/schematics/utils/build-component.ts
  src/cdk/schematics/utils/vendored-ast-utils/index.ts
  src/material/schematics/ng-generate/address-form/schema.json
  src/material/schematics/ng-generate/dashboard/schema.json
  src/material/schematics/ng-generate/navigation/schema.json
  src/material/schematics/ng-generate/table/schema.json
  src/material/schematics/ng-generate/tree/schema.json
  tools/public_api_guard/cdk/a11y.d.ts
  tools/public_api_guard/cdk/bidi.d.ts
  tools/public_api_guard/cdk/clipboard.d.ts
  tools/public_api_guard/cdk/collections.d.ts
  tools/public_api_guard/cdk/drag-drop.d.ts
  tools/public_api_guard/cdk/layout.d.ts
  tools/public_api_guard/cdk/observers.d.ts
  tools/public_api_guard/cdk/overlay.d.ts
  tools/public_api_guard/cdk/platform.d.ts
  tools/public_api_guard/cdk/scrolling.d.ts
  tools/public_api_guard/cdk/table.d.ts
  tools/public_api_guard/cdk/text-field.d.ts
  tools/public_api_guard/google-maps/google-maps.d.ts
  tools/public_api_guard/material/bottom-sheet.d.ts
  tools/public_api_guard/material/core.d.ts
  tools/public_api_guard/material/datepicker.d.ts
  tools/public_api_guard/material/dialog.d.ts
  tools/public_api_guard/material/icon.d.ts
  tools/public_api_guard/material/icon/testing.d.ts
  tools/public_api_guard/material/paginator.d.ts
  tools/public_api_guard/material/snack-bar.d.ts
  tools/public_api_guard/material/sort.d.ts
  tools/public_api_guard/material/stepper.d.ts
  yarn.lock
Labels: P2, cla: yes, merge ready, merge safe, target: rc

#22427 refactor(cdk/a11y): Refactor focus indicator theme mixins to match other theme mixins
  src/dev-app/theme.scss
  src/material-experimental/mdc-helpers/_focus-indicators-theme.scss
  src/material-experimental/mdc-helpers/_focus-indicators.import.scss
  src/material/core/focus-indicators/_focus-indicators-theme.scss
  src/material/core/focus-indicators/_focus-indicators.import.scss
Labels: cla: yes, merge ready, target: minor

#22096 docs(schematics): correct a spelling mistake
  src/material/schematics/collection.json
Labels: cla: yes, commit message fixup, docs, merge ready, merge safe, target: rc

#22528 release: bump version to 11.2.10 w/ changelog
  CHANGELOG.md
  package.json
Labels: cla: yes, merge ready, merge safe, target: patch

#22531 release: bump version to 12.0.0-rc.0 w/ changelog
  CHANGELOG.md
  package.json
Labels: cla: yes, merge ready, merge safe, target: rc

#22523 fix(material/expansion): unable to assign custom tabindex on header
  src/material/expansion/expansion-panel-header.ts
  src/material/expansion/expansion.spec.ts
  tools/public_api_guard/material/expansion.d.ts
Labels: P3, cla: yes, merge ready, target: minor

#22546 test(material-experimental/mdc-slider): add custom form control tests
  src/material-experimental/mdc-slider/slider.spec.ts
  src/material-experimental/mdc-slider/slider.ts
Labels: cla: yes, target: feature branch

#22572 test(material-experimental/mdc-slider): add directionality tests
  src/material-experimental/mdc-slider/BUILD.bazel
  src/material-experimental/mdc-slider/slider.spec.ts
  src/material-experimental/mdc-slider/slider.ts
Labels: cla: yes, target: feature branch

#22265 fix(material/tabs): stop scrolling on tab change
  src/material-experimental/mdc-tabs/tab-group.spec.ts
  src/material/tabs/tab-group.spec.ts
  src/material/tabs/tab-group.ts
Labels: P3, cla: yes, merge ready, target: patch

#22441 refactor(material-experimental/mdc-progress-bar): remove wrapper element for progress bar
  src/material-experimental/mdc-progress-bar/progress-bar.html
  src/material-experimental/mdc-progress-bar/progress-bar.scss
  src/material-experimental/mdc-progress-bar/progress-bar.spec.ts
  src/material-experimental/mdc-progress-bar/progress-bar.ts
Labels: P3, cla: yes, merge ready, target: minor

#22540 fix(cdk/stepper): show error state if explicitly enabled
  src/cdk/stepper/stepper.ts
  src/material/stepper/public-api.ts
  src/material/stepper/stepper.spec.ts
  tools/public_api_guard/cdk/stepper.d.ts
Labels: P3, cla: yes, merge ready, target: minor

#22541 docs: minor fix in code
  src/google-maps/map-directions-renderer/README.md
Labels: cla: yes, docs, merge ready, merge safe, target: minor

#22534 build: update to angular v12.0.0-rc.0
  package.json
  yarn.lock
Labels: P2, cla: yes, merge ready, merge safe, preserve commits, target: rc

#22527 docs: switch remaining docs to @use
  src/cdk/text-field/text-field.md
  src/material-experimental/README.md
  src/material-experimental/mdc-autocomplete/README.md
  src/material-experimental/mdc-card/README.md
  src/material-experimental/mdc-checkbox/README.md
  src/material-experimental/mdc-chips/README.md
  src/material-experimental/mdc-dialog/README.md
  src/material-experimental/mdc-menu/README.md
  src/material-experimental/mdc-paginator/README.md
  src/material-experimental/mdc-progress-bar/README.md
  src/material-experimental/mdc-progress-spinner/README.md
  src/material-experimental/mdc-radio/README.md
  src/material-experimental/mdc-select/README.md
  src/material-experimental/mdc-slide-toggle/README.md
  src/material-experimental/mdc-slider/README.md
  src/material-experimental/mdc-snack-bar/README.md
  src/material-experimental/mdc-table/README.md
  src/material-experimental/mdc-tabs/README.md
  src/material-experimental/mdc-tooltip/README.md
Labels: P3, cla: yes, docs, merge ready, merge safe, target: rc

#22522 build: disable copying the minified umd bundles
  .circleci/config.yml
Labels: P3, cla: yes, merge ready, merge safe, target: minor

#22565 fix(material/datepicker): support for date range input in MDC-based form field
  src/material/datepicker/date-range-input.html
  src/material/datepicker/date-range-input.ts
  tools/public_api_guard/material/datepicker.d.ts
Labels: P2, cla: yes, merge ready, target: patch

#22566 refactor(multiple): resolve rxjs 7 compilation errors
  src/cdk-experimental/combobox/combobox-panel.ts
  src/cdk-experimental/menu/context-menu.ts
  src/cdk-experimental/menu/menu-bar.ts
  src/cdk-experimental/menu/menu-stack.ts
  src/cdk-experimental/menu/menu.ts
  src/components-examples/cdk-experimental/selection/cdk-selection-column/cdk-selection-column-example.ts
  src/components-examples/cdk-experimental/selection/cdk-selection-list/cdk-selection-list-example.ts
  src/components-examples/material-experimental/selection/mat-selection-column/mat-selection-column-example.ts
  src/components-examples/material-experimental/selection/mat-selection-list/mat-selection-list-example.ts
  src/material/datepicker/datepicker-toggle.ts
  src/material/menu/menu-trigger.ts
  src/material/menu/menu.ts
  src/material/tabs/paginated-tab-header.ts
  src/material/tree/data-source/nested-data-source.ts
Labels: P3, cla: yes, merge ready, target: rc

#22555 build: use platform from shared dev-infra package for remote execution
  .bazelrc
  WORKSPACE
  package.json
  tools/BUILD.bazel
  tools/rbe_cross_platform_workaround.patch
  yarn.lock
Labels: cla: yes, merge ready, merge safe, target: minor

#22585 release: bump version to 12.0.0-rc.1 w/ changelog
  CHANGELOG.md
  package.json
Labels: cla: yes, merge safe
