Repository angular/components, pull requests merged in 2021-01, with the labels that each got.

#21404 docs(material/tabs): add harness example for tabs
  src/components-examples/material/tabs/BUILD.bazel
  src/components-examples/material/tabs/index.ts
  src/components-examples/material/tabs/tab-group-harness/tab-group-harness-example.html
  src/components-examples/material/tabs/tab-group-harness/tab-group-harness-example.spec.ts
  src/components-examples/material/tabs/tab-group-harness/tab-group-harness-example.ts
Labels: P3, cla: yes, docs, merge ready, merge safe, target: patch

#21405 docs(material/table): add harness example for table
  src/components-examples/material/table/BUILD.bazel
  src/components-examples/material/table/index.ts
  src/components-examples/material/table/table-harness/table-harness-example.html
  src/components-examples/material/table/table-harness/table-harness-example.spec.ts
  src/components-examples/material/table/table-harness/table-harness-example.ts
Labels: P3, cla: yes, docs, merge ready, merge safe, target: patch

#21406 docs(material/icon): add harness example for icon
  src/components-examples/material/icon/BUILD.bazel
  src/components-examples/material/icon/icon-harness/icon-harness-example.html
  src/components-examples/material/icon/icon-harness/icon-harness-example.spec.ts
  src/components-examples/material/icon/icon-harness/icon-harness-example.ts
  src/components-examples/material/icon/index.ts
Labels: P3, cla: yes, docs, merge ready, merge safe, target: patch

#21416 docs(material/input): add harness example for input
  src/components-examples/material/input/BUILD.bazel
  src/components-examples/material/input/index.ts
  src/components-examples/material/input/input-harness/input-harness-example.html
  src/components-examples/material/input/input-harness/input-harness-example.spec.ts
  src/components-examples/material/input/input-harness/input-harness-example.ts
Labels: P3, cla: yes, docs, merge ready, merge safe, target: patch

#21417 docs(material/progress-bar): add harness example for progress bar
  src/components-examples/material/progress-bar/BUILD.bazel
  src/components-examples/material/progress-bar/index.ts
  src/components-examples/material/progress-bar/progress-bar-harness/progress-bar-harness-example.html
  src/components-examples/material/progress-bar/progress-bar-harness/progress-bar-harness-example.spec.ts
  src/components-examples/material/progress-bar/progress-bar-harness/progress-bar-harness-example.ts
Labels: P3, cla: yes, docs, merge ready, merge safe, target: patch

#21448 docs(material/autocomplete): add mat-label to examples
  src/components-examples/material/autocomplete/autocomplete-auto-active-first-option/autocomplete-auto-active-first-option-example.html
  src/components-examples/material/autocomplete/autocomplete-filter/autocomplete-filter-example.html
  src/components-examples/material/autocomplete/autocomplete-optgroup/autocomplete-optgroup-example.html
  src/components-examples/material/autocomplete/autocomplete-overview/autocomplete-overview-example.html
  src/components-examples/material/autocomplete/autocomplete-simple/autocomplete-simple-example.html
Labels: P3, cla: yes, docs, merge ready, merge safe, target: patch

#21449 docs(material/progress-spinner): add harness example for progress spi…
  src/components-examples/material/progress-spinner/BUILD.bazel
  src/components-examples/material/progress-spinner/index.ts
  src/components-examples/material/progress-spinner/progress-spinner-harness/progress-spinner-harness-example.html
  src/components-examples/material/progress-spinner/progress-spinner-harness/progress-spinner-harness-example.spec.ts
  src/components-examples/material/progress-spinner/progress-spinner-harness/progress-spinner-harness-example.ts
Labels: P3, cla: yes, docs, merge ready, merge safe, target: patch

#21450 docs(material/list): add harness example for list
  src/components-examples/material/list/BUILD.bazel
  src/components-examples/material/list/index.ts
  src/components-examples/material/list/list-harness/list-harness-example.html
  src/components-examples/material/list/list-harness/list-harness-example.spec.ts
  src/components-examples/material/list/list-harness/list-harness-example.ts
Labels: P3, cla: yes, docs, merge ready, merge safe, target: patch

#21502 Project import generated by Copybara.
  src/material-experimental/mdc-checkbox/_checkbox-theme.scss
  src/material-experimental/mdc-checkbox/checkbox.scss
Labels: P2, cla: yes, merge ready, merge safe, target: minor

#21451 docs(material/menu): add harness example for menu
  src/components-examples/material/menu/BUILD.bazel
  src/components-examples/material/menu/index.ts
  src/components-examples/material/menu/menu-harness/menu-harness-example.html
  src/components-examples/material/menu/menu-harness/menu-harness-example.spec.ts
  src/components-examples/material/menu/menu-harness/menu-harness-example.ts
Labels: P3, cla: yes, docs, merge ready, merge safe, target: patch

#21454 docs(material/paginator): add harness example for paginator
  src/components-examples/material/paginator/BUILD.bazel
  src/components-examples/material/paginator/index.ts
  src/components-examples/material/paginator/paginator-harness/paginator-harness-example.html
  src/components-examples/material/paginator/paginator-harness/paginator-harness-example.spec.ts
  src/components-examples/material/paginator/paginator-harness/paginator-harness-example.ts
Labels: P3, cla: yes, docs, merge ready, merge safe, target: patch

#21455 docs(material/bottom-sheet): add harness example for bottom sheet
  src/components-examples/material/bottom-sheet/BUILD.bazel
  src/components-examples/material/bottom-sheet/bottom-sheet-harness/bottom-sheet-harness-example.html
  src/components-examples/material/bottom-sheet/bottom-sheet-harness/bottom-sheet-harness-example.spec.ts
  src/components-examples/material/bottom-sheet/bottom-sheet-harness/bottom-sheet-harness-example.ts
  src/components-examples/material/bottom-sheet/index.ts
Labels: P3, cla: yes, docs, merge ready, merge safe, target: patch

#21463 docs(material/radio): add harness example for radio
  src/components-examples/material/radio/BUILD.bazel
  src/components-examples/material/radio/index.ts
  src/components-examples/material/radio/radio-harness/radio-harness-example.html
  src/components-examples/material/radio/radio-harness/radio-harness-example.spec.ts
  src/components-examples/material/radio/radio-harness/radio-harness-example.ts
Labels: P3, cla: yes, docs, merge ready, merge safe, target: patch

#21464 docs(material/select): add harness example for select
  src/components-examples/material/select/BUILD.bazel
  src/components-examples/material/select/index.ts
  src/components-examples/material/select/select-harness/select-harness-example.html
  src/components-examples/material/select/select-harness/select-harness-example.spec.ts
  src/components-examples/material/select/select-harness/select-harness-example.ts
Labels: P3, cla: yes, docs, merge ready, merge safe, target: patch

#21465 docs(material/slide-toggle): add harness example for slide-toggle
  src/components-examples/material/slide-toggle/BUILD.bazel
  src/components-examples/material/slide-toggle/index.ts
  src/components-examples/material/slide-toggle/slide-toggle-harness/slide-toggle-harness-example.html
  src/components-examples/material/slide-toggle/slide-toggle-harness/slide-toggle-harness-example.spec.ts
  src/components-examples/material/slide-toggle/slide-toggle-harness/slide-toggle-harness-example.ts
Labels: P3, cla: yes, docs, merge ready, merge safe, target: patch

#21466 docs(material/slider): add harness example for slider
  src/components-examples/material/slider/BUILD.bazel
  src/components-examples/material/slider/index.ts
  src/components-examples/material/slider/slider-harness/slider-harness-example.html
  src/components-examples/material/slider/slider-harness/slider-harness-example.spec.ts
  src/components-examples/material/slider/slider-harness/slider-harness-example.ts
Labels: P3, cla: yes, docs, merge ready, merge safe, target: patch

#21469 docs(material/sort): add harness example for sort
  src/components-examples/material/sort/BUILD.bazel
  src/components-examples/material/sort/index.ts
  src/components-examples/material/sort/sort-harness/sort-harness-example.html
  src/components-examples/material/sort/sort-harness/sort-harness-example.spec.ts
  src/components-examples/material/sort/sort-harness/sort-harness-example.ts
Labels: P3, cla: yes, docs, merge ready, merge safe, target: patch

#21470 docs(material/grid-list): add harness example for grid-list
  src/components-examples/material/grid-list/BUILD.bazel
  src/components-examples/material/grid-list/grid-list-harness/grid-list-harness-example.html
  src/components-examples/material/grid-list/grid-list-harness/grid-list-harness-example.spec.ts
  src/components-examples/material/grid-list/grid-list-harness/grid-list-harness-example.ts
  src/components-examples/material/grid-list/index.ts
Labels: P3, cla: yes, docs, merge ready, merge safe, target: patch

#21471 docs(material/form-field): add harness example for form-field
  src/components-examples/material/form-field/BUILD.bazel
  src/components-examples/material/form-field/form-field-harness/form-field-harness-example.html
  src/components-examples/material/form-field/form-field-harness/form-field-harness-example.spec.ts
  src/components-examples/material/form-field/form-field-harness/form-field-harness-example.ts
  src/components-examples/material/form-field/index.ts
Labels: P3, cla: yes, docs, merge ready, merge safe, target: patch

#21472 docs(material/expansion): add harness example for expansion
  src/components-examples/material/expansion/BUILD.bazel
  src/components-examples/material/expansion/expansion-harness/expansion-harness-example.html
  src/components-examples/material/expansion/expansion-harness/expansion-harness-example.spec.ts
  src/components-examples/material/expansion/expansion-harness/expansion-harness-example.ts
  src/components-examples/material/expansion/index.ts
Labels: P3, cla: yes, docs, merge ready, merge safe, target: patch

#21473 docs(material/divider): add harness example for divider
  src/components-examples/material/divider/BUILD.bazel
  src/components-examples/material/divider/divider-harness/divider-harness-example.html
  src/components-examples/material/divider/divider-harness/divider-harness-example.spec.ts
  src/components-examples/material/divider/divider-harness/divider-harness-example.ts
  src/components-examples/material/divider/index.ts
Labels: P3, cla: yes, docs, merge ready, merge safe, target: patch

#21475 docs(material/datepicker): add harness example for datepicker
  src/components-examples/material/datepicker/BUILD.bazel
  src/components-examples/material/datepicker/datepicker-harness/datepicker-harness-example.html
  src/components-examples/material/datepicker/datepicker-harness/datepicker-harness-example.spec.ts
  src/components-examples/material/datepicker/datepicker-harness/datepicker-harness-example.ts
  src/components-examples/material/datepicker/index.ts
Labels: P3, cla: yes, docs, merge ready, merge safe, target: patch

#21124 docs: fix form field example styles
  src/components-examples/material/form-field/form-field-overview/form-field-overview-example.css
  src/components-examples/material/form-field/form-field-overview/form-field-overview-example.html
  src/components-examples/material/form-field/form-field-overview/form-field-overview-example.ts
Labels: P4, cla: yes, docs, merge ready, merge safe, target: patch

#21252 fix(material/menu): set correct focus origin on item when opened via keyboard
  src/material-experimental/mdc-menu/menu.spec.ts
  src/material/menu/menu-trigger.ts
  src/material/menu/menu.spec.ts
  tools/public_api_guard/material/menu.d.ts
Labels: G, P2, a11y, cla: yes, merge ready, target: patch

#21499 refactor(material/datepicker): expose year view change detector ref
  src/material/datepicker/year-view.ts
  tools/public_api_guard/material/datepicker.d.ts
Labels: G, P2, area: material/datepicker, cla: yes, merge ready, target: patch

#21227 fix(cdk/drag-drop): don't stop event propagation unless nested
  src/cdk/drag-drop/directives/drag.spec.ts
  src/cdk/drag-drop/directives/drag.ts
  src/cdk/drag-drop/drag-ref.ts
  tools/public_api_guard/cdk/drag-drop.d.ts
Labels: P2, cla: yes, merge ready, target: patch

#21228 fix(material/datepicker): a couple of accessibility issues in touch UI mode
  src/material/datepicker/calendar-body.scss
  src/material/datepicker/datepicker-base.ts
  src/material/datepicker/datepicker-content.html
Labels: P2, a11y, area: material/datepicker, cla: yes, merge ready, target: patch

#21382 fix(cdk/drag-drop): don't block scrolling if it happens before delay has elapsed
  src/cdk/drag-drop/directives/drag.spec.ts
  src/cdk/drag-drop/drag-drop-registry.spec.ts
  src/cdk/drag-drop/drag-drop-registry.ts
  src/cdk/drag-drop/drag-ref.ts
  tools/public_api_guard/cdk/drag-drop.d.ts
Labels: P2, cla: yes, merge ready, target: patch

#21391 fix(material-experimental/mdc-progress-spinner): indeterminate animation not working
  src/material-experimental/mdc-progress-spinner/progress-spinner.scss
Labels: P2, cla: yes, merge ready, target: patch

#21419 fix(google-maps): typo in retina methods
  src/google-maps/map-marker-clusterer/map-marker-clusterer.spec.ts
  src/google-maps/map-marker-clusterer/map-marker-clusterer.ts
  src/google-maps/map-marker-clusterer/marker-clusterer-types.ts
  src/google-maps/testing/fake-google-map-utils.ts
  tools/public_api_guard/google-maps/google-maps.d.ts
Labels: P2, cla: yes, merge ready, target: minor

#21428 fix(material-experimental/mdc-table): error when flexbox-based table is initialized
  src/cdk/table/table.ts
  src/material-experimental/mdc-table/BUILD.bazel
  src/material-experimental/mdc-table/table.spec.ts
  src/material-experimental/mdc-table/table.ts
  tools/public_api_guard/cdk/table.d.ts
Labels: P2, cla: yes, merge ready, target: patch

#17223 fix(cdk/overlay): block scroll strategy throwing off scroll behavior feature detection
  src/cdk/overlay/scroll/block-scroll-strategy.ts
  src/cdk/platform/features/scrolling.ts
Labels: P3, cla: yes, merge ready, target: patch

#21394 fix(material-experimental/mdc-autocomplete): panel losing max-height if menu is opened after autocomplete
  src/material-experimental/mdc-autocomplete/autocomplete.scss
Labels: P3, cla: yes, merge ready, target: patch

#21421 fix(cdk/tree): add missing generic types to trackBy Fixes (#21364)
  .gitignore
  src/cdk/tree/nested-node.ts
  src/cdk/tree/padding.ts
  src/cdk/tree/toggle.ts
  src/cdk/tree/tree.ts
  src/material/tree/node.ts
  src/material/tree/padding.ts
  src/material/tree/toggle.ts
  src/material/tree/tree.ts
  tools/public_api_guard/cdk/tree.d.ts
  tools/public_api_guard/material/tree.d.ts
Labels: P3, cla: yes, merge ready, target: patch

#21365 fix(material-experimental/mdc-form-field): fix fill appearance contra…
  src/material-experimental/mdc-form-field/_mdc-text-field-theme-variable-refresh.scss
Labels: G, a11y, cla: yes, merge ready, target: patch

#21398 build: fix not being able to test MDC density in RTL
  src/dev-app/dev-app/dev-app-layout.html
  src/dev-app/dev-app/dev-app-layout.ts
Labels: P3, cla: yes, merge ready, merge safe, target: patch

#21429 docs: fix SVG icon example on Stackblitz
  src/components-examples/material/icon/icon-svg/icon-svg-example.ts
Labels: P3, cla: yes, docs, merge ready, merge safe, target: patch

#21479 feat(material/schematics): use newer Google Fonts version
  guides/typography.md
  src/dev-app/index.html
  src/e2e-app/index.html
  src/material/schematics/ng-add/fonts/material-fonts.ts
  src/material/schematics/ng-add/index.spec.ts
  src/universal-app/index.html
Labels: P3, cla: yes, merge ready, merge safe, target: minor

#21486 build: bump year
  LICENSE
Labels: P3, cla: yes, merge ready, merge safe, target: patch

#21488 build: fix compilation errors in utility scripts
  tools/dev-server/dev-server.ts
  tools/release/changelog.ts
  tools/release/release-output/check-package.ts
Labels: P3, cla: yes, merge ready, merge safe, target: patch

#21501 build: bump material-components-web from 9.0.0-canary.eff7b46ac.0 to …
  package.json
  yarn.lock
Labels: P2, cla: yes, merge ready, merge safe, target: minor

#21395 docs(material/slider): updated slider documentation.
  src/material/slider/slider.md
Labels: caretaker note, cla: yes, docs, merge ready, merge safe, target: patch

#21437 build: update to latest postcss and resolve issues
  package.json
  tools/postcss/compare-nodes.ts
  tools/stylelint/no-ampersand-beyond-selector-start.ts
  tools/stylelint/stylelint-postcss-types.ts
  tools/stylelint/theme-mixin-api.ts
  yarn.lock
Labels: P3, cla: yes, merge ready, merge safe, target: minor

#21445 build: update to gulp 4
  package.json
  tools/gulp/gulpfile.ts
  tools/gulp/tasks/ci.ts
  tools/gulp/tasks/clean.ts
  tools/gulp/tasks/unit-test.ts
  tools/package-tools/gulp/build-tasks-gulp.ts
  tools/package-tools/gulp/sequence-task.ts
  tools/package-tools/index.ts
  yarn.lock
Labels: P3, cla: yes, merge ready, merge safe, target: minor

#21200 feat(cdk-experimental/table-scroll-container): Create directive and demo
  .github/CODEOWNERS
  .ng-dev/commit-message.ts
  src/cdk-experimental/config.bzl
  src/cdk-experimental/table-scroll-container/BUILD.bazel
  src/cdk-experimental/table-scroll-container/index.ts
  src/cdk-experimental/table-scroll-container/public-api.ts
  src/cdk-experimental/table-scroll-container/table-scroll-container-module.ts
  src/cdk-experimental/table-scroll-container/table-scroll-container.spec.ts
  src/cdk-experimental/table-scroll-container/table-scroll-container.ts
  src/cdk/table/public-api.ts
  src/cdk/table/sticky-position-listener.ts
  src/cdk/table/sticky-styler.ts
  src/cdk/table/table.spec.ts
  src/cdk/table/table.ts
  src/dev-app/BUILD.bazel
  src/dev-app/dev-app/dev-app-layout.ts
  src/dev-app/dev-app/routes.ts
  src/dev-app/table-scroll-container/BUILD.bazel
  src/dev-app/table-scroll-container/table-scroll-container-demo-module.ts
  src/dev-app/table-scroll-container/table-scroll-container-demo.html
  src/dev-app/table-scroll-container/table-scroll-container-demo.scss
  src/dev-app/table-scroll-container/table-scroll-container-demo.ts
  src/dev-app/theme.scss
  tools/public_api_guard/cdk/table.d.ts
Labels: G, P2, area: cdk/table, cla: yes, merge ready, target: minor

#21223 fix(material/datepicker): range input controls dirty on init
  src/material/datepicker/date-range-input-parts.ts
  src/material/datepicker/date-range-input.spec.ts
  src/material/datepicker/datepicker-input-base.ts
  src/material/datepicker/datepicker-input.ts
  tools/public_api_guard/material/datepicker.d.ts
Labels: P2, cla: yes, merge ready, target: minor

#20979 fix(material-experimental/mdc-tabs): correct min-width according to m…
  src/material-experimental/mdc-tabs/_tabs-common.scss
Labels: P2, cla: yes, merge ready, target: minor

#21377 fix(material-experimental/mdc-snack-bar): disable animations in noop
  src/material-experimental/mdc-snack-bar/snack-bar-container.scss
  src/material-experimental/mdc-snack-bar/snack-bar-container.ts
Labels: P2, cla: yes, merge ready, target: patch

#21384 fix(material-experimental/mdc-snack-bar): simple snack button should be accent
  src/material-experimental/mdc-snack-bar/_snack-bar-theme.scss
Labels: P2, cla: yes, merge ready, target: patch

#21487 feat(material/datepicker): add support for cancel/apply buttons
  src/components-examples/material/datepicker/datepicker-actions/datepicker-actions-example.css
  src/components-examples/material/datepicker/datepicker-actions/datepicker-actions-example.html
  src/components-examples/material/datepicker/datepicker-actions/datepicker-actions-example.ts
  src/components-examples/material/datepicker/index.ts
  src/dev-app/datepicker/datepicker-demo.html
  src/dev-app/datepicker/datepicker-demo.ts
  src/material/datepicker/BUILD.bazel
  src/material/datepicker/date-range-picker.ts
  src/material/datepicker/date-selection-model.ts
  src/material/datepicker/datepicker-actions.scss
  src/material/datepicker/datepicker-actions.spec.ts
  src/material/datepicker/datepicker-actions.ts
  src/material/datepicker/datepicker-base.ts
  src/material/datepicker/datepicker-content.html
  src/material/datepicker/datepicker-content.scss
  src/material/datepicker/datepicker-module.ts
  src/material/datepicker/datepicker.md
  src/material/datepicker/datepicker.ts
  src/material/datepicker/public-api.ts
  tools/public_api_guard/material/datepicker.d.ts
Labels: P2, cla: yes, merge ready, target: minor

#21441 fix(google-maps): compatibility with latest typings
  package.json
  src/dev-app/google-map/google-map-demo.ts
  src/google-maps/google-map/README.md
  src/google-maps/google-map/google-map.spec.ts
  src/google-maps/google-map/google-map.ts
  src/google-maps/map-circle/map-circle.ts
  src/google-maps/map-ground-overlay/map-ground-overlay.ts
  src/google-maps/map-info-window/README.md
  src/google-maps/map-marker-clusterer/README.md
  src/google-maps/map-marker/README.md
  src/google-maps/map-marker/map-marker.ts
  src/google-maps/map-polygon/map-polygon.ts
  src/google-maps/map-polyline/map-polyline.ts
  src/google-maps/map-rectangle/map-rectangle.ts
  src/google-maps/package.json
  tools/public_api_guard/google-maps/google-maps.d.ts
  yarn.lock
Labels: P2, caretaker note, cla: yes, merge ready, target: minor

#21512 fix(cdk/a11y): focusVia not accounting for focused child node
  src/cdk/a11y/focus-monitor/focus-monitor.spec.ts
  src/cdk/a11y/focus-monitor/focus-monitor.ts
Labels: G, P3, cla: yes, merge ready, target: patch

#21210 fix(material/datepicker): unable to pass in errorStateMatcher through binding on range input
  src/material/datepicker/date-range-input-parts.ts
  src/material/datepicker/date-range-input.spec.ts
  tools/public_api_guard/material/datepicker.d.ts
Labels: P3, cla: yes, merge ready, target: patch

#21397 fix(material/autocomplete): not closing when clicking outside using auxiliary button
  src/material-experimental/mdc-autocomplete/autocomplete.spec.ts
  src/material/autocomplete/autocomplete-trigger.ts
  src/material/autocomplete/autocomplete.spec.ts
Labels: P3, cla: yes, merge ready, target: patch

#21399 fix(material/datepicker): unable to distinguish disabled calendar cells in high contrast mode
  src/material/datepicker/calendar-body.scss
Labels: P3, a11y, cla: yes, merge ready, target: patch

#21400 feat(cdk/drag-drop): support configurable scroll speed
  src/cdk/drag-drop/directives/drag.spec.ts
  src/cdk/drag-drop/directives/drop-list.ts
  src/cdk/drag-drop/drop-list-ref.ts
  tools/public_api_guard/cdk/drag-drop.d.ts
Labels: P3, cla: yes, merge ready, target: minor

#21403 fix(material/table): increase specificity on sticky selector
  src/material-experimental/mdc-table/table.scss
  src/material/core/style/_vendor-prefixes.scss
  src/material/table/table.scss
Labels: P3, cla: yes, merge ready, target: patch

#21431 feat(material/icon): add support for registry resolver function
  src/material/icon/icon-registry.ts
  src/material/icon/icon.spec.ts
  src/material/icon/testing/fake-icon-registry.ts
  tools/public_api_guard/material/icon.d.ts
  tools/public_api_guard/material/icon/testing.d.ts
Labels: P3, cla: yes, merge ready, target: minor

#21436 fix(material/menu): allow menu height to grow after open
  src/material/menu/menu-trigger.ts
Labels: P3, cla: yes, merge ready, target: patch

#21438 fix(material-experimental/mdc-list): make internal input non-interactive
  src/material-experimental/mdc-list/list-option.html
  src/material-experimental/mdc-list/list-option.scss
  src/material-experimental/mdc-list/list-option.ts
Labels: P3, a11y, cla: yes, merge ready, target: patch

#21446 fix(material-experimental/mdc-form-field): fill appearance blending in with the background in high contrast mode
  src/material-experimental/mdc-form-field/_mdc-text-field-structure-overrides.scss
Labels: P3, a11y, cla: yes, merge ready, target: patch

#21484 fix(material/core): unable to distinguish disabled mat-option in high contrast mode
  src/material/core/option/option.scss
Labels: P3, a11y, cla: yes, merge ready, target: patch

#21493 fix(material/datepicker): remove scroll bar while animating in touch UI mode
  src/material/datepicker/datepicker-content.scss
Labels: P3, cla: yes, merge ready, target: patch

#21505 fix(cdk/scrolling): Prevents NaN being returned as firstVisibleIndex.
  src/cdk/scrolling/fixed-size-virtual-scroll.ts
Labels: P3, cla: yes, merge ready, target: patch

#21496 refactor(material-experimental/mdc-snack-bar): de-duplicate test harness logic
  src/material-experimental/mdc-snack-bar/testing/BUILD.bazel
  src/material-experimental/mdc-snack-bar/testing/public-api.ts
  src/material-experimental/mdc-snack-bar/testing/snack-bar-harness-filters.ts
  src/material-experimental/mdc-snack-bar/testing/snack-bar-harness.ts
  src/material/snack-bar/testing/snack-bar-harness.ts
  tools/public_api_guard/material/snack-bar/testing.d.ts
Labels: P3, cla: yes, merge ready, target: minor

#21201 feat(cdk/scrolling): update ScrollDispatcher to allow HTMLElement par…
  src/cdk/scrolling/scroll-dispatcher.spec.ts
  src/cdk/scrolling/scroll-dispatcher.ts
  tools/public_api_guard/cdk/scrolling.d.ts
  yarn.lock
Labels: cla: yes, merge ready, target: minor

#21474 docs(material/dialog): add harness example for dialog
  src/components-examples/material/dialog/BUILD.bazel
  src/components-examples/material/dialog/dialog-harness/dialog-harness-example.html
  src/components-examples/material/dialog/dialog-harness/dialog-harness-example.spec.ts
  src/components-examples/material/dialog/dialog-harness/dialog-harness-example.ts
  src/components-examples/material/dialog/index.ts
Labels: P3, cla: yes, docs, merge ready, merge safe, target: patch

#21412 Minor grammar fix
  src/cdk/layout/layout.md
Labels: cla: yes, commit message fixup, docs, merge ready, merge safe, target: patch

#21542 docs: update readme for Q1 2021
  README.md
Labels: cla: yes, docs, merge ready, merge safe, target: patch

#21545 docs(material/tree): add a description of the when predicate
  src/material/tree/node.ts
Labels: cla: yes, merge ready, merge safe, target: patch

#21534 build: replace deprecated axe dependency
  package.json
  src/e2e-app/e2e-app/e2e-app-layout.html
  src/e2e-app/e2e-app/e2e-app-layout.ts
  src/e2e-app/mdc-progress-bar/mdc-progress-bar-e2e.html
  src/e2e-app/mdc-progress-spinner/mdc-progress-spinner-e2e.html
  src/e2e-app/progress-bar/progress-bar-e2e.html
  src/e2e-app/progress-spinner/progress-spinner-e2e.html
  src/e2e-app/protractor.conf.js
  src/e2e-app/test_suite.bzl
  src/e2e-app/virtual-scroll/virtual-scroll-e2e.html
  tools/axe-protractor/index.js
  yarn.lock
Labels: P3, cla: yes, merge ready, merge safe, target: minor

#21080 Update to latest @angular/dev-infra-private and husky@5
  .github/CODEOWNERS
  .husky/.gitignore
  .husky/commit-msg
  .husky/prepare-commit-msg
  package.json
  yarn.lock
Labels: area: build, cla: yes, merge ready, merge safe, target: minor

#21568 Revert "fix(material-experimental/mdc-table): error when flexbox-based table is initialized (#21428)"
  src/cdk/table/table.ts
  src/material-experimental/mdc-table/BUILD.bazel
  src/material-experimental/mdc-table/table.spec.ts
  src/material-experimental/mdc-table/table.ts
  tools/public_api_guard/cdk/table.d.ts
  yarn.lock
Labels: cla: yes, merge ready, merge safe, target: patch

#21559 build: update to latest @angular/dev-infra-private and husky@5
  .github/CODEOWNERS
  .husky/.gitignore
  .husky/commit-msg
  .husky/prepare-commit-msg
  package.json
  yarn.lock
Labels: area: build, cla: yes, merge ready, merge safe, target: patch

#21477 fix(material-experimental/mdc-snack-bar): not stretching to full width on handset
  src/material-experimental/mdc-snack-bar/snack-bar-container.scss
Labels: P3, cla: yes, merge ready, target: patch

#21516 refactor(material/core): add functions for normalizing to 2014 and
  src/material/core/typography/_typography.scss
Labels: P2, cla: yes, merge ready, target: patch

#21525 feat(material-experimental/mdc-autocomplete): add panel animation
  src/material-experimental/mdc-autocomplete/animations.ts
  src/material-experimental/mdc-autocomplete/autocomplete.html
  src/material-experimental/mdc-autocomplete/autocomplete.scss
  src/material-experimental/mdc-autocomplete/autocomplete.spec.ts
  src/material-experimental/mdc-autocomplete/autocomplete.ts
  src/material/autocomplete/testing/shared.spec.ts
Labels: cla: yes, merge ready, target: patch

#21566 fix(material-experimental/mdc-table): remove bottom border for flex table
  src/material-experimental/mdc-table/table.scss
Labels: P2, cla: yes, merge ready, target: patch

#21567 ci: fix indentation of CODEOWNERS entries
  .github/CODEOWNERS
Labels: area: build, cla: yes, merge ready, merge safe, target: minor

#21580 release: update angular deps
  package.json
  yarn.lock
Labels: cla: yes, merge ready, merge safe, target: minor

#21590 release: bump version to 11.0.4 w/ changelog
  CHANGELOG.md
  package.json
Labels: cla: yes, merge ready, target: patch

#21594 fix(material-experimental/mdc-table): don't import template from other package
  src/material-experimental/mdc-table/text-column.ts
  src/material/table/text-column.ts
  tools/public_api_guard/material/table.d.ts
Labels: cla: yes, merge ready, target: minor

#21595 release: fix release-script
  tools/release/stage-release.ts
Labels: cla: yes, merge ready, merge safe, target: minor

#21596 release: bump version to 11.1.0-rc.0 w/ changelog
  CHANGELOG.md
  package.json
Labels: cla: yes, merge ready, target: minor

#21598 release: bump master branch version to 11.2.0-next.0
  package.json
Labels: cla: yes, merge ready, merge safe, target: minor

#21393 fix(material-experimental/mdc-list): not accounting for global ripple options
  src/material-experimental/mdc-list/list-base.ts
  src/material-experimental/mdc-list/list-option.ts
  src/material-experimental/mdc-list/list.ts
Labels: P3, cla: yes, merge ready, target: minor

#21409 docs(material/stepper): add harness example for stepper
  src/components-examples/material/stepper/BUILD.bazel
  src/components-examples/material/stepper/index.ts
  src/components-examples/material/stepper/stepper-harness/stepper-harness-example.html
  src/components-examples/material/stepper/stepper-harness/stepper-harness-example.spec.ts
  src/components-examples/material/stepper/stepper-harness/stepper-harness-example.ts
Labels: P3, cla: yes, docs, merge ready, merge safe, target: patch

#21513 fix(material/autocomplete): activate first enabled option with autoActiveFirstOption
  src/material-experimental/mdc-autocomplete/autocomplete.spec.ts
  src/material/autocomplete/autocomplete-trigger.ts
  src/material/autocomplete/autocomplete.spec.ts
Labels: P3, cla: yes, merge ready, target: patch

#21527 fix(material/menu): focus indication rendering partially in high contrast mode
  src/material-experimental/mdc-menu/menu.scss
  src/material/menu/menu.scss
Labels: P3, a11y, cla: yes, merge ready, target: patch

#21528 build: update to rules_nodejs 2.3.2
  WORKSPACE
  package.json
  yarn.lock
Labels: P3, caretaker note, cla: yes, merge ready, merge safe, target: rc

#21533 fix(material/tabs): background color inherited to nested groups
  src/material-experimental/mdc-tabs/_tabs-theme.scss
  src/material/tabs/_tabs-theme.scss
Labels: P3, caretaker note, cla: yes, merge ready, target: patch

#21432 refactor(material/core): remove unnecessary styles from mat-option
  src/material-experimental/mdc-core/option/option.scss
  src/material/core/option/option.scss
Labels: P4, cla: yes, merge ready, target: patch

#21444 feat(material/datepicker): allow for focus restoration to be disabled
  src/material/datepicker/datepicker-base.ts
  src/material/datepicker/datepicker.spec.ts
Labels: P4, cla: yes, merge ready, target: minor

#21117 fix(material/button): anchor mat-icon-button as matSuffix focus misaligned
  src/material/button/button.scss
Labels: P3, cla: yes, merge ready, target: patch

#21427 fix(cdk/overlay): sub-pixel deviations throwing off positioning in some cases
  src/cdk/overlay/position/flexible-connected-position-strategy.spec.ts
  src/cdk/overlay/position/flexible-connected-position-strategy.ts
Labels: P3, cla: yes, merge ready, target: patch

#21604 build: check tooling scripts for compilation errors
  .circleci/config.yml
  package.json
  tools/tsconfig-ci.json
  tools/tslint-rules/noUnescapedHtmlTagRule.ts
Labels: P2, cla: yes, merge ready, merge safe, target: rc

#21426 fix(cdk/tree): Overflowing inline-code markup in readme
  src/cdk/tree/tree.md
Labels: P3, cla: yes, commit message fixup, merge ready, merge safe, target: patch

#21600 docs: fix incorrect changelog entries
  CHANGELOG.md
Labels: cla: yes, docs, merge ready, merge safe, target: rc

#21610 build: downgrade bazel dependencies
  package.json
  yarn.lock
Labels: P2, cla: yes, merge ready, merge safe, target: rc

#21611 build: configure the ng-dev caretaker check command
  .github/angular-robot.yml
  .ng-dev/caretaker.ts
  .ng-dev/config.ts
Labels: area: dev-infra, cla: yes, merge ready, merge safe, target: patch

#21280 fix(material/radio): remove tabindex from host node
  src/material-experimental/mdc-radio/radio.spec.ts
  src/material-experimental/mdc-radio/radio.ts
  src/material/radio/radio.spec.ts
  src/material/radio/radio.ts
Labels: G, P2, a11y, cla: yes, merge ready, target: patch

#21552 fix(material/snack-bar): fix Firefox/JAWS not reading out snackbar me…
  src/material-experimental/mdc-snack-bar/BUILD.bazel
  src/material-experimental/mdc-snack-bar/snack-bar-container.html
  src/material-experimental/mdc-snack-bar/snack-bar-container.ts
  src/material-experimental/mdc-snack-bar/snack-bar.spec.ts
  src/material/snack-bar/BUILD.bazel
  src/material/snack-bar/snack-bar-container.html
  src/material/snack-bar/snack-bar-container.ts
  src/material/snack-bar/snack-bar.spec.ts
  tools/public_api_guard/material/snack-bar.d.ts
Labels: P2, a11y, cla: yes, merge ready, target: patch

#21586 fix(material-experimental/mdc-chips): decouple removal from animation
  src/material-experimental/mdc-chips/chip-grid.spec.ts
  src/material-experimental/mdc-chips/chip-grid.ts
  src/material-experimental/mdc-chips/chip-remove.spec.ts
  src/material-experimental/mdc-chips/chip-row.spec.ts
  src/material-experimental/mdc-chips/chip-row.ts
  src/material-experimental/mdc-chips/chip.spec.ts
  src/material-experimental/mdc-chips/chip.ts
  src/material-experimental/mdc-chips/chips.scss
  src/material-experimental/mdc-chips/testing/chip-harness.ts
Labels: P2, cla: yes, merge ready, target: rc

#21467 fix(material/tooltip): not closing when clicking outside using auxiliary button
  src/material/tooltip/tooltip.spec.ts
  src/material/tooltip/tooltip.ts
Labels: P3, cla: yes, merge ready, target: patch

#21597 refactor(material/core): clean up deprecated API usages
  src/cdk-experimental/column-resize/event-dispatcher.ts
  src/cdk-experimental/dialog/dialog-ref.ts
  src/cdk/scrolling/virtual-for-of.ts
  src/cdk/scrolling/virtual-scroll-viewport.ts
  src/material-experimental/mdc-paginator/paginator.spec.ts
  src/material-experimental/mdc-tabs/tab-body.ts
  src/material/dialog/dialog-ref.ts
  src/material/expansion/expansion-panel.ts
  src/material/form-field/form-field.ts
  src/material/paginator/paginator.spec.ts
  src/material/tabs/tab-body.ts
  src/youtube-player/youtube-player.ts
  tools/public_api_guard/material/tabs.d.ts
Labels: P3, caretaker note, cla: yes, merge ready, target: patch

#21599 refactor(material-experimental/mdc-progress-bar): update mdc-progress-bar to be compatible with API changes in MDC
  package.json
  src/material-experimental/mdc-progress-bar/progress-bar.ts
  yarn.lock
Labels: caretaker note, cla: yes, merge ready, merge safe, target: rc

#21634 Revert "fix(material-experimental/mdc-chips): decouple removal from animation"
  src/material-experimental/mdc-chips/chip-grid.spec.ts
  src/material-experimental/mdc-chips/chip-grid.ts
  src/material-experimental/mdc-chips/chip-remove.spec.ts
  src/material-experimental/mdc-chips/chip-row.spec.ts
  src/material-experimental/mdc-chips/chip-row.ts
  src/material-experimental/mdc-chips/chip.spec.ts
  src/material-experimental/mdc-chips/chip.ts
  src/material-experimental/mdc-chips/chips.scss
  src/material-experimental/mdc-chips/testing/chip-harness.ts
Labels: cla: yes, merge ready, target: rc

#21645 feat(material-experimental/mdc-slider): add skeleton code for MDCSliderFoundation
  src/material-experimental/mdc-slider/slider-adapter.ts
  src/material-experimental/mdc-slider/slider.ts
Labels: cla: yes, merge ready, merge safe, target: feature branch

#21651 release: bump angular deps to 11.1.0
  package.json
  yarn.lock
Labels: cla: yes, merge ready, merge safe, target: rc

#21653 release: bump version to 11.1.0 w/ changelog
  CHANGELOG.md
  package.json
Labels: cla: yes, merge ready, merge safe, target: rc

#21654 release: copy 11.1.0 changelog to master
  CHANGELOG.md
Labels: cla: yes, merge ready, merge safe, target: minor

#21663 build: fix error from latest MDC canary
  package.json
  src/material-experimental/mdc-progress-bar/BUILD.bazel
  src/material-experimental/mdc-progress-bar/progress-bar.ts
  src/material-experimental/tsconfig-tests.json
  tsconfig.json
  yarn.lock
Labels: P2, cla: yes, merge ready, merge safe, target: patch

#21655 feat(material-experimental/mdc-slider): add skeleton code for MatSlid…
  src/material-experimental/mdc-slider/module.ts
  src/material-experimental/mdc-slider/public-api.ts
  src/material-experimental/mdc-slider/slider-thumb.ts
Labels: cla: yes, merge safe, target: feature branch

#21532 fix(material-experimental/mdc-radio): de-duplicate test harness logic
  scripts/check-mdc-exports-config.ts
  src/material-experimental/mdc-radio/testing/BUILD.bazel
  src/material-experimental/mdc-radio/testing/public-api.ts
  src/material-experimental/mdc-radio/testing/radio-harness-filters.ts
  src/material-experimental/mdc-radio/testing/radio-harness.ts
  src/material/radio/testing/radio-harness.ts
  tools/public_api_guard/material/radio/testing.d.ts
Labels: P3, cla: yes, merge ready, target: patch

#21506 refactor(material-experimental/mdc-checkbox): de-duplicate test harness logic
  scripts/check-mdc-exports-config.ts
  src/material-experimental/mdc-checkbox/testing/BUILD.bazel
  src/material-experimental/mdc-checkbox/testing/checkbox-harness.ts
  src/material/checkbox/testing/checkbox-harness.ts
  tools/public_api_guard/material/checkbox/testing.d.ts
Labels: P3, cla: yes, merge ready, target: patch

#21483 refactor(material-experimental/mdc-menu): de-duplicate test harness logic
  src/material-experimental/mdc-menu/testing/BUILD.bazel
  src/material-experimental/mdc-menu/testing/menu-harness.ts
  src/material/menu/testing/menu-harness.ts
  tools/public_api_guard/material/menu/testing.d.ts
Labels: P3, cla: yes, merge ready, target: patch

#21476 refactor(material-experimental/mdc-autocomplete): de-duplicate test harness logic
  src/material-experimental/mdc-autocomplete/testing/BUILD.bazel
  src/material-experimental/mdc-autocomplete/testing/autocomplete-harness.ts
  src/material/autocomplete/testing/autocomplete-harness.ts
  src/material/autocomplete/testing/shared.spec.ts
  tools/public_api_guard/material/autocomplete/testing.d.ts
Labels: P3, cla: yes, merge ready, target: patch

#21460 refactor(material-experimental/mdc-select): de-duplicate test harness logic
  src/material-experimental/mdc-select/testing/BUILD.bazel
  src/material-experimental/mdc-select/testing/select-harness.ts
  src/material/select/testing/select-harness.ts
  tools/public_api_guard/material/select/testing.d.ts
Labels: P3, cla: yes, merge ready, target: patch

#21668 fix(cdk/drag-drop): not detecting parent when projected using ngTemplateOutlet
  src/cdk/drag-drop/directives/drag.spec.ts
  src/cdk/drag-drop/directives/drag.ts
  src/cdk/drag-drop/drag-ref.ts
  tools/public_api_guard/cdk/drag-drop.d.ts
Labels: P3, cla: yes, merge ready, target: patch

#21646 fix(material/datepicker): mark date input as touched when calendar is closed
  src/material/datepicker/date-range-input.spec.ts
  src/material/datepicker/date-range-input.ts
  src/material/datepicker/datepicker-input.ts
  src/material/datepicker/datepicker.spec.ts
  tools/public_api_guard/material/datepicker.d.ts
Labels: P3, cla: yes, merge ready, target: patch

#21620 fix(material/form-field): flickering when hovering invalid input on chrome
  src/material/form-field/form-field.scss
Labels: P3, cla: yes, merge ready, target: patch

#21649 fix(material/autocomplete): prevent inert host node from affecting surrounding layout
  src/material-experimental/mdc-autocomplete/autocomplete.scss
  src/material/autocomplete/autocomplete.scss
Labels: P4, cla: yes, merge ready, target: patch

#21692 build: fix lint failures
  scripts/check-mdc-exports-config.ts
Labels: cla: yes, merge ready, merge safe, target: patch

#21519 refactor(material-experimental/mdc-paginator): de-duplicate test harness logic
  scripts/check-mdc-exports-config.ts
  src/material-experimental/mdc-paginator/testing/BUILD.bazel
  src/material-experimental/mdc-paginator/testing/paginator-harness-filters.ts
  src/material-experimental/mdc-paginator/testing/paginator-harness.ts
  src/material-experimental/mdc-paginator/testing/public-api.ts
  src/material/paginator/testing/paginator-harness.ts
  tools/public_api_guard/material/paginator/testing.d.ts
Labels: P3, cla: yes, merge ready, target: patch

#21624 fix(material-experimental/mdc-chips): set correct ripple opacity for …
  src/material-experimental/mdc-chips/_chips-theme.scss
Labels: G, P2, cla: yes, merge ready, target: patch

#21666 fix(cdk/overlay): overriding pointer-events style
  src/cdk/overlay/overlay-ref.ts
  src/cdk/overlay/overlay.spec.ts
Labels: P3, cla: yes, merge ready, target: patch

#21633 fix(material/datepicker): clear tabindex from host node
  src/material/datepicker/datepicker-toggle.ts
  src/material/datepicker/datepicker.spec.ts
Labels: P3, cla: yes, merge ready, target: patch

#21694 build: bump material-components-web
  package.json
  yarn.lock
Labels: cla: yes, merge ready, merge safe, target: patch

#21693 build: update to the latest version of @angular/dev-infra-private
  package.json
  yarn.lock
Labels: area: dev-infra, cla: yes, merge ready, merge safe, target: patch

#21669 fix(material-experimental/mdc-typography): fix always using mat-level
  src/material-experimental/mdc-helpers/_mdc-helpers.scss
Labels: P2, cla: yes, merge ready, target: patch

#21636 fix(material-experimental/mdc-chips): decouple removal from animation
  src/material-experimental/mdc-chips/chip-grid.spec.ts
  src/material-experimental/mdc-chips/chip-grid.ts
  src/material-experimental/mdc-chips/chip-remove.spec.ts
  src/material-experimental/mdc-chips/chip-row.spec.ts
  src/material-experimental/mdc-chips/chip-row.ts
  src/material-experimental/mdc-chips/chip.spec.ts
  src/material-experimental/mdc-chips/chip.ts
  src/material-experimental/mdc-chips/chips.scss
  src/material-experimental/mdc-chips/testing/chip-harness.ts
Labels: P2, caretaker note, cla: yes, merge ready, target: patch

#21718 release: bump version to 11.1.1 w/ changelog
  CHANGELOG.md
  package.json
Labels: cla: yes, merge ready, merge safe, target: patch

#21720 release: bump changelog to 11.1.1
  CHANGELOG.md
Labels: cla: yes, merge ready, merge safe

#21722 build: update bazel to 4.0.0
  .bazelversion
  WORKSPACE
Labels: area: build, cla: yes, merge ready, merge safe, target: patch

#21740 docs(material-experimental): fix scss examples
  src/material-experimental/mdc-autocomplete/README.md
  src/material-experimental/mdc-checkbox/README.md
  src/material-experimental/mdc-menu/README.md
  src/material-experimental/mdc-paginator/README.md
  src/material-experimental/mdc-progress-bar/README.md
  src/material-experimental/mdc-progress-spinner/README.md
  src/material-experimental/mdc-select/README.md
  src/material-experimental/mdc-slide-toggle/README.md
  src/material-experimental/mdc-tabs/README.md
Labels: cla: yes, docs, merge ready, merge safe, target: patch
