Repository angular/components, pull requests merged in 2021-12, with the labels that each got.

#24039 Bump version to "v13.0.3" with changelog.
  CHANGELOG.md
  package.json
Labels: cla: yes

#24040 docs: release notes for the v13.0.3 release
  CHANGELOG.md
Labels: cla: yes

#24041 Bump version to "v13.1.0-next.3" with changelog.
  CHANGELOG.md
  package.json
Labels: cla: yes

#24004 fix(material-experimental/mdc-checkbox): reduce amount of emitted theme css
  src/material-experimental/mdc-checkbox/_checkbox-theme.scss
Labels: cla: yes, P2, merge ready, target: patch

#23934 fix(cdk/drag-drop): last item not returned at initial index when sorting is disabled
  src/cdk/drag-drop/directives/drag.spec.ts
  src/cdk/drag-drop/drop-list-ref.ts
Labels: cla: yes, P3, merge ready, target: patch

#24007 fix(cdk-experimental/column-resize): Ensure resizable entity is not d…
  src/cdk-experimental/column-resize/resizable.ts
Labels: cla: yes, merge ready, G, target: patch, area: material/table

#23908 fix(material-experimental/column-resize): Update for MDC and spec cha…
  src/material-experimental/column-resize/_column-resize-theme.scss
  src/material-experimental/column-resize/column-resize.spec.ts
  src/material-experimental/column-resize/overlay-handle.ts
Labels: cla: yes, merge ready, G, target: patch, area: cdk/table

#24012 feat(material/core): change ErrorStateMatcher to accept AbstractForm
  src/material/core/error/error-options.ts
  tools/public_api_guard/material/core.md
Labels: cla: yes, merge ready, target: minor

#24014 Fix missing method parameter documentation
  tools/dgeni/templates/method.template.html
Labels: cla: yes, merge ready, merge safe, target: patch

#23882 build: run partial compilation tests with linker JIT
  .circleci/config.yml
  integration/linker/BUILD.bazel
  package.json
  tools/BUILD.bazel
  tools/defaults.bzl
Labels: cla: yes, P2, merge ready, merge safe, target: patch

#24027 feat(material-luxon-adapter): add option to set first day of week
  src/material-luxon-adapter/adapter/luxon-date-adapter.spec.ts
  src/material-luxon-adapter/adapter/luxon-date-adapter.ts
Labels: cla: yes, P3, merge ready, target: minor

#24061 fix(material-experimental/mdc-slider): throw error when thumb is missing
  src/material-experimental/mdc-slider/slider.ts
Labels: cla: yes, P3, merge ready, target: patch

#24048 build: update to typescript 4.5 and angular 13.1
  integration/ts-compat/BUILD.bazel
  package.json
  scripts/caretaking/firebase-functions/package.json
  scripts/caretaking/firebase-functions/yarn.lock
  src/cdk/schematics/utils/build-component.ts
  src/material/schematics/ng-update/migrations/hammer-gestures-v9/import-manager.ts
  yarn.lock
Labels: cla: yes, P2, merge ready, merge safe, target: minor

#24031 docs(material/prebuilt-themes): fix wrong theme filename
  guides/theming.md
Labels: cla: yes, P3, docs, merge ready, merge safe, target: patch, commit message fixup

#23707 docs(material/datepicker): use two-way data-binding
  src/components-examples/material/datepicker/datepicker-inline-calendar/datepicker-inline-calendar-example.html
Labels: cla: yes, docs, merge ready, merge safe, target: patch

#23688 docs(material/chips): use defaults for input bindings
  src/components-examples/material/chips/chips-autocomplete/chips-autocomplete-example.html
  src/components-examples/material/chips/chips-autocomplete/chips-autocomplete-example.ts
  src/components-examples/material/chips/chips-input/chips-input-example.html
  src/components-examples/material/chips/chips-input/chips-input-example.ts
Labels: cla: yes, merge ready, merge safe, target: patch

#24064 build: fix formatting failure
  src/cdk/overlay/dispatchers/overlay-outside-click-dispatcher.ts
Labels: P2, merge ready, merge safe, target: patch

#24070 Bump version to "v13.1.0-rc.0" with changelog.
  CHANGELOG.md
  package.json
Labels: merge ready

#24071 Update next branch to reflect new release-train "v13.2.0-next.0".
  CHANGELOG.md
  package.json
Labels: merge ready

#24072 Bump version to "v13.1.0" with changelog.
  CHANGELOG.md
  package.json
Labels: merge ready

#24073 docs: release notes for the v13.1.0 release
  CHANGELOG.md
Labels: merge ready

#24063 feat(material-experimental/mdc-core): add missing color, density, typography mixins
  src/material-experimental/_index.scss
  src/material-experimental/mdc-core/_core-theme.scss
Labels: P2, merge ready, G, target: minor

#24076 refactor(material-experimental/mdc-list): account for mdc-list handleClick signature change
  package.json
  packages.bzl
  src/material-experimental/mdc-list/interactive-list-base.ts
  yarn.lock
Labels: merge ready, target: patch

#24084 build: bump to Angular 13.1
  package.json
  yarn.lock
Labels: P3, merge ready, merge safe, target: patch

#24074 test(material/snack-bar): fix error logs in tests
  src/material-experimental/mdc-snack-bar/snack-bar.spec.ts
  src/material/snack-bar/snack-bar.spec.ts
Labels: P3, merge ready, merge safe, target: patch

#24091 fix(material/tabs): remove CSS content from chevron element
  src/material-experimental/mdc-tabs/_tabs-common.scss
  src/material/tabs/_tabs-common.scss
Labels: P3, merge ready, target: patch

#24025 fix(material/stepper): assistive technology reading out stepper icon
  src/material/stepper/step-header.html
  src/material/stepper/stepper.spec.ts
Labels: cla: yes, P3, a11y, merge ready, target: patch

#24021 fix(material/schematics): don't replace variables contained within the names of other variables in theming API migration
  src/material/schematics/ng-update/migrations/theming-api-v12/migration.ts
  src/material/schematics/ng-update/test-cases/v12/misc/theming-api-v12.spec.ts
Labels: cla: yes, P3, merge ready, merge safe, target: patch

#24115 refactor(material/schematics): clean up workaround for TS 4.5
  src/material/schematics/ng-update/migrations/hammer-gestures-v9/import-manager.ts
Labels: P3, merge ready, merge safe, target: patch

#24105 fix(material-experimental/mdc-slide-toggle): remove aria-required rather than setting to false
  src/material-experimental/mdc-slide-toggle/slide-toggle.html
  src/material-experimental/mdc-slide-toggle/slide-toggle.spec.ts
Labels: P2, merge ready, G, target: patch

#24114 build: run integration tests in sandbox and with RBE
  .bazelrc
  integration/ng-add/BUILD.bazel
  integration/ng-add/karma.conf.js
  integration/ng-add/package.json
  integration/ng-add/yarn.lock
  integration/ng-update-v13/BUILD.bazel
  integration/ng-update-v13/package.json
  integration/ng-update-v13/yarn.lock
  tools/defaults.bzl
Labels: P2, merge ready, merge safe, target: patch

#24085 fix(material/datepicker): fix duplicate nav stop with Voiceover
  src/material/datepicker/calendar-body.html
Labels: a11y, merge ready, target: patch, area: material/datepicker

#24077 fix(multiple): correct tooltip and table MDC style import paths
  src/material-experimental/mdc-table/_table-theme.scss
  src/material-experimental/mdc-tooltip/_tooltip-theme.scss
Labels: P3, merge ready, caretaker note, target: patch

#24023 docs(theming): fix seprate typo
  guides/theming.md
Labels: merge ready, merge safe, target: patch, commit message fixup
