Repository angular/components, pull requests merged in 2021-02, with the labels that each got.

#21744 fix(cdk/collections): recycle repeater strategy retaining references to destroyed views
  src/cdk/collections/recycle-view-repeater-strategy.ts
Labels: P3, cla: yes, merge ready, target: patch

#21721 build: update to latest ts-api-guardian and fix error
  package.json
  src/material/grid-list/public-api.ts
  tools/public_api_guard/generate-guard-tests.bzl
  tools/public_api_guard/material/grid-list.d.ts
  yarn.lock
Labels: P3, cla: yes, merge ready, merge safe, target: patch

#21716 fix(material/select): overlay offset calculation for disabled option centering
  scripts/check-mdc-tests-config.ts
  src/material/select/select.spec.ts
  src/material/select/select.ts
Labels: P3, cla: yes, merge ready, target: patch

#21702 fix(material-experimental/mdc-dialog): afterClosed being run outside of NgZone
  src/material-experimental/mdc-dialog/dialog-container.ts
  src/material-experimental/mdc-dialog/dialog.spec.ts
  src/material/dialog/dialog.spec.ts
Labels: G, P2, cla: yes, merge ready, target: patch

#21648 feat(material/sort): Add default configuration options
  src/material/sort/sort.spec.ts
  src/material/sort/sort.ts
  tools/public_api_guard/material/sort.d.ts
Labels: G, P2, area: material/sort, cla: yes, merge ready, target: minor

#21591 fix(material/datepicker): reset preview range after selecting a date
  src/material/datepicker/month-view.spec.ts
  src/material/datepicker/month-view.ts
Labels: P3, cla: yes, merge ready, target: patch

#21531 fix(material/menu): nested menu trigger not restoring focus
  src/material-experimental/mdc-menu/menu.spec.ts
  src/material/menu/menu-trigger.ts
  src/material/menu/menu.spec.ts
  src/material/menu/menu.ts
  tools/public_api_guard/material/menu.d.ts
Labels: P2, a11y, cla: yes, merge ready, target: patch

#21754 fix(material/schematics): fix typo in warning
  src/material/schematics/ng-add/setup-project.ts
Labels: P4, cla: yes, merge ready, merge safe, target: patch

#21733 fix(material/select): VoiceOver reading out blank space
  src/material-experimental/mdc-select/select.html
  src/material-experimental/mdc-select/select.scss
  src/material/select/select.html
  src/material/select/select.scss
Labels: P3, a11y, cla: yes, merge ready, target: patch

#21723 Update MapGroundOverlay doc for class reference error
  src/google-maps/map-ground-overlay/README.md
Labels: cla: yes, docs, merge ready, merge safe, target: patch

#21704 feat(cdk/table): add HTML elements to sticky styler state
  src/cdk/table/sticky-position-listener.ts
  src/cdk/table/sticky-styler.ts
  src/cdk/table/table.spec.ts
  tools/public_api_guard/cdk/table.d.ts
Labels: G, P2, area: cdk/table, cla: yes, merge ready, target: patch

#21772 fix(material-experimental/mdc-form-field): remove extraneous sass var…
  src/material-experimental/mdc-form-field/_form-field-sizing.scss
Labels: P2, cla: yes, merge ready, merge safe, target: patch

#21549 fix(material/expansion): add focus indication in high contrast mode
  src/material/expansion/_expansion-mixins.scss
  src/material/expansion/_expansion-theme.scss
  src/material/expansion/expansion-panel-header.scss
Labels: P3, a11y, cla: yes, merge ready, target: patch

#21800 build: bump master branch version to 12.0.0-next.0
  package.json
Labels: cla: yes, merge ready, target: major

#21799 release: bump version to 11.2.0-rc.0 w/ changelog
  CHANGELOG.md
  package.json
Labels: cla: yes, merge ready, target: rc

#21801 release: update changelog w/ 11.2.0-rc.0
  CHANGELOG.md
Labels: cla: yes, merge ready, target: major

#21804 release: bump version to 11.1.2 w/ changelog
  CHANGELOG.md
  package.json
Labels: cla: yes, merge ready, target: patch

#21807 release: update changelog w/ 11.1.2
  CHANGELOG.md
Labels: cla: yes, merge ready, merge safe

#21753 refactor(google-maps): clean up clusterer internal setup
  src/google-maps/map-marker-clusterer/map-marker-clusterer.ts
  tools/public_api_guard/google-maps/google-maps.d.ts
Labels: P3, cla: yes, merge ready, target: patch

#21769 feat(cdk/a11y): allow focus options to be passed in to focus trap
  src/cdk/a11y/focus-trap/focus-trap.spec.ts
  src/cdk/a11y/focus-trap/focus-trap.ts
  tools/public_api_guard/cdk/a11y.d.ts
Labels: P3, cla: yes, merge ready, target: minor

#21798 fix(cdk/platform): adjust return type for _getShadowRoot
  src/cdk/a11y/focus-monitor/focus-monitor.ts
  src/cdk/drag-drop/drag-ref.ts
  src/cdk/drag-drop/drop-list-ref.ts
  src/cdk/platform/features/shadow-dom.ts
  src/material/progress-spinner/progress-spinner.spec.ts
  tools/public_api_guard/cdk/platform.d.ts
Labels: P3, cla: yes, merge ready, target: patch

#21736 feat(google-maps): Add MapDirectionsRenderer and MapDirectionsService
  .gitignore
  src/dev-app/BUILD.bazel
  src/dev-app/google-map/google-map-demo.html
  src/dev-app/google-map/google-map-demo.ts
  src/dev-app/index.html
  src/google-maps/README.md
  src/google-maps/google-maps-module.ts
  src/google-maps/map-directions-renderer/README.md
  src/google-maps/map-directions-renderer/map-directions-renderer.spec.ts
  src/google-maps/map-directions-renderer/map-directions-renderer.ts
  src/google-maps/map-directions-renderer/map-directions-service.spec.ts
  src/google-maps/map-directions-renderer/map-directions-service.ts
  src/google-maps/public-api.ts
  src/google-maps/testing/fake-google-map-utils.ts
  tools/public_api_guard/google-maps/google-maps.d.ts
Labels: area: google-maps, cla: yes, feature, merge ready, target: minor

#21358 feat(material/list): return selected options from selection list selectAll/deselectAll
  src/material-experimental/mdc-list/selection-list.spec.ts
  src/material-experimental/mdc-list/selection-list.ts
  src/material/list/selection-list.spec.ts
  src/material/list/selection-list.ts
  tools/public_api_guard/material/list.d.ts
Labels: P4, cla: yes, merge ready, target: minor

#21402 fix(material/tabs): strong focus indicator not visible when tab header has a background
  src/material-experimental/mdc-tabs/_tabs-theme.scss
  src/material/tabs/_tabs-theme.scss
Labels: P4, a11y, cla: yes, merge ready, target: patch

#21508 feat(cdk/table) add directive to enable recycle view repeater
  src/cdk/table/table-module.ts
  src/cdk/table/table.ts
  src/components-examples/cdk/table/cdk-table-recycle-rows/cdk-table-recycle-rows-example.css
  src/components-examples/cdk/table/cdk-table-recycle-rows/cdk-table-recycle-rows-example.html
  src/components-examples/cdk/table/cdk-table-recycle-rows/cdk-table-recycle-rows-example.ts
  src/components-examples/cdk/table/index.ts
  src/components-examples/material/table/index.ts
  src/components-examples/material/table/table-recycle-rows/table-recycle-rows-example.css
  src/components-examples/material/table/table-recycle-rows/table-recycle-rows-example.html
  src/components-examples/material/table/table-recycle-rows/table-recycle-rows-example.ts
  src/dev-app/table/table-demo.html
  src/material-experimental/mdc-table/module.ts
  src/material-experimental/mdc-table/table.ts
  src/material/table/table-module.ts
  src/material/table/table.ts
  tools/public_api_guard/cdk/table.d.ts
  tools/public_api_guard/material/table.d.ts
Labels: G, P2, area: cdk/table, area: material/table, cla: yes, merge ready, target: minor

#21585 feat(material-experimental/mdc-button): add extended fab
  src/dev-app/mdc-button/mdc-button-demo.html
  src/material-experimental/mdc-button/button.spec.ts
  src/material-experimental/mdc-button/fab.scss
  src/material-experimental/mdc-button/fab.ts
  src/material-experimental/mdc-button/module.ts
Labels: G, P2, cla: yes, merge ready, target: patch

#21750 docs: fix input text color to match theme in custom form guide
  guides/creating-a-custom-form-field-control.md
Labels: P2, a11y, area: material/form-field, cla: yes, docs, merge ready, target: patch

#21752 fix(cdk/drag-drop): not blocking initial move event
  src/cdk/drag-drop/directives/drag.spec.ts
  src/cdk/drag-drop/drag-ref.ts
Labels: P2, cla: yes, merge ready, target: patch

#20968 fix(material/menu): unable to move focus from inside opened event
  src/material-experimental/mdc-menu/menu.spec.ts
  src/material/menu/menu-trigger.ts
  src/material/menu/menu.spec.ts
Labels: P3, cla: yes, merge ready, target: patch

#21746 fix(material-experimental/mdc-tabs): support backgroundColor on nav bar
  src/material-experimental/mdc-tabs/_tabs-theme.scss
Labels: P3, cla: yes, merge ready, target: patch

#21747 refactor(material-experimental/mdc-slide-toggle): de-duplicate test harness logic
  scripts/check-mdc-exports-config.ts
  src/material-experimental/mdc-slide-toggle/testing/BUILD.bazel
  src/material-experimental/mdc-slide-toggle/testing/slide-toggle-harness.ts
  src/material/slide-toggle/testing/slide-toggle-harness.ts
  tools/public_api_guard/material/slide-toggle/testing.d.ts
Labels: P3, cla: yes, merge ready, target: patch

#21751 docs: create anchors for all header elems & fix a11y in guides
  guides/bidirectionality.md
  guides/creating-a-custom-form-field-control.md
  guides/creating-a-custom-stepper-using-the-cdk-stepper.md
  guides/customizing-component-styles.md
  guides/duplicate-theming-styles.md
  guides/elevation.md
  guides/getting-started.md
  guides/schematics.md
  guides/theming-your-components.md
  guides/theming.md
  guides/typography.md
  guides/using-component-harnesses.md
  guides/v9-hammerjs-migration.md
  tools/markdown-to-html/docs-marked-renderer.ts
Labels: P2, a11y, cla: yes, docs, merge ready, merge safe, target: patch

#21788 docs(material/sidenav): add sidenav harness example
  src/components-examples/material/sidenav/BUILD.bazel
  src/components-examples/material/sidenav/index.ts
  src/components-examples/material/sidenav/sidenav-harness/sidenav-harness-example.html
  src/components-examples/material/sidenav/sidenav-harness/sidenav-harness-example.spec.ts
  src/components-examples/material/sidenav/sidenav-harness/sidenav-harness-example.ts
Labels: P3, cla: yes, docs, merge ready, merge safe, target: patch

#21790 docs(material/snack-bar): add harness example for snack bar
  src/components-examples/material/snack-bar/BUILD.bazel
  src/components-examples/material/snack-bar/index.ts
  src/components-examples/material/snack-bar/snack-bar-harness/snack-bar-harness-example.html
  src/components-examples/material/snack-bar/snack-bar-harness/snack-bar-harness-example.spec.ts
  src/components-examples/material/snack-bar/snack-bar-harness/snack-bar-harness-example.ts
Labels: P3, cla: yes, docs, merge ready, merge safe, target: patch

#21766 build: a couple of minor improvements to the dev app
  src/dev-app/dev-app/dev-app-layout.html
  src/dev-app/dev-app/dev-app-layout.scss
Labels: P4, cla: yes, merge ready, merge safe, target: patch

#21812 build: resolve circular dependencies in e2e code
  goldens/ts-circular-deps.json
  src/cdk/testing/private/e2e/actions.ts
  src/cdk/testing/private/e2e/asserts.ts
  src/cdk/testing/private/e2e/query.ts
Labels: P4, cla: yes, merge ready, merge safe, target: patch

#21246 fix(material/menu): prevent mat-menu from affecting flex layout
  src/material-experimental/mdc-menu/menu.scss
  src/material/menu/menu.scss
Labels: G, P3, cla: yes, merge ready, target: patch

#15817 feat(material/stepper): allow for content to be rendered lazily
  src/components-examples/material/stepper/index.ts
  src/components-examples/material/stepper/stepper-lazy-content/stepper-lazy-content-example.css
  src/components-examples/material/stepper/stepper-lazy-content/stepper-lazy-content-example.html
  src/components-examples/material/stepper/stepper-lazy-content/stepper-lazy-content-example.ts
  src/material/stepper/public-api.ts
  src/material/stepper/step-content.ts
  src/material/stepper/step.html
  src/material/stepper/stepper-module.ts
  src/material/stepper/stepper.md
  src/material/stepper/stepper.spec.ts
  src/material/stepper/stepper.ts
  tools/public_api_guard/material/stepper.d.ts
Labels: P3, cla: yes, merge ready, target: minor

#21489 feat(google-maps): add heatmap support
  package.json
  src/dev-app/google-map/google-map-demo.html
  src/dev-app/google-map/google-map-demo.ts
  src/dev-app/index.html
  src/google-maps/README.md
  src/google-maps/google-maps-module.ts
  src/google-maps/map-heatmap-layer/README.md
  src/google-maps/map-heatmap-layer/map-heatmap-layer.spec.ts
  src/google-maps/map-heatmap-layer/map-heatmap-layer.ts
  src/google-maps/package.json
  src/google-maps/public-api.ts
  src/google-maps/testing/fake-google-map-utils.ts
  src/universal-app/kitchen-sink/kitchen-sink.html
  tools/public_api_guard/google-maps/google-maps.d.ts
  yarn.lock
Labels: P3, cla: yes, merge ready, target: minor

#21735 feat(material-experimental/mdc-tooltip): implement MDC-based tooltip
  .github/CODEOWNERS
  .ng-dev/commit-message.ts
  rollup-globals.bzl
  scripts/check-mdc-exports-config.ts
  src/dev-app/BUILD.bazel
  src/dev-app/dev-app/dev-app-layout.ts
  src/dev-app/dev-app/routes.ts
  src/dev-app/mdc-tooltip/BUILD.bazel
  src/dev-app/mdc-tooltip/mdc-tooltip-demo-module.ts
  src/dev-app/mdc-tooltip/mdc-tooltip-demo.html
  src/dev-app/mdc-tooltip/mdc-tooltip-demo.scss
  src/dev-app/mdc-tooltip/mdc-tooltip-demo.ts
  src/e2e-app/devserver-configure.js
  src/material-experimental/config.bzl
  src/material-experimental/mdc-theming/BUILD.bazel
  src/material-experimental/mdc-theming/_all-theme.scss
  src/material-experimental/mdc-tooltip/BUILD.bazel
  src/material-experimental/mdc-tooltip/README.md
  src/material-experimental/mdc-tooltip/_tooltip-theme.scss
  src/material-experimental/mdc-tooltip/index.ts
  src/material-experimental/mdc-tooltip/module.ts
  src/material-experimental/mdc-tooltip/public-api.ts
  src/material-experimental/mdc-tooltip/tooltip-animations.ts
  src/material-experimental/mdc-tooltip/tooltip.html
  src/material-experimental/mdc-tooltip/tooltip.scss
  src/material-experimental/mdc-tooltip/tooltip.spec.ts
  src/material-experimental/mdc-tooltip/tooltip.ts
  src/material-experimental/mdc_require_config.js
  src/material/tooltip/tooltip.ts
  tools/public_api_guard/material/tooltip.d.ts
  tools/system-config-tmpl.js
Labels: P2, cla: yes, merge ready, target: minor

#21820 fix(material-experimental/mdc-form-field): allow shrinking in grid/flex layouts
  src/material-experimental/mdc-form-field/form-field.scss
Labels: G, P2, cla: yes, merge ready, target: minor

#21809 refactor(cdk/testing): change deprecated APIs for v12
  src/cdk/testing/test-element.ts
  src/cdk/testing/tests/cross-environment.spec.ts
  src/material/datepicker/testing/datepicker-input-harness-base.ts
  src/material/input/testing/input-harness.ts
  src/material/input/testing/native-select-harness.ts
  tools/public_api_guard/cdk/testing.d.ts
Labels: P2, cla: yes, merge ready, target: major

#13361 fix(select): not marking options as selected correctly when setting value with duplicates
  src/material/select/select.spec.ts
  src/material/select/select.ts
Labels: P3, cla: yes, merge ready, target: patch

#15094 fix(tabs): focusChange not being emitted when tabbing into a tab header
  src/material/tabs/tab-group.html
  src/material/tabs/tab-group.spec.ts
  src/material/tabs/tab-group.ts
  tools/public_api_guard/material/tabs.d.ts
Labels: P3, cla: yes, merge ready, target: patch

#16344 fix(tabs): mark tab body as a scrollable container
  src/material/tabs/tab-body.html
  src/material/tabs/tab-body.spec.ts
Labels: P3, cla: yes, merge ready, target: patch

#17976 fix(material/stepper): last step not being marked as interacted
  src/cdk/stepper/stepper.ts
  src/material/stepper/stepper.spec.ts
Labels: P3, cla: yes, merge ready, target: patch

#21079 refactor(google-maps): clean up internal setup
  src/google-maps/google-map/google-map.ts
  tools/public_api_guard/google-maps/google-maps.d.ts
Labels: P3, cla: yes, merge ready, target: patch

#21220 fix(material/tooltip): handle touch devices in test harness
  src/material/tooltip/testing/BUILD.bazel
  src/material/tooltip/testing/shared.spec.ts
  src/material/tooltip/testing/tooltip-harness.ts
Labels: P3, cla: yes, merge ready, target: patch

#21619 fix(material/input): uncessary scroll bar on auto-resize textarea in some cases
  src/material/form-field/form-field-input.scss
Labels: P3, caretaker note, cla: yes, merge ready, target: patch

#21796 fix(material/datepicker): focus restoration not working inside shadow dom
  src/material/datepicker/BUILD.bazel
  src/material/datepicker/datepicker-base.ts
  src/material/datepicker/datepicker.spec.ts
Labels: P3, cla: yes, merge ready, target: minor

#21805 fix(material/form-field): focus indication not working for standard appearance in high contrast mode
  src/material/form-field/form-field-standard.scss
Labels: P3, a11y, cla: yes, merge ready, target: patch

#21825 build: set up generic way of passing in environment variables to dev app
  .gitignore
  src/dev-app/BUILD.bazel
  src/dev-app/index.html
  tools/dev-server/dev-server.ts
Labels: P3, cla: yes, merge ready, merge safe, target: minor

#21850 build: fix test failures and add missing tests
  src/material-experimental/mdc-select/select.spec.ts
  src/material-experimental/mdc-tabs/tab-body.html
  src/material-experimental/mdc-tabs/tab-body.spec.ts
  src/material-experimental/mdc-tabs/tab-group.html
  src/material-experimental/mdc-tabs/tab-group.spec.ts
  src/material/tabs/tab-group.spec.ts
Labels: P2, cla: yes, merge ready, merge safe, target: patch

#21864 release: bump version to 11.2.0 w/ changelog
  CHANGELOG.md
  package.json
Labels: cla: yes, merge ready, merge safe, target: minor

#21865 release: copy over changelog for 11.2.0
  CHANGELOG.md
Labels: cla: yes, merge ready, merge safe, target: minor

#21625 fix(material/select): value not updated if the same array is updated and re-assigned
  src/material-experimental/mdc-select/select.spec.ts
  src/material/select/select.spec.ts
  src/material/select/select.ts
Labels: P3, cla: yes, merge ready, target: patch

#21609 fix(material/input): only set as aria-invalid if the input isn't empty
  src/material-experimental/mdc-input/input.spec.ts
  src/material-experimental/mdc-input/input.ts
  src/material/input/input.spec.ts
  src/material/input/input.ts
Labels: P3, a11y, cla: yes, merge ready, target: patch

#15217 feat(material/tooltip): add class to tooltip element based on the current position
  src/material-experimental/mdc-tooltip/tooltip.spec.ts
  src/material/tooltip/tooltip.md
  src/material/tooltip/tooltip.spec.ts
  src/material/tooltip/tooltip.ts
Labels: P3, cla: yes, merge ready, target: minor

#16756 fix(material/tooltip): clear pending timers on destroy
  src/material-experimental/mdc-tooltip/tooltip.spec.ts
  src/material/tooltip/tooltip.spec.ts
  src/material/tooltip/tooltip.ts
  tools/public_api_guard/material/tooltip.d.ts
Labels: P3, cla: yes, merge ready, target: minor

#21885 build: update to Angular 12
  .circleci/config.yml
  package.json
  src/cdk/schematics/ng-update/migrations/property-names.ts
  yarn.lock
Labels: P2, cla: yes, merge ready, merge safe, target: major

#21821 fix(cdk/drag-drop): destroyed items not being cleaned up correctly
  src/cdk/drag-drop/directives/drag.ts
Labels: P2, cla: yes, merge ready, target: patch

#21855 feat(material-experimental/mdc-tooltip): add test harness
  scripts/check-mdc-exports-config.ts
  src/material-experimental/config.bzl
  src/material-experimental/mdc-tooltip/testing/BUILD.bazel
  src/material-experimental/mdc-tooltip/testing/index.ts
  src/material-experimental/mdc-tooltip/testing/public-api.ts
  src/material-experimental/mdc-tooltip/testing/tooltip-harness.spec.ts
  src/material-experimental/mdc-tooltip/testing/tooltip-harness.ts
  src/material/tooltip/testing/tooltip-harness.ts
  tools/public_api_guard/material/tooltip/testing.d.ts
Labels: P2, cla: yes, merge ready, target: minor

#21830 feat(cdk/drag-drop): allow for preview container to be customized
  src/cdk/drag-drop/directives/config.ts
  src/cdk/drag-drop/directives/drag.spec.ts
  src/cdk/drag-drop/directives/drag.ts
  src/cdk/drag-drop/drag-drop.md
  src/cdk/drag-drop/drag-ref.ts
  src/cdk/drag-drop/public-api.ts
  src/dev-app/drag-drop/drag-drop-demo.scss
  tools/public_api_guard/cdk/drag-drop.d.ts
Labels: P3, cla: yes, merge ready, target: minor

#21832 feat(google-maps): add geocoder wrapper
  src/google-maps/README.md
  src/google-maps/map-geocoder/README.md
  src/google-maps/map-geocoder/map-geocoder.spec.ts
  src/google-maps/map-geocoder/map-geocoder.ts
  src/google-maps/public-api.ts
  src/google-maps/testing/fake-google-map-utils.ts
  tools/public_api_guard/google-maps/google-maps.d.ts
Labels: P3, cla: yes, merge ready, target: minor

#21841 build: update to latest jasmine and resolve errors
  package.json
  tslint.json
  yarn.lock
Labels: P3, cla: yes, merge ready, merge safe, target: patch

#21842 fix(material/stepper): don't allow focus inside a hidden element
  src/material/stepper/stepper-animations.ts
Labels: P3, cla: yes, merge ready, target: patch

#21856 fix(material/datepicker): avoid interfering with external click listener
  src/material/datepicker/datepicker-toggle.html
  src/material/datepicker/datepicker-toggle.ts
Labels: P3, caretaker note, cla: yes, merge ready, target: patch

#21861 feat(google-maps): support options object on marker clusterer
  src/google-maps/map-marker-clusterer/map-marker-clusterer.spec.ts
  src/google-maps/map-marker-clusterer/map-marker-clusterer.ts
  src/google-maps/map-marker-clusterer/marker-clusterer-types.ts
  src/google-maps/testing/fake-google-map-utils.ts
  tools/public_api_guard/google-maps/google-maps.d.ts
Labels: P3, cla: yes, merge ready, target: minor

#21810 docs(material/core): show typography as part of the theme
  guides/theming.md
  guides/typography.md
  src/material-experimental/README.md
Labels: cla: yes, docs, merge ready, merge safe, target: minor

#21824 fix(material/theming): change to update comments in theming
  src/material/core/theming/_theming.scss
Labels: cla: yes, merge ready, merge safe, target: patch

#21917 fix(google-maps): correct minor typo in the code
  src/google-maps/map-circle/map-circle.ts
Labels: cla: yes, docs, merge ready, merge safe, target: patch

#21915 fix(google-maps): correct minor typo in the code
  src/google-maps/map-marker/map-marker.ts
Labels: cla: yes, docs, merge ready, merge safe, target: patch

#21913 docs: use BooleanInput in examples for custom control
  src/components-examples/material-experimental/mdc-form-field/mdc-form-field-custom-control/form-field-custom-control-example.ts
  src/components-examples/material/form-field/form-field-custom-control/form-field-custom-control-example.ts
Labels: cla: yes, docs, merge ready, merge safe, target: patch

#21908 docs: radius typed instead of assigned
  src/google-maps/map-circle/README.md
Labels: cla: yes, docs, merge ready, merge safe, target: patch

#21921 docs(material/table): additional details on table data sources
  src/material/table/table.md
Labels: cla: yes, commit message fixup, docs, merge ready, merge safe, target: patch

#21906 docs: pass ElementRef<HTMLElement> as is into FocusMonitor methods
  guides/creating-a-custom-form-field-control.md
Labels: cla: yes, docs, merge ready, merge safe, target: patch

#21905 docs: implement ControlValueAccessor in the code snippet
  guides/creating-a-custom-form-field-control.md
Labels: cla: yes, docs, merge ready, merge safe, target: patch

#21899 docs: typo in changelog
  CHANGELOG.md
Labels: cla: yes, docs, merge ready, merge safe, target: patch

#21879 docs: document button-toggle-group usage with forms(+add example)
  src/components-examples/material/button-toggle/button-toggle-forms/button-toggle-forms-example.html
  src/components-examples/material/button-toggle/button-toggle-forms/button-toggle-forms-example.ts
  src/components-examples/material/button-toggle/index.ts
  src/material/button-toggle/button-toggle.md
Labels: cla: yes, docs, merge ready, merge safe, target: patch

#21933 release: bump version to 11.2.1 w/ changelog
  CHANGELOG.md
  package.json
Labels: cla: yes, merge ready, target: patch

#21878 fix(material-experimental/mdc-typography): strip typography properties
  src/material-experimental/mdc-helpers/_mdc-helpers.scss
Labels: G, P2, cla: yes, merge ready, target: patch

#21877 refactor(cdk/table): change deprecated APIs for v12
  src/cdk/schematics/ng-update/data/constructor-checks.ts
  src/cdk/table/sticky-styler.ts
  src/cdk/table/table.ts
  src/material-experimental/mdc-table/table.ts
  src/material/table/table.ts
  tools/public_api_guard/cdk/table.d.ts
Labels: P2, cla: yes, merge ready, target: major

#21897 refactor(material/tooltip): change deprecated APIs for v12
  src/material-experimental/mdc-tooltip/tooltip.ts
  src/material/schematics/ng-update/data/constructor-checks.ts
  src/material/tooltip/tooltip.ts
  tools/public_api_guard/material/tooltip.d.ts
Labels: P2, cla: yes, merge ready, target: major

#21909 fix(google-maps): mapTypeId not being set from options
  src/google-maps/google-map/google-map.spec.ts
  src/google-maps/google-map/google-map.ts
Labels: P2, cla: yes, merge ready, target: patch

#21858 fix(material/core): mat-optgroup labels are read twice during screen-reader page navigation
  src/material-experimental/mdc-core/option/optgroup.html
  src/material-experimental/mdc-select/select.spec.ts
  src/material/core/option/optgroup.html
  src/material/select/select.spec.ts
Labels: G, P3, a11y, cla: yes, merge ready, target: patch

#21896 fix(cdk/overlay): not setting correct opacity in high contrast mode on Firefox
  CODING_STANDARDS.md
  src/cdk/overlay/BUILD.bazel
  src/cdk/overlay/_overlay.scss
Labels: G, P3, a11y, cla: yes, merge ready, target: patch

#21919 fix(material-experimental/mdc-button): fix incomplete icon class targ…
  src/material-experimental/mdc-button/fab.scss
Labels: G, P3, cla: yes, merge ready, target: patch

#21895 fix(material-experimental/mdc-paginator): use MDC-based tooltip
  src/material-experimental/mdc-paginator/BUILD.bazel
  src/material-experimental/mdc-paginator/paginator-module.ts
  src/material-experimental/mdc-paginator/testing/BUILD.bazel
  src/material-experimental/mdc-table/BUILD.bazel
Labels: P3, cla: yes, merge ready, target: minor

#21900 refactor(material-experimental/mdc-form-field): de-duplicate test harness logic
  scripts/check-mdc-exports-config.ts
  src/material-experimental/mdc-form-field/testing/form-field-harness.ts
  src/material/form-field/testing/form-field-harness.ts
  tools/public_api_guard/material/form-field/testing.d.ts
Labels: P3, cla: yes, merge ready, target: patch

#21509 refactor(material-experimental/mdc-core): rename sass theme file
  src/material-experimental/mdc-core/_core-theme.scss
  src/material-experimental/mdc-theming/_all-theme.scss
Labels: caretaker note, cla: yes, merge ready, target: patch

#21953 fix(material-experimental/mdc-core): rename core import file
  src/material-experimental/mdc-core/_core-theme.import.scss
  src/material-experimental/mdc-theming/_all-theme.import.scss
Labels: cla: yes, merge ready, target: patch

#21964 fix(material-experimental/mdc-typography): change transform to none
  src/material-experimental/mdc-helpers/_mdc-helpers.scss
Labels: P2, cla: yes, merge ready, target: patch

#21623 fix(material-experimental/mdc-button): use mdc mixins to style icons within buttons
  src/material-experimental/mdc-button/button.scss
Labels: P2, cla: yes, merge ready, target: patch

#21968 fix(material-experimental/mdc-list): update mixin and variable names after MDC's deprecation
  package.json
  src/material-experimental/mdc-autocomplete/_autocomplete-theme.scss
  src/material-experimental/mdc-autocomplete/autocomplete.scss
  src/material-experimental/mdc-core/option/_optgroup-theme.scss
  src/material-experimental/mdc-core/option/_option-theme.scss
  src/material-experimental/mdc-core/option/optgroup.scss
  src/material-experimental/mdc-core/option/option.scss
  src/material-experimental/mdc-list/_list-option-theme.scss
  src/material-experimental/mdc-list/_list-theme.scss
  src/material-experimental/mdc-list/list.scss
  src/material-experimental/mdc-menu/_menu-theme.scss
  src/material-experimental/mdc-menu/menu.scss
  src/material-experimental/mdc-select/_select-theme.scss
  src/material-experimental/mdc-select/select.scss
  yarn.lock
Labels: caretaker note, cla: yes, merge ready, merge safe, target: patch

#21971 fix(material-experimental/mdc-slider): init step on thumb inputs
  src/material-experimental/mdc-slider/slider.ts
Labels: cla: yes, merge ready, target: feature branch

#21934 feat(material-experimental/mdc-slider): add slider styles
  src/dev-app/mdc-slider/mdc-slider-demo.html
  src/material-experimental/mdc-slider/_slider-theme.scss
  src/material-experimental/mdc-slider/slider.scss
  src/material-experimental/mdc-slider/slider.ts
Labels: cla: yes, merge ready, target: feature branch

#21928 Update rules nodejs
  .nvmrc
  WORKSPACE
  integration/size-test/index.bzl
  package.json
  packages.bzl
  src/cdk/schematics/ng-add/index.spec.ts
  src/cdk/schematics/ng-add/package-config.ts
  src/e2e-app/BUILD.bazel
  src/material-experimental/mdc-helpers/BUILD.bazel
  src/material/schematics/ng-add/index.spec.ts
  src/material/schematics/ng-add/package-config.ts
  src/material/schematics/ng-update/migrations/hammer-gestures-v9/hammer-gestures-migration.ts
  src/material/schematics/ng-update/test-cases/v9/misc/hammer-migration-v9.spec.ts
  src/universal-app/BUILD.bazel
  test/bazel-karma-local-config.js
  test/benchmarks/cdk/testing/component-harness/BUILD.bazel
  test/benchmarks/material/button/BUILD.bazel
  test/benchmarks/material/card/BUILD.bazel
  test/benchmarks/material/checkbox/BUILD.bazel
  test/benchmarks/material/chips/BUILD.bazel
  test/benchmarks/material/form-field/BUILD.bazel
  test/benchmarks/material/menu/BUILD.bazel
  test/benchmarks/material/radio/BUILD.bazel
  test/benchmarks/material/slide-toggle/BUILD.bazel
  test/benchmarks/material/table/BUILD.bazel
  test/benchmarks/material/tabs/BUILD.bazel
  test/benchmarks/mdc/button/BUILD.bazel
  test/benchmarks/mdc/card/BUILD.bazel
  test/benchmarks/mdc/checkbox/BUILD.bazel
  test/benchmarks/mdc/chips/BUILD.bazel
  test/benchmarks/mdc/form-field/BUILD.bazel
  test/benchmarks/mdc/menu/BUILD.bazel
  test/benchmarks/mdc/radio/BUILD.bazel
  test/benchmarks/mdc/slide-toggle/BUILD.bazel
  test/benchmarks/mdc/table/BUILD.bazel
  test/benchmarks/mdc/tabs/BUILD.bazel
  tools/defaults.bzl
  tools/dev-server/BUILD.bazel
  tools/dgeni/BUILD.bazel
  tools/example-module/BUILD.bazel
  tools/highlight-files/BUILD.bazel
  tools/markdown-to-html/BUILD.bazel
  tools/markdown-to-html/docs-marked-renderer.ts
  tools/package-docs-content/BUILD.bazel
  tools/postinstall/@bazel_typescript_tsc_wrapped_worker_cache_fix.patch
  tools/postinstall/apply-patches.js
  yarn.lock
Labels: area: build, area: cdk/schematics, cla: yes, merge ready, merge safe, target: minor

#21980 build: update mdc_snapshot_test_cronjob to yarn install before bazel setup
  .circleci/config.yml
Labels: area: build, cla: yes, merge ready, merge safe, target: patch

#21986 fix(material-experimental/mdc-progress-bar): check observer function
  src/material-experimental/mdc-progress-bar/progress-bar.ts
Labels: P1, cla: yes, merge ready, target: patch

#21941 docs(material/autocomplete): fix aria-label docs
  src/material/autocomplete/autocomplete.ts
Labels: cla: yes, docs, merge ready, merge safe, target: patch

#21942 docs(material/select): remove placeholder fallback from aria-label docs
  src/material/select/select.ts
Labels: cla: yes, docs, merge ready, merge safe, target: patch

#21959 test(material/select): fix form field class name in assertion
  src/material/select/select.spec.ts
Labels: cla: yes, merge ready, merge safe, target: patch

#21963 test(material/select): remove form-field dependency in deselection test
  src/material-experimental/mdc-select/select.spec.ts
  src/material/select/select.spec.ts
Labels: cla: yes, merge ready, merge safe, target: patch

#21983 test(material/select): remove form-field dependency in focus test
  src/material-experimental/mdc-select/select.spec.ts
  src/material/select/select.spec.ts
Labels: cla: yes, merge ready, merge safe, target: patch

#21978 fix(cdk/clipboard): typo in injection token name
  src/cdk/clipboard/copy-to-clipboard.ts
  tools/public_api_guard/cdk/clipboard.d.ts
Labels: P3, cla: yes, merge ready, target: patch

#21975 fix(material/bottom-sheet): focus restoration not working inside shadow dom
  src/material/bottom-sheet/BUILD.bazel
  src/material/bottom-sheet/bottom-sheet-container.ts
  src/material/bottom-sheet/bottom-sheet.spec.ts
Labels: P3, cla: yes, merge ready, target: patch

#21952 refactor(material/datepicker): remove deprecated APIs for v12
  src/material/datepicker/date-selection-model.ts
  src/material/datepicker/datepicker-base.ts
  src/material/schematics/ng-update/data/constructor-checks.ts
  tools/public_api_guard/material/datepicker.d.ts
Labels: P2, cla: yes, merge ready, target: major

#21940 feat(cdk/stepper): allow for orientation to be changed
  src/cdk/stepper/stepper.ts
  src/material/stepper/BUILD.bazel
  src/material/stepper/stepper.spec.ts
  src/material/stepper/stepper.ts
  tools/public_api_guard/cdk/stepper.d.ts
  tools/public_api_guard/material/stepper.d.ts
Labels: P3, cla: yes, merge ready, target: minor

#21886 feat(cdk/table): add element offsets to sticky styler state
  src/cdk/table/sticky-position-listener.ts
  src/cdk/table/sticky-styler.ts
  src/cdk/table/table.spec.ts
  tools/public_api_guard/cdk/table.d.ts
Labels: G, area: cdk/table, cla: yes, merge ready, target: minor

#21937 refactor(material/theming): normalize config in all typography mixins for non-mdc components
  src/dev-app/theme.scss
  src/material-experimental/popover-edit/_popover-edit.scss
  src/material/badge/_badge-theme.scss
  src/material/bottom-sheet/_bottom-sheet-theme.scss
  src/material/button-toggle/_button-toggle-theme.scss
  src/material/button/_button-theme.scss
  src/material/card/_card-theme.scss
  src/material/checkbox/_checkbox-theme.scss
  src/material/chips/_chips-theme.scss
  src/material/core/option/_optgroup-theme.scss
  src/material/core/option/_option-theme.scss
  src/material/core/typography/_typography.scss
  src/material/datepicker/_datepicker-theme.scss
  src/material/dialog/_dialog-theme.scss
  src/material/expansion/_expansion-theme.scss
  src/material/form-field/_form-field-fill-theme.scss
  src/material/form-field/_form-field-legacy-theme.scss
  src/material/form-field/_form-field-outline-theme.scss
  src/material/form-field/_form-field-theme.scss
  src/material/grid-list/_grid-list-theme.scss
  src/material/input/_input-theme.scss
  src/material/list/_list-theme.scss
  src/material/menu/_menu-theme.scss
  src/material/paginator/_paginator-theme.scss
  src/material/radio/_radio-theme.scss
  src/material/select/_select-theme.scss
  src/material/slide-toggle/_slide-toggle-theme.scss
  src/material/slider/_slider-theme.scss
  src/material/snack-bar/_snack-bar-theme.scss
  src/material/stepper/_stepper-theme.scss
  src/material/table/_table-theme.scss
  src/material/tabs/_tabs-theme.scss
  src/material/toolbar/_toolbar-theme.scss
  src/material/tooltip/_tooltip-theme.scss
  src/material/tree/_tree-theme.scss
  tools/stylelint/theme-mixin-api.ts
Labels: cla: yes, merge ready, target: minor

#22004 build: ignore dependency updates for @material/
  .github/dependabot.yml
Labels: cla: yes, merge ready, merge safe, target: patch

#21990 build: update to rules_nodejs@3.2.1
  WORKSPACE
  package.json
  yarn.lock
Labels: area: build, cla: yes, merge ready, merge safe, target: minor

#22010 release: bump version to 11.2.2 w/ changelog
  CHANGELOG.md
  package.json
Labels: cla: yes, merge ready, merge safe, target: patch

#21979 feat(material-experimental/mdc-slider): implement slider thumb ripples
  src/material-experimental/mdc-slider/BUILD.bazel
  src/material-experimental/mdc-slider/_slider-theme.scss
  src/material-experimental/mdc-slider/module.ts
  src/material-experimental/mdc-slider/slider-thumb.html
  src/material-experimental/mdc-slider/slider-thumb.scss
  src/material-experimental/mdc-slider/slider.html
  src/material-experimental/mdc-slider/slider.scss
  src/material-experimental/mdc-slider/slider.ts
Labels: cla: yes, target: feature branch

#21987 fix(cdk/a11y): detect fake touchstart events from screen readers
  src/cdk/a11y/fake-event-detection.ts
  src/cdk/a11y/fake-mousedown.ts
  src/cdk/a11y/focus-monitor/focus-monitor.ts
  src/cdk/a11y/public-api.ts
  src/material/core/ripple/ripple-renderer.ts
  src/material/menu/menu-trigger.ts
  tools/public_api_guard/cdk/a11y.d.ts
Labels: G, P2, a11y, cla: yes, merge ready, target: patch

#22014 release: bump to 11.2.2 changelog
  CHANGELOG.md
Labels: cla: yes, target: patch

#21972 docs: mention `entryComponents` is no longer necessary
  src/cdk/portal/portal.md
  src/material/bottom-sheet/bottom-sheet.md
  src/material/dialog/dialog.md
Labels: cla: yes, docs, merge ready, merge safe, target: patch

#21946 docs: missing import in map-directions-render
  src/google-maps/map-directions-renderer/README.md
Labels: cla: yes, docs, merge ready, merge safe, target: minor

#22011 build: fix theming api lint rule
  src/material/expansion/_expansion-theme.scss
  tools/stylelint/theme-mixin-api.ts
Labels: P2, cla: yes, merge ready, merge safe, target: major

#21923 fix(material-experimental/mdc-button): add mdc ripple class for fab
  src/material-experimental/mdc-button/button-base.ts
  src/material-experimental/mdc-button/button.html
  src/material-experimental/mdc-button/fab.ts
Labels: G, P2, cla: yes, merge ready, target: patch

#21956 feat(material-expeirmental/mdc-form-field): separate out text and icon prefixes/suffixes
  src/dev-app/mdc-input/mdc-input-demo.html
  src/material-experimental/mdc-form-field/_form-field-theme.scss
  src/material-experimental/mdc-form-field/directives/prefix.ts
  src/material-experimental/mdc-form-field/directives/suffix.ts
  src/material-experimental/mdc-form-field/form-field.html
  src/material-experimental/mdc-form-field/form-field.scss
  src/material-experimental/mdc-form-field/form-field.ts
  src/material-experimental/mdc-form-field/testing/form-field-harness.ts
  src/material-experimental/mdc-input/BUILD.bazel
  src/material-experimental/mdc-input/input.spec.ts
  src/material/form-field/testing/shared.spec.ts
Labels: G, P2, cla: yes, merge ready, target: minor
