Repository angular/components, pull requests merged in 2021-03, with the labels that each got.

#22016 feat(material-experimental/mdc-slider): implement control value accessor
  src/material-experimental/mdc-slider/slider.ts
Labels: cla: yes, merge ready, target: feature branch

#22070 feat(material-experimental/mdc-card): add appearance input
  src/dev-app/mdc-card/mdc-card-demo.html
  src/dev-app/mdc-card/mdc-card-demo.ts
  src/material-experimental/mdc-card/card.ts
Labels: P3, cla: yes, merge ready, target: minor

#22056 fix(material/datepicker): hide date selection model from docs
  src/material/datepicker/date-selection-model.ts
  tools/public_api_guard/material/datepicker.d.ts
Labels: P3, cla: yes, merge ready, target: patch

#22055 fix(cdk/accordion): allow for closeAll to be used when multiple mode is disabled
  src/cdk/accordion/accordion.spec.ts
  src/cdk/accordion/accordion.ts
Labels: P3, cla: yes, merge ready, target: patch

#22054 refactor(material/autocomplete): remove deprecated APIs for v12
  src/material-experimental/mdc-autocomplete/public-api.ts
  src/material/autocomplete/autocomplete-trigger.ts
  tools/public_api_guard/material/autocomplete.d.ts
Labels: P2, cla: yes, merge ready, target: major

#22047 feat(material/slide-toggle): allow for default color to be configured globally
  src/material-experimental/mdc-slide-toggle/slide-toggle-config.ts
  src/material-experimental/mdc-slide-toggle/slide-toggle.spec.ts
  src/material-experimental/mdc-slide-toggle/slide-toggle.ts
  src/material/slide-toggle/slide-toggle-config.ts
  src/material/slide-toggle/slide-toggle.spec.ts
  src/material/slide-toggle/slide-toggle.ts
  tools/public_api_guard/material/slide-toggle.d.ts
Labels: P3, cla: yes, merge ready, target: minor

#22025 fix(material-experimental/mdc-tooltip): change class prefixes to mat-mdc
  src/material-experimental/mdc-tooltip/public-api.ts
  src/material-experimental/mdc-tooltip/tooltip.spec.ts
  src/material-experimental/mdc-tooltip/tooltip.ts
  src/material/tooltip/tooltip.spec.ts
  src/material/tooltip/tooltip.ts
  tools/public_api_guard/material/tooltip.d.ts
Labels: P2, cla: yes, merge ready, target: minor

#22049 fix(material-experimental/mdc-button): apply appropriate focus/actives styles to FAB
  src/dev-app/mdc-button/mdc-button-demo.html
  src/material-experimental/mdc-button/_button-base.scss
  src/material-experimental/mdc-button/_button-theme.scss
  src/material-experimental/mdc-button/fab.ts
Labels: G, P2, cla: yes, merge ready, target: minor

#22043 fix(cdk/overlay): resolve regression when overlay is imported through shorthand path
  src/cdk/a11y/_a11y.scss
  src/cdk/overlay/_overlay.scss
Labels: P2, cla: yes, merge ready, regression, target: minor

#22086 fix(cdk/overlay): resolve regression when overlay is imported through…
  src/cdk/a11y/_a11y.scss
  src/cdk/overlay/_overlay.scss
Labels: cla: yes, merge ready, target: patch

#22068 fix(material-experimental/mdc-form-field): always check hideRequiredMarker
  src/material-experimental/mdc-form-field/form-field.ts
  src/material-experimental/mdc-input/input.spec.ts
  src/material/input/input.spec.ts
Labels: P2, cla: yes, merge ready, target: patch

#22071 fix(material-experimental/mdc-radio): include form field core theme styles
  src/material-experimental/mdc-radio/_radio-theme.scss
  src/material-experimental/mdc-slide-toggle/_slide-toggle-theme.scss
Labels: P2, cla: yes, merge ready, target: minor

#21748 fix(material-experimental/mdc-checkbox): remove background state styles
  src/dev-app/mdc-checkbox/mdc-checkbox-demo.html
  src/material-experimental/mdc-checkbox/_checkbox-theme.scss
  src/material-experimental/mdc-checkbox/checkbox.html
  src/material-experimental/mdc-checkbox/checkbox.scss
Labels: P2, cla: yes, merge ready, target: minor

#22099 release: bump version to 11.2.3 w/ changelog
  CHANGELOG.md
  package.json
Labels: cla: yes, merge ready, merge safe, target: patch

#22100 release: bump changelog to 11.2.3
  CHANGELOG.md
Labels: cla: yes, merge ready, target: minor

#22101 build: bump angular version to 12 || 13
  packages.bzl
Labels: cla: yes, merge ready, target: major

#22103 build: fix angular version
  packages.bzl
Labels: cla: yes, merge ready, merge safe, target: major

#22104 release: bump version to 12.0.0-next.1 w/ changelog
  CHANGELOG.md
  package.json
Labels: cla: yes, merge ready, merge safe, target: major

#22052 fix(material/schematics): generate code that works in strict CLI projects
  src/cdk/schematics/ng-generate/drag-drop/files/__path__/__name@dasherize@if-flat__/__name@dasherize__.component.ts.template
  src/material/schematics/ng-generate/address-form/files/__path__/__name@dasherize@if-flat__/__name@dasherize__.component.ts.template
  src/material/schematics/ng-generate/table/files/__path__/__name@dasherize@if-flat__/__name@dasherize__-datasource.ts.template
  src/material/schematics/ng-generate/table/files/__path__/__name@dasherize@if-flat__/__name@dasherize__.component.html.template
  src/material/schematics/ng-generate/table/files/__path__/__name@dasherize@if-flat__/__name@dasherize__.component.ts.template
  src/material/schematics/ng-generate/tree/files/__path__/__name@dasherize@if-flat__/__name@dasherize__.component.ts.template
Labels: P3, area: ng-generate, cla: yes, merge ready, merge safe, target: patch

#22053 docs(material/table): use declarative idiomatic RxJS in table-http-example
  src/components-examples/material/table/table-http/table-http-example.css
  src/components-examples/material/table/table-http/table-http-example.html
  src/components-examples/material/table/table-http/table-http-example.ts
Labels: P3, area: material/table, cla: yes, merge ready, merge safe, target: patch

#21870 feat(material/form-field): make mat-errors more polite
  src/material-experimental/mdc-chips/chip-grid.spec.ts
  src/material-experimental/mdc-form-field/directives/error.ts
  src/material-experimental/mdc-input/input.spec.ts
  src/material/chips/chip-list.spec.ts
  src/material/form-field/error.ts
  src/material/input/input.spec.ts
  tools/public_api_guard/material/form-field.d.ts
Labels: G, P2, a11y, cla: yes, merge ready, target: minor

#21827 refactor(material/select): remove deprecated APIs for v12
  src/material-experimental/mdc-select/public-api.ts
  src/material/select/public-api.ts
  src/material/select/select.ts
  tools/public_api_guard/material/select.d.ts
Labels: P2, cla: yes, merge ready, target: major

#21901 refactor(material/stepper): remove deprecated APIs for v12
  src/cdk/schematics/ng-update/data/constructor-checks.ts
  src/cdk/stepper/stepper.ts
  src/material/schematics/ng-update/data/constructor-checks.ts
  src/material/stepper/stepper.ts
  tools/public_api_guard/cdk/stepper.d.ts
  tools/public_api_guard/material/stepper.d.ts
Labels: P2, cla: yes, merge ready, target: major

#21588 fix(material-experimental/mdc-autocomplete): only animate along y axis
  src/material-experimental/mdc-autocomplete/animations.ts
Labels: P3, cla: yes, merge ready, target: patch

#21811 fix(material/dialog): focus restoration not working inside shadow dom
  src/material-experimental/mdc-dialog/BUILD.bazel
  src/material-experimental/mdc-dialog/dialog.spec.ts
  src/material/dialog/BUILD.bazel
  src/material/dialog/dialog-container.ts
  src/material/dialog/dialog.spec.ts
Labels: P3, cla: yes, merge ready, target: patch

#21564 fix(material-experimental/mdc-progress-bar): run resize observer outside zone
  src/material-experimental/mdc-progress-bar/progress-bar.ts
Labels: P4, cla: yes, merge ready, target: patch

#15228 feat(material/tabs): add method for programmatically setting focus
  src/material-experimental/mdc-tabs/tab-group.spec.ts
  src/material/tabs/tab-group.spec.ts
  src/material/tabs/tab-group.ts
  tools/public_api_guard/material/tabs.d.ts
Labels: P5, cla: yes, merge ready, target: minor

#21442 fix(material-experimental/mdc-snack-bar): use MDC-based button
  src/material-experimental/mdc-snack-bar/BUILD.bazel
  src/material-experimental/mdc-snack-bar/_snack-bar-theme.scss
  src/material-experimental/mdc-snack-bar/module.ts
  src/material-experimental/mdc-snack-bar/snack-bar.spec.ts
  src/material-experimental/mdc-snack-bar/testing/BUILD.bazel
Labels: G, P2, cla: yes, merge ready, target: minor

#19492 fix(material/sort): view not updated when sort state is changed through binding
  src/material/sort/sort-header.ts
  src/material/sort/sort.spec.ts
Labels: G, P2, cla: yes, merge ready, target: patch

#20040 fix(material/card): not clearing margin on last button in end alignment
  src/material/card/card.scss
Labels: P3, cla: yes, merge ready, target: patch

#21606 fix(material-experimental/mdc-select): arrow not rendering in high contrast mode
  src/material-experimental/mdc-select/select.html
  src/material-experimental/mdc-select/select.scss
Labels: P3, a11y, cla: yes, merge ready, target: patch

#22136 docs(cdk/a11y): fix overview table of contents
  src/cdk/a11y/a11y.md
  src/cdk/a11y/focus-trap/focus-trap.md
Labels: P2, area: cdk/a11y, cla: yes, docs, merge ready, merge safe, target: patch

#22132 fix(material-experimental/mdc-chips): click interaction of remove icon
  src/material-experimental/mdc-chips/chip-icons.ts
Labels: G, P2, cla: yes, merge ready, target: patch

#22058 fix(material/table): data source filteredData not updating while disconnected
  src/material/table/table-data-source.spec.ts
  src/material/table/table-data-source.ts
Labels: P3, cla: yes, merge ready, target: patch

#22090 fix(material-experimental/mdc-form-field): fix prefix/suffix padding
  src/material-experimental/mdc-form-field/_form-field-sizing.scss
  src/material-experimental/mdc-form-field/_mdc-text-field-structure-overrides.scss
  src/material-experimental/mdc-form-field/directives/prefix.ts
  src/material-experimental/mdc-form-field/directives/suffix.ts
  src/material-experimental/mdc-form-field/form-field.html
  src/material-experimental/mdc-form-field/form-field.scss
  src/material-experimental/mdc-form-field/form-field.ts
Labels: G, P2, cla: yes, merge ready, target: minor

#21826 fix(material/grid-list): remove internal figure element
  src/material/grid-list/grid-list.scss
  src/material/grid-list/grid-tile.html
Labels: P3, a11y, cla: yes, merge ready, target: minor

#22057 build: clean up sass patch workaround
  WORKSPACE
  package.json
  tools/postinstall/sass_worker_async.patch
  yarn.lock
Labels: P3, cla: yes, merge ready, merge safe, target: minor

#22114 docs: monospace DataSource (table docs)
  src/material/table/table.md
Labels: P4, cla: yes, merge ready, merge safe, target: patch

#22072 feat(material-experimental/mdc-slider): implement some basic unit tests
  src/cdk/testing/testbed/fake-events/dispatch-events.ts
  src/cdk/testing/testbed/fake-events/event-objects.ts
  src/material-experimental/mdc-slider/BUILD.bazel
  src/material-experimental/mdc-slider/slider-thumb.html
  src/material-experimental/mdc-slider/slider.spec.ts
  src/material-experimental/mdc-slider/slider.ts
  src/material-experimental/mdc-theming/_all-theme.scss
Labels: cla: yes, target: feature branch

#22168 feat(material-experimental/mdc-slider): add unit tests for disabled s…
  src/material-experimental/mdc-slider/slider.spec.ts
Labels: cla: yes, target: feature branch

#22169 docs(badge): specify badge targets must be block-level
  src/material/badge/badge.md
Labels: area: material/badge, cla: yes, docs, merge ready, merge safe, target: patch

#22176 release: add 11.2.4 changelog to master
  CHANGELOG.md
Labels: cla: yes, merge ready, merge safe, target: minor

#19700 feat(material/chips): prevent chips from being deleted when user holds backspace
  src/components-examples/material/chips/chips-autocomplete/chips-autocomplete-example.ts
  src/components-examples/material/chips/chips-input/chips-input-example.ts
  src/dev-app/chips/chips-demo.ts
  src/dev-app/mdc-chips/mdc-chips-demo.ts
  src/material-experimental/mdc-chips/chip-grid.spec.ts
  src/material-experimental/mdc-chips/chip-grid.ts
  src/material-experimental/mdc-chips/chip-input.ts
  src/material/chips/chip-input.ts
  src/material/chips/chip-list.spec.ts
  src/material/chips/chip-list.ts
  tools/public_api_guard/material/chips.d.ts
Labels: P2, cla: yes, commit message fixup, merge ready, target: minor

#22045 refactor(material-experimental/mdc-core): clean up remaining @import usages
  src/material-experimental/mdc-autocomplete/_autocomplete-theme.scss
  src/material-experimental/mdc-autocomplete/autocomplete.scss
  src/material-experimental/mdc-button/_button-theme.scss
  src/material-experimental/mdc-button/button.scss
  src/material-experimental/mdc-button/fab.scss
  src/material-experimental/mdc-button/icon-button.scss
  src/material-experimental/mdc-card/_card-theme.scss
  src/material-experimental/mdc-card/card.scss
  src/material-experimental/mdc-checkbox/_checkbox-theme.scss
  src/material-experimental/mdc-checkbox/checkbox.scss
  src/material-experimental/mdc-chips/_chips-theme.scss
  src/material-experimental/mdc-chips/chips.scss
  src/material-experimental/mdc-core/option/_optgroup-theme.scss
  src/material-experimental/mdc-core/option/_option-theme.scss
  src/material-experimental/mdc-core/option/optgroup.scss
  src/material-experimental/mdc-core/option/option.scss
  src/material-experimental/mdc-dialog/_dialog-legacy-padding.scss
  src/material-experimental/mdc-dialog/_dialog-theme.scss
  src/material-experimental/mdc-dialog/dialog.scss
  src/material-experimental/mdc-form-field/_form-field-density.scss
  src/material-experimental/mdc-form-field/_form-field-focus-overlay.scss
  src/material-experimental/mdc-form-field/_form-field-sizing.scss
  src/material-experimental/mdc-form-field/_form-field-subscript.scss
  src/material-experimental/mdc-form-field/_form-field-theme.scss
  src/material-experimental/mdc-form-field/_mdc-text-field-structure-overrides.scss
  src/material-experimental/mdc-form-field/_mdc-text-field-theme-variable-refresh.scss
  src/material-experimental/mdc-form-field/form-field.scss
  src/material-experimental/mdc-helpers/_mdc-helpers.scss
  src/material-experimental/mdc-list/_interactive-list-theme.scss
  src/material-experimental/mdc-list/_list-option-theme.scss
  src/material-experimental/mdc-list/_list-theme.scss
  src/material-experimental/mdc-list/list-option.scss
  src/material-experimental/mdc-list/list.scss
  src/material-experimental/mdc-menu/_menu-theme.scss
  src/material-experimental/mdc-menu/menu.scss
  src/material-experimental/mdc-paginator/_paginator-theme.scss
  src/material-experimental/mdc-progress-bar/_progress-bar-theme.scss
  src/material-experimental/mdc-progress-bar/progress-bar.scss
  src/material-experimental/mdc-progress-spinner/_progress-spinner-theme.scss
  src/material-experimental/mdc-progress-spinner/progress-spinner.scss
  src/material-experimental/mdc-radio/_radio-theme.scss
  src/material-experimental/mdc-radio/radio.scss
  src/material-experimental/mdc-select/_select-theme.scss
  src/material-experimental/mdc-select/select.scss
  src/material-experimental/mdc-slide-toggle/_slide-toggle-theme.scss
  src/material-experimental/mdc-slide-toggle/slide-toggle.scss
  src/material-experimental/mdc-slider/_slider-theme.scss
  src/material-experimental/mdc-slider/slider.scss
  src/material-experimental/mdc-snack-bar/_snack-bar-theme.scss
  src/material-experimental/mdc-snack-bar/snack-bar-container.scss
  src/material-experimental/mdc-table/_table-theme.scss
  src/material-experimental/mdc-table/table.scss
  src/material-experimental/mdc-tabs/_tabs-common.scss
  src/material-experimental/mdc-tabs/_tabs-theme.scss
  src/material-experimental/mdc-tabs/tab-group.scss
  src/material-experimental/mdc-tabs/tab-header.scss
  src/material-experimental/mdc-tabs/tab-nav-bar/tab-link.scss
  src/material-experimental/mdc-tabs/tab-nav-bar/tab-nav-bar.scss
  src/material-experimental/mdc-typography/_all-typography.scss
Labels: P2, cla: yes, merge ready, target: major

#19517 fix(material/select): float label on focus if there's a placeholder
  src/material/select/select.spec.ts
  src/material/select/select.ts
Labels: P3, cla: yes, merge ready, target: patch

#22135 docs(dev-app): remove references to mdc-select placeholder
  src/dev-app/mdc-select/mdc-select-demo.html
Labels: cla: yes, merge ready, merge safe, target: patch

#22171 docs: replace programatically by programmatically
  src/cdk-experimental/column-resize/column-resize-notifier.ts
  src/cdk/table/cell.ts
  src/components-examples/material/tooltip/tooltip-disabled/tooltip-disabled-example.html
  src/material-experimental/mdc-autocomplete/autocomplete.scss
  src/material/menu/menu.ts
Labels: P3, cla: yes, merge ready, merge safe, target: patch

#22152 fix(material-experimental/mdc-progress-bar): improve buffer color
  src/material-experimental/mdc-progress-bar/_progress-bar-theme.scss
Labels: P3, cla: yes, merge ready, target: minor

#22198 fix(material-experimental/mdc-checkbox): fix mdc function name
  src/material-experimental/mdc-checkbox/_checkbox-theme.scss
Labels: P1, cla: yes, merge ready, merge safe, target: major

#22193 test(material-experimental/mdc-slider): add unit tests for sliders wi…
  src/material-experimental/mdc-slider/slider.spec.ts
Labels: cla: yes, target: feature branch

#22195 fix(material-experimental/mdc-slider): dedup mdc-slider styles
  src/dev-app/theme.scss
  src/material-experimental/mdc-slider/_slider-theme.scss
Labels: cla: yes, target: feature branch

#22196 feat(material-experimental/mdc-slider): add support for rtl/ltr toggle
  src/material-experimental/mdc-slider/slider.ts
Labels: cla: yes, target: feature branch

#22157 fix(material-experimental/mdc-list): rename mdc-list-* classes
  package.json
  src/material-experimental/mdc-core/option/_option-theme.scss
  src/material-experimental/mdc-core/option/optgroup.html
  src/material-experimental/mdc-core/option/option.html
  src/material-experimental/mdc-core/option/option.scss
  src/material-experimental/mdc-core/option/option.ts
  src/material-experimental/mdc-core/testing/option-harness.ts
  src/material-experimental/mdc-list/_interactive-list-theme.scss
  src/material-experimental/mdc-list/_list-option-theme.scss
  src/material-experimental/mdc-list/_list-theme.scss
  src/material-experimental/mdc-list/action-list.ts
  src/material-experimental/mdc-list/list-base.ts
  src/material-experimental/mdc-list/list-item.html
  src/material-experimental/mdc-list/list-option.html
  src/material-experimental/mdc-list/list-option.ts
  src/material-experimental/mdc-list/list-styling.ts
  src/material-experimental/mdc-list/list.scss
  src/material-experimental/mdc-list/list.spec.ts
  src/material-experimental/mdc-list/list.ts
  src/material-experimental/mdc-list/nav-list.ts
  src/material-experimental/mdc-list/selection-list.spec.ts
  src/material-experimental/mdc-list/selection-list.ts
  src/material-experimental/mdc-list/testing/list-item-harness-base.ts
  src/material-experimental/mdc-list/testing/selection-list-harness.ts
  src/material-experimental/mdc-menu/menu.html
  src/material-experimental/mdc-select/select.spec.ts
  yarn.lock
Labels: P2, caretaker note, cla: yes, merge ready, merge safe, target: minor

#22213 Revert "feat(material/chips): prevent chips from being deleted when u…
  src/components-examples/material/chips/chips-autocomplete/chips-autocomplete-example.ts
  src/components-examples/material/chips/chips-input/chips-input-example.ts
  src/dev-app/chips/chips-demo.ts
  src/dev-app/mdc-chips/mdc-chips-demo.ts
  src/material-experimental/mdc-chips/chip-grid.spec.ts
  src/material-experimental/mdc-chips/chip-grid.ts
  src/material-experimental/mdc-chips/chip-input.ts
  src/material/chips/chip-input.ts
  src/material/chips/chip-list.spec.ts
  src/material/chips/chip-list.ts
  tools/public_api_guard/material/chips.d.ts
Labels: cla: yes

#22218 fix(material-experimental/mdc-core): fix broken list option style
  src/material-experimental/mdc-core/option/_option-theme.scss
Labels: P1, cla: yes, merge ready, merge safe, target: minor

#22216 fix(material-experimental/mdc-slider): add slider to mdc_scss_deps_lib
  src/material-experimental/mdc-helpers/BUILD.bazel
Labels: cla: yes, merge ready, merge safe, target: feature branch

#22220 refactor: update MDC and switch chips Sass import path
  package.json
  src/material-experimental/mdc-chips/_chips-theme.scss
  src/material-experimental/mdc-chips/chips.scss
  yarn.lock
Labels: P1, cla: yes, merge ready, merge safe, target: minor

#22222 build: add lint rule to prevent @import usage
  .stylelintrc.json
  src/material/core/theming/tests/test-theming-bundle.scss
  tools/stylelint/no-import.ts
Labels: P3, cla: yes, merge ready, merge safe, target: major

#22208 build: run commit message check after other lint checks
  .circleci/config.yml
Labels: P3, cla: yes, merge ready, merge safe, target: patch

#22167 build: lay foundation for migrating to ng-dev release tooling
  .ng-dev/config.ts
  .ng-dev/merge.ts
  .ng-dev/release.ts
  scripts/build-packages-dist.js
Labels: area: build, cla: yes, merge ready, merge safe, target: patch

#22224 docs(material/button-toggle): add missing type on public API
  src/material/button-toggle/button-toggle.ts
Labels: P4, cla: yes, merge ready, merge safe, target: patch

#22238 test(material-experimental/mdc-slider): add tests for slider with set…
  src/material-experimental/mdc-slider/slider.spec.ts
  src/material-experimental/mdc-slider/slider.ts
Labels: cla: yes, target: feature branch

#22240 docs: remove node-sass references
  guides/theming.md
  tools/package-tools/gulp/build-scss-pipeline.ts
Labels: P4, cla: yes, merge ready, merge safe, target: major

#22241 build: update all @material packages to canary
  .circleci/config.yml
  package.json
  scripts/circleci/setup-mdc-canary.js
Labels: P3, cla: yes, merge ready, merge safe, target: minor

#21547 fix the warning on lock-closed gh-actions: Warning: Unexpected input(s) 'lock-bot-key'
  .github/workflows/lock-closed.yml
Labels: cla: yes, commit message fixup, merge ready, merge safe, target: patch

#22235 Revert "Revert "feat(material/chips): prevent chips from being delete…
  src/components-examples/material/chips/chips-autocomplete/chips-autocomplete-example.ts
  src/components-examples/material/chips/chips-input/chips-input-example.ts
  src/dev-app/chips/chips-demo.ts
  src/dev-app/mdc-chips/mdc-chips-demo.ts
  src/material-experimental/mdc-chips/chip-grid.spec.ts
  src/material-experimental/mdc-chips/chip-grid.ts
  src/material-experimental/mdc-chips/chip-icons.ts
  src/material-experimental/mdc-chips/chip-input.ts
  src/material/chips/chip-input.ts
  src/material/chips/chip-list.spec.ts
  src/material/chips/chip-list.ts
  tools/public_api_guard/material/chips.d.ts
Labels: P2, cla: yes, merge ready, target: minor

#22242 test(material-experimental/mdc-slider): add tests for slider with one…
  src/material-experimental/mdc-slider/slider.spec.ts
Labels: cla: yes, merge ready, target: feature branch

#22239 refactor(material-experimental/mdc-chips): switch to import deprecated from @material/chips
  package.json
  src/material-experimental/mdc-chips/chip-icons.ts
  src/material-experimental/mdc-chips/chip-listbox.ts
  src/material-experimental/mdc-chips/chip-option.spec.ts
  src/material-experimental/mdc-chips/chip-option.ts
  src/material-experimental/mdc-chips/chip-set.ts
  src/material-experimental/mdc-chips/chip.ts
  yarn.lock
Labels: P2, caretaker note, cla: yes, merge ready, target: minor

#22263 release: bump version to 11.2.5 w/ changelog
  CHANGELOG.md
  package.json
Labels: cla: yes, merge ready, target: patch

#22262 build: update to TypeScript 4.2
  package.json
  packages.bzl
  src/cdk-experimental/selection/selection.ts
  src/google-maps/map-marker-clusterer/map-marker-clusterer.ts
  src/material-experimental/mdc-chips/chip.ts
  src/material/chips/chip.ts
  tools/public_api_guard/cdk/a11y.d.ts
  tools/public_api_guard/cdk/accordion.d.ts
  tools/public_api_guard/cdk/bidi.d.ts
  tools/public_api_guard/cdk/clipboard.d.ts
  tools/public_api_guard/cdk/drag-drop.d.ts
  tools/public_api_guard/cdk/layout.d.ts
  tools/public_api_guard/cdk/observers.d.ts
  tools/public_api_guard/cdk/overlay.d.ts
  tools/public_api_guard/cdk/platform.d.ts
  tools/public_api_guard/cdk/portal.d.ts
  tools/public_api_guard/cdk/scrolling.d.ts
  tools/public_api_guard/cdk/stepper.d.ts
  tools/public_api_guard/cdk/table.d.ts
  tools/public_api_guard/cdk/text-field.d.ts
  tools/public_api_guard/cdk/tree.d.ts
  tools/public_api_guard/google-maps/google-maps.d.ts
  tools/public_api_guard/material/autocomplete.d.ts
  tools/public_api_guard/material/badge.d.ts
  tools/public_api_guard/material/bottom-sheet.d.ts
  tools/public_api_guard/material/button-toggle.d.ts
  tools/public_api_guard/material/button.d.ts
  tools/public_api_guard/material/card.d.ts
  tools/public_api_guard/material/checkbox.d.ts
  tools/public_api_guard/material/chips.d.ts
  tools/public_api_guard/material/core.d.ts
  tools/public_api_guard/material/datepicker.d.ts
  tools/public_api_guard/material/dialog.d.ts
  tools/public_api_guard/material/divider.d.ts
  tools/public_api_guard/material/expansion.d.ts
  tools/public_api_guard/material/form-field.d.ts
  tools/public_api_guard/material/grid-list.d.ts
  tools/public_api_guard/material/icon.d.ts
  tools/public_api_guard/material/icon/testing.d.ts
  tools/public_api_guard/material/input.d.ts
  tools/public_api_guard/material/list.d.ts
  tools/public_api_guard/material/menu.d.ts
  tools/public_api_guard/material/paginator.d.ts
  tools/public_api_guard/material/progress-bar.d.ts
  tools/public_api_guard/material/progress-spinner.d.ts
  tools/public_api_guard/material/radio.d.ts
  tools/public_api_guard/material/select.d.ts
  tools/public_api_guard/material/sidenav.d.ts
  tools/public_api_guard/material/slide-toggle.d.ts
  tools/public_api_guard/material/slider.d.ts
  tools/public_api_guard/material/snack-bar.d.ts
  tools/public_api_guard/material/sort.d.ts
  tools/public_api_guard/material/stepper.d.ts
  tools/public_api_guard/material/table.d.ts
  tools/public_api_guard/material/tabs.d.ts
  tools/public_api_guard/material/toolbar.d.ts
  tools/public_api_guard/material/tooltip.d.ts
  tools/public_api_guard/material/tree.d.ts
  tools/public_api_guard/youtube-player/youtube-player.d.ts
  yarn.lock
Labels: P3, cla: yes, merge ready, merge safe, target: major

#22264 release: bump version to 12.0.0-next.3 w/ changelog
  CHANGELOG.md
  package.json
Labels: cla: yes, merge ready, target: major

#22293 build: schematics unit tests not being run
  src/cdk/schematics/BUILD.bazel
  src/cdk/schematics/index.spec.ts
  src/cdk/schematics/ng-add/index.spec.ts
  src/cdk/schematics/ng-generate/drag-drop/index.spec.ts
  src/cdk/schematics/ng-update/test-cases/index.spec.ts
  src/cdk/schematics/ng-update/test-cases/misc/external-resource-resolution.spec.ts
  src/cdk/schematics/ng-update/test-cases/misc/global-stylesheets.spec.ts
  src/cdk/schematics/ng-update/test-cases/misc/method-call-checks.spec.ts
  src/cdk/schematics/paths.ts
  src/material/schematics/BUILD.bazel
  src/material/schematics/index.spec.ts
  src/material/schematics/ng-add/index.spec.ts
  src/material/schematics/ng-generate/address-form/index.spec.ts
  src/material/schematics/ng-generate/dashboard/index.spec.ts
  src/material/schematics/ng-generate/navigation/index.spec.ts
  src/material/schematics/ng-generate/table/index.spec.ts
  src/material/schematics/ng-generate/tree/index.spec.ts
  src/material/schematics/ng-update/test-cases/index.spec.ts
  src/material/schematics/ng-update/test-cases/misc/class-inheritance.spec.ts
  src/material/schematics/ng-update/test-cases/misc/constructor-checks.spec.ts
  src/material/schematics/ng-update/test-cases/misc/import-checks.spec.ts
  src/material/schematics/ng-update/test-cases/v8/misc/material-imports.spec.ts
  src/material/schematics/ng-update/test-cases/v9/misc/hammer-migration-v9.spec.ts
  src/material/schematics/ng-update/test-cases/v9/misc/material-imports.spec.ts
  src/material/schematics/paths.ts
Labels: P2, cla: yes, merge ready, merge safe, target: patch

#22200 build: require reviews to be completed for all PRs before merging
  .github/angular-robot.yml
Labels: area: build, cla: yes, merge ready, merge safe, target: patch

#22252 build: remove commit message line length limit
  .ng-dev/commit-message.ts
Labels: P3, cla: yes, merge ready, merge safe, target: patch

#22270 fix(cdk/schematics): update generated css class
  src/cdk/schematics/ng-generate/drag-drop/files/__path__/__name@dasherize@if-flat__/__name@dasherize__.component.__style__.template
Labels: cla: yes, merge ready, merge safe, target: patch

#22291 build: fix jasmine_node_test
  tools/defaults.bzl
Labels: cla: yes, merge ready, merge safe, target: patch

#22283 build: avoid installing node-sass
  package.json
  tools/package-tools/gulp/build-scss-pipeline.ts
  yarn.lock
Labels: P3, cla: yes, merge ready, merge safe, target: minor

#22166 fix(material/progress-bar): Support ChromeVox
  src/material-experimental/mdc-progress-bar/progress-bar.html
  src/material-experimental/mdc-progress-bar/progress-bar.spec.ts
  src/material/progress-bar/progress-bar.html
  src/material/progress-bar/progress-bar.spec.ts
Labels: G, P2, a11y, area: material/progress-bar, cla: yes, merge ready, target: patch

#22134 fix(material-experimental/mdc-select): fix floating label behavior
  src/material-experimental/mdc-select/select.ts
Labels: P2, cla: yes, merge ready, target: patch

#22137 fix(cdk/a11y): FocusTrap deprecation docs don't render correctly
  src/cdk/a11y/focus-trap/focus-trap.ts
  tools/dgeni/templates/macros.html
Labels: P2, area: cdk/a11y, cla: yes, docs, merge ready, target: patch

#22138 fix(cdk/a11y): add ConfigurableFocusTrapConfig to the public API
  src/cdk/a11y/focus-trap/configurable-focus-trap-config.ts
  src/cdk/a11y/focus-trap/configurable-focus-trap-factory.ts
  src/cdk/a11y/public-api.ts
  tools/public_api_guard/cdk/a11y.d.ts
Labels: P2, area: cdk/a11y, cla: yes, docs, merge ready, target: minor

#22261 fix(material/autocomplete): avoid assigning invalid aria-labelledby values
  src/material-experimental/mdc-autocomplete/autocomplete.spec.ts
  src/material/autocomplete/autocomplete-trigger.ts
  src/material/autocomplete/autocomplete.spec.ts
  src/material/autocomplete/autocomplete.ts
  tools/public_api_guard/material/autocomplete.d.ts
Labels: P3, a11y, cla: yes, merge ready, target: patch

#22260 fix(cdk/platform): avoid error during server-side rendering if document is stubbed out
  src/cdk/platform/features/scrolling.ts
Labels: P3, cla: yes, merge ready, target: patch

#22251 fix(material/select): trim aria-labelledby
  src/material-experimental/mdc-select/select.spec.ts
  src/material/select/select.spec.ts
  src/material/select/select.ts
Labels: P3, a11y, cla: yes, merge ready, target: patch

#22219 fix(material/progress-spinner): resolve accessibility issue in ChromeVox
  src/material-experimental/mdc-progress-spinner/progress-spinner.html
  src/material-experimental/mdc-progress-spinner/progress-spinner.spec.ts
  src/material/progress-spinner/progress-spinner.html
  src/material/progress-spinner/progress-spinner.spec.ts
Labels: P3, a11y, cla: yes, merge ready, target: patch

#22281 fix(material-experimental/mdc-button): remove unthemed icon color
  src/material-experimental/mdc-button/_button-theme.scss
Labels: G, P2, cla: yes, merge ready, target: minor

#22197 fix(cdk/text-field): autosize text areas using the placeholder
  scripts/check-mdc-tests-config.ts
  src/cdk/text-field/autosize.spec.ts
  src/cdk/text-field/autosize.ts
  src/material/input/input.spec.ts
  tools/public_api_guard/cdk/text-field.d.ts
Labels: area: cdk/text-field, cla: yes, merge ready, target: major

#22231 fix(material/grid-list): remove mat-figure class
  src/dev-app/screen-type/screen-type-demo.scss
  src/material/grid-list/grid-tile.html
Labels: P3, cla: yes, merge ready, target: minor

#22159 fix(google-maps): instantiate geocoder lazily
  src/google-maps/map-geocoder/map-geocoder.spec.ts
  src/google-maps/map-geocoder/map-geocoder.ts
Labels: P3, cla: yes, merge ready, target: minor

#22145 fix(material/radio): add high contrast focus indication
  src/material-experimental/mdc-radio/radio.scss
  src/material/radio/radio.scss
Labels: P3, a11y, cla: yes, merge ready, target: minor

#22296 Revert "fix(cdk/text-field): autosize text areas using the placeholder
  scripts/check-mdc-tests-config.ts
  src/cdk/text-field/autosize.spec.ts
  src/cdk/text-field/autosize.ts
  src/material/input/input.spec.ts
  tools/public_api_guard/cdk/text-field.d.ts
Labels: cla: yes, merge ready, target: major

#22295 ci: disable dependabot
  .github/dependabot.yml
Labels: area: dev-infra, cla: yes, merge ready, merge safe, target: patch

#22310 build: update material-components-web dependency
  package.json
  yarn.lock
Labels: cla: yes, merge ready, merge safe, target: minor

#22309 build: enforce that we use comments that won't show up in the generated output
  .stylelintrc.json
  src/dev-app/virtual-scroll/virtual-scroll-demo.scss
  src/material-experimental/mdc-button/fab.scss
  src/material-experimental/mdc-form-field/_mdc-text-field-structure-overrides.scss
  src/material-experimental/mdc-helpers/_focus-indicators-theme.scss
  src/material-experimental/mdc-helpers/_mdc-helpers.scss
  src/material/autocomplete/autocomplete.scss
  src/material/core/focus-indicators/_focus-indicators-theme.scss
  src/material/core/ripple/_ripple-theme.scss
  src/material/core/style/_menu-common.scss
  src/material/core/style/_vendor-prefixes.scss
  src/material/core/typography/_typography.scss
  src/material/expansion/expansion-panel-header.scss
  src/material/progress-spinner/progress-spinner.scss
  src/material/slide-toggle/slide-toggle.scss
  src/material/snack-bar/snack-bar-container.scss
  src/material/table/_table-flex-styles.scss
  src/material/table/table.scss
  src/material/toolbar/toolbar.scss
  tools/stylelint/single-line-comment-only.ts
Labels: P3, cla: yes, merge ready, merge safe, target: major

#22300 feat(slider): show background-color in print stylesheet (#11364)
  src/material/slider/slider.scss
Labels: cla: yes, merge ready, target: patch

#22254 fix(material/stepper): setting invalid value for visibility
  src/material/stepper/stepper-animations.ts
Labels: P3, cla: yes, merge ready, target: patch

#22194 fix(material-experimental/mdc-form-field): use coercion for boolean input
  src/material-experimental/mdc-form-field/form-field.ts
Labels: G, P2, cla: yes, merge ready, target: minor

#22187 fix(material-experimental/mdc-select): float label on focus if there's a placeholder
  scripts/check-mdc-tests-config.ts
  src/material-experimental/mdc-select/select.spec.ts
  src/material-experimental/mdc-select/select.ts
Labels: P2, cla: yes, merge ready, target: patch

#22302 fix(google-maps): initialize directions service lazily
  src/google-maps/map-directions-renderer/map-directions-service.spec.ts
  src/google-maps/map-directions-renderer/map-directions-service.ts
Labels: P3, cla: yes, merge ready, target: minor

#22268 docs(material/theming): rewrite theming guide for `@use`
  guides/getting-started.md
  guides/theming.md
Labels: cla: yes, docs, merge ready, merge safe, target: major

#22098 fix(google-maps): ensure that a mapTypeId is always passed in
  src/google-maps/google-map/google-map.spec.ts
  src/google-maps/google-map/google-map.ts
Labels: P3, cla: yes, merge ready, target: patch

#22046 feat(material/menu): allow updating menu position a la autocomplete
  src/material-experimental/mdc-menu/menu.spec.ts
  src/material/menu/menu-trigger.ts
  src/material/menu/menu.spec.ts
  tools/public_api_guard/material/menu.d.ts
Labels: P3, cla: yes, merge ready, target: minor

#22324 build: revert rollup to 1.25.0
  package.json
  yarn.lock
Labels: cla: yes

#22336 release: bump version to 11.2.6 w/ changelog
  CHANGELOG.md
  package.json
Labels: cla: yes, merge safe

#22321 feat(cdk/testing): create a webdriver harness environment
  package.json
  rollup-globals.bzl
  src/cdk/config.bzl
  src/cdk/testing/webdriver/BUILD.bazel
  src/cdk/testing/webdriver/index.ts
  src/cdk/testing/webdriver/public-api.ts
  src/cdk/testing/webdriver/webdriver-element.ts
  src/cdk/testing/webdriver/webdriver-harness-environment.ts
  src/cdk/testing/webdriver/webdriver-keys.ts
  src/cdk/tsconfig-tests.json
  tools/public_api_guard/cdk/testing/webdriver.d.ts
  tools/public_api_guard/generate-guard-tests.bzl
  yarn.lock
Labels: cla: yes, target: feature branch

#22304 feat(material/schematics): add migration to switch to the new theming API
  src/cdk/_index.scss
  src/material/schematics/collection.json
  src/material/schematics/ng-generate/theming-api/index.spec.ts
  src/material/schematics/ng-generate/theming-api/index.ts
  src/material/schematics/ng-generate/theming-api/migration.ts
  src/material/schematics/ng-generate/theming-api/schema.json
  src/material/schematics/ng-generate/theming-api/schema.ts
Labels: P2, cla: yes, merge ready, merge safe, target: major

#22316 fix(material/checkbox): native input not in sync if checked state is changed inside event
  src/material-experimental/mdc-checkbox/checkbox.spec.ts
  src/material-experimental/mdc-checkbox/checkbox.ts
  src/material/checkbox/checkbox.spec.ts
  src/material/checkbox/checkbox.ts
Labels: P3, cla: yes, merge ready, target: patch

#22326 build: align MDC version requirement
  packages.bzl
Labels: P3, cla: yes, merge ready, merge safe, target: major

#22338 refactor(material-experimental/mdc-core): expose new @use-based Sass API
  src/dev-app/BUILD.bazel
  src/dev-app/theme.scss
  src/e2e-app/BUILD.bazel
  src/e2e-app/theme.scss
  src/material-experimental/BUILD.bazel
  src/material-experimental/_index.scss
  src/material-experimental/column-resize/_column-resize-theme.scss
  src/material-experimental/column-resize/_column-resize.import.scss
  src/material-experimental/mdc-core/_core-theme.scss
  src/material-experimental/mdc-core/option/_optgroup-theme.scss
  src/material-experimental/mdc-core/option/_option-theme.import.scss
  src/material-experimental/mdc-core/option/_option-theme.scss
  src/material-experimental/mdc-helpers/_mdc-helpers.scss
  src/material-experimental/mdc-typography/_all-typography.import.scss
  src/material-experimental/mdc-typography/_all-typography.scss
  src/material-experimental/popover-edit/_popover-edit-theme.scss
  src/material-experimental/popover-edit/_popover-edit.import.scss
  tools/stylelint/theme-mixin-api.ts
Labels: P2, cla: yes, merge ready, target: major

#22345 feat(google-maps): add clusterer click event
  src/google-maps/map-marker-clusterer/map-marker-clusterer.spec.ts
  src/google-maps/map-marker-clusterer/map-marker-clusterer.ts
  tools/public_api_guard/google-maps/google-maps.d.ts
Labels: P3, cla: yes, merge ready, target: minor

#22359 refactor(cdk/overlay): clean up variable names
  src/cdk/_index.scss
  src/cdk/overlay/_overlay-deprecated.scss
  src/cdk/overlay/_overlay.import.scss
  src/cdk/overlay/_overlay.scss
  src/material/schematics/ng-generate/theming-api/index.spec.ts
  src/material/schematics/ng-generate/theming-api/migration.ts
Labels: P2, cla: yes, merge ready, target: major

#22344 test(cdk/testing): Get webdriver test suite running with dummy tests
  src/cdk/testing/tests/BUILD.bazel
  src/cdk/testing/tests/webdriver.e2e.spec.ts
Labels: cla: yes, target: feature branch

#22364 fix(material/progress-spinner): not visible in high contrast mode on chromium browsers
  src/material/progress-spinner/progress-spinner.scss
Labels: P3, a11y, cla: yes, merge ready, target: patch

#22299 feat(radio/checkbox): show background-color in print stylesheet (#22298)
  src/material-experimental/mdc-checkbox/checkbox.scss
  src/material/checkbox/checkbox.scss
  src/material/radio/radio.scss
Labels: cla: yes, merge ready, target: patch

#22346 fix(material-experimental/mdc-tooltip): use new MDC class names
  src/material-experimental/mdc-tooltip/tooltip.html
Labels: cla: yes, merge ready, merge safe, target: minor

#22380 release: bump version to 11.2.7 w/ changelog
  CHANGELOG.md
  package.json
Labels: cla: yes, merge ready, merge safe

#22381 release: bump version to 12.0.0-next.5 w/ changelog
  CHANGELOG.md
  package.json
Labels: cla: yes
