Repository angular/components, pull requests merged in 2022-08, with the labels that each got.

#25364 fix(cdk/schematics): strip bom from sass files
  src/cdk/schematics/update-tool/component-resource-collector.ts
Labels: P3, merge ready, merge safe, target: patch

#25368 build: fix error in size tests
  goldens/size-test.yaml
  integration/size-test/material/select/BUILD.bazel
Labels: P3, merge ready, merge safe, target: major

#25317 docs(cdk-experimental/listbox): add docs & examples
  src/cdk-experimental/listbox/listbox.md
  src/cdk-experimental/listbox/listbox.spec.ts
  src/cdk-experimental/listbox/listbox.ts
  src/components-examples/cdk-experimental/listbox/BUILD.bazel
  src/components-examples/cdk-experimental/listbox/cdk-listbox-activedescendant/cdk-listbox-activedescendant-example.css
  src/components-examples/cdk-experimental/listbox/cdk-listbox-activedescendant/cdk-listbox-activedescendant-example.html
  src/components-examples/cdk-experimental/listbox/cdk-listbox-activedescendant/cdk-listbox-activedescendant-example.ts
  src/components-examples/cdk-experimental/listbox/cdk-listbox-compare-with/cdk-listbox-compare-with-example.css
  src/components-examples/cdk-experimental/listbox/cdk-listbox-compare-with/cdk-listbox-compare-with-example.html
  src/components-examples/cdk-experimental/listbox/cdk-listbox-compare-with/cdk-listbox-compare-with-example.ts
  src/components-examples/cdk-experimental/listbox/cdk-listbox-custom-navigation/cdk-listbox-custom-navigation-example.css
  src/components-examples/cdk-experimental/listbox/cdk-listbox-custom-navigation/cdk-listbox-custom-navigation-example.html
  src/components-examples/cdk-experimental/listbox/cdk-listbox-custom-navigation/cdk-listbox-custom-navigation-example.ts
  src/components-examples/cdk-experimental/listbox/cdk-listbox-custom-typeahead/cdk-listbox-custom-typeahead-example.css
  src/components-examples/cdk-experimental/listbox/cdk-listbox-custom-typeahead/cdk-listbox-custom-typeahead-example.html
  src/components-examples/cdk-experimental/listbox/cdk-listbox-custom-typeahead/cdk-listbox-custom-typeahead-example.ts
  src/components-examples/cdk-experimental/listbox/cdk-listbox-disabled/cdk-listbox-disabled-example.css
  src/components-examples/cdk-experimental/listbox/cdk-listbox-disabled/cdk-listbox-disabled-example.html
  src/components-examples/cdk-experimental/listbox/cdk-listbox-disabled/cdk-listbox-disabled-example.ts
  src/components-examples/cdk-experimental/listbox/cdk-listbox-forms-validation/cdk-listbox-forms-validation-example.css
  src/components-examples/cdk-experimental/listbox/cdk-listbox-forms-validation/cdk-listbox-forms-validation-example.html
  src/components-examples/cdk-experimental/listbox/cdk-listbox-forms-validation/cdk-listbox-forms-validation-example.ts
  src/components-examples/cdk-experimental/listbox/cdk-listbox-horizontal/cdk-listbox-horizontal-example.css
  src/components-examples/cdk-experimental/listbox/cdk-listbox-horizontal/cdk-listbox-horizontal-example.html
  src/components-examples/cdk-experimental/listbox/cdk-listbox-horizontal/cdk-listbox-horizontal-example.ts
  src/components-examples/cdk-experimental/listbox/cdk-listbox-multiple/cdk-listbox-multiple-example.css
  src/components-examples/cdk-experimental/listbox/cdk-listbox-multiple/cdk-listbox-multiple-example.html
  src/components-examples/cdk-experimental/listbox/cdk-listbox-multiple/cdk-listbox-multiple-example.ts
  src/components-examples/cdk-experimental/listbox/cdk-listbox-overview/cdk-listbox-overview-example.css
  src/components-examples/cdk-experimental/listbox/cdk-listbox-overview/cdk-listbox-overview-example.html
  src/components-examples/cdk-experimental/listbox/cdk-listbox-overview/cdk-listbox-overview-example.ts
  src/components-examples/cdk-experimental/listbox/cdk-listbox-reactive-forms/cdk-listbox-reactive-forms-example.css
  src/components-examples/cdk-experimental/listbox/cdk-listbox-reactive-forms/cdk-listbox-reactive-forms-example.html
  src/components-examples/cdk-experimental/listbox/cdk-listbox-reactive-forms/cdk-listbox-reactive-forms-example.ts
  src/components-examples/cdk-experimental/listbox/cdk-listbox-template-forms/cdk-listbox-template-forms-example.css
  src/components-examples/cdk-experimental/listbox/cdk-listbox-template-forms/cdk-listbox-template-forms-example.html
  src/components-examples/cdk-experimental/listbox/cdk-listbox-template-forms/cdk-listbox-template-forms-example.ts
  src/components-examples/cdk-experimental/listbox/cdk-listbox-value-binding/cdk-listbox-value-binding-example.css
  src/components-examples/cdk-experimental/listbox/cdk-listbox-value-binding/cdk-listbox-value-binding-example.html
  src/components-examples/cdk-experimental/listbox/cdk-listbox-value-binding/cdk-listbox-value-binding-example.ts
  src/components-examples/cdk-experimental/listbox/index.ts
  src/dev-app/cdk-experimental-listbox/BUILD.bazel
  src/dev-app/cdk-experimental-listbox/cdk-listbox-demo.css
  src/dev-app/cdk-experimental-listbox/cdk-listbox-demo.html
  src/dev-app/cdk-experimental-listbox/cdk-listbox-demo.ts
Labels: merge ready, target: major, dev-app preview

#25372 docs(cdk-experimental/listbox): add docs & examples (#25317)
  src/cdk-experimental/listbox/listbox.md
  src/cdk-experimental/listbox/listbox.spec.ts
  src/cdk-experimental/listbox/listbox.ts
  src/components-examples/cdk-experimental/listbox/BUILD.bazel
  src/components-examples/cdk-experimental/listbox/cdk-listbox-activedescendant/cdk-listbox-activedescendant-example.css
  src/components-examples/cdk-experimental/listbox/cdk-listbox-activedescendant/cdk-listbox-activedescendant-example.html
  src/components-examples/cdk-experimental/listbox/cdk-listbox-activedescendant/cdk-listbox-activedescendant-example.ts
  src/components-examples/cdk-experimental/listbox/cdk-listbox-compare-with/cdk-listbox-compare-with-example.css
  src/components-examples/cdk-experimental/listbox/cdk-listbox-compare-with/cdk-listbox-compare-with-example.html
  src/components-examples/cdk-experimental/listbox/cdk-listbox-compare-with/cdk-listbox-compare-with-example.ts
  src/components-examples/cdk-experimental/listbox/cdk-listbox-custom-navigation/cdk-listbox-custom-navigation-example.css
  src/components-examples/cdk-experimental/listbox/cdk-listbox-custom-navigation/cdk-listbox-custom-navigation-example.html
  src/components-examples/cdk-experimental/listbox/cdk-listbox-custom-navigation/cdk-listbox-custom-navigation-example.ts
  src/components-examples/cdk-experimental/listbox/cdk-listbox-custom-typeahead/cdk-listbox-custom-typeahead-example.css
  src/components-examples/cdk-experimental/listbox/cdk-listbox-custom-typeahead/cdk-listbox-custom-typeahead-example.html
  src/components-examples/cdk-experimental/listbox/cdk-listbox-custom-typeahead/cdk-listbox-custom-typeahead-example.ts
  src/components-examples/cdk-experimental/listbox/cdk-listbox-disabled/cdk-listbox-disabled-example.css
  src/components-examples/cdk-experimental/listbox/cdk-listbox-disabled/cdk-listbox-disabled-example.html
  src/components-examples/cdk-experimental/listbox/cdk-listbox-disabled/cdk-listbox-disabled-example.ts
  src/components-examples/cdk-experimental/listbox/cdk-listbox-forms-validation/cdk-listbox-forms-validation-example.css
  src/components-examples/cdk-experimental/listbox/cdk-listbox-forms-validation/cdk-listbox-forms-validation-example.html
  src/components-examples/cdk-experimental/listbox/cdk-listbox-forms-validation/cdk-listbox-forms-validation-example.ts
  src/components-examples/cdk-experimental/listbox/cdk-listbox-horizontal/cdk-listbox-horizontal-example.css
  src/components-examples/cdk-experimental/listbox/cdk-listbox-horizontal/cdk-listbox-horizontal-example.html
  src/components-examples/cdk-experimental/listbox/cdk-listbox-horizontal/cdk-listbox-horizontal-example.ts
  src/components-examples/cdk-experimental/listbox/cdk-listbox-multiple/cdk-listbox-multiple-example.css
  src/components-examples/cdk-experimental/listbox/cdk-listbox-multiple/cdk-listbox-multiple-example.html
  src/components-examples/cdk-experimental/listbox/cdk-listbox-multiple/cdk-listbox-multiple-example.ts
  src/components-examples/cdk-experimental/listbox/cdk-listbox-overview/cdk-listbox-overview-example.css
  src/components-examples/cdk-experimental/listbox/cdk-listbox-overview/cdk-listbox-overview-example.html
  src/components-examples/cdk-experimental/listbox/cdk-listbox-overview/cdk-listbox-overview-example.ts
  src/components-examples/cdk-experimental/listbox/cdk-listbox-reactive-forms/cdk-listbox-reactive-forms-example.css
  src/components-examples/cdk-experimental/listbox/cdk-listbox-reactive-forms/cdk-listbox-reactive-forms-example.html
  src/components-examples/cdk-experimental/listbox/cdk-listbox-reactive-forms/cdk-listbox-reactive-forms-example.ts
  src/components-examples/cdk-experimental/listbox/cdk-listbox-template-forms/cdk-listbox-template-forms-example.css
  src/components-examples/cdk-experimental/listbox/cdk-listbox-template-forms/cdk-listbox-template-forms-example.html
  src/components-examples/cdk-experimental/listbox/cdk-listbox-template-forms/cdk-listbox-template-forms-example.ts
  src/components-examples/cdk-experimental/listbox/cdk-listbox-value-binding/cdk-listbox-value-binding-example.css
  src/components-examples/cdk-experimental/listbox/cdk-listbox-value-binding/cdk-listbox-value-binding-example.html
  src/components-examples/cdk-experimental/listbox/cdk-listbox-value-binding/cdk-listbox-value-binding-example.ts
  src/components-examples/cdk-experimental/listbox/index.ts
  src/dev-app/cdk-experimental-listbox/BUILD.bazel
  src/dev-app/cdk-experimental-listbox/cdk-listbox-demo.css
  src/dev-app/cdk-experimental-listbox/cdk-listbox-demo.html
  src/dev-app/cdk-experimental-listbox/cdk-listbox-demo.ts
Labels: merge ready, target: minor

#25374 Switch form field and select examples to MDC
  src/components-examples/material/form-field/BUILD.bazel
  src/components-examples/material/form-field/form-field-appearance/form-field-appearance-example.html
  src/components-examples/material/form-field/form-field-custom-control/form-field-custom-control-example.ts
  src/components-examples/material/form-field/form-field-error/form-field-error-example.css
  src/components-examples/material/form-field/form-field-harness/form-field-harness-example.spec.ts
  src/components-examples/material/form-field/form-field-hint/form-field-hint-example.css
  src/components-examples/material/form-field/form-field-label/form-field-label-example.css
  src/components-examples/material/form-field/form-field-label/form-field-label-example.html
  src/components-examples/material/form-field/form-field-label/form-field-label-example.ts
  src/components-examples/material/form-field/form-field-prefix-suffix/form-field-prefix-suffix-example.css
  src/components-examples/material/form-field/form-field-prefix-suffix/form-field-prefix-suffix-example.html
  src/components-examples/material/form-field/form-field-theming/form-field-theming-example.css
  src/components-examples/material/form-field/form-field-theming/form-field-theming-example.html
  src/components-examples/material/form-field/form-field-theming/form-field-theming-example.ts
  src/components-examples/material/form-field/index.ts
  src/components-examples/material/select/BUILD.bazel
  src/components-examples/material/select/index.ts
  src/components-examples/material/select/select-harness/select-harness-example.spec.ts
  src/components-examples/material/select/select-panel-class/select-panel-class-example.css
  src/material/form-field/form-field.md
Labels: P2, merge ready, merge safe, target: major

#25375 build: fix select e2e tests
  src/material/legacy-select/BUILD.bazel
  src/material/select/BUILD.bazel
  src/material/select/select.e2e.spec.ts
Labels: P2, merge ready, merge safe, target: major

#25373 fix(cdk-experimental/listbox): fix issue with aria-selected
  src/cdk-experimental/listbox/listbox.md
  src/cdk-experimental/listbox/listbox.spec.ts
  src/cdk-experimental/listbox/listbox.ts
  src/components-examples/cdk-experimental/listbox/cdk-listbox-activedescendant/cdk-listbox-activedescendant-example.css
  src/components-examples/cdk-experimental/listbox/cdk-listbox-compare-with/cdk-listbox-compare-with-example.css
  src/components-examples/cdk-experimental/listbox/cdk-listbox-custom-navigation/cdk-listbox-custom-navigation-example.css
  src/components-examples/cdk-experimental/listbox/cdk-listbox-custom-typeahead/cdk-listbox-custom-typeahead-example.css
  src/components-examples/cdk-experimental/listbox/cdk-listbox-disabled/cdk-listbox-disabled-example.css
  src/components-examples/cdk-experimental/listbox/cdk-listbox-forms-validation/cdk-listbox-forms-validation-example.css
  src/components-examples/cdk-experimental/listbox/cdk-listbox-horizontal/cdk-listbox-horizontal-example.css
  src/components-examples/cdk-experimental/listbox/cdk-listbox-multiple/cdk-listbox-multiple-example.css
  src/components-examples/cdk-experimental/listbox/cdk-listbox-overview/cdk-listbox-overview-example.css
  src/components-examples/cdk-experimental/listbox/cdk-listbox-reactive-forms/cdk-listbox-reactive-forms-example.css
  src/components-examples/cdk-experimental/listbox/cdk-listbox-template-forms/cdk-listbox-template-forms-example.css
  src/components-examples/cdk-experimental/listbox/cdk-listbox-value-binding/cdk-listbox-value-binding-example.css
Labels: merge ready, target: minor

#25379 build: split material ng-update schematics to a separate bundle
  src/cdk/schematics/BUILD.bazel
  src/cdk/schematics/ng-update/test-cases/misc/external-resource-resolution.spec.ts
  src/cdk/schematics/ng-update/test-cases/misc/global-stylesheets.spec.ts
  src/cdk/schematics/ng-update/test-cases/misc/method-call-checks.spec.ts
  src/cdk/schematics/testing/index.ts
  src/cdk/schematics/testing/resolve-bazel-path.ts
  src/material/schematics/BUILD.bazel
  src/material/schematics/migration.json
  src/material/schematics/ng-generate/mdc-migration/BUILD.bazel
  src/material/schematics/ng-update/BUILD.bazel
  src/material/schematics/ng-update/migrations/hammer-gestures-v9/find-hammer-script-tags.ts
  src/material/schematics/ng-update/migrations/hammer-gestures-v9/gesture-config-template.ts
  src/material/schematics/ng-update/migrations/hammer-gestures-v9/hammer-gestures-migration.ts
  src/material/schematics/ng-update/migrations/hammer-gestures-v9/hammer-template-check.ts
  src/material/schematics/ng-update/migrations/package-imports-v8/material-symbols.json
  src/material/schematics/ng-update/migrations/package-imports-v8/material-symbols.ts
  src/material/schematics/ng-update/migrations/package-imports-v8/secondary-entry-points-migration.ts
  src/material/schematics/ng-update/test-cases/misc/class-inheritance.spec.ts
  src/material/schematics/ng-update/test-cases/misc/constructor-checks.spec.ts
  src/material/schematics/ng-update/test-cases/misc/import-checks.spec.ts
  src/material/schematics/ng-update/test-cases/misc/symbol-removal.spec.ts
  src/material/schematics/ng-update/test-cases/v8/misc/material-imports.spec.ts
  src/material/schematics/ng-update/test-cases/v9/misc/hammer-migration-v9.spec.ts
  src/material/schematics/ng-update/test-cases/v9/misc/material-imports.spec.ts
  src/material/schematics/ng-update/tsconfig.json
  src/material/schematics/paths.ts
Labels: merge ready, target: major

#25388 build: fix snapshot tests failure
  src/material/schematics/ng-update/BUILD.bazel
Labels: merge ready, merge safe, target: major

#25383 fix(material/form-field): remove hardcoded 16px label padding
  src/material/form-field/_mdc-text-field-structure-overrides.scss
  src/material/form-field/form-field.ts
Labels: merge ready, target: major

#25399 feat(material/form-field): Ability to support custom error message components inside a form field
  src/material/form-field/directives/error.ts
  src/material/form-field/form-field.html
  src/material/form-field/testing/shared.spec.ts
  tools/public_api_guard/material/form-field.md
Labels: merge ready, target: major

#25359 feat(material/datepicker): Allow user to jump between start and end d…
  src/material/datepicker/date-range-input-parts.ts
  src/material/datepicker/date-range-input.spec.ts
  tools/public_api_guard/material/datepicker.md
Labels: merge ready, G, target: minor, dev-app preview

#25356 fix(material/dialog): using incorrect mixin for structural styles
  src/material/dialog/_dialog-theme.scss
  src/material/dialog/dialog.scss
Labels: P3, merge ready, target: major

#25398 fix(material/input): fix input prefix & suffix disabled color
  src/material/legacy-input/_input-theme.scss
Labels: merge ready, target: major

#25402 refactor(material/tooltip): switch to new theming API
  package.json
  packages.bzl
  src/material/tooltip/_tooltip-theme.scss
  src/material/tooltip/tooltip.scss
  yarn.lock
Labels: P3, merge ready, target: major

#25395 feat(material/schematics): v15 ng-update scss migration
  src/material/schematics/ng-update/BUILD.bazel
  src/material/schematics/ng-update/migrations/legacy-components-v15/constants.ts
  src/material/schematics/ng-update/migrations/legacy-components-v15/index.ts
  src/material/schematics/ng-update/test-cases/v15/legacy-components-v15.spec.ts
Labels: merge ready, merge safe, target: major

#25419 feat(material/checkbox): refactor pseudo-checkbox size styles
  src/material/_index.scss
  src/material/core/selection/pseudo-checkbox/_pseudo-checkbox-common.scss
  src/material/core/selection/pseudo-checkbox/pseudo-checkbox.scss
  src/material/core/style/_checkbox-common.scss
Labels: merge ready, target: major

#25424 feat(material/checkbox): use $legacy-size for legacy checkbox
  src/material/legacy-checkbox/checkbox.scss
Labels: merge ready, target: major

#25426 Revert "fix(material/tooltip): avoid problem when triggers hide anima…
  src/material/tooltip/tooltip.ts
Labels: merge ready, target: patch

#24906 fix(material/chips): `selectable="false"` doesn't work on initial assignment
  src/material/chips/chip-listbox.spec.ts
  src/material/legacy-chips/chip-list.spec.ts
  src/material/legacy-chips/chip-list.ts
Labels: merge ready, target: patch

#25202 feat(material/tooltip): add option to open tooltip at mouse position
  src/cdk/overlay/position/flexible-connected-position-strategy.ts
  src/components-examples/material/tooltip/index.ts
  src/components-examples/material/tooltip/tooltip-position-at-origin/tooltip-position-at-origin-example.css
  src/components-examples/material/tooltip/tooltip-position-at-origin/tooltip-position-at-origin-example.html
  src/components-examples/material/tooltip/tooltip-position-at-origin/tooltip-position-at-origin-example.ts
  src/dev-app/tooltip/tooltip-demo.html
  src/material/legacy-tooltip/tooltip.spec.ts
  src/material/tooltip/tooltip.md
  src/material/tooltip/tooltip.spec.ts
  src/material/tooltip/tooltip.ts
Labels: merge ready, target: major

#25429 build: fix CI issues
  src/material/chips/chip-list.spec.ts
Labels: merge ready, target: patch

#25430 Revert "feat(material/tooltip): add option to open tooltip at mouse position (#25202)"
  src/cdk/overlay/position/flexible-connected-position-strategy.ts
  src/components-examples/material/tooltip/index.ts
  src/components-examples/material/tooltip/tooltip-position-at-origin/tooltip-position-at-origin-example.css
  src/components-examples/material/tooltip/tooltip-position-at-origin/tooltip-position-at-origin-example.html
  src/components-examples/material/tooltip/tooltip-position-at-origin/tooltip-position-at-origin-example.ts
  src/dev-app/tooltip/tooltip-demo.html
  src/material/legacy-tooltip/tooltip.spec.ts
  src/material/tooltip/tooltip.md
  src/material/tooltip/tooltip.spec.ts
  src/material/tooltip/tooltip.ts
Labels: merge ready, target: major

#25412 fix(material-experimental/mdc-list): set a role on MatNavList and Mat…
  src/material-experimental/mdc-list/action-list.ts
  src/material-experimental/mdc-list/list.spec.ts
  src/material-experimental/mdc-list/nav-list.ts
  src/material/list/list.spec.ts
  src/material/list/list.ts
Labels: a11y, merge ready, target: patch, area: material/list

#25442 fix(material/legacy-checkbox): fix scss mixin names
  src/material/_index.scss
Labels: merge ready, target: major

#25439 Revert "Revert "feat(material/tooltip): add option to open tooltip at…
  src/cdk/overlay/position/flexible-connected-position-strategy.ts
  src/components-examples/material/tooltip/index.ts
  src/components-examples/material/tooltip/tooltip-position-at-origin/tooltip-position-at-origin-example.css
  src/components-examples/material/tooltip/tooltip-position-at-origin/tooltip-position-at-origin-example.html
  src/components-examples/material/tooltip/tooltip-position-at-origin/tooltip-position-at-origin-example.ts
  src/dev-app/tooltip/tooltip-demo.html
  src/material/legacy-tooltip/tooltip.spec.ts
  src/material/tooltip/tooltip.md
  src/material/tooltip/tooltip.spec.ts
  src/material/tooltip/tooltip.ts
  tools/public_api_guard/cdk/overlay.md
  tools/public_api_guard/material/tooltip.md
Labels: merge ready, target: major

#25448 Bump version to "v14.1.2" with changelog.
  CHANGELOG.md
  package.json
Labels: merge ready, target: patch

#25449 docs: release notes for the v14.1.2 release
  CHANGELOG.md
Labels: merge ready, target: minor

#25450 Bump version to "v14.2.0-next.2" with changelog.
  CHANGELOG.md
  package.json
Labels: merge ready, target: minor

#25451 docs: release notes for the v14.2.0-next.2 release
  CHANGELOG.md
Labels: merge ready, target: major

#25425 feat(material/checkbox): update pseudo-checkbox size
  src/material/core/selection/pseudo-checkbox/pseudo-checkbox.scss
  src/material/core/style/_checkbox-common.scss
Labels: merge ready, target: major

#25459 fix(material/legacy-button): rename classnames in comments
  src/material/legacy-button/button.ts
  src/material/legacy-button/testing/button-harness.ts
Labels: merge ready, merge safe, target: major

#25460 fix(material/legacy-button): rename classnames in comments
  src/material/legacy-button/testing/button-harness-filters.ts
Labels: merge ready, merge safe, target: major

#25454 refactor(material/card): switch to new theming API
  src/material/card/_card-theme.scss
  src/material/card/card.scss
  src/material/card/card.ts
Labels: P3, merge ready, target: major

#25406 fix(cdk/dialog): fall back to node injector token doesn't exist in template injector
  src/cdk/dialog/dialog.spec.ts
  src/cdk/dialog/dialog.ts
Labels: P3, merge ready, target: patch

#25447 feat(material/schematics): impl mat-mdc ts v15 ng-update
  src/material/schematics/ng-update/migrations/legacy-components-v15/constants.ts
  src/material/schematics/ng-update/migrations/legacy-components-v15/index.ts
  src/material/schematics/ng-update/test-cases/v15/legacy-components-v15.spec.ts
Labels: merge ready, merge safe, target: major

#25464 Revert "refactor(material/card): switch to new theming API"
  src/material/card/_card-theme.scss
  src/material/card/card.scss
  src/material/card/card.ts
Labels: merge ready, target: major

#20019 fix(expansion): fix expansion `.mat-expansion-panel-header` styles
  src/components-examples/material/expansion/expansion-expand-collapse-all/expansion-expand-collapse-all-example.css
  src/components-examples/material/expansion/expansion-steps/expansion-steps-example.css
  src/material/expansion/expansion-panel-header.html
  src/material/expansion/expansion-panel-header.scss
  src/material/expansion/expansion.spec.ts
Labels: merge ready, caretaker note, target: patch

#25469 fix(material/expansion): fix lint issue
  src/material/expansion/expansion.spec.ts
Labels: merge ready, merge safe, target: patch

#24713 fix(material/button-toggle): toggle name falling out of sync if name changes
  src/material/button-toggle/button-toggle.html
  src/material/button-toggle/button-toggle.spec.ts
  src/material/button-toggle/button-toggle.ts
  tools/public_api_guard/material/button-toggle.md
Labels: P3, merge ready, target: patch

#25165 feat(youtube-player): support no cookie mode
  src/dev-app/youtube-player/BUILD.bazel
  src/dev-app/youtube-player/youtube-player-demo.html
  src/dev-app/youtube-player/youtube-player-demo.ts
  src/youtube-player/youtube-player.spec.ts
  src/youtube-player/youtube-player.ts
  tools/public_api_guard/youtube-player/youtube-player.md
Labels: merge ready, merge safe, target: major

#25466 refactor(material/card): switch to new theming API
  src/material/card/_card-theme.scss
  src/material/card/card.scss
  src/material/card/card.ts
Labels: P3, merge ready, target: major

#25380 feat(cdk/listbox): add listbox to cdk
  .github/CODEOWNERS
  .ng-dev/commit-message.mts
  scripts/approve-api-golden.js
  src/cdk-experimental/config.bzl
  src/cdk/config.bzl
  src/cdk/listbox/BUILD.bazel
  src/cdk/listbox/index.ts
  src/cdk/listbox/listbox-module.ts
  src/cdk/listbox/listbox.md
  src/cdk/listbox/listbox.spec.ts
  src/cdk/listbox/listbox.ts
  src/cdk/listbox/public-api.ts
  src/components-examples/cdk/listbox/BUILD.bazel
  src/components-examples/cdk/listbox/cdk-listbox-activedescendant/cdk-listbox-activedescendant-example.css
  src/components-examples/cdk/listbox/cdk-listbox-activedescendant/cdk-listbox-activedescendant-example.html
  src/components-examples/cdk/listbox/cdk-listbox-activedescendant/cdk-listbox-activedescendant-example.ts
  src/components-examples/cdk/listbox/cdk-listbox-compare-with/cdk-listbox-compare-with-example.css
  src/components-examples/cdk/listbox/cdk-listbox-compare-with/cdk-listbox-compare-with-example.html
  src/components-examples/cdk/listbox/cdk-listbox-compare-with/cdk-listbox-compare-with-example.ts
  src/components-examples/cdk/listbox/cdk-listbox-custom-navigation/cdk-listbox-custom-navigation-example.css
  src/components-examples/cdk/listbox/cdk-listbox-custom-navigation/cdk-listbox-custom-navigation-example.html
  src/components-examples/cdk/listbox/cdk-listbox-custom-navigation/cdk-listbox-custom-navigation-example.ts
  src/components-examples/cdk/listbox/cdk-listbox-custom-typeahead/cdk-listbox-custom-typeahead-example.css
  src/components-examples/cdk/listbox/cdk-listbox-custom-typeahead/cdk-listbox-custom-typeahead-example.html
  src/components-examples/cdk/listbox/cdk-listbox-custom-typeahead/cdk-listbox-custom-typeahead-example.ts
  src/components-examples/cdk/listbox/cdk-listbox-disabled/cdk-listbox-disabled-example.css
  src/components-examples/cdk/listbox/cdk-listbox-disabled/cdk-listbox-disabled-example.html
  src/components-examples/cdk/listbox/cdk-listbox-disabled/cdk-listbox-disabled-example.ts
  src/components-examples/cdk/listbox/cdk-listbox-forms-validation/cdk-listbox-forms-validation-example.css
  src/components-examples/cdk/listbox/cdk-listbox-forms-validation/cdk-listbox-forms-validation-example.html
  src/components-examples/cdk/listbox/cdk-listbox-forms-validation/cdk-listbox-forms-validation-example.ts
  src/components-examples/cdk/listbox/cdk-listbox-horizontal/cdk-listbox-horizontal-example.css
  src/components-examples/cdk/listbox/cdk-listbox-horizontal/cdk-listbox-horizontal-example.html
  src/components-examples/cdk/listbox/cdk-listbox-horizontal/cdk-listbox-horizontal-example.ts
  src/components-examples/cdk/listbox/cdk-listbox-multiple/cdk-listbox-multiple-example.css
  src/components-examples/cdk/listbox/cdk-listbox-multiple/cdk-listbox-multiple-example.html
  src/components-examples/cdk/listbox/cdk-listbox-multiple/cdk-listbox-multiple-example.ts
  src/components-examples/cdk/listbox/cdk-listbox-overview/cdk-listbox-overview-example.css
  src/components-examples/cdk/listbox/cdk-listbox-overview/cdk-listbox-overview-example.html
  src/components-examples/cdk/listbox/cdk-listbox-overview/cdk-listbox-overview-example.ts
  src/components-examples/cdk/listbox/cdk-listbox-reactive-forms/cdk-listbox-reactive-forms-example.css
  src/components-examples/cdk/listbox/cdk-listbox-reactive-forms/cdk-listbox-reactive-forms-example.html
  src/components-examples/cdk/listbox/cdk-listbox-reactive-forms/cdk-listbox-reactive-forms-example.ts
  src/components-examples/cdk/listbox/cdk-listbox-template-forms/cdk-listbox-template-forms-example.css
  src/components-examples/cdk/listbox/cdk-listbox-template-forms/cdk-listbox-template-forms-example.html
  src/components-examples/cdk/listbox/cdk-listbox-template-forms/cdk-listbox-template-forms-example.ts
  src/components-examples/cdk/listbox/cdk-listbox-value-binding/cdk-listbox-value-binding-example.css
  src/components-examples/cdk/listbox/cdk-listbox-value-binding/cdk-listbox-value-binding-example.html
  src/components-examples/cdk/listbox/cdk-listbox-value-binding/cdk-listbox-value-binding-example.ts
  src/components-examples/cdk/listbox/index.ts
  src/dev-app/BUILD.bazel
  src/dev-app/cdk-listbox/BUILD.bazel
  src/dev-app/cdk-listbox/cdk-listbox-demo.html
  src/dev-app/cdk-listbox/cdk-listbox-demo.ts
  src/dev-app/dev-app/dev-app-layout.ts
  src/dev-app/routes.ts
  tools/public_api_guard/cdk/listbox.md
Labels: merge ready, target: major, dev-app preview

#25474 feat(cdk/listbox): add listbox to cdk (#25380)
  .github/CODEOWNERS
  .ng-dev/commit-message.mts
  scripts/approve-api-golden.js
  src/cdk-experimental/config.bzl
  src/cdk/config.bzl
  src/cdk/listbox/BUILD.bazel
  src/cdk/listbox/index.ts
  src/cdk/listbox/listbox-module.ts
  src/cdk/listbox/listbox.md
  src/cdk/listbox/listbox.spec.ts
  src/cdk/listbox/listbox.ts
  src/cdk/listbox/public-api.ts
  src/components-examples/cdk/listbox/BUILD.bazel
  src/components-examples/cdk/listbox/cdk-listbox-activedescendant/cdk-listbox-activedescendant-example.css
  src/components-examples/cdk/listbox/cdk-listbox-activedescendant/cdk-listbox-activedescendant-example.html
  src/components-examples/cdk/listbox/cdk-listbox-activedescendant/cdk-listbox-activedescendant-example.ts
  src/components-examples/cdk/listbox/cdk-listbox-compare-with/cdk-listbox-compare-with-example.css
  src/components-examples/cdk/listbox/cdk-listbox-compare-with/cdk-listbox-compare-with-example.html
  src/components-examples/cdk/listbox/cdk-listbox-compare-with/cdk-listbox-compare-with-example.ts
  src/components-examples/cdk/listbox/cdk-listbox-custom-navigation/cdk-listbox-custom-navigation-example.css
  src/components-examples/cdk/listbox/cdk-listbox-custom-navigation/cdk-listbox-custom-navigation-example.html
  src/components-examples/cdk/listbox/cdk-listbox-custom-navigation/cdk-listbox-custom-navigation-example.ts
  src/components-examples/cdk/listbox/cdk-listbox-custom-typeahead/cdk-listbox-custom-typeahead-example.css
  src/components-examples/cdk/listbox/cdk-listbox-custom-typeahead/cdk-listbox-custom-typeahead-example.html
  src/components-examples/cdk/listbox/cdk-listbox-custom-typeahead/cdk-listbox-custom-typeahead-example.ts
  src/components-examples/cdk/listbox/cdk-listbox-disabled/cdk-listbox-disabled-example.css
  src/components-examples/cdk/listbox/cdk-listbox-disabled/cdk-listbox-disabled-example.html
  src/components-examples/cdk/listbox/cdk-listbox-disabled/cdk-listbox-disabled-example.ts
  src/components-examples/cdk/listbox/cdk-listbox-forms-validation/cdk-listbox-forms-validation-example.css
  src/components-examples/cdk/listbox/cdk-listbox-forms-validation/cdk-listbox-forms-validation-example.html
  src/components-examples/cdk/listbox/cdk-listbox-forms-validation/cdk-listbox-forms-validation-example.ts
  src/components-examples/cdk/listbox/cdk-listbox-horizontal/cdk-listbox-horizontal-example.css
  src/components-examples/cdk/listbox/cdk-listbox-horizontal/cdk-listbox-horizontal-example.html
  src/components-examples/cdk/listbox/cdk-listbox-horizontal/cdk-listbox-horizontal-example.ts
  src/components-examples/cdk/listbox/cdk-listbox-multiple/cdk-listbox-multiple-example.css
  src/components-examples/cdk/listbox/cdk-listbox-multiple/cdk-listbox-multiple-example.html
  src/components-examples/cdk/listbox/cdk-listbox-multiple/cdk-listbox-multiple-example.ts
  src/components-examples/cdk/listbox/cdk-listbox-overview/cdk-listbox-overview-example.css
  src/components-examples/cdk/listbox/cdk-listbox-overview/cdk-listbox-overview-example.html
  src/components-examples/cdk/listbox/cdk-listbox-overview/cdk-listbox-overview-example.ts
  src/components-examples/cdk/listbox/cdk-listbox-reactive-forms/cdk-listbox-reactive-forms-example.css
  src/components-examples/cdk/listbox/cdk-listbox-reactive-forms/cdk-listbox-reactive-forms-example.html
  src/components-examples/cdk/listbox/cdk-listbox-reactive-forms/cdk-listbox-reactive-forms-example.ts
  src/components-examples/cdk/listbox/cdk-listbox-template-forms/cdk-listbox-template-forms-example.css
  src/components-examples/cdk/listbox/cdk-listbox-template-forms/cdk-listbox-template-forms-example.html
  src/components-examples/cdk/listbox/cdk-listbox-template-forms/cdk-listbox-template-forms-example.ts
  src/components-examples/cdk/listbox/cdk-listbox-value-binding/cdk-listbox-value-binding-example.css
  src/components-examples/cdk/listbox/cdk-listbox-value-binding/cdk-listbox-value-binding-example.html
  src/components-examples/cdk/listbox/cdk-listbox-value-binding/cdk-listbox-value-binding-example.ts
  src/components-examples/cdk/listbox/index.ts
  src/dev-app/BUILD.bazel
  src/dev-app/cdk-listbox/BUILD.bazel
  src/dev-app/cdk-listbox/cdk-listbox-demo.html
  src/dev-app/cdk-listbox/cdk-listbox-demo.ts
  src/dev-app/dev-app/dev-app-layout.ts
  src/dev-app/routes.ts
  tools/public_api_guard/cdk/listbox.md
Labels: merge ready, merge safe, target: minor

#25477 docs(cdk/listbox): make listbox examples available
  src/components-examples/cdk/listbox/cdk-listbox-multiple/cdk-listbox-multiple-example.html
  src/components-examples/config.bzl
Labels: merge ready, merge safe, target: minor

#25328 docs(material/custom-form-field): fixed propname
  guides/creating-a-custom-form-field-control.md
Labels: docs, merge ready, merge safe, target: patch, commit message fixup

#25339 feat(material/schematics): add style migration support within typescipt files
  src/material/schematics/ng-generate/mdc-migration/rules/theming-styles.ts
  src/material/schematics/ng-generate/mdc-migration/rules/ts-migration/runtime-migration.ts
  src/material/schematics/ng-generate/mdc-migration/rules/ts-migration/runtime-migrator.spec.ts
Labels: merge ready, merge safe, target: major, area: ng-generate

#25482 feat(material/table): pass `this` rather than concrete classes in the harnesses
  src/material/legacy-table/testing/cell-harness.ts
  src/material/table/testing/cell-harness.ts
Labels: merge ready, merge safe, target: major

#25487 fix(cdk/overlay): backdropClass type mismatch
  src/cdk/overlay/overlay-directives.ts
  tools/public_api_guard/cdk/overlay.md
Labels: P3, merge ready, target: patch

#25486 feat(material/core): move MDC-based elevation styles out of experimental
  src/material-experimental/_index.scss
  src/material-experimental/mdc-core/_core-theme.scss
  src/material-experimental/mdc-core/_elevation.scss
  src/material/core/_core-theme.scss
  src/material/core/style/_elevation.scss
  src/material/core/style/_private.scss
  src/material/legacy-core/_core-theme.scss
  src/material/menu/menu.spec.ts
  src/material/menu/menu.ts
Labels: merge ready, target: major

#25496 feat(material/schematics): add template migration support within typescript files
  src/material/schematics/ng-generate/mdc-migration/rules/template-migration.ts
  src/material/schematics/ng-generate/mdc-migration/rules/theming-styles.ts
  src/material/schematics/ng-generate/mdc-migration/rules/ts-migration/runtime-migration.ts
  src/material/schematics/ng-generate/mdc-migration/rules/ts-migration/runtime-migrator.spec.ts
Labels: merge ready, merge safe, target: major, area: ng-generate

#25505 build: update to TypeScript 4.8
  integration/harness-e2e-cli/package.json
  integration/harness-e2e-cli/yarn.lock
  integration/ng-add-standalone/package.json
  integration/ng-add-standalone/yarn.lock
  integration/ng-add/package.json
  integration/ng-add/yarn.lock
  integration/ng-update-v13/package.json
  integration/ng-update-v13/yarn.lock
  integration/yarn-pnp-compat/yarn.lock
  package.json
  scripts/caretaking/firebase-functions/package.json
  scripts/caretaking/firebase-functions/yarn.lock
  src/cdk/schematics/update-tool/component-resource-collector.ts
  src/material/datepicker/datepicker-actions.ts
  src/material/schematics/ng-update/migrations/hammer-gestures-v9/hammer-gestures-migration.ts
  tools/dgeni/common/directive-metadata.ts
  tools/example-module/parse-example-file.ts
  tools/integration.bzl
  tools/public_api_guard/material/datepicker.md
  tools/tslint-rules/lightweightTokensRule.ts
  tools/tslint-rules/memberNamingRule.ts
  tools/tslint-rules/noHostDecoratorInConcreteRule.ts
  tools/tslint-rules/noPrivateGettersRule.ts
  tools/tslint-rules/noUndecoratedBaseClassDiRule.ts
  tools/tslint-rules/noUndecoratedClassWithAngularFeaturesRule.ts
  tools/tslint-rules/preferConstEnumRule.ts
  tools/tslint-rules/settersAfterGettersRule.ts
  tools/tslint-rules/validateDecoratorsRule.ts
  yarn.lock
Labels: P2, merge ready, target: minor

#25506 build: migrate MDC input demo
  .github/CODEOWNERS
  src/components-examples/config.bzl
  src/components-examples/material/form-field/index.ts
  src/dev-app/BUILD.bazel
  src/dev-app/dev-app/dev-app-layout.ts
  src/dev-app/input/BUILD.bazel
  src/dev-app/input/input-demo.html
  src/dev-app/input/input-demo.scss
  src/dev-app/input/input-demo.ts
  src/dev-app/legacy-input/BUILD.bazel
  src/dev-app/legacy-input/legacy-input-demo.html
  src/dev-app/legacy-input/legacy-input-demo.scss
  src/dev-app/legacy-input/legacy-input-demo.ts
  src/dev-app/mdc-input/BUILD.bazel
  src/dev-app/routes.ts
  src/material/BUILD.bazel
  src/material/legacy-form-field/BUILD.bazel
  src/material/legacy-form-field/form-field.md
Labels: merge ready, merge safe, target: major

#25509 build: remove legacy component overviews
  src/material/legacy-autocomplete/BUILD.bazel
  src/material/legacy-autocomplete/autocomplete.md
  src/material/legacy-button/BUILD.bazel
  src/material/legacy-button/button.md
  src/material/legacy-card/BUILD.bazel
  src/material/legacy-card/card.md
  src/material/legacy-checkbox/BUILD.bazel
  src/material/legacy-checkbox/checkbox.md
  src/material/legacy-chips/BUILD.bazel
  src/material/legacy-chips/chips.md
  src/material/legacy-core/BUILD.bazel
  src/material/legacy-core/legacy-core.md
  src/material/legacy-dialog/BUILD.bazel
  src/material/legacy-dialog/dialog.md
  src/material/legacy-input/BUILD.bazel
  src/material/legacy-input/input.md
  src/material/legacy-list/BUILD.bazel
  src/material/legacy-list/list.md
  src/material/legacy-menu/BUILD.bazel
  src/material/legacy-menu/menu.md
  src/material/legacy-progress-bar/BUILD.bazel
  src/material/legacy-progress-bar/progress-bar.md
  src/material/legacy-progress-spinner/BUILD.bazel
  src/material/legacy-progress-spinner/progress-spinner.md
  src/material/legacy-radio/BUILD.bazel
  src/material/legacy-radio/radio.md
  src/material/legacy-select/BUILD.bazel
  src/material/legacy-select/select.md
  src/material/legacy-slide-toggle/BUILD.bazel
  src/material/legacy-slide-toggle/slide-toggle.md
  src/material/legacy-slider/BUILD.bazel
  src/material/legacy-slider/slider.md
  src/material/legacy-snack-bar/BUILD.bazel
  src/material/legacy-snack-bar/snack-bar.md
  src/material/legacy-table/table.md
  src/material/legacy-tabs/BUILD.bazel
  src/material/legacy-tabs/tabs.md
Labels: P3, merge ready, merge safe, target: major

#25512 build: invalidate circleci cache to prune unused nested node modules
  .circleci/config.yml
Labels: merge ready, merge safe, target: patch

#25503 fix(material/core): Move remaining MDC core functionality out of experimental
  .github/CODEOWNERS
  .ng-dev/commit-message.mts
  integration/yarn-pnp-compat/src/styles.scss
  src/dev-app/theme.scss
  src/e2e-app/theme.scss
  src/material-experimental/BUILD.bazel
  src/material-experimental/_index.scss
  src/material-experimental/config.bzl
  src/material-experimental/mdc-core/BUILD.bazel
  src/material-experimental/mdc-core/_core-theme.import.scss
  src/material-experimental/mdc-core/_core-theme.scss
  src/material-experimental/mdc-core/color/BUILD.bazel
  src/material-experimental/mdc-core/color/_all-color.import.scss
  src/material-experimental/mdc-core/color/_all-color.scss
  src/material-experimental/mdc-core/density/BUILD.bazel
  src/material-experimental/mdc-core/density/_all-density.import.scss
  src/material-experimental/mdc-core/density/_all-density.scss
  src/material-experimental/mdc-core/index.ts
  src/material-experimental/mdc-core/public-api.ts
  src/material-experimental/mdc-core/theming/BUILD.bazel
  src/material-experimental/mdc-core/theming/_all-theme.import.scss
  src/material-experimental/mdc-core/theming/_all-theme.scss
  src/material-experimental/mdc-core/theming/prebuilt/deeppurple-amber.scss
  src/material-experimental/mdc-core/theming/prebuilt/indigo-pink.scss
  src/material-experimental/mdc-core/theming/prebuilt/pink-bluegrey.scss
  src/material-experimental/mdc-core/theming/prebuilt/purple-green.scss
  src/material-experimental/mdc-core/theming/tests/BUILD.bazel
  src/material-experimental/mdc-core/theming/tests/test-theming.scss
  src/material-experimental/mdc-core/typography/BUILD.bazel
  src/material-experimental/mdc-core/typography/_all-typography.import.scss
  src/material-experimental/mdc-core/typography/_all-typography.scss
  src/material-experimental/package-base.json
  src/material/_index.scss
  src/material/core/_core-legacy-index.scss
  src/material/core/_core-theme.scss
  src/material/core/_core.import.scss
  src/material/core/density/private/_all-density.scss
  src/material/core/theming/_all-theme.scss
  src/material/core/theming/_theming.scss
  src/material/core/typography/_all-typography.scss
  src/material/legacy-core/_core-theme.scss
  src/material/legacy-core/_core.import.scss
  src/universal-app/theme.scss
Labels: merge ready, target: major

#25504 fix(material/schematics): make ts import replacements more specific
  src/material/schematics/ng-update/migrations/legacy-components-v15/constants.ts
  src/material/schematics/ng-update/migrations/legacy-components-v15/index.ts
  src/material/schematics/ng-update/test-cases/v15/legacy-components-v15.spec.ts
Labels: merge ready, merge safe, target: major

#25427 feat(cdk/a11y): add named export and public property to CdkMonitorFocus directive
  src/cdk/a11y/focus-monitor/focus-monitor.spec.ts
  src/cdk/a11y/focus-monitor/focus-monitor.ts
  tools/public_api_guard/cdk/a11y.md
Labels: merge ready, target: minor

#25461 fix(cdk/scrolling): error during server-side rendering
  src/cdk/scrolling/virtual-scroll-viewport.ts
Labels: P3, merge ready, target: patch

#25522 fix(material/schematics): make ts symbol renamings more specific
  src/material/schematics/ng-update/migrations/legacy-components-v15/index.ts
  src/material/schematics/ng-update/test-cases/v15/legacy-components-v15.spec.ts
Labels: merge ready, merge safe, target: major

#25517 docs(material/card): update docs & examples for MDC-based card
  .github/CODEOWNERS
  src/components-examples/config.bzl
  src/components-examples/material-experimental/mdc-card/BUILD.bazel
  src/components-examples/material-experimental/mdc-card/index.ts
  src/components-examples/material-experimental/mdc-card/mdc-card-fancy/mdc-card-fancy-example.css
  src/components-examples/material-experimental/mdc-card/mdc-card-fancy/mdc-card-fancy-example.html
  src/components-examples/material-experimental/mdc-card/mdc-card-fancy/mdc-card-fancy-example.ts
  src/components-examples/material/card/BUILD.bazel
  src/components-examples/material/card/card-actions/card-actions-example.html
  src/components-examples/material/card/card-footer/card-footer-example.html
  src/components-examples/material/card/card-harness/card-harness-example.spec.ts
  src/components-examples/material/card/card-media-size/card-media-size-example.html
  src/components-examples/material/card/card-overview/card-overview-example.html
  src/components-examples/material/card/card-subtitle/card-subtitle-example.html
  src/components-examples/material/card/index.ts
  src/dev-app/BUILD.bazel
  src/dev-app/card/BUILD.bazel
  src/dev-app/card/card-demo.html
  src/dev-app/card/card-demo.scss
  src/dev-app/card/card-demo.ts
  src/dev-app/dev-app/dev-app-layout.ts
  src/dev-app/legacy-card/BUILD.bazel
  src/dev-app/legacy-card/legacy-card-demo.html
  src/dev-app/legacy-card/legacy-card-demo.scss
  src/dev-app/legacy-card/legacy-card-demo.ts
  src/dev-app/mdc-card/BUILD.bazel
  src/dev-app/mdc-card/mdc-card-demo.html
  src/dev-app/mdc-card/mdc-card-demo.ts
  src/dev-app/routes.ts
  src/e2e-app/BUILD.bazel
  src/e2e-app/e2e-app/e2e-app-layout.ts
  src/e2e-app/main-module.ts
  src/e2e-app/mdc-card/mdc-card-e2e-module.ts
  src/e2e-app/mdc-card/mdc-card-e2e.ts
  src/e2e-app/routes.ts
  src/material/card/card.e2e.spec.ts
  src/material/card/card.md
  src/material/card/testing/card-harness.e2e.spec.ts
  src/material/legacy-card/BUILD.bazel
  src/material/legacy-card/card.e2e.spec.ts
  src/material/legacy-card/testing/BUILD.bazel
  src/material/legacy-card/testing/card-harness.e2e.spec.ts
Labels: merge ready, merge safe, target: major, comp: docs

#25523 fix(material/schematics): add renaming of non standard symbols
  src/material/schematics/ng-update/migrations/legacy-components-v15/constants.ts
  src/material/schematics/ng-update/migrations/legacy-components-v15/index.ts
  src/material/schematics/ng-update/test-cases/v15/legacy-components-v15.spec.ts
Labels: merge ready, merge safe, target: major

#25528 feat(material/schematics): add handling for all-component-themes
  src/material/schematics/ng-update/migrations/legacy-components-v15/index.ts
  src/material/schematics/ng-update/test-cases/v15/legacy-components-v15.spec.ts
Labels: merge ready, merge safe, target: major

#25525 fix(material/table): cleanup legacy usage
  src/dev-app/table-scroll-container/BUILD.bazel
  src/dev-app/table-scroll-container/table-scroll-container-demo.scss
  src/dev-app/table-scroll-container/table-scroll-container-demo.ts
  src/material/legacy-table/testing/BUILD.bazel
  src/material/legacy-table/testing/table-harness.spec.ts
  src/material/table/testing/BUILD.bazel
  src/material/table/testing/shared.spec.ts
  src/material/table/testing/table-harness.spec.ts
Labels: merge ready, merge safe, target: major

#25529 build: update ng-dev version
  package.json
  yarn.lock
Labels: merge ready, merge safe, target: minor

#25531 docs: release notes for the v14.2.0 release
  CHANGELOG.md
Labels: comp: docs

#25535 build: remove exceptional minor logic
  .ng-dev/pull-request.mts
  scripts/docs-deploy/deploy-ci-push.mts
Labels: merge ready, merge safe, target: patch

#25536 build: update to TypeScript 4.8 final
  integration/harness-e2e-cli/package.json
  integration/harness-e2e-cli/yarn.lock
  integration/ng-add-standalone/package.json
  integration/ng-add-standalone/yarn.lock
  integration/ng-add/package.json
  integration/ng-add/yarn.lock
  integration/ng-update-v13/package.json
  integration/ng-update-v13/yarn.lock
  integration/yarn-pnp-compat/.yarn/releases/yarn-3.2.1.cjs
  integration/yarn-pnp-compat/.yarn/releases/yarn-3.2.3.cjs
  integration/yarn-pnp-compat/.yarnrc.yml
  integration/yarn-pnp-compat/package.json
  integration/yarn-pnp-compat/yarn.lock
  package.json
  scripts/caretaking/firebase-functions/package.json
  scripts/caretaking/firebase-functions/yarn.lock
  src/material/schematics/ng-update/migrations/hammer-gestures-v9/hammer-gestures-migration.ts
  tools/integration.bzl
  yarn.lock
Labels: P3, merge ready, merge safe, target: patch

#25526 fix(cdk/collections): ConnectableObservable incorrectly inferred as data source
  src/cdk/collections/data-source.ts
Labels: P3, merge ready, target: patch

#25457 fix(material/datepicker): calendar aria-descriptions start/end date
  src/material/datepicker/aria-accessible-name.spec.ts
  src/material/datepicker/aria-accessible-name.ts
  src/material/datepicker/calendar-body.html
  src/material/datepicker/calendar-body.scss
  src/material/datepicker/calendar-body.ts
  src/material/datepicker/calendar.html
  src/material/datepicker/calendar.ts
  src/material/datepicker/date-range-input-parts.ts
  src/material/datepicker/date-range-input.spec.ts
  src/material/datepicker/date-range-input.ts
  src/material/datepicker/date-range-picker.ts
  src/material/datepicker/datepicker-base.ts
  src/material/datepicker/datepicker-content.html
  src/material/datepicker/month-view.html
  src/material/datepicker/month-view.ts
  tools/public_api_guard/material/datepicker.md
Labels: a11y, merge ready, target: minor, area: material/datepicker

#25544 fix(material/button-toggle): incorrect event source in some cases
  src/material/button-toggle/button-toggle.ts
  tools/public_api_guard/material/button-toggle.md
Labels: P3, merge ready, target: patch

#25546 fix(multiple): resolve extended template diagnostic warnings
  src/bazel-tsconfig-build.json
  src/components-examples/material/form-field/form-field-custom-control/example-tel-input-example.html
  src/components-examples/material/form-field/form-field-hint/form-field-hint-example.html
  src/components-examples/material/list/list-single-selection/list-single-selection-example.html
  src/dev-app/example/example-list.ts
  src/dev-app/legacy-select/legacy-select-demo.html
  src/dev-app/legacy-select/legacy-select-demo.ts
  src/dev-app/select/select-demo.html
  src/dev-app/select/select-demo.ts
  src/material/legacy-select/select.html
  src/material/legacy-select/select.ts
  tools/public_api_guard/material/legacy-select.md
  tsconfig.json
Labels: P3, merge ready, target: major

#25547 docs(material/checkbox): switch docs and examples to MDC
  .github/CODEOWNERS
  src/components-examples/material/checkbox/BUILD.bazel
  src/components-examples/material/checkbox/checkbox-harness/checkbox-harness-example.spec.ts
  src/components-examples/material/checkbox/index.ts
  src/dev-app/BUILD.bazel
  src/dev-app/checkbox/BUILD.bazel
  src/dev-app/checkbox/checkbox-demo.html
  src/dev-app/checkbox/checkbox-demo.ts
  src/dev-app/dev-app/dev-app-layout.ts
  src/dev-app/legacy-checkbox/BUILD.bazel
  src/dev-app/legacy-checkbox/legacy-checkbox-demo.html
  src/dev-app/legacy-checkbox/legacy-checkbox-demo.scss
  src/dev-app/legacy-checkbox/legacy-checkbox-demo.ts
  src/dev-app/legacy-checkbox/legacy-nested-checklist.html
  src/dev-app/mdc-checkbox/BUILD.bazel
  src/dev-app/routes.ts
Labels: merge ready, merge safe, target: major, comp: docs

#25520 docs(material/list): switch examples and demo to MDC
  .github/CODEOWNERS
  src/components-examples/material/list/BUILD.bazel
  src/components-examples/material/list/index.ts
  src/components-examples/material/list/list-harness/list-harness-example.html
  src/components-examples/material/list/list-harness/list-harness-example.spec.ts
  src/components-examples/material/list/list-sections/list-sections-example.css
  src/components-examples/material/list/list-sections/list-sections-example.html
  src/components-examples/material/list/list-selection/list-selection-example.css
  src/components-examples/material/list/list-selection/list-selection-example.ts
  src/components-examples/material/list/list-single-selection/list-single-selection-example.css
  src/components-examples/material/list/list-single-selection/list-single-selection-example.ts
  src/dev-app/BUILD.bazel
  src/dev-app/dev-app/dev-app-layout.ts
  src/dev-app/legacy-list/BUILD.bazel
  src/dev-app/legacy-list/legacy-list-demo.html
  src/dev-app/legacy-list/legacy-list-demo.scss
  src/dev-app/legacy-list/legacy-list-demo.ts
  src/dev-app/list/BUILD.bazel
  src/dev-app/list/list-demo.html
  src/dev-app/list/list-demo.scss
  src/dev-app/list/list-demo.ts
  src/dev-app/mdc-list/BUILD.bazel
  src/dev-app/routes.ts
  src/material/list/list.md
Labels: merge ready, merge safe, target: major, comp: docs

#25542 test(cdk/testing): add includeAsyncTests flag
  src/cdk/testing/tests/cross-environment.spec.ts
Labels: merge ready, merge safe, target: patch

#25524 fix(material/dialog): allow customizing animation duration
  src/material/dialog/dialog-animations.ts
  src/material/dialog/dialog-config.ts
  src/material/dialog/dialog-container.ts
  src/material/dialog/dialog.scss
  src/material/dialog/dialog.ts
  src/material/dialog/public-api.ts
  src/material/legacy-dialog/dialog-config.ts
  src/material/legacy-dialog/dialog-container.ts
  src/material/legacy-dialog/dialog.ts
  src/material/legacy-dialog/public-api.ts
  tools/public_api_guard/material/dialog.md
  tools/public_api_guard/material/legacy-dialog.md
Labels: merge ready, target: major, flag: breaking change

#25552 feat(material/datepicker): expose datepicker symbols
  src/material/datepicker/public-api.ts
  tools/public_api_guard/material/datepicker.md
Labels: merge ready, target: minor

#25550 fix(material/schematics): update theme names for MDC migration schematic
  integration/mdc-migration/golden/src/styles.scss
  integration/mdc-migration/sample-project/src/styles.scss
  src/material/schematics/ng-generate/mdc-migration/rules/components/autocomplete/autocomplete-styles.spec.ts
  src/material/schematics/ng-generate/mdc-migration/rules/components/autocomplete/autocomplete-styles.ts
  src/material/schematics/ng-generate/mdc-migration/rules/components/button/button-styles.spec.ts
  src/material/schematics/ng-generate/mdc-migration/rules/components/button/button-styles.ts
  src/material/schematics/ng-generate/mdc-migration/rules/components/card/card-styles.spec.ts
  src/material/schematics/ng-generate/mdc-migration/rules/components/card/card-styles.ts
  src/material/schematics/ng-generate/mdc-migration/rules/components/checkbox/checkbox-styles.spec.ts
  src/material/schematics/ng-generate/mdc-migration/rules/components/checkbox/checkbox-styles.ts
  src/material/schematics/ng-generate/mdc-migration/rules/components/chips/chips-styles.spec.ts
  src/material/schematics/ng-generate/mdc-migration/rules/components/chips/chips-styles.ts
  src/material/schematics/ng-generate/mdc-migration/rules/components/dialog/dialog-styles.spec.ts
  src/material/schematics/ng-generate/mdc-migration/rules/components/dialog/dialog-styles.ts
  src/material/schematics/ng-generate/mdc-migration/rules/components/form-field/form-field-styles.spec.ts
  src/material/schematics/ng-generate/mdc-migration/rules/components/form-field/form-field-styles.ts
  src/material/schematics/ng-generate/mdc-migration/rules/components/input/input-styles.spec.ts
  src/material/schematics/ng-generate/mdc-migration/rules/components/input/input-styles.ts
  src/material/schematics/ng-generate/mdc-migration/rules/components/list/list-styles.spec.ts
  src/material/schematics/ng-generate/mdc-migration/rules/components/list/list-styles.ts
  src/material/schematics/ng-generate/mdc-migration/rules/components/menu/menu-styles.spec.ts
  src/material/schematics/ng-generate/mdc-migration/rules/components/menu/menu-styles.ts
  src/material/schematics/ng-generate/mdc-migration/rules/components/multiple-components-styles.spec.ts
  src/material/schematics/ng-generate/mdc-migration/rules/components/paginator/paginator-styles.spec.ts
  src/material/schematics/ng-generate/mdc-migration/rules/components/paginator/paginator-styles.ts
  src/material/schematics/ng-generate/mdc-migration/rules/components/progress-bar/progress-bar-styles.spec.ts
  src/material/schematics/ng-generate/mdc-migration/rules/components/progress-bar/progress-bar-styles.ts
  src/material/schematics/ng-generate/mdc-migration/rules/components/progress-spinner/progress-spinner-styles.ts
  src/material/schematics/ng-generate/mdc-migration/rules/components/progress-spinner/progress-spinner.spec.ts
  src/material/schematics/ng-generate/mdc-migration/rules/components/radio/radio-styles.spec.ts
  src/material/schematics/ng-generate/mdc-migration/rules/components/radio/radio-styles.ts
  src/material/schematics/ng-generate/mdc-migration/rules/components/select/select-styles.spec.ts
  src/material/schematics/ng-generate/mdc-migration/rules/components/select/select-styles.ts
  src/material/schematics/ng-generate/mdc-migration/rules/components/slider/slider-styles.spec.ts
  src/material/schematics/ng-generate/mdc-migration/rules/components/slider/slider-styles.ts
  src/material/schematics/ng-generate/mdc-migration/rules/components/snack-bar/snack-bar-styles.spec.ts
  src/material/schematics/ng-generate/mdc-migration/rules/components/tooltip/tooltip-styles.spec.ts
  src/material/schematics/ng-generate/mdc-migration/rules/components/tooltip/tooltip-styles.ts
  src/material/schematics/ng-generate/mdc-migration/rules/style-migrator.ts
  src/material/schematics/ng-generate/mdc-migration/rules/theming-styles.ts
Labels: merge ready, merge safe, target: major, area: ng-generate

#25551 feat(material/core): make mdc-based typography default
  src/material/_index.scss
  src/material/core/theming/tests/test-theming-api.scss
  src/material/core/typography/_all-typography.scss
  src/material/core/typography/_typography-deprecated.scss
  src/material/core/typography/_typography.scss
  src/material/legacy-core/typography/_all-typography.scss
Labels: merge ready, target: major

#25560 docs(material/dialog): update examples to use MDC-based dialog
  .github/CODEOWNERS
  src/components-examples/material/dialog/BUILD.bazel
  src/components-examples/material/dialog/dialog-animations/dialog-animations-example.ts
  src/components-examples/material/dialog/dialog-content/dialog-content-example.ts
  src/components-examples/material/dialog/dialog-data/dialog-data-example.ts
  src/components-examples/material/dialog/dialog-elements/dialog-elements-example.ts
  src/components-examples/material/dialog/dialog-from-menu/dialog-from-menu-example.ts
  src/components-examples/material/dialog/dialog-harness/dialog-harness-example.spec.ts
  src/components-examples/material/dialog/dialog-harness/dialog-harness-example.ts
  src/components-examples/material/dialog/dialog-overview/dialog-overview-example.ts
  src/components-examples/material/dialog/index.ts
  src/dev-app/BUILD.bazel
  src/dev-app/dev-app/dev-app-layout.ts
  src/dev-app/dialog/BUILD.bazel
  src/dev-app/dialog/dialog-demo.html
  src/dev-app/dialog/dialog-demo.scss
  src/dev-app/dialog/dialog-demo.ts
  src/dev-app/legacy-dialog/BUILD.bazel
  src/dev-app/legacy-dialog/legacy-dialog-demo.html
  src/dev-app/legacy-dialog/legacy-dialog-demo.scss
  src/dev-app/legacy-dialog/legacy-dialog-demo.ts
  src/dev-app/mdc-dialog/BUILD.bazel
  src/dev-app/mdc-dialog/mdc-dialog-demo.scss
  src/dev-app/routes.ts
Labels: merge ready, merge safe, target: major, comp: docs
