Repository angular/components, pull requests merged in 2022-02, with the labels that each got.

#24331 build: fix rules_sass error
  WORKSPACE
  package.json
  yarn.lock
Labels: P2, merge ready, merge safe, target: patch

#21457 fix(material/menu): adjust overlay size when amount of items changes
  src/cdk/overlay/position/flexible-connected-position-strategy.ts
  src/material-experimental/mdc-menu/menu.spec.ts
  src/material/menu/menu-trigger.ts
  src/material/menu/menu.spec.ts
  src/material/menu/menu.ts
  tools/public_api_guard/material/menu.md
Labels: cla: yes, P3, merge ready, target: patch

#24335 build: update checksum for io_bazel_rules_sass
  WORKSPACE
Labels: merge ready, merge safe, target: patch, area: build

#24308 fix(cdk-experimental/menu): keep context menus open when mouse is released
  src/cdk-experimental/menu/context-menu.spec.ts
  src/cdk-experimental/menu/context-menu.ts
Labels: merge ready, target: patch

#24326 feat(material/schematics): set up a system for migrating scss
  src/material/schematics/ng-generate/mdc-migration/BUILD.bazel
  src/material/schematics/ng-generate/mdc-migration/index.ts
  src/material/schematics/ng-generate/mdc-migration/rules/button-styles.spec.ts
  src/material/schematics/ng-generate/mdc-migration/rules/button-styles.ts
  src/material/schematics/ng-generate/mdc-migration/rules/index.ts
  src/material/schematics/ng-generate/mdc-migration/rules/style-migrator.ts
  src/material/schematics/ng-generate/mdc-migration/rules/theming-styles.spec.ts
  src/material/schematics/ng-generate/mdc-migration/rules/theming-styles.ts
Labels: target: feature branch

#24346 fix(material-experimental/mdc-tabs): CSS applied to wrong element when preserveContent is enabled
  src/material-experimental/mdc-tabs/tab-body.scss
Labels: P2, merge ready, target: minor

#23962 perf(cdk/overlay): add event listeners for overlay dispatchers outside of zone
  src/cdk/overlay/dispatchers/overlay-keyboard-dispatcher.spec.ts
  src/cdk/overlay/dispatchers/overlay-keyboard-dispatcher.ts
  src/cdk/overlay/dispatchers/overlay-outside-click-dispatcher.spec.ts
  src/cdk/overlay/dispatchers/overlay-outside-click-dispatcher.ts
  tools/public_api_guard/cdk/overlay.md
Labels: P3, merge ready, target: patch

#24353 Revert "perf(cdk/overlay): add event listeners for overlay dispatchers outside of zone"
  src/cdk/overlay/dispatchers/overlay-keyboard-dispatcher.spec.ts
  src/cdk/overlay/dispatchers/overlay-keyboard-dispatcher.ts
  src/cdk/overlay/dispatchers/overlay-outside-click-dispatcher.spec.ts
  src/cdk/overlay/dispatchers/overlay-outside-click-dispatcher.ts
  tools/public_api_guard/cdk/overlay.md
Labels: merge ready, target: patch

#24303 build: update dev-infra package and format json files with prettier
  .github/workflows/dev-infra.yml
  .github/workflows/lock-closed.yml
  .ng-dev/tsconfig.json
  .stylelintrc.json
  .vscode/extensions.json
  .vscode/settings.json
  firebase.json
  goldens/ts-circular-deps.json
  goldens/tsec-exemption.json
  integration/harness-e2e-cli/angular.json
  integration/harness-e2e-cli/e2e/jasmine.json
  integration/harness-e2e-cli/e2e/package.json
  integration/harness-e2e-cli/e2e/tsconfig.json
  integration/harness-e2e-cli/tsconfig.app.json
  integration/harness-e2e-cli/tsconfig.json
  integration/harness-e2e-cli/tsconfig.spec.json
  integration/ng-add/angular.json
  integration/ng-add/tsconfig.app.json
  integration/ng-add/tsconfig.json
  integration/ng-add/tsconfig.spec.json
  integration/ng-update-v13/angular.json
  integration/ng-update-v13/tsconfig.app.json
  integration/ng-update-v13/tsconfig.json
  integration/ng-update-v13/tsconfig.spec.json
  package.json
  scripts/caretaking/firebase-functions/tsconfig.json
  src/cdk/package.json
  src/cdk/schematics/ng-generate/drag-drop/schema.json
  src/cdk/schematics/ng-update/devkit-migration.ts
  src/cdk/schematics/tsconfig.json
  src/components-examples/package.json
  src/google-maps/tsconfig.json
  src/material-experimental/mdc-snack-bar/tsconfig-build.json
  src/material-experimental/mdc-table/tsconfig-build.json
  src/material/package.json
  src/material/schematics/ng-add/schema.json
  src/material/schematics/ng-generate/address-form/schema.json
  src/material/schematics/ng-generate/dashboard/schema.json
  src/material/schematics/ng-generate/navigation/schema.json
  src/material/schematics/ng-generate/table/schema.json
  src/material/schematics/ng-generate/tree/schema.json
  src/material/schematics/tsconfig.json
  src/tsconfig-legacy.json
  src/tsconfig-tsec.json
  tools/dgeni/tsconfig.json
  tools/markdown-to-html/tsconfig.json
  tsconfig.json
  tslint.json
  yarn.lock
Labels: merge ready, merge safe, target: patch

#24266 test: add an integration test to verify mdc-migration against a golden
  .bazelignore
  integration/mdc-migration/BUILD.bazel
  integration/mdc-migration/golden/.browserslistrc
  integration/mdc-migration/golden/.editorconfig
  integration/mdc-migration/golden/.gitignore
  integration/mdc-migration/golden/README.md
  integration/mdc-migration/golden/angular.json
  integration/mdc-migration/golden/karma.conf.js
  integration/mdc-migration/golden/src/app/app.component.html
  integration/mdc-migration/golden/src/app/app.component.scss
  integration/mdc-migration/golden/src/app/app.component.spec.ts
  integration/mdc-migration/golden/src/app/app.component.ts
  integration/mdc-migration/golden/src/app/app.module.ts
  integration/mdc-migration/golden/src/assets/.gitkeep
  integration/mdc-migration/golden/src/environments/environment.prod.ts
  integration/mdc-migration/golden/src/environments/environment.ts
  integration/mdc-migration/golden/src/favicon.ico
  integration/mdc-migration/golden/src/index.html
  integration/mdc-migration/golden/src/main.ts
  integration/mdc-migration/golden/src/polyfills.ts
  integration/mdc-migration/golden/src/styles.scss
  integration/mdc-migration/golden/src/test.ts
  integration/mdc-migration/golden/tsconfig.app.json
  integration/mdc-migration/golden/tsconfig.json
  integration/mdc-migration/golden/tsconfig.spec.json
  integration/mdc-migration/migration-test.bzl
  integration/mdc-migration/sample-project/.browserslistrc
  integration/mdc-migration/sample-project/.editorconfig
  integration/mdc-migration/sample-project/.gitignore
  integration/mdc-migration/sample-project/README.md
  integration/mdc-migration/sample-project/angular.json
  integration/mdc-migration/sample-project/karma.conf.js
  integration/mdc-migration/sample-project/package.json
  integration/mdc-migration/sample-project/src/app/app.component.html
  integration/mdc-migration/sample-project/src/app/app.component.scss
  integration/mdc-migration/sample-project/src/app/app.component.spec.ts
  integration/mdc-migration/sample-project/src/app/app.component.ts
  integration/mdc-migration/sample-project/src/app/app.module.ts
  integration/mdc-migration/sample-project/src/assets/.gitkeep
  integration/mdc-migration/sample-project/src/environments/environment.prod.ts
  integration/mdc-migration/sample-project/src/environments/environment.ts
  integration/mdc-migration/sample-project/src/favicon.ico
  integration/mdc-migration/sample-project/src/index.html
  integration/mdc-migration/sample-project/src/main.ts
  integration/mdc-migration/sample-project/src/polyfills.ts
  integration/mdc-migration/sample-project/src/styles.scss
  integration/mdc-migration/sample-project/src/test.ts
  integration/mdc-migration/sample-project/tsconfig.app.json
  integration/mdc-migration/sample-project/tsconfig.json
  integration/mdc-migration/sample-project/tsconfig.spec.json
  integration/mdc-migration/sample-project/yarn.lock
  integration/mdc-migration/verify-golden.ts
Labels: merge ready, merge safe, target: feature branch

#24106 fix(material/datepicker): remove abbr from day of week header
  src/material/datepicker/calendar.scss
  src/material/datepicker/month-view.html
Labels: cla: yes, a11y, merge ready, target: patch, area: material/datepicker, dev-app preview

#23692 fix(material/chips): Make `MatChipInputEvent.chipInput` required.
  src/material-experimental/mdc-chips/chip-input.ts
  src/material/chips/chip-input.ts
  tools/public_api_guard/material/chips.md
Labels: cla: yes, merge ready, merge safe, target: major, flag: breaking change

#24354 fix(material-experiental/mdc-list): update material-components-web to pick up multi-select list keyboard support
  package.json
  packages.bzl
  src/material-experimental/mdc-list/interactive-list-base.ts
  yarn.lock
Labels: merge ready, target: patch

#24355 feat(cdk/testing): add methods `getOptionalHarness` and `hasHarness`
  src/cdk/testing/component-harness.ts
  src/cdk/testing/harness-environment.ts
  src/cdk/testing/tests/cross-environment.spec.ts
  tools/public_api_guard/cdk/testing.md
Labels: feature, merge ready, target: minor

#24350 fix(material-experimental/mdc-checkbox): add missing classes for checked
  src/material-experimental/mdc-checkbox/checkbox.ts
Labels: merge ready, target: patch

#24372 ci: group all scorecard action dependencies
  renovate.json
Labels: merge ready, merge safe, target: patch

#24364 test: clean up IE/Edge test workarounds
  src/material-experimental/mdc-input/input.spec.ts
  src/material/button/testing/shared.spec.ts
  src/material/grid-list/BUILD.bazel
  src/material/grid-list/grid-list.spec.ts
  src/material/input/input.spec.ts
  src/material/select/BUILD.bazel
  src/material/select/select.spec.ts
  src/material/sidenav/BUILD.bazel
  src/material/sidenav/drawer.spec.ts
Labels: P3, merge ready, merge safe, target: patch

#24279 Listen for focus event on calendar cells
  src/material/datepicker/calendar-body.html
  src/material/datepicker/calendar-body.ts
  src/material/datepicker/month-view.html
  src/material/datepicker/month-view.spec.ts
  src/material/datepicker/month-view.ts
  src/material/datepicker/multi-year-view.html
  src/material/datepicker/multi-year-view.spec.ts
  src/material/datepicker/multi-year-view.ts
  src/material/datepicker/year-view.html
  src/material/datepicker/year-view.spec.ts
  src/material/datepicker/year-view.ts
  tools/public_api_guard/material/datepicker.md
Labels: a11y, merge ready, target: patch, area: material/datepicker, dev-app preview

#24153 fix(cdk/scrolling): fix scrolling in appendOnly mode
  src/cdk/scrolling/virtual-scroll-viewport.spec.ts
  src/cdk/scrolling/virtual-scroll-viewport.ts
Labels: P3, merge ready, target: patch

#24300 Datepicker focus trap
  src/material/datepicker/date-range-input.spec.ts
  src/material/datepicker/datepicker-base.ts
  src/material/datepicker/datepicker-content.html
  src/material/datepicker/datepicker.spec.ts
  tools/public_api_guard/material/datepicker.md
Labels: a11y, merge ready, target: patch, area: material/datepicker, dev-app preview

#24380 Revert "Listen for focus event on calendar cells"
  src/material/datepicker/calendar-body.html
  src/material/datepicker/calendar-body.ts
  src/material/datepicker/month-view.html
  src/material/datepicker/month-view.spec.ts
  src/material/datepicker/month-view.ts
  src/material/datepicker/multi-year-view.html
  src/material/datepicker/multi-year-view.spec.ts
  src/material/datepicker/multi-year-view.ts
  src/material/datepicker/year-view.html
  src/material/datepicker/year-view.spec.ts
  src/material/datepicker/year-view.ts
  tools/public_api_guard/material/datepicker.md
Labels: merge ready, target: patch, area: material/datepicker

#24396 fix(cdk-experimental/column-resize): Fix bug in hover logic introduce…
  src/cdk-experimental/column-resize/column-resize.ts
Labels: merge ready, G, target: patch

#24400 docs(material/tabs): Update tabs keyboard interaction section.
  src/material/tabs/tabs.md
Labels: docs, merge ready, merge safe, target: patch

#24393 docs(material/datepicker): fix custom class example
  src/components-examples/material/datepicker/datepicker-date-class/datepicker-date-class-example.css
Labels: P3, docs, merge ready, merge safe, target: patch

#24366 refactor(multiple): remove PlatformModule usages
  src/cdk/a11y/a11y-module.ts
  src/cdk/scrolling/scrolling-module.ts
  src/cdk/text-field/text-field-module.ts
  src/components-examples/cdk/platform/index.ts
  src/dev-app/platform/platform-demo-module.ts
  src/material/core/datetime/index.ts
  src/material/core/ripple/index.ts
  src/material/sidenav/sidenav-module.ts
  tools/public_api_guard/cdk/a11y.md
  tools/public_api_guard/cdk/scrolling.md
  tools/public_api_guard/cdk/text-field.md
  tools/public_api_guard/material/core.md
  tools/public_api_guard/material/sidenav.md
Labels: P3, merge ready, target: patch

#24356 feat(material/progress-spinner): add color to default options
  src/material-experimental/mdc-progress-spinner/progress-spinner.spec.ts
  src/material-experimental/mdc-progress-spinner/progress-spinner.ts
  src/material/progress-spinner/progress-spinner.spec.ts
  src/material/progress-spinner/progress-spinner.ts
  tools/public_api_guard/material/progress-spinner.md
Labels: merge ready, target: minor

#24328 fix(material/dialog): Use `align` as `@Input()` in `MatDialogActions`
  src/dev-app/dialog/dialog-demo.ts
  src/dev-app/mdc-dialog/mdc-dialog-demo.ts
  src/material-experimental/mdc-dialog/dialog-content-directives.ts
  src/material-experimental/mdc-dialog/dialog.scss
  src/material-experimental/mdc-dialog/dialog.spec.ts
  src/material/dialog/dialog-content-directives.ts
  src/material/dialog/dialog.scss
  src/material/dialog/dialog.spec.ts
  tools/public_api_guard/material/dialog.md
Labels: P3, merge ready, caretaker note, target: minor

#24385 fix(material/menu): position classes not updated when window is resized
  src/material-experimental/mdc-menu/menu.spec.ts
  src/material-experimental/mdc-menu/menu.ts
  src/material/menu/menu-trigger.ts
  src/material/menu/menu.spec.ts
  src/material/menu/menu.ts
  tools/public_api_guard/material/menu.md
Labels: P3, merge ready, G, target: patch

#24292 feat(material/chips): update chip-list describedby to match input
  src/material/chips/chip-list.ts
  tools/public_api_guard/material/chips.md
Labels: P3, merge ready, target: minor

#24384 fix(material/datepicker): update active date on focusing a cell
  src/material/datepicker/calendar-body.html
  src/material/datepicker/calendar-body.ts
  src/material/datepicker/month-view.html
  src/material/datepicker/month-view.spec.ts
  src/material/datepicker/month-view.ts
  src/material/datepicker/multi-year-view.html
  src/material/datepicker/multi-year-view.spec.ts
  src/material/datepicker/multi-year-view.ts
  src/material/datepicker/year-view.html
  src/material/datepicker/year-view.spec.ts
  src/material/datepicker/year-view.ts
  tools/public_api_guard/material/datepicker.md
Labels: a11y, merge ready, caretaker note, target: minor, area: material/datepicker

#24412 feat(material/schematics): add progress bar styles migrator and tests
  src/material/schematics/ng-generate/mdc-migration/rules/components/progress-bar/progress-bar-styles.spec.ts
  src/material/schematics/ng-generate/mdc-migration/rules/components/progress-bar/progress-bar-styles.ts
  src/material/schematics/ng-generate/mdc-migration/rules/index.ts
Labels: target: feature branch

#24410 build: fix compilation error with new version of stylelint
  package.json
  tools/stylelint/no-prefixes/index.ts
  yarn.lock
Labels: P3, merge ready, merge safe, target: patch

#24402 build: remove mdc-sidenav package
  .github/CODEOWNERS
  .ng-dev/commit-message.ts
  scripts/check-mdc-exports-config.ts
  src/dev-app/BUILD.bazel
  src/dev-app/dev-app/dev-app-layout.ts
  src/dev-app/mdc-sidenav/BUILD.bazel
  src/dev-app/mdc-sidenav/mdc-sidenav-demo-module.ts
  src/dev-app/mdc-sidenav/mdc-sidenav-demo.html
  src/dev-app/mdc-sidenav/mdc-sidenav-demo.scss
  src/dev-app/mdc-sidenav/mdc-sidenav-demo.ts
  src/dev-app/routes.ts
  src/material-experimental/config.bzl
  src/material-experimental/mdc-sidenav/BUILD.bazel
  src/material-experimental/mdc-sidenav/README.md
  src/material-experimental/mdc-sidenav/_sidenav-theme.import.scss
  src/material-experimental/mdc-sidenav/_sidenav-theme.scss
  src/material-experimental/mdc-sidenav/index.ts
  src/material-experimental/mdc-sidenav/module.ts
  src/material-experimental/mdc-sidenav/public-api.ts
  src/material-experimental/mdc-sidenav/sidenav.e2e.spec.ts
  src/material-experimental/mdc-sidenav/sidenav.scss
Labels: P3, merge ready, merge safe, target: patch

#24401 refactor(material/datepicker): unit test with not the first of the month
  src/material/datepicker/multi-year-view.spec.ts
Labels: merge ready, merge safe, target: patch, area: material/datepicker

#24411 feat(material/schematics): add slide toggle styles migrator and tests
  src/material/schematics/ng-generate/mdc-migration/rules/components/slide-toggle/slide-toggle-styles.spec.ts
  src/material/schematics/ng-generate/mdc-migration/rules/components/slide-toggle/slide-toggle-styles.ts
  src/material/schematics/ng-generate/mdc-migration/rules/index.ts
Labels: target: feature branch

#24413 feat(material/schematics): add radio styles migrator and tests
  src/material/schematics/ng-generate/mdc-migration/rules/components/radio/radio-styles.spec.ts
  src/material/schematics/ng-generate/mdc-migration/rules/components/radio/radio-styles.ts
  src/material/schematics/ng-generate/mdc-migration/rules/index.ts
Labels: target: feature branch

#24425 build: use less ambiguous peer dependency to Angular framework
  packages.bzl
  tools/release-checks/check-framework-peer-dependency.ts
Labels: merge ready, merge safe, target: minor

#24420 feat(material/schematics): add slider styles migrator and tests
  src/material/schematics/ng-generate/mdc-migration/rules/components/slider/slider-styles.spec.ts
  src/material/schematics/ng-generate/mdc-migration/rules/components/slider/slider-styles.ts
  src/material/schematics/ng-generate/mdc-migration/rules/index.ts
Labels: target: feature branch

#24419 feat(material/schematics): add progress spinner styles migrator and tests
  src/material/schematics/ng-generate/mdc-migration/rules/components/progress-spinner/progress-spinner-styles.ts
  src/material/schematics/ng-generate/mdc-migration/rules/components/progress-spinner/progress-spinner.spec.ts
  src/material/schematics/ng-generate/mdc-migration/rules/index.ts
  src/material/schematics/ng-generate/mdc-migration/rules/style-migrator.ts
Labels: target: feature branch

#24417 fix(material-experimental/mdc-list): use body-1 rather than subtitle-1 typography for list items
  src/material-experimental/mdc-list/_list-theme.scss
Labels: merge ready, target: patch

#24422 fix(material/form-field): use correct color for form fields in high contrast mode
  src/material-experimental/mdc-form-field/_form-field-high-contrast.scss
  src/material-experimental/mdc-select/select.scss
  src/material/form-field/form-field-fill.scss
  src/material/form-field/form-field-legacy.scss
  src/material/form-field/form-field-outline.scss
  src/material/form-field/form-field.scss
Labels: P3, a11y, merge ready, G, target: patch

#24309 perf(material-experimental/mdc-table): reduce bundle size
  src/material-experimental/mdc-table/_table-theme.scss
  src/material-experimental/mdc-table/table.scss
Labels: P2, merge ready, target: patch

#24404 fix(cdk/drag-drop): stop pointer events on placeholder
  src/cdk/drag-drop/directives/drag.spec.ts
  src/cdk/drag-drop/drag-ref.ts
Labels: P3, merge ready, target: patch

#22875 refactor(material/core): no longer define stateChanges in `mixinErrorState`
  src/material-experimental/mdc-chips/chip-grid.ts
  src/material/chips/chip-list.ts
  src/material/core/common-behaviors/error-state.ts
  src/material/datepicker/date-range-input-parts.ts
  src/material/input/input.ts
  src/material/select/select.ts
  tools/public_api_guard/material/core.md
Labels: cla: yes, merge ready, target: major, flag: breaking change

#24433 feat(material-experimental/mdc-list): add support for marking the act…
  src/dev-app/mdc-list/mdc-list-demo.html
  src/dev-app/mdc-list/mdc-list-demo.ts
  src/material-experimental/mdc-list/BUILD.bazel
  src/material-experimental/mdc-list/list.ts
Labels: merge ready, target: minor

#24415 refactor(multiple): disable CSS variable fallbacks in MDC components
  src/material-experimental/mdc-card/card.scss
  src/material-experimental/mdc-dialog/dialog.scss
  src/material-experimental/mdc-form-field/form-field.scss
  src/material-experimental/mdc-menu/menu.scss
  src/material-experimental/mdc-progress-bar/progress-bar.scss
  src/material-experimental/mdc-progress-spinner/progress-spinner.scss
  src/material-experimental/mdc-slider/slider.scss
  src/material-experimental/mdc-snack-bar/snack-bar-container.scss
Labels: P3, merge ready, target: patch

#24125 docs: add note about mat-app-background to theming guide
  guides/theming.md
Labels: cla: yes, P3, docs, merge ready, merge safe, target: patch

#23609 feat(material/sort): default arrow position in MatSortDefaultOptions
  src/material/sort/sort-header.html
  src/material/sort/sort-header.ts
  src/material/sort/sort.spec.ts
  src/material/sort/sort.ts
  tools/public_api_guard/material/sort.md
Labels: cla: yes, P3, merge ready, target: minor

#24448 fix(material-experimental/mdc-list): fix typo in action-list css class
  src/material-experimental/mdc-list/action-list.ts
Labels: merge ready, target: patch

#24339 refactor(material-experimental/mdc-form-field): align label setup with non-MDC version
  src/material-experimental/mdc-chips/chip-grid.spec.ts
  src/material-experimental/mdc-form-field/_form-field-density.scss
  src/material-experimental/mdc-form-field/_form-field-theme.scss
  src/material-experimental/mdc-form-field/_mdc-text-field-structure-overrides.scss
  src/material-experimental/mdc-form-field/directives/floating-label.ts
  src/material-experimental/mdc-form-field/form-field.html
  src/material-experimental/mdc-input/input.spec.ts
  src/material-experimental/mdc-select/select.scss
  src/material-experimental/mdc-select/select.spec.ts
Labels: P3, merge ready, G, target: patch

#19505 fix(material/radio): not checked on first click if partially visible
  src/material/radio/radio.html
  src/material/radio/radio.scss
Labels: P3, merge ready, target: patch

#14722 fix(material/button-toggle): unable to override elevation and high contrast styling applied incorrectly
  src/material/button-toggle/_button-toggle-theme.scss
  src/material/button-toggle/button-toggle.scss
Labels: merge ready, P4, target: patch

#24451 fix(material-experimental/mdc-dialog): align change detection with non-MDC version
  src/material-experimental/mdc-dialog/dialog-container.ts
Labels: P3, merge ready, G, target: patch

#24449 docs(material/chips): add chips avatar sample
  src/components-examples/material/chips/chips-avatar/chips-avatar-example.css
  src/components-examples/material/chips/chips-avatar/chips-avatar-example.html
  src/components-examples/material/chips/chips-avatar/chips-avatar-example.ts
  src/components-examples/material/chips/index.ts
Labels: merge ready, merge safe, target: patch, dev-app preview

#24454 refactor(material/schematics): replace usages of deprecated TypeScript APIs
  src/material/schematics/ng-update/migrations/hammer-gestures-v9/hammer-gestures-migration.ts
  src/material/schematics/ng-update/migrations/hammer-gestures-v9/import-manager.ts
  src/material/schematics/ng-update/migrations/package-imports-v8/secondary-entry-points-migration.ts
Labels: P3, merge ready, merge safe, target: major

#24455 ci: fix stamping for builds performed in CI
  .circleci/config.yml
  scripts/bazel/setup-remote-execution.sh
Labels: merge ready, merge safe, target: patch

#24459 fix(material/radio): clicks not propagating to wrapper elements
  src/material/radio/radio.scss
Labels: P3, merge ready, G, target: patch

#24458 build: install snapshot builds for angular-devkit and schematics
  scripts/circleci/setup-angular-snapshots.js
Labels: merge ready, merge safe, target: patch

#17092 fix(material/checkbox): clear static aria attributes from host nodes
  src/material-experimental/mdc-checkbox/checkbox.spec.ts
  src/material-experimental/mdc-checkbox/checkbox.ts
  src/material/checkbox/checkbox.spec.ts
  src/material/checkbox/checkbox.ts
Labels: P3, a11y, merge ready, target: patch

#21081 fix(material/autocomplete): closing immediately when input is focused programmatically
  src/material-experimental/mdc-autocomplete/autocomplete.spec.ts
  src/material/autocomplete/autocomplete-trigger.ts
  src/material/autocomplete/autocomplete.spec.ts
Labels: P3, merge ready, target: patch

#24466 build: fix formatting failure
  src/material-experimental/mdc-autocomplete/autocomplete.spec.ts
  src/material/autocomplete/autocomplete.spec.ts
Labels: P3, merge ready, merge safe, target: patch

#15281 fix(material/select): arrow highlighted state not updating in Safari
  src/material/select/select.scss
Labels: P3, merge ready, target: patch

#24440 feat(material/form-field): add color to default options (#24438)
  src/material-experimental/mdc-form-field/form-field.ts
  src/material-experimental/mdc-input/input.spec.ts
  src/material/form-field/form-field.ts
  src/material/input/input.spec.ts
  src/material/input/input.ts
  tools/public_api_guard/material/form-field.md
Labels: P3, merge ready, target: minor

#24462 feat(cdk/a11y): HighContrastModeDetector need not support `IE11`
  src/cdk/a11y/high-contrast-mode/high-contrast-mode-detector.ts
Labels: merge ready, target: minor

#14806 fix(cdk/drag-drop): incorrectly sorting element inside dialog with blocked scrolling
  src/cdk/drag-drop/directives/drag.spec.ts
  src/cdk/drag-drop/drag-ref.ts
  src/cdk/drag-drop/drop-list-ref.ts
  src/cdk/drag-drop/parent-position-tracker.ts
Labels: P2, merge ready, target: patch

#12488 fix(ripple): not fading out on touch devices
  src/material-experimental/mdc-list/list.spec.ts
  src/material-experimental/mdc-list/selection-list.spec.ts
  src/material-experimental/mdc-slider/slider.spec.ts
  src/material-experimental/mdc-tabs/tab-group.spec.ts
  src/material/core/ripple/ripple-ref.ts
  src/material/core/ripple/ripple-renderer.ts
  src/material/core/ripple/ripple.spec.ts
  src/material/list/list.spec.ts
  src/material/list/selection-list.spec.ts
  src/material/tabs/tab-group.spec.ts
  tools/public_api_guard/material/core.md
Labels: P3, merge ready, target: minor, dev-app preview

#24258 fix(material-experimental/mdc-select): target correct element with typography
  src/material-experimental/mdc-select/_select-theme.scss
Labels: P3, merge ready, G, target: patch

#15361 fix(material/autocomplete): use narrow value for aria-haspopup
  src/material-experimental/mdc-autocomplete/autocomplete-trigger.ts
  src/material-experimental/mdc-autocomplete/autocomplete.spec.ts
  src/material/autocomplete/autocomplete-trigger.ts
  src/material/autocomplete/autocomplete.spec.ts
Labels: P3, merge ready, target: patch

#17077 feat(cdk/drag-drop): expose native event objects in custom events
  src/cdk/drag-drop/directives/drag.spec.ts
  src/cdk/drag-drop/directives/drag.ts
  src/cdk/drag-drop/directives/drop-list.ts
  src/cdk/drag-drop/drag-events.ts
  src/cdk/drag-drop/drag-ref.ts
  src/cdk/drag-drop/drop-list-ref.ts
  tools/public_api_guard/cdk/drag-drop.md
Labels: P3, merge ready, target: major

#11987 fix(material/autocomplete): don't block default arrow keys when using modifiers
  src/material-experimental/mdc-autocomplete/autocomplete.spec.ts
  src/material/autocomplete/autocomplete-trigger.ts
  src/material/autocomplete/autocomplete.spec.ts
Labels: P3, a11y, merge ready, target: patch

#24468 ci: update remote browsers in saucelabs and browserstack
  src/cdk-experimental/menu/context-menu.spec.ts
  src/cdk-experimental/menu/menu-bar.spec.ts
  src/cdk-experimental/menu/menu.spec.ts
  src/cdk/table/table.spec.ts
  src/cdk/testing/testbed/unit-test-element.ts
  src/material-experimental/menubar/menubar.spec.ts
  src/material/checkbox/testing/BUILD.bazel
  src/material/checkbox/testing/shared.spec.ts
  src/material/radio/testing/BUILD.bazel
  src/material/radio/testing/shared.spec.ts
  src/material/slide-toggle/testing/BUILD.bazel
  src/material/slide-toggle/testing/shared.spec.ts
  test/browser-providers.js
  test/karma-browsers.json
Labels: merge ready, target: patch

#14514 fix(material/progress-spinner): unable to change mode on spinner directive
  src/material-experimental/mdc-progress-spinner/progress-spinner.spec.ts
  src/material/progress-spinner/progress-spinner-module.ts
  src/material/progress-spinner/progress-spinner.spec.ts
  src/material/progress-spinner/progress-spinner.ts
  src/material/progress-spinner/public-api.ts
  tools/public_api_guard/material/progress-spinner.md
Labels: P3, merge ready, target: patch

#24408 perf(cdk/overlay): add event listeners for overlay dispatchers outside of zone
  src/cdk/overlay/dispatchers/overlay-keyboard-dispatcher.spec.ts
  src/cdk/overlay/dispatchers/overlay-keyboard-dispatcher.ts
  src/cdk/overlay/dispatchers/overlay-outside-click-dispatcher.spec.ts
  src/cdk/overlay/dispatchers/overlay-outside-click-dispatcher.ts
  tools/public_api_guard/cdk/overlay.md
Labels: merge ready, target: patch

#23638 feat(material/icon): add default options
  src/material/icon/icon.spec.ts
  src/material/icon/icon.ts
  tools/public_api_guard/material/icon.md
Labels: merge ready, target: minor

#24156 docs(material/slider): adjust CSS of configurable slider example
  src/components-examples/material/slider/slider-configurable/slider-configurable-example.css
  src/components-examples/material/slider/slider-configurable/slider-configurable-example.html
Labels: docs, merge ready, merge safe, target: patch

#16020 fix(material/autocomplete): reopen panel on input click
  src/material-experimental/mdc-autocomplete/autocomplete-trigger.ts
  src/material-experimental/mdc-autocomplete/autocomplete.spec.ts
  src/material/autocomplete/autocomplete-trigger.ts
  src/material/autocomplete/autocomplete.spec.ts
  tools/public_api_guard/material/autocomplete.md
Labels: merge ready, P4, target: patch

#20699 feat(material/autocomplete): add the ability to auto-select the active option while navigating
  src/material-experimental/mdc-autocomplete/autocomplete.spec.ts
  src/material/autocomplete/autocomplete-trigger.ts
  src/material/autocomplete/autocomplete.spec.ts
  src/material/autocomplete/autocomplete.ts
  tools/public_api_guard/material/autocomplete.md
Labels: cla: yes, P3, merge ready, target: minor

#24482 fix(material/core): ripples persisting when container is removed from DOM while fading-in
  .github/CODEOWNERS
  src/e2e-app/BUILD.bazel
  src/e2e-app/e2e-app/e2e-app-layout.ts
  src/e2e-app/main-module.ts
  src/e2e-app/routes.ts
  src/e2e-app/select/select-e2e-module.ts
  src/e2e-app/select/select-e2e.ts
  src/material/core/ripple/ripple-renderer.ts
  src/material/core/ripple/ripple.spec.ts
  src/material/select/BUILD.bazel
  src/material/select/select.e2e.spec.ts
Labels: merge ready, target: minor, dev-app preview

#24437 feat(material/menu): allow for menu to be conditionally removed from trigger
  src/material-experimental/mdc-menu/menu.spec.ts
  src/material/menu/menu-errors.ts
  src/material/menu/menu-trigger.ts
  src/material/menu/menu.spec.ts
  tools/public_api_guard/material/menu.md
Labels: P3, merge ready, target: minor

#24475 fix(material/tooltip): don't hide when pointer moves to tooltip
  src/material-experimental/mdc-tooltip/tooltip.scss
  src/material-experimental/mdc-tooltip/tooltip.spec.ts
  src/material-experimental/mdc-tooltip/tooltip.ts
  src/material/tooltip/tooltip.scss
  src/material/tooltip/tooltip.spec.ts
  src/material/tooltip/tooltip.ts
  tools/public_api_guard/material/tooltip.md
Labels: P2, a11y, merge ready, target: patch

#24481 ci: instruct renovate to not update/override merge ready PRs
  renovate.json
Labels: merge ready, merge safe, target: patch

#15219 fix(material/menu): use narrower value for aria-haspopup on trigger element
  src/material-experimental/mdc-menu/menu.spec.ts
  src/material/menu/menu-trigger.ts
  src/material/menu/menu.spec.ts
Labels: a11y, merge ready, target: minor

#11524 fix(material/datepicker): matDatepickerParse error not being added on first invalid value
  src/material/datepicker/datepicker-input-base.ts
  src/material/datepicker/datepicker.spec.ts
Labels: P3, merge ready, target: patch

#15275 feat(cdk/a11y): add input to control the duration of the aria live directive
  src/cdk/a11y/live-announcer/live-announcer.spec.ts
  src/cdk/a11y/live-announcer/live-announcer.ts
  tools/public_api_guard/cdk/a11y.md
Labels: merge ready, target: minor

#13705 feat(material/paginator): add input for configuring the underlying select
  src/material-experimental/mdc-paginator/paginator.html
  src/material-experimental/mdc-paginator/paginator.spec.ts
  src/material-experimental/mdc-paginator/public-api.ts
  src/material/paginator/paginator.html
  src/material/paginator/paginator.md
  src/material/paginator/paginator.spec.ts
  src/material/paginator/paginator.ts
  tools/public_api_guard/material/paginator.md
Labels: merge ready, P4, target: minor

#22559 feat(material/schematics): add option not to include animations module in ng-add
  src/material/schematics/ng-add/index.spec.ts
  src/material/schematics/ng-add/schema.json
  src/material/schematics/ng-add/schema.ts
  src/material/schematics/ng-add/setup-project.ts
Labels: cla: yes, P3, merge ready, merge safe, target: minor

#24485 build: fix formatting failure
  src/material/schematics/ng-add/schema.json
Labels: P3, merge ready, merge safe, target: minor

#12007 feat(cdk/overlay): add start and end positions to GlobalPositionStrategy
  src/cdk/overlay/position/global-position-strategy.spec.ts
  src/cdk/overlay/position/global-position-strategy.ts
  tools/public_api_guard/cdk/overlay.md
Labels: P3, merge ready, target: minor

#16169 fix(material/menu): account for menu padding different from the default
  src/material-experimental/mdc-menu/menu.scss
  src/material-experimental/mdc-menu/menu.spec.ts
  src/material/menu/menu-trigger.ts
  src/material/menu/menu.scss
  src/material/menu/menu.spec.ts
  tools/public_api_guard/material/menu.md
Labels: merge ready, P4, target: minor

#14039 fix(material/menu): focus lost if active item is removed
  src/material-experimental/mdc-menu/menu.spec.ts
  src/material/menu/menu-item.ts
  src/material/menu/menu.spec.ts
  src/material/menu/menu.ts
  tools/public_api_guard/material/menu.md
Labels: P3, a11y, merge ready, caretaker note, target: patch

#24487 build: update to Angular 14
  package.json
  yarn.lock
Labels: P3, merge ready, merge safe, target: major

#14507 fix(material/autocomplete): auto-highlighted first option not display correctly if the floating label is disabled
  src/material-experimental/mdc-autocomplete/autocomplete.spec.ts
  src/material/autocomplete/autocomplete-trigger.ts
  src/material/autocomplete/autocomplete.spec.ts
Labels: P3, merge ready, caretaker note, target: patch

#23083 fix(material/checkbox): inconsistent disabled color
  src/material/checkbox/_checkbox-theme.scss
Labels: cla: yes, P3, merge ready, caretaker note, target: patch

#10484 feat(material/icon): allow multiple classes in setDefaultFontSetClass
  src/material/icon/icon-registry.ts
  src/material/icon/icon.spec.ts
  src/material/icon/icon.ts
  src/material/icon/testing/fake-icon-registry.ts
  tools/public_api_guard/material/icon-testing.md
  tools/public_api_guard/material/icon.md
Labels: merge ready, P4, target: major

#24492 build: prepare framework peer dependency and migration collection for v14
  .ng-dev/tsconfig.json
  packages.bzl
  scripts/breaking-changes.ts
  scripts/check-mdc-exports.ts
  scripts/check-mdc-tests.ts
  scripts/check-package-externals.ts
  scripts/ownerslint.ts
  scripts/tsconfig.json
  src/cdk/schematics/migration.json
  src/cdk/schematics/ng-update/index.ts
  src/cdk/schematics/update-tool/target-version.ts
  src/material/schematics/migration.json
  src/material/schematics/ng-update/index.ts
  tools/dgeni/common/class-inheritance.ts
  tools/dgeni/processors/async-functions.ts
  tools/dgeni/processors/categorizer.ts
  tools/dgeni/processors/merge-inherited-properties.ts
  tools/dgeni/processors/resolve-inherited-docs.ts
  tools/example-module/parse-example-file.ts
  tools/example-module/parse-example-module-file.ts
  tools/release-checks/check-framework-peer-dependency.ts
  tools/release-checks/check-migration-collections.ts
  tools/release-checks/npm-package-output/check-package.ts
  tools/release-checks/npm-package-output/index.ts
  tools/release-checks/npm-package-output/output-validations.ts
  tools/tslint-rules/lightweightTokensRule.ts
  tools/tslint-rules/memberNamingRule.ts
  tools/tslint-rules/ngOnChangesPropertyAccessRule.ts
  tools/tslint-rules/noCoercionMembersRule.ts
  tools/tslint-rules/noCrossEntryPointRelativeImportsRule.ts
  tools/tslint-rules/requireLicenseBannerRule.ts
  tools/tslint-rules/validateDecoratorsRule.ts
Labels: merge ready, merge safe, target: major

#24493 build: cleanup leftover from `esModuleInterop` in `tools`
  scripts/generate-schematic-imports-map.ts
  tools/tslint-rules/noHostDecoratorInConcreteRule.ts
  tools/tslint-rules/noLifecycleInvocationRule.ts
  tools/tslint-rules/noNestedTernaryRule.ts
  tools/tslint-rules/noPrivateGettersRule.ts
  tools/tslint-rules/noUndecoratedBaseClassDiRule.ts
  tools/tslint-rules/noUndecoratedClassWithAngularFeaturesRule.ts
  tools/tslint-rules/noUnescapedHtmlTagRule.ts
  tools/tslint-rules/preferConstEnumRule.ts
  tools/tslint-rules/requireBreakingChangeVersionRule.ts
  tools/tslint-rules/settersAfterGettersRule.ts
  tools/tslint-rules/symbolNamingRule.ts
Labels: merge ready, merge safe, target: patch
