Repository angular/components, pull requests merged in 2022-05, with the labels that each got.

#24752 feat(material/autocomplete): add clear method to test harness
  src/material/autocomplete/testing/autocomplete-harness.ts
  src/material/autocomplete/testing/shared.spec.ts
  tools/public_api_guard/material/autocomplete-testing.md
Labels: P3, merge ready, target: minor

#24736 docs(material/button): fix button harness example test
  src/components-examples/material/button/button-harness/button-harness-example.spec.ts
Labels: P3, docs, merge ready, merge safe, target: patch

#24860 fix(material/menu): add constructor overloads for non-deprecated signatures
  src/material/menu/menu-content.ts
  src/material/menu/menu-item.ts
  src/material/menu/menu-trigger.ts
  src/material/menu/menu.ts
  tools/public_api_guard/material/menu.md
Labels: P3, merge ready, target: patch

#24857 refactor(material/dialog): switch to CDK dialog internally
  src/cdk/dialog/dialog-config.ts
  src/cdk/dialog/dialog-container.ts
  src/cdk/dialog/dialog.ts
  src/material-experimental/mdc-dialog/BUILD.bazel
  src/material-experimental/mdc-dialog/dialog-container.ts
  src/material-experimental/mdc-dialog/dialog-ref.ts
  src/material-experimental/mdc-dialog/dialog.spec.ts
  src/material-experimental/mdc-dialog/dialog.ts
  src/material-experimental/mdc-dialog/module.ts
  src/material-experimental/mdc-dialog/public-api.ts
  src/material/dialog/BUILD.bazel
  src/material/dialog/dialog-container.ts
  src/material/dialog/dialog-content-directives.ts
  src/material/dialog/dialog-module.ts
  src/material/dialog/dialog-ref.ts
  src/material/dialog/dialog.ts
  tools/public_api_guard/cdk/dialog.md
  tools/public_api_guard/material/dialog.md
Labels: P2, merge ready, target: major

#24865 build: resolve type bundling issues
  package.json
  src/components-examples/material/chips/chips-harness/chips-harness-example.ts
  src/google-maps/map-marker-clusterer/map-marker-clusterer.spec.ts
  src/google-maps/map-marker-clusterer/map-marker-clusterer.ts
  src/google-maps/map-marker-clusterer/marker-clusterer-types.ts
  src/google-maps/public-api.ts
  src/google-maps/testing/fake-google-map-utils.ts
  tools/public_api_guard/google-maps/google-maps.md
  yarn.lock
Labels: P3, merge ready, target: major

#24866 build: cleanup remaining references to `master` branch
  .circleci/config.yml
  .circleci/rebase-pr.js
  .github/angular-robot.yml
  .github/workflows/scorecard.yml
  CHANGELOG.md
  CHANGELOG_ARCHIVE.md
  CODING_STANDARDS.md
  CONTRIBUTING.md
  README.md
  guides/theming.md
  src/cdk/schematics/ng-update/update-schematic.md
  src/cdk/schematics/utils/build-component.ts
  src/cdk/schematics/utils/schematic-options.ts
  src/cdk/stepper/stepper.md
  src/cdk/testing/private/mock-ng-zone.ts
  src/cdk/testing/selenium-webdriver/selenium-web-driver-harness-environment.ts
  src/cdk/testing/test-element.ts
  src/cdk/testing/test-harnesses.md
  src/google-maps/package.json
  src/material-experimental/mdc-list/_list-theme.scss
  src/material/core/theming/_theming.scss
  src/youtube-player/package.json
  tools/defaults.bzl
Labels: merge ready, target: major

#24869 [13.3.x] build: cleanup remaining references to `master` branch
  .circleci/config.yml
  .circleci/rebase-pr.js
  .github/angular-robot.yml
  .github/workflows/scorecard.yml
  CHANGELOG.md
  CHANGELOG_ARCHIVE.md
  CODING_STANDARDS.md
  CONTRIBUTING.md
  README.md
  guides/theming.md
  src/cdk/schematics/ng-update/update-schematic.md
  src/cdk/schematics/utils/build-component.ts
  src/cdk/schematics/utils/schematic-options.ts
  src/cdk/stepper/stepper.md
  src/cdk/testing/private/mock-ng-zone.ts
  src/cdk/testing/selenium-webdriver/selenium-web-driver-harness-environment.ts
  src/cdk/testing/test-element.ts
  src/cdk/testing/test-harnesses.md
  src/google-maps/package.json
  src/material-experimental/mdc-list/_list-theme.scss
  src/material/core/theming/_theming.scss
  src/youtube-player/package.json
  tools/defaults.bzl
Labels: merge ready, merge safe, target: patch

#24867 fix(material-experimental/mdc-table): add inherit background to rows
  src/material-experimental/mdc-table/table.scss
Labels: merge ready, target: patch

#24757 fix(material-experimental/mdc-snack-bar): avoid multiple snack bars on the page if opened in quick succession
  src/material-experimental/mdc-snack-bar/snack-bar-container.ts
  src/material-experimental/mdc-snack-bar/snack-bar.spec.ts
  src/material/snack-bar/snack-bar-ref.ts
  src/material/snack-bar/snack-bar.spec.ts
Labels: P2, merge ready, caretaker note, G, target: patch

#24872 Bump version to "v13.3.6" with changelog.
  CHANGELOG.md
  package.json
Labels: merge ready, target: patch

#24873 docs: release notes for the v13.3.6 release
  CHANGELOG.md
Labels: merge ready, target: major

#24876 Bump version to "v14.0.0-next.13" with changelog.
  CHANGELOG.md
  package.json
Labels: merge ready, target: major

#24877 Update next branch to reflect new release-train "v14.1.0-next.0".
  CHANGELOG.md
  package.json
Labels: merge ready, target: major

#24880 build: update to TypeScript 4.7
  .circleci/config.yml
  .vscode/settings.json
  integration/yarn-pnp-compat/.yarn/releases/yarn-3.2.0.cjs
  integration/yarn-pnp-compat/.yarn/releases/yarn-4.0.0-rc.4.cjs
  integration/yarn-pnp-compat/.yarnrc.yml
  integration/yarn-pnp-compat/package.json
  integration/yarn-pnp-compat/yarn.lock
  package.json
  scripts/caretaking/firebase-functions/package.json
  scripts/caretaking/firebase-functions/yarn.lock
  src/material/table/table-data-source.ts
  yarn.lock
Labels: P2, merge ready, target: rc

#24878 test(multiple): enable easy extension of harnesses
  src/material-experimental/mdc-autocomplete/testing/autocomplete-harness.ts
  src/material-experimental/mdc-button/testing/button-harness.ts
  src/material-experimental/mdc-card/testing/card-harness.ts
  src/material-experimental/mdc-checkbox/testing/checkbox-harness.ts
  src/material-experimental/mdc-chips/testing/chip-avatar-harness.ts
  src/material-experimental/mdc-chips/testing/chip-grid-harness.ts
  src/material-experimental/mdc-chips/testing/chip-harness.ts
  src/material-experimental/mdc-chips/testing/chip-input-harness.ts
  src/material-experimental/mdc-chips/testing/chip-listbox-harness.ts
  src/material-experimental/mdc-chips/testing/chip-option-harness.ts
  src/material-experimental/mdc-chips/testing/chip-remove-harness.ts
  src/material-experimental/mdc-chips/testing/chip-row-harness.ts
  src/material-experimental/mdc-chips/testing/chip-set-harness.ts
  src/material-experimental/mdc-core/testing/optgroup-harness.ts
  src/material-experimental/mdc-core/testing/option-harness.ts
  src/material-experimental/mdc-dialog/testing/dialog-harness.ts
  src/material-experimental/mdc-form-field/testing/form-field-harness.ts
  src/material-experimental/mdc-list/testing/action-list-harness.ts
  src/material-experimental/mdc-list/testing/list-harness.ts
  src/material-experimental/mdc-list/testing/nav-list-harness.ts
  src/material-experimental/mdc-list/testing/selection-list-harness.ts
  src/material-experimental/mdc-menu/testing/menu-harness.ts
  src/material-experimental/mdc-paginator/testing/paginator-harness.ts
  src/material-experimental/mdc-progress-bar/testing/progress-bar-harness.ts
  src/material-experimental/mdc-progress-spinner/testing/progress-spinner-harness.ts
  src/material-experimental/mdc-radio/testing/radio-harness.ts
  src/material-experimental/mdc-select/testing/select-harness.ts
  src/material-experimental/mdc-slide-toggle/testing/slide-toggle-harness.ts
  src/material-experimental/mdc-slider/testing/slider-harness.ts
  src/material-experimental/mdc-slider/testing/slider-thumb-harness.ts
  src/material-experimental/mdc-snack-bar/testing/snack-bar-harness.ts
  src/material-experimental/mdc-table/testing/cell-harness.ts
  src/material-experimental/mdc-table/testing/row-harness.ts
  src/material-experimental/mdc-table/testing/table-harness.ts
  src/material-experimental/mdc-tabs/testing/tab-group-harness.ts
  src/material-experimental/mdc-tabs/testing/tab-harness.ts
  src/material-experimental/mdc-tabs/testing/tab-link-harness.ts
  src/material-experimental/mdc-tabs/testing/tab-nav-bar-harness.ts
  src/material-experimental/mdc-tabs/testing/tab-nav-panel-harness.ts
  src/material-experimental/mdc-tooltip/testing/tooltip-harness.ts
Labels: P3, merge ready, commit message fixup, target: rc

#24882 fix(material/expansion): inconsistent spacing for anchor buttons
  src/material/expansion/expansion-panel.scss
Labels: P3, merge ready, G, target: patch

#24871 build: add menu example to mdc-migration integration test
  integration/mdc-migration/golden/src/app/app.component.html
  integration/mdc-migration/golden/src/app/app.module.ts
  integration/mdc-migration/golden/src/app/components/menu/menu.component.html
  integration/mdc-migration/golden/src/app/components/menu/menu.component.scss
  integration/mdc-migration/golden/src/app/components/menu/menu.component.spec.ts
  integration/mdc-migration/golden/src/app/components/menu/menu.component.ts
  integration/mdc-migration/golden/src/styles.scss
  integration/mdc-migration/sample-project/src/app/app.component.html
  integration/mdc-migration/sample-project/src/app/app.module.ts
  integration/mdc-migration/sample-project/src/app/components/menu/menu.component.html
  integration/mdc-migration/sample-project/src/app/components/menu/menu.component.scss
  integration/mdc-migration/sample-project/src/app/components/menu/menu.component.spec.ts
  integration/mdc-migration/sample-project/src/app/components/menu/menu.component.ts
  integration/mdc-migration/sample-project/src/styles.scss
Labels: target: feature branch

#24813 fix(material/datepicker): add ability to have numeric zero value in input
  src/material/datepicker/datepicker-input-base.ts
  src/material/datepicker/testing/datepicker-input-harness-shared.spec.ts
Labels: merge ready, target: patch

#24733 fix(material/menu): focus the first item when opening menu on iOS VoiceOver
  src/material/menu/menu.ts
Labels: a11y, merge ready, caretaker note, target: patch, area: material/menu, dev-app preview

#24895 build: completely switch dev app to standalone components
  src/dev-app/BUILD.bazel
  src/dev-app/dev-app.ts
  src/dev-app/dev-app/dev-app-404.ts
  src/dev-app/dev-app/dev-app-home.ts
  src/dev-app/dev-app/dev-app-layout.ts
  src/dev-app/dev-app/dev-app-module.ts
  src/dev-app/example/example-list.ts
  src/dev-app/example/example-module.ts
  src/dev-app/example/example.ts
  src/dev-app/examples-page/examples-page.ts
  src/dev-app/main-module.ts
  src/dev-app/main.ts
Labels: P3, merge ready, merge safe, target: rc, dev-app preview

#24896 build: invalidate github action cache to prune old files
  .github/actions/yarn-install/action.yml
Labels: merge ready, merge safe, target: rc

#24897 fix(google-maps): error when minified through closure
  src/google-maps/map-marker-clusterer/map-marker-clusterer.ts
Labels: P2, merge ready, G, target: rc

#24898 refactor(google-maps): expose event manager
  src/google-maps/public-api.ts
  tools/public_api_guard/google-maps/google-maps.md
Labels: P3, merge ready, target: rc

#24905 fix(cdk/dialog): add container structural styles
  src/cdk/dialog/BUILD.bazel
  src/cdk/dialog/dialog-container.scss
  src/cdk/dialog/dialog-container.ts
  src/dev-app/cdk-dialog/dialog-demo.scss
  src/dev-app/cdk-dialog/dialog-demo.ts
Labels: P3, merge ready, target: rc

#24904 fix(material/core): noop animations not applying to selector lists
  src/material/core/style/_private.scss
  src/material/progress-spinner/progress-spinner.scss
Labels: P3, merge ready, G, target: rc

#24912 build: update to Angular 14 RC, TypeScript 4.7 RC and MDC 15
  integration/yarn-pnp-compat/package.json
  integration/yarn-pnp-compat/yarn.lock
  package.json
  packages.bzl
  scripts/caretaking/firebase-functions/package.json
  scripts/caretaking/firebase-functions/yarn.lock
  tools/public_api_guard/cdk/menu.md
  tools/public_api_guard/cdk/overlay.md
  yarn.lock
Labels: P3, merge ready, merge safe, target: rc

#24923 build: switch back to yarn v3
  integration/yarn-pnp-compat/.yarn/releases/yarn-3.2.1.cjs
  integration/yarn-pnp-compat/.yarn/releases/yarn-4.0.0-rc.4.cjs
  integration/yarn-pnp-compat/.yarnrc.yml
  integration/yarn-pnp-compat/package.json
Labels: P3, merge ready, merge safe, target: rc

#24925 refactor(material-experimental/mdc-radio): remove adapter usage
  src/material-experimental/mdc-radio/radio.html
  src/material-experimental/mdc-radio/radio.ts
Labels: P3, merge ready, target: rc

#24922 refactor(material-experimental/mdc-checkbox): remove usage of MDC adapter
  src/material-experimental/mdc-checkbox/checkbox.html
  src/material-experimental/mdc-checkbox/checkbox.spec.ts
  src/material-experimental/mdc-checkbox/checkbox.ts
  src/material/checkbox/checkbox.ts
  tools/public_api_guard/material/checkbox.md
Labels: P3, merge ready, target: rc, dev-app preview

#24885 fix(material/tabs): ensure the ink bar realigns when the tab header changes dimensions
  src/material/tabs/paginated-tab-header.ts
Labels: P3, merge ready, caretaker note, target: patch

#24935 refactor(material-experimental/mdc-slide-toggle): remove usage of MDC adapter
  src/material-experimental/mdc-slide-toggle/slide-toggle.html
  src/material-experimental/mdc-slide-toggle/slide-toggle.spec.ts
  src/material-experimental/mdc-slide-toggle/slide-toggle.ts
  src/material/slide-toggle/slide-toggle.html
  src/material/slide-toggle/slide-toggle.ts
  tools/public_api_guard/material/slide-toggle.md
Labels: P3, merge ready, target: rc

#24942 refactor(material-experimental/mdc-tabs): remove usage of MDC adapter
  src/material-experimental/mdc-tabs/BUILD.bazel
  src/material-experimental/mdc-tabs/ink-bar.ts
  src/material-experimental/mdc-tabs/tab-label-wrapper.ts
  src/material-experimental/mdc-tabs/tab-nav-bar/tab-nav-bar.ts
Labels: P3, merge ready, target: rc

#24945 refactor(material-experimental/mdc-form-field): remove MDC adapter usage
  src/material-experimental/mdc-form-field/BUILD.bazel
  src/material-experimental/mdc-form-field/directives/floating-label.ts
  src/material-experimental/mdc-form-field/directives/line-ripple.ts
  src/material-experimental/mdc-form-field/directives/notched-outline.html
  src/material-experimental/mdc-form-field/directives/notched-outline.ts
  src/material-experimental/mdc-form-field/form-field.ts
Labels: P3, merge ready, target: rc

#24927 fix(material-experimental/mdc-checkbox): Use cursor:pointer for label
  src/material-experimental/mdc-checkbox/checkbox.scss
Labels: merge ready, target: patch

#24934 feat(material-experimental/mdc-list): add support for activated state in harness
  src/material-experimental/mdc-list/testing/list-harness-filters.ts
  src/material-experimental/mdc-list/testing/list-harness.spec.ts
  src/material-experimental/mdc-list/testing/nav-list-harness.ts
Labels: merge ready, target: minor

#24952 build: update saucelabs and browserstack key
  .circleci/config.yml
Labels: merge ready, merge safe, target: patch, area: build

#24907 fix(material-experimental/mdc-checkbox): remove extra a11y tree node … …for the <label/>
  src/material-experimental/mdc-checkbox/checkbox.html
  src/material-experimental/mdc-checkbox/checkbox.spec.ts
  src/material-experimental/mdc-checkbox/checkbox.ts
  src/material/checkbox/checkbox.spec.ts
  src/material/checkbox/checkbox.ts
  tools/public_api_guard/material/checkbox.md
Labels: a11y, merge ready, target: patch, area: material/checkbox, dev-app preview

#24955 refactor(material-experimental/mdc-progress-spinner): remove MDC adapter usage
  src/material-experimental/mdc-progress-spinner/BUILD.bazel
  src/material-experimental/mdc-progress-spinner/progress-spinner.ts
Labels: P3, merge ready, target: rc

#24941 refactor(cdk/menu): use `inject` for all injection
  package.json
  src/cdk/menu/context-menu-trigger.ts
  src/cdk/menu/menu-aim.ts
  src/cdk/menu/menu-bar.ts
  src/cdk/menu/menu-base.ts
  src/cdk/menu/menu-item-radio.ts
  src/cdk/menu/menu-item.ts
  src/cdk/menu/menu-trigger-base.ts
  src/cdk/menu/menu-trigger.ts
  src/cdk/menu/menu.ts
  src/material-experimental/menubar/menubar.ts
  tools/public_api_guard/cdk/menu.md
  tslint.json
  yarn.lock
Labels: P2, refactoring, merge ready, target: rc, area: cdk/menu

#24951 refactor(material/bottom-sheet): use CDK dialog internally
  src/material/bottom-sheet/BUILD.bazel
  src/material/bottom-sheet/bottom-sheet-container.ts
  src/material/bottom-sheet/bottom-sheet-module.ts
  src/material/bottom-sheet/bottom-sheet-ref.ts
  src/material/bottom-sheet/bottom-sheet.ts
  tools/public_api_guard/material/bottom-sheet.md
Labels: P3, merge ready, target: rc

#24957 build: set up post approval changes commit action
  .github/workflows/dev-infra.yml
Labels: merge ready, merge safe, target: minor, area: build

#24967 build: update to TypeScript 4.7 final
  integration/ng-add-standalone/yarn.lock
  integration/yarn-pnp-compat/package.json
  integration/yarn-pnp-compat/yarn.lock
  package.json
  scripts/caretaking/firebase-functions/package.json
  scripts/caretaking/firebase-functions/yarn.lock
  yarn.lock
Labels: P2, merge ready, merge safe, target: rc

#24968 refactor(cdk/schematics): import AST utilities
  src/cdk/schematics/index.ts
  src/cdk/schematics/utils/ast.ts
  src/cdk/schematics/utils/ast/standalone.ts
  src/cdk/schematics/utils/build-component.ts
  src/cdk/schematics/utils/vendored-ast-utils/index.ts
  src/material/schematics/ng-update/test-cases/v9/misc/hammer-migration-v9.spec.ts
  tslint.json
Labels: P2, merge ready, merge safe, target: rc

#24971 [14.0.x] build: set up post approval changes commit action (#24957)
  .github/workflows/dev-infra.yml
Labels: target: rc

#24961 refactor(material-experimental/mdc-chips): remove usage of MDC adapter
  src/dev-app/mdc-chips/mdc-chips-demo.html
  src/material-experimental/mdc-chips/BUILD.bazel
  src/material-experimental/mdc-chips/chip-action.ts
  src/material-experimental/mdc-chips/chip-default-options.ts
  src/material-experimental/mdc-chips/chip-grid.spec.ts
  src/material-experimental/mdc-chips/chip-grid.ts
  src/material-experimental/mdc-chips/chip-icons.ts
  src/material-experimental/mdc-chips/chip-input.ts
  src/material-experimental/mdc-chips/chip-listbox.spec.ts
  src/material-experimental/mdc-chips/chip-listbox.ts
  src/material-experimental/mdc-chips/chip-option.html
  src/material-experimental/mdc-chips/chip-option.spec.ts
  src/material-experimental/mdc-chips/chip-option.ts
  src/material-experimental/mdc-chips/chip-remove.spec.ts
  src/material-experimental/mdc-chips/chip-row.spec.ts
  src/material-experimental/mdc-chips/chip-row.ts
  src/material-experimental/mdc-chips/chip-set.ts
  src/material-experimental/mdc-chips/chip.spec.ts
  src/material-experimental/mdc-chips/chip.ts
  src/material-experimental/mdc-chips/emit-event.ts
  src/material-experimental/mdc-chips/module.ts
  src/material-experimental/mdc-chips/public-api.ts
  src/material-experimental/mdc-chips/tokens.ts
Labels: P3, merge ready, target: rc

#24985 docs(cdk/menu): fix wrong example name
  src/cdk/menu/menu.md
Labels: P2, merge ready, merge safe, target: rc

#24989 Revert "refactor(material-experimental/mdc-chips): remove usage of MDC adapter (#24961)"
  src/dev-app/mdc-chips/mdc-chips-demo.html
  src/material-experimental/mdc-chips/BUILD.bazel
  src/material-experimental/mdc-chips/chip-action.ts
  src/material-experimental/mdc-chips/chip-default-options.ts
  src/material-experimental/mdc-chips/chip-grid.spec.ts
  src/material-experimental/mdc-chips/chip-grid.ts
  src/material-experimental/mdc-chips/chip-icons.ts
  src/material-experimental/mdc-chips/chip-input.ts
  src/material-experimental/mdc-chips/chip-listbox.spec.ts
  src/material-experimental/mdc-chips/chip-listbox.ts
  src/material-experimental/mdc-chips/chip-option.html
  src/material-experimental/mdc-chips/chip-option.spec.ts
  src/material-experimental/mdc-chips/chip-option.ts
  src/material-experimental/mdc-chips/chip-remove.spec.ts
  src/material-experimental/mdc-chips/chip-row.spec.ts
  src/material-experimental/mdc-chips/chip-row.ts
  src/material-experimental/mdc-chips/chip-set.ts
  src/material-experimental/mdc-chips/chip.spec.ts
  src/material-experimental/mdc-chips/chip.ts
  src/material-experimental/mdc-chips/emit-event.ts
  src/material-experimental/mdc-chips/module.ts
  src/material-experimental/mdc-chips/public-api.ts
  src/material-experimental/mdc-chips/tokens.ts
Labels: merge ready, target: rc

#24982 fix(cdk/a11y): ensure that aria describer ID is unique
  src/cdk/a11y/aria-describer/aria-describer.ts
Labels: P3, merge ready, target: rc

#24994 refactor(material-experimental/mdc-list): remove usage of MDC adapter
  src/material-experimental/mdc-list/BUILD.bazel
  src/material-experimental/mdc-list/interactive-list-base.ts
  src/material-experimental/mdc-list/list-base.ts
  src/material-experimental/mdc-list/list-option.ts
  src/material-experimental/mdc-list/selection-list.spec.ts
  src/material-experimental/mdc-list/selection-list.ts
Labels: P3, merge ready, target: rc

#24995 build: speed up TS compilations and type bundling by removing locale files
  tools/postinstall/apply-patches.js
Labels: merge ready, merge safe, target: rc

#24990 refactor(material-experimental/mdc-chips): remove usage of MDC adapter
  src/material-experimental/mdc-chips/BUILD.bazel
  src/material-experimental/mdc-chips/chip-action.ts
  src/material-experimental/mdc-chips/chip-default-options.ts
  src/material-experimental/mdc-chips/chip-grid.spec.ts
  src/material-experimental/mdc-chips/chip-grid.ts
  src/material-experimental/mdc-chips/chip-icons.ts
  src/material-experimental/mdc-chips/chip-input.ts
  src/material-experimental/mdc-chips/chip-listbox.spec.ts
  src/material-experimental/mdc-chips/chip-listbox.ts
  src/material-experimental/mdc-chips/chip-option.html
  src/material-experimental/mdc-chips/chip-option.spec.ts
  src/material-experimental/mdc-chips/chip-option.ts
  src/material-experimental/mdc-chips/chip-remove.spec.ts
  src/material-experimental/mdc-chips/chip-row.spec.ts
  src/material-experimental/mdc-chips/chip-row.ts
  src/material-experimental/mdc-chips/chip-set.ts
  src/material-experimental/mdc-chips/chip.spec.ts
  src/material-experimental/mdc-chips/chip.ts
  src/material-experimental/mdc-chips/emit-event.ts
  src/material-experimental/mdc-chips/module.ts
  src/material-experimental/mdc-chips/public-api.ts
  src/material-experimental/mdc-chips/tokens.ts
Labels: P3, merge ready, target: rc

#25001 Bump version to "v14.0.0-rc.2" with changelog.
  CHANGELOG.md
  package.json
Labels: merge ready, target: rc

#25002 docs: release notes for the v14.0.0-rc.2 release
  CHANGELOG.md
Labels: merge ready

#24999 fix(cdk/schematics): remove instanceof check since it was always false when checking if a directory exists
  src/cdk/schematics/ng-update/devkit-file-system.ts
Labels: merge ready, merge safe, target: rc

#24938 build: add chips example to mdc-migration integration test
  integration/mdc-migration/golden/src/app/app.component.html
  integration/mdc-migration/golden/src/app/app.module.ts
  integration/mdc-migration/golden/src/app/components/chips/chips.component.html
  integration/mdc-migration/golden/src/app/components/chips/chips.component.scss
  integration/mdc-migration/golden/src/app/components/chips/chips.component.spec.ts
  integration/mdc-migration/golden/src/app/components/chips/chips.component.ts
  integration/mdc-migration/golden/src/app/components/menu/menu.component.ts
  integration/mdc-migration/golden/src/styles.scss
  integration/mdc-migration/sample-project/src/app/app.component.html
  integration/mdc-migration/sample-project/src/app/app.module.ts
  integration/mdc-migration/sample-project/src/app/components/chips/chips.component.html
  integration/mdc-migration/sample-project/src/app/components/chips/chips.component.scss
  integration/mdc-migration/sample-project/src/app/components/chips/chips.component.spec.ts
  integration/mdc-migration/sample-project/src/app/components/chips/chips.component.ts
  integration/mdc-migration/sample-project/src/app/components/menu/menu.component.ts
  integration/mdc-migration/sample-project/src/styles.scss
Labels: merge ready, merge safe, target: feature branch
