Repository angular/components, pull requests merged in 2022-07, with the labels that each got.

#25206 build: fix dev-app preview action permissions
  .github/workflows/build-dev-app.yml
  .github/workflows/deploy-dev-app.yml
  .github/workflows/lock-closed.yml
Labels: merge ready, merge safe, target: patch

#25224 build: update stylelint and minor cleanup of custom rules
  package.json
  tools/stylelint/single-line-comment-only.ts
  tools/stylelint/theme-mixin-api.ts
  yarn.lock
Labels: merge ready, merge safe, P4, target: patch

#25178 fix(material-experimental/mdc-form-field): use a CSS var for the floating label scale
  src/material-experimental/mdc-form-field/_form-field-density.scss
  src/material-experimental/mdc-form-field/_form-field-theme.scss
  src/material-experimental/mdc-form-field/directives/notched-outline.ts
  src/material-experimental/mdc-form-field/form-field.html
  src/material-experimental/mdc-form-field/form-field.scss
  src/material-experimental/mdc-form-field/form-field.ts
Labels: merge ready, target: patch

#25230 docs: Fix two links in CONTRIBUTING.md
  CONTRIBUTING.md
Labels: merge ready, target: patch

#25192 fix(material-experimental/mdc-paginator): allow form-field density to go lower than -4
  src/material-experimental/mdc-paginator/BUILD.bazel
  src/material-experimental/mdc-paginator/_paginator-theme.scss
  src/material-experimental/mdc-paginator/paginator.scss
Labels: merge ready, target: major

#25240 build: add tooltip example to mdc-migration integration test
  integration/mdc-migration/golden/src/app/app.component.html
  integration/mdc-migration/golden/src/app/app.module.ts
  integration/mdc-migration/golden/src/app/components/tooltip/tooltip.component.html
  integration/mdc-migration/golden/src/app/components/tooltip/tooltip.component.scss
  integration/mdc-migration/golden/src/app/components/tooltip/tooltip.component.spec.ts
  integration/mdc-migration/golden/src/app/components/tooltip/tooltip.component.ts
  integration/mdc-migration/golden/src/styles.scss
  integration/mdc-migration/sample-project/src/app/app.component.html
  integration/mdc-migration/sample-project/src/app/app.module.ts
  integration/mdc-migration/sample-project/src/app/components/tooltip/tooltip.component.html
  integration/mdc-migration/sample-project/src/app/components/tooltip/tooltip.component.scss
  integration/mdc-migration/sample-project/src/app/components/tooltip/tooltip.component.spec.ts
  integration/mdc-migration/sample-project/src/app/components/tooltip/tooltip.component.ts
  integration/mdc-migration/sample-project/src/styles.scss
Labels: target: feature branch

#25241 build: attempt to de-flake harness integration test
  integration/harness-e2e-cli/BUILD.bazel
  integration/harness-e2e-cli/e2e/radio-harness.spec.ts
  integration/harness-e2e-cli/package.json
  integration/harness-e2e-cli/src/app/app.component.html
  integration/harness-e2e-cli/src/app/app.module.ts
  integration/harness-e2e-cli/yarn.lock
Labels: P3, merge ready, merge safe, target: patch

#25245 build: increase timeout for harness integration test
  integration/harness-e2e-cli/e2e/radio-harness.spec.ts
Labels: P3, merge ready, merge safe, target: patch

#25232 fix(cdk/a11y): correctly detect focus from input label
  src/cdk/a11y/focus-monitor/focus-monitor.spec.ts
  src/cdk/a11y/focus-monitor/focus-monitor.ts
Labels: P2, a11y, merge ready, target: patch

#25237 fix(material/select): add selected indication in high contrast mode
  src/material-experimental/mdc-core/option/option.scss
  src/material/core/option/option.scss
Labels: P3, a11y, merge ready, target: patch

#25201 fix(material-experimental/mdc-form-field): fix notch visual artifact
  src/material-experimental/mdc-form-field/_form-field-theme.scss
  src/material-experimental/mdc-form-field/directives/notched-outline.ts
  src/material-experimental/mdc-form-field/form-field.scss
  src/material/_index.scss
  src/material/core/style/_vendor-prefixes.scss
Labels: merge ready, target: patch, dev-app preview

#25252 build: use `pin` instead of `replace` range strategy
  renovate.json
Labels: merge ready, merge safe, target: patch

#25181 fix(multiple): fix disabled label style
  src/material-experimental/mdc-checkbox/_checkbox-theme.scss
  src/material-experimental/mdc-radio/_radio-theme.scss
  src/material-experimental/mdc-slide-toggle/_slide-toggle-theme.scss
Labels: merge ready, target: patch

#25221 fix(cdk/clipboard): page jumping on iOS
  src/cdk/clipboard/pending-copy.ts
Labels: P3, merge ready, target: patch

#25254 refactor(material/schematics): reuse standalone component utilities
  src/cdk/schematics/utils/ast/standalone.spec.ts
  src/cdk/schematics/utils/ast/standalone.ts
  src/cdk/schematics/utils/index.ts
  src/material/schematics/ng-add/setup-project.ts
Labels: P3, merge ready, merge safe, target: minor

#25258 build: enable renovate dashboard
  renovate.json
Labels: merge ready, merge safe, target: patch

#25259 test: fix incorrect usage in theming tests
  src/material/core/theming/tests/test-legacy-theming-bundle.scss
  src/material/core/theming/tests/theming-api.spec.ts
Labels: merge ready, merge safe, target: patch

#25218 fix(material/tabs): ink bar not shown in some cases
  src/material/tabs/ink-bar.ts
Labels: P3, merge ready, target: patch

#25200 fix(material-experimental/mdc-button): always treat icon-button content as an icon
  src/material-experimental/mdc-button/button-base.ts
  src/material-experimental/mdc-button/button.html
  src/material-experimental/mdc-button/icon-button.html
  src/material-experimental/mdc-button/icon-button.ts
Labels: merge ready, target: patch

#25248 refactor(material-experimental/mdc-progress-spinner): switch to new theming API
  package.json
  packages.bzl
  src/material-experimental/mdc-progress-spinner/_progress-spinner-theme.scss
  src/material-experimental/mdc-progress-spinner/progress-spinner.scss
  yarn.lock
Labels: P2, merge ready, target: minor

#25265 feat(material/core): delete deprecated legacy theming API tests
  src/material/core/theming/tests/theming-api.spec.ts
Labels: merge ready, merge safe, target: major

#25266 ci: fix incorrect style imports
  src/material-experimental/mdc-core/option/option.scss
  src/material-experimental/mdc-form-field/form-field.scss
Labels: merge ready, merge safe, target: patch

#25271 build: improve logging for docs deployment targets
  scripts/docs-deploy/snapshot-deploy.mts
Labels: merge ready, merge safe, target: patch

#25264 fix(material-experimental/mdc-form-field): ensure clip-path does not truncate label early
  src/material-experimental/mdc-form-field/form-field.scss
Labels: merge ready, target: patch

#25005 fix(cdk-experimental/listbox): clean up some TODOs
  src/cdk-experimental/listbox/BUILD.bazel
  src/cdk-experimental/listbox/listbox.spec.ts
  src/cdk-experimental/listbox/listbox.ts
  src/cdk/collections/selection-model.ts
  src/dev-app/cdk-experimental-listbox/cdk-listbox-demo.html
  src/dev-app/cdk-experimental-listbox/cdk-listbox-demo.ts
  tools/public_api_guard/cdk/collections.md
Labels: merge ready, target: minor, dev-app preview

#25290 build: fix lint issues introduced by #25285
  integration/mdc-migration/golden/angular.json
  integration/mdc-migration/golden/tsconfig.app.json
  integration/mdc-migration/golden/tsconfig.json
  integration/mdc-migration/golden/tsconfig.spec.json
  integration/mdc-migration/sample-project/angular.json
  integration/mdc-migration/sample-project/package.json
  integration/mdc-migration/sample-project/tsconfig.app.json
  integration/mdc-migration/sample-project/tsconfig.json
  integration/mdc-migration/sample-project/tsconfig.spec.json
Labels: merge ready, merge safe, target: major

#25229 docs: Fix link to theming-guide in guides/elevation.md
  guides/elevation.md
Labels: P3, docs, merge ready, merge safe, target: patch, area: theming

#25273 refactor(material-experimental/mdc-snack-bar): switch to new theming API
  src/material-experimental/mdc-snack-bar/_snack-bar-theme.scss
  src/material-experimental/mdc-snack-bar/snack-bar-container.scss
Labels: P2, merge ready, target: minor

#25302 refactor(material/snack-bar): fix out-of-sync code
  src/material-experimental/mdc-snack-bar/_snack-bar-theme.scss
Labels: P2, merge ready, merge safe, target: minor

#25301 fix(material/slider): add cancelable checks to touchmove and touchend events
  src/material/slider/slider.ts
Labels: merge ready, P4, target: patch

#25292 fix(material/card): don't add extra padding around mat-card-title-group
  src/dev-app/mdc-card/mdc-card-demo.html
  src/material/card/card.scss
Labels: merge ready, target: major, dev-app preview

#25297 fix(material/checkbox): incorrect animation state when going from pre-checked to indeterminate
  scripts/check-mdc-tests-config.ts
  src/material/checkbox/checkbox.spec.ts
  src/material/checkbox/checkbox.ts
Labels: P3, merge ready, target: patch

#25308 fix(material/tabs): disable tab label color transition when animations are disabled
  src/material-experimental/mdc-tabs/_tabs-common.scss
Labels: P3, merge ready, G, target: patch

#25212 fix(cdk/overlay): detach overlay when portal is destroyed from the outside
  src/cdk/overlay/overlay-ref.ts
  src/cdk/overlay/overlay.spec.ts
Labels: P3, merge ready, target: patch

#25140 refactor: explicitly set the display of the mat-paginator-icon to inline
  src/material-experimental/mdc-paginator/paginator.scss
  src/material/paginator/paginator.scss
Labels: P3, merge ready, target: patch

#25327 fix(material-experimental/mdc-chips): don't use button element if chip row isn't editable
  src/dev-app/mdc-chips/mdc-chips-demo.html
  src/material-experimental/mdc-chips/chip-row.html
  src/material-experimental/mdc-chips/chip-row.spec.ts
  src/material-experimental/mdc-chips/chip-row.ts
Labels: P2, merge ready, G, target: patch

#25337 build: avoid use of github team for dev-infra codeowner
  .github/CODEOWNERS
Labels: merge ready, merge safe, target: major

#25341 fix(cdk/drag-drop): expose pickup position in constrainPosition callback
  src/cdk/drag-drop/directives/drag.spec.ts
  src/cdk/drag-drop/directives/drag.ts
  src/cdk/drag-drop/drag-ref.ts
  tools/public_api_guard/cdk/drag-drop.md
Labels: P3, merge ready, target: patch

#25332 fix(cdk/dialog): use config injector if provided
  src/cdk/dialog/dialog.spec.ts
  src/cdk/dialog/dialog.ts
Labels: merge ready, target: patch

#25349 build: remove sass module migration script
  scripts/migrate-sass-modules.js
Labels: P3, merge ready, merge safe, target: major

#25354 build: update to latest MDC canary
  package.json
  packages.bzl
  yarn.lock
Labels: merge ready, merge safe, P4, target: major
