Repository angular/components, pull requests merged in 2022-11, with the labels that each got.

#25692 refactor(material/slider): mdc slider rewrite
  src/dev-app/slider/BUILD.bazel
  src/dev-app/slider/slider-demo.html
  src/dev-app/slider/slider-demo.scss
  src/dev-app/slider/slider-demo.ts
  src/e2e-app/slider/slider-e2e.ts
  src/material/slider/BUILD.bazel
  src/material/slider/global-change-and-input-listener.ts
  src/material/slider/module.ts
  src/material/slider/public-api.ts
  src/material/slider/slider-input.ts
  src/material/slider/slider-interface.ts
  src/material/slider/slider-thumb.html
  src/material/slider/slider-thumb.scss
  src/material/slider/slider-thumb.ts
  src/material/slider/slider.e2e.spec.ts
  src/material/slider/slider.html
  src/material/slider/slider.scss
  src/material/slider/slider.spec.ts
  src/material/slider/slider.ts
  src/material/slider/testing/slider-harness.spec.ts
  tools/public_api_guard/material/slider.md
Labels: action: merge, target: rc

#25904 refactor(cdk/menu): convert all directives to standalone
  src/cdk/menu/context-menu-trigger.ts
  src/cdk/menu/menu-aim.ts
  src/cdk/menu/menu-bar.ts
  src/cdk/menu/menu-group.ts
  src/cdk/menu/menu-item-checkbox.ts
  src/cdk/menu/menu-item-radio.ts
  src/cdk/menu/menu-item.ts
  src/cdk/menu/menu-module.ts
  src/cdk/menu/menu-trigger.ts
  src/cdk/menu/menu.ts
  tools/public_api_guard/cdk/menu.md
Labels: P3, action: merge, target: rc

#25898 fix(material/schematics): initialize slider template migrator
  src/material/schematics/ng-generate/mdc-migration/rules/components/slider/slider-template.spec.ts
  src/material/schematics/ng-generate/mdc-migration/rules/components/slider/slider-template.ts
  src/material/schematics/ng-generate/mdc-migration/rules/index.ts
Labels: action: merge, merge safe, target: rc

#25909 fix(cdk/overlay): provide Overlay in root
  src/cdk/overlay/overlay.ts
Labels: P3, action: merge, target: rc

#25913 Bump version to "v15.0.0-rc.1" with changelog.
  CHANGELOG.md
  package.json
Labels: action: merge, merge safe

#25914 docs: release notes for the v15.0.0-rc.1 release
  CHANGELOG.md
Labels: area: docs

#25911 refactor: replaces `aria-hidden` with `alt=""`
  src/components-examples/material/autocomplete/autocomplete-overview/autocomplete-overview-example.html
Labels: action: merge, merge safe, target: patch

#25814 refactor(material/core): clean up temporary mixins from MDC migration
  src/material/core/density/private/_all-density.scss
  src/material/core/theming/_all-theme.scss
  src/material/core/theming/tests/test-css-variables-theme.scss
  src/material/core/typography/_all-typography.scss
  src/material/legacy-core/density/private/_all-density.scss
  src/material/legacy-core/theming/_all-theme.scss
  src/material/legacy-core/typography/_all-typography.scss
Labels: P3, action: merge, target: rc

#25890 fix(material/chips): use checkmark graphic for single-selection
  src/material/chips/chip-option.ts
Labels: a11y, action: merge, area: material/chips, target: rc

#25922 fix(material/schematics): add handling for invert and vertical
  src/material/schematics/ng-generate/mdc-migration/rules/components/slider/slider-template.spec.ts
  src/material/schematics/ng-generate/mdc-migration/rules/components/slider/slider-template.ts
Labels: action: merge, merge safe, target: rc

#25928 fix(material/tabs): avoid reference error
  src/material/tabs/tab-nav-bar/tab-nav-bar.ts
Labels: P3, action: merge, target: rc

#25921 refactor(multiple): clean up map-get usages
  src/material/checkbox/_checkbox-private.scss
  src/material/radio/_radio-theme.scss
Labels: action: merge, P4, target: rc

#25393 Add HCM disabled styles for stepper and tabs
  src/material/stepper/step-header.scss
  src/material/tabs/tab-header.scss
Labels: a11y, action: merge, area: material/stepper, area: material/tabs, target: rc

#25930 fix(material/stepper): content not visibile on first navigation when nested in tabs
  src/material/stepper/stepper.scss
Labels: P3, action: merge, target: patch

#25937 fix(cdk/scrolling): error when querying for CdkVirtualScrollViewport as CdkScrollable
  src/cdk/scrolling/virtual-scroll-viewport.spec.ts
  src/cdk/scrolling/virtual-scroll-viewport.ts
Labels: P3, action: merge, target: patch

#25931 build: setup action for identifying changes needing to be tested in google
  .github/workflows/dev-infra.yml
  .github/workflows/google-internal-tests.yml
  .github/workflows/lock-closed.yml
  .ng-dev/caretaker.mts
  .ng-dev/google-sync-config.json
  .ng-dev/pull-request.mts
  package.json
  yarn.lock
Labels: action: merge, merge safe, target: minor

#25941 build: update sync config to use valid minimatch syntax
  .ng-dev/google-sync-config.json
Labels: action: merge, merge safe, target: rc

#25891 build: add Zach to chips codeowners
  .github/CODEOWNERS
Labels: action: merge, merge safe, area: build & ci, target: rc

#25940 docs: update typography guide to new terminology
  guides/typography.md
Labels: P2, action: merge, merge safe, target: rc, area: docs

#25818 feat(cdk/menu): Allow setting cdkMenuTriggerFor null
  src/cdk/menu/menu-item.ts
  src/cdk/menu/menu-trigger-base.ts
  src/cdk/menu/menu-trigger.spec.ts
  src/cdk/menu/menu-trigger.ts
  tools/public_api_guard/cdk/menu.md
Labels: action: merge, target: minor, detected: feature

#25942 fix(material/chips): show checkmark for selected non-selectable chips
  src/material/chips/chip-option.html
  src/material/chips/chip-option.ts
  tools/public_api_guard/material/chips.md
Labels: P3, action: merge, target: rc

#25945 docs: release notes for the v14.2.7 release
  CHANGELOG.md
Labels: action: merge, target: minor, area: docs

#25947 docs: release notes for the v15.0.0-rc.2 release
  CHANGELOG.md
Labels: area: docs

#25943 fix(material/schematics): add handling for several api changes
  src/material/schematics/ng-generate/mdc-migration/rules/components/slider/slider-template.spec.ts
  src/material/schematics/ng-generate/mdc-migration/rules/components/slider/slider-template.ts
Labels: action: merge, merge safe, target: rc

#25949 fix(material/schematics): handle input level in typography migration
  src/material/schematics/ng-generate/mdc-migration/rules/components/typography-config.spec.ts
  src/material/schematics/ng-generate/mdc-migration/rules/components/typography-hierarchy/constants.ts
  src/material/schematics/ng-generate/mdc-migration/rules/theming-styles.ts
Labels: P2, action: merge, merge safe, target: rc

#25950 fix(material/schematics): improve instructions for dealing with typography changes
  src/material/schematics/ng-update/migrations/legacy-components-v15/index.ts
  src/material/schematics/ng-update/test-cases/v15/legacy-components-v15.spec.ts
Labels: action: merge, merge safe, target: rc

#25956 fix(material/schematics): not migrating elements with template directives
  integration/mdc-migration/golden/src/app/components/chips/chips.component.html
  src/material/schematics/ng-generate/mdc-migration/rules/components/chips/chips-template.spec.ts
  src/material/schematics/ng-generate/mdc-migration/rules/tree-traversal.spec.ts
  src/material/schematics/ng-generate/mdc-migration/rules/tree-traversal.ts
Labels: P2, action: merge, merge safe, target: rc

#25924 fix(material/slider): fix track animation
  src/material/slider/slider.scss
  src/material/slider/slider.ts
Labels: action: merge, target: rc

#25952 fix(material/schematics): add slider input & change template updates
  src/material/schematics/ng-generate/mdc-migration/rules/components/slider/slider-template.spec.ts
  src/material/schematics/ng-generate/mdc-migration/rules/components/slider/slider-template.ts
  src/material/slider/public-api.ts
  src/material/slider/slider-interface.ts
  tools/public_api_guard/material/slider.md
Labels: action: merge, target: rc

#25953 docs(material/slider): hide slider internals
  src/material/slider/slider-input.ts
  src/material/slider/slider.ts
  tools/public_api_guard/material/slider.md
Labels: action: merge, target: rc, area: docs

#25964 fix(material/schematics): avoid mutating the AST when traversing
  src/material/schematics/ng-generate/mdc-migration/rules/tree-traversal.ts
Labels: P3, action: merge, merge safe, target: rc

#25796 docs: write slider section of mdc-migration guide
  guides/v15-mdc-migration.md
Labels: action: merge, merge safe, target: rc, area: docs

#25969 fix(material/schematics): add clarification about directory path format for MDC migration schematic
  src/material/schematics/ng-generate/mdc-migration/schema.json
Labels: action: merge, merge safe, area: ng-generate, target: rc

#25971 docs: add example for variants of mdc list
  src/components-examples/material/list/index.ts
  src/components-examples/material/list/list-variants/list-variants-example.css
  src/components-examples/material/list/list-variants/list-variants-example.html
  src/components-examples/material/list/list-variants/list-variants-example.ts
Labels: action: merge, target: rc, dev-app preview, area: docs

#25982 build: setup remote execution for dev-app preview action
  .github/workflows/build-dev-app.yml
Labels: action: merge, target: patch, dev-app preview, action: review

#25975 docs(material/theming): update guide for density
  guides/theming.md
Labels: docs, action: merge, merge safe, area: theming, target: rc, area: docs

#25970 build: update peer dependency to angular framework
  packages.bzl
Labels: action: merge, target: rc

#25994 docs: release notes for the v15.0.0 release
  CHANGELOG.md
Labels: area: docs

#25978 fix(cdk/a11y): live announcer not working with aria-modal element
  src/cdk/a11y/BUILD.bazel
  src/cdk/a11y/live-announcer/live-announcer.spec.ts
  src/cdk/a11y/live-announcer/live-announcer.ts
Labels: P2, a11y, action: merge, target: patch

#25548 feat(material/datepicker): Support drag and drop to adjust date ranges
  src/material/datepicker/calendar-body.spec.ts
  src/material/datepicker/calendar-body.ts
  src/material/datepicker/calendar.html
  src/material/datepicker/calendar.ts
  src/material/datepicker/date-range-selection-strategy.ts
  src/material/datepicker/datepicker-base.ts
  src/material/datepicker/datepicker-content.html
  src/material/datepicker/month-view.html
  src/material/datepicker/month-view.spec.ts
  src/material/datepicker/month-view.ts
  tools/public_api_guard/material/datepicker.md
Labels: action: merge, G, target: minor, detected: feature

#25967 fix(material/datepicker): date range inputs not aligning in some cases
  src/material/datepicker/date-range-input-parts.ts
  src/material/datepicker/date-range-input.html
  src/material/datepicker/date-range-input.scss
  src/material/datepicker/date-range-input.ts
  tools/public_api_guard/material/datepicker.md
Labels: P3, action: merge, target: patch

#25892 fix(material/chips): fix state layer interferring with text color
  src/material/chips/chip.scss
Labels: a11y, action: merge, target: patch, area: material/chips

#25985 fix(material/slider): update VI when toggling discrete
  src/material/slider/slider.ts
Labels: action: merge, target: patch

#25972 fix(material/slider): form control w/ initial disabled state
  src/material/slider/slider-input.ts
Labels: action: merge, target: patch

#25983 fix(material/autocomplete): apply theme of parent form field to panel
  src/dev-app/autocomplete/autocomplete-demo.html
  src/dev-app/autocomplete/autocomplete-demo.ts
  src/material/autocomplete/autocomplete-trigger.ts
  src/material/autocomplete/autocomplete.spec.ts
  src/material/autocomplete/autocomplete.ts
  tools/public_api_guard/material/autocomplete.md
Labels: action: merge, target: minor, area: material/autocomplete, area: theming

#26012 fix(material/list): pointer events disabled around content
  src/material/list/list.scss
Labels: P3, action: merge, target: patch

#26014 docs(cdk/listbox): fix a11y of example
  src/components-examples/cdk/listbox/cdk-listbox-disabled/cdk-listbox-disabled-example.html
Labels: action: merge, merge safe, target: patch, area: docs

#26016 fix(material/list): hover indication blocking interactions
  src/material/list/list.scss
Labels: P3, action: merge, target: patch

#25987 fix(material/form-field): don't block click on prefix/suffix when disabled
  src/material/form-field/form-field.scss
Labels: action: merge, target: patch

#25935 fix(material/chips): add support for aria-description
  src/components-examples/material/chips/chips-input/chips-input-example.html
  src/components-examples/material/chips/chips-input/chips-input-example.ts
  src/material/chips/chip-option.html
  src/material/chips/chip-option.spec.ts
  src/material/chips/chip-option.ts
  src/material/chips/chip-row.html
  src/material/chips/chip-row.spec.ts
  src/material/chips/chip-row.ts
  src/material/chips/chip.ts
  tools/public_api_guard/material/chips.md
Labels: a11y, action: merge, target: minor, area: material/chips

#26015 fix(material/core): reintroduce opacity in elevation mixin
  src/material/core/style/_elevation.scss
Labels: P3, action: merge, target: patch

#26027 fix(material/schematics): ensure mdc migration compatibility with nx
  src/material/schematics/ng-generate/mdc-migration/schema.json
Labels: action: merge, target: patch

#26031 build: update to Angular 15 final
  integration/harness-e2e-cli/yarn.lock
  integration/ng-add-standalone/package.json
  integration/ng-add-standalone/yarn.lock
  integration/ng-add/package.json
  integration/ng-add/yarn.lock
  integration/yarn-pnp-compat/package.json
  integration/yarn-pnp-compat/yarn.lock
  package.json
  yarn.lock
Labels: P3, action: merge, merge safe, target: patch

#26039 build: bump MDC version to resolve deprecation warning
  package.json
  packages.bzl
  yarn.lock
Labels: P3, action: merge, merge safe, target: patch

#25995 test(material/slider): improve slider demo
  src/dev-app/slider/BUILD.bazel
  src/dev-app/slider/slider-demo.html
  src/dev-app/slider/slider-demo.scss
  src/dev-app/slider/slider-demo.ts
Labels: action: merge, target: patch

#25933 fix(material/list): add radio toggles
  src/dev-app/list/list-demo.html
  src/dev-app/list/list-demo.ts
  src/material/legacy-list/selection-list.ts
  src/material/list/BUILD.bazel
  src/material/list/_list-option-theme.scss
  src/material/list/list-item-sections.ts
  src/material/list/list-option-types.ts
  src/material/list/list-option.html
  src/material/list/list-option.scss
  src/material/list/list-option.ts
  src/material/list/public-api.ts
  src/material/list/selection-list.spec.ts
  src/material/list/testing/list-harness.spec.ts
  src/material/list/testing/selection-list-harness.ts
  src/material/radio/BUILD.bazel
  src/material/radio/_radio-private.scss
  src/material/radio/_radio-theme.scss
  src/material/radio/radio.scss
  tools/public_api_guard/material/list-testing.md
  tools/public_api_guard/material/list.md
Labels: a11y, action: merge, target: minor, area: material/list

#26051 fix(cdk/menu): prevent default selection key actions
  src/cdk/menu/menu-item.spec.ts
  src/cdk/menu/menu-item.ts
  src/cdk/menu/menu-trigger.spec.ts
  src/cdk/menu/menu-trigger.ts
Labels: P3, action: merge, target: patch

#26060 fix(material/schematics): improve mdc-migration error logging
  src/material/schematics/ng-generate/mdc-migration/rules/template-migration.ts
Labels: action: merge, target: patch

#26065 docs: address incorrect density in migration guide
  guides/v15-mdc-migration.md
Labels: P2, docs, action: merge, merge safe, target: patch, area: docs

#26058 docs(material/theming): fix customizing-density link
  guides/theming.md
Labels: action: merge, merge safe, target: patch, area: docs

#26044 fix(material/slider): fix slider resize w/ transforms
  src/material/slider/slider.ts
Labels: action: merge, target: patch, area: material/slider

#26096 fix(material/core): ripples not being removed if container is hidden
  src/material/core/ripple/ripple-renderer.ts
Labels: action: merge, P4, target: patch

#26092 fix(material/list): allow mat-list-item outside list
  src/material/list/list-base.ts
  src/material/list/list.scss
  src/material/list/list.spec.ts
  src/material/list/list.ts
  tools/public_api_guard/material/list.md
Labels: action: merge, P4, target: patch

#26081 fix(material/schematics): add undefined check
  src/material/schematics/ng-generate/mdc-migration/rules/tree-traversal.ts
Labels: action: merge, target: patch

#26088 fix(material/form-field): not visually disabled if form control is disabled without emitting an event
  src/material/input/input.spec.ts
  src/material/input/input.ts
Labels: P3, action: merge, target: patch

#26089 fix(material/toolbar): inherit toolbar color in flat buttons
  src/dev-app/dev-app/dev-app-layout.scss
  src/material/toolbar/toolbar.scss
Labels: P3, action: merge, target: patch

#26073 fix(multiple): remove touch tap highlights
  src/material/button/_button-base.scss
  src/material/checkbox/checkbox.scss
  src/material/chips/chip.scss
  src/material/core/option/option.scss
  src/material/list/list.scss
  src/material/radio/radio.scss
  src/material/slide-toggle/slide-toggle.scss
  src/material/tabs/_tabs-common.scss
Labels: P3, action: merge, target: patch

#26106 build: resolve syntax error in list
  src/material/list/list.scss
Labels: P2, action: merge, merge safe, target: patch

#25211 docs(material/tree): add instructing to use flat tree for best perfor…
  src/material/tree/tree.md
Labels: docs, action: merge, merge safe, target: patch, area: material/tree

#26026 build: enable the assistant-to-the-branch-manager github action
  .github/workflows/assistant-to-the-branch-manager.yml
Labels: action: merge, target: patch, area: build & ci

#26086 build: update to latest version of parse5
  package.json
  src/cdk/package.json
  src/cdk/schematics/BUILD.bazel
  src/cdk/schematics/ng-update/html-parsing/elements.ts
  src/cdk/schematics/utils/html-manipulation.ts
  src/cdk/schematics/utils/parse5-element.ts
  yarn.lock
Labels: action: merge, merge safe, P4, target: patch

#19722 refactor(material/menu): explicitly set aria-expanded to true/false
  src/material/legacy-menu/menu.spec.ts
  src/material/menu/menu-trigger.ts
  src/material/menu/menu.spec.ts
Labels: action: merge, target: patch

#26112 fix(cdk/menu): not closing when inside shadow DOM
  src/cdk/menu/context-menu-trigger.ts
  src/cdk/menu/menu-trigger.ts
Labels: P3, action: merge, target: patch

#23315 fix(material/select): changed after checked error if option label changes
  src/material/core/option/option.ts
  src/material/legacy-select/select.spec.ts
  src/material/select/select.spec.ts
  src/material/select/select.ts
Labels: cla: yes, P2, action: merge, target: patch

#26111 fix(material/slide-toggle): focus indication not showing inside OnPush parent
  src/material/slide-toggle/slide-toggle.ts
Labels: P2, action: merge, G, target: patch

#26113 perf(material/chips): reduce amount of macro tasks
  src/material/chips/chip-grid.ts
  src/material/chips/chip-input.ts
  src/material/chips/chip-set.ts
  tools/public_api_guard/material/chips.md
Labels: P2, action: merge, target: patch

#26075 fix(material/form-field): change selector to allow density class on form field
  src/material/form-field/_form-field-density.scss
Labels: action: merge, P4, target: patch

#26117 build: switch to new preview deploy github action
  .github/workflows/build-dev-app.yml
  .github/workflows/deploy-dev-app.yml
  scripts/github/fetch-workflow-artifact.mjs
Labels: action: merge, target: patch, area: build & ci, dev-app preview

#26009 refactor(material/autocomplete): declare injected properties as nullable
  src/material/autocomplete/autocomplete-trigger.ts
  tools/public_api_guard/material/autocomplete.md
Labels: refactoring, action: merge, target: minor, area: material/autocomplete

#25951 fix(material/datepicker): fix date picker shortcuts
  src/cdk/keycodes/modifiers.ts
  src/material/datepicker/datepicker-base.ts
  src/material/datepicker/datepicker-input-base.ts
  src/material/datepicker/datepicker.spec.ts
  tools/public_api_guard/cdk/keycodes.md
Labels: action: merge, target: minor

#26122 docs(build): fix typo in code comment
  packages.bzl
Labels: action: merge, merge safe, target: patch, area: build & ci

#26123 build: update version of preview deploy actions
  .github/workflows/build-dev-app.yml
  .github/workflows/deploy-dev-app.yml
Labels: action: merge, target: patch, area: build & ci

#26125 build: update preview deploy github actions
  .github/workflows/build-dev-app.yml
  .github/workflows/deploy-dev-app.yml
Labels: action: merge, target: patch, area: build & ci

#26110 fix(material/form-field): allow clicking on floating label
  src/material/form-field/_mdc-text-field-structure-overrides.scss
  src/material/input/input.e2e.spec.ts
Labels: action: merge, target: patch

#26054 fix(material/core): icons not aligned inside mat-option
  src/material/core/option/option.html
  src/material/core/option/option.scss
  src/material/core/option/option.ts
  src/material/legacy-core/option/option.html
  tools/public_api_guard/material/core.md
Labels: P3, action: merge, target: patch

#26129 docs(material/form-field): remove font size example
  src/components-examples/material/form-field/form-field-theming/form-field-theming-example.html
  src/components-examples/material/form-field/form-field-theming/form-field-theming-example.ts
  src/material/form-field/form-field.md
Labels: action: merge, merge safe, P4, target: patch, area: docs

#26140 fix(cdk/menu): remove unused var
  src/cdk/menu/menu-trigger.spec.ts
Labels: action: merge

#26142 docs: release notes for the v15.0.1 release
  CHANGELOG.md
Labels: area: docs

#26127 fix(material/form-field): allow ng-container to be used as prefix/suffix
  src/material/form-field/directives/prefix.ts
  src/material/form-field/directives/suffix.ts
  src/material/input/input.spec.ts
  tools/public_api_guard/material/form-field.md
Labels: action: merge, target: patch
