Repository angular/components, pull requests merged in 2022-06, with the labels that each got.

#24954 docs(material/icon): update the FontAwesome example link
  src/material/icon/icon.md
Labels: docs, merge ready, merge safe, commit message fixup, target: rc

#24991 fix(material/datepicker): page scrolling for fast keyboard repeat
  src/material/datepicker/datepicker-base.ts
  src/material/datepicker/datepicker.spec.ts
Labels: P3, merge ready, target: patch

#25004 refactor(material-experimental/mdc-progress-bar): remove usage of MDC adapter
  src/material-experimental/mdc-progress-bar/BUILD.bazel
  src/material-experimental/mdc-progress-bar/progress-bar.html
  src/material-experimental/mdc-progress-bar/progress-bar.spec.ts
  src/material-experimental/mdc-progress-bar/progress-bar.ts
Labels: P3, merge ready, target: rc

#25012 Bump version to "v13.3.9" with changelog.
  CHANGELOG.md
  package.json
Labels: merge ready

#25015 Bump version to "v14.0.0" with changelog.
  CHANGELOG.md
  package.json
Labels: merge ready, merge safe, target: rc

#25016 docs: release notes for the v14.0.0 release
  CHANGELOG.md
Labels: merge ready, merge safe, target: minor

#25028 build: set up schematics for version 15
  src/cdk/schematics/migration.json
  src/cdk/schematics/ng-update/index.ts
  src/cdk/schematics/update-tool/target-version.ts
  src/material/schematics/migration.json
  src/material/schematics/ng-update/index.ts
Labels: P3, merge ready, merge safe, target: patch

#24986 fix(material-experimental/mdc-radio): fix ripple color
  src/material-experimental/mdc-radio/radio.scss
Labels: merge ready, target: patch

#25024 fix(material/datepicker): add i18n strings
  src/material/datepicker/datepicker-intl.ts
  tools/public_api_guard/material/datepicker.md
Labels: a11y, i18n, merge ready, target: minor, area: material/datepicker

#24394 feat(cdk/scrolling): make scroller element configurable for virtual scrolling
  src/cdk/scrolling/public-api.ts
  src/cdk/scrolling/scrollable.ts
  src/cdk/scrolling/scrolling-module.ts
  src/cdk/scrolling/virtual-scroll-viewport.scss
  src/cdk/scrolling/virtual-scroll-viewport.spec.ts
  src/cdk/scrolling/virtual-scroll-viewport.ts
  src/cdk/scrolling/virtual-scrollable-element.ts
  src/cdk/scrolling/virtual-scrollable-window.ts
  src/cdk/scrolling/virtual-scrollable.ts
  src/dev-app/virtual-scroll/virtual-scroll-demo.html
  tools/public_api_guard/cdk/scrolling.md
Labels: merge ready, target: minor

#25043 docs(cdk/scrolling): Docs for new virtual scroll features added in #24394
  src/cdk/scrolling/scrolling.md
  src/components-examples/cdk/scrolling/cdk-virtual-scroll-parent-scrolling/cdk-virtual-scroll-parent-scrolling-example.css
  src/components-examples/cdk/scrolling/cdk-virtual-scroll-parent-scrolling/cdk-virtual-scroll-parent-scrolling-example.html
  src/components-examples/cdk/scrolling/cdk-virtual-scroll-parent-scrolling/cdk-virtual-scroll-parent-scrolling-example.ts
  src/components-examples/cdk/scrolling/cdk-virtual-scroll-window-scrolling/cdk-virtual-scroll-window-scrolling-example.css
  src/components-examples/cdk/scrolling/cdk-virtual-scroll-window-scrolling/cdk-virtual-scroll-window-scrolling-example.html
  src/components-examples/cdk/scrolling/cdk-virtual-scroll-window-scrolling/cdk-virtual-scroll-window-scrolling-example.ts
  src/components-examples/cdk/scrolling/index.ts
  src/dev-app/virtual-scroll/BUILD.bazel
  src/dev-app/virtual-scroll/virtual-scroll-demo.html
  src/dev-app/virtual-scroll/virtual-scroll-demo.scss
  src/dev-app/virtual-scroll/virtual-scroll-demo.ts
Labels: P1, merge ready, merge safe, target: minor

#25020 build: add paginator example to mdc-migration integration test
  integration/mdc-migration/golden/src/app/app.component.html
  integration/mdc-migration/golden/src/app/app.component.spec.ts
  integration/mdc-migration/golden/src/app/app.module.ts
  integration/mdc-migration/golden/src/app/components/chips/chips.component.spec.ts
  integration/mdc-migration/golden/src/app/components/menu/menu.component.spec.ts
  integration/mdc-migration/golden/src/app/components/paginator/paginator.component.html
  integration/mdc-migration/golden/src/app/components/paginator/paginator.component.scss
  integration/mdc-migration/golden/src/app/components/paginator/paginator.component.spec.ts
  integration/mdc-migration/golden/src/app/components/paginator/paginator.component.ts
  integration/mdc-migration/sample-project/src/app/app.component.html
  integration/mdc-migration/sample-project/src/app/app.component.spec.ts
  integration/mdc-migration/sample-project/src/app/app.module.ts
  integration/mdc-migration/sample-project/src/app/components/chips/chips.component.spec.ts
  integration/mdc-migration/sample-project/src/app/components/menu/menu.component.spec.ts
  integration/mdc-migration/sample-project/src/app/components/paginator/paginator.component.html
  integration/mdc-migration/sample-project/src/app/components/paginator/paginator.component.scss
  integration/mdc-migration/sample-project/src/app/components/paginator/paginator.component.spec.ts
  integration/mdc-migration/sample-project/src/app/components/paginator/paginator.component.ts
Labels: target: feature branch

#25027 build: update to Angular 14 stable
  integration/yarn-pnp-compat/package.json
  integration/yarn-pnp-compat/yarn.lock
  package.json
  src/material/schematics/ng-add/setup-project.ts
  yarn.lock
Labels: P3, merge ready, merge safe, target: patch

#25044 refactor(cdk/drag-drop): move sorting and positioning logic into a separate class
  src/cdk/drag-drop/directives/drag.spec.ts
  src/cdk/drag-drop/dom/client-rect.ts
  src/cdk/drag-drop/dom/clone-node.ts
  src/cdk/drag-drop/dom/parent-position-tracker.ts
  src/cdk/drag-drop/dom/styling.ts
  src/cdk/drag-drop/dom/transition-duration.ts
  src/cdk/drag-drop/drag-ref.ts
  src/cdk/drag-drop/drop-list-ref.ts
  src/cdk/drag-drop/sorting/drop-list-sort-strategy.ts
  src/cdk/drag-drop/sorting/single-axis-sort-strategy.ts
Labels: P3, merge ready, target: patch

#25049 fix(material-experimental/mdc-list): don't access class before initialization
  src/material-experimental/mdc-list/list-base.ts
Labels: P3, merge ready, target: patch

#25057 build: add select example to mdc-migration integration test
  integration/mdc-migration/golden/src/app/app.component.html
  integration/mdc-migration/golden/src/app/app.module.ts
  integration/mdc-migration/golden/src/app/components/select/select.component.html
  integration/mdc-migration/golden/src/app/components/select/select.component.scss
  integration/mdc-migration/golden/src/app/components/select/select.component.spec.ts
  integration/mdc-migration/golden/src/app/components/select/select.component.ts
  integration/mdc-migration/golden/src/styles.scss
  integration/mdc-migration/sample-project/src/app/app.component.html
  integration/mdc-migration/sample-project/src/app/app.module.ts
  integration/mdc-migration/sample-project/src/app/components/select/select.component.html
  integration/mdc-migration/sample-project/src/app/components/select/select.component.scss
  integration/mdc-migration/sample-project/src/app/components/select/select.component.spec.ts
  integration/mdc-migration/sample-project/src/app/components/select/select.component.ts
  integration/mdc-migration/sample-project/src/styles.scss
Labels: target: feature branch

#25058 build: add autocomplete example to mdc-migration integration test
  integration/mdc-migration/golden/src/app/app.component.html
  integration/mdc-migration/golden/src/app/app.module.ts
  integration/mdc-migration/golden/src/app/components/autocomplete/autocomplete.component.html
  integration/mdc-migration/golden/src/app/components/autocomplete/autocomplete.component.scss
  integration/mdc-migration/golden/src/app/components/autocomplete/autocomplete.component.spec.ts
  integration/mdc-migration/golden/src/app/components/autocomplete/autocomplete.component.ts
  integration/mdc-migration/golden/src/styles.scss
  integration/mdc-migration/sample-project/src/app/app.component.html
  integration/mdc-migration/sample-project/src/app/app.module.ts
  integration/mdc-migration/sample-project/src/app/components/autocomplete/autocomplete.component.html
  integration/mdc-migration/sample-project/src/app/components/autocomplete/autocomplete.component.scss
  integration/mdc-migration/sample-project/src/app/components/autocomplete/autocomplete.component.spec.ts
  integration/mdc-migration/sample-project/src/app/components/autocomplete/autocomplete.component.ts
  integration/mdc-migration/sample-project/src/styles.scss
Labels: target: feature branch

#25039 feat(material/core): use strong focus indicators in high contrast mode
  src/dev-app/theme.scss
  src/material-experimental/mdc-button/_button-base.scss
  src/material-experimental/mdc-button/button-high-contrast.scss
  src/material-experimental/mdc-button/button.scss
  src/material-experimental/mdc-button/fab.scss
  src/material-experimental/mdc-checkbox/checkbox.scss
  src/material-experimental/mdc-chips/chip.scss
  src/material-experimental/mdc-core/option/option.scss
  src/material-experimental/mdc-helpers/_focus-indicators-theme.scss
  src/material-experimental/mdc-helpers/_focus-indicators.scss
  src/material-experimental/mdc-list/list.scss
  src/material-experimental/mdc-menu/menu.scss
  src/material-experimental/mdc-radio/radio.scss
  src/material-experimental/mdc-slide-toggle/slide-toggle.scss
  src/material-experimental/mdc-slider/slider.scss
  src/material-experimental/mdc-tabs/_tabs-common.scss
  src/material-experimental/mdc-tabs/tab-header.scss
  src/material-experimental/mdc-tabs/tab-nav-bar/tab-link.scss
  src/material/_index.scss
  src/material/button-toggle/button-toggle.scss
  src/material/button/button.scss
  src/material/checkbox/checkbox.scss
  src/material/chips/chips.scss
  src/material/core/_core.scss
  src/material/core/focus-indicators/_focus-indicators-theme.scss
  src/material/core/focus-indicators/_focus-indicators.scss
  src/material/core/option/option.scss
  src/material/core/style/_focus-indicators.scss
  src/material/datepicker/calendar-body.scss
  src/material/datepicker/calendar.scss
  src/material/expansion/expansion-panel-header.scss
  src/material/list/list.scss
  src/material/menu/menu.scss
  src/material/radio/radio.scss
  src/material/slide-toggle/slide-toggle.scss
  src/material/sort/BUILD.bazel
  src/material/sort/sort-header.scss
  src/material/stepper/step-header.scss
  src/material/tabs/_tabs-common.scss
  src/material/tabs/tab-header.scss
  src/material/tabs/tab-nav-bar/tab-nav-bar.scss
Labels: P2, merge ready, target: minor, preserve commits

#25052 build: update to the latest version of dev-infra with ESM
  .circleci/config.yml
  .ng-dev/caretaker.mts
  .ng-dev/commit-message.mts
  .ng-dev/config.mts
  .ng-dev/config.ts
  .ng-dev/format.mts
  .ng-dev/github.mts
  .ng-dev/pull-request.mts
  .ng-dev/release.mts
  .ng-dev/tsconfig.json
  package.json
  scripts/build-and-check-release-output.mts
  scripts/build-and-check-release-output.ts
  scripts/build-docs-content-main.mts
  scripts/build-docs-content.mts
  scripts/build-packages-dist-main.mts
  scripts/build-packages-dist.mts
  scripts/circleci/notify-slack-job-failure.mjs
  scripts/docs-deploy/clone-docs-repo.mts
  scripts/docs-deploy/deploy-ci-push.mts
  scripts/docs-deploy/deploy-to-site.mts
  scripts/docs-deploy/docs-deps-install.mts
  scripts/docs-deploy/github-versioning.mts
  scripts/docs-deploy/install-built-packages.mts
  scripts/docs-deploy/monitoring/ci-test.mts
  scripts/docs-deploy/monitoring/ci-test.ts
  scripts/docs-deploy/monitoring/index.mts
  scripts/docs-deploy/snapshot-deploy.mts
  scripts/docs-deploy/update-versions-file.mts
  scripts/docs-deploy/utils.mts
  scripts/tsconfig.json
  src/material/core/theming/tests/BUILD.bazel
  tools/dgeni/processors/entry-point-grouper.ts
  tools/example-module/generate-example-module.ts
  tools/example-module/parse-example-file.ts
  tools/release-checks/check-framework-peer-dependency.mts
  tools/release-checks/check-migration-collections.mts
  tools/release-checks/index.js
  tools/release-checks/npm-package-output/check-package.mts
  tools/release-checks/npm-package-output/index.mts
  tools/release-checks/npm-package-output/output-validations.mts
  tools/sass/compiler-main.ts
  tools/sass/local-sass-importer.ts
  tools/stylelint/cross-package-import-validation.ts
  tools/stylelint/no-ampersand-beyond-selector-start.ts
  tools/stylelint/no-concrete-rules.ts
  tools/stylelint/no-import.ts
  tools/stylelint/no-prefixes/index.ts
  tools/stylelint/no-top-level-ampersand-in-mixin.ts
  tools/stylelint/no-unused-import.ts
  tools/stylelint/selector-no-deep.ts
  tools/stylelint/single-line-comment-only.ts
  tools/stylelint/theme-mixin-api.ts
  tools/tsconfig.json
  yarn.lock
Labels: merge ready, merge safe, target: patch

#25062 ci: fix slack notification script failing due to missing `ts-node`
  .circleci/config.yml
  package.json
  scripts/circleci/notify-slack-job-failure.mts
Labels: merge ready, merge safe, target: patch

#25061 fix(cdk/drag-drop): constrainPosition not working as expected
  src/cdk/drag-drop/directives/drag.spec.ts
  src/cdk/drag-drop/directives/drag.ts
  src/cdk/drag-drop/drag-ref.ts
  tools/public_api_guard/cdk/drag-drop.md
Labels: P2, merge ready, target: patch

#25065 docs(material/select): Disabling the select or individual options
  src/material/select/select.md
Labels: docs, merge ready, merge safe, target: patch, commit message fixup

#24929 fix(material-experimental/mdc-button): don't apply styles to icons within the text label
  src/material-experimental/mdc-button/button.scss
  src/material-experimental/mdc-button/fab.scss
Labels: merge ready, target: patch

#24987 feat(material-experimental/mdc-button): support custom leading/trailing icons
  src/material-experimental/mdc-button/button.html
Labels: merge ready, target: minor

#25072 fix(material-experimental/mdc-chips): checkmark blending into background in high contrast mode
  src/material-experimental/mdc-chips/chip.scss
Labels: P3, merge ready, target: patch

#24964 fix(material-experimental/mdc-form-field): replace !important with CSS var
  src/material-experimental/mdc-form-field/_form-field-density.scss
  src/material-experimental/mdc-form-field/form-field.ts
Labels: merge ready, target: patch

#25075 fix(docs/typography-guide): Update dialog.md typo
  src/cdk/dialog/dialog.md
Labels: docs, merge ready, merge safe, target: patch, commit message fixup

#25067 fix(docs/typography-guide): Defining a level
  guides/typography.md
Labels: merge ready, merge safe, target: minor, commit message fixup

#25078 refactor(material/core): clean up focus indicators
  src/dev-app/theme.scss
  src/material-experimental/mdc-button/button.scss
  src/material-experimental/mdc-button/fab.scss
  src/material-experimental/mdc-checkbox/BUILD.bazel
  src/material-experimental/mdc-chips/chip.scss
  src/material-experimental/mdc-core/BUILD.bazel
  src/material-experimental/mdc-helpers/_focus-indicators-theme.scss
  src/material-experimental/mdc-helpers/_focus-indicators.scss
  src/material-experimental/mdc-list/list.scss
  src/material-experimental/mdc-radio/BUILD.bazel
  src/material-experimental/mdc-radio/radio.scss
  src/material-experimental/mdc-slide-toggle/BUILD.bazel
  src/material-experimental/mdc-tabs/BUILD.bazel
  src/material/_index.scss
  src/material/button/button.scss
  src/material/chips/chips.scss
  src/material/core/_core.scss
  src/material/core/focus-indicators/_focus-indicators-theme.scss
  src/material/core/focus-indicators/_focus-indicators.scss
  src/material/core/focus-indicators/_private.scss
  src/material/core/theming/tests/test-theming-bundle.scss
  src/material/datepicker/calendar.scss
  src/material/expansion/BUILD.bazel
  src/material/sort/sort-header.scss
Labels: P3, merge ready, target: minor

#25076 build: add button example to mdc-migration integration test
  integration/mdc-migration/golden/src/app/app.component.html
  integration/mdc-migration/golden/src/app/app.module.ts
  integration/mdc-migration/golden/src/app/components/button/button.component.html
  integration/mdc-migration/golden/src/app/components/button/button.component.scss
  integration/mdc-migration/golden/src/app/components/button/button.component.spec.ts
  integration/mdc-migration/golden/src/app/components/button/button.component.ts
  integration/mdc-migration/golden/src/styles.scss
  integration/mdc-migration/sample-project/src/app/app.component.html
  integration/mdc-migration/sample-project/src/app/app.module.ts
  integration/mdc-migration/sample-project/src/app/components/button/button.component.html
  integration/mdc-migration/sample-project/src/app/components/button/button.component.scss
  integration/mdc-migration/sample-project/src/app/components/button/button.component.spec.ts
  integration/mdc-migration/sample-project/src/app/components/button/button.component.ts
  integration/mdc-migration/sample-project/src/styles.scss
Labels: target: feature branch

#25080 build: add card example to mdc-migration integration test
  integration/mdc-migration/golden/src/app/app.component.html
  integration/mdc-migration/golden/src/app/app.module.ts
  integration/mdc-migration/golden/src/app/components/card/card.component.html
  integration/mdc-migration/golden/src/app/components/card/card.component.scss
  integration/mdc-migration/golden/src/app/components/card/card.component.spec.ts
  integration/mdc-migration/golden/src/app/components/card/card.component.ts
  integration/mdc-migration/golden/src/styles.scss
  integration/mdc-migration/sample-project/src/app/app.component.html
  integration/mdc-migration/sample-project/src/app/app.module.ts
  integration/mdc-migration/sample-project/src/app/components/card/card.component.html
  integration/mdc-migration/sample-project/src/app/components/card/card.component.scss
  integration/mdc-migration/sample-project/src/app/components/card/card.component.spec.ts
  integration/mdc-migration/sample-project/src/app/components/card/card.component.ts
  integration/mdc-migration/sample-project/src/styles.scss
Labels: target: feature branch

#25083 build: update to latest snapshot of ESM ng-dev
  package.json
  tools/defaults.bzl
  yarn.lock
Labels: merge ready, merge safe, target: patch

#25102 feat(material/schematics): initial setup for v15 ng-update
  src/cdk/schematics/update-tool/target-version.ts
  src/material/schematics/migration.json
  src/material/schematics/ng-update/index.ts
  src/material/schematics/ng-update/migrations/legacy-components-v15/index.ts
  src/material/schematics/ng-update/test-cases/v15/legacy-components-v15.spec.ts
Labels: target: feature branch

#25106 refactor(material/schematics): create shared migration utilities folder
  src/material/schematics/migration-utilities/BUILD.bazel
  src/material/schematics/migration-utilities/index.spec.ts
  src/material/schematics/migration-utilities/index.ts
  src/material/schematics/ng-generate/mdc-migration/BUILD.bazel
  src/material/schematics/ng-generate/mdc-migration/rules/components/card/card-template.ts
  src/material/schematics/ng-generate/mdc-migration/rules/components/chips/chips-template.ts
  src/material/schematics/ng-generate/mdc-migration/rules/template-migration.ts
  src/material/schematics/ng-generate/mdc-migration/rules/template-migrator.ts
Labels: target: feature branch

#25097 fix(cdk/scrolling): content jumping in appendOnly mode
  src/cdk/scrolling/virtual-scroll-viewport.spec.ts
  src/cdk/scrolling/virtual-scroll-viewport.ts
Labels: P3, merge ready, target: patch

#25109 build: ensure ng-dev command works on windows
  package.json
Labels: merge ready, merge safe, target: patch

#25111 build: avoid use of `yarn ts-node` to avoid nested yarn execution
  package.json
  tools/defaults.bzl
Labels: merge ready, merge safe, target: patch

#25114 fix(material/button-toggle): selected state not visible in high contrast mode
  src/material/button-toggle/button-toggle.scss
Labels: P3, a11y, merge ready, target: patch

#25121 build: fix benchpress build errors
  test/benchmarks/cdk/testing/component-harness/BUILD.bazel
  test/benchmarks/cdk/testing/component-harness/testbed.perf-spec.ts
  test/benchmarks/material/button/BUILD.bazel
  test/benchmarks/material/card/BUILD.bazel
  test/benchmarks/material/checkbox/BUILD.bazel
  test/benchmarks/material/chips/BUILD.bazel
  test/benchmarks/material/form-field/BUILD.bazel
  test/benchmarks/material/menu/BUILD.bazel
  test/benchmarks/material/radio/BUILD.bazel
  test/benchmarks/material/slide-toggle/BUILD.bazel
  test/benchmarks/material/table/BUILD.bazel
  test/benchmarks/material/tabs/BUILD.bazel
  test/benchmarks/mdc/button/BUILD.bazel
  test/benchmarks/mdc/card/BUILD.bazel
  test/benchmarks/mdc/checkbox/BUILD.bazel
  test/benchmarks/mdc/chips/BUILD.bazel
  test/benchmarks/mdc/form-field/BUILD.bazel
  test/benchmarks/mdc/menu/BUILD.bazel
  test/benchmarks/mdc/radio/BUILD.bazel
  test/benchmarks/mdc/slide-toggle/BUILD.bazel
  test/benchmarks/mdc/table/BUILD.bazel
  test/benchmarks/mdc/tabs/BUILD.bazel
Labels: merge ready, merge safe, target: patch

#25126 build: fix `yarn merge` script alias since it wasn't using ts-node
  package.json
Labels: merge ready, merge safe, target: patch

#25129 build: add list example to mdc-migration integration test
  integration/mdc-migration/golden/src/app/app.component.html
  integration/mdc-migration/golden/src/app/app.module.ts
  integration/mdc-migration/golden/src/app/components/list/list.component.html
  integration/mdc-migration/golden/src/app/components/list/list.component.scss
  integration/mdc-migration/golden/src/app/components/list/list.component.spec.ts
  integration/mdc-migration/golden/src/app/components/list/list.component.ts
  integration/mdc-migration/golden/src/styles.scss
  integration/mdc-migration/sample-project/src/app/app.component.html
  integration/mdc-migration/sample-project/src/app/app.module.ts
  integration/mdc-migration/sample-project/src/app/components/list/list.component.html
  integration/mdc-migration/sample-project/src/app/components/list/list.component.scss
  integration/mdc-migration/sample-project/src/app/components/list/list.component.spec.ts
  integration/mdc-migration/sample-project/src/app/components/list/list.component.ts
  integration/mdc-migration/sample-project/src/styles.scss
Labels: target: feature branch

#25128 feat(material/schematics): create updateModuleSpecifier ts migrat…
  src/material/schematics/migration-utilities/BUILD.bazel
  src/material/schematics/migration-utilities/index.ts
  src/material/schematics/migration-utilities/typescript/import-operations.spec.ts
  src/material/schematics/migration-utilities/typescript/import-operations.ts
  src/material/schematics/migration-utilities/update.ts
Labels: target: feature branch

#25132 feat(material/schematics): create updateNamedImport ts migration fn
  src/material/schematics/migration-utilities/typescript/import-operations.spec.ts
  src/material/schematics/migration-utilities/typescript/import-operations.ts
Labels: target: feature branch

#25123 fix(material/datepicker): actions not re-rendering if swapped out while calendar is open
  src/material/datepicker/datepicker-actions.spec.ts
  src/material/datepicker/datepicker-base.ts
  tools/public_api_guard/material/datepicker.md
Labels: P3, merge ready, target: patch

#25141 build: avoid use of ts-node wrapper script as it breaks child process forking
  package.json
  yarn.lock
Labels: merge ready, merge safe, target: patch

#25146 build: prepare for v15 and exceptional minors for v14
  .ng-dev/pull-request.mts
  package.json
  scripts/docs-deploy/deploy-ci-push.mts
  yarn.lock
Labels: merge ready, merge safe, target: minor

#25139 build: add radio example to mdc-migration integration test
  integration/mdc-migration/golden/src/app/app.component.html
  integration/mdc-migration/golden/src/app/app.module.ts
  integration/mdc-migration/golden/src/app/components/radio/radio.component.html
  integration/mdc-migration/golden/src/app/components/radio/radio.component.scss
  integration/mdc-migration/golden/src/app/components/radio/radio.component.spec.ts
  integration/mdc-migration/golden/src/app/components/radio/radio.component.ts
  integration/mdc-migration/golden/src/styles.scss
  integration/mdc-migration/sample-project/src/app/app.component.html
  integration/mdc-migration/sample-project/src/app/app.module.ts
  integration/mdc-migration/sample-project/src/app/components/radio/radio.component.html
  integration/mdc-migration/sample-project/src/app/components/radio/radio.component.scss
  integration/mdc-migration/sample-project/src/app/components/radio/radio.component.spec.ts
  integration/mdc-migration/sample-project/src/app/components/radio/radio.component.ts
  integration/mdc-migration/sample-project/src/styles.scss
Labels: target: feature branch

#25105 fix(material/stepper): isErrorState accepts AbstractControl instead of UntypedFormControl to avoid compiler errors when strict typing is enabled
  src/material/core/common-behaviors/error-state.ts
  src/material/stepper/stepper.ts
  tools/public_api_guard/material/stepper.md
Labels: merge ready, target: patch

#25150 build: add slide-toggle example to mdc-migration integration test
  integration/mdc-migration/golden/src/app/app.component.html
  integration/mdc-migration/golden/src/app/app.module.ts
  integration/mdc-migration/golden/src/app/components/slide-toggle/slide-toggle.component.html
  integration/mdc-migration/golden/src/app/components/slide-toggle/slide-toggle.component.scss
  integration/mdc-migration/golden/src/app/components/slide-toggle/slide-toggle.component.spec.ts
  integration/mdc-migration/golden/src/app/components/slide-toggle/slide-toggle.component.ts
  integration/mdc-migration/golden/src/styles.scss
  integration/mdc-migration/sample-project/src/app/app.component.html
  integration/mdc-migration/sample-project/src/app/app.module.ts
  integration/mdc-migration/sample-project/src/app/components/slide-toggle/slide-toggle.component.html
  integration/mdc-migration/sample-project/src/app/components/slide-toggle/slide-toggle.component.scss
  integration/mdc-migration/sample-project/src/app/components/slide-toggle/slide-toggle.component.spec.ts
  integration/mdc-migration/sample-project/src/app/components/slide-toggle/slide-toggle.component.ts
  integration/mdc-migration/sample-project/src/styles.scss
Labels: target: feature branch

#25152 build: dependencies duplicated when deploying snapshots
  scripts/docs-deploy/install-built-packages.mts
Labels: P2, merge ready, merge safe, target: patch

#25116 Fix mat-chip avatar image stretch issue
  src/components-examples/material/chips/chips-avatar/chips-avatar-example.html
Labels: docs, merge ready, merge safe, target: patch, commit message fixup

#25155 build: add slider example to mdc-migration integration test
  integration/mdc-migration/golden/src/app/app.component.html
  integration/mdc-migration/golden/src/app/app.module.ts
  integration/mdc-migration/golden/src/app/components/slider/slider.component.html
  integration/mdc-migration/golden/src/app/components/slider/slider.component.scss
  integration/mdc-migration/golden/src/app/components/slider/slider.component.spec.ts
  integration/mdc-migration/golden/src/app/components/slider/slider.component.ts
  integration/mdc-migration/golden/src/styles.scss
  integration/mdc-migration/sample-project/src/app/app.component.html
  integration/mdc-migration/sample-project/src/app/app.module.ts
  integration/mdc-migration/sample-project/src/app/components/slider/slider.component.html
  integration/mdc-migration/sample-project/src/app/components/slider/slider.component.scss
  integration/mdc-migration/sample-project/src/app/components/slider/slider.component.spec.ts
  integration/mdc-migration/sample-project/src/app/components/slider/slider.component.ts
  integration/mdc-migration/sample-project/src/styles.scss
Labels: target: feature branch

#25151 fix(docs): rename master to main
  src/components-examples/material-experimental/mdc-table/table-selection/table-selection-example.html
  src/components-examples/material-experimental/mdc-table/table-selection/table-selection-example.ts
  src/components-examples/material/table/table-selection/table-selection-example.html
  src/components-examples/material/table/table-selection/table-selection-example.ts
  src/material/core/style/_variables.scss
  src/material/table/table.md
Labels: docs, merge ready, merge safe, target: patch

#25157 build: add snack-bar example to mdc-migration integration test
  integration/mdc-migration/golden/src/app/app.component.html
  integration/mdc-migration/golden/src/app/app.module.ts
  integration/mdc-migration/golden/src/app/components/snack-bar/snack-bar.component.html
  integration/mdc-migration/golden/src/app/components/snack-bar/snack-bar.component.scss
  integration/mdc-migration/golden/src/app/components/snack-bar/snack-bar.component.spec.ts
  integration/mdc-migration/golden/src/app/components/snack-bar/snack-bar.component.ts
  integration/mdc-migration/golden/src/styles.scss
  integration/mdc-migration/sample-project/src/app/app.component.html
  integration/mdc-migration/sample-project/src/app/app.module.ts
  integration/mdc-migration/sample-project/src/app/components/snack-bar/snack-bar.component.html
  integration/mdc-migration/sample-project/src/app/components/snack-bar/snack-bar.component.scss
  integration/mdc-migration/sample-project/src/app/components/snack-bar/snack-bar.component.spec.ts
  integration/mdc-migration/sample-project/src/app/components/snack-bar/snack-bar.component.ts
  integration/mdc-migration/sample-project/src/styles.scss
Labels: target: feature branch

#25158 build: add table example to mdc-migration integration test
  integration/mdc-migration/golden/src/app/app.component.html
  integration/mdc-migration/golden/src/app/app.module.ts
  integration/mdc-migration/golden/src/app/components/table/table.component.html
  integration/mdc-migration/golden/src/app/components/table/table.component.scss
  integration/mdc-migration/golden/src/app/components/table/table.component.spec.ts
  integration/mdc-migration/golden/src/app/components/table/table.component.ts
  integration/mdc-migration/golden/src/styles.scss
  integration/mdc-migration/sample-project/src/app/app.component.html
  integration/mdc-migration/sample-project/src/app/app.module.ts
  integration/mdc-migration/sample-project/src/app/components/table/table.component.html
  integration/mdc-migration/sample-project/src/app/components/table/table.component.scss
  integration/mdc-migration/sample-project/src/app/components/table/table.component.spec.ts
  integration/mdc-migration/sample-project/src/app/components/table/table.component.ts
  integration/mdc-migration/sample-project/src/styles.scss
Labels: target: feature branch

#25162 build: load Google Maps and YouTube APIs on demand in dev app
  src/dev-app/google-map/google-map-demo.html
  src/dev-app/google-map/google-map-demo.ts
  src/dev-app/index.html
  src/dev-app/youtube-player/youtube-player-demo.ts
Labels: P3, merge ready, merge safe, target: patch

#25167 docs(material/autocomplete): use single map instead of two maps in a row
  src/components-examples/material/autocomplete/autocomplete-display/autocomplete-display-example.ts
Labels: docs, merge ready, merge safe, target: patch

#25160 fix(material-experimental/mdc-chips): missing role for trailing actions container
  src/material-experimental/mdc-chips/chip-row.html
Labels: P3, a11y, merge ready, target: patch

#24578 feat(material/icon): SEO friendly ligature icons
  src/components-examples/material/icon/icon-harness/icon-harness-example.html
  src/components-examples/material/icon/icon-harness/icon-harness-example.spec.ts
  src/components-examples/material/icon/icon-overview/icon-overview-example.html
  src/dev-app/icon/icon-demo.html
  src/material/icon/icon-registry.ts
  src/material/icon/icon.scss
  src/material/icon/icon.spec.ts
  src/material/icon/icon.ts
  src/material/icon/testing/shared.spec.ts
  tools/public_api_guard/material/icon.md
Labels: merge ready, target: minor

#25176 build: configure renovate to update bazel dependencies
  renovate.json
Labels: merge ready, merge safe, target: patch

#25183 build: fix loose yarn engine range
  package.json
Labels: merge ready, merge safe, target: patch

#25185 feat(cdk/portal): support projectableNodes in component portal
  src/cdk/portal/dom-portal-outlet.ts
  src/cdk/portal/portal-directives.ts
  src/cdk/portal/portal.spec.ts
  src/cdk/portal/portal.ts
  tools/public_api_guard/cdk/portal.md
Labels: P3, merge ready, target: minor

#25081 build: add checkbox example to mdc-migration integration test
  integration/mdc-migration/golden/src/app/app.component.html
  integration/mdc-migration/golden/src/app/app.module.ts
  integration/mdc-migration/golden/src/app/components/checkbox/checkbox.component.html
  integration/mdc-migration/golden/src/app/components/checkbox/checkbox.component.scss
  integration/mdc-migration/golden/src/app/components/checkbox/checkbox.component.spec.ts
  integration/mdc-migration/golden/src/app/components/checkbox/checkbox.component.ts
  integration/mdc-migration/golden/src/styles.scss
  integration/mdc-migration/sample-project/src/app/app.component.html
  integration/mdc-migration/sample-project/src/app/app.module.ts
  integration/mdc-migration/sample-project/src/app/components/checkbox/checkbox.component.html
  integration/mdc-migration/sample-project/src/app/components/checkbox/checkbox.component.scss
  integration/mdc-migration/sample-project/src/app/components/checkbox/checkbox.component.spec.ts
  integration/mdc-migration/sample-project/src/app/components/checkbox/checkbox.component.ts
  integration/mdc-migration/sample-project/src/styles.scss
Labels: target: feature branch

#25199 build: account for rename of angular/code-of-conduct default branch
  CONTRIBUTING.md
Labels: merge ready, merge safe, target: patch

#25197 fix(material/checkbox): broken appearance in some grid layouts
  src/material-experimental/mdc-checkbox/checkbox.scss
  src/material/checkbox/checkbox.scss
Labels: P3, merge ready, target: patch
