Repository angular/components, pull requests merged in 2022-01, with the labels that each got.

#24167 fix(material-experimental/mdc-slider): keep value indicator within bounds
  package.json
  src/material-experimental/mdc-slider/slider-thumb.html
  src/material-experimental/mdc-slider/slider.ts
  yarn.lock
Labels: merge ready, merge safe, target: patch

#24152 build: add unlisted dependencies to package.json
  src/material-experimental/package.json
  src/material/package.json
Labels: P3, merge ready, merge safe, target: patch

#24149 build: bump year
  LICENSE
Labels: merge ready, merge safe, P4, target: patch

#24142 build: add all prebuilt themes to experimental
  src/material-experimental/mdc-theming/BUILD.bazel
  src/material-experimental/mdc-theming/prebuilt/deeppurple-amber.scss
  src/material-experimental/mdc-theming/prebuilt/pink-bluegrey.scss
  src/material-experimental/mdc-theming/prebuilt/purple-green.scss
  src/material-experimental/package.json
Labels: P3, merge ready, merge safe, target: patch

#24066 ci: Add tsec_test for all ng_module targets.
  goldens/BUILD.bazel
  goldens/tsec-exemption.json
  package.json
  src/BUILD.bazel
  src/cdk/a11y/focus-monitor/focus-monitor.ts
  src/material-experimental/mdc-chips/chip-row.ts
  src/tsconfig-tsec.json
  tools/defaults.bzl
  yarn.lock
Labels: merge ready, target: patch

#24160 fix(cdk/overlay): fix positioning when zooming in Safari
  src/cdk/overlay/position/flexible-connected-position-strategy.spec.ts
  src/cdk/overlay/position/flexible-connected-position-strategy.ts
Labels: P3, merge ready, target: patch

#24159 fix(cdk/text-field): handle undefined placeholder
  src/cdk/text-field/autosize.spec.ts
  src/cdk/text-field/autosize.ts
Labels: P3, merge ready, target: patch

#24131 fix(material/stepper): icon not centered in header if direction changes
  src/material/stepper/step-header.scss
Labels: cla: yes, P3, merge ready, target: patch, dev-app preview

#24094 refactor(cdk/testing): reuse stabilize callback when creating test element
  src/cdk/testing/harness-environment.ts
  src/cdk/testing/selenium-webdriver/selenium-web-driver-harness-environment.ts
  src/cdk/testing/testbed/testbed-harness-environment.ts
  tools/public_api_guard/cdk/testing.md
Labels: P3, merge ready, target: patch

#24169 fix(cdk/schematics): remove file extensions in tilde migration
  src/cdk/schematics/ng-update/migrations/tilde-import-v13/tilde-import-migration.ts
  src/cdk/schematics/ng-update/test-cases/v13/misc/tilde-import-v13.spec.ts
Labels: P3, merge ready, merge safe, target: patch

#24168 build: add .vimrc to gitignore
  .gitignore
Labels: merge ready, merge safe, target: patch, area: build

#24062 Refactor MatTabNav as ARIA tabs with a new MatTabNavPanel component and [tabPanel] input.
  src/components-examples/material/tabs/index.ts
  src/components-examples/material/tabs/tab-nav-bar-with-panel/tab-nav-bar-with-panel-example.css
  src/components-examples/material/tabs/tab-nav-bar-with-panel/tab-nav-bar-with-panel-example.html
  src/components-examples/material/tabs/tab-nav-bar-with-panel/tab-nav-bar-with-panel-example.ts
  src/dev-app/mdc-tabs/mdc-tabs-demo.html
  src/dev-app/tabs/tabs-demo.html
  src/material-experimental/mdc-tabs/module.ts
  src/material-experimental/mdc-tabs/public-api.ts
  src/material-experimental/mdc-tabs/tab-nav-bar/tab-nav-bar.spec.ts
  src/material-experimental/mdc-tabs/tab-nav-bar/tab-nav-bar.ts
  src/material-experimental/mdc-tabs/testing/tab-harness-filters.ts
  src/material-experimental/mdc-tabs/testing/tab-nav-bar-harness.ts
  src/material-experimental/mdc-tabs/testing/tab-nav-panel-harness.ts
  src/material/tabs/public-api.ts
  src/material/tabs/tab-nav-bar/tab-nav-bar.spec.ts
  src/material/tabs/tab-nav-bar/tab-nav-bar.ts
  src/material/tabs/tabs-module.ts
  src/material/tabs/testing/tab-harness-filters.ts
  src/material/tabs/testing/tab-nav-bar-harness.ts
  src/material/tabs/testing/tab-nav-bar-shared.spec.ts
  src/material/tabs/testing/tab-nav-panel-harness.ts
  tools/public_api_guard/material/tabs-testing.md
  tools/public_api_guard/material/tabs.md
Labels: cla: yes, P2, merge ready, G, target: minor

#23218 fix(material-experimental/mdc-checkbox): switch to non-deprecated styles
  src/material-experimental/mdc-checkbox/_checkbox-theme.scss
  src/material-experimental/mdc-checkbox/checkbox.scss
  src/material-experimental/mdc-list/_list-option-theme.scss
  src/material-experimental/mdc-list/_list-theme.scss
  src/material-experimental/mdc-list/list-option.scss
Labels: cla: yes, P2, merge ready, target: patch

#24140 fix(material-experimental/mdc-dialog): remove extra outline in high contrast mode
  src/material-experimental/mdc-dialog/dialog.scss
Labels: cla: yes, P3, merge ready, target: patch

#24129 fix(material-experimental/mdc-select): change max height to show scrollability
  src/material-experimental/mdc-select/select.scss
  src/material-experimental/mdc-select/select.spec.ts
Labels: cla: yes, P3, merge ready, target: patch

#24148 refactor(material-experimental/mdc-select): remove dependency on @material/select
  src/material-experimental/mdc-select/_select-theme.scss
Labels: P3, merge ready, target: patch

#23462 refactor(material/table): clean up IE workarounds
  src/cdk/table/cell.ts
  src/material/table/_table-flex-styles.scss
  src/material/table/table.md
Labels: cla: yes, P3, merge ready, target: patch

#24083 build: reduce jelbourn presence in code owners
  .github/CODEOWNERS
Labels: cla: yes, merge ready, merge safe, target: patch

#24175 fix(material-experimental/mdc-list): export missing harness symbols
  src/material-experimental/mdc-list/testing/public-api.ts
Labels: merge ready, merge safe, target: patch

#24176 docs(material/radio): fix button width
  src/components-examples/material/radio/radio-ng-model/radio-ng-model-example.css
Labels: P3, docs, merge ready, merge safe, target: patch

#24120 fix(material/core): disable strong focus indicators in high contrast mode
  src/material-experimental/mdc-helpers/_focus-indicators.scss
  src/material/core/focus-indicators/_focus-indicators.scss
Labels: cla: yes, P3, a11y, merge ready, G, target: patch

#24116 refactor(material/menu): use separate signature for deprecated constructor parameters
  src/material/menu/menu-content.ts
  src/material/menu/menu-item.ts
  src/material/menu/menu-trigger.ts
  tools/public_api_guard/material/menu.md
Labels: cla: yes, P3, merge ready, target: patch

#23885 fix(cdk/table): Measure column width for sticky columns after new data ha…
  src/cdk/table/table.ts
  tools/public_api_guard/cdk/table.md
Labels: merge ready, G, target: patch, area: cdk/table

#24174 fix(material-experimental/mdc-list): ensure selection change event fires properly
  src/material-experimental/mdc-list/selection-list.spec.ts
  src/material-experimental/mdc-list/selection-list.ts
Labels: merge ready, target: minor, dev-app preview

#23982 build: prevent * expansion for static css content in ng_web_test_suite
  tools/defaults.bzl
Labels: merge ready, merge safe, target: patch

#23931 feat(material-experimental/mdc-chips): switch to evolution API
  scripts/check-mdc-tests-config.ts
  src/dev-app/chips/chips-demo.html
  src/dev-app/mdc-chips/mdc-chips-demo.html
  src/material-experimental/mdc-chips/BUILD.bazel
  src/material-experimental/mdc-chips/_chips-theme.scss
  src/material-experimental/mdc-chips/chip-action.ts
  src/material-experimental/mdc-chips/chip-edit-input.spec.ts
  src/material-experimental/mdc-chips/chip-edit-input.ts
  src/material-experimental/mdc-chips/chip-grid.spec.ts
  src/material-experimental/mdc-chips/chip-grid.ts
  src/material-experimental/mdc-chips/chip-icons.ts
  src/material-experimental/mdc-chips/chip-input.spec.ts
  src/material-experimental/mdc-chips/chip-input.ts
  src/material-experimental/mdc-chips/chip-listbox.spec.ts
  src/material-experimental/mdc-chips/chip-listbox.ts
  src/material-experimental/mdc-chips/chip-option.html
  src/material-experimental/mdc-chips/chip-option.spec.ts
  src/material-experimental/mdc-chips/chip-option.ts
  src/material-experimental/mdc-chips/chip-remove.spec.ts
  src/material-experimental/mdc-chips/chip-row.html
  src/material-experimental/mdc-chips/chip-row.spec.ts
  src/material-experimental/mdc-chips/chip-row.ts
  src/material-experimental/mdc-chips/chip-set.scss
  src/material-experimental/mdc-chips/chip-set.ts
  src/material-experimental/mdc-chips/chip.html
  src/material-experimental/mdc-chips/chip.scss
  src/material-experimental/mdc-chips/chip.spec.ts
  src/material-experimental/mdc-chips/chip.ts
  src/material-experimental/mdc-chips/chips.scss
  src/material-experimental/mdc-chips/emit-event.ts
  src/material-experimental/mdc-chips/grid-focus-key-manager.ts
  src/material-experimental/mdc-chips/grid-key-manager.ts
  src/material-experimental/mdc-chips/module.ts
  src/material-experimental/mdc-chips/testing/chip-harness.ts
  src/material-experimental/mdc-chips/testing/chip-option-harness.ts
  src/material-experimental/mdc-chips/testing/chip-row-harness.spec.ts
  src/material-experimental/mdc-chips/testing/chip-row-harness.ts
  src/material-experimental/mdc-helpers/_focus-indicators.scss
Labels: P2, merge ready, target: minor

#24179 fix(material-experimental/mdc-button): incorrect metadata for fab anchor
  src/material-experimental/mdc-button/fab.ts
Labels: P3, merge ready, target: patch

#24132 fix(material/core): move pseudo-checkbox module to same directory
  src/material/core/selection/index.ts
  src/material/core/selection/pseudo-checkbox/pseudo-checkbox-module.ts
Labels: cla: yes, P3, merge ready, caretaker note, target: patch

#24186 fix(material-experimental/mdc-button): remove unwanted native button styles
  src/material-experimental/mdc-list/list.scss
Labels: merge ready, target: patch, dev-app preview

#24198 build: update to latest angular version and fix snapshot CI jobs
  package.json
  tools/postinstall/devmode-es2020-bazel.patch
  yarn.lock
Labels: merge ready, merge safe, target: minor

#24191 build: update shelljs dependencies to "^0.8.5"
  package.json
  yarn.lock
Labels: merge ready, merge safe, target: patch, area: build

#24188 build: update to latest version of sass
  package.json
  yarn.lock
Labels: P3, merge ready, merge safe, target: minor

#24184 fix(material-experimental/mdc-checkbox): emitting fallback values for density CSS variables
  src/material-experimental/mdc-checkbox/_checkbox-theme.scss
Labels: P3, merge ready, target: patch

#14434 fix(material/tooltip): not closing if escape is pressed while trigger isn't focused
  src/material-experimental/mdc-tooltip/tooltip.spec.ts
  src/material/tooltip/tooltip.spec.ts
  src/material/tooltip/tooltip.ts
Labels: merge ready, P4, target: patch

#14813 fix(material/autocomplete): optionSelections not emitting when the list of options changes
  src/material-experimental/mdc-autocomplete/autocomplete.spec.ts
  src/material/autocomplete/autocomplete-trigger.ts
  src/material/autocomplete/autocomplete.spec.ts
Labels: P2, merge ready, target: patch

#23992 perf(material/button): do not run change detection when the anchor is clicked
  src/material-experimental/mdc-button/BUILD.bazel
  src/material-experimental/mdc-button/button-base.ts
  src/material-experimental/mdc-button/button.spec.ts
  src/material/button/BUILD.bazel
  src/material/button/button.spec.ts
  src/material/button/button.ts
  tools/public_api_guard/material/button.md
Labels: P3, perf, merge ready, target: patch, area: material/button

#13973 fix(sidenav): implicit content element being registered twice with scroll dispatcher
  src/material/sidenav/drawer.ts
  src/material/sidenav/sidenav-container.html
  src/material/sidenav/sidenav.ts
Labels: merge ready, target: patch

#24203 build: fix sidenav formatting
  src/material/sidenav/drawer.ts
  src/material/sidenav/sidenav.ts
Labels: P3, merge ready, merge safe, target: patch

#23482 refactor(material/core): remove extra version constant
  src/material/core/common-behaviors/common-module.ts
Labels: cla: yes, P3, merge ready, target: patch

#21425 fix(material-experimental/mdc-snack-bar): avoid hard reference to base components and align API
  src/dev-app/mdc-snack-bar/mdc-snack-bar-demo.ts
  src/material-experimental/mdc-snack-bar/module.ts
  src/material-experimental/mdc-snack-bar/public-api.ts
  src/material-experimental/mdc-snack-bar/simple-snack-bar.ts
  src/material-experimental/mdc-snack-bar/snack-bar.spec.ts
  src/material-experimental/mdc-snack-bar/snack-bar.ts
  src/material-experimental/mdc-snack-bar/testing/snack-bar-harness.spec.ts
  src/material/snack-bar/snack-bar.ts
  tools/public_api_guard/material/snack-bar.md
Labels: cla: yes, P3, merge ready, target: patch

#23831 feat(google-maps): allow for info window focus behavior to be customized
  src/google-maps/map-info-window/map-info-window.spec.ts
  src/google-maps/map-info-window/map-info-window.ts
  src/google-maps/testing/fake-google-map-utils.ts
  tools/public_api_guard/google-maps/google-maps.md
Labels: P3, merge ready, target: minor

#23612 fix(material/core): throw error if hue does not exist
  src/material/core/theming/_theming.scss
Labels: cla: yes, P3, merge ready, target: patch

#22889 fix(material/datepicker): add focus indication to calendar selected date in high contrast mode
  src/material/datepicker/calendar-body.scss
Labels: cla: yes, P3, a11y, merge ready, target: patch

#23827 fix(material/slider): first keypress ignored if out-of-bounds value is assigned
  src/material/slider/slider.spec.ts
  src/material/slider/slider.ts
Labels: P3, merge ready, target: patch

#23823 fix(material/slider): avoid error on some touchstart events
  src/material/slider/slider.spec.ts
  src/material/slider/slider.ts
Labels: P3, merge ready, target: patch

#14717 fix(material/autocomplete): don't handle enter events with modifier keys
  src/material-experimental/mdc-autocomplete/autocomplete.spec.ts
  src/material/autocomplete/autocomplete-trigger.ts
  src/material/autocomplete/autocomplete.spec.ts
Labels: P3, merge ready, target: patch

#19233 fix(material/input): inconsistently reading name from input with ngModel
  src/material-experimental/mdc-input/input.ts
  src/material/input/input.ts
  src/material/input/testing/shared-input.spec.ts
  tools/public_api_guard/material/input.md
Labels: P3, merge ready, target: patch

#20242 fix(material/core): make MatOption generic
  src/material-experimental/mdc-core/option/option.ts
  src/material/core/option/option.ts
  tools/public_api_guard/material/core.md
Labels: P3, merge ready, target: patch

#21334 fix(material/slider): incorrectly inheriting color when nested inside component with theme
  src/material/slider/_slider-theme.scss
Labels: cla: yes, P3, merge ready, target: patch

#23288 feat(material/tabs): add API to update the pagination
  src/material/tabs/tab-group.ts
  tools/public_api_guard/material/tabs.md
Labels: cla: yes, P3, merge ready, target: minor

#23310 fix(material/menu): not interrupting keyboard events to other overlays
  src/material-experimental/mdc-menu/menu.spec.ts
  src/material/menu/menu.spec.ts
  src/material/menu/menu.ts
Labels: cla: yes, P3, merge ready, caretaker note, target: patch

#19025 fix(material/progress-bar): unable to change value through property setter
  src/material-experimental/mdc-progress-bar/progress-bar.spec.ts
  src/material/progress-bar/progress-bar.spec.ts
  src/material/progress-bar/progress-bar.ts
  tools/public_api_guard/material/progress-bar.md
Labels: P3, merge ready, target: patch

#23674 fix(material/progress-spinner): animation not working on some zoom levels in Safari
  src/material/progress-spinner/BUILD.bazel
  src/material/progress-spinner/progress-spinner.html
  src/material/progress-spinner/progress-spinner.scss
  src/material/progress-spinner/progress-spinner.ts
  tools/public_api_guard/material/progress-spinner.md
Labels: cla: yes, P3, merge ready, target: patch

#23691 feat(material/tabs): label & body classes
  src/material-experimental/mdc-tabs/tab-body.ts
  src/material-experimental/mdc-tabs/tab-group.html
  src/material-experimental/mdc-tabs/tab-group.spec.ts
  src/material-experimental/mdc-tabs/tab-group.ts
  src/material-experimental/mdc-tabs/tab-header.ts
  src/material-experimental/mdc-tabs/tab-nav-bar/tab-nav-bar.ts
  src/material-experimental/mdc-tabs/tab.ts
  src/material/tabs/tab-group.html
  src/material/tabs/tab-group.spec.ts
  src/material/tabs/tab.ts
  tools/public_api_guard/material/tabs.md
Labels: P3, merge ready, target: minor

#14356 chore: improve type safety in breakpoint observer
  src/cdk/layout/breakpoints-observer.ts
Labels: P3, merge ready, target: patch

#18443 fix(select): component value not in sync with control value on init
  src/material/select/select.spec.ts
  src/material/select/select.ts
Labels: P3, merge ready, target: patch

#24219 build: add missing test
  src/material-experimental/mdc-select/select.spec.ts
Labels: P3, merge ready, merge safe, target: patch

#24054 fix(material/paginator): allow readonly options (#24050)
  src/material-experimental/mdc-paginator/paginator.spec.ts
  src/material/paginator/paginator.spec.ts
  src/material/paginator/paginator.ts
  tools/public_api_guard/material/paginator.md
Labels: merge ready, P4, target: patch

#24212 fix(material/list): add isDisabled to all list item harnesses
  src/material-experimental/mdc-list/testing/list-harness.spec.ts
  src/material-experimental/mdc-list/testing/list-item-harness-base.ts
  src/material-experimental/mdc-list/testing/selection-list-harness.ts
  src/material/list/testing/list-item-harness-base.ts
  src/material/list/testing/selection-list-harness.ts
  src/material/list/testing/shared.spec.ts
  tools/public_api_guard/material/list-testing.md
Labels: P3, merge ready, target: minor

#18881 fix(material/list): fix up disabled list item styles
  src/material/core/theming/_palette.scss
  src/material/list/_list-theme.scss
Labels: P3, merge ready, presubmit failures, target: patch

#23949 fix(material/form-field): outline gap not recalculated when switching to empty label
  scripts/check-mdc-tests-config.ts
  src/material/form-field/form-field.ts
  src/material/input/input.spec.ts
Labels: P3, merge ready, target: patch

#23678 fix(material/card): handle picture element as mat-card-image
  src/material/card/card.scss
Labels: cla: yes, P3, merge ready, target: patch

#23493 fix(cdk/a11y): not detecting fake mousedown on firefox
  src/cdk/a11y/fake-event-detection.ts
  src/cdk/a11y/focus-monitor/focus-monitor.spec.ts
  src/cdk/a11y/input-modality/input-modality-detector.spec.ts
Labels: cla: yes, P2, a11y, merge ready, target: patch

#18707 fix(autocomplete): restore focus after emitting option selected event
  src/material/autocomplete/autocomplete-trigger.ts
  src/material/autocomplete/autocomplete.spec.ts
Labels: merge ready, P4, target: patch

#24216 docs: rename `navgating` to `navigating`
  src/material-experimental/mdc-menu/menu.spec.ts
  src/material/menu/menu.spec.ts
  src/material/tabs/tabs.md
Labels: docs, merge ready, merge safe, target: patch

#24202 fix(cdk/table): revert breaking change of CdkTable constructor
  src/cdk/table/table.ts
  tools/public_api_guard/cdk/table.md
Labels: P2, merge ready, merge safe, target: patch

#18101 fix(material/sidenav): end position sidenav tab order not matching visual order
  src/material/sidenav/drawer.html
  src/material/sidenav/drawer.spec.ts
  src/material/sidenav/drawer.ts
  tools/public_api_guard/material/sidenav.md
Labels: P3, a11y, merge ready, target: patch

#24231 build: fix unformatted files
  src/cdk/a11y/focus-monitor/focus-monitor.spec.ts
  src/cdk/table/table.ts
  src/material-experimental/mdc-autocomplete/autocomplete.spec.ts
  src/material/autocomplete/autocomplete.spec.ts
  src/material/select/select.spec.ts
Labels: P3, merge ready, merge safe, target: patch

#14471 fix(cdk/a11y): activeItem out of date if active index is removed from ListKeyManager
  src/cdk/a11y/key-manager/list-key-manager.spec.ts
  src/cdk/a11y/key-manager/list-key-manager.ts
  src/material-experimental/mdc-menu/menu.spec.ts
  src/material/menu/menu.spec.ts
Labels: P3, a11y, merge ready, caretaker note, target: patch

#24232 refactor(cdk/a11y): use correct method when updating active item
  src/cdk/a11y/key-manager/list-key-manager.ts
Labels: P3, merge ready, merge safe, target: patch

#24233 Revert "fix(cdk/a11y): activeItem out of date if active index is removed from ListKeyManager
  src/cdk/a11y/key-manager/list-key-manager.spec.ts
  src/cdk/a11y/key-manager/list-key-manager.ts
  src/material-experimental/mdc-menu/menu.spec.ts
  src/material/menu/menu.spec.ts
Labels: merge ready, merge safe, target: patch

#24201 refactor(material-experimental/mdc-button): switch to new theming API
  src/material-experimental/mdc-button/_button-base.scss
  src/material-experimental/mdc-button/_button-theme-private.scss
  src/material-experimental/mdc-button/_button-theme.scss
  src/material-experimental/mdc-button/_fab-theme.scss
  src/material-experimental/mdc-button/_icon-button-theme.scss
  src/material-experimental/mdc-button/button-base.ts
  src/material-experimental/mdc-button/button.html
  src/material-experimental/mdc-button/button.scss
  src/material-experimental/mdc-button/fab.scss
  src/material-experimental/mdc-button/icon-button.scss
  src/material-experimental/mdc-button/icon-button.ts
Labels: P2, merge ready, target: patch

#24243 fix(material-experimental/mdc-chips): fix changed after checked error when restoring focus to input
  src/material-experimental/mdc-chips/chip-grid.ts
Labels: P3, merge ready, G, target: patch

#24247 fix(material-experimental/mdc-core): make mat-option typography easier to override
  src/material-experimental/mdc-core/option/_option-theme.scss
  src/material-experimental/mdc-core/option/option.scss
Labels: P3, merge ready, G, target: patch

#23361 fix(material/list): fix duplicate focus with chromevox on action-list items
  src/material/list/list-item.html
  src/material/list/list.scss
Labels: cla: yes, P2, a11y, merge ready, target: patch, area: material/list

#12161 fix(expansion-panel): title text not centered with taller description
  src/material/expansion/expansion-panel-header.scss
Labels: P3, merge ready, target: patch

#24222 fix(material-experimental/mdc-form-field): incorrect alignment with border-box alignment
  src/material-experimental/mdc-form-field/form-field.scss
Labels: P3, merge ready, G, target: patch

#24029 fix(material/core): ripples not being clipped on safari in shadow dom
  src/material/core/ripple/_ripple.scss
  src/material/core/ripple/ripple-renderer.ts
Labels: P3, merge ready, target: patch

#24241 feat(material-experimental/mdc-form-field): Add option for dynamic su…
  src/dev-app/mdc-input/mdc-input-demo.html
  src/material-experimental/mdc-form-field/_form-field-subscript.scss
  src/material-experimental/mdc-form-field/form-field.html
  src/material-experimental/mdc-form-field/form-field.ts
  src/material-experimental/mdc-input/input.spec.ts
Labels: merge ready, G, target: patch, dev-app preview

#24260 build: setup renovate to update shared dev-infra code
  renovate.json
Labels: merge ready, merge safe, target: patch

#24267 perf(material-experimental/mdc-radio): reduce bundle size
  src/material-experimental/mdc-radio/_radio-theme.scss
  src/material-experimental/mdc-radio/radio.html
  src/material-experimental/mdc-radio/radio.scss
Labels: P2, merge ready, target: patch

#24256 perf(material-experimental/mdc-checkbox): reduce bundle size
  src/material-experimental/mdc-checkbox/BUILD.bazel
  src/material-experimental/mdc-checkbox/_checkbox-theme.scss
  src/material-experimental/mdc-checkbox/checkbox.html
  src/material-experimental/mdc-checkbox/checkbox.scss
  src/material-experimental/mdc-checkbox/checkbox.ts
  src/material-experimental/mdc-checkbox/module.ts
Labels: P2, merge ready, target: patch

#24171 Put buttons in calendar cells
  src/material/datepicker/calendar-body.html
  src/material/datepicker/calendar-body.scss
  src/material/datepicker/calendar-body.spec.ts
  src/material/datepicker/calendar-body.ts
  src/material/datepicker/testing/calendar-cell-harness.ts
Labels: a11y, merge ready, target: patch, area: material/datepicker, dev-app preview

#24263 fix(material-experimental/mdc-form-field): Properly handle when defau…
  src/material-experimental/mdc-form-field/form-field.ts
  src/material-experimental/mdc-input/input.spec.ts
Labels: merge ready, target: minor

#21224 fix(material/slide-toggle): remove divs nested inside label
  src/material/slide-toggle/slide-toggle.html
  src/material/slide-toggle/slide-toggle.scss
Labels: cla: yes, P3, a11y, merge ready, target: patch

#24262 perf(material-experimental/mdc-tabs): reduce bundle size
  src/material-experimental/mdc-tabs/_tabs-common.scss
  src/material-experimental/mdc-tabs/_tabs-theme.scss
Labels: P2, merge ready, target: patch

#19763 fix(material/chips): don't stop propagation on all click events
  src/material/chips/chip.ts
Labels: P3, merge ready, target: patch

#24272 docs(material/datepicker): luxon link
  src/material/datepicker/datepicker.md
Labels: docs, merge ready, merge safe, target: patch

#24274 docs(material): fix 2 spelling errors
  src/material/progress-bar/progress-bar.md
  src/material/progress-spinner/progress-spinner.md
Labels: merge ready, merge safe, target: patch

#24286 release: update version to 14.0.0-next.0
  package.json
Labels: merge ready, merge safe, target: minor

#24291 perf(material-experimental/mdc-list): reduce bundle size
  src/material-experimental/mdc-checkbox/BUILD.bazel
  src/material-experimental/mdc-checkbox/_checkbox-private.scss
  src/material-experimental/mdc-checkbox/_checkbox-theme.scss
  src/material-experimental/mdc-checkbox/checkbox.scss
  src/material-experimental/mdc-list/_list-option-theme.scss
  src/material-experimental/mdc-list/_list-option-trailing-avatar-compat.scss
  src/material-experimental/mdc-list/_list-theme.scss
  src/material-experimental/mdc-list/list-option.scss
  src/material-experimental/mdc-list/list.scss
Labels: P2, merge ready, target: patch

#20393 feat(material/tabs): add the ability to keep content inside the DOM while off-screen
  src/components-examples/material/tabs/index.ts
  src/components-examples/material/tabs/tab-group-preserve-content/tab-group-preserve-content-example.html
  src/components-examples/material/tabs/tab-group-preserve-content/tab-group-preserve-content-example.ts
  src/material-experimental/mdc-tabs/tab-body.scss
  src/material-experimental/mdc-tabs/tab-group.html
  src/material-experimental/mdc-tabs/tab-group.spec.ts
  src/material/tabs/tab-body.scss
  src/material/tabs/tab-body.ts
  src/material/tabs/tab-config.ts
  src/material/tabs/tab-group.html
  src/material/tabs/tab-group.spec.ts
  src/material/tabs/tab-group.ts
  src/material/tabs/tabs-animations.ts
  src/material/tabs/tabs.md
  tools/public_api_guard/material/tabs.md
Labels: P3, merge ready, target: minor

#24298 Revert #20393
  src/components-examples/material/tabs/index.ts
  src/components-examples/material/tabs/tab-group-preserve-content/tab-group-preserve-content-example.html
  src/components-examples/material/tabs/tab-group-preserve-content/tab-group-preserve-content-example.ts
  src/material-experimental/mdc-tabs/tab-body.scss
  src/material-experimental/mdc-tabs/tab-group.html
  src/material-experimental/mdc-tabs/tab-group.spec.ts
  src/material/tabs/tab-body.scss
  src/material/tabs/tab-body.ts
  src/material/tabs/tab-config.ts
  src/material/tabs/tab-group.html
  src/material/tabs/tab-group.spec.ts
  src/material/tabs/tab-group.ts
  src/material/tabs/tabs-animations.ts
  src/material/tabs/tabs.md
  tools/public_api_guard/material/tabs.md
Labels: P2, merge ready, merge safe, target: minor

#24296 build: update to latest version of postcss
  package.json
  yarn.lock
Labels: merge ready, merge safe, target: feature branch

#24299 feat(material/tabs): add the ability to keep content inside the DOM while off-screen
  src/components-examples/material/tabs/index.ts
  src/components-examples/material/tabs/tab-group-preserve-content/tab-group-preserve-content-example.html
  src/components-examples/material/tabs/tab-group-preserve-content/tab-group-preserve-content-example.ts
  src/material-experimental/mdc-tabs/tab-body.scss
  src/material-experimental/mdc-tabs/tab-group.html
  src/material-experimental/mdc-tabs/tab-group.spec.ts
  src/material/tabs/tab-body.scss
  src/material/tabs/tab-body.ts
  src/material/tabs/tab-config.ts
  src/material/tabs/tab-group.html
  src/material/tabs/tab-group.spec.ts
  src/material/tabs/tab-group.ts
  src/material/tabs/tabs-animations.ts
  src/material/tabs/tabs.md
  tools/public_api_guard/material/tabs.md
Labels: P2, merge ready, target: minor

#24218 fix(material/slider): Ticks updated wrongly if the max property 0
  src/material/slider/slider.spec.ts
  src/material/slider/slider.ts
Labels: P3, merge ready, target: patch

#24255 fix(material/datepicker): content overflowing when large custom header is provided
  src/material/datepicker/datepicker-content.html
  src/material/datepicker/datepicker-content.scss
Labels: P3, merge ready, target: patch

#24304 refactor(cdk/testing): remove deprecated protractor harness environment from public API
  scripts/check-entry-point-setup.js
  src/cdk/config.bzl
  src/cdk/testing/protractor/README.md
Labels: merge ready, merge safe, target: major, flag: breaking change

#24321 build: ignore integration test sub-projects within renovate
  renovate.json
Labels: merge ready, merge safe, target: patch

#24314 build: bump to angular 13.2 final
  package.json
  yarn.lock
Labels: P3, merge ready, merge safe, target: patch

#24311 build: remove unnecessary dependency on `core-js`
  package.json
  src/dev-app/BUILD.bazel
  src/dev-app/index.html
  src/e2e-app/BUILD.bazel
  src/e2e-app/index.html
  test/karma.conf.js
  yarn.lock
Labels: merge ready, merge safe, target: patch

#24310 build: fix docs-content missing some inherited member description
  tools/dgeni/common/decorators.ts
  tools/dgeni/common/private-docs.ts
  tools/dgeni/common/tags.ts
  tools/dgeni/docs-package.ts
  tools/dgeni/processors/error-unknown-jsdoc-tags.ts
  tools/dgeni/processors/resolve-inherited-docs.ts
Labels: merge ready, merge safe, target: patch

#24307 docs(cdk/testing): Clean up references to the now deprecated ProtractorHarnessEnvironment
  CHANGELOG.md
  guides/using-component-harnesses.md
  src/cdk/testing/protractor/protractor-harness-environment.ts
  src/cdk/testing/test-harnesses.md
Labels: merge ready, merge safe, target: patch

#24306 build: add an action for handling feature requests
  .github/workflows/feature-requests.yml
Labels: merge ready, merge safe, target: patch, area: build

#24316 docs(material/tabs): Update public documentation with new mat-tab-nav-bar/panel guidance
  src/components-examples/material/tabs/index.ts
  src/components-examples/material/tabs/tab-nav-bar-basic/tab-nav-bar-basic-example.html
  src/components-examples/material/tabs/tab-nav-bar-with-panel/tab-nav-bar-with-panel-example.css
  src/components-examples/material/tabs/tab-nav-bar-with-panel/tab-nav-bar-with-panel-example.html
  src/components-examples/material/tabs/tab-nav-bar-with-panel/tab-nav-bar-with-panel-example.ts
  src/dev-app/tabs/tabs-demo.html
  src/material/tabs/tabs.md
Labels: docs, merge ready, merge safe, target: minor

#14640 fix(material/tabs): use buttons for paginator
  src/material/tabs/_tabs-common.scss
  src/material/tabs/tab-nav-bar/tab-nav-bar.html
Labels: P3, merge ready, target: patch

#24249 fix(material-experimental/mdc-button): align outline color with spec
  src/material-experimental/mdc-button/_button-theme.scss
Labels: P3, merge ready, G, target: patch

#23507 fix(cdk/a11y): allow for multiple browser-generated description containers
  src/cdk/a11y/aria-describer/aria-describer.spec.ts
  src/cdk/a11y/aria-describer/aria-describer.ts
  tools/public_api_guard/cdk/a11y.md
Labels: P3, merge ready, target: patch
