Repository angular/components, pull requests merged in 2022-12, with the labels that each got.

#26136 test(material/slider): add disabled harness filter
  src/material/slider/testing/slider-harness-filters.ts
  src/material/slider/testing/slider-harness.spec.ts
  src/material/slider/testing/slider-harness.ts
  tools/public_api_guard/material/slider-testing.md
Labels: action: merge, target: patch

#26137 test(material/autocomplete): add disabled harness filter
  src/material/autocomplete/testing/autocomplete-harness-filters.ts
  src/material/autocomplete/testing/autocomplete-harness.ts
  src/material/autocomplete/testing/shared.spec.ts
  src/material/legacy-autocomplete/testing/autocomplete-harness-filters.ts
  src/material/legacy-autocomplete/testing/autocomplete-harness.ts
  tools/public_api_guard/material/autocomplete-testing.md
  tools/public_api_guard/material/legacy-autocomplete-testing.md
Labels: action: merge, target: patch

#26138 test(material/button): add disabled harness filter
  src/material/button/testing/button-harness-filters.ts
  src/material/button/testing/button-harness.ts
  src/material/button/testing/shared.spec.ts
  src/material/legacy-button/testing/button-harness.ts
  tools/public_api_guard/material/button-testing.md
Labels: action: merge, target: patch

#26139 test(material/button-toggle): add disabled harness filter
  src/material/button-toggle/testing/button-toggle-group-harness-filters.ts
  src/material/button-toggle/testing/button-toggle-group-harness.ts
  src/material/button-toggle/testing/button-toggle-group-shared.spec.ts
  src/material/button-toggle/testing/button-toggle-harness-filters.ts
  src/material/button-toggle/testing/button-toggle-harness.ts
  src/material/button-toggle/testing/button-toggle-shared.spec.ts
  tools/public_api_guard/material/button-toggle-testing.md
Labels: action: merge, target: patch

#26146 fix(material/button): ensure svg icon is centered
  src/material/button/icon-button.scss
Labels: P3, action: merge, target: patch

#26147 perf(material/core): delegate trigger events
  src/material/core/ripple/ripple-event-manager.ts
  src/material/core/ripple/ripple-renderer.ts
  tools/public_api_guard/material/core.md
Labels: P2, action: merge, G, target: patch

#26108 refactor(material/progress-spinner): deprecate MatSpinner
  src/material/progress-spinner/progress-spinner.ts
  tools/public_api_guard/material/progress-spinner.md
Labels: action: merge, target: patch

#26158 fix(material/schematics): update flat button styles class name mapping
  src/material/schematics/ng-generate/mdc-migration/rules/components/button/button-styles.ts
Labels: action: merge, merge safe, target: patch, area: ng-generate

#26155 test(material/checkbox): add disabled harness filter
  src/material/checkbox/testing/checkbox-harness-filters.ts
  src/material/checkbox/testing/checkbox-harness.ts
  src/material/checkbox/testing/shared.spec.ts
  src/material/legacy-checkbox/testing/checkbox-harness.ts
  tools/public_api_guard/material/checkbox-testing.md
Labels: action: merge, target: patch

#26170 doc(material/button): improve button docs & examples
  src/components-examples/material/button/BUILD.bazel
  src/components-examples/material/button/button-types/button-types-example.css
  src/components-examples/material/button/button-types/button-types-example.html
  src/components-examples/material/button/index.ts
  src/material/button/README.md
  src/material/button/button.md
Labels: docs, action: merge, merge safe, target: patch, area: docs

#26165 fix(material/list): remove previously removed API
  src/material/list/selection-list.ts
  tools/public_api_guard/material/list.md
Labels: P3, action: merge, target: patch

#26171 fix(material/chips): set correct cursor on interactive chips
  src/material/chips/chip-action.ts
Labels: P3, action: merge, target: patch

#26135 refactor(cdk/drag-drop): convert all directives to standalone
  src/cdk/drag-drop/directives/drag-handle.ts
  src/cdk/drag-drop/directives/drag-placeholder.ts
  src/cdk/drag-drop/directives/drag-preview.ts
  src/cdk/drag-drop/directives/drag.ts
  src/cdk/drag-drop/directives/drop-list-group.ts
  src/cdk/drag-drop/directives/drop-list.ts
  src/cdk/drag-drop/drag-drop-module.ts
  tools/public_api_guard/cdk/drag-drop.md
Labels: P3, action: merge, target: patch

#26174 fix(cdk/listbox): set initial focus to selected option
  src/cdk/listbox/listbox.spec.ts
  src/cdk/listbox/listbox.ts
  tools/public_api_guard/cdk/listbox.md
Labels: P3, action: merge, target: patch

#26157 fix(material/dialog): change width to not cut off form field in component example
  src/components-examples/material/dialog/dialog-overview/dialog-overview-example.ts
Labels: action: merge, merge safe, target: patch, area: material/dialog

#26186 perf(material/tabs): reduce amount of CSS generated for background color
  src/components-examples/material/tabs/tab-group-theme/tab-group-theme-example.html
  src/material/tabs/_tabs-common.scss
  src/material/tabs/_tabs-theme.scss
  src/material/tabs/tab-group.scss
  src/material/tabs/tab-group.ts
  src/material/tabs/tab-nav-bar/tab-nav-bar.scss
  src/material/tabs/tab-nav-bar/tab-nav-bar.ts
Labels: P3, action: merge, target: patch

#26053 fix(material/tabs): icons not centered inside tab
  src/material/tabs/_tabs-common.scss
Labels: P3, action: merge, target: patch

#26206 docs: release notes for the v15.0.2 release
  CHANGELOG.md
Labels: action: merge, area: docs

#26212 fix(material/tabs): allow both foreground and background colors to be set
  src/material/tabs/_tabs-common.scss
Labels: P2, action: merge, G, target: patch

#26105 fix(material/chips): implement ariaDescription with aria-describedby
  src/material/chips/chip-option.html
  src/material/chips/chip-option.spec.ts
  src/material/chips/chip-row.html
  src/material/chips/chip-row.spec.ts
  src/material/chips/chip.ts
  tools/public_api_guard/material/chips.md
Labels: a11y, action: merge, target: minor, area: material/chips

#26228 docs: update what we're working on
  README.md
Labels: action: merge, target: patch, area: docs

#26234 fix(material/schematics): fix transform for FloatLabelType
  src/material/schematics/ng-update/migrations/legacy-components-v15/constants.ts
Labels: P3, action: merge, target: patch, merge safe

#26151 test(material/slider): add slider dialog demo
  src/dev-app/slider/BUILD.bazel
  src/dev-app/slider/slider-demo.html
  src/dev-app/slider/slider-demo.scss
  src/dev-app/slider/slider-demo.ts
Labels: action: merge, target: patch

#26169 fix(material/schematics): fix card tmpl migration
  src/material/schematics/ng-generate/mdc-migration/rules/tree-traversal.spec.ts
  src/material/schematics/ng-generate/mdc-migration/rules/tree-traversal.ts
Labels: action: merge, target: patch

#26239 fix(cdk/stepper): set focus origin when navigating with keyboard
  src/cdk/stepper/stepper.ts
Labels: action: merge, P4, target: patch

#26215 fix(material/slider): avoid manual fixing values on pointer up
  src/material/slider/slider-input.ts
  tools/public_api_guard/material/slider.md
Labels: action: merge, target: patch

#26260 fix(material/core): better handling of css variables in theme palettes
  src/material/card/_card-theme.scss
  src/material/chips/_chips-theme.scss
  src/material/core/mdc-helpers/_mdc-helpers.scss
  src/material/core/theming/tests/test-css-variables-theme.scss
  src/material/form-field/_mdc-text-field-theme-variable-refresh.scss
  src/material/progress-bar/_progress-bar-theme.scss
  src/material/snack-bar/_snack-bar-theme.scss
Labels: P2, action: merge, target: patch

#26265 docs: release notes for the v15.0.3 release
  CHANGELOG.md
Labels: area: docs

#26274 build: update renovate to not apply `merge safe` label
  renovate.json
Labels: action: merge, target: patch, area: build & ci

#26268 fix(material/snack-bar): set explicit color on action in dark themes
  src/material/snack-bar/_snack-bar-theme.scss
Labels: P3, action: merge, target: patch

#26275 fix(material-experimental/popover-edit): Make cell focus indicator vi…
  src/material-experimental/popover-edit/_popover-edit-theme.scss
Labels: action: merge, target: patch

#26298 docs: fix invalid SCSS in migration guide
  guides/v15-mdc-migration.md
Labels: action: merge, target: patch, area: docs

#26283 fix(material/list): add opt-out for radio indicators
  src/dev-app/list/list-demo.html
  src/dev-app/list/list-demo.ts
  src/material/list/_interactive-list-theme.scss
  src/material/list/list-base.ts
  src/material/list/list-option.ts
  src/material/list/public-api.ts
  src/material/list/selection-list.spec.ts
  src/material/list/selection-list.ts
  src/material/list/tokens.ts
  tools/public_api_guard/material/list.md
Labels: a11y, action: merge, target: minor, area: material/list

#26322 fix(material/slider): avoid updating tick marks unnecessarily
  src/material/slider/slider.ts
Labels: action: merge, target: patch
