Repository angular/components, pull requests merged in 2023-12, with the labels that each got.

#28221 docs: release notes for the v17.0.2 release
  CHANGELOG.md
Labels: area: docs

#28234 fix(material/datepicker): fix create control value when null
  src/components-examples/material/datepicker/datepicker-views-selection/datepicker-views-selection-example.ts
Labels: docs, action: merge, target: patch, merge: fix commit message

#28193 fix(material/slider): fix tick mark precision
  src/material/slider/slider-input.ts
  src/material/slider/slider.spec.ts
  src/material/slider/slider.ts
Labels: action: merge, target: patch

#28236 fix(multiple): consolidate and tokenize internal form field
  .github/CODEOWNERS
  src/material/checkbox/_checkbox-theme.scss
  src/material/checkbox/checkbox.html
  src/material/checkbox/checkbox.scss
  src/material/checkbox/checkbox.ts
  src/material/core/BUILD.bazel
  src/material/core/internal-form-field/_internal-form-field-theme.scss
  src/material/core/internal-form-field/internal-form-field.scss
  src/material/core/internal-form-field/internal-form-field.ts
  src/material/core/public-api.ts
  src/material/core/tokens/m2/mdc/_form-field.scss
  src/material/core/tokens/tests/test-validate-tokens.scss
  src/material/radio/_radio-theme.scss
  src/material/radio/radio.html
  src/material/radio/radio.scss
  src/material/radio/radio.ts
  src/material/slide-toggle/_slide-toggle-theme.scss
  src/material/slide-toggle/slide-toggle.html
  src/material/slide-toggle/slide-toggle.scss
  src/material/slide-toggle/slide-toggle.ts
  tools/public_api_guard/material/core.md
  tools/public_api_guard/material/radio.md
Labels: P3, action: merge, target: minor

#28247 docs: release notes for the v17.0.3 release
  CHANGELOG.md
Labels: area: docs

#27999 refactor(material/button): switch typography to tokens
  src/material/button/_button-theme.scss
  src/material/button/button.scss
  src/material/core/tokens/m2/mdc/_filled-button.scss
  src/material/core/tokens/m2/mdc/_outlined-button.scss
  src/material/core/tokens/m2/mdc/_protected-button.scss
  src/material/core/tokens/m2/mdc/_text-button.scss
Labels: action: merge, target: patch

#28260 fix(material/chips): enable hydration
  src/material/chips/chip-listbox.ts
  src/universal-app/kitchen-sink/kitchen-sink.html
Labels: P3, action: merge, target: patch

#28256 FIX: Example of mat-tabs deletion is showing wrong index
  src/components-examples/material/tabs/tab-group-dynamic/tab-group-dynamic-example.ts
Labels: docs, action: merge, target: patch, merge: fix commit message

#28262 fix(material/tabs): deprecate backgroundColor API
  src/material/tabs/tab-group.ts
  tools/public_api_guard/material/tabs.md
Labels: action: merge, target: patch

#28242 feat(material/button): add the ability to interact with disabled buttons
  src/components-examples/material/button/button-disabled-interactive/button-disabled-interactive-example.css
  src/components-examples/material/button/button-disabled-interactive/button-disabled-interactive-example.html
  src/components-examples/material/button/button-disabled-interactive/button-disabled-interactive-example.ts
  src/components-examples/material/button/index.ts
  src/dev-app/button/BUILD.bazel
  src/dev-app/button/button-demo.html
  src/dev-app/button/button-demo.ts
  src/material/button/_button-base.scss
  src/material/button/button-base.ts
  src/material/button/button.md
  src/material/button/button.scss
  src/material/button/button.spec.ts
  src/material/button/fab.scss
  src/material/button/public-api.ts
  src/material/button/testing/button-harness.ts
  src/material/core/tokens/m2/mat/_fab.scss
  src/material/core/tokens/m2/mat/_filled-button.scss
  src/material/core/tokens/m2/mat/_icon-button.scss
  src/material/core/tokens/m2/mat/_outlined-button.scss
  src/material/core/tokens/m2/mat/_protected-button.scss
  src/material/core/tokens/m2/mat/_text-button.scss
  tools/public_api_guard/material/button.md
Labels: P2, action: merge, G, target: minor, detected: feature

#28249 refactor(material/form-field): tokenize density overrides
  src/material/core/tokens/m2/mat/_form-field.scss
  src/material/form-field/BUILD.bazel
  src/material/form-field/_form-field-density.scss
  src/material/form-field/_form-field-sizing.scss
  src/material/form-field/_form-field-subscript.scss
  src/material/form-field/_form-field-theme.scss
  src/material/form-field/_mdc-text-field-density-overrides.scss
  src/material/form-field/form-field.scss
  src/material/paginator/BUILD.bazel
  src/material/paginator/_paginator-theme.scss
Labels: P3, action: merge, target: patch

#28244 fix(material/tabs): add header divider for m3
  src/dev-app/tabs/tabs-demo.html
  src/material-experimental/theming/_custom-tokens.scss
  src/material/core/tokens/m2/mat/_tab-header.scss
  src/material/tabs/_tabs-common.scss
  src/material/tabs/tab-header.scss
Labels: action: merge, target: patch

#28269 Revert "refactor(material/form-field): tokenize density overrides (#28249)"
  src/material/core/tokens/m2/mat/_form-field.scss
  src/material/form-field/BUILD.bazel
  src/material/form-field/_form-field-density.scss
  src/material/form-field/_form-field-sizing.scss
  src/material/form-field/_form-field-subscript.scss
  src/material/form-field/_form-field-theme.scss
  src/material/form-field/_mdc-text-field-density-overrides.scss
  src/material/form-field/form-field.scss
  src/material/paginator/BUILD.bazel
  src/material/paginator/_paginator-theme.scss
Labels: action: merge, target: patch

#28277 docs: release notes for the v17.0.4 release
  CHANGELOG.md
Labels: area: docs

#28273 refactor(material/form-field): tokenize density overrides
  src/material/core/tokens/m2/mat/_form-field.scss
  src/material/form-field/BUILD.bazel
  src/material/form-field/_form-field-density.scss
  src/material/form-field/_form-field-sizing.scss
  src/material/form-field/_form-field-subscript.scss
  src/material/form-field/_form-field-theme.scss
  src/material/form-field/_mdc-text-field-density-overrides.scss
  src/material/form-field/form-field.scss
  src/material/paginator/BUILD.bazel
  src/material/paginator/_paginator-theme.scss
Labels: P3, action: merge, target: patch

#28250 fix(material/slider): fix value indicator bubble for m3
  src/material-experimental/theming/_custom-tokens.scss
  src/material/core/tokens/m2/mat/_slider.scss
  src/material/slider/_slider-theme.scss
  src/material/slider/slider.scss
  yarn.lock
Labels: action: merge, target: patch, dev-app preview

#28285 fix(material/paginator): match visual and reading order
  src/material/paginator/paginator.scss
Labels: a11y, action: merge, merge: caretaker note, target: minor, area: material/paginator

#28281 refactor(material/core): switch app background to tokens theming API
  src/material/core/_core-theme.scss
  src/material/core/_core.scss
  src/material/core/tokens/m2/mat/_app.scss
Labels: P3, action: merge, target: minor

#28287 fix(material/select): flicker if opened from inside a focus handler
  src/material/select/select.html
  src/material/select/select.ts
Labels: action: merge, P4, target: patch

#28282 refactor(material-experimental/theming): Remove theming-next directory
  .github/CODEOWNERS
  .ng-dev/commit-message.mts
  src/material-experimental/BUILD.bazel
  src/material-experimental/theming-next/BUILD.bazel
  src/material-experimental/theming-next/README.md
  src/material-experimental/theming-next/_card.scss
  src/material-experimental/theming-next/_checkbox.scss
  src/material-experimental/theming-next/_m3-tokens.scss
  src/material-experimental/theming-next/_theming.scss
  src/material-experimental/theming-next/_token-resolution.scss
Labels: action: merge, target: patch

#28295 Add support for density to M3 form field
  src/dev-app/dev-app/dev-app-layout.ts
  src/dev-app/theme.scss
  src/material-experimental/theming/_m3-density.scss
Labels: P3, action: merge, target: minor, area: build & ci

#28284 docs(material/list): fix grammer in MAT_LIST_CONFIG token description
  src/material/list/tokens.ts
Labels: action: merge, target: patch, merge: fix commit message, area: docs

#28310 refactor(material/expansion): remove incorrect `inputs` overrides
  src/material/expansion/accordion.ts
  src/material/expansion/expansion-panel.ts
  tools/public_api_guard/material/expansion.md
Labels: action: merge, target: minor

#28311 refactor(multiple): remove unnecessary inputs and outputs metadata
  src/material/slide-toggle/slide-toggle.ts
  src/material/stepper/stepper-button.ts
  src/material/stepper/stepper.ts
  src/material/tabs/paginated-tab-header.ts
  src/material/tabs/tab-header.ts
  src/material/tabs/tab-nav-bar/tab-nav-bar.ts
  tools/public_api_guard/material/slide-toggle.md
  tools/public_api_guard/material/stepper.md
  tools/public_api_guard/material/tabs.md
Labels: P3, action: merge, target: minor

#28315 Fix M3 form field disabled state and shape
  src/material-experimental/theming/_m3-tokens.scss
Labels: action: merge, target: minor, merge: preserve commits

#28316 fix(material/autocomplete): not closing when clicking on hint area
  src/material/autocomplete/autocomplete-trigger.ts
Labels: P3, action: merge, target: patch

#28140 docs(material/list): Fix code example formatting
  src/components-examples/material/list/list-variants/list-variants-example.html
Labels: action: merge, target: patch

#28324 refactor(material/core): remove MDC theme patches
  src/material/_index.scss
  src/material/core/mdc-helpers/_mdc-helpers.scss
  src/material/slide-toggle/_slide-toggle-theme.scss
Labels: P3, action: merge, target: minor

#28325 refactor(multiple): remove references to deprecated ClientRect
  src/cdk/drag-drop/directives/drag.spec.ts
  src/cdk/drag-drop/directives/drag.ts
  src/cdk/drag-drop/dom/dom-rect.ts
  src/cdk/drag-drop/dom/parent-position-tracker.ts
  src/cdk/drag-drop/drag-ref.ts
  src/cdk/drag-drop/drop-list-ref.ts
  src/cdk/drag-drop/sorting/single-axis-sort-strategy.ts
  src/cdk/overlay/position/flexible-connected-position-strategy.spec.ts
  src/cdk/overlay/position/flexible-connected-position-strategy.ts
  src/cdk/overlay/position/scroll-clip.ts
  src/cdk/scrolling/viewport-ruler.ts
  src/cdk/scrolling/virtual-scrollable.ts
  src/dev-app/drag-drop/drag-drop-demo.ts
  src/material/core/ripple/ripple-renderer.ts
  src/material/tabs/ink-bar.ts
  tools/public_api_guard/cdk/drag-drop.md
Labels: action: merge, P4, target: patch

#28339 fix(material/chip-set): fixed chips-avatar-example
  src/components-examples/material/chips/chips-avatar/chips-avatar-example.html
Labels: docs, action: merge, target: patch, merge: fix commit message

#28342 fix(material/schematics): schema error in mdc migration
  src/material/schematics/ng-generate/mdc-migration/schema.json
Labels: P2, action: merge, target: patch
