Repository angular/components, pull requests merged in 2023-10, with the labels that each got.

#27864 fix(material/radio): Apply tokens at mixin root
  src/material/list/_list-theme.scss
  src/material/radio/_radio-theme.scss
Labels: action: merge, target: major

#27865 feat(material/theming): Open up new APIs to access theme values
  src/material-experimental/column-resize/_column-resize-theme.scss
  src/material-experimental/popover-edit/_popover-edit-theme.scss
  src/material/_index.scss
  src/material/core/theming/tests/theming-inspection-api.spec.ts
Labels: action: merge, target: major, detected: feature

#27663 Toggle aria-modal attribute in parent modal when autocomplete panel opens / closes
  src/material/autocomplete/autocomplete-trigger.ts
  src/material/autocomplete/autocomplete.spec.ts
Labels: action: merge, target: patch

#27876 build: fix lint failure
  src/material/autocomplete/autocomplete.spec.ts
Labels: P3, action: merge, target: patch, area: build & ci

#27868 feat(material-experimental/theming): add M3 progress-spinner support
  src/dev-app/BUILD.bazel
  src/dev-app/dev-app/dev-app-layout.html
  src/dev-app/dev-app/dev-app-layout.ts
  src/dev-app/dev-app/dev-app-state.ts
  src/dev-app/main.ts
  src/dev-app/theme-m3.scss
  src/material-experimental/theming-next/README.md
  src/material-experimental/theming/_m3-tokens.scss
  src/material/progress-spinner/_progress-spinner-theme.scss
Labels: action: merge, target: major, area: build & ci, dev-app preview, detected: feature

#27867 feat(material-experimental/theming): add M3 radio support
  src/dev-app/theme-m3.scss
  src/material-experimental/theming/_custom-tokens.scss
  src/material-experimental/theming/_m3-density.scss
  src/material-experimental/theming/_m3-tokens.scss
  src/material/radio/_radio-theme.scss
Labels: action: merge, target: major, dev-app preview, detected: feature

#27875 fix(cdk/schematics): support both application and browser builders
  src/cdk/schematics/utils/project-index-file.ts
  src/cdk/schematics/utils/project-main-file.ts
  src/cdk/schematics/utils/project-targets.ts
  src/material/schematics/ng-add/index.spec.ts
  src/material/schematics/ng-add/theming/theming.ts
Labels: P2, action: merge, target: major

#27900 docs: release notes for the v16.2.7 release
  CHANGELOG.md
Labels: area: docs

#27893 refactor(multiple): Add base mixin for components with no base tokens
  src/material/_index.scss
  src/material/autocomplete/_autocomplete-theme.scss
  src/material/badge/_badge-theme.scss
  src/material/core/option/_optgroup-theme.scss
  src/material/core/option/_option-theme.scss
  src/material/datepicker/_datepicker-theme.scss
  src/material/grid-list/_grid-list-theme.scss
  src/material/icon/_icon-theme.scss
  src/material/input/_input-theme.scss
  src/material/paginator/_paginator-theme.scss
  src/material/select/_select-theme.scss
  src/material/stepper/_stepper-theme.scss
  src/material/toolbar/_toolbar-theme.scss
Labels: action: merge, target: major

#27880 feat(material-experimental/theming): add M3 progress bar support
  src/dev-app/theme-m3.scss
  src/material-experimental/theming/_custom-tokens.scss
  src/material-experimental/theming/_m3-density.scss
  src/material-experimental/theming/_m3-tokens.scss
  src/material/progress-bar/_progress-bar-theme.scss
Labels: action: merge, target: major, dev-app preview, detected: feature

#27866 refactor(material/button): switch raised-button to density tokens
  src/material/button/_button-theme.scss
  src/material/core/tokens/m2/mdc/_button-protected.scss
Labels: action: merge, target: major

#27898 fix(material/theming): Fix subtle bug in current-selector-or-root
  src/material/core/style/_sass-utils.scss
  src/material/core/theming/tests/theming-mixin-api.spec.ts
Labels: action: merge, target: major

#27888 fix(material/menu): move unthemable tokens to theme mixin
  src/material/_index.scss
  src/material/menu/_menu-theme.scss
  src/material/menu/menu.scss
Labels: action: merge, target: major, detected: breaking change

#27889 fix(material/sidenav): move unthemable tokens to theme mixin
  src/material/_index.scss
  src/material/sidenav/_sidenav-theme.scss
  src/material/sidenav/drawer.scss
Labels: action: merge, target: major, detected: breaking change

#27890 fix(material/table): move unthemable tokens to theme mixin
  src/material/_index.scss
  src/material/table/_table-theme.scss
  src/material/table/table.scss
Labels: action: merge, target: major, detected: breaking change

#27907 fix: ci lint failure
  src/material/_index.scss
Labels: action: merge, target: major, area: build & ci

#27882 fix(material/bottom-sheet): move unthemable tokens to theme mixin
  src/material/_index.scss
  src/material/bottom-sheet/_bottom-sheet-theme.scss
  src/material/bottom-sheet/bottom-sheet-container.scss
Labels: action: merge, target: major, detected: breaking change

#27904 fix(material/button): fix color tokens of raised buttons
  src/material/button/_button-theme.scss
  src/material/core/tokens/m2/mdc/_button-protected.scss
Labels: action: merge, target: major

#27903 docs(material/form-field): use correct input color in custom control example
  src/components-examples/material/form-field/form-field-custom-control/example-tel-input-example.css
Labels: action: merge, target: patch, area: docs

#27894 docs(material/toolbar): fix indentation in example
  src/components-examples/material/toolbar/toolbar-overview/toolbar-overview-example.html
Labels: action: merge, target: patch, area: docs

#27797 refactor(material/button): switch flat-button to density tokens
  src/material/button/_button-theme.scss
  src/material/core/tokens/m2/mdc/_button-filled.scss
  src/material/core/tokens/tests/test-validate-tokens.scss
Labels: action: merge, target: major

#27884 fix(material/chips): move unthemable tokens to theme mixin
  src/material/_index.scss
  src/material/chips/_chips-theme.scss
  src/material/chips/chip.scss
Labels: action: merge, target: major, detected: breaking change

#27850 remove subscription for expandAll and collapseAll
  src/cdk/tree/tree.ts
  src/material/tree/testing/tree-harness.spec.ts
Labels: area: cdk/tree, dev-app preview

#27886 ci: migrate saucelabs and browserstack tests to GHA
  .circleci/config.yml
  .github/angular-robot.yml
  .github/workflows/ci-privileged.yml
  scripts/saucelabs/start-tunnel.sh
  test/karma.conf.js
Labels: action: merge, target: patch, area: build & ci

#27891 fix(material/tabs): move unthemable tokens to theme mixin
  src/material/_index.scss
  src/material/tabs/_tabs-common.scss
  src/material/tabs/_tabs-theme.scss
Labels: action: merge, target: major, detected: breaking change

#27883 fix(material/button-toggle): move unthemable tokens to theme mixin
  src/material/_index.scss
  src/material/button-toggle/_button-toggle-theme.scss
  src/material/button-toggle/button-toggle.scss
Labels: action: merge, target: major, detected: breaking change

#27905 fix(material/slide-toggle): move unthemable tokens to theme mixin
  src/material/_index.scss
  src/material/slide-toggle/_slide-toggle-theme.scss
  src/material/slide-toggle/slide-toggle.scss
Labels: action: merge, target: major, detected: breaking change

#27926 feat(material/snack-bar): convert to standalone
  src/dev-app/snack-bar/snack-bar-demo.ts
  src/material/snack-bar/module.ts
  src/material/snack-bar/simple-snack-bar.ts
  src/material/snack-bar/snack-bar-container.ts
  src/material/snack-bar/snack-bar-content.ts
  src/material/snack-bar/snack-bar.ts
  tools/public_api_guard/material/snack-bar.md
Labels: P3, action: merge, target: major, detected: feature

#27806 fix(material/button): Emit fab tokens under mixin root selector
  src/material/button/_fab-theme.scss
Labels: action: merge, target: major, area: material/button

#27830 fix(material/dialog): Emit tokens under mixin root selector
  src/material/dialog/_dialog-theme.scss
Labels: action: merge, target: major, area: material/dialog

#27597 fix(material/slider): Emit tokens under mixin root selector
  src/material/slider/_slider-theme.scss
Labels: action: merge, target: major, area: material/slider

#27924 feat(material/theming): Add 'base' theming dimension to all components
  src/material/_index.scss
  src/material/button/_button-theme.scss
  src/material/button/_icon-button-theme.scss
  src/material/core/_core-theme.scss
  src/material/core/ripple/_ripple-theme.scss
  src/material/core/selection/pseudo-checkbox/_pseudo-checkbox-theme.scss
  src/material/core/theming/_all-theme.scss
  src/material/divider/_divider-theme.scss
  src/material/expansion/_expansion-theme.scss
  src/material/form-field/_form-field-theme.scss
  src/material/sort/_sort-theme.scss
  src/material/tree/_tree-theme.scss
Labels: action: merge, target: major, detected: feature, detected: breaking change

#27929 docs: release notes for the v16.2.8 release
  CHANGELOG.md
Labels: area: docs

#27936 fix(material/button): align prefixes with MDC
  src/material/button/_button-theme.scss
  src/material/button/button.scss
  src/material/core/tokens/m2/mdc/_filled-button.scss
  src/material/core/tokens/m2/mdc/_protected-button.scss
  src/material/core/tokens/tests/test-validate-tokens.scss
Labels: P3, action: merge, target: rc

#27885 fix(material/expansion): move unthemable tokens to theme mixin
  src/material/expansion/_expansion-theme.scss
  src/material/expansion/expansion-panel.scss
Labels: action: merge, target: rc

#27948 fix(material/button): buttons in toolbars
  src/material/toolbar/toolbar.scss
Labels: action: merge, target: patch

#27944 docs(cdk/a11y): add example of LiveAnnouncer inside dialog
  src/dev-app/live-announcer/BUILD.bazel
  src/dev-app/live-announcer/live-announcer-demo.html
  src/dev-app/live-announcer/live-announcer-demo.ts
Labels: a11y, docs, action: merge, target: patch, area: cdk/a11y, area: docs

#27945 build: switch kitchen sink to standalone
  src/universal-app/BUILD.bazel
  src/universal-app/index.html
  src/universal-app/kitchen-sink-root.ts
  src/universal-app/kitchen-sink/kitchen-sink.ts
  src/universal-app/main.ts
  src/universal-app/prerender.ts
Labels: action: merge, P4, area: build & ci, target: rc

#27951 refactor(youtube-player): simplify component internals
  src/youtube-player/youtube-player.ts
  tools/public_api_guard/youtube-player/youtube-player.md
Labels: P3, action: merge, target: rc

#27939 feat(cdk/tree): add caveats for a11y support with `treeControl`, also document `isExpandable`
  src/cdk/tree/tree.md
  src/material/tree/tree.md
Labels: detected: feature

#27954 refactor(material/button): clean up margin reset
  src/material/button/_button-theme.scss
Labels: P3, action: merge, target: rc

#27960 docs: release notes for the v17.0.0-rc.0 release
  CHANGELOG.md
Labels: area: docs

#27881 fix(material/divider): move unthemable tokens to theme mixin
  src/material/divider/_divider-theme.scss
  src/material/divider/divider.scss
Labels: action: merge, target: rc

#27949 Minor optimizations to button-base
  src/material/button/button-base.ts
Labels: action: merge, merge: fix commit message, target: rc

#27963 refactor(material/sort): switch to token theming API
  src/material/core/tokens/m2/mat/_sort.scss
  src/material/sort/_sort-theme.scss
  src/material/sort/sort-header.scss
Labels: P3, action: merge, target: rc

#27966 ci: fix environment variables
  .github/workflows/ci.yml
Labels: action: merge, target: patch, area: build & ci

#27964 fix(material/schematics): Create a schematic to add the base theme dimension
  src/material/_index.scss
  src/material/schematics/ng-update/index.ts
  src/material/schematics/ng-update/migrations/theme-base-v17/index.ts
  src/material/schematics/ng-update/migrations/theme-base-v17/migration.ts
  src/material/schematics/ng-update/test-cases/theme-base.spec.ts
Labels: action: merge, target: rc

#27977 build: update to Angular v17 RC
  package.json
  src/dev-app/input/input-demo.html
  yarn.lock
Labels: P3, action: merge, area: build & ci, target: rc

#27887 fix(material/form-field): move unthemable tokens to theme mixin
  src/material/form-field/_form-field-theme.scss
  src/material/form-field/form-field.scss
Labels: action: merge, target: rc

#27570 fix(material/button): Move unthemable icon button tokens to theme mixin
  src/material/button/_icon-button-theme.scss
  src/material/button/icon-button.scss
Labels: action: merge, target: minor, area: material/button

#27970 fix(material/checkbox): add aria-checked
  src/material/checkbox/checkbox.html
  src/material/checkbox/checkbox.spec.ts
Labels: action: merge, target: patch

#27906 refactor(material/button): switch outlined button to tokens theming API
  src/material/button/_button-theme.scss
  src/material/button/button.scss
  src/material/core/tokens/m2/mdc/_outlined-button.scss
  src/material/core/tokens/tests/test-validate-tokens.scss
Labels: action: merge, target: minor

#27987 perf(multiple): switch to built-in control flow
  src/cdk-experimental/selection/selection-column.ts
  src/material-experimental/selection/selection-column.ts
  src/material/chips/BUILD.bazel
  src/material/chips/chip-option.html
  src/material/chips/chip-row.html
  src/material/chips/chip.html
  src/material/chips/module.ts
  src/material/core/BUILD.bazel
  src/material/core/option/index.ts
  src/material/core/option/option.html
  src/material/datepicker/calendar-body.html
  src/material/datepicker/calendar.html
  src/material/datepicker/datepicker-toggle.html
  src/material/datepicker/month-view.html
  src/material/expansion/BUILD.bazel
  src/material/expansion/expansion-module.ts
  src/material/expansion/expansion-panel-header.html
  src/material/form-field/form-field.html
  src/material/list/list-option.html
  src/material/menu/menu-item.html
  src/material/paginator/BUILD.bazel
  src/material/paginator/module.ts
  src/material/paginator/paginator.html
  src/material/select/select.html
  src/material/sidenav/BUILD.bazel
  src/material/sidenav/drawer-container.html
  src/material/sidenav/sidenav-container.html
  src/material/sidenav/sidenav-module.ts
  src/material/slide-toggle/BUILD.bazel
  src/material/slide-toggle/module.ts
  src/material/slide-toggle/slide-toggle.html
  src/material/slider/module.ts
  src/material/slider/slider-thumb.html
  src/material/slider/slider.html
  src/material/snack-bar/simple-snack-bar.html
  src/material/sort/BUILD.bazel
  src/material/sort/sort-header.html
  src/material/sort/sort-module.ts
  src/material/stepper/step-header.html
  src/material/stepper/stepper.html
  src/material/tabs/tab-group.html
  tools/public_api_guard/material/chips.md
  tools/public_api_guard/material/core.md
  tools/public_api_guard/material/expansion.md
  tools/public_api_guard/material/paginator.md
  tools/public_api_guard/material/sidenav.md
  tools/public_api_guard/material/slide-toggle.md
  tools/public_api_guard/material/slider.md
  tools/public_api_guard/material/sort.md
Labels: P3, action: merge, target: rc

#27988 refactor(material/button): handle disabled state of icon buttons through tokens
  src/dev-app/button/button-demo.html
  src/material/button/_icon-button-theme.scss
  src/material/button/icon-button.scss
  src/material/core/tokens/m2/mdc/_icon-button.scss
Labels: P3, action: merge, target: rc

#27990 refactor(material/button): handle disabled state of icon buttons through tokens
  src/dev-app/button/button-demo.html
  src/material/button/_icon-button-theme.scss
  src/material/button/icon-button.scss
  src/material/core/tokens/m2/mdc/_icon-button.scss
Labels: P3, action: merge, target: rc

#27991 ci: provide environment variables to the right step
  .github/workflows/ci.yml
Labels: action: merge, target: patch, area: build & ci

#27996 docs: release notes for the v17.0.0-rc.1 release
  CHANGELOG.md
Labels: area: docs

#27998 docs: release notes for the v16.2.10 release
  CHANGELOG.md
Labels: area: docs

#27994 refactor(material/button): clean up fab tokens
  src/material/button/_fab-theme.scss
  src/material/button/fab.scss
  src/material/core/tokens/m2/mat/_fab.scss
  src/material/core/tokens/m2/mdc/_fab.scss
Labels: P3, action: merge, target: rc

#27986 refactor(material/button): switch outlined-button to density tokens
  src/material/button/_button-theme.scss
  src/material/core/tokens/m2/mdc/_outlined-button.scss
Labels: action: merge, target: minor

#28005 refactor(material/button): handle disabled states through tokens
  src/material/button/_button-base.scss
  src/material/button/_button-theme-private.scss
  src/material/button/_button-theme.scss
  src/material/button/button.scss
  src/material/core/tokens/m2/mdc/_outlined-button.scss
Labels: P3, action: merge, target: rc

#28007 refactor(material/button): handle disabled states through tokens
  src/material/button/_button-base.scss
  src/material/button/_button-theme-private.scss
  src/material/button/_button-theme.scss
  src/material/button/button.scss
  src/material/core/tokens/m2/mdc/_outlined-button.scss
Labels: P3, action: merge, target: rc

#28008 refactor(material/button): fix out of sync file
  src/material/button/_button-theme.scss
Labels: action: merge, target: rc

#28009 ci: provide environment variables to the deploy step
  .github/workflows/ci.yml
Labels: action: merge, target: patch, area: build & ci

#27992 docs(material/theming): Add docs for the new base theming dimension
  guides/theming.md
Labels: docs, action: merge, target: rc, area: docs

#28002 docs(material/theming): Update docs on accessing theme values
  guides/theming-your-components.md
  guides/theming.md
  guides/typography.md
Labels: docs, action: merge, target: rc, area: docs

#28015 docs(material/theming): Fix broken theme guide formatting
  guides/theming.md
  src/material/schematics/ng-update/migrations/theme-base-v17/migration.ts
  src/material/schematics/ng-update/test-cases/theme-base.spec.ts
Labels: docs, action: merge, target: rc, area: docs

#28013 feat(material/chips): expose _chipGrid in MatChipInput and add a stream of chip removal events
  src/material/chips/chip-input.ts
  src/material/chips/chip-set.ts
  tools/public_api_guard/material/chips.md
Labels: action: merge, target: minor, detected: feature

#28018 refactor(material/core): remove unused compatibility code
  src/material/core/density/private/_compatibility.scss
  src/material/core/theming/_theming.scss
Labels: action: merge, P4, target: rc

#28025 fix(material/schematics): account for browser-esbuild builder
  src/cdk/schematics/utils/project-targets.ts
  src/material/schematics/ng-add/index.spec.ts
Labels: P2, action: merge, target: rc

#28026 refactor(schematics): don't add the preconnect for fonts
  src/material/schematics/ng-add/fonts/material-fonts.ts
Labels: action: merge, merge: fix commit message, target: rc

#28027 test(material/schematics): fix failing test
  src/material/schematics/ng-add/index.spec.ts
Labels: P3, action: merge, target: rc

#27981 fix(cdk/accordion): add `CDK_ACCORDION` export
  src/cdk/accordion/public-api.ts
  tools/public_api_guard/cdk/accordion.md
Labels: action: merge, target: patch
