Repository angular/components, pull requests merged in 2023-08, with the labels that each got.

#27542 docs: fix typo error in ink-bar.ts
  src/material/tabs/ink-bar.ts
Labels: action: merge, target: patch, area: docs

#27543 refactor(multiple): align letter spacing terminology
  src/material/core/tokens/m2/mat/_slide-toggle.scss
  src/material/core/tokens/m2/mat/_tab-header.scss
  src/material/slide-toggle/slide-toggle.scss
  src/material/tabs/_tabs-common.scss
Labels: P3, action: merge, target: minor

#27554 docs: improved the docs
  CHANGELOG_ARCHIVE.md
  DEV_ENVIRONMENT.md
  src/cdk/stepper/stepper.md
Labels: action: merge, target: patch, area: docs

#27558 docs: improve the spec file by removing duplicate word
  src/cdk/portal/portal.spec.ts
Labels: action: merge, target: patch, area: docs

#27548 refactor(material/form-field): switch to tokens theming API
  src/material/core/tokens/m2/mat/_form-field.scss
  src/material/core/tokens/m2/mdc/_filled-text-field.scss
  src/material/core/tokens/m2/mdc/_outlined-text-field.scss
  src/material/form-field/_form-field-theme.scss
  src/material/form-field/_mdc-text-field-structure-overrides.scss
  src/material/form-field/form-field.scss
Labels: P3, action: merge, target: minor

#27565 docs: release notes for the v16.1.7 release
  CHANGELOG.md
Labels: area: docs

#27375 fix(material/slider): change slider to use MDC's token API
  src/material/core/tokens/m2/mat/_slider.scss
  src/material/core/tokens/m2/mdc/_slider.scss
  src/material/core/tokens/tests/test-validate-tokens.scss
  src/material/slider/_slider-theme.scss
  src/material/slider/slider.scss
Labels: action: merge, target: minor, area: material/slider

#27572 fix(material/autocomplete): don't assign to model value while typing when requireSelection is enabled
  src/components-examples/material/autocomplete/autocomplete-require-selection/autocomplete-require-selection-example.css
  src/components-examples/material/autocomplete/autocomplete-require-selection/autocomplete-require-selection-example.html
  src/components-examples/material/autocomplete/autocomplete-require-selection/autocomplete-require-selection-example.ts
  src/dev-app/autocomplete/autocomplete-demo.html
  src/dev-app/autocomplete/autocomplete-demo.ts
  src/material/autocomplete/autocomplete-trigger.ts
  src/material/autocomplete/autocomplete.spec.ts
Labels: P2, action: merge, target: rc

#27559 fix(material/chips): focus lingering on previous chip
  src/material/chips/chip-option.ts
Labels: P3, action: merge, target: patch

#27546 fix(material/slider): match active & focus state on IOS
  src/material/slider/slider-input.ts
  src/material/slider/slider-interface.ts
  src/material/slider/slider-thumb.ts
  src/material/slider/slider.spec.ts
  src/material/slider/slider.ts
  tools/public_api_guard/material/slider.md
Labels: action: merge, target: patch

#27556 fix(material/checkbox): Move unthemable tokens to theme mixin
  src/material/_index.scss
  src/material/checkbox/_checkbox-theme.scss
  src/material/checkbox/checkbox.scss
Labels: action: merge, target: major, detected: breaking change

#27581 refactor(material/form-field): switch color styles to tokens
  src/material/core/tokens/m2/mat/_form-field.scss
  src/material/core/tokens/m2/mdc/_filled-text-field.scss
  src/material/core/tokens/m2/mdc/_outlined-text-field.scss
  src/material/form-field/BUILD.bazel
  src/material/form-field/_form-field-focus-overlay.scss
  src/material/form-field/_form-field-native-select.scss
  src/material/form-field/_form-field-subscript.scss
  src/material/form-field/_form-field-theme.scss
  src/material/form-field/_mdc-text-field-structure-overrides.scss
  src/material/form-field/_mdc-text-field-theme-variable-refresh.scss
  src/material/form-field/form-field.scss
Labels: P3, action: merge, target: rc

#27563 fix(material/progress-bar): Move unthemable tokens to theme mixin
  src/material/_index.scss
  src/material/progress-bar/_progress-bar-theme.scss
  src/material/progress-bar/progress-bar.scss
Labels: action: merge, target: major, detected: breaking change

#27569 fix(material/tooltip): Move unthemable tokens to theme mixin
  src/material/_index.scss
  src/material/tooltip/_tooltip-theme.scss
  src/material/tooltip/tooltip.scss
Labels: action: merge, target: major, detected: breaking change

#27567 fix(material/progress-spinner): Move unthemable tokens to theme mixin
  src/material/_index.scss
  src/material/progress-spinner/_progress-spinner-theme.scss
  src/material/progress-spinner/progress-spinner.scss
Labels: action: merge, target: major, detected: breaking change

#27579 fix(material/card): Move unthemable tokens to theme mixin
  src/material/_index.scss
  src/material/card/_card-theme.scss
  src/material/card/card.scss
Labels: action: merge, target: major, detected: breaking change

#27588 fix(youtube-player): Allow playlists without specifying videoId (#27529)
  src/dev-app/youtube-player/youtube-player-demo.html
  src/dev-app/youtube-player/youtube-player-demo.ts
  src/youtube-player/youtube-player.spec.ts
  src/youtube-player/youtube-player.ts
Labels: action: merge, target: patch

#27586 fix(cdk/menu): nested menus requiring two taps to open touch devices
  src/cdk/menu/menu-item.ts
  src/cdk/menu/menu-trigger.ts
Labels: P3, action: merge, target: patch

#27589 build: add tokens test for form field
  package.json
  packages.bzl
  src/material/core/tokens/tests/test-validate-tokens.scss
  yarn.lock
Labels: P3, action: merge, area: build & ci, target: rc

#27590 refactor(material/form-field): switch custom typography styles to tokens
  src/material/core/tokens/m2/mat/_form-field.scss
  src/material/core/tokens/m2/mdc/_filled-text-field.scss
  src/material/core/tokens/m2/mdc/_outlined-text-field.scss
  src/material/form-field/_form-field-subscript.scss
  src/material/form-field/_form-field-theme.scss
  src/material/form-field/form-field.scss
Labels: P3, action: merge, target: rc

#27557 fix(material/card): Apply tokens at mixin root
  src/material/card/_card-theme.scss
Labels: action: merge, target: major

#27585 fix(material/tooltip): Emit tokens under mixin root selector
  src/material/tooltip/_tooltip-theme.scss
Labels: action: merge, target: major

#27584 fix(material/slider): Move unthemable tokens to theme mixin
  src/material/_index.scss
  src/material/slider/_slider-theme.scss
  src/material/slider/slider.scss
Labels: action: merge, target: major, detected: breaking change

#27615 docs: release notes for the v16.1.8 release
  CHANGELOG.md
Labels: area: docs

#27619 docs: release notes for the v16.2.0 release
  CHANGELOG.md
Labels: area: docs

#27637 docs: fix broken example due to missing input module import
  src/components-examples/material/sidenav/BUILD.bazel
  src/components-examples/material/sidenav/sidenav-fixed/sidenav-fixed-example.ts
Labels: action: merge, target: patch, area: docs

#27640 fix(material/table): resolve local compilation issues
  src/material/table/row.ts
  src/material/table/table.ts
Labels: P3, action: merge, G, target: patch

#27643 docs: update developer environment to setup project
  DEV_ENVIRONMENT.md
Labels: action: merge, target: patch, area: docs

#27596 fix(material/snack-bar): Move unthemable tokens to theme mixin
  src/material/_index.scss
  src/material/snack-bar/_snack-bar-theme.scss
  src/material/snack-bar/snack-bar-container.scss
Labels: action: merge, target: major, detected: breaking change

#27646 fix(material/progress-bar): alignment affected by parent text-align
  src/material/progress-bar/progress-bar.scss
Labels: P3, action: merge, target: patch

#27656 docs(material/autocomplete): reset template driven autocomplete example
  src/dev-app/autocomplete/autocomplete-demo.html
  src/dev-app/autocomplete/autocomplete-demo.ts
Labels: docs, action: merge, target: patch, area: material/autocomplete, dev-app preview, area: docs

#27634 docs(material/tree): fix demos where keyboard navigates to hidden nodes
  src/components-examples/cdk/tree/cdk-tree-flat-children-accessor/cdk-tree-flat-children-accessor-example.html
  src/components-examples/cdk/tree/cdk-tree-flat-level-accessor/cdk-tree-flat-level-accessor-example.html
  src/components-examples/cdk/tree/cdk-tree-nested-level-accessor/cdk-tree-nested-level-accessor-example.html
  src/components-examples/cdk/tree/cdk-tree-nested-level-accessor/cdk-tree-nested-level-accessor-example.ts
Labels: a11y, target: major, area: cdk/tree, area: material/tree, dev-app preview, area: docs

#27665 docs: release notes for the v16.2.1 release
  CHANGELOG.md
Labels: area: docs

#27666 build: set up schematics for version 17
  src/cdk/schematics/migration.json
  src/cdk/schematics/ng-update/index.ts
  src/cdk/schematics/ng-update/migrations/misc-template.ts
  src/cdk/schematics/update-tool/target-version.ts
  src/material/schematics/migration.json
  src/material/schematics/ng-update/index.ts
Labels: area: build & ci

#27662 docs(material/autocomplete): fix autocomplete typo
  src/material/autocomplete/autocomplete.ts
Labels: action: merge, target: patch, area: docs

#26144 fix(material/datepicker): deprecate constructor injection in NativeDateAdapter
  src/material/core/datetime/native-date-adapter.ts
  tools/public_api_guard/material/core.md
Labels: action: merge, target: major, detected: breaking change

#27678 fix(material/select): set pointer cursor on entire form field
  src/material/select/select.scss
Labels: action: merge, P4, target: patch

#27686 docs(material/snack-bar): fix broken doc example
  src/material/snack-bar/snack-bar.md
Labels: docs, action: merge, target: patch, area: docs

#27693 refactor(cdk/dialog): changes to accommodate standalone
  src/cdk/dialog/dialog-container.ts
  src/cdk/dialog/dialog-injectors.ts
  src/cdk/dialog/dialog-module.ts
  src/cdk/dialog/dialog.ts
  tools/public_api_guard/cdk/dialog.md
Labels: P3, action: merge, target: major

#27687 fix(cdk/table): the CdkNoDataRow directive does not render in the OnPush strategy
  src/cdk/table/table.spec.ts
  src/cdk/table/table.ts
Labels: action: merge, target: patch

#27685 refactor(material/paginator): remove unused file
  src/material/paginator/_paginator-variables.scss
Labels: action: merge, P4, target: patch

#27606 fix(material/dialog): Move unthemable tokens to theme mixin
  src/material/_index.scss
  src/material/dialog/_dialog-theme.scss
  src/material/dialog/dialog.scss
Labels: action: merge, target: major, detected: breaking change

#27594 fix(material/progress-spinner): Emit tokens under mixin root selector
  src/material/progress-spinner/_progress-spinner-theme.scss
Labels: action: merge, target: major, area: material/progress-spinner

#27701 fix(material/slider): keep ios safari slider value binding in sync
  src/material/slider/slider-input.ts
Labels: action: merge, target: patch

#27672 feat(cdk/overlay): add disposeOnNavigation
  src/cdk/overlay/overlay-directives.ts
  tools/public_api_guard/cdk/overlay.md
Labels: action: merge, target: major, detected: feature

#27667 fix(material/snack-bar): Emit tokens under mixin root selector
  src/material/snack-bar/_snack-bar-theme.scss
Labels: action: merge, target: major, area: material/snack-bar

#27688 refactor(multiple): convert components to theme inspection API
  .stylelintrc.json
  src/dev-app/theme.scss
  src/material/card/_card-theme.scss
  src/material/core/_core-theme.scss
  src/material/core/option/_optgroup-theme.scss
  src/material/core/option/_option-theme.scss
  src/material/core/ripple/_ripple-theme.scss
  src/material/core/selection/pseudo-checkbox/_pseudo-checkbox-theme.scss
  src/material/core/style/_private.scss
  src/material/core/style/_sass-utils.scss
  src/material/core/theming/_m2-inspection.scss
  src/material/core/theming/_theming.scss
  src/material/core/theming/tests/test-css-variables-theme.scss
  src/material/core/tokens/m2/mat/_card.scss
  src/material/core/tokens/m2/mat/_form-field.scss
  src/material/core/tokens/m2/mat/_optgroup.scss
  src/material/core/tokens/m2/mat/_option.scss
  src/material/core/tokens/m2/mdc/_elevated-card.scss
  src/material/core/tokens/m2/mdc/_filled-text-field.scss
  src/material/core/tokens/m2/mdc/_linear-progress.scss
  src/material/core/tokens/m2/mdc/_outlined-card.scss
  src/material/core/tokens/m2/mdc/_outlined-text-field.scss
  src/material/form-field/_form-field-density.scss
  src/material/form-field/_form-field-theme.scss
  src/material/progress-bar/_progress-bar-theme.scss
Labels: action: merge, target: major

#27709 fix(material/slider): set word-break on value-indicator
  src/material/slider/slider.scss
Labels: action: merge, target: patch

#27716 refactor(material/button-toggle): remove unused file
  src/material/button-toggle/_button-toggle-variables.scss
Labels: action: merge, P4, target: major

#27712 docs: remove duplicate words
  src/material/datepicker/month-view.ts
  src/material/datepicker/multi-year-view.ts
  src/material/datepicker/year-view.ts
Labels: action: merge, P4, target: patch, area: docs

#27720 build: bump node version
  .circleci/config.yml
  .nvmrc
  WORKSPACE
Labels: P3, action: merge, target: major, area: build & ci

#27704 refactor(material/button): remove mixin class usages
  src/material/button/button-base.ts
  src/material/button/button.ts
  src/material/button/fab.ts
  src/material/button/icon-button.ts
  src/material/button/testing/BUILD.bazel
  src/material/button/testing/button-harness.ts
  tools/public_api_guard/material/button.md
Labels: P3, action: merge, target: major

#27713 refactor(multiple): convert components to theme inspection API (round 2)
  .stylelintrc.json
  src/material-experimental/popover-edit/_popover-edit-theme.scss
  src/material/autocomplete/autocomplete.ts
  src/material/button/_button-base.scss
  src/material/button/_button-theme-private.scss
  src/material/button/_button-theme.scss
  src/material/button/_fab-theme.scss
  src/material/button/_icon-button-theme.scss
  src/material/checkbox/_checkbox-theme.scss
  src/material/core/mdc-helpers/_mdc-helpers.scss
  src/material/core/theming/_m2-inspection.scss
  src/material/core/tokens/m2/mat/_paginator.scss
  src/material/core/tokens/m2/mat/_radio.scss
  src/material/core/tokens/m2/mat/_slide-toggle.scss
  src/material/core/tokens/m2/mat/_slider.scss
  src/material/core/tokens/m2/mdc/_checkbox.scss
  src/material/core/tokens/m2/mdc/_extended-fab.scss
  src/material/core/tokens/m2/mdc/_fab.scss
  src/material/core/tokens/m2/mdc/_icon-button.scss
  src/material/core/tokens/m2/mdc/_list.scss
  src/material/core/tokens/m2/mdc/_radio.scss
  src/material/core/tokens/m2/mdc/_slider.scss
  src/material/core/tokens/m2/mdc/_switch.scss
  src/material/core/typography/_definition.scss
  src/material/core/typography/_property-getters.scss
  src/material/core/typography/_typography-utils.scss
  src/material/core/typography/_typography.scss
  src/material/core/typography/_versioning.scss
  src/material/input/_input-theme.scss
  src/material/list/_list-theme.scss
  src/material/paginator/_paginator-theme.scss
  src/material/radio/_radio-theme.scss
  src/material/slide-toggle/_slide-toggle-theme.scss
  src/material/slider/_slider-theme.scss
Labels: action: merge, target: major, area: build & ci

#27635 docs(material/tree): fix keyboard issues with "Load more flat tree"
  src/components-examples/material/tree/tree-loadmore/tree-loadmore-example.html
  src/components-examples/material/tree/tree-loadmore/tree-loadmore-example.ts
Labels: a11y, docs, target: major, area: material/tree, dev-app preview, area: docs

#27631 fix(cdk/tree): CdkTreeNodeToggle focuses node when toggling it
  src/cdk/tree/toggle.ts
  src/cdk/tree/tree-redesign.spec.ts
Labels: a11y, target: major, area: cdk/tree, area: material/tree, dev-app preview

#27673 ci: migrate linker tests to GHA
  .circleci/config.yml
  .github/workflows/ci.yml
Labels: action: merge, target: patch, area: build & ci

#27738 docs: release notes for the v16.2.2 release
  CHANGELOG.md
Labels: area: docs

#27746 docs: omit repetitions
  src/cdk/a11y/interactivity-checker/interactivity-checker.ts
Labels: action: merge, target: patch, area: docs

#27743 docs: remove duplicate word
  src/material/button-toggle/button-toggle.ts
Labels: action: merge, target: patch, area: docs

#27728 refactor(multiple): convert components to theme inspection API (round 3)
  .stylelintrc.json
  src/material-experimental/column-resize/_column-resize-theme.scss
  src/material-experimental/popover-edit/_popover-edit-theme.scss
  src/material/core/color/_all-color.scss
  src/material/core/density/private/_all-density.scss
  src/material/core/focus-indicators/_private.scss
  src/material/core/theming/_all-theme.scss
  src/material/core/theming/_inspection.scss
  src/material/core/theming/_m2-inspection.scss
  src/material/core/tokens/m2/mat/_datepicker.scss
  src/material/core/tokens/m2/mat/_stepper.scss
  src/material/core/typography/_all-typography.scss
  src/material/core/typography/_typography.scss
  src/material/datepicker/_datepicker-theme.scss
  src/material/sort/_sort-theme.scss
  src/material/stepper/_stepper-theme.scss
  src/material/tree/_tree-theme.scss
Labels: action: merge, target: major
