Repository angular/components, pull requests merged in 2023-05, with the labels that each got.

#27011 fix(material/select): ensure arrow is centered on all densities
  src/material/select/_select-theme.scss
Labels: P3, action: merge, target: patch

#27028 build: update to Angular 16 final
  package.json
  yarn.lock
Labels: P3, action: merge, target: patch, area: build & ci

#26586 feat(cdk/tree): implement expansion methods for TreeKeyManager
  src/cdk/a11y/key-manager/tree-key-manager.spec.ts
  src/cdk/a11y/key-manager/tree-key-manager.ts
Labels: detected: feature

#26820 fix(material/tooltip): change tooltip to use MDC's token API
  src/material/core/tokens/m2/mdc/_plain-tooltip.scss
  src/material/core/tokens/tests/test-validate-tokens.scss
  src/material/tooltip/_tooltip-theme.scss
  src/material/tooltip/tooltip.scss
Labels: P3, target: major

#27054 build: update caniuse version
  integration/harness-e2e-cli/yarn.lock
  integration/ng-add-standalone/yarn.lock
  integration/ng-add/yarn.lock
  yarn.lock
Labels: P3, action: merge, target: patch, area: build & ci

#27031 fix(material/tabs): avoid unnecessary updates of tab ink bar
  src/material/tabs/ink-bar.ts
Labels: action: merge, target: patch

#27060 fix(cdk/schematics): avoid throwing an error for empty program
  src/cdk/schematics/update-tool/utils/parse-tsconfig.ts
Labels: P3, action: merge, target: patch

#27038 feat(material/tooltip): add isDisabled method to tooltip harness
  src/material/legacy-tooltip/testing/tooltip-harness.ts
  src/material/legacy-tooltip/tooltip.ts
  src/material/tooltip/testing/shared.spec.ts
  src/material/tooltip/testing/tooltip-harness.ts
  src/material/tooltip/tooltip.ts
  tools/public_api_guard/material/legacy-tooltip-testing.md
  tools/public_api_guard/material/tooltip-testing.md
Labels: action: merge, target: minor, detected: feature

#27056 feat(material/tabs): ink bar animation synchronize
  src/material/tabs/_tabs-common.scss
  src/material/tabs/tab-group.spec.ts
  src/material/tabs/tab-group.ts
  src/material/tabs/tab-nav-bar/tab-nav-bar.spec.ts
  src/material/tabs/tab-nav-bar/tab-nav-bar.ts
  tools/public_api_guard/material/tabs.md
Labels: action: merge, target: minor, merge: fix commit message, detected: feature

#27062 build: generate a new app in ng new test
  integration/ng-add-standalone/.editorconfig
  integration/ng-add-standalone/.gitignore
  integration/ng-add-standalone/BUILD.bazel
  integration/ng-add-standalone/README.md
  integration/ng-add-standalone/_angular.json
  integration/ng-add-standalone/src/app/app.component.html
  integration/ng-add-standalone/src/app/app.component.scss
  integration/ng-add-standalone/src/app/app.component.spec.ts
  integration/ng-add-standalone/src/app/app.component.ts
  integration/ng-add-standalone/src/app/app.config.ts
  integration/ng-add-standalone/src/app/app.routes.ts
  integration/ng-add-standalone/src/assets/.gitkeep
  integration/ng-add-standalone/src/favicon.ico
  integration/ng-add-standalone/src/index.html
  integration/ng-add-standalone/src/main.ts
  integration/ng-add-standalone/src/styles.scss
  integration/ng-add-standalone/tsconfig.app.json
  integration/ng-add-standalone/tsconfig.json
  integration/ng-add-standalone/tsconfig.spec.json
Labels: P3, action: merge, target: patch, area: build & ci

#27025 fix(material/badge): insert inline description for non-interactive hosts
  src/dev-app/badge/badge-demo.html
  src/material/badge/badge.md
  src/material/badge/badge.spec.ts
  src/material/badge/badge.ts
Labels: a11y, action: merge, target: patch, area: material/badge

#27047 refactor(material/progress-bar): Add `active-indicator-height` to unthemable tokens
  package.json
  packages.bzl
  src/material/core/tokens/m2/mdc/_linear-progress.scss
  yarn.lock
Labels: action: merge, target: patch, area: build & ci

#27079 docs: release notes for the v16.0.1 release
  CHANGELOG.md
Labels: area: docs

#27073 refactor(material/progress-bar): Delete temp `bar-and-track-height` token
  src/material/core/tokens/m2/mdc/_linear-progress.scss
  src/material/core/tokens/tests/test-validate-tokens.scss
Labels: action: merge, target: patch

#26028 fix(material/form-field): make notch sizing more reliable
  src/cdk/config.bzl
  src/cdk/observers/private/BUILD.bazel
  src/cdk/observers/private/index.ts
  src/cdk/observers/private/shared-resize-observer.spec.ts
  src/cdk/observers/private/shared-resize-observer.ts
  src/dev-app/input/input-demo.html
  src/dev-app/input/input-demo.ts
  src/material/form-field/BUILD.bazel
  src/material/form-field/directives/floating-label.ts
  src/material/form-field/directives/notched-outline.html
  src/material/form-field/directives/notched-outline.ts
  src/material/form-field/form-field.html
  src/material/form-field/form-field.scss
  src/material/form-field/form-field.ts
  src/material/input/input.spec.ts
  src/universal-app/prerender.ts
  tools/public_api_guard/BUILD.bazel
  tools/public_api_guard/material/form-field.md
Labels: action: merge, target: minor, area: build & ci, dev-app preview

#27081 fix(material/core): Fix MacOS Hover feature compatibility with optgroup
  src/material/legacy-core/option/optgroup.html
Labels: a11y, action: merge, target: patch, area: material/autocomplete, area: material/core, area: material/select, dev-app preview

#27089 refactor(cdk/schematics): remove deprecated utility usages
  src/cdk/schematics/testing/test-project.ts
Labels: P3, action: merge, target: patch

#27096 build: create ng add integration test using ng new
  integration/ng-add-standalone/karma.conf.js
  integration/ng-add/.browserslistrc
  integration/ng-add/.editorconfig
  integration/ng-add/.gitignore
  integration/ng-add/BUILD.bazel
  integration/ng-add/README.md
  integration/ng-add/_angular.json
  integration/ng-add/karma.conf.js
  integration/ng-add/src/app/app-routing.module.ts
  integration/ng-add/src/app/app.component.html
  integration/ng-add/src/app/app.component.scss
  integration/ng-add/src/app/app.component.spec.ts
  integration/ng-add/src/app/app.component.ts
  integration/ng-add/src/app/app.module.ts
  integration/ng-add/src/assets/.gitkeep
  integration/ng-add/src/environments/environment.prod.ts
  integration/ng-add/src/environments/environment.ts
  integration/ng-add/src/favicon.ico
  integration/ng-add/src/index.html
  integration/ng-add/src/main.ts
  integration/ng-add/src/polyfills.ts
  integration/ng-add/src/styles.scss
  integration/ng-add/src/test.ts
  integration/ng-add/tsconfig.app.json
  integration/ng-add/tsconfig.json
  integration/ng-add/tsconfig.spec.json
Labels: P3, action: merge, target: patch, area: build & ci

#27083 fix(material/paginator): add aria-hidden="true" to decorative svg's
  src/material/paginator/paginator.html
Labels: a11y, action: merge, target: patch, area: material/paginator, dev-app preview

#26918 refactor(material/chips): change mat-chip to use MDC's token API
  src/material/chips/_chips-theme.scss
  src/material/chips/chip.scss
  src/material/core/mdc-helpers/_mdc-helpers.scss
  src/material/core/tokens/m2/mdc/_chip.scss
  src/material/core/tokens/tests/test-validate-tokens.scss
Labels: action: merge, target: minor

#27111 fix(documentation/faq.md) - Update FAQ.md - Fixes #27110
  FAQ.md
Labels: action: merge, target: patch, merge: fix commit message

#27116 fix(multiple): set aria-hidden on presentational svgs
  src/material/chips/chip-option.html
  src/material/datepicker/datepicker-toggle.html
  src/material/legacy-menu/menu-item.html
  src/material/legacy-paginator/paginator.html
  src/material/menu/menu-item.html
  src/material/select/select.html
  src/material/slide-toggle/slide-toggle.html
Labels: action: merge, P4, target: patch

#27093 refactor(multiple): simplify ngSkipHydration expressions
  src/cdk/table/table.ts
  src/material/autocomplete/autocomplete.ts
  src/material/chips/chip-listbox.ts
  src/material/legacy-autocomplete/autocomplete.ts
  src/material/legacy-chips/chip-list.ts
  src/material/legacy-form-field/form-field.ts
  src/material/legacy-menu/menu.ts
  src/material/legacy-select/select.ts
  src/material/legacy-table/table.ts
  src/material/legacy-tabs/tab-group.ts
  src/material/menu/menu.ts
  src/material/select/select.ts
  src/material/sidenav/drawer.ts
  src/material/sidenav/sidenav.ts
  src/material/stepper/stepper.ts
  src/material/table/table.ts
  src/material/tabs/tab-group.ts
Labels: P3, action: merge, target: patch

#27082 fix(material/datepicker): set explicit event options
  src/material/datepicker/calendar-body.ts
Labels: P3, action: merge, target: patch

#27114 fix(material/checkbox): set token values on the element where theme is @included
  src/material/checkbox/_checkbox-theme.scss
  src/material/checkbox/checkbox.scss
  src/material/core/style/_sass-utils.scss
  src/material/core/theming/tests/theming-api.spec.ts
Labels: action: merge, target: patch

#27131 fix(cdk/schematics): handle templates with byte order mark
  src/cdk/schematics/update-tool/component-resource-collector.ts
Labels: P3, action: merge, target: patch

#27122 docs: fix reading hues from palettes
  guides/theming.md
Labels: action: merge, target: patch, area: docs

#27119 docs: fix blue-grey palette name in theming
  guides/theming.md
Labels: action: merge, target: patch, area: docs

#27099 Updates tabs.md to reflect current link to ARIA Tabs Pattern page
  src/material/tabs/tabs.md
Labels: docs, action: merge, target: patch, merge: fix commit message

#27134 fix(material/tooltip): missing positionAtOrigin documentation
  src/material/tooltip/tooltip.ts
  tools/public_api_guard/material/tooltip.md
Labels: action: merge, target: patch, merge: fix commit message

#27132 fix(material/icon): harness returning wrong name if icon has other content
  src/material/icon/testing/icon-harness.ts
  src/material/icon/testing/shared.spec.ts
Labels: P3, action: merge, target: patch

#27126 fix(material/list): input coercion does not working for `disableRipple` on list items
  src/material/list/list-base.ts
Labels: action: merge, target: patch

#27135 docs(material/list): description for disableRipple
  src/material/list/list-base.ts
Labels: action: merge, target: patch, area: docs

#27140 fixed missing declaration
  src/google-maps/google-map/README.md
Labels: action: merge, target: patch, merge: fix commit message

#27138 test(material/progress-bar): Re-enable token slots validation test
  package.json
  packages.bzl
  src/material/core/tokens/tests/test-validate-tokens.scss
  yarn.lock
Labels: action: merge, target: patch, area: build & ci

#27157 refactor(material/button): clean up antipattern
  src/material/button/button-base.ts
  tools/public_api_guard/material/button.md
Labels: P3, action: merge, target: patch

#27151 docs: updated the html tags
  src/cdk/menu/menu-item.spec.ts
  src/components-examples/cdk/listbox/cdk-listbox-forms-validation/cdk-listbox-forms-validation-example.html
  src/components-examples/cdk/listbox/cdk-listbox-reactive-forms/cdk-listbox-reactive-forms-example.html
  src/components-examples/cdk/listbox/cdk-listbox-template-forms/cdk-listbox-template-forms-example.html
  src/components-examples/cdk/listbox/cdk-listbox-value-binding/cdk-listbox-value-binding-example.html
Labels: action: merge, target: patch, area: docs

#27149 fix(material/slider): handle ngModel initial null value
  src/material/slider/slider-input.ts
  src/material/slider/slider.spec.ts
  tools/public_api_guard/material/slider.md
Labels: action: merge, target: patch

#27164 docs: html tags updated
  src/components-examples/material/chips/chips-form-control/chips-form-control-example.html
  src/components-examples/material/form-field/form-field-label/form-field-label-example.html
  src/dev-app/input-modality/input-modality-detector-demo.html
  src/dev-app/input/input-demo.html
Labels: action: merge, target: patch, area: docs

#27161 docs(material/datepicker): fix description for matDatepickerFilter
  src/material/datepicker/datepicker.md
Labels: action: merge, target: patch, area: docs

#27154 docs(material/table): fix description for MatHeaderRow
  src/material/table/row.ts
Labels: action: merge, target: patch, area: docs

#27174 build: update zone.js version
  integration/harness-e2e-cli/package.json
  integration/harness-e2e-cli/yarn.lock
  integration/ng-add/package.json
  integration/ng-add/yarn.lock
  package.json
  yarn.lock
Labels: P3, action: merge, target: patch, area: build & ci

#27173 build: add missing progress bar token
  package.json
  packages.bzl
  src/material/core/tokens/m2/mdc/_linear-progress.scss
  yarn.lock
Labels: P3, action: merge, target: patch, area: build & ci

#27190 fix(cdk/overlay): remove circular dependency workarounds
  src/cdk/overlay/dispatchers/base-overlay-dispatcher.ts
  src/cdk/overlay/dispatchers/overlay-keyboard-dispatcher.ts
  src/cdk/overlay/dispatchers/overlay-outside-click-dispatcher.ts
  src/cdk/overlay/overlay-ref.ts
  src/cdk/overlay/overlay-reference.ts
  src/cdk/overlay/overlay.spec.ts
  src/cdk/overlay/position/flexible-connected-position-strategy.ts
  src/cdk/overlay/position/global-position-strategy.ts
  src/cdk/overlay/position/position-strategy.ts
  src/cdk/overlay/scroll/close-scroll-strategy.ts
  src/cdk/overlay/scroll/reposition-scroll-strategy.ts
  src/cdk/overlay/scroll/scroll-strategy.ts
  tools/public_api_guard/cdk/overlay.md
Labels: P3, action: merge, target: patch

#27158 Import path shortened in form-field
  src/material/form-field/_form-field-focus-overlay.import.scss
Labels: action: merge, target: patch

#27188 feat(material/select): add input to control the panel width
  src/material/legacy-select/public-api.ts
  src/material/legacy-select/select.ts
  src/material/select/select.spec.ts
  src/material/select/select.ts
  tools/public_api_guard/material/legacy-select.md
  tools/public_api_guard/material/select.md
Labels: P3, action: merge, target: minor, detected: feature

#27198 fix(material/select): incorrect position if initialized late
  src/material/select/select.ts
  tools/public_api_guard/material/select.md
Labels: P3, action: merge, target: minor

#27129 fix(material/chips): fix click target when stacked
  src/dev-app/chips/chips-demo.html
  src/material/chips/chip-set.scss
Labels: a11y, action: merge, target: patch, area: material/chips, dev-app preview

#27205 docs: Update contribution guidelines and issue template regarding issue reproductions
  .github/ISSUE_TEMPLATE/bug.yml
  CONTRIBUTING.md
Labels: action: merge, target: patch, area: docs

#27000 feat(material-experimental/theming): add first part of token-based theming API
  .github/CODEOWNERS
  .ng-dev/commit-message.mts
  src/dev-app/BUILD.bazel
  src/dev-app/dev-app.ts
  src/dev-app/index.html
  src/dev-app/theme-token-api.scss
  src/material-experimental/BUILD.bazel
  src/material-experimental/_index.scss
  src/material-experimental/theming/BUILD.bazel
  src/material-experimental/theming/_theming.scss
  src/material/BUILD.bazel
  src/material/_index.scss
  src/material/_token-theming.scss
  src/material/button/_icon-button-theme.scss
  src/material/card/_card-theme.import.scss
  src/material/card/_card-theme.scss
  src/material/checkbox/_checkbox-theme.import.scss
  src/material/checkbox/_checkbox-theme.scss
  src/material/core/style/_sass-utils.scss
  src/material/core/tokens/_token-utils.scss
  src/material/core/tokens/m2/_index.scss
  src/material/core/tokens/m2/mat/_card.scss
  src/material/core/tokens/m2/mat/_radio.scss
  src/material/core/tokens/m2/mat/_snack-bar.scss
  src/material/core/tokens/m2/mat/_tab-header-with-background.scss
  src/material/core/tokens/m2/mat/_tab-header.scss
  src/material/core/tokens/m2/mdc/_checkbox.scss
  src/material/core/tokens/m2/mdc/_chip.scss
  src/material/core/tokens/m2/mdc/_circular-progress.scss
  src/material/core/tokens/m2/mdc/_dialog.scss
  src/material/core/tokens/m2/mdc/_elevated-card.scss
  src/material/core/tokens/m2/mdc/_icon-button.scss
  src/material/core/tokens/m2/mdc/_linear-progress.scss
  src/material/core/tokens/m2/mdc/_list.scss
  src/material/core/tokens/m2/mdc/_outlined-card.scss
  src/material/core/tokens/m2/mdc/_plain-tooltip.scss
  src/material/core/tokens/m2/mdc/_radio.scss
  src/material/core/tokens/m2/mdc/_snack-bar.scss
  src/material/core/tokens/m2/mdc/_tab-indicator.scss
  src/material/core/tokens/m2/mdc/_tab.scss
  src/material/core/tokens/tests/test-validate-tokens.scss
  src/material/legacy-radio/radio.scss
  src/material/legacy-slide-toggle/slide-toggle.scss
  src/material/slide-toggle/slide-toggle.scss
  src/material/stepper/stepper.scss
  src/material/tabs/_tabs-theme.scss
  tools/stylelint/no-unused-import.ts
Labels: action: merge, target: minor, dev-app preview, detected: feature
