Repository angular/components, pull requests merged in 2023-09, with the labels that each got.

#27742 fix(material/tabs): add aria-hidden to inactive tabs
  src/material/tabs/tab-group.html
  src/material/tabs/tab-group.spec.ts
Labels: a11y, action: merge, target: patch, area: material/tabs, dev-app preview

#27753 docs: omit repetitions
  src/material/form-field/_form-field-sizing.scss
  src/material/schematics/ng-generate/mdc-migration/rules/ts-migration/runtime-migration.ts
Labels: action: merge, target: patch, area: docs

#27726 fix(cdk/menu): run change detection for changes to overlay ref of trigger
  src/cdk/menu/menu-trigger.ts
Labels: action: merge, target: patch

#27510 fix(material/dialog): css structure change
  src/material/dialog/_mdc-dialog-structure-overrides.scss
  src/material/dialog/dialog-container.ts
  tools/public_api_guard/material/dialog.md
Labels: action: merge, target: major

#27766 feat(MatOptionHarness): make MatOptionHarness extend ContentContainerComponentHarness
  src/material/core/testing/option-harness.ts
  tools/public_api_guard/material/core-testing.md
Labels: P3, action: merge, target: major, merge: fix commit message

#27771 docs: release notes for the v16.2.3 release
  CHANGELOG.md
Labels: area: docs

#27752 fix(doc): mat-error can only rendered if the input has touched and is invalid state
  src/material/input/input.md
Labels: action: merge, target: patch, merge: fix commit message

#27781 fix(material/autocomplete): requireSelection incorrectly resetting value when there are no options
  src/material/autocomplete/autocomplete-trigger.ts
  src/material/autocomplete/autocomplete.spec.ts
Labels: P3, action: merge, target: patch

#27792 build: update to TypeScript 5.2 and Angular 17
  integration/ng-add-standalone/BUILD.bazel
  integration/ng-add-standalone/_angular.json
  integration/ng-add-standalone/package.json
  integration/ng-add-standalone/yarn.lock
  integration/ng-add/BUILD.bazel
  integration/ng-add/_angular.json
  integration/ng-add/package.json
  integration/ng-add/yarn.lock
  package.json
  src/cdk/schematics/utils/project-main-file.ts
  src/cdk/schematics/utils/project-targets.ts
  src/material/core/theming/tests/theming-definition-api.spec.ts
  src/material/core/theming/tests/theming-inspection-api.spec.ts
  src/material/core/theming/tests/theming-mixin-api.spec.ts
  src/material/schematics/ng-add/index.spec.ts
  src/material/schematics/ng-add/theming/theming.ts
  tools/sass/local-sass-importer.ts
  tslint.json
  yarn.lock
Labels: P3, action: merge, target: major, area: build & ci

#27784 refactor(material/button): switch to tokens theming API
  src/material/button/_button-theme.scss
  src/material/button/button.scss
  src/material/core/tokens/m2/mdc/_button-filled.scss
  src/material/core/tokens/tests/test-validate-tokens.scss
Labels: action: merge, target: minor

#27798 fix(cdk/schematics): account for single string in styles and new styleUrl
  src/cdk/schematics/update-tool/component-resource-collector.ts
Labels: P3, action: merge, target: major

#27800 fix(cdk/scrolling): unsubscribe from scrolled stream when viewport is destroyed
  src/cdk/scrolling/virtual-scroll-viewport.ts
Labels: action: merge, P4, target: patch

#27711 fix(material/list): Emit tokens under mixin root selector
  src/material/list/_list-theme.scss
Labels: action: merge, target: major, area: material/list

#27795 fix(material/form-field): style the cursor the same way as the rest of the input
  src/material/form-field/_mdc-text-field-structure-overrides.scss
Labels: action: merge, target: patch

#27805 build: fix snapshot tests
  package.json
  packages.bzl
  src/material/core/tokens/m2/mdc/_icon-button.scss
  yarn.lock
Labels: P3, action: merge, target: major, area: build & ci

#27816 ci: fix preview deploys not working due to folder rename
  .github/workflows/build-dev-app.yml
  .github/workflows/deploy-dev-app.yml
Labels: action: merge, target: patch, area: build & ci

#27820 docs: release notes for the v16.2.5 release
  CHANGELOG.md
Labels: area: docs

#27808 Docs spelling cdk target menu aim
  src/cdk/menu/menu.md
Labels: docs, action: merge, target: patch, area: cdk/menu, area: docs

#27812 feat(material-experimental/theming): add M3 toolbar support
  src/dev-app/theme-token-api.scss
  src/material-experimental/theming/_custom-tokens.scss
  src/material-experimental/theming/_m3-density.scss
  src/material-experimental/theming/_m3-tokens.scss
  src/material/core/tokens/m2/_index.scss
  src/material/toolbar/_toolbar-theme.scss
Labels: action: merge, target: major, dev-app preview

#27577 docs(material/tree): delete tree-checklist example.
  src/components-examples/material/tree/index.ts
  src/components-examples/material/tree/tree-checklist/tree-checklist-example.css
  src/components-examples/material/tree/tree-checklist/tree-checklist-example.html
  src/components-examples/material/tree/tree-checklist/tree-checklist-example.ts
  src/dev-app/tree/tree-demo.html
  src/dev-app/tree/tree-demo.ts
Labels: docs, action: merge, target: patch, area: material/tree, area: docs

#27809 fix(material/radio): move unthemable tokens to theme mixin
  src/material/_index.scss
  src/material/radio/_radio-theme.scss
  src/material/radio/radio.scss
Labels: action: merge, target: major, detected: breaking change

#27825 refactor(material/card): remove legacy theme normalization
  src/material/card/_card-theme.scss
Labels: action: merge, target: major

#27810 feat(material-experimental/theming): add M3 tooltip support
  src/dev-app/theme-token-api.scss
  src/material-experimental/theming/_m3-density.scss
  src/material-experimental/theming/_m3-tokens.scss
  src/material/core/tokens/m2/_index.scss
  src/material/tooltip/_tooltip-theme.scss
Labels: action: merge, target: major, dev-app preview, detected: feature

#27824 feat(material-experimental/theming): add M3 snackbar support
  src/dev-app/theme-token-api.scss
  src/material-experimental/theming/_custom-tokens.scss
  src/material-experimental/theming/_m3-tokens.scss
  src/material/snack-bar/_snack-bar-theme.scss
Labels: action: merge, target: major, dev-app preview, detected: feature

#27826 feat(material-experimental/theming): add M3 slider support
  src/dev-app/theme-token-api.scss
  src/material-experimental/theming/_custom-tokens.scss
  src/material-experimental/theming/_m3-density.scss
  src/material-experimental/theming/_m3-tokens.scss
  src/material/core/tokens/m2/_index.scss
  src/material/slider/_slider-theme.scss
Labels: action: merge, target: major, dev-app preview, detected: feature

#27833 build: replace custom lint rule with compiler option
  integration/mdc-migration/verify-golden.ts
  integration/size-test/check-size.ts
  scripts/build-docs-content.mts
  scripts/build-packages-dist.mts
  scripts/caretaking/resync-caretaker-app-prs.ts
  scripts/circleci/notify-slack-job-failure.mts
  scripts/docs-deploy/deploy-ci-push.mts
  scripts/docs-deploy/deploy-to-site.mts
  scripts/docs-deploy/utils.mts
  scripts/tsconfig.json
  src/bazel-tsconfig-build.json
  src/cdk/schematics/tsconfig.json
  src/cdk/schematics/utils/build-component.ts
  src/cdk/schematics/utils/html-manipulation.ts
  src/cdk/schematics/utils/project-index-file.ts
  src/cdk/schematics/utils/project-main-file.ts
  src/cdk/schematics/utils/project-style-file.ts
  src/cdk/schematics/utils/project-tsconfig-paths.ts
  src/cdk/schematics/utils/schematic-options.ts
  src/cdk/testing/tests/webdriver.e2e.spec.ts
  src/material/datepicker/date-range-input.spec.ts
  src/material/schematics/ng-add/index.spec.ts
  src/material/schematics/ng-add/setup-project.ts
  src/material/schematics/ng-add/theming/theming.ts
  src/material/schematics/tsconfig.json
  src/universal-app/prerender.ts
  tools/dgeni/tsconfig.json
  tools/tslint-rules/ngOnChangesPropertyAccessRule.ts
  tsconfig.json
  tslint.json
Labels: P3, action: merge, target: major, area: build & ci

#27836 build: update to latest version of Sass
  WORKSPACE
  package.json
  yarn.lock
Labels: P3, action: merge, target: major, area: build & ci

#27838 fix(cdk/menu): context menu closing immediately on control + click on Safari
  src/cdk/menu/context-menu-trigger.ts
Labels: P3, action: merge, target: patch

#27757 docs: fix typo in css file
  src/material/core/theming/_m2-inspection.scss
  src/material/core/typography/_versioning.scss
Labels: action: merge, target: major, merge: fix commit message, area: docs

#26889 fix: improved missing dateAdapters error message to include matLuxon and matDateFns
  src/material/datepicker/datepicker-errors.ts
Labels: action: merge, target: patch

#27774 docs(material/theming): get-color-from-palette passes in '500' instead o…
  guides/theming.md
Labels: action: merge, target: patch, area: docs

#27846 docs(material/slider): clarify behavior of slider range thumbs
  src/material/slider/slider.md
Labels: action: merge, target: patch, merge: fix commit message, area: docs

#27760 docs(theming): change color pallete format
  guides/theming.md
Labels: action: merge, target: patch, merge: fix commit message, area: docs

#27857 docs: release notes for the v16.2.6 release
  CHANGELOG.md
Labels: area: docs

#27860 feat(material/dialog): switch to standalone
  src/material/dialog/dialog-container.ts
  src/material/dialog/dialog-content-directives.ts
  src/material/dialog/dialog.ts
  src/material/dialog/module.ts
  tools/public_api_guard/material/dialog.md
Labels: P3, action: merge, target: major, detected: feature

#27862 fix(material/tabs): nav bar not navigating on enter presses
  src/material/tabs/tab-nav-bar/tab-nav-bar.spec.ts
  src/material/tabs/tab-nav-bar/tab-nav-bar.ts
Labels: P2, a11y, action: merge, target: patch

#27871 ci: setup slack messages for integration test
  .github/workflows/ci.yml
Labels: action: merge, target: patch, area: build & ci
