Repository angular/components, pull requests merged in 2023-06, with the labels that each got.

#27215 docs: release notes for the v16.0.3 release
  CHANGELOG.md
Labels: area: docs

#27210 refactor: use improved relative import path in button
  src/material/button/_button-base.import.scss
Labels: action: merge, target: patch

#27212 fix(material/tabs): default stretchTabs value not picked up by nav bar
  src/material/tabs/tab-nav-bar/tab-nav-bar.ts
Labels: P3, action: merge, target: patch

#27218 fix(material/slider): fix track getting out of sync
  src/material/slider/slider.scss
  src/material/slider/slider.ts
Labels: action: merge, target: patch

#27233 test(cdk/observers): reduce flakiness in resize observer tests
  src/cdk/observers/private/shared-resize-observer.spec.ts
Labels: P3, action: merge, target: minor

#27202 feat(cdk/tree): implement typeahead for TreeKeyManager
  src/cdk/a11y/key-manager/tree-key-manager.spec.ts
  src/cdk/a11y/key-manager/tree-key-manager.ts
  src/cdk/a11y/public-api.ts
  tools/public_api_guard/cdk/a11y.md
Labels: detected: feature

#27237 docs: removed the obsolete Tag and updated the files
  src/components-examples/material/tabs/tab-group-preserve-content/tab-group-preserve-content-example.html
  src/dev-app/dialog/dialog-demo.ts
  src/dev-app/legacy-dialog/legacy-dialog-demo.ts
Labels: action: merge, target: patch, area: docs

#27236 docs: updated the deprecated tags in the html
  src/dev-app/legacy-input/legacy-input-demo.html
  src/dev-app/performance/performance-demo.html
Labels: action: merge, target: patch, area: docs

#27232 fix(material/stepper): two-way binding for selectedIndex
  src/cdk/stepper/stepper.ts
  src/material/stepper/stepper.spec.ts
  tools/public_api_guard/cdk/stepper.md
Labels: action: merge, target: minor

#27091 fix(material/tabs): tab header is clickable if its disable
  src/material/tabs/_tabs-common.scss
Labels: action: merge, target: patch

#27227 fix(material/slider): handle contextmenu events
  src/material/slider/slider-input.ts
  src/material/slider/slider-thumb.ts
Labels: action: merge, target: patch

#27244 docs: replaced the map with the forEach
  integration/harness-e2e-cli/src/test.ts
Labels: action: merge, target: patch, area: docs

#27239 fix(material/core): Fix MacOS Hover feature compatibility with optgroup
  src/material/core/option/optgroup.html
Labels: a11y, action: merge, target: patch, area: material/autocomplete, area: material/core, area: material/select, dev-app preview

#27185 docs: improved code smells
  src/dev-app/card/card-demo.html
  src/material/bottom-sheet/bottom-sheet-container.ts
Labels: action: merge, target: patch, area: docs

#27258 build: resolve browserslist errors in patch branch
  integration/harness-e2e-cli/yarn.lock
  integration/mdc-migration/golden/yarn.lock
  integration/mdc-migration/sample-project/yarn.lock
  integration/ng-add-standalone/yarn.lock
  integration/ng-add/yarn.lock
  integration/yarn-pnp-compat/package.json
  integration/yarn-pnp-compat/yarn.lock
  yarn.lock
Labels: P2, action: merge, target: patch, area: build & ci

#27262 docs: release notes for the v16.0.4 release
  CHANGELOG.md
Labels: area: docs

#27259 docs: updating the docs with the http secure tag
  CHANGELOG_ARCHIVE.md
  CODING_STANDARDS.md
  CONTRIBUTING.md
  src/dev-app/legacy-list/legacy-list-demo.html
  src/dev-app/legacy-menu/legacy-menu-demo.html
  src/dev-app/menu/menu-demo.html
  src/material/button/button.spec.ts
  src/material/icon/icon-registry.ts
  src/material/icon/icon.md
  src/material/legacy-button/button.scss
  src/material/legacy-button/button.spec.ts
  tools/markdown-to-html/docs-marked-renderer.spec.ts
Labels: action: merge, target: patch, area: docs

#27254 docs: delete redundant word
  src/material/list/list.md
Labels: action: merge, target: patch, area: docs

#27252 refactor: use improved relative import path in form-field
  src/material/form-field/_form-field-theme.import.scss
Labels: action: merge, target: patch

#27257 docs: updating the contribution guidline docs with the secure tag
  CONTRIBUTING.md
Labels: action: merge, target: minor, area: docs

#27267 fix(material/select): provide horizontal fallback positions
  src/material/select/select.ts
Labels: P3, action: merge, target: rc

#27197 docs(material/chips): require announcing removal of chip to AT
  src/components-examples/material/chips/chips-autocomplete/chips-autocomplete-example.ts
  src/components-examples/material/chips/chips-form-control/chips-form-control-example.ts
  src/components-examples/material/chips/chips-input/chips-input-example.ts
  src/dev-app/chips/chips-demo.ts
  src/material/chips/chips.md
Labels: a11y, docs, action: merge, target: patch, area: material/chips, dev-app preview, area: docs

#27219 feat(material-experimental/theming): Introduce a facade layer between user-facing customizable keys and actual MDC token names
  src/dev-app/checkbox/checkbox-demo.html
  src/dev-app/theme-token-api.scss
  src/material-experimental/_index.scss
  src/material-experimental/theming/README.md
  src/material-experimental/theming/_card.scss
  src/material-experimental/theming/_checkbox.scss
  src/material-experimental/theming/_theming.scss
  src/material-experimental/theming/_token-resolution.scss
  src/material/card/_card-theme.scss
  src/material/checkbox/_checkbox-theme.scss
  src/material/core/style/_sass-utils.scss
Labels: action: merge, target: minor, dev-app preview, detected: feature

#27271 docs: codig standard docs updated
  CODING_STANDARDS.md
Labels: action: merge, target: patch, area: docs

#27274 fix(material/tabs): prevent default keyboard actions on disabled links
  src/material/tabs/tab-nav-bar/tab-nav-bar.spec.ts
  src/material/tabs/tab-nav-bar/tab-nav-bar.ts
Labels: P3, action: merge, target: patch

#27273 docs: removed unused methods from button component
  integration/mdc-migration/golden/src/app/components/button/button.component.ts
  integration/mdc-migration/sample-project/src/app/components/button/button.component.ts
Labels: action: merge, target: minor, merge: fix commit message, area: docs

#27268 docs: removed unused imports from autocomplete-trigger file
  src/material/legacy-autocomplete/autocomplete-trigger.ts
Labels: action: merge, target: minor, merge: fix commit message, area: material/autocomplete

#27277 build: remove node 14 support
  package.json
Labels: action: merge, target: patch, area: build & ci

#26897 refactor(material/core): generalize lazy ripple logic
  .github/CODEOWNERS
  src/material/button/button-base.ts
  src/material/button/button-lazy-loader.ts
  src/material/button/button.spec.ts
  src/material/button/icon-button.ts
  src/material/core/private/index.ts
  src/material/core/private/ripple-loader.ts
  src/material/core/public-api.ts
  tools/public_api_guard/material/button.md
  tools/public_api_guard/material/core.md
Labels: action: merge, target: minor

#27192 refactor(material/table): switch to tokens API
  src/material/core/tokens/_token-utils.scss
  src/material/core/tokens/m2/mat/_table.scss
  src/material/table/_table-theme.scss
  src/material/table/table.scss
Labels: P3, action: merge, target: minor

#27286 docs(cdk/drag-drop): fix cursor for disable drag
  src/components-examples/cdk/drag-drop/cdk-drag-drop-disabled/cdk-drag-drop-disabled-example.css
Labels: action: merge, target: patch, area: docs

#27295 docs: release notes for the v16.1.0 release
  CHANGELOG.md
Labels: area: docs

#27299 build: update to Angular 16.1
  package.json
  yarn.lock
Labels: P3, action: merge, target: minor, area: build & ci

#27288 refactor(material/autocomplete): switch to tokens API
  src/material/autocomplete/BUILD.bazel
  src/material/autocomplete/_autocomplete-theme.scss
  src/material/autocomplete/autocomplete.scss
  src/material/core/tokens/m2/mat/_autocomplete.scss
Labels: P3, action: merge, target: patch

#27307 docs: release notes for the v16.1.1 release
  CHANGELOG.md
Labels: area: docs

#27314 build: speed up RBE by allowing more concurrent jobs
  .bazelrc
Labels: action: merge, target: patch, area: build & ci

#27315 fix(cdk/a11y): don't emit blurred events on the server
  src/cdk/a11y/focus-monitor/focus-monitor.spec.ts
  src/cdk/a11y/focus-monitor/focus-monitor.ts
Labels: P3, action: merge, target: patch

#27245 refactor(material/chips): Use tokens for state layer
  src/material/chips/_chips-theme.scss
  src/material/chips/chip.scss
  src/material/core/tokens/m2/mdc/_chip.scss
Labels: a11y, action: merge, target: patch, area: material/chips, dev-app preview

#27302 fix(material/slider): fix voiceover on ios
  src/material/slider/slider.spec.ts
  src/material/slider/slider.ts
  src/material/slider/testing/slider-harness.spec.ts
Labels: action: merge, target: patch

#27310 refactor(material/select): switch to tokens API
  src/material/core/tokens/m2/mat/_select.scss
  src/material/select/_select-theme.scss
  src/material/select/select.scss
Labels: P3, action: merge, target: patch

#27320 build: fix out of sync file
  src/material/select/select.scss
Labels: P3, action: merge, target: patch, area: build & ci

#27319 test(cdk/testing): attempt to deflake webdriver tests
  src/cdk/testing/tests/test-main-component.html
Labels: P3, action: merge, target: patch

#27324 docs(material/theming): add missing theme variable to theming guide docs
  guides/theming-your-components.md
Labels: action: merge, target: patch, area: docs

#27323 refactor(material/select): rename some tokens for more clarity
  src/material/core/tokens/m2/mat/_select.scss
  src/material/select/select.scss
Labels: P3, action: merge, target: patch

#27330 feat(material/slide-toggle): allow for icon to be hidden
  src/dev-app/slide-toggle/slide-toggle-demo.html
  src/material/slide-toggle/slide-toggle-config.ts
  src/material/slide-toggle/slide-toggle.html
  src/material/slide-toggle/slide-toggle.spec.ts
  src/material/slide-toggle/slide-toggle.ts
  tools/public_api_guard/material/slide-toggle.md
Labels: action: merge, P4, target: minor, detected: feature

#26966 fix(material/slide-toggle): change slide-toggle to use MDC's token API
  src/material/core/tokens/m2/mat/_slide-toggle.scss
  src/material/core/tokens/m2/mdc/_switch.scss
  src/material/core/tokens/tests/test-validate-tokens.scss
  src/material/slide-toggle/_slide-toggle-theme.scss
  src/material/slide-toggle/slide-toggle.scss
Labels: action: merge, target: minor, area: material/slide-toggle

#27285 feat(cdk/tree): integrate TreeKeyManager with cdk/tree
  src/cdk/a11y/key-manager/tree-key-manager.ts
  src/cdk/tree/control/nested-tree-control.ts
  src/cdk/tree/nested-node.ts
  src/cdk/tree/toggle.ts
  src/cdk/tree/tree-redesign.spec.ts
  src/cdk/tree/tree.spec.ts
  src/cdk/tree/tree.ts
  src/components-examples/cdk/tree/cdk-tree-flat-children-accessor/cdk-tree-flat-children-accessor-example.ts
  src/components-examples/cdk/tree/cdk-tree-flat-level-accessor/cdk-tree-flat-level-accessor-example.ts
  src/components-examples/cdk/tree/cdk-tree-flat/cdk-tree-flat-example.html
  src/components-examples/cdk/tree/cdk-tree-nested-level-accessor/cdk-tree-nested-level-accessor-example.ts
  src/components-examples/cdk/tree/cdk-tree-nested/cdk-tree-nested-example.html
  src/dev-app/tree/tree-demo.ts
  src/material/tree/node.ts
  src/material/tree/testing/shared.spec.ts
  src/material/tree/tree.spec.ts
  src/material/tree/tree.ts
  tools/public_api_guard/cdk/a11y.md
  tools/public_api_guard/cdk/tree.md
  tools/public_api_guard/material/tree.md
Labels: detected: feature

#27343 test(material/dialog): add tokens test
  src/material/core/tokens/m2/mdc/_dialog.scss
  src/material/core/tokens/tests/test-validate-tokens.scss
Labels: P3, action: merge, target: patch

#27352 docs: release notes for the v16.1.2 release
  CHANGELOG.md
Labels: area: docs

#27350 build: add missing token from canary version
  package.json
  packages.bzl
  src/material/core/tokens/m2/mdc/_dialog.scss
  yarn.lock
Labels: P3, action: merge, target: patch, area: build & ci

#27357 fix(material/core): add validation to create-token-slot
  src/material/core/tokens/_token-utils.scss
Labels: P3, action: merge, target: patch

#27363 fix(cdk/schematics): clean up deep imports of devkit APIs
  src/cdk/schematics/ng-update/devkit-migration-rule.ts
  src/cdk/schematics/ng-update/devkit-migration.ts
  src/cdk/schematics/utils/ast.ts
  src/cdk/schematics/utils/build-component.ts
  src/cdk/schematics/utils/get-project.ts
  src/cdk/schematics/utils/project-index-file.ts
  src/cdk/schematics/utils/project-main-file.ts
  src/cdk/schematics/utils/project-style-file.ts
  src/cdk/schematics/utils/project-targets.ts
  src/cdk/schematics/utils/project-tsconfig-paths.ts
  src/cdk/schematics/utils/schematic-options.ts
  src/material/schematics/ng-add/index.spec.ts
  src/material/schematics/ng-add/theming/theming.ts
Labels: P2, action: merge, target: patch

#27371 refactor(material/core): resolve flakes in ripple tests
  src/material/core/ripple/ripple-renderer.ts
Labels: P3, action: merge, target: patch

#27317 fix(material/chips): remove button role from editable chips
  src/material/chips/chip-row.html
  src/material/chips/chip-row.spec.ts
  src/material/chips/chip.scss
Labels: a11y, action: merge, target: patch, area: material/chips, dev-app preview

#27368 fix(material/badge): warn if use with mat-icon
  src/material/badge/badge.ts
Labels: action: merge, target: patch

#27365 refactor(material/core): switch option and option group to tokens API
  src/material/core/option/_optgroup-theme.scss
  src/material/core/option/_option-theme.scss
  src/material/core/option/optgroup.scss
  src/material/core/option/option.scss
  src/material/core/tokens/m2/mat/_optgroup.scss
  src/material/core/tokens/m2/mat/_option.scss
Labels: P3, action: merge, target: patch

#27383 docs: release notes for the v16.1.3 release
  CHANGELOG.md
Labels: area: docs

#27378 fix(material/menu): prevent menu styles from leaking to other components
  src/material/menu/_menu-theme.scss
  src/material/menu/menu-trigger.ts
  tools/public_api_guard/material/menu.md
Labels: P3, action: merge, target: patch
