Repository angular/components, pull requests merged in 2023-02, with the labels that each got.

#26527 fix(material/tabs): unable to click projected content in tab label
  src/material/tabs/_tabs-common.scss
Labels: P3, action: merge, target: patch

#26541 build: split up changelog
  CHANGELOG.md
  CHANGELOG_ARCHIVE.md
Labels: P3, action: merge, target: patch, area: build & ci

#26391 test(multiple): add performance testing page to dev-app
  .github/CODEOWNERS
  src/dev-app/BUILD.bazel
  src/dev-app/dev-app/dev-app-layout.html
  src/dev-app/performance/BUILD.bazel
  src/dev-app/performance/performance-demo.html
  src/dev-app/performance/performance-demo.scss
  src/dev-app/performance/performance-demo.ts
  src/dev-app/routes.ts
Labels: perf, action: merge, target: patch

#26319 fix(material/tabs): set color on disabled tabs
  src/material/tabs/_tabs-theme.scss
Labels: P3, action: merge, target: patch

#26545 fix(material/checkbox): focus not moved to input when clicking on touch target
  src/material/checkbox/checkbox.html
  src/material/checkbox/checkbox.spec.ts
  src/material/checkbox/checkbox.ts
  tools/public_api_guard/material/checkbox.md
Labels: P3, action: merge, target: patch

#26560 docs: release notes for the v15.1.3 release
  CHANGELOG.md
Labels: area: docs

#26230 test(material/select): add disabled harness filter
  src/material/legacy-select/testing/select-harness-filters.ts
  src/material/legacy-select/testing/select-harness.ts
  src/material/select/testing/select-harness-filters.ts
  src/material/select/testing/select-harness.ts
  src/material/select/testing/shared.spec.ts
  tools/public_api_guard/material/legacy-select-testing.md
  tools/public_api_guard/material/select-testing.md
Labels: action: merge, target: patch

#26550 docs(material/guides/v15-mdc-migration): Change CSS-Selector-Specificity
  guides/v15-mdc-migration.md
Labels: action: merge, target: patch, merge: fix commit message

#26563 docs: mention that typography hierarchy isn't included by default
  guides/typography.md
  guides/v15-mdc-migration.md
Labels: P3, action: merge, target: patch, area: docs

#26564 fix(material/chips): unable to add space when editing chip
  src/material/chips/chip-action.ts
  src/material/chips/chip-row.spec.ts
Labels: P3, action: merge, target: patch

#26597 docs: release notes for the v15.1.4 release
  CHANGELOG.md
Labels: area: docs

#26515 docs(material/select, material/autocomplete): update a11y docs on che…
  src/material/autocomplete/autocomplete.md
  src/material/select/select.md
Labels: a11y, docs, action: merge, target: patch, area: material/autocomplete, area: material/select, area: docs

#26535 fix(material/slider): make valueChange emit only on change and not on…
  src/material/slider/slider-input.ts
Labels: action: merge, target: patch

#26516 refactor: change mat-list to use MDC's token API
  .github/CODEOWNERS
  src/material/core/theming/_theming.scss
  src/material/core/tokens/_token-utils.scss
  src/material/core/tokens/m2/mdc/_list.scss
  src/material/core/tokens/tests/BUILD.bazel
  src/material/core/tokens/tests/test-validate-tokens.scss
  src/material/list/_interactive-list-theme.import.scss
  src/material/list/_interactive-list-theme.scss
  src/material/list/_list-option-theme.scss
  src/material/list/_list-theme.import.scss
  src/material/list/_list-theme.scss
  src/material/list/list.scss
Labels: action: merge, target: minor, dev-app preview

#25156 fix(docs): remove troubleshooting issue template
  .github/ISSUE_TEMPLATE/config.yml
  .github/ISSUE_TEMPLATE/troubleshooting.yml
Labels: docs, action: merge, target: patch, area: docs

#26624 fix(material/core): Fix legacy prebuilt themes export
  src/material/package-base.json
Labels: action: merge, target: patch

#26616 docs: fix outdated wai-aria-practices dialog_modal url
  src/cdk/a11y/a11y.md
  src/cdk/a11y/focus-trap/focus-trap.md
Labels: action: merge, target: patch, area: docs

#26607 docs(material/typography): fix "kids theme" example
  guides/typography.md
Labels: action: merge, target: patch, merge: fix commit message, area: docs

#26629 build: update to Angular 15.2
  integration/harness-e2e-cli/yarn.lock
  integration/mdc-migration/golden/package.json
  integration/mdc-migration/golden/yarn.lock
  integration/mdc-migration/sample-project/package.json
  integration/mdc-migration/sample-project/yarn.lock
  integration/ng-add-standalone/yarn.lock
  integration/ng-add/package.json
  integration/ng-add/yarn.lock
  integration/yarn-pnp-compat/.browserslistrc
  integration/yarn-pnp-compat/package.json
  integration/yarn-pnp-compat/tsconfig.json
  integration/yarn-pnp-compat/yarn.lock
  package.json
  yarn.lock
Labels: P3, action: merge, target: patch, area: build & ci

#26618 fix(material/radio): input not focused when clicking on touch target
  src/material/radio/radio.html
  src/material/radio/radio.spec.ts
  src/material/radio/radio.ts
  tools/public_api_guard/material/radio.md
Labels: P3, action: merge, target: patch

#26633 docs: release notes for the v15.1.5 release
  CHANGELOG.md
Labels: area: docs

#26646 build: update to latest remote build execution setup
  .circleci/config.yml
  .github/workflows/build-dev-app.yml
Labels: action: merge, target: patch, area: build & ci

#26647 fix(material/tabs): disablePagination not working
  src/material/tabs/tab-group.html
  src/material/tabs/tab-group.spec.ts
Labels: P3, action: merge, target: patch

#26658 docs(material/chips): fix minor spelling mistake
  src/material/chips/chips.md
Labels: action: merge, target: rc, area: docs

#26652 docs(material/datepicker): avoid CalendarView switching
  src/components-examples/material/datepicker/datepicker-views-selection/datepicker-views-selection-example.ts
Labels: action: merge, target: rc, area: docs

#26667 build: prepare for v16 in `main` branch
  package.json
Labels: action: merge, target: minor, area: build & ci

#26668 build: update sync config to reflect internal config
  .ng-dev/google-sync-config.json
Labels: action: merge, area: build & ci, target: rc

#26679 docs: release notes for the v15.1.6 release
  CHANGELOG.md
Labels: area: docs

#26681 docs: release notes for the v15.2.0 release
  CHANGELOG.md
Labels: area: docs

#26683 fix(material/chips): allow attribute selectors for chips
  guides/v15-mdc-migration.md
  src/material/chips/chip-option.ts
  src/material/chips/chip-row.ts
  src/material/chips/chip.ts
  tools/public_api_guard/material/chips.md
Labels: P3, action: merge, target: patch

#26692 fix(material/snack-bar): misaligned lines on safari for long messages
  src/material/snack-bar/snack-bar-container.scss
Labels: P3, action: merge, target: patch

#26694 build: update to Angular 16
  package.json
  yarn.lock
Labels: P3, action: merge, target: major, area: build & ci

#26696 fix(material/chips): styling not updating when actions are removed
  src/material/chips/chip.ts
  tools/public_api_guard/material/chips.md
Labels: P3, action: merge, target: patch

#26699 build: update angular shared dev-infra code
  .github/workflows/assistant-to-the-branch-manager.yml
  .github/workflows/build-dev-app.yml
  .github/workflows/deploy-dev-app.yml
  .github/workflows/dev-infra.yml
  .github/workflows/google-internal-tests.yml
  .github/workflows/lock-closed.yml
  package.json
  yarn.lock
Labels: target: patch, area: build & ci

#26689 fix(material/chips): remove spans from top level of component
  src/material/chips/chip-grid.ts
  src/material/chips/chip-listbox.ts
  src/material/chips/chip-set.ts
Labels: P3, action: merge, target: patch

#26674 fix(material/card): refactor to depend on @angular/material/core/tokens
  src/material/card/_card-theme.scss
  src/material/card/card.scss
  src/material/core/tokens/_token-utils.scss
  src/material/core/tokens/m2/mat/_card.scss
  src/material/core/tokens/m2/mdc/_elevated-card.scss
  src/material/core/tokens/m2/mdc/_list.scss
  src/material/core/tokens/m2/mdc/_outlined-card.scss
  src/material/core/tokens/tests/test-validate-tokens.scss
Labels: action: merge, target: minor

#26688 fix(material/chips): chips should assume their minimum density rather than error for small densities
  package.json
  src/dev-app/dev-app/dev-app-layout.ts
  src/dev-app/theme.scss
  src/material/chips/_chips-theme.scss
Labels: action: merge, target: patch, dev-app preview

#26686 docs: fix update command for v15 migration
  guides/v15-mdc-migration.md
Labels: action: merge, target: patch, area: docs

#26427 fix(mdc-migration): migrate components selectively bug
  src/material/schematics/ng-generate/mdc-migration/rules/index.ts
  src/material/schematics/ng-generate/mdc-migration/rules/ts-migration/runtime-migration.ts
  src/material/schematics/ng-generate/mdc-migration/rules/ts-migration/runtime-migrator.spec.ts
Labels: action: merge, target: patch, merge: fix commit message

#26330 reverse body-1 and body-2 description
  guides/typography.md
Labels: action: merge, target: patch, merge: fix commit message, area: docs, detected: breaking change

#26672 fix(material/list): add disabled attribute for mat-list-item buttons
  src/material/list/list-base.ts
  src/material/list/list.spec.ts
Labels: action: merge, target: patch
