Repository angular/components, pull requests merged in 2023-01, with the labels that each got.

#26346 build: bump year
  LICENSE
Labels: action: merge, target: patch, area: build & ci

#26289 fix(material/slider): dragEnd not being emitted
  src/material/slider/slider-input.ts
Labels: P3, action: merge, target: patch

#26328 refactor(cdk/overlay): switch directives to standalone
  src/cdk/overlay/overlay-directives.ts
  src/cdk/overlay/overlay-module.ts
  tools/public_api_guard/cdk/overlay.md
Labels: P3, action: merge, target: patch

#26296 fix(cdk/menu): don't prevent default selection key actions
  src/cdk/menu/menu-item.spec.ts
  src/cdk/menu/menu-item.ts
  src/cdk/menu/menu-trigger.spec.ts
  src/cdk/menu/menu-trigger.ts
  tools/public_api_guard/cdk/menu.md
Labels: P2, action: merge, target: minor

#26279 fix(material/menu): aria-expanded not updating in an OnPush component
  src/material/menu/menu-trigger.ts
  src/material/menu/menu.spec.ts
Labels: P3, action: merge, target: patch

#26357 build: fix snapshot jobs by not updating `@angular/bazel`
  scripts/circleci/setup-angular-snapshots.js
Labels: action: merge, target: patch, area: build & ci

#26323 fix(material/menu): prevent pointer events on animating menu
  src/material/menu/menu.scss
Labels: P3, action: merge, target: patch

#26341 fix(material/datepicker): Update strategy to handle dragging across m…
  src/material/datepicker/date-range-selection-strategy.spec.ts
  src/material/datepicker/date-range-selection-strategy.ts
Labels: action: merge, G, target: minor

#26345 fix(material/slider): value jumping after drag with box-sizing: border-box
  src/material/slider/slider.scss
Labels: P3, action: merge, target: patch

#26344 fix(material/tabs): touch gestures not working on tab nav bar
  src/material/tabs/tab-nav-bar/tab-nav-bar.ts
Labels: P3, action: merge, target: patch

#26366 refactor(multiple): remove remaining dependencies on MDC JS
  package.json
  packages.bzl
  src/material/checkbox/BUILD.bazel
  src/material/core/ripple/ripple-renderer.ts
  src/material/dialog/BUILD.bazel
  src/material/dialog/dialog-container.ts
  src/material/dialog/dialog.spec.ts
  src/material/dialog/public-api.ts
  src/material/input/BUILD.bazel
  src/material/radio/BUILD.bazel
  src/material/slide-toggle/BUILD.bazel
  tslint.json
  yarn.lock
Labels: P2, action: merge, target: minor

#26334 fix(material/snack-bar): incorrect width at some breakpoints
  src/material/snack-bar/snack-bar-container.scss
Labels: P3, action: merge, target: patch

#26368 build: use a more appropriate naming for the snapshot deploy GitHub token
  scripts/deploy/publish-build-artifacts.sh
  scripts/deploy/publish-docs-content.sh
Labels: action: merge, target: patch, area: build & ci

#26338 fix(material/chips): add opt-out for single-select checkmarks
  src/dev-app/chips/chips-demo.html
  src/dev-app/chips/chips-demo.ts
  src/material/chips/chip-listbox.ts
  src/material/chips/chip-option.html
  src/material/chips/chip-option.spec.ts
  src/material/chips/chip-option.ts
  src/material/chips/tokens.ts
  tools/public_api_guard/material/chips.md
Labels: a11y, action: merge, target: minor, area: material/chips

#26380 build: update to TypeScript 4.9
  integration/yarn-pnp-compat/.yarn/releases/yarn-3.2.3.cjs
  integration/yarn-pnp-compat/.yarn/releases/yarn-3.3.1.cjs
  integration/yarn-pnp-compat/.yarnrc.yml
  integration/yarn-pnp-compat/package.json
  package.json
  scripts/caretaking/firebase-functions/package.json
  yarn.lock
Labels: P2, action: merge, area: build & ci, target: rc

#26343 fix(material/chips): change div to span
  src/material/chips/chip.html
Labels: action: merge, target: patch, area: material/chips

#26386 fix(cdk/drag-drop): receiving class not updated in OnPush component
  src/cdk/drag-drop/directives/drag.spec.ts
  src/cdk/drag-drop/directives/drop-list.ts
  src/cdk/drag-drop/drop-list-ref.ts
  tools/public_api_guard/cdk/drag-drop.md
Labels: P3, action: merge, target: patch

#26149 build: enable ng-dev auth service
  .ng-dev/github.mts
Labels: action: merge, target: patch, area: build & ci

#26375 docs(material/chips): update a11y documention on checkmark indicators
  src/material/chips/chips.md
Labels: a11y, docs, action: merge, target: minor, area: material/chips, area: docs

#26374 docs(material/list): update a11y documention on radio indicators
  src/material/list/list.md
Labels: a11y, docs, action: merge, target: minor, area: material/list, area: docs

#26397 fix(material/tabs): allow focus on disabled tabs
  src/material/legacy-tabs/_tabs-theme.scss
  src/material/legacy-tabs/tab-group.html
  src/material/legacy-tabs/tab-header.spec.ts
  src/material/tabs/_tabs-theme.scss
  src/material/tabs/paginated-tab-header.ts
  src/material/tabs/tab-group.html
  src/material/tabs/tab-group.scss
  src/material/tabs/tab-group.ts
  src/material/tabs/tab-header.spec.ts
  tools/public_api_guard/material/tabs.md
Labels: P3, action: merge, G, target: patch, dev-app preview

#26406 build: update peer dependency for v15.1.0 release
  packages.bzl
Labels: action: merge, area: build & ci, target: rc

#26411 docs: release notes for the v15.1.0 release
  CHANGELOG.md
Labels: area: docs

#26414 fix(material/select): active class not removed from reset option when new value is assigned through form control
  src/material/legacy-select/select.spec.ts
  src/material/select/select.spec.ts
  src/material/select/select.ts
Labels: P3, action: merge, target: patch

#26421 build: adjust peer dependency to include all minor pre-releases
  .bazelrc
  .ng-dev/release.mts
  package.json
  packages.bzl
  scripts/docs-deploy/deploy-ci-push.mts
  tools/bazel-additional-stamp.mjs
  tools/release-checks/check-framework-peer-dependency.mts
  yarn.lock
Labels: action: merge, target: patch, area: build & ci

#26378 fix(material/slider): Use non-deprecated theme key
  package.json
  packages.bzl
  src/material/slider/_slider-theme.scss
  yarn.lock
Labels: action: merge, target: patch, area: build & ci

#26409 fix(multiple): remove the commented out code
  tools/region-parser/region-parser.ts
Labels: action: merge, target: patch, merge: fix commit message

#26408 fix(multiple): removed unused variable from sepc file
  src/cdk/dialog/dialog.spec.ts
Labels: action: merge, target: patch, merge: fix commit message

#26404 fix(multiple): update the html tags and add the alt attr
  src/components-examples/cdk/dialog/cdk-dialog-overview/cdk-dialog-overview-example.html
  src/components-examples/cdk/listbox/cdk-listbox-compare-with/cdk-listbox-compare-with-example.html
  src/components-examples/material/card/card-media-size/card-media-size-example.html
Labels: docs, action: merge, target: patch, merge: fix commit message

#26433 build: update to Angular 15.1 stable
  package.json
  yarn.lock
Labels: P3, action: merge, target: patch, area: build & ci

#26434 test(material/schematics): clean up deprecated API usage
  src/cdk/schematics/ng-add/index.spec.ts
  src/cdk/schematics/ng-generate/drag-drop/index.spec.ts
  src/cdk/schematics/testing/test-case-setup.ts
  src/material/schematics/ng-add/index.spec.ts
  src/material/schematics/ng-generate/address-form/index.spec.ts
  src/material/schematics/ng-generate/dashboard/index.spec.ts
  src/material/schematics/ng-generate/mdc-migration/rules/components/test-setup-helper.ts
  src/material/schematics/ng-generate/navigation/index.spec.ts
  src/material/schematics/ng-generate/table/index.spec.ts
  src/material/schematics/ng-generate/tree/index.spec.ts
Labels: action: merge, P4, target: patch

#26450 fix(material/schematics): don't migrate unknown stylesheet formats
  src/material/schematics/ng-generate/mdc-migration/rules/theming-styles.ts
  src/material/schematics/ng-generate/mdc-migration/rules/ts-migration/runtime-migration.ts
  src/material/schematics/ng-update/migrations/legacy-components-v15/index.ts
Labels: P3, action: merge, target: patch

#25962 fix(material/core): add checkmark for single-select
  src/dev-app/autocomplete/BUILD.bazel
  src/dev-app/autocomplete/autocomplete-demo.html
  src/dev-app/autocomplete/autocomplete-demo.ts
  src/dev-app/checkbox/checkbox-demo.html
  src/dev-app/select/BUILD.bazel
  src/dev-app/select/select-demo.html
  src/dev-app/select/select-demo.scss
  src/dev-app/select/select-demo.ts
  src/material/autocomplete/autocomplete.spec.ts
  src/material/autocomplete/autocomplete.ts
  src/material/core/option/option-parent.ts
  src/material/core/option/option.html
  src/material/core/option/option.scss
  src/material/core/option/option.ts
  src/material/core/selection/pseudo-checkbox/_pseudo-checkbox-common.scss
  src/material/core/selection/pseudo-checkbox/_pseudo-checkbox-theme.scss
  src/material/core/selection/pseudo-checkbox/pseudo-checkbox.scss
  src/material/core/selection/pseudo-checkbox/pseudo-checkbox.ts
  src/material/select/select.spec.ts
  src/material/select/select.ts
  tools/public_api_guard/material/autocomplete.md
  tools/public_api_guard/material/core.md
  tools/public_api_guard/material/select.md
Labels: P2, a11y, action: merge, target: minor, area: material/autocomplete, area: material/core, area: material/select, dev-app preview

#26455 docs: release notes for the v15.1.1 release
  CHANGELOG.md
Labels: area: docs

#26458 refactor(material/menu): expose MenuCloseReason type
  src/material/menu/public-api.ts
  tools/public_api_guard/material/menu.md
Labels: action: merge, P4, target: patch

#26470 docs(theming) Fix densitites > densities typo in theming doc
  guides/theming.md
Labels: action: merge, target: patch, merge: fix commit message

#26471 fix(material/core): top-level font family not copied when converting between typography formats
  src/material/core/typography/_typography.scss
Labels: P3, action: merge, target: patch

#26377 fix(material/schematics): improve logging of mdc-migration ts migrator
  src/material/schematics/ng-generate/mdc-migration/rules/ts-migration/runtime-migration.ts
Labels: action: merge, target: patch

#26475 fix(material/schematics): add string literal check
  src/material/schematics/ng-generate/mdc-migration/rules/ts-migration/runtime-migration.ts
Labels: action: merge, target: patch

#26501 docs: release notes for the v15.1.2 release
  CHANGELOG.md
Labels: area: docs

#26447 fix(cdk/collections): SelectionModel does not always respect the compareWith function
  src/cdk/collections/selection-model.ts
  src/cdk/collections/selection.spec.ts
Labels: action: merge, target: patch

#26503 refactor(cdk/a11y): restrict setAttribute fanout capability
  src/cdk/a11y/aria-describer/aria-reference.ts
Labels: action: merge, target: patch

#26520 fix(google-maps): error if API is initialized incorrectly
  src/google-maps/map-event-manager.spec.ts
  src/google-maps/map-event-manager.ts
Labels: P3, action: merge, target: patch

#26443 docs(cdk/drag-drop): put back Episode V poster exemple ✨
  src/components-examples/cdk/drag-drop/cdk-drag-drop-custom-preview/cdk-drag-drop-custom-preview-example.ts
Labels: action: merge, target: patch, area: docs

#26324 fix(material/dialog): take dialog background from theme palette
  src/material/dialog/_dialog-theme.scss
Labels: P3, action: merge, target: patch

#26530 build: update angular shared dev-infra code
  .github/workflows/assistant-to-the-branch-manager.yml
  .github/workflows/build-dev-app.yml
  .github/workflows/deploy-dev-app.yml
  .github/workflows/dev-infra.yml
  .github/workflows/google-internal-tests.yml
  .github/workflows/lock-closed.yml
  WORKSPACE
  package.json
  packages.bzl
  scripts/build-packages-dist.mts
  scripts/create-legacy-tests-bundle.mjs
  tools/angular/BUILD.bazel
  tools/angular/esbuild.config.mjs
  yarn.lock
Labels: action: merge, target: patch, area: build & ci
