Repository angular/components, pull requests merged in 2023-07, with the labels that each got.

#27393 fix(material/core): throw better error messages from typography utils
  src/material/core/typography/_typography-utils.scss
Labels: P3, action: merge, target: patch

#27398 fix(material/button-toggle): not preserving value if preselected option is removed
  src/material/button-toggle/button-toggle.spec.ts
  src/material/button-toggle/button-toggle.ts
Labels: P3, action: merge, target: patch

#27400 docs: updated the comments in which removed the redundant phrase and added the comma to linked two sentence
  src/material/menu/menu-item.ts
  src/material/schematics/ng-generate/mdc-migration/rules/tree-traversal.ts
Labels: action: merge, target: patch, area: docs

#27401 fix(cdk/menu): control + option + space not working on VoiceOver
  src/cdk/menu/event-detection.ts
  src/cdk/menu/menu-item.ts
  src/cdk/menu/menu-trigger.ts
  tools/public_api_guard/cdk/menu.md
Labels: P2, action: merge, target: patch

#27405 fix(material/chips): error if empty getter is accessed too early
  src/material/chips/chip-set.spec.ts
  src/material/chips/chip-set.ts
Labels: action: merge, P4, target: patch

#27394 docs(google-maps): remove synchronous loading example
  src/google-maps/README.md
Labels: action: merge, target: patch, area: docs

#27407 fix(material/schematics): fix template diagnostic in table schematic
  src/material/schematics/ng-generate/table/files/__path__/__name@dasherize@if-flat__/__name@dasherize__.component.html.template
  src/material/schematics/ng-generate/table/files/__path__/__name@dasherize@if-flat__/__name@dasherize__.component.ts.template
Labels: action: merge, P4, target: patch

#27386 refactor(material/stepper): switch to tokens API
  src/material/core/tokens/_token-utils.scss
  src/material/core/tokens/m2/mat/_stepper.scss
  src/material/stepper/_stepper-theme.scss
  src/material/stepper/step-header.scss
  src/material/stepper/stepper.scss
Labels: P3, action: merge, target: patch

#27355 fix(material/sidenav): only trap focus when backdrop is enabled
  src/components-examples/material/sidenav/index.ts
  src/components-examples/material/sidenav/sidenav-configurable-focus-trap/sidenav-configurable-focus-trap-example.css
  src/components-examples/material/sidenav/sidenav-configurable-focus-trap/sidenav-configurable-focus-trap-example.html
  src/components-examples/material/sidenav/sidenav-configurable-focus-trap/sidenav-configurable-focus-trap-example.ts
  src/material/sidenav/drawer.spec.ts
  src/material/sidenav/drawer.ts
Labels: a11y, action: merge, target: minor, area: material/sidenav, dev-app preview

#27336 docs(material/chips): require communicating to AT how to edit a chip
  src/material/chips/chips.md
Labels: a11y, docs, action: merge, target: patch, area: material/chips, area: docs

#27377 refactor(material/menu): switch to tokens API
  src/material/core/tokens/m2/mat/_menu.scss
  src/material/menu/_menu-theme.scss
  src/material/menu/menu-trigger.ts
  src/material/menu/menu.scss
  tools/public_api_guard/material/menu.md
Labels: P3, action: merge, target: patch

#27411 build: add a script to detect component ID collisions
  package.json
  scripts/detect-component-id-collisions.ts
Labels: P3, action: merge, target: patch, area: build & ci

#27416 docs: release notes for the v16.1.4 release
  CHANGELOG.md
Labels: area: docs

#27309 refactor(material-experimental/theming): condense matx.theme and matx.retheme into a single mixin
  src/dev-app/theme-token-api.scss
  src/material-experimental/_index.scss
  src/material-experimental/theming/README.md
  src/material-experimental/theming/_theming.scss
  src/material/card/_card-theme.scss
  src/material/checkbox/_checkbox-theme.scss
Labels: action: merge, target: minor

#27422 fix(material/autocomplete): clear selected option if input is cleared
  src/material/autocomplete/autocomplete-trigger.ts
  src/material/autocomplete/autocomplete.spec.ts
  src/material/core/option/option.ts
  tools/public_api_guard/material/core.md
Labels: P3, action: merge, target: patch

#27390 refactor(material/expansion): switch to tokens API
  src/material/core/tokens/_token-utils.scss
  src/material/core/tokens/m2/mat/_expansion.scss
  src/material/expansion/_expansion-legacy-index.scss
  src/material/expansion/_expansion-mixins.import.scss
  src/material/expansion/_expansion-mixins.scss
  src/material/expansion/_expansion-theme.import.scss
  src/material/expansion/_expansion-theme.scss
  src/material/expansion/expansion-panel-header.scss
  src/material/expansion/expansion-panel.scss
Labels: P3, action: merge, target: patch

#27432 fix(material/autocomplete): blocking events to other overlays when there are no results
  src/material/autocomplete/autocomplete-trigger.ts
  src/material/autocomplete/autocomplete.spec.ts
Labels: P3, action: merge, target: patch

#27423 feat(material/autocomplete): add input to require selection from the panel
  src/components-examples/material/autocomplete/autocomplete-require-selection/autocomplete-require-selection-example.css
  src/components-examples/material/autocomplete/autocomplete-require-selection/autocomplete-require-selection-example.html
  src/components-examples/material/autocomplete/autocomplete-require-selection/autocomplete-require-selection-example.ts
  src/components-examples/material/autocomplete/index.ts
  src/dev-app/autocomplete/autocomplete-demo.html
  src/dev-app/autocomplete/autocomplete-demo.ts
  src/material/autocomplete/autocomplete-trigger.ts
  src/material/autocomplete/autocomplete.html
  src/material/autocomplete/autocomplete.md
  src/material/autocomplete/autocomplete.spec.ts
  src/material/autocomplete/autocomplete.ts
  src/material/legacy-autocomplete/autocomplete.ts
  tools/public_api_guard/material/autocomplete.md
  tools/public_api_guard/material/legacy-autocomplete.md
Labels: P3, action: merge, target: minor, detected: feature

#27435 docs(material/menu): require only static content and MenuItems in popup
  src/material/menu/menu.md
Labels: a11y, action: merge, target: patch, area: material/menu, area: docs

#27438 fix(material/expansion): panel content visible when placed inside a hidden parent
  src/material/expansion/expansion-animations.ts
Labels: P3, action: merge, target: patch

#27433 ci: migrate lint job from CircleCI to GHA
  .circleci/config.yml
  .github/angular-robot.yml
  .github/workflows/ci.yml
Labels: action: merge, target: patch, area: build & ci

#26823 refactor(material/fab): change mat-fab to use MDC's token API
  src/material/button/_fab-theme.scss
  src/material/button/fab.scss
  src/material/core/tokens/m2/mdc/_extended-fab.scss
  src/material/core/tokens/m2/mdc/_fab.scss
  src/material/core/tokens/tests/test-validate-tokens.scss
Labels: action: merge, target: minor

#27409 feat(material-experimental/themeing): add M3 token values for checkbox and card
  src/dev-app/theme-token-api.scss
  src/material-experimental/_index.scss
  src/material-experimental/theming/_m3-tokens.scss
  src/material/card/_card-theme.scss
Labels: action: merge, target: minor, dev-app preview, detected: feature

#27451 docs(material/slider): make component example more intuitive
  src/components-examples/material/slider/slider-configurable/slider-configurable-example.html
Labels: action: merge, target: patch, area: docs

#27456 fix(cdk/clipboard): not working inside fullscreen element
  src/cdk/clipboard/pending-copy.ts
  src/dev-app/clipboard/clipboard-demo.html
Labels: P3, action: merge, target: patch

#27455 docs: release notes for the v16.1.5 release
  CHANGELOG.md
Labels: area: docs

#27465 fix(material/chips): ensure that edit input query is re-evaluated on time
  src/material/chips/chip-row.ts
Labels: P3, action: merge, target: patch, dev-app preview

#27466 fix(material/radio): clear selected radio button from group
  src/material/radio/radio.spec.ts
  src/material/radio/radio.ts
  tools/public_api_guard/material/radio.md
Labels: action: merge, P4, target: patch

#27391 fix(material/slide-toggle): add cursor pointer for label
  src/material/slide-toggle/slide-toggle.scss
Labels: action: merge, P4, target: patch

#27457 fix(material/chips): increase specificity of chip ripple selector
  src/material/chips/chip.scss
Labels: action: merge, target: patch

#27468 refactor(material/sidenav): switch to tokens API
  src/material/core/tokens/m2/mat/_sidenav.scss
  src/material/sidenav/_sidenav-theme.scss
  src/material/sidenav/drawer.scss
Labels: P3, action: merge, target: patch

#27453 feat(material-luxon-adapter): add option to set default calendar
  src/material-luxon-adapter/adapter/luxon-date-adapter.spec.ts
  src/material-luxon-adapter/adapter/luxon-date-adapter.ts
Labels: action: merge, target: minor, detected: feature

#27471 refactor(material/bottom-sheet): switch to token API
  src/material/bottom-sheet/BUILD.bazel
  src/material/bottom-sheet/_bottom-sheet-theme.scss
  src/material/bottom-sheet/bottom-sheet-container.scss
  src/material/core/tokens/m2/mat/_bottom-sheet.scss
Labels: P3, action: merge, target: patch

#27010 docs(material/form-field): add guide for handling unsubscribable error triggers in custom form field control
  guides/creating-a-custom-form-field-control.md
Labels: action: merge, target: patch, area: docs

#27102 fix(material/form-field): fix duplicate announcement of form controls
  src/material/chips/chip-grid.spec.ts
  src/material/datepicker/date-range-input.spec.ts
  src/material/form-field/form-field.html
  src/material/input/input.spec.ts
Labels: a11y, action: merge, target: patch, area: material/form-field, area: material/select, dev-app preview

#27472 fix(cdk/testing): sending incorrect keyCode for comma
  src/cdk/testing/testbed/fake-events/type-in-element.ts
  src/cdk/testing/tests/cross-environment.spec.ts
  src/cdk/testing/tests/harnesses/main-component-harness.ts
  src/cdk/testing/tests/test-main-component.ts
  src/material/chips/testing/BUILD.bazel
  src/material/chips/testing/chip-input-harness.spec.ts
Labels: P3, action: merge, target: patch

#27485 Revert "fix(cdk/testing): sending incorrect keyCode for comma (#27472)"
  src/cdk/testing/testbed/fake-events/type-in-element.ts
  src/cdk/testing/tests/cross-environment.spec.ts
  src/cdk/testing/tests/harnesses/main-component-harness.ts
  src/cdk/testing/tests/test-main-component.ts
  src/material/chips/testing/BUILD.bazel
  src/material/chips/testing/chip-input-harness.spec.ts
Labels: P3, action: merge, target: patch

#27479 refactor(material/toolbar): switch to tokens API
  src/material/core/tokens/_token-utils.scss
  src/material/core/tokens/m2/mat/_toolbar.scss
  src/material/toolbar/BUILD.bazel
  src/material/toolbar/_toolbar-theme.scss
  src/material/toolbar/toolbar.scss
Labels: P3, action: merge, target: patch

#27486 fix(cdk/testing): allow for comma key to be sent
  src/cdk/testing/protractor/protractor-element.ts
  src/cdk/testing/selenium-webdriver/selenium-webdriver-keys.ts
  src/cdk/testing/test-element.ts
  src/cdk/testing/testbed/unit-test-element.ts
  src/material/chips/testing/BUILD.bazel
  src/material/chips/testing/chip-input-harness.spec.ts
  tools/public_api_guard/cdk/testing.md
Labels: P3, action: merge, target: patch

#27492 refactor(material/badge): switch to tokens theming API
  src/material/badge/_badge-theme.scss
  src/material/core/tokens/m2/mat/_badge.scss
Labels: P3, action: merge, target: patch

#27478 refactor(material/divider): switch to tokens API
  src/material/core/tokens/m2/mat/_divider.scss
  src/material/divider/BUILD.bazel
  src/material/divider/_divider-theme.scss
  src/material/divider/divider.scss
Labels: P3, action: merge, target: patch

#27497 refactor(material/menu): remove MDC classes from markup
  src/material/menu/menu-item.html
  src/material/menu/menu-item.ts
  src/material/menu/menu.html
  src/material/menu/menu.scss
Labels: P3, action: merge, target: patch

#27488 ci: migrate api golden check to GHA
  .circleci/config.yml
  .github/workflows/ci.yml
Labels: action: merge, target: patch, area: build & ci, action: review

#27503 refactor(material/datepicker): switch to tokens API
  src/dev-app/datepicker/datepicker-demo.html
  src/material/core/theming/tests/theming-api.spec.ts
  src/material/core/tokens/m2/mat/_datepicker.scss
  src/material/datepicker/BUILD.bazel
  src/material/datepicker/_datepicker-theme.scss
  src/material/datepicker/calendar-body.scss
  src/material/datepicker/calendar.scss
  src/material/datepicker/date-range-input.scss
  src/material/datepicker/datepicker-content.scss
  src/material/datepicker/datepicker-toggle.scss
Labels: P3, action: merge, target: patch

#27499 fix(cdk/listbox): prevent wrong activeItemIndex after browser tab switch
  src/cdk/listbox/listbox.ts
  tools/public_api_guard/cdk/listbox.md
Labels: action: merge, target: patch

#27509 refactor(material/button-toggle): switch to tokens API
  src/material/button-toggle/_button-toggle-theme.scss
  src/material/button-toggle/_button-toggle-variables.scss
  src/material/button-toggle/button-toggle.scss
  src/material/core/tokens/m2/mat/_legacy-button-toggle.scss
  src/material/core/tokens/m2/mat/_standard-button-toggle.scss
Labels: P3, action: merge, target: patch

#27520 docs: release notes for the v16.1.6 release
  CHANGELOG.md
Labels: area: docs

#27524 refactor(material/icon): switch to tokens API
  src/material/core/tokens/m2/mat/_icon.scss
  src/material/icon/_icon-theme.scss
  src/material/icon/icon.scss
Labels: P3, action: merge, target: minor

#27533 refactor(material/grid-list): switch to tokens theming API
  src/material/core/tokens/m2/mat/_grid-list.scss
  src/material/grid-list/_grid-list-theme.scss
  src/material/grid-list/grid-list.scss
Labels: P3, action: merge, target: patch

#27537 docs : fix typos in styling files
  src/material/core/selection/pseudo-checkbox/_pseudo-checkbox-common.scss
  src/material/core/tokens/m2/mdc/_circular-progress.scss
  src/material/core/tokens/m2/mdc/_plain-tooltip.scss
  src/material/list/list.scss
Labels: action: merge, target: patch, merge: fix commit message

#27538 build: bump MDC version
  package.json
  packages.bzl
  yarn.lock
Labels: P3, action: merge, target: minor
