Repository angular/components, pull requests merged in 2023-03, with the labels that each got.

#26718 build: set up schematics for version 16
  src/cdk/schematics/migration.json
  src/cdk/schematics/ng-update/index.ts
  src/cdk/schematics/ng-update/migrations/misc-template.ts
  src/cdk/schematics/update-tool/target-version.ts
  src/material/schematics/migration.json
  src/material/schematics/ng-update/index.ts
  src/material/schematics/ng-update/migrations/legacy-components-v15/constants.ts
  src/material/schematics/ng-update/migrations/legacy-components-v15/index.ts
  src/material/schematics/ng-update/test-cases/v15/legacy-components-v15.spec.ts
Labels: action: merge, target: major, area: build & ci

#26727 fix(material/chips): unable to shift + tab out of a chip set
  src/material/chips/chip-set.ts
Labels: P3, a11y, action: merge, target: patch

#26725 fix(material/snack-bar): live region not working when modal is open
  src/material/legacy-snack-bar/snack-bar-container.html
  src/material/snack-bar/snack-bar-container.html
  src/material/snack-bar/snack-bar-container.ts
  tools/public_api_guard/material/snack-bar.md
Labels: P3, a11y, action: merge, G, target: patch

#26736 Change the throw in line 186 from string to error
  src/cdk-experimental/scrolling/auto-size-virtual-scroll.ts
Labels: action: merge, target: patch, merge: fix commit message

#26673 fix(material/core): mat-option sets aria-selected="false"
  src/material/core/option/option.ts
  src/material/legacy-core/option/option.ts
  src/material/legacy-select/select.spec.ts
  src/material/select/select.spec.ts
  tools/public_api_guard/material/core.md
Labels: a11y, action: merge, target: patch, area: material/autocomplete, area: material/core, area: material/select, dev-app preview

#26742 fix(material/datepicker): resolve server-side rendering error
  src/material/datepicker/calendar-body.ts
Labels: P3, action: merge, target: patch

#26636 refactor(material/progress-spinner): change mat-progress-spinner to u…
  src/material/core/tokens/m2/mdc/_circular-progress.scss
  src/material/core/tokens/tests/test-validate-tokens.scss
  src/material/progress-spinner/_progress-spinner-theme.scss
  src/material/progress-spinner/progress-spinner.scss
  src/material/progress-spinner/progress-spinner.ts
Labels: action: merge, target: major

#26746 fix(material/paginator): opt-out of single-selection indicator
  src/material/paginator/paginator.html
Labels: a11y, action: merge, target: patch, area: material/paginator, dev-app preview

#26751 docs: release notes for the v15.2.2 release
  CHANGELOG.md
Labels: area: docs

#26756 build: remove ts-node forking bug workaround
  package.json
  yarn.lock
Labels: action: merge, target: patch, area: build & ci

#26755 build: update to TypeScript 5.0
  integration/yarn-pnp-compat/.yarn/releases/yarn-3.3.1.cjs
  integration/yarn-pnp-compat/.yarn/releases/yarn-3.4.1.cjs
  integration/yarn-pnp-compat/.yarnrc.yml
  integration/yarn-pnp-compat/BUILD.bazel
  integration/yarn-pnp-compat/package.json
  integration/yarn-pnp-compat/yarn.lock
  package.json
  src/material/form-field/form-field.html
  src/material/legacy-form-field/form-field.html
  tools/tslint-rules/lifecycleHookInterfaceRule.ts
  tools/tslint-rules/memberNamingRule.ts
  tslint.json
  yarn.lock
Labels: P3, action: merge, target: major, area: build & ci

#26765 fix(material/chips): don't prevent default mousedown action
  src/material/chips/chip-row.spec.ts
  src/material/chips/chip-row.ts
  tools/public_api_guard/material/chips.md
Labels: P3, action: merge, G, target: patch

#26774 docs(material/chips): fix stacked chips example
  src/components-examples/material/chips/chips-stacked/chips-stacked-example.css
Labels: docs, action: merge, P4, target: patch, area: docs

#26763 refactor(multiple): Updated components to use host binding for ngSkipHydration
  src/cdk/table/table.ts
  src/material/autocomplete/autocomplete.ts
  src/material/chips/chip-listbox.ts
  src/material/legacy-autocomplete/autocomplete.ts
  src/material/legacy-chips/chip-list.ts
  src/material/legacy-form-field/form-field.ts
  src/material/legacy-menu/menu.ts
  src/material/legacy-select/select.ts
  src/material/legacy-table/table.ts
  src/material/legacy-tabs/tab-group.ts
  src/material/menu/menu.ts
  src/material/select/select.ts
  src/material/sidenav/drawer.ts
  src/material/sidenav/sidenav.ts
  src/material/sort/sort.ts
  src/material/stepper/stepper.ts
  src/material/table/table.ts
  src/material/tabs/tab-group.ts
Labels: action: merge, target: major

#26771 fix(material/chips): styling not cleared on basic chips in listbox and grid
  src/dev-app/chips/chips-demo.html
  src/dev-app/chips/chips-demo.scss
  src/material/chips/chip-option.ts
  src/material/chips/chip-set.ts
  src/material/chips/chip.scss
  src/material/chips/chip.ts
  tools/public_api_guard/material/chips.md
Labels: P3, action: merge, G, target: patch

#26710 fix(material/checkbox): fix ARIA semantics and use native DOM properties
  src/material/checkbox/checkbox.html
  src/material/checkbox/checkbox.spec.ts
  src/material/checkbox/checkbox.ts
  src/material/legacy-checkbox/checkbox.html
  src/material/legacy-checkbox/checkbox.spec.ts
  tools/public_api_guard/material/checkbox.md
Labels: a11y, action: merge, target: patch, area: material/checkbox, dev-app preview

#26737 fix(material/tabs): update MatTab _scrollToLabel function to always display a label from its start
  src/material/legacy-tabs/tab-header.spec.ts
  src/material/tabs/paginated-tab-header.ts
  src/material/tabs/tab-header.spec.ts
Labels: action: merge, target: patch

#26794 fix(material/chips): chip label appearing above sticky columns
  src/material/chips/chip.scss
Labels: P3, action: merge, target: patch

#26799 docs: release notes for the v15.2.3 release
  CHANGELOG.md
Labels: area: docs

#26777 Fix ommitted word 'in'
  guides/schematics.md
Labels: docs, action: merge, target: major, merge: fix commit message

#26809 build: update to TypeScript 5.0 final
  integration/mdc-migration/golden/yarn.lock
  integration/mdc-migration/sample-project/yarn.lock
  integration/ng-add-standalone/yarn.lock
  package.json
  yarn.lock
Labels: P3, action: merge, target: major, area: build & ci

#26770 fix(material/card): tokenize the card elevation
  src/material/card/_card-theme.scss
  src/material/card/card.scss
  src/material/core/tokens/_token-utils.scss
  src/material/core/tokens/m2/mdc/_elevated-card.scss
  src/material/core/tokens/m2/mdc/_outlined-card.scss
Labels: action: merge, target: minor

#26744 fix(material/checkbox): refactor to depend on @angular/material/core/tokens
  src/material/_index.scss
  src/material/checkbox/_checkbox-private.scss
  src/material/checkbox/_checkbox-theme.scss
  src/material/checkbox/checkbox.scss
  src/material/core/tokens/m2/mdc/_checkbox.scss
  src/material/core/tokens/tests/test-validate-tokens.scss
  src/material/list/_list-option-theme.import.scss
  src/material/list/_list-option-theme.scss
  src/material/list/_list-theme.import.scss
  src/material/list/_list-theme.scss
  src/material/list/list-option.scss
Labels: action: merge, target: minor, merge: fix commit message

#26786 fix(material/tooltip): only expand hover area on side closest to trigger
  src/material/tooltip/tooltip.scss
Labels: action: merge, P4, target: patch

#26749 fix(material/datepicker): date range input not marked as required when using reactive forms
  src/material/datepicker/date-range-input.spec.ts
  src/material/datepicker/date-range-input.ts
Labels: P3, action: merge, target: patch

#26811 fix(material/core): apply strong focus styles to selected option
  src/material/core/option/option.html
  src/material/core/option/option.scss
  src/material/core/option/option.spec.ts
  src/material/core/option/option.ts
Labels: a11y, action: merge, target: patch, area: material/autocomplete, area: material/core, area: material/select, dev-app preview

#26643 refactor(material/progress-bar): change mat-progress-bar to use MDC's…
  src/material/core/tokens/m2/mdc/_linear-progress.scss
  src/material/core/tokens/tests/test-validate-tokens.scss
  src/material/progress-bar/_progress-bar-theme.scss
  src/material/progress-bar/progress-bar.scss
Labels: action: merge, target: minor

#26826 build: ran 'browserlist --update-db' to fix integration tests
  integration/mdc-migration/sample-project/yarn.lock
  integration/ng-add-standalone/yarn.lock
  yarn.lock
Labels: action: merge, target: patch, area: build & ci

#26829 Revert "refactor(material/progress-bar): change mat-progress-bar to u…
  src/material/core/tokens/m2/mdc/_linear-progress.scss
  src/material/core/tokens/tests/test-validate-tokens.scss
  src/material/progress-bar/_progress-bar-theme.scss
  src/material/progress-bar/progress-bar.scss
Labels: action: merge, target: minor

#26828 docs: release notes for the v15.2.4 release
  CHANGELOG.md
Labels: area: docs

#26745 fix(material/core): allow keyboard navigation to disabled options
  src/dev-app/autocomplete/autocomplete-demo.html
  src/dev-app/autocomplete/autocomplete-demo.ts
  src/dev-app/select/select-demo.html
  src/dev-app/select/select-demo.ts
  src/material/autocomplete/autocomplete-trigger.ts
  src/material/autocomplete/autocomplete.spec.ts
  src/material/autocomplete/autocomplete.ts
  src/material/core/option/_option-theme.scss
  src/material/core/option/option.scss
  src/material/select/select.spec.ts
  src/material/select/select.ts
  tools/public_api_guard/material/autocomplete.md
  tools/public_api_guard/material/select.md
Labels: a11y, action: merge, target: minor, area: material/autocomplete, area: material/core, area: material/select

#26838 fix(material/datepicker): remove div as a child of button
  src/material/datepicker/calendar-body.html
  src/material/datepicker/calendar-body.scss
Labels: action: merge, P4, target: patch

#26840 fix(cdk/overlay): don't close if scroll is coming from inside overlay
  src/cdk/overlay/scroll/close-scroll-strategy.spec.ts
  src/cdk/overlay/scroll/close-scroll-strategy.ts
Labels: P3, action: merge, target: patch

#26851 feat(material/formfield): Add `mdc-label` class to `<label>`
  src/material/checkbox/checkbox.html
  src/material/radio/radio.html
  src/material/slide-toggle/slide-toggle.html
Labels: action: merge, target: major, merge: fix commit message, detected: feature

#26854 fix(google-maps): update to latest typings
  package.json
  src/google-maps/google-map/google-map.ts
  src/google-maps/map-marker/map-marker.ts
  src/google-maps/package.json
  tools/public_api_guard/google-maps/google-maps.md
  yarn.lock
Labels: P2, action: merge, target: major

#26857 Bump version to "v15.2.5" with changelog.
  CHANGELOG.md
  package.json
Labels: action: merge

#26859 docs: release notes for the v15.2.5 release
  CHANGELOG.md
Labels: area: docs

#26867 refactor(material/dialog): resolve lint error
  src/material/dialog/dialog.scss
Labels: action: merge, P4, target: major

#26824 feat(material/button): change to use MDC's token API
  src/material/button/_icon-button-theme.scss
  src/material/button/icon-button.scss
  src/material/core/tokens/m2/mdc/_icon-button.scss
  src/material/core/tokens/tests/test-validate-tokens.scss
Labels: action: merge, target: major, detected: feature
