Repository angular/components, pull requests merged in 2024-04, with the labels that each got.

#28800 fix(multiple): set nonce using setAttribute
  src/cdk-experimental/column-resize/resize-strategy.ts
  src/cdk-experimental/table-scroll-container/table-scroll-container.ts
  src/cdk/layout/media-matcher.ts
  src/youtube-player/youtube-player.ts
Labels: action: merge, target: patch

#28801 fix(material/sort): clear aria description on destroy
  src/material/sort/sort-header.ts
Labels: action: merge, G, target: patch

#28817 docs: release notes for the v17.3.3 release
  CHANGELOG.md
Labels: area: docs

#28815 test: Fix invalid test that breaks in zoneless
  src/cdk/overlay/dispatchers/overlay-keyboard-dispatcher.spec.ts
  tslint.json
Labels: action: merge, target: major

#28820 docs: fix typo in M3 themeing docs
  guides/material-3.md
Labels: docs, action: merge, target: patch, area: docs

#28825 fix(cdk/drag-drop): make sure event is cancelable before calling "preventDefault"
  src/cdk/drag-drop/drag-ref.ts
Labels: action: merge, target: patch, merge: fix commit message

#28830 fix(material/menu): invert arrow in RTL
  src/material/core/style/_menu-common.scss
Labels: action: merge, target: patch

#28853 build: remove engines field from package.json
  package.json
Labels: action: merge, target: patch, area: build & ci

#28846 fix(cdk/scrolling): fix virtual scrolling jankiness with run coalescing
  src/cdk/scrolling/virtual-scroll-viewport.ts
  src/dev-app/main.ts
Labels: action: merge, target: major

#28789 fix(material/list): nav list item border-radius
  src/material/core/tokens/m2/mat/_list.scss
  src/material/list/list.scss
Labels: action: merge, target: patch, dev-app preview

#28857 Add autosize virtual-scroll and popover edit to universal test app
  src/universal-app/BUILD.bazel
  src/universal-app/kitchen-sink/kitchen-sink.html
  src/universal-app/kitchen-sink/kitchen-sink.ts
  tsconfig.json
Labels: action: merge, target: patch, area: build & ci

#28863 docs(material/chips): added an example that corresponds to the title static chips
  src/components-examples/material/chips/chips-overview/chips-overview-example.html
Labels: action: merge, target: patch, area: docs

#28867 docs: release notes for the v17.3.4 release
  CHANGELOG.md
Labels: area: docs

#28257 docs(material/slider): value should go in the input tag
  src/material/slider/slider.md
Labels: action: merge, target: patch, area: docs

#28871 fix(cdk/observers): don't observe content of comments
  src/cdk/a11y/live-announcer/live-announcer.spec.ts
  src/cdk/observers/observe-content.spec.ts
  src/cdk/observers/observe-content.ts
  src/material/tabs/tab-header.spec.ts
Labels: action: merge, target: patch

#28835 fix(cdk/drag-drop): text selection not disabled inside shadow dom on firefox
  src/cdk/drag-drop/directives/drag.spec.ts
  src/cdk/drag-drop/drag-ref.ts
Labels: action: merge, target: patch

#28855 docs: replace incorrect word in M3 theming guide
  guides/material-3.md
Labels: action: merge, target: patch, area: docs

#28875 fix(material/tabs): remove dependency on NgClass
  src/material/tabs/tab-group.html
  src/material/tabs/tab-group.ts
  src/material/tabs/tab.ts
Labels: action: merge, target: patch

#28865 fix(material/datepicker): remove dependency on NgClass
  src/material/datepicker/datepicker-base.ts
  src/material/datepicker/datepicker-content.html
Labels: action: merge, target: patch

#28843 fix(material/autocomplete): panel not visible when opened from multiple triggers
  src/material/autocomplete/autocomplete-trigger.ts
  src/material/autocomplete/autocomplete.ts
  tools/public_api_guard/material/autocomplete.md
Labels: action: merge, target: patch

#28849 fix(material/autocomplete): remove dependency on NgClass
  src/material/autocomplete/autocomplete.html
  src/material/autocomplete/autocomplete.ts
  tools/public_api_guard/material/autocomplete.md
Labels: action: merge, target: patch

#28880 fix(material/core): throw better error when mixin doesn't support color variants
  src/material/core/tokens/_token-utils.scss
Labels: action: merge, target: patch

#28877 fix(material/menu): remove dependency on NgClass
  src/material/menu/menu.html
  src/material/menu/menu.ts
Labels: action: merge, target: patch

#28870 fix(cdk/observers): Run content changed callback in NgZone
  src/cdk/observers/observe-content.ts
  tools/public_api_guard/cdk/observers.md
Labels: action: merge, target: major

#28890 Revert "fix(cdk/scrolling): fix virtual scrolling jankiness with run coalescing (#28846)
  src/cdk/scrolling/virtual-scroll-viewport.ts
  src/dev-app/main.ts
Labels: action: merge, target: major

#28766 feat(material/schematics): Add custom M3 theme schematic
  guides/material-3.md
  guides/schematics.md
  package.json
  src/material/schematics/BUILD.bazel
  src/material/schematics/collection.json
  src/material/schematics/ng-generate/m3-theme/BUILD.bazel
  src/material/schematics/ng-generate/m3-theme/README.md
  src/material/schematics/ng-generate/m3-theme/index.spec.ts
  src/material/schematics/ng-generate/m3-theme/index.ts
  src/material/schematics/ng-generate/m3-theme/schema.d.ts
  src/material/schematics/ng-generate/m3-theme/schema.json
  tools/mdc-deps/add-to-package-json.ts
  tslint.json
  yarn.lock
Labels: action: merge, target: major, area: ng-generate, detected: feature, merge: squash commits

#28895 docs: release notes for the v17.3.5 release
  CHANGELOG.md
Labels: area: docs

#28892 feat(material/core): namespace m2-specific theming APIs
  integration/yarn-pnp-compat/src/styles.scss
  src/dev-app/theme.scss
  src/material-experimental/theming/_m3-tokens.scss
  src/material/_index.scss
  src/material/core/_m2.scss
  src/material/core/theming/tests/test-theming-bundle.scss
  src/material/core/theming/tests/theming-definition-api.spec.ts
  src/material/core/theming/tests/theming-inspection-api.spec.ts
  src/material/core/theming/tests/theming-mixin-api.spec.ts
  src/material/core/typography/_definition.scss
Labels: action: merge, target: major, detected: feature, detected: breaking change

#28901 refactor(material/core): move M2-specific theming APIs into a separate directory
  .github/CODEOWNERS
  src/material/_index.scss
  src/material/core/m2/_index.scss
  src/material/core/m2/_palette.scss
  src/material/core/m2/_theming.scss
  src/material/core/m2/_typography-utils.scss
  src/material/core/m2/_typography.scss
  src/material/core/theming/_m2-inspection.scss
  src/material/core/theming/_theming-deprecated.scss
  src/material/core/theming/_theming.scss
  src/material/core/theming/prebuilt/deeppurple-amber.scss
  src/material/core/theming/prebuilt/indigo-pink.scss
  src/material/core/theming/prebuilt/pink-bluegrey.scss
  src/material/core/theming/prebuilt/purple-green.scss
  src/material/core/theming/tests/test-css-variables-theme.scss
  src/material/core/theming/tests/test-theming-api.scss
  src/material/core/theming/tests/test-typography-font-family.scss
  src/material/core/theming/tests/theming-inspection-api.spec.ts
  src/material/core/tokens/_token-utils.scss
  src/material/core/tokens/m2/mat/_chip.scss
  src/material/core/tokens/m2/mat/_form-field.scss
  src/material/core/tokens/m2/mdc/_checkbox.scss
  src/material/core/tokens/m2/mdc/_chip.scss
  src/material/core/tokens/m2/mdc/_radio.scss
  src/material/core/typography/_all-typography.scss
  src/material/core/typography/_typography-utils.scss
  src/material/core/typography/_typography.scss
  src/material/core/typography/_versioning.scss
Labels: action: merge, target: major

#28897 refactor(material/theming): make batch-create-token-values more flexible
  src/material/checkbox/_checkbox-theme.scss
  src/material/core/tokens/_token-utils.scss
Labels: action: merge, target: major

#28899 docs(material/slide-toggle): add examples with labelPosition="before"
  src/components-examples/material/slide-toggle/slide-toggle-overview/slide-toggle-overview-example.html
  src/dev-app/slide-toggle/slide-toggle-demo.html
Labels: Accessibility, docs, action: merge, target: patch, area: material/slide-toggle, area: docs

#28854 fix(cdk): handle signal based items in list key manager
  src/cdk/a11y/key-manager/list-key-manager.ts
Labels: action: merge, target: patch, merge: fix commit message

#28907 build: fix lint error
  src/components-examples/material/sidenav/sidenav-drawer-overview/sidenav-drawer-overview-example.css
Labels: action: merge, target: patch, area: build & ci

#28913 feat(material/core): move Material 3 support into stable
  guides/material-3.md
  package.json
  packages.bzl
  src/dev-app/theme-m3.scss
  src/e2e-app/theme.scss
  src/material-experimental/BUILD.bazel
  src/material-experimental/_index.scss
  src/material-experimental/theming/BUILD.bazel
  src/material-experimental/theming/_color-api-back-compat.scss
  src/material/_index.scss
  src/material/core/theming/_color-api-backwards-compatibility.scss
  src/material/core/theming/_config-validation.scss
  src/material/core/theming/_definition.scss
  src/material/core/theming/_palettes.scss
  src/material/core/theming/prebuilt/azure-blue.scss
  src/material/core/theming/prebuilt/cyan-orange.scss
  src/material/core/theming/prebuilt/magenta-violet.scss
  src/material/core/theming/prebuilt/rose-red.scss
  src/material/core/theming/tests/m3-theme.spec.ts
  src/material/core/theming/tests/theming-definition-api.spec.ts
  src/material/core/theming/tests/theming-inspection-api.spec.ts
  src/material/core/theming/tests/theming-typography-hierarchy.spec.ts
  src/material/core/tokens/_custom-tokens.scss
  src/material/core/tokens/_density.scss
  src/material/core/tokens/_format-tokens.scss
  src/material/core/tokens/_m3-tokens.scss
  src/material/schematics/ng-add/index.spec.ts
  src/material/schematics/ng-add/theming/create-custom-theme.ts
  src/material/schematics/ng-generate/m3-theme/index.spec.ts
  src/material/schematics/ng-generate/m3-theme/index.ts
  src/universal-app/styles.scss
Labels: action: merge, target: major, detected: feature

#28918 build: update to the latest version of Angular
  integration/harness-e2e-cli/yarn.lock
  integration/ng-add-standalone/yarn.lock
  integration/ng-add/yarn.lock
  package.json
  src/dev-app/main.ts
  yarn.lock
Labels: action: merge, target: major, area: build & ci

#28915 build: fix webdriver tests
  src/cdk/testing/tests/webdriver.e2e.spec.ts
  src/e2e-app/components/component-harness-e2e.ts
  src/e2e-app/components/e2e-app/e2e-app.ts
Labels: action: merge, target: patch, area: build & ci

#28898 feat(material-experimental/theming): add ability to use sys variables
  src/dev-app/theme-m3.scss
  src/material/_index.scss
  src/material/core/style/_sass-utils.scss
  src/material/core/theming/_config-validation.scss
  src/material/core/theming/_definition.scss
  src/material/core/theming/tests/theming-definition-api.spec.ts
  src/material/core/tokens/_m3-tokens.scss
Labels: action: merge, target: minor, merge: fix commit message, detected: feature

#28910 feat(multiple): token overrides api
  src/material/_index.scss
  src/material/autocomplete/_autocomplete-theme.scss
  src/material/badge/_badge-theme.scss
  src/material/bottom-sheet/_bottom-sheet-theme.scss
  src/material/button-toggle/_button-toggle-theme.scss
  src/material/button/_button-theme.scss
  src/material/button/_fab-theme.scss
  src/material/button/_icon-button-theme.scss
  src/material/card/_card-theme.scss
  src/material/chips/_chips-theme.scss
  src/material/core/_core-theme.scss
  src/material/core/option/_optgroup-theme.scss
  src/material/core/option/_option-theme.scss
  src/material/core/ripple/_ripple-theme.scss
  src/material/core/selection/pseudo-checkbox/_pseudo-checkbox-theme.scss
  src/material/datepicker/_datepicker-theme.scss
  src/material/dialog/_dialog-theme.scss
  src/material/divider/_divider-theme.scss
  src/material/expansion/_expansion-theme.scss
  src/material/form-field/_form-field-theme.scss
  src/material/grid-list/_grid-list-theme.scss
  src/material/icon/_icon-theme.scss
  src/material/input/_input-theme.scss
  src/material/list/_list-theme.scss
  src/material/menu/_menu-theme.scss
  src/material/paginator/_paginator-theme.scss
  src/material/progress-bar/_progress-bar-theme.scss
  src/material/progress-spinner/_progress-spinner-theme.scss
  src/material/radio/_radio-theme.scss
  src/material/select/_select-theme.scss
  src/material/sidenav/_sidenav-theme.scss
  src/material/slide-toggle/_slide-toggle-theme.scss
  src/material/slider/_slider-theme.scss
  src/material/snack-bar/_snack-bar-theme.scss
  src/material/sort/_sort-theme.scss
  src/material/stepper/_stepper-theme.scss
  src/material/table/_table-theme.scss
  src/material/tabs/_tabs-theme.scss
  src/material/toolbar/_toolbar-theme.scss
  src/material/tooltip/_tooltip-theme.scss
  src/material/tree/_tree-theme.scss
Labels: action: merge, target: major, detected: feature

#28927 fix(material/core): add migration for M2 theming APIs
  src/material/schematics/ng-update/BUILD.bazel
  src/material/schematics/ng-update/index.ts
  src/material/schematics/ng-update/migrations/m2-theming-v18/index.ts
  src/material/schematics/ng-update/migrations/m2-theming-v18/migration.ts
  src/material/schematics/ng-update/test-cases/m2-theming.spec.ts
Labels: action: merge, target: major

#28946 fix(material/progress-bar): avoid CSP issues for apps not using buffer mode
  src/material/progress-bar/progress-bar.html
Labels: action: merge, target: patch

#28948 fix(multiple): remove label for attribute on non-native elements
  src/material/datepicker/date-range-input.ts
  src/material/form-field/form-field-control.ts
  src/material/form-field/form-field.html
  src/material/select/select.ts
  tools/public_api_guard/material/datepicker.md
  tools/public_api_guard/material/form-field.md
  tools/public_api_guard/material/select.md
Labels: action: merge, target: patch

#28944 fix(material/theming): restrict css color usage behind a flag
  src/material/core/style/_sass-utils.scss
  src/material/core/theming/_definition.scss
  src/material/core/tokens/_m3-tokens.scss
Labels: action: merge, target: major

#28959 build: fix patch deployment
  package.json
Labels: action: merge, target: patch, area: build & ci

#28962 docs: release notes for the v17.3.6 release
  CHANGELOG.md
Labels: area: docs

#28953 fix(material/theming): remove shadow css variable
  src/material/core/tokens/_m3-tokens.scss
Labels: action: merge, target: rc

#28963 fix(material/dialog): mark dialog content as scrollable
  src/material/dialog/dialog-content-directives.ts
  src/material/dialog/dialog.spec.ts
  tools/public_api_guard/material/dialog.md
Labels: action: merge, target: rc

#28975 fix(material/core): export all available M3 palettes
  guides/material-3.md
  src/material/_index.scss
Labels: action: merge, target: rc

#28968 fix(cdk/scrolling): fix virtual scrolling jankiness with run coalescing
  src/cdk/scrolling/virtual-scroll-viewport.ts
  src/dev-app/main.ts
Labels: action: merge, target: rc

#28980 fix(cdk/drag-drop): resolve incompatibility with property minification
  src/cdk/drag-drop/preview-ref.ts
Labels: action: merge, G, target: patch

#28979 fix(material/slide-toggle): no outline when selected in high contrast mode
  src/material/core/tokens/m2/mat/_switch.scss
  src/material/core/tokens/m3/mat/_switch.scss
  src/material/slide-toggle/slide-toggle.scss
Labels: action: merge, target: rc
