Repository angular/components, pull requests merged in 2024-05, with the labels that each got.

#28976 Preview popover fixes
  src/cdk/drag-drop/BUILD.bazel
  src/cdk/drag-drop/directives/drag.spec.ts
  src/cdk/drag-drop/drag-drop.ts
  src/cdk/drag-drop/preview-ref.ts
  src/cdk/drag-drop/resets.scss
Labels: action: merge, target: patch, merge: preserve commits

#28969 docs(cdk\drag-drop): Add table drag drop example
  src/cdk/drag-drop/drag-drop.md
  src/components-examples/cdk/drag-drop/BUILD.bazel
  src/components-examples/cdk/drag-drop/cdk-drag-drop-table/cdk-drag-drop-table-example.css
  src/components-examples/cdk/drag-drop/cdk-drag-drop-table/cdk-drag-drop-table-example.html
  src/components-examples/cdk/drag-drop/cdk-drag-drop-table/cdk-drag-drop-table-example.ts
  src/components-examples/cdk/drag-drop/index.ts
Labels: action: merge, target: patch, merge: fix commit message, area: docs

#28992 docs: release notes for the v18.0.0-rc.0 release
  CHANGELOG.md
Labels: area: docs

#28994 docs: release notes for the v17.3.7 release
  CHANGELOG.md
Labels: area: docs

#28996 fix(material/button): incorrect template for icon button anchor
  src/material/button/icon-button.ts
  tools/public_api_guard/material/button.md
Labels: action: merge, target: patch

#28997 fix(material/schematics): Change themeTypes to a single select instead of a multiselect prompt in M3 theme schematic
  src/material/schematics/ng-generate/m3-theme/README.md
  src/material/schematics/ng-generate/m3-theme/index.spec.ts
  src/material/schematics/ng-generate/m3-theme/index.ts
  src/material/schematics/ng-generate/m3-theme/schema.d.ts
  src/material/schematics/ng-generate/m3-theme/schema.json
Labels: action: merge, area: ng-generate, target: rc

#29001 fix(material/chips): highlighted not working in M3
  src/material/chips/chip.scss
Labels: action: merge, target: patch

#29003 build: update to the Angular v18 release candidate
  integration/harness-e2e-cli/yarn.lock
  integration/ng-add-standalone/yarn.lock
  integration/ng-add/yarn.lock
  package.json
  src/cdk-experimental/table-scroll-container/table-scroll-container.spec.ts
  yarn.lock
Labels: action: merge, area: build & ci, target: rc

#29005 fix(cdk/menu): allow for scroll strategy to be configured
  src/cdk/menu/context-menu-trigger.ts
  src/cdk/menu/menu-trigger-base.ts
  src/cdk/menu/menu-trigger.ts
  tools/public_api_guard/cdk/menu.md
Labels: action: merge, target: patch

#29000 fix(material/tooltip): Tooltip should mark for check when visibility …
  src/material/tooltip/tooltip.ts
Labels: action: merge, target: patch

#29019 docs: release notes for the v17.3.8 release
  CHANGELOG.md
Labels: area: docs

#29021 build: temporarily force local spawn strategy during release builds
  scripts/build-packages-dist.mts
Labels: action: merge, target: patch, area: build & ci

#29024 docs: release notes for the v18.0.0-rc.1 release
  CHANGELOG.md
Labels: area: docs

#29015 fix(material/core): ripple loader not working in shadow DOM
  src/material/button/button.spec.ts
  src/material/core/private/ripple-loader.ts
Labels: action: merge, target: rc

#29012 fix(material/core): ripple element not destroyed after trigger change
  src/material/core/ripple/ripple-renderer.ts
Labels: action: merge, target: patch

#29028 fix(material/datepicker): resolve repeater warnings in calendar
  src/material/datepicker/calendar-body.html
  src/material/datepicker/calendar-body.ts
  src/material/datepicker/month-view.html
  src/material/datepicker/month-view.ts
  tools/public_api_guard/material/datepicker.md
Labels: action: merge, target: rc

#28727 refactor(cdk/dialog): Remove use of focusInitialElementWhenReady
  src/cdk/dialog/dialog-container.ts
  src/cdk/dialog/dialog.spec.ts
  src/material/bottom-sheet/bottom-sheet.spec.ts
  src/material/dialog/dialog-container.ts
  src/material/dialog/dialog.spec.ts
  tslint.json
Labels: action: merge, target: rc

#29038 build: update to latest YouTube typings
  package.json
  src/youtube-player/package.json
  yarn.lock
Labels: action: merge, area: build & ci, target: rc

#29036 fix(cdk/observers): logs "ResizeObserver loop limit exceeded" errors
  src/cdk/observers/private/shared-resize-observer.ts
Labels: action: merge, target: patch

#29044 fix(cdk/overlay): skip trigger interactions in outside click event
  src/cdk/overlay/overlay-directives.ts
Labels: action: merge, target: patch

#29050 docs: release notes for the v17.3.9 release
  CHANGELOG.md
Labels: area: docs

#29052 docs: release notes for the v18.0.0-rc.2 release
  CHANGELOG.md
Labels: area: docs

#29042 fix(material/slider): aria-valuetext host binding should be onPush co…
  src/material/slider/slider-input.ts
  src/material/slider/slider-interface.ts
  src/material/slider/slider.ts
  tools/public_api_guard/material/slider.md
Labels: action: merge, target: patch

#29048 fix(material/chips): simplify repeat chip removal prevention
  src/material/chips/chip-grid.spec.ts
  src/material/chips/chip-input.ts
  src/material/chips/chip-row.spec.ts
  src/material/chips/chip.ts
  tools/public_api_guard/material/chips.md
Labels: action: merge, G, target: patch

#29055 fix(cdk/tree): implement typeahead label
  src/cdk/tree/tree.spec.ts
  src/cdk/tree/tree.ts
  src/components-examples/cdk/tree/cdk-tree-complex/cdk-tree-complex-example.html
  src/components-examples/cdk/tree/cdk-tree-custom-key-manager/cdk-tree-custom-key-manager-example.html
  src/components-examples/cdk/tree/cdk-tree-flat-children-accessor/cdk-tree-flat-children-accessor-example.html
  src/components-examples/cdk/tree/cdk-tree-flat-level-accessor/cdk-tree-flat-level-accessor-example.html
  src/components-examples/cdk/tree/cdk-tree-flat/cdk-tree-flat-example.html
  src/components-examples/cdk/tree/cdk-tree-nested-children-accessor/cdk-tree-nested-children-accessor-example.html
  src/components-examples/cdk/tree/cdk-tree-nested-level-accessor/cdk-tree-nested-level-accessor-example.html
  src/components-examples/cdk/tree/cdk-tree-nested/cdk-tree-nested-example.html
  src/components-examples/material/tree/tree-dynamic/tree-dynamic-example.html
  src/components-examples/material/tree/tree-flat-overview/tree-flat-overview-example.html
  src/components-examples/material/tree/tree-harness/tree-harness-example.html
  src/components-examples/material/tree/tree-loadmore/tree-loadmore-example.html
  src/components-examples/material/tree/tree-nested-overview/tree-nested-overview-example.html
  tools/public_api_guard/cdk/tree.md
Labels: action: merge

#29056 fix(cdk/drag-drop): defer loading reset styles
  src/cdk/drag-drop/drag-drop-registry.ts
  src/cdk/drag-drop/drag-drop.ts
  src/cdk/drag-drop/public-api.ts
Labels: action: merge, target: patch

#29054 docs: Move M2 theming information into separate guide
  guides/material-2.md
  guides/material-3.md
  guides/theming-your-components.md
  guides/theming.md
Labels: docs, action: merge, target: rc, area: docs

#29031 refactor(cdk/a11y): make focus-trap zoneless compatible
  src/cdk/a11y/focus-trap/focus-trap.ts
  src/cdk/dialog/dialog-container.ts
  tools/public_api_guard/cdk/a11y.md
  tslint.json
Labels: action: merge, target: rc

#29069 Bug #29047 - Glitchy password form field
  src/components-examples/material/form-field/form-field-prefix-suffix/form-field-prefix-suffix-example.html
  src/components-examples/material/form-field/form-field-prefix-suffix/form-field-prefix-suffix-example.ts
Labels: action: merge, merge: fix commit message, target: rc

#29067 docs: Update theming your components guide for M3 and move M2 specific info
  guides/material-2.md
  guides/theming-your-components.md
  guides/theming.md
Labels: action: merge, target: rc, area: docs

#29061 test(menu): remove provideZoneChangeDetection for all menu tests
  src/cdk/menu/context-menu-trigger.spec.ts
  src/cdk/menu/context-menu-trigger.ts
  src/cdk/menu/menu-item-checkbox.spec.ts
  src/cdk/menu/menu-item-radio.spec.ts
  src/cdk/menu/menu-item.spec.ts
  src/cdk/menu/menu-trigger.spec.ts
  src/cdk/menu/pointer-focus-tracker.spec.ts
  src/material/menu/menu.spec.ts
Labels: action: merge, target: rc

#29068 refactor(material/dialog): simplify structural styles
  src/material/core/tokens/m2/mat/_dialog.scss
  src/material/core/tokens/m2/mdc/_dialog.scss
  src/material/core/tokens/m3/mat/_dialog.scss
  src/material/core/tokens/m3/mdc/_dialog.scss
  src/material/dialog/_dialog-theme.scss
  src/material/dialog/_mdc-dialog-structure-overrides.scss
  src/material/dialog/dialog-container.html
  src/material/dialog/dialog.scss
Labels: action: merge, target: rc

#29087 docs: release notes for the v18.0.0-rc.3 release
  CHANGELOG.md
Labels: area: docs

#29094 docs: release notes for the v17.3.10 release
  CHANGELOG.md
Labels: area: docs

#29083 test: move some CDK tests to zoneless
  src/cdk/a11y/focus-monitor/focus-monitor.spec.ts
  src/cdk/a11y/focus-monitor/focus-monitor.zone.spec.ts
  src/cdk/a11y/live-announcer/live-announcer.spec.ts
  src/cdk/clipboard/copy-to-clipboard.spec.ts
  src/cdk/drag-drop/directives/drag.spec.ts
  src/cdk/drag-drop/directives/drag.zone.spec.ts
  src/cdk/drag-drop/directives/test-utils.spec.ts
  src/cdk/drag-drop/drag-drop.spec.ts
  src/cdk/listbox/listbox.spec.ts
  src/cdk/observers/observe-content.spec.ts
  src/cdk/overlay/overlay-directives.spec.ts
  src/cdk/overlay/overlay-directives.zone.spec.ts
Labels: action: merge, target: minor, area: build & ci

#29097 build: update to Angular v18 final
  integration/harness-e2e-cli/yarn.lock
  integration/ng-add-standalone/yarn.lock
  integration/ng-add/yarn.lock
  integration/yarn-pnp-compat/yarn.lock
  package.json
  yarn.lock
Labels: action: merge, area: build & ci, target: rc

#29099 docs: release notes for the v18.0.0 release
  CHANGELOG.md
Labels: area: docs

#29090 build: remove unused dependencies on platform-browser-dynamic
  src/components-examples/cdk/dialog/BUILD.bazel
  src/components-examples/material/autocomplete/BUILD.bazel
  src/components-examples/material/badge/BUILD.bazel
  src/components-examples/material/bottom-sheet/BUILD.bazel
  src/components-examples/material/button-toggle/BUILD.bazel
  src/components-examples/material/button/BUILD.bazel
  src/components-examples/material/card/BUILD.bazel
  src/components-examples/material/checkbox/BUILD.bazel
  src/components-examples/material/chips/BUILD.bazel
  src/components-examples/material/datepicker/BUILD.bazel
  src/components-examples/material/dialog/BUILD.bazel
  src/components-examples/material/divider/BUILD.bazel
  src/components-examples/material/expansion/BUILD.bazel
  src/components-examples/material/form-field/BUILD.bazel
  src/components-examples/material/grid-list/BUILD.bazel
  src/components-examples/material/icon/BUILD.bazel
  src/components-examples/material/input/BUILD.bazel
  src/components-examples/material/list/BUILD.bazel
  src/components-examples/material/menu/BUILD.bazel
  src/components-examples/material/paginator/BUILD.bazel
  src/components-examples/material/progress-bar/BUILD.bazel
  src/components-examples/material/progress-spinner/BUILD.bazel
  src/components-examples/material/radio/BUILD.bazel
  src/components-examples/material/select/BUILD.bazel
  src/components-examples/material/sidenav/BUILD.bazel
  src/components-examples/material/slide-toggle/BUILD.bazel
  src/components-examples/material/slider/BUILD.bazel
  src/components-examples/material/snack-bar/BUILD.bazel
  src/components-examples/material/sort/BUILD.bazel
  src/components-examples/material/stepper/BUILD.bazel
  src/components-examples/material/table/BUILD.bazel
  src/components-examples/material/tabs/BUILD.bazel
  src/components-examples/material/toolbar/BUILD.bazel
  src/components-examples/material/tooltip/BUILD.bazel
  src/components-examples/material/tree/BUILD.bazel
  src/material/datepicker/BUILD.bazel
Labels: action: merge, target: patch, area: build & ci

#29105 docs: fix broken links
  guides/material-2.md
  guides/theming-your-components.md
  guides/theming.md
Labels: action: merge, target: patch, area: docs

#29100 test: move some CDK tests to zoneless
  src/cdk/a11y/focus-monitor/focus-monitor.spec.ts
  src/cdk/a11y/focus-monitor/focus-monitor.zone.spec.ts
  src/cdk/a11y/live-announcer/live-announcer.spec.ts
  src/cdk/clipboard/copy-to-clipboard.spec.ts
  src/cdk/drag-drop/directives/drag.spec.ts
  src/cdk/drag-drop/directives/drag.zone.spec.ts
  src/cdk/drag-drop/directives/test-utils.spec.ts
  src/cdk/drag-drop/drag-drop.spec.ts
  src/cdk/listbox/listbox.spec.ts
  src/cdk/observers/observe-content.spec.ts
  src/cdk/overlay/overlay-directives.spec.ts
  src/cdk/overlay/overlay-directives.zone.spec.ts
Labels: action: merge, target: patch

#29110 test: Make tests fail on errors and fix newly uncovered failures
  src/cdk-experimental/combobox/combobox.spec.ts
  src/cdk-experimental/scrolling/virtual-scroll-viewport.spec.ts
  src/cdk/listbox/listbox.spec.ts
  src/cdk/menu/menu-trigger.spec.ts
  src/cdk/menu/menu.spec.ts
  src/components-examples/material/checkbox/checkbox-harness/checkbox-harness-example.spec.ts
  src/components-examples/material/slide-toggle/slide-toggle-harness/slide-toggle-harness-example.spec.ts
  src/material/autocomplete/autocomplete.spec.ts
  src/material/bottom-sheet/bottom-sheet.spec.ts
  src/material/datepicker/datepicker.spec.ts
  src/material/dialog/testing/dialog-opener.spec.ts
  src/material/menu/menu.spec.ts
  src/material/stepper/stepper.spec.ts
  src/material/toolbar/toolbar.spec.ts
  test/angular-test-init-spec.ts
Labels: action: merge, target: patch

#29127 fix(youtube-player): error when interacting with the player before the API has been loaded
  src/youtube-player/youtube-player.ts
Labels: action: merge, target: patch

#29121 fix(material/tabs): avoid pagination infinite loop in safari
  src/material/tabs/paginated-tab-header.ts
Labels: action: merge, G, target: patch

#29126 build: fix deprecated husky install command
  package.json
Labels: action: merge, target: patch, area: build & ci

#29123 fix(material/form-field): outline label position
  src/material/form-field/form-field.ts
Labels: action: merge, target: patch, merge: fix commit message

#29132 Revert "fix(material/form-field): outline label position (#29123)"
  src/material/form-field/form-field.ts
Labels: action: merge, target: patch

#29131 test: fix overzealous calls to markForCheck from #29083
  src/cdk/a11y/live-announcer/live-announcer.spec.ts
  src/cdk/clipboard/copy-to-clipboard.spec.ts
  src/cdk/drag-drop/directives/drag.spec.ts
  src/cdk/drag-drop/directives/test-utils.spec.ts
  src/cdk/drag-drop/drag-drop-registry.ts
  src/cdk/drag-drop/drag-drop.spec.ts
  src/cdk/drag-drop/drag-ref.ts
  src/cdk/listbox/listbox.spec.ts
  src/cdk/listbox/listbox.ts
  src/cdk/observers/observe-content.spec.ts
  src/cdk/overlay/overlay-directives.spec.ts
Labels: action: merge, target: patch

#29103 test: move some CDK tests to zoneless
  src/cdk/overlay/overlay.spec.ts
  src/cdk/overlay/scroll/close-scroll-strategy.spec.ts
  src/cdk/overlay/scroll/close-scroll-strategy.zone.spec.ts
  src/cdk/portal/portal.spec.ts
  src/cdk/scrolling/scrollable.spec.ts
  src/cdk/scrolling/virtual-scroll-viewport.spec.ts
  src/cdk/scrolling/virtual-scroll-viewport.zone.spec.ts
Labels: action: merge, target: patch

#29143 docs: release notes for the v18.0.1 release
  CHANGELOG.md
Labels: area: docs

#29108 fix(material/slider): Tick marks changes position as the slider is changed (for a step that is decimal number)
  src/material/slider/slider.ts
Labels: action: merge, target: patch

#29136 refactor(material/checkbox): simplify structural styles
  src/material/checkbox/_checkbox-common.scss
  src/material/checkbox/_checkbox-theme.scss
  src/material/checkbox/checkbox.scss
  src/material/core/tokens/m2/mdc/_checkbox.scss
  src/material/list/BUILD.bazel
  src/material/list/_list-item-hcm-indicator.scss
  src/material/list/_list-theme.scss
  src/material/list/list-option.scss
Labels: action: merge, target: patch

#29144 test: Move more CDK tests to zoneless
  src/cdk/a11y/focus-trap/focus-trap.spec.ts
  src/cdk/menu/menu-base.ts
  src/cdk/menu/menu-trigger.spec.ts
  src/cdk/menu/menu.spec.ts
  src/cdk/table/table.spec.ts
  src/cdk/table/text-column.spec.ts
  src/cdk/text-field/autofill.spec.ts
  src/cdk/text-field/autofill.zone.spec.ts
  src/cdk/text-field/autosize.spec.ts
  src/cdk/tree/tree.spec.ts
  src/cdk/tree/tree.ts
Labels: action: merge, target: patch
