Repository angular/components, pull requests merged in 2024-06, with the labels that each got.

#29169 refactor(material/schematics): add project name for theme styles & backwards compatibility
  src/material/schematics/ng-add/theming/create-custom-theme.ts
Labels: action: merge, target: patch

#29168 refactor(material/table): simplify structural styles
  src/dev-app/main.ts
  src/material/core/style/_vendor-prefixes.scss
  src/material/table/table.scss
Labels: action: merge, target: patch

#29171 fix(material/schematics): theming API migration not working with CRLF line endings
  src/material/schematics/ng-update/migrations/m2-theming-v18/migration.ts
  src/material/schematics/ng-update/test-cases/m2-theming.spec.ts
Labels: action: merge, target: patch

#29137 fix(material/datepicker): Move aria-live attribute so month can also …
  src/material/datepicker/calendar-header.html
Labels: Accessibility, action: merge, target: patch, area: material/datepicker

#29166 refactor(material/snack-bar): clean up structural styles
  src/material/snack-bar/_snack-bar-theme.scss
  src/material/snack-bar/snack-bar-container.html
  src/material/snack-bar/snack-bar-container.scss
  src/material/snack-bar/snack-bar-container.ts
Labels: action: merge, target: patch

#29184 fix(material/core): hide ripples inside drag&drop elements
  src/material/core/ripple/_ripple.scss
Labels: action: merge, target: patch

#29082 fix(material/radio): Ensure focus and selected states stay linked
  src/material/radio/radio.ts
Labels: Accessibility, action: merge, target: patch

#29176 fix(cdk/testing): TestbedHarnessEnvironment should work when Zone is …
  src/cdk/testing/testbed/testbed-harness-environment.ts
Labels: action: merge, target: patch

#29181 test: Convert tests for cdk-experimental, components-examples, google-maps, youtube-player to zoneless
  src/cdk-experimental/combobox/combobox.spec.ts
  src/cdk-experimental/combobox/combobox.ts
  src/cdk-experimental/popover-edit/popover-edit.spec.ts
  src/cdk-experimental/table-scroll-container/table-scroll-container.spec.ts
  src/components-examples/material/checkbox/checkbox-harness/checkbox-harness-example.spec.ts
  src/components-examples/material/slide-toggle/slide-toggle-harness/slide-toggle-harness-example.spec.ts
  src/google-maps/google-map/google-map.spec.ts
  src/google-maps/map-ground-overlay/map-ground-overlay.spec.ts
  src/google-maps/map-heatmap-layer/map-heatmap-layer.spec.ts
  src/google-maps/map-marker-clusterer/map-marker-clusterer.spec.ts
  src/youtube-player/youtube-player.spec.ts
Labels: action: merge, target: patch

#29193 test: Extend zoneless lint to cover tests
  src/cdk/scrolling/scroll-dispatcher.spec.ts
  src/cdk/scrolling/scroll-dispatcher.zone.spec.ts
  src/cdk/scrolling/viewport-ruler.spec.ts
  src/cdk/scrolling/viewport-ruler.zone.spec.ts
  src/cdk/text-field/autofill.zone.spec.ts
  src/dev-app/main.ts
  src/material-experimental/popover-edit/popover-edit.spec.ts
  tools/tslint-rules/noZoneDependenciesRule.ts
  tslint.json
Labels: action: merge, target: patch

#29201 docs: release notes for the v18.0.2 release
  CHANGELOG.md
Labels: area: docs

#29139 feat(material/core): add option to configure prefix of system variables
  src/material/core/theming/_config-validation.scss
  src/material/core/theming/_definition.scss
  src/material/core/tokens/_m3-tokens.scss
  src/material/schematics/ng-generate/m3-theme/README.md
Labels: action: merge, target: minor, detected: feature

#29204 test: Convert some material tests to zoneless
  src/material/autocomplete/autocomplete-trigger.ts
  src/material/autocomplete/autocomplete.spec.ts
  src/material/autocomplete/autocomplete.zone.spec.ts
  src/material/badge/testing/badge-harness.spec.ts
  src/material/bottom-sheet/bottom-sheet.spec.ts
  src/material/button-toggle/button-toggle.spec.ts
  src/material/button-toggle/testing/button-toggle-group.spec.ts
  src/material/button-toggle/testing/button-toggle-harness.spec.ts
  src/material/button/button.spec.ts
  src/material/checkbox/checkbox.spec.ts
Labels: action: merge, target: patch

#29199 build: broaden ownership to team
  .github/CODEOWNERS
Labels: action: merge, target: patch, area: build & ci

#29180 fix(material/snack-bar): fix overrides mixin name typo
  src/material/_index.scss
Labels: action: merge, target: patch

#29203 fix(material/radio): mark radio-group for check on touch
  src/material/radio/radio.ts
Labels: action: merge, target: patch

#29205 test(material/dialog): Open dialogs inside NgZone
  src/material/dialog/testing/dialog-opener.ts
Labels: action: merge, target: patch

#28995 fix(material/divider): non-text color contrast issues
  src/dev-app/list/list-demo.scss
  src/material/core/tokens/m3/mat/_divider.scss
  src/material/core/tokens/m3/mat/_expansion.scss
  src/material/core/tokens/m3/mat/_stepper.scss
  src/material/core/tokens/m3/mat/_table.scss
Labels: action: merge, target: minor, dev-app preview

#29195 fix(material/dialog): Make autofocus work with animations disabled
  src/cdk/dialog/dialog-container.ts
  src/material/dialog/dialog-container.ts
  src/material/dialog/dialog.spec.ts
Labels: action: merge, target: patch

#29213 test(material/bottom-sheet): fix broken tests
  src/material/bottom-sheet/bottom-sheet.spec.ts
Labels: action: merge, target: patch

#29209 docs(cdk/dialog): add initial setup instructions for CDK dialogs
  src/cdk/dialog/dialog.md
Labels: action: merge, target: patch, area: docs

#29217 build: update to TypeScript 5.5
  integration/harness-e2e-cli/yarn.lock
  integration/ng-add-standalone/BUILD.bazel
  integration/ng-add-standalone/package.json
  integration/ng-add-standalone/tsconfig.json
  integration/ng-add-standalone/yarn.lock
  integration/ng-add/BUILD.bazel
  integration/ng-add/package.json
  integration/ng-add/tsconfig.json
  integration/ng-add/yarn.lock
  package.json
  src/google-maps/google-map/google-map.ts
  src/google-maps/map-advanced-marker/map-advanced-marker.ts
  src/google-maps/map-anchor-point.ts
  src/google-maps/map-base-layer.ts
  src/google-maps/map-bicycling-layer/map-bicycling-layer.ts
  src/google-maps/map-circle/map-circle.ts
  src/google-maps/map-directions-renderer/map-directions-renderer.ts
  src/google-maps/map-directions-renderer/map-directions-service.ts
  src/google-maps/map-geocoder/map-geocoder.ts
  src/google-maps/map-ground-overlay/map-ground-overlay.ts
  src/google-maps/map-heatmap-layer/map-heatmap-layer.ts
  src/google-maps/map-info-window/map-info-window.ts
  src/google-maps/map-kml-layer/map-kml-layer.ts
  src/google-maps/map-marker-clusterer/map-marker-clusterer.ts
  src/google-maps/map-marker-clusterer/marker-clusterer-types.ts
  src/google-maps/map-marker/map-marker.ts
  src/google-maps/map-polygon/map-polygon.ts
  src/google-maps/map-polyline/map-polyline.ts
  src/google-maps/map-rectangle/map-rectangle.ts
  src/google-maps/map-traffic-layer/map-traffic-layer.ts
  src/google-maps/map-transit-layer/map-transit-layer.ts
  src/material-luxon-adapter/adapter/luxon-date-adapter.ts
  src/universal-app/BUILD.bazel
  src/youtube-player/youtube-player.ts
  tools/public_api_guard/cdk/drag-drop.md
  tools/public_api_guard/cdk/layout.md
  tools/public_api_guard/cdk/menu.md
  tools/public_api_guard/cdk/overlay.md
  tools/public_api_guard/cdk/table.md
  tools/public_api_guard/cdk/tree.md
  tools/public_api_guard/material/autocomplete.md
  tools/public_api_guard/material/bottom-sheet.md
  tools/public_api_guard/material/core.md
  tools/public_api_guard/material/sort.md
  tools/public_api_guard/material/tree.md
  yarn.lock
Labels: action: merge, target: minor, area: build & ci

#29192 fix(material/dialog): Make focus behavior consistent across zoneful/zoneless apps
  src/cdk/dialog/dialog-container.ts
Labels: action: merge, target: patch

#29231 fix(material/schematics): estimate missing hues in M3 schematic
  src/material/core/theming/_palettes.scss
  src/material/schematics/ng-generate/m3-theme/index.spec.ts
  src/material/schematics/ng-generate/m3-theme/index.ts
Labels: action: merge, target: patch

#29232 docs: remove the MDC migration guide
  guides/v15-mdc-migration.md
  src/material/core/m2/_typography.scss
  src/material/slider/slider-interface.ts
Labels: docs, action: merge, target: patch, area: docs

#29237 refactor(cdk/dialog): Consolidate afterNextRender calls
  src/cdk/dialog/dialog-container.ts
Labels: action: merge, target: patch

#29236 docs(material/datepicker): Update datepicker docs & examples
  src/components-examples/material/datepicker/date-range-picker-comparison/date-range-picker-comparison-example.ts
  src/components-examples/material/datepicker/date-range-picker-forms/date-range-picker-forms-example.ts
  src/components-examples/material/datepicker/date-range-picker-overview/date-range-picker-overview-example.ts
  src/components-examples/material/datepicker/date-range-picker-selection-strategy/date-range-picker-selection-strategy-example.ts
  src/components-examples/material/datepicker/datepicker-actions/datepicker-actions-example.html
  src/components-examples/material/datepicker/datepicker-actions/datepicker-actions-example.ts
  src/components-examples/material/datepicker/datepicker-api/datepicker-api-example.ts
  src/components-examples/material/datepicker/datepicker-color/datepicker-color-example.css
  src/components-examples/material/datepicker/datepicker-color/datepicker-color-example.html
  src/components-examples/material/datepicker/datepicker-color/datepicker-color-example.ts
  src/components-examples/material/datepicker/datepicker-custom-header/datepicker-custom-header-example.ts
  src/components-examples/material/datepicker/datepicker-custom-icon/datepicker-custom-icon-example.ts
  src/components-examples/material/datepicker/datepicker-date-class/datepicker-date-class-example.ts
  src/components-examples/material/datepicker/datepicker-disabled/datepicker-disabled-example.ts
  src/components-examples/material/datepicker/datepicker-events/datepicker-events-example.html
  src/components-examples/material/datepicker/datepicker-events/datepicker-events-example.ts
  src/components-examples/material/datepicker/datepicker-filter/datepicker-filter-example.ts
  src/components-examples/material/datepicker/datepicker-formats/datepicker-formats-example.ts
  src/components-examples/material/datepicker/datepicker-harness/datepicker-harness-example.html
  src/components-examples/material/datepicker/datepicker-harness/datepicker-harness-example.ts
  src/components-examples/material/datepicker/datepicker-inline-calendar/datepicker-inline-calendar-example.html
  src/components-examples/material/datepicker/datepicker-inline-calendar/datepicker-inline-calendar-example.ts
  src/components-examples/material/datepicker/datepicker-locale/datepicker-locale-example.html
  src/components-examples/material/datepicker/datepicker-locale/datepicker-locale-example.ts
  src/components-examples/material/datepicker/datepicker-min-max/datepicker-min-max-example.html
  src/components-examples/material/datepicker/datepicker-min-max/datepicker-min-max-example.ts
  src/components-examples/material/datepicker/datepicker-moment/datepicker-moment-example.ts
  src/components-examples/material/datepicker/datepicker-overview/datepicker-overview-example.ts
  src/components-examples/material/datepicker/datepicker-start-view/datepicker-start-view-example.ts
  src/components-examples/material/datepicker/datepicker-touch/datepicker-touch-example.ts
  src/components-examples/material/datepicker/datepicker-value/datepicker-value-example.ts
  src/components-examples/material/datepicker/datepicker-views-selection/datepicker-views-selection-example.ts
  src/components-examples/material/datepicker/index.ts
  src/material/datepicker/datepicker-base.ts
  src/material/datepicker/datepicker.md
Labels: action: merge, target: patch, area: docs

#29235 docs(material/chips): Update chips docs & examples
  src/components-examples/material/chips/chips-autocomplete/chips-autocomplete-example.html
  src/components-examples/material/chips/chips-autocomplete/chips-autocomplete-example.ts
  src/components-examples/material/chips/chips-avatar/chips-avatar-example.html
  src/components-examples/material/chips/chips-avatar/chips-avatar-example.ts
  src/components-examples/material/chips/chips-drag-drop/chips-drag-drop-example.html
  src/components-examples/material/chips/chips-drag-drop/chips-drag-drop-example.ts
  src/components-examples/material/chips/chips-form-control/chips-form-control-example.html
  src/components-examples/material/chips/chips-form-control/chips-form-control-example.ts
  src/components-examples/material/chips/chips-harness/chips-harness-example.ts
  src/components-examples/material/chips/chips-input/chips-input-example.html
  src/components-examples/material/chips/chips-input/chips-input-example.ts
  src/components-examples/material/chips/chips-overview/chips-overview-example.ts
  src/components-examples/material/chips/chips-stacked/chips-stacked-example.html
  src/components-examples/material/chips/chips-stacked/chips-stacked-example.ts
  src/material/chips/chip.ts
  src/material/chips/chips.md
Labels: action: merge, target: patch, area: docs

#29234 docs(material/checkbox): Update checkbox docs & examples
  src/components-examples/material/checkbox/checkbox-configurable/checkbox-configurable-example.html
  src/components-examples/material/checkbox/checkbox-configurable/checkbox-configurable-example.ts
  src/components-examples/material/checkbox/checkbox-harness/checkbox-harness-example.html
  src/components-examples/material/checkbox/checkbox-harness/checkbox-harness-example.spec.ts
  src/components-examples/material/checkbox/checkbox-harness/checkbox-harness-example.ts
  src/components-examples/material/checkbox/checkbox-overview/checkbox-overview-example.html
  src/components-examples/material/checkbox/checkbox-overview/checkbox-overview-example.ts
  src/components-examples/material/checkbox/checkbox-reactive-forms/checkbox-reactive-forms-example.ts
  src/material/checkbox/checkbox-config.ts
  src/material/checkbox/checkbox.md
  src/material/checkbox/checkbox.ts
Labels: action: merge, target: patch, area: docs

#29247 docs: release notes for the v18.0.3 release
  CHANGELOG.md
Labels: area: docs

#29238 test: Convert material chips tests to zoneless
  src/material/chips/chip-grid.spec.ts
  src/material/chips/chip-grid.ts
  src/material/chips/chip-input.spec.ts
  src/material/chips/chip-listbox.spec.ts
  src/material/chips/chip-option.spec.ts
  src/material/chips/chip-remove.spec.ts
  src/material/chips/chip-row.spec.ts
  src/material/chips/chip-row.ts
  src/material/chips/chip-set.spec.ts
  src/material/chips/chip-set.ts
  src/material/chips/chip.spec.ts
  src/material/chips/chip.ts
  src/material/chips/testing/chip-grid-harness.spec.ts
  src/material/chips/testing/chip-input-harness.spec.ts
  src/material/chips/testing/chip-listbox-harness.spec.ts
  src/material/chips/testing/chip-row-harness.spec.ts
  tools/public_api_guard/material/chips.md
Labels: action: merge, target: patch

#29245 docs(material/form-field): Update form-field docs & examples
  src/components-examples/material/form-field/form-field-appearance/form-field-appearance-example.ts
  src/components-examples/material/form-field/form-field-custom-control/example-tel-input-example.html
  src/components-examples/material/form-field/form-field-custom-control/form-field-custom-control-example.html
  src/components-examples/material/form-field/form-field-custom-control/form-field-custom-control-example.ts
  src/components-examples/material/form-field/form-field-error/form-field-error-example.html
  src/components-examples/material/form-field/form-field-error/form-field-error-example.ts
  src/components-examples/material/form-field/form-field-harness/form-field-harness-example.ts
  src/components-examples/material/form-field/form-field-hint/form-field-hint-example.html
  src/components-examples/material/form-field/form-field-hint/form-field-hint-example.ts
  src/components-examples/material/form-field/form-field-label/form-field-label-example.html
  src/components-examples/material/form-field/form-field-label/form-field-label-example.ts
  src/components-examples/material/form-field/form-field-overview/form-field-overview-example.ts
  src/components-examples/material/form-field/form-field-prefix-suffix/form-field-prefix-suffix-example.html
  src/components-examples/material/form-field/form-field-prefix-suffix/form-field-prefix-suffix-example.ts
  src/components-examples/material/form-field/form-field-theming/form-field-theming-example.css
  src/components-examples/material/form-field/form-field-theming/form-field-theming-example.html
  src/components-examples/material/form-field/form-field-theming/form-field-theming-example.ts
  src/components-examples/material/form-field/index.ts
  src/material/form-field/form-field.md
  src/material/form-field/form-field.ts
Labels: action: merge, target: patch, area: docs

#29242 docs(material/dialog): Update dialog examples
  src/components-examples/material/dialog/dialog-animations/dialog-animations-example.ts
  src/components-examples/material/dialog/dialog-content/dialog-content-example.ts
  src/components-examples/material/dialog/dialog-elements/dialog-elements-example.ts
  src/components-examples/material/dialog/dialog-from-menu/dialog-from-menu-example.ts
  src/components-examples/material/dialog/dialog-harness/dialog-harness-example.ts
  src/components-examples/material/dialog/dialog-overview/dialog-overview-example-dialog.html
  src/components-examples/material/dialog/dialog-overview/dialog-overview-example.html
  src/components-examples/material/dialog/dialog-overview/dialog-overview-example.ts
Labels: action: merge, target: patch, area: docs

#29244 docs(material/expansion): Update expansion docs & examples
  src/components-examples/material/expansion/expansion-expand-collapse-all/expansion-expand-collapse-all-example.html
  src/components-examples/material/expansion/expansion-expand-collapse-all/expansion-expand-collapse-all-example.ts
  src/components-examples/material/expansion/expansion-harness/expansion-harness-example.ts
  src/components-examples/material/expansion/expansion-overview/expansion-overview-example.html
  src/components-examples/material/expansion/expansion-overview/expansion-overview-example.ts
  src/components-examples/material/expansion/expansion-steps/expansion-steps-example.html
  src/components-examples/material/expansion/expansion-steps/expansion-steps-example.ts
  src/material/expansion/expansion.md
Labels: action: merge, target: patch, area: docs

#29243 docs(material/divider): Update divider examples
  src/components-examples/material/divider/divider-harness/divider-harness-example.ts
  src/components-examples/material/divider/divider-overview/divider-overview-example.ts
Labels: action: merge, target: patch, area: docs

#29249 fix(cdk/overlay): incorrectly dispatching outside click for shadow DOM
  src/cdk/overlay/dispatchers/overlay-outside-click-dispatcher.ts
Labels: action: merge, target: patch

#29251 docs(material/core): list out pre-built themes
  guides/getting-started.md
  guides/schematics.md
  guides/theming.md
Labels: docs, action: merge, target: patch, area: docs

#28982 fix(material/autocomplete): autocomplete panel top is cut off in landscape mode
  src/material/autocomplete/autocomplete-trigger.ts
  src/material/autocomplete/autocomplete.spec.ts
Labels: action: merge, target: patch

#29252 docs(material/button): update button documentation and examples for M3
  src/components-examples/material/button/button-overview/button-overview-example.html
  src/components-examples/material/button/button-types/button-types-example.css
  src/components-examples/material/button/button-types/button-types-example.html
  src/components-examples/material/button/button-types/button-types-example.ts
  src/components-examples/material/button/index.ts
  src/material/button/button-base.ts
  src/material/button/button.md
Labels: action: merge, target: patch, area: docs

#29254 Update color input comments to standarize across the components
  src/material/button/button-base.ts
  src/material/checkbox/checkbox.ts
  src/material/chips/chip.ts
  src/material/datepicker/datepicker-base.ts
  src/material/form-field/form-field.ts
  src/material/list/selection-list.ts
  src/material/paginator/paginator.ts
  src/material/radio/radio.ts
  src/material/slide-toggle/slide-toggle.ts
  src/material/stepper/step-header.ts
  src/material/stepper/stepper.ts
  src/material/tabs/tab-nav-bar/tab-nav-bar.ts
  src/material/toolbar/toolbar.ts
Labels: action: merge, target: patch, area: many, area: docs

#29256 docs(material/button-toggle): Update docs and examples
  src/components-examples/material/button-toggle/BUILD.bazel
  src/components-examples/material/button-toggle/button-toggle-appearance/button-toggle-appearance-example.ts
  src/components-examples/material/button-toggle/button-toggle-exclusive/button-toggle-exclusive-example.css
  src/components-examples/material/button-toggle/button-toggle-exclusive/button-toggle-exclusive-example.html
  src/components-examples/material/button-toggle/button-toggle-exclusive/button-toggle-exclusive-example.ts
  src/components-examples/material/button-toggle/button-toggle-forms/button-toggle-forms-example.ts
  src/components-examples/material/button-toggle/button-toggle-harness/button-toggle-harness-example.ts
  src/components-examples/material/button-toggle/button-toggle-mode/button-toggle-mode-example.html
  src/components-examples/material/button-toggle/button-toggle-mode/button-toggle-mode-example.ts
  src/components-examples/material/button-toggle/index.ts
  src/material/button-toggle/button-toggle.md
Labels: docs, action: merge, target: patch, area: docs

#29257 fix(material/core): generate mat-optgroup tokens in M3
  src/material/core/_core-theme.scss
Labels: action: merge, target: patch

#29253 test: Convert some material tests to zoneless
  src/material/core/ripple/ripple.spec.ts
  src/material/core/testing/option-harness.spec.ts
  src/material/datepicker/calendar-body.spec.ts
  src/material/datepicker/calendar.spec.ts
  src/material/datepicker/date-range-input-parts.ts
  src/material/datepicker/date-range-input.spec.ts
  src/material/datepicker/date-range-input.ts
  src/material/datepicker/datepicker-actions.spec.ts
  src/material/datepicker/datepicker-base.ts
  src/material/datepicker/datepicker-input.ts
  src/material/datepicker/datepicker.spec.ts
  src/material/datepicker/month-view.spec.ts
  src/material/datepicker/multi-year-view.spec.ts
  src/material/datepicker/testing/calendar-harness.spec.ts
  src/material/datepicker/testing/date-range-input-harness.spec.ts
  src/material/datepicker/testing/datepicker-input-harness.spec.ts
  src/material/datepicker/testing/datepicker-toggle-harness.spec.ts
  src/material/datepicker/year-view.spec.ts
  tools/public_api_guard/material/datepicker.md
Labels: action: merge, target: patch

#29259 docs(material/card): Update card examples
  src/components-examples/material/card/BUILD.bazel
  src/components-examples/material/card/card-actions/card-actions-example.html
  src/components-examples/material/card/card-actions/card-actions-example.ts
  src/components-examples/material/card/card-fancy/card-fancy-example.html
  src/components-examples/material/card/card-fancy/card-fancy-example.ts
  src/components-examples/material/card/card-footer/card-footer-example.css
  src/components-examples/material/card/card-footer/card-footer-example.html
  src/components-examples/material/card/card-footer/card-footer-example.ts
  src/components-examples/material/card/card-harness/card-harness-example.ts
  src/components-examples/material/card/card-media-size/card-media-size-example.html
  src/components-examples/material/card/card-media-size/card-media-size-example.ts
  src/components-examples/material/card/card-overview/card-overview-example.html
  src/components-examples/material/card/card-overview/card-overview-example.ts
  src/components-examples/material/card/card-subtitle/card-subtitle-example.css
  src/components-examples/material/card/card-subtitle/card-subtitle-example.html
  src/components-examples/material/card/card-subtitle/card-subtitle-example.ts
  src/components-examples/material/card/index.ts
Labels: action: merge, target: patch, area: docs

#29261 build: fix missing elevation import
  src/material/core/tokens/m2/mat/_app.scss
Labels: action: merge, target: patch, area: build & ci

#29270 docs(material/card): remove unneeded null coalescing from example
  src/components-examples/material/card/card-harness/card-harness-example.spec.ts
Labels: action: merge, target: patch, area: docs

#29260 docs(material/icon): Update docs and examples
  src/components-examples/material/icon/icon-harness/icon-harness-example.ts
  src/components-examples/material/icon/icon-overview/icon-overview-example.ts
  src/components-examples/material/icon/icon-svg/icon-svg-example.ts
  src/material/icon/icon.md
  src/material/icon/icon.ts
Labels: docs, action: merge, target: patch, area: docs

#29267 refactor(material/menu): simplify structural styles
  src/material/menu/menu.scss
Labels: action: merge, target: patch

#29096 fix(material/tree): aria-expanded attribute should not appear in the leaf node
  src/cdk/tree/tree.spec.ts
  src/cdk/tree/tree.ts
  src/material/tree/tree.spec.ts
  tools/public_api_guard/cdk/tree.md
Labels: action: merge, target: patch

#29109 fix(material/paginator): items per page form field touch target size insufficient
  src/material/core/tokens/_density.scss
  src/material/core/tokens/m2/mat/_paginator.scss
  src/material/paginator/paginator.html
  src/material/paginator/paginator.scss
Labels: action: merge, target: patch, dev-app preview

#29269 refactor(material/core): simplify structural styles
  src/material/core/option/optgroup.scss
  src/material/core/option/option.scss
Labels: action: merge, target: patch

#29272 Revert "fix(material/tree): aria-expanded attribute should not appear in the leaf node (#29096)"
  src/cdk/tree/tree.spec.ts
  src/cdk/tree/tree.ts
  src/material/tree/tree.spec.ts
  tools/public_api_guard/cdk/tree.md
Labels: action: merge, target: patch

#29226 docs(material/tooltip): minor refresh to documentation
  src/material/tooltip/tooltip.md
Labels: action: merge, target: patch, area: docs

#29227 docs(material/toolbar): minor doc fixes
  src/components-examples/material/toolbar/index.ts
  src/components-examples/material/toolbar/toolbar-multirow/toolbar-multirow-example.html
  src/components-examples/material/toolbar/toolbar-overview/toolbar-overview-example.html
  src/components-examples/material/toolbar/toolbar-simple/toolbar-simple-example.html
  src/components-examples/material/toolbar/toolbar-simple/toolbar-simple-example.ts
  src/dev-app/toolbar/toolbar-demo.html
  src/dev-app/toolbar/toolbar-demo.ts
  src/material/toolbar/toolbar.md
Labels: action: merge, target: patch, area: docs

#29271 refactor(material/radio): simplify structural styles
  src/material/list/_list-theme.scss
  src/material/list/list-option.scss
  src/material/radio/_radio-common.scss
  src/material/radio/_radio-theme.scss
  src/material/radio/radio.scss
Labels: action: merge, target: patch

#29276 build: show ruler at 100 since we have a lint for it
  .vscode/settings.json
Labels: action: merge, target: patch, area: build & ci

#29274 build: fix rootDir
  src/material/tsconfig.json
Labels: action: merge, target: patch, area: build & ci

#29138 fix(material/form-field): outline label position
  src/material/form-field/form-field.ts
Labels: action: merge, target: patch

#29277 fix(material/bottom-sheet): changed after checked error with zoneless
  src/material/bottom-sheet/bottom-sheet-container.ts
Labels: action: merge, target: patch

#29282 Revert "fix(material/form-field): outline label position (#29138)"
  src/material/form-field/form-field.ts
Labels: action: merge, target: patch

#29279 build: configure vscode bazel integration
  .vscode/settings.json
Labels: action: merge, target: patch, area: build & ci

#29280 fix(material/menu): animation issue when same menu is used for multiple nested triggers
  src/material/menu/menu.scss
Labels: action: merge, G, target: patch

#29283 feat(cdk/drag-drop): add the ability to specify an alternate drop list container
  src/cdk/drag-drop/directives/drop-list-shared.spec.ts
  src/cdk/drag-drop/directives/drop-list.ts
  src/cdk/drag-drop/drop-list-ref.ts
  src/cdk/drag-drop/sorting/drop-list-sort-strategy.ts
  src/cdk/drag-drop/sorting/mixed-sort-strategy.ts
  src/cdk/drag-drop/sorting/single-axis-sort-strategy.ts
  tools/public_api_guard/cdk/drag-drop.md
Labels: action: merge, G, target: minor, detected: feature

#29289 docs: release notes for the v18.0.4 release
  CHANGELOG.md
Labels: area: docs

#29292 fix(material/sidenav): not closing on escape key press
  src/material/sidenav/drawer.ts
Labels: action: merge, target: patch

#29297 feat(material/button): allow button color to be configured through DI
  src/material/button/button-base.ts
  src/material/button/button.spec.ts
  tools/public_api_guard/material/button.md
Labels: action: merge, G, target: minor, detected: feature

#29305 docs: Fix usage of `effect` in examples
  src/components-examples/material/form-field/form-field-custom-control/form-field-custom-control-example.ts
Labels: action: merge, target: patch, area: docs

#29308 fix(material/button-toggle): skip disabled buttons during keyboard navigation
  src/material/button-toggle/button-toggle.ts
Labels: action: merge, target: patch

#29303 refactor(material/progress-bar): simplify structural styles
  src/material/core/style/_vendor-prefixes.scss
  src/material/progress-bar/_progress-bar-theme.scss
  src/material/progress-bar/progress-bar.scss
Labels: action: merge, target: patch

#29300 refactor(material/tooltip): simplify structural styles
  src/material/tooltip/_tooltip-theme.scss
  src/material/tooltip/tooltip.html
  src/material/tooltip/tooltip.scss
Labels: action: merge, target: patch

#29295 build: bump Angular to 18.1.0-next.3
  integration/harness-e2e-cli/package.json
  integration/harness-e2e-cli/yarn.lock
  integration/ng-add-standalone/package.json
  integration/ng-add-standalone/yarn.lock
  integration/ng-add/package.json
  integration/ng-add/yarn.lock
  package.json
  yarn.lock
Labels: action: merge, target: minor, area: build & ci

#29225 fix(cdk/a11y): Make focus-trap behavior consistent across zoneful/zoneless
  src/cdk/a11y/focus-trap/configurable-focus-trap-factory.ts
  src/cdk/a11y/focus-trap/configurable-focus-trap.ts
  src/cdk/a11y/focus-trap/event-listener-inert-strategy.spec.ts
  src/cdk/a11y/focus-trap/focus-trap.ts
  tools/public_api_guard/cdk/a11y.md
Labels: action: merge, target: patch

#29278 test: Convert some material tests to zoneless
  src/material/dialog/dialog.spec.ts
  src/material/dialog/dialog.zone.spec.ts
  src/material/expansion/accordion.spec.ts
  src/material/expansion/expansion.spec.ts
  src/material/expansion/testing/expansion-harness.spec.ts
  src/material/grid-list/grid-list.spec.ts
  src/material/icon/icon.spec.ts
  src/material/input/input.spec.ts
  src/material/list/list.spec.ts
  src/material/list/selection-list.spec.ts
  src/material/list/selection-list.ts
  src/material/menu/menu.spec.ts
  src/material/paginator/paginator.spec.ts
  src/material/progress-bar/progress-bar.spec.ts
  src/material/radio/radio.spec.ts
  src/material/radio/testing/radio-harness.spec.ts
Labels: action: merge, target: minor

#29309 test: Convert some material tests to zoneless
  src/material/core/ripple/ripple.spec.ts
  src/material/core/ripple/ripple.zone.spec.ts
  src/material/sidenav/drawer.spec.ts
  src/material/sidenav/sidenav.spec.ts
  src/material/slide-toggle/slide-toggle.spec.ts
  src/material/slider/slider.spec.ts
  src/material/snack-bar/snack-bar.spec.ts
  src/material/snack-bar/snack-bar.zone.spec.ts
  src/material/sort/sort.spec.ts
  src/material/tooltip/tooltip.spec.ts
  src/material/tooltip/tooltip.zone.spec.ts
  tslint.json
Labels: action: merge, target: patch

#29296 fix(multiple): remove workarounds for formControl directive
  src/material/autocomplete/autocomplete-trigger.ts
  src/material/chips/chip-grid.ts
  src/material/radio/radio.ts
  tools/public_api_guard/material/chips.md
Labels: action: merge, target: minor

#29291 fix(material/button): stack icons on top of touch target
  src/material/button/_button-base.scss
Labels: action: merge, target: patch

#29311 test: Convert some material tests to zoneless
  src/material/stepper/stepper.spec.ts
  src/material/tabs/tab-body.spec.ts
  src/material/tabs/tab-body.ts
  src/material/tabs/tab-group.spec.ts
  src/material/tabs/tab-header.spec.ts
  src/material/tabs/tab-nav-bar/tab-nav-bar.spec.ts
  tslint.json
Labels: action: merge, target: minor

#29314 refactor(material/tabs): simplify structural styles
  src/material/core/tokens/_density.scss
  src/material/core/tokens/m2/_index.scss
  src/material/core/tokens/m2/mdc/_secondary-navigation-tab.scss
  src/material/core/tokens/m3/_index.scss
  src/material/core/tokens/m3/mdc/_secondary-navigation-tab.scss
  src/material/core/tokens/tests/test-validate-tokens.scss
  src/material/tabs/_tabs-common.scss
  src/material/tabs/_tabs-theme.scss
Labels: action: merge, target: patch

#29321 docs(material/core): update the typography guide
  guides/typography.md
Labels: action: merge, target: patch, area: docs

#29320 build: update to TypeScript 5.5 stable
  integration/harness-e2e-cli/package.json
  integration/harness-e2e-cli/yarn.lock
  integration/ng-add-standalone/package.json
  integration/ng-add-standalone/yarn.lock
  integration/ng-add/package.json
  integration/ng-add/yarn.lock
  integration/yarn-pnp-compat/.yarn/releases/yarn-4.1.1.cjs
  integration/yarn-pnp-compat/.yarn/releases/yarn-4.3.1.cjs
  integration/yarn-pnp-compat/.yarnrc.yml
  integration/yarn-pnp-compat/package.json
  integration/yarn-pnp-compat/yarn.lock
  package.json
  yarn.lock
Labels: action: merge, target: minor, area: build & ci

#29318 ci: fix lint on patch branch
  tslint.json
Labels: action: merge, target: patch, area: build & ci

#29327 docs(material/list): Update description for color input description on API page
  src/material/list/list-option.ts
Labels: docs, action: merge, target: patch, area: docs

#29331 docs(material/progress-bar): Update description and examples for color input description on API page
  src/components-examples/material/progress-bar/progress-bar-configurable/progress-bar-configurable-example.html
  src/components-examples/material/progress-bar/progress-bar-configurable/progress-bar-configurable-example.ts
  src/material/progress-bar/progress-bar.md
  src/material/progress-bar/progress-bar.ts
Labels: docs, action: merge, target: patch, area: docs

#29332 docs(material/progress-spinner): Update description and examples for color input description on API page
  src/components-examples/material/progress-spinner/progress-spinner-configurable/progress-spinner-configurable-example.html
  src/components-examples/material/progress-spinner/progress-spinner-configurable/progress-spinner-configurable-example.ts
  src/material/progress-spinner/progress-spinner.md
  src/material/progress-spinner/progress-spinner.ts
Labels: docs, action: merge, target: patch, area: docs

#29335 docs(material/slider): Update description for color input description on API page
  src/material/slider/slider.ts
Labels: docs, action: merge, target: patch, area: docs

#29334 docs(material/slide-toggle): Update description and examples for color input description on API page
  src/components-examples/material/slide-toggle/slide-toggle-configurable/slide-toggle-configurable-example.html
  src/components-examples/material/slide-toggle/slide-toggle-configurable/slide-toggle-configurable-example.ts
  src/material/slide-toggle/slide-toggle-config.ts
  src/material/slide-toggle/slide-toggle.md
Labels: docs, action: merge, target: patch, area: docs

#29336 docs(material/tabs): Update description and examples for color input description on API page
  src/components-examples/material/tabs/index.ts
  src/components-examples/material/tabs/tab-group-theme/tab-group-theme-example.css
  src/components-examples/material/tabs/tab-group-theme/tab-group-theme-example.html
  src/components-examples/material/tabs/tab-group-theme/tab-group-theme-example.ts
  src/components-examples/material/tabs/tab-nav-bar-basic/tab-nav-bar-basic-example.html
  src/components-examples/material/tabs/tab-nav-bar-basic/tab-nav-bar-basic-example.ts
  src/dev-app/tabs/tabs-demo.html
  src/dev-app/tabs/tabs-demo.ts
  src/material/tabs/tab-group.ts
  src/material/tabs/tab-nav-bar/tab-nav-bar.ts
Labels: docs, action: merge, target: patch, area: docs

#29333 docs(material/radio): Update description for color input description on API page
  src/material/radio/radio.md
  src/material/radio/radio.ts
  tools/public_api_guard/material/radio.md
Labels: docs, action: merge, target: patch, area: docs

#29338 docs: release notes for the v18.0.5 release
  CHANGELOG.md
Labels: area: docs

#29319 test: Convert some material tests to zoneless
  src/google-maps/map-event-manager.spec.ts
  src/material/autocomplete/autocomplete.spec.ts
  src/material/autocomplete/autocomplete.zone.spec.ts
  src/material/dialog/dialog.spec.ts
  src/material/form-field/form-field.ts
  src/material/select/select.spec.ts
  tools/public_api_guard/material/form-field.md
  tools/tslint-rules/noZoneDependenciesRule.ts
  tslint.json
Labels: action: merge, target: minor

#29323 fix(material/core): add fallback if ripples get stuck
  src/material/core/ripple/ripple-renderer.ts
  src/material/slider/slider.spec.ts
Labels: action: merge, target: patch

#29345 docs: remove color property from remaining examples and overview pages and make description comment consistent across components
  src/components-examples/material/expansion/expansion-steps/expansion-steps-example.html
  src/components-examples/material/sidenav/sidenav-responsive/sidenav-responsive-example.html
  src/material/badge/badge.ts
  src/material/button/fab.ts
  src/material/checkbox/checkbox-config.ts
  src/material/checkbox/checkbox.md
  src/material/chips/chips.md
  src/material/datepicker/datepicker-base.ts
  src/material/datepicker/datepicker.md
  src/material/form-field/form-field.ts
  tools/public_api_guard/material/button.md
Labels: docs, action: merge, target: patch, area: docs

#29325 refactor(material/card): simplify structural styles
  src/material/card/_card-theme.scss
  src/material/card/card.scss
  src/material/core/tokens/m2/mdc/_elevated-card.scss
  src/material/core/tokens/m2/mdc/_outlined-card.scss
  src/material/core/tokens/m3/mdc/_elevated-card.scss
  src/material/core/tokens/m3/mdc/_outlined-card.scss
Labels: action: merge, target: patch

#29343 docs-bug(@angular/google-maps) - Update mapMarker to mapMarkerAdvance…
  src/google-maps/map-info-window/README.md
Labels: action: merge, target: patch, merge: fix commit message

#29342 refactor(material/button): simplify icon button structural styles
  src/material/button/_icon-button-theme.scss
  src/material/button/icon-button.scss
Labels: action: merge, target: patch
