Repository angular/components, pull requests merged in 2024-02, with the labels that each got.

#28519 docs(material/dialog): use h2 for dialog title
  src/cdk/dialog/dialog.spec.ts
  src/components-examples/material/dialog/dialog-animations/dialog-animations-example-dialog.html
  src/components-examples/material/dialog/dialog-data/dialog-data-example-dialog.html
  src/components-examples/material/dialog/dialog-elements/dialog-elements-example-dialog.html
  src/components-examples/material/dialog/dialog-overview/dialog-overview-example-dialog.html
  src/dev-app/slider/slider-demo.ts
  src/material/dialog/dialog.spec.ts
Labels: action: merge, target: patch, area: docs

#28520 [Cherry pick] fix(material/schematics): schema error in mdc migration
  src/material/schematics/ng-generate/mdc-migration/schema.json
Labels: P2, action: merge, target: lts

#28522 docs: release notes for the v16.2.14 release
  CHANGELOG.md
Labels: area: docs

#28518 refactor(material-experimental/theming): align sidenav with M3
  src/dev-app/dev-app/dev-app-layout.scss
  src/dev-app/theme-m3.scss
  src/material-experimental/theming/_custom-tokens.scss
  src/material/core/tokens/m2/mat/_sidenav.scss
  src/material/sidenav/drawer.scss
Labels: action: merge, target: minor

#28503 fix(material/slide-toggle): fix m3 slide-toggle handle
  src/material-experimental/theming/_custom-tokens.scss
  src/material-experimental/theming/_m3-tokens.scss
  src/material/core/tokens/m2/_index.scss
  src/material/core/tokens/m2/mat/_switch.scss
  src/material/slide-toggle/_slide-toggle-theme.scss
  src/material/slide-toggle/slide-toggle.scss
Labels: action: merge, target: minor

#28526 fix(material-experimental/theming): Make color API back-compat styles available
  src/dev-app/BUILD.bazel
  src/dev-app/theme-m3.scss
  src/material-experimental/_index.scss
  src/material-experimental/theming/_color-api-back-compat.scss
Labels: action: merge, target: minor

#28498 fix(material/chips): Tokenize the selected state
  src/dev-app/chips/chips-demo.html
  src/material-experimental/theming/_custom-tokens.scss
  src/material-experimental/theming/_m3-tokens.scss
  src/material/chips/_chips-theme.scss
  src/material/chips/chip.scss
  src/material/core/tokens/m2/_index.scss
  src/material/core/tokens/m2/mat/_chip.scss
  src/material/core/tokens/m2/mdc/_chip.scss
Labels: action: merge, target: minor

#28530 fix(material-experimental/theming): Fix chip trailing icon opacity in M3
  src/material-experimental/theming/_custom-tokens.scss
  src/material/chips/chip.scss
  src/material/core/tokens/m2/mat/_chip.scss
  src/material/core/tokens/m2/mdc/_chip.scss
Labels: action: merge, target: minor, dev-app preview

#28540 fix(material-experimental/theming): Make M3 work with typography-hierarchy
  src/dev-app/theme-m3.scss
  src/material/core/theming/tests/BUILD.bazel
  src/material/core/theming/tests/theming-typography-hierarchy.spec.ts
  src/material/core/typography/_typography.scss
Labels: action: merge, target: minor

#28549 docs(cdk/scrolling): fix typo
  src/cdk/scrolling/scrolling.md
Labels: docs, action: merge, target: patch, area: cdk/scrolling, area: docs

#28504 fix(material/list): use transparent background for M3
  src/material-experimental/theming/_m3-tokens.scss
Labels: action: merge, target: minor

#28555 test: Ensure M3 theme is well behaved
  src/material/core/theming/tests/m3-theme.spec.ts
Labels: action: merge, target: minor

#28532 fix(material/tabs): prevent page scroll on space press
  src/material/tabs/tab-nav-bar/tab-nav-bar.ts
Labels: action: merge, target: patch

#28541 fix(material/menu): prevent icon from collapsing when text is long
  src/material/menu/menu.scss
Labels: action: merge, target: patch

#28531 Fixing indexOf usage bug when selection-list handles changes in items.
  src/material/list/selection-list.spec.ts
  src/material/list/selection-list.ts
Labels: action: merge, target: patch

#28551 fix(cdk/table): error if outlets are assigned too early
  src/cdk/table/sticky-styler.ts
  src/cdk/table/table.ts
  tools/public_api_guard/cdk/table.md
Labels: action: merge, target: patch

#28533 refactor(material/core): remove private APIs from root export
  src/material/_index.scss
Labels: action: merge, target: rc

#28470 fix(material/menu): Update token values and styles for M3
  src/material-experimental/theming/_custom-tokens.scss
  src/material/core/style/_menu-common.scss
  src/material/core/tokens/m2/mat/_menu.scss
  src/material/menu/menu.scss
Labels: action: merge, target: minor, material spec, area: material/menu, dev-app preview, action: review

#28546 fix(material/form-field): container height in lower densities
  src/material/form-field/form-field.scss
Labels: action: merge, target: minor

#28561 fix(material-experimental/theming): Add more tests for M3 theme tokens
  src/material-experimental/theming/_custom-tokens.scss
  src/material-experimental/theming/_m3-density.scss
  src/material-experimental/theming/_m3-tokens.scss
  src/material/button/_button-theme.scss
  src/material/core/theming/_inspection.scss
  src/material/core/theming/tests/m3-theme.spec.ts
  src/material/core/theming/tests/theming-inspection-api.spec.ts
  src/material/core/tokens/m2/mat/_paginator.scss
  src/material/core/typography/_all-typography.scss
  src/material/paginator/_paginator-theme.scss
  src/material/paginator/paginator.scss
Labels: action: merge, target: rc

#28556 fix(material/datepicker): fix M3 styles
  src/dev-app/datepicker/datepicker-demo.html
  src/material-experimental/theming/_custom-tokens.scss
  src/material/core/tokens/m2/mat/_datepicker.scss
  src/material/datepicker/_datepicker-theme.scss
  src/material/datepicker/calendar.scss
  src/material/datepicker/datepicker-content.scss
Labels: action: merge, target: rc, dev-app preview

#28569 fix(material-experimental/theming): Fix token causing test failure on CI
  src/material-experimental/theming/_custom-tokens.scss
Labels: action: merge, target: rc

#28571 build: minor improvement to dev app density toggling
  src/dev-app/dev-app/dev-app-layout.html
  src/dev-app/dev-app/dev-app-layout.ts
Labels: action: merge, target: patch, area: build & ci

#28573 build: ensure component owners are assigned to public API changes
  .github/CODEOWNERS
Labels: action: merge, target: patch, area: build & ci

#28580 docs(material/list): fix m3 demo trailing icon color
  src/dev-app/list/list-demo.scss
Labels: action: merge, area: material/list, target: rc, dev-app preview, area: docs

#28565 fix(material/slide-toggle): m3 track outline and handle opacity
  src/material-experimental/theming/_custom-tokens.scss
  src/material/core/tokens/m2/mat/_switch.scss
  src/material/core/tokens/m2/mdc/_switch.scss
  src/material/slide-toggle/slide-toggle.scss
Labels: action: merge, target: rc

#28566 docs: Add a guide for M3 theming
  guides/material-3.md
Labels: action: merge, target: rc, area: docs

#28583 fix(cdk/listbox): unable to tab in if active option is removed
  src/cdk/listbox/listbox.spec.ts
  src/cdk/listbox/listbox.ts
Labels: action: merge, target: patch

#28577 fix(material/datepicker): fix touchui shadow and border-radius
  src/material-experimental/theming/_custom-tokens.scss
  src/material/core/tokens/m2/mat/_datepicker.scss
  src/material/datepicker/datepicker-content.scss
Labels: action: merge, target: rc

#28587 build: Update angular versions
  package.json
  src/universal-app/BUILD.bazel
  yarn.lock
Labels: action: merge, area: build & ci, target: rc

#28589 build: reduce implicit timeouts in webdriver test
  src/cdk/testing/tests/webdriver.e2e.spec.ts
Labels: action: merge, area: build & ci, target: rc

#28578 fix(material/button-toggle): Add remaining typography tokens needed for M3
  src/material-experimental/theming/_custom-tokens.scss
  src/material/button-toggle/button-toggle.scss
  src/material/core/tokens/m2/mat/_legacy-button-toggle.scss
  src/material/core/tokens/m2/mat/_standard-button-toggle.scss
Labels: action: merge, area: material/button-toggle, target: rc

#28592 docs: add blurb of M2 support
  guides/material-3.md
Labels: action: merge, target: rc, area: docs

#28593 docs: Add better documentation and errors regarding including theme mixins at root
  guides/material-3.md
  src/material/autocomplete/_autocomplete-theme.scss
  src/material/badge/_badge-theme.scss
  src/material/bottom-sheet/_bottom-sheet-theme.scss
  src/material/button-toggle/_button-toggle-theme.scss
  src/material/button/_button-theme.scss
  src/material/button/_fab-theme.scss
  src/material/button/_icon-button-theme.scss
  src/material/card/_card-theme.scss
  src/material/checkbox/_checkbox-theme.scss
  src/material/chips/_chips-theme.scss
  src/material/core/_core-theme.scss
  src/material/core/option/_optgroup-theme.scss
  src/material/core/option/_option-theme.scss
  src/material/core/ripple/_ripple-theme.scss
  src/material/core/selection/pseudo-checkbox/_pseudo-checkbox-theme.scss
  src/material/core/theming/_validation.scss
  src/material/core/theming/tests/m3-theme.spec.ts
  src/material/datepicker/_datepicker-theme.scss
  src/material/dialog/_dialog-theme.scss
  src/material/divider/_divider-theme.scss
  src/material/expansion/_expansion-theme.scss
  src/material/form-field/_form-field-theme.scss
  src/material/grid-list/_grid-list-theme.scss
  src/material/icon/_icon-theme.scss
  src/material/input/_input-theme.scss
  src/material/list/_list-theme.scss
  src/material/menu/_menu-theme.scss
  src/material/paginator/_paginator-theme.scss
  src/material/progress-bar/_progress-bar-theme.scss
  src/material/progress-spinner/_progress-spinner-theme.scss
  src/material/radio/_radio-theme.scss
  src/material/select/_select-theme.scss
  src/material/sidenav/_sidenav-theme.scss
  src/material/slide-toggle/_slide-toggle-theme.scss
  src/material/slider/_slider-theme.scss
  src/material/snack-bar/_snack-bar-theme.scss
  src/material/sort/_sort-theme.scss
  src/material/stepper/_stepper-theme.scss
  src/material/table/_table-theme.scss
  src/material/tabs/_tabs-theme.scss
  src/material/toolbar/_toolbar-theme.scss
  src/material/tooltip/_tooltip-theme.scss
  src/material/tree/_tree-theme.scss
Labels: action: merge, target: rc, area: docs

#28594 build: Update Angular to 17.2.0
  package.json
  yarn.lock
Labels: action: merge, area: build & ci, target: rc

#28586 fix(material/list): tokenize active-indicator
  src/dev-app/list/list-demo.html
  src/dev-app/list/list-demo.ts
  src/material-experimental/theming/_custom-tokens.scss
  src/material-experimental/theming/_m3-tokens.scss
  src/material/core/tokens/m2/mat/_list.scss
  src/material/list/list.scss
Labels: action: merge, area: material/list, target: rc, dev-app preview

#28596 docs: release notes for the v17.2.0 release
  CHANGELOG.md
Labels: area: docs

#28602 fix(cdk/listbox): make typeahead label nullable
  src/cdk/listbox/listbox.ts
  tools/public_api_guard/cdk/listbox.md
Labels: action: merge, target: patch

#28603 fix(material/expansion): center indicator icon in M3
  src/material-experimental/theming/_custom-tokens.scss
  src/material/core/tokens/m2/mat/_expansion.scss
  src/material/expansion/expansion-panel-header.html
  src/material/expansion/expansion-panel-header.scss
Labels: action: merge, target: patch

#28606 refactor(material/tabs): remove mixin function
  src/material/tabs/ink-bar.ts
  src/material/tabs/tab-label-wrapper.ts
  src/material/tabs/tab-nav-bar/tab-nav-bar.ts
  tools/public_api_guard/material/tabs.md
Labels: action: merge, target: patch

#28630 docs: release notes for the v17.2.1 release
  CHANGELOG.md
Labels: area: docs

#28628 fix(material/autocomplete): requireSelection sometimes not clearing value when editing after selection
  src/material/autocomplete/autocomplete-trigger.ts
  src/material/autocomplete/autocomplete.spec.ts
Labels: action: merge, target: patch

#28625 fix(material/slide-toggle): m3 selected track outline
  src/material-experimental/theming/_custom-tokens.scss
  src/material/core/tokens/m2/mat/_switch.scss
  src/material/slide-toggle/slide-toggle.scss
Labels: action: merge, target: patch

#28645 fix(material/schematics): add typography and density to custom theme
  guides/theming.md
  src/material/schematics/ng-add/theming/create-custom-theme.ts
Labels: P2, action: merge, target: patch

#28638 refactor(multiple): use object literal syntax in inputs array
  src/cdk-experimental/popover-edit/lens-directives.ts
  src/cdk-experimental/popover-edit/table-directives.ts
  src/cdk/menu/context-menu-trigger.ts
  src/cdk/menu/menu-trigger.ts
  src/cdk/portal/portal-directives.ts
  src/cdk/tree/node.ts
  src/material-experimental/column-resize/resizable-directives/common.ts
  src/material-experimental/popover-edit/lens-directives.ts
  src/material-experimental/popover-edit/table-directives.ts
  src/material-experimental/selection/row-selection.ts
  src/material-experimental/selection/selection-toggle.ts
  src/material/tabs/ink-bar.ts
  src/material/tabs/tab-label-wrapper.ts
  src/material/tree/node.ts
  src/material/tree/toggle.ts
  tools/public_api_guard/material/tabs.md
Labels: action: merge, target: patch

#28233 fix(cdk/overlay): fix overlay margin in isBoundedByLeftViewportEdge
  src/cdk/overlay/position/flexible-connected-position-strategy.spec.ts
  src/cdk/overlay/position/flexible-connected-position-strategy.ts
Labels: action: merge, target: patch

#28633 fix(cdk/drag-drop): resolve helper directives with DI for proper hostDirectives support
  src/cdk/drag-drop/directives/drag-handle.ts
  src/cdk/drag-drop/directives/drag-placeholder.ts
  src/cdk/drag-drop/directives/drag-preview.ts
  src/cdk/drag-drop/directives/drag.ts
  src/cdk/drag-drop/drag-parent.ts
  tools/public_api_guard/cdk/drag-drop.md
Labels: action: merge, target: patch

#28650 ci: pin dependency for actions/upload-artifact
  .github/workflows/ci.yml
Labels: action: merge, target: patch, area: build & ci

#28637 refactor(material/select): Remove use of zone onStable to wait for options
  src/material/select/select.ts
  tools/public_api_guard/material/select.md
Labels: action: merge, target: patch

#28553 fix(material/button-toggle): Add checkmark indicators with hideSingleSelectionIndicator and hideMultipleSelectionIndicator input and config options
  src/dev-app/button-toggle/button-toggle-demo.html
  src/dev-app/button-toggle/button-toggle-demo.ts
  src/material/button-toggle/button-toggle.html
  src/material/button-toggle/button-toggle.scss
  src/material/button-toggle/button-toggle.spec.ts
  src/material/button-toggle/button-toggle.ts
  tools/public_api_guard/material/button-toggle.md
Labels: Accessibility, action: merge, target: patch, area: material/button-toggle, dev-app preview

#28635 docs(material-3): fix typography config
  guides/material-3.md
Labels: action: merge, target: patch, area: docs

#26873 docs(material/form-field): custom MatFormFieldControl validation not …
  src/components-examples/material/form-field/form-field-custom-control/form-field-custom-control-example.ts
Labels: action: merge, target: patch, area: docs

#27251 perf(material/form-field): resolve scrolling performance issues
  src/material/form-field/_mdc-text-field-structure-overrides.scss
Labels: P2, action: merge, target: patch

#27512 feat(material/tooltip): be able to customize the longpress delay
  src/material/tooltip/tooltip.ts
  tools/public_api_guard/material/tooltip.md
Labels: feature, action: merge, target: minor, area: material/tooltip, detected: feature

#28664 fix(multiple): derive all token values from theme
  src/material/core/theming/_inspection.scss
  src/material/core/theming/tests/theming-inspection-api.spec.ts
  src/material/core/tokens/_token-utils.scss
  src/material/core/tokens/m2/mat/_datepicker.scss
  src/material/core/tokens/m2/mat/_fab-small.scss
  src/material/core/tokens/m2/mat/_fab.scss
  src/material/core/tokens/m2/mat/_filled-button.scss
  src/material/core/tokens/m2/mat/_form-field.scss
  src/material/core/tokens/m2/mat/_icon-button.scss
  src/material/core/tokens/m2/mat/_menu.scss
  src/material/core/tokens/m2/mat/_option.scss
  src/material/core/tokens/m2/mat/_outlined-button.scss
  src/material/core/tokens/m2/mat/_protected-button.scss
  src/material/core/tokens/m2/mat/_radio.scss
  src/material/core/tokens/m2/mat/_select.scss
  src/material/core/tokens/m2/mat/_tab-header.scss
  src/material/core/tokens/m2/mat/_text-button.scss
  src/material/core/tokens/m2/mdc/_dialog.scss
  src/material/core/tokens/m2/mdc/_filled-button.scss
  src/material/core/tokens/m2/mdc/_filled-text-field.scss
  src/material/core/tokens/m2/mdc/_outlined-button.scss
  src/material/core/tokens/m2/mdc/_outlined-text-field.scss
  src/material/core/tokens/m2/mdc/_protected-button.scss
  src/material/core/tokens/m2/mdc/_radio.scss
  src/material/core/tokens/m2/mdc/_text-button.scss
Labels: P2, action: merge, target: patch
