Repository angular/components, pull requests merged in 2024-08, with the labels that each got.

#29520 fix(material/tooltip): remove aria-describedby when disabled
  src/material/tooltip/tooltip.spec.ts
  src/material/tooltip/tooltip.ts
Labels: action: merge, target: minor

#29538 build: fix the approve-size-tests script
  goldens/size-test.yaml
  integration/size-test/BUILD.bazel
  integration/size-test/esbuild.config.mjs
Labels: action: merge, target: patch, area: build & ci

#29531 fix(material/chips): missing tokens in M3
  src/material/core/tokens/m3/mdc/_chip.scss
Labels: action: merge, target: patch

#29541 refactor(cdk/drag-drop): remove unnecessary type
  src/cdk/drag-drop/drop-list-ref.ts
Labels: action: merge, target: patch

#29542 refactor(cdk/drag-drop): remove unnecessary generics
  src/cdk/drag-drop/drag-drop-registry.spec.ts
  src/cdk/drag-drop/drag-drop-registry.ts
  src/cdk/drag-drop/drag-drop.ts
  src/cdk/drag-drop/drag-ref.ts
  src/cdk/drag-drop/drop-list-ref.ts
  src/cdk/drag-drop/sorting/mixed-sort-strategy.ts
  src/cdk/drag-drop/sorting/single-axis-sort-strategy.ts
  tools/public_api_guard/cdk/drag-drop.md
Labels: action: merge, target: patch

#29546 fix(material/list): checkmark not visible in high contrast mode
  src/material/checkbox/_checkbox-common.scss
  src/material/checkbox/checkbox.scss
Labels: action: merge, target: minor

#29548 fix(material/sidenav): disable focus trap while closed
  src/material/sidenav/drawer.spec.ts
  src/material/sidenav/drawer.ts
Labels: action: merge, target: patch

#29555 docs: release notes for the v18.1.4 release
  CHANGELOG.md
Labels: area: docs

#29550 feat(material/button-toggle): allow disabled buttons to be interactive
  src/dev-app/button-toggle/button-toggle-demo.html
  src/dev-app/button-toggle/button-toggle-demo.ts
  src/material/button-toggle/button-toggle.html
  src/material/button-toggle/button-toggle.scss
  src/material/button-toggle/button-toggle.spec.ts
  src/material/button-toggle/button-toggle.ts
  src/material/button-toggle/testing/button-toggle-harness.spec.ts
  src/material/button-toggle/testing/button-toggle-harness.ts
  tools/public_api_guard/material/button-toggle.md
Labels: action: merge, G, target: minor, detected: feature

#29091 Fix spelling mistakes that appear on the webapp
  CONTRIBUTING.md
  src/cdk/accordion/accordion-item.ts
  src/cdk/portal/portal.ts
  src/cdk/text-field/_index.scss
  src/material/core/datetime/native-date-adapter.ts
  src/material/core/tokens/m2/mat/_standard-button-toggle.scss
  src/material/core/tokens/m2/mdc/_checkbox.scss
  src/material/expansion/expansion-animations.ts
  src/material/form-field/_form-field-native-select.scss
  src/material/list/list-option.ts
Labels: action: merge, target: patch

#29529 build: remove ie-based lint rule
  .stylelintrc.json
Labels: action: merge, target: patch, area: build & ci

#29532 fix(material/autocomplete): typos and unresolved variables in tests
  src/material/autocomplete/autocomplete.spec.ts
Labels: action: merge, target: patch, merge: fix commit message

#29552 fix(material/tree): switch example to signals
  src/components-examples/material/tree/tree-dynamic/tree-dynamic-example.html
  src/components-examples/material/tree/tree-dynamic/tree-dynamic-example.ts
Labels: action: merge, merge: fix commit message, target: rc

#29568 build: move commit message check to be last in pipeline
  .github/workflows/pr.yml
Labels: action: merge, target: patch, area: build & ci

#29566 refactor(multiple): remove mdc-based descriptions
  src/material/autocomplete/autocomplete.spec.ts
  src/material/autocomplete/autocomplete.zone.spec.ts
  src/material/button/button.spec.ts
  src/material/button/testing/button-harness.ts
  src/material/card/card.spec.ts
  src/material/card/testing/card-harness.ts
  src/material/checkbox/checkbox.spec.ts
  src/material/chips/chip-edit-input.spec.ts
  src/material/chips/chip-grid.spec.ts
  src/material/chips/chip-input.spec.ts
  src/material/chips/chip-listbox.spec.ts
  src/material/chips/chip-option.spec.ts
  src/material/chips/chip-remove.spec.ts
  src/material/chips/chip-row.spec.ts
  src/material/chips/chip-set.spec.ts
  src/material/chips/chip.spec.ts
  src/material/core/testing/optgroup-harness.ts
  src/material/core/testing/option-harness.ts
  src/material/dialog/dialog.spec.ts
  src/material/dialog/dialog.zone.spec.ts
  src/material/dialog/testing/dialog-opener.spec.ts
  src/material/form-field/testing/error-harness.ts
  src/material/list/list.spec.ts
  src/material/list/selection-list.spec.ts
  src/material/list/testing/action-list-harness.ts
  src/material/list/testing/list-harness.ts
  src/material/list/testing/list-item-harness-base.ts
  src/material/list/testing/nav-list-harness.ts
  src/material/list/testing/selection-list-harness.ts
  src/material/menu/menu.spec.ts
  src/material/menu/testing/menu-harness.ts
  src/material/paginator/paginator.spec.ts
  src/material/progress-bar/progress-bar.spec.ts
  src/material/progress-bar/testing/progress-bar-harness.ts
  src/material/progress-spinner/progress-spinner.spec.ts
  src/material/radio/radio.spec.ts
  src/material/radio/testing/radio-harness.ts
  src/material/select/select.spec.ts
  src/material/select/testing/select-harness.ts
  src/material/slide-toggle/slide-toggle.spec.ts
  src/material/slider/slider.spec.ts
  src/material/slider/testing/slider-harness.spec.ts
  src/material/snack-bar/testing/snack-bar-harness.ts
  src/material/table/table.spec.ts
  src/material/tabs/tab-body.spec.ts
  src/material/tabs/tab-group.spec.ts
  src/material/tabs/tab-header.spec.ts
  src/material/tabs/tab-nav-bar/tab-nav-bar.spec.ts
  src/material/tabs/testing/tab-group-harness.ts
  src/material/tabs/testing/tab-link-harness.ts
  src/material/tabs/testing/tab-nav-bar-harness.ts
  src/material/tooltip/tooltip.spec.ts
  src/material/tooltip/tooltip.zone.spec.ts
Labels: action: merge, target: patch

#29536 fix(material/schematics): Generate more accurate tonal palettes for M3 schematic
  src/material/schematics/ng-generate/m3-theme/index.spec.ts
  src/material/schematics/ng-generate/m3-theme/index.ts
Labels: action: merge, target: patch

#29572 docs(material/chips): wrong example name
  src/material/chips/chips.md
Labels: action: merge, target: patch, area: docs

#29573 fix(material/form-field): update state if control changes
  src/material/form-field/form-field.ts
Labels: action: merge, target: patch

#29565 fix(cdk/tree): fix issue where `isExpanded` wouldn't be set if placed before `isExpandable`
  src/cdk/tree/tree.spec.ts
  src/cdk/tree/tree.ts
Labels: action: merge, target: minor

#29562 fix(material/tabs): allow for tablist aria-label and aria-labelledby to be set
  src/material/tabs/tab-group.html
  src/material/tabs/tab-group.spec.ts
  src/material/tabs/tab-group.ts
  src/material/tabs/tab-header.html
  src/material/tabs/tab-header.ts
  tools/public_api_guard/material/tabs.md
Labels: action: merge, target: patch

#29580 docs: release notes for the v18.1.5 release
  CHANGELOG.md
Labels: area: docs

#29582 docs: release notes for the v18.2.0 release
  CHANGELOG.md
Labels: area: docs

#29584 build: set up schematics for v19
  src/cdk/schematics/migration.json
  src/cdk/schematics/ng-update/index.ts
  src/cdk/schematics/ng-update/migrations/misc-template.ts
  src/cdk/schematics/update-tool/target-version.ts
  src/material/schematics/migration.json
  src/material/schematics/ng-update/data/css-tokens.ts
  src/material/schematics/ng-update/index.ts
  src/material/schematics/ng-update/migrations/m2-theming-v18/index.ts
  src/material/schematics/ng-update/migrations/m2-theming-v18/migration.ts
  src/material/schematics/ng-update/test-cases/m2-theming.spec.ts
  src/material/schematics/ng-update/test-cases/v18-renames.spec.ts
Labels: action: merge, target: major, area: build & ci

#29574 feat(material/input): add the ability to interact with disabled inputs
  src/dev-app/input/input-demo.html
  src/dev-app/input/input-demo.ts
  src/material/form-field/_mdc-text-field-structure.scss
  src/material/input/input.spec.ts
  src/material/input/input.ts
  src/material/input/public-api.ts
  src/material/input/testing/input-harness.spec.ts
  src/material/input/testing/input-harness.ts
  tools/public_api_guard/material/input.md
Labels: action: merge, G, target: major, detected: feature

#29588 refactor(multiple): fix initializers using constructor members
  src/cdk-experimental/column-resize/column-resize-notifier.ts
  src/cdk/a11y/interactivity-checker/interactivity-checker.spec.ts
  src/cdk/platform/platform.ts
  src/cdk/testing/testbed/task-state-zone-interceptor.ts
  src/material-experimental/selection/row-selection.ts
  src/material/dialog/dialog-container.ts
  src/material/select/select.ts
  tools/public_api_guard/cdk/platform.md
  tools/public_api_guard/material/dialog.md
  tools/public_api_guard/material/select.md
Labels: action: merge, target: major

#29589 fix(material/icon): update error message for missing HttpClient
  src/material/icon/icon-registry.ts
Labels: action: merge, target: patch

#29592 build: remove outdated `--non-interactive` yarn option from doc site install
  scripts/docs-deploy/docs-deps-install.mts
Labels: action: merge, target: patch, area: build & ci

#29598 build: use the new logo for the dev app favicon
  src/dev-app/favicon.ico
Labels: action: merge, target: patch, area: build & ci

#29603 fix(material/menu): inconsistent layout of submenu icon
  src/material/core/style/_menu-common.scss
Labels: action: merge, target: patch

#29606 fix(cdk/drag-drop): preview positioned incorrectly when RTL is set on the body
  src/cdk/drag-drop/directives/drop-list-shared.spec.ts
  src/cdk/drag-drop/preview-ref.ts
Labels: action: merge, target: patch

#29605 fix(material/tabs): switch pagination to not use native buttons
  src/material/tabs/_tabs-common.scss
  src/material/tabs/tab-header.html
  src/material/tabs/tab-nav-bar/tab-nav-bar.html
Labels: action: merge, target: patch

#29596 fix(multiple): account for mixed declarations in latest Sass version
  package.json
  src/material/badge/badge.scss
  src/material/button-toggle/button-toggle.scss
  src/material/button/_button-base.scss
  src/material/button/button.scss
  src/material/button/fab.scss
  src/material/button/icon-button.scss
  src/material/checkbox/_checkbox-common.scss
  src/material/checkbox/checkbox.scss
  src/material/chips/chip.scss
  src/material/core/option/option.scss
  src/material/core/selection/pseudo-checkbox/_pseudo-checkbox-theme.scss
  src/material/core/style/_list-common.scss
  src/material/core/theming/tests/m3-theme.spec.ts
  src/material/core/tokens/_m3-tokens.scss
  src/material/core/tokens/_token-utils.scss
  src/material/datepicker/calendar-body.scss
  src/material/dialog/dialog.scss
  src/material/expansion/expansion-panel.scss
  src/material/form-field/form-field.scss
  src/material/grid-list/grid-list.scss
  src/material/menu/menu.scss
  src/material/radio/radio.scss
  src/material/slide-toggle/_slide-toggle-theme.scss
  src/material/slide-toggle/slide-toggle.scss
  src/material/stepper/stepper.scss
  src/material/tabs/_tabs-common.scss
  src/material/tabs/tab-group.scss
  yarn.lock
Labels: action: merge, target: major, detected: breaking change

#29610 fix(material/datepicker): calendar font tokens not being picked up
  src/material/core/tokens/m2/mat/_datepicker.scss
  src/material/core/tokens/m3/mat/_datepicker.scss
  src/material/datepicker/calendar-body.scss
Labels: action: merge, target: minor

#29615 [Patch port] fix(material/datepicker): calendar font tokens not being picked up
  src/material/core/tokens/m2/mat/_datepicker.scss
  src/material/core/tokens/m3/mat/_datepicker.scss
  src/material/datepicker/calendar-body.scss
Labels: action: merge, target: patch

#29528 fix(multiple): change fallbacks to use m3
  src/material/core/_core.scss
  src/material/core/tokens/_token-utils.scss
Labels: action: merge, target: minor

#29619 refactor(material/core): split out m3 theme mixins
  src/material/_index.scss
  src/material/core/tokens/_m3-system.scss
  src/material/core/tokens/_m3-tokens.scss
  src/material/core/tokens/_token-utils.scss
Labels: action: merge, target: minor

#29622 fix(multiple): stop exposing internal ripple implementation
  src/material/button/button-base.ts
  src/material/button/button.spec.ts
  src/material/checkbox/checkbox.spec.ts
  src/material/checkbox/checkbox.ts
  src/material/chips/chip.spec.ts
  src/material/chips/chip.ts
  src/material/core/private/ripple-loader.ts
  tools/public_api_guard/material/button.md
  tools/public_api_guard/material/checkbox.md
  tools/public_api_guard/material/chips.md
  tools/public_api_guard/material/core.md
Labels: action: merge, target: major, detected: breaking change

#29630 fix(material/core): stop manually instantiating MatRipple directive
  src/material/core/private/ripple-loader.ts
  tools/public_api_guard/material/core.md
Labels: action: merge, target: major

#29634 fix(cdk/drag-drop): error if ngDevMode is undefined
  src/cdk/drag-drop/drag-ref.ts
Labels: action: merge, target: patch

#29624 fix(material/core): add missing system variables
  src/material/core/tokens/_m3-system.scss
  src/material/core/tokens/m3/mat/_sidenav.scss
Labels: action: merge, target: major

#29640 build: remove goo.gl links
  src/material/core/style/_elevation.scss
  src/material/table/table-data-source.ts
Labels: action: merge, target: patch, area: build & ci

#29636 feat(material/core): add experimental theme demo
  .stylelintrc.json
  src/dev-app/BUILD.bazel
  src/dev-app/dev-app/dev-app-layout.html
  src/dev-app/dev-app/dev-app-layout.ts
  src/dev-app/dev-app/dev-app-state.ts
  src/dev-app/routes.ts
  src/dev-app/theme-m3.scss
  src/dev-app/theme/BUILD.bazel
  src/dev-app/theme/theme-demo.html
  src/dev-app/theme/theme-demo.scss
  src/dev-app/theme/theme-demo.ts
  src/material/_index.scss
Labels: action: merge, target: major, dev-app preview, detected: feature

#29623 fix(multiple): consolidate strong focus indicators
  src/material/_index.scss
  src/material/button/_button-base.scss
  src/material/button/button.html
  src/material/button/button.scss
  src/material/button/button.spec.ts
  src/material/button/fab.scss
  src/material/button/icon-button.html
  src/material/checkbox/checkbox.html
  src/material/checkbox/checkbox.scss
  src/material/checkbox/checkbox.spec.ts
  src/material/chips/chip-icons.ts
  src/material/chips/chip-option.html
  src/material/chips/chip-option.spec.ts
  src/material/chips/chip-remove.spec.ts
  src/material/chips/chip-row.html
  src/material/chips/chip.html
  src/material/chips/chip.scss
  src/material/core/_core.scss
  src/material/core/focus-indicators/_focus-indicators-theme.scss
  src/material/core/focus-indicators/_focus-indicators.scss
  src/material/core/focus-indicators/_private.scss
  src/material/core/option/option.html
  src/material/core/option/option.scss
  src/material/core/option/option.spec.ts
  src/material/list/list-item.html
  src/material/list/list-option.html
  src/material/list/list.scss
  src/material/list/list.spec.ts
  src/material/list/selection-list.spec.ts
  src/material/menu/menu-item.ts
  src/material/menu/menu.spec.ts
  src/material/radio/radio.html
  src/material/radio/radio.scss
  src/material/radio/radio.spec.ts
  src/material/slide-toggle/slide-toggle.html
  src/material/slide-toggle/slide-toggle.scss
  src/material/slide-toggle/slide-toggle.spec.ts
  src/material/slider/slider-thumb.html
  src/material/slider/slider.scss
  src/material/tabs/_tabs-common.scss
  src/material/tabs/tab-group.html
  src/material/tabs/tab-group.spec.ts
  src/material/tabs/tab-nav-bar/tab-nav-bar.spec.ts
  src/material/tabs/tab-nav-bar/tab-nav-bar.ts
Labels: action: merge, target: major

#29641 fix(cdk/tree): capturing focus on load
  src/cdk/a11y/key-manager/tree-key-manager-strategy.ts
  src/cdk/a11y/key-manager/tree-key-manager.ts
  src/cdk/tree/tree.ts
  tools/public_api_guard/cdk/a11y.md
  tools/public_api_guard/cdk/tree.md
Labels: Accessibility, action: merge, target: patch

#29647 [Patch port] fix(cdk/tree): fix issue where `isExpanded` wouldn't be set if placed…
  src/cdk/tree/tree.spec.ts
  src/cdk/tree/tree.ts
Labels: action: merge, target: patch

#29648 fix(cdk/tree): avoid breaking change in constructor
  src/cdk/tree/tree.ts
  tools/public_api_guard/cdk/tree.md
Labels: action: merge, target: patch

#29643 perf(material/tooltip): Avoid unneeded calls to clearTimeout
  src/material/tooltip/tooltip.ts
Labels: action: merge, G, target: patch

#29654 build: update `@angular/bazel` to consume new format of APF
  package.json
  tools/postinstall/patches/@angular+bazel+16.0.0-next.6.patch
  yarn.lock
Labels: action: merge, target: major, area: build & ci

#29657 docs: release notes for the v18.2.2 release
  CHANGELOG.md
Labels: area: docs

#29665 fix(material/core): Allow system variables to be formatted for opacity
  src/material/core/style/_sass-utils.scss
Labels: action: merge, target: patch, area: material/core, area: theming

#29655 fix(material/core): Fix incorrect color role mappings
  src/material/core/theming/tests/theming-definition-api.spec.ts
  src/material/core/tokens/m3/definitions/_md-sys-color.scss
Labels: action: merge, target: patch, area: material/core, area: theming
