Repository angular/components, pull requests merged in 2024-09, with the labels that each got.

#29676 fix(material/badge): resolve memory leak
  src/material/badge/badge.ts
Labels: action: merge, target: patch

#29680 build: bump up machine size
  .github/workflows/ci.yml
  .github/workflows/pr.yml
Labels: action: merge, target: patch, area: build & ci

#29678 feat(cdk/a11y): use native media query for high contrast detection
  src/cdk/a11y/_index.scss
  src/cdk/a11y/a11y.md
  src/material-experimental/popover-edit/_popover-edit-theme.scss
  src/material/autocomplete/autocomplete.scss
  src/material/badge/badge.scss
  src/material/bottom-sheet/bottom-sheet-container.scss
  src/material/button-toggle/button-toggle.scss
  src/material/button/button-high-contrast.scss
  src/material/checkbox/_checkbox-common.scss
  src/material/chips/chip.scss
  src/material/core/focus-indicators/_private.scss
  src/material/core/option/option.scss
  src/material/core/ripple/_ripple.scss
  src/material/core/style/_menu-common.scss
  src/material/datepicker/calendar-body.scss
  src/material/datepicker/calendar.scss
  src/material/datepicker/date-range-input.scss
  src/material/datepicker/datepicker-toggle.scss
  src/material/dialog/dialog.scss
  src/material/expansion/expansion-panel-header.scss
  src/material/expansion/expansion-panel.scss
  src/material/form-field/_form-field-high-contrast.scss
  src/material/form-field/_mdc-text-field-structure.scss
  src/material/list/_list-inherited-structure.scss
  src/material/list/_list-item-hcm-indicator.scss
  src/material/menu/menu.scss
  src/material/paginator/paginator.scss
  src/material/progress-bar/progress-bar.scss
  src/material/progress-spinner/progress-spinner.scss
  src/material/select/select.scss
  src/material/sidenav/drawer.scss
  src/material/slide-toggle/slide-toggle.scss
  src/material/slider/slider.scss
  src/material/snack-bar/snack-bar-container.scss
  src/material/sort/sort-header.scss
  src/material/stepper/step-header.scss
  src/material/stepper/stepper.scss
  src/material/tabs/tab-header.scss
  src/material/toolbar/toolbar.scss
Labels: Accessibility, action: merge, target: major, detected: feature, detected: breaking change

#29674 fix(material/tooltip): remove old IE workaround
  src/material/tooltip/tooltip.ts
Labels: action: merge, target: patch

#29672 fix(multiple): ripples not showing up in some cases
  src/material/checkbox/checkbox.scss
  src/material/core/private/ripple-loader.ts
  src/material/tabs/_tabs-common.scss
Labels: action: merge, target: major

#29651 fix(material/core): delete deprecated APIs
  src/material/core/common-behaviors/color.spec.ts
  src/material/core/common-behaviors/color.ts
  src/material/core/common-behaviors/constructor.ts
  src/material/core/common-behaviors/disable-ripple.spec.ts
  src/material/core/common-behaviors/disable-ripple.ts
  src/material/core/common-behaviors/disabled.spec.ts
  src/material/core/common-behaviors/disabled.ts
  src/material/core/common-behaviors/error-state.ts
  src/material/core/common-behaviors/index.ts
  src/material/core/common-behaviors/initialized.spec.ts
  src/material/core/common-behaviors/initialized.ts
  src/material/core/common-behaviors/palette.ts
  src/material/core/common-behaviors/tabindex.spec.ts
  src/material/core/common-behaviors/tabindex.ts
  tools/public_api_guard/material/core.md
Labels: action: merge, target: major, detected: breaking change

#29675 refactor(multiple): switch experimental packages to inject
  src/cdk-experimental/column-resize/column-resize-directives/column-resize-flex.ts
  src/cdk-experimental/column-resize/column-resize-directives/column-resize.ts
  src/cdk-experimental/column-resize/column-resize-directives/default-enabled-column-resize-flex.ts
  src/cdk-experimental/column-resize/column-resize-directives/default-enabled-column-resize.ts
  src/cdk-experimental/column-resize/event-dispatcher.ts
  src/cdk-experimental/column-resize/resize-strategy.ts
  src/cdk-experimental/combobox/combobox-popup.ts
  src/cdk-experimental/combobox/combobox.ts
  src/cdk-experimental/popover-edit/edit-event-dispatcher.ts
  src/cdk-experimental/popover-edit/edit-ref.ts
  src/cdk-experimental/popover-edit/edit-services.ts
  src/cdk-experimental/popover-edit/focus-dispatcher.ts
  src/cdk-experimental/popover-edit/focus-escape-notifier.ts
  src/cdk-experimental/popover-edit/lens-directives.ts
  src/cdk-experimental/popover-edit/table-directives.ts
  src/cdk-experimental/selection/row-selection.ts
  src/cdk-experimental/selection/select-all.ts
  src/cdk-experimental/selection/selection-column.ts
  src/cdk-experimental/selection/selection-toggle.ts
  src/cdk-experimental/selection/selection.spec.ts
  src/cdk-experimental/table-scroll-container/table-scroll-container.ts
  src/material-experimental/column-resize/column-resize-directives/column-resize-flex.ts
  src/material-experimental/column-resize/column-resize-directives/column-resize.ts
  src/material-experimental/column-resize/column-resize-directives/default-enabled-column-resize-flex.ts
  src/material-experimental/column-resize/column-resize-directives/default-enabled-column-resize.ts
  src/material-experimental/column-resize/overlay-handle.ts
  src/material-experimental/column-resize/resizable-directives/default-enabled-resizable.ts
  src/material-experimental/column-resize/resizable-directives/resizable.ts
  src/material-experimental/column-resize/resize-strategy.ts
  src/material-experimental/selection/selection-column.ts
Labels: action: merge, target: major

#29693 docs: release notes for the v18.2.3 release
  CHANGELOG.md
Labels: area: docs

#29695 build: clean up unused imports
  package.json
  src/components-examples/material/autocomplete/autocomplete-require-selection/autocomplete-require-selection-example.ts
  src/dev-app/datepicker/datepicker-demo.ts
  src/dev-app/portal/portal-demo.ts
  src/dev-app/table/table-demo.ts
  src/dev-app/tabs/tabs-demo.ts
  src/dev-app/toolbar/toolbar-demo.ts
  src/dev-app/tooltip/tooltip-demo.ts
  src/dev-app/tree/tree-demo.ts
  yarn.lock
Labels: action: merge, target: major, area: build & ci

#29688 fix(material/core): drop sanity checks
  src/material/core/_core-theme.scss
  src/material/core/common-behaviors/common-module.ts
  src/material/core/theming/tests/m3-theme.spec.ts
  src/material/core/theming/tests/theming-inspection-api.spec.ts
  tools/public_api_guard/material/core.md
Labels: action: merge, target: major

#29699 build: fix broken build
  src/material/core/theming/tests/m3-theme.spec.ts
Labels: action: merge, target: major, area: build & ci

#29701 docs(material/progress-spinner): remove legacy prefix
  src/material/progress-spinner/progress-spinner.md
Labels: action: merge, target: patch, area: docs

#29673 fix(material/form-field): Don't allow label to grow larger than input
  src/material/form-field/_mdc-text-field-structure.scss
  src/material/form-field/form-field.html
  src/material/form-field/form-field.ts
  tools/public_api_guard/material/form-field.md
Labels: action: merge, G, target: patch

#29709 fix(cdk/overlay): avoid leaking memory through afterNextRender
  src/cdk/overlay/overlay-ref.ts
Labels: action: merge, target: patch

#29457 feat(mat/checkbox): add new aria properties to MatCheckbox
  src/material/checkbox/checkbox.html
  src/material/checkbox/checkbox.md
  src/material/checkbox/checkbox.spec.ts
  src/material/checkbox/checkbox.ts
  tools/public_api_guard/material/checkbox.md
Labels: action: merge, target: minor, merge: fix commit message, detected: feature

#29712 Fix typo in expansion-panel-header.scss
  src/material/expansion/expansion-panel-header.scss
Labels: action: merge, target: patch

#29684 fix(material/select): Update checkbox color to match the selected label text color
  src/material/core/option/option.scss
Labels: action: merge, target: patch

#29713 fix(material/badge): change legacy container size default
  src/material/badge/badge.scss
  src/material/core/tokens/m3/mat/_badge.scss
Labels: action: merge, target: patch

#29719 refactor(material/list): restore before pseudo element
  src/material/list/_list-inherited-structure.scss
Labels: action: merge, target: minor

#29728 docs: release notes for the v18.2.4 release
  CHANGELOG.md
Labels: area: docs

#29722 fix(cdk/listbox): scroll active option into view when using aria-activedescendant
  src/cdk/listbox/listbox.ts
Labels: action: merge, target: patch

#29725 fix(cdk/overlay): load structural styles in a cascade layer
  src/cdk/overlay/BUILD.bazel
  src/cdk/overlay/_index.scss
  src/cdk/overlay/overlay-container.ts
  src/cdk/overlay/overlay-structure.scss
Labels: action: merge, target: major

#27427 fix(cdk/portal): remove ComponentFactoryResolver usages
  src/cdk/portal/dom-portal-outlet.ts
  src/cdk/portal/portal-directives.ts
  src/cdk/portal/portal.spec.ts
  src/cdk/portal/portal.ts
  src/material/dialog/dialog.spec.ts
  tools/public_api_guard/cdk/portal.md
Labels: action: merge, target: major

#29736 build: update to TypeScript 5.6 final
  integration/harness-e2e-cli/package.json
  integration/harness-e2e-cli/yarn.lock
  integration/ng-add-standalone/package.json
  integration/ng-add-standalone/yarn.lock
  integration/ng-add/package.json
  integration/ng-add/yarn.lock
  integration/yarn-pnp-compat/.yarn/releases/yarn-4.3.1.cjs
  integration/yarn-pnp-compat/.yarn/releases/yarn-4.4.1.cjs
  integration/yarn-pnp-compat/.yarnrc.yml
  integration/yarn-pnp-compat/package.json
  integration/yarn-pnp-compat/yarn.lock
  package.json
  yarn.lock
Labels: action: merge, target: major, area: build & ci

#29744 feat(material-date-fns-adapter): add support for date-fns 4
  package.json
  src/material-date-fns-adapter/package.json
  yarn.lock
Labels: action: merge, target: major, detected: feature

#29739 fix(cdk/drag-drop): account for scale when setting free drag position
  src/cdk/drag-drop/directives/drag.ts
  src/cdk/drag-drop/directives/standalone-drag.spec.ts
Labels: action: merge, target: patch

#29746 docs(material/select): prevent select from jumping in custom trigger example
  src/components-examples/material/select/select-custom-trigger/select-custom-trigger-example.css
Labels: action: merge, target: patch, area: docs

#29745 fix(material/slider): log proper error when slider isn't configured correctly
  src/material/slider/slider-thumb.ts
  src/material/slider/slider.ts
Labels: action: merge, target: patch

#29755 fix(material/datepicker): replace labels not pointing to anything
  src/material/datepicker/calendar-body.html
  src/material/datepicker/calendar-header.html
Labels: action: merge, target: patch

#29747 feat(google-maps/map-advanced-marker): Add support for some mouse events #29741
  src/google-maps/map-advanced-marker/map-advanced-marker.spec.ts
  src/google-maps/map-advanced-marker/map-advanced-marker.ts
  tools/public_api_guard/google-maps/google-maps.md
Labels: action: merge, target: minor, merge: fix commit message, detected: feature

#29754 fix(cdk/tree): resolve maximum call stack error
  src/cdk/tree/tree.ts
Labels: action: merge, target: patch

#29645 fix(material/select): remove incompatible aria-autocomplete attribute
  src/material/select/select.ts
Labels: action: merge, target: patch

#29452 fix(material/chips): increase chip remove touch target size
  src/material/chips/chip.scss
Labels: action: merge, target: patch

#29752 docs(mat/tree): update examples on docs pages, add new childrenAccessor examples
  src/cdk/tree/tree.md
  src/components-examples/material/tree/index.ts
  src/components-examples/material/tree/tree-flat-child-accessor-overview/tree-flat-child-accessor-overview-example.html
  src/components-examples/material/tree/tree-flat-child-accessor-overview/tree-flat-child-accessor-overview-example.ts
  src/components-examples/material/tree/tree-nested-child-accessor-overview/tree-nested-child-accessor-overview-example.css
  src/components-examples/material/tree/tree-nested-child-accessor-overview/tree-nested-child-accessor-overview-example.html
  src/components-examples/material/tree/tree-nested-child-accessor-overview/tree-nested-child-accessor-overview-example.ts
  src/dev-app/tree/tree-demo.html
  src/dev-app/tree/tree-demo.ts
  src/material/tree/tree.md
Labels: action: merge, target: patch, merge: fix commit message, area: docs

#29760 test(material/select): fix broken test
  src/material/select/select.spec.ts
Labels: action: merge, target: patch

#29773 docs: release notes for the v18.2.5 release
  CHANGELOG.md
Labels: area: docs

#29757 feat(cdk/private): create cdk-visually-hidden style loader
  src/cdk/private/BUILD.bazel
  src/cdk/private/public-api.ts
  src/cdk/private/visually-hidden/visually-hidden.scss
  src/cdk/private/visually-hidden/visually-hidden.ts
  tools/public_api_guard/cdk/private.md
Labels: action: merge, target: major, detected: feature

#29774 refactor(google-maps): switch to inject function
  src/google-maps/google-map/google-map.ts
  src/google-maps/map-advanced-marker/map-advanced-marker.ts
  src/google-maps/map-base-layer.ts
  src/google-maps/map-circle/map-circle.ts
  src/google-maps/map-directions-renderer/map-directions-renderer.ts
  src/google-maps/map-directions-renderer/map-directions-service.ts
  src/google-maps/map-geocoder/map-geocoder.ts
  src/google-maps/map-ground-overlay/map-ground-overlay.ts
  src/google-maps/map-heatmap-layer/map-heatmap-layer.ts
  src/google-maps/map-info-window/map-info-window.ts
  src/google-maps/map-kml-layer/map-kml-layer.ts
  src/google-maps/map-marker-clusterer/map-marker-clusterer.ts
  src/google-maps/map-marker/map-marker.ts
  src/google-maps/map-polygon/map-polygon.ts
  src/google-maps/map-polyline/map-polyline.ts
  src/google-maps/map-rectangle/map-rectangle.ts
  src/google-maps/map-traffic-layer/map-traffic-layer.ts
  tools/public_api_guard/google-maps/google-maps.md
Labels: action: merge, target: major

#29775 refactor(youtube-player): switch to inject function
  src/youtube-player/youtube-player.ts
  tools/public_api_guard/youtube-player/youtube-player.md
Labels: action: merge, target: major

#29770 fix(material/datepicker): set explicit line height on calendar
  src/material/datepicker/calendar.scss
Labels: action: merge, target: patch

#29786 refactor: create mixins for core classes
  src/dev-app/theme.scss
  src/material/_index.scss
  src/material/core/_core.scss
  src/universal-app/styles.scss
Labels: action: merge, target: major

#29768 feat(material/schematics): create v19 core removal schematic
  src/material/schematics/ng-update/index.ts
  src/material/schematics/ng-update/migrations/mat-core-removal.ts
  src/material/schematics/ng-update/test-cases/v19-mat-core-removal.spec.ts
Labels: action: merge, target: major, detected: feature

#29780 docs(material/datepicker): Fixed typo in date-range-picker-selection-…
  src/components-examples/material/datepicker/date-range-picker-selection-strategy/date-range-picker-selection-strategy-example.ts
Labels: action: merge, target: patch, area: docs

#29779 feat(material/tabs): add `alignTabs` in `MatTabsConfig`
  src/material/tabs/tab-config.ts
  src/material/tabs/tab-group.spec.ts
  src/material/tabs/tab-group.ts
  tools/public_api_guard/material/tabs.md
Labels: action: merge, target: major, detected: feature

#29795 fix(material/chips): chip set overwriting disabled state
  src/material/chips/chip-listbox.spec.ts
  src/material/chips/chip-set.ts
  src/material/chips/chip.ts
  tools/public_api_guard/material/chips.md
Labels: action: merge, target: patch

#29802 fix(material/core): infer first day of week in native date adapter
  src/material/core/datetime/native-date-adapter.ts
Labels: action: merge, target: patch

#29803 refactor(multiple): re-add missing feedback
  src/material-date-fns-adapter/adapter/date-fns-adapter.spec.ts
  src/material-date-fns-adapter/adapter/date-fns-adapter.ts
  src/material-luxon-adapter/adapter/luxon-date-adapter.spec.ts
  src/material-luxon-adapter/adapter/luxon-date-adapter.ts
  src/material-moment-adapter/adapter/moment-date-adapter.spec.ts
  src/material-moment-adapter/adapter/moment-date-adapter.ts
  src/material/core/datetime/date-adapter.ts
  src/material/core/datetime/native-date-adapter.spec.ts
  src/material/core/datetime/native-date-adapter.ts
  tools/public_api_guard/material/core.md
Labels: action: merge, target: major
