Repository angular/components, pull requests merged in 2024-01, with the labels that each got.

#28348 build: support multiple packages in api approval script
  scripts/approve-api-golden.js
Labels: action: merge, P4, target: patch, area: build & ci

#28346 build: bump year
  LICENSE
Labels: action: merge, target: patch, area: build & ci

#28343 fix(multiple): enable hydration in autocomplete, menu and select
  src/material/autocomplete/autocomplete.ts
  src/material/menu/menu.ts
  src/material/select/select.ts
  tools/public_api_guard/material/select.md
Labels: P3, action: merge, target: minor

#28334 fix(cdk/drag-drop): auto-scroll to the left not starting in rtl layout
  src/cdk/drag-drop/directives/drag.spec.ts
  src/cdk/drag-drop/drop-list-ref.ts
Labels: P2, action: merge, target: patch

#28337 perf(cdk/a11y): Micro-optimizations to aria-reference.ts.
  src/cdk/a11y/aria-describer/aria-reference.ts
Labels: action: merge, G, target: patch

#28351 build: resolve api golden failure
  tools/public_api_guard/material/select.md
Labels: action: merge, target: minor, area: build & ci

#28349 fix(multiple): provide standalone-friendly APIs for date adapters
  src/components-examples/material/datepicker/date-range-picker-comparison/date-range-picker-comparison-example.ts
  src/components-examples/material/datepicker/date-range-picker-forms/date-range-picker-forms-example.ts
  src/components-examples/material/datepicker/date-range-picker-overview/date-range-picker-overview-example.ts
  src/components-examples/material/datepicker/date-range-picker-selection-strategy/date-range-picker-selection-strategy-example.ts
  src/components-examples/material/datepicker/datepicker-actions/datepicker-actions-example.ts
  src/components-examples/material/datepicker/datepicker-api/datepicker-api-example.ts
  src/components-examples/material/datepicker/datepicker-color/datepicker-color-example.ts
  src/components-examples/material/datepicker/datepicker-custom-header/datepicker-custom-header-example.ts
  src/components-examples/material/datepicker/datepicker-custom-icon/datepicker-custom-icon-example.ts
  src/components-examples/material/datepicker/datepicker-date-class/datepicker-date-class-example.ts
  src/components-examples/material/datepicker/datepicker-disabled/datepicker-disabled-example.ts
  src/components-examples/material/datepicker/datepicker-events/datepicker-events-example.ts
  src/components-examples/material/datepicker/datepicker-filter/datepicker-filter-example.ts
  src/components-examples/material/datepicker/datepicker-formats/datepicker-formats-example.ts
  src/components-examples/material/datepicker/datepicker-harness/datepicker-harness-example.ts
  src/components-examples/material/datepicker/datepicker-inline-calendar/datepicker-inline-calendar-example.ts
  src/components-examples/material/datepicker/datepicker-locale/datepicker-locale-example.ts
  src/components-examples/material/datepicker/datepicker-min-max/datepicker-min-max-example.ts
  src/components-examples/material/datepicker/datepicker-moment/datepicker-moment-example.ts
  src/components-examples/material/datepicker/datepicker-overview/datepicker-overview-example.ts
  src/components-examples/material/datepicker/datepicker-start-view/datepicker-start-view-example.ts
  src/components-examples/material/datepicker/datepicker-touch/datepicker-touch-example.ts
  src/components-examples/material/datepicker/datepicker-value/datepicker-value-example.ts
  src/components-examples/material/datepicker/datepicker-views-selection/datepicker-views-selection-example.ts
  src/components-examples/material/expansion/expansion-expand-collapse-all/expansion-expand-collapse-all-example.ts
  src/components-examples/material/expansion/expansion-steps/expansion-steps-example.ts
  src/dev-app/datepicker/datepicker-demo.ts
  src/dev-app/main.ts
  src/material-date-fns-adapter/adapter/index.ts
  src/material-luxon-adapter/adapter/index.ts
  src/material-moment-adapter/adapter/index.ts
  src/material-moment-adapter/adapter/moment-date-adapter.ts
  src/material/core/datetime/index.ts
  src/material/datepicker/datepicker-errors.ts
  src/material/datepicker/datepicker.md
  src/universal-app/kitchen-sink/kitchen-sink.ts
  tools/public_api_guard/material/core.md
Labels: P2, action: merge, target: minor

#28329 fix(material/dialog): `mat-dialog-title` should work under `OnPush` `viewContainerRef`
  src/cdk/dialog/dialog-container.ts
  src/material/bottom-sheet/bottom-sheet-container.ts
  src/material/dialog/dialog-content-directives.ts
  src/material/dialog/dialog.spec.ts
  tools/public_api_guard/cdk/dialog.md
  tools/public_api_guard/material/bottom-sheet.md
Labels: action: merge, target: minor, area: material/dialog

#28353 fix(guides/theming.md) Typo fix of theming.md
  guides/theming.md
Labels: action: merge, target: patch, merge: fix commit message

#28275 fix(material/slider): update inactive input width on value change
  src/material/slider/slider-input.ts
  src/material/slider/slider.spec.ts
  tools/public_api_guard/material/slider.md
Labels: action: merge, target: minor

#28359 build: import sass
  tools/sass/compiler-main.ts
  tools/sass/local-sass-importer.ts
Labels: action: merge, target: minor, area: build & ci

#28364 feat(material-date-fns-adapter): support date-fns 3.0
  package.json
  src/material-date-fns-adapter/adapter/date-fns-adapter.ts
  src/material-date-fns-adapter/package.json
  yarn.lock
Labels: P3, action: merge, target: minor, detected: feature

#28331 fix(material/snack-bar): Ensure snackbar enter/exit works with OnPush ancestor
  src/material/snack-bar/snack-bar-container.ts
  src/material/snack-bar/snack-bar.spec.ts
Labels: action: merge, target: minor, area: material/snack-bar

#28243 fix(material/slider): fix internal focus state on safari
  src/material/slider/slider-input.ts
  src/material/slider/slider-thumb.ts
  src/material/slider/slider.spec.ts
Labels: action: merge, target: patch

#28366 fix(material/tabs): enable hydration
  src/material/tabs/tab-group.html
  src/material/tabs/tab-group.ts
  src/material/tabs/tab.ts
  src/universal-app/kitchen-sink/kitchen-sink.html
  tools/public_api_guard/material/tabs.md
Labels: P3, action: merge, target: minor

#28383 build: delete unused firebase code
  scripts/caretaking/firebase-functions/.gitignore
  scripts/caretaking/firebase-functions/firebase.json
  scripts/caretaking/firebase-functions/package.json
  scripts/caretaking/firebase-functions/src/github-pr.ts
  scripts/caretaking/firebase-functions/src/index.ts
  scripts/caretaking/firebase-functions/tsconfig.json
  scripts/caretaking/firebase-functions/yarn.lock
  scripts/tsconfig.json
Labels: action: merge, target: patch, area: build & ci

#28382 fix(material/stepper): enable hydration
  src/material/stepper/stepper.html
  src/material/stepper/stepper.ts
  tools/public_api_guard/material/stepper.md
Labels: P3, action: merge, target: minor

#28363 fix(multiple): use provide functions in providers for date adapters
  src/material-date-fns-adapter/adapter/index.ts
  src/material-luxon-adapter/adapter/index.ts
  src/material-moment-adapter/adapter/index.ts
  src/material/core/datetime/index.ts
Labels: action: merge, target: minor

#28356 fix(cdk/table): support hydration
  src/cdk/table/sticky-styler.ts
  src/cdk/table/table.ts
  src/material/table/table.ts
  src/universal-app/kitchen-sink/kitchen-sink.html
  src/universal-app/kitchen-sink/kitchen-sink.ts
  tools/public_api_guard/cdk/table.md
  tools/public_api_guard/material/table.md
Labels: P2, action: merge, target: minor

#28365 fix(material/slide-toggle): delete custom typography tokens
  src/material/core/tokens/m2/_index.scss
  src/material/core/tokens/m2/mat/_slide-toggle.scss
  src/material/slide-toggle/_slide-toggle-theme.scss
  src/material/slide-toggle/slide-toggle.scss
Labels: P3, action: merge, target: minor

#28388 build: update API golden
  tools/public_api_guard/material/core.md
Labels: P3, action: merge, target: minor, area: build & ci

#28370 refactor(material/snack-bar): Remove NgZone.onMicrotaskEmpty dependency
  src/material/snack-bar/snack-bar-container.ts
Labels: action: merge, target: patch

#28336 perf(cdk/table): Optimize a11y role logic in CdkCell.
  src/cdk/table/cell.ts
  src/cdk/table/table.spec.ts
  src/cdk/table/table.ts
  tools/public_api_guard/cdk/table.md
Labels: action: merge, G, target: minor

#28283 fix(material/slider): slider tx imprecision
  src/material/slider/slider-input.ts
  src/material/slider/slider-interface.ts
  src/material/slider/slider.spec.ts
  src/material/slider/slider.ts
  tools/public_api_guard/material/slider.md
Labels: action: merge, target: patch

#28385 fix(material/datepicker): unable to distinguish disabled buttons in the calendar
  src/material/datepicker/calendar.scss
Labels: P3, action: merge, target: patch

#28391 fix(cdk/table): _cellRole lint error
  src/cdk/table/cell.ts
  src/cdk/table/table.ts
  tools/public_api_guard/cdk/table.md
Labels: action: merge, target: minor

#28369 fix(material/slider): m3 ripple color
  src/material-experimental/theming/_custom-tokens.scss
  src/material/core/tokens/m2/mat/_slider.scss
  src/material/slider/_slider-theme.scss
  src/material/slider/slider.scss
Labels: action: merge, target: patch

#28375 feat(material-experimental/theming): add M3 button tokens
  src/dev-app/theme-m3.scss
  src/material-experimental/theming/_custom-tokens.scss
  src/material-experimental/theming/_m3-density.scss
  src/material-experimental/theming/_m3-tokens.scss
  src/material/button/_button-theme.scss
  src/material/core/tokens/m2/_index.scss
Labels: P3, action: merge, target: minor, detected: feature

#28314 fix(material/theming): Expose the `theme-remove` Sass function
  src/material/_index.scss
Labels: action: merge, target: patch

#28389 docs(material/theming-your-component): Typo in code-block example
  guides/theming-your-components.md
Labels: action: merge, target: patch, area: docs

#28393 fix(cdk/table): measuring sticky row too early
  src/cdk/table/sticky-styler.ts
Labels: P2, action: merge, target: minor

#28395 build: add automated test for hydration
  src/universal-app/BUILD.bazel
  src/universal-app/hydration.e2e.spec.ts
  src/universal-app/kitchen-sink/kitchen-sink.html
  src/universal-app/protractor.conf.js
  src/universal-app/start-devserver.js
Labels: action: merge, target: minor, area: build & ci

#28396 fix(material/button): use tokens for button elevation
  package.json
  packages.bzl
  src/material/button/_button-base.scss
  src/material/button/_button-theme.scss
  src/material/button/_fab-theme.scss
  src/material/button/button.scss
  src/material/button/fab.scss
  src/material/core/tokens/m2/mdc/_extended-fab.scss
  src/material/core/tokens/m2/mdc/_fab.scss
  src/material/core/tokens/m2/mdc/_filled-button.scss
  src/material/core/tokens/m2/mdc/_protected-button.scss
  yarn.lock
Labels: P3, action: merge, target: minor

#28279 feat(material-experimental/theming): Add support for color variants
  src/dev-app/theme-m3.scss
  src/material-experimental/theming/_custom-tokens.scss
  src/material-experimental/theming/_m3-tokens.scss
  src/material/core/style/_sass-utils.scss
  src/material/core/tokens/_token-utils.scss
  src/material/icon/_icon-theme.scss
Labels: action: merge, target: minor, area: docs, detected: feature

#28401 docs: release notes for the v17.0.5 release
  CHANGELOG.md
Labels: area: docs

#28407 feat(material-experimental/theming): add M3 tokens for pseudo checkbox
  src/dev-app/theme-m3.scss
  src/material-experimental/theming/_custom-tokens.scss
  src/material-experimental/theming/_m3-density.scss
  src/material-experimental/theming/_m3-tokens.scss
  src/material/_index.scss
  src/material/core/selection/pseudo-checkbox/_pseudo-checkbox-theme.scss
  src/material/core/tokens/m2/_index.scss
Labels: P3, action: merge, target: minor, detected: feature

#28408 Backport ripple memory leak fix to LTS
  src/material/button/button-base.ts
  src/material/chips/chip.ts
  src/material/core/private/ripple-loader.ts
  tools/public_api_guard/material/core.md
Labels: P3, action: merge, target: lts

#28411 docs: release notes for the v16.2.13 release
  CHANGELOG.md
Labels: area: docs

#28415 fix(material-experimental/theming): disabled radio button incorrect label color
  src/material-experimental/theming/_custom-tokens.scss
Labels: P3, action: merge, target: minor

#28414 fix(material-experimental/theming): set up internal form field in M3
  src/material-experimental/theming/_m3-tokens.scss
  src/material/checkbox/_checkbox-theme.scss
  src/material/core/tokens/m2/_index.scss
  src/material/radio/_radio-theme.scss
  src/material/slide-toggle/_slide-toggle-theme.scss
Labels: P3, action: merge, target: minor

#28418 refactor(google-maps): clean up typing workarounds
  package.json
  src/google-maps/google-map/google-map.ts
  src/google-maps/import-library.ts
  src/google-maps/map-bicycling-layer/map-bicycling-layer.ts
  src/google-maps/map-circle/map-circle.ts
  src/google-maps/map-directions-renderer/map-directions-renderer.spec.ts
  src/google-maps/map-directions-renderer/map-directions-renderer.ts
  src/google-maps/map-directions-renderer/map-directions-service.spec.ts
  src/google-maps/map-directions-renderer/map-directions-service.ts
  src/google-maps/map-geocoder/map-geocoder.ts
  src/google-maps/map-ground-overlay/map-ground-overlay.ts
  src/google-maps/map-heatmap-layer/map-heatmap-layer.ts
  src/google-maps/map-info-window/map-info-window.ts
  src/google-maps/map-kml-layer/map-kml-layer.ts
  src/google-maps/map-marker/map-marker.ts
  src/google-maps/map-polygon/map-polygon.ts
  src/google-maps/map-polyline/map-polyline.ts
  src/google-maps/map-rectangle/map-rectangle.ts
  src/google-maps/map-traffic-layer/map-traffic-layer.ts
  src/google-maps/map-transit-layer/map-transit-layer.ts
  src/google-maps/package.json
  yarn.lock
Labels: action: merge, target: minor

#28423 Fix example in input-prefix-suffix-example.html
  src/components-examples/material/input/input-prefix-suffix/input-prefix-suffix-example.html
Labels: docs, action: merge, target: patch

#28424 fix(material/schematics): import async animations and remove deprecated function usages
  src/material/schematics/ng-add/index.spec.ts
  src/material/schematics/ng-add/setup-project.ts
Labels: action: merge, target: minor

#28420 build: update to the 17.1 RC
  package.json
  yarn.lock
Labels: action: merge, target: minor

#28416 fix(material/progress-bar): remove track color workaround
  src/material/progress-bar/_progress-bar-theme.scss
  src/material/progress-bar/progress-bar.scss
Labels: P3, action: merge, target: patch

#28412 fix(material-experimental/theming): Add support for color variants in option, checkbox, and fab
  src/dev-app/theme-m3.scss
  src/material-experimental/theming/_custom-tokens.scss
  src/material-experimental/theming/_m3-tokens.scss
  src/material/button/_fab-theme.scss
  src/material/checkbox/_checkbox-theme.scss
  src/material/core/option/_option-theme.scss
  src/material/icon/_icon-theme.scss
Labels: action: merge, target: minor, dev-app preview

#28431 fix(material-experimental/theming): set up core theme and app tokens
  src/dev-app/theme-m3.scss
  src/material-experimental/theming/_custom-tokens.scss
  src/material-experimental/theming/_m3-tokens.scss
  src/material/core/_core-theme.scss
  src/material/core/tokens/m2/_index.scss
Labels: action: merge, target: minor

#28438 docs: release notes for the v17.0.6 release
  CHANGELOG.md
Labels: area: docs

#28417 fix(material-experimental/theming): Add support for color variants in tabs and slider
  src/dev-app/theme-m3.scss
  src/material-experimental/theming/_custom-tokens.scss
  src/material-experimental/theming/_m3-tokens.scss
  src/material/slider/_slider-theme.scss
  src/material/tabs/_tabs-theme.scss
Labels: action: merge, target: minor, dev-app preview

#28405 fix(material/core): fix mat-error not rendering with Closure Compiler
  src/material/core/common-behaviors/error-state.ts
  tools/public_api_guard/material/core.md
Labels: action: merge, target: patch, area: material/core, area: material/stepper

#28449 fix(material/dialog): scale animation not working
  src/dev-app/dialog/dialog-demo.ts
  src/material/dialog/dialog.scss
Labels: action: merge, target: patch

#28444 docs: update reference to internal issue
  src/material-experimental/theming/_m3-tokens.scss
Labels: action: merge, target: minor, area: docs

#28445 fix(material-experimental/theming): Add support for color variants in slide-toggle, select, and radio
  src/dev-app/theme-m3.scss
  src/material-experimental/theming/_custom-tokens.scss
  src/material-experimental/theming/_m3-tokens.scss
  src/material/icon/_icon-theme.scss
  src/material/radio/_radio-theme.scss
  src/material/select/_select-theme.scss
  src/material/slide-toggle/_slide-toggle-theme.scss
Labels: action: merge, target: minor, dev-app preview

#28253 docs(material/chips): remove instructions to announce deletion
  src/material/chips/chips.md
Labels: a11y, docs, action: merge, target: patch, area: material/chips, area: docs

#28451 fix(material-experimental/theming): Add support for color variants in progress-spinner, progress-bar, list, form-field, and datepicker
  src/dev-app/theme-m3.scss
  src/material-experimental/theming/_custom-tokens.scss
  src/material-experimental/theming/_m3-tokens.scss
  src/material/datepicker/_datepicker-theme.scss
  src/material/form-field/_form-field-theme.scss
  src/material/progress-bar/_progress-bar-theme.scss
  src/material/progress-spinner/_progress-spinner-theme.scss
Labels: action: merge, target: minor, dev-app preview

#28452 fix(material/badge): move structural styles out of theme
  src/material/badge/BUILD.bazel
  src/material/badge/_badge-theme.scss
  src/material/badge/badge-module.ts
  src/material/badge/badge.scss
  src/material/badge/badge.spec.ts
  src/material/badge/badge.ts
  src/material/badge/public-api.ts
  tools/public_api_guard/material/badge.md
Labels: action: merge, target: patch

#28459 fix(multiple): import ANIMATION_MODULE_TYPE from core
  src/cdk/clipboard/BUILD.bazel
  src/cdk/observers/private/BUILD.bazel
  src/cdk/portal/BUILD.bazel
  src/dev-app/checkbox/checkbox-demo.ts
  src/material/badge/badge.ts
  src/material/button/button.ts
  src/material/button/fab.ts
  src/material/button/icon-button.ts
  src/material/checkbox/checkbox.ts
  src/material/chips/chip-row.ts
  src/material/chips/chip.ts
  src/material/core/ripple/ripple.ts
  src/material/core/selection/pseudo-checkbox/pseudo-checkbox.ts
  src/material/dialog/dialog-container.ts
  src/material/expansion/expansion-panel-header.ts
  src/material/expansion/expansion-panel.ts
  src/material/form-field/form-field.ts
  src/material/list/list-base.ts
  src/material/list/list.ts
  src/material/progress-bar/progress-bar.ts
  src/material/progress-spinner/progress-spinner.ts
  src/material/radio/radio.ts
  src/material/sidenav/drawer.ts
  src/material/slide-toggle/slide-toggle.ts
  src/material/slider/slider.ts
  src/material/tabs/paginated-tab-header.ts
  src/material/tabs/tab-group.ts
  src/material/tabs/tab-header.ts
  src/material/tabs/tab-nav-bar/tab-nav-bar.ts
  src/material/tooltip/tooltip.ts
  tools/defaults.bzl
Labels: action: merge, target: patch

#28354 perf(cdk/table): Use afterRender hooks
  src/cdk-experimental/column-resize/resize-strategy.ts
  src/cdk-experimental/table-scroll-container/table-scroll-container.ts
  src/cdk/table/coalesced-style-scheduler.ts
  src/cdk/table/sticky-styler.ts
  src/cdk/table/table.ts
  tools/public_api_guard/cdk/table.md
Labels: action: merge, G, target: patch

#28457 fix(material-experimental/theming): Add support for color variants in badge, button-toggle, button, pseudo-checkbox, and chips
  src/dev-app/theme-m3.scss
  src/material-experimental/theming/_custom-tokens.scss
  src/material-experimental/theming/_m3-tokens.scss
  src/material/badge/_badge-theme.scss
  src/material/button-toggle/_button-toggle-theme.scss
  src/material/button/_button-theme.scss
  src/material/chips/_chips-theme.scss
  src/material/core/selection/pseudo-checkbox/_pseudo-checkbox-theme.scss
Labels: action: merge, target: minor, dev-app preview

#28461 Revert "perf(cdk/table): Use afterRender hooks (#28354)"
  src/cdk-experimental/column-resize/resize-strategy.ts
  src/cdk-experimental/table-scroll-container/table-scroll-container.ts
  src/cdk/table/coalesced-style-scheduler.ts
  src/cdk/table/sticky-styler.ts
  src/cdk/table/table.ts
  tools/public_api_guard/cdk/table.md
Labels: action: merge, target: patch

#28463 fix(material-experimental/theming): align form field icons with M3
  src/material-experimental/theming/_custom-tokens.scss
  src/material/core/tokens/m2/mat/_form-field.scss
  src/material/core/tokens/m2/mdc/_filled-text-field.scss
  src/material/core/tokens/m2/mdc/_outlined-text-field.scss
  src/material/form-field/form-field.scss
Labels: action: merge, target: patch

#28471 fix(material/slide-toggle): use css var for disabled label color
  src/material/slide-toggle/_slide-toggle-theme.scss
  src/material/slide-toggle/slide-toggle.scss
Labels: action: merge, target: patch

#28478 docs: release notes for the v17.1.1 release
  CHANGELOG.md
Labels: area: docs

#28430 fix(material/stepper): Update token values for M3 and add color variant support
  src/dev-app/theme-m3.scss
  src/material-experimental/theming/_custom-tokens.scss
  src/material/core/tokens/m2/mat/_stepper.scss
  src/material/stepper/_stepper-theme.scss
  src/material/stepper/step-header.scss
Labels: action: merge, target: minor, area: material/stepper

#28481 [Cherry pick] fix(material/schematics): import async animations and remove deprecated function usages
  src/material/schematics/ng-add/index.spec.ts
  src/material/schematics/ng-add/setup-project.ts
Labels: action: merge, target: patch

#28472 fix(material-experimental/theming): Update color palettes
  src/dev-app/select/select-demo.html
  src/dev-app/select/select-demo.ts
  src/dev-app/theme-m3.scss
  src/material-experimental/_index.scss
  src/material-experimental/theming/_config-validation.scss
  src/material-experimental/theming/_custom-tokens.scss
  src/material-experimental/theming/_definition.scss
  src/material-experimental/theming/_m3-palettes.scss
  src/material-experimental/theming/_m3-tokens.scss
  src/material/core/theming/tests/theming-definition-api.spec.ts
Labels: action: merge, target: minor, dev-app preview

#28482 fix(material-experimental/theming): resolve M3 issues in mat-option
  src/material-experimental/theming/_custom-tokens.scss
  src/material/core/option/option.scss
Labels: action: merge, target: minor

#28484 fix(material-experimental/theming): incorrect track color for alternate progress bar palettes
  src/material-experimental/theming/_custom-tokens.scss
Labels: action: merge, target: minor

#28490 build: update to Angular 17.1 stable
  package.json
  yarn.lock
Labels: action: merge, target: minor, area: build & ci

#28390 fix(material/slide-toggle): Emit slide-toggle tokens under mixin root…
  src/material/slide-toggle/_slide-toggle-theme.scss
Labels: action: merge, target: patch

#28494 fix(material/slider): error if slider is destroyed before first change detection
  src/material/slider/slider-thumb.ts
  src/material/slider/slider.spec.ts
Labels: action: merge, target: patch

#28274 fix(material/form-field): failing color contrast text to bg color ratio
  src/material/core/tokens/m2/mat/_form-field.scss
Labels: a11y, action: merge, target: patch, area: material/form-field, dev-app preview

#28491 docs: update coercion coding standards
  CODING_STANDARDS.md
Labels: action: merge, target: patch, area: docs

#28488 fix(material/chips): Tokenize chip outline and disabled opacity
  src/material-experimental/theming/_custom-tokens.scss
  src/material/chips/_chips-theme.scss
  src/material/chips/chip.scss
  src/material/core/tokens/m2/mat/_chip.scss
  src/material/core/tokens/m2/mdc/_chip.scss
Labels: action: merge, target: minor

#28514 docs: release notes for the v17.1.2 release
  CHANGELOG.md
Labels: area: docs

#28497 fix(material/chips): Tokenize the hover & focus overlays
  src/material-experimental/theming/_custom-tokens.scss
  src/material/chips/chip.scss
  src/material/core/tokens/m2/mdc/_chip.scss
Labels: action: merge, target: minor
